- browser/Makefile.am
- test/integration-http-server.cpp
and gets multiple duplicates of "script src=" lines in it
and on switching branches, etc there can be entries in it that doesn't exist, which then causes unit-integration to fail on the Fileserver not able to provide all files referenced in cool.html
presumably since:
commit e30367d6344a87787b816a9efd92294711e8c5ba
CommitDate: Wed Aug 28 12:44:57 2024 +0200
input file to m4 macro through intermediate file, not parameter
Change-Id: Id48ff3b420649532740958e7fed86daf9fa64e99
* Resolves: # 
> COOL_JS.m4 constantly grows in size

- common/SigUtil.cpp
When a process is already reaped, waitpid(3) will
fail with errno == 0 (success). Instead of blindly
warning, we for success in errno and therefore
have nothing to warn about.
Change-Id: I4d2d35a58eb3cfe6b70b0d2593e62f4ee1015581
> wsd: do not complain if process is reaped already

- browser/src/canvas/sections/ScrollSection.ts
Scroll extents were not being recalculated when attempting to scroll in ScrollSection, causing scrolling initiated with the mouse not to work sometimes. This was especially noticeable with Impress notes view as scroll extents weren't otherwise recalculated elsewhere.
> Fix mousewheel scrolling sometimes not working in one direction

- browser/css/toolbar.css
Change-Id: Ic7857910b9321a087798ebfa83cca81aed622845
* Resolves: #10725 
Vertical alignment of the checkbox label in the user popup, ensuring it is properly centered for better visual consistency and user experience.
> Align checkbox label vertically and centered in user popup

- net/HttpRequest.hpp
- net/NetUtil.cpp
- net/NetUtil.hpp
- test/HttpRequestTests.cpp
- test/UnitProxy.cpp
- test/WhiteBoxTests.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
- wsd/ClientSession.cpp
- wsd/HostUtil.cpp
- wsd/HostUtil.hpp
- wsd/ProxyRequestHandler.cpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/WopiStorage.cpp
The endpoint is accessible at /hosting/wopiAccessCheck
You send it a POST with input json:
{
"callbackUrl: "<url-to-my-wopi-host>"
}
For instance:
curl -ki https://localhost:9980/hosting/wopiAccessCheck --header "Content-Type: application/json" -d '{"callbackUrl":"https://cool.local"}'
Returns json such as:
{
"status": 0,
"details": "OK"
}
With status and details giving hints to what went wrong if it did.
The callbackUrl needs just to be an HTTPS endpoint, it does not need to be the wopi service but can be only a healthcheck url for instance.
Change-Id: Ibdef0bbf0d2fd98e3d293a06dfcfc79478d618e5
cc @juliushaertl 
Superseeds https://github.com/CollaboraOnline/online/pull/4353
> Add an endpoint to check connectivity to WOPI server

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
This is a follow up since previous patch has a problem when presenter console is
started in Firefox when Impress is in notes view mode.
Oddly, it seems that presentation information are requested but the reply with
the info never reaches CanvasTileLayer._onMessage.
Anyway I can see that the reply is sent by the core.
Since I'm not able to understand the root cause, I implemented a simple
workaround by delay the presenter console start by 500ms.
In order to be safer I decided to apply the same delay also when we present
without the console.
Change-Id: I941419b3d33095608973af18aab9df2b767a02f4
> slideshow: followup: exit  from notes view before starting

- common/StateEnum.hpp
wsd/ClientRequestDispatcher.cpp:1106:1: error: unused function 'toStringShort' [-Werror,-Wunused-function] STATE_ENUM(CheckStatus,
^
./common/StateEnum.hpp:63:31: note: expanded from macro 'STATE_ENUM'
static inline std::string toStringShort(NAME e)                                                \
^
wsd/ClientRequestDispatcher.cpp:1106:1: error: unused function 'toString' [-Werror,-Wunused-function]
./common/StateEnum.hpp:76:31: note: expanded from macro 'STATE_ENUM'
static inline std::string toString(NAME e)                                                     \
^
wsd/ClientRequestDispatcher.cpp:1106:1: error: unused variable 'CheckStatusMax' [-Werror,-Wunused-const-variable]
./common/StateEnum.hpp:80:25: note: expanded from macro 'STATE_ENUM'
static const size_t NAME##Max = …
> Fix clang warning about unused functions

- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
commit:
- slideshow: exit notes view before starting the slideshow
> slideshow: backport to 24.04 branch

- browser/src/control/Control.ContextMenu.js
Change-Id: I15f62cbdfc69d9ba4c1c7e53f2238d13b65285e5
* Resolves: # 
If the postmessage command Hide_Command was sent, also hide the command from the context menu.
See #10351 for a related change.
> context menu: Don't show items for hidden commands

- browser/src/control/Control.JSDialogBuilder.js
- Ensured img elements within buttons receive an empty alt attribute when the button has a programmatic label (e.g., aria-label).
- Added descriptive alt attributes to img elements if the button lacks a programmatic label.
- This change improves screen reader support by avoiding redundant announcements and providing meaningful descriptions where needed.
Change-Id: I3317e5c0d192db493cd2928b2c63396d9df64e49
* Resolves: # 
> Add appropriate alt attributes to images within buttons for better accessibility

- wsd/ClientRequestDispatcher.cpp
So in json response we have `Ok` instead of `CheckStatus::Ok`.
Amends #9202
Change-Id: I0d26ac1e098e8a6889248102d3baad5cd9a38bc1
* Resolves: # 
> wsd: wopiAccessCheck, use nameShort for Status

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.Combobox.js
- added aria-label for pushbutton control
- generic method to add aria label based on `aria` or `text` property
Change-Id: I80e1aaa132ed944d24223519e640fc56d01b9dcb
* Resolves: # 
> Add aria label for pushbutton control

- browser/src/control/Control.JSDialog.js
Change-Id: I5a29ddf7b4562221fc8a6c574a775d2a2e9180a8
* Resolves: # 
> Focus inside input field on show show input modal

- browser/css/btns.css
SVG images may not have an intrinsic width and height defined. This can cause max-content to behave unexpectedly since it relies on the size of the content, and an SVG without dimensions may not contribute to the content's width.
We set width explicitely in this case.
Change-Id: I5ebed738bd4f3a12a96596ddac07341097e43bc3
Before:
After:
> Fix width of Thesaurus left arrow button

- browser/css/jsdialogs.css
Change-Id: I4edf2311bf225483bfad59676d0e764385fde4b9
* Resolves: #10813 
Fixes the misalignment of text labels relative to checkboxes in the "Show Sheets" dialog for improved visual consistency.
> Correct text vertical alignment of checkboxes in show sheets dialog

- browser/src/canvas/sections/CommentSection.ts
Change-Id: Ia3b6ac17ad1f4677e61d9128806bac90a819bfb3
* Resolves: #10762 
This fix addresses an issue where comments in cells appeared misaligned or visually inconsistent when the cell was extended
> Adjust comment styling for extended cells to ensure consistent appearance

- browser/css/toolbar.css
Change-Id: I5c801bbddfba1166030c8b0ca0cebabc576867f1
Introduced a background color to the following chip to remove odd border over the user avatar
> Add background color on following chip of user avatar

- browser/src/control/Control.JSDialog.js
Missing alt Attribute for Icons
The Icons do not have alt attributes.
Solution : In this case, it is advisable to use an empty alt tag for the icons, as the information of the funktion is available in text form
Change-Id: Ibdb1c7833477b9a020c1e77e5da6fe08a0f90336
* Resolves: # 
> Accessibility: Navigator use an empty alt tag for the icons

- browser/src/control/Control.JSDialog.js
- browser/src/control/jsdialog/Widget.TreeView.ts
- Navigator: Missing alt Attribute for Icons
- The Icons do not have alt attributes.
- Solution : In this case, it is advisable to use an empty alt tag for the icons, as the information of the function is available in text form
Change-Id: Iac161fd9e096e6765ef5ee66aa55839dfa057b5b
* Resolves: # 
> Accessibility navigator: use an empty alt tag for the icons

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
do not add additional margin or padding to context menu also don't round the borders in it's entries
example menu to test can be found in style sidebar Writer -> Format -> Style sidebar (experimental for now)
result:
> jsdialog: no padding in treeview context menu

- browser/src/control/Control.JSDialog.js
- Enhance dialog accessibility: Add aria-labelledby, set role="dialog", and ensure meaningful titles.
- Improve dialog accessibility: Add aria-labelledby and set role="dialog" for semantic clarity.
Change-Id: I815db1a23b9331e4de4e34ba57851364c081f320
* Resolves: # 
> Add  aria-labelledby with appropriate description and set role="dialog" for all form modal

- wsd/FileServer.cpp
The intent was to avoid VLA, but later in the code the sizeof operator returned 16 and the length of token[4] was 256. This mismatch caused a regression, admin console's secure password was not accepted.
I decided to use std::vector instead of alloca. It's more readable and C++-like to me.
Change-Id: I3cbbce5c4ac568735b2b44dad2fb20e143bf4c75
> Fix regression from c0e53f04741987b70

- browser/src/control/Control.JSDialog.js
- cypress_test/integration_tests/desktop/calc/focus_spec.js
- in current case we did not have any fallback for cases like undefined init focus
- it is simple that if no focus-able id defined then we will add focus on first focus-able element
Change-Id: Ib46a1c7a3366933e8b01ca831798d92bf96797e0
* Resolves: # 
> For undefined init focus id we should focus on first focus able element in container

- browser/css/toolbar.css
Change-Id: I4ad71e2935a17275b6fa1f2ef1568cf6d68adcc0
Fixes regression from https://github.com/CollaboraOnline/online/pull/10686
Since user avatar icons are now using --btn-img-size, the following chip dimensions have to be adjusted from --btn-size to --btn-img-size and use "box-sizing: border-box" to ensure avatar icons align properly within the chip without overlap or layout issues
> Change following chip dimensions on user avatars

- wsd/ClientRequestDispatcher.cpp
Change-Id: Ic022614625bfa3aa0a5b819fda1adcf50c7465d1
* Resolves: # 
Amends #9202
> wsd: wopiAccessCheck, remove unused CheckStatus, hook NotHttpSuccess

- browser/css/color-palette.css
- browser/src/canvas/sections/CommentSection.ts
Change-Id: Ib1db1e122c91e74a7477b18cd920e7e01424dceb
* Resolves: #10762 
Replaced the hardcoded color `#BF819E` in the canvas context with the CSS variable `--color-calc-comment`, defined in `color-palette.css` for consistent theming.
This is a regression that resolves  "The color should come from the palette or dark palette css instead (css var)"  from #10762
> Replace hardcoded canvas comment color with CSS variable

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
do not add additional margin or padding to context menu also don't round the borders in it's entries
example menu to test can be found in style sidebar Writer -> Format -> Style sidebar (experimental for now)
Change-Id: I2b70ad0742bbb6a815768894f148de1d9cd3c21e
--------------- we did duplicate with the same changeId so adding manual port here -------------------
see:
https://github.com/CollaboraOnline/online/pull/10823/commits/c81e4d558f142ead7049619d9e6c5d5039254ae1
and
https://github.com/CollaboraOnline/online/commit/bbe11a084df36da9beb28cf378571d6cdc1869ba
> jsdialog: no padding in treeview context menu (mobile)

- wsd/ClientRequestDispatcher.cpp
Change-Id: I3f04b7877c5ac87f00c75f8326767a4aadd228eb
* Resolves: # 
> wsd: wopiAccessCheck, fix consistency in CheckStatus SslHandshake

- net/HttpRequest.hpp
`result` is allocated on the stack, don't capture its address in a
lambda.
Change-Id: I2d6dad1f76002559e400c57cd5b4ffa0b6e0f0d6
> Fix memory handling in Session::asyncConnect()

- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
Fixes regression from commit 03b42ad45d4ce1774530be55d47e2f092da7ab1a following: reset on user interaction by uno command
BEFORE REGRESSION:
1735648839262 OUTGOING: uno .uno:ControlCodes
global.js:566 1735648839296 INCOMING: canonicalidchange: viewid=4 canonicalid=1001 viewrenderedstate=PS;Light global.js:566 1735648839297 OUTGOING: tilecombine ...
AFTER REGRESSION:
1735648643409 OUTGOING: uno .uno:ControlCodes
global.js:566 1735648643409 OUTGOING: clientvisiblearea x=-4995 y=0 width=22455 height=9765 splitx=0 splity=0 global.js:566 1735648643410 OUTGOING: clientzoom tilepixelwidth=256 tilepixelheight=256 tiletwipwidth=3840 tiletwipheight=3840 dpiscale=1 zoom=10 global.js:566 1735648643473 INCOMING: invalidatetiles: EMPTY, 0, 0 wid=344 global.js:566 1735648643473 INCOMING: …
> Do not jump on uno command to cursor

- browser/src/control/jsdialog/Widget.TreeView.ts
This is used in Audit dialog to open SDK help
> jsdialog: allow to open links inside treeview

- browser/src/canvas/sections/ScrollSection.ts
Change-Id: Ied41faf1bd078a72b23e6f1bc6ae26a2268b1b98
* Resolves: #10701 
Fix scrollbar color in darkmode for writer and draw
Writer|Draw -> View -> change between light and dark mode and move the scrollbars
[Screencast from 02-01-25 22:58:08.webm](https://github.com/user-attachments/assets/8dc01630-4cdb-4273-85a3-443d8cf5b8c5)
[Screencast from 02-01-25 22:54:33.webm](https://github.com/user-attachments/assets/671e3d21-61ab-4c5f-8b9c-ca9b48aec1a2)
> Fix scrollbar color in darkmode for writer and draw

- browser/src/layer/tile/CalcTileLayer.js
Prevent premature setting of layoutIsRtl, which can cause some sections to remain in incorrect positions if they are not defined before calling _adjustCanvasSectionsForLayoutChange. Fix this by ensuring all sections are adjusted before setting layoutIsRtl.
Change-Id: I13f9e18c185e61265503d413a77a2a8151bb6857
* Resolves: #10814 
Right now, an early call to _adjustCanvasSectionsForLayoutChange will set the sheet's layoutIsRTL to true before adjusting the anchor position of all of the sections. 
I'm not sure if this is the correct fix.  What I can think of is if "status" messages and w/e calls into _adjustCanvasSectionsForLayoutChange should be delayed further (set is_ready after we render). Any comments on this would be appreciated.
> Delay setting layoutIsRtl to ensure correct section positioning

- browser/src/control/Control.CornerHeader.ts
Change-Id: I2f855273bc8824ac9d4b999ca8ecef4974c5d570
Updates the style of the corner entry when switching between dark/light mode.
> Reinit CornerHeader on modechange.

- browser/src/control/Control.JSDialogBuilder.js
Missing Alt Attribute for push button like Input Range Buttons
The controls do not have alt attributes, which results in screen readers and
other assistive technologies being unable to adequately describe the icons.
The problem has been solved by checking for available labelledBy attribute
beyond aria.label.
The alt attribute is set empty for button image.
Change-Id: I6187cb03fffed960c098e51448b705dd1c787e4b
> accessibility: missing labelledBy attribute for pushbutton

- common/JailUtil.cpp
- common/SpookyV2.cpp
- common/Util.cpp
- common/Util.hpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- net/Socket.cpp
- net/Socket.hpp
- net/Ssl.cpp
- net/SslSocket.hpp
- tools/WebSocketDump.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/Storage.hpp
- wsd/wopi/StorageConnectionManager.hpp
- **wsd: cosmetics**
- **wsd: use non-deprecated SSL_get1_peer_certificate**
- **wsd: string -> string_view**
- **wsd: include cleanup**
- **wsd: log the OpenSSL version**
- **wsd: as of C++17 [[fallthrough]] is standard**
- **wsd: constexpr string_view**
> Misc Improvements (2)

- net/SslSocket.hpp
Non-functional SSL error handling and logging improvements.
Functional changes will follow separately.
- **wsd: net: breakout handleSslError() from handleSslState()**
- **wsd: net: handle SSL_ERROR_NONE**
- **wsd: net: hoist getBioError() and call it once**
- **wsd: net: assert and error on unsupported async encryption**
- **wsd: net: document the error conditions**
- **wsd: net: unify SSL error logging**
- **wsd: net: remove duplicate logging of rc**
> SSL Improvements (1)

- common/ConfigUtil.hpp
- net/SslSocket.hpp
More non-functional error-handling improvements.
This greatly simplifies error handling, _without_ introducing any functional changes.
Functional changes will follow.
- **wsd: net: simplify ssl error handling**
- **wsd: net: unify SSL error logging**
- **wsd: net: remove single-use macro**
- **wsd: net: conditional use of SSL_ERROR_WANT_RETRY_VERIFY**
- **wsd: include missing atomic header**
- **wsd: net: assert catch-all SSL errors**
- **wsd: net: peek the error only once**
- **wsd: net: assert on unexpected SSL errors**
- **wsd: net: hoist restoring errno**
> SSL Improvements (2)

- wsd/ClientSession.cpp
The Ctrl+q shortcut exits Core when
forwarded. There is no use to having
this shortcut processed in Core, so
we suppress it.
If we should process it by saving and
closing the document, it needs to be
handled in a special way (ideally by
sending 'closedocument' from the
client instead).
Change-Id: I6b3280342490a013645ae73888188f20cd25168d
> wsd: suppress Ctrl+q

- browser/src/control/Control.StatusBar.js
- cypress_test/integration_tests/desktop/calc/statusbar_spec.js
not possible to mark multiple entries yet, but it is visible if core has it activated
AFTER FIX:
multiple entries are selected
> calc: allow multi-selection of functions in statusbar

- browser/css/btns.css
- browser/css/device-desktop.css
Change-Id: I2b03d7e241618a75b97e8712c01c94e5c264b2ba
* Resolves: #10859 
Fixes the font size of the "Push" button to ensure it is consistent with other buttons in the dialog
> Add font size to the jsdialog Push button to ensure it is consistent with other buttons 

- browser/css/jsdialogs.css
Change-Id: Ia5993bfbad217bc51780b155b80feab4bcaf4684
* Resolves: #10860 
The radio button labels were wrapping to the next line in cases of limited space, causing misalignment and poor readability. Adding white-space: nowrap ensures the labels remain on a single line, maintaining a consistent and professional appearance across all layouts.
> Add white space nowrap to radio button label

- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.Mention.ts
- browser/src/control/Control.ServerAuditDialog.ts
- browser/src/control/Control.Sidebar.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.TreeView.ts
- move sorting and cell creation to separate function
- enable/disable sorting functionality depending on "sortable" property from JSON
- requires: https://gerrit.libreoffice.org/c/core/+/179949 to be merged first
> jsdialog: treeview improvements

- wsd/DocumentBroker.cpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
If UserCanWrite and UserCanOnlyComment are set to true the document is
opened in comment only mode. If UserCanWrite is false,
UserCanOnlyComment is ingnored.
Change-Id: I3417aadc428e079bb1533e2432ea60a1e62d03fb
> wopi: add UserCanOnlyComment option

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/calc/searchbar_spec.js
- cypress_test/integration_tests/desktop/calc/sheet_switch_spec.js
- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- cypress_test/integration_tests/multiuser/calc/cell_cursor_spec.js
Followup for https://github.com/CollaboraOnline/online/pull/10876:
- cell not fully visible if we scroll to it after search (thanks to [@jaumep](https://phabricator.collabora.com/p/jaumep/) )
- fix for turning off following ( regression )
- jump to found result always ( if have text cursor or cell cursor visible)
- added cypress tests
> cypress: check search with following off

- browser/src/canvas/sections/ScrollSection.ts
- browser/src/control/Control.ContextMenu.js
- browser/src/control/Control.Header.ts
- browser/src/control/jsdialog/Util.Dropdown.js
- disable mouse clicks for context-menu-layer
- close popups if a dropdown menu is opened -> this only applies to the autofill context-menu. other context menus should not be affected.
- close all popups when scrolling and reset selection with _resetReferencesMarks() if autofill context menu is open
- close all popups if a row/column header is selected
Change-Id: Iaf7b5c09003291f27155ae9ab6787f2f871ac466
* Resolves: # 
> sc autofill: make cells selectable after first click - if autofill context menu is open

- browser/src/control/jsdialog/Widget.TreeView.ts
This hack removes the need to press the `tab` key in order to get a tree entry
focused after clicking on it.
That improves usability for the Navigation pane and also for gridview such as
the one for the 'font' tab in the Format cell dialog.
Change-Id: I1be820367f935c8460ab5a60ef74cc648230ac64
> a11y: treeview get current entry focused

- browser/src/canvas/CanvasSectionProps.js
Because other sections need to read the up-to-date data that is updated by scroll section, we need to set its z-index to a higher value.
Issue: AutoFill marker section drawing lags behind while scrolling.
Also refactored some of the things in the file, without changing the logic.
Change-Id: Ia2305efaaa0bbca5bd59881c5e246e7894bc5043
* Resolves: # 
> Re-adjust z-index of Scroll section.

- browser/src/canvas/sections/URLPopUpSection.ts
In Writer, it was not performing well. Document position is also taken into account.
Issue:
* Open a Writer file.
* Add some text and a hyperlink.
* Scroll down the document and let the hyperlink be the first visible row.
* If you click on the text part with the link, hyperlink popup will be shown in the invisible area.
Change-Id: Idfd01a0486bf0ce0f072472c3ca6dfe26d1f6014
* Resolves: # 
> Improve URL popup positioning.

- common/Seccomp.cpp
Change-Id: Ia17360035035418ada519cf758e38be35c01a177
* Resolves: # 
> Seccomp: filter more syscalls

- browser/src/core/Socket.js
Possibly regression from commit 4512fc8f4064c1472c3c134e7e76cb1377fe6064 Move graphic selection related logic to its own file.
Socket.js:1680 Uncaught TypeError: this._map._docLayer._onUpdateGraphicSelection is not a function
at NewClass._onSocketClose (Socket.js:1680:25)
_onSocketClose	@	Socket.js:1680
we don't have that function anymore
> Fix for #10885 : uncaught typeerror when leaving

- net/Socket.cpp
- net/Socket.hpp
This combines the _closed member of Socket
with the _fd, such that we invalidate the
_fd and don't need a separate flag. This
is safer and reduces duplication.
This fixes a possible bug where we
inadvertently close _another_ socket
when we call shutdown(2) on the already
closed FD after the FD gets recycled.
For example, StreamSocket::checkRemoval()
has a case where we unconditionally call
Socket::shutdown(), via closeConnection(),
which calls shutdown(2). There could
easily be other cases where we close a
socket that can later be reused by
accept(2) before we call shutdown(2) on
this recylced FD again, closing the
recently accepted connection.
If this has been happening in the wild,
it probably is rather rare, otherwise
we should have seen more issues related
to closed sockets. Still, …
> Safer Socket Closed State

- wsd/FileServer.cpp
wsd: Simplify HTTP request to use direct octet-stream content type for files
Change-Id: I7a4f902582195b1cf0e0e4d1107254b42c5a0987
* Resolves: # 
> wsd: Simplify HTTP request to use direct octet-stream content type

- net/Socket.cpp
- net/Ssl.cpp
- net/SslSocket.hpp
These are functional SSL improvements and change of behavior.
Commit logs explain rationale and the changes.
The first 3 commits are non-functional, while the last 3 are functional changes.
- **wsd: simplify Socket::streamImpl()**
- **wsd: net: always process application-data if available**
- **wsd: net: log SSL errors at debug level**
- **wsd: net: handle unexpected closed-socket gracefully**
- **wsd: net: always clear SSL errors after failed IO**
- **wsd: net: check for unexpected errors in SSL**
> Functional SSL Improvements

- browser/src/control/Ruler.js
- browser/src/control/VRuler.ts
Change-Id: Id232cee5fe59c198dec8f0b5223ce84ede915216
* Resolves: # 
> Use app variables instead of latlng conversion.

- scripts/undoStatistics.py
fixed kit id parse, as it is a hexadecimal number not a decimal. fixed also undo command recheck part, as these lines start with "kit=" now, not with "time=".
Change-Id: I1e649efda96b2a728b1efd2d5bcfa84f1e1c5af2
* Resolves: # 
> fixes for log UI Commands (kit-id)

- kit/Kit.cpp
so the the correct/main thread gets the signal so we can get a backtrace generated.
Change-Id: I64f8f374bad92964f42ba34e23011bf827d87bf9
* Resolves: # 
> kill saving thread with SIGABRT

- net/Socket.cpp
- net/Socket.hpp
- net/Ssl.cpp
- net/SslSocket.hpp
- tools/Stress.cpp
- **wsd: cosmetics**
- **wsd: replace _closed member with invalidating the FD**
- **wsd: invalidate socket FD by negating**
- **wsd: simplify shutting down in checkRemoval**
- **wsd: simplify Socket::streamImpl()**
- **wsd: net: always process application-data if available**
- **wsd: net: log SSL errors at debug level**
- **wsd: net: handle unexpected closed-socket gracefully**
- **wsd: net: always clear SSL errors after failed IO**
- **wsd: net: check for unexpected errors in SSL**
> Backport SSL Improvements

- net/HttpHelper.cpp
- net/HttpHelper.hpp
- test/UnitCopyPaste.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- **wsd: string -> string_view in HttpHelper**
- **wsd: reuse HttpHelper::sendErrorAndShutdown**
- **wsd: test: simplify UnitCopyPaste**
- **wsd: send clipboard response with no-cache header**
> Clipboard Response Is Not Cacheable

- browser/src/app/SearchService.ts
Change-Id: Icd084deedda131624bc123da24817ba23b7b0db2
* Resolves: # 
> Use app.file.viewedRectangle instead of latlng.

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- browser/src/dom/PosAnimation.js
* Resolves: #10748
It is desirable for comments to scroll in sync with the document instead of lagging behind the scroll position. The first commit in this branch anchors comments directly to the scroll position and the second commit fixes various performance issues doing this exposes.
> Anchor comments directly to the scroll position and optimise comment layout

- config.h.in
- configure.ac
- ios/config.h.in
- tools/Config.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
This bumps the minimum OpenSSL version requirements to 3.x.
I believe gitpod uses 1.1.1 and will need to be updated before we merge this, lest we break it.
CC: @Darshan-upadhyay1110
- **configure: require OpenSSL 3.0.11 or newer**
- **wsd: logging**
> Require OpenSSL 3.x

- browser/css/jssidebar.css
Otherwise the text gets cropped and impossible to read.
This commit also fixes or decreases the image diff in cypress test fail on "writer/navigator_spec.js" due to Visual Regression Plugin detecting a image mismatch.
- make -C cypress_test run-desktop spec=writer/navigator_spec.js
Change-Id: I4c90b6296b9d4b47490e7a46d8578c5485909b61
* Resolves: # 
> Navigator: Allow text list items to wrap

- browser/src/geo/crs/CRS.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
Previously, in order to change the scale of a coordinate we roundtripped through lat/lng. The conversion here, unproject with the old zoom and then re-project with the new zoom, is valid with all point types (core pixels, css pixels and twips) but the intermediate step (a lat/lng from the unproject) isn't valid for anything except CSS pixels. The new rescale function is a simplification of the project(unproject(x)), as a single step and with duplicate terms cancelled.
Change-Id: I65fec84d2160299d5edb2d5264bc3b8ce0c1d29f
* Resolves: # 
> refactor: allow rescaling without projecting

- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
e.g. pressing F1 will dispatch help twice, so tag that the event dispatched a shortcut in _handleKeyEvent to not handle it again in _globalKeyEvent
1st
_handleKeyEvent
_onKeyDown
handler
2nd
_globalKeyEvent
handler
the ev.preventDefault to make the browser ignore the event is used in multiple places where we don't immediately dispatch the event in _handleKeyEvent but explicitly leave it to be handled later by _globalKeyEvent, e.g. Ctrl+S, so doesn't work as a proxy that a shortcut was already handled
Change-Id: I7c025ba4a8a883982ddf5ea0bf741e7b66d3cae5
* Resolves: # 
> only call short cuts once for a shortcut combination

- scripts/chartUndoStatistics.py
- scripts/undoStatistics.py
- test/.gitignore
- test/data/empty-chart.fods
Added more statistics recorded inside undoStatistics.py. These statistics are now written into separate sheets in a .fods file located in test/data. To add the data it uses a template .fods (empty-chart.fods) file which contains a sheet with some chart configurations and table data (to be overridden)
Created a script that reads in the .fods file and updates the chart configurations for each sheet, meaning that each data set will be auto charted.  It's still quite restricted but as of right now it can successfully chart the required data.
Change-Id: Idc00802960b045fa8a43df4e8239ad381a986fff
* Resolves: #10761 
> Generating nicer output from UI log commands

- browser/src/slideshow/SlideShowPresenter.ts
- Added a `_startingPresentation` flag to track the state of the presentation startup.
- Modified the `onUpdateParts` method to prevent redundant `getpresentationinfo` calls during initialization.
- Updated the presentation start logic to set the flag when the presentation begins, ensuring the request is sent only once.
* Resolves: #10198 
Change-Id: Ib1edc8b57a3ec879db93cffbd649b5b96d0004f4
* Resolves: # 
> Avoid redundant `getpresentationinfo` call when `startPresentation` parameter is used

- browser/Makefile.am
- browser/css/leaflet.css
- browser/src/control/Control.UIManager.js
- browser/src/control/HRuler.ts
- browser/src/control/Ruler.ts
- browser/src/control/VRuler.ts
Converted ruler file into typescript
created base class and subclass for Horizontal and vertical ruler
Moved the _updatePaintTimer method to the base Ruler class to avoid duplication across HRuler and VRuler.
Added _updateBreakPoints as an abstract-like method in the base class, throwing an error to enforce implementation in subclasses.
Streamlined the initialization logic in Ruler.initializeRuler for better readability and modularity.
* Resolves: # 
> Convert ruler file into typescript

- browser/src/control/Control.Menubar.js
- Current case only writer had the print option available in menubar
- added print option for all apps by adding this to `AllowedView Mode action` list
Change-Id: I0884fe0809bb1de5eb12c141a9ee9ce499096212
* Resolves: # 
> Add "Print" option in menubar for readonly mode in all app

- browser/src/control/Control.UIManager.js
- showFormulaTooltip() and hideFormulaTooltip() are no longer in use -> removed.
Change-Id: I621e462f32470077215004b41aa82cb4fd16b829
> Calc: remove unused FormulaTooltip functions

- clang/Makefile
- clang/README.md
- clang/plugin.cpp
- clang/test/capture.cpp
- configure.ac
As suggested at
<https://github.com/CollaboraOnline/online/pull/10838#pullrequestreview-2527339319>,
detect some cases where capturing variables by reference in a lambda is
not safe, assuming that most lambdas are long-lived in coolwsd.
It would fail without commit
19861a2d0bdc2db9825f9d4b953ce3e0a7a3539b (kit, BackgroundSaveWatchdog:
fix memory management in the ctor, 2024-11-20) with the following
output:
kit/Kit.cpp:183:67: error: function parameter captured by reference, capture by value instead
Util::setThreadName("kitbgsv_" + Util::encodeId(mobileAppDocId, 3) + "_wdg");
^~~~~~~~~~~~~~
1 error generated.
And it would fail without commit
92efdebaeb3dae25eedb02801ac395ad6abf95dd (Fix memory handling in
Session::asyncConnect(), 2025-01-03) with the folliwng output: …
> Add an initial COOL-specific clang plugin

- browser/css/cool.css
- browser/src/canvas/sections/CommentListSection.ts
Change-Id: I4746de9d38ce016e0fdef2d0ef15d810474276b6
* Resolves: #10887 
Fixes the alignment, size, and interactivity issues with the number of replies indicator in the comments section, resized to fit seamlessly within the circle, and includes a hover state
[Screencast from 10-01-25 15:38:57.webm](https://github.com/user-attachments/assets/bed079eb-32fe-44e8-8846-5308a80c413a)
> Align comments indicator and add hover state to comments avatar

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- browser/src/map/Map.js
problem:
if user was editing comment and switched tab/window, on returning to tab document will gain focus instead of comment and user accidentally type in doc instead of comment
Change-Id: I356f311461010fc191620ac489f6b3bc65434e2b
> annotation: refocus comments on tab getting focus

- browser/src/canvas/sections/CommentListSection.ts
> annotation: avoid comment conflict warning when irrelevan

- net/Socket.hpp
We now close socket FDs when we shutdown
the underlying connection, rather than
waiting until the Socket object is destroyed.
This fixes a recent regression where we leaked
FDs because we invalidated before closing.
This was introduced in af747c1.
In addition, we unify the logic to shutdown
and close and localize all in setClosed().
Change-Id: Ib3cb84394fca53f41a64aba9201c5779ee536dcf
(cherry picked from commit 39d7eafebebcf11b6f5e3773c9274900edc83984)
> wsd: shutdown and close sockets early

- net/Socket.cpp
- net/Socket.hpp
- **Revert "wsd: shutdown and close sockets early"**
- **Revert "wsd: invalidate socket FD by negating"**
- **Revert "wsd: replace _closed member with invalidating the FD"**
> fd leak: just revert instead of an invasive fix for now

- .gitpod.dockerfile
- Using latest ensures you’re working with the most up-to-date version of Gitpod’s VNC-enabled workspace image.
Change-Id: Id03996b2acd5a011dec2c188722c79a5e61ca359
* Resolves: # 
> Update gitpod workspace vnc to latest version

- scripts/undoStatistics.py
Changed the reorder, so after a "log-end-time:"
new lines with same kit-ID will be handled as different kit-id.
Change-Id: Ib36aec7f7add53b75e377c0c40bfd0cfdd946d3d
* Resolves: # 
> Fixed same kid-id reorder problem in UI-log-script

- browser/src/control/Control.JSDialog.js
- for undefined element we should add safe check here for controlPosition
- we are already showing error about absece of contolId element in `executeAction`` method (browser/src/control/Control.JSDialogBuilder.js#L2778)
- so no need to show JsError here.
Change-Id: I557e2c386408f0b9fe197fcf7a931152b31f9286
* Resolves: # 
> Add null safety check for controlPosition initialization

- browser/src/canvas/sections/ScrollSection.ts
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
In calc, when handling auto-scroll outside the map, the selected range
was updated using the mouse down position. This causes the selection to
shrink and expand when the mouse leaves and enters the map area.
Change-Id: I307b9e30f8a06333a034f18914b1322146358512
> calc: drag select outside the map

- wsd/wopi/WopiStorage.cpp
Change-Id: Icea911ea3a136602bf05f4051a0e3222e83de048
* Resolves: # 
> fix: unnecessary UserSettingsUri set from wopi response

- browser/css/jsdialogs.css
Change-Id: Id4b45e9097b8ba77df5280bedf1635693fce72fc
* Resolves: #10841 
Improvements in alignment of icons and text in the server audit dialog
> Correct text and icon alignments in server audit dialog

- kit/ChildSession.cpp
- scripts/undoStatistics.py
- test/data/empty-chart.fods
delete ?params from the end of uno commands, before logging The script delete them too... to be sure... (if we have old log)
Added char/sec type speed to statistics.
Fixed a bug with uno command connection... (a list was not deleted) found a problem: some cases undo-count-change not happens therefore some undo may not connectable to an undo-count-change made a new "unknown" command .. and count these wrong cases.
Made other statistics a bit better:
-added 45 degree rotattion
-added logarithmical scaling to uno commands
(maybe soem other charts will need it too)
-wrote text to A1 ..and fixed the code to not use that for charts -added new groups: "Single viewer", "Single Editor"
Change-Id: I6bfa40e3505971bd6fb7f77da618f76410ebf87a
* Resolves: # 
> UI log: small fixes, and extra addons

- kit/Kit.cpp
- wsd/CacheUtil.hpp
- **wsd: fix clang-15 build**
- **cool#11002 kit: fix memory corruption in Document::handleSaveMessage()**
> cool#11002 kit: fix memory corruption in Document::handleSaveMessage()

- browser/src/slideshow/PresenterConsole.js
> Presenter console: fix disable button for single slide & some improvements on PC close 

- dev-notes/locale.md
Change-Id: I69bdb5de8a51ef04e15dcb3696a48855472b19b8
> dev_notes: added notes for locale decimal separators

- browser/css/notebookbar.css
- browser/src/control/Control.NotebookbarWriter.js
Before this commit, few users reported some level of friction when
attempting to find buttons.
- Group visually groups of buttons by means of separators. Thus,
making it easier to identify the "undo, redo group", "Clipboard
group", "font group", etc.
Change-Id: I48136194d03c109a27fb7faafbe0cd9a54fca1a1
> Writer: Notebookbar: Home tab: Add ui separators in between groups

- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- this is done to make the json format consistent
- json format after this change
```json
{
"autotext": [
{
"stamp": "\"780e98110c\"",
"uri": "https://localhost:9980/wopi/settings/home/rashesh/work/collabora/online/master//test/data/presets/user/autotextuser.bau"
}
],
"browsersetting": [
{
"stamp": "\"780e98110c\"",
"uri": "https://localhost:9980/wopi/settings/home/rashesh/work/collabora/online/master/test/data/presets/user/browsersetting.json"
}
],
"kind": "user",
"wordbook": [
{
"stamp": "\"780e98110c\"",
"uri": "https://localhost:9980/wopi/settings/home/rashesh/work/collabora/online/master//test/data/presets/user/dictionaryuser.dic"
}
],
"xcu": [
{
"stamp": "\"780e98110c\"",
"uri": "https://localhost:9980/wopi/settings/home/rashesh/work/collabora/online/master//test/data/presets/user/co …
```
> wsd: presets: pass xcu as json array instead of json object

- browser/admin/src/Util.js
- wsd/AdminModel.cpp
Change-Id: I562a7eacdb04bae7745c5f92502c21ef88bf9627
* Resolves: #10984
> doc_memory_used_bytes should be in bytes not in kilobytes (fixes #10984)

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
"Find and replace" button in the notebookbar can be:
- Too long: Requiring additional scrolling in narrower windows can
become particularly frustrating when dealing with certain long-form
languages."
- Too hard for first eye scanning: Since the button is placed within
the Search group ("Search" btn at the top and "Find and replace" btn
at the bottom) it can be difficult to spot "replace" when user tries
to find it but at the first sight sees only "Search" and then "Find".
- A bit unexpected, specially when the user is used to see "Replace"
in other workflows and Office suites.
Change-Id: I3e875191490610df5fbf717e259cf7c7bb85d61a
> Notebookbar: Shorten "Find and replace" Translatable string

- browser/src/app/GraphicSelectionMiddleware.ts
- browser/src/canvas/sections/ShapeHandlesSection.ts
- browser/src/control/Control.Menubar.js
- browser/src/layer/tile/CanvasTileLayer.js
- **cool#10630 doc electronic sign: fix no SVG in graphic selection on 2nd page**
- **cool#10630 doc electronic sign: fix outgoing mouse messages on 2nd page**
- **cool#10630 doc electronic sign: fix outgoing transform pos on 2nd page**
- **cool#10630 doc electronic sign: fix outdated tile for shape move on 2nd page**
> cool#10630 doc electronic sign: 4 fixes for the non-first-page case

- browser/src/slideshow/PresenterConsole.js
- handled the case where we do enable the repeat slide show & PC should not get closed
- isEndless will make sure we do not terminate the window
Change-Id: I6e7f5bb11e784195acc2e8dbb4918875c829e7f3
* Resolves: # 
> Fix Presenter Console gets close in case of repeat slideshow after x sec

- browser/src/canvas/sections/CommentSection.ts
avoid triggering autosave when textbox loses focus so user can navigate buttons using tab
Change-Id: Ibe0348ab7160c383f40e97328c5d844921a461c3
> comment: autosave only when entire comment container loses focus

- browser/css/color-palette.css
Set style preview border color to match the toolbar border and
notebookbar's separators, reducing contrast while enhancing the
visibility of the selected/active child's border.
Change-Id: I786d32fa1b97ddbeb18c2205805a5666d9ca1765
> Notebookbar: style previews: Reduce parent's border color contrast

- browser/.gitignore
- browser/Makefile.am
- browser/package.json
Store the compiled mocha js files in a separate folder away from the source typescript files.
Change-Id: Ibc1ecd263f53b2e6db736d9c6f1330998d4e2bf8
Store the compiled mocha js files in a separate folder away from the source typescript files.
> mocha: store the compiled js files in a separate folder away from the typescript files

- wsd/COOLWSD.cpp
- wsd/CacheUtil.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/RequestVettingStation.cpp
Unescaped and used in subforkit announce they get parsed as additional arguments. Escaped, they end up doubly unescaped elsewhere. Just drop them entirely and disambiguate where necessary.
Change-Id: Ia57f14f7cb3aa7c4f77f2dc536996bdcaa38db78
* Resolves: # 
> Drop the config url query params from identifier

- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
test for fix from 296d48f4a0c14f2c527df209e8f10e40e33bdfef
Change-Id: I7033cf78a25235863662da6687107b6a539c2232
> cypress: added jsdialog test

- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
- when UI is refreshed old html is deleted which consist of overwritten css background-image
- this patch makes sure to update document header after '#document-header' is re-created
Change-Id: I6b2723ada4319f9139be8ff8d29b463401540969
> fix: custom logo doesn't persist sometimes

- wsd/COOLWSD.cpp
Visible when running UnitMultiTenant:
#0 0x563e36164273 in __interceptor_memcpy /home/abuild/rpmbuild/BUILD/llvm-15.0.7.src/build/../projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:899:5
...
#3 0x7f41a250828a in UnitSubForKit::killSubForKit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) test/UnitMultiTenant.cpp:65:9
#4 0x563e36538c1b in cleanupDocBrokers() wsd/COOLWSD.cpp:493:32
#5 0x563e365b1b93 in PrisonPoll::wakeupHook() wsd/COOLWSD.cpp:2676:9
Just make a copy if the iterator will be invalidated before the last use
of that config ID.
Change-Id: Ie074d3ff282e228ffd8b96b3514068ec0b08e2a3
> wsd: fix memory corruption in cleanupDocBrokers()

- browser/admin/adminIntegratorSettings.html
- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
* Resolves: # 
- Generate a configuration section using JavaScript to reduce code repetition.
- Add a browser settings section with the following conditions: 
- Only one file can be uploaded. If a file is already uploaded, the upload button should be disabled.
- Applicable only for user configurations.
- Add an XCU section similar to browser settings:
- Only one file can be uploaded at a time.
> Add new sections to setting iframe

- common/ConfigUtil.cpp
- common/ConfigUtil.hpp
- common/FileUtil.hpp
- common/Protocol.hpp
- kit/ForKit.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ProofKey.cpp
- wsd/RemoteConfig.hpp
- **wsd: resolve race on ChildSpawnTimeoutMs**
- **wsd: use unordered_map for default config**
- **wsd: avoid overflowing cleanupWait**
- **wsd: signed-to-unsigned conversion**
- **wsd: avoid copying strings**
- **wsd: avoid overflowing unsigned index**
- **wsd: sign-to-unsigned conversion**
- **wsd: unsigned char to char conversion**
- **wsd: signed-to-unsigned char conversion**
> Sanitization

- browser/css/toolbar.css
- browser/src/control/jsdialog/Util.ScrollableBar.ts
- fixed "this._RTL always returns undefined" issue. scroll buttons are now correctly visible/hidden when scrolling horizontally with right/left scroll buttons.
- aligned scroll-right button arrows on RTL docs
- scroll-right button arrows of statusbar and toolbar were misaligned to the left. This is fixed with 'left: 0px'
-  Calc: show/hide scroll buttons correctly with shift + mouse wheel
- Fixed: "Scrolling toolbar and statusbar with Shift + mouseWheelUp/Down does not hide/show the scroll right/left buttons correctly. Therefore, right/left buttons overlap with other elements." 
Change-Id: Ieeb124df61ba0e2dea94ea256ec1daa2f87b220b
* Resolves: #10942 
**LTR docs:**
**RTL docs:**
- the reason: `this._RTL` always returns `undefined`. So we couldn't know if the doc …
> Calc toolbar/statusbar: fix scroll button issues on horizontal scroll

- browser/src/canvas/CanvasSectionContainer.ts
in I6df1f36d6100857373686c6b57daaa805917df02, we early-exit from onResize to avoid it being called unnecessarily. Unfortunately, it also sets `documentAnchor`, which we missed when checking whether we needed to run through it. This caused an error on mobile web, leading to a failure to open documents in, say, the Nextcloud app.
Change-Id: I4938ade7f03be95b0f0ff3edd4e5805302f22036
* Resolves: # 
> fix: ensure documentAnchor is set in onResize

- browser/src/canvas/sections/CommentSection.ts
problem:
comment HTML being undefined caused some conditions to evaluate to true ie:
in function onLostFocus
this.sectionProperties.contentText.origHTML !== this.sectionProperties.nodeModifyText.innerHTML
Change-Id: Ibeaf20618a9f47b4f3833459c120d6e5155f4fa0
> annotation: avoid autosaving empty comments

- test/UnitTimeoutInactive.cpp
fails for me locally with --enable-debug 'CFLAGS=-O0 -ggdb' 'CXXFLAGS=-O0 -ggdb'
Change-Id: I8cd0cb1d187bf3adab1f81345c1cd83b5180eee4
* Resolves: # 
> increase UnitTimeoutInactive inactivityTimeout

- browser/src/slideshow/PresenterConsole.js
- all the btn (ex: Notes, Slider sorter etc) should have border radius on initialization
- this patch will fix the inconsistency of border radius around btn in PresenterConsole
Change-Id: I880159a69cf5c20ac914785ca12c826c257b6c96
* Resolves: # 
> Buttons in presenter console does not have border radius until be we hover on it

- browser/src/canvas/sections/CommentListSection.ts
Change-Id: I82dd343fdfe6b5fc389320c4b95d6808de4f3e6f
* Resolves: #11057
Changed wording from "Show comment bigger" as it was a bit  of odd (grammar) to "Open in full view"
> Improved comment menu item wording 

- browser/css/cool.css
- browser/src/control/Control.Sidebar.ts
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/calc/sheet_switch_spec.js
- cypress_test/integration_tests/desktop/writer/editable_area_spec.js
- cypress_test/integration_tests/multiuser/writer/cursor_spec.js
The sidebar-showing animation was relying on jQuery, which just animates the width/height properties (absolutely killer for performance). Replace this with a CSS animation. Note, the animation isn't identical; previously the document size would animate, but this now just snaps to the destination size. Animating document size changes is unlikely to be viable any time soon, but we may want to consider some kind of 2-part move + resize animation.
Change-Id: I68eb16e9eff9a3a9601f3f903f9edb25b97a56cd
* Resolves: #10578
> Replace jQuery show animation with CSS animation in sidebar

- browser/src/control/Control.Mention.ts
- Created a separate copy of cursorPosAtStart to avoid modifying the original values when adjusting `cursorPos.y`.
- this will fix the popup moves when user types mention name
- popup should be at start and do not move
Change-Id: I09fad05d742cec7f735648e4f0a5e5217d0d2434
* Resolves: # 
> Fix: Prevent cursor position reference issue

- browser/src/control/Control.NotebookbarImpress.js
- **Impress: Home tab: shuffle buttons, better grouping and space**
- **Impress: Notebookbar: Home tab: Add ui separators in between groups**
> private/pedro/notebookbar impress home tab UI fix

- browser/src/control/Control.MobileWizard.js
Way-back-when, we deselected the toolbar button when the mobile wizard was closed. We stopped doing this during the leaflet migration because the functions we previously used to do it no longer existed (I652a163ea0c831b47ce7725ffd0f9f190a98d9bf). Instead, we can use whether the 'selected' class is on our elements in the DOM to see if they should be unchecked.
That change had far more '.uncheck(...)' and '.check(...)' than I've set up here, and some of those may be necessary, but this was the bug I knew about and I didn't want to poke around with things that I wasn't completely sure where I was changing.
Change-Id: I737693f6db96c8298c07b195aa374a1bbb670108
* Resolves: # 
> fix(mobileWizard): stop highlighting on close

- browser/src/canvas/sections/ShapeHandleRotationSubSection.ts
- browser/src/canvas/sections/ShapeHandleScalingSubSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/common/impress_helper.js
Issue:
* Open an Impress file and start editing a textbox.
* See that handles are visible.
* Try to re-scale the selected shape.
* It doesn't work but the preview is shown.
* When text editing is active, scaling is not enabled.
* We need to hide the handles in that case.
Change-Id: I0ebf20270fc08f8553c1985456836711369407e4
* Resolves: # 
> Hide scaling handles of shapes when text cursor is visible.

- browser/html/cool.html.m4
- browser/js/global.js
- browser/src/control/Control.AboutDialog.ts
- common/ConfigUtil.cpp
- configure.ac
- coolwsd.xml.in
- wsd/FileServer.cpp
In user_interface section.
Change-Id: If5033a3221de985cf82eace8dc7c28fec220c419
* Resolves: # 
This allows to set a product name and product url.
The option is visible only in COOL.
> Add xml parameters brandProductName and brandproductURL

- browser/src/map/handler/Map.Keyboard.js
If we are in the state when we didn't load document (for example error appeared) - on key press we
got error in the console:
Map.Keyboard.js:377 Uncaught TypeError: Cannot read properties of undefined (reading '_docType')
at NewClass._onKeyDown (Map.Keyboard.js:377:29)
at HTMLDivElement.handler (DomEvent.js:51:14)Understand this errorAI
Map.KeyboardShortcuts.ts:113 Uncaught TypeError: Cannot read properties of null (reading 'dispatch')
at KeyboardShortcuts.processEventImpl (Map.KeyboardShortcuts.ts:113:32)
at KeyboardShortcuts.processEvent (Map.KeyboardShortcuts.ts:138:18)
at NewClass._globalKeyEvent (Map.Keyboard.js:408:32)
at HTMLDocument.handler (DomEvent.js:51:14)Understand this errorAI
Map.Keyboard.js:377 Uncaught TypeError: Cannot read properties of undefined (reading '_docType')
at …
> Fix error in onKeyDown handler

- browser/src/map/handler/Map.Keyboard.js
- browser/src/map/handler/Map.KeyboardShortcuts.ts
Change-Id: I28e1583b0ba3cb3e0e2bf85bfd482392e3ea04d8
> js: move disabling AutoText dialog shortcut logic to Map.KeyboardShortcuts.ts

- test/UnitTimeoutInactive.cpp
Encouraged by commit 91a83bcacb7d1d181bb6e37a26e69920dfde912a (increase
UnitTimeoutInactive inactivityTimeout, 2025-01-30), looking at why a
core.git dbgutil + online.git debug build still fails here, it seems it
now passes fine with a bit more relaxed timeout.
The new value is still 10k times smaller than the default, so is meant
to be still minimal.
Change-Id: I04cc2e111ac86b4bb49e03ab73635796078f0a1a
> test, UnitTimeoutInactive: increase the timeout further

- browser/css/jsdialogs.css
- browser/images/circle-check.svg
- browser/images/monochrome-x-cross.svg
- browser/src/control/Control.ServerAuditDialog.ts
Change-Id: I6c91fb915d6abd6dfd93536fdde6a2835091b6f5
* Improves: https://github.com/CollaboraOnline/online/pull/10925#issuecomment-2601894287
- Added new stylings to the indicator to make it distinct
- Added both cases for no issues and errors plus count of issues
- Added new check-mark icon for audit success
With no Issues
> UX iprovements on server audit dialog

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
As initially written in 2022
https://github.com/CollaboraOnline/online/issues/4738 and later
https://github.com/CollaboraOnline/online/issues/9566, in non
technical terms user should be able to navigate with cell cursor
through lengthly sheets without getting lost when attempting to
read/scan distant cells from the same row or column.
- Use a more concise "Focus Cell" term that is more reminiscent of a
mode and that describes better the desired intent.
Change-Id: I47b3e6e06aacc7f9fd42c57edb6acade63a125f9
> Calc: Rename Column/Row Highlighting to Focus Cell

- browser/src/control/Control.UserList.ts
We seems to rerender avatars (in DOM) on every key press. Do it only if selected user was changed.
see:
Map.Keyboard.js     : _handleKeyEvent
Control.UserList.ts : selectUser
> UserList: do not render when not changed

- browser/css/jssidebar.css
visible in Calc where not always we have that much content inside the tree
> css: make style tree in sidebar full height

- .clang-tidy
- common/SigUtil.cpp
- common/Util.cpp
- common/Util.hpp
- fuzzer/Common.hpp
- fuzzer/HttpEcho.cpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitWebSocket.cpp
- net/NetUtil.cpp
- **fuzz: include cleanup in HttpEcho.cpp**
- **wsd: constexpr Util::isFuzzing()**
- **wsd: short-circuit isKitInProcess() where possible**
- **clang-tidy: ignore static-assert**
- **fuzz: move CHECK to Common.hpp**
- **fuzz: no error logging while fuzzing**
- **fuzz: disable some assertions during fuzzing**
- **fuzz: disable precondition assertion during fuzzing**
- **fuzz: disable handling of some commands**
- **fuzz: disable asserting for valid commands**
- **fuzz: never terminate**
- **wsd: use the sanitized LogLevel**
- **wsd: avoid copying shared_ptr**
- **wsd: optimize resolveDNS eviction**
> Fuzzing and Misc Improvements

- browser/src/docdispatcher.ts
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
Pressing Column Row Highlight button wasn't switching the highlight mode quickly. We had to wait cursor invalidation to see highlight. Now pressing button triggers the mode quickly.
Change-Id: Ic5c84e625a3f96f6cc9858dfb84d14474bd9e773
* Resolves: # 
> Update highlight mode without waiting cursor invalidation

- wsd/wopi/CheckFileInfo.cpp
https://sdk.collaboraonline.com/docs/advanced_integration.html
See: CheckFileInfo response properties
BaseFileName:
A string containing the base name of the file, omitting its path.
Change-Id: Ia861aef80fe2d89a6953628ef7557b2488d24323
* Resolves: # 
> validate BaseFileName requirements

- browser/src/control/Control.JSDialogBuilder.js
The jquery-ui tooltip is creating a instance for each toolbar
button, which creates unnecesary hidden elements
<div role="log" aria-live="assertive" aria-relevant="additions"
class="ui-helper-hidden-accessible"></div>
Anyway, the tooltip was replaced for a new Tooltip class.
Change-Id: I73368b3ce46ec72e4fa7efb94a772637b24e8541
> browser: accessibility: remove jquery tooltip for buttons

- coolwsd.spec.in
- debian/coolwsd.postinst.in
Backstory:
Our client has set up an EDR on their servers.
Recently Collabora could not be updated.
On the configuration step of the coolwsd package, the script tries to remove "/opt/cool/systemplate/etc/hosts" . Because it's a hard-link of the "/etc/hosts", the EDR disallow any modification, including removal.
The client doesn't want to set an exception to allow a package to modify a sensible file like "hosts". Can Collabora avoid a removal on this file ?
--
I hope this helps...
Change-Id: Id4c1d72b705dee460a709a5a22312bc3d692a5a6
> Do not fail install when /opt/cool is not fully deletable

- browser/css/jssidebar.css
Change-Id: I3f9949029940491f9fd72e0fec0c3f2eaf68a65f
* Regression #11100 
After change in information hierarchy in the style list the height on n-th div was applied to setting and filter instead of treeviews
> css: make treeview in stylelist sidebar full height

- net/NetUtil.cpp
In file included from net/NetUtil.cpp:14:
In file included from ./net/NetUtil.hpp:14:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/chrono:41:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/sstream:38:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/istream:38:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/ios:42:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/bits/ios_base.h:41:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/bits/locale_classes.h:40:
In file included from …
> net: fix clang-15 build

- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
We now validate the CheckFileInfo response
immediately after receiving it, and we mark
it as Fail if it doesn't pass.
This results in the prompt closing of the
client connection, with an equally immediate
"Document loading failed" message to the user
with "Unauthorized" in the message (though the
message refers to the host).
The logs show:
```
ERR  #30: BaseFileName should be the name of the file without a path, but is: ../../about21.odt
ERR  #30: WOPI::CheckFileInfo (24ms) failed or no valid JSON payload returned. Access denied.
DBG  #31: WOPI::CheckFileInfo failed, sending error and closing connection now
```
And the connection is closed via sendUnauthorizedErrorAndShutdown().
Change-Id: I1e706c7d12e66452476a90631b1521fc93d44e63
Signed-off-by: Ashod Nakashian …
> wsd: better CheckFileInfo validation

- coolwsd.xml.in
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/KitWebSocket.cpp
- scripts/undoStatistics.py
load / save is logged with time duration, filesize, and extension like this:
kit=001 time=0.594 dur=0.534 user=4 rep=1 cmd:load size=10377 ext=docx
there are some separarate "save" for different saving: "save"
"savebg" - save in background
"saveas"
"exportas"
reporting script is not final, it just list all the load/save It will need a better statistics with better charts, but that can be done later.
Change-Id: I67ab4bf4591aca4ec03d9167a26b13cbc6b6aa07
* Resolves: # 
> UILog save/load statistics

- browser/src/control/Control.UIManager.js
When we add a new custom button it resets all top toolbar and builds again. So we lost the style changes of the old custom buttons and have only last inserted one.
To fix that we have to update old custom button style too.
Change-Id: I26188ff8af99dfe07484fd4c8b00edeed81c562e
* Resolves: # 
> Update all custom button style rules during insert new one

- common/RenderTiles.hpp
- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/TileCache.cpp
- wsd/TileCache.hpp
- wsd/TileDesc.hpp
Related to #10980 
Check if we have pending rendering before requesting new one for the same tile.
Add some useful logging for rare cases in TRC.
Client only "can" request rendering keyframe by wid=0 when tile is not in cache.
Client cannot force it when we already have correct one.
Manual test:
1. open calc
2. open debug tools with tile overlays and invalidations
3. hold page down until reaching missing tiles (red color)
Check what we received, ideally would be to just get single tile as it wasn't edited.
> tiles: duplicated rendering

- browser/mocha_tests/LOUtil.test.ts
- browser/src/app/LOUtil.ts
Fix an issue in LOUtil._doRectanglesIntersect() caught by mocha. Also introduce unit tests for LOUtil._getIntersectionRectangle().
> Fix an issue in LOUtil._doRectanglesIntersect() caught by mocha

- browser/css/toolbar.css
Change-Id: I84239134f959e62fb6cfe7bea62bba782593bf29
These properties were missing making the branding icon invisible in light mode
> impress: fix navigator sidebar icon missing width and height

- wsd/DocumentBroker.cpp
and since:
commit e0ca4a82328a6750c5ab99dde64b3000b4e11f17
CommitDate: Tue Jan 14 08:31:11 2025 +0000
use std::weak_ptr's of CheckFileInfo to detect callbacks after end of life
we rely upon creation via std::shared_ptr to detect callbacks that outlive CheckFileInfo
and so richdocumentscode didn't work
Change-Id: I1feb7859cc9d078ac70833a230c49ed964ef43e7
* Resolves: # 
> CheckFileInfo created without std::shared_ptr

- browser/css/jssidebar.css
Change-Id: I9997609f0f94cfc09f7be39369af8aa5cef2e543
Aligned the 'Highlight styles' checkbox to match the correct positioning, ensuring visual consistency and improved UI alignment.
> Align style list settings checkbox for visual consistency

- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Util.FocusCycle.js
- no need for mobile wizard on desktop
- shortcut for input detection
Related to issue #11124
> Reduce some cost of cursor update

- browser/src/core/Debug.js
- browser/src/core/Socket.js
Add the ability to start a watchdog timer on event delays when processing events to track when large, unexpected event delays may happen.
Change-Id: I7a73069fade52b3eca6f8793e43ee52bf9087c9a
> Introduce an event delay watchdog debugging feature

- wsd/ClientSession.cpp
- Steps to reproduce:
1. Open document and toggle darkmode
2. Reload the document
- Actual: Notice inverted document background with darkmode
- Expected: Both background and UI should be in darkmode
Change-Id: I22dc8cc45adc0baf98a95947242f927826c0437c
> browsersetting: fix: client defaults to use darkTheme with inverted background

- kit/Kit.cpp
- net/Socket.cpp
- net/Socket.hpp
Open the 300 pages bugdoc, go to the end of page 1 (before a page
break), press enter, a page 2 is inserted and we get new tiles after a
delay:
15:08:33.803 global.js:566 1738073313803 OUTGOING: key type=up char=0 key=1280
...
15:08:34.249 global.js:566 1738073314249 INCOMING: delta: nviewid=1000 part=0 ...
-> 446 ms.
The reason this happens is because our anyInput callback tells core to
finish the idle Writer layout first and only then render the tiles for
the visible area, which is a problem similar to what commit
930cd616fb6defd8c0de0163bd92e637c7b6b76f (Related: cool#9735 kit: use
the new registerAnyInputCallback() LOK API, 2024-08-26) fixed.
Fix this problem by improving the anyInput callbacks to take 2 more
"inputs" into account:
1) LOK_CALLBACK_INVALIDATE_TILES went to …
> cool#11064 kit: check for callbacks & wsd socket in the anyInput callback

- docker/from-packages/Dockerfile
- docker/from-packages/scripts/start-collabora-online.sh
- docker/from-source-gh-action/Dockerfile
- docker/from-source-gh-action/start-collabora-online.sh
- docker/from-source/ArchLinux
- docker/from-source/Debian
- docker/from-source/Fedora
- docker/from-source/Ubuntu
- docker/from-source/openSUSE
* Resolves: # 
Consider using the Collabora Online container in a federated Nextcloud setup. To make federation work, an additional parameter to configure CSPs has to be passed to Collabora: `--o:net.content_security_policy="frame-ancestors *.example.com:*;"`.
However, this is not possible via the current `extra_params` environment variable as it will do word splitting on spaces. Instead of retaining spaces, it will split the frame ancestors configuration on each space.
**Actual:** `|--o:net.content_security_policy="frame-ancestors|*.example.com:*;"|` (2 arguments)
**Expected:** `|--o:net.content_security_policy=frame-ancestors *.example.com:*;|` (1 argument)
The `|` character was added to demonstrate word splitting problems. It represents the separation of …
> feat(docker): pass arguments directly to the entry point

- browser/src/control/Control.ServerAuditDialog.ts
Some languages have more than 1 plural forms, which we cannot handle in current l10n framework.
Change-Id: Ifc5cb44e667ea8649b75d2983198e655b36728d0
> More localizable issue count on Server Audit dialog

- browser/src/map/handler/Map.Mouse.js
Scrollbar section is on top of document, if we click there - events are propagated. If we follow someone we don't want to stop just by scrolling. Let's not allow to pass events to the document if user clicks on a scrollbar.
```
(anonymous) (Map.Mouse.js:133)
_executeMouseEvents (Map.Mouse.js:196)
setTimeout
(anonymous) (Map.Mouse.js:136)
(anonymous) (global.js:954)
fire (Events.js:153)
_fireDOMEvent (Map.js:1602)
_handleDOMEvent (Map.js:1572)
(anonymous) (global.js:954)
handler (DomEvent.js:52)
```
> following: don't stop if using scrollbar

- clang/Makefile
- clang/plugin.cpp
- clang/test/refcounting.cpp
Finds:
CXX      wsd/DocumentBroker.o
wsd/DocumentBroker.cpp:1035:27: error: instance allocated on the stack, create it with std::shared_ptr [coplugin:refcounting]
CheckFileInfo checkFileInfo(poller, session->getPublicUri(), [](CheckFileInfo&) {});
^~~~~~~~~~~~~
1 error generated.
With 67504c45efeb36a8d91b1ce85b27af8cf257e051 (CheckFileInfo created
without std::shared_ptr, 2025-02-13) reverted.
Change-Id: Ic702d5ab3cd08c0de54df5edc61db8d5c50834fb
> coplugin: add refcounting check

- browser/Makefile.am
- browser/npm-shrinkwrap.json.in
- browser/package.json
- browser/tsconfig.json
- cool-sbom-template.spdx.json
DOMPurify before 3.2.4 has an incorrect template literal regular expression, sometimes leading to mutation
cross-site scripting (mXSS).
Change-Id: If69bb5b06a0519c56c13019f7d19d7f58856814e
> Use DOMPurify 3.2.4

- browser/Makefile.am
- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/admin/src/integrator/WordBook.ts
- wsd/FileServer.cpp
- wsd/FileServer.hpp
Change-Id: I68b70ee8c140e8e71f312b6120ae880fab46a5d1
* Resolves: # 
This PR enables the edit button for WordBook, which opens a popup dialog allowing you to add or delete words from the dictionary.
It also updates the .dic file upload flow:
-  Previously, .dic files were uploaded directly without processing, which caused issues.
-  Now, if a user uploads a file without headers, a default header is appended; if headers are present, they are removed and replaced with our own.
> setting: allow wordbook to edit and remove words from wordbook

- browser/src/canvas/sections/CommentListSection.ts
While importing comments, confirmation popup causes false alerts. Issue: Because when user's comment is autosaved, import comments is activated and model pops up.
Change-Id: I61d75d4ee5c9343f14edb86630c9b5e49b29a7ec
> Impress: Return silently if a comment is being edited.

- common/JsonUtil.hpp
* Resolves: #11175
This fixes compilation with poco 1.14.1 (and probably 1.14 - but I haven't explicitly tested that
> Fix missing include for poco 1.14.1

- kit/ChildSession.cpp
- kit/LogUI.cpp
- scripts/undoStatistics.py
fixed a save/load problem ..
If application opened the document, it logged the open with its userID, so it seemed it has a real viewer user.
Now it will set userID to -1, if it is opened by an app, And if userID == 1, it will not count it.
Fixed the script part too... if userID<0 then it does not use it.
Made 5 statistics:
load / save:
- size-count (grouped by writer/calc/impress/draw)
load / save foreground / save background:
- size-time(median) (grouped by basic filetypes)
Change-Id: Ibac04981160bf86d43fabc6802facf61316c4984
* Resolves: # 
> UILog fix save/load and add statistics

- browser/src/dom/NotebookbarAccessibility.js
Otherwise it will create a possible pattern:
<div style="height: 0px; width: 0px; overflow: hidden;"><input type="submit" role="tablist" id="accessibilityInputElement" autocomplete="off" style="height: 0px; width: 0px;"></div>
<div style="height: 0px; width: 0px; overflow: hidden;"><input type="submit" role="tablist" id="accessibilityInputElement" autocomplete="off" style="height: 0px; width: 0px;"></div>
<div style="height: 0px; width: 0px; overflow: hidden;"><input type="submit" role="tablist" id="accessibilityInputElement" autocomplete="off" style="height: 0px; width: 0px;"></div>
<div style="height: 0px; width: 0px; overflow: hidden;"><input type="submit" role="tablist" id="accessibilityInputElement" autocomplete="off" style="height: 0px; width: 0px;"></div>
<div style="height: 0px; …
> browser: accessibility: ensure to create only single instance

- common/JsonUtil.hpp
- common/StateEnum.hpp
- common/Unit.cpp
- net/DelaySocket.cpp
- net/HttpRequest.hpp
- net/Socket.cpp
- test/KitPidHelpers.cpp
- test/Makefile.am
- test/NetUtilWhiteBoxTests.cpp
- test/UnitOAuth.cpp
- test/UnitQuarantine.cpp
- test/UnitSaveTorture.cpp
- test/UnitTyping.cpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPILock.cpp
- test/WOPIUploadConflictCommon.hpp
- test/WhiteBoxTests.cpp
- test/integration-http-server.cpp
- test/lokassert.hpp
- tools/Replay.hpp
- **wsd: remove toString from StateEnum**
- **wsd: remove toStringShort**
- **wsd: avoid intermediate vector when escaping JSON**
- **wsd: StateEnum const char`*` -> string_view**
- **wsd: reduce copying and simplify Replay.hpp**
- **wsd: minimize string copying in asyncUpload**
- **wsd: test: move NetUtil tests to NetUtilWhiteBoxTests.cpp**
- **wsd: test: include cleanup in WhiteBoxTests.cpp**
- **wsd: test: add StateEnum tests**
> Reduce String Copying

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.Combobox.js
- browser/src/control/jsdialog/Widget.Edit.ts
Change-Id: I0c86a21b95babf866a49d3db9800cd3be45e929a
This adds autocomplete="off" to input elements including radio buttons, checkboxes, spinfields and text inputs. This prevents unwanted browser autofill behavior and native browser popups that can interfere with the application's form handling.
> Set input elements to autocomplete="off" to prevent browser autofill

- tools/map.cpp
stl_vector.h:1149: Assertion '__n < this->size()' failed.
Change-Id: Ie9a081fd6c797be181b0075c70b54b5bed8f4a1b
* Resolves: # 
> fix coolmap crash

- browser/src/app/LOUtil.ts
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Widget.Combobox.js
- browser/src/control/jsdialog/Widget.SidebarContainers.ts
- browser/src/control/jsdialog/Widget.TreeView.ts
- browser/src/map/handler/Map.WOPI.js
Before imgurl was essential while inserting custom buttons. Now we find the button icon via uno command name even if the imgurl doesn't send by user.
Change-Id: Ide8f6df68018fcac98ce95f1a5c4a9317cff3473
* Resolves: # 
> Allow to handle custom uno commands without imgurl

- common/RenderTiles.hpp
Change-Id: I8ca3a6cf15a844e6c7fe1613362b8f977781b83c
* Resolves: # 
> include size in tiles in 'extremely large tile combine' warning

- net/Socket.hpp
- wsd/DocumentBroker.cpp
- **wsd: remove single-use setClosed()**
- **wsd: improve isClosed/setClosed documentation**
- **wsd: enrich warning log with context**
- **wsd: assertions for socket closing consistency**
> Misc Socket Cosmetics

- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/admin/src/integrator/WordBook.ts
- wsd/FileServer.cpp
- wsd/FileServer.hpp
* Resolves: # 
Previously, loading large dictionary files sometimes crashed the browser due to synchronous parsing. This change converts the parsing process to run asynchronously using a Web Worker, ensuring that the main UI remains responsive while large files are downloaded and processed in the background.
Additional changes:
- Renamed some references from "dictionaries" to "wordbook" for consistency.
- Added a loader UI during the file download process.
- [fix: implement custom smooth scrolling for large wordbooks](https://github.com/CollaboraOnline/online/pull/11199/commits/d8409a58d488556bdc842fae501408131a240f26)
- [enhancement: Scroll to end when we add new word to wordlist](https://github.com/CollaboraOnline/online/pull/11199/commits/1a5b4d4a15442e5ad5df60 …
> handle large wordbook file with Web Worker

- browser/src/canvas/sections/CommentSection.ts
- Fixed an issue where day and month were swapped in cell comments (e.g., "12.02.2025" interpreted as "02.12.2025").
- Implemented proper date parsing to correctly interpret DD.MM.YYYY HH:MM format.
- Ensured comments display the expected localized date format across different languages.( Specially in german)
Change-Id: Id6d44792bf005992ea22e62b27934e16fa6e3732
* Resolves: #11149
> Fix incorrect date display in cell comments

- common/Common.hpp
- discovery.xml
- wsd/ClientRequestDispatcher.cpp
Change-Id: Ib4f903c6d7fef466bd967ccbba11abc97d6582b9
* Resolves: # 
[discovery: add Settings app to support settings iframe URL](https://github.com/CollaboraOnline/online/commit/4f2cf87c77f77199f2e50b770ccbf5727d0b730f)
> discovery: add Settings app to support settings iframe URL

- net/HttpRequest.hpp
- wsd/ClientRequestDispatcher.cpp
* Resolves: # 
Add new CheckStatus SelfSignedCertificate and ExpiredCertificate along the way.
Fixes #11162
Context: https://github.com/CollaboraOnline/online/pull/9202
> wsd/wopiAccessCheck: handle self-signed certificate

- net/AsyncDNS.hpp
- net/NetUtil.cpp
- net/NetUtil.hpp
- wsd/ClientRequestDispatcher.cpp
Change-Id: I2a08bd77f837ba3b8a2a57e90e79ce5bb86305e8
* Resolves: # 
> we might have a HostEntry in the dns cache already

- common/JailUtil.cpp
- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/RemoteConfig.cpp
- wsd/RemoteConfig.hpp
- It was added to install templates on the fly. After 608d3cae9377af85a47877f0124eac9888988811 this feature is no longer needed. Templates can be added by defining it in "SharedSetting" and "UserSetting" CheckFileInfo property for admin and user respectively.
- This patch reverts all the related commit added in the PR: https://github.com/CollaboraOnline/online/pull/10463
- List of reverted commits:
- Revert "wsd: remoteassetpoll: rename json property "stamp" to "version""
4d922bb06c0cacde728bedbfb74eb33a81a95828.
- Revert "wsd: remoteassetpoll: rename jsonkey "presnt" to "presentation""
1492f92d43b909e6c44c7661ba7c6b9193a8397e.
- Revert "wsd: remote: adjust templates json object" 2e79ac30bcb89f990fb68377867a07059c85a290.
- Revert "wsd: fix: don't start remoteassetconfig_poll if configkey …
> wsd: revert remoteassetpoll, remote_asset_config is no longer needed

- net/SslSocket.hpp
Since those are very common and aren't errors, print output about them only in trace.
Logs are filled with logs such as:
Feb 18 01:13:45 collabora coolwsd[509]: wsd-00509-00509 2025-02-18 01:13:45.083739 +0100 [ coolwsd ] DBG  #37: SSL error (handshake): WANT_READ (2), rc: -1, errno: 11 (EAGAIN: Resource temporarily unavailable): BIO error: 0: error:00000000:lib(0)::reason(0):| net/SslSocket.hpp:384
Feb 18 01:13:45 collabora coolwsd[509]: wsd-00509-00509 2025-02-18 01:13:45.099295 +0100 [ coolwsd ] DBG  #37: SSL error (read): WANT_READ (2), rc: -1, errno: 11 (EAGAIN: Resource temporarily unavailable): BIO error: 0: error:00000000:lib(0)::reason(0):| net/SslSocket.hpp:384
Feb 18 15:22:12 collabora coolwsd[509]: wsd-00509-00520 2025-02-18 15:22:12.216662 +0100 [ websrv_poll ] DBG  #37: SSL …
> net/SslSocket: don't log Zero_Return and EAGAIN in dbg level

- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- we have custom tooltip that gave information about document's last saved state
- this is missing from impress and draw.
- this patch will enable the custom tooltip for impress and draw
Before:
After:
Change-Id: Ifc00921f127e517dbe9a497243e8f40b2e37ace9
* Resolves: # 
> Added document's last modified information in impress

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/map/handler/Map.WOPI.js
If either _supportsRename() or UserCanRename are false (default value) the rename document button is hidden. So is the menu item.
_supportRename() checks for both SupportsRename and not UserCanNotWriteRelative
Change-Id: I1543b6e02358ee6307a6c184440bd2a850a4b848
* Resolves: # 
Hide the rename document button / menu if rename isn't supported or allowed.
> wopi: Hide Rename button if WOPI doesn't support or allow

- wsd/RequestVettingStation.cpp
- happens when templates are not passed as a part of sharedconfig.json
Change-Id: I5ca53e35a6db3cef84d18ad8004ceeed4cc839ac
* Resolves: # 
> lokit: fix fail to mount shared preset template directory

- wsd/DocumentBroker.cpp
RequestVettingStation can complete and take down its PresetsInstallTask if the required subforkit is already available
Change-Id: I7b2ec831158022e904bb28223053150543a2a241
* Resolves: # 
> protect asyncInstall lifecycle

- browser/css/notebookbar.css
- browser/css/toolbar.css
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
In compact mode, the toolbar-row (the second bar up top) was being set
with a hard coded pixel (42px) which was resulting in extra space and
the misaligned icon row.
The initial diff comes from:
e88d9340a0067c9fb267fe3a3653e42c0298ee71
Fix toolbar up section after w2ui rework
Maybe there is something I missed, but I think we can now safely
remove that compact mode related CSS declaration while making sure
the one that is intended to affect notebookbar only does that.
Change-Id: Ic50c8a89578bb1dc7c2acf5f631fdea81a1d235d
> Compact mode: Fix toolbar-row height

- browser/css/spreadsheet.css
- browser/src/control/Control.Menubar.js
- browser/src/unocommands.js
Remove old CSS rule to hide style sidebar shortcut. We have it now in calc. Unify menubar command with other places. EditStyle doesn't work second time when used.
Menubar changes:
- put "Open the Styles Deck" in Calc -> Format (like in Writer)
- add "Styles Deck" in Calc -> View
- moved Edit -> View in Writer for "Styles Deck" (similar to Navigator and general properties Sidebar decks)
> Use correct command for style sidebar

- browser/src/app/TilesMiddleware.ts
We should give coolwsd plenty of time to return a complete keyframe if we are pre-loading it, so annotate a tilecombine with when the last tilecombined was sent on it.
For tiles in the current view, we should get pushed tile content anyway almost always; special-case keyframe fetching when we have cleared our cache early.
Change-Id: Id6bfe630ac276a7cc3d7eb7a748c769bddd95a80
* Resolves: # 
> tiles: avoid sending tilecombines too fast.

- scripts/run-wsdunit
- test/TileCacheTests.cpp
- **run-wsdunit: build the test if necessary**
- **unit-tiletest, testUnresponsiveClient: don't assume invalidate is sent without having tiles first**
- **unit-tiletest: disable remaining broken tests in this suite**
> unit-tiletest, testUnresponsiveClient: don't assume invalidate is sent without having tiles first

- kit/KitQueue.cpp
- test/KitQueueTests.cpp
- test/Makefile.am
- wsd/TileDesc.hpp
* Resolves: # 
Try and create more sensible tile combines. Combine as many horizontal tiles as sensible with priority tile, working from both sides of it, favoring nearer tiles until reasonable span width is exhausted. Combine adjacent rows with this span. Distribute any "unused" available span width on comparing adjacent rows to pick up relatively cheap additions to the combine.
> avoid excessively wide tile combines

- Makefile.am
- cypress_test/Makefile.am
- **automake silent rules: handle build-samples.py**
- **cypress: reduce the max num of open file descriptors to catch problems**
> cypress: reduce the max num of open file descriptors to catch problems

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
Change-Id: I0ce4621c9db23ec429fcd8304f3133850f89495b
Style list -> Hierarchical -> Default paragraph->  Body text -> List
[Screencast from 27-02-25 15:03:18.webm](https://github.com/user-attachments/assets/19d9d889-90c8-47c5-ada5-ce5c7c922162)
-
> ui-treeview: reduce margins to fit headings in treeview sidebar

- test/TileCacheTests.cpp
- **cool#11254 unit-tiletest: restore testTileInvalidateWriter()**
- **cool#11254 unit-tiletest: restore testTileInvalidateWriterPage()**
- **cool#11254 unit-tiletest: restore testTileInvalidateCalc()**
- **cool#11254 unit-tiletest: restore testTileRequestByInvalidation()**
> cool#11254 unit-tiletest: restore tests

- common/ConfigUtil.cpp
- wsd/ClientRequestDispatcher.cpp
Directly enable hasSettingIframeSupport by removing the configuration override for setting_iframe.enable
Change-Id: I5d827119f66b3a43656a4f18f2bc1b54f557d1b2
* Resolves: # 
Mentioned here : https://github.com/CollaboraOnline/online/pull/11088#pullrequestreview-2598600195
> refactor: enforce hasSettingIframeSupport capability

- Makefile.am
Similar to commit cffb277cc22a0b25fdac783f0cd876eeb8a85a0d (automake
silent rules: handle build-samples.py, 2025-03-06), so 'make V=1' shows
the full output and it's more compact in the --enable-silent-rules case.
Change-Id: I1cc0a92d218cdcde36a70f6c06367a26a1e09d8f
> automake silent rules: handle create-sbom.py

- docker/from-packages/scripts/start-collabora-online.sh
- docker/from-source-gh-action/start-collabora-online.sh
so doesn't need to be written.
See man 1 openssl for "Random State Options", -rand option reads the output from -writerand and that's unused here and apparently unnecessary since OpenSSL 1.1.1
Change-Id: Ia3709f993b71644be8f0b816a88212efc7b76092
* Resolves: # 
> output from writerand is unused

- docker/from-packages/scripts/start-collabora-online.sh
- docker/from-source-gh-action/start-collabora-online.sh
Change-Id: Id1077ff63203f74f4802af087558a6ae652fbcf1
* Resolves: # 
> assuming a readonly root, if we gen certs, don't overwrite the originals

- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
**wsd: handle disconnection while loading**
When the client disconnects while we are
loading the document, we risk getting
in an invalid state.
When we get disconnected while loading,
we have logic to terminate the kit.
Unfortunately, we don't account for
the fact that the session isn't yet
removed from the container, and fail
to detect this case. Furtheremore,
we should stop the DocBroker poll,
which we didn't previously.
Also, we fix an invalid state transition:
**wsd: avoid transitioning to LIVE from WAIT_DISCONNECT**
wsd: avoid transitioning to LIVE from WAIT_DISCONNECT
In the event that we gave up on loading,
we should never change the state back to LIVE
once we are in WAIT_DISCONNECT.
This was caught with: WRN  ToClient-002: Unusual race - attempts to
transition from …
> Unload While Loading

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- this will disable browsersetting on client side if parsing fails and user will rely on browser's local storage.
Change-Id: Ica24c0facc880db83f81957d403b5648376f1163
* Resolves: # 
> browsersettting: don't send browsersetting message if parsing fails

- browser/js/global.js
- browser/src/control/Control.Sidebar.ts
- browser/src/control/Control.UIManager.js
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- There are multiple sidebar setting/preference are set by client when user opens the sidebar.
- This patches avoid to send preference individually to each time.
- Ths will also the reduce the amount of upload request to wopihost.
Change-Id: I62d3000493f9d175b9190dffe7fefff79b8f976e
> browsersetting: send multiple preference to server at once

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
"focuscell" reference type is defined for the focus cell feature. resetReferenceMarks can reset the reference by type anymore. And It won't affect the other references.
Change-Id: Ia0ade35bb5c87549eebeea2d73b1d149e3adc9c5
* Resolves: # 
> Seperate focus cell references and other references

- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Definitions.Menu.ts
Have 2 views, both are typing. View 1 turns on recording of tracked
changes, now surprisingly this is also turned on in view 2.
If we record track changes were part of the model previously, now this
is optionally part of the view.
Fix the problem by adding explicit UI to have recording 'off', or 'on'
for a single view / all views.
Requires core.git co-24.04 commit
a67519e2053fae13945df64c959e975bb1298833 (cool#11226 sw per-view redline
on: support this-view <-> all-views transition, 2025-03-10).
Change-Id: I1d5f1079e3b705b6844516a6938f54b446c0c261
> cool#11226 sw per-view redline on: add tri-state UI in the notebookbar

- wsd/Admin.cpp
- wsd/DocumentBroker.cpp
- wsd/Storage.hpp
- wsd/wopi/WopiStorage.cpp
Mostly logging and state-dumping improvements, with only one functional change where we now upload when previously we had skipped it. The commit log (and comments) explain the case in question, which is rather rare but gets us stuck.
- **wsd: better admin OOM closing**
- **wsd: dump Storage state**
- **wsd: log the URI that we failed to connect to**
- **wsd: detect inconsistent lastModifiedTime in the managers**
- **wsd: allow uploading when otherwise there might be no need**
> Better OOM Handling

- kit/Kit.cpp
terminate called after throwing an instance of 'std::system_error'
what():  Invalid argument
```
#7  0x00007eed108ae277 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007eed108ae4d8 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#9  0x000000000056014b in ?? ()
#10 0x00000000005f899f in BackgroundSaveWatchdog::BackgroundSaveWatchdog(unsigned int, int)::{lambda()#1}::operator()() const ()
```
it strikes me that there is a possibility that _watchdogMutex might be used here before it gets initialized.
Change-Id: I04ed96a280dc02a2ecd534cc093e2584fd577aca
* Resolves: # 
> init _watchdogThread after _watchdogMutex was constructed

- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- this patch will delay the socket shutdown if request require async operation in FileServer
- we need to delay socket shutdown for preset fetch, upload, delete operation
Change-Id: I4b8124e7302d6352cb542b2d85ded246a9e7c24e
> wsd: fix: socket closes early when fetching preset file(backport)

- browser/src/app/TilesMiddleware.ts
- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
* Resolves: #11255 
Return canvas elements to a pool for reuse instead of always creating them on-demand and destroying them immediately.
> cool#11255 - don't free tile canvases, but queue them for re-use

- browser/css/menubar.css
Before this commit the .main-nav's width had bigger width than the
webview due to borders not being factored in. This was particular
visible for integrators that have the close button toggled off and
that have no "EnableShare" where the last sidebar icon was "glued" the
right edge of the web view.
Cases where this is possible to test:
- Using the make run Edit mode urls in Tabbed view
- Places where Collabora Online is integrated with close and
share buttons. Example: Moddle
Change-Id: Ie189ed780080cda69d3d41e425a047c45d0e69e9
> Notebookbar: main-nav: Fix last child being glued to the edge

- wsd/FileServer.cpp
- fetch-wordbook is not async
Change-Id: Iac7ca9062b0e8ca6d0ff9b5da050bfea3015fcc4
* Target version: distro/collabora/co-24.04
> wsd: preset: close socket for fetch-wordbook(backport)

- test/KitQueueTests.cpp
- wsd/SenderQueue.hpp
Change-Id: I72a57dd2d7d068c6a7ee89b910f7c971d4f20a53
* Resolves: # 
> SenderQueue - collapse repeated items, and dump size in bytes.

- wsd/DocumentBroker.cpp
```
wsd-05530-05210 2025-03-14 05:50:12.416584 +0000 [ docbroker_2fe ] INF Syncing browsersettings of the users| wsd/COOLWSD.cpp:341
wsd-05530-05210 2025-03-14 05:50:12.422754 +0000 [ docbroker_2fe ] SIG Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x730000159a
Backtrace 5530 - wsd 24.04.13.2snapshot 8266fe8509:
Files in quarantine:
/usr/bin/coolwsd
SigUtil::dumpBacktrace()
/home/collabora/jenkins/workspace/package_cool_24.04_rpm/rpmbuild/BUILD/coolwsd-24.04.13.2snapshot/common/SigUtil.cpp:462
/lib/x86_64-linux-gnu/libpthread.so.0
__restore_rt
??:?
/lib/x86_64-linux-gnu/libc.so.6
__GI_raise
/build/glibc-5efeFw/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51 (discriminator 3)
/lib/x86_64-linux-gnu/libc.so.6
__GI_abort …
```
> wsd: browsersetting: fix SIGABRT when syncing browsersetting

- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- Steps to reproduce:
1. Open 2 document for same user
2. Do a single change like for e.g toggle sidebar
3. Notice in logs browsersetting is uploaded twice
- It happens because syncBrowserSettings was getting called for each docbroker and in syncBrowserSetting we were uploading the browsersetting if we find a session with same userId.
- For above mentioned case we uploaded twice
Change-Id: I5bb1f3a6830bc3bc944e74e4f718c9962958db54
> wsd: fix: browsersetting is uploaded multiple times

- kit/Kit.cpp
- kit/Kit.hpp
If we got a:
[ kitbroker_002 ] WRN  Failed to ensure we have just one thread for bgsave, we have: 2 synchronously saving| kit/Kit.cpp:1451
Then we would bail out of forkToSave without re-starting the _deltaPool.
So guard against that from all return paths more simply.
Change-Id: I0751b68613832da3b3a2bb96235300d638119035
* Resolves: # 
> ensure threads are re-started on a failed joinThreads.

- kit/Kit.cpp
This wasn't possible previously, because the core side was missing
commit 4f15a47c7faf55997e776af738106d3da229c7d2 (cool#11064 Set priority
of some idles to TaskPriority::DEFAULT_IDLE, 2025-02-18), but now
co-25.04 has it.
The benefit is that now we don't interrupt high priority core jobs now,
and only start painting tiles after the high priority tasks are done,
but still before idle tasks.
Change-Id: I5556fdbc43841a2fbf3e2ea084199c17e04439d6
> cool#11064 any input: enable COOL_ANYINPUT_CONSIDER_PRIORITY by default

- docker/from-packages/Dockerfile
It is primarily to please vulnerability scanners. E.g. docker scout: 
- Before: 1 high, 1 medium, 35 low severity vulnerabilities 
- After: 24 low severity vulnerabilities
Change-Id: I1b0fa99bace739b38976e2fd4e7b30bfa9ce1f11
> docker: remove packages which were only needed for installation

- browser/src/control/Control.PartsPreview.js
Sometimes the child of the expected element fires the event. Check also parentNode when searching for clicked part.
Issue:
* Cannot re-position a slide by dragging without first selecting it.
Change-Id: I884fc2908ef6523b0f2ad58e00b3793fcda1de2e
* Resolves: # 
> Impress: Fix drag & drop slide pages for reordering.

- browser/src/control/Control.StatusBar.js
- cypress_test/integration_tests/desktop/calc/statusbar_spec.js
- cypress_test/integration_tests/multiuser/calc/invalidations_spec.js
Change-Id: Iecc367a54024dac6719465b4dc7760c285298dd6
* Resolves: #11244 
Change from "Insert mode: Inactive" to "Tracking changes: on" so users don’t think they can’t type when they actually can.
> status bar: update insert mode label for clarity

- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
This was removed in commit 0acb3d515fe4d2a020c91ed833db1c3a72a09cfb
(cypres: fix broken test after switching to 25.04 core branch,
2025-03-14), but the underlying problem is fixed with core.git commit
2490d8fc97b9ec9819755a3b81a6e464431c7cdb (cool#11347 sw lok: avoid view
jump on showing formatting marks, 2025-03-14), so this can be restored.
Change-Id: Ifdabf3a4f7f193dc257568df3bb1e6658422efff
> cool#11347 cypress desktop: restore the last test in writer/scrolling_spec.js

- common/Clipboard.hpp
- wsd/COOLWSD.cpp
Log server up-time.
Log clipboard sizes
Avoid copying large clipboards on dump.
Change-Id: I15a105181bff2a8f3dc8ca76d0f41258076674bf
* Resolves: # 
> Improve diagnostic debug dumping.

- browser/js/global.js
- browser/package.json
- browser/src/canvas/sections/CommentSection.ts
- browser/src/canvas/sections/TilesSection.ts
- browser/src/global.d.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
Previously the only way to control a presentation from a touchscreen was
by tapping to go forward - one slide at a time until you got to the end
where you could tap to exit. This is "non-ideal" for web touchscreen
users, and a blocker on adding support for the new presentation code to
the mobile apps.
I've added some code using hammer.js to detect swipes and act on them,
mirroring some of the keyboard actions. I've done my best to replicate
existing expectations (swipe forwards to go forwards, swipe backwards to
go backwards, swipe up-or-down to exit) from the previous presentation
code.
> feat(slideshow): Add touch gesture support

- fuzzer/HttpEcho.cpp
Otherwise with fail in a non-interesting way:
net/NetUtil.cpp:443:21: runtime error: member call on null pointer of type 'net::AsyncDNS'
#0 0x5639c3c2ea77 in net::AsyncDNS::lookup(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::function<void (net::HostEntry const&)> const&, std::function<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> ()> const&) /home/vmiklos/git/collaboraonline/online-fuzz/net/NetUtil.cpp:443:21
#1 0x5639c3c2e5a1 in net::syncResolveDNS(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/vmiklos/git/collaboraonline/online-fuzz/net/NetUtil.cpp:213:5
#2 0x5639c3c395d3 in net::connect(std::__cxx11::basic_string<char, std::char_traits<char>, …
> httpecho fuzzer: fix this to work with net::AsyncDNS

- wsd/DocumentBroker.cpp
hard to find what is crashing in a optimized build, but:
print _storage._M_t._M_t._M_head_impl
$13 = (StorageBase *) 0x0
points to recently added _storage->dumpState()
Change-Id: Iab3595bdfb3fa2a494dce5f54873313db4be500a
* Resolves: # 
> DocumentBroker::dumpState seen to crash

- wsd/wopi/CheckFileInfo.cpp
To reproduce: open a document through a debug link and close it to establish a baseline.
On each subsequent open and close:
$ ls /proc/`pidof coolwsd`/fd|wc
increments by 2
in ClientRequestDispatcher::handleIncomingMessage closeConnection is the default 'false' for this request and nothing otherwise explictly closes the socket on that side.
Anything similar is not seen in release mode with, e.g. a nextcloud instance.
Change-Id: I927138ba77f54ff6ae86a7c10f003abd89549653
* Resolves: # 
> make run mode fd leak

- browser/src/control/Control.UIManager.js
on mobile there is no notebookbar but we still tried to use it in some cases - detected in cypress
> mobile: do not use notebookbar

- browser/src/canvas/CanvasSectionContainer.ts
When a resize is handled by CanvasTileLayer, two resizes may end up being triggered on CanvasSectionContainer. In this situation, the first happens prematurely and causes drawing to happen before the map is updated, while the second is ignored because the canvas size change was already handled.
> Fix double-resize on CanvasSectionContainer

- browser/src/app/TilesMiddleware.ts
`releaseCanvas` can be called on tiles with no canvas, make sure to check a canvas and context are non-null before adding them to the cache. This is follow-up from #11351
> Don't cache null canvases in TilesMiddleware.CanvasCache

- browser/js/global.js
- browser/src/map/handler/Map.SlideShow.js
- browser/src/slideshow/SlideShowPresenter.ts
- common/MobileApp.hpp
- ios/Mobile.xcodeproj/project.pbxproj
- ios/Mobile/CODocument.mm
- ios/Mobile/CoolURLSchemeHandler.h
- ios/Mobile/CoolURLSchemeHandler.mm
- ios/Mobile/DocumentViewController.h
- ios/Mobile/DocumentViewController.mm
- kit/Kit.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/ServerURL.hpp
Previously, as videos are normally loaded via a /media/ endpoint on the
server, mobile apps did not support loading it. That's because mobile
apps lack a server.
To get around either making a server (opening up HTTP just to serve user
media) or embedding the content directly into the page (as data:, losing
control of when the content was loaded and losing the ability to update
to partial loading - essential for long videos), I've opted to use a
custom protocol handler. Effectively, requests to "cool:/cool/media" are
treated as iOS media requests. Sadly this technique won't immediately
work on Android as it doesn't seem to support custom protocol handlers
so I'll possibly have to make up something else over there (it'll
probably be best to use a similar technique though).
I've also …
> feat(iOS): Support loading video

- common/SigUtil.cpp
- common/SigUtil.hpp
- net/Socket.cpp
- wsd/Admin.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientRequestDispatcher.hpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/TileCache.hpp
- wsd/TileDesc.hpp
- wsd/wopi/StorageConnectionManager.cpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
Various improvements to getting a cleaner valgrind memcheck report.
- **wsd: don't process logging_ui_cmd config if disabled**
- **wsd: don't process logging config if disabled**
- **wsd: clean up remote font config thread before exiting**
- **wsd: unique_ptr needs the size of the pointee**
- **wsd: addStorageDebugCookie in StorageConnectionManager**
- **wsd: replace WopiStorage::initHttpRequest() with StorageConnectionManager**
- **wsd: Admin class cosmetics**
- **wsd: overwrite coolwsd exit code with unit-test result**
- **wsd: clean up as much as possible before forced exit**
- **wsd: add SigUtil::uninitialize()**
- **wsd: string_view in TileDesc**
- **wsd: privatize ClientDeltaTracker**
- **wsd: log active ClientSession in DocBroker dtor**
- **wsd: uninitialize …
> Better Valgrind Support

- wsd/COOLWSD.cpp
If I munge fetchUpdateCheck to make this happen once a second instead of the default every 10 hours I can see this rapidly accumulates hundreds of open fds: ls /proc/`pidof coolwsd`/fd|wc
Unlikely to be very significant in a normal setup.
Change-Id: Ib5041835d2bbd10a52aa98997cbc806a25f06e3a
* Resolves: # 
> fd leak with --with-infobar-url

- browser/js/global.js
browsersettting: fallback to localStorage/uiDefault for undefined setting
When a browser setting is not defined, use localStorage/uiDefault as a fallback. This fixes the regression related to the saveAsMode issue. bug: https://github.com/CollaboraOnline/online/issues/11297
Change-Id: Ic035f3a5af95f903aff4934e998dd0a38675ccdc
* Resolves: #11297 
> browsersettting: fallback to localStorage/uiDefault for undefined setting

- browser/src/layer/vector/Path.js
Seen logs:
bundle.js:22040 Uncaught TypeError: Cannot read properties of undefined (reading '_removePath')
at NewClass.onRemove (bundle.js:22040:16)
at NewClass.removeLayer (bundle.js:13578:87)
at NewClass.removeLayer (bundle.js:21995:43)
at NewClass.clearLayers (bundle.js:21997:75)
at NewClass._clearSearchResults (bundle.js:19773:26)
which may be result of regression in
https://github.com/CollaboraOnline/online/pull/11276 (not sure)
make code more defensive
> Prevent error on Path removal

- browser/src/layer/tile/CalcTileLayer.js
_syncTileContainerSize returns true if it calls requestRedraw. In that case "_restrictDocumentSize" will not call it again.
Issue: Adding a new sheet while zoomed out or switching sheets may result in a smaller view than expected.
Change-Id: Id3663e360b57b433ffede2213b32cb4d4bcd492b
* Resolves: # 
> Calc: Call _syncTileContainerSize after changing document size.

- net/Buffer.hpp
large capacity but ~empty buffers can be reproduced by inserting a large jpg into a blank writer document and copying it to clipboard a few times and then: kill -SIGUSR 1 `pidof coolwsd`
```
rbuffered   rcapacity   wbuffered   wcapacity
0        1993           0    19881378
```
Change-Id: Idc4020ffef5e3d4bc4801792412e2d1f706e2ef1
* Resolves: # 
> reset underlying capacity of previously large buffers

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
This better handles an edge case where saving fails while uploading, as described in the commit log.
- **wsd: more aggressive saving and uploading while unloading**
- **wsd: report how much more time before issuing save/upload**
- **wsd: force saving before unloading if the last save had failed**
> Handle Save Failure While Unloading

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Related to issue #10980
Followup for 6ae718e
tiles: client cannot force keyframe
Version can protect us from rendering the same tile twice. The increase was introduced in commit 5260eae05f89056d4ffc1bdfad1927c3c5f9706d Avoid rendering / sending the same tile twice
> tiles: avoid duplicated version bump

- browser/src/map/handler/Map.Keyboard.js
- browser/src/map/handler/Map.KeyboardShortcuts.ts
Online doesn't know what keybinds it has. Instead, it leaves knowing that up to core. This means we preventDefault() on keybinds relatively indiscriminately, having explicit carve-outs for keybinds we want to execute - such as Ctrl+Shift+I to open the browser devtools, and sending everything to core.
Sometimes, we may have keybinds which don't have a core equivalent - for example Cmd+Ctrl+Space. In this case the keybind is ignored in core and Everything Is Fine... mostly. The problem is when these bindings collide with system bindings. Cmd+Ctrl+Space happens to be the binding on MacOS to open the emoji picker... which previously never opened in Collabora Online. Another example is the MacOS minimize keybind, Cmd+M, which appeared to do nothing but was preventing a MacOS system shortcut in …
> fix(MacOS): Allow Mac users more system keybinds

- browser/src/canvas/sections/ShapeHandlesSection.ts
Issue:
* Open an Impress file.
* Add a table.
* Select more than one cells.
* While selecting the cells, table moves.
Reason:
* We check if the text cursor is visible or not before moving the table.
* But while selecting multiple cells, table gets selected and text cursor is not visible.
* So while the user is selecting the cells, dragging gets enabled.
* For determining the table selection better, we check if the deleteRows is disabled or not.
* If table is selected (not selecting the cells), deleteRows should be disabled. In that case, we can drag the table.
Change-Id: Idb3ad256534a0b96bf5f8eb73f9d4c454f338160
* Resolves: # 
> Impress: Disallow moving the table while selecting cells.

- browser/src/app/MultiPageViewLayout.ts
- browser/src/app/TilesMiddleware.ts
- browser/src/canvas/sections/PreloadMapSection.ts
- browser/src/canvas/sections/TilesSection.ts
This appears to have been comprehensively broken for a while. This commit fixes these issues:
- Tile.current should reflect whether the tile is in the visible area
- Various tile update functions were unnecessarily redrawing the screen
- Tile.hasPendingDelta and Tile.hasPendingKeyframe were not initialised
- Tile.lastRendered was not stored or updated efficiently
- TileManager.garbageCollect was not sorting tiles correctly
- TileManager.garbageCollect was not respecting highNumCanvases correctly
- Tile preload map was not visualising current or canvas-GC'd tiles
- TileManager.updateLayoutView was typo'd as 'udpateLayoutView'
Fixing garbage collection has the knock-on effect of markedly enhancing performance on 4k screens and possibly fixing some OOM situations.
> Fix TileManager.garbageCollect

- browser/src/control/Control.Menubar.js
No need to add the additional second parameter for the string (as it's
not coming from core).
regression introduce in 34b4ff6a4efc3429ecd7ecf4bfbf9ca0e1803a98 with
Mobile: spreadsheet: Allow user to define and remove print area #5882
- https://github.com/CollaboraOnline/online/pull/5882
Change-Id: Ic7f1fdcdfc2f1bfb57652a1d3559b67a21a8ec24
> Fix DefinePrintArea and DeletePrintArea name, remove bogus parameter

- fuzzer/ClientSession.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/RequestVettingStation.cpp
Change-Id: I9f542a0d4093a102c09d77f3be3cccb635d7a721
* Resolves: # 
> last arg to findOrCreateDocBroker is always null

- browser/src/control/Control.NotebookbarBuilder.js
- cypress_test/integration_tests/desktop/writer/notebookbar_spec.js
In notebookbar we have heuristic to detect when we want label for an icon and when not. We should not modify the state permanently, when we exit current context, we should recover old value.
This fixes regression from commit 61d9f6767c37f2ad163970634b9ed6cb906ce952 notebookbar: correctly setup toolbox after update
Labels in the Review tab disappeared for some icons.
> jsdialogs: notebookbar: preserve labels state when building

- wsd/DocumentBroker.cpp
```
#0  0x00007f82abc16d2b in raise () from /lib64/libc.so.6
#1  0x00007f82abc183e5 in abort () from /lib64/libc.so.6
#2  0x00000000005bf80f in Poco::SignalHandler::handleSignal(int) [clone .cold] ()
#3  <signal handler called>
#4  0x00007f82abd4dfdf in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#5  0x00007f82ac0a8a48 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib64/libstdc++.so.6
#6  0x00007f82ac09ab5d in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) () from /usr/lib64/libstdc++.so.6
#7  0x0000000000601243 in std::operator<< <char, std::char_traits<char>, std::allocator<char> > (__str="", __os=...) …
```
> extend DocumentBroker lifecycle until preset callbacks no longer need it

- browser/src/control/Control.NotebookbarWriter.js
Change-Id: I14e0bffd450253303c477c15300df6d58285c0ed
Add missing icons of formula bar.
> formula-tab: add missing icons

- wsd/COOLWSD.cpp
Change-Id: I23ddbce215d8404d8422473564460a2501aeadb7
* Resolves: # 
So that links in output in terminal are correct, even if path contained spaces.
> wsd: url encode file path

- browser/src/canvas/sections/PreloadMapSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
In quick testing, this seems to work well - GC is restored and 4k performance is much better because of it (not to the level it is in master, but much better). Presumably there's also a much lower chance of being OOM-killed :)
We need to watch out for tile invalidation issues this may cause. I haven't immediately spotted anything, but despite the tiny size, this isn't a low-risk patch (though at least it's easy to revert).
> Fix garbage collection in 24.04

- common/TraceEvent.cpp
- kit/KitWebSocket.cpp
Logging was confusing about whether this was the parent kit or the child process - so fix that.
Also there is a tiny subset of messages that make sense to accept from bgsave, avoid propagating some that came after saving and made no sense eg. viewcursorvisible and contentcontrol.
By changing from accept by default to deny by default improve future robustness.
Change-Id: I566e96141a4bcae2b51e5745fbe421acc2fff69f
* Resolves: # 
> Better filtering of bg save messages and logging.

- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/src/control/Control.StatusBar.js
- browser/src/control/jsdialog/Util.ScrollableBar.ts
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/bottom_bar_spec.js
- cypress_test/integration_tests/desktop/calc/statusbar_spec.js
Change-Id: Ied57f580bc7c1ea5d488e935f5f906f0935bd3cf
[Screencast from 25-03-25 04:40:39.webm](https://github.com/user-attachments/assets/199992d7-fbc2-4032-97a5-abb1f9bc7544)
- Removes the left and right arrows from the status bar to address inconsistencies after removing default states.
- The arrows also block the Zoom "+" which is frustrating to users as they would need to double click the arrow to remove it and click zoom +
> status bar: remove right and left arrows

- cypress_test/integration_tests/desktop/writer/navigator_spec.js
this allow to not break CI while merging the left-side sidebar
> cypress: skip navigator tests

- common/Clipboard.hpp
- common/ConfigUtil.cpp
- common/Message.hpp
- common/Util.hpp
- kit/ChildSession.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- net/Socket.cpp
- net/Socket.hpp
- test/Makefile.am
- test/UnitWOPIStuckSave.cpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/SenderQueue.hpp
- **wsd: return an array for hex conversion**
- **wsd: simplify Message::contains()**
- **wsd: replace single-use vectorAppendHex**
- **wsd: avoid copying the clipboard when dumping**
- **wsd: dump the total socket buffer size**
- **wsd: better state dumping**
- **wsd: use chrono for limit_load_secs**
- **make: shorter unit-test run time**
- **wsd: stop early when the shutdown flag is set**
- **wsd: skip empty config entries**
- **wsd: avoid duplicate state dumping with unit-tests**
- **wsd: flush thread-local log buffer on idle polling**
> Better Dumping And Reduced Noise

- kit/ChildSession.cpp
a problem since:
commit 2178f959e775afe7f430b9bef9e2c19a0a1caf6c
CommitDate: Mon Mar 31 16:24:10 2025 +0100
wsd: replace single-use vectorAppendHex
Luckily, it's a single liner.
Change-Id: Ia6b41aa637bf03d5b11c51cc31cd022b4e0b621b
* Resolves: # 
> clipboard length should be number encoded as hex

- browser/src/app/TilesMiddleware.ts
- browser/src/canvas/sections/PreloadMapSection.ts
Tiles were previously GC'd based on their last render time, which was generally inaccurate. Instead, GC them based on their distance from the visible area (including split panes).
> GC tiles based on their distance from the visible area

- browser/src/app/TilesMiddleware.ts
- browser/src/geometry/Bounds.ts
This set of changes makes it so that pre-fetched tiles are not immediately decompressed and the 'current' area (which will be decompressed) is expanded around the visible region. The intended change in behaviour is that tiles that are necessary for a consistent feeling experience are prioritised and not considered for GC, and we don't waste so much worker time decompressing tiles that may never be seen.
This can increase memory pressure on 4k screens as it will maintain all on-screen tiles and the expanded area tiles (currently set at 2 tiles around the visible region). I think this may be necessary long-term, but have some ideas to mitigate this. I'm also going to look at prototyping use of ImageBitmap instead of canvas for tiles, which ought to significantly reduce resource pressure …
> Improve tile prefetch behaviour

- wsd/ContentSecurityPolicy.hpp
- wsd/FileServer.cpp
This in addition to the deprecated 'net.frame_ancestors'
Add a new ContentSecurityPolicy constructor from string.
Add a new ContentSecurityPolicy::merge() from a ContentSecurityPolicy
Change-Id: I89c02d820bd4d4bfc6ae7de6ebf75970997822c2
* Resolves: # 
> wsd: Set window.frameAncestors with the CSP directive

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: I14ef4d05a88d1ae991673bbefc6f7322e1094bfc
* Resolves: # 
When we open the admin page, we keep getting a "shared config URL is missing" error because we bundle everything into the admin bundle, so we have prevented calling it unless it is actually the settings iframe page.
> fix: prevent unintended SettingIframe initialization on non-iframe pages

- browser/src/app/TilesMiddleware.ts
- browser/src/canvas/sections/PreloadMapSection.ts
This can reduce flicker by ensuring we de-hydrated by the time we get to the content.
Change-Id: I1b3952102ca0c394b0a907cfb52cc007df9ee226
* Resolves: # 
> Skew pxBounds tile range growth in the direction of travel.

- clang/test/refcounting.cpp
- wsd/COOLWSD.cpp
- **coolwsd --clean: don't produce error output on success**
- **clang, test: cover SocketPoll subclass check**
> clang, test: cover SocketPoll subclass check

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
- browser/src/map/handler/Map.WOPI.js
* Show no errors when Hide/Show_Command, Hide/Show_Button and Hide/Show_Menu_Item found an item to show/hide
* Set id for Sidebar Menu entry
Change-Id: I38c83cc8c6563e61a00c6b52ecc7366824b0e4a4
* Resolves: # 
To allow to hide the Sidebar using Hide_Button with the same "id" as used in the notebookbar in the compact style.
And have errors messages only when a button, menu or toolbar entry was not found.
> Improve Hide/show Menu_Item Command and Button errors

- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
if there are no ssl certs and a fatal exception is thrown.
FTL  Failed to initialize COOLWSD: File not found: /tmp/ssl/certs/ca/root.crt.pem| wsd/COOLWSD.hpp:268
File not found: /tmp/ssl/certs/ca/root.crt.pem
Change-Id: I0d8ecb10ae17034be554e3f54fd0028c9c2705f8
* Resolves: # 
> don't crash after FTL unable to initialize ssl scenario

- browser/src/app/TilesMiddleware.ts
- browser/src/canvas/sections/PreloadMapSection.ts
- browser/src/canvas/sections/TilesSection.ts
- browser/src/layer/tile/CanvasTileUtils.ts
- browser/src/layer/tile/CanvasTileWorkerSrc.js
Instead of using canvas elements as a tile image backing store, use ImageBitmap. As ImageBitmap is a light wrapper around graphics memory, this has the benefit of reducing resource usage, simplifying the code and dramatically improving performance.
> Replace Tile canvas backing store with ImageBitmap

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.TreeView.ts
Change-Id: I5a552903e9349fa8cd87c4c0f2d8a642674e51d8
Enable tooltip for style list
> widget-treeview: enable tooltips to Styles deck tabs

- kit/KitQueue.cpp
The expression `tileQueue.begin() + leftTile + 1` can be compiled so that `tileQueue.begin() + leftTile` is evaluated first. (Or should that always happen, isn't the + operator left associative?) When leftTile is -1 that is obviously problematic. Use parens to make sure that `leftTile + 1` is evaluated first.
Change-Id: I47720f16832a9fabfb718c09fa5e793fe1462df3
* Resolves: # 
> Avoid potentially seeking before begin() of iterator

- wsd/COOLWSD.cpp
from --with-infobar-url feature:
[ asyncdns ] WRN Waking up dead poll thread [main], started: false, finished: false| net/Socket.hpp:830
[ coolwsd ] WRN  Waking up dead poll thread [main], started: false, finished: false| net/Socket.hpp:830
Change-Id: I23cd2981d70abf4d57907614eb9adf66926828fd
* Resolves: # 
> silence worrying 'Waking up dead poll thread [main]' warning

- wsd/wopi/WopiStorage.cpp
It's rather common to get various errors,
including timeouts, when making lock-refresh
requests. We shouldn't consider these as
"unauthorized" responses.
This patch limits the invalidation of the
user's access token to responses that
are specifically authorization-related
and not for other unrelated failures.
Change-Id: I50e5e2449f129dd811b2f8defe5fb3cd57897339
> wsd: invalidate the token only for authorization failures

- wsd/COOLWSD.cpp
- wsd/QuarantineUtil.cpp
When the quarantine path is invalid or read-only,
the issue remains hidden and hard to debug.
This validates the path and exists with
a fatal error when it's either invalid or
inaccessible (no write permissions), giving
the user immediate feedback to allow them
to fix the issue (or disable the feature).
Change-Id: Ifbde1cea4594ac3c9f9fc92810a41813fef0b69f
> wsd: do not start the service with invalid quarantine path

- browser/src/control/Control.MobileWizardBuilder.js
fix(soundness): Correct typeof comparison
Previously we were comparing typeof to `undefined`, however this is
invalid: typeof never evaluates to `undefined` as it is always a string.
The correct value should probably be the *string* `'undefined'`, so as
to make the expression this:
var charCode = (typeof e.which === 'undefined') ? e.keyCode : e.which;
However this is still a bit of a weird expression - using typeof here is
unnecessary and it would be more normal to write the equivalent:
var charCode = e.which === undefined ? e.keyCode : e.which;
I wanted to refactor this to use use the nullish coalescing operator,
which is equivalent as e.which will never be null, however our
javascript package versions are not high enough to parse this (despite
it being MDN baseline):
var charCode = …
> fix(soundness): Correct typeof comparison

- browser/css/btns.css
- browser/css/jsdialogs.css
All active buttons have already a background that is different than its
container so, better to set the bg transparent for the hover
state. This way, the background of the container doesn't matter and
the disabled button will always look disabled.
Before this commit, we were setting the background of the button as
the same background of the container:
- the problem is, we have different containers (sidebar, dialogs)
- and when integrator has a different background in
the sidebar, the disabled button would actually be emphasized, looking
more active and disabled.
Another alternative would be to set additional rules, targeting dialog
and then the sidebar, which seems less elegant.
Change-Id: …
> Menubutton: don't set background for disabled buttons

- net/HttpRequest.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/PresetsInstall.hpp
- wsd/RequestVettingStation.cpp
A minimal backport of https://github.com/CollaboraOnline/online/pull/11411 that only changes the presets async install case and leaves other uses of HttpRequest::asyncRequest untouched
Earlier effort of https://github.com/CollaboraOnline/online/pull/11421 is useless, that just keeps the poll alive until _asyncInstallTask is destroyed which doesn't help
```
#3  <signal handler called>
#4  __memcpy_ssse3 () at ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2942
#5  0x00007f2d26fb8478 in std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007f2d26fa8b84 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> …
```
> abandon preset install if required poll is destroyed

- browser/src/map/handler/Map.Welcome.js
- wsd/ClientSession.cpp
- we tokenize messages in ClientSession with ' ' as delimeter. If message has extra spaces the json parsing will break
- this patch replaces ' '(space) in date string with '-' when sending setting `WSDWelcomeDisabledDate`. Also replaces '-' with ' '(space) when getting the preference
Change-Id: Ie903bd2f3c13c151029de9a262f8ec5261744311
* Resolves: #https://github.com/nextcloud/richdocuments/issues/4598. This patch fixes the underlying issue where `WSDWelcomeDisabledDate` preference can't be uploaded.
> browsersetting: fix: failed to update `WSDWelcomeDisabledDate`

- browser/css/jssidebar.css
This - "justify-self: end;" - seems to be an old declaration when we
were attempting fixing alignments by incorrectly aligning everything
to the right -> remove it.
for the majority of ".sidebar.ui-grid.ui-grid-cell .menubutton" that
declaration was rendered inactive (for menu icon buttons) but for the
dropdown (color widget) it was active, resulting in misalignment
1. Open a presentation file
2. Open sidebar
3. In the slide section set the background dropdown to color
4. Notice the misalignment
Change-Id: I2dc569f008bc4cad63a29469d81bfd36d7b9c7c7
> Sidebar: fix color widget dropdown alignment

- browser/src/layer/tile/CalcTileLayer.js
In some case - when cell have background color and text color - it can
be hard to see the content.
Follow up:
Ideally we would also change the lateral lines to match the same css
var ('--column-row-highlight') or a
new ('--column-row-highlight-border') but I couldn't figure out a way
to do it elegantly.
I do see the possibility to change for the whole Calc:
@@ -3919,7 +3919,7 @@ L.CanvasTileLayer = L.Layer.extend({
if (this.isCalc()) {
var cursorStyle = new CStyleData(this._cursorDataDiv);
var weight = cursorStyle.getFloatPropWithoutUnit('border-top-width') * app.dpiScale;
-			var color = cursorStyle.getPropValue('border-top-color');
+			var color =
getComputedStyle(document.documentElement).getPropertyValue('--column-row-highlight');
Which it would be nice to do it so, we could use …
> Focus cell: reduce opacity

- browser/css/jssidebar.css
Before this change, the daRatioTop images was forced to be at huge
300px size.
The 300px was introduced in 07bbf1d38f6d18d383fd1c71bc47e0f1ca38bc5b
to make sure that the Master slide thumbnails do not get cropped, at
that time we didn't have things like daRatioTop
Change-Id: Idcf73ef59bcf2dcc44cda43b8b116506c324f448
> Sidebar: ui-drawing-area: avoid hard coded pixels

- browser/src/map/handler/Map.Welcome.js
- wsd/ClientSession.cpp
- we tokenize messages in ClientSession with ' ' as delimeter. If message has extra spaces the json parsing will break
- this patch replaces ' '(space) in date string with '-' when sending setting `WSDWelcomeDisabledDate`. Also replaces '-' with ' '(space) when getting the preference
Change-Id: Ie903bd2f3c13c151029de9a262f8ec5261744311
> browsersetting: fix: failed to update `WSDWelcomeDisabledDate` (backport)

- wsd/COOLWSD.cpp
- wsd/QuarantineUtil.cpp
- wsd/wopi/WopiStorage.cpp
- **wsd: invalidate the token only for authorization failures**
- **wsd: do not start the service with invalid quarantine path**
> Backports to 24.04

- browser/src/canvas/CanvasSectionContainer.ts
Seems we have a rather large number of re-renderings for no good reason on simple operations.
Change-Id: Ifbc8577f9e349fdd08f95cd4e375771c49e319ba
A tad embarrassing  eg. pressing 'down arrow' in a cell in calc gives five back to back drawSections renders - or oddly, fewer depending on where you are in the sheet (weird) ;-)
Anyhow - showing the problem is helpful I hope.
> Add a frame count to the debug overlay.

- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/canvas/sections/ScrollSection.ts
Touchpad scrolling was immediately redrawing the screen on every event. Fix this by storing the scroll delta and deferring redraw until a requestAnimationFrame callback.
> Fix touchpad scrolling causing uncapped drawing

- common/Unit.hpp
- net/AsyncDNS.hpp
- net/HttpRequest.hpp
- net/NetUtil.cpp
- test/Makefile.am
- test/UnitUserPresets.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
add test for presets not installed yet at doc dtor time
The DocBroker can be created, launch presets to be installed async, and
then destroyed before the presets complete.
If async dns was still handling a dns lookup on behalf of
net::asyncConnect for http::Session::asyncConnect to attempt to install
a preset when the DocBroker was destroyed, then the SocketPoll of the
DocBroker was already destroyed when the pushConnectCompleteToPoll
lambda of http::Session::asyncConnect was called and then attempted to
use addCallback on the destroyed SocketPoll of the DocBroker.
This test successfully triggers:
[ asyncdns ] WRN  #20: asyncConnect completed after poll was destroyed| net/HttpRequest.hpp:1755
while with:
commit eebf9268ef8e83103fe1f32d7cb1b23a4c7d51d5
CommitDate: Wed Mar 26 16:34:03 2025 …
> test for presets not installed yet at doc dtor time

- kit/ChildSession.cpp
- wsd/DocumentBroker.cpp
This fixes below bug:
- Open Impress
- Edit textbox but do not accept it by pressing Enter
- Click Save
- Exit Presentation
Result: file doesn't have edits typed to the textbox
Expected: no data is lost, content was autosaved
The behavior is caused by the background save which got null parameters so we didn't support DontTerminateFlag
or DontSaveIfUnmodified for example. Missing DontTerminateFlag wasn't considered as: please terminate editing in the core. It has to be explicit false to force it. So far it was used in Calc but I also prepared Impress support for it: https://gerrit.libreoffice.org/c/core/+/183652
In case of background save it can be ignored and set to false because it doesn't impact user session (it's a fork).
> save: pass args also for background save

- browser/css/jssidebar.css
Already being set in #sidebar-dock-wrapper, #navigator-dock-wrapper
Change-Id: Id0220e7254eb788d83e662569cbecc971122f8d6
> Navigator: remove duplicated background-color

- net/HttpRequest.hpp
- wsd/DocumentBroker.cpp
avoid confusion on reading net/HttpRequest.hpp on seeing two "Session" classes
Change-Id: Ie6685cff58722f6e966f71670c7fd12de7a151ed
* Resolves: # 
> rename server::Session to ServerSession

- cypress_test/integration_tests/mobile/writer/annotation_spec.js
Mobile wizard sometimes still uses old refresh-all signal. That may cause button to disappear and be recreated so check before click to avoid using detached element.
> cypress: make mobile writer/annotation_spec.js more stable

- net/Socket.cpp
- net/Socket.hpp
"main" poll runs on client thread, as in it doesn't use its own thread, so COOLWSD::processFetchUpdate triggers
assert(!_runOnClientThread) in SocketPoll::startThread since
commit 3cd36f1236c165c4bf1c1af769bf86b5fb2ec711
CommitDate: Mon Apr 7 21:09:09 2025 +0100
use SocketDisposition to transfer Socket to SocketPoll
because SocketDisposition::execute unconditionally calls startThread
Change-Id: I3031f67007c2221f7d3adcd0b2f9e8c1bc7ad887
* Resolves: # 
> processFetchUpdate triggers SocketPoll::startThread assert

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
Before this commit items in Navigator were being indented on a
parent level making the entries not interactive in the left most edge
(click and mouse hover was hitting the container and not the entry)
Change-Id: I60ccdde7adcbb0f1901bc0aa345f1093bf6bbce7
> Navigator: full width treeview entries

- browser/src/app/TilesMiddleware.ts
TileManager.pixelCoordsToTwipTileBounds needs to take into account app.dpiScale.
> Fix invalidation when dpiScale is not equal to one

- browser/src/control/Control.ESignature.ts
availableProviderIDs doesn't have to be a member since commit
4d42b1e3e47ad0183649678d2aa931b44c5ffe10 (cool#10630 doc electronic
sign: return dialog result without an index, 2024-12-17).
availableCountryCodes was write-only since the same commit.
And fix the remaining lints in the file, so strict mode can be enabled
here.
Actual esign with the config from
<https://github.com/CollaboraOnline/online/issues/10630#issuecomment-2606548860>
continues to work.
Change-Id: I55a023261bc51f69150426c6fdb4fa8a5dc4f777
> esign: clean up two unused members in ESignature

- net/HttpRequest.hpp
Change-Id: I814cc1d584cfc2cdd0612bcd118f1473ff532a1c
* Resolves: # 
> disconnect methods of Session/ServerSession are unused

- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- wsd/COOLWSD.cpp
- wsd/ProxyProtocol.cpp
Add ASSERT_CORRECT_THREAD checks to methods of ProtocolHandlerInteface api (avoiding getIOStats called by dumpState)
Merge Socket::InhibitThreadChecks and SocketPoll::InhibitThreadChecks as ThreadChecks::Inhibit (both are always toggled together) and reuse that for this.
Make Socket setThreadOwner/resetThreadOwner protected and virtual so StreamSocket can override and additionally call the protocolHandler equivalents.
Set a ProtocolHandlerInterface's threadowner to that of the owning StreamSocket in StreamSocket::setHandler
> merge SocketPoll::InhibitThreadChecks and Socket::InhibitThreadChecks

- common/Session.cpp
- common/Util.hpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- net/HttpRequest.hpp
- net/Socket.cpp
- test/KitQueueTests.cpp
- test/UnitCopyPaste.cpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/ProxyProtocol.cpp
- wsd/Storage.hpp
and
cid#318944 Not restoring ostream format
cid#410823 Not restoring ostream format
cid#410831 Not restoring ostream format
cid#427992 Not restoring ostream format
cid#516981 Not restoring ostream format
drop setting std::boolalpha in individual dumpStates and instead add a makeDumpStateStream which creates a std::ostringstream to dump to, which already has boolalpha set by default
ClientSession::loadDocument is a different case, a short lived std::ostringstream, just move the std::boolalpha to when its created.
Change-Id: I543fd819b8c7cfdd42f3ba13b6a689b316d6be68
* Resolves: # 
> cid#318913 Not restoring ostream format

- wsd/DocumentBroker.cpp
so we got:
uno command .uno:Save {"DontTerminateEdit" : { "type":"boolean", "value":false }"DontSaveIfUnmodified" : { "type":"boolean", "value":true }}
instead of
uno command .uno:Save {"DontTerminateEdit" : { "type":"boolean", "value":false },"DontSaveIfUnmodified" : { "type":"boolean", "value":true }}
since:
commit d851318a86b515a9c7c39a89c60a9b7680f4b411
CommitDate: Tue Apr 8 09:18:32 2025 +0200
save: pass args also for background save
which always outputs DontTerminateEdit of true/false now so we always need the separator if there is DontSaveIfUnmodified
Change-Id: Ie66068d2b79d2cf17c4fba9bc3dd0050e47135a1
* Resolves: # 
> Missing "," seperator in json save message

- browser/src/control/Control.ESignatureDialog.ts
This fixes the remaining lints in the file, so strict mode can be
enabled here.
Change-Id: I36c2da6b3348eade4407bde60299468ec973d86b
> esign: fix missing member initializers in ESignatureDialog

- browser/Makefile.am
- browser/src/app/LayoutingService.ts
- browser/src/app/LocaleService.ts
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/docstate.js
- browser/src/main.js
- cypress_test/integration_tests/common/writer_helper.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
- cypress_test/integration_tests/desktop/writer/file_properties_spec.js
When we open big dialogs like eg. Format -> Character we first get the full dialog and then series of updates. We touch DOM a lot by replacing some nodes and layouting the content.
Let's create a queue which will collect them and flush at once.
Use DocumentFragment when we build widget to not insert directly into real Document.
Setup number formatting only once, not on every builder creation.
BEFORE (open Character dialog):
Related to issue  #11124
All the layouting happens now in the seaparate task. JS for building dialog is shorter.
> jsdialogs: slurp also widget updates

- test/UnitWOPIHttpRedirect.cpp
so we don't call initWebsocket multiple times once the first is launched.
Change-Id: I2418cdb660b3cd46ec3d09cbc777387f84b0e674 (cherry picked from commit 78a6e3c873a98d6a9e0081634f600d4014d57809)
* Resolves: # 
> add a WaitLoad phase to this test

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.MenuButton.js
Change-Id: Ic71df7415075523c841194902b0f7f1a6177b6b8
> browser: accessibility: add 'aria-disabled' attribute

- browser/admin/src/integrator/WordBook.ts
Change-Id: I1df6ca6287fdf34e26f4ee5ac8942c1ab762eaa6
* Resolves: # 
> fix(regression): disable 'Add' button for duplicate words in wordbook

- browser/src/control/Control.JSDialogBuilder.js
Accessibility request to remove "label for" elements for button
Change-Id: Ief83bb73f6befbe39097de3e6aa550d58fd04de5
> browser: jsbuilder: replace button label for span element

- browser/src/control/jsdialog/Widget.TreeView.ts
Change-Id: Ib89dd448bf583bff4fb385e10c0eae51eed0ce96
Prevent setting a tooltip attribute if there is no text available, which was producing an "Undefined" tooltip in some scenarios (e.g., formula suggestions).
> TreeView: Add check for tooltip text before setting attribute

- ios/Mobile/CoolURLSchemeHandler.mm
Previously we would send a ranged media request whether the server
requested it or not. This is incorrect, and can be skipped pretty easily
by just missing out the header.
I do not know of a time when Safari will avoid sending a range header
for media, but it is technically possible and I know that Safari does
require the right type of response in some cases.
Change-Id: I012c3295101e0bea675d5d05af929c006082abb8* Resolves: # 
> fix(iOS): Correct unranged multimedia response

- browser/css/jsdialogs.css
Example: Calc -> Format Cells: Font tab VS Western, Asian, Complex sub
tabs
Before this commit the sub tabs (e.g.: "Western", "Asian", "Complex")
could be confused and perceived as top level tabs. Plus the fact that
"Western" controls only the left part and "Asian/Complex" controls the
right part could have been more clear.
- Increase spacing: to increase the difference between levels
- Add border to emphasize ^ and to help distinguish which part of the
dialog the sub tabs control
Change-Id: I04b4e04682c7d9d143ded2bcd9ef145c2d31935a
> Dialogs: Emphasize difference between tabs and sub tabs

- android/lib/src/main/cpp/androidapp.cpp
- android/lib/src/main/java/org/libreoffice/androidlib/COWebView.java
- android/lib/src/main/java/org/libreoffice/androidlib/COWebViewClient.java
- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- browser/src/map/handler/Map.SlideShow.js
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/VideoRenderer.ts
- ios/Mobile/CoolURLSchemeHandler.mm
- kit/Kit.cpp
- kit/Kit.hpp
- wsd/ServerURL.hpp
This is the android counterpart to #11214 
There's a few things I'm unhappy about here...
- Slideshow doesn't close when android back gesture is used - instead the whole document closes
- It's pretty annoying to have video in presentations - it starts as soon as it loads, can't be paused, and loops at the end. We could do much better
- ~~I'm fairly sure the *iOS* protocol handler code is unsound - see what happens when you don't provide a range (-> this never happens on iOS, but might be easy to fix), the end variable is redundant earlier on ... - and needs to be fixed~~ I've determined that these problems never happen in a real case, so decided to strike them from this PR... I'll make another PR tweaking a few things that are Wrong code
- ~~I would like to Just Refactor The Range Header …
> feat(android): Support loading video

- browser/src/layer/tile/CanvasTileLayer.js
Arrow-down in a spreadsheet with split-panes is now smooth not jerky for me at least.
Change-Id: If9662826a959476564740251a5dac40e9e2d47a7
* Resolves: # 
> cool#11649 - avoid triggering re-draws on key-press with split-panes.

- browser/src/control/Control.JSDialogBuilder.js
- Added aria-expanded attribute toggle to reflect expanded/collapsed state.
- Improves accessibility for keyboard and assistive tech users
Change-Id: I2ef563417c6f510c8c417880c45faa535a5068ad
* Resolves: # 
> Added toggle expander state with aria-expanded for a11y

- scripts/run-wsdunit
One way to investigate an unstable test is to have logs for both a
failing and passing case. If it takes several tries to find a passing
case, then this new mode can help, so if you run a test 10 times, then
it won't overwrite a passing run with a next, potentially again failing
run.
Change-Id: I22fe78016021ea4308db2b7d0dc4f484b06a6a82
> run-wsdunit: add a mode that stops on first success

- common/SigUtil.cpp
- common/SigUtil.hpp
- kit/Kit.cpp
- kit/KitWebSocket.cpp
Memory operations are not safe from
signal handlers as they can lead to
dead-locks. The zombie reaping logs
and to generate log entries, strings
are created, which allocate.
This has indeed been observed:
#0  0x00007f6415ca187c in __lll_lock_wait_private () from /lib64/libc.so.6
https://github.com/CollaboraOnline/online/pull/1  0x00007f6415c1dba2 in _L_lock_16654 () from /lib64/libc.so.6
https://github.com/CollaboraOnline/online/pull/2  0x00007f6415c1a7e3 in malloc () from /lib64/libc.so.6
...
https://github.com/CollaboraOnline/online/pull/7  0x0000000000729727 in std::string::_S_construct<char const*> (__beg=__beg@entry=0x7ffdf02654b0 "kit-43991-43991 2025-04-14 12:50:32.942788 +0000 [ kitbroker_003 ] TRC  ", __end=<optimized out>, __a=...) at …
> wsd: support reaping zombies safely on SIGCHLD

- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Non-functional changes to de-duplicate Lock result handling and unify sync and async paths, with some logging improvements.
The commits try to minimize the diffs to make reviewing easier.
- **wsd: make updateStorageLockState similar to the async version**
- **wsd: extract handleLockResult**
- **wsd: deduplicate lock result handling**
- **wsd: no Hungarian notation**
> De-Duplicate Lock Result Handling

- dev-notes/socket-ownership.md
A pair of underscores results in italics, unpaired underline is a syntax
error, so quite all of those using backticks. Also fix a typo.
Change-Id: If2f1927d35b2803fc95a85744227703191defa5e
> dev-notes: fix markup in socket-ownership.md

- browser/src/control/Control.DownloadProgress.js
had error:
```
Uncaught TypeError: Cannot read properties of null (reading 'focus')
at NewClass.setupKeyboardShortcutForDialog (Control.DownloadProgress.js:151:36)
at NewClass._showLargeCopyPasteWarning (Control.DownloadProgress.js:71:9)
at NewClass.show (Control.DownloadProgress.js:174:9)
at NewClass._startProgress (Clipboard.js:1230:26)
at NewClass._onDownloadOnLargeCopyPaste (Clipboard.js:1239:9)
at NewClass._getHtmlForClipboard (Clipboard.js:535:10)
at NewClass.populateClipboard (Clipboard.js:552:19)
at NewClass._doCopyCut (Clipboard.js:1111:10)
at NewClass.copy (Clipboard.js:1142:35)
at document.oncopy (Clipboard.js:82:49)
```
> Fix download progress after async JSDialog

- wsd/SpecialBrokers.cpp
- wsd/SpecialBrokers.hpp
this Socket belongs to the DocumentBroker poll.
Change-Id: I582d3a4c0659324cdb814f9b4cdf5d1d644013cd
* Resolves: # 
> hold weak_ptr of StreamSocket in RenderSearchResultBroker

- browser/src/control/Control.UIManager.ts
Fixes regression from commit 1c3e2bffbfa059a0bf2732bdfa182c4b36aa7a68 jsdialog: allow no titlebar for formula usage popup
Before:
> Idle popup shouldn't have titlebar

- kit/ChildSession.cpp
appending string to json argument caused json to become invalid and entire command was not executed
Change-Id: I7e22b89022ef91fbe1db3eda52f210e7e65852e2
> zotero: fixed citation style not being saved

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- cypress_test/integration_tests/desktop/writer/jsdialog_widgets_spec.js
- cypress_test/integration_tests/desktop/writer/navigator_spec.js
We have more animated elements now in the UI, this PR frinds fade-in effect for dialogs to make the appearing less "sharp". This especially matters for large dialogs which load embedded tabs later and do a blink. Thanks to animation it is not visible now.
Toghether with previous DOM layout sync in JSDialogs it reduces flicker and "moving elements" around the screen while loading dialogs and popups.
> jsdialog: fade in dialogs

- browser/src/canvas/CanvasSectionContainer.ts
related to https://github.com/CollaboraOnline/online/issues/11124
If we already do a canvas animation frame - process also other tasks we gathered (to the end) and cancel scheduled LayoutingService frame.
Merged this way as agreed with Gokay, thinking was:
1. canvas rerender may happen on document content change
2. layouting service may happen on document content change or just dialog change
so in case 2. we possibly don't need to rerender canvas, let's then just do the tasks from layouting service,
canvas will request frame if needed
> LayoutingService: flush with canvas frame

- browser/src/canvas/sections/ShapeHandlesSection.ts
Previously, we could upload any multimedia files (video or audio-only) but audio files would show an "unsupported video" warning when played in the editor in Chromium-based browsers.
That turns out to be because we test for "video.webkitDecodedFrameCount" which is a Chromium-specific property to see whether any video frames have been decoded. If the property exists and is 0 we assume that, since as no video has been decoded, the file is corrupted or unsupported. As audio doesn't have any video frames to decode, we will always see it as undecodeable and therefore always corrupted.
To fix this we can check webkitAudioDecodedByteCount to see if we have decoded any audio. Since as some videos can have no audio track we still need to check video as well, however corrupted or unsupported videos …
> fix: Remove unsupported warning on audio multimedia

- wsd/DocumentBroker.cpp
we check session for null/empty everywhere else
Change-Id: I4853fbeda7d952eb9745e8114c9367d36dd43460
* Resolves: # 
> cid#362805 Dereference after null check

- wsd/COOLWSD.cpp
As of Id6d9e7bbfce7c750e4c7fc19f51bd795d7571103, "Don't store Socket in a non-SocketPoll Object", we were attempting to getFD from an already moved socket when starting COOLWSD on mobile. This caused a crash due to invalid memory access.
Refs: #11622
Change-Id: I82b0df8690db463946cd7b8460a849762216181f
* Resolves: # 
> fix(mobile): don't attempt to use after move

- config.h.in
- ios/config.h.in
- kit/Kit.cpp
- net/Socket.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/RequestVettingStation.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd/wopi/WopiProxy.cpp
Excludes local filesystem storage at compile-time and replaces many MOBILEAPP directives.
Requires #11699 to build.
- **wsd: reduce ifdef MOBILEAPP in Socket.hpp**
- **wsd: exclude filesystem storage when unnecessary**
- **wsd: reduce ifdef MOBILEAPP in DocumentBroker**
- **wsd: linearize implementation of DocumentBroker::getJailRoot()**
- **wsd: reduce ifdef MOBILEAPP in DocumentBroker**
- **wsd: refactor DocumentBroker::getAbsoluteMediaPath()**
- **wsd: reduce ifdef MOBILEAPP in Kit.cpp**
> Reduce Compiler Directives

- browser/src/canvas/sections/CommentSection.ts
By default DOMPurify will strip all targets, so set everything as target=_blank with rel=noopener
See:
https: //github.com/cure53/DOMPurify/issues/317
https: //github.com/cure53/DOMPurify/blob/main/demos/hooks-target-blank-demo.html
Change-Id: I10dc8fd25db23bb55c0d805ecd11718e828361ee
* Resolves: # 
> '_blank' target stripped during sanitize

- browser/src/control/Control.JSDialog.js
- fixes snackbar interaction
- creation was in the task but not closing, when it happened too quickly - we didn't get correct dialog to close
> jsdialog: close in layouting task

- browser/src/canvas/CanvasSectionContainer.ts
When canvas is being resized larger, clear it first to avoid showing black in the newly exposed area.
> Clear canvas when resizing to a larger size

- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/SlideCompositor.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/VideoRenderer.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
Previously we gave the user no control at all over video playback - although these aren't full player controls, they should at least make it a bit nicer to use video in presentations.
We probably want some visuals for these ... things like darkening the video frame when we're paused, showing a paused icon, showing a play icon when the video has loaded, showing a spinner when the video is loading, showing a replay button at the end of the video, etc. ... consider it a followup :)
Additionally, and from what I said at the start of this PR message you might've guessed this, it would be really nice to have full player controls! A seek bar/going back and forwards is a big one, as is volume. Other than that, a restart button, some play time indication, etc. would be very nice too! Probably …
> feat(video): basic playback controls

- browser/src/layer/tile/CanvasTileLayer.js
when closing the COOL I saw unhandled exception:
TypeError: this.stopUpdates is not a function
that function doesn't exist in the current code base:
https://github.com/search?q=repo%3ACollaboraOnline%2Fonline%20stopUpdates&type=code
> canvas: remove not exising function call

- net/Socket.cpp
- net/Socket.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
Reorganize so that the SocketPoll remains in the sole ownership of its current SocketPoll until it can be transferred to ownership of the DocumentBroker SocketPoll.
With parallel CheckFileInfo it might not be possible to create the DocumentBroker, and transfer ownership of the Socket to its poll, at the ideal ClientRequestDispatcher::handleClientWsUpgrade opportunity.
If so, wait until the CheckFileInfo results are available before creating the DocumentBroker and doing the Socket transfer to its SocketPoll.
Add a method to ProtocolHandlerInterface (similar to checkTimeout) to enable a ProtocolHandler to trigger a transfer of Socket via the usual SocketDisposition mechanism, which ClientRequestDispatcher can use to execute the transfer in the delayed CheckFileInfo result case.
Change-Id: …
> Don't share ownership of Socket with RequestVettingStation

- clang/plugin.cpp
Change-Id: I2e3dd88b3ca6122de18cd0ed154ae34b821e91d5
Implement requirement from caolan:
We've bootstrapped some rough notes on the "Socket" class in online
where we basically want to set a claim along the lines that only
"SocketPoll" should have std::shared_ptr<Socket> as a member and that
everything else should have std::weak_ptr<Socket> of those[1].
https://github.com/CollaboraOnline/online/blob/master/dev-notes/socket-ownership.md
And the question is if there is a possibility to express something like
those rules as a clang plugin? (there is an existing clang plugin in
online FWIW)
[1] Though I'm sure there will be exceptions.
> plugin: enforce Socket shared_ptr semantics

- wsd/wopi/WopiProxy.cpp
uriPublic capture is unused
Change-Id: I9cf43eff985db2e1edb652f4e7f936ae74f4f5c5
* Resolves: # 
> cid#360698 Big parameter passed by value

- fuzzer/HttpEcho.cpp
- kit/ChildSession.cpp
- test/UnitProxy.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/ProxyRequestHandler.hpp
- wsd/RequestDetails.hpp
- **wsd: c-string -> string_view in RequestDetails**
- **wsd: cleanup ClientRequestDispatcher::handleWopiAccessCheckRequest()**
- **wsd: factor out conversion aborting**
- **wsd: abort conversion on save-as errors**
> Better Conversion Failure Handling

- common/Unit.hpp
- wsd/ClientRequestDispatcher.cpp
Only explicitly used in UnitProxy.
Change-Id: Iac9c787458dbd257ed3ef0552a4a6c39049fe0e9
* Resolves: # 
> Don't access rating.collaboraonline.com during tests to avoid timeouts

- browser/src/app/Debug.ts
- browser/src/canvas/sections/ScrollSection.ts
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
If the coordinate is already visible, then don't scroll to that direction (x or y).
Issue:
* On Writer, it scrolls to view to (0, y) position to get to the end of the file.
* If there is a space on the left (zoomed-out), then the view is rendered non-centered.
Change-Id: I81f320ff29d1c5c84f1452e2f59935c78e929ad5
* Resolves: # 
> ScrollTo functionality is for making an object or a area visible.

- browser/admin/adminIntegratorSettings.html
- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: I898a624b7ba12b20929148b71e7e5574c141631d
* Resolves: # 
- Test translations by appending ?lang=<locale> to the URL, for example: `https://<BASE_URL>/admin/adminIntegratorSettings.html?lang=hu`
- If a matching translation bundle is available, the page will render in that locale, otherwise, it will fall back to English (en-US).
Hungarian Preview
> fix(integrator-settings): init l10n for translations

- browser/src/control/Control.JSDialogBuilder.js
Commit 1:
- Ignore disabled elements in focus traversal and move to next enabled element on keydown
- Extended keydown handler to support Shift+Tab for reverse focus traversal
- Implemented cyclic focus: Shift+Tab from first element moves focus to last
- Ensures consistent and accessible navigation across visible tab panels
Commit 2: 
A small improvement in spin field element
- added Arai-lable for Springfield element
Change-Id: I33e741f0f39c638a94513a8ee4a829febf6af89e
* Resolves: # 
> Improve keyboard navigation: add Shift+Tab support with cyclic focus behavior

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.TreeView.ts
Change-Id: Ib89dd448bf583bff4fb385e10c0eae51eed0ce96
Enable tooltip for style list in 24.04.
> Backport 11463: Enable tooltip for style list

- browser/css/cool.css
- browser/src/control/Control.UIManager.ts
- browser/src/control/Permission.js
- browser/src/docdispatcher.ts
On the edit button in the mobile view, the pencil icon has been off-center for a little while. To prevent that from happening again, we can can center it using flex rather than providing a fixed margin and position
Change-Id: Ie080a740ca8927d47be3c3bb444bea79043cb575
* Resolves: # 
> fix(mobile): Recenter pencil icon

- browser/src/slideshow/SlideShowPresenter.ts
Previously we would let videos run underneath a presentation, causing audio from the video to mangle any presentation audio.
Change-Id: I50c86b9fa68cd8ad5774eacf4df0b0fbdf0ab3d5
* Resolves: # 
> feat(impress): Pause videos when presenting

- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/admin/src/integrator/Xcu.ts
These settings change the document's settings. They are not per-view in the sense that each user has a separate "view" of the document. The settings of the session that opens the document are applied to it and affect the document regardless of the settings of sessions that later join the document. Drop the use of "View" which is somewhat ambiguous here.
Change-Id: I296c2bd738b14a044ebfb170bfddb6aad54d2ec1
* Resolves: # 
> xcu settings affect the document for all users

- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
lock the weak_ptr and use -1 if it no longer exists instead of stashing the original fd value for use as log context
Change-Id: I6c6ffccded2c6baac55aafa0940b436329ef309a
* Resolves: # 
> use Socket for log context

- wsd/RequestDetails.hpp
Change-Id: I551febbc29a5d6aed7049c2af22f6e866d365d91
* Resolves: # 
> RequestDetails::_documentURI is unused

- browser/src/docstatefunctions.js
- browser/src/layer/tile/CanvasTileLayer.js
Issue:
* Use split panes.
* Follow a view.
* Scroll down with the first view, say row 100 is behind the frozen area, 101 and below are visible.
* With the second view, type something on line 99. Line 99 seems visible on first view. But there is frozen pane there.
* So the first view won't jump to the second (followed) view's position.
This commit fixes the issue.
Change-Id: I75556a4f9350f2e8d46a3f66b2d8ae87f931ba9f
* Resolves: # 
> ScrollToPos: Take split panes into consideration.

- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/DocumentBroker.cpp
- wsd/Process.hpp
Admin::Documents are moved to _expiredDocuments when the matching real document is closed. At which point _memoryDirty won't be updated anymore so we can close the open FILE* to the removed process smaps file to release a fd, and drop the FILE buffer.
Change-Id: Ied919f6e0fe614be7ad42cc15ddca60f0a4adab2
* Resolves: # 
> close Admin::Document smaps file when document is expired

- kit/ForKit.cpp
- kit/Kit.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/COOLWSD.cpp
- **wsd: admin: stream logs instead of concatenating strings**
- **wsd: admin: docKey is an opaque ID and shouldn't be decoded**
- **wsd: admin: privatize ActiveExpiredStats members**
- **wsd: admin: clean up AggregateStats**
- **wsd: admin: cleanup AdminModel**
- **wsd: admin: constexpr**
- **wsd: normalize state dumping**
- **wsd: admin: const correctness in Admin**
- **wsd: admin: printers take ostream**
- **wsd: dump Admin metrics through dumpState**
- **wsd: admin: clean up AdminModel::notifyDocsMemDirtyChanged()**
- **wsd: admin: move AdminModel::doRemove() to re-work it**
- **wsd: admin: no need to keep expired documents around**
> Admin Improvements

- browser/css/jsdialogs.css
Backport PR: https://github.com/CollaboraOnline/online/pull/11751
- Fixed alignment issue in the manage dialog for date/time picker.
- Increased ui-listbox-container height for better visibility.
- targeted only gird elements inside AcceptRejectChangesDialog to avoid affecting other dialogs.
Change-Id: I8c36526343593329da45b557e07e9d12636975a5
* Resolves: # 
> Backport: Manage Changes Filter date/time picker needs alignment

- kubernetes/helm/collabora-online/templates/nginx-deny/configmap.yaml
- kubernetes/helm/collabora-online/templates/nginx-deny/deployment.yaml
- kubernetes/helm/collabora-online/templates/nginx-deny/ingress.yaml
- kubernetes/helm/collabora-online/templates/nginx-deny/service.yaml
- kubernetes/helm/collabora-online/values.yaml
- Ingress-Nginx has changed their default security settings in release <https://github.com/kubernetes/ingress-nginx/blob/main/changelog/controller-1.12.0.md>. `annotations-risk-level` default settings has changed from `critical` -> `high`. So annotation like `nginx.ingress.kubernetes.io/server-snippet` is not allowed.
- so something like following is not allowed unless you change the annotation-risk-level to critical and sometimes admins don't want to change the risk level:
```yml
nginx.ingress.kubernetes.io/server-snippet: |
location /cool/getMetrics { deny all; return 403; }
location /cool/adminws/ { deny all; return 403; }
location /browser/dist/admin/admin.html { deny all; return 403; }
```
- this patch introduce workaround in our helm chart where we will deploying a dummy …
> helm: add nginx-deny service

- ios/Mobile/Info.plist.in
The version for the rest of the app was bumped in Ic41770e5918bbb8b7e37615b52b99eb7c370013f, but iOS was ommitted.
To build new testflight versions, we can't be using the same version as was already released on the app store
Change-Id: I404577837423cfcc5b929baa63a924605e4284e5
* Resolves: # 
> chore(iOS): bump version

- Makefile.am
- common/ThreadPool.hpp
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/Kit.hpp
- kit/SlideCompressor.hpp
Current PNG compression is as expected unfeasibly slow - so parallelize this with a ThreadPool where possible.
Change-Id: Ifd0e33c5da42b0c1b7722a2b45b9fe101733cd66
* Resolves: # 
> cool#11779 - thread slide layer compression.

- browser/src/control/Control.ColumnGroup.ts
- browser/src/control/Control.CornerGroup.ts
- browser/src/control/Control.GroupBase.ts
- browser/src/control/Control.RowGroup.ts
Change-Id: I0e53c2cc5a61b64e786757a4443c73f9021c9993
* Resolves: #11372 
When switching between light and dark mode in Calc, the row, column, and corner of the document canvas did not immediately apply the correct background color. The background color only updated after refreshing the page, regardless of whether dark mode or light mode was active.
[Screencast from 23-04-25 20:10:19.webm](https://github.com/user-attachments/assets/ffc18d37-4967-4426-8377-1983573ce10c)
> calc: light and dark mode sync in document-canvas

- browser/css/leaflet.css
Change-Id: I34cca4da76a6d8279a04c9f9c7159f943bbb8ec4
Since we removed [L.Control.Attribution.](https://github.com/CollaboraOnline/online/pull/11466/commits/88a4403309204c343705bdc926ed53c2fe09d2ab), this CSS should also be removed as its unused
> Remove unused attribution css

- browser/src/control/Control.JSDialogBuilder.js
- it was removed recently due to fix for popups
- do not do it partially inside updateWidgetImpl
- schedule task in entry point for all components
commit 59432e8bd6eaee0f2c1740992bbdca8ba09affc6
jsdialog: reduce flicker and position changes 3
> LayoutingService: use taks for update widget

- browser/src/layer/tile/CanvasTileLayer.js
browser/a510bb2f78/src/layer/tile/CanvasTileLayer.js:3360 Uncaught TypeError: this._painter.dispose is not a function
at NewClass.onRemove (/browser/a510bb2f78/src/layer/tile/CanvasTileLayer.js:3360:23)
dispose doesn't exist
> Avoid error on close

- net/Socket.cpp
- net/Socket.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
only std::istream api of Poco::MemoryInputStream needed in these handlers.
> only std::istream api of Poco::MemoryInputStream needed

- browser/src/docstate.js
See CanvasTileLayer.js _updateTileTwips(). A wrong guess would be that
these are CSS pixels, which are not zoom dependent.
Change-Id: I2c1afe8f012dcd75e4f2d46bf2a063b0823fd451
> browser, docstate: document that twips<->pixel multipliers are zoom-dependent

- browser/src/slideshow/CanvasLoader.ts
- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayerRenderer.ts
- browser/src/slideshow/RenderContext.ts
- browser/src/slideshow/Transition2d.ts
- browser/src/slideshow/VideoRenderer.ts
- browser/src/slideshow/transition3d/PermTextureTransition.ts
…ture storage
Change-Id: I27088679ff66652c453e18cb131ca185946d6941
* Resolves: # 
> hackweek : improve performance/memory for webgl

- browser/css/btns.css
- browser/css/device-desktop.css
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialogBuilder.js
- Create a <button> for the dropdown arrow if applycallback is present, allowing user interaction.
- Create a non-focusable <div aria-hidden="true"> if no interaction is needed (purely decorative).
- Solves confusion where screen readers would announce inactive buttons, improving keyboard and screen reader usability.
Change-Id: I1a81857c59ff8faa9fbb6ab341986e1124218af7
* Resolves: # 
> Improve split button structure for accessibility compliance

- browser/css/jsdialogs.css
Change-Id: Ib6f96f3a016377ed1d14543c57cf407c1ef36e85
* Resolves: # 
- Apply a full width to the AcceptRejectChangesDialog
- Removed margins on menubuttons to fix alignments in date/time picker
> Manage changes dialog alignments

- browser/src/canvas/sections/ShapeHandlesSection.ts
- browser/src/map/handler/Map.FileInserter.js
- kit/ChildSession.cpp
- wsd/FileServer.cpp
Previously we were not getting the size of multimedia we were inserting as we can't use gstreamer to do this job in core and we had no process for doing this in online. That meant that all videos were inserted with a fallback size, which happened to be small and square. As not all videos are small and square, this led to some videos having a box with a considerably different aspect ratio than the video itself.
This patch is probably not quite right - for instance if we insert a very large video it will end up much, much bigger than the slide - but it's probably a good jumping-off point to do nicer things.
* Resolves: # 
> fix(multimedia): Insert multimedia at correct size

- common/StringVector.hpp
- kit/ChildSession.cpp
- test/StringVectorTests.cpp
* Resolves: #8103
When ignoreQuotes = false delimiters within quotes (' or ") aren't tokenised.
Causes problems especially as space is the default delimiter, so if the input string has any `key="string"` pattern tokens a space will cause issues
For #8103 
Unocommand was being incorrectly tokenized as space is the default delimiter:
`uno .uno:ExecuteSearch {"SearchItem.SearchString":{"type":"string","value":" "}, ...`
`                                                                           ^^^`
> Tokenize Quotes

- browser/src/map/Clipboard.js
Previously we were awaiting some of our operations - e.g. the fetch or
the _check - before calling navigator.clipboard.write. This worked in
most places, but unfortunately iOS seems to fail when we do this.
While it wasn't possible to tell from debugging whether it was a small
delay that caused the clipboard write to fail or whether awaiting some
promises cause the failure in-and-of, deferring the promises into the
clipboard item fixes the issue on iOS.
Doing this requires a bit of promise juggling - in particular, we need
to reject if we have a check failure to avoid writing to the clipboard.
Doing this, however, will cause a generic failure that we previously
interpreted as a permission error. To bypass this, we can await the
clipboard items afterwards to see if they would have failed, …
> fix(clipboard/write): Defer fetching and checking

- config.h.in
- configure.ac
tweak config.h to always have CONFIG_STATIC as static for coverity, with or without --enable-debug used.
Change-Id: I0dddf0235a4c5b18af1b2d7c1f92d7741a9224d3
* Resolves: # 
> cid#463621 silence Variable copied when it could be moved

- browser/src/control/Control.Zotero.js
problem:
in online when a reference mark field is inserted(as ref mark)  and you start typing after it, field always expanded.
Change-Id: I10dc7ce28db5d212f91e6cf26abaefb11938d652
> zotero: send field parameter to avoid citation field expansion

- .gitignore
- Makefile.am
- configure.ac
- coolkitconfig.xcu.in
Change-Id: I716c9c00b91a481c2f47e0ac4755712e08765b6e
* Resolves: # 
> disable exotic file format by default

- coolwsd-systemplate-setup
I have a font installed under /usr/local/share/fonts/. Running Online
(debug core build), I immediately see a warning:
warn:vcl.unx.freetype:968539:968522:vcl/unx/generic/glyphs/freetype_glyphcache.cxx:118: open('/usr/local/share/fonts/CAVOLINI.TTF') failed: No such file or directory
But when in a document I try to expand the font list dropdown, Online
crashes on the assertion in FreeTypeTextRenderImpl::GetTextLayout.
The problem is the font that is reported by fontconfig, but is not
available for Online. Handle that path same way as /usr/share/fonts.
Change-Id: I8292194ed6c0410d6720c46e1e3067efb3bf41dc
> Also copy fonts from /usr/local/share/fonts

- common/StringVector.hpp
- kit/ChildSession.cpp
- test/StringVectorTests.cpp
of the original string.
Change-Id: I64926ac9dca7d7f0ece343afeb0eef1615d67777
* Resolves: # 
> avoid need for tokenize_outside_quotes by using trailing substr

- browser/src/control/Control.SidebarBase.ts
This fixes regression from commit b5949f46
Implement NavigatorPanel and create SidebarBase
1. Open Writer
2. Sidebar is opened, close it
3. reopen app
Expected: sidebar is closed (remember last state)
Result: sidebar is always opened
property name is ShowSidebar not Showsidebar
> sidebar: remember last state

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
- avoid using force so we know we already have the elements initialized and visible
- avoid switching the view mode on start which is not necessary for the testing feature itself
> cypress: make scrolling tests more stable

- browser/css/btns.css
Before this commit, the disabled button in the toolbar-down where
being set with a background color from the following declaration:
"jsdialog:not(.sidebar) *[disabled]" in the same btns.css file.
Change-Id: I86f433bf2f9219fd8e799ab290f128dd1b4fb1ad
> Toolbar-down: fix search buttons when disabled

- browser/src/app/LayoutingService.ts
- browser/src/control/Control.JSDialog.js
- browser/src/control/jsdialog/Util.Dropdown.js
- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
prevents us from errors when some dynamically created menu is not available
or we used wrong instance in the callback
> jsdialog errors fixes

- browser/css/jssidebar.css
- browser/src/control/jsdialog/Widget.TreeView.ts
So, it shares the some alignment as navigation-header
Change-Id: I075a1c43b69b7f22b0e7cc4faf49035cd2677385
> Navigator: Add padding to placeholder (empty list text)

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
- cypress_test/integration_tests/desktop/writer/notebookbar_spec.js
force parameter allows to ignore some errors, like:
- button is covered by other element
that is what we should avoid if there is any option to do it well
> cypress: reduce usage of force

- net/Socket.cpp
- net/Socket.hpp
Hopefully this ensures that we always get at least one onDisconnect, and the logic is easier to read / see / reason about around that.
Change-Id: If0c58c5844f432e0a65ad05681d7759c7e3874d3
* Resolves: # 
> Simplify onDisconnect emission.

- browser/css/jsdialogs.css
Change-Id: If5d39bb689da38f812fd32ced170405f078c94dc
* Regression: #11783 
When font size increases, text was previously overflowing into adjacent columns, creating readability issues. This new grid alignment implementation resolves this problem by using responsive column sizing.
CURRENT IF THE FONT SIZE IS "15PX"
WITH THIS PR
> Fix table alignments in manage changes dialog

- browser/.stylelintrc.json
- browser/Makefile.am
- browser/css/btns.css
- browser/css/cool.css
- browser/css/device-mobile.css
- browser/css/device-tablet.css
- browser/css/impress-mobile.css
- browser/css/jsdialogs.css
- browser/css/jssidebar.css
- browser/css/leaflet.css
- browser/css/menubar.css
- browser/css/mobilewizard.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
Change-Id: Ie74b9a730d13dadf8c66bc7e5676f05930925800
* Resolves: #11824 
- Added Stylelint rule to enforce space before block-opening brace and fix CSS files
> Added Stylelint rule to enforce space before block-opening brace and fix CSS files

- kit/ChildSession.cpp
appending string to json argument caused json to become invalid and entire command was not executed
Change-Id: I7e22b89022ef91fbe1db3eda52f210e7e65852e2
* Target version: distro/collabora/co-24.04
> zotero: fixed citation style not being saved (cherry-pick)

- net/HttpHelper.cpp
- net/Socket.cpp
- tools/map.cpp
- wsd/ProxyProtocol.cpp
&foo[0] is caught by the hardening compiler flags for the empty case. Which isn't the case here, but tidier to be consistent on this.
Similarly use std::unique_ptr<>.get() instead of &foo[0].
Change-Id: I898a0320e6d4f0eafb6d2a80cebf14ed460a9f3c
* Resolves: # 
> use std::vector::data instead of &foo[0]

- browser/src/layer/tile/CanvasTileLayer.js
In I10e1ae5781c170c0d8a85b8638daa8f61e3eaa6e, we removed the unused tile pane. Unfortunately, it wasn't quite unused.
In CanvasTileLayer, we used it as a parent to our container. When we synchronized the position, that also moved around the container. Touch control, it seems, needed that movement: while we could start moving we would very often end up unable to move afterwards.
Change-Id: Ib9859b3faa71edee4826ed41c976f5f9fde9f83d
* Resolves: # 
> fix: Stop touch movement from freezing

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Title Case can be hard to read and, for example, some
languages (German where capitalization goes for all nouns) even harder
to achieve without problems. Furthermore, this iframe will be seen in
the integrator side and is probably a safer option to make sure
everything is sent out in: Sentence case.
Change-Id: I5183fd5adaf877b557b4636c7b5bfd1ee8dd81c0
> setting-iframe: Adjust sectionTitles to sentence case

- wsd/DocumentBroker.cpp
DocumentBroker::pollThread check for _storage at:
if (_storage && !_lockStateUpdateRequest && _lockCtx->needsRefresh(now)) {
refreshLock();
}
but not when calling updateStorageLockState later
Change-Id: I55b72be06e3000983fd7887c5158ed768003de98
* Resolves: # 
> cid#427990 Dereference after null check

- scripts/build-samples.py
- wsd/COOLWSD.cpp
The "-large" suffix is big enough to not work with a simple \t anymore,
so do an explicit padding instead.
The width is just a value that does nothing for the currently longest
string.
Change-Id: I52e698b1e918e382b2c1dae216b8e1b948b3a2b1
> make run: show large writer document by default

- wsd/DocumentBroker.cpp
and the comment mentions this explicitly, but it is unconditionally dereferenced here:
```
#1  0x00007fb91dd367f1 in __GI_abort () at abort.c:79
#2  0x0000000000c22a7e in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) ()
#3  0x00000000006fec1e in std::__shared_ptr_access<ClientSession, (__gnu_cxx::_Lock_policy)2, false, false>::operator* (this=<synthetic pointer>)
at /opt/rh/devtoolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:1347
#4  std::__shared_ptr_access<ClientSession, (__gnu_cxx::_Lock_policy)2, false, false>::operator* (this=<optimized out>)
at /opt/rh/devtoolset-12/root/usr/include/c++/12/bits/shared_ptr_base.h:1347
#5  DocumentBroker::updateStorageLockStateAsync(std::shared_ptr<ClientSession> const&, StorageBase::LockState, …
```
> lockStateUpdateRequest holds ClientSession by weak_ptr

- browser/js/global.js
We were encountering this issue because URLSearchParams.get() returns strings, and in JavaScript, any non-empty string is truthy, including "0" and "false".
I guess it was wrong since a722687c116f81be19423fc92630cb7d7209b65a
Change-Id: Ib6b82ab78939fb00c92552bad8a7a50639db0511
* Resolves: #11865
> cool#11865 &closebutton=false or &closebutton=0 was misinterpreted

- browser/admin/src/AdminSocketAnalytics.js
- browser/css/cool.css
- browser/css/helpdialog.css
- browser/css/jsdialogs.css
- browser/css/jssidebar.css
- browser/css/leaflet.css
- browser/css/notebookbar.css
- browser/welcome/welcome.css
- The font in collabora online did not scale well with the change of browser font size change
- now we changes all font sizes to rem units
- this will improve accessibility when change in browser font size change
- improve custom font size changes in jsDialog and in notbookbar
Change-Id: I5c4c180e897333c06b1bde3a87323205253cd3ea
* Resolves: # 
> Use rem units for font sizes to improve accessibility

- browser/css/iframedialog.css
- browser/src/map/handler/Map.Feedback.js
Change-Id: I5750b51e9baea6654eb0b76974b72889019ef535
* Resolves: # 
Added support for capturing the doc_type when users submit feedback. This helps us understand which application (like Writer, Calc, or Impress) the feedback is coming from. This gives us useful context to better analyze and respond to user issues.
> Add doc_type parameter to feedback dialog

- wsd/COOLWSD.cpp
Change-Id: Icc2cb59415da3db0d8b86fdb5904b6f53c1ccfa8
* Resolves: # 
Ensure to encode the whole file_path.
> wsd: url encode whole file path

- kit/Kit.cpp
Profiling suggests the un-necessary wakeup on every message is unfeasibly expensive, 40% of a long-running profile.
Change-Id: Icc51ae917c2ceddfc648a05b7f0332adf5238309
* Resolves: # 
> Only enable input processing on jsdialog message if it is disabled.

- browser/src/app/TilesMiddleware.ts
- browser/src/geometry/Bounds.ts
- browser/src/layer/tile/CanvasTileWorkerSrc.js
Various optimisation work, mostly to enable work to be broken up into more manageable chunks and interrupted/cancelled more easily.
> Optimise scrolling to make scroll-handle scrolling feel better

- browser/admin/src/AdminSocketAnalytics.js
- browser/admin/src/Util.js
Change-Id: I65126d65ae2f43efaeefb8091385a405bd2544e0
* Resolves: # 
Refines PR #10456 by removing duplicate code, factoring out data text processing into Util.consumeDataText.
> AdminSocketAnalytics.js: Remove duplicated code

- browser/css/jsdialogs.css
* Backport PR: #11839 
Manage changes dialog alignments
- Apply a full width to the AcceptRejectChangesDialog
- Resolved text bleeding between columns when font-size increases
- Removed margins on menubuttons to fix alignments in date/time picker
- Fixed misalignment between ui-treeview-headers and ui-treeview-entries
by setting consistent grid-template-columns
> Backport: Manage changes dialog alignments

- browser/src/control/Control.Header.ts
- browser/src/layer/tile/SheetGeometry.ts
The maxIndex was calculated wrong. This commit fixes the issue.
Change-Id: I12dbb530909262c62e2c269385eb441a5a958078
* Resolves: # 
> Calc hidden rows / columns flickering issue.

- browser/css/partsPreviewControl.css
* Resolves: # [Last preview slide in navigation is not fully visible #11810](https://github.com/CollaboraOnline/online/issues/11810)
adjusted the height to make last preview slide visible properly.
> fix (11810) - Last preview slide in navigation is not fully visible

- kit/Kit.cpp
This fixes regression caused by commit	1acd37a671b9d3633a7d31a0b60478815fbc685f author	Armin Le Grand (Collabora) <Armin.Le.Grand@me.com>	Fri Sep 13 11:42:27 2024 +0200 committer	Armin Le Grand <Armin.Le.Grand@me.com>	Mon Sep 23 14:12:04 2024 +0200 CairoSDPR: Activate globally to check builds/tests
This is to check all builds/tests with activated CairoSDPR to evtl. make needed additional changes as preparation to activate this in the future.
----------------------
The bug was in rendering tiles while chart becomes activated (double click on chart) - surrounding tiles become blank. So selecting some data range was not possible without visual aid where to look for them.
This patch uses embedded feature flag to disable it without core change.
> Disable system dependent primitive renderer in kit

- common/Unit.hpp
- test/UnitInitialLoadFail.cpp
- test/UnitMultiTenant.cpp
- test/UnitUserPresets.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPIHttpRedirect.cpp
- test/UnitWOPITemplate.cpp
- test/WopiTestServer.hpp
Change-Id: I1697726144bde3730d8a9f0303bdd38022f0edd7
* Resolves: # 
> use std::istream baseclass instead of Poco::MemoryInputStream

- common/Util.hpp
- net/HttpRequest.hpp
- test/HttpRequestTests.cpp
- test/UnitWOPIDocumentConflict.cpp
- test/UtilTests.cpp
- wsd/Admin.cpp
- wsd/DocumentBroker.cpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
- wsd/wopi/WopiStorage.cpp
- **wsd: log and ProfileZone name**
- **wsd: remove const to allow moving**
- **wsd: test: fix stability of UnitConflictAfterTimeoutSuccess**
- **wsd: simplify Util::eliminatePrefix and add tests**
- **wsd: test: include cleanup in HttpRequestTests**
- **wsd: test: remove redundant variables**
- **wsd: test: support ssl and non-ssl external http tests**
- **wsd: asyncRequest checks for valid SocketPoll**
- **wsd: test: add invalid poll test to HttpRequestTests**
- **wsd: reset the checkfileinfo when we fail**
> Reset CheckFileInfo on Failure

- browser/src/canvas/sections/CalcValidityDropDownSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
Issue:
* On the core side, position of the validity dropdown is calculated as:
* The right most position whether the cells are merged or not.
* The bottom position of the first cell - even if the cells are merged.
* We are sending the click event to the core side to activate the dropdown. So we need to click on the correct position.
This commit also removes unnecessary onClick handler.
Change-Id: I6a5b26b42e4cf77a070452042d5f7a242e874bc0
* Resolves: # 
> Calc Validity Dropdown: Fix positioning on merged cells.

- common/Util.cpp
- common/Util.hpp
- wsd/COOLWSD.cpp
which typically calls malloc_trim but will call tcmalloc's MallocExtension_ReleaseFreeMemory if tcmalloc is in use instead.
log which allocator is in use.
Change-Id: I95a777bdcdc9cbec12ccba3b95f73d555d87d7fe
* Resolves: # 
> add Util::trimMalloc

- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/canvas/sections/FocusCellSection.ts
Issue:
* Workaround for always-visibility causes other issues. Drawing of the section with split panes were incorrect.
Fix:
* Set section position properly.
Later:
* Add a "alwaysVisible" property for documentObjects.
Change-Id: I5c36a78302808eba0078c4eb2b5d5505e4f72ad8
* Resolves: # 
> Focus cell section: Set the position of the section properly.

- browser/src/control/jsdialog/Widget.TreeView.ts
we were not able to open SDK due to CSP in the same page
> audit dialog: add attributes to SDK entries

- browser/src/app/Util.ts
- browser/src/dom/Draggable.js
- browser/src/map/handler/Map.TouchGesture.js
Previously, in Ifdf885452135346e1df5f3196d49f76b8d1f983a, we would have
fallbacks for if requestAnimationFrame didn't exist
var requestFn = window.requestAnimationFrame || getPrefixed('RequestAnimationFrame') || timeoutDefer,
We would sometimes run a function immediately: in the case that the
function couldn't be deferred into a timeout and timeoutDefer was the
selected requestAnimationFrame fallback
L.Util.requestAnimFrame = function (fn, context, immediate) {
if (immediate && requestFn === timeoutDefer) {
fn.call(context);
} else {
return requestFn.call(window, L.bind(fn, context));
}
};
Unfortunately, when we removed the fallbacks we changed the code like so
export function requestAnimFrame(
fn: () => void,
// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types …
> fix: Don't run requestAnimationFrames instantly

- common/Unit.hpp
- test/UnitInitialLoadFail.cpp
- test/UnitMultiTenant.cpp
- test/UnitUserPresets.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPIHttpRedirect.cpp
- test/UnitWOPITemplate.cpp
- test/WopiTestServer.hpp
doing this will allow these to be later called from const methods
Change-Id: I17b8b7c2f92443266c91749381a26913a368ac6e
* Resolves: # 
> these can be const

- common/FileUtil.hpp
- test/WhiteBoxTests.cpp
Change-Id: I412626adb0566fac77eca2c12fecf058cf26a4d6
* Resolves: # 
> Stat::path is unused

- android/lib/src/main/cpp/CMakeLists.txt.in
This is a regression from I7a6f906a8b245efb4f9540022c81cbc27099e997 which split up the mobile bits of unit tests...
I suspect something similar to I9c4df8c22c25de72b5ddc231f5cef37ba19f0d04 where Tor didn't notice an identical issue immediately - with the suspicion that it's based on debug mode
> Is it required only when using --enable-debug?
Change-Id: I8005d352e4b0eb61b84d27739d85118656598187
* Resolves: # 
> fix(android): add Unit-mobile.cpp

- browser/src/app/TilesMiddleware.ts
- browser/src/layer/tile/CanvasTileWorkerSrc.js
This reverts commit 46cbac82ed1ee1071da66f107ee87928043ea0bd.
It was causing artifacts shown on a screen.
Mostly visible when working with charts or formatting marks
> Revert "Skip decompressing keyframes that become not-current"

- browser/src/canvas/sections/TilesSection.ts
In PDFs, we have some code to render the page numbers based on a fixed page size when tiles haven't yet loaded
Rather than page 1 being the top, the top page is internally considered to be page 0. That means that when subtracting 1, we would shift all the rendered placeholder pages up by one page.
This effect wouldn't show when you were at the top of the document, because then we would be on 'page 0' and would go into the other branch, not subtracting 1 and not rendering the pages incorrectly offset. Scroll down a little, however, and you would find that as soon as the top of page 2 reached the top of your screen the numbers would jump - page "2" becoming page "3". Finally, you wouldn't get a page rendered at all where the last page should be
* Resolves: # 
> fix: show correct page number

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
I found this while digging through Android Vitals crash reports, as well as a few similar reports of NullPointerExceptions on mime types...
Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.collabora.libreoffice/org.libreoffice.androidlib.LOActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference ------ 8< snip ------
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
at org.libreoffice.androidlib.LOActivity.canDocumentBeExported (LOActivity.java:1233)
------ 8< snip ------
...This seems to be because we can sometimes pass an invalid URL to …
> fix: don't crash on null mime-type

- browser/src/control/Control.NavigatorPanel.ts
- browser/src/control/Control.UIManager.ts
- browser/src/control/HRuler.ts
- browser/src/docstate.js
- Before this patch in presentation mode because of cache `ShowNavigator` seems to set to true even if navigator is not populated
- we were string this value in local storage which not getting reset on reload
- also we did not need to remember state if session changes
- so better to manage state in app object and not in local storage
- this will remember navigator state only for current session using app object
Change-Id: If5836097cfce6b5a047de2b05aec4b5d7a26fcd0
* Resolves: # 
> Set default values for showNavigator on document load

- net/Socket.cpp
coolwsd(Util::assertCorrectThread(std::thread::id, char const*, int)+0x300)[0xa35e2a]
coolwsd(Socket::assertCorrectThread(char const*, int) const+0x42)[0x71cc86]
coolwsd(StreamSocket::ensureDisconnected()+0x3f)[0x7d21fd]
coolwsd(StreamSocket::~StreamSocket()+0x1d8)[0x7d2072]
coolwsd(void std::destroy_at<StreamSocket>(StreamSocket*)+0x23)[0x81bb33]
coolwsd(void std::_Destroy<StreamSocket>(StreamSocket*)+0x1c)[0x81b88b]
coolwsd(std::_Sp_counted_ptr_inplace<StreamSocket, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()+0x44)[0x81975e]
coolwsd(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use()+0x27)[0x7349f9]
coolwsd(std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release_last_use_cold()+0x1c)[0x72c9d6] …
> move _socket in SocketDisposition::execute

- browser/Makefile.am
Similar to commit 582b36ce0edd50c663239224c8ef6ae4a617a607 (automake
silent rules: handle jscpcd, 2025-04-14), i.e. the cmdline was hidden
unconditionally, now it's hidden for --enable-silent-rules and shown
otherwise.
Change-Id: Ic2eedfd7ba051893da0db6ce421a62df82902075
> automake silent rules: handle CSS stylelint

- net/Socket.cpp
- net/Socket.hpp
this is an out_value used by
ClientRequestDispatcher::handleIncomingMessage to update its _lastSeenHTTPHeader member
went awry in:
commit bebf8902038d1e6553a5175bc93f07fd8b734d28
CommitDate: Fri Mar 28 11:04:19 2025 +0000
wsd: time_point is best passed by value
Change-Id: I9c306bc6d28cfd1e6e96c1d3272eda1f2bd392ea
* Resolves: # 
> restore passing lastHTTPHeader by reference

- net/HttpRequest.hpp
So any remaining data in the buffer from an earlier socket::send doesn't really get sent over the wire. Explicitly flush before shutdownConnection.
Change-Id: I7979223cb289adfd970b1678eaa9c5a0f097aa53
* Resolves: # 
> ServerSession may shutdownConnection on socket before all data gets sent

- docker/README
- docker/cool-seccomp-profile.json
That can be used by docker, or kubernetes, to allow Collabora Online to containerize its document processes without require CAP_SYS_ADIMIN
Change-Id: I71ef65ca07657a33a9342644cfe75ad5918dc1bd
This is the docker default profile (https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) with the required six syscalls allowed: unshare, mount, umount2, setns, clone and chroot.
Reference:
https://docs.docker.com/engine/security/seccomp/
https://kubernetes.io/docs/reference/node/seccomp/
More context:
https://caolanm.blogspot.com/2024/08/linux-namespaces-and-collabora-online.html
> Add a reference seccomp profile json

- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
Change-Id: Idbc3945a3ce78532eb56f8a914286e78452094e1
* Resolves: #11919 
- Removed darkgrey border from selected thumbnails in read-only mode and added  preview-img-currentpart class to the selected thumbnail
https://github.com/user-attachments/assets/e5710e48-07d4-4464-bf8a-8d5fda511c67
https://github.com/user-attachments/assets/db8f2498-6949-48f0-ab61-341dbafd7abe
> Add styling for active thumbnails in read-only slides

- browser/css/jsdialogs.css
https://github.com/CollaboraOnline/online/issues/11840
Changed `.ui-listbox-arrow` to draw a vector arrow instead of using JQuerry UI Lightness theme icon.
Updated `.ui-combobox-button` to center new `.ui-listbox-arrow` logic.
Updated `.arrowbackground` for better centering of `.unoarrow`.
`.ui-listbox-arrow` before: 
`.ui-listbox-arrow` after:
`.arrowbackground` and `.unoarrow` before:
`.arrowbackground` and `.unoarrow` after:
Change-Id: Ifd5f9b68a8897a20a3e4fad74830f8469c850e45
* Resolves: # 
> gh#11840 Replace bitmap icon with svg

- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
```
cypress: avoid async check for clipboard
We use clipboard to fetch the document content in many places.
Unfortunately when we do doIFWriter or similar - we invoke async
checks. So there is a race if we just after that try to type
something else...
We need a barrier at the end of the function to prevent above.
I'm wondering if it is not enough to use it instead specialized
functions for different app. But let's keep it as it also check
some structure inside.
```
------
```
cypress: restore impress/undo_redo_spec.js
- fix fails caused by async checks in the parallel execution with
typing
- for now add safe waits to check if it is stable on CI
```
> cypress: avoid async check

- browser/npm-shrinkwrap.json.in
- browser/src/map/Clipboard.js
This is a trivial backport of #11668
Previously we were awaiting some of our operations - e.g. the fetch or
the _check - before calling navigator.clipboard.write. This worked in
most places, but unfortunately iOS seems to fail when we do this.
While it wasn't possible to tell from debugging whether it was a small
delay that caused the clipboard write to fail or whether awaiting some
promises cause the failure in-and-of, deferring the promises into the
clipboard item fixes the issue on iOS.
Doing this requires a bit of promise juggling - in particular, we need
to reject if we have a check failure to avoid writing to the clipboard.
Doing this, however, will cause a generic failure that we previously
interpreted as a permission error. To bypass this, we can assume that a
permission failure …
> backport: fix(clipboard/write): Defer fetching and checking

- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
Continue to do that if convert-to is used and it was denied, but don't do that when we self-query if convert-to is allowed in order to fill out if convert-to is available in capabilities
Change-Id: I17afe6a733a59ba7d3480362d116f1f54956cfa3
* Resolves: # 
> from capability query don't log a WRN if convert-to is not available

- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- wsd/ClientRequestDispatcher.cpp
We centralize `closeFD()` logic to have strong guarantees that we call `close(2)` once, and we always invalidate the FD. In addition, we now treat closed-but-not-shutdown equivalent to `isShutdown()`, where it matters. This is done through the new member `isOpen()`, which we use instead of `isShutdown()` where being closed implies being shut down.
- **wsd: deduplicate Socket::closeFD()**
- **wsd: add Socket::isOpen() and replace isShutdown()**
> Tighter Socket Closed State

- net/HttpRequest.hpp
When there is no more data left to send from a ServerSession use StreamSocket::shutdown to set _shutdownSignalled to flag async shutdown and let handlePoll write the queued outBuffer until it is empty (or no more writes are possible). handlePoll will trigger onDisconnect at that point instead of explicitly calling it early here.
i.e. with this, onDisconnect is called as:
```
#0  http::ServerSession::onDisconnect (this=0x7fffc00041c0) at ./net/HttpRequest.hpp:2210
#1  0x00000000007d63c9 in StreamSocket::ensureDisconnected (this=0x7fffcc003230) at net/Socket.hpp:1258
#2  0x0000000000aa3901 in StreamSocket::handlePoll (this=0x7fffcc003230, disposition=..., now=std::chrono::_V2::steady_clock time_point = { 611539841270573ns }, events=4)
at net/Socket.hpp:1779
#3  0x0000000000a9001f in …
```
> flag async shutdown via _shutdownSignalled

- coolwsd.xml.in
- net/WebSocketHandler.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/HostUtil.cpp
- wsd/HostUtil.hpp
- wsd/Storage.cpp
- only if `allowed_websocket_origins.origin` matches
- particularly useful when using geolocation setup where websocket uri
and value at "Origin" header can be different because uri can be altered
by indirection server
Change-Id: I9f3e8a389248080ba44ebafc03ac2ad6373b7756
1. normal case it should accept the request if origin matches
```sh
websocat --insecure "wss://localhost:9980/cool/https%3A%2F%2Flocalhost%3A9980%2Fwopi%2Ffiles%2Fhome%2Frashesh%2Fwork%2Fcollabora%2Fonline%2Fmaster%2Ftest%2Fsamples%2Fcalc-edit.ods%3Faccess_token%3Dtest%26access_token_ttl%3D0/ws?WOPISrc=https%3A%2F%2Flocalhost%3A9980%2Fwopi%2Ffiles%2Fhome%2Frashesh%2Fwork%2Fcollabora%2Fonline%2Fmaster%2Ftest%2Fsamples%2Fcalc-edit.ods&compat=/ws" -H "Origin: https://localhost:9980"
```
- Works as …
> indirection: allow ws request with cross origin

- browser/src/control/Control.NavigatorPanel.ts
No matter its permission, these document types should allow the user
to see the page/slide thumbnails. Before this commit, that was not
possible.
Change-Id: I9161c3caeae6d155919fd24de13c273d39edc2a1
> Show page/slide thumbnails for PDF, drawing or presentation

- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitWebSocket.hpp
Change-Id: Ia97b9e762e3e28e0ff82b91c19dcf946e753a361
* Resolves: # 
> don't trim memory in parent while bgsave child exists

- common/Seccomp.cpp
This can be allowed for the container, the child process does not need it.
Change-Id: I3d91dee111394c347ed2e583005834ccfa3adcab
* Resolves: # 
Just for completion
> Seccomp: disable setns for child processes

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Fix: Auto-adjust iframe height using postMessage
Previously, the iframe height was hardcoded, which could result in excessive whitespace at the bottom. Now, we send a postMessage with the type  and the height (in pixels) as the payload. This allows the integrator to dynamically adjust the iframe height based on actual content.
Follow UP: Once this get in, a change in the SDK is needed.
Change-Id: I509c7ffb9fdaccb65146a52371d8b08d1b0c0301
* Resolves: # 
> Fix: Auto-adjust iframe height using postMessage

- kit/Kit.cpp
- kit/Kit.hpp
which will pick up a missed deep trim opportunity if a bg save was still ongoing at the time of declaration of the last active session of entering inactivity
Change-Id: I21ed783f4250cadd1f5c7720b7a32fc745345186
* Resolves: # 
> trim more aggressively when all sessions declared they are inactive

- browser/css/cool.css
- before this patch we are using --border-color variable which is causing issues when we are in dark mode or document loaded in dark mode.
- so if user is in dark mode and click freeze pane then the split line color is not visible because the --color-border does not making good contrast with dark theme canavs.
- also it looks good whene we use same color code for both mode as a split line color.
- so now i changed it to a hardcoded color code which is same for both light and dark mode.
Before:
After:
Change-Id: I6542b66275fe4d154c18103bd5c2e9b63b2dd64b
* Resolves: # 
> Set freeze pane split line color code

- kubernetes/helm/collabora-online/templates/deployment.yaml
- kubernetes/helm/collabora-online/templates/statefulset.yaml
- kubernetes/helm/collabora-online/values.yaml
* Resolves: #11984 
Add annotations and labels configuration to the Kubernetes Helm chart `values.yaml` and Deployment/StatefulSet resource templates.
> feat(helm): Add deployment annotations and labels configuration

- browser/src/canvas/sections/CommentSection.ts
- browser/src/canvas/sections/URLPopUpSection.ts
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Toolbar.js
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/control/jsdialog/Widget.Edit.ts
- in few places, added roles and aria-labels to div elements that were missing them
- this will help screen readers to better understand the purpose of these elements
Change-Id: I7a16ae03e73e2cce076e6d5bc84f660a39938211
* Resolves: # 
> Add roles and aria-label for missing div elements for better screen reader

- browser/src/control/Control.JSDialogBuilder.js
followup for commit 17e6dd10fc288533bfc9cc00a4d784b4cd1a919c Fix close when map is not present
fixes regression from commit 662a707ec87d0a1855ca81102fa4dd512bece91a Share code for close action
steps to reproduce:
1. open mobile calc using csv file and some web integrator (see import dialog)
2. open second instance of that file when first dialog is still opened result: exception
Events.ts:281 Uncaught TypeError: Cannot read properties of null (reading 'dispatch')
at NewClass._defaultCallbackHandler (Control.JSDialogBuilder.js:285:20)
at NewClass.closeDialog (Control.JSDialog.js:128:12)
at NewClass.close (Control.JSDialog.js:94:10)
at NewClass.closeAll (Control.JSDialog.js:104:9)
at UIManager.closeAll (Control.UIManager.ts:1587:22)
at NewClass._onError (Control.AlertDialog.js:27:24)
> mobile: fix closing the app in csv import

- browser/src/control/Control.MobileWizardBuilder.js
We should follow the pattern: widget creates single root node which is only point visible from outside, so we do not set any properties for inner nodes outside widget handler function.
> mobile-wizard: disbled state sync for checkbox and radiobutton

- browser/src/core/Socket.js
1. open PDF file in impress or readonly presentation
2. kill server to see reconnecting dialog
3. restart server to try reconnect Result: error
Exception TypeError: Cannot read properties of null (reading 'resetInCore') emitting event status: {"mode": 0,"viewid":... TypeError: Cannot read properties of null (reading 'resetInCore')
at NewClass._onStatusMsg (http://co25:9980/browser/040b6e26d0/src/core/Socket.js:1415:49)
at NewClass._onMessage (http://co25:9980/browser/040b6e26d0/src/core/Socket.js:1178:18)
> notebookbar: fix error on reconnect in readonly

- browser/js/global.js
- browser/src/core/Socket.js
- cypress_test/cypress.config.ts
- cypress_test/integration_tests/common/helper.js
The purpose is to create a function to be stubbed by a
third-party application, such as Cypress, to log server responses.
Change-Id: I76781cc6b90954d471dd5777379bcea136d96b42
> browser: add initial empty function "_stubMessage"

- kit/ChildSession.cpp
- test/TileCacheTests.cpp
- test/UnitCursor.cpp
- test/UnitEachView.cpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
Replaced Poco::format with std::ostringstream in kit/, test/, and wsd/.
Signed-off-by: areg <areg.nakashian@gmail.com>
Change-Id: I576e942478cb318fe7d9737aae3a184b55dc0aae
> killpoco: replace Poco::format

- browser/src/slideshow/LayerDrawing.ts
problem:
regression from d82d7ca8e96e6fb125d527cf8ac066a734216115 
since we switched to using bitmaps for text field, these fields were never invoked for drawing on canvas
Change-Id: I3534671ff878149b1054a87d8e0632548f8e838e
> presentation: render text field bitmaps

- browser/src/control/Control.JSDialog.js
- Open Writer
- Show Sidebar
- Open any popup using dropdown (like bulets, underline or color selector)
Result:
LayoutingTask exception: TypeError: Cannot read properties of undefined (reading 'isDocumentAreaPopup') LayoutingService.runTheTopTask	@	LayoutingService.ts:46 (anonymous)	@	LayoutingService.ts:80
requestAnimationFrame
LayoutingService._flushLayoutingQueue	@	LayoutingService.ts:76 setTimeout
LayoutingService._setupTimer	@	LayoutingService.ts:60 LayoutingService._scheduleLayouting	@	LayoutingService.ts:91 LayoutingService.appendLayoutingTask	@	LayoutingService.ts:32 focusToLastElement	@	Control.JSDialog.js:176
closePopover	@	Control.JSDialog.js:165
close	@	Control.JSDialog.js:92
overlay.onclick
> jsdialog: fix error about missing popup after close

- browser/css/jsdialogs.css
This reverts commit d30f5b1348a640404dc1332a4d2dbba3c7a39350.
It was causing issues in the Manage Changes dialog in Writer when we had lots of actions with tree structure and icons
> Revert "Manage changes dialog alignments"

- browser/admin/adminIntegratorSettings.html
- browser/html/cool.html.m4
- browser/js/global.js
- browser/src/core/Socket.js
- browser/src/main.js
- common/Authorization.cpp
- common/Authorization.hpp
- test/RequestDetailsTests.cpp
- test/UnitInitialLoadFail.cpp
- test/UnitMultiTenant.cpp
- test/UnitUserPresets.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
Introduce the `no_auth_header` parameter. Pass this along the `access_token` to specify to never send `Authorization:` headers to the WOPI Host. This is usefull for some case where the WOPI host of the integration has some check of the header that cause errors to be returned.
Most of the time this is not needed.
Change-Id: I9fac6aaa2e9d409ccf4776b0a31164ea2a697084
* Resolves: # 
> Implement no_auth_header

- browser/Makefile.am
`man test` says "STRING1 = STRING2, the strings are equal". `==` is not a valid equality operator.
Change-Id: I3b9fa5dc28868ca9402414fb679b4ec5420b560f
> use correct string equality operator in the test expression

- browser/src/control/Control.IdleHandler.ts
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
_gotFirstCellCursor is used in Calc to draw only after we loaded the spreadsheet. It is not perfect, I found case where it wasn't enabled due to some problems with deactivation (IdleHandler).
Let's do it safe: we do activate() when we receive signal that document was loaded, that is good enough too. At the same time I don't change any other logic.
Steps to reproduce (not everywhere, on good performance only):
- clear cookies and site data
- open Calc Result: you see only first-screen of tiles,
scrolling doesn't show more
Not easy to reproduce.
> Calc: allow drawing on activity

- browser/src/slideshow/LayerDrawing.ts
Move WebGL video program initialisation to handleVideos(), ensuring it's created before any video renderer resources are set up. This commit would fix the video not loading on the first slide of the slideshow.
Change-Id: I1a857aa7d1302120e8bdeed765bcff9af21ef364
* Resolves: # 
This commit would fix the video not loading on the first slide of the slideshow.
> fix(slideshow): ensure program initialisation before first video setup

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: I5892afe1ea16869967332812fe8b397e9058a707
* Resolves: # 
> fix(settingIframe): validate JSON on browser file upload

- configure.ac
This is pretty similar to #7081, but works for --with-lo-builddir which is used in the Android app
* Resolves: # 
> build: fix failure on relative-path core

- common/SigUtil-server.cpp
- kit/Kit.cpp
Replace strlen() used on std::string.c_str operations to simply use std::string.size().
Change-Id: I73aa8f84d434fc19964dcf569cd28988e1a1efc3
> Replace strlen on std::strings

- net/HttpRequest.hpp
Change-Id: I951b0d7ac24f7b3f5d49748a2c6964fd31555a7e
* Resolves: # 
To keep the function name explicit.
> HttpRequest: rename finish function to more explicit error

- kit/Kit.cpp
This reverts commit 34d958e9790ebe529f642ab23e7622a2c7476730. Which was introduced to mask a problem with Chart editing. After double click on a chart we got all white tiles around the screen and it was not possible to select some interesing data because we didn't see them.
This can be done as fix in the core was merged for the issue: https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-25.04&id=4f65d3e2446a246a95fb963e1bafff7bfa0966d3
commit	4f65d3e2446a246a95fb963e1bafff7bfa0966d3
CairoSDPR: Correct BackgroundColorPrimitive2D when Viewport set
> Enable system dependent primitive renderer in kit

- browser/src/control/jsdialog/Widget.DrawingArea.js
The "aria-label" and "data-cooltip" attributes are mutually exclusive,
so add them appropriately if data exists.
Change-Id: I14e6ab50d3140f5f1b17ec8d14c92443382e7b49
> browser: accessibility: add "aria-label" attribute to drawing image

- browser/src/app/TilesMiddleware.ts
- browser/src/layer/tile/CanvasTileWorkerSrc.js
This started as a rewrite of my previous reverted scroll optimisations, but has really ended up in a refactor that should have no user-visible change, but may have some performance benefits.
As @mmeeks discovered with my previous patch set, there was the problem that if a decompression was cancelled, you could end up in a state where you don't have the raw deltas that were being decompressed. This patch-set first decouples collecting raw deltas from decompression. In addition, we concatenate the raw deltas only when we're going to decompress them - this has the benefit of cutting down on potential copying as we don't need to store the raw deltas concatenated, we can just keep a list. This should make non-visible tile pre-loading more memory bandwidth efficient.
After this change, I've …
> Refactor and simplify tile transactions in preparation for multiple workers (and possibly cancellable transactions)

- browser/src/canvas/sections/ShapeHandlesSection.ts
Preview is an HTML object, no need to add dpiScale multiplier. This fixes the shape scaling issue with browser zoom != 100.
Change-Id: I0509e5d7c1a9f606bb106b28485ceb423a6ae5db
* Resolves: # 
> Fix preview shape scale calculation.

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.IconView.ts
- browser/src/control/jsdialog/Widget.TreeView.ts
* Resolves: #12113
- adds right-click context menu support for icon view entries
- modifies css to adjust height for context menu
- used `_cleanText` utility to sanitize text
core side changes: https://gerrit.libreoffice.org/c/core/+/185516
Change-Id: I68c73a7664e2e2bbbf5c7fd6250e0af077d0c357
> iconview: added support for contextmenu

- browser/src/control/Control.Menubar.ts
"--o:document_signing.enable=false" option disables the signing menu in ui. But it was forgotten to be disabled in "compact" mode.
This change should be made in 6cdbbe04
Before change:
After change:
> fix: hide signature option when document signing is disabled

- browser/src/map/handler/Map.Keyboard.js
copy stopped working for slides from 5a1f572
Change-Id: I661c6b3109c4491abffa9ddc2e24971cdbc52079
> slide: avoid default cut/copy handing for slides

- browser/css/jsdialogs.css
https://github.com/CollaboraOnline/online/issues/11840
- Updated `.ui-listbox-arrow` comment for clarity.
- Removed the redundant dark mode color scheme for `.ui-listbox-arrow` class.
- Check for RTL direction and update `margin-inline-start` and `margin-inline-end` using `:dir(rtl)` under `.ui-listbox-arrow` for proper centering based on text direction.
- Use `border-inline-start` logical CSS  property instead of `border-left` in `.ui-combobox-button` to automatically detect text direction and the border properly.
The arrow's position is completely off, but the button itself is still functional. This is because the button's margins are statically given, and text direction is not checked for to account for this.
Also, the small border separating the grey button area (left side in picture …
> gh#11840 Support RTL centering, minor cleanup

- coolkitconfig-mobile.xcu
- coolkitconfig.xcu.in
share/registry/cjk*.xcd and share/registry/ctl*.xcd are not installed for COOL. Maybe it's a bug, but... These files are in the so called "brand" layer, in collaboraoffice-<lang> deb/rpm that we do not use. On the other hand, why would a feature like inserting vertical text depend on an optional language pack?
It is a valid use case when someone uses English UI and edits CJK/CTL text, or when someone wants to insert vertical text e.g. in English.
Change-Id: I2ed446aeff8a6a0a00c0a489eaa1d26778e1b61e
> Set CJK/CTL settings here for LOKit

- browser/css/jsdialogs.css
- browser/src/control/Control.DownloadProgress.js
- browser/src/control/Control.UIManager.ts
- browser/src/control/jsdialog/Util.SnackbarController.ts
- browser/src/control/jsdialog/Widget.Progressbar.js
Change-Id: Id86945ff9f75e90dabf944b0530ac9c1df7d916a
* Resolves: # 
Users weren’t seeing any progress indicator when progress info was missing, which could be confusing. Now there’s a smooth infinite animation to let users know something’s happening even if we don’t have exact progress yet.
Updated dialog title from "Download Selection" to "Paste Selection" to reflect user action, complementing existing "Downloading clipboard content" label.
[Screencast from 09-06-25 02:36:05.webm](https://github.com/user-attachments/assets/03fe4dd9-abe1-4f8d-a0db-be813f45b433)
> progressbar: add infinite loading animation when progress is unknown

- browser/js/global.js
- browser/src/core/Socket.js
This is a partial revert of Id3874e692d003e534648d06eeacd19fa9c5f2ce5. On iOS and Android this communication method works fine, but there is another platform which is technically considered "mobile" by the code: the gtk app. Since as we don't have an implementation of the cool:/cool/mobilesocket endpoint for it, when we ungated that for all mobile platforms it started blowing up. That's no good!
Change-Id: I8efee81f2c436585658d6c4affe91abff0844d74
* Resolves: # 
> fix(gtkapp): don't attempt to use mobilesocket

- common/Util.cpp
Fix `--enable-gtkapp` build after 2d83187c764ad69457bdb47efd6050b96af82da9 "add Util::trimMalloc" caused it to fail with
```
gtk/../common/Util.cpp:804:65: error: ‘RTLD_NEXT’ was not declared in this scope
804 |             auto symbol = reinterpret_cast<void(*)(void)>(dlsym(RTLD_NEXT, "MallocExtension_ReleaseFreeMemory"));
|                                                                 ^~~~~~~~~
gtk/../common/Util.cpp:804:59: error: ‘dlsym’ was not declared in this scope
804 |             auto symbol = reinterpret_cast<void(*)(void)>(dlsym(RTLD_NEXT, "MallocExtension_ReleaseFreeMemory"));
|                                                           ^~~~~
```
- [x ] I have run `make prettier-write` and formatted the code.
- [ x] All commits have Change-Id
- [ x] Documentation (manuals or …
> Fix --enable-gtkapp build

- browser/css/jsdialogs.css
Change-Id: I27b4d91845ab746d6e9d48a6961d5f1ab9f352e1
* Resolves: # 
Fix spinfield padding for RTL to properly space and center icons and value
> RTL: Fix spinfield padding for RTL to properly space and center icons and value

- browser/css/btns.css
- browser/css/jsdialogs.css
- browser/css/jssidebar.css
Change-Id: I9986af79314fb03a9dc69e0e1954d1cc9353f0aa
* Resolves: # 
The sidebar menubutton had inconsistent alignment and undesirable visual effects on hover:
- Items inside the button were not vertically centered.
- On hover, the font-size changed, causing the button to shrink slightly.
- A box-shadow was applied to the text, creating a jarring visual effect.
- These hover effects occasionally caused a flicker/glitch
**Changes**
- Center-aligned all items within the menubutton to ensure visual consistency.
- Added padding to sidebar menubutton for proper spacing and alignment.
- Removed the font-size change and box-shadow on hover to prevent visual shifts and glitches.
https://github.com/user-attachments/assets/36b5b1a4-7b22-4980-b128-b6c741b6178b …
> Fix menubutton alignment and styling inconsistencies

- gtk/Makefile.am
The cmake_list in gtk/Makefile.am had presumably gone stale for one reason or another, so just add more sources files to it until there are no further missing symbol linker errors.
> Revive --enable-gtkapp: Fix missing linker symbols

- kit/Kit.cpp
- happens when mout_jail_tree set to false and coolwsd tries to copy or link the files sharedpresets template instead of mounting it.
- only happens to `num_prespawn_children` as when prespawning we don't have correct sharedpreset directory
```log
Jun 22 01:22:15 server coolwsd[92790]: kit-92790-92790 2025-06-22
01:22:15.348554 +0200 [ kit_spare_038 ] ERR  Failed to get the realpath
of [/opt/cool/child-roots/91829-59db4560/tmp/sharedpresets/template]
(ENOENT: No such file or directory)| common/FileUtil-unix.cpp:63
Jun 22 01:22:15 server coolwsd[92790]: kit-92790-92790 2025-06-22
01:22:15.349576 +0200 [ kit_spare_038 ] ERR  linkOrCopy: nftw() failed
for '/opt/cool/child-roots/91829-59db4560/tmp/sharedpresets/template'|
kit/Kit.cpp:612
Jun 22 01:23:30 server coolwsd[92899]: kit-92899-92899 …
```
> wsd: fix: failed to get realpath of /tmp/sharedpresets/template

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
The 'title' attribute, which provides a native browser tooltip,
has been replaced with a custom 'cooltip' implementation.
Change-Id: I642a6636d1c1474d096b118d00506f9db23cbf25
> browser: remove the 'title' attribute from notebookbar Tabs

- scripts/contributors-credit.js
- as we did add all the beaver ilustrations in our IO page
- this patch will change the contributors card image to a new beaver image
Change-Id: I24f1ff115676dae53d4797ee5c6b13de0601e62d
* Resolves: # 
> Change contributors card image to a new beaver image

- browser/src/control/Control.NotebookbarImpress.js
- cypress_test/integration_tests/desktop/impress/slideshow_spec.js
moves the slideshow controls from View tab to Slide tab
Change-Id: I14e0957b17f4fad0f10be4b84b5cc91a64f91229
> Impress: Notebookbar: Add Slide tab

- browser/css/jsdialogs.css
Change-Id: Ia301f0e6790012fac7415a2c475f17b9d366560c
This will make the hover selection clearly visible.
> colorpicker: Improves color picker hover visibility with outline

- docker/from-packages/Dockerfile
Change-Id: Ifcd45544800ab45bb4782f2df3fd31cef98410db
* Resolves: # 
The run fails without it, since the user is now cool (1001) but start-collabora-online.sh is owned by root.
> docker: make sure start-collabora-online.sh is executable

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Util.Dropdown.js
- browser/src/control/jsdialog/Widget.MenuButton.js
- Move ARIA attributes from container divs to interactive elements
- Add role="group" to dropdown containers for proper composite control semantics
- Consolidate duplicate dropdown arrow creation logic
- Fix aria-haspopup placement to only apply when no interactive arrow exists
- Ensure aria-expanded is set on correct focusable elements
- Update element selection logic in dropdown utils to find proper ARIA target
- Remove redundant aria-haspopup from menubutton containers
Fixes accessibility issues where ARIA attributes were incorrectly placed on non-focusable wrapper elements instead of interactive buttons that actually toggle dropdowns.
Change-Id: I6dad052a8d20fe981afeb93c7ddb821b6b22372c
> accessibility: improve accessibility for split buttons and dropdown menus

- browser/Makefile.am
- browser/src/app/SlideshowMiddleware.ts
- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayerRenderer.ts
- kit/ChildSession.cpp
fixes: CollaboraOnline#11740
another version of zstd implementation was reverted due to regression causing some animation to not load properly. i.e text would not be visible when slide is transitioning
original commit: d82d7ca
reverted commit: cb45b4a
Change-Id: I0465527b62c75b5ef9960f3bb67cf6922b405650
> presentation: use zstd to compress bitmaps for presentations

- browser/admin/css/adminIntegratorSettings.css
- The `--co-border` color was not clearly visible when switching between Notebookbar and Compact views
- It looked fine in light mode but was barely visible in dark mode
- Replaced it with `--co-settings-text` for better contrast
- Enhances appearance and consistency across both light and dark themes
Change-Id: I30856c7e88c0a058610eac13fb526bcf4aa390ec
* Resolves: # 
> Browser Settings: Improve border color visibility for view selection

- wsd/AdminModel.hpp
...seemingly unused ever since their introduction in ada6a74dc019ba30f00e761452da4185ef91306a "loolwsd: Basic layout and interaction with AdminModel" (View::_start) and afb7e7dcff4657b34ffdde60f5ab84b225b25f8a "loolwsd: Make clients subscribe to commands" (Subscriber::_start)
Change-Id: I38f5770a78f5c333fdd24ad33bac9b8ac565e113
* Resolves: # 
> -Werror,-Wunused-private-field

- browser/src/control/Control.NotebookbarImpress.js
Change-Id: I358fc41c0fbec9c2c2649efc01a49e8052bbb957
- Removed "Slide Layout", "Slide Transition" , "Animation", "Navigator", "Select All", "Object align", "Align"
buttons from the Layout tab as per design direction 
- Moved the "Interaction" button to the Picture and Shape contextual tabs
> Impress: Restructure layout tab buttons and relocate "Interaction"

- test/fakesockettest.cpp
FakeSocketTest::testBasic.../common/Log.cpp:661:16: runtime error: downcast of address 0x6070000004f0 which does not point to an object of type 'GenericLogger'
0x6070000004f0: note: object is of type 'Poco::Logger'
00 00 00 00  28 db ac 9a 32 7f 00 00  70 db ac 9a 32 7f 00 00  01 00 00 00 be be be be  18 05 00 00
^~~~~~~~~~~~~~~~~~~~~~~
vptr for 'Poco::Logger'
#0 0x55c44738f721 in Log::logger() /home/vmiklos/git/collaboraonline/online-san/test/../common/Log.cpp:661:16
#1 0x55c44738f2b2 in Log::log(Log::Level, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/vmiklos/git/collaboraonline/online-san/test/../common/Log.cpp:812:9
#2 0x55c4472b25d4 in FakeSocketTest::testBasic() /home/vmiklos/git/collaboraonline/online-san/test/fakesockettest.cpp:78:5 …
> fakesockettest: fix bad downcast

- browser/src/control/Control.Command.js
Changes in JSDialog require the use of a layouting task to
modify the DOM.
Also fix the markup.
Change-Id: I1274302311b289cf652349040d024f723995a965
* Resolves: # 
> Fix the feature unlock dialog

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.Frame.js
* For  Writer -> Format -> Page Style -> Area -> Image dialog to work, we need the following gerrit patch: https://gerrit.libreoffice.org/c/core/+/187592 to work as expected.
* For rest, it should work as expected.
Some labels like “Tiling Position:” (id="label9") are visually grouped with the two input fields X-Offset
and Y-Offset, but they are not programmatically associated with them. This causes screen readers to
miss the group context and violates WCAG’s requirement for conveying relationships in a
programmatic way.
here are few examples of before vs after:
This PR also adds missing grid space for dialog elements
Before:
After:
> Accessibility: form control group support via fieldset and legend

- autogen.py
core.git autogen.sh is actually a Perl script, and then that can read
options from autogen.input, in a similar style. This has the benefit
that you can track your options as a config file, e.g. comment out lines
while you experiment, etc.
Here provide something similar, but keep autogen.sh as a shell script
and rather provide an autogen.py wrapper around it, so those who like
autogen.input can enjoy it.
Change-Id: I5f65c0f375da2c70ac97acb139ef372d5e1f20c2
> autogen: add a way to read options from an autogen.input file

- browser/src/control/Control.NotebookbarCalc.js
It seems users hunt for the keyword "page" when searching for layout
related actions and having only "Layout" seems to induce the
spreadsheet user in thinking it's related to formatting/styling stuff.
Change-Id: If5ee16574beedd3b5f0fe2d0f835a3d948bbe8a0
> Calc: Rename Layout Tab to Page Layout

- browser/html/cool.html.m4
Also add m4_dnl to the ends to avoid empty lines in the generated
output.
Change-Id: Iff34af04aab163d6728ce6853e470d0dbd86fcf9
> Define MOBILEAPP early to avoid %BROWSER_VIEWPORT% in apps

- net/NetUtil.cpp
- net/NetUtil.hpp
- net/WebSocketHandler.hpp
- test/NetUtilWhiteBoxTests.cpp
- tools/WebSocketDump.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/Process.hpp
https: //github.com/CollaboraOnline/online/issues/12095
Change-Id: Ia517d9ed52e57bfa45c6a22d906c5ae99e947c26
* Resolves: # 
> allow implied port numbers to equal explicit ones

- browser/src/canvas/sections/URLPopUpSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.StateChanges.js
Use the link info (list of rectangles and urls) received from core to
show user a link pop-up in PDF like in other documents.
Change-Id: Ic348d7e2d5a559deafbad5ab5c845c036d8d79e8
> pdf: handle handle links like other documents

- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/layer/tile/CanvasTileLayer.js
We immediately show the canvas, but a default canvas is black and looks bad. We shouldn't show the canvas until it's sized correctly and populated with content.
> Fix black flash on startup of calc (and possibly others)

- dev-notes/dependency-issues.md
- wsd/ClientSession.cpp
This is a problem since:
https://github.com/CollaboraOnline/online/pull/11485
But only manifests when built against poco < 1.13.3 https://github.com/pocoproject/poco/issues/4492
Because Poco::BasicMemoryStreamBuf::seekpos wasn't implemented before that version.  This can be worked around with the two argument variant of seekp which uses Poco::BasicMemoryStreamBuf::seekoff which was implemented.
Change-Id: Ifdcf03b5613db93c9aaf6b430f9d26e61b4ff0a5
* Resolves: # 
> fix inserting of origin in selection html

- wasm/Makefile.am
...as main in wasm/wasmapp.cpp just spawns a detached thread that does all the work, and then exits (effectively doing manually what PROXY_TO_PTHREAD would do automatically for us), so we won't block the browser's main thread (which would block further threads from spawning, for which PTHREAD_POOL_SIZE is a workaround).
But that would lead to harmless console warnings
> Tried to spawn a new thread, but the thread pool is exhausted.
> This might result in a deadlock unless some threads eventually exit or the code explicitly breaks out to the event loop.
> If you want to increase the pool size, use setting `-sPTHREAD_POOL_SIZE=...`.
> If you want to throw an explicit error instead of the risk of deadlocking in those cases, use setting `-sPTHREAD_POOL_SIZE_STRICT=2`.
whenever a new thread is …
> Wasm: No need for preallocated threads via PTHREAD_POOL_SIZE

- browser/src/control/Control.JSDialogBuilder.js
"The input field (posoffx-input) has a visible label (“X-Offset:”) linked using a <label for="...">
element. However, the aria-label="0%" on the input overrides the label association. As a result,
assistive technologies do not announce the visible “X-Offset:” label but instead use the aria-label value,
which is not descriptive."
Change-Id: I1430fa7bab875e46cf03b3c9f83fe88e1db48ca2
> browser: accessibility: remove aria-label from spinbutton input element

- browser/src/app/TilesMiddleware.ts
This is unpleasant; it seems to be a workaround to wait for a tilecombine result as a zero-length (imgsize=1) delta to arrive in order to work out that we need to de-hydrate the updated while off-screen, so non-de-hydrated tile data that we want to render.
Essentially this undoes this hunk from
commit 947fe72f7c293bfe0ea41340ee86d88184855ab9
-		var hasContent = img != null;
+		var hasContent = img != null && img.rawData.length > 0;
Without appending zero length deltas to the RawDelta list. It should be further investigated later.
Change-Id: I7a581a1c4d1aca495b43d48e344f33f00a31651f
* Resolves: # 
> Ensure we de-hydrate tiles even of 0 length as we used to.

- common/SigUtil-dummy.cpp
- common/SigUtil-server.cpp
- common/SigUtil.hpp
- ios/Mobile.xcodeproj/project.pbxproj
- wsd/COOLWSD.cpp
This fixes a regression from CollaboraOnline/online#11845 which incorrectly excluded shutdown/termination flags from all mobile builds when previously they were excluded from iOS only.
Doing this would save the document properly but kit would never shut down, leaving the user with a perpetual document closing message...
This fix notably doesn't fix some other similar issues we've had with the document lifecycle: in particular, you can't open a document with an app instance that already had a document open even if you close it with this patch added
Change-Id: Ic283d96a94b0e91c795e0bc66d890720e55db836
* Resolves: # 
> fix(android): do not hang on document close

- browser/js/global.js
- browser/src/core/Socket.js
This fixes a regression from #12037
When a password protected document is opened, Collabora Online tries to reopen the socket in order to reload the document...
...Unfortunately this isn't possible with the mobile socket...
...Luckily that also wasn't possible with the FakeWebSocket so there is a mobile-specific route to load password protected documents anyway...
...Unfortunately we accidentally kept in code that can close the socket on a passworded document, leading to the socket being closed and never properly re-opened
It may be nice to make this work one day, but for now let's just stop the MobileSocket from trying to close or reopen
* Resolves: # 
> fix(mobile): fix password-protected documents

- browser/src/canvas/CanvasSectionProps.js
- browser/src/canvas/sections/CalcValidityDropDownSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Mouse.js
Issue:
* For validity dropdown, mouse click is sent to core side.
* Core side understands that the user clicked on the validity dropdown.
* It sends the required information back.
* But the clickable area for the dropdown is a little small on the core side.
* Users sometimes click close to the edges of the dropdown arrow.
* In that case, click is not recognized by the core side.
Solution:
* Handle the click on the Online side.
* Send the center of the dropdown arrow to the core side with click event.
* It provides larger clickable area for the dropdown.
Change-Id: Ib48f7266f7b0d147761eaccd647caf39df0d6550
* Resolves: # 
> Calc: Use section borders for validity dropdown.

- wsd/ClientSession.cpp
'line' is unused and we seek back to the start after reading it, so drop this uselessness. There is no scenario where we are not at the start of the stream on calling postProcessCopyPayload.
Change-Id: I65a8b0c83729d801997712ff102b8112629b992b
* Resolves: # 
> remove redundant code

- wsd/COOLWSD.cpp
This fixes a regression from Ie0b68e0b1da83987214a983bf36c7556cc664a8e
In that change, we stopped running Util::forcedExit on a mobile exit
which appears to be a side-effect of assuming it was only used to stop
a Poco SSL deadlock. Unfortunately it seems to have been load-bearing in
closing down the Android app's document (despite that not using SSL) and 
without it we would be left in a state where no further documents could
be opened
Luckily it's a pretty easy fix - adding this line back (gated for mobile
as we don't need it on a server) corrects the problem
Change-Id: Ieab70b0a51016efa8dd7e13fbb90f38711320eea
To test this you probably want #12363, so I have used it as a base for this commit
> fix(android): allow opening documents after close

- browser/css/toolbar.css
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Definitions.Menu.ts
- browser/src/unocommands.js
- Add Brightness menubutton
- Add Contrast menubutton
- Add Transparency menubutton
- Add Color Mode menubutton
- Add labels for menubuttons
- Add icons with different css filters
> Notebookbar: Picture context tab: Add pre-canned menubuttons

- browser/css/jsdialogs.css
Change-Id: I4935768edb3bf4a1c9a7039aa13ab1ea7f04fb2b
* Resolves: # 
Auto filter Checklist dropdown height was being reset when more options are selected
https://github.com/user-attachments/assets/9e4edb1a-dd9c-4650-964b-0b0a490f2dc8
> Fix autofilter checklist box height in Calc by overriding modal min-height

- browser/src/canvas/sections/CalcValidityDropDownSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
Issue:
Its scale is calculated wrong when dpiScale is different than one and OS-level display scale is used.
Change-Id: I6921b62d90b9b9ab356420918a7cbd0464768d48
* Resolves: # 
> Scale the calc validity dropwdown arrow's size with dpiScale.

- browser/src/control/Control.NotebookbarImpress.js
This is a trivial backport of #12429
Video insertion appears not to work in either iOS or Android
- in Android it does nothing
- in iOS it gives an "invalid syntax" error
- in iOS if you click the "take video" button it crashes the app, losing unsaved data
These are not ideal effects - particularly not the crash of the app which is highly undesirable.
In the future we will add this functionality back, but right now the "crash the app and lose my data" button needs to be gone for the 25.04.3 release
Change-Id: I6a6a6964b411be3c65b57e9b46b2a3a9b2b01c1c
* Resolves: # 
> backport(co-25.04-mobile): fix(mobile): disable video insertion

- browser/src/control/Control.NotebookbarImpress.js
Video insertion appears not to work in either iOS or Android
- in Android it does nothing
- in iOS it gives an "invalid syntax" error
- in iOS if you click the "take video" button it crashes the app, losing unsaved data
These are not ideal effects - particularly not the crash of the app which is highly undesirable.
In the future we will add this functionality back, but right now the "crash the app and lose my data" button needs to be gone for the 25.04.3 release
Change-Id: I6a6a6964b411be3c65b57e9b46b2a3a9b2b01c1c
* Resolves: # 
> fix(mobile): disable video insertion

- browser/src/control/jsdialog/Widget.HTMLContent.ts
With the following changes:
25.04 https://gerrit.libreoffice.org/c/core/+/187669
master https://gerrit.libreoffice.org/c/core/+/187733
We now have a dialog that gets open when user clicks the status bar's
pager. Update the tooltip to increase discoverability of the new feature.
Change-Id: Ieda2040c2725b54250ce5bb9aa2e3301fbef68a7
> Status bar: Pager: Improve Tooltip to reflect the new functionality

- browser/src/canvas/sections/AutoFillMarkerSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
We can't write/autofill in readonly mode so showing the blinking cursor and autofill handle is confusing for users.
I've hidden sections here by introducing an accessor over the showSection property as otherwise various other things will interfere with the showing/hiding even in readonly mode. The cursor is the exception: it is hidden by making sure that when it updates it will not be shown if we are in readonly mode
I haven't hidden anything that could still theoretically be used. For example, you can copy from the cell cursor and selecting text/cells/etc. still works fine so I've avoided hiding the cell cursor or selection handes.
If you're testing this out you may run across another bug where entering readonly mode improperly deselects the content, leaving you with some handles …
> feat(readonly): hide uninteractible elements

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- cypress_test/integration_tests/common/desktop_helper.js
- **browser: accessibility: convert color picker entry to radio button group**
- **browser: accessibility: adjust CSS properties for color picker entry**
- **browser: accessibility: remove explicit tabindex from focusable button**
- **browser: accessibility: add aria-label to color picker entry**
* Resolves: # 
> color picker entry

- browser/images/dark/lc_groupsparklines.svg
- browser/images/dark/lc_ungroupsparklines.svg
- browser/images/lc_groupsparklines.svg
- browser/images/lc_ungroupsparklines.svg
Change-Id: I0810c414aaf8fa276bfe8ac3cc15d7ed912cc0d2
* Resolves: # 
Updated Sparkline contextual group and ungroup icons
> Updated sparkline contexual group and ungroup icons

- browser/css/jsdialogs.css
Change-Id: Ic8a5376dc7022eb13803d24cd20e96822619b2ab
* Resolves: # 
accompanies https://gerrit.libreoffice.org/c/core/+/188305. the buttons are center aligned so i added some css to justify them at the start.
> place find replace dialog tab buttons at the start and not in the center

- browser/src/control/Control.ContextToolbar.ts
problem:
incorrect coordinates were used in equation. now we use css pixel pos
Change-Id: I92de7d0d182ee650adfb38fd3eaef57cb08d0e29
*
> context toolbar: fix wrong positioning with zoom

- browser/css/notebookbar.css
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarImpress.js
Change-Id: I2b2db04f78c882036127b54020dc53e4b5fa33f7
I have hard-coded the color in css as I didn't see any other color being used for a label at the top bar
> Notebookbar: add inline label to Share button on the top bar

- browser/css/jssidebar.css
Style previews are shown always in true colors so the background color is white. If image previews are off we need to use black font to make it visible.
> style previews: use black text on white in dark mode

- browser/js/global.js
- browser/src/main.js
- wasm/wasmapp.cpp
- wsd/COOLWSD.cpp
...in preparation of allowing the Wasm code to run in a shared worker (where the global object will be some kind of WorkerGlobalScope rather than a Window).
(Yes, the silly ESLint that is run on browser/src/main.js would complain about "error  'globalThis' is not defined  no-undef" unless explicitly listed in a /* global */ comment.)
Change-Id: I127d27b11aaf8ef29b1cfb8beae9ee4c858e38f2
* Resolves: # 
> Replace some uses of window with globalThis

- browser/css/btns.css
- browser/css/device-desktop.css
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/common/repair_document_helper.js
- cypress_test/integration_tests/desktop/draw/esign_spec.js
- cypress_test/integration_tests/desktop/draw/sign_spec.js
- cypress_test/integration_tests/desktop/writer/file_properties_spec.js
- cypress_test/integration_tests/desktop/writer/sign_spec.js
- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- cypress_test/integration_tests/mobile/impress/delete_objects_spec.js
- cypress_test/integration_tests/mobile/writer/insert_content_control_spec.js
- cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
- cypress_test/integration_tests/multiuser/impress/repair_document_spec.js
Change-Id: I16c15dd1807b81a1e56cb5353ab17095913caa5c
* Resolves: # 
-This update makes the Find and Replace buttons visually resemble tabs, improving consistency with common UI patterns.
The Replace tab is highlighted conditionally based on the visibility of the Replace frame.
https://github.com/user-attachments/assets/e66cadb7-2072-4ca2-8ba5-b15ea3ca38c3
> Style buttons in Find/Replace and Properties dialogs as tabs

- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Definitions.Menu.ts
Re-use the widget from Calc, minus the button which opens the 'format cell' dialog
> Add border tool to Writer Notebookbar

- configure.ac
Unclear if the POCO_UNBUNDLED is actually required with version 1.14 but the header Poco/XML/ParserEngine.h definitely doesn't exist in 1.14.
Change-Id: I02045bb825c1026024e0712e7d01c85054c5fa94
* Resolves: regression from previous PR
> configure: use header Poco/SAX/SAXParser.h which also exists in 1.14

- coolwsd-systemplate-setup
- kit/Kit.cpp
I've previously been having to use [this patch from CollaboraOnline/nix-build-support](https://github.com/CollaboraOnline/nix-build-support/blob/main/patches/online/0001-build-add-nix-build-support.patch) and the command `sudo mount --bind /nix systemplate/nix` to make Collabora run
I would like to not have to do that anymore.
I'm expecting these changes to do very little outside of NixOS, but drastically improve the experience for anyone trying to develop Collabora Online on NixOS
> feat: improve NixOS support

- wsd/ClientRequestDispatcher.cpp
since:
commit f1fe0ba405965e1f7ec8ac01b702631726471729
Date:   Wed Apr 30 20:19:40 2025 +0100
accumulate POST messages in a temp stream before dispatching
the consumer assumes nothing was consumed yet and the socket can be passed to another handler and has full contents of message so far still available
Change-Id: I7132a4b8dcb41bfad5330546c8a88e5514a9ab69
* Resolves: # 
> fix richdocuments code

- browser/css/jsdialogs.css
Change-Id: I9d7b8fab62a97a816e117b8002ff8cfe4300cc41
The placement of visible labels that are not in close proximity to their corresponding input fields can
impact the usability and accessibility for users, especially those with cognitive impairments or visual
impairments. It's important to group labels and input fields together to facilitate the identification and
understanding of the function of each input field.
It turns out that after: https://github.com/CollaboraOnline/online/pull/12314, we can just remove the `width: 100%` to put labels closer to their input fields and for `Area` tab, we don't need really need it.
here are screenshots for reference:
It will be same for `Area` tab.
> accessibility: adjusted width for jsdialog in format area ensuring labels are near to their input field

- wsd/ClientRequestDispatcher.cpp
Change-Id: I4e497d0f3a4e985ced7cafb0cf0e7ddc70f91075
* Resolves: #-
This type does not exist in C, and only in some gnu headers for compatibility. I see no reason to keep using it. The usage also causes issues on FreeBSD.
I cannot run `make check` as I need to compile with `--without-system-nss`, which I need to compile in freeBSD atm.
I have more small patches incoming to allow running collabora-online on freebsd! I also have a patch which I don't think you want to include, I am working on a proper fix to upstream later.
> Remove usage of ulong type

- common/Util-server.cpp
- test/WhiteBoxTests.cpp
- tools/KitClient.cpp
Change-Id: Ic706155750f906bbecec7d57b437a99fd998a6b0
* Resolves: # 
unistd.h is probably included indirectly on linux, but should be included direclty for good measure. The include is absolutely needed on FreeBSD. E.G.:
https://man7.org/linux/man-pages/man2/getpagesize.2.html https://man.freebsd.org/cgi/man.cgi?getpid(2)
Environ is sometimes non-standard conventionally maybe included mayhaps in unistd.h, but not always. See:
https://man.freebsd.org/cgi/man.cgi?environ(7)
https://man7.org/linux/man-pages/man7/environ.7.html
Cannot run make check, can confirm results in working setup on FreeBSD
> [FreeBSD/correctness]  Include unistd.h and declare environ

- browser/src/control/Control.ContextToolbar.ts
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.ts
- browser/src/core/Socket.js
problem:
in compact view mode notebookbar is not initialized this causes font box(s) to not work and render fonts
Change-Id: Ifc87e31a0e576100cd68d1f19680e2041d1a3df4
* Resolves: # 
> context toolbar: initialize notebookbar in core if needed

- cypress_test/integration_tests/desktop/impress/jsdialog_spec.js
- after incompatible core change related to sidebar
for c++ tests requires core change: https://gerrit.libreoffice.org/c/core/+/189034
> cypress: disable failing test in impress/jsdialog_spec.js

- browser/html/framed.doc.html
- browser/src/control/Control.ContextToolbar.ts
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/map/handler/Map.WOPI.js
This works with the existing "Insert_Button" message. Add the property 'target': 'context-toolbar' to add a button to the contextual toolbar
Change-Id: I1681d5b0499f2c9bb438524b19dfb62dadadf9a4
For Message: `Insert_ContextualButton`, and
Values: 
```
{"id":"somebutton", "imgurl":"lc_printgrid.svg", "unoCommand":"customCommand", "hint":"tooltip"}
```
, the following button will be added
Also added an example button to postmessage demo page:
> context-toolbar: allow integrators to add a button via PostMessage

- browser/css/jsdialogs.css
- enhanced layout and styling of the color window by using a grid layout with consistent spacing and limit the main color palette to certain height to enable scrollbar if needed
- improved color picker's hover and selection visibility with outline and border
- placeholder texts were hidden to prevent layout shifts caused by lazy loading of color icons (icon-view entries)
core patch(requires): https://gerrit.libreoffice.org/c/core/+/188921
Change-Id: I4d169eb35d9bae17dde4c0effb60422ed53da4d9
> iconview: improve color palette UI for color window

- browser/css/notebookbar.css
Set Height and Width for icon to make sure the ratio is kept 1:1 and
that they are properly rendered in different browsers.
Change-Id: I1ecfa9e55eacdf99bcd2082db126edc3c518c1df
> Context toolbar: Fix button sizes

- browser/src/slideshow/engine/SlideShowNavigator.ts
slideshow: Skip animations/transitions on rapid Next presses
When the user rapidly presses the Next button or holds it down, ongoing animations and transitions are now skipped to improve responsiveness and prevent lag. This ensures a smoother experience when navigating slides quickly.
Change-Id: I0045dcf39bdb8692b56db247a8f0ad07fa63bb95
* Resolves: # 
> slideshow: Skip animations/transitions on rapid Next presses

- browser/css/device-desktop.css
- browser/src/canvas/sections/TextSelectionHandleSection.ts
- cypress_test/integration_tests/desktop/writer/copy_paste_spec.js
This is a **nontrivial** backport of #12508: since as #12508 depended on #12455 (which is not getting backported) I have adapted the code to work with the code that is currently in distro/collabora/co-25.04
This reimplements the I6544845526c2e70bee7d6e3b193e9fb4931422c6's intent but using the existing system to show/hide the teardrop
I do this in a similar way to my recent work hiding uninteractible elements from #12422, albeit without an event to switch over when we change from mouse to touch or vice-versa time. The lack of an event is because the selection handles aren't properly moved into place when they are hidden and there are some finnicky events (where sometimes we end up detecting touch events as having some mouse events too) on the mouse -> touch switch. We may change this …
> backport(co-25.04): fix(teardrop): correct non-desktop hiding

- net/Socket.cpp
Change-Id: I378e70541e46a4aa4fb9c198233a8ab7f09e077f
* Resolves: # 
This just precasts the LHS to ssize_t, as that is the correct type.
The compile error this fixes is:
```
:1624:42: error: use of overloaded operator '+' is ambiguous (with operand types 'pos_type' (aka 'fpos<__mbstate_t>') and 'std::streamsize' (aka 'long'))
1624 |     ssize_t headerSize = message.tellg() + static_cast<std::streamsize>(marker.size());
|                          ~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
with compiler FreeBSD clang version 19.1.7
not sure if this has anything to do with FreeBSD or specific compiler settings (sigh).
Can confirm this results in a working setup on FreeBSD, no make check
> [FreeBSD(?)] Rework the casting for the header size

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
slideshow: Enable video control from presenter console
Add click event handling to the presenter console canvas to allow video playback control from the presenter view. Previously, video controls only worked from the main slideshow canvas.
The coordinate normalization ensures clicks work regardless of canvas size differences between presenter console and main slideshow window.
Change-Id: I4235c217515269ceb8fee2bb8f380261682ef453
* Resolves: # 
https://github.com/user-attachments/assets/615529a8-a2da-49ef-82a9-b6c1a2f2df58
> slideshow: Enable video control from presenter console

- browser/src/canvas/sections/CellCursorSection.ts
- browser/src/canvas/sections/OtherViewCellCursorSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
Issue:
* When the cell cursor drawing overlaps with the split panes, the cursor drawing overlaps with the other cells.
* To reproduce, set split panes. Click on an edge cell that is not frozen. Scroll the view slightly to the right.
Fix:
* Check if cursor drawing overlaps with other cells.
Change-Id: I5a8850cfd55ed6bc14e5cb5576679e94dbe7f441
* Resolves: # 
> Calc: Adjust cell cursor drawing according to split panes when needed.

- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
Before this commit when running
make -C cypress_test run-desktop spec=calc/jsdialog_spec.js
we were getting the following:
Error:
cy:command ✔  cGet	#Help-tab-label
cy:command ✔  click
cy:command ✔  cGet	#Help
cy:command ✔  click
cy:command ✔  cGet	#online-help-content
cy:command ✘  assert	expected **#online-help-content** to exist in
the DOM
Because the button is not called #Help but instead #online-help
Change-Id: Ic8bceab543b40f871e8eff1478af94805074a41f
> Cypress: Fix open help dialog test

- browser/src/control/Control.NotebookbarImpress.js
- Remove insert comment: this button is already present in multiple
places (Insert tab; review tab; contextual toolbar; right click menu)
- Remove Duplicated fullscreen presentation: We now have dedicated Slide Show tab for
that and it is also present in the the slide sorter
- Remove Duplicated slide: already present in multiple places
including in the slide sorter
- Move the inter text box to the place where the duplicated slide
button was in so to reduce number of groups
Change-Id: I9bfc893628a873bd3e14236f34f91972614e57f8
> Impress: Home tab: Reduce number of buttons

- browser/src/control/Control.ContextToolbar.ts
- For now we need to disable contextual toolbar in calc.
-  When working with spreadsheets there are more things at play here that appear/respond to mouse cursor changes
- autocomplete formula and its variations, drag to fill copy or fill series, editing formula by selecting other cells
- Thus, it's important to don't add more friction to any of these actions.
Change-Id: I2b95a7d28215184ecea1aa3f6e988ef5f69909d1
* Resolves: # 
> Calc: Disable contextual toolbar

- browser/css/notebookbar.css
With the introduction of groups and the overflow button we have now
dorpdowns that appear with other buttons inside when there is no space
to show them all. Nevertheless, there will be still cases where the
window is even narrower. So, let's make it scrollable.
Also updates the scroll-wrapper height that was missing from
9efe7c23533fae8def368a9e3bb884012969de19 where the following was also
changed:
```javascript
.hasnotebookbar > #toolbar-row {
-       height: 74px;
+       height: 82px;
}
```
Change-Id: I7818067d1830552142b4743f1fb549aa3f74bdcc
> Tabbed view: Make it horizontally scrollable if there is not space

- browser/css/jsdialogs.css
- browser/css/override-smartmenus.css
- browser/css/toolbar.css
- browser/src/control/Control.TopToolbar.js
- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
1. Compact mode: Move out separator out of the overflow manager div
- Instead of adding separator inside group we should separate it out side the manager div
- this will fix issue when we do resize of screen
- on resize screen before this patch it was including the separator within other options in dropdown which is not needed in that compact view
2. Add some breathing space after fontsizecombobox for compact mode
- Before this change fontsizecombobox and the next element which in this case is separator glued with each other on high zoom
- so by adding minor margin will fix the breathing issues
3. On zoom 200% the last updated status time in navigation shifted to next row.
- In compact mode when we do 200% zoom in the navigation bar the last updated time jumps to next line and make …
> Overflow icons: compact mode

- browser/src/control/jsdialog/Util.Shortcuts.ts
Change-Id: I05537e1a72b9eef5bf7210447213450b3f6cae2d
> Add missing Format Cell keyboard shortcut to the toolbar's tooltips

- browser/src/main.js
...that was introduced in a7d6d1debc46f618733e180bd1b8ff87e7303ab7 "wasm: pass the docURL to the wasm app", alongside Module.arguments, for no apparent reason (Emscripten only uses Module.arguments, see
<https://emscripten.org/docs/api_reference/module.html#Module.arguments>)
Change-Id: Ic7b727e82b567b422c30fdd1aa4193f7c889f2cb
* Resolves: # 
> Drop unused Module.arguments_ property

- browser/src/slideshow/SlideShowPresenter.ts
Issue:
* Auto color and background color is not working in dark mode.
* So the slides may have invisible text.
* Thinking that slides should have their own background colors and color scheme, dark mode switch may not be good in terms of design.
* So we set the dark mode off before start and set it back to on after user ends the slide show.
Change-Id: I36e47d6867abecbecd0977e558347a8aea6e39e0
* Resolves: # 
> Impress slideshow: Check if dark mode is active before start.

- browser/src/control/jsdialog/Widget.ColorPickerButton.js
- Previously, changing a color (e.g., border color in Calc) from its properties dialog did not update the corresponding color icon in the sidebar.
- This patch updates the `colorLastSelection` document state property based on incoming UNO command values, ensuring the sidebar reflects color changes made via jsdialog.
- A simple change that resolves all cases where sidebar colors failed to update after being changed from jsdialog.
Change-Id: I7eb011b58120bef2cbb29a8f53027094b76503e3
* Resolves: # 
> Fix: Sidebar color icons now update when changed via jsdialog

- browser/src/control/Control.NotebookbarCalc.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
- Rename Character group to Font as it seems easier on the user both
in terms of understanding but more crucial when eye scanning
- Rename Merge Cells to what the buttons actually does: "Merge &
Center"
- Place it under alignment group
- Shorten "Number Format" to "Number" to save space
- Rename generic "Insert" group to a more semantic one "Cells" as the
actions in it are not just for inserting
- Move Conditional format button into the existing Style group to save
space and to help user understand that conditional formatting is
change the style according to conditionals
- Move Search related buttons into a more generic group with the sort
and filter called "Editing" as it seems to be what the users search
when looking and it also saves space
Signed-off-by: Pedro Pinto Silva …
> Calc: Home tab: Reduce number of buttons

- browser/src/canvas/sections/CellCursorSection.ts
CellCursorSection.adjustSizePos (CellCursorSection.ts:40)
CellCursorSection.onDraw (CellCursorSection.ts:69)
CanvasSectionContainer.drawSections (CanvasSectionContainer.ts:1796)
CanvasSectionContainer.redrawCallback (CanvasSectionContainer.ts:662)
requestAnimationFrame
CanvasSectionContainer.requestReDraw (CanvasSectionContainer.ts:670)
Header._updateCanvas (Control.Header.ts:145)
Evented.fire (Events.ts:280)
fire (Events.js:25)
SplitPanesContext.setSplitPos (SplitPanesContext.ts:73)
CalcSplitPanesContext.setSplitPosFromCell (CalcSplitPanesContext.ts:47)
setSplitPosFromCell (CalcTileLayer.js:833)
_onSplitStateChanged (CalcTileLayer.js:961)
_onCommandStateChanged (CalcTileLayer.js:897)
Evented.fire (Events.ts:280)
fire (Events.js:25)
_onStateChangedMsg (CanvasTileLayer.js:2201)
_onMessage …
> app.activeDocument seen as undefined:

- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Definitions.Menu.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.MenuButton.js
- browser/src/control/jsdialog/Widget.OverflowGroup.ts
- browser/src/map/handler/Map.WOPI.js
- cypress_test/integration_tests/common/desktop_helper.js
- The InsertImage buttons are of type menubutton.
- Overflow group icon can be definied statically with `icon`.
- Disable menu button that have no menu entries
- This fixes a regression introduced when refactoring the UI code and further when relayouting UI.
Change-Id: I97fd063f66c3edda1c2e311a4c3d6c1fb5c71452
* Resolves: # 
> When InsertLocalImage is false, disable the feature

- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/src/control/Control.NotebookbarWriter.js
commit 127c86f48a528d44efc0923f3abeffb4037e3405 (HEAD -> master, origin/private/pedro/writer-home-tab-reduce-btns, private/pedro/writer-home-tab-reduce-btns)
Date:   Thu Aug 14 13:02:24 2025 +0200
Tabbed view: Overflow group labels: reduce font size
These labels are there just for extra help and thus they shouldn't be
at the same size as the default button labels etc
Change-Id: I243f96c8c124c7557d2c3de9dba69e137c29ff07
commit df6f40cbec5f501aea7d8799cce844beea0212ac
Date:   Thu Aug 14 13:00:06 2025 +0200
Writer: Home tab: Reduce number of buttons
- Remove insert comment: this button is already present in multiple
places …
> Writer: Home tab: Reduce number of buttons 

- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/css/mobilewizard.css
- browser/src/control/Toolbar.js
- browser/src/docdispatcher.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
- cypress_test/integration_tests/mobile/writer/insert_object_spec.js
Change-Id: I6774fa507ec1e51e9c94894337b35c2604b665b8
Use the CORE dialog for creating hyperlinks in all cases; previously, it was only used for calc and when right clicking on text. The CORE dialog has a few benefits, such as allowing mail links and having a name field (which so only works on writer text). It also removes a bug where a race condition causes the hyperlink text box to not receive any text.
Replace calls to showHyperlinkDialog() with sendUnoCommand('.uno:HyperlinkDialog').
Change CORE to allow image links to be added to draw/impress
Change CORE to make dialog only show relevant fields (e.g. no name or text fields for images)
Allow image links to be clickable in draw/impress online (without this, they can only be used after exporting)
> Always use core dialog for sethyperlinkdialog

- browser/css/cool.css
This is a trivial backport of #12580
Previously the hyperlink preview text wouldn't change color in dark mode which led to black text on a dark background. If we make it dependent on our CSS variables then we will be able to read it in any theme
Change-Id: I6a6a6964154cd34c3c1fe15577b4c1bcf83d4656
* Resolves: # 
> backport(co-25.04): fix(dark): make hyperlink preview readable

- browser/src/app/ViewLayout.ts
- browser/src/canvas/sections/ScrollSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/impress/scrolling_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
We need to make the scroll section document-view agnostic.
Change-Id: I80236c67f0dbd362611e1dbb9a66822580edd0b8
* Resolves: # 
> Move the scroll related code into ViewLayout base class.

- coolkitconfig-mobile.xcu
- coolkitconfig.xcu.in
There is (debug) log spam of:
warn:sfx.sidebar ... sfx2/source/sidebar/ResourceManager.cxx:537:
expecting three or four values per ContextList entry, separated by comma, entries: any, default, hidden
This suppreses that by using the correct format for this entry. The original in officecfg/registry/data/org/openoffice/Office/UI/Sidebar.xcu is "any, Media,  visible"
Change-Id: I863a401558028a9e145d13d72189c677049b6093
* Resolves: # 
> silence 'expecting three or four values per ContextList entry' spam

- browser/src/layer/tile/CanvasTileLayer.js
It assumes that text selection and cell selection cannot exist simultaneously.
But they can exist simultaneously:
* Select a range of cells.
* Start editing one of the selected cells with F2 (still keeping the cell selection set).
* Select a portion of the text from currently edited cell.
* So text selection and cell selection exist at the same time.
This issue also causes copy & paste operation to not work on some systems.
Change-Id: I022d4a9354c658b92b181e128a8f6aa40d16709d
* Resolves: # 
> Cool#12606 Remove extra condition of textSelectionMsg.

- browser/src/control/Control.NavigatorPanel.ts
- browser/src/control/Control.StatusBar.js
- browser/src/control/Control.UIManager.ts
- cypress_test/integration_tests/common/writer_helper.js
- cypress_test/integration_tests/desktop/writer/focus_spec.js
- cypress_test/integration_tests/desktop/writer/quickfind_spec.js
- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- cypress_test/integration_tests/multiuser/writer/cursor_spec.js
* Resolves: # 
Once #12511 is merged, use the unified search bar on `Ctrl+F` and `Home > Search` rather than the (current) status bar search.
> Simplify Status bar

- browser/src/slideshow/RenderContext.ts
Handle cross-window CanvasRenderingContext2D instanceof failures in windowed presentations by adding constructor name fallback check for iframe contexts.
Change-Id: Ib215ba2dede4ca4e763ffeba8cc325cb727d95ab
* Resolves: # 
> [Backport] slideshow: Fix 2D context detection across iframe boundaries

- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/jsdialog/Definitions.Menu.ts
- browser/src/map/handler/Map.WOPI.js
Also the InsertMedia button needed a similar fix
as in commit af317e4130583e29038fd9f45f3a750b11b0cbe5 ie being a menubutton.
Change-Id: I64ed638a6179bb5f274b11729c5681f3e1ac54fb
* Resolves: # 
> Insert Image button was broken without WOPI

- browser/src/control/Control.JSDialogBuilder.js
Prevent the wrapper of the JS dialog button being given the 'tabIndex: 0' property
Change-Id: I6a6a69646dce8ab29c90059806ad51062ebe4309
> Prevent JS dialog buttons being selected twice durign tab navigation

- browser/css/btns.css
- browser/css/jssidebar.css
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.OverflowGroup.ts
- We have introduce a new button "more"
- it works same as we have more button on sidebar for some categories
- This more button will shown after the label of group at very end
- user can easily open the respected dialog of that related group to change many other properties.
Change-Id: I3dcae849176c63e222acd62dd5281d327eca2b2b
* Resolves: # 
> Feat: Add more button in notebookbar groups

- browser/src/main.js
...which had been added with a7d6d1debc46f618733e180bd1b8ff87e7303ab7 "wasm: pass the docURL to the wasm app" for unclear reasons, as the defaults of calling console.log and console.error, respectively, should work just fine
Change-Id: Idbcc67279613560f4e75b680ca0a06ad92864ccf
* Resolves: # 
> Drop Emscripten Module.print and Module.printErr overrides

- browser/src/control/Control.StatusBar.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.UIManager.ts
- cypress_test/integration_tests/common/find_helper.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/calc/find_dialog_spec.js
- cypress_test/integration_tests/desktop/impress/find_dialog_spec.js
* Resolves: # 
Remove search box from the status bar, route `Ctrl+F` to the find and replace dialog (find tab is open first by default).
> Search: Remove search box and use Find dialog instead

- browser/css/spreadsheet.css
Change-Id: I95abcfb786741d10ce5230b9344366ede2cdd5ac
* Resolves: # 
- Updated the sheet tab buttons to use the document type color defined in the theme.
> Calc: apply doc type theme color to sheet buttons

- browser/src/control/Control.NotebookbarCalc.js
- cypress_test/integration_tests/desktop/calc/focus_spec.js
commit e110727e11a3d7d940b68259c7a1461c34409397 (HEAD -> master, origin/private/pedro/Calc-Layout-tab-remove-Page-button, origin/private/pedro/Calc, private/pedro/Calc-Layout-tab-remove-Page-button, private/pedro/Calc)
Date:   Fri Aug 22 10:28:38 2025 +0200
Calc: Layout tab: remove Page button, add more button and label
With the new pre-canned menu items recently added  we can now remove
the bigtoolitem that we have and add a label and a more button that opens the dialog.
- Add group label: makes it easier to conceptually group them and
understand their functionality
- Add more button that opens the "Page Style" (.uno:PageDialog)
dialog: which makes it evident that all those options can be also
found with further control in that dialog …
> Calc: Layout tab: remove Page button, add more button and label

- browser/src/layer/tile/CanvasTileLayer.js
In some cases, a tile may be requested at the end of a document, when
layout isn't finished, and current size of the document is loo small.
This may happen e.g. when renaming a long document, when the current
position is near its end.
In this case, an empty tile would be returned. Later, when the layout
finishes, 'invalidatetiles: EMPTY' message would arrive, requesting
to flush all cached tiles. This makes handleInvalidateTilesMsg create
a new 'invalidatetiles' message with a rectangle, and then pass it to
_onInvalidateTilesMsg, which checks if cached tiles are in the area,
and then drops them.
The old code used document size as the size of the rectangle. But it
is the old size of the document at this point; and the empty tiles
requested initially turn out to be outside of the bounds …
> Use MAX_SAFE_INTEGER to make sure that all tiles are invalidated

- browser/src/control/Control.NotebookbarImpress.js
- before this patch `Reset layout` option was not working
- Reason: We accidentally added `_UNO`  prefix for `command` property  in json this cause issue to send uno command to CORE
- this patch will fix this _UNO prefix issue
Regression commit: https://github.com/CollaboraOnline/online/pull/12479/commits/dfd4a7733e96602e052340563128c59ebad5f0d7
Change-Id: I39d7fb709ef0c120bb28a77b5c2752880312cef1
* Resolves: # 
> Fix reset slide layout option not working

- browser/css/jsdialogs.css
fixes regression from commit 625a2370d6493bd83903d6aab07d20c2946c296d Tabbed: overflow: Align buttons without overflow label
Bug was visible in some window sizes when styles previews scrolling was not possible to the very top
Backport of: https://github.com/CollaboraOnline/online/pull/12679
> notebookbar: fix scroll range inside icon views (backport)

- browser/src/control/Control.QuickFindPanel.ts
- browser/src/control/Control.UIManager.ts
- browser/src/map/Map.js
- cypress_test/integration_tests/desktop/writer/invalidations_spec.js
BEFORE:
```
INCOMING: status: ...
OUTGOING: uno .uno:ChangeTheme {"NewTheme":{"type":"string","value":"Dark"}}
OUTGOING: uno .uno:InvertBackground {"NewTheme":{"type":"string","value":"Dark"}}
OUTGOING: uno .uno:ToolbarMode?Mode:string=notebookbar_online.ui
OUTGOING: uno .uno:SidebarShow
OUTGOING: uno .uno:SidebarHide 
... Creating CanvasTileWorker
```
AFTER:
```
INCOMING: status: ...
OUTGOING: a11ystate false
Creating CanvasTileWorker
OUTGOING: clientzoom
OUTGOING: tilecombine
... delay ...
sidebar, notebookbar, quick find
```
> Initialize core components after first tiles request

- browser/src/control/Control.NavigatorPanel.ts
* Resolves: # 
QuickFind only exists in writer so trying to focus the search bar causes an error in non-writer.
Fix this:
> Navigator: dont register to 'focussearch' in non-writer

- browser/css/jssidebar.css
- browser/src/control/jsdialog/Widget.TreeView.ts
- cypress_test/integration_tests/desktop/writer/navigator_spec.js
* Resolves: # 
Highlight matched text in search results.
e.g. searching for `prod` used to yield results like
`Collabora [Prod]uctivity` now we get: 
<details>
<summary>Outdated: Original issue with square brackets</summary>
~~However to continue with this approach we need to deal with cases where the user has placed square brackets in the document which is currently breaking it:~~
</details>
Fixed by searching for search term inbetween brackets
> QuickFind: Highlight matched text in results tab

- browser/src/control/Control.NavigatorPanel.ts
* Resolves: # 
QuickFind only exists in writer so trying to focus the search bar causes an error in non-writer.
Fix this:
backport of #12698
> Navigator: dont register to 'focussearch' in non-writer (backport)

- browser/css/cool.css
- browser/css/jssidebar.css
* Resolves: # 
dont push view up when we have many results, additionally wrap results that were previously out of bounds.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> Fix QuickFind overflow 

- browser/css/jssidebar.css
Inherit font size and family from existing styles and set the color to gray
Change-Id: Ifbb75e883979d6001c87bce1ffd44bad0dfbeebd
> Navigation: Style Page dividers

- browser/css/cool.css
- browser/css/jssidebar.css
* Resolves: # 
* Target version: distro/collabora/co-25.04
backport of #12716
dont push view up when we have many results, additionally wrap results that were previously out of bounds.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> Fix QuickFind overflow (backport)

- browser/src/control/Control.JSDialog.js
Change-Id: I35d4c6c509b48bb9afd15b8604a08cdf0c641f03
* Backport PR: #12729
- Ensures the sheet name is automatically pre-selected in the input field when the rename modal is opened by double clicking a sheet tab.
> Backport: Pre-selection of sheet name in rename modal

- browser/css/jssidebar.css
* Resolves: # 
Avoid scrolling the whole wrapper, thus leaving the 'numberofsearchfinds' static in the layout.
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
> QuickFind: scroll only in results

- kit/ForKit.cpp
6f4eeaa75d27cfb5dee8d70335757545dce1cc18 "ForKit: log killed child processes by users & oom" (replacing a use of waitpid with a use of waitid) broke it in three regards:
For one, waitid (unlike waitpid) doesn't take WUNTRACED ("The status of any child processes specified by pid that are stopped [...] shall also be reported to the requesting process", POSIX.1-2024).  It would take a corresponding WSTOPPED ("Status shall be returned for any child that has stopped upon receipt of a signal [...]", POSIX.1-2024), but why should we be interested in SIGSTOP/SIGTSTP here, anyway (and treat that as if the child had terminated)? WUNTRACED had been added in de7cda7891fff43992df61a1b2702608ed579549 "loolwsd: improve child cleanup and forking", for unclear reasons.  So just drop it unconditionally. …
> Fix usage of waitid

- browser/src/control/jsdialog/Widget.TreeView.ts
Change-Id: I36619e09d3683865cd1ae0da776a8931f8bbd5e4
In treeview, the container with role="grid" (e.g., id="charttype" and id="shape") does not contain elements with role="row". According to the WAI-ARIA specification, a grid must contain direct children with role="row", and each row must in turn contain children with role="gridcell". This semantic structure is essential for screen readers and other assistive technologies to correctly interpret the layout and enable keyboard navigation.
> accessibility: add role attribute to tree view rows for improved accessibility

- net/HttpRequest.cpp
- net/HttpRequest.hpp
- test/HttpWhiteBoxTests.cpp
Adds support for parsing chunks and multipart/data in POST requests.
Since we never supported parsing POST requests, the new code is only used in tests, and therefore is safe.
- **wsd: http: support chunked POST in RequestParser**
- **wsd: http: Request supports chunk writing**
- **wsd: http: MultipartDataParser and test**
> HTTP Chunking and Multipart/Data Support

- test/HttpWhiteBoxTests.cpp
This fixes randomly failing unit-tests due to this recently merged test that suffers use-after-free.
> wsd: test: fix use-after-free

- browser/css/notebookbar.css
- browser/css/toolbar.css
- before this patch because of the fixed width of popup some level of big content items or you can say elements gets hiddedn on screen
- this will fix the issue and make sure all the content gets visible and for overflow condition we will add scroll bar
Before:
After:
Change-Id: I0d746433848d5f7d77a3256635ca3206a1fd5966
* Resolves: # 
> Fix overflow popup width to display full content

- browser/Makefile.am
- browser/css/toolbar.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Definitions.Menu.ts
- browser/src/control/jsdialog/Widget.PageSizeEntry.ts
Change-Id: I36675856151cf0beb5b9d12cc7d8adcbb3b0dd53
* Resolves: # 
- Implements a new PageSizeEntry widget to provide a custom dropdown UI.
- Renders all sizes in a single scrollable list with a sticky "More Paper Sizes…" entry kept outside the scrolling area.
- "More Paper Sizes…" opens the Page Style dialog directly on the Page tab.
- Keeps the list height shorter and responsive
[Screencast from 03-09-25 18:10:17.webm](https://github.com/user-attachments/assets/083dd91f-0fff-423e-83e4-57fdd7a88214)
> Calc: Add “Page Sizes” dropdown with sticky "More Paper Sizes…"

- browser/css/jsdialogs.css
In CORE, there is an address book after the 'URL' field. We hide this in online, but this causes a third column to be added, which is then given a third of the spare width due to the auto property. This leaves a gap, which is solved by adding css to set the width to 0px.
Change-Id: I6a6a696433cf8f324005ead68104f39d98e17d88
* Resolves: # 
> Prevent gap to left of hyperlink dialog mail fields

- browser/src/control/Control.JSDialogBuilder.js
While using tab to navigate would loop through each option in the JSdialog, using shift tab would only swap between the exit button and the first item. Adding tabindex: 0 to the final button fixes this, and seems to have no other effect. 
Change-Id: I6a6a6964e020244c6d36fc9d5bc430dab1cdff7d
* Resolves: # 
> Allow JSdialog tab navigation to loop

- browser/Makefile.am
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.Text.ts
Requires core patch: https://gerrit.libreoffice.org/c/core/+/190558
> Static content rendering using span instead of Label

- wsd/COOLWSD.cpp
This should fix the race on DocBrokers
which is accessed from both cleanupDocBrokers()
and dumpState(), where it wasn't protected.
Change-Id: I1bb87a11ea12fb73dbfa23c6135cf8af7cabfa28
> wsd: take DocBrokersMutex in dumpState

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.QuickFindPanel.ts
- browser/src/control/Control.UIManager.ts
- browser/src/map/Map.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/writer/invalidations_spec.js
- cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
- it helps with the bug where Writer -> References tab was updated before we got core widget updates
- in above case we got clean styles previews because we rebuilt notebookbar but we didn't insert updates we got so far
- backports boot management, so we initialize core components only after first tile is received by a client so we have more time to do a "references update", it's not a proper fix but reduces the probability of an event
will be continued
> notebookbar: startup (backport 25.04)

- browser/css/jsdialogs.css
Change-Id: I9a6367901409acd2603988c6adea1fa0696058f1
* Resolves: # 
- Move padding from general snackbar buttons to mobile-wizard specific  buttons only
> Snackbar: remove extra padding from feedback popup

- browser/src/control/Control.JSDialog.js
Issue: Extracting the scrolled amount from the position leads to wrong position if an ordinate is in frozen pane.
Change-Id: I6ca15acb3027aba18ef060393e5d5eb56b904f76
* Resolves: # 
> Autofilter and validity dropdown popups: Consider frozen panes.

- browser/css/jsdialogs.css
Change-Id: Iabfbd5b7bdd7bb68d725570245960e083d69483c
* Backport : #12813 
- Move padding from general snackbar buttons to mobile-wizard specific
buttons only
> Backport: Snackbar: remove extra padding from feedback popup

- browser/css/notebookbar.css
Change-Id: I10a4d6e9cabb4544f991c93e0cbca7487ea4ce31
* Backport: #12799 
- Set fixed height of 2.75rem for masterpageall_icons entries to ensure consistent preview sizes across all slide templates in notebookbar
> Backport: Impress: Design-tab: Set uniform height for slide template icons

- browser/src/canvas/sections/SplitterLinesSection.ts
Issue: When browser zoom is at a higher level, gradient becomes invisible. Because its width is not multiplied with dpiScale and is very tiny.
Change-Id: I08f8951ad954268c3b7d0e6a57234ed20c5e90c5
* Resolves: # 
> Calc splitter lines: Multiply gradient width with dpiScale.

- browser/src/control/Control.NotebookbarImpress.js
Change-Id: I2173cd26c763e5e581c4c9809935187f26d86aff
* Resolves: #12775 
- Added the two slide layout controls to the Design tab
- Matches user expectations: slide layout is a design decision, so keeping these controls in Design aligns with the mental model and common workflows.
> Backport: Impress: Add slide layout controls to the Design tab

- browser/src/canvas/sections/ShapeHandleScalingSubSection.ts
- cypress_test/integration_tests/desktop/calc/image_operation_spec.js
- cypress_test/integration_tests/desktop/writer/image_operation_spec.js
- cypress_test/integration_tests/mobile/calc/image_operation_spec.js
- cypress_test/integration_tests/mobile/impress/image_operation_spec.js
- cypress_test/integration_tests/mobile/writer/image_operation_spec.js
Issue:
When a user is scaling a shape using shape scaling handles at the corners:
* They can break the width / height ratio.
* To keep the ratio, they can press and hold shift & ctrl keys.
For images:
* **the opposite functionality should be default**.
* When scaling images, if user doesn't press any keys, image should keep the ratio.
* If user presses shift & ctrl keys, they can break the width & height ratio.
Fix: Reverse the keepRatio variable for images.
> Shape Scaling: Reverse the scaling shortcut function for images.

- android/app/src/main/res/values/themes.xml
Google has turned on edge-to-edge mode by default for all API-version-35 Android apps. This makes our app underlay the toolbar, which is a bad thing as you can't click on elements that are underneath the toolbar.
The true solution is figuring out how to modify every activity to turn the bar text the right color and add some padding (I guess to both top and bottom depending on the navigation bar mode?) but for now it's easier to Just Opt Out
Change-Id: I6a6a696444fb71e6bce1dd8260d1c9f11dff96dd
* Resolves: # 
> fix(android): disable edge-to-edge mode

- test/UnitWOPIDocumentConflict.cpp
- wsd/DocumentBroker.cpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
- **wsd: differentiate unauthorized CheckFileInfo response**
- **wsd: end SyncFileTimestamp activity when CheckFileInfo fails**
- **wsd: test: SyncFileTimestamp failure test**
> Backport 500-Error Handling

- browser/css/jsdialogs.css
Change-Id: I2130abb1c2192f509cbda01bee5650d84dd4f19d
* Resolves: # 
- Overrides original grid layout (which forces 3 fixed columns via 'grid-template-columns: 1fr 1fr 1fr', causing empty space/visible "missing" columns when fewer than 3 items are present, e.g., only 1 element)
> Impress: Design tab: Responsive flex layout for master slide template iconview

- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
Issue:
When calling the function, if a form control in Writer is focused, the command works on the wrong window. It deletes text from the document. It should delete the content from the form control, which has a different window id.
Change-Id: I0371d3ea24b8b4ffdf8201df7fcc0c152470404f
* Resolves: # 
> cool#12608: Check windowId when calling removeTextContext.

- browser/css/spreadsheet.css
- browser/src/canvas/sections/AutoFillMarkerSection.ts
- browser/src/canvas/sections/CellCursorSection.ts
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- Before this patch formatting mark icon do not change on formatting mark option get enabled
- Switched target from `.leaflet-layer` to `.leaflet-map-pane` for consistent class application
- Added `.bucket-cursor.spreadsheet-cursor` rule to ensure fill cursor displays correctly on spreadsheets
Before:
After:
Fix:
[Screencast from 2025-09-12 23-54-33.webm](https://github.com/user-attachments/assets/d193e825-cab3-40af-a8ff-e5124b958247)
Change-Id: I78ce9f5037ba52160a7b6024d3c3ab5f4e25f6ff
* Resolves: # 
> Fix formatting cursor handling in spreadsheet view

- browser/src/control/Control.UIManager.ts
- Ensure Ctrl+F always opens the Navigation sidebar (if closed) and focuses its search box.
- Prevent Ctrl+F from also triggering the Find dialog on subsequent presses.
- Keep Ctrl+H behavior to open the standard Find dialog.
Change-Id: I59827a21d69ca330712b3b76b51a673fe719bade
* Resolves: # 
> Fix: Ctrl+F in Writer consistently opens Navigator search only

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
when a follower tries to navigate the presentation himself
he automatically unfollows the presentation and free to navigate
follower has extra button in presentation bar to start following the
presentation again which brings them to the same slide as leader and
follows again
> followme slide: allow users to follow and unfollow slideshow 

- browser/css/cool.css
- browser/css/jssidebar.css
- browser/src/control/Control.QuickFindPanel.ts
- browser/src/control/jsdialog/Widget.TreeView.ts
* Resolves: # 
- Adds prev/next buttons that appear when search finds matches and hide when the results list is empty.
https://github.com/user-attachments/assets/151cb66c-78a5-42f5-a174-571274a2ed64
> Navigator: Results tab: add up/down arrows for search navigation

- browser/src/control/Control.NotebookbarImpress.js
Change-Id: I37f093b35d593b6eefea6463690784761c84ebde
* Backport: #12870 
- Replace default ellipsis with proper master slide icon in overflow group
> Backport: Impress: Design tab: Replace ellipsis with master slide icon in overflow group

- browser/src/slideshow/engine/SlideShowHandler.ts
slideshow: fix null slideInfo error when closing during transition
Add presenter state check in notifyTransitionEnd to prevent accessing, null slideInfo when slideshow is closed during slide transitions.
Reproduce Steps:
- Start Presentation Console.
- Press esc key while running transition.
- Before this fix, You would see console Error  : `Uncaught TypeError: can't access property "videos", slideInfo is null`
Change-Id: Id86ab7b5bee4dee96f1704ccca7b29ed5ad68450
* Resolves: # 
> slideshow: fix null slideInfo error when closing during transition

- kit/Kit.cpp
- This log is added for debugging purposes, to determine why in some cases we don't have chroot permission inside the usernamespace.
Change-Id: Ie5cb43e9137f74390bbabbb9485dcf3b99fe8388
> wsd: log capabilities before and after entering namespace

- browser/src/control/Control.Toolbar.js
- browser/src/control/jsdialog/Component.Toolbar.ts
Changes:
1. added aria-live attribute to search box for improved screen reader support when search key not found
2. renamed isItemEnabled to isItemDisabled for clarity
> Search Key not found accessibility support in Find and Replace Dialog

- browser/src/app/TilesMiddleware.ts
Previously, drawing was only paused if we trigger rehydration when requesting new tiles, but we should really pause drawing any time we're rehydrating visible content.
* Resolves: #12857 (maybe)
> Pause drawing for any rehydration of visible tiles

- browser/src/control/Control.NotebookbarWriter.js
Change-Id: I69b3ccc1edda31103c4c154a3fbc00e262c08505
* Resolves: # 
- The separator was incorrectly placed in the same toolbox container as the unotoolbutton, causing the container height to increase and misaligning the report-an-issue button vertically.
**CURRENT FIX**
> Notebookbar: Fix vertical alignment of report-an-issue button in help tab

- browser/css/menubar.css
Change-Id: Ied5e04f5bf6e2bf3e00150d8613add54268fe140
* Resolves: # 
-Removed fixed height and gap to allow proper text baseline alignment with other main-nav elements.
> notebookbar: fix alignment of document title

- browser/src/control/Control.Menubar.ts
shows the Options (settings dialog) menubar entry in file menu only when wopiSettingBaseUrl is available.
Change-Id: Ibd11569225bf550b42b5c6ccc450b862c695269a
* Resolves: https://github.com/CollaboraOnline/online/pull/12696#pullrequestreview-3229484691
> Add Options (Settings) dialog menubar entry in file menu

- common/Session.hpp
and
cid#548881 Variable copied when it could be moved
Change-Id: I802365501c4b6d962844e82871ffd9e79a0815d1
* Resolves: # 
> cid#548882 Variable copied when it could be moved

- browser/css/menubar.css
Change-Id: I9702bcc4f34a3c943a46fb9e80960cff244012fd
* Backport: #12897 
- Removed fixed height and gap to allow proper text baseline alignment with other main-nav elements.
> Backport: notebookbar: fix alignment of document title

- browser/src/control/Control.NotebookbarWriter.js
Change-Id: Ic918dece732a443d3a8298ee334f43374acf73e3
* Backport: #12901 
-  The separator was incorrectly placed in the same toolbox container as the unotoolbutton, causing the container height to increase and misaligning the report-an-issue button vertically.
> Backport: Notebookbar: Fix vertical alignment of report-an-issue button in help tab

- browser/src/control/jsdialog/Widget.OverflowManager.ts
- in some themes we use additional margin on the sides of a notebookbar
- that is not accounted in our algorithm for max width calculation
- let's increase required additional space after last visible element so we can afford additional margins without showing scrollbars due to delayed fold decision
- this is rather workaround, we should better discover limits of our parent container - but it is more safe than rework
> notebookbar: avoid scrollbars

- browser/css/jsdialogs.css
Change-Id: Id93a5693b896b12c1bc07c89e5ea5ea0f20232de
* Resolves: # 
- Add 4px right margin to menubutton images  to improve visual separation between icons and text labels.
> jsdialog: add spacing between icon and label in menu buttons

- browser/css/jsdialogs.css
Change-Id: Ife6148b77a8cc794cd4f7dac4cc601061451689c
* Backport: #12909 
- Add 4px right margin to menubutton images to improve visual separation
> Backport: jsdialog: add spacing between icon and label in menubuttons

- browser/src/app/ViewLayout.ts
- browser/src/map/Map.js
Issue: After renaming a file, the tiles are not reloaded when document is re-loaded. Because the client visible area needs to be sent for the newly loaded document. This causes not-updated tiles on the views.
Change-Id: I6d8261ddc865f6e53361e743fa10f32503ddd8f3
* Resolves: # 
> Force sending the client visible area on document load.

- browser/src/control/Control.ContextToolbar.ts
- UI: Show hyperlink preview only when cursor is inside the link
- Previously the hyperlink preview would appear on text selection and overlap the contextual toolbar. Now it appears only when the text cursor is placed inside a hyperlink.
Now:
[Screencast from 2025-09-19 19-18-08.webm](https://github.com/user-attachments/assets/4c73873f-ec9f-4837-869d-4adbfc21476d)
Change-Id: I34992b2c3da600afb0f6b334a89ee721d42c5f4b
* Resolves: # 
> UI: Prevent hyperlink preview from showing when contextual toolbar is active

- browser/src/control/jsdialog/Widget.Containers.ts
Example was: Writer -> Format -> Page Style -> Area with None selected. The content was moved to vertical center of a tabpage causing weird whitespace on top.
> jsdialog: prevent adding empty space on top of tabpages

- browser/src/control/jsdialog/Widget.Containers.ts
Example was: Writer -> Format -> Page Style -> Area with None selected. The content was moved to vertical center of a tabpage causing weird whitespace on top.
when we process tab page content it contains usually container with single child which we interpreted as grid and also were adding additional container on top
grid with single child element should be a regular container
backport of https://github.com/CollaboraOnline/online/pull/12925
> jsdialog: prevent adding empty space on top of tabpages (backport)

- browser/css/btns.css
- browser/css/jsdialogs.css
- browser/css/toolbar.css
Change-Id: I434dbaccdf206c4a320633c14b769355a3ec9a62
* Backport: #12918 
- Change align-items from 'end' to 'center' for consistent icon positioning 
- Add height: max-content to unotoolbuttons for consistent sizing
> Backport: notebookbar: fix misaligned tabbed icons in ui-overflow-manager

- browser/css/jsdialogs.css
Change-Id: I974e4284251cfacd6232eddf3cc5026896a24ebd
* Resolves: # 
- Adjust width of text inputs for a uniform alignment 
- Hide empty frame in document page
**Before**
**After**
> Hyperlink Dailog: Fix alignments of text inputs

- browser/css/notebookbar.css
Change-Id: I4780c5acc1a2d2c7911dd473f12f2c42e8ee327d
* Resolves: # 
- Implemented CSS scroll snap for smooth element visibility 
- Adjusted container height to ensure icons display fully 
- Resolves issue where menu options appeared truncated and cut off during scroll
https://github.com/user-attachments/assets/e9dd7715-7dcf-4365-9a45-c23c84a282b8
> impress: prevent menu transition icons from being cut off with scroll

- browser/css/notebookbar.css
Change-Id: Ic444016bc915599aba177ef712a1d6e8c32cf356
* Backport: #12941 
- Implemented CSS scroll snap for smooth element visibility 
- Adjusted container height to ensure icons display fully 
- Resolves issue where menu options appeared truncated and cut off during scroll
> Backport: impress: prevent menu transition icons from being cut off with scroll

- browser/Makefile.am
- browser/src/control/Control.ContextToolbar.ts
- browser/src/control/Control.MobileBottomBar.js
- browser/src/control/Control.MobileSearchBar.ts
- browser/src/control/Control.MobileTopBar.ts
- browser/src/control/Control.QuickFindPanel.ts
- browser/src/control/Control.SidebarBase.ts
- browser/src/control/Control.StatusBar.js
- browser/src/control/Control.TopToolbar.js
- browser/src/control/jsdialog/Component.Base.ts
- browser/src/control/jsdialog/Component.Toolbar.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- share more code for message routing inside JSDialog components (so far it's repeated every time)
- foundation for the restoring of impress sidebars in compact mode
- foundation for more clear message handling for expanded icon views (https://github.com/CollaboraOnline/online/pull/12654)
- more typing used
- no functional change
> jsdialog: compact mode sidebars / component messages

- browser/src/control/Control.Menubar.ts
shows the Options (settings dialog) menubar entry in file menu only when wopiSettingBaseUrl is available.
Change-Id: Ibd11569225bf550b42b5c6ccc450b862c695269a
* Related: https://github.com/CollaboraOnline/online/pull/12892
> Backport: Options: add menubar entry

- browser/css/jsdialogs.css
Change-Id: I10b426faf0282602af8c6339c8ddf4d1b94c6a50
* Resolves: # 
- Adjust container height to 4.25rem to match overflow-group container height. This ensures consistent alignment for both vertical and horizontal tabs across all states
**Before**
**After**
> notebookbar: fix alignment of vertical tabs

- browser/css/btns.css
Change-Id: I82230311268a764e55c86b508f4aaf087e684774
* Resolves: # 
- Set width to 100% to prevent varying button sizes from max-content 
- Consistent 24px column for icons with 5px gap from text 
- Scope limited to non-sidebar buttons via :not(.sidebar) to avoid unintended UI changes elsewhere.
> jsdialog: alignment of popup buttons with text and images

- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/css/notebookbar.css
- when using non-default font size in the browser we had issues
- relative font size caused layout issues inside notebookbar
- let's unify all the units to absolute pixels for now
- simplify icon view sizing so all of them use exactly the same rules
Test with increased default font in the browser
BEFORE
AFTER
> css: fix scaling of notebookbar fonts

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.ServerAuditDialog.ts
- browser/src/control/Control.UIManager.ts
- browser/src/layer/tile/CanvasTileLayer.js
notebookbar: do not reload, just hide server audit
- load time might be different in different instances
- server audit dialog was reloading notebookbar on message
from core
- when we reload notebookbar we lose all previous updates
like style previews
- do not reload, instead hide server audit when needed
so we do not break style previews in case of different event orders
> notebookbar: fix for empty styles

- browser/src/control/Control.Notebookbar.js
- browser/src/layer/tile/CanvasTileLayer.js
Backport of https://github.com/CollaboraOnline/online/pull/13006
This is followup for commit c0423d6f3f362dd30a9a0751afb1a7c78169a187 
notebookbar: do not reload, just hide server audit
We should show the button only if needed. Not leaving it until we detect it should be hidden.
Also this fixes problem in compact mode where non-admin user got error due to lack of notebookbar:
Exception TypeError: Cannot read properties of null (reading 'hideItem') emitting event ...
> notebookbar: show audit button correctly (backport)

- browser/src/control/Control.Notebookbar.js
- browser/src/layer/tile/CanvasTileLayer.js
This is followup for commit c0423d6f3f362dd30a9a0751afb1a7c78169a187 (HEAD -> master, origin/master, origin/HEAD) notebookbar: do not reload, just hide server audit
We should show the button only if needed. Not leaving it until we detect it should be hidden.
Also this fixes problem in compact mode where non-admin user got error due to lack of notebookbar:
Exception TypeError: Cannot read properties of null (reading 'hideItem') emitting event ...
> notebookbar: show audit button correctly

- browser/src/control/Control.PartsPreview.js
- browser/src/map/Clipboard.js
partially reverts 291be73a075643458e4d6b3f66386835
Change-Id: If4f9aafad83a86fb089ab82879ab75fd8dd2455c
> copy slide: send copySlide command from slide context menu

- browser/src/app/LOUtil.ts
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
Change-Id: I2f999f135118dc8ab7015fe97aae9de6cf8de6b8
Core changes requires: https://gerrit.libreoffice.org/c/core/+/191289
Changes:
1. Introduced new param `InitialFocusReplace` for `.uno:SearchDialog` to enable initial focus on replace tab when,
1. Click on Replace button
2. Use `Ctrl + H` shortcut
> UNO: update search dialog command to include initial focus parameter

- cypress_test/integration_tests/desktop/writer/replace_dialog_spec.js
Scenarios:
- ctrl + h should open find and replace dialog with replace tab as active
- clicking on Replace button should open find and replace dialog with replace tab as active
Change-Id: I9f2eba4bd9890a9a64c4b6b54a528b1d41604228
Relevant PR: #12931
> cypress-test: for replace tab in find and replace dialog

- test/Makefile.am
it started failing after da6b93e01c76fb1e1cc20dbca29fb96030521b24 and 9179d7f676703fe598bba9acd5e0af9b29907c14
it should be enabled again after the test is fixed
Change-Id: Ie566ba96c6da451fc335290d28675c004f1293a7
* Resolves: # 
> test: temporarily disable unit-paste

- test/Makefile.am
- test/UnitPaste.cpp
This test started to fail after core.git co-25.04 commits
9179d7f676703fe598bba9acd5e0af9b29907c14 (tdf#162153 Introduce a new
dialog for pasting plain text as Markdown, 2025-09-29) and
da6b93e01c76fb1e1cc20dbca29fb96030521b24 (tdf#162153 Remove selection
dialog for markdown when pasting, 2025-09-29).
What happens is that we now try to detect if the pasted text is
markdown, and given that the "random" content matches the "foo _bar_
baz" pattern, what gets pasted and the plain text version of the
selection ("foo bar baz") doesn't match anymore.
Fix the problem by avoiding '_' in the pasted content, we intend to just
paste some content here.
Allows reverting commit f422b2f673751a31023b709c52bce977ea4e6207 (test:
temporarily disable unit-paste, 2025-09-30).
Signed-off-by: Miklos Vajna …
> unit-paste: avoid '_' in the pasted text

- g
Backport would fail if the branch was already checked out locally.
Signed-off-by: Samuel Mehrbrodt <samuel.mehrbrodt@collabora.com>
Change-Id: I246b52e1a826d89576685ee1c4deb7e545aa3add
> Fix backport command when backport branch already exists

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarBase.ts
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.UIManager.ts
- browser/src/control/jsdialog/Component.Base.ts
- browser/src/control/jsdialog/Widget.OverflowGroup.ts
- browser/src/docstate.ts
- finally fixes case when first session opens compact mode but other user will join with notebookbar
- we need to listen core events always and always initialize notebookbar to remember style previews updates
- removes annoying assert which is not critical
It fixes case:
- open comact in A
- open tabbed in B
- switch A to tabbed - result no styles
caused by removed handlers and not recovered after switch, which are now deleted:
```
onRemove: function() {
-               this.map.off('notebookbar');
-               this.map.off('jsdialogupdate', this.onJSUpdate, this);
-               this.map.off('jsdialogaction', this.onJSAction, this);
```
followup for https://github.com/CollaboraOnline/online/pull/13035
> notebookbar: empty styles

- browser/src/layer/vector/CPolyUtil.ts
If you do a text search for a common term that will have a lot of hits (for example, searching for 'the' in the large writer test document), the browser blocks for a *long* time before displaying the rectangles around the search hits.
In the above example on my computer, it takes 37 seconds. The first commit in this patch does some basic optimisation and takes that down to 21 seconds. The second commit disables close-rectangle merging for text searches (rectangles that exactly share edges will still be merged) and that takes it down to 3 seconds.
There is still a lot of optimisation possible here, but these at least seem like low-hanging fruit that make the behaviour much closer to acceptable.
> Optimise CPolyUtil.rectangleToPointSet

- browser/src/layer/vector/CPolyUtil.ts
This is follow-up from #13060. Performance when searching in writer is very bad if you get a lot of search hits - this is mostly down to an O(N^2) algorithm that iterates over the rectangles returned by the backend, which can number in the 10s of thousands. This commit rewrites that algorithm using bisection sort on an already-sorted array so the efficiency is close to O(N). There should be no change in behaviour.
Note, we do have what looks like a very efficient alternative to this in geometry.ts (`rectanglesToPolygon`), but unlike this one in CPolyUtil, it does not deal with disjoint rectangles. I think there may actually be good reasons to have both of these, though perhaps some backend changes would negate the need for this one.
In the case described in #13060 of searching for 'the' …
> Rewrite rectangle merging in CPolyUtil.rectanglesToPointSet

- browser/css/device-mobile.css
Before this commit the top bar was being cropped because the formula bar
was now appearing even on read-only mode due to the following
commit:
afba6586d97ce26587752f6acf501cc071a8f4ba
-
The formula bar is not meant to be shown in the read-only mode
Change-Id: I3327d41a0282391bcd62c7d41ceb3a884246e66d
> Mobile: Calc: fix the top bar being cropped

- common/Seccomp.cpp
- common/security.h
- kit/Kit.cpp
We did not take the define HAVE_LIBCAP into account at all places using cap_* functions which lead to compilation failures when libcap-devel was not installed. This adds HAVE_LIBCAP to the places that makes sense and makes the code compile again.
If this makes sense I don't know as libcap could just be mandatory when using Linux, which would simplify the code a bit.
Change-Id: I11a9c6df2553c3602446565cd59e6a0ccba8e002
> Make code compile when libcap-devel is not available

- browser/src/control/Control.ContextToolbar.ts
- Previously, I had a patch to hide the URL popup when the ContextToolbar appears, but I missed an important case.
- On double-click, the ContextToolbar is shown, but tile invalidation also occurs, which triggers the `showUrl` function again after the ContextToolbar logic completes.
- To address this, we can call `CloseUrl` during the layout rendering step for the contextual menu.
- This ensures the URL popup is closed consistently, even when tile invalidation happens for a URL in the document.
Change-Id: I46d9c4beb32ccc1276937cba8a2d491ff994d0e4
* Resolves: # 
> Improvement: Hide URL popup when ContextToolbar is shown

- browser/css/cool.css
- browser/src/canvas/sections/TableResizeMarkerSection.ts
I had added them because they were under map element. Then i fixed the issue. Now they conflict with the possible themeing patches and also not needed anymore.
Change-Id: I432840be86596b08216a60833eeb450ac3762ac2
* Resolves: # 
> Table resize marker: Remove unnecessary classes.

- browser/src/control/Control.NotebookbarCalc.js
Before:
Change-Id: I9d8514dd91458338c069a2a8da7824b36446653e
* Resolves: # 
> Remove duplicate `function` option from insert tab in NotebookbarCalc
