CollaboraOnline/online

loleaflet/src/control/Control.MobileWizardBuilder.js

Change-Id: I01f40dbfa08bb361f9261eaede37af88b95d162b

Mobile remove StyleUpdateByExampleimg and StyleNewByExampleimg from sidebar

---

common/Png.hpp

Change-Id: I77fb1ae0e9ef892b23212222b44dc3dc522c7ce3
* Resolves: # 

Log also the average tile PNG size and the average compression ratio

---

loleaflet/src/control/Permission.js
loleaflet/src/core/Socket.js
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

Offer saveas for plain text types

---

ios/Mobile/DocumentViewController.mm
kit/Kit.cpp

Two crash fix cherry-picks

---

cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js

build test

---

loleaflet/css/jsdialogs.css
loleaflet/css/notebookbar.css
loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: I9c894a3a3377bb35b64a797792350cba44870929

jsdialog: simple menu button

---

loleaflet/css/mobilewizard.css

Change-Id: I67457515e99572a8ef122547f02a6ee73c4da243

Mobile fix left padding insert commands

---

loleaflet/Makefile.am
loleaflet/css/loleaflet.css
loleaflet/html/loleaflet.html.m4
loleaflet/js/ResizeObserverPolyfill.js
loleaflet/src/control/Control.Header.js
loleaflet/src/layer/marker/Cursor.ts
loleaflet/src/layer/tile/CommentListSection.ts

Change-Id: If595e742ecef633741892c4a714f74d93e97c6a9
* Resolves: # 

IE11 compatibility changes.

---

loleaflet/Makefile.am

warning: overriding recipe for target 'check'
Change-Id: I9584ffaa9258d779a4e6da3de8838729fec54e5e

loleaflet: fix overriding recipe for target 'check'

---

loleaflet/Makefile.am

Error: No test files found: "mocha_tests/**/*.js"
Change-Id: I57e86689011dceebd1100005b8e800b6155bb7c1

loleaflet: fix mocha tests

---

loleaflet/js/global.js
loleaflet/src/core/Socket.js

required to log exceptions
Change-Id: Ic63b31080b252042284b2826e82d4c5300e17f6d

loleaflet: introduce logServer function

---

common/StringVector.cpp
net/HttpRequest.cpp
net/HttpRequest.hpp

HTTP improvements

---

loleaflet/src/map/handler/Map.Keyboard.js

Change-Id: Ib38252197d9a6597d88622b0b965ad026bb53fcb
* Resolves: # 

Emit Trace Event (if enabled and turned on) for handling of key events

---

kit/ChildSession.cpp
loleaflet/src/layer/tile/CanvasTileLayer.js

More trace events (when enabled and turned on)

---

cypress_test/integration_tests/desktop/writer/apply_font_spec.js
cypress_test/integration_tests/mobile/writer/apply_font_spec.js

Change-Id: Ia87351eedef0fbe644a6abff6debb3e76781f5a8

cypress:fix writer/apply_font_spec failing

---

loleaflet/src/layer/tile/CanvasTileLayer.js

Change-Id: Ic8b69da652adde02417d2e4b605ad319fa670299
* Resolves: # 

Remove repeated assignment

---

.gitpod.yml

Change-Id: Idf9c43120e5e3b2907688d6390fdcb3675101661
* Resolves: # 

Update Gitpod config to core co-2021

---

loleaflet/css/jsdialogs.css
loleaflet/src/control/Control.JSDialog.js
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.LokDialog.js
loleaflet/src/control/Control.UIManager.js
loleaflet/src/control/Toolbar.js
loleaflet/src/core/Socket.js
loleaflet/src/layer/marker/TextInput.js
loleaflet/src/map/Map.js
loleaflet/src/map/handler/Map.Keyboard.js
loleaflet/src/map/handler/Map.Mouse.js
loleaflet/src/map/handler/Map.TouchGesture.js

when UI is blocked any interactions with sidebar/dialogs,
jsdialogs or menu/toolbar items are blocked.
to use: fire 'blockUI' / 'unblockUI' events
or call directly: map.uiManager.blockUI() / .unblockUI()

Add UI blocking functions to UIManager

---

loleaflet/css/notebookbar.css

Do not target item by item instead apply to all
- No need to update code if new items are added
Change-Id: I75bc3eeb3cedc7ee1d8b3b0036ce0d614c54f281

Notebookbar: shortcutstoolbox: Simplify CSS

---

loleaflet/src/layer/marker/TextInput.js

Change-Id: I0a1e807a2872e83d654fb7564aa1e9f4a2b5b88e
* Target version: 6-4

leaflet: disable resizeable property from clipboard-container (co-6-4)

---

loleaflet/src/layer/tile/TileLayer.js

Change-Id: Icc8a34876897c989dcc40c11fcc26bafabf21d66
* Target version: 6-4

leaflet:fix:mouse pointer turns into I-beam after letting go of scrollbar

---

test/helpers.hpp

Change-Id: I5385dfd2c7cf7b7638e11191c5320d0bc4e04a48
* Resolves: # 

Avoid 'DEL' in random strings.

---

wsd/ClientSession.cpp

More Trace Event metadata improvements

---

wsd/ClientSession.cpp

Cherry-picks from master

---

Makefile.am
common/Png.hpp
wsd/ClientSession.cpp

Misc Trace Event improvements

---

loleaflet/src/layer/tile/CanvasTileLayer.js

Change-Id: I3bc2aa31b077ef8c71de7447f98220d6db5ba9f9

leaflet:fix:mouse pointer turns into I-beam after letting go of scrollbar(master)

---

cypress_test/integration_tests/common/helper.js
cypress_test/integration_tests/common/impress_helper.js
cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

This restores and improves some cypress tests that were commented out earlier.
* Resolves: # 

Restore and improve commented out cypress tests

---

loleaflet/src/core/Socket.js
wsd/ClientSession.cpp

Change-Id: I58970ccc6e6f7e2d9a19b51f8ba1ca8a00a0fd03
* Resolves: # 

Use S and F events here, too, instead of b and e

---

loleaflet/src/control/Control.Menubar.js

Change-Id: If6366bf028d4de3fa477a6542d588afec79b1a2f

mobile: added select options in table menu

---

Makefile.am
common/Png.hpp
loleaflet/src/core/Socket.js
wsd/ClientSession.cpp

Cherry picks from master

---

loleaflet/css/override-vex.css

Change-Id: I66ca8f579c622b19bf72293587ef8f6e660ef200

Vex dialogs: Close btn: Fix position

---

loleaflet/src/control/Control.Header.js

Change-Id: I80557c11932e024aa47c6e3eee8f149760f35664
* Resolves: # 

Calc: Delete multiple rows & column bug solved.

---

loleaflet/src/core/Socket.js

Change-Id: Ie503ee60666b690f3f2d7d5a42bb588bb7e7208e
* Resolves: # 

Socket.js: Force a full reload when the server is restarted.

---

loleaflet/js/global.js
loleaflet/src/core/Socket.js

Change-Id: I7d99b570da4ee2751ea3f1d88701ceb8d7e8f878
* Resolves: # 

ie11: use subarray in place of slice.

---

loleaflet/src/control/Control.Header.js

Corrected it.
Change-Id: Ib0276ad5d94fa59307232ecdde1fcfba2f8fd48d
* Resolves: # 

Seems that IE11 compatibility changes broke functionality.

---

loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.MobileTopBar.js

* Resolves: # 
* Target version: 6.4.10 
Backport Andreas Kainz's work on master. Fixes incomplete mobile UI of Draw in branch co-6-4

Mobile Draw add TopBar commands from Impress

---

loleaflet/src/control/Permission.js

We cant have rich-formatting with these types so better
to request save-as odt or ods depending on the type
Change-Id: I3e8be3fd44aaf42833f691dcd70b7bf1b0633103
* Resolves: # 

Offer save-as for plain text files like txt or csv

---

loleaflet/css/leaflet.css
loleaflet/css/loleaflet.css
loleaflet/css/notebookbar.css

- autofillmarker: white top-left outer border
- Synchronize map with TilesSection: Fix CSS

private/pedro/fix annotation T28712 maybe also T28904

---

loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.NotebookbarImpress.js

Change-Id: Ibfab8a2bc9cfc300b151549c1e089dfc019c231e

fix table options in NB and mobile

---

loleaflet/src/control/Control.MobileTopBar.js

Change-Id: I07a429f53adb9a51aa576000182a5bfa91de31c6

leaflet: fix comment wizard icon

---

loleaflet/src/control/Control.ContextMenu.js
loleaflet/src/control/Control.Tabs.js

Change-Id: If96461a5670ceeda035a77715cf24d419a0c2151

loleaflet: show some options in context menu only when there are more than one sheets (6-4)

---

cypress_test/integration_tests/common/mobile_helper.js
loleaflet/css/device-mobile.css
loleaflet/css/menubar.css
loleaflet/css/notebookbar.css
loleaflet/src/control/Control.Freemium.js
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.TopToolbar.js

Freeemium followup patches

---

kit/Kit.cpp

Signed-off-by: Gopi Krishna Menon <gopi.menon@collabora.com>
Change-Id: I1e5bda8f2c003fa25dc173dab3b0683167903195

Improve logging

---

cypress_test/integration_tests/common/helper.js
cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
cypress_test/integration_tests/mobile/impress/delete_objects_spec.js
cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
cypress_test/integration_tests/mobile/impress/impress_focus_spec.js
cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
cypress_test/integration_tests/mobile/impress/searchbar_spec.js
cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

Change-Id: Idfe418f20b57c55dceb1b49996ab7134088d47de

cypress: disable some tests temporarily

---

kit/Watermark.hpp

Change-Id: I753d1f44e176d4033ead57c6ffdb0f8c8369cfc2

Hardcode some trigonometry, and some FP math in loop

---

loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: If87de8f51bae231a73079d30457595d983a8c33b

jsdialog: keep image on the left side of the button

---

kit/Kit.cpp

Improve logging information in setdocumentPassword for better clarity. 😊
Signed-off-by: Gopi Krishna Menon <gopi.menon@collabora.com>
Change-Id: I292991cbee2cf0cf1430ba4c5626b6e08ccbc0f5

Improve logging Information

---

loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.NotebookbarImpress.js

Change-Id: I47de5b95a312e2c416e448d8fbfecfeb556b918c

fix: table options missing in mobile and NB

---

cypress_test/integration_tests/desktop/calc/annotation_spec.js
cypress_test/integration_tests/desktop/impress/annotation_spec.js
cypress_test/integration_tests/desktop/writer/annotation_spec.js

Change-Id: I0e2deee82c1ee83c9bf9d64d65572b0b65d11e3e

CI stability co-6-4

---

cypress_test/integration_tests/common/helper.js
cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
cypress_test/integration_tests/mobile/impress/delete_objects_spec.js
cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
cypress_test/integration_tests/mobile/impress/impress_focus_spec.js
cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
cypress_test/integration_tests/mobile/impress/searchbar_spec.js

Change-Id: I9243769df3dadd4a8dfa07eaceb7e9a8d8f42950
Summary:
The failing and disabled tests are passing so now enabling them

cypress: enable some tests to check

---

loleaflet/src/control/Control.JSDialog.js

Change-Id: If88494b47be1d1e91a65be9123ae40fb3930ad40

jsdialog: simplify popup code

---

loleaflet/src/control/Control.JSDialogBuilder.js

we receive updated by welding framework

jsdialog: don't use uno updates for numeric fields

---

loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: Ia2aa29bf064fb2bb518b80a6d5fa5617a1334f2c
* Target version: co-6.4

leaflet:NB:added hyperlink in copy,paste and cut button (co-6-4)

---

loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.NotebookbarBuilder.js

Change-Id: I2ac3d878edf6a765e6debf62369c1a772f9726ab
* Target version:co-6-4
Regression from the following commit in 6.4:
https://github.com/CollaboraOnline/online/commit/1831d42d029ffca1166f1a85896ac700390acee3

fix: loleaflet: Trying to add a comment with NB adds an empty comment

---

loleaflet/src/layer/marker/TextInput.js

Change-Id: I282a50a802b32c14bf13ad9d21ddc33e0b515c3c
* Resolves: # 

Comment out spurious console.log()

---

loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: Ie48fb346a4cbb494116f532a9039766a3af0a761

jsdialog: implemented radiobutton with images

---

loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: Iad7ad6c6c9fd60d20eeb0f9377454117fd9632aa

jsdialog: if toolitem has image use it

---

loleaflet/src/layer/tile/TilesSection.ts

Change-Id: I6c11a5d1dcbb63b72a2eff08ba27f732a26d46d9
* Resolves: # 

Set tab-width in Emacs mode line

---

loleaflet/src/control/Control.DownloadProgress.js
loleaflet/src/map/Clipboard.js

User procedes to other tasks, and does not need the button anymore
Change-Id: Ie7d377c03f87f519574903e9b58c7735661badc1

Hide download button after selection change

---

cypress_test/integration_tests/desktop/writer/delete_objects_spec.js
cypress_test/integration_tests/mobile/calc/annotation_spec.js
cypress_test/integration_tests/mobile/impress/annotation_spec.js
cypress_test/integration_tests/mobile/writer/annotation_spec.js
cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js

Change-Id: I6e4d467224a9d7f1565fe9d895c4a40fda331824
* Target version: 6-4

cypress: increase the stability of some tests

---

loleaflet/Makefile.am
loleaflet/test/load.js

load.js fixes

---

loleaflet/src/core/Socket.js

This reverts commit 9f409ba6d293792de68649ccef6ef96fa7cfd0bd.
There may be some problems with this approach.
Change-Id: If06cd655024d8d5540797f676a8ae58b7b362bf0
* Resolves: # 

Revert "Socket.js: Force a full reload when the server is restarted."

---

loleaflet/src/layer/tile/CanvasTileLayer.js

Change-Id: I4990f8c9d44c92f711fb4d973bf44ef77812c757
* Resolves: # 

CanvasTileLayer: Correct the check for the tile source.

---

cypress_test/integration_tests/desktop/impress/delete_objects_spec.js
cypress_test/integration_tests/desktop/impress/image_operation_spec.js
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.MobileWizardBuilder.js

Change-Id: If58cfe7135acbeaac11df294a47db7712114db81

jsdialog: prefer svg icons

---

loleaflet/src/control/Control.Sidebar.js

Change-Id: I12341a3f472d93aded899dac3049bfe46140b35f

jsdialog: sidebar: don't show empty

---

loleaflet/src/control/Ruler.js
loleaflet/src/dom/DomUtil.js

Guard against two uncaught JS exceptions

---

wsd/ClientSession.cpp

Change-Id: I09de6d3f1e406e53692eb4ce16644c337c9e3793

wsd: log javascript handled exceptions

---

cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js
loleaflet/src/control/Control.Tabs.js

Change-Id: I548ad9aa56883c7a0ec70d2a51fced420d0c2d1d
###Summary:
Show option also gets hidden when after hiding for example 1 sheet out of 2 sheets

fix: sheetoperation spec failing

---

kit/ChildSession.cpp
kit/ChildSession.hpp

Change-Id: Icf4e49c7d4d8f77a37557e1990f37673e1b9c91d
* Resolves: # 

Fix build of iOS app: Bypass updateFreemiumStatus

---

loleaflet/css/jsdialogs.css
loleaflet/css/mobilewizard.css
loleaflet/src/control/Control.ContextMenu.js
loleaflet/src/control/Control.Header.js
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.MobileTopBar.js
loleaflet/src/control/Control.MobileWizard.js
loleaflet/src/control/Control.MobileWizardBuilder.js
loleaflet/src/control/Control.Tabs.js
loleaflet/src/control/Control.Toolbar.js
loleaflet/src/control/Control.UIManager.js
loleaflet/src/core/Socket.js
loleaflet/src/layer/tile/CanvasTileLayer.js

popup is injected into container prepared by toolitem/menubutton
Change-Id: Ic75474c4da757f6401f6d347ab8942048b2db5c4

mobile-wizard: add menubutton/toolbar popups

---

loleaflet/src/control/Control.MobileWizard.js

Change-Id: Ifa238bc24b6ae0c8e196f9c2f0d4ab48ba99264b

mobile-wizard: be sure elements are hidden

---

loleaflet/css/menubar.css

Change-Id: I7a36f0a50b2e8867e18744270bb6d84d6c5a917b

Toolbar-up: avoid adding extra padding on the left

---

loleaflet/Makefile.am
loleaflet/test/bootstrap.js
loleaflet/test/load.js

New perf test

---

loleaflet/src/map/Map.js

Signed-off-by: Hannah Meeks <hmeeks4153@gmail.com>
* Resolves: # 

Copy documentation into source code as comments #2160

---

loleaflet/src/control/Control.TopToolbar.js
loleaflet/src/control/Toolbar.js

Font combobox Updates

---

loleaflet/src/layer/tile/CommentListSection.ts
loleaflet/src/layer/tile/CommentSection.ts
loleaflet/src/layer/tile/TileLayer.js

Open new comments directly in the cell's position, without animation.
Focus on the comment box.
Change-Id: I0dda23baaa9c8cdd940fc9d429e0e72e5464b854
* Resolves: # 

Calc: Issues with comments.

---

test/UnitWOPIHttpRedirectLoop.cpp
wsd/Storage.cpp
wsd/Storage.hpp

Change-Id: Iaac4384385e05f33472b6678422b4a444319b59c

HTTP 302 - updates after review

---

loleaflet/css/leaflet.css
loleaflet/src/layer/marker/ProgressOverlay.js

- Re-use CSS vars
- Add additional clase so we can distinguish between labels
- Add hierarchy and style brand-label: Make that span to be
recognizable as part of the icon and avoid being perceived
as part of the message (Connecting...)
Change-Id: Ib8a11a932e93a825390feb2f16745a44d1dc3432

Leaflet-progress: use proper css vars

---

loleaflet/src/control/Control.UIManager.js

This will prevent us from flickering if popup has to be shown
for less than 0.7s.
Change-Id: I5904e5f836dae40b83ca24d19e0b2fb779eb504b

BusyPopup: show after 0.7s delay

---

loleaflet/src/control/Control.TopToolbar.js

Change-Id: Id2f5ec1e1776ad3f96b2d23952739ffbc47098bb

leaflet: fixed insert graphic button on top toolbar

---

cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js

Change-Id: I82fdc04ffa21699066529f556170596791323539

cypress: fix: apply_paragraph_props_shape/text fails due to core changes

---

loleaflet/src/map/Map.js

Copy loleaflet-api.html into code: defaultZoom as said in #2160

Copy loleaflet-api.html into code: defaultZoom

---

loleaflet/src/layer/tile/CanvasTileLayer.js

Seen from these three locations in "make perf-test".
Change-Id: I7f9fc4a073f583647e02427033fbd60c7c919a8e
* Resolves: # 

Guard against "Cannot read property '_dpiScale' of undefined"

---

loleaflet/src/layer/tile/CanvasSectionContainer.ts

Change-Id: Iab6cd410f668c788b8abb14bc0e1cddc09d71dd9
* Resolves: # 

CanvasSectionContainer: Create / update test divs only when testing.

---

loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.NotebookbarBuilder.js

Change-Id: I2ac3d878edf6a765e6debf62369c1a772f9726ab

fix: loleaflet: Trying to add a comment with NB adds an empty comment(master)

---

loleaflet/css/partsPreviewControl.css

Change-Id: I1b60bf2688a4a3fdeec535d933f27876db07190a
* Resolves: # 

Impress Mobile: Fix slide sorter size.

---

.gitpod-files/settings.json
.gitpod.yml

Change-Id: I373f6c13a0c1f2634677ea600f90c1452b44283c
* Resolves: # 

Add default vscode settings for Gitpod

---

kit/ChildSession.cpp
loleaflet/src/control/Control.JSDialog.js

fixes https://github.com/CollaboraOnline/online/issues/2829

Handle dialogevent exception

---

cypress_test/integration_tests/desktop/calc/annotation_spec.js
cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
cypress_test/integration_tests/desktop/impress/delete_objects_spec.js
cypress_test/integration_tests/desktop/impress/statusbar_spec.js
cypress_test/integration_tests/desktop/impress/table_operation_spec.js
cypress_test/integration_tests/desktop/writer/table_operation_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
cypress_test/integration_tests/mobile/writer/apply_paragraph_properties_spec.js
cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

Change-Id: Ifc34a9b09ab40ceec8c799490ee1ccac08433095

cypress: disabled tests temporary

---

kit/ChildSession.cpp
test/Makefile.am
test/UnitWOPIAsyncUpload_Modify.cpp
test/UnitWOPIAsyncUpload_ModifyClose.cpp
wsd/ClientSession.cpp
wsd/DocumentBroker.cpp

Various improvements to saving and tests.

Improve saving and add tests

---

.github/config.yml

Change-Id: I54050204ecddc6fe0871a1424db164977442a176
* Resolves: # 

Add welcome messages for pull requests

---

cypress_test/integration_tests/mobile/calc/apply_font_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
cypress_test/integration_tests/mobile/writer/apply_font_spec.js
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.MobileWizardBuilder.js

we receive that information by welding updates
Change-Id: I9ff7f5d26740b1f13d1f1cccd88793ca35a4ee76

mobile-wizard: don't use uno status updates

---

loleaflet/css/device-mobile.css
loleaflet/src/control/Control.Tabs.js

Change-Id: If1c37b4516bf90dd48dcf5b21f13b113df09f5f8
* Resolves: # 

Calc: Buttons for scrolling tabs list were not working.

---

cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

Change-Id: Ia302f05f2524c446f32b7baccdd86d25766b1707
This tests are failing due to core changes

cypress: disabled failing tests

---

kit/ChildSession.cpp
loleaflet/src/core/Socket.js
loleaflet/src/map/Map.js

- kit: add payload to 'statusindicatorstart'
- loleaflet: check the 'statusindicatorstart' label

add a status indicator label

---

cypress_test/integration_tests/common/mobile_helper.js

Change-Id: If8689bbc9505d05d8343b624cb0213a583f362a2
* Resolves: # 

Cypress: Workaround for a bug inside the library.

---

loleaflet/src/layer/tile/ScrollSection.ts

Change-Id: I39cfe37dddc603cc35a4cb02a2bfd45db224df52
* Resolves: # 

ScrollSection: Make vertical scroll bar always visible on desktop.

---

cypress_test/integration_tests/desktop/calc/annotation_spec.js
cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
cypress_test/integration_tests/desktop/impress/annotation_spec.js
cypress_test/integration_tests/desktop/impress/statusbar_spec.js
cypress_test/integration_tests/desktop/writer/table_operation_spec.js
cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
cypress_test/integration_tests/mobile/writer/apply_paragraph_properties_spec.js
cypress_test/integration_tests/mobile/writer/delete_objects_spec.js

cypress: make tests more stable

---

kit/ChildSession.cpp
loleaflet/src/core/Socket.js
loleaflet/src/map/Map.js

- kit: add payload to 'statusindicatorstart'
- loleaflet: check the 'statusindicatorstart' label

add  a status indicator label

---

loleaflet/css/btns.css
loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: Ib8b0e17696791a6f9c32ab4e2879d226b7889dfe

jsdialog: handle images

---

loleaflet/src/layer/tile/TileLayer.js

Change-Id: I1557e55be4dafebccf06f9bdb2ffd4ed1df71b55
* Resolves: # 

PDF View: Update search feature to make it work with PDF view.

---

loleaflet/css/jssidebar.css
loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: I49024be7a3a46665f709c1b6a063a25a0d6ddf38

jsdialog: sidebar: add more options buttons for panels

---

loleaflet/css/device-mobile.css
loleaflet/css/jsdialogs.css
loleaflet/css/mobilewizard.css
loleaflet/src/control/Control.JSDialog.js
loleaflet/src/control/Control.MobileWizard.js
loleaflet/src/control/Control.UIManager.js

mobile busy popup + delay 0.7s
needs some styling

busy popup: mobile

---

loleaflet/src/layer/tile/CommentListSection.ts

Change-Id: I86c5793b33e7edcbe8484fd9d520d31b0eea33ff
* Resolves: # 

CommentListSection: Remove unused function's call.

---

net/NetUtil.cpp
net/NetUtil.hpp
net/Socket.cpp
net/Socket.hpp
net/Ssl.cpp
net/Ssl.hpp
net/SslSocket.hpp
test/HttpRequestTests.cpp
test/UnitWOPIAsyncUpload_Modify.cpp
test/WopiTestServer.hpp
test/test.cpp
tools/WebSocketDump.cpp
wsd/LOOLWSD.cpp
wsd/Storage.cpp

- wsd: move isLocalhost to a common area
- wsd: support certificate verification
- wsd: ssl certificate verification requirements
- wsd: killpoco: cert verification
- wsd: test: improve modify test
- wsd: prevent recycling the listening port during tests

SSL Certificate Verification

---

loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: I7ee0e8678350d28da82c983713cac5627d099e54

jsdialog: don't request .../undefined when no image

---

common/Log.cpp

there was a case detected by tinderbox when logger
somehow existed already what closed the app:
unit-wopi-versionrestore:
Test unit-wopi-versionrestore FAILED.
-25786 2021-07-19 08:37:08.429079 [ loolwsd ] TST  UnitWOPIVersionRestore (+0ms): WopiTestServer created for []| WopiTestServer.hpp:71
-25786 2021-07-19 08:37:08.429160 [ loolwsd ] TST  UnitWOPIVersionRestore (+0ms): setFileContent: [Hello, world]| WopiTestServer.hpp:57
wsd-25786-25789 2021-07-19 08:37:08.430827 [ UnitWOPIVersionRestore ] INF  Thread 25789 (7fb8e5063700) of process 25786 formerly unnamed is now called [UnitWOPIVersionRestore]| common/Util.cpp:572
wsd-25786-25789 2021-07-19 08:37:08.430954 [ UnitWOPIVersionRestore ] INF  Starting polling thread [UnitWOPIVersionRestore] with thread affinity set to 0x7fb8e5063700.| …

Don't stop loolwsd when logger already exists

---

loleaflet/src/control/Control.JSDialog.js

Change-Id: Ic3437565fe53205c6a94362e9d4805c73ae31bd8

jsdialog: properly close popup on esc key

---

common/MessageQueue.hpp
net/WebSocketSession.hpp

Change-Id: Ie007344f9a0ffe7fdf767cb9e9069db99aa224b9
* Resolves: # 

No need for the template class MessageQueueBase

---

loleaflet/js/global.js
loleaflet/src/control/Control.ColumnGroup.js
loleaflet/src/control/Control.ColumnHeader.js
loleaflet/src/control/Control.CornerHeader.js
loleaflet/src/control/Control.GroupBase.js
loleaflet/src/control/Control.Header.js
loleaflet/src/control/Control.LokDialog.js
loleaflet/src/control/Control.RowGroup.js
loleaflet/src/control/Control.RowHeader.js
loleaflet/src/control/Parts.js
loleaflet/src/core/Socket.js
loleaflet/src/core/Util.js
loleaflet/src/layer/SplitPanesContext.js
loleaflet/src/layer/marker/Cursor.ts
loleaflet/src/layer/tile/AutoFillMarkerSection.ts
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/CommentSection.ts
loleaflet/src/layer/tile/ScrollSection.ts
loleaflet/src/layer/tile/TilesSection.ts
loleaflet/src/layer/vector/CSplitterLine.ts
loleaflet/src/layer/vector/Canvas.js
loleaflet/src/map/Map.js

Change-Id: I2ce695076343320ec16f02d058af3caf2dbd6d03
* Resolves: # 

Use global app.dpiScale variable instead of local copies.

---

common/MessageQueue.hpp
test/UnitTyping.cpp

textinput and removetextontext merging forward ports

---

loleaflet/css/notebookbar.css

Ensure 0 margins
Change-Id: I843e9a9a4e178611ec216b0e2f1dc4c49bcce464

Notebookbar: Center save icon

---

loleaflet/src/layer/tile/ScrollSection.ts

* Scrolling was not smooth.
* Scroll bar was not visible in large files.
Change-Id: I036d3699997ee3b88c2cfc6e8bc5d0e67399f522
* Resolves: # 

Scroll Section: Bug fixing.

---

loleaflet/Makefile.am
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/test/bootstrap.js
loleaflet/test/load.js

Change-Id: I49e6acc4225478380fdd10a0c325138bfda402bd
* Resolves: # 

perf-tests: calculate some tile stats

---

loleaflet/README
loleaflet/css/color-palette.css
loleaflet/css/device-mobile.css
loleaflet/css/jsdialogs.css
loleaflet/css/jssidebar.css
loleaflet/css/loleaflet.css
loleaflet/css/mobilewizard.css
loleaflet/css/spreadsheet.css
loleaflet/css/toolbar.css
loleaflet/src/control/Control.LokDialog.js
loleaflet/src/control/Control.Sidebar.js
loleaflet/src/control/Control.StatusBar.js
loleaflet/src/control/Control.UIManager.js

Change-Id: I50def4b41144d56a3cc2de41b3ed00ed550fa74d

JS Sidebar: Style and layout fixes

---

loleaflet/css/mobilewizard.css

Change-Id: I5977aee554daf022fa144d38cf022bc40eef0675
* Resolves: # 

mobile-wizard: hide duplicated paragraph images

---

loleaflet/css/device-mobile.css
loleaflet/css/spreadsheet.css

Change-Id: I1918e3c87bfd8aef2799e3dde3b9b4267b5d96d8

Spreadsheet tabs: remove unused padding n margins

---

loleaflet/src/control/Toolbar.js

Change-Id: I2010a45433a207b2586778d922946d191c17f33c
* Resolves: # 

Fix font doesnt change with multiple font selected

---

loleaflet/src/control/Control.Tabs.js

Change-Id: I21553d1c45db6bbde342abefa4d863c6305409f2

loleaflet: make show option visible only when there are hidden tabs

---

loleaflet/src/layer/tile/TilesSection.ts

So user can see which page they are scrolling before tiles are loaded.
Change-Id: I1fc92eef8ac4de97a7cdc6f8a214f94afd51044c
* Resolves: # 

PDF View: Add drawing of page borders.

---

wsd/ClientSession.cpp

Return proper HTTP code when disconnecting and log
to make the communication more effective.
Change-Id: I4da9d5a7fe4c09d6fcd44b1f31b439180d7012bd

wsd: better response when disconnecting

---

loleaflet/src/map/Clipboard.js

+ this will allow to perform internal copy/cut/paste     but only paste form external source
+ will inform user when trying to paste outside app that copying is disabled by a stub message in the clipboard

DisableCopy handling

---

loleaflet/css/btns.css

Change-Id: Ia5dbe5099bc65c01ab43eb720d676e4fd57c63f2

jsdialog: fix buttons alignment

---

loleaflet/css/jsdialogs.css
loleaflet/src/control/Control.JSDialog.js
loleaflet/src/control/Control.UIManager.js

- be sure overlay will be removed
- show fadout effect also when closing old popup and showing new one
Change-Id: I6565c96d664a2a289a9950cc2a6b60677872a3a9

busypopup: fadeout also when showing new popup

---

loleaflet/css/btns.css
loleaflet/css/jsdialogs.css

Change-Id: I25f85163e1dbdedbff4cdbf29f7a98e30d145cf1

jsdialog: fix buttons alignment (update)

---

loleaflet/src/layer/tile/CanvasTileLayer.js

Change-Id: I918c00c5f9ca8f31a90218dd8601909c60f8c252
* Resolves: # 

Bin two functions that aren't used anywhere

---

loleaflet/src/core/Socket.js
loleaflet/src/errormessages.js
wsd/Storage.cpp

Change-Id: I60ac82647a999cf24c694a9db824dfaaf6c44db3

leaflet: better docunloading message to the user

---

net/ServerSocket.hpp

Change-Id: I38b29c06220d2493dc9d47a0ac9b077e3bafd512

Remove unused private class member.

---

loleaflet/src/control/Control.NotebookbarWriter.js

Change-Id: Ibea283fa1cd0045fc75aac27ccbaa6053c0a359d

Notebookar: Remove extra Lists button from Format tab

---

loleaflet/css/jsdialogs.css

Change-Id: I79e15a80efc54549875a8736846853afa53e230d

Busypopup: Center SVG spinner

---

loleaflet/css/device-mobile.css
loleaflet/css/jsdialogs.css
loleaflet/src/control/Control.JSDialog.js
loleaflet/src/control/Control.MobileWizard.js
loleaflet/src/control/Control.UIManager.js
loleaflet/src/core/Socket.js

Snackbar element is intended to replace all w2ui .lock
dialog (alerts) with or without button
Change-Id: Iad836d0dc094be01ad265492eaacf0a8dbf8a06d

Mobile: busypopup: Adding snackbar styles

---

loleaflet/src/core/Socket.js

Change-Id: I95abd1cbccccaf46780519914b39ce4db7e806fe
* Resolves: # 

Fix missing wopiSrc on save-as and renamefile

---

loleaflet/js/global.js
loleaflet/src/layer/tile/CommentSection.ts
loleaflet/src/layer/tile/TileLayer.js

Change-Id: I4c9cbfcd4762e15c8716881fba776e77dbc195c0
* Resolves: # 

Comment: Set a variable while focused.

---

loleaflet/src/core/Socket.js
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/CommentListSection.ts

Change-Id: Iecf59d48122c15e8baa4de0fbe2b486168b4de41
* Resolves: # 

Pause and resume drawing while clearing comment & redline sections.

---

loleaflet/src/layer/tile/ScrollSection.ts

- Make it thicker
- Make it visible by default
- Hide it only when there is nothing to scroll
Change-Id: Ibffead10c09eda979ef8d3d2201173aca3553503

Document: Scrollbar: Increase affordance

---

loleaflet/js/global.js

Change-Id: I31bc41ba519f3bd5e5b873a836f6c8ed5bd842d5

loleaflet: simplify logException

---

loleaflet/css/jssidebar.css

Change-Id: Ic562deb5f338540cfc0840cfc0b9506b8efdc495
* Resolves: # 

Sidebar: expander with is 290px (322px - 2x16px)

---

loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.StatusBar.js
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/TilesSection.ts
loleaflet/src/layer/vector/CanvasOverlay.ts
loleaflet/src/map/Map.js
loleaflet/src/map/handler/Map.Keyboard.js
loleaflet/src/map/handler/Map.TouchGesture.js

* Resolves: # 
Zoom animation in desktop online for all apps.

PC zoom animation

---

loleaflet/css/loleaflet.css
loleaflet/src/layer/marker/TextInput.js
loleaflet/src/layer/tile/AutoFillMarkerSection.ts
loleaflet/src/layer/tile/CalcTileLayer.js
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/vector/CPath.ts
loleaflet/src/layer/vector/CRectangle.ts
loleaflet/src/layer/vector/CanvasOverlay.ts
loleaflet/src/map/handler/Map.Keyboard.js

* Resolves: # 
cellcursor, selections, AFmarker styling (forward port from co64 to master)

cellcursor, selections, AFmarker styling (master)

---

loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.StatusBar.js
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/TilesSection.ts
loleaflet/src/layer/vector/CanvasOverlay.ts
loleaflet/src/map/Map.js
loleaflet/src/map/handler/Map.Keyboard.js
loleaflet/src/map/handler/Map.TouchGesture.js

* Resolves: # 
PC zoom animation (forward porting : co-6-4 -> master)

PC zoom animation (co-6-4 -> master)

---

loleaflet/css/device-mobile.css

- Present locker as a floating badge for locked items
Change-Id: I00c601a9b809956022bf321dd667b68dca10d3d3

Mobie: Freemium: toolbar-down: Style overlay properly

---

loleaflet/css/mobilewizard.css

Change-Id: I666978fa301ba977b4cc3fa8a57a56754d206f6a

Make it clear when unotoolbutton is disabled

---

loleaflet/html/loleaflet-help.html

Change-Id: I3117d6137e2ec6a7a544fcb4cecf1ef4aa543b85

Calc: Help: Add Navigational shortcuts

---

cypress_test/integration_tests/desktop/impress/apply_font_spec.js
loleaflet/js/w2ui-1.5.rc1.js

loleaflet: added recent section in colorPicker

---

cypress_test/integration_tests/desktop/impress/apply_font_spec.js
loleaflet/js/w2ui-1.5.rc1.js

loleaflet: added recent color section in colorPicker

---

loleaflet/src/layer/tile/CalcTileLayer.js
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/ScrollSection.ts

* Resolves: # 
Fix view jump flicker on docload in Calc (forward port to master)

Fix view jump flicker on docload in Calc (master)

---

loleaflet/js/global.js
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/GridLayer.js
loleaflet/src/layer/tile/ScrollSection.ts
loleaflet/src/map/handler/Map.Mouse.js

Code from old implementation was forgotten to update.
Change-Id: I4d5090ebf6ac5fa0e9746e542c47c0e682160ba5
* Resolves: # 

OnScrollBy: Fix bug.

---

loleaflet/src/core/Socket.js

Change-Id: I38b157c75f95345dbf8f3ac4d1ef163cc714ca73
* Target version:

loleaflet: hidecursor when document becomes idle

---

loleaflet/src/control/Control.PartsPreview.js
loleaflet/src/control/Control.Toolbar.js
loleaflet/src/control/Parts.js
loleaflet/src/layer/tile/CanvasTileLayer.js

Change-Id: Iedee2c90ee93cf5ccebe9ae8745b48d8f7af161d
* Resolves: # 

Fix PDF view: Switching pages using button

---

wsd/Admin.cpp

I noticed this while looking into issue #2910 but it is not a fix for this issue.

use Request.has instead of .find and .end

---

loleaflet/src/control/Parts.js

fix calc's incorrect sheet switch

---

kit/Kit.cpp
loleaflet/src/control/Control.Toolbar.js
loleaflet/src/core/Socket.js
wsd/DocumentBroker.cpp

wsd: each view handles its own url params

---

cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
loleaflet/src/control/Control.PartsPreview.js
loleaflet/src/control/Control.Toolbar.js
loleaflet/src/map/handler/Map.Keyboard.js

Pdf page buttons co6410 followups

---

loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: I725014c0325e4b9f97df43fd2ce3ed4af52dda08

sidebar: simplify morebutton icon generation

---

Makefile.am
tools/Stress.cpp

Change-Id: I6fba41c826ab70b1f653f6511dac32f10f998259
* Resolves: # 

stress: start to implement based on SocketPoll.

---

loleaflet/js/w2ui-1.5.rc1.js

Change-Id: I85fe51d4c7a839b9743df6c739e4d0a02daacf40

loleaflet: store recent and custom colors locally

---

kit/ChildSession.cpp

Change-Id: I12660822829c874179ccffd84dcdd33f5dde27e3
* Resolves: # 

fix build: add missing break -Werror=implicit-fallthrough

---

loleaflet/src/control/Control.TopToolbar.js

closes #3099
Change-Id: I5d75b32aff849c31a844298e2d6aaecadc777d0c
* Resolves: # 

leaflet: fix slide format JS bug in presentations

---

loleaflet/js/w2ui-1.5.rc1.js

Change-Id: I200789fc5aa9cd5a6fc8a0bc311cbe71dde33e42

loleaflet: when user select existing color in colorPicker it comes on first position in recentRow

---

loleaflet/src/layer/tile/ScrollSection.ts

Change-Id: I26ddd343309492d6e930b8d4b232d932804eb269

fix: loleaflet: cursor behaviour when mouseleaves from verticalScrollbar

---

wsd/ClientSession.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

Change-Id: I556b7b49b2d1abc0e61ea7ecaa8e5f9406c408f3

wsd: autosave using the last editing session

---

loleaflet/src/map/Map.js

* Resolves: # [loleaflet-api.html: Copy documentation into source code as comments #2160](https://github.com/CollaboraOnline/online/issues/2160)

Copy loleaflet-api.html into code: cursorURL

---

cypress_test/integration_tests/desktop/calc/image_operation_spec.js
cypress_test/integration_tests/desktop/impress/sidebar_spec.js
cypress_test/integration_tests/desktop/impress/slide_operations_spec.js

Change-Id: I10532dc3307810476882944682928622dedd3994

cypress: increase stability of some tests

---

loleaflet/src/control/Control.LokDialog.js

Change-Id: Ibea42d1fa9c3c7fe8abc6b5efdb5dc93cab1a491

loleaflet: fix: Calc: Dragging scrollbar and releasing button over formula bar keeps drag mode active

---

cypress_test/Makefile.am
cypress_test/integration_tests/common/desktop_helper.js
cypress_test/integration_tests/common/impress_helper.js
cypress_test/integration_tests/desktop/calc/annotation_spec.js
cypress_test/integration_tests/desktop/impress/annotation_spec.js
cypress_test/integration_tests/desktop/writer/annotation_spec.js
cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
cypress_test/plugins/selectorList.js
cypress_test/plugins/whitelists.js
cypress_test/run_parallel.sh
loleaflet/src/control/Control.TopToolbar.js

Change-Id: I76f70262c13896ccb5bd41f68ac12b337db7f7c2
I have removed one test from comment scrolling because the behaviour of the comment scrolling has been changed 
Before the comments were scrolling on the individual basics per slide but now they show up in group per slides
hence we don't need that test

cypress: make annotation specs compaitable with NB

---

cypress_test/integration_tests/desktop/impress/sidebar_spec.js

Change-Id: Ic4d814112b97863ee4d812efa61869e059d705ee

cypress: fix: unstable desktop/impress/sidebar_spec.js

---

common/Freemium.hpp
configure.ac
loleaflet/src/control/Control.Freemium.js
wsd/DocumentBroker.cpp
wsd/LOOLWSD.cpp

Change-Id: If21f4471b3ad4b20f049e2e9f2330e31989ead0b

freemium: corrected typos

---

loleaflet/src/control/Control.Sidebar.js

Change-Id: Ic3763c300bf677914b06c6bf2296818770a3ec5e

Readonly: Do not show sidebar when in this mode

---

loleaflet/src/core/Socket.js

Change-Id: I65c7b350e8ca948c086aa9365a264cb32ed3cfb1
* Resolves: # 

Remove the tile file (in the iOS app) also if it failed to load

---

common/MobileApp.cpp
ios/Mobile/DocumentBrowserViewController.mm
ios/Mobile/DocumentViewController.mm

Brown paper bag fix

---

kit/ChildSession.cpp
loleaflet/src/layer/tile/CanvasTileLayer.js

* Resolves: # 
Forward port from co-6-4

New callback for calc document background color (master)

---

ios/Mobile/AppDelegate.mm

Change-Id: I45017d117ac439ff869971b41521d46ee7b5864b
* Resolves: # 

Fix typo in log message

---

tools/Stress.cpp

Change-Id: I3da8f8fef6df245617620955e09fbcf03ab31bdc
* Resolves: # 

stress: more work to base on SocketPoll.

---

loleaflet/admin/admin.html
loleaflet/admin/admin.strings.js
loleaflet/admin/src/AdminSocketOverview.js
wsd/Admin.cpp
wsd/Admin.hpp
wsd/AdminModel.cpp
wsd/AdminModel.hpp
wsd/DocumentBroker.cpp

Change-Id: I58a0463a2564932c4113b2e569d85e1406598858
* Resolves: # 

Admin console: Show wopi host on the dashboard.

---

loleaflet/admin/admin.html
loleaflet/admin/admin.strings.js
loleaflet/admin/src/AdminSocketOverview.js
wsd/Admin.cpp
wsd/Admin.hpp
wsd/AdminModel.cpp
wsd/AdminModel.hpp
wsd/DocumentBroker.cpp

Change-Id: I8ce68653200bb16877f6ced57fc77f6291b375a8

Admin Console: add wopihost name in the dashboard (backport)

---

loleaflet/css/btns.css
loleaflet/css/jsdialogs.css
loleaflet/src/control/Control.JSDialogBuilder.js

Change-Id: I88f1b97939c59927686bd72ea295f87abffcbe29

Mobile: do not use span inside of a button

---

net/HttpRequest.hpp
test/HttpRequestTests.cpp
test/HttpTestServer.hpp
test/helpers.hpp

Resolves #3065 and #3199
Change-Id: I07f7f126891f4d6b5137b45bf91cbcaa11796cda

wsd: chunked transfer and tests

---

loleaflet/css/loleaflet.css
loleaflet/css/toolbar-mobile.css

Signed-off-by: Pranam Lashkari <plashkari628@gmail.com>
Change-Id: Ie3755e01a92c39ab5ab178e7634fcdd7a27bdf73

leaflet: avoid font picker overlapping menu dropdowns

---

loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.NotebookbarBuilder.js

not focus notebookbar on button click

jsdialog: prevent from document losing focus on toolbutton click

---

android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java

When we create a document inside a network storage
we need to do it in a seperate thread
Change-Id: I43cb5f09dfab2f6c31de4647b4a312a3c29e746b
* Resolves: # 

android: Fix creating a new document causes an exception

---

android/lib/src/main/cpp/androidapp.cpp

Change-Id: Ib5dd0f28071285df3eecc8803a46b7156eabc044
* Resolves: # 

android: Decrease Logging level to information for release

---

loleaflet/src/control/Control.Menubar.js

closes 3177
Change-Id: Ib6959852263afba0b268d73f2879ec22357716c3
* Resolves: # 

loleaflet: add menubar shortcuts where applicable

---

loleaflet/test/load.js

There's a new parameter needed to be replaced
and it caused an exception
Change-Id: Icf6345d4d050116512ee0fe207c7ea756aad7ec8
* Resolves: # 

Fix perf-test broken

---

loleaflet/src/core/Socket.js

Change-Id: I92dce54e9032695f00f27b0180a8ab46861fad8b

loleaflet: show "Reconnecting..." indicator

---

loleaflet/src/map/handler/Map.Feedback.js

Do not show feedback dialog until welcome dialog is closed.
Change-Id: I8268308fe6f2c30967e097fdc2568245b7b64831

loleaflet: check if welcome dialog is open

---

loleaflet/css/jssidebar.css

Change-Id: I809378607b30d32758056b259ab7569d03a31763
Before:
After:

Sidebar justify-content flex-end for last-child

---

loleaflet/src/control/Control.MobileBottomBar.js
loleaflet/src/control/Control.StatusBar.js
loleaflet/src/control/Control.Toolbar.js
loleaflet/src/control/Control.TopToolbar.js

Change-Id: I07d8a0b8066414b5ac832ef70511c3f0e3a69bac
* Resolves: # 

Add ContectToolbar functionality

---

loleaflet/css/mobilewizard.css

Change-Id: Iecd1b99dce0e45331973b5f995c2721448b57ce5
fix alignment for
- wrap
- aligntoolbar

Mobile Sidebar fix some alignments

---

cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js
cypress_test/integration_tests/mobile/writer/bottom_toolbar_spec.js
loleaflet/src/control/Control.Toolbar.js

Change-Id: I3cdd3914e31a2e5b1952e20ec1c2cbbb2668133a
Cypress tests were failing due to this exception

loleaflet: fix: TypeError: window.onUpdateParts is not a function

---

loleaflet/src/control/Control.NotebookbarCalc.js

Signed-off-by: Stavros kois <s.kois@outlook.com>
Change-Id: I7f62745c7b9ea3fca49c124ef9fb76535107160a
* Resolves: #3264 
Fixes `Page...` button on Calc for NotebookBar

Fix Page... button on Calc for NotebookBar

---

loleaflet/src/control/Control.NotebookbarCalc.js

Signed-off-by: Stavros kois <s.kois@outlook.com>
Change-Id: I27f130dfbba25c2a357600c6cb0cd6903df4f3bf
* Resolves: #3264
Adds missing parameters

Follow up #3277 -  Also add missing parameters

---

loleaflet/images/close_toolbar.svg
loleaflet/images/lc_closedocmobile.svg

Change-Id: I77491fe09090617123dd6db39b654511993befc7

Icon fix for closedocmobile it was to height at mobile insert menu

---

cypress_test/integration_tests/common/desktop_helper.js
cypress_test/integration_tests/common/mobile_helper.js
cypress_test/integration_tests/desktop/impress/annotation_spec.js
cypress_test/integration_tests/desktop/writer/annotation_spec.js
cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
cypress_test/integration_tests/mobile/impress/annotation_spec.js
cypress_test/integration_tests/mobile/writer/annotation_spec.js
loleaflet/Makefile.am
loleaflet/css/loleaflet.css
loleaflet/css/mobilewizard.css
loleaflet/html/loleaflet.html.m4
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.MobileWizardPopup.js
loleaflet/src/control/Control.UIManager.js
loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/CommentListSection.ts
loleaflet/src/layer/tile/CommentSection.ts
loleaflet/src/layer/tile/TilesSection.ts
loleaflet/src/map/Map.js

This change introduces comments list with reduced size for small browser windows or tablets.

Annotations for small windows

---

ios/Mobile/Info.plist.in

Change-Id: I41e1ab374868b9f598c054914e29a1a751de1475
* Resolves: # 

Add explanatory comment for the CFBundleShortVersionString

---

kit/Kit.cpp
loleaflet/src/control/Control.Toolbar.js
loleaflet/src/core/Socket.js
loleaflet/src/errormessages.js
net/HttpRequest.cpp
net/HttpRequest.hpp
test/HttpRequestTests.cpp
test/HttpTestServer.hpp
test/HttpWhiteBoxTests.cpp
test/helpers.hpp
test/lokassert.hpp
wsd/ClientSession.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp
wsd/RequestDetails.cpp
wsd/RequestDetails.hpp
wsd/Storage.cpp

- leaflet: explanatory message when loading fails while unloading
- wsd: allow new views while unloading
- loleaflet: Process the reconnection in _onSocketClose in a timeout.
- wsd: http: reason phrase is optional
- leaflet: better docunloading message to the user
- wsd: close the upload socket if exit-save
- leaflet: more accurate wording in comment

Ports from 6.4

---

loleaflet/src/core/Socket.js
test/HttpWhiteBoxTests.cpp

- wsd: test: correct include order for operator resolution
- leaflet: allow only more restrictive permission change

Port from 6.4

---

loleaflet/src/core/Socket.js

Change-Id: Iee192f7e75f0ede12c0b3cf34bf04ff3ed50c110

leaflet: allow only more restrictive permission change

---

loleaflet/admin/src/AdminSocketOverview.js
net/Socket.cpp

Change-Id: I54c4819f463e6b340e66968fb6b223414da6fa18
* Resolves: # 

Use inner-text for active users count.

---

loleaflet/css/jssidebar.css

Change-Id: I6efad6535cafe29aa719ff1de5a535f527680443
* Resolves: # 

Calc Sidebar fix for Number Format Section

---

loleaflet/css/jssidebar.css

decimal places input is now show
n

sidebar: show decimal places input

---

android/lib/src/main/java/org/libreoffice/androidlib/COWebView.java
android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
android/lib/src/main/res/layout/lolib_activity_main.xml

This issue is fixing some unidentifed keys
being sent such es 'space' also some keydown and up
events not being sent correctly. Fixes some shortcut
problems.
Change-Id: I6706a7581ef3c4e4fa8cf26209af93d77423740c
* Resolves: # 

Fix android does not send keyevents correctly

---

kubernetes/helm/collabora-online/templates/ingress.yaml

Change-Id: I0ffcc8dca1cff7dc4c6eaec115d2030a250aca33

kubernetes: added nginx ingress config

---

loleaflet/css/notebookbar.css
loleaflet/js/ResizeObserverPolyfill.js
loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/map/Map.js

- use ResizeObserver polyfill
- avoid using null reference

fix firefox 52

---

loleaflet/css/jssidebar.css

Change-Id: I28720a9d0c1b85bcd598bc43343d429cbb85751a
* Resolves: # 

Sidebar fix alignment for LB_SHOW_COLOR, LB_GLOW_COLOR and button2

---

tools/Stress.cpp

Change-Id: I014d6a357f5d089f7c89f2d2441c5a30df5a0df4
* Resolves: # 

stress: Initialize SSL

---

cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js

Change-Id: Id9039082f19b41caf96c9e737cb8067b9ef749f1
* Resolves: # 

cypress: restore text in shape tests

---

loleaflet/src/control/Control.Notebookbar.js
loleaflet/src/control/Control.NotebookbarBuilder.js

Bin full screen button and hamburger menu entry in mobile apps

---

cypress_test/integration_tests/common/calc_helper.js
cypress_test/integration_tests/multiuser/calc/repair_document_spec.js

Change-Id: I1e0f02e380589058a2631c7a40cdd7f63987831d

cypress:fix: unstable calc/repair_document_spec.js

---

loleaflet/src/layer/tile/ImpressTileLayer.js

Impress document layer is created

loleaflet: ensure to create doc previews when ..

---

tools/Stress.cpp

Change-Id: I3fe58c4e3e1a6b633fa4e94ba66db2d4bb465699
* Resolves: # 

stress: remove older code-paths and make the help helpful.

---

common/SigUtil.cpp
common/SigUtil.hpp
common/Util.cpp
common/Util.hpp
wsd/LOOLWSD.cpp

- wsd: avoid misbehaving library cleanup
- wsd: allow shutting down during startup

Shutdown improvements

---

test/traces/calc-sheet-edit.txt
test/traces/impress-slide-edit.txt
test/traces/writer-document-edit.txt

Created traces for text document, Spreadsheet and Impress files using real editing sessions
Signed-off-by: Nnamani Ezinne Martina <nnamani.ezinne@collabora.com>
Change-Id: I99e290b1cc9c2d14e1341a211190d7d2a64b2ea4
* Resolves: # 

Trace: Generated loolstress traces

---

loleaflet/src/layer/tile/CommentListSection.ts
loleaflet/src/layer/tile/CommentSection.ts
loleaflet/src/layer/tile/ImpressTileLayer.js

* Resolves: #3485
Fixes https://github.com/CollaboraOnline/online/issues/3485

fix: comments do not appear when PDF/Impress file is opened [master]

---

loleaflet/admin/src/AdminSocketOverview.js

Change-Id: I36b1aed552568de8fb3338cf77550f6c88ca46d0
* Resolves: # 

AdminSocket: Decode filename uri.

---

loleaflet/src/layer/tile/TilesSection.ts

Set background color to white.
Change-Id: I05d0284573b9ce63604ecac03dd011a6e91c6680
* Resolves: # 

Writer: Remove margin from page background.

---

loleaflet/html/loleaflet-help.html

Change-Id: I226bc4deb4d07f0283c2e3ad87e36168e20bd0e2

loleaflet: Open external URL in help in new tab

---

loleaflet/src/map/handler/Map.Keyboard.js

Change-Id: I0a306377bca31ae2d118a41103b9b75424f60794
* Resolves: # 

PDF View: Enable Home & End buttons.

---

loolkitconfig-mobile.xcu
loolkitconfig.xcu.in

Change-Id: I1d2b17241494036e1f68d37eb23c934c8c187b5f

fix #3491: Don't show the 'corners' in the text documents

---

android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java

If network provider is used, on some devices download/upload
operations can cause an exception. Creating a new file is already
covered but better to cover saving back operation too.
Change-Id: I90ffa890ed864e730c16c68bc777b1d6371fd0a8
* Resolves: # 

android: Do copy back in another thread for network operations

---

loleaflet/src/control/Control.NotebookbarBuilder.js

…ction
Change-Id: Ibd19ead342a50658eae76808f2af81f378ac17cc
* Resolves: #3513 

loleaflet: calc: fix: comment button active when there is graphicselection

---

loolwsd.xml.in
wsd/LOOLWSD.cpp
wsd/QuarantineUtil.cpp

some code cleaning for code repeatation
Change-Id: I4ea7972ed711eba41c7bbcfa36b8db607ad3d738

Quarantine: minor correction for path resolution

---

wsd/FileServer.cpp

Change-Id: I5410e787db5ac0461a01b3c877fb5b91e4677e2b

wsd: do not embed cookies when reuse_cookies is disabled

---

loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.LokDialog.js

It should return to the integration instead
Change-Id: I1b2ce5013365faa4f67263866764ed4bd34277d7
* Resolves: # 

Fix closing CSV dialog returns an exception

---

test/helpers.hpp

Change-Id: I8627f16fb7ad67561312d3053d855bab8008ab75

test: double the timeout in isDocumentLoaded() for sanitizers

---

kit/Kit.cpp

built-in hard-link support performs extremely badly otherwise.
Change-Id: I26d5080590538cb6342d64e2e0a4023bbc84c427
* Resolves: # 

Optimize for overlayfs by forcing an initial copy to linkable/

---

loleaflet/Makefile.am

By removing those files that are not needed anymore and
thus avoiding extra useless requests
Change-Id: I8fcbd8053edd0ee00d388117ccd77094fc4594ed

Fix: empty CSS file errors

---

test/traces/impress-edit-text-on-shape.txt
test/traces/writer-add-bullet.txt

Created trace for adding and editing slides and shapes in Impress. And also for re-typing and adding bullet points using a large Writer file
Signed-off-by: Nnamani Ezinne Martina <nnamani.ezinne@collabora.com>
Change-Id: I3541295fada230338acb934409c2bcb80730354b
* Resolves: # 

Trace: Writer and Impress: Generated loolstress traces

---

android/app/build.gradle.in
android/lib/build.gradle.in

Change-Id: Id220d003dd9e8ada616ea6af11652c6fc1d4e5fa

Android: change targetSdkVersion and compileSdkVersion to 30

---

loleaflet/src/control/Control.NotebookbarImpress.js
loleaflet/src/control/Control.Tabs.js
loleaflet/src/unocommands.js

Change-Id: I627103970ce34cf1612dfe1c2f072e4f58596965
* Resolves: #3527 #3489 

loleaflet: fix: UX inconsistency

---

cypress_test/integration_tests/mobile/writer/annotation_spec.js
loleaflet/html/debug.html
wsd/FileServer.cpp

Change-Id: I4b4e59721fb1deec709bc778a8e59a52fb466a3a

debug.html:use iframe as a target after submiting form

---

loleaflet/src/map/handler/Map.Keyboard.js

Change-Id: I1f1ce57faa7e9afef621cc5550174e11988d5554
* Resolves: # 

Map.Keyboard.js: Remove duplicate definiton.

---

loleaflet/html/debug.html

Change-Id: Icc948a7ba39be1d4deb5178dd5a58a7708e7dbea

debug.html: fix: cannot open files when ssl is disabled

---

wsd/QuarantineUtil.cpp

Improve quarantining error handling

---

cypress_test/integration_tests/desktop/writer/undo_redo_spec.js
cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
cypress_test/integration_tests/mobile/writer/undo_redo_spec.js
cypress_test/integration_tests/multiuser/writer/repair_document_spec.js

Change-Id: I1870ba3d9111694e2df756bd9a5b06c54aa8aab3

cypress: disable writer/repair_document_spec.js temporarily

---

cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js

Change-Id: I202a23bbc43c5d45a87a4dea305f135181e92430

cypress: disable writer/hamburger_menu_spec.js/repair test temporarily

---

loleaflet/src/core/Socket.js

Change-Id: I72e716ae343e08d6e7a028aacbfcedb6f5859404

loleaflet: Make buttons in password entry dialog translatable

---

browser/src/map/Map.js

Signed-off-by: Luka Trovic <luka@nextcloud.com>
Change-Id: I76b945c1405479a9094ea8443e61671910261524
* Resolves: # 

update last modified time label & translation

---

.gitpod-files/loolwsd-gitpod.xml
browser/html/cool.html.m4
browser/test/load.js
configure.ac
loolwsd.xml.in
wsd/FileServer.cpp
wsd/LOOLWSD.cpp

Change-Id: I175e5256fcae42477cb2c84fc2b4048aca40bed7
* Resolves: # 

more descriptive name of a config setting for debugging: browser_logging

---

browser/css/cool.css
browser/html/cool.html.m4

- Allow for dynamic resizing (flex box)
- Set sub elements with id so we can use less background images
in the main parent element and use it directly in its own element
- Also make integrator logo optional and easy to switch on/off via
flex-grow: 1 | 0 respectively
Change-Id: I837b26d77e0bfa722c6ff3d4a247a36ef8944797

About Dialog: Increase structure flexibility

---

browser/src/control/Control.Sidebar.js
browser/src/map/Map.js

- apply new height limit when window was resized
- remove leftovers after pixel-based sidebar

sidebar: fix resizing

---

browser/src/map/Map.js

* remove old, unused code
* String.locale respects the language requested by the integration
Change-Id: I799856bdd721427e7d58be0a8fcddba866b726ea

small cleanup around "Last saved:" label

---

browser/html/debug.html
cypress_test/integration_tests/common/helper.js

in html/debug.html
Change-Id: I7e14bf9deb140090fbb39c8facfaf9360e5a1a7d

browser: rename 'loleafletframe' -> 'coolframe'

---

.gitignore
.gitpod-files/loolwsd-gitpod.xml
Makefile.am
configure.ac
loolwsd.spec.in
loolwsd.xml.in
man/coolconfig.1
man/loolconvert.1
man/loolforkit.1
man/loolmount.1
man/loolwsd-generate-proof-key.1
man/loolwsd-systemplate-setup.1
man/loolwsd.1
tools/Config.cpp
tools/WebSocketDump.cpp
wsd/FileServer.cpp
wsd/LOOLWSD.cpp

Change-Id: Ied23cb46a668f754931fc125745b674b546a0195
* Resolves: # 

rename: loolconfig -> coolconfig

---

loolwsd.xml.in

Change-Id: I570d13e696e7e2dc01dd29751df26eb532fa1a76
* Resolves: # 

Default to automatically cleaning up high resource consumers.

---

docker/from-packages/scripts/start-collabora-online.sh

...and user interface mode parametrizable.
Change-Id: Id4538f27f5aef9190c546ec8dc1d505042837aeb

docker: Make Notebookbar the default again

---

docker/from-packages/RHEL8
docker/from-packages/Ubuntu

This will speed up docker build if only something in start-collabora-online.sh has changed.

Move adding the start script after running the install script.

---

browser/css/override-vex.css
browser/src/map/Map.js

Signed-off-by: Luka Trovic <luka@nextcloud.com>
* Resolves: # 
- Updated "Last modification: ..." to "Last saved ..."
- Updated idle document popup content

update idle document modal content

---

loleaflet/src/layer/tile/CanvasSectionContainer.ts
loleaflet/src/layer/tile/ScrollSection.ts

This improves user experience.
Change-Id: Ia1706610727015a2fd8f35c42c1cc9583883fd45
* Resolves: # 

Scroll bars won't move when pointer position is not parallel.

---

common/Log.cpp
common/Log.hpp

Change-Id: I895bff775b36db48fa88f02c8b81841567e62271
* Resolves: # 

Write timestamps to log in local time and add time zone differential

---

.gitignore
Makefile.am
common/Common.hpp
debian/loolwsd.postinst.in
docker/from-source/Debian
docker/from-source/Ubuntu
docker/from-source/openSUSE
kit/ForKit.cpp
loolwsd.spec.in
man/coolconfig.1
man/coolforkit.1
man/loolconvert.1
man/loolmount.1
man/loolwsd-generate-proof-key.1
man/loolwsd-systemplate-setup.1
man/loolwsd.1
scripts/segv-catch.pl
wsd/LOOLWSD.cpp
wsd/README
wsd/protocol.txt

Change-Id: I1de688dce4b068bff35451604486b72ecc8c91d4
* Resolves: # 

rename: loolforkit -> coolforkit

---

loleaflet/css/loleaflet.css
loleaflet/html/loleaflet.html.m4

Massage the HTML and CSS for the Help > About to be like in master.
Change-Id: I2b7c346752d010826e900f1e65fb5d8261cb55ca
* Resolves: # 

Add the lokit-logo here, too

---

wsd/LOOLWSD.cpp
wsd/LOOLWSD.hpp

These instances are really private to the
LOOLWSD.cpp file and need not be in the class.
Change-Id: I4162afd7ac1a0fdc995518d956361a65678c3989

wsd: return local statics to LOOLWSD.cpp

---

loolwsd.xml.in
wsd/LOOLWSD.cpp
wsd/QuarantineUtil.cpp

Change-Id: Idabef2aec46d6b7c194ef06f4235b60d6ad29e4a

quarantine: automatically delete quarantined files after specified time

---

browser/html/cool.html.m4

Change-Id: I6da26b85d7b22fed498269a978762e8b9b5183ae
* Resolves: # 

s/lool/cool/ here, too

---

Makefile.am
coolwsd.xml
cypress_test/Makefile.am
loolwsd.spec.in
test/Makefile.am
test/run_unit.sh.in

Change-Id: Ia44f7f96bcad7200031ad87f6a6fdd3e361f2808
* Resolves: # 

rename: loolwsd -> coolwsd only binary

---

browser/src/control/Control.Menubar.js
browser/src/map/handler/Map.Feedback.js

Change-Id: I2490feb7f7d12a80cc0a407327e8659936c17ff3

browser: add menu item "Send Feedback"

---

browser/images/lc_feedback.svg
browser/src/control/Control.NotebookbarBuilder.js
browser/src/control/Control.NotebookbarWriter.js

Change-Id: I02971031d2300a828a0fb4d2bf5799be92a8b74e

notebookbar: add tool item 'Send Feedback'

---

browser/src/control/IFrameDialog.js

Change-Id: I9c2a0e48b724f53ce9b30398856895edd1f546d5

browser: fix typo 'querySelectors' -> 'querySelector'

---

browser/src/map/handler/Map.Feedback.js

in the feedback handler.
Change-Id: Ib4a19c5043c32877dda048f69293070f38147de5

browser: fix local storage values

---

cypress_test/integration_tests/mobile/writer/mobile_wizard_state_spec.js

Change-Id: I6db2ce276bf6038d2aac86611d7e06731ca47be9

cypress: fix: writer/mobile_wizard_state_spec.js

---

wsd/FileServer.cpp
wsd/Storage.cpp

Change-Id: I013a042b47906ab48a0d02de422982dd8a6c85e4
* Resolves: # 

rename: add compatibility for existing integrations

---

etc/apache2/coolwsd.conf
etc/nginx/coolwsd.conf
wsd/COOLWSD.cpp

Change-Id: I8a3930a01a18be32bee657142f872ba58383594d
* Resolves: # 

backward compatibility: /lool/convert-to endpoint

---

wsd/FileServer.cpp

Change-Id: I72da1c8e3cfea0d4984c80b6dddd3e39af020bee

wsd: fix: don't use hardcoded PostMessageOrigin

---

browser/src/map/handler/Map.Feedback.js

Change-Id: Ie6cba7f5582cc23aa50398d39964d1559895cbdf

feedback: increase a day when "later" button is pushed

---

browser/src/map/handler/Map.Feedback.js

case.
Change-Id: Ia779d95cba6aec69207239420012f926a3ba93ad

feedback: show only to the main user in a multi-user document

---

Makefile.am

Change-Id: I16375c3d1c55cf7bda690a3c71dd5c996cd8be5a

Cleanup the old binaries

---

wsd/DocumentBroker.cpp

additionals:
make sure quarantine does not fail on the exit
Change-Id: I8843ba7e72dc3703c1168b57c9927598bfa5d1f7

quarantine: quarantine file on loading

---

browser/src/map/Map.js

Signed-off-by: Luka Trovic <luka@nextcloud.com>
Change-Id: I55f9a14ea1bc737e6b285d5406760fbb2bd9a64b
* Resolves: # 

fix feedback for the last saved time over 1 day

---

browser/html/cool.html.m4
browser/src/core/Socket.js

Change-Id: I555e94c4c6a14c08978079beb109854952d5dadc
* Resolves: # 

About box: bring back the coolwsd-id and make version labels localizable

---

browser/src/control/Permission.js

Change-Id: I1c18ca74d1436f669f0415285efee78abb2c1e5a
* Resolves: # 

xlsb type should be readonly and added option to saveas odf

---

browser/src/control/Control.MobileWizardPopup.js

Uncaught TypeError: app.sectionContainer is undefined
_hideWizard http://localhost:9980/browser/00536e91a/src/control/Control.MobileWizardPopup.js:55

fix: undefined usage in _hideWizard

---

.gitpod.dockerfile
.gitpod.yml
README.md

Fix many issue and improve the overall workflow,
thanks @bvarga91 for reporting it and for helping with tests [#3712](https://github.com/CollaboraOnline/online/issues/3712)

Improve gitpod

---

.gitpod.yml
README.md

As this does not affect people who use the VS Code desktop integration
Change-Id: I10826505d6eec9423a29c93c0c0707c289e8cadb

GitPod: make instructions more clear

---

browser/src/control/Control.Command.js
browser/src/control/Control.JSDialogBuilder.js
browser/src/control/Control.NotebookbarBuilder.js
browser/src/control/Control.PartsPreview.js
browser/src/control/Signing.js

important when using richdocumentscode

jsdialog: create correct paths for images

---

browser/test/bootstrap.js

Change-Id: I3a4b419a7307b11f9ce91bdc4fb1539b0ceb1160
* Resolves: # 

perf-test: print out URL to watch document from.

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/org/libreoffice/androidapp/ui/FileUtilities.java
android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java
android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java

Also request odf if editing is needed otherwise continue readonly.
Change-Id: I21060b24f6b4733024d8f0ddee504ee9eb554372
* Resolves: # 

add option to open xlsb type with android

---

browser/src/control/Control.JSDialogBuilder.js

instead of listbox use edit field so user can type anything in Find & replace dialog

Fix regression: use edit field in find and replace dialog

---

loleaflet/html/loleaflet.html.m4

Change-Id: Ia1c5c4fca64762787240398f38de14d5d973ba77
* Resolves: # 

Use the branding.js also in the mobile apps

---

browser/src/map/handler/Map.Keyboard.js

Change-Id: I2084c1760e17d6464e0fd7a6a011666533e1d50a
* Resolves: #3629 

browser: fix: cannot use keyboard shortcut to search if statusbar is hidden

---

cypress_test/data/multiuser/cypress-multiuser.html
cypress_test/integration_tests/common/calc_helper.js
cypress_test/integration_tests/common/helper.js
cypress_test/integration_tests/common/mobile_helper.js
cypress_test/integration_tests/desktop/calc/annotation_spec.js
cypress_test/integration_tests/desktop/calc/macro_spec.js
cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
cypress_test/integration_tests/desktop/impress/fullscreen_presentation_spec.js
cypress_test/integration_tests/desktop/writer/focus_spec.js
cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
cypress_test/integration_tests/mobile/calc/alignment_options_spec.js
cypress_test/integration_tests/mobile/calc/annotation_spec.js
cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js
cypress_test/integration_tests/mobile/calc/focus_spec.js
cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
cypress_test/integration_tests/mobile/calc/row_column_operation_spec.js
cypress_test/integration_tests/mobile/calc/spellchecking_spec.js
cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
cypress_test/integration_tests/mobile/impress/impress_focus_spec.js
cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
cypress_test/integration_tests/mobile/writer/annotation_spec.js
cypress_test/integration_tests/mobile/writer/focus_spec.js
cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
cypress_test/integration_tests/multiuser/calc/sheet_operations_spec.js
cypress_test/integration_tests/multiuser/impress/repair_document_spec.js
cypress_test/integration_tests/multiuser/writer/track_changes_spec.js

cypress: use WOPI endpoints in cypress test 

---

wsd/TileCache.cpp

Change-Id: I373f85e68964610fe88cb6fa057c548b9a50fb51

TileCache: improve parsing in parseInvalidateMsg()

---

browser/src/map/handler/Map.Feedback.js

Change-Id: I0966b257f3aae1376ff5ee06d286e03886a5e0da

feedback: delay 2 days and count open documents

---

loleaflet/src/control/Control.JSDialogBuilder.js
loleaflet/src/control/Control.LokDialog.js

Change-Id: Ic0871a2a78bf3326c6edc1453802b24c657c1c12
* Resolves: # 

android: fix csv import dialog ok btn exits the app

---

browser/images/minus.svg
browser/images/plus.svg

Change-Id: I0c805370bf17ea4f2f73964b9c6c867544235713
* Resolves: #3779

Toolbar-down: Zoom: minus/plus icon fix #3779

---

browser/css/toolbar.css
browser/images/close_toolbar.svg
browser/images/lc_cancel.svg
browser/images/lc_downsearch.svg
browser/images/lc_nextrecord.svg
browser/images/lc_nexttrackedchange.svg
browser/images/lc_previoustrackedchange.svg
browser/images/lc_prevrecord.svg
browser/images/lc_upsearch.svg
browser/images/lc_view100.svg
browser/images/lc_zoomreset.svg
browser/images/minus.svg
browser/images/plus.svg

Change-Id: If2ac4f403b2e691ad6d4f24e5ffbfaffe8a13ce6
* Resolves: #3778

Toolbar-down: icon update #3778

---

browser/src/control/Control.Toolbar.js

* Resolves: #2484
fix from szymon see #3287 3287
All done and fine.

Toolbars: add support for 'default' context patch from eszkadev

---

configure.ac
test/TileCacheTests.cpp

When I did the previous "C++17" commit I removed C++11 and C++14
from the checked list, but I missed the fact that the code checked
for C++17/14/11 and then did nothing with it. So actually do use
the detected required C++ standard.
Signed-off-by: Luboš Luňák <l.lunak@collabora.com>
Change-Id: Ia82d14d11f81456abed7ee2609903afe5366f5e7

actually require C++17

---

browser/src/control/Control.JSDialog.js

it requires in the core: https://gerrit.libreoffice.org/c/core/+/126565

jsdialog: handle initial focus in dialog

---

loleaflet/src/control/Permission.js

Change-Id: I6dd19aeee18d5f157529a459a6bd4a7ea2d93840
* Resolves: # 

populate saveas dialog with the filename on offering save-as

---

wsd/COOLWSD.cpp

Change-Id: I8a9a05498649dfea80ec425671326aa0c62d4917
* Resolves: # 

add pdf version option for conversion

---

browser/src/control/Control.JSDialog.js
browser/src/layer/tile/CanvasTileLayer.js

- default button is the first button in the form
- change main container of a dialog into <form>
- create hidden default button as a first element in the form

jsdialog: handle default button

---

wsd/QuarantineUtil.cpp

Change-Id: I9159c6fe33d66f64e56e084a203af74629e330c6

Quarantine: fixed quarantining when jail mounting is disabled

---

kit/ChildSession.cpp
loleaflet/src/control/Control.AlertDialog.js
loleaflet/src/core/Socket.js
loleaflet/src/errormessages.js

check if we save-as successfully before proceed with downloadas

---

cypress_test/integration_tests/desktop/writer/delete_objects_spec.js
cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
cypress_test/integration_tests/multiuser/impress/repair_document_spec.js
cypress_test/integration_tests/multiuser/writer/repair_document_spec.js

Change-Id: Ia99f75302a988fc2ef744807e01ba6441ff161ec

cypress:added retries parameter in some fragile tests

---

cypress_test/integration_tests/common/desktop_helper.js
cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
cypress_test/integration_tests/desktop/impress/annotation_spec.js
cypress_test/integration_tests/desktop/writer/annotation_spec.js
cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
cypress_test/integration_tests/multiuser/impress/repair_document_spec.js
cypress_test/plugins/selectorList.js

Change-Id: I02b42b8943ecfedb5a950d062a0fef2a7e3f3e6b

cypress:disable repair_document_spec.js temporarily

---

browser/src/control/Control.Command.js
browser/src/control/Permission.js
common/CommandControl.hpp
configure.ac
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp

Change-Id: I4dadb535e722cbeaacf177b30247899795d048f9

freemium: added option to make freemium user read only

---

browser/src/control/Control.Menubar.js

Change-Id: I9e88d95d97b0991d11385f451334f3de891fcf7f

browser: Add Status bar toggle to View menu in Calc

---

coolwsd.xml.in

Change-Id: I6defd34a07154f386c50f15a0f5bda8f9f6acaf7

coolwsd.xml - extend private subnet in post_allow

---

browser/Makefile.am

Change-Id: Ic34695faa47e47dd4951837a8a1dd2ba288ece62

added inline source to debug ts in browser

---

loleaflet/src/control/Control.LokDialog.js

Adjust the drop-down dialog to the #map element
to show the correct position sent by the server.
Change-Id: I74a6d7402438241aae77a18699c3297d64b34098

browser: add 'dropdown' dialog type

---

browser/src/map/handler/Map.FileInserter.js

Change-Id: I56d38f05d8da4fc55393203764692ca2b5f864f2
* Resolves: # 

Fix InsertFile returns 400 after an idle reload

---

wsd/DocumentBroker.cpp

Change-Id: I699aaed92d41f76a8eb9de6bdb65608099802663

wsd:fix: Document conflict window not shown

---

browser/images/lc_fontworkshapetype.fontwork-circle-pour.svg
browser/images/lc_fontworkshapetype.fontwork-fade-down.svg
browser/images/lc_fontworkshapetype.fontwork-triangle-up.svg

- best check on mobile
- Insert Fontwork
- edit Fontwork in the sidebar
Change-Id: I2f9307fb8e45d9dfa8692adb93c79baef7c3c770

Fontwork Shape Type use correct colors

---

browser/src/layer/tile/CalcTileLayer.js

Change-Id: I37ebdadc4186e5159125c7089b64f87ca929f071
* Resolves: # 

CalcTileLayer: Convert cell selections to tiletwips.

---

wsd/DocumentBroker.cpp

Change-Id: Ibc5338b34713233c540e0de938dbb76b88398ef5

wsd: fix: remove unnecessary condition

---

browser/Makefile.am
browser/css/override-smartmenus.css

Change-Id: Ib42767f2110fc7bd0f471ea490f5430ae2958021

Fix top menu for split screen view

---

browser/src/map/handler/Map.TouchGesture.js

Change-Id: I2dcf29e08f137f0553d0e598da60b54dc68e5685

scrolling: increase scrolling speed with each swipe

---

browser/src/control/Control.CornerGroup.js
browser/src/control/Control.CornerHeader.js

This makes keyboard handler does not receive key events
and functions like delete does not work.
Change-Id: If49d8ff760c9db774d85d8fcdb7eb40fd85c4329
* Resolves: # 

Fix selecting all cells with top left corner btn make the focus lost

---

net/ServerSocket.hpp
net/Socket.cpp
net/Socket.hpp
wsd/COOLWSD.cpp

Create a link to the master UDS file inside the jail when we aren't using abstract sockets.

---

wsd/AdminModel.cpp

Target version: master 
Added new LOG_INF line

log more info about administrative document adding

---

cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
cypress_test/plugins/selectorList.js

Change-Id: I2ef0bcbffbc3644d88a86eb00d61dde548704072

cypress: fix: NB writer/top_toolbar_spec.js

---

ios/Mobile.xcodeproj/project.pbxproj

Change-Id: I2a2d7301cd9fa65bb96c2bf221f51fbc179d965e
* Resolves: # 

Add some more source files for debugging convenience

---

Makefile.am
tools/Config.cpp
tools/ConfigMigrationAssistant.cpp

Change-Id: I44e16bd07588887e01732b430e4c6e368a034cd1

coolconfig: Add config migration tool

---

browser/css/menubar.css

cherry-picked and put into its own individual commits (plus solve conflicts) from https://github.com/CollaboraOnline/online/pull/3839

Private/andreas kainz/toolbar remove bg color

---

kit/ChildSession.cpp

this will help solve the deadloack for failing CI between:
https://gerrit.libreoffice.org/c/core/+/128107
https://github.com/CollaboraOnline/online/pull/3960
Change-Id: If3b13b49994ace7de48b0da7a99602508c36fcd7

this is a temporary commit which will be reverted

---

tools/ConfigMigrationAssistant.cpp

- new method for migrating "host" entries:
only done if there are new entries in the old config,
and then replace the list in the new config with the old one
- other small changes, eg.
don't migrate special default values if they match target value
Change-Id: Idf43db4068c163077109825486855a259666181c

coolconfig: Updated "host" entry handling in migration tool

---

browser/src/control/Control.AutofilterDropdown.js
browser/src/layer/Layer.js
browser/src/layer/Popup.js
browser/src/layer/marker/Cursor.ts
browser/src/layer/tile/CalcTileLayer.js
browser/src/layer/tile/CanvasSectionContainer.ts
browser/src/layer/tile/CanvasTileLayer.js
browser/src/layer/tile/TilesSection.ts
browser/src/layer/vector/CanvasOverlay.ts
browser/src/layer/vector/Path.Transform.js
browser/src/layer/vector/SVGGroup.js
browser/src/layer/vector/SplitPanesSVG.js
browser/src/map/Map.js
kit/KitHelper.hpp

Calc RTL follow-up patches

---

cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

cypress: restore writer shape properties tests (backport)

---

browser/css/menubar.css

cherry-picked and put into its own individual commits (plus solve conflicts) from #3839

Classic: Vertical align main menu

---

common/CommandControl.hpp
configure.ac
loleaflet/src/control/Control.Command.js
loleaflet/src/control/Permission.js
wsd/DocumentBroker.cpp
wsd/LOOLWSD.cpp

freemium: added option to make freemium user read only 6.4

---

loleaflet/src/layer/tile/CalcTileLayer.js
loleaflet/src/layer/tile/CommentListSection.ts
loleaflet/src/layer/tile/CommentSection.ts

co-6-4: Private/mert/calc comment fixes backport

---

browser/src/control/Control.JSDialogBuilder.js

Change-Id: I5226bb374d7a79ca2a531c3b2d3af53d3e4d1954

Mobile: _explorableEntry: hide images that failed to load

---

net/Socket.hpp
net/WebSocketHandler.hpp
wsd/ClientSession.cpp

co-6-4: Exceptions handling

---

man/coolconfig.1

Follow-up to a6b258a0db07a4fa720903f1fcf2e32c4677bb47
Change-Id: I79e457bb6fd410cbb40de500d2f3ce0f33f2e9ae

coolconfig: updated man page

---

coolwsd.xml.in

Change-Id: Id12487efd4d3bd3dee1e6c4b7ed98b41a7465c37

coolwsd.xml: Remove confusing server_name description part

---

tools/ConfigMigrationAssistant.cpp

Also fix ssl.hpkp.pins.pin handling.
Change-Id: I48ffe3db9ec0ff2db53f5e8cac5ec3d7aa55e66c

coolconfig: migrate missing entries in special cases

---

browser/src/control/Control.LokDialog.js

use margin-inline-start with relative offset instead of fixed position

RTL: fix tunneled child windows

---

browser/css/jsdialogs.css
browser/css/jssidebar.css
browser/css/notebookbar.css

- spinfields, units
- notebookbar alignment
- dropdowns

RTL sidebar & notebookbar fixes

---

browser/html/cool.html.m4

Change-Id: I1bf6c3279e4d1d07f23973e6742de7618d4141e4
* Resolves: # 

Add clarification about %FOO% and mobile apps

---

README.md

Change-Id: I6bb602dcc987235460bf019971f515a6ca29cb76

Link PR policy shields to contributing guidelines

---

browser/src/control/Control.Notebookbar.js
browser/src/control/Control.NotebookbarCalc.js
browser/src/control/Control.NotebookbarDraw.js
browser/src/control/Control.NotebookbarImpress.js
browser/src/control/Control.NotebookbarWriter.js

remove undo and redo commands from shortcutstoolbox
add undo and redo to home tab
in all apps
Change-Id: I914fe9d2955a64d124d9c76aaaa769b0e1292684

NB undo and redo commands at home tab

---

common/FileUtil.hpp

If these fail, we wstill want something sensible to go on.
Change-Id: Iabd8b60a67808a17767ac63037636e3aadd7be48
* Resolves: # 

fileutil: ubsan - clear state records before stat / lstat.

---

browser/html/cool.html.m4
browser/test/load.js
coolwsd.xml.in
wsd/COOLWSD.cpp
wsd/FileServer.cpp

Change-Id: I679328e29f2e2297491c73249632627d01a1bf42

theme: added config flag to switch between integration and cool themes

---

browser/src/control/Parts.js

Signed-off-by: Emmy Denison <emmydenison@gmail.com>
Change-Id: I7b851ca431beff5f184ae16e53238242cf2814ac
* Resolves: #2160 

Copy cool-api.html into code: getCustomPreview()

---

browser/src/unocommands.js

It should be Shapes as it was before.
----
Context:
Regression started with following commit:
5c2e457eae1f7fcc707173a88efd5516e61fa9c5
Change-Id: I85f064e2158175dd7910b09d03c29255117c345e

Rename BasicShapes string, again

---

test/UnitInsertDelete.cpp
test/UnitWOPILock.cpp
test/WopiTestServer.hpp

- wsd: test: kill poco in pasteBlank
- wsd: test: improve lock tests

Test improvements

---

browser/js/global.js

Paranoia in case a back-port causes an unexpected exception.
Change-Id: Ic3d287618cb1e035cd17597f8d336d5f698a8014
* Resolves: # 

compatibility with master's new window.app.console logging.

---

configure.ac
wsd/FileServer.hpp

Change-Id: Ibfb5de3dc5d4c5a57f4d50bf0a9bbc45df2ecadb

Rename: outdated loleflet strings

---

browser/images/lc_firstrecord.svg
browser/images/lc_lastrecord.svg

2px thick lines same as other icons in the statusbar
Change-Id: I08d493038047be16af4c8f4a12cdb22684decf11

Update Firstrecord and Lastrecord icon

---

browser/src/control/Control.Notebookbar.js

Change-Id: Ieeed3599ffa51450a5bca4157144dc225df2f470
* Resolves: # 

fix typo on accessing map and uiManager

---

browser/src/map/handler/Map.Welcome.js

the servers are down.
Change-Id: Ie06a833af3be1063690c1a854bcbaa0b30fe6e08

browser: ensure no welcome dialog is shown if

---

Makefile.am
loleaflet/js/global.js
test/Makefile.am
wsd/AdminModel.cpp
wsd/Exceptions.cpp
wsd/Exceptions.hpp
wsd/metrics.txt

Count and report on various internal exceptions.

Count and report on various internal exceptions.

---

browser/css/notebookbar.css
browser/src/control/Control.NotebookbarCalc.js
browser/src/control/Control.NotebookbarDraw.js
browser/src/control/Control.NotebookbarImpress.js
browser/src/control/Control.NotebookbarWriter.js

First Group app specific commands
Second Group Zoom commands
Third Group visibility toggle
Change-Id: I822d1ea8ef3460bea9869235b039749dad028c17

NB View Tab group commands according to LibO

---

kit/ChildSession.cpp
kit/KitHelper.hpp
loleaflet/src/control/Control.PartsPreview.js
loleaflet/src/control/Parts.js
loleaflet/src/core/Socket.js
loleaflet/src/layer/tile/ImpressTileLayer.js
loleaflet/src/map/handler/Map.StateChanges.js

after switching to master view previews would remain unchanged
this patch will invalidate tiles for all the previews
Change-Id: Ie7320d625bd95fe80fc76a459b576d6148b39276

fixed master slide previews not being updated

---

browser/src/layer/tile/CanvasTileLayer.js
browser/src/layer/vector/Path.Transform.js
browser/src/layer/vector/SVGGroup.js

- update preview when new arrives

Image operations fixes

---

.github/ISSUE_TEMPLATE/easy-project-template.md

So it's easy to create ideas for GSoC projects
Change-Id: I465f7b8876a4f43262fae52cf88ceacd89248517

GitHub: Add Easy Project Template

---

loleaflet/src/control/Control.Menubar.js

Change-Id: I9e88d95d97b0991d11385f451334f3de891fcf7f

co-6-4: browser: Add Status bar toggle to View menu in Calc

---

browser/css/jssidebar.css

Change-Id: I6df2656c215d85fe31907fa73e063b45ef8522f5
fix min/max width settings from https://github.com/CollaboraOnline/online/commit/74811df14ae89c73943187eb98f783ca967bb315

Sidebar fix Style and Character dropdown dialog width

---

browser/html/cool.html.m4

Change-Id: I6acbba5a6ebe930935a5425a3f5c52ed99992f91
* Resolves: # 

Set formula bar length.

---

cypress_test/integration_tests/common/calc_helper.js
cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
cypress_test/integration_tests/desktop/impress/image_operation_spec.js
cypress_test/integration_tests/mobile/calc/row_column_operation_spec.js

Change-Id: Ib3a869cd65c80a6dffa2992284cbf46aa3fc30bf

cypress: removed explicit wait from row_column_operation_spec.js tests

---

browser/npm-shrinkwrap.json.in

Change-Id: I39630d59f432ddd0712063ded0629ab0f4953839

Fixed broken freeBSD CI

---

.gitignore
coolwsd.xml.in
test/Makefile.am
test/UnitWOPIFailUpload.cpp
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

- gitingore: .clangd and .cache
- wsd: count save and upload failures
- wsd: limit store failure when unloading

Limit Failure to Store

---

cypress_test/plugins/whitelists.js

Change-Id: Iae5ea1f891a149e49aea0cdea3fcd25317877c06
* Resolves: # 

cypress: temporarily disable few NB tests

---

browser/css/jssidebar.css

move #table-indentfieldbox for better alignment
Change-Id: I5238c6efda7d58d8eb7612eb91329ac9b45d11db

Sidebar alignment fixes

---

browser/src/control/Control.Notebookbar.js
browser/src/control/Control.UIManager.js

Change-Id: I8e59003fef433e6692f02e144223c4e0ee833330
* Resolves: # 

notebookbar: fix toggle ruler/statusbar states on change

---

cypress_test/integration_tests/common/desktop_helper.js
cypress_test/integration_tests/common/impress_helper.js
cypress_test/integration_tests/common/mobile_helper.js
cypress_test/integration_tests/desktop/calc/annotation_spec.js
cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
cypress_test/integration_tests/desktop/impress/annotation_spec.js
cypress_test/integration_tests/desktop/writer/annotation_spec.js
cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
cypress_test/plugins/selectorList.js
cypress_test/plugins/whitelists.js
loleaflet/src/control/Control.TopToolbar.js
wsd/DocumentBroker.cpp

Cherry picked missing patches

---

browser/css/notebookbar.css

simplify the css file
use for select/hover tab the same color
than for select/hover commands
Change-Id: I665eff84efb413dcc04ae288189f78528c4b4cce

Notebookbar tab container

---

browser/css/toolbar.css

w2ui-toolbar w2ui-button use the correct colors
Change-Id: If4cf49bc4d6ba8099978de672fcfe5e8a8891fdb

Toolbar checked and hover buttons

---

browser/js/global.js
browser/src/layer/tile/CanvasTileLayer.js

Change-Id: Ica0765242b82a2da86722da0b40b6ecdf401d383
* Resolves: # 

Allow protocol logging to be enabled from debug overlay.

---

browser/css/color-palette.css
browser/css/welcome.css

the welcome dialog use the var's from the color-scheme.
no visual change
Change-Id: Ie3f0166f27d471dd21465bb76d680f63a592ee6b

Welcome dialog .css file use var's

---

browser/css/toolbar-mobile.css

Change-Id: I5f8f5a18e8827960088d24eecdb5f91b88d0dd5c

toolbar-mobile use color-palette var's

---

browser/css/infobar.css
browser/css/override-vex.css

use color-scheme vars
Change-Id: Ia4ed91f428673e66799e6cbd378e8fe5807e7173

About Dialog update

---

browser/css/jsdialogs.css
browser/css/jssidebar.css

Change-Id: Ie644be283add981ba5bc4f7d159479cb1187ccf2

Sidebar separator-horizontal use --color-border-lighter and 1px height

---

browser/css/toolbar.css

Change-Id: Id18af50448bf4c4019baf6f9f4d6d75d69179f3a

toolbar selected text use --color-text-dark

---

browser/css/leaflet.css

Change-Id: Iccaa63a050721331c1b10553762424b1166bff25

Ruler use var color from color-scheme

---

android/lib/src/main/java/org/libreoffice/androidlib/SlideShowActivity.java

Change-Id: I473d9d8fcd658ba8259feba9e393059b3757ef36
* Resolves: # 

android: fix slideshow displays black background

---

browser/src/control/Control.NotebookbarBuilder.js

Change-Id: I6d5dce4c3cd31baa9e103b5e09559c4994fe6f86

NB: Hamburger menu: Remove items present already within tabs

---

loleaflet/js/global.js

Change-Id: Id4aa67e98779dd0d5c92172425baa753fcaca27c
* Resolves: # 

browser: add missing error method for logging

---

tools/Replay.hpp

Change-Id: I48e1540795f0992833d4c4365d4a9d0da7a48442
* Resolves: # 

Count bandwidth use during stress testing.

---

browser/src/control/Control.NotebookbarBuilder.js
browser/src/control/Control.NotebookbarCalc.js
browser/src/control/Control.NotebookbarDraw.js
browser/src/control/Control.NotebookbarImpress.js
browser/src/control/Control.NotebookbarWriter.js

Change-Id: I82f5d8275571292ffa4568954e97f376cae61b04
Follow up to #4200

Notebookbar add Save command to file tab

---

browser/src/map/handler/Map.Infobar.js
browser/src/map/handler/Map.Welcome.js

This blocks adding controller for Welcome dialog (remote one) and Infobar.

Disable remote welcome dialog and infobar

---

browser/css/menubar.css
browser/css/override-smartmenus.css

Change-Id: I82565cd811bc4b0b71c39670a88e0fe21fa91d70

Menubar use var for background-color at dropdown menues from the menubar

---

browser/css/toolbar.css

Change-Id: I081abd676f97da26a928a87d6997179acea1c42d

CSS Var: Toolbar widget dropdown arrow use text color

---

browser/css/toolbar.css

added variables for dropdown container
Change-Id: Ifa350d6c0a65f31135d39da49f583c5c589614d8

CSS Var: dropdown menu use var colors

---

README.md

Change-Id: Iacaff7a6c78eccf556224b7fa14ca5b0e7adabaf

CI: Add build status badges

---

test/traces/calc-ramblings.txt
test/traces/calc-sheet-edit.txt
test/traces/impress-shape-edit.txt
test/traces/impress-slide-edit.txt
test/traces/mobile-calc-sheet-edit.txt
test/traces/mobile-impress-slide-edit.txt
test/traces/mobile-writer-doc-edit.txt
test/traces/writer-document-edit.txt
test/traces/writer-hello-shape.txt
test/traces/writer-mash-text-table.txt
test/traces/writer-quick.txt
tools/Replay.hpp

Change-Id: I15c04eb9eef02f3f6002c35dc5701b7dbe9a1398
* Resolves: # 

Detect trace replay errors & exit and cleanup traces.

---

browser/css/jsdialogs.css
browser/css/jssidebar.css

Indent vertical widget alignment
Change-Id: I9737bbbd8f96936b0af73faf50e9cc007a2ca34f
* Resolves: #4260

Sidebar Alignment fix #4260

---

browser/css/notebookbar.css

Change-Id: Ie98cbdcb643a8cbbd95e3ffa3f9512849dd83be1

NB Shortcuts-bar vertical center align

---

browser/css/jsdialogs.css

Fix padding
Fix text-height
Fix colors for select and hover
Change-Id: I42a991dd6c00a222151d7bae16da7682743cdc76

CSS Var: macro dialog update

---

browser/css/cool.css
browser/css/jssidebar.css

CSS Var: updates

---

browser/css/cool.css

search-input use --color-background-lighter color
Change-Id: I4dfaabb9771ac4a128e5bab0ffeed5d99c9b0087

CSS Var: Search field background

---

browser/src/map/handler/Map.Feedback.js

Change-Id: I9a62bfe530f985d3f49e3173cce6cfe3fa55b062

feedback: add the lokit hash parameter

---

browser/css/jsdialogs.css
browser/css/jssidebar.css

Change-Id: Ia6efac56feb869af0dd40619d2983585a64ca4f7

Sidebar add var's to sidebar widgets

---

browser/css/jssidebar.css

Change-Id: Iec419c0c6721077d1207b54fd0133e37bac2be88

Sidebar Edit Chart button use default height, colors and size

---

cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

changed defaultStartPoint
Change-Id: I5a6947d233b7fb95052722a921becbd162c6a6ae

cypress: fix: mobile/writer/shape_properties_spec.js failure

---

browser/css/toolbar.css

Inserttable-grid var update
Change-Id: Idd2ac12161d79b7cf6b440477ac692537d6e7d4e

Use Var Colors

---

browser/css/btns.css
browser/css/color-palette.css
browser/css/cool.css
browser/css/jsdialogs.css
browser/css/jssidebar.css
browser/css/leaflet.css
browser/css/menubar.css
browser/css/mobilewizard.css
browser/css/notebookbar.css
browser/css/spreadsheet.css
browser/css/toolbar.css

the following vars were added
- header-height
- default-font-size
- color-box-shadow
value names come from
- https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss
Change-Id: I05a081d5b27f6e9d8102002805c9194062f8ea0f

Color-Palette Vars added

---

.gitignore
common/JailUtil.cpp
common/RenderTiles.hpp
common/Session.cpp
kit/ForKit.cpp
kit/Kit.cpp
net/Socket.cpp
net/Socket.hpp
net/SslSocket.hpp
test/UnitWOPIFailUpload.cpp
test/UnitWOPILock.cpp
test/WOPIUploadConflictCommon.hpp
test/WopiTestServer.hpp
test/lokassert.hpp
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp
wsd/FileServer.cpp
wsd/Storage.cpp
wsd/TileCache.cpp

- wsd: test: extend the timeout of the conflict tests
- wsd: dump all the state managers in DocBroker
- wsd: reduce debug and generally redundant logs
- wsd: const correctness and minor cleanups
- gitignore: ignore fuzzer, gdb.txt and remove some duplicates
- wsd: test: minor cleanup in UnitWOPILock
- wsd: test: minor cleanup COOL test socket helpers
- wsd: exit forkit when WSD dies
- wsd: exit the kit when we fail to connect to wsd

Test, logging, and misc improvements 

---

browser/css/toolbar.css

classic toolbar toolbar background didn't need a color
Change-Id: Iddb4058ff56535222c3794746f07d383d8b4c526

Use CSS var's at toolbar.css

---

browser/css/menubar.css

Change-Id: Ib5f68ff37f871ebfd9e5ce686ac9a9a6f7ac96a5

menubar.css use var colors

---

browser/css/btns.css
browser/css/cool.css
browser/css/infobar.css
browser/css/jsdialogs.css
browser/css/override-vex.css
browser/css/toolbar.css

to dialog, popup widgets
Change-Id: I8f0170b181f88ed8e4b3f1b9a4303a9f21ab0083

Add Color Scheme Var's

---

browser/css/jsdialogs.css
browser/css/jssidebar.css

Change-Id: I6213fd2c35791bc368d802159a37cc0e89ec4bf3

Sidebar Widget right alignment with text-align

---

common/CommandControl.cpp
common/CommandControl.hpp
common/Util.hpp
configure.ac
coolwsd.xml.in
wsd/COOLWSD.cpp
wsd/Storage.cpp
wsd/Storage.hpp

Change-Id: Id0e2b4b524a80de88b2b3559dd18c4a95b8163fb
* Resolves: # 

wsd: introduce remote config

---

browser/css/cool.css
browser/css/jsdialogs.css
browser/css/toolbar.css
browser/css/welcome.css

Dialogue box-shadow setting:
-webkit-box-shadow: 0 0 3px var(--color-border);
box-shadow: 0 0 3px var(--color-box-shadow);
Change-Id: I4ce226b317d3c30dcf508e4272eba690b007ff80

Add css vars and harmonize settings for dialogues

---

browser/css/btns.css
browser/css/infobar.css
browser/css/jsdialogs.css
browser/css/jssidebar.css
browser/css/mobilewizard.css
browser/css/notebookbar.css
browser/css/override-vex.css
browser/css/partsPreviewControl.css
browser/css/searchControl.css
browser/css/toolbar.css

Change-Id: I0388e2b38cc13920eb5c2de74ad34fde56f4d417

css vars use header-font-size and default-font-size

---

browser/css/color-palette.css

Change-Id: Ic4588709f02ae25db8823db40ed50632b4165b45

Color Scheme add Descriptions to var's

---

browser/src/layer/tile/CommentListSection.ts

Change-Id: I281fcb3a613166bc9be4b3bc09dbe0b28fdca6bc
* Resolves: # 

fix copy annotations on shared-view doc causes uncaught exception

---

browser/css/jsdialogs.css
browser/src/control/Control.JSDialog.js
browser/src/control/Control.JSDialogBuilder.js
browser/src/control/Control.MobileWizardBuilder.js

- update pos on invalidate
- implement scrollwindow

jsdialog: Accessibility check dialog fixes

---

browser/css/notebookbar.css

Change-Id: I8468f6deb8f4e02f38d3cfad3b0d6a72b247ffdc

NB: Increase text contrast for selected tab label

---

browser/css/jsdialogs.css

Change-Id: I1aabb241ca986bd8e8f81405819aa270b45dac6d

AccessibilityCheckBox: Fix paragraph style

---

loleaflet/src/control/Control.StatusBar.js

Change-Id: Iff349ec26139ce4f561ce2e38a2492bda1e56780
* Resolves: # 

draw: added more details in the draw status bar

---

android/lib/build.gradle.in

Change-Id: Ic9788141c398600cc2fd6d69e49d557019d8cbd6
* Resolves: # 

android: fix typescript files dont make it to apk

---

browser/src/control/Control.ContextMenu.js
browser/src/unocommands.js

the following commands will popup an dialog:
- CompressGraphic
- GraphicDialog
- InsertCaptionDialog
- FontDialog
- FontDialogForParagraph
- TableDialog
Change-Id: I824e883f2ea8979edf7a752e267acf76c0e29d4b

Contextmenu add Dialog commands

---

browser/css/jssidebar.css

Paragraph Section
- add justify-content: space-between;
- remove hardcoded position: relative
- remote hardcoded margin-top
perfect horizontal and vertical alignment
for spacing and indent
Change-Id: If6182bf5a4d46f9936dc260707e9ae12988fc8da
* Resolves: #4305

Sidebar css Fixes

---

browser/src/layer/vector/Path.Transform.js

in one document I have it has "21" instead of "16"

Check if needed anchor exist before use

---

loleaflet/src/control/Control.AutofilterDropdown.js

Autofilter position fix for co-6-4

---

browser/css/color-palette.css
browser/css/cool.css
browser/css/device-mobile.css
browser/css/jsdialogs.css
browser/css/mobilewizard.css
browser/css/toolbar.css

primary colors use color from colibre icon theme
Change-Id: Iaf8eddbe4b66aebd00c7c0d1598bad8cdc4db988

Mobile color var update

---

cypress_test/integration_tests/desktop/impress/scrolling_spec.js
cypress_test/integration_tests/mobile/writer/shape_properties_spec.js

Change-Id: Ib576e9f4d90ec53dc21c2955d61e8ee85bd3e2ca
* Resolves: #4350

cypress:fix: writer/shape_properties_spec.js failing

---

browser/css/device-mobile.css
browser/css/iframedialog.css
browser/css/jsdialogs.css
browser/css/jssidebar.css
browser/css/leaflet.css
browser/css/menubar.css
browser/css/mobilewizard.css
browser/css/override-vex.css

input field use var colors
Change-Id: I747b3dcde814a9d473739341736946ed2e3c539a

Mobile use var colors

---

browser/css/color-palette.css
browser/css/device-mobile.css
browser/css/device-tablet.css
browser/css/jsdialogs.css
browser/css/leaflet.css
browser/css/mobilewizard.css
browser/css/notebookbar.css
browser/css/override-vex.css
browser/src/control/Control.JSDialogBuilder.js

the following vars are not needed anymore
--gray-light-txt--color
--gray-light-bg-color
--gray-color
Change-Id: Ia23954e50629b60d3df50ea778c57de4e26bea88

cleanup css vars

---

browser/css/leaflet.css

leaflet-popup dialog use var colors
Change-Id: Ibc8a0a2ca2ff63dc0bc66613a202959288a331d1

Leaflet use var colors

---

cypress_test/integration_tests/desktop/writer/undo_redo_spec.js

Change-Id: I03d1f0ded1c177838bd493f11778ee1d4d8c542e
* Resolves: #4374 cypress failures

cypress:fix: writer/undo_redo_spec.js

---

browser/src/layer/tile/CanvasTileLayer.js
browser/src/map/handler/Map.StateChanges.js

Change-Id: I680eb4bb330da9235f40db6045838249199dd155
* Resolves: # 

fix switching to masterpage does not update the page

---

browser/po/templates/welcome.pot
browser/src/control/IFrameDialog.js
browser/src/map/handler/Map.Welcome.js
browser/welcome/welcome.html
browser/welcome/welcome.js
wsd/FileServer.cpp

- welcome: add function to post a message
- welcome: add function to extract translatable strings
- welcome: add function to translate strings
- welcome: execute action to translate strings
- welcome: add missing strings

welcome translate strings

---

browser/welcome/welcome.html

Change-Id: Ibac85925f9382d6ce426eac10cc749a52518c7b3
* Resolves: # 

Generalize welcome.html text.

---

browser/src/map/handler/Map.StateChanges.js

Change-Id: I3b01757926a19290a7819536931e33498da6b614
* Resolves: # 

presentation: fix masterview and normal view tiles can be mixed up

---

browser/src/layer/tile/CanvasTileLayer.js

Change-Id: I56a263711bd034ff1a56357eb5efe713fe076db3
* Resolves: # 

fix empty selection handles appear on calc

---

browser/css/cool.css
browser/css/device-mobile.css
browser/css/editor.css
browser/css/iframedialog.css
browser/css/impress-mobile.css
browser/css/toolbar.css

mobile use vars

---

browser/css/btns.css
browser/css/device-tablet.css
browser/css/jssidebar.css
browser/css/leaflet.css
browser/css/notebookbar.css
browser/css/override-vex.css
browser/css/spreadsheet.css

stylesheet.css use var colors
Change-Id: If6b49591e6c61361464898d0d1dd6199ea33a4f9

color-scheme var update css files

---

browser/css/notebookbar.css

Change-Id: I583502733a9fd7053a67b8cd3445896fb56c74a8

Savemodified placement of the box-shadow was misaligned

---

browser/css/cool.css
browser/css/device-mobile.css
browser/css/jsdialogs.css
browser/css/menubar.css
browser/css/mobilewizard.css
browser/css/notebookbar.css
browser/css/override-vex.css
browser/css/toolbar.css

replace white color with var colors
autofilter container use var colors

var colors

---

browser/welcome/welcome.html
browser/welcome/welcome.js

Change-Id: I9b66f7b301487cf345c9a136943a6148827a2d49
* Resolves: # 

Enable translations for paragraphs containing links.

---

common/Log.cpp
common/Log.hpp
common/SigUtil.cpp

Change-Id: I8e975886800ce02cb12e840ad36a818145c1112a
* Resolves: # 

signal handling: print code, and relevant address too.

---

loleaflet/src/control/Ruler.js
loleaflet/src/core/Socket.js

- browser: initialize layout hidden for ruler control
- browser: fix 'rulerupdate:' missing message

pr/distro/collabora/co 6 4/0D

---

kit/Kit.cpp
test/UnitPasswordProtected.cpp

* Resolves: # 
kit: can't open password-protected files [co64]

kit: can't open password-protected files [co64]

---

cypress_test/integration_tests/common/desktop_helper.js
cypress_test/integration_tests/desktop/impress/open_different_file_types_spec.js
cypress_test/integration_tests/desktop/writer/open_different_file_types_spec.js
discovery.xml

Change-Id: I67c57be272f3b4818f9bcd3a9b3b6df61846cbdb
* Resolves: # 

Editing of document templates does not work well currently

---

wsd/Storage.cpp

Change-Id: I3c5c7da5d1cad6fe7e6703d0941f250e91a5f552
* Resolves: # 

Disable export of template files

---

common/FileUtil.cpp
test/Makefile.am
test/UnitStorage.cpp
test/countcoolkits.hpp
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp
wsd/Storage.cpp

- wsd: wait longer when restarting forkit
- wsd: stop loading when low on disk space
- wsd: gracefully close the document when disconnected from Kit
- wsd: last modified timestamp of the upload file is not now

Fixes to save/upload corner-cases

---

browser/css/device-mobile.css

Make sure it occupies the whole view
Change-Id: If492fdca19aac024a749b7273c515047be208d7d

Fix Welcome dialog for mobile when served from outside

---

browser/src/map/handler/Map.Infobar.js

Change-Id: Iedf6aff2f026f4530bfed06cd4bf5e7acae15a50

infobar: show message every five days

---

browser/css/jssidebar.css

Change-Id: If77f343e66cea627a7eb2afadd2905df8b332c82

Calc Sidebar Alignemten section fix leftindent alignment

---

kit/Kit.cpp
test/UnitPasswordProtected.cpp

* Resolves: # 
Followup fixes for PR#4388

Followup fixes for PR#4388 

---

browser/css/color-palette.css
browser/css/cool.css
browser/css/device-mobile.css
browser/css/mobilewizard.css

Change-Id: I03693f67c69d108ef3dcbf5cc9cd0127bd37b5a3
* Resolves: # 

fix comment reply is too wide when the content is big enough

---

README.md

Change-Id: I242e83feb8073fea040a2a61a41801e9962d7520

Update branch status

---

coolwsd.xml.in
wsd/COOLWSD.cpp
wsd/Storage.cpp
wsd/Storage.hpp

- wsd: parse and check syntax alias host
- wsd: use get/set Authority to extract host + port
* Resolves: # 

alias host reviews

---

browser/src/control/Toolbar.js
cypress_test/integration_tests/mobile/writer/insert_formatting_mark_spec.js
cypress_test/integration_tests/mobile/writer/table_properties_spec.js

- use .unoXXX class instead of id
- check only if height was changed on Optimal Row Height command

co-22.05: mobile writer/table_properties_spec.js

---

browser/css/cool.css

prefer universal value as opposed to WebKit-based and blink only
value
Change-Id: Ie0bff5de254829db6bffcd7a928629a98b1889ac

Fix overflow property for FF

---

browser/src/map/handler/Map.Infobar.js

Change-Id: I4df356663efa91207ef310341b7b08992bcb77de
* Resolves: # 

Add condition for infobar.

---

configure.ac
coolwsd-welcome.xml
coolwsd.xml.in
wsd/COOLWSD.cpp
wsd/FileServer.cpp

Change-Id: Ia99eb5b587a849d32d7d4f392c15f84db2423e95
* Resolves: # 

Re-work welcome configuration.

---

browser/js/global.js

Change-Id: Ie5d2017ed6ce9f38623b42b336c5261be322b025

Escape some parameters for a good measure

---

wsd/COOLWSD.cpp
wsd/COOLWSD.hpp

(Commit message from first commit. Will add more commits.)
Only one of them is needed, and only in COOLWSD.cpp itself.
Change-Id: I03864afdc13e778a2b8ce8205e135d679dddf13d
* Resolves: # 

Various minor cleanups without functionality changes

---

common/CommandControl.cpp
common/Util.hpp

Change-Id: Ia150975467d1df8a9d05c8543bcb5d7369d29099

util: removed duplicate string trimming function

---

common/Util.cpp
common/Util.hpp
coolwsd.xml.in
wsd/Storage.cpp

Change-Id: I2534ea9afa7d3d3bf10f91eeac44f70381acc76a

wsd: added regex support for alias tag

---

net/Socket.hpp

Change-Id: I4305baf828ccb1ae71d3b3b12fa90a7aeb5e0928

wsd: reduce logging noise in socket reads

---

browser/src/core/Socket.js
common/Util.cpp
common/Util.hpp
wsd/Admin.cpp
wsd/ClientSession.cpp

Change-Id: I00d6cb861c3050d5b4f80b0cb41e70012d0fe610
* Resolves: # 

Show (E) for experimental mode in help->about if present.

---

browser/html/debug.html

Change-Id: I3e618dbb9aa6363974e0759e955dfe73e8787824
* Resolves: # 

Allow debug.html to be passed a WOPISrc for easier debugging.

---

browser/src/layer/tile/CommentListSection.ts
browser/src/layer/tile/CommentSection.ts

fixes for redline annotations collapsed mode problems

---

ios/Mobile/Info.plist.in

Signed-off-by: Tor Lillqvist <tml@iki.fi>
Change-Id: I7045084422c5247ce6fd70dba76e891ca7e4c1d5
* Resolves: # 

Bump version to match configure.ac

---

browser/css/device-mobile.css
browser/css/infobar.css
browser/src/control/IFrameDialog.js

Change-Id: I949b3bc6d72541cba18867847cd43f0c6e57a32f

fixed edit button not appearing in ipads

---

browser/src/control/Control.JSDialog.js
browser/src/control/Control.Menubar.js
browser/src/control/Control.NotebookbarBuilder.js
browser/src/map/Clipboard.js
browser/src/map/handler/Map.Keyboard.js
browser/src/unocommands.js

It makes paste special feature more visible to the users
Also move paste special popup code to the clipboard.js so it is easiet to share the code.
What to do with notebookbar mode: to be discussed...

clipboard: introduce paste special menu entries

---

common/Session.cpp

Change-Id: Iba4f96c75d69e52044f6460c4e26d0ab1d187d3c

l10n: if english variant is not specified then choose US as default

---

browser/css/device-mobile.css
browser/src/control/IFrameDialog.js

* Resolves: # 
also reverted 3c1185aca331222fefcc7a55c8d30064e2ef0a58
it breaks the visibilty of the dialog

welcome dialog: give focus to welcome dialog onshow

---

common/Unit.hpp
test/Makefile.am
test/UnitWOPICrashModified.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

- wsd: remove unsed function in DocumentBroker
- wsd: remove dup entry in dumpState
- wsd: unload when no Kit and nothing to upload

Gracefully unload when there is no Kit and nothing to upload

---

browser/src/map/handler/Map.Keyboard.js

In Impress, launch slideshow.
Change-Id: Ib4b72f2f1278eb30b0177da4e3c3ef9bfd6d11a8

browser: Disable browser reload on F5

---

browser/src/map/handler/Map.Welcome.js

Change-Id: Ia0f945f8f1e667541b7d8d7b1613538f65501fef
* Resolves: # 

Correct iFrame links.

---

browser/src/control/Control.Menubar.js

we dont have welcome dialog for mobile
Change-Id: I7b0196418e5c3b00f87630de42b131b3deb3ae15
* Resolves: # 

mobile: hide send feedback button

---

common/Message.hpp
common/Util.hpp
kit/ChildSession.cpp
net/WebSocketHandler.hpp
test/WhiteBoxTests.cpp
wsd/DocumentBroker.cpp

Change-Id: I84e83c63351cd0aac0923bf7c833b14c1be2c051
* Resolves: # 

Validate as utf-8 all Websocket text messages in debug mode.

---

loleaflet/src/control/Control.ContextMenu.js
loleaflet/src/control/Control.Menubar.js
loleaflet/src/control/Control.NotebookbarBuilder.js
loleaflet/src/map/Clipboard.js
loleaflet/src/map/handler/Map.Keyboard.js
loleaflet/src/unocommands.js

added Paste Special to menubar, notebookbar and context menu

paste special shortcuts in manus and context 6.4

---

coolwsd.xml.in
wsd/HostUtil.cpp
wsd/HostUtil.hpp
wsd/Storage.cpp

Change-Id: Iacca38868f06a417cbb99984e2dac1eef727df6e

wsd: removed host list from coolwsd.xml

---

wsd/Storage.cpp

Change-Id: I2bdc7b21d11afa70214e8cb498b7e2dec77ef655

wsd: fix: log messages to coolwsd.log of firsthost and denied hosts

---

browser/css/jssidebar.css
browser/src/control/Control.JSDialogBuilder.js
browser/src/control/Control.Toolbar.js
browser/src/map/handler/Map.StateChanges.js

Change-Id: Ib5c2ff5629a8334d9c2866642e1d6d1c794aff82
* Resolves: # 

Fix clone formatting button does not have state on notebookbar

---

browser/src/map/handler/Map.Infobar.js

the localstorage save the number as string
Change-Id: I5f1006c5dc434d7b145a5f4964b3f77f9df96f4e
* Resolves: # 

infobar: fix number conversion

---

browser/src/map/handler/Map.Feedback.js

the null value is converted to 0
Change-Id: Ie8ca2a41ab35252f3bb2187831ae9abd500777b6
* Resolves: # 

fix Number conversion

---

loleaflet/src/control/Control.MobileWizard.js
loleaflet/src/layer/tile/CanvasTileLayer.js
loleaflet/src/layer/tile/TileLayer.js
loleaflet/src/map/Map.js

endless keyboard android backport

---

browser/src/layer/vector/CDarkOverlay.ts

* Use unix line endings.
* Use tabs instead of spaces to indent.
* Remove eslint-disable flag.
Change-Id: Ic7fe77097c0e1b652636e5771fd4835d547ffa90
* Resolves: # 

enable eslint for CDarkOverlay.ts

---

browser/welcome/welcome.css
browser/welcome/welcome.html
browser/welcome/welcome.js

Change-Id: Ifdf373c2c0b5a0962610d5fcb35f5845603a7a03

Fix fallback welcome dialog on phone + other backports from online welcome dialog

---

README.md

Change-Id: I45922584e6ceb3ccf8067a8875368c9c1255a8a3

Communication channels: Add more information

---

browser/Makefile.am
browser/html/cool.html.m4

Change-Id: Ib525515f27640114f5d8bc83314b63f006893d37

jsdialog: added button in about dialog to open WidgetTestDialog

---

browser/src/layer/tile/CommentListSection.ts
cypress_test/integration_tests/desktop/writer/annotation_spec.js

annotation scroll problems

---

browser/css/notebookbar.css

Change-Id: Idc294d215d7191f28ed6e4090ab5734d44e6bfe7

Notebookbar dropdown arrow is visible at hover

---

browser/css/device-mobile.css
browser/src/layer/tile/CanvasTileLayer.js

feedbackdialog keyboard problems

---

.gitpod.yml

Change-Id: I8c60a39588503011b526419c358d3b93f6f237ce

GitPod: Update core assets url to 22.05

---

.gitignore
Makefile.am
configure.ac
kit/ForKit.cpp
kit/Kit.cpp
test/helpers.hpp
wsd/COOLWSD.cpp
wsd/COOLWSD.hpp

- wsd: make: build the fuzzer binaries only configured with fuzzing
- configure: choose the correct sanitizer library when fuzzing
- wsd: kill coolwsd_fuzzer

Build fuzzer binaries on demand and improve configure

---

cypress_test/integration_tests/mobile/writer/insert_formatting_mark_spec.js

Change-Id: Ia21c27e80507d7be4b44935e0a7dc225ad0f7776

Fix cypress test after InsertZWNBSP->InsertWJ

---

configure.ac
coolkitconfig.xcu.in

Change-Id: If3dc1dae35250c54d62e69396aea7df51873d4cb

We do not use tunneled sidebar any more

---

browser/src/map/handler/Map.Keyboard.js

Change-Id: Ib0f008d25ed9b508a3fbc002816b4729b5743314
* Resolves: #4109

Fix 'Insert Comment' invoked by keyboard shortcut (fixes #4109)

---

browser/src/control/Control.NotebookbarBuilder.js

regression from:
commit e8d759f18a8da62df867148cdefbc3e3d82cb1ef
jsdialog: postprocess toolitems
fixes for example About dialog

notebookbar: fix help items

---

browser/src/control/Control.JSDialogBuilder.js

fixes selection in fontwork dialog - regression from last jsdialog updates

jsdialog: fontwork dialog fix

---

browser/css/leaflet.css

- Revert "Fix leaflet-control alignment"
- Fix leaflet-control alignment

private/pedro/fix close btn on leaflet popup eg repairDoc part2

---

browser/src/control/Control.Menubar.js
browser/src/control/Control.TopToolbar.js
browser/src/control/Control.UIManager.js
browser/src/core/Socket.js

This also makes us sure we are in sync due to
single point of knowledge about UI Mode

Remember last UI mode (21.11)

---

browser/src/control/Control.Menubar.js
browser/src/control/Control.TopToolbar.js
browser/src/control/Control.UIManager.js
browser/src/core/Socket.js

This also makes us sure we are in sync due to
single point of knowledge about UI Mode

Remember last UI mode

---

browser/src/control/Control.NotebookbarDraw.js
browser/src/control/Control.StatusBar.js

Change-Id: I8831f0a1edcbbe8e8ea08ad691f86c7a422a89aa

draw: make sure page settings do not use term "slide"

---

browser/src/control/Control.Menubar.js
browser/src/control/Control.UIManager.js
browser/src/core/Socket.js

previously without data in localstorage it started with
compact mode always

notebookbar: fix ui mode switch

---

wsd/COOLWSD.cpp

Change-Id: I62b53bb4ff16eac3e122f9b6d702c69d2355595d
* Resolves: # 

Restart ForKit when a downloaded font has been updated or removed

---

browser/test/bootstrap.js
browser/test/load.js
wsd/AdminModel.cpp
wsd/COOLWSD.cpp
wsd/COOLWSD.hpp

- browser: test: add process env NODE_PATH
- browser: test: replace GROUP_DOWNLOAD_AS variable
- browser: test: fix missing 'DOCUMENT_SIGNING_URL'
- browser: test: fix stdio pipes
- wsd: add parameter --signal
- browser:test: add function serverReady
- browser:test: exit process if uncaugth signal
- browser:test: fix exception http or https protocol
- browser:test: ensure to write the stats to stderr
* Resolves: # 

browser: test: perf-test fixes

---

browser/src/control/Control.NotebookbarBuilder.js
browser/src/control/Control.UIManager.js

backports 21.11: errors in logs

---

browser/src/control/Control.FormulaBarJSDialog.js
browser/src/control/Toolbar.js

- also hide autosum button - it was hidden before conversion

formulabar: fix focus also on mobile

---

browser/src/map/handler/Map.Welcome.js

- use only built-in welcome dialog
- make sure it works with proxies

welcome dialog: only built-in (21.11)

---

browser/src/control/Control.Menubar.js
browser/src/map/handler/Map.Feedback.js

- prevent from multiple onDocLoaded calls
- use snackbar to ask user first before showing main dialog

feedback: fix in wopi case and ask before

---

browser/src/control/Control.JSDialog.js

Change-Id: I2eb5f22bd9d0f02e605179e4246fcaa89d3ade32
* Resolves: # 

increase the dialogue timeout to 10 secs.

---

browser/src/map/handler/Map.Feedback.js

Change-Id: Ia63a0098b65540462dce32b54cb4910b388f9065
* Resolves: # 

fix: isVisible is not a function error.

---

browser/css/cool.css

border on left and right so it work also for RTL languages
Change-Id: Ic973cfee4c8fd563008477ab38a9e4e3e69c8300

Sidebar RTL fixes

---

cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js

Change-Id: I53e463f91e6ef7b295bbd9e04c4c40735cdd8ed9

cypress: fix: getting stuck in CI

---

browser/src/control/Control.Menubar.js

When user click the menu options.
Change-Id: Ia53126b5c2972149839de501214d0a1cb2b5fc6c

browser: fix show feedback dialog

---

cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js

Identified the faulty test, on heavy load the test gets stuck on waitUntil command
skipped the test for now
Change-Id: Ia4b7ca081098e7e5b6f15135304131521629e524

fix:cypress: abort without error in CI

---

common/Log.hpp
common/SigUtil.cpp
common/Unit.cpp
common/Unit.hpp
kit/Kit.cpp
test/UnitConvert.cpp
test/UnitEachView.cpp
test/UnitPrefork.cpp
test/UnitTileCache.cpp
test/UnitTimeout.cpp
test/UnitUNOCommand.cpp
test/WopiTestServer.hpp
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp
wsd/FileServer.cpp

- wsd: test: always set the test name
- wsd: test: correctly stop SocketPoll in UnitTimeout
- wsd: cosmetics
- wsd: forced exit after cleaning up jails
- wsd: correctly set termination and shutdown flag

Misc Improvements and Cosmetics

---

test/UnitWOPIFailUpload.cpp
test/WOPIUploadConflictCommon.hpp
wsd/DocumentBroker.cpp
wsd/Storage.hpp

Change-Id: If5a9601d9baa10dcdab38c57bfba82a45d8e5024

wsd: detect lost upload on exit and dumpState once only

---

browser/css/toolbar.css

Change-Id: I3b77ba1e99dee24e74f9f839de5590d0a0def939

.w2ui-button use var color for :hover

---

browser/src/core/Socket.js

Change-Id: Icfc95fb72bee6696dffbb194efe95aa5f9716a72

browser: don't show conflict dialog to read-only users

---

browser/html/cool.html.m4
browser/src/control/IFrameDialog.js
browser/src/layer/tile/CanvasTileLayer.js
browser/src/map/handler/Map.Infobar.js
coolwsd.xml.in
wsd/COOLWSD.cpp
wsd/COOLWSD.hpp
wsd/ClientSession.cpp
wsd/FileServer.cpp

- infobar: remove unused functions
- infobar: show a snackbar message
- infobar: clean up unused code
- infobar: fire 'infobar' message
- wsd: infobar: add config value "fetch_update_check"
- wsd: infobar: fetch and save the latest version data
- wsd: infobar: send latest version to the client side
- wsd: infobar: clean up unused code
* Resolves: # 

issue 4730 update: check for new versions

---

.cirrus.yml
.github/workflows/codeql-analysis.yml

Otherwise we fail to find new callbacks, see e.g.
<https://github.com/CollaboraOnline/online/runs/6365091834?check_suite_focus=true>.
Change-Id: I820823d0307d0a4a5d8c51b944c01b2b9ba6632a

CI: codeql-analysis: work with core co-22.05 assets

---

browser/src/map/handler/Map.WOPI.js

Change-Id: Ifa842f64ed70137f06ebdfc053fa5a3afd2f4185

framed.doc.html: fix: cannot change UI view (master)

---

browser/css/toolbar.css

Change-Id: I0908c446ea5eb02c5fcd82f9fe0e2ac1af491dcb

w2ui-scroll use var colors

---

browser/Makefile.am
browser/src/control/Control.Menubar.js
browser/src/control/Control.NotebookbarWriter.js
browser/src/layer/tile/CanvasSectionProps.js
browser/src/layer/tile/CanvasTileLayer.js
browser/src/layer/tile/ContentControlSection.ts
browser/src/unocommands.js
kit/ChildSession.cpp

added unocommand to enter rich text
created a new section to draw rich text rectangles
handle the callback for content control
Change-Id: If9912b3598729c26014519c4e1c3c65000b973a4

introduce content control in online

---

browser/src/map/handler/Map.WOPI.js

Change-Id: Ifa842f64ed70137f06ebdfc053fa5a3afd2f4185

framed.doc.html: fix: cannot change UI view

---

cypress_test/integration_tests/common/calc_helper.js
cypress_test/integration_tests/mobile/calc/alignment_options_spec.js
cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js
cypress_test/integration_tests/mobile/calc/calc_mobile_helper.js

after the jumbo sheet patch selecting entire row and merging all the cells becomes costly and cypress timeouts
therefore select first 100 cells and test the merging functionality
Change-Id: I8568bbdbabdccc55c2938f886619a1d178ae7d22

cypress: added new function selectCellsInRange

---

cypress_test/integration_tests/mobile/impress/table_operation_spec.js

cannot reproduce the issue locally.Added waitUntilIdle
Change-Id: Ic66faada9543ff4a219cd1f878ac71d874615404

cypress: skipping: mobilie/impress/table_operation_spec.js

---

browser/src/control/Control.ColumnHeader.js
browser/src/control/Control.Header.js
browser/src/control/Control.RowHeader.js
browser/src/layer/tile/CalcTileLayer.js

Change-Id: Ifc5a4a5899e3e4ff26530e9b2f1794824e70f660
* Resolves: # 

Remove unused functions.

---

browser/css/jsdialogs.css
browser/src/control/Control.FormulaBarJSDialog.js

added button to the formulabar for expanding/collapsing input line

formulabar: added expand/collapse button

---

cypress_test/integration_tests/mobile/impress/table_operation_spec.js

cannot reproduce locally temporarily skipping the test
Change-Id: I2007a2dc643306551be859b1bdcf48982fe4a33d

cypress: skipping columns test in impress/table_operation_spec.js

---

browser/css/btns.css

btns use var names that didn't exist
* Resolves: #4781
Change-Id: I13f2acbdd91cf05391da81adc721156d125f3de7

btns var color name fixes

---

browser/src/map/handler/Map.Welcome.js

In order to get the list users and identify if it
is a guest user to not show the welcome dialog.
Change-Id: I439f46dcfd3ea5b307059952f98f49a387158e24
* Resolves: # 

#4729 avoid showing for remote shares

---

browser/src/map/handler/Map.Welcome.js

In order to get the list users and identify if it
is a guest user to not show the welcome dialog.
Change-Id: I439f46dcfd3ea5b307059952f98f49a387158e24
* Resolves: # 

welcome: modify to listen view list changes

---

browser/src/control/Control.JSDialog.js
browser/src/control/Control.JSDialogBuilder.js

jsdialog popups: tab key handling

---

browser/Makefile.am
browser/css/writer.css
browser/src/control/Control.Menubar.js
browser/src/control/Control.NotebookbarWriter.js
browser/src/layer/tile/ContentControlSection.ts
browser/src/unocommands.js
kit/ChildSession.cpp
kit/ChildSession.hpp
wsd/ClientSession.cpp

Change-Id: I178561b081f9c1cb3c7db081fcdab606c6426cc5
* Resolves: # 

browser: contentcontrol: add dropdown type

---

browser/src/layer/tile/CanvasTileLayer.js

Change-Id: Id7a0acaa3aefdcde4a0cf65ccbbf133ac9510a67
* Resolves: # 

testing the cherry-pick bot.

---

browser/css/jsdialogs.css
browser/css/toolbar-mobile.css
browser/css/toolbar.css

Change-Id: I0bee881aafb52d86641243f3e614ffd60427d198

calc formularbar use var colors for input elements for dark mode

---

tools/Replay.hpp
wsd/TileCache.hpp

Change-Id: Ie94add7197672106a2c0684405a1b15c307470e4
* Resolves: # 

stress: account for the size of each message.

---

common/Log.cpp
common/Log.hpp
common/Session.cpp
common/Session.hpp
common/Util.hpp
kit/ChildSession.cpp
kit/Kit.cpp
net/HttpRequest.hpp
net/ServerSocket.hpp
net/Socket.cpp
net/Socket.hpp
net/SslSocket.hpp
wsd/ClientSession.cpp
wsd/ClientSession.hpp

- wsd: make socket FD log prefix implicit and cleanup logs
- wsd: improved socket logging
- wsd: simplify socket read logging
- wsd: better logging of unix socket binding
- wsd: cleanup log initialization

Socket Logs with Context

---

browser/css/cool.css
wsd/COOLWSD.cpp
wsd/COOLWSD.hpp
wsd/FileServer.cpp
wsd/FileServer.hpp

- wsd: add indirect request logo image
- browser: css: add '#lokit-logo' style to fetch logo.png
- wsd: cache logo image
* Resolves: # 

indirect logo

---

tools/Replay.hpp

Count data sent as well as received, re-factor, and measure B/W
usage too.
Change-Id: I5d00f0568c774cc03d2b8e4f730bfe4a8fb5b06f
* Resolves: # 

reply: record more statistics.

---

browser/src/control/Control.JSDialogBuilder.js

Change-Id: I36191d622c70d296f50db8ba4913a2e47dd36f94
* Resolves: # 

Add the missing global definition.

---

browser/src/control/Control.Menubar.js

Change-Id: I50decd1f84dd6e91ba268dabdca2d579e8d229ec

browser: adjusted Field submenu in menu bar

---

browser/src/control/Control.JSDialogBuilder.js

add combobox to list of non-containers and cleanup

jsdialog: combobox is not a container type

---

coolkitconfig.xcu.in
coolwsd.xml.in
wsd/COOLWSD.cpp

Change-Id: Ifc494d5e9f17fc4459556ae809ef3ca12a6b7307
* Resolves: # 
This patch needs https://gerrit.libreoffice.org/c/core/+/135464 to be in for it to work

LanguageTool Grammar checker settings to enable it

---

browser/css/jssidebar.css

patch2:
sidebar: css: calc area, line, shadow, possize panels
context: shape
patch1:
sidebar: css: calc number format and alignment panels
context: default/cell
- removed not needed direct position rules

sidebar: calc panels layout

---

browser/css/jsdialogs.css
browser/src/control/Control.JSDialogBuilder.js
browser/src/control/Control.Menubar.js
browser/src/control/Control.MobileWizard.js
browser/src/control/Control.NotebookbarWriter.js
browser/src/layer/tile/ContentControlSection.ts
browser/src/map/handler/Map.TouchGesture.js
browser/src/unocommands.js
wsd/protocol.txt

add uno command to insert date in form tab
renamed 'Content Control Properties' -> 'Properties'
Change-Id: Ib4a439cd349bb79430d590e0b80c825372c629d3

browser: contentcontrol: add date type

---

wsd/COOLWSD.cpp

Change-Id: Ia8dbc16024e8f9970d45df16550328fa8c196563
* Resolves: # 

wsd: add query parameter product name & version.

---

common/MessageQueue.cpp

Apparently for some subset of messages (presumably on busy queues)
we have been double compressing the same tiles ...
Change-Id: I79aea4f2162caa8a5b5660c13ae2cae855d90755
* Resolves: # 

MessageQueue: don't insert duplicates of tiles into TileCombined.

---

common/Log.hpp
coolwsd.xml.in
wsd/AdminModel.cpp
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp

introduce user stats

---

browser/src/control/Control.JSDialogBuilder.js

Open spreadsheet, click on formulabar, type, press tab -> it should move to the next cell in a row

jsdialog: formulabar: handle tab key

---

configure.ac
net/HttpRequest.hpp
test/.gitignore
test/HttpRequestTests.cpp
test/Makefile.am
test/run_unit_standalone.sh.in

- wsd: test: HttpRequestTests timeout cleanup
- wsd: test: fix heap-use-after-free

Fix heap-use-after-free in HttpRequestTests

---

browser/src/control/Control.JSDialogBuilder.js

This helps to keep id unique and process events correctly.

jsdialog: listbox and scrollwindow are not containers which need additional parent

---

browser/src/control/Control.JSDialogBuilder.js

Keep in sync colors in sidebar and notebookbar when
we change one of them.
Followup for
commit 13ef21aa1ecff764ed7c5b24bee83e25297ca21e
notebookbar: unify color control with core

notebookbar: unify color control in all components

---

wsd/COOLWSD.cpp
wsd/ProxyRequestHandler.hpp

Change-Id: I3d2333e1441b8acb63824affe8e21541afb12511

wsd: proxy: ensure to forward only static files

---

wsd/COOLWSD.cpp

Change-Id: I4508fc3e32f4d13a1a8ae88c3e4b9abc6d724ac4

wsd: proxy: fix length static string

---

browser/js/global.js

Change-Id: I98da25735a3b889824a72c2134c495abd26b3a05
* Resolves: # 

proxy.php: Special case for the remote image

---

browser/css/cool.css

User a darker background for on mouseover items
Change-Id: Ib6dc6d2ed434d21765ab3d6bf3988dc918261281

Context menu: on hover, fix contrast

---

common/JailUtil.cpp
common/JailUtil.hpp
net/HttpRequest.hpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

- wsd: privatize internal JailUtil helpers
- wsd: saving timeout set to 4x loading-time
- wsd: http: do not assert on net::connect returning nullptr

Misc Minor Fixes and Improvements

---

.cirrus.yml

Change-Id: Id3e05d54c2d5b3f1dd4a9794ef4a0c455b72c04c
* Resolves: # 

Attempt to solve freebsd check issue.

---

browser/src/control/Control.LokDialog.js
browser/src/map/Map.js

This is for "0 JS errors" task

Fix TypeError when using formulabar variable in Writer

---

browser/src/control/Control.JSDialogBuilder.js

if there is no more paragraphs: exit the loop

jsdialog: formulabar: fix freeze when server sent huge paragraph id

---

browser/css/leaflet.css
browser/src/control/Control.DownloadProgress.js

Change-Id: I3294ce292b7921e36cb243f25149375f025e517d

Fix DownloadPopup close btn overlapping popup link

---

browser/src/map/handler/Map.Infobar.js

- infobar: remove interval timer
- infobar: listen 'updateviewlist' event

Infobar changes

---

docker/from-packages/scripts/start-collabora-online.pl

based on extra_params update the scheme and port when mapping domain->alias_groups
Change-Id: Ic5783112b8331407622f547a84d70ab2e1ba0c37

docker: improve start-collabora-online.pl

---

kit/ChildSession.cpp
wsd/ProofKey.cpp

GCC 12 build fixes.
Please see commit logs for details.

GCC12 Build Fixes

---

browser/src/map/Map.js

Change-Id: I54a5d6501f8a70cada753708c2b0f20c1ae95372

browser: fix undefined doclayer exception

---

browser/html/cool.html.m4
wsd/FileServer.cpp

Change-Id: I9939ee243aa81b50969168df2e8bb5c8cbf2a34c
* Resolves: # 

If integration theme does not exits, fall back to default theme

---

browser/src/map/handler/Map.Welcome.js
wsd/FileServer.cpp

- wsd: remove unused welcome code
- config: simplify enable welcome message
- browser: ensure if welcome was disabled
- wsd: fix enable/disable welcome message
* Resolves: # 

Ticket #4489: welcome fixes

---

kubernetes/helm/collabora-online/templates/configmap.yaml
kubernetes/helm/collabora-online/values.yaml

Change-Id: Ie7a3db6fafd164541075baf6577dd6dc7d72a5c1

kubernetes: introduce config map

---

wsd/COOLWSD.cpp
wsd/ClientSession.cpp
wsd/ClientSession.hpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp
wsd/TileCache.cpp
wsd/TileCache.hpp

Change-Id: I9d67f92ba99037954400e07a7d1101e5de3716fd

wsd: reuse parsed message

---

browser/src/map/handler/Map.Infobar.js

Change-Id: I12a236ad6ee112e620c100b8bbf0663cd2e3c4b6
* Resolves: # 

remove interval timer and listen to updateviewlist event.

---

wsd/COOLWSD.cpp

Change-Id: I1f101d8091a5fae64f19b8d4ace7b2db7d5cf5b1

add server id to capability list

---

ios/Mobile/CODocument.mm

Fix the iOS app, part 1

---

browser/src/core/Socket.js

Now the tiles show up correctly in the iOS app again.
Change-Id: I2b1741ed9f5fc4e4df30cb67addfa45eb0d20b92
* Resolves: # 

On iOS the tile messages arrive with e.data as a string

---

browser/css/override-vex.css
browser/src/control/Control.Command.js
common/CommandControl.cpp
common/CommandControl.hpp
common/ConfigUtil.cpp
common/ConfigUtil.hpp
configure.ac
coolwsd.xml.in
wsd/COOLWSD.cpp
wsd/ClientSession.cpp
wsd/ClientSession.hpp
wsd/DocumentBroker.cpp
wsd/HostUtil.cpp
wsd/ProxyRequestHandler.cpp
wsd/ProxyRequestHandler.hpp
wsd/Storage.cpp

Upsell backport

---

browser/src/layer/tile/AutoFillMarkerSection.ts

This will allow to fill column with formula when data
are present in neighborhood

calc: handle DoubleClick on AutoFillMarker

---

wsd/FileServer.cpp

Change-Id: I586da3390487727f0d4b743d4d285cce59f7d55b

wsd: slightly improve logging in case of version mismatch

---

PROBLEMS
common/Util.hpp
net/Socket.cpp
net/Socket.hpp

- wsd: fix signedness warning/error
- wsd: minor log improvements
- docs: add note on Control-C and --cleanup

Sign Mismatch Warning and Logging 

---

browser/src/layer/tile/AutoFillMarkerSection.ts

- allow to use auto scrolling feature by event propagation
- it required to create new modified event which will
contain coordinates of the autofill marker

calc: scroll when we reached end of view on AutoFill

---

kit/Delta.hpp

Change-Id: Ia6ed98534f87006ba5ffcffc8b928f16cfc892cd
* Resolves: # 

delta: fix delta cache sizing.

---

kit/Kit.cpp

Requires an updated core.
Change-Id: Ie000e86851d7dfbc1e70a3f1631d427a3d18188f
* Resolves: # 

Add the ability to dump internal LOK core state / details.

---

common/Seccomp.cpp
common/SigUtil.cpp
common/SigUtil.hpp
common/Util.cpp
gtk/mobile.cpp
kit/ForKit.cpp
kit/Kit.cpp
net/HttpRequest.cpp
net/Socket.hpp
tools/Config.cpp
tools/Connect.cpp
tools/KitClient.cpp
tools/Replay.hpp
tools/Stress.cpp
wsd/Admin.cpp
wsd/COOLWSD.cpp
wsd/COOLWSD.hpp

- wsd: http: improved logging
- wsd: always use Util::forcedExit to properly cleanup
- wsd: remove default arg from SigUtil::killChild
- wsd: mark copied jails early

Misc Minor Improvements

---

common/SigUtil.cpp
common/Util.hpp
configure.ac
kit/ChildSession.cpp
kit/ChildSession.hpp
net/HttpRequest.hpp
wsd/COOLWSD.cpp
wsd/ClientSession.cpp
wsd/ClientSession.hpp
wsd/DocumentBroker.cpp
wsd/HostUtil.cpp
wsd/Storage.cpp

...for variables coming from configure.ac.
Change-Id: I39ebd21c4cb56d2a3bd38fdc35dc59b5f1fd4b49

Replace #ifdef-s with #if-s, and enable -Wundef

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/org/libreoffice/androidapp/ui/FileUtilities.java
android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java

Change-Id: I7b28870e3b1d3c4941e516871c2077e1d0695d09
* Resolves: # 

add .xlsm mimetype to android

---

common/Message.hpp
common/Unit.cpp
common/Unit.hpp
common/Util.hpp
net/WebSocketHandler.hpp
test/Makefile.am
test/UnitWOPIAsyncUpload_Close.cpp
test/UnitWOPIRenameFile.cpp
test/UnitWOPISaveAs.cpp
test/UnitWOPISaveAsWithEncodedFileName.cpp
test/UnitWOPIStuckSave.cpp
test/UnitWOPIVersionRestore.cpp
test/WOPIUploadConflictCommon.hpp
test/run_unit.sh.in
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

- wsd: test: handle save notifications in tests
- wsd: test: filterSendMessage -> filterSendWebSocketMessage
- wsd: test: cleanup and cosmetics
- wsd: Message supports new find and contains operations
- wsd: test: support filtering Kit messages
- wsd: timeout on saving stuck with test

Backport of Stuck-Saving

---

browser/Makefile.am
browser/css/color-palette-dark.css

This reverts commit a864d41c09e16a44e733050c02a3314642bec050.
Because we can now work in this WIP feature in its dedicated
feature branch.
* Resolves: # 

Revert "Revert "Add color-scheme-dark.css support""

---

browser/css/cool.css
browser/css/toolbar.css

- Fix position of avatar list
- Avatar List: Remove extra margin rule for user-info

private/pedro/avatarlist 2111 T36961 T36421

---

browser/src/control/Control.UIManager.js

This has the intent to help any integrator in targeting  CO
and thus adding additional buttons etc when EnableShare is true.
Change-Id: Id010d1e817c3d32c5a835ee0bf8aabefc977f962

Note when in presence of an integrator with sharing capabilities

---

docker/README
docker/from-packages/RHEL8
docker/from-packages/Ubuntu
docker/from-packages/scripts/install-collabora-online-rhel8.sh
docker/from-packages/scripts/install-collabora-online-ubuntu.sh

Change-Id: I437b0a4c4eb552579548bc0ede66a8209453d360

docker: update files for the 22.05 release

---

browser/css/cool.css
browser/css/toolbar.css

Follow up on the changes introduced in
4e07514 , update acceptrackedchanges svg
Change-Id: Id2902602a546756d1d8e9299fa7e91d2750f5ce8

Fix outdated accepttrackedchanges svg references in CSS files

---

browser/css/jssidebar.css
browser/src/control/Control.JSDialogBuilder.js
cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js

There is no reason for custom handler.
Thanks to that we don't need special css.

jsdialog: unify clear formatting icon

---

browser/src/control/Control.Menubar.js
cypress_test/integration_tests/desktop/writer/file_properties_spec.js

Now it is merged on core side.
This reverts commit 4e3b34d6dd6dfe24a4c0707bb2da1d6ab7d1699a.

Revert "cypress: skip file properties for now"

---

browser/Makefile.am
browser/src/layer/tile/CanvasSectionContainer.ts
browser/src/layer/tile/ScrollSection.ts
common/Authorization.hpp
common/MessageQueue.hpp
common/Session.hpp
common/StateEnum.hpp
common/StringVector.hpp
common/TraceEvent.hpp
common/Util.hpp
cypress_test/integration_tests/common/helper.js
kit/Kit.cpp
net/HttpRequest.hpp
net/NetUtil.hpp
net/Socket.hpp
net/SslSocket.hpp
test/HttpTestServer.hpp
test/UnitWOPIAsyncUpload_Modify.cpp
test/WopiTestServer.hpp
wsd/ClientSession.hpp
wsd/DocumentBroker.hpp
wsd/QuarantineUtil.cpp
wsd/RequestDetails.cpp

Change-Id: I813f652b516c79f350b46317e589b91e0ef39a1a
* Resolves: # 

Fix typos in comments

---

kubernetes/helm/collabora-online/templates/ingress.yaml
kubernetes/helm/collabora-online/templates/service.yaml

This reverts commit 22f38ef455ecd72736a78007e59d5b0d80d76619.
Change-Id: I26bafde2db40c327ba5bcb2ea2ccf49de1287b3e
* Resolves: # 

Revert "HAProxy: better load balancing"

---

browser/src/control/Control.JSDialog.js

Change-Id: If8b01a7c29ade1f6ed17cb865a975cf38c5ea4f3

Set proper button-primary CSS class, don't rely on IDs

---

browser/src/control/Control.UIManager.js
browser/src/map/handler/Map.Keyboard.js

Change-Id: Ibfd160fd8fb80a9dfd4c71dfb9a4a2725be48465
* Resolves: #4920

Stop follow user feature if a key has been pressed by the original user.

---

browser/src/control/Control.JSDialogBuilder.js
cypress_test/integration_tests/common/helper.js
cypress_test/integration_tests/desktop/writer/table_operation_spec.js
cypress_test/integration_tests/mobile/calc/number_format_spec.js
cypress_test/integration_tests/mobile/writer/apply_paragraph_properties_spec.js
cypress_test/integration_tests/mobile/writer/focus_spec.js
cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
cypress_test/integration_tests/mobile/writer/table_properties_spec.js

this needs also core part, fixes chrome spinfield updates which are ignored when clicking very fast on arrows (up/down)

jsdialog: spinfields improvements 21-11

---

browser/html/cool.html.m4

Follow-up to 616e9200d126bda70b32d31d6e6ac9d43f75559d.
Change-Id: I4d9a77d34c3ae3f45df6bce9afad5c99b2142358
* Resolves: # 

Use the name "lok" for the iOS app Webkit message handler here, too

---

common/FileUtil.cpp

...when it's requested.
Previously always an empty string was returned on subsequent
calls, and the error message was only shown once.
Change-Id: I7645c7770e3e1712c8ef1b3ad145daec14530fb0

wsd: Cache result of disk space check, too

---

ios/Mobile/L10n.h
ios/Mobile/L10n.mm

Change-Id: I28cdba1b82d391cf4d847c6e2e40f8e08d928519
* Resolves: # 

ios: Rule out LIBO_VERSION checking on master

---

browser/package.json

Change-Id: I8d3e85ab0b1d590a130569dd74d3c45cade708f5
* Resolves: # 

Attempt to solve FreeBSD issue.

---

browser/html/framed.doc.html
kit/ChildSession.cpp

Change-Id: I0e42bf2efcc2aa6ecf3f6705aab621cc1ea18774
* Resolves: # 

Embed images to exported HTML

---

common/Log.hpp
common/Session.cpp
kit/ForKit.cpp
kit/Kit.cpp
net/Socket.cpp
tools/WebSocketDump.cpp
wsd/COOLWSD.cpp
wsd/DocumentBroker.cpp
wsd/Storage.cpp

- wsd: fix multi-part logging
- wsd: minor log cleanup
- wsd: reduce logging of allowed convert-to addresses

Log Improvements

---

browser/src/layer/marker/Cursor.ts

Change-Id: I15418181394d27cb379d99e7f4c688153ac7a443

Resize cursor width according to browser zoom.

---

kubernetes/helm/collabora-online/templates/ingress.yaml
kubernetes/helm/collabora-online/templates/service.yaml
kubernetes/helm/collabora-online/values.yaml

Change-Id: I7297069166b33669a9c1f91f62ee35c77f2887cd

improved load balancing with HAProxy

---

browser/css/device-mobile.css
browser/src/control/Control.ContextMenu.js

- [] I have run tests with `make check`

Mobile: hide non-working context menus, and fix missing icon

---

browser/src/layer/tile/CommentSection.ts

Change-Id: I6eeb716c118778c1a386437c751bda3e9e3a5a24

fix: calc: comments in frozen row headers aren't shown after scrolling

---

kubernetes/helm/collabora-online/templates/hpa.yaml

Change-Id: I677dff0deb34a3c505ed0422bb359de7691d4c90

updated kubernetes HorizontalPodAutoscaler to V2

---

browser/css/cool.css
browser/html/cool-help.html

Change-Id: I766076d7819dfb2034134d3cb2a3f67ed0110b2c

Fix Online help: buttons are no buttons, also decrease vertical space

---

browser/src/control/Control.JSDialogBuilder.js

indexOf returns position - do not sum the positions This fixes not working cursor position change in
formulabar when we had multiple lines.

formulabar: fix selection in multi-line cell

---

browser/Makefile.am
browser/css/cool.css
browser/html/framed.doc.html
browser/src/control/Control.JSDialog.js
browser/src/control/Control.JSDialogBuilder.js
browser/src/control/Control.Mention.js
browser/src/control/Control.UIManager.js
browser/src/layer/marker/TextInput.js
browser/src/layer/tile/CanvasTileLayer.js
browser/src/map/handler/Map.WOPI.js

Change-Id: I326cd663737a2e8e04bedeccd8f130fec4014c26
* Core patch: https://gerrit.libreoffice.org/c/core/+/140015
* Resolves: # 

writer: introducing new mention feature

---

browser/Makefile.am

Change-Id: Iceebef11d522be1a964be35dbd6484ed44b699d4
* Resolves: # 

Enable l10n of browser/src/map/handler/Map.Feedback.js

---

browser/src/layer/marker/TextInput.js

Change-Id: I7fac8ddfcdf5eeb3f03fe79bdf538fb52d311cce
This fixes both the chrome and firefox bugs  :)

browser: fix: using IME input candidates cannot be selected correctly

---

browser/src/control/Control.Command.js

Change-Id: Id667f4307b30eb38b0ebe0ce4ff6ee71b62020eb
* Resolves: #5323

fixed read only feature locking popup not working

---

browser/css/override-vex.css

Before this commit, list entries with multiple lines where not being
properly aligned.
Change-Id: I0ca9861289f471285ace2dc1d39104d608eb8f15

Fix multiple line list within feature_lock dialog

---

browser/html/cool.html.m4
browser/src/map/handler/Map.WOPI.js
wsd/FileServer.cpp
wsd/FileServer.hpp
wsd/FileServerUtil.cpp

Change-Id: I4d9015840335131bf5e5e30c66a29f7cdb492e3a

feat: added  checkfileinfo_override header's handling

---

wsd/COOLWSD.cpp

Cleanup remote config

---

browser/admin/adminSettings.html
browser/admin/src/AdminSocketSettings.js
common/Util.cpp
config.h.in
configure.ac

Change-Id: Iac66ea99d23416c494b04ff92abc0bfeb646e5be
* Resolves: # 

Display build config (configure options) on admin console

---

browser/src/core/Socket.js
coolwsd-systemplate-setup
coolwsd.xml.in
kit/ChildSession.cpp
wsd/COOLWSD.cpp

For now, just display it using an infobar. UI experts, feel free to
design something more appropriate.
Change-Id: I0b6e592a51441299cc08d0e42ba3b5c5087b30db
* Resolves: # 

Handle the callback for missing fonts

---

browser/src/layer/marker/TextInput.js

Change-Id: I422f63c6d3963bdf125fc00e7dafc4428883c7ce
* Resolves: # 

Add percentage sign to cell automatically.

---

browser/Makefile.am
browser/src/control/Parts.js
browser/src/layer/tile/CalcTileLayer.js
browser/src/layer/tile/CanvasTileLayer.js
browser/src/layer/tile/SheetSwitch.ts
cypress_test/integration_tests/desktop/calc/autofilter_spec.js

* Resolves: # 
restore view on sheet switch

restore scroll position on sheet switch (master)

---

browser/src/map/handler/Map.Keyboard.js

Signed-off-by: Tushar <tusharbarman123@gmail.com>
Change-Id: Iccb2e4e89381a78337a3123543d01b00f9f24e6f
* Resolves: # 
Just added some of the keystrokes, much more needed to be done

Replace magic numbers with keycode constants #4929

---

browser/Makefile.am
browser/src/control/Parts.js
browser/src/layer/tile/CalcTileLayer.js
browser/src/layer/tile/CanvasTileLayer.js
browser/src/layer/tile/SheetSwitch.ts
cypress_test/integration_tests/desktop/calc/autofilter_spec.js

* Resolves: # 
* Target version: co-21-11
restore scroll position on sheet switch

restore scroll position on sheet switch

---

config.h.in

Change-Id: I5ffbe723341fc5a2e4363aaa6abe11e33e262ffa

config: HAVE_PPOLL should be 0 by default instead of undefined

---

browser/css/menubar.css

Change cursor so to make that clear
Change-Id: Ia448e639d98186c3e5eb5ef8ccc9236031ba3774

Disabled menu items are not clickable

---

browser/src/control/Control.JSDialogBuilder.js

Use iconURLAlias -> signature (already available svg)
Change-Id: Icdc35aa7206efedffb88d9c87992b791de05647d

Fix missing lc_signdocument svg

---

browser/package.json

Change-Id: I779dc0d4c328e5fba20b9c458152358d2038f170
* Resolves: # 

Move node-canvas into devdependencies.

---

browser/src/control/Toolbar.js

Change-Id: I7212e6a617df159a5ee42ff03bfd6d8a3aaac444
* Resolves: # 

Allow .uno:ResolveComment on readonly mode.

---

kubernetes/helm/README.md
kubernetes/helm/collabora-online/Chart.yaml
kubernetes/helm/collabora-online/grafana_dashboards/ha-allocation.json
kubernetes/helm/collabora-online/grafana_dashboards/overview.json
kubernetes/helm/collabora-online/templates/_helpers.tpl
kubernetes/helm/collabora-online/templates/configmap.yaml
kubernetes/helm/collabora-online/templates/configmap_grafana_dashboards.yaml
kubernetes/helm/collabora-online/templates/dynamicConfig_configmap.yaml
kubernetes/helm/collabora-online/templates/dynamicConfig_deployment.yaml
kubernetes/helm/collabora-online/templates/dynamicConfig_ingress.yaml
kubernetes/helm/collabora-online/templates/dynamicConfig_service.yaml
kubernetes/helm/collabora-online/templates/hpa.yaml
kubernetes/helm/collabora-online/templates/prometheus-rules.yaml
kubernetes/helm/collabora-online/templates/secret.yaml
kubernetes/helm/collabora-online/templates/serviceaccount.yaml
kubernetes/helm/collabora-online/templates/servicemonitor.yaml
kubernetes/helm/collabora-online/templates/statefulset.yaml
kubernetes/helm/collabora-online/values.yaml

Make this HelmChart to state of the Art ;)
with nice optional Features:
- Monitoring with Prometheus:
- ServiceMonitor
- Alerting (with default PrometheusRules)
- Grafana Dashboards
- Dynamic Config reloading:
- extra nginx-pod (+service, + ingress)
- json will be generated from values.yaml into a ConfigMap
---
After Merge, please Release it to https://artifacthub.io/

improve HelmChart

---

browser/src/layer/tile/CanvasTileLayer.js
browser/src/layer/vector/SVGGroup.js
kit/ChildSession.cpp
kit/Kit.cpp
net/HttpRequest.hpp
wsd/COOLWSD.cpp
wsd/ClientSession.cpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp
wsd/FileServer.cpp

- embedded video: show inside selection marker
- wsd: support embedded media

Embedded Media

---

docker/from-source/Debian

Signed-off-by: Tushar <tusharbarman123@gmail.com>
Change-Id: Id8a6769ffab18b1d5094799e63d851685c5b1a4f
* Resolves: #4695
Have resolved all the dependencies issues related to Debian 11 dockerfile.

resolved the Debian 11 dockerfile dependecies issues

---

browser/src/layer/tile/CanvasTileLayer.js
common/Util.cpp
common/Util.hpp
kit/ChildSession.cpp
wsd/ClientSession.cpp
wsd/ClientSession.hpp
wsd/DocumentBroker.cpp
wsd/DocumentBroker.hpp

- wsd: extract URI encoding in a helper
- wsd: reuse getClipboardURI generically
- wsd: move mediashape handling to ClientSession
- wsd: move svg processing to ClientSession

Embedded Video Improvements

---

browser/src/control/Control.JSDialogBuilder.js

works with: https://gerrit.libreoffice.org/c/core/+/141619

jsdialog: apply edit field type

---

browser/css/jssidebar.css

Fix alignment panel width in calc

---

wsd/Admin.cpp

Change-Id: Idfe4ee00be9f805f5e12c7ece4f890aa2b9d08ed

wsd: limit memToFreeKb in Admin::triggerMemoryCleanup()

---

browser/src/map/Clipboard.js

To copy paste whole column into another document needs more time to get a reply from server.
Change-Id: I5321b42e321179d541464f8cbdc49fe01502c353
* Resolves: # 

Increase the timeout in case copy-paste whole column.

---

scripts/build-zstd-ios.sh

Improve zstd ios build script

---

browser/src/control/Control.ContextMenu.js

Thanks to Tracie Fabb for the tip.
Change-Id: I5e8a7cb833e0d9a6257fd73324cd1fa553de1fd9
Requires: https://gerrit.libreoffice.org/c/core/+/142163 to be merged too ...

calc: add InsertCells / DeleteCells to calc row/column context menu.

---

common/Unit.hpp
test/UnitWOPILock.cpp
wsd/ClientSession.cpp

Change-Id: Ib91f53f4ebbfef8d93cebe24d48fea26df479dfa

wsd: improved UnitWOPILock to avoid race-condition

---

docker/from-source/ArchLinux

Change-Id: I96a3f07e32fe0132be2081db11b62c666097057d

docker: added docker file for arch linux to build from source

---

ios/Mobile/Info.plist.in

Change-Id: I76e35aad4115ad4dd7ddcd60b579d16ee3aa58d2
* Resolves: # 

Bump CFBundleShortVersionString to match configure.ac

---

browser/src/control/Control.Menubar.js
browser/src/map/handler/Map.Feedback.js

That is only for web-based COOL. The mobile app stores have their own feedback and rating mechanisms.
Change-Id: I6f28e27abdf204c7b77247136cc88924639efbd7
* Resolves: # 

Avoid the Send Feedback functionality in the mobile apps

---

browser/src/layer/tile/CanvasTileLayer.js

Change-Id: Ib1a22ce30c9b84692c673196642cf0522035d5ea
* Resolves: # 

Enable print dialogue on FireFox browser.

---

ios/Mobile/DocumentViewController.mm

Signed-off-by: Tor Lillqvist <tml@iki.fi>
* Resolves: # 

Add a cross-referencing comment

---

browser/css/notebookbar.css

Change-Id: Ie9f02a9d453ca269305f6c7e382d9dacf532dcc0

Show not-allowed cursor when user mouseovers disabled items

---

wsd/RequestDetails.cpp
wsd/RequestDetails.hpp

Change-Id: Ib2a6bb69b09776dbaf48216330f1c260299d9cac
* Resolves: # 

RequestDetails::_isMobile is unused

---

browser/src/control/Control.Header.js
browser/src/control/Control.LokDialog.js

Change-Id: I09ca97f2f7ec19cd4836f0dbfb8cbf863f3c5f3e
* Resolves: # 

Send column selection text when Function Wizard is open.

---

browser/src/control/Control.JSDialogBuilder.js
browser/src/control/Toolbar.js

Change-Id: I6ec564d2524a9cc8735179fc282eaf8deb81a74b

annotation: fine tune the comment permission in mobile

---

wsd/COOLWSD.cpp
wsd/HostUtil.cpp

* Resolves: # 
* Target version: co-21-11

Backport remote config imprv

---

.gitpod.dockerfile

Fixes issue #5465
Change-Id: I5139fb4491cc1c6a29bfdf3ef3e0b2b7cb9c890c

GitPod: Fix No package 'libzstd' found

---

wsd/Admin.cpp

Follow-up to
<https://github.com/CollaboraOnline/online/pull/5421#pullrequestreview-1179138409>.
Change-Id: Ie293218e504808d317436181639d9189eb6fb05c

admin: drop conditional that is now redundant with clamping
