- coolwsd.xml.in
- kit/Kit.cpp
- wsd/COOLWSD.cpp
The path of the NSS certdb is defined in the coolwsd.xml config
file and if the config file is set and contains the certdb files,
then the db files are copied to the jail into /tmp/certdb folder.
Also the /tmp/certdb path is set to LO_CERTIFICATE_DATABASE_PATH
env. var, which is then used as the default certdb in LibreOffice
when LOKit starts up.
Signed-off-by: Tomaž Vajngerl <tomaz.vajngerl@collabora.co.uk>
Change-Id: I72e8f28f27a0306fef9319bc6212cd99cb3f8212
* Resolves: # 
> support for a custom path to NSS certdb files for sign/encrypt

- browser/css/notebookbar.css
Removes additional vertical padding that was conflicting with overall
vertical alignment (specially affecting hamburger icon but also save...)
Change-Id: Iccfc308c689cd2f522709143fbbe692ec537a625
> Fix for notebookbar-shortcuts-bar vertical alignment

- common/Protocol.hpp
- wsd/TileCache.cpp
To simplify code that wants to extract a non-negative number from a
token value. See
<https://github.com/CollaboraOnline/online/pull/3788#pullrequestreview-826099897>.
Change-Id: I389dfa1a2838e501fc308dbfd7927b142a361922
> common: introduce COOLProtocol::getNonNegTokenInteger()

- browser/css/device-mobile.css
Even though the on mobile the display set to flex seems to work
introduced with 95bd65d2f658ca8c378b50f4ff09ef1424c15c13
the fact is that we do not need flex here and it might cause different
unexpected results depending on the device
This commit is not needed on 6.4 (as it was already fixed while cherry
picking Document has been changed related commits)
Change-Id: Ib50d6fa9e1e456c3dfdceaae802c2fe1edad15a7
> Document has been changed: set cancel btn on mobile to block

- browser/css/device-mobile.css
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
In master the toolbar height is smaler than a selected command
With this request the toolbar height has the same height
than a selected command at the bottom toolbar
Change-Id: I147237b9a68730dc5a3655a752ee0231275b55e4
**BottomToolbar before**
**BottomToolbar after**
**BottomToolbar search after**
> Mobile: Fix BottomToolbar height

- browser/js/global.js
At least for me, whenever I have seen the result of that code logged
in Xcode when debugging the iOS app, the lines for the "description"
and "stack" have said just "[object Object]". It is unclear whether
that is because the code explicitly assigns the empty object {} to the
desc and stack variables here, or because err.message and/or err.stack
do exist but are objects, not strings.
Change-Id: I08a2fa361baf20814a40249d30ff49ba39292aa6
* Resolves: # 
> Prefer "(no message)" etc to "[object Object]"

- browser/Makefile.am
enabling source maps helps while debugging through the IDEs
it becomes necessary with typescript
Change-Id: Ia5f09595ed9726e0076d1837024868a651d92361
> enable source maps for debug mode

- coolwsd-generate-proof-key
The downstream packagers can patch the "PREFIX=/" line to their liking.
While there, converts tabs into spaces for consistency.
Change-Id: I424f6fe6efac8e51f74f5848586e7fd10fa40904
> Make coolwsd-generate-proof-key prepared for a custom prefix.

- browser/css/jssidebar.css
Endable checkbox use flex-start
Transparancy label and spinfieldcontainer are vertical aligned
Change-Id: I49cfdf4b3b508b7f178d76a4c5e61c4b21fdf2bb
* Resolves: # 
**Screenshot after**
> Sidebar Shadow Section alignment

- browser/css/jssidebar.css
spinboxes are right aligned
labels are vertical center aligned
remove padding at table element 
so all commands have the same row height
Change-Id: If5b89cac71e2918d3d870066f2b895136286b8b2
**after**
> Calc sidebar NumberFormat section alignment

- browser/images/lc_forumhelp.svg
**Steps to test**
- notebookbar
- open help tab
- first command
**reason of the change**
the old icon didn't use 1px width line style
in addition an annotation symbol is better for converstation
Change-Id: I2244ca7779dc607b27a123133b89d211ac541f93
> Update forumhelp icon

- loleaflet/src/map/handler/Map.FileInserter.js
Change-Id: I56d38f05d8da4fc55393203764692ca2b5f864f2
* Resolves: # 
> Fix InsertFile returns 400 after an idle reload

- browser/css/color-palette.css
- browser/css/jssidebar.css
add a --border-radius: 4px value
and use it for sidebar and notebookbar
other stuff will follow, but I want to test where the value was visible
selected-inline values in notebookbar use border-radius
**test change**
- use notebookbar in writer
- goto tab review
- Automatic Spell Checking use now the border-radius: 4px
Change-Id: I3083cd2ff2cc3efd784aafb0c71cb2f823b9b79d
value name is similar to https://github.com/nextcloud/server/blob/master/core/css/css-variables.scss#L57
> Use var(--border-radius)

- browser/js/w2ui-1.5.rc1.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.Toolbar.js
Home tab's contitional formatting control is old and is not the same
as Format's tabs control. Now they are the same.
Change-Id: I9a08cda3a2ff98a18e711ba4a17bd8ebb8b4027b
* Resolves: # 
> notebookbar: use more advanced optioned Conditional Formatting control

- browser/src/layer/tile/ScrollSection.ts
autoscroll caused cell selection problems when selection started from origin
Change-Id: Icfc45d3859fe1c6e25b2d5b54a3cafe0e2cd622e
> Avoid unintentional autoscroll near document origins

- browser/css/jssidebar.css
This reverts commit 27be41fb787762111cd1212524e3f3c48b4d8cb1 which introduce regression (align buttons in the sidebar calc overlap each other)
> Revert "Draw/Impress sidebar paragraph topalignment space"

- browser/css/menubar.css
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/impress/scrolling_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
To occupy less space critical in some languages where the last save
string is quite long also increase its height so the click target
is not too small
Change-Id: I16affef5b5ecb484a14c7f6ff03ba8a28b3eef63
> Classic: shortened size of menus

- cypress_test/integration_tests/common/mobile_helper.js
'Select time from list' test was failing because to click on 'Time' option, cypress's contains() will search for element with class .ui-combobox-next having 'Time' substring but there are two element containing 'Time' substring having same class. By adding regex we make sure that the selection and click on element happens on exact string not on class containing substring.
Change-Id: If44a1a535d4e08d40cc069308c2a637c6bd07048
> cypress:fix: number_format_spec.js failure

- browser/src/core/Socket.js
Otherwise, the 'rulerupdate:' message, it never processed
and the ruler show like an empty box.
Change-Id: Ibe0e76e3615c2c9460aba65dbe76fbad51e9bf42
> browser: fix 'rulerupdate:' missing message

- browser/src/main.js
fix "Uncaught TypeError: Cannot set property 'permission' of undefined"
Change-Id: Id3844d1fe5ac309b0a7c703f6913f6e632d46dff
> browser: fix WOPI empty params

- browser/css/jssidebar.css
This complements the rework of highlights (mouse hover) from
b199fd0f8777afa002ad82e8cfb60bd95d1429c6 by adding the missing elmts
Change-Id: I632470b088c7e8775849933b657583fc908f7bcc
> Add missing highlight color to clear n paste Formatting

- browser/src/core/Socket.js
Also, the ReconnectCount under normal condition
it should be 0, otherwise the document is cleaning the session.
Change-Id: I07b383a7810b8bc06e207fc600ebec99eaac9c77
> browser: show busy label if cleaning session

- browser/css/device-tablet.css
In the wsd version git hash was getting set right after the previous
word (completely adjacent and without space and brackets)
- Fix outdated "loolwsd-*" class name and make sure the CSS rules does
get applied
Change-Id: I77ea5ac19a5dbaa798437ec70489a1aee1051b1f
> Aboud: Ipad: Fix git hash formatting

- browser/css/cool.css
On Chrome the scroll bar was overlapping some sidebar icons; The
scroll bar thumb was not the same color as the document scroll bar.
Additionally on Firefox (using Windows) the sidebar-panel's scroll bar
would also overlap a bit of those sidebar icons.
- Fix sidebar scroll bar width and make sure is not too big
- Done in different ways for Chrome and FF since they do not posses the
same CSS spec (plus FF does not allow the use of exact widths)
- Fix sidebars inconsistencies regarding color
- Use the same #bec0c0 used in the document's scroll bar albeit only
on mouseover. In the default state it stays with the browser's default
opacity and thus looks lighter than the document's scroll bar. This
is not only fine but desirable so to avoid taking to much attention
from the document itself. …
> Fix Sidebar scroll bar width and improve consistency

- coolwsd.xml.in
- net/Ssl.cpp
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
(cherry picked from commit dad7ed85e97afe0e4f5229b1de125aada9a8c2e8)
Change-Id: I5683f835f37f67ee353a0b629a4662c7c78787a6
> wsd: enforce TLSv1.2 as the minimum acceptable version

- browser/css/menubar.css
- browser/css/notebookbar.css
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Make the whole nav bar scroll-able, specially important when still on
desktop but using small factor screen or simply when resizing window
Change-Id: Ib0011c8353a5c4d09f5f150032088bc69e0f7d90
> Notebookbar: Fix Tabs' overlapping into other elements

- browser/css/menubar.css
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
c9b4b619cfde85553761662f9a7d5914e246b2f4 fixed the tabs overlap issue
but for the smartmenus on notebookbar (hamburger menu) to work the CSS
overflow property needs to be set (both for x and y) to visible, any
other value and the smartmenus' visibility suffers (gets cropped).
- Make set the CSS overflow property of .main-nav elm dynamically
depending on menu state.
- If it's open: set to `visible`
(this disables the .main nav scroll but that's completely fine
for when the Hamburger menu is open since it's not needed)
- If it's close: back to `scroll hidden`.
Change-Id: I8a5522cb4a107d0583cde252e2ee551124c06f02
> Notebookbar: Fix smartmenus visibility and set overflow dynamically

- browser/src/control/Control.LokDialog.js
- browser/src/map/Map.js
If the size is the same as last time we sent the message, don't send
it. This fixes ugly flashing of the input bar tunnelled dialog when
the symbols displayed in front of the input field change.
Change-Id: I6532d85fddede54f416ee6686958bb650fdcb4f1
* Resolves: # 
> Don't send unnecessary resizewindow message for the Calc input bar

- browser/css/jssidebar.css
Changes introduced in 46a7f6ba98b46f3e653830fb85f1144172efc696
and intended only for desktop were affecting mobile as well.
Change-Id: Iedc11d3a4a4fabdf45e82c0b112ba040ecd4e154
> Mobile:remove padding n width from color panel

- browser/src/control/Control.DocumentNameInput.js
Change-Id: Ie163ee479ee62d314248a8b891751a3755eca4ca
* Resolves: #3880
Adds the file path as a title attribute so that it shows up as a tooltip when you mouse over the file name. It show up as the following:
```
File_name.extension
Path: Path/to/folder/containing/file
```
Added the translation for the most popular languages for 'Path': English, French, Spanish, Italian (bonus: Romanian).
> browser: add file path tooltip

- browser/css/toolbar.css
- browser/src/control/Control.UserList.js
Improvement on top of 89f55aaa183ed8a301b64a45b3146c3ef30ac23e
- no need to add additional classes to each element when we
can target html element's rtl attribute
Change-Id: I719b9c8b02add7948bc4ae819ae5e48f1aa33342
> RTL: user list: target rtl attribute instead of class

- loleaflet/src/layer/tile/CalcTileLayer.js
as of co-2021 we use a new jsonwriter for json callbacks and it generates an empty array.
but in cp-6.4 we use boost for generating json and it cannot create an empty array
but instead it creates an empty string
The previous fix was taking advantage of it being an empty array
Change-Id: I0b4a4b39c3cff0b2f054765dbc47527633b56151
* Resolves: # 
> calc: fix commentsPos field is empty string instead of empty array

- tools/Config.cpp
Change-Id: I1efcca7a773df366a2cca1d56f1d6fb967402deb
* Resolves: # 
> coolconfig: allow set command to create new config settings

- browser/css/device-mobile.css
This was affecting some themes and plus is not used anywhere on mobile
it was just causing troubles for no benefit
On mobile we rely on the bottom border of toolbar wrapper and thus
toolbar-up doesn't need any border. For now I opted to just make
transparent to avoid any bad outcomes with positions etc.
Change-Id: Idd4f08c15ac252ffd410bc7e919975e35512963c
> Remove border color from #toolbar-up on mobile

- browser/src/layer/tile/ScrollSection.ts
it is possible to scroll outside the document
with anything that uses onScrollBy function because
it does not respect the scroll area.
Change-Id: Ia8609311b8ead97f5866ff6300ddebb0d3f5b14d
* Resolves: # 
> fix infinite scrolling

- wsd/DocumentBroker.cpp
This avoids all the corner-cases of 'unloading document recovery' by pushing back on the new connection while unloading, so that the client will have to retry again later. This seems to handle reloading cases handsomely and it also restores the older behavior anyway.
- wsd: dump the state of the sessions of DocBroker
- wsd: do not load a new view when unloading
> Unloading documents now make new clients retry after unloading is complete

- browser/src/control/Control.Header.js
Change-Id: I141dd097e326c99021f5f85b95113e79c57cadd8
* Resolves: # 
there can only be one isCurrent row/col
in case of multiple row/col selected,
original condition may fail as row/col maybe selected
but not the current.
added condition to also check if the row/col is selected
> browser: fixed broken show row/col after hiding

- coolwsd.xml.in
- wsd/AdminModel.cpp
Change-Id: Icccc9d842703b3159965f67be2bf16404d50bad6
So that the logging about administrative document handling requires intentional configuration to see the data.
put this check in front of every admin level logging ?
> Admin: introduce docstats subsection in logging in config

- coolwsd.spec.in
- debian/coolwsd.postinst.in
Change-Id: I76d06ca68dbb7e62fd4f5e31215d4ba3f753dce9
* Resolves: # 
> automatically migrate old config during package upgrade (6.4 -> 21.11)

- browser/src/control/Control.JSDialogBuilder.js
these boxes should display empty string when there's a mixed of font name
and/or sized text selected as the desktop application.
to test it, it needs a core change: https://gerrit.libreoffice.org/c/core/+/128551
Change-Id: I2564f14f9411711b5a1791d08a90d85235863b18
* Resolves: # 
> fix fontname/fontsize comboboxes shows first element on mixed selection

- loleaflet/src/control/Control.Header.js
there can only be one isCurrent row/col
in case of multiple row/col selected,
original condition may fail as row/col maybe selected
but not the current.
added condition to also check if the row/col is selected
> co-6-4: browser: fixed broken show row/col after hiding

- test/UnitWOPISlow.cpp
When running this test against a debug core.git, then this test times
out for me. But if I increase the timeout, then it passes after 316s
just fine.
Change-Id: I1cd0d227dd9aac7279f991493b9aaa7c07468fdd
> unit-wopi-async-slow: increase timeout

- wsd/AdminModel.cpp
Change-Id: Iea0a75927b495735787496468ab39d5314992a50
> Admin: force un-conditional logging when docstats enabled

- browser/src/control/Control.JSDialogBuilder.js
if the font is not includede in the core and already exists
in the document, we need to display that as menubar's fontnamebox
does
Change-Id: Ia725fb5d031aca9382f0247772bdc9e7bbe95729
* Resolves: # 
> fix selectedFont is not shown on sidebar

- fuzzer/ClientSession.cpp
An alternative would be to tweak online-fuzz/wsd/DocumentBroker.cpp:534
to check for Util::isFuzzing(), but this is probably a better & more
generic way.
'./clientsession_fuzzer fuzzer/data/load' now works again.
Change-Id: I4d9fa387597695ff0802b268bc4d86be51dbabb2
> clientsession_fuzzer: fix missing UnitWSD

- common/Util.cpp
Change-Id: I3490c1353d9e2eebc3dc856fe5bd4767df4b1bec
> use gmtime_r instead of std::gmtime for thread safe purposes

- wsd/AdminModel.cpp
I saw similar implementations in Util.cpp
Change-Id: I3927ef9989de2217dee6c4b3034c9ffbd8fb184d
> Admin: alternate std::localtime

- wsd/DocumentBroker.cpp
When we reject a connection (possibly due to
authorization failure) we will not have a
storage instance to use.
This fixes #4030.
> wsd: handle no-storage when shutting down

- test/TileCacheTests.cpp
- test/UnitWOPILock.cpp
- test/WopiTestServer.hpp
- wsd/DocumentBroker.cpp
- wsd: test: improve and disable TileCacheTests::testTileInvalidatedOutside
- wsd: dump the state of the sessions of DocBroker
- wsd: do not load a new view when unloading
- wsd: test: improve lock tests
- wsd: handle no-storage when shutting down
> Backports from Master

- browser/css/color-palette.css
- browser/css/cool.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
You can simple modify the background colors of the toolbars
for now NB and bottom toolbar
You can edit the borders and separators with --color-border
so it's very easy to remove focus for separators
Change-Id: I661513031eb231d6ffc5036df38381d7fdcac5a7
result look the same than before, 
but the values names are easier to understood 
and changes like in https://github.com/nextcloud/richdocuments/issues/1976
are more simple.
> Toolbars use var(--color-toolbar) and var(--color-border)

- common/FileUtil.cpp
- common/JailUtil.cpp
A non-writable path isn't an error in itself.
The reason why the service tried to write the systemplate,
and the perf implications is worth reporting even on default
log level.
Change-Id: Ie168875ceb4e501291676a5aa4ddc21b88c5761f
> wsd: Adjust log levels

- tools/map.cpp
'sscanf' may overflow; destination buffer in 'smap_key' has size 20, but
the corresponding specifier in tools/map.cpp:570 may require size 21.
Change-Id: Ie7356db924193777869a39b882512a864c0e10c5
> tools: fix -Werror,-Wfortify-source

- browser/css/mobilewizard.css
- browser/src/control/Control.JSDialogBuilder.js
Before we were not passing any additional class to mobile-wizard-content
as a result and, even thought child elements were set to 100% height,
the empty state was still cropped. Pass additional class to parent and
make sure child is set to full height (minus header bar).
Change-Id: I42013bfc9976edcf13680fe428484a086dcf1074
> Mobile: Comments: Fix empty state's height

- cypress_test/integration_tests/desktop/writer/delete_objects_spec.js
- cypress_test/integration_tests/mobile/calc/alignment_options_spec.js
- cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js
- cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
- cypress_test/integration_tests/multiuser/impress/repair_document_spec.js
- cypress_test/integration_tests/multiuser/writer/repair_document_spec.js
removed unnecessary 'retries' parameters from the tests we already
have default global value for retries no need for specific tests
Change-Id: Idc78831ce240d4d840f3dbc785e66165c6e07d3d
> cypress: fix: inconsistent text wrapping text in calc

- wsd/FileServer.cpp
* Resolves: # 
Fix a `CSP` formatting error introduced with 7e94149ec476445a445ffcd0922d83b1c60c5c64.
Spottet this error in cp-6.4.16-2 (however, this tag is not in the merge base but the name sounds legit).
> wsd: fix malformed img-src field

- browser/css/notebookbar.css
- browser/src/control/Control.JSDialogBuilder.js
In writer with notebookbar toolbar there is an option to show
previews of writer styles within the stylesview element.
Now there is an img with the preview AND the text name of the style
with this patch the text was removed and shown as tooltip
The benefit is that you see ONLY an preview of Default Paragr
but not in addition the name which is simple a duplicate
after the patch you see more previews and it's simplier to select
Change-Id: I18605af2daf3c47aee9902164060f530e71fad60
recommendation come from https://github.com/nextcloud/richdocuments/issues/1976
> NB Writer Stylesview show only preview and no label

- wsd/FileServer.cpp
We get a syntax error message in the logs - but have no indication as
to what in the config file caused this issue. Bringing back both more
detail to the browser and logging the extended details.
Signed-off-by: stellarpower <5004545+stellarpower@users.noreply.github.com>
Change-Id: Ib8ddb20a1968f879558e59f50579ee4b18db0f09
* Resolves: # 
> Add more detail to error logs.

- common/FileUtil.hpp
otherwise, on some platforms, the calculation might occur with 32-bits, but we really need 64 bits for microseconds.
Also tweak the return type to make sure we use 64 bits.
Signed-off-by: Noel Grandin <noel.grandin@collabora.co.uk>
Change-Id: Ie8b8a49938c7ac2cfe7c5fc1dd6629e6ea347115
* Resolves: # 
> make sure modifiedTimeUs calculates with enough precision

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
PDFs are view_comment type documents where
editing is not supported, but adding comments
are. This means that we do get ModifiedStatus=true
but we never get ModifiedStatus=false after
.uno:Save. This is because the save command is
handled in a special way in Core by invoking
save-as instead, which doesn't reset the
ModifiedStatus.
The issue with this was that DocBroker was
stuck on trying to save the document
before unloading, thinking it was modified
due to the stuck ModifiedStatus. Here,
we change the definition of isPossiblyModified()
to ignore the ModifiedStatus for such documents.
Instead, we rely on the last save being successful
and that no new user input exists past the last
save request.
In addition, we now have a new Cypress test
that reproduced the failure without the fix
and …
> wsd: support PDF comment saving during unload with test

- browser/src/control/Ruler.js
Otherwise, if the server does not send data the ruler
will not show as an empty box.
Change-Id: I990e43fb0e950f6085f9d17d30129327993a72ac
> browser: initialize layout hidden for ruler control

- browser/css/color-palette.css
- browser/css/jsdialogs.css
- browser/css/jssidebar.css
- browser/css/menubar.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
there are 3 color var's added
var(--color-main-text)
this is the default text color EVERYWHERE
var(--color-text-accent)
will be used when a label was selected, or during hover
also for the filename accent text color was used
var(--color-text-lighter)
was use for saved date or when a label was disabled
PR was tested for classic and notebookbar
for the sidebar and dropdown elements.
Change-Id: I21795875e58b956081f2020422e77ccecd9bfba3
> Use variables for text colors

- browser/src/layer/tile/CalcTileLayer.js
it only checks the cellPos and this can cause
modifying the existing comment when we try to add
a new one if the same cell has a comment in another
tab already.
Change-Id: I69fd607b487fe18c9a48420b7df202b7d3db311d
* Resolves: # 
> calc: Fix new comments do not check tabid on insert

- wsd/COOLWSD.cpp
For example, to skip exporting the first page of a document:
curl -k -F "data=@3page.odg" -F "format=pdf" -F "options={\"PageRange\":{\"type\":\"string\",\"value\":\"2-\"}}" https://localhost:9980/cool/convert-to > out.pdf
https://gerrit.libreoffice.org/c/core/+/128849 has more examples.
Change-Id: I6c4ce25bc580dac041f2865f74c856780d6fe137
> wsd, convert-to: allow specifying filter options as JSON

- loleaflet/js/global.js
Paranoia in case a back-port causes an unexpected exception.
Change-Id: Ic3d287618cb1e035cd17597f8d336d5f698a8014
* Resolves: # 
> compatibility with master's new window.app.console logging.

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/plugins/selectorList.js
- cypress_test/plugins/whitelists.js
- loleaflet/src/control/Control.TopToolbar.js
- wsd/DocumentBroker.cpp
When the storage returns modified-in-storage or conflict status
to an upload attempt, we prompt the user to handle the conflict
when the document is modified. Previously, we only prompted
when we had the modified flag set, ignoring the possibility of
having a race with the modified flag, in case the document was
just modified, or potentially modified.
We now prompt the user even when the document is potentially
modified, giving the user the opportunity to decide what to do.
Change-Id: I699aaed92d41f76a8eb9de6bdb65608099802663
> wsd: consider possibly-modified docs when handling conflicts (backport)

- browser/js/global.js
- browser/src/control/Control.AlertDialog.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Clipboard.js
- browser/src/map/handler/Map.FileInserter.js
- browser/src/map/handler/Map.SlideShow.js
Change-Id: If83611cc17d00dd049093de0a35caa7739f10400
* Resolves: #4066
This commits adds a function call to `window.processCoolUrl` if that function is present each time it encounters an URL (internal for backend calls to Cool or inside a document, user generated). The function take an object that contains the `url` (string) and the `type` (string) of the url. 
The `type` can be one of the following:
- 'ws' (websocket url)
- 'doc' (hyperlinks in documents, processed as the user clicks on 'open link')
- 'print' (basically the same as 'export' to pdf)
- 'export' ('download as' in various formats),
- 'clipboard' (backend request when the user pastes into the document)
- 'insertfile' (when inserting a …
> browser: add optional function to process the URLs (internal and user generated)

- browser/css/menubar.css
if you hover over the last-mod string the color switch from
var(--color-text-lighter) to var(--color-text-accent).
In addition the text-decoration: underline was removed
cause it use text-lighter the focus shouldn't be there
with an underline.
Change-Id: I750981730b6daa8605f8d70ebd3df4029f990e36
> last-mod string removed underline and add hover accent color

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
In the layout tab there are the object related stuff like
align and front/back. So I add there SelectAll command.
Change-Id: I4cdd9fbb0351cede9cd78dd1edd50e0612d895f0
see https://github.com/nextcloud/richdocuments/issues/1976 moved command from the hamburger menu to the tab.
> NB add SelectAll command to Layout tab

- browser/css/menubar.css
If you hover at the classic toolbar at the menubar,
a border was shown and the string jump at 1px size.
Change-Id: I5d03a380c2bfa34bd169bb12295d535875e54a5f
> Classic Toolbar Menubar no juming up at hover menu element

- browser/src/control/Control.StatusBar.js
Make sure the toggle also reacts not only to the user interaction¹ but
also at the startup time
1 Which is already done with:
- e384c561798e7616f10e763788e92acec6caff9c
- from PR: https://github.com/CollaboraOnline/online/pull/4088/
Change-Id: I29e401eede4fc11c821da91b66430ba99d1ec1aa
> Notebookbar: Set statusbar toggle's status on loading

- browser/src/control/Control.NotebookbarWriter.js
Without this change items related with document layout and
interface view were mixed together within the same "layout" tab. This
makes it harder to scan and find the desired action.
- Split Document layout commands and interface commands by creating a
new tab.
Change-Id: I625bb48a6c135d390f595511ddc8639ea5bdd2a8
> Notebookbar: Writer: move interface actions to view tab

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
- Make sure a trigger is fired no matter the UI mode
- Handle it (do anything) just from withing the NB widget
(get proper css classes)
Note: similar to what we did with statusbar in:
e384c561798e7616f10e763788e92acec6caff9c
Change-Id: I6c8a38f2e426f20cc5b7a06241f7a92fa4d938e4
> Notebookbar: Set ruler toggle to react to visibility

- browser/src/control/Control.Sidebar.js
To be safe, we can ignore the idea of this.map.isPermissionReadOnly()
control would always return true for PDF views and add
additional check for app.file.fileBasedView which is always
true and readonly true for PDF view
Change-Id: I8f0a4401087c735508534404ee987bb35c3bb0fd
* Resolves: # 
> sidebar: Don't show sidebar on pdf regardless of the permisson

- loleaflet/src/layer/tile/TileLayer.js
Avoid doubled PNG generation when graphic is selected.
We only need 'rendershapeselection' request to get preview.
'gettextselection' will only setup '_selectionContent' in
the Clipboard code but it will be never used as
`_getHtmlForClipboard` will ignore it for complex selection
with graphic.
> Do not request unnecessary image on selection

- browser/css/color-palette.css
there are 4 type of color sections:
1. text
2. background
3. border
4. primary
and for each section there are
1. without extension for default color usage
2. -dark suffix for selected
3. -darker suffix for hover
4. -lighter for non available
with this setting the developer can choose
easy the section and the -suffix.
In addition there is primary color
which bring color the the apps and should depend
on the app so
- writer = LibO brand color blue,
- calc = LibO brand color green,
- ...
Change-Id: I668b5505abd5d70345221bc79d921071c4a49cd7
* Resolves: #3772
> Variable names for the color-palette

- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
- browser/src/core/Socket.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/map/handler/Map.StateChanges.js
- kit/ChildSession.cpp
- kit/KitHelper.hpp
after switching to master view previews would remain unchanged
this patch will invalidate tiles for all the previews
Change-Id: Ie7320d625bd95fe80fc76a459b576d6148b39276
* Resolves: # 
> fixed master slide previews not being updated

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Path.Transform.js
- loleaflet/src/layer/vector/SVGGroup.js
- fixes error sometimes shown in the console
- fixes preview update - before it was leaving empty rectangle when new preview arrived during rotation
(for more info how to reproduce see the commit message)
> Image operations fixes (co-6-4)

- browser/src/layer/tile/CanvasTileLayer.js
The expected shortcuts are documented in
https://support.apple.com/en-us/HT201236 . This patch handles a small
subset of those:
Command–Up Arrow: Move the insertion point to the beginning of the
document.
Command–Down Arrow: Move the insertion point to the end of the
document.
Command–Left Arrow: Move the insertion point to the beginning of the
current line.
Command–Right Arrow: Move the insertion point to the end of the
current line.
Option–Left Arrow: Move the insertion point to the beginning of the
previous word.
Option–Right Arrow: This should move the insertion point to the end of
the next word. But I don't think LO has such a shortcut so we move to
the beginning of the next word instead.
Change-Id: …
> Make some shortcuts on Mac clients match expectations better

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
We no store the origina modified time of the document
as we receive from the storage server in string
form and send it back as-is. This avoids any
potential issues with the roundtrip of conversion
to and from a timestamp.
Change-Id: I524bea8f36c3ce62dcd00c4fe6a1e7e083287ed1
> wsd: preserve the original modified time as string

- android/lib/src/main/cpp/CMakeLists.txt.in
- wsd/Exceptions.hpp
CMakeLists.txt lacks recently added Exceptions.cpp
file and also needed <string> header in Exceptions.hpp
Change-Id: I183cc9d71e3f98e63d2a0d0b79229b8311bfd611
* Resolves: # 
> fix android build failure

- Makefile.am
- test/Makefile.am
- test/UnitWOPIDocumentConflict.cpp
- test/UnitWOPISaveOnExit.cpp
- test/WOPIUploadConflictCommon.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd: wait for the modified flag before giving up 
- wsd: improved removeSession
- wsd: do not force uploading when in conflict
- wsd: detect storage conflict with no clients
- wsd: reuse autoSaveAndStop for consistentcy
- wsd: merge unloading logic and centralize
- wsd: test: rework and extend UnitWOPIDocumentConflict
- wsd: test: add discarding after closing test to DocumentConflict
- wsd: test: add SaveOnExit test
> Detect storage conflict with no clients

- browser/css/jssidebar.css
In the Writer Sidebar when the user insert an table, 
the table edit panel was shown.
As flex-end isn't needed for this panel, 
`display: inheret;` was used
Change-Id: I5238c6efda7d58d8eb7612eb91329ac9b45d11db
> Sidebar Writer Table Edit Panel

- browser/css/jssidebar.css
The cell Appearance in calc sidebar show the following commands:
- background color
- border arrange with border width
- border color
in master there is a lot of vertical space used
without additional feature
so the height was shrinked to one row only
Change-Id: I0831995ccfc18bc6625304d8faeb65fae0fea9f2
> Sidebar Calc Cell Appearance smaler height usage

- browser/css/notebookbar.css
use correct var's inkl. border-radius
remove not used css definitions
Change-Id: Iaad11a5ace1bdc1c2fccc2ea9f1ef6828e8442af
> Notebookbar Font style selector update

- browser/css/cool.css
The sidebar background color was replaced to
var(--color-main-background)
cause otherwise we don't have the same contrast
than for the toolbar / notebookbar
Change-Id: Ic6b1229f958479ef3abe9dd5b00991f0c2784a5b
> Sidebar background color

- browser/css/jsdialogs.css
The dropdown elements show an left-border and background color
when hover over an dropdown element arrow in the sidebar
this color was replaced with transparant
As the arrow is an border element, the arrow use
the text color and has an hover effect.
Arrow follow Text color
Change-Id: I890121a25408789472d7591edf1a4277d0823c4e
> Drowdown arrow without inline border and with hover effect

- browser/css/menubar.css
Menubar use transparent background color,
so the menubar use the color of the toolbar
In read only mode the bottom-border use --color-border var
Change-Id: I0f5b612cc2af7f10e62442b3568778be2ce4e52f
> Menubar use transparent background and correct border color

- browser/css/color-palette.css
- browser/css/toolbar.css
In status-readonly-mode the element on the down toolbar
use --color-warning background color and --border-radius
Change-Id: I55782f5632f55f5923d53ec9a03628e048fa45da
> Toolbar color update

- browser/css/mobilewizard.css
there is a light text effect on mobile for commands
that aren't available (disabled) which work fine
but the additional gray background and border color
is not easy to recognize
and it cause visual issues on desktops
general everywhere in cool lighter text mean not available,
so no additional stuff is needed.
Change-Id: I5315e1d6a84ae3caf037ec7ab4c1ab81dcfbe44d
> mobilewizard input checkbox disabled no gray background

- browser/css/cool.css
- browser/css/impress-mobile.css
- browser/css/impress.css
- browser/css/jssidebar.css
- browser/css/toolbar.css
The sidebar width is 330px and not 322px.
330px is the default width with 322px the sidebar width is smaler
than needed which causes issues of symetry AND issues when
there is an additional scrallbar needed.
Top borders at the sidebar's were removed
cause there is already an border at the top toolbar.
Change-Id: I6c53132b273a2b83fd89c58778577e1b47cda125
> sidebar width is 330px and duplicate borders removed

- browser/js/global.js
Change-Id: Id4aa67e98779dd0d5c92172425baa753fcaca27c
* Resolves: relates to #3883 
The `.error()` method was missing from the logging ones, so `window.app.console.error()` would not work.
> browser: add missing error method for logging

- browser/src/layer/tile/CommentListSection.ts
core sends same id for copy comments and this breaks the
existing implementation because sections are named based on the id.
Change-Id: Ia410227b7a42ac8ea7682f12aa980b34ee5c940b
* Resolves: # 
> fix copy comments breaking the canvassection completely

- browser/images/lc_hamburger.svg
icon
- hamburger menu use --color-main-text
- so all stuff in the header area use the same color
Change-Id: Id3361c0f58d5ce12bd1d312bd7aa303fe2071282
follow up to #4200
> Hamburger icon update

- browser/css/notebookbar.css
Notebookbar
-   Updated save and burger menu in the
shortcuts-bar color follow --color-main-text
- savemodified use var color and modifier was added to save
icon in the file tab
Change-Id: If12b9cf5e294982298c4ef392eeac9e12d0ef800
follow up to #4200
> Notebookbar shortcutbar layout update

- browser/css/device-mobile.css
improvement upon d9e766c19af1d0236cb4065daa53ff9c30b3ba4c
- On calc we need that border since we have the formula bar component
Change-Id: I7d4c255654bf570a2fa4ac11a9df978f36f22971
> Remove border color from #toolbar-up on mobile except calc

- browser/src/map/handler/Map.Mouse.js
Not sure why the browser doesn't do it automatically. Ctrl-left-click
works on normal webpages just fine, it is equivalent to a tap with two
fingers on a trackpad. (Which, I think, is what Mac users most often
use. That is equivalent to a right-click.)
Change-Id: I1f0daf0929b41e25a58456bd995f1463c873c42c
* Resolves: # 
> Turn ctrl-left-click into right-click for browsers on macOS

- browser/js/global.js
- browser/src/control/Control.Sidebar.js
- browser/src/core/Socket.js
it appears that sidebar callback can arrive before
docloaded message when it is already loaded in the background
Also app.file.fileBasedView parameter is set after docloaded
so it wasnt a correct fix. perm: message arrives before document
initialization and we can hide sidebar unless the arrived messsage is
not 'edit'. if the user have edit mode, it will be up to the users preference
Change-Id: Ifb220d8bb8baad0078bcd32f71ee6853d31adfb8
* Resolves: # 
> fix sidebar can be visible on pdf

- kit/Kit.cpp
This avoids an endless spinner for the loading mobile app in this case.
Change-Id: I047797cbdb066a236afc40337d2eba08f9c0c84b
* Resolves: # 
> Send error on failed load and/or exception during document load

- browser/css/toolbar.css
Change-Id: I5cc8e47148df5b5a68fed75d4b0298ee930b7792
arrows in the screenshot get `--color-main-text`
> Toolbar Dropdown Widget arrow use --color-main-text

- browser/css/jssidebar.css
the borders are ordinary 1px so it was update for
jsdialog.cell.sidebar to be also 1px border size.
Change-Id: Ie85a82fecd608edd25d5c3314e70a8b91c0a31bb
> Sidebar select and hover 1px border as everywhere

- browser/css/toolbar.css
the border-radius was needed at .select2.container--default and
.select2.selection--single and __rendered to have nice borders
Change-Id: I6ae386d65f45c49f221a3c987b101132eb4d56c7
> CSS Var: fix for toolbar dropdown menu border radius

- common/JailUtil.cpp
- tools/mount.cpp
COOL uses `mknod()` system call to create `/dev/random` and `/dev/urandom` devices. On FreeBSD this does create a special file, but it doesn't function as proper random device. The correct way to do this is to mount a special filesystem called `devfs`.
This patch teaches `coolmount` to perform `devfs` mounts and changes COOLWSD to use that when running on FreeBSD. It also fixes the cleanup procedure to not leave dangling `devfs` mounts after the daemon shutdown.
> mount /dev via devfs on FreeBSD

- browser/css/jssidebar.css
when you insert an table there is in the sidebar paragraph section
alignment horizontal LtR RtL and alignment vertical
overall there are 9 command
which are to much for the sidebar width
therefore if there is alignment-vertical available,
it was moved to the next row with display: table-row
as the new command for writer work also for impress and draw
the setting for impress/draw only was removed
for prefext alignment padding: 2px was added
Change-Id: Ic030cab180921e238c44a4fb62962e69542beee5
* Resolves: #3805 
> Sidebar Table Paragraph vertical alignment commands next row

- browser/css/cool.css
menubar padding: 3px 3px 3px 0;
so toolbar padding: 3px 0; similar to what menubar use
harmonize padding. Fit's also well when menubar was shrinked.
Change-Id: Iaced9d5a647267139eca26daa4793e83732f969e
> Toolbar padding similar to menubar padding

- browser/css/toolbar.css
color selector use css var's.
- border-radius
- outline use --color-main-background
Change-Id: Ic6187da6230e67025c670b596134766bf9a0c899
No visual change but it use the css var's
> CSS Var's update for color selector

- browser/src/control/Control.UIManager.js
This allows simpler targeting of different ui modes (classic/notebookbar) through css by adding the currently applied mode to the body element as a data-userinterfacemode attribute.
e.g.:
```
body[data-userinterfacemode="classic"] {
.some-css { ... }
}
body[data-userinterfacemode="notebookbar"] {
.some-css { ... }
}
```
@pedropintosilva What do you think about this? I think this could make styling easier to target and be more structured.
> Add ui mode to body for easier styling rules

- browser/src/control/Control.MobileWizard.js
Similar to 4764937ad44a5cca99a7d5b962e661f491d18cb1
* Resolves: #4264
Should avoid issues like
```
Uncaught TypeError: app.sectionContainer.getSectionWithName(...) is null
_hideWizard https://coolwsd.xxx.org/browser/e4d06c2/bundle.js:1
[bundle.js:1:2264150](https://coolwsd.framasoft.org/browser/e4d06c2/bundle.js)
_hideWizard https://coolwsd.xxx.org/browser/e4d06c2/bundle.js:1
_hideWizard self-hosted:1184
```
> Fix app.sectionContainer being null

- browser/src/control/Control.JSDialogBuilder.js
Contributes to the temporary solution of https://github.com/CollaboraOnline/online/issues/1285#issuecomment-824547942 by applying the removal of potentially existing ellipsis on a wider range by performing this cleanup in the JSDialogBuilder.
I could imagine that this also has an effect on other jsdialog based components, however I could not see any noticeable impact on the sidebar for example.
What do you think about that approach @pedropintosilva @Andreas-Kainz
> Notebookbar: Remove ellipsis from generated uno button labels

- browser/css/menubar.css
Now that both classic and notebookbar mode have the document header
without background color and effects, we can safely remove the initial
margin that is not needed anymore
Change-Id: Id3f653c42d6099753bc852ac75f454698b6ffdc2
> Document header: remove unnecessary margin

- browser/css/color-palette.css
- browser/css/cool.css
- browser/css/impress.css
- browser/css/jssidebar.css
- browser/css/leaflet.css
- browser/css/menubar.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
- color-main-background LibO document background was used
- color-main-backgroud was used for all elements
- only select, hover and toolbar's use other background colors
- color-background-lighter is the color for toolbars
- better contrast for select stuff
Change-Id: I1e8be68aa1f6e73fb03994dac0ad634725e2aef0
> color-palette UI elements update

- browser/css/jssidebar.css
spinfield and dropdown widget have the same width
(when possible) so there is no jumping widget alignment
Change-Id: I0148295285a4174464de5ccea6bfa11a387de9a6
* Resolves: #4260
> spinfield and dropdown widget use the same width

- browser/src/layer/vector/SVGGroup.js
> fix wrongly sized shape selection overlay

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
closes #4230
Change-Id: Ibcc0a3c8bb17dc78775362bc4fd61601d186e822
* Resolves: #4230 
Added a new `source` param to the `postMessage` API for `UI_Save`, so that it can be differentiated between saving from keyboard, file menu or toolbar.
> browser: enhance postMessage for UI_Save

- browser/images/lc_accessibilitycheck.svg
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/unocommands.js
* Resolves: # 
Exposes the accessibility checker used in LO writer and core for use in COOL Writer.
Can be accessed in Notebookbar under review and also the hamburger drop down in the top left under tools>accessibility check.
Also added in the menubar, but I don't see this anywhere in the actual UI- possibly not used not sure?
Note I just used the svg for the a11y logo from [their website](https://www.a11yproject.com/) and changed the color, don't know if we want this to be something else
> Expose a11y check online

- browser/css/notebookbar.css
Context:
With the f4cde4a18c8a402f5028971987193a2b28aa3d69 there is no visual
delimiter between the icon and the indicator which results in lack of
contrast.
- Add back shadow and tweak it so we do have better contrast between
them
- Also tweak indicators' position so it's aligned to the top and so it
feels more like an indicator (notifying the user)
Change-Id: I2ff6e00383a7ad7305680c92b587fc1b6890a886
> NB: Fix Save savemodified indicators' contrast

- browser/src/control/Control.JSDialogBuilder.js
problem:
locking a command which has uno button on the sidebar,
would result in locking all the DOM siblings
Change-Id: I0e97ecd52e0be1fe262f8f9605c253c76f3d0a86
> fixed feature locking on the sidebar

- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd: stop if unloading and have no sessions to upload
- wsd: send the client 'docunloading' for all unloading cases
- wsd: do not clobber closeReason
- wsd: do not skip uploading when last save skipped
- wsd: faster save and exit when unloading
> Improved Save and Upload corner-case handling

- browser/css/notebookbar.css
Re-align indicator and make sure indicator has white space
around it (on top of the save icon) so to increase its
readability
Change-Id: Ieaf4258c3dc594aa47904a1066deaee11417053d
> NB: File tab: Fix savemodified indicator

- kit/ChildSession.cpp
- kit/ChildSession.hpp
The buffer and length parameters were unused in methods in ChildSession.
Signed-off-by: Kristopher Maxwell <kristophermaxwellc@gmail.com>
Change-Id: I6aff3c92a5d787db84bbe64aa13f2f0160340f7f
* Resolves: #3937 
> Remove unused parameters in ChildSession

- browser/css/jsdialogs.css
Content parent was being set with shadow while the main parent element
also has shadow
Change-Id: I4f8f13f579e5b1205433801e95cc482c63f1fcc7
> JSDialog: remove duplicated shadow

- browser/css/jssidebar.css
- browser/src/control/Control.UIManager.js
We can hid the whole container and avoid the background of that
container to be visible (when collpased)
- This was useful in the before when the tabs were visually "connected"
to the content
- Also it was done like that before to give a "clue" to the user that
something is there and can be expanded but probably by now it's not
needed and if the user actively collpased them then he/she would know
how to expand them
Change-Id: Ib586f4aa3e83e650276b25c2ac13d45f475816e3
> NB: collpasing tabs: hide container instead of child

- wsd/COOLWSD.cpp
Change-Id: I8b71d4e5a06e2c0a7fcd7dedc370cc4810a204fd
* Resolves: # 
> Don't require https when ENABLE_DEBUG for the remote config thing

- cypress_test/run_parallel.sh
Signed-off-by: Bayram Çiçek <bayram.cicek@libreoffice.org>
Change-Id: I781070c32d89c329effbc233cf356fe983b85c1e
* Resolves: #2720
- `cd cypress_test && make` is equal to `make -C cypress_test`
-  current directory will remain unchanged with `make -C`.
> Use make's -C argument instead of cd in cypress_test/run_parallel.sh

- browser/src/map/Map.js
Steps to reproduce the issue:
1. Set per_document / idle_timeout_secs to something small, like 30,
2. Open a spreadsheet with various row heights,
3. Wait until you idle out of the session,
4. Open the same file from another browser tab/window, add an empty row near the top, then close it,
5. Wait a little bit (let's say ~5s), and click into the original session, then select various cells.
-> Note how the selection is misaligned.
Root cause:
When a session becomes idle (at least for the current use-case) the
corresponding lok-view is terminated and when the js-view is resumed a
new lok view is created! In this case there is no one to one
correspondence between a js-view and lok-view. So there is no
remembering of events or replaying of events.
Fix:
Ask for sheetgeometry whenever the …
> calc: misaligned selection if sheet geometry changed while idle

- browser/css/notebookbar.css
Make sure gray background or any bg for that matter is used on hover
- It shouldn't be used because each style is an image with white bg
Decrease hover status prominence so it's still visible which style is
selected
Also do not add hover status for the selected style, as clicking on it
would not change the selected style
Change-Id: Ie66abada24a7c6491987d9052dc94bba920d5a7f
> NB: stylesview: fix hover bg and shadows

- cypress_test/README
Signed-off-by: Bayram Çiçek <bayram.cicek@libreoffice.org>
Change-Id: I2c03535d5f27cffeffc75a0f101d0280cc6e50ae
* Resolves: # 
- after changes in #4304, two uses of `cd cypress_test && make` replaced with `make -C cypress_test` in `cypress_test/README`.
> update cypress_test/README and use make's -C argument

- test/helpers.hpp
- test/httpwstest.cpp
Change-Id: I2f1c39d03d61ef2074fe6e946a79fc2f07ffd27b
* Resolves: # 
> Unit test for &lang=es-419 style code, disliked by boost gettext.

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
Sidebar section header use
- header-font-size
- header-height
Sidebar section labels use
- default-font-size
- default-height
see #4305 
Change-Id: I6011b686a5d72159b87db0f70c99d14001d73356
> Sidebar Global Layout update

- browser/src/control/Control.AutofilterDropdown.js
- browser/src/control/Control.JSDialogBuilder.js
core is adjusted to send offset for autofilter popup
related to gridwindow (spreadsheet area) instead of
absolute screen coordinates - what helps to simplify
code.
requires: https://gerrit.libreoffice.org/c/core/+/130528
> autofilter: use gridwindow instead of screen offset

- browser/css/cool.css
Avatar images was not aligned to its parent element and looked like it
was out of that parent "circle". A box size property was getting inherit
from generic vex style sheet
-Make sure the box size of the parent avatar image:
.cool-annotation-img is calculated with the width of any border or
padding added to the final rendered width, making the element wider
than 32px.
Change-Id: Ia32c06fd6dea23feb431c2afbe9cdb591063a732
> Fix insert comment dialog's avatar size

- wsd/LOOLWSD.cpp
The static instances cause a lot of grief
when they aren't called in the correct order.
Worse, when we are cleaning up, we don't
even initialize some of them (Admin, for one).
This means that a normal exit will destroy
what isn't created, in some cases (Admin) it
will even force creating instances when we
are destroying others.
This avoid all this by simply exiting bluntly.
Change-Id: I6a9443ca5ab999ed6ca1d27314136472cfc6ddb6
> wsd: forced exit after cleaning up jails

- browser/src/control/Control.AutofilterDropdown.js
fixes bug:
- open autofilter popup
- click somewhere outside to close it
- try to type something using keyboard to the cell
result: popup closed but cannot type, no jsdialog message about
autofilter close in the browser console
button is not a valid type in jsdialog executor:
vcl/jsdialog/executor.cxx
> autofilter: fix closing on out-of-popup click

- browser/src/layer/tile/CanvasTileLayer.js
Dark overlays like any other overlay need regular document coordinates.
But in calc-rtl mode, charts (like shapes) have negative x document
coordinate internal representation.
Before this fix, the CDarkOverlay used to get negative x coordinates
hence the positions of the four dark rectangles were wrong.
Change-Id: Iea3202e2a0c0594cd8f894ee96123a0281cf2f38
* Resolves: # 
> calcRTL: dark-overlay incorrectly covers the chart

- browser/css/color-palette.css
- browser/css/override-vex.css
- browser/css/welcome.css
- Make sure overlay stays an overlay and not a solid opaque color
- Make sure dialogs' background is white and not gray
- Since they appear above the content they shouldn't be darker
- Also make sure Welcome dialog is not gray
related:
6f2be29ab7df147dcdabf0a0c3b3059af952c3f5
4a5b3b6465646802c0be5403d8a6a561961c7df9
08a500e938cef836e777952ec849bcfd5926a0a4
Change-Id: I4fbaa3f79f7fb1c348b5fe0ef87e98f9007ce007
> JS Dialogs: Fix regressions background and overlay color

- kit/Kit.cpp
- test/UnitPasswordProtected.cpp
* Resolves: # 
Reproduction:
Opening a password protected document gives an error corresponding to
'faileddocloading' and then a blank file is displayed.
Fix:
Since 0b76383346887fa6fbf732e680a79a8d5e38411b, when Document::load()
fails without any exception, onLoad() sends
"error: cmd=load kind=faileddocloading"
to the client. This is a problem when load() fails just because the
client did not provide password for a password protected document.
Besides for all "exception free cases" load() already sends the correct
error message(s) to the client. So this patch also avoids sending
duplicate error messages.
This PR also adds a check for this case in the relevant unit test.
> Can't open password-protected files

- browser/src/layer/marker/Cursor.ts
When an image is inserted, the cursor is not shown.
Change-Id: Iea305a9a666bf06c68e7407eac3252f7faab627a
> browser: fix to show cursor blinking

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
this patch not only fixes the issue in the title
also fixes similar problems such as lets say the
browser page is not maximized and then it is decided
to be maximized. This operation normally does trigger redrawing
but it only draws tiles that are in the cache already and does not
trigger tile invalidation and cells can stay empty until something
retriggers tile invalidation again
Change-Id: I5981aa36c77a87626809c92e72e1cd6263826953
* Resolves: # 
> calc: fix cells become empty after closing sidebar

- coolwsd.xml.in
- test/Makefile.am
- wsd/COOLWSD.cpp
- wsd/RequestDetails.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
This allows us to use multiple hosts using same coolwsd instance.
added aliases configuration to coolwsd.xml to avoid
possibility of opening the same file as two if the
WOPI host is accessed using different aliases
Change-Id: I32913015c15fd396cecc702b76e0dcaa8bcafad3
* Resolves: # 
> wsd: use hostname, port and scheme in doc key

- common/Common.hpp
- common/Unit.cpp
- configure.ac
- coolwsd.xml.in
- kit/ForKit.cpp
- net/Socket.hpp
- net/SslSocket.hpp
- wsd/COOLWSD.cpp
While SSL is handshaking, there can be no general
application data communication. During that early
stage of connecting we have data to send (the
request, headers, etc.) and so we poll on POLLOUT.
Naturally, we also always want to poll on POLLIN,
because we can never know when there is data to
read (especially true for web-sockets).
The problem is when SSL will not send data just
yet because it is handshaking. It is typically
waiting for handshake negotiation data to read,
so when we POLLOUT, poll immediately returns, but
writing (via SSL_write) fails with WANTS_READ
error. This goes on in a busy-loop until the
negotiation data is available for read and the
handshake is completed. Very inefficient.
The solution is to poll on whatever SSL needs
during the handshake, exclusively. Once the …
> wsd: reduce polling when blocked on ssl handshake

- wsd/RequestDetails.cpp
- wsd/Storage.cpp
==30332==ERROR: AddressSanitizer: odr-violation (0x0000020b9b20):
[1] size=1 'StorageBase::SSLAsScheme' ../wsd/Storage.cpp:67:19
[2] size=1 'StorageBase::SSLAsScheme' wsd/Storage.cpp:67:19
These globals were registered at these points:
[1]:
#0 0x71d0f8 in __asan_register_globals.part.13 lode/packages/llvm-llvmorg-9.0.1.src/compiler-rt/lib/asan/asan_globals.cc:362
#1 0x7f4c362ed33b in asan.module_ctor (online-san/test/../test/.libs/unit-base.so+0x10eb33b)
[2]:
#0 0x71d0f8 in __asan_register_globals.part.13 lode/packages/llvm-llvmorg-9.0.1.src/compiler-rt/lib/asan/asan_globals.cc:362
#1 0x11c709e in asan.module_ctor (online-san/coolwsd+0x11c709e)
==30332==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
SUMMARY: AddressSanitizer: odr-violation: …
> sanitizers: fix unit-base

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I1b3cfefdd6abb7f81ff741eee4edab7e349c932d
fixed regression caused by https://github.com/CollaboraOnline/online/commit/1c86fd2ff869d36156bb97b3f44fc0cf7fec037c
regression: while we move textbox in impress previews would not go away
> image operation: make sure embedded svgs are shown in writer only

- browser/src/control/Control.TopToolbar.js
Breaks were removed in commit df925222a2c4ce94024b8df7eeb0d014e2d82271
Signed-off-by: Kristopher Maxwell <kristophermaxwellc@gmail.com>
Change-Id: I376207d654ccbe98fc1d1b4b84363748190ab646
* Resolves: # 3184
> Add back removed breaks from TopToolbar, see #3184

- loleaflet/src/layer/vector/SVGGroup.js
The svg sent from core does not exactly match the corresponding contents
in tile of the shape - especially the legend texts. This commit does not
attempt to fix that.
Before the commit e64ff372fc54e42fb1337ac3b76200c021018c96, the svg
embedded image was always hidden when a shape/chart/ole is merely
selected and it is only shown while the shape is being resized or moved.
Because of the strict inequality used with getAttribute('opacity') this
condition is always true at least in Chrome as getAttribute() returns a
string.  Comparing the parsed integer version of that results in the
intended behaviour and also hides the svg preview when chart/shape is
not dragged or resized.
Change-Id: I0aef873e392b0959e93057e6399e8f77cf70042c …
> calcRTL: chart selection's svg does not match the tile

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Sidebar.js
In some cases we add 'table-' prefix for toolboxes due to
some old requirements in the mobile-wizard. We need to find these
modified ids in a fallback on widget update.
In the future we should get rid of 'table-' prefix.
This fixes missing numbering/bullets items in the impress sidebar
> jsdialog: find also controls with modified id

- Makefile.am
- browser/src/map/handler/Map.Keyboard.js
- common/StringVector.hpp
- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/SslSocket.hpp
- net/WebSocketHandler.hpp
- test/lokassert.hpp
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
- browser: protect against undefined keyEventFn
- wsd: always include the BIO errors in SSL logs
- wsd: trace poll events and revents flags arround ppoll
- wsd: test: correctly show the failing code in the assertion message
- wsd: minor improvements to StringVector::equals overloads
- wsd: exclude deprecated openssl API
> SSL logging and other improvements

- browser/src/control/Control.Toolbar.js
we send the slideshow buttons reference to onClick function
in that item.disabled is false but later we reassign it from
w2ui get function and then it becomes disabled true on readonlymode
The logic is incorrect because onClick function does not respect
wheter the item is passed or not and tries to reassign it anyway.
Change-Id: I025e26c455a7673a002f894f49452b360550b178
* Resolves: # 
> mobile: fix fullscreen-presentation does not work on readonly mode

- browser/src/control/Control.TopToolbar.js
This is important because we in many places might want to still have the
respective element's space but without actually showing it.
Example: divider's space without that being represented by a bezel
Change-Id: Ib58cc9564144c4ad48fa240878a3654add5d4d03
> Allow items to be shown invisible on the TopToolbar

- Makefile.am
Apparently this breaks the build on at least
CentOS. Reverting for now.
This reverts commit 23f02b89294bd03b5add402d097df62d9651b0c8.
> Revert "wsd: exclude deprecated openssl API"

- browser/css/cool.css
- Partly revert 7e705fcf09cd30159d0703fbfbe5a89dce1f2e82
- RGB expects rgb values. Hex annotation does not work: renders it
transparent
- Avoid low contrast between font and background (white with light bg)
- Use instead primary color
Change-Id: Iad24d6bf30d2e62505254c70b174e9b9971cbeb1
> Fix comment reply count color

- browser/src/control/Control.JSDialogBuilder.js
- add possibility to specify name alias for icons that are
generated via jsbuilder (sidebar, notebookbar). The goal here is to
avoid having multiple duplicated icons with different names:
Example: 2 identical SVG files were being used just because of their
name.
Context: When unifying icons between sidebar and toolbar PR #4426 ,
9576137df51725b677342c606dcad8749eaf0622 we end up with icons without
images on:
- Calc: Notebookbar
- Calc: Sidebar
This happens because even though we want to use the same icons the uno
commands are actually different from ones used in writer and elsewhere
(uno.AlignLeft <> uno.LeftPara)
Note: Since the sidebar uno.commands come from core we really need to
use icon url alias. If that was not the case we could have used here the
newest compatibilityAliases …
> Fix missing icons by creating iconURL aliases

- browser/src/layer/tile/CommentListSection.ts
modify and reply causes relayouting due to expansion of the
commentsections but it is based on whether they are selected or not
currently. If they are already selected we dont relayout them again
and it causes overlapping. To avoid that we can simply unselect
comments just before reply or modify.
Change-Id: Ifc2e546504b36b46f98a9b22ce791b4279239457
* Resolves: # 
> annotation: fix layouting problem on selected comments

- kit/Kit.cpp
Change-Id: I7e768416b5113d71330148227aeceb941013c578
* Resolves: # 
> nftw() does not set errno on failure

- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
- browser/src/layer/tile/CanvasTileLayer.js
Fixes problem with:
- showing wrong slide number in statusbar
- inserting comment at correct page
in pdfs where we see slides in continuous mode.
Sending slide id from online to server is much easier
than calculating based on visible area on the server
where we have to put that data into TabControl widget
which is used in different places.
It updates visible slide on scroll and also when selected
from the previews bar.
> Notify server about visible slide

- net/Socket.hpp
- net/SslSocket.hpp
While chasing #4480, I was able to produce `handshake failure` error that this patch resolved.
```
#26 SSL error: SSL (1) BIO error: 336151568, rc: -1: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:| ./net/SslSocket.hpp:345                                                                                                                                              
#26 Error while handling poll at 0 in HttpSynReqPoll: #26: socket closed unexpectedly. BIO error: 0, rc: -1: error:00000000:lib(0):func(0):reason(0):| net/Socket.cpp:466                
```
Since the hostname argument is passed
to both the base class of SslStreamSocket
and SSL_set_tlsext_host_name, and since
the base class's getter, also called
hostname(), is hidden by the argument,
we cannot move it. …
> wsd: hostname is needed for SSL SNI

- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Follow the same order as anywhere else such as annotations, JSdialog or
even tunneled dialogs:
primary action aligned to the left
Change-Id: Iac209aa343f22ddfdbd5662eba43d7adaa3f0892
> Fix button order on HyperlinkDialog

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/WriterTileLayer.js
fix typo on clearList loop that prevents skipping trackchange
comments from being deleted
Also I removed the line in WriterTileLayer.js containing
clearList because clearList is already called on importComments
function so it was unnecessary
Change-Id: Ic4086a80b126aec62e382078f53d68bc17da8a1c
* Resolves: # 
> fix trackchange comments are not displayed on docload

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- now widgets are accessible using tab key
- can close all dialogs with ESC key
> jsdialog: a11y: make widgets focusable fixes #2965

- browser/src/control/Control.NotebookbarCalc.js
With the reorganization of Calc tabs:
584e139bbdfd1870c15cb5ad141ee15421e9aefc both Define and Manage names
disappear form the notebookbar. Add it back following the same new
organization.
Change-Id: I06740e225090407117e8b5a6aff54b476368e358
> Calc Notebookbar: Add missing Define and Manage Names

- test/Makefile.am
- wsd/RequestDetails.cpp
==4544==ERROR: AddressSanitizer: odr-violation (0x000002c40140):
[1] size=104 'HostUtil::WopiHosts' ../wsd/HostUtil.cpp:12:34
[2] size=104 'HostUtil::WopiHosts' wsd/HostUtil.cpp:12:34
These globals were registered at these points:
[1]:
#0 0x71f618 in __asan_register_globals.part.13 /home/vmiklos/git/libreoffice/lode/packages/llvm-llvmorg-9.0.1.src/compiler-rt/lib/asan/asan_globals.cc:362
#1 0x7f00cb0f3d7b in asan.module_ctor (/home/vmiklos/git/libreoffice/online-san/test/../test/.libs/unit-base.so+0x10e0d7b)
[2]:
#0 0x71f618 in __asan_register_globals.part.13 /home/vmiklos/git/libreoffice/lode/packages/llvm-llvmorg-9.0.1.src/compiler-rt/lib/asan/asan_globals.cc:362
#1 0x120e2ae in asan.module_ctor (/home/vmiklos/git/libreoffice/online-san/coolwsd+0x120e2ae)
==4544==HINT: if you don't care …
> sanitizers: fix unit-base, again

- browser/css/leaflet.css
now, it uses a css theme variable for the color
but it is a kind of light grayish and it is harder
to see in a crowded document.
Change-Id: Iec5a7efdb4cb385512226841b036eba3b3212427
* Resolves: # 
> change blinking cursor color to black

- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
No need to specify if it's first or second button as there is always
only one primary button. On top of that this avoids maintenance work
whenever for some reason the button is not the first in line.
Change-Id: Idd3ef60023e88d1a9a8fd6f465dc4c63c068debd
> Cypress: Do not hard target buttons based on their position

- browser/css/jsdialogs.css
Example: Fontwork dialog
Avoid using webKit and Blink only values such as "overlay" for overflow
instead, use auto which in practice has the same behavior.
Fixes:
https://archive.org/download/4d-1475b-46-fix-icon-view-breakage/4d1475b46-Fix-IconView-breakage.png
Change-Id: I35e27204f0653f8eae973e830dcc701d0ca782b0
> Fix IconView breakage on gecko based browsers (e.g.:FF)

- test/HttpRequestTests.cpp
We can't test SSL when SSL is disabled.
Signed-off-by: Tomaž Vajngerl <tomaz.vajngerl@collabora.co.uk>
Change-Id: I231a3c7d32f848870e90594e2d1151d3a0911f9a
* Resolves: # 
> fix build of HttpRequestTests when SSL is disabled

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
This reverts commit 32f5c874e71c347fa0eaad3c7a9489353efb9744.
The text alignment is causing some problems both on the sidebar and in
the mobile wizard:
- Sidebar arrows (from dropdown menus) position are affected due to this
- Mobilewizard: content is getting wrongly aligned to the right
- On top of that we should preffer start and end due to RTL instead of
right or left
https://archive.org/details/cool-txt-align-bug
Change-Id: I02f22da0b14b02e7431ea26c16930554e3c13aa2
* Resolves: # 
> Revert "Sidebar Widget right alignment with text-align"

- browser/src/control/Control.MobileBottomBar.js
most of them don't have the text where they need to have
otherwise the text is defaulted to id. We can use hint prop
to text because it has the same output due to the uno command
name convention.
Change-Id: I0dd38ebdaaa95c41225c49e02d7615007e8a4049
* Resolves: # 
> add text prop to mobilebottombar menu items

- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
Running command in /home/runner/work/online/online: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh]
[2022-04-05 08:02:27] [build-stderr] Skipping path /home/runner/work/online/online/**/*w2ui-1.5.rc1.js, which does not exist.
[2022-04-05 08:02:27] [build-stderr] Skipping path /loleaflet, which does not exist.
[2022-04-05 08:02:27] [build-stderr] Illegal '//' in exclude path
Error: 4-05 08:02:27] [ERROR] Spawned process exited abnormally (code 1; tried to run: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh])
A fatal error occurred: Exit status 1 from command: [/opt/hostedtoolcache/CodeQL/0.0.0-20220311/x64/codeql/javascript/tools/autobuild.sh]
Change-Id: …
> Attempt to fix a codeql error

- kit/Kit.cpp
the state is explicitly set by the first view but on makeRenderParams
function we dont check if the spellonline is empty or not, if empty
we should not change the state. It is only empty for views after the
first one
Change-Id: Ief5754bdae2eb952c2df9485fa323fc957da40a6
* Resolves: # 
> Fix views after the first one change spellOnline status

- common/Util.cpp
- common/Util.hpp
- docker/from-packages/RHEL8
- docker/from-packages/Ubuntu
- docker/from-packages/scripts/start-collabora-online.pl
- docker/from-packages/scripts/start-collabora-online.sh
- docker/from-source/.gitignore
- docker/from-source/Debian
- docker/from-source/Ubuntu
- docker/from-source/build.sh
- docker/from-source/openSUSE
- wsd/HostUtil.cpp
This is to be able to define the alias groups via YAML easily, like:
environment:
- aliasgroup1=https://servername:443,https://its-alias:443,https://its-second-alias:443
- aliasgroup2=https://second-servername:443,https://seconds-alias:443
Change-Id: Ib653f7ab420fed342a00f5f5997a113da9739866
> Script to rewrite coolwsd.xml based on the aliasgroup<number> envvars

- ios/Mobile/CODocument.h
- ios/Mobile/CODocument.mm
- ios/Mobile/DocumentBrowserViewController.mm
- ios/Mobile/SceneDelegate.mm
Fixes the issue where you can edit a document that was opened directly from the Mail app (where it was an attachment to an email message). Now we open such documents read-only.
* Resolves: # 
> iOS app fixes

- common/Util.hpp
UTF-8 is expected to encode a code point using 1 to 4 bytes.
Change-Id: I9b4f346738865fc18242e51a33c97e5b38ee90d8
> common: isValidUtf8: ensure chunk len is 4 at max

- Makefile.am
- common/FileUtil.cpp
- common/Log.hpp
- common/StateEnum.hpp
- common/Unit.hpp
- net/HttpRequest.hpp
- net/Socket.cpp
- test/TileCacheTests.cpp
- test/UnitStorage.cpp
- test/UnitWOPI.cpp
- test/UnitWOPIAsyncUpload_Close.cpp
- test/UnitWOPICrashModified.cpp
- test/UnitWOPILock.cpp
- test/UnitWOPISlow.cpp
- test/UnitWOPIVersionRestore.cpp
- test/UnitWopiOwnertermination.cpp
- test/WOPIUploadConflictCommon.hpp
- test/testlog.hpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Misc test, logging, assertions, and similar improvements.
All of these changes are non-functional and any functional change should be flagged in the review.
- wsd: move tokenizer helpers into StringVector
- wsd: log the duration of save and upload when done
- wsd: move STATE_ENUM to common/StateEnum.hpp
- wsd: use STATE_ENUM for DocBroker states
- wsd: minor improvements to logging and macros
- wsd: modernize UnitWOPI
- wsd: logging and minor cosmetics
- wsd: add LOG_ASSERT to replace assert with extra logging
- wsd: include the ClientSession name in logs
- wsd: use STATE_ENUM for SessionState
- wsd: support serializing STATE_ENUM to ostream 
- wsd: use STATE_ENUM for http
> Tests, logs, and non-functional improvements

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
when we decide the keyboard is closed by checking the screen size
we should not force keyboard to close again instead we just need to
set the state
Change-Id: I486cda0598ab02e426aefd726475f0e70e0eee52
* Resolves: # 
> Fix endless keyboard show/hide flicker

- browser/src/control/Control.Menubar.js
When working with tables it is now possible to to slip cells
where: Top menu: Table -> Split Cell...
Change-Id: Ia242358245cebb6bded55aa995bd8c80900b9aaa
> Classic: Add missing split cell dialog trigger to writer

- test/helpers.hpp
The webframe buffer size used to be READ_BUFFER_SIZE (64k), but that's
no longer enough in unit-uno-command since
<https://github.com/libreoffice/core/commit/a20e761cb1112357bfae35e24b49fae872bce3f6>
(jsdialog: fix toolboxes with children, 2022-03-17) if you have enough
fonts installed locally, because one toolbox in Writer is the font
dropdown, and that lists all the fonts you have.
getResponseMessage() already uses this increased buffer size, so this
also improves consistency.
Change-Id: Ic2ad0e8e7443365395b16618d6c82465252ba455
> test: increase buffer size in SocketProcessor()

- browser/src/layer/marker/Cursor.ts
When the focus is lost, TextInput actually removes the mouse cursor
but there are other functions that sets the cursor and we need to
check whether the cursor is deleted or not before we set it.
Change-Id: I57622d9a7156148ce2a3cdbedc1af551581d0f8a
* Resolves: # 
> don't set cursor to IBeam unless textinput has the focus

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
changes, mainly in Chart Editing Panel
(select chart -> press "edit chart")
- simplified sidebar panel label with arrow
arrow has simpler rules without left/right (for RTL)
- turned off margins for .jsdialog.root-container
what caused elements to overflow in chart panel
(eg drawingarea with chart types)
- changed panel width definition from fixed pixels to
"100% - scrollbar"
- RTL: converted left/right -> margin-inline-* for some
spinfields in chart panel
also includes :not(autofilter) in one rule which is changed in not merged PR...:
https://github.com/CollaboraOnline/online/pull/4541
> sidebar: fix alignment in chart deck

- browser/src/control/Control.AutofilterDropdown.js
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.MobileWizard.js
jsdialog: autofilter: unify with regular popup (from co-22.05)
- in 22.05 core autofilter was welded and converted into regular popup
- for now we have to support both versions for 2021 and 22.05:
- for 22.05 handled in Control.JSDialog.js
- for 2021 handled in Control.AutofilterDropdown.js
- leter we need to remove Control.AutofilterDropdown.js
- special handling in Control.JSDialog.js should be separated later...
requires core changes:
https://gerrit.libreoffice.org/c/core/+/132538
https://gerrit.libreoffice.org/c/core/+/132539
https://gerrit.libreoffice.org/c/core/+/132619
> jsdialog: autofilter: fix fox co-22.05

- browser/css/notebookbar.css
Before we needed an exception for the StatisticsMenu, to position the
arrow. Now this is no longer needed. The component get well placed by
default
- Remove CSS exception and fix the inconsistency:
https://archive.org/download/cool-nb-bug-arrow-statistics/cool-nb-bug-arrow-statistics.png
Change-Id: I7cf46c7c3d2593b571c91c0dedc197fdcae3a7ee
> Fix StatisticsMenu arrow

- cypress_test/integration_tests/desktop/calc/image_operation_spec.js
Change-Id: I471d220cd15b66693b6e43bcf5ee83276921ff9c
> cypress: fix:ui-expander-label getting detached from dom

- net/Socket.hpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
**Part 1**
A number of fixes and improvements to Save and Upload cases. Each commit explains the need for the change.
Where appropriate, `ExperimentalEnabled` is used.
Most were found through tests (a few through reviewing code). Improved test coverage included (which fail without these fixes) in part-3 #4567. Please review part-2 #4566 after this.
_Best to review each commit separately._
- wsd: detect ECONNRESET and EPIPE after reads and writes
- wsd: check the stop flag immediately after poll
- wsd: correct active-session counting
- wsd: add and use isWritable helper in session
- wsd: do not close the socket while have data to read
> Save and Upload Improvements: Part 1

- browser/src/control/Control.JSDialog.js
it is easy to block the input in the app if we didn't close
popup on the server but already deleted HTML elements for it
> jsdialog: popups: don't close if nto received message from the server

- coolwsd-systemplate-setup
- coolwsd.xml.in
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/Kit.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
The coolwsd.xml file can contain a URI of a JSON file on some server
that contains URIs of fonts. These fonts are downloaded. Just like the
remote configuration thing, the URIs are checked once a minute and the
JSON or the fonts are re-downloaded if their contents change.
If a font has been removed from the JSON then the corresponding
downloaded file is removed, too.
It is still unclear how exactly handle this with LibreOffice core and
Fontconfig.
Change-Id: If78058ddff5ed05c7a82d7ea465a7a414fd0d861
* Resolves: # 
> Add a remote font configuration thing

- browser/html/cool.html.m4
- browser/html/debug.html
textarea focus makes firefox zoom in without
specifying viewport scale properties
Change-Id: Iea5c0e61af14dc8f05319570f84681ca2b76aed1
* Resolves: # 
> fix firefox zooms in whole page on mobile

- browser/css/device-mobile.css
- browser/css/welcome.css
- browser/welcome/welcome.css
* Resolves: #3790
devices-mobiles.css
- rules for mobile wasn't needed
everywthing is in welcome.css
welcome.css
- screen behind welcome dialog use --color-overlay
as at every dialog
- no fixed width and height
max-width and max-height was the old width/height
width and height are now 95%
dialog window was center justify
- content width is 96%
when smaler than 500px padding was added to <p>
- fig get top an bottom margin
so now all fig's have the same height
- hyperlinks use --color-primary
and not underline
Change-Id: If921bc2abc3977930f7d60256d8011d8986a22c9
> Update welcome screen for smaler sizes and mobile

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
Just a to make the sparkline actions accessible from the menu
and notebookbar.
Signed-off-by: Tomaž Vajngerl <tomaz.vajngerl@collabora.co.uk>
Change-Id: I80a483397184a8a9c0eb28048b3636ec91b95081
* Resolves: # 
> add sparkline action to the menubar and notebookbar

- browser/src/control/Control.JSDialogBuilder.js
Add iconAlias and avoid duplicating svg
Change-Id: I4a14da88c9e97e5541d224c2d1f29a99df19a7f9
> Fix missing sparklines icon on notebookbar, format tab

- ios/Mobile/L10n.h
- ios/Mobile/L10n.mm
- ios/Mobile/TemplateCollectionViewController.mm
The ifdef conditions seems a bit over-complicated but as long as it
compiles it is good enough for me. I don't remember the details from
my earlier work on this.
Change-Id: I9a1873dc3676c15c7fb4cde84c0e14bf56653443
* Resolves: # 
> Make the TranslateId things compile against co-22.05

- browser/mocha_tests/CPointSet.test.ts
Include Bounds.ts (definition of cool.Bounds) to fix the following build error of CPointSet.test.ts
```
./node_modules/typescript/bin/tsc mocha_tests/CPointSet.test.ts --outfile mocha_tests/CPointSet.test.js --module none --lib dom,es2016 --target ES5
src/layer/vector/CPointSet.ts:23:33 - error TS2694: Namespace 'cool' has no exported member 'Bounds'.
23  static fromBounds(bounds: cool.Bounds) {
~~~~~~
```
Change-Id: I8853995544c56c9a3bd522bacbf572bc1084cb17
* Resolves: # 
> mocha-tests: fix build for CPointSet.test.ts

- browser/images/lc_toggleuimode.svg
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
* Resolves: #3955 
This implements a toggleuimode action that allows switching between classic and notebookbar UI mode which is then exposed in the menubar (View > Use Notebookbar UI) and notebookbar (View > Classic UI).
@eszkadev I'd be interested about feedback on the implementation as I could not get a clear understanding on how the actions are shared between the menubar and notebookbar and if the approach to trigger them in the way done is the best.
@pedropintosilva Do you have a suggestion for a good icon from the existing ones maybe? For now I added a temporary commit with a material icon, but should be something matching the upstream icon theme there of course.
https://user-images.githubusercontent.com/3404133/154939267-0169e562-9cb8-4d58-9062-5f1512b9fe95. …
> Add toggle for UI mode to menubar and notebookbar

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
No need to indicate that those components are toggles since they
visually communicate there. Plus we are not using that prefix for
other toggles like "sidebar"
Change-Id: Idb99d1e8505feb3adaa9378f0f96309cd3cf7158
> Remove toggle prefix from status bar and ruler

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
**Part 2**
A number of fixes and improvements to Save and Upload cases. Each commit explains the need for the change.
Most were found through tests (a few through reviewing code). Improved test coverage included (which fail without these fixes) in part-3 #4567.
- wsd: do not prevent saving when storage is missing
- wsd: add canUploadToStorage helper
- wsd: add canSaveToDisk helper
- wsd: needToSaveToDisk helper and improved autoSaveAndStop
- wsd: delay uploading if the last attempt had failed
> Save and Upload Improvements: Part 2

- browser/src/control/Control.NotebookbarWriter.js
Context:
Repair document on the Notebookbar is currently always a small item
https://archive.org/download/repairdoc-writer-smallitem/repairdoc-writer-smallitem.png
,it should be a bigtooltiem when the extra additional/optional item
Sign document is not available:
- Set it to small item and vertically stacked when hasSigning is true
- Set it to bigtoolitem when hasSigning is false
Change-Id: I26a8e1b721bf2550127eff1ccfdc44ab4876db52
> Fix repair document item on notebookbar writer

- browser/src/control/Control.Header.js
if right clicked on already selected row/column range,
don't reselect the right clicked row/column
Change-Id: I718a0a727913c38bc506fd2b808fba8feaebb0c8
> calc header: avoid reselecting selected row/col range

- browser/css/leaflet.css
context: https://archive.org/download/repair-doc-close-misaligned/repair-doc-close-misaligned.png
line-height, if the hard-coded px is needed, then it should be the
same value as the width and height so not 28px but 32px
as it's the values used in a.leaflet-popup-close-button.
But better to just rely on the unitless value that line-height can
accept then it will fit whatever the font-size and width the anchor has:
- Fix it by letting the web browsers align the content for us. Web
browser multiplies our number by the font-size value (1 times font-size)
, so no need to depend on specific px values for that.
Change-Id: I4145231241a9acc540c684971e3bde46adb2304b
> Fix leaflet-control alignment

- browser/src/control/Control.Toolbar.js
Normally these kind of button wouldn't need a tooltip but:
1. Doesn't hurt to add it
2. It helps the user with understanding what that btn does:
- The button doesn't remove the current opened document
- The button doesn't save and close
- The button closes the document
Change-Id: I45e63c4c7f42d314743702e6ff50b777527c4367
> Add tooltip to close document button

- coolwsd-systemplate-setup
If I have used a path with symlinks in it when changing directory to
my build directory, what gets put in config.status as ac_pwd is that
path, not a realpath version. That then propagates to
ac_abs_to_builddir and to SYSTEMPLATE_PATH, which is what Makefile.am
passes for the --o:sys_template_path option to coolwsd.
Change-Id: I7575120090986e6207497c5ce740aedd6075e48f
* Resolves: # 
> Avoid using only "real" paths for the tmpfont thing

- test/WopiProofTests.cpp
This is a temprorary patch until we can properly
migrate the verification code to openSSL 3.x.
Change-Id: I676ae3b5a1e0d27ef1d253dba2275f7de5fc08ff
> wsd: test: disable verifySignature test with openssl 3

- wsd/LOOLWSD.cpp
This extends 231fae4ebd990cb344143759cbdfa19c4f30d4f2
to cover the --help and --version-hash command
line options.
Fixes #4662.
> wsd: forced exit after --help and --version-hash

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
commit da1927a0ebd6d797acf37547c2128b7ae1d59b26 (HEAD -> private/pedro/fix-T34772, origin/private/pedro/fix-T34772)
Listbox: remove unnecessary margin and fix padding
The additional margin was affecting the surrounding elements in some
browsers in the sidebar
Better to not call padding-right or padding-left specifically:
- Better to use shorthand and make sure how the final padding will be
- Better for RTL
----
commit a3d2ac5e9176734005e59e30c09d2677e2aad669
Listbox: do not multiple font-size
use the same font-size for listox no matter where it's placeholder
- Multiplying would make it look too big in some places
----
commit 15fac252a0c6d26a1f6a5c8a3bc41ce6e2956337
Listbox: reduce height
with refactoring from 2da8de38df1660b205392391ebada7759ee8e2d6
and with the code now in onw place we …
> private/pedro/fix T34772

- browser/src/control/Control.MobileTopBar.js
- browser/src/control/Control.MobileWizard.js
- browser/src/control/Control.UIManager.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasSectionContainer.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/WriterTileLayer.js
- browser/src/map/Map.js
Prevent errors on load when section may be missing
In the past I've seen very often that for example
commentList section was missing but used without any
check.
This commit checks if section exists before use and
warns if it doesn't so we can see that in the console
logs.
Second commit:
removed unnecessary console.error with notebookbar state used for debugging and commited by mistake
> Prevent errors on document load

- net/Socket.hpp
- net/SslSocket.hpp
Without knowing whether the write succeeded
or failed, we cannot trust errno has our
error or some earlier and unrelated error.
This was caught when there were two sockets,
one of which disconnected. The write to the
disconnected one returned -1 and set errno
to ECONNRESET. We subsequently wrote to the
second socket, which succeeded. However,
because errno wasn't reset, and since
writeOutgoingData didn't return anything
to indicate the success, errno's ECONNRESET
value meant the second socket was also
disconnected, which was incorrect.
writeOutgoingData now returns the last return
value from writeData so we can make informed
decision as to whether to check errno or not.
Also, to avoid incorrecly propagating errno,
we now capture errno only when readData and
writeData return -1. This has …
> wsd: return status from writeOutgoingData

- coolwsd.xml.in
- wsd/COOLWSD.cpp
This way, there is only one entry point for all the remote
configuration, and the remote_font_config does not have to be specified
in coolwsd.xml, in case the remote_config JSON specifies that.
Change-Id: I857bab3d300ddb5c0c3df0a9f62eda20f43c3ff7
> Allow specifying the remote_font_config URI in the remote_config

- browser/css/notebookbar.css
remove padding-top: 5px so there is no scrolling
needed for two rows.
Change-Id: I9a0450074cc55486d0f7de8a39b7edff8e66c752
> writer notebookbar stylesview previews no padding

- browser/Makefile.am
- browser/css/color-palette-dark.css
@media (prefers-color-scheme: dark) setting
is available by use color-scheme-dark.css
instead of color-scheme.css
sure the scheme need some update
but there are other open points like
use dark color for document
use dark colibre icons
this is only the .css change
so no full dark mode update
* Resolves: #4382 
* only use dark color-sheme-dark.css  
Change-Id: I5c2adcbb75583a952f419af507d7cfe5c1343e3c
> Add color-scheme-dark.css support

- browser/css/btns.css
- browser/images/symbol_SPIN_DOWN.svg
- browser/images/symbol_SPIN_UP.svg
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileTopBar.js
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.Sidebar.js
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- build drawingarea even if is empty (so we can later apply update events)
- remove old hack which added "table-" prefix to some widgets
- implemented textarea with raw keyboard handling (by the core, user cannot type directly into the field, only see the result from server) `not used in 21.11`
- implemented buttons with "symbol" instead of image `not used in 21.11`
- implemented `toolitem` which can easily share code with eg. menubar `customtoolitem` and `map.dispatch(command)`
This PR is for unifying jsdialog code between 21.11 and master so cherry-picking will be easier
> backports 21.11: jsdialog improvements

- wsd/COOLWSD.cpp
This went wrong when the forward-port of commit
b96e8b7c77a1739f36e5f17ab7770052282dc158 (wsd: correct use the exit code
from UnitWSD, 2021-11-29) didn't adapt the string to the updated
filename.
Change-Id: Ica8047dc05dedf9e075663f405dea89913cf789a
> wsd: fix log message typo in COOLWSD::innerMain()

- common/Util.hpp
- wsd/COOLWSD.cpp
- wsd/HostUtil.cpp
- wsd/HostUtil.hpp
- wsd/Storage.cpp
we added AllHosts to give admin the err log that host is not in alias_groups but now as we removed the host list entries from configuration we don't need that log
Change-Id: I8b5e9e6b7df7df59befb496c12966c7ddc60c707
> wsd: cleanup firsthost code

- loleaflet/js/ResizeObserverPolyfill.js
Instead of messing with parsing useragent - lets just check whether
the type exists.
Change-Id: Ib654dc71ec12fd643c906bc50fa9dff1791dc14e
* Resolves: # 
> A more robust resizeobserver polyfill detection.

- wsd/protocol.txt
As Tor noted on IRC, this was forgotten when the actual protocol
commands were introduced.
Change-Id: I548ac73348bceb469484ce934f7548ddb4091b63
> wsd: add initial protocol documentation for paintwindow and windowpaint:

- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
Also corrects the counting of number of active
sessions when broadcasting messages.
Change-Id: I5ab5995ed2cbc18b215542d0b2c9568957fd6a3a
> wsd: do not enqueue messages on closed sessions

- browser/src/layer/tile/CanvasTileLayer.js
Otherwise, if the user selects all the document,
the clipboard blocks Page Up or Page Down cursor jumps.
Change-Id: Ia9c432646c51063775bb7cca6a998e7d1cdcdbf2
> browser: allow cursor jump if text selection is empty

- browser/src/control/Control.FormulaBar.js
- browser/src/control/Control.JSDialogBuilder.js
- handle CTRL and SHIFT key modifiers in formulabar (eg. for selecting few chars using keyboard)
- clear reference marks after formulabar was deactivated
> formulabar: improvements

- docker/from-packages/scripts/start-collabora-online.pl
- docker/from-packages/scripts/start-collabora-online.sh
show a verbose warning about using domain
Change-Id: I41fdea3419eb2719fa665a62de33e3a237cf3df8
This is what the message look like in docker logs:
> docker: map domain env variable to alias_groups

- browser/src/core/Socket.js
browsers having different themes make it hard to read the logs
this will help make logs more readable irrespective of themes
Change-Id: I9e48f75d0f1ed20221c969db6d4a6ea00910717e
> logging: let the log text colour be selected by the browser

- browser/css/jsdialogs.css
switch to ffffff instead of 222222 when the prefers-color-scheme is dark
Change-Id: I3e3c68879c6b6a831d5fbf095597ddae6eb51f77
> jquery-ui-lightness/ui-icons_ for dark mode

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/mobile/calc/calc_mobile_helper.js
Some places tested for AMJ being the last column, but with 16k
columns it's XFD. Without this those tests run in an endless
loop when run with Calc set to 16k columns.
Signed-off-by: Luboš Luňák <l.lunak@centrum.cz>
Change-Id: I6249e0ec975634b60aaf3291e021b74b4aa3cc5d
> make cypress tests work also with 16384 columns

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/SheetGeometry.ts
- kit/ChildSession.cpp
* Target version: co-21-11 
* Introduce new callback LOK_CALLBACK_PRINT_RANGES
* Read the print ranges for the current sheet from LOK_CALLBACK_PRINT_RANGES message and draw dashed grid lines for the rows/columns bordering the range.
Caveats:
* Desktop calc does not draw print ranges on document load if there are
print ranges set previously on save. Cool also has the same behaviour.
* If there are multiple print ranges in the same sheet desktop calc does
not show any dashed lines indicating the ranges. Cool also adopts this
behaviour for now.
* Styling of the dashed lines was not investigated much for writing this
patch hence it uses the same drawing style as normal grids.
> Show visual indicator for print ranges in Calc

- test/UnitTimeout.cpp
A problem since c6561a99d8c2a7a7941543dd4655675b6a0a1030 (wsd: test:
correctly stop SocketPoll in UnitTimeout, 2022-04-21), the trouble was
that calling UnitWSD::returnValue() from UnitTimeout::returnValue()
deletes the 'this' pointer, so we need to copy the interesting data
members to the stack before calling the base.
Change-Id: I86583ae516e2b2f367fbf5cb2a9401cc21f1b1cf
> unit-test: fix crash-on-shutdown

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/SheetGeometry.ts
- kit/ChildSession.cpp
* Introduce new callback LOK_CALLBACK_PRINT_RANGES
* Read the print ranges for the current sheet from LOK_CALLBACK_PRINT_RANGES message and draw dashed grid lines for the rows/columns bordering the range.
Caveats:
* Desktop calc does not draw print ranges on document load if there are
print ranges set previously on save. Cool also has the same behaviour.
* If there are multiple print ranges in the same sheet desktop calc does
not show any dashed lines indicating the ranges. Cool also adopts this
behaviour for now.
* Styling of the dashed lines was not investigated much for writing this
patch hence it uses the same drawing style as normal grids.
> Show visual indicator for print ranges in Calc (master)

- net/Socket.hpp
- net/SslSocket.hpp
- wsd/DocumentBroker.cpp
This enables code that was protected with
EnableExperimental in the socket logic (and one
case in DocBroker). These changes are now deemed
safe to enable permanently.
Change-Id: Ie62f5d7bd281ade90f38d654b51b104b8d1f14bc
> wds: enable experimental blocks unconditionally

- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
Reset document info on idle
resetting document info will force to use new status of the document
problem:
reconnecting after idle, user could not type anything in document,
this was due to some properties were to set assuming they existed from last session (i.e: clientzoom)
resetting document info will force to use new status message and set all the properties again correctly
* Target version: distrp/collabora/co-21-11
> fix: typing after idle

- browser/src/core/Socket.js
- browser/src/errormessages.js
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
It seems at least some storage hosts report disk-full
errors via 413. This logic of handling 413 error as
disk-full was introduced in
https://github.com/CollaboraOnline/online/commit/f8e0b8c11e94810fdde73f8b4d27b80a989670cb.
Here we handle 413 as it is defined, as Entity Too Large.
> wsd: browser: handle 413 Entity Too Large from storage

- browser/src/control/Control.NotebookbarWriter.js
Don't use strings coming from uno commands as they include
"Insert":
1. There is no need to say that these actions will "Insert", they
are already in the Insert tab
2. All other actions do not have Insert so it would be not consistent
3. On top of that with Insert in each icon the labels look quite long
Signed-off-by: Pedro Pinto da Silva <pedro.silva@collabora.com>
Change-Id: I286e95187d5df08cdf2d71bd99f3b77a17ef12ad
> Fix Insertcontentcontrols strings on tabbed view

- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
Reset document info on idle
resetting document info will force to use new status of the document
problem:
reconnecting after idle, user could not type anything in document,
this was due to some properties were to set assuming they existed from last session (i.e: clientzoom)
resetting document info will force to use new status message and set all the properties again correctly
> Idle typing

- browser/css/toolbar.css
Resolves: Issue #4821
Target version: master
Summary
Removed CSS bits that are targeting elements that do not exist anymore and were left over from the formulabar in the browser calc editor being converted from html canvas to normal. Expected there to be more unused bits, but everything else was in use.
TODO:
N/A
Checklist
[x] Code is properly formatted
[x] All commits have Change-Id
[x] I have run tests with make check
[x] I have issued make run and manually verified that everything looks okay
[x] Documentation (manuals or wiki) has been updated or is not required
Signed-off-by: Dekota Nelson [nelson.dekota@gmail.com](mailto:nelson.dekota@gmail.com)
> Removed unused CSS related to old formulabar.

- wsd/ProxyProtocol.cpp
https: //github.com/nextcloud/richdocuments/issues/2196
Change-Id: I4fce74290e8bf8a6681922a2165772933443703e
* Resolves: # 
> Proxy: send explicit charset=utf-8

- browser/src/control/Control.JSDialogBuilder.js
Handles for example: CTRL + "i" in the formulabar what triggers italic font
we should do the same for other modifiers: shift, alt...
> jsdialog: use correct codes for shortcuts CTRL + char

- configure.ac
fuzzers use the code as a library, so we don't produce binaries like
coolwsd in such a config, leading to:
Failed to set capabilities on file `coolforkit' (No such file or directory)
when building from scratch.
Just disable setcap in the fuzzers case, it's fine to not have these
binaries.
Change-Id: I178ec7d8fa4d582e5d7289764a6ce2227c049205
> fuzzers: avoid setcap

- kit/ChildSession.cpp
Otherwise calling getSelectionType() first and then getTextSelection()
creates the XTransferable2 twice, and then possibly converts it
to the text format twice, which may be expensive.
Also some cypress tests use selectEntireSheet() and then check
the clipboard contents, which with the switch to 16k columns in Calc
may be slow enough in debug builds when done twice to time out
the test, and this helps a bit there.
Signed-off-by: Luboš Luňák <l.lunak@centrum.cz>
Change-Id: If166f67c216281d32dbb1d3e10b51177b42a9668
This requires https://gerrit.libreoffice.org/c/core/+/134615 .
> use the more efficient getSelectionTypeAndText()

- net/Socket.hpp
- net/SslSocket.hpp
A corner case where read doesn't return 0
on a closed socket can result in a stuck
state where we attempt to read when we
do get ECONNRESET (which we didn't check
on reads).
This makes the interface of readIncomingData
the same as writeOutgoingData by returning
the actual return value of the read syscall.
So now we handle both return 0 as well as
error codes returned on failed calls.
The logic hasn't changed, just that now
we handle errors better and similar to the
write case.
Change-Id: I0b38a63da4e6c92a482948478d5d8d446e0b8b58
> wsd: handle socket closed on read better

- cypress_test/integration_tests/mobile/impress/table_operation_spec.js
modify the test to use 2x2 table when testing 'insert column before/after' tests
no idea why we don't get svg when there is 3x2 table
Change-Id: Id927fede691c4483206fa2b65c450f11cc980581
> cypress: re-enable impress/table_operation_spec.js

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- Only visible when macros is switched on (coolwsd.xml)
- Added to the File tab because:
- We do not have Tools tab and it seems we do not have a need or
more > 1 action that justifies an yet another new tab
- Run Macro could fall into Review or insert category but and
since the icon when pressed Runs a Macro, best to place it
within File tab since it affects the file. Plus user that is used
to operate within classic view it's more likely to go to File tab
Signed-off-by: Pedro Pinto da Silva <pedro.silva@collabora.com>
Change-Id: I8110fc259860d285f0c911b9b553bdc67235f4e2
> Add missing Run Macro action to tabbed view

- browser/src/control/Control.JSDialog.js
So we can type after we closed popup in the sidebar.
> jsdialog: focus map after popup is closed

- browser/css/cool.css
This reverts commit dd83984896d62f8c0441b2058cffa5e9d6e7ce0c.
The logo style already exists and to avoid override rule.
> Revert "browser: css: add '#lokit-logo' style to fetch lokit-extra-img.svg"

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
Compact View is separate in the menubar from Sidebar and Statusbar
So it shouldn't be between them in the View Tab.
Change-Id: Ib46e9c4a4df24432eae5a7fef335e7cde68b1766
> Compact View isn't part of Sidebar, Statusbar

- wsd/COOLWSD.cpp
Change-Id: I208dce052ba02a4ccfc283fbb5ff3af8d8bf38bb
* Resolves: # 
> wsd: fetch external resource in debug build, but not for unit tests

- browser/src/layer/marker/Cursor.ts
when other view moved cursor outside out view - all of
them were hidden because we used selector for all the
elements matching cursor class - instead of current
instance
> fix hidden cursor 21.11

- browser/src/control/Control.JSDialog.js
jsdialog: be sure popup overlay will not block user
Don't add multiple overlays with the same id.
Remove overlay always when it exists and we close.
Close dropdown entires by dropdown click - specific to 21.11
where popups in the core are handled differently.
------------------------------------------------------------------------------------------------------------
jsdialog: use correct element to close popup
For toolitems with dropdowns we should toggle the button.
Use correct parent so we don't use button from other component.
Later we send toggle event to properly close the popup on the server.
example: Calc sidebar, Underline popup
Before this patch when we clicked in outside the popup it dissapeared
but app was completly blocked.
> jsdialog: correct popup close in 21.11

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Toolbar.js
notebookbar: retry to activate when needed
Don't generate spam in the console log with warnings about not
activated notebookbar in apps where we don't use any welded widgets.
Allow to send view mode command when dialog is opened
We automatically send notebookbar activation command in some cases.
Allow this command when dialog is opened and don't blink.
> Fix blinking dialog & warnings about notebookbar in Impress (21.11)

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Toolbar.js
notebookbar: retry to activate when needed
Don't generate spam in the console log with warnings about not
activated notebookbar in apps where we don't use any welded widgets.
Allow to send view mode command when dialog is opened
We automatically send notebookbar activation command in some cases.
Allow this command when dialog is opened and don't blink.
> Fix blinking dialog & warnings about notebookbar in Impress (master)

- browser/css/jssidebar.css
No visual change only switch from `padding-left` and `-right` to `padding-inline`
`padding-inline` was supported by all browsers
https://developer.mozilla.org/en-US/docs/Web/CSS/padding-inline
Change-Id: Ib694d2acf60b2f0058f5ef0633e19aa086498c77
> Sidebar padding-inline instead of -left -right for RTL support

- browser/css/cool.css
- browser/src/control/Control.JSDialogBuilder.js
Bug
- pushbuttons with images get misaligned. Namely the inner image that
it's position well. Visible in some places within the sidebar
impress, calc:
https://archive.org/download/bug-pushbutton-with-img-alignments/bug-pushbutton-with-img-alignments.png
Fix
- Pushbuttons with images are now classified with .has-img and inherit
the respective global flexbox CSS classes.
- Add global flex box CSS classes so we can avoid code duplication
- Also make sure other pushbuttons with image don't butchered with this
change (e.g. calc > pivot table dialog)
Change-Id: Ie37680eb02c15417c505402074bbe01d302910cb
> Fix images' alignment within pushbutton control, add flex classes

- browser/css/jssidebar.css
The left padding was there before and is needed for the scrollbar. I suggest to have also an right padding so that the sidebar expander-content elements are better visual interacting with the ui-expander.
Also for the ui-expander (header area) the width calculation was removed, cause than the separator line was not 100% of the sidebar. To have the img for the dialog button not hidden by an scrollbar the 10px was added as marign-inline-end element.
As you can see the light bottom border line was 100% of the sidebar width and didn't stop 10px before.
Change-Id: Ifbeecbaef00963498ac3a1bafd2a42075856d9ca
> Sidebar .ui-expander-content have left and right same padding

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js
in desktop case color widget should show the latest selected
color not current one. split the button into arrow with dropdown
and "last color" button (icon)
> notebookbar: unify color control with core

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- Open eg. the hello world spreadsheet,
- In the sidebar, open the font list, and wait a few seconds.
The font list closes. If you reopen it, it closes immediately, this can go on a few times, then it stays on as expected.
> Calc font list in sidebar loses focus

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- Open eg. the hello world spreadsheet,
- In the sidebar, open the font list, and wait a few seconds.
The font list closes. If you reopen it, it closes immediately, this can go on a few times, then it stays on as expected.
> Calc font list in sidebar loses focus (21.11)

- Makefile.am
- net/HttpRequest.hpp
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/ProxyRequestHandler.cpp
- wsd/ProxyRequestHandler.hpp
- Revert "serve lokit-extra-img.svg with integrator theme, too"
- Revert "wsd: fetch external resource in debug build, but not for unit tests"
- Revert "wsd: add indirect request logo image"
- Revert "wsd: add fetch external method"
- wsd: proxy: add ProxyRequestHandler files
- wsd: proxy: add handler request function
- wsd: proxy: add a callback response handler
- wsd: proxy: add cache response
- wsd: proxy: handle cache max age
- wsd: proxy: modify basic headers to forward
- wsd: proxy: handle the proxy request
* Resolves: # 
> proxy request handler

- wsd/HostUtil.cpp
- wsd/Storage.cpp
…_groups entry in config
Change-Id: I7ea73f147e283077b02bdacb37f8850f7613c0c3
It can happen that admin has old configuration (wopi.storage.host) and new configuration (wopi.storage.alais_groups.group) so we should not parse the wopi.storage.host entries at all
> wsd: fix: use only alias_groups entries when defined

- browser/src/layer/tile/CanvasTileLayer.js
When spreadsheet was opened after few seconds we received CellCursor
message.
If comment was opened end edited at that time - it dissapeared
> comments: don't lose focus if is edited

- browser/src/control/Control.JSDialogBuilder.js
This helps us to be in sync with core especially with
problematic dropdowns like:
Sidebar in shape context -> Line Panel -> Line Width
This will close and not reopen the popup when we click outside.
requires core change: https://gerrit.libreoffice.org/c/core/+/136570
> jsdialog: use open/close instead of toggle for dropdowns (master)

- kit/Delta.hpp
Change-Id: If4b18b96f3188489f1e5a027e08523722a2d85dc
> TileLocation::hash(): shift when the input size_t already

- browser/src/control/Control.JSDialogBuilder.js
This helps us to be in sync with core especially with
problematic dropdowns like:
Sidebar in shape context -> Line Panel -> Line Width
This will close and not reopen the popup when we click outside.
requires core change: https://gerrit.libreoffice.org/c/core/+/136571
> jsdialog: use open/close instead of toggle for dropdowns (21.11)

- browser/css/btns.css
ported from:
PR: https://github.com/CollaboraOnline/online/pull/4976
In cases when the button text is too long
or when using CO in, for example, DE language and when
the length of the parent dialog was not enough the btns
would not stack up, instead that would overlap. This would
make reading those btns impossible.
Change-Id: I801ea330db21add35d0a81466a1fba9501a61899
> Allow buttons in vex dialogs to wrap

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
When we use API call InsertButton and we add custom buttons
we want to keep them when we switch between compact/tabbed view.
> Keep custom buttons when switching the view

- Makefile.am
- net/HttpRequest.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ProxyRequestHandler.cpp
- wsd/ProxyRequestHandler.hpp
- wsd: proxy: add ProxyRequestHandler files
- wsd: proxy: add handler request function
- net: add getter funtion "getUrl"
- net: add "response" getter function
- wsd: proxy: add a callback response handler
- wsd: proxy: add cache response
- wsd: proxy: handle cache max age
- wsd: proxy: modify basic headers to forward
- wsd: proxy: handle the proxy request
- wsd: proxy: simplify time_point
- wsd: proxy: add missing catcher exception
- wsd: proxy: replace std::map -> std::std::unordered_map
- wsd: proxy: ensure to forward only static files
- wsd: proxy: fix length static string
> pr/distro/collabora/co 21 11/01

- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
jsdialog: formulabar: fix backward selection using shift+arrow
When editing formulabar using keyboard - try to use shift + arrow
to make selection from the end in backward direction.
This patch makes it possible (visible).
Signed-off-by: Szymon K\u0142os <szymon.klos@collabora.com>
Change-Id: I48073214545892d98be097b38c60251ff95082f3
-------------------------------------------------------------------------------------------------
jsdialog: formulabar: unify behaviour of Safari/Gnome Web with other browsers
eg. Chrome setups selection only if element has focus
it prevents us from stealing focus by formulabar when
switching cells
> formulabar fixes: backward selection, focus on Gnome Web / Safari

- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/insert_object_spec.js
- cypress_test/integration_tests/mobile/writer/searchbar_spec.js
Our plain text clipboard output generated additional newlines
at the beginning of every paragraph. To fix that we need
fix in core side which now fails due to expected bad format in cypress.
This is interim state where we accept both old and new format.
see for reference: https://gerrit.libreoffice.org/c/core/+/136893
lok: don't pretty print html for online
Change-Id: I2b17d62398d947fcf1d3fb1ed6005c3063d114f2
> cypress: clipboard formatting new lines fix 2

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Our plain text clipboard output generated additional newlines
at the beginning of every paragraph. To fix that we need
fix in core side which now fails due to expected bad format in cypress.
This is interim state where we accept both old and new format.
see for reference: https://gerrit.libreoffice.org/c/core/+/136893
lok: don't pretty print html for online
I2b17d62398d947fcf1d3fb1ed6005c3063d114f2
> cypress: allow correct plain text clipboard formatting 3

- common/Common.hpp
- common/JailUtil.cpp
- common/JailUtil.hpp
- common/Log.cpp
- common/Log.hpp
- common/Seccomp.cpp
- common/SigUtil.cpp
- common/SigUtil.hpp
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/Kit.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
These patches implement SIGUSR2 to backtrace the stack of the receiving process. For the moment, we backtrace the main thread only. In addition, we implement a long-desired, signal-safe method for capturing stack-traces in log files. Here we dump the backtrace in question into a special signalLog file and we then extract it (outside of the signal handler) and dump into the log file.
The changes are large mostly to accommodate these changes. That is, there is quite a bit of refactoring that isn't functional.
- wsd: jail: rename jails to childroot to distinguish them
- wsd: jail: move LO_JAIL_SUBPATH to JailUtil
- wsd: jail: no need to pass loSubPath between processes
- wsd: jail: add Poco namespace where missing in LinkOrCopy
- wsd: minor cleanup of addNewChild
- wsd: sig: prime libgcc and …
> USR2 to Backtrace and Signal-Safe Logging

- kubernetes/helm/collabora-online/templates/ingress.yaml
- kubernetes/helm/collabora-online/templates/service.yaml
Instead of using URL parameter hash to direct all the users on same document to same server,
use stick-tables for it
original problem:
Problem was load balancer provided us with required persistence and balance both.
we directed traffic based on the url_param which means,
all the traffic with same url_param will go to same pod/server.
All the new values of url_param will be directed to different servers in round-robin way
this can be less efficient in a high traffic environment
solution:
this new method allows us to balance and manage persistence separately
so we can specify our desired algorithm for load balancing
and persistence is managed using stick-table
Change-Id: I80d63a2fc33f796c4534d94fb8de1e44c62ee9e2
* Target version: …
> HAProxy: better load balancing

- browser/src/control/Control.UIManager.js
This is needed so 584aa5b8f624f3871a94d5294ab754d7b03cff2f
is also applied on tabbed view.
Until now we were just adding that class when on compact view
(Control.TopToolbar.js)
Change-Id: I8c0ac3d909f64025f301651564b3c2b1ae130e1c
> Calc: Add missing class to toolbar-wrapper when on tabbed view

- docker/README
- docker/from-packages/scripts/install-collabora-online-ubuntu.sh
- docker/from-source/Ubuntu
- docker/from-source/openSUSE
Several functions in Collabora Online depend on the server timezone setting.
The most common is possibly the rendering of dates and times using the `<text:date>`
tag in order to include the current date and time in the header or footer of documents.
Unfortunately current docker images do not provide any means to change the timezone
from the default UTC. Linux docker users should be able to mount the system's `/etc/localtime`
and similar system files, but this is a hack, does not support users in other platforms, and
does not seem to work in recent versions of the docker images.
This commit adds the the `tzdata` package to Ubuntu-based docker builds and the
`timezone` package to openSUSE builds. This allows docker users to run the containers
with a custom timezone by simply passing a TZ …
> Added support for setting the timezone in Docker

- ios/config.h.in
Change-Id: I3d8e38aac0ed7bd783cc0d8c79b2d4d08fa478a1
* Resolves: # 
> ENABLE_WELCOME_MESSAGE should now be 0 for iOS, not "false"

- net/Socket.cpp
Before ed5569da30a3f1d4cd29562c7d14eecd0ce512a8
we invoked handlePoll on all sockets in
each poll. But that's not true anymore.
Since i = _pollStartIndex; (line 432),
when we assigned previ = i; (line 451)
we made previ == _pollStartIndex, which
immediately broke the loop
while (previ != _pollStartIndex)
at line 438, causing handlePoll to be
called on one socket at a time (and
likely *not* the socket that had an event).
It's inefficient to poll and ignore the
result.
Now we do handle revents on multiple
sockets correctly and efficiently for
each ppoll() by going through all sockets
and handling based on whatever revents
gave us. We need to invoke the handler
of each socket to handle timeouts (i.e.
if we don't call the handler until
the socket gets an revent, we wouldn't
be able to support …
> wsd: invoke handlePoll on all sockets

- .gitignore
Automatically generated .log folder relate to typescript
was not being ignored
Change-Id: I0fa8bcbe9e3a9eeae8f1549d6d073865d06eb41d
> Add log directory (typescript) to gitignore

- browser/css/notebookbar.css
The dot above the save icon was not scrolling together
with its parent:
- Make sure the little dot is always under a parent with
position set to relative
- Adjust top position due to that ^ change
- It also fixes for narrow window on desktop.
Change-Id: I24278d09ace6e54769771fafb6f113ce9d4f1542
> Tablet: Fix Save icon floating when in presence of changes

- browser/src/control/Control.FormulaBar.js
- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Toolbar.js
- browser/src/layer/marker/TextInput.js
- browser/src/map/Map.js
formulabar: mobile: reuse TextInput for mobile IME
Fixes typing on Android using GBoard in Chrome
before this patch we didn't get any input due to
lack of keyCode, we need to use 'input' events
which are already handled in TextInput.js
This patch does that only for mobile case, later
we can try to unify it with desktop so we remove
our custom formulabar input even there.
mobile: fix TypeError, missing Intl API
this error was shown on socket disconnect on mobile Chrome in older
phone
> formulabar: mobile input fix

- browser/src/control/Control.JSDialogBuilder.js
this happens something when selecting column or row with shift or control key. then all next keypress events send not valid modifier....
> jsdialog: formulabar: reset shift key state after focus is lost

- browser/src/layer/tile/CanvasTileLayer.js
After commit:
change default Calc number of columns to 16384 (tdf#50916)
https://cgit.freedesktop.org/libreoffice/core/commit/?id=4c5f8ccf0a2320432b8fe91add1dcadf54d9fd58
Last column code is 'XFD'
> calc: correctly detect complete row was selected

- wsd/DocumentBroker.cpp
When in interactive mode, the user has a dialog
to interact with. The issue is that the user may
dismiss said dialog, the Kit process may stop,
crash, or otherwise exit. This basically leaves
DocBroker in a deadlocked state, expecting
input from the interactive document, which
will never materialize.
Here, we rely on the machinery already in place
for flagging such a DocBroker that has no Kit.
We check for said flag and stop DocBroker if
such a case is detected, exiting clearly.
Change-Id: Iecb91c49226da08567cdd2c5d050d458e2f0fc9b
> wsd: correctly stop DocBroker from interactive mode

- browser/css/cool.css
- Previously going into Help > About > View widgets would show a window
where the close button was rendered slightly out of the top of the
window
- This was because without the title taking up a line, the title bar
shrunk to be too small to contain the close button
- This PR makes sure that the title can never take up less than a
line in height
> Fix the close button on windows without a title

- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
Should make it more obvious which Kit disconnected from which DocBroker. Improved dumpState too.
> wsd: improve logging when kit disconnects

- wsd/DocumentBroker.cpp
We get stuck on exitting the app progressbar on mobile
with the interactive dialogs such as csv import or macro security
dialog, we have a different use case for killing the document
as in the normal case. We are not running a separate process
but a thread and we dont trigger regular killing use case.
This piece is not relevant for android because we always have
one connection through fakesocket until the main thread is killed
and it is waiting on the mutex to finish before we finally exit the
document activity.
Change-Id: I99bd333152d40a04f95d4747705a721112317bb2
* Resolves: # 
> android: fix closing the document on interactive dialogs

- coolwsd.xml.in
- coolwsd.xml.in is the file copied to coolwsd.xml to become the configuration file for COOL
- this PR fixes a typo in the languagetool section
Signed-off-by: Skyler Grey <skyler3665@gmail.com>
> Fix typo in coolwsd.xml.in

- common/Common.hpp
- net/WebSocketHandler.hpp
- net/WebSocketSession.hpp
- test/Makefile.am
- test/UnitBadDocLoad.cpp
- test/UnitCalc.cpp
- test/UnitClose.cpp
- test/UnitCopyPaste.cpp
- test/UnitEachView.cpp
- test/UnitHTTP.hpp
- test/UnitHosting.cpp
- test/UnitLargePaste.cpp
- test/UnitLoadTorture.cpp
- test/UnitPaste.cpp
- test/UnitRenderSearchResult.cpp
- test/UnitRenderShape.cpp
- test/UnitSession.cpp
- test/UnitTiffLoad.cpp
- test/UnitTileCache.cpp
- test/UnitUNOCommand.cpp
- test/UnitWOPIHttpHeaders.cpp
- test/UnitWOPILoadEncoded.cpp
- test/UnitWOPIRenameFile.cpp
- test/UnitWOPISaveAsWithEncodedFileName.cpp
- test/UnitWOPIStuckSave.cpp
- test/UnitWOPIWatermark.cpp
- test/WOPIUploadConflictCommon.hpp
- test/WopiTestServer.hpp
- test/helpers.hpp
- test/integration-http-server.cpp
The tests now run much faster. They now finish in almost _half the time_ they used to take prior to killing poco and fixing various issues.
- wsd: test: modernize UnitTileCache
- wsd: test: remove COOLWebSocket from WopiTestServer
- wsd: test: modernize some tests
- wsd: test: clang-tidy some args
- wsd: test: killpoco for UnitClose
- wsd: test: break WebSocketHandler polling when terminating
- wsd: test: correct shutdown of WebSocketSession
- wsd: test: replace hard-coded test timeouts
- wsd: test: killpoco test helpers
- wsd: test: improve Upload-Conflict tests stability
- wsd: test: correct shutdown UnitWebSocket
- wsd: test: killpoco for UnitBadDocLoad
- wsd: test: cleanup test helpers
- wsd: test: send WS close-frame only once 
- wsd: test: killpoco for UnitCopyPaste 
- wsd: test: …
> Kill Poco and Improve Tests

- .gitignore
- Makefile.am
- common/Common.hpp
- common/SigUtil.cpp
- common/Unit.cpp
- common/Util.cpp
- common/Util.hpp
- configure.ac
- gtk/mobile.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- test/UnitTimeout.cpp
- test/helpers.hpp
- test/integration-http-server.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
This adds code-coverage reporting in HTML via --with-coverage configuration. Here is the text summary that I get:
```
Overall coverage rate:
lines......: 72.8% (17748 of 24367 lines)
functions..: 83.1% (2330 of 2804 functions)
branches...: 39.4% (20080 of 51024 branches)
Code-Coverage report generated in /home/cool/online/gcov/html
```
- wsd: always use Util::forcedExit to properly cleanup
- wsd: remove default arg from SigUtil::killChild
- wsd: test: replace hard-coded test timeouts
- wsd: mark copied jails early
- wsd: support code-coverage report via --with-coverage
- wsd: minor code-coverage improvements
- wsd: extend the fork timeout when copying systemplate
> Code-Coverage

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
redline comments dont have position properties set
and some calculation needed in order to have it
and scrolling to comment relies on position property.
We have now instead getter for it and if it is a redline
comment it is calculated otherwise the default one is returned
because it is already set.
Change-Id: I6a3cefdd1c881783832de3de8fc1df7c849aad09
* Resolves: # 
> fix selecting redline comment jumps to scroll to beginning

- browser/css/jssidebar.css
Change-Id: Ia9cd8db9dcfa580f049c7212cfb01384d957d5cc
* Resolves: # 
This will ensure that branding can hide the border more easily and it does not seem to be necessary to force this with !important
> browser: Avoid important property on sidebar border

- browser/src/control/Control.NotebookbarCalc.js
Change-Id: I486c2709fd2dd5d133c4c46416dcea5ef0479fc1
* Resolves: # 
- Use unique ids for the row height and column width menus
- Use proper label "Row height" instead of "Row width"
> Unique ids and proper label for row height / column width

- browser/css/jssidebar.css
- browser/src/control/Control.JSDialogBuilder.js
It was removed in:
mobile wizard: hide unsupported items in table panel
commit 1aed5ddaa440c0d687708bd0ba7819499dd247fc
but now works
related to: https://github.com/CollaboraOnline/online/issues/4942
> sidebar: show Misc panel with Table Cell Color

- browser/src/control/Control.NotebookbarCalc.js
Change-Id: Ic654c9b3316a73a09033f58414c2e98043ccf0de
* Resolves: # 
Use proper ids instead of the generated ones from the uno command which are not valid otherwise:
Before: `StyleApply%3FStyle%3Astring%3DDefault%26FamilyName%3Astring%3DCellStyles`
After: `StyleApplyDefault`
> browser: Add proper id to StyleApply buttons on notebookbar

- cypress_test/integration_tests/desktop/calc/macro_spec.js
- cypress_test/integration_tests/desktop/calc/open_different_file_types_spec.js
- kit/Kit.cpp
'callback except-' is not used anywhere anymore.
Initially implemented in 68e597b to handle a certain invalid cursor event.
Removed in 986bcce due to a bug.
Not used anywhere else in the codebase.
Signed-off-by: NickWingate <nicholas.wingate03@gmail.com>
Change-Id: Ib620e6a33639f510c8f2415cf009e4d183a353fd
* Resolves: # 
> Remove residual 'callback except-' code

- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- The split cells test currently uses tunneled dialogs to make sure that
we can split table cells
- There is an open gerrit review to switch the split cells dialog to
JSDialogs (https://gerrit.libreoffice.org/c/core/+/137791) which is
blocked because the tunneled dialog needs to be removed in it, and
that fails this test
- This test needs to be temporarily disabled to give coreside a chance
to merge that review and build a new version of the libreoffice
archive. Once that has happened, this test should be replaced with a
rewritten version
Signed-off-by: Skyler Grey <skyler3665@gmail.com>
Change-Id: I0bb51e3cdbc04020e03c8d87696d014a0f693554
CC: @eszkadev @pedropintosilva
> Disable testing splitting cells

- browser/css/toolbar.css
- browser/src/control/Control.FormulaBar.js
unclutter formula bar surrouding elements by removing the visual
break and instead add padding. This is a partly cherry-pick
from 8f0f1c700
Change-Id: I4a9990a5709918d7cacfac2ef41b91281f9af54a
> Calc: address bar, remove w2ui break

- test/UnitWOPIFailUpload.cpp
- test/WOPIUploadConflictCommon.hpp
**Part 3**
**_Requires #4565 and #4566 for the tests to pass._**
A number of fixes and improvements to Save and Upload cases. Each commit explains the need for the change.
Most were found through tests (a few through reviewing code). Improved test coverage included (which fail without these fixes).
_Best to review each commit separately._
- wsd: do not enqueue messages on closed sessions
- wsd: detect lost upload on exit and dumpState once only
- wsd: test: better PutFile assertion
> Save and Upload Improvements: Part 3

- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Adds support to configure the minimum time between save and upload (in case of retrying failed attempts).
- wsd: add min_time_between_save_ms config
- wsd: add min_time_between_upload_ms config
- wsd: config: merge auto- and idle-save comment and make uint
- wsd: move the autosave interval into SaveManager
- wsd: cosmetic and logging 
- wsd: move minTimeBetweenSaves into SaveManager 
- wsd: move minTimeBetweenUploads into StorageManager 
- wsd: remove lastUploadTime as it is redundant
> Configurable Delayed Save and Upload

- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- This is a followup to 3ce47b0c1607b715fc300293789164608a49648e
(https://github.com/CollaboraOnline/online/pull/5106)
- This commit rewrites the split cells test to work with JSDialogs
(merged in https://gerrit.libreoffice.org/c/core/+/137791) and
re-enables that test
Signed-off-by: Skyler Grey <skyler3665@gmail.com>
Change-Id: I7901cfa1489618d005faffe68af0883e0ca998a1
CC: @pedropintosilva @eszkadev
> Rewrite testing of splitting table cells

- browser/css/jsdialogs.css
Change-Id: Id38951ddc79e99573008c63d4e6c7ed36fcc52a2
* Resolves: # 
The unoAutoSumMenu button has a different size than unoacceptformula button, which leads to a minor jump when clicking into the input field. Setting a fixed width solves this.
> browser: Give formulabar a fixed button width to avoid jumping

- browser/src/control/Control.UIManager.js
* Resolves: "Selected" state not displayed correctly after UI mode changed
This code added to the uiManager ensures that the Ruler, Statusbar and DarkMode toggle remain selected on the Notebookbar, after the UI mode has been changed.
> Display selection fix

- browser/src/control/Control.UIManager.js
Signed-off-by: ChrisGlad <chris.gladman2004@gmail.com>
This code fixes the problem that elements in the Notebookbar will
not be correctly displayed as "selected" after changing the UI
mode.
Change-Id: I4f889f8593029c375a06e17dbf1062bb9b9f5efc
> Fix UI Selection bug

- browser/css/toolbar.css
Follow up on the changes introduced in
4e075146b91c6ca3197fdf96d7bb5d75a73b350e
- Update toolbar.css with current valid aliases
- Which fixes all a couple of missing SVG console errors
Change-Id: I4eb96175d297b2a6962aa0ec6ab46b82cf060a34
> Fix outdated svg references in CSS files

- browser/src/control/Control.JSDialog.js
Since 22.05 popups (eg autofilter) are handled by the same
code as dialog (Control.JSDialog.js). Allow processing their
messages.
> jsdialog: hanlde popup updates correctly

- browser/src/control/Control.JSDialogBuilder.js
Follow up on the changes introduced in
4e07514
Make sure the explorable list runs iconURLAliases first before
insert image url
Change-Id: I9295fad934f000acdd27cac64b0c70284c0bbd2f
> Mobile: fix missing icon on hamburger menu top level

- browser/css/device-mobile.css
- browser/css/w2ui-1.5.rc1.css
- browser/js/w2ui-1.5.rc1.js
- browser/src/control/Control.Toolbar.js
- In classic mode, toolbar color indicators weren't visible when no
text is selected. The reason is that color indicators didn't have
border(outline) color.
- In fact, color indicators were just a box-shadow property. So,
it was not possible(?) to add properties like border and
border-radius.
- No need to use box-shadow property. A `<div>` tag can represent
color indicators.
- Removed box-shadow property.
- Added `<div>` tag that has `class="selected-color-classic"`.
Signed-off-by: Bayram Çiçek <bayram.cicek@libreoffice.org>
Change-Id: I1b1b68fdc015fd3719d1c59ef7f782036a5934a5
* Resolves: #2809
- Outline/border added to color indicator by creating `<div>` element.
- This commit only resolves outline/border issue in classic mode.
In classic mode: 
* Issues listed …
> Add outline to color indicator for classic mode

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
Revamped https://github.com/CollaboraOnline/online/pull/4576
commit 2d3313813488d23b7fd675e7ac08f2dfb07713bb (HEAD -> private/pedro/group_download_as-v2, origin/private/pedro/group_download_as-v2)
Date:   Fri Apr 8 18:19:37 2022 +0200
NB: Simplify group_download_as implementation and make it bigtoolitem
- Avoid using random UNO command (InsertGraphic) for download action
- Centralize download option (re-use bigmenubartoolitem)
Change-Id: Ie9cb8564acee8611221e0ff6f841de7b31b777e4
>  NB: Simplify group_download_as implementation and make it bigtoolitem

- wsd/DocumentBroker.hpp
Change-Id: Id004b635cfd8e77de85f932a3035870300ba1c47
> wsd: fix uninitialized DocumentBroker::_savingTimeout

- common/JailUtil.cpp
When bind-mounting is disabled, we do a best-effort
to unmount any lingering mount-points. This is a
cleanup that helps with leftovers. Here, we
do a debug log level in case the unmounting fails,
and error, otherwise, when bind-mounting is enabled.
Change-Id: I199d6234aebfd84e6be812e5b7d3758273086815
> wsd: log unmount errors only when mounting is enabled

- browser/src/control/Control.MobileWizardPopup.js
- browser/src/layer/tile/CommentListSection.ts
- Show error instead of throwing an TypeError exception.
- Prevent us from showing empty popup when removed comment.
noticed when testing: https://gerrit.libreoffice.org/c/core/+/138398
> comment bubbles: don't use undefined container on comment remove

- browser/src/layer/tile/ScrollSection.ts
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/impress/scrolling_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
- Draw the railway for vertical and horizontal scrollbars
- The railway should be 50% transparent on all apps, except for calc which should have a fully opaque railway
Signed-off-by: Skyler Grey <skyler3665@gmail.com>
Change-Id: I57975e52700f3b91782f9be40ad9864fc8c3baf2
*Note: Crossed out tasks were planned but have (on request) been moved to be in a later PR [not yet opened]*
> Improve the scrollbars

- browser/css/jsdialogs.css
Force placeholder to inherit the same rules as ui-treeview-body
Change-Id: I61ecde9e35812026683c655f6a2f9ead18e10d02
> Remove jump in impress anim sidebar when adding the first anim

- browser/css/jsdialogs.css
- This is too generic
- If in the beginning this made sense now we have to many elements
and many should not have hover states (invisible, labels etc)
Change-Id: Ice27ccb41cff73fa34b89453d99e3bb1fbc03edf
> Don't add hover states to generated jsdialogbuilder td elements

- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
problem: when we click on checkbox to filter the data in autofilter dialog the checkbox itself disappear
if that is expected behaviour then cypress test needs to modified if not bug needs to be fixed first before
enabling this test
Change-Id: I4dbfcf8abebe1c65e27c8c090bfce3ed0c59d086
* Resolves: # 
> cypress: temporarily disable autofilter test

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
after core commit:
https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-22.05&id=62d5622540c7251bb870a837b5ca6a836fac6f01
DumpAsPropertyTree: use more efficient overloads of JsonWriter::put
we use boolean not string
this also enables test broken by that core commit
> jsdialog: allow boolean as treeview entry state

- browser/src/control/Control.JSDialogBuilder.js
- it is needed for mobile wizard spin fields
Removes annoying bug in Chrome. When using spinfields in sidebar - when you click on "arrow up" it focuses "arrow down" what causes revert of the last change on next click.
requires code change: https://gerrit.libreoffice.org/c/core/+/138700
> jsdialog: find real input on setText action

- browser/css/override-vex.css
- browser/src/control/Control.Command.js
fixed:
- image overlapping with high res image
- shows empty bullet when highlight text is empty
- no space between bullet points and text
Change-Id: I0e3bcd11d9132913d69f8a7c74d21cc0b4ab3305
> feature locked dialog visual improvements

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- cypress_test/integration_tests/mobile/calc/number_format_spec.js
- cypress_test/integration_tests/mobile/writer/apply_paragraph_properties_spec.js
- cypress_test/integration_tests/mobile/writer/focus_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
Adding attribute by jQuery and testing in cypress was
not working: visible value was correct after change but
in DOM we had original value which was tested by cypress.
Use val() to setup value and have.value for cypress to test.
Unify inputs so we don't use attributes but always props.
> jsdialog: correctly setup & test value for spinfields

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/ScrollSection.ts
Instead of jump to the position on a scrollbar, the quick scroll
action (click above/below scrollbar marker) should move us one
page up/down.
> Scrollbar: step by step quick scroll

- .gitignore
- common/Util.cpp
- config.h.in
- config_version.h.in
- configure.ac
- kit/ForKit.cpp
- kit/Kit.cpp
- net/HttpHelper.cpp
- net/HttpRequest.hpp
- test/RequestDetailsTests.cpp
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
Eg. if only the version was changed, config.h was updated, and
everything was recompiled.
New structure, maintain these manually:
config.h.in - for configured variables that are stable if
configuration parameters are unchanged
config_version.h.in - for version/hash related variables
----
config_unused.h.in - still generated by autoheader with all
variables, don't use it
Change-Id: Id9a50a9f1e798a3b3814778d8683b7d7cb57bb29
> Split config.h into separate headers to avoid extensive rebuild

- test/Makefile.am
Due to this error:
[ coolwsd ] TST  testTileProcessed  [testTileProcessed] (+12566ms):
ERROR: Assertion failure: Expected exactly the requested number of
tiles Expected arrivedTile == [25] but got [28]
| TileCacheTests.cpp:1580
Probably since 2cc955f9109c0fc8443c9f93c1bf6bd317043cb5 (core)
Change-Id: Ie854a57e4241f2c8fbf8e3d769aba8a19981feb1
> Temporarily disable unit-tiletest

- coolwsd.xml.in
There are now too many download options to have each format as
an individual icon on the tabbed view. Plus with improvements
introduced in cbf5f1ad712a3d1eaff71a04ec022fe6424ba310
we can now safely set group_download_as to true as the default
value. Of course, it can still be switched to false if so
desired.
Notes:
Ideally, and if no one objects to it, we can later on and after
a period of testing remove this option and have only one way of
implementing/showing download options (as dropdown).
Change-Id: I1130684ec2ec54832f5a13648754d29ac71b9d35
> Set group_download_as to true as default

- wsd/AdminModel.cpp
- wsd/metrics.txt
continue to use the pid as a short-ish label to disambiguate metrics,
but also define the pid with more labels in the 1st instance.
doc_pid{host="localhost",key="https://localhost:9980/.../hello-world.odt",filename="hello-world.odt"} 1261609
doc_views{pid=1261609} 2
doc_views_active{pid=1261609} 2
doc_is_modified{pid=1261609} 1
...
Change-Id: I573f6d5c8ceb9a7daee83d1f2ee9f42b8e0cd089
* Resolves: # 
> prometheus: don't export string values.

- browser/src/control/Control.DocumentRepair.js
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.MobileWizard.js
- cypress_test/integration_tests/common/repair_document_helper.js
- cypress_test/integration_tests/desktop/calc/undo_redo_spec.js
- cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
- cypress_test/integration_tests/desktop/writer/undo_redo_spec.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/calc/undo_redo_spec.js
- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/undo_redo_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/undo_redo_spec.js
- cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
- cypress_test/integration_tests/multiuser/impress/repair_document_spec.js
- cypress_test/integration_tests/multiuser/writer/repair_document_spec.js
- The repair document dialog is a leaflet dialog
- As this dialog is online-side only, I'll use the JSDialog builder
directly rather than writing a UI file
- Most of the code to build the dialogs is already very adaptable from
looking at the protocol of existing JSDialogs that come from the
server & where the code goes, however a small change had to be made to
dialog modifications to allow us a callback function, as otherwise we
would send off to the server whenever we pressed on a list item
- Finally, if there's no list to show, we'll show a bit of text saying
that there's nothing, as otherwise it looks like an empty/broken dialog
Change-Id: Iab9e943a428e66b05e28819c2ee1001a2deffd2c
> Make the repair document dialog into a JSDialog

- wsd/AdminModel.cpp
hope it fixes #5206
@mmeeks for you ;)
-----
https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#label
> Labels are key-value pairs consisting of strings.
> prometheus: labels are always strings

- wsd/COOLWSD.cpp
Maybe solves NullPointer-Problem with this configuration:
```
{
"kind": "configuration",
"storage":
{
"wopi":
{
"alias_groups":
{
"mode" : "groups",
"groups":
[
{
"host": "scheme://hostname:port",
"allow": "true"
},
]
}
},
}
}
```
(PS: I am not a good C++ Programmer, so that is untested Code with an Idea to solve it - e.g. i do not know, if the `if` works that way)
Current we use as **workaround**:
```diff
{
"kind": "configuration",
"storage":
{
"wopi":
{
"alias_groups":
{
"mode" : "groups",
"groups":
[
{
"host": "scheme://hostname:port",
"allow": "true" ,
+                       "aliases": []
},
]
}
},
}
}
```
---
For @mmeeks :
We got NullPointer again (like told on wednesday), with Workaround is everything fine.
We believe that we find the Bug, and maybe this solve it.
> fix(remote_config_pull): nullpointer if alieses not defined in host groups json

- common/Protocol.hpp
- test/UnitWOPIAsyncUpload_ModifyClose.cpp
- test/UnitWOPISlow.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd: remove unused uploadLocalFileToStorage
- wsd: mark last-upload as failed in early-failure
- wsd: track modifying user commands
- wsd: state-dumping and comments
- wsd: move storage attributes to DocBroker
- wsd: test: modernize UnitWOPIAsyncUpload_ModifyClose
- wsd: test: enable IsModifiedByUser assertion
> Backport of the IsModifiedByUser Flag

- .cirrus.yml
This reverts commit 869f7f73af0a998e9c924ea70e19c887436fa125.
* Resolves: # 
> Revert "Attempt to fix FreeBSD node convas module not found error"

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Sidebar.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/calc/alignment_options_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
works with core fix: https://gerrit.libreoffice.org/c/core/+/139729
sidebar: show on demand
Previously sidebar was always active on launch.
This patch together with core fix changes that so
initially it is off and we don't waste resources
for rendering sidebar which is hidden just after short
time.
We don't know the state of sidebar (which deck is activated)
on the core side so in some cases we need to switch decks
in 2 steps: send SidebarShow, and when we received result
we change deck to other one or we do nothing. This allows us
to switch correctly the decks.
>  Save different sidebar states for Impress. (Szymon's version)

- net/SslSocket.hpp
ERR_get_error cleared the returned error,
which meant the subsequent call to print
the error in string form, using
ERR_print_errors_cb, didn't find anything
to report.
Change-Id: If131a8cc0d2c1d8bbf705ed38f144b38abf6c8c6
> wsd: improve SSL error reporting

- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
rollbackPastChange function already opens the menu so don't do it twice
regression from: https://github.com/CollaboraOnline/online/commit/fd0c49a0be757c047674164a941914d15c18fd17
> cypress: fix mobile repair test

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Sidebar.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/calc/alignment_options_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
works with core fix: https://gerrit.libreoffice.org/c/core/+/140035
sidebar: show on demand
Previously sidebar was always active on launch.
This patch together with core fix changes that so
initially it is off and we don't waste resources
for rendering sidebar which is hidden just after short
time.
We don't know the state of sidebar (which deck is activated)
on the core side so in some cases we need to switch decks
in 2 steps: send SidebarShow, and when we received result
we change deck to other one or we do nothing. This allows us
to switch correctly the decks.
> Save different sidebar states for Impress. (Szymon's version)

- browser/css/notebookbar.css
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Toolbar.js
- wsd/FileServerUtil.cpp
We can provide doctype extensions for save-as much like downloadAs but this will load the new file in the integration. instead of downloading
To achive this, args: {format: '<extension>' } parameter needs to be sent inside UI_SaveAs postmessage. Because the integration provides dialog with filename, there the extension will be set after the filename. Our save-as work flow already handles the rest.
Change-Id: I6005846047fc0b26ea07e8eeea965965ed1b87e7
* Resolves: # 
> added option to group save-as

- kit/ChildSession.cpp
Avoids logging an ERR.
Proper handling of that functionality is still a work in progress.
Change-Id: Id6bd985ee62e6cb76641d6f866f6318868b9b2b3
* Resolves: # 
> Add a dummy handler (for now) for LOK_CALLBACK_FONTS_MISSING

- browser/src/control/Parts.js
- browser/src/core/Socket.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- browser/src/layer/tile/WriterTileLayer.js
- browser/src/map/handler/Map.StateChanges.js
- common/MessageQueue.cpp
- common/Unit.cpp
- common/Unit.hpp
- kit/ChildSession.cpp
- kit/KitHelper.hpp
- test/TileCacheTests.cpp
- test/UnitTileCache.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/TileCache.cpp
- wsd/TileCache.hpp
- wsd/TileDesc.hpp
It is needed for Impress Master Page mode to provide different types of tile for the same part.
// Idea here is to keep CI green, this change doesn't change behaviour - it added optional 'mode' parameter for different tile commands with default/ignored value 0.
> Introduce 'mode' property to the tile requests

- browser/src/layer/tile/CommentSection.ts
Change-Id: I6eeb716c118778c1a386437c751bda3e9e3a5a24
* Resolves: # 
* Target version: co-21-11
> fix: calc: comments in frozen row headers aren't shown after scrolling

- common/JailUtil.cpp
It seems that on some systems it is possible
to succeed in mounting, but fail to unmount.
This is proving very problematic and it is
best to detect unmount failures and disable
mount-binding altogether.
Should avoid the issues seen in #5155 and #5164.
> wsd: disable mounting when unmount fails

- browser/css/jssidebar.css
Change-Id: Idd1b71e1b32a1367902a230eb9f43fe18321f856
* Resolves: # 
> Remove obsolete css rules for shadow-transparency items.

- common/JailUtil.cpp
- common/JailUtil.hpp
- kit/Kit.cpp
This guarantees that the jail directory is always
created, especially in case mounting fails and
we cleanup and fallback.
Also, move the directory creation and setting
the perms into a helper, and reuse.
> wsd: re-create the jail directory when mounting fails

- browser/css/partsPreviewControl.css
Mark as important so will not be overriden by the mobile-wizard rules.
Use primary color for selection so it will be visible...
Previously we had primary color for current slide (from mobile-wizard) and grey for other selected slides.
> slidesorter: use correct styles for desktop & selection more visible

- net/HttpHelper.cpp
- wsd/Admin.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/ProxyProtocol.cpp
If the connection is closed right after the response was sent then it's wise to add 'Connection: close' header to the response so that the client optimizes its behaviour: e.g. does not reuse the socket for further http requests. Normally  a client should retry a request if the reuse of an old socket fails and that should solve the problem but still this is an overhead.
Change-Id: I29f1498610c567024def3beb1ad7014f2c15a232
* Resolves: # 
> add 'Connection: close' header to http responses.

- wsd/COOLWSD.cpp
Since the request is really synchronous,
there is no benefit in firing up a thread
and doing an asynchronous request when
we will block until the result is in.
Luckily, we have a much simpler sync-
request API that avoids threads and
callbacks.
Also, avoid failure logs when no
infobar URL is provided.
Change-Id: I06a2f7fb042c8e8d5599bb06ecee5b1afa51911a
> wsd: simplify infobar fetching

- browser/css/jsdialogs.css
Signed-off-by: hanswang123456 <50556568+hanswang123456@users.noreply.github.com>
* Resolves: #5128
* Target version: feature/dark-mode
> fix(css):Improve dark-mode contrast, remove hover for jsdialog

- browser/test/bootstrap.js
- browser/test/load.js
Seemingly rejectUnauthorized doesn't make nodejs happy either for unknown reasons.
Change-Id: I99299489ba6af98c4088ee7b95c4d55d1291dfc6
* Resolves: # 
> perf-test: disable SSL for now, and print the right url.

- browser/src/control/Control.DownloadProgress.js
So round the value in the progress bar to integer.
Change-Id: I34058b2b8e04714eb7da60d8274660b06e583702
> browser: Paste progress bar has double precision

- browser/css/menubar.css
Before this commit, some actions were unreachable on tablets,
small screen factor laptops. Basically  when the web browser window
is smaller then the top bar's content.
Change-Id: I2e93540fa7b7d7bcf1a9f7e9f6697322528562f7
> Allow top bar to be scroll-able when in tabbed view

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/map/handler/Map.WOPI.js
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd/protocol.txt
When present and equal to 'true', the 'Repair' button and/or menu entry
is hidden in the UI.
Change-Id: If8075be479551e0d1a5fa03014aa5e4412578c31
> Implement HideRepairOption in CheckFileInfo

- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
This is needed, for example, for date type cells
for which the format language is set to default.
In this case the load language is used and it
determines the display/output format.
Change-Id: I49ec4940377b261971224d37ea5fbe8ed7006157
* Resolves: # 
> wsd: add lang param to conversion

- browser/src/control/Control.Menubar.js
Without this commit if the status bar is hidden, it's impossible
to bring it back and so the user is unable to:
- Search within readonly mode
- View the number of pages
- Zoom in our out via selecting the specific values
Change-Id: If30a0729862788f7475ce800b643db2b386722f3
> Enable Show Status Bar menu entry in readonly mode

- browser/src/core/Socket.js
The cursor will hide and the permission will be updated
after the document is re-connected.
Change-Id: Ib0a584371317adabe9898dad8bb0cd96717cefff
> browser: set the document view only if it is offline

- browser/src/control/Toolbar.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/WriterTileLayer.js
- kit/ChildSession.cpp
helps with:
- activation of a closed sidebar on master page activation
- parses correctly message with `mode` param, should be separated with `,` not a space
this is required for next set of patches which will activate the `mode` param
> masterpage: followup

- wsd/ClientSession.cpp
Handle corner-case when the embedded video has no extension.
> wsd: handle embedded video without extension

- browser/src/control/Control.Menubar.js
So user can have yet another visual cue that the current mode
is read-only
Change-Id: Ie7862e963603541c04d1b6662fbc7350f6e675a0
> Add read-only mode tooltip when hovering disabled menu items

- browser/src/layer/tile/CanvasTileLayer.js
This happens when second time embedded video was selected.
(Error in the browser console about wrong URL)
> Dont show error for wrong shape content

- test/UnitInsertDelete.cpp
Avoid unnecessary wait that spans dozens of seconds.
> wsd: test: faster UnitInsertDelete::testPasteBlank

- browser/src/layer/marker/TextInput.js
In mobile view there is no way to select a cell and type something into. We had to switch edit mode or use formula bar. So automatic percentage sign addition is useless on mobile view.
Change-Id: Ie0fca8121534a53304414d98e6fbdef82a349d89
* Resolves: # 
> Limit the automatic addition of percentage sign.

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.FileInserter.js
When we insert empty/not esiting image - we can continue...
> Dont set readonly on non-critical error

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
added button in file menu in desktop view in:
calc, impress and draw
added this button in mobile too.
this will allow user to check the property or change it (i.e: password)
Change-Id: Ie9b0776e291046231755739a3c0aa48323c67725
> UI: add missing file property setting button in UI

- browser/css/toolbar.css
Before this commit the extra space was not used plus
it was making the popup bigger without necessity.
Referenced in https://github.com/CollaboraOnline/online/issues/2015
Change-Id: I6b2ba82b3d522f9673e555fb4f762b563c3a9c99
> Remove insert shape dropdown extra bottom padding

- browser/html/cool.html.m4
There is no "file server" in the mobile apps that would expand such percent sequences. The generated cool.html file is used as is.
Change-Id: I046c23c13ade6195f3f4a8b395ede7c42fc46bd2
* Resolves: # 
> Fix the iOS app: Can't use %THINGIES% in cool.html.m4

- browser/css/toolbar.css
With the following commit
4e075146b91c6ca3197fdf96d7bb5d75a73b350e
we need to update css to use the same lc_linespacing.svg
Change-Id: Ibd7131a69765b29d69de6d2bb53d1407df363345
> Fix missing icon for Line Spacing: 1.5

- coolwsd-systemplate-setup
It seems the location of the NSS dynamic
libraries have changed recently. This is
true on Ubuntu 22.04 and it seems on
Clear Linux.
We expected to find them in /usr/lib but
they are now in /lib. We support both
now, so the systemplate should work on
both new and old systems.
The symptom of not having the NSS libs
is failure to open password-protected
documents. The tests failed, which
helped to reproduce and debug.
Change-Id: Ifb4cbc4e2c852464ffcdcc19801689ea60355042
> systemplate: include /lib/*/nss

- kit/ChildSession.cpp
We should just ignore that callback in the mobile apps for now.
Change-Id: Ic1e2f79b23d75433a1f4c491bc31e43d4ebbe3c2
* Resolves: # 
> Fix crash for LOK_CALLBACK_FONTS_MISSING in the mobile apps

- browser/src/control/Control.NotebookbarWriter.js
Accessibility checker seems hard to discover. Users tend
to look for such feature in the Help tab (near to Keyboard shortcuts)
and after all we have plenty of space to place it in the help tab.
Better to duplicate instead of moving the icon altogether since it has
been there and we might already have a user base that expects to see
it there. On top of that it makes sense to be together with other
review related action.
Change-Id: Ibb5fa8b681faa5a16267f8a23cdbff0ee0d42ec2
> Duplicate and place Accessibility Check in the Help tab

- common/Unit.cpp
- test/Makefile.am
- test/TileCacheTests.cpp
- test/UnitWOPIStuckSave.cpp
- wsd/COOLWSD.cpp
- wsd: test: reduce the duration of UnitWOPIStuckSave
- wsd: log the socket FD used to listen to client connections
- wsd: test: log multiple exitTest cases with different results
- wsd: test: enable tile-tests
- wsd: test: re-order tests to minimize execution time
> Re-Enable TileTests and Minor Misc Improvements

- common/Unit.cpp
- test/Makefile.am
- test/UnitWOPILock.cpp
- test/UnitWOPIStuckSave.cpp
- test/UnitWOPIUnlock.cpp
- test/WopiTestServer.hpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd: test: log multiple exitTest cases with different results
- wsd: log the socket FD used to listen to client connections
- wsd: test: reduce the duration of UnitWOPIStuckSave
- wsd: test: move assertLockRequest to WopiTestServer
- wsd: unlock the document only after uploading
> Unlock only after uploading

- wsd/COOLWSD.cpp
- wsd/HostUtil.cpp
when eTag header is not passed from remote server it keeps on parsing the new settings without clearing old ones
Change-Id: Iaad9fb6c0e7fd45be3e121b0c0bebaba17d90aab
* Resolves: #5436 
> fix: memory leak with remote config

- android/lib/src/main/cpp/CMakeLists.txt.in
This was added in commit 4f03f09c534d4b7ac7d397ed697cfebfacaf1895
(android: Gradle project and other stuff to build., 2019-02-12), but
Online doesn't need it, probably was a copy&paste mistake that went
unnoticed till today Michael S mentioned it on IRC.
Change-Id: Icb60cacfb9469a674db3f0f7a359ccdf01132558
> android: don't link against PocoRedis

- test/UnitWOPILock.cpp
- test/UnitWOPIUnlock.cpp
This fixes a race in UnitWOPILock and the
fact that the second view wasn't really
read-only due to empty extensions being
commentable, by default.
Also, improve UnitWOPIUnlock.
> wsd: test: fix UnitWOPILock once and for all

- Makefile.am
- test/UnitHTTP.hpp
- test/UnitInsertDelete.cpp
- test/UnitLoad.cpp
- test/UnitPasswordProtected.cpp
- test/UnitRenderingOptions.cpp
- test/UnitTimeout.cpp
- test/UnitWSDClient.hpp
- test/WopiTestServer.hpp
- wsd: test: header and forward declaration cleanup
- wsd: test: simplify UnitTimeout
- wsd: test: refactor client connection management
The client connection management had nothing to
do with the WopiTestServer and it was there
for convenience. The issue was that it was
not available to tests that do not need
the custom WopiTestServer and depending
on it would make them unnecessarily
complicated.
This adds a new intermediary class to manage
client connections in tests. The reason
this logic didn't move to UnitWSD or even
UnitBase is simply because the client
connection logic depends on the helpers
namespace and other test-specific code
that isn't available in COOLWSD. In short,
UnitBase and UnitWSD are primarily an
interface that COOLWSD and co depend on
and cannot contain test-specific …
> Test Improvements and Refactoring

- coolkitconfig.xcu.in
It does not work in Online.
Video playback controls are implemented by the browser.
Change-Id: Ib1aa2bb3d8820afb375a6a2c1a71d022a4dc119e
* Resolves: # 
> Hide MediaPlaybackPanel on sidebar

- common/Unit.cpp
- common/Unit.hpp
- kit/ForKit.cpp
- test/UnitTimeout.cpp
- test/UnitWSDClient.hpp
- wsd/COOLWSD.cpp
This adds support for multiple tests
within a single unit-test .so.
We did have many, many tests within
the converted "old style" tests already.
Except, they couldn't support the proper
event-driven tests, nor were they running
as fast as possible. They also blocked the
main thread in COOLWSD.
With this support, we can now avoid
creating a new .so for each test case.
This will reduce the effort to add new
tests and the build time. In addition,
the execution of each unit-test is
dominated by the initialization, which
takes in the order of 5 seconds. Running
multiple tests after this high load time
reduces the per-test average time.
Later we will support listing tests,
running particular tests (i.e. filtering)
and other debugging and troubleshooting
facilities.
Each commit is …
> Multitest Support

- browser/src/control/Control.Menubar.js
except if we are in presence of PDF
- Insert is needed there (insert > comment)
Change-Id: I20276e5690fa515a6fb497d1bb3447d0808f02d0
> Hide insert menu item when in readonly mode

- browser/src/layer/tile/CanvasTileLayer.js
Remove the comment mentioning the pdf.js issue,
which has been fixed since FF 87:
https://github.com/mozilla/pdf.js/issues/5397
Also remove the Edge and IE cases:
- Edge identifies itself as Chrome, and supports print dialog,
- IE is not supported anymore.
Follow-up to 403e9739cfce97738eac315e8518613e3cc6853d.
Change-Id: I7747ee27fccc52b90212ade2a2665dcbd8aa97d4
> Code cleanup around print dialog vs. directly opening PDF

- common/Message.hpp
- kit/Kit.cpp
- net/WebSocketHandler.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd: detect json arrays in messages
- wsd: notify the client when the doc URI is invalid
- wsd: kill poco
- wsd: log more info on exception in WebSocketHandler
- wsd: correctly set the Content-Type
- wsd: getServerURL is debug/test only
- wsd: reuse local variable
- wsd: log save failures more visibly
- wsd: when loading fails exit Kit
> Misc Small Improvements 

- browser/src/control/Control.StatusBar.js
So tablet user is able to check what is the current edit mode
by looking at the status bar
Change-Id: I4990ca748762eb100b0ca9e791b4ae2a0843f2f6
> Enable read-only status label for tablets

- common/Unit.cpp
- common/Unit.hpp
- net/WebSocketHandler.hpp
- test/UnitWOPICrashModified.cpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPIStuckSave.cpp
- test/UnitWSDClient.hpp
- test/WOPIUploadConflictCommon.hpp
- test/WopiTestServer.hpp
- test/lokassert.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd: test: return the correct type from hooks multi
- wsd: test: simplify WSD_CMD_BY_CONNECTION_INDEX
- wsd: test: log test start and finish visibly
- wsd: test: non-numeric filenames in WopiTestServer
- wsd: test: stop DocBroker when unit-test finishes
- wsd: test: fail -> onDataLoss
- wsd: test: capture the UnitWSD instance per DocBroker
- wsd: test: filter tests using COOL_TEST_OPTIONS
- wsd: test: log all test names before running
- wsd: test: capture the reason in exitTest
- wsd: test: improved assert logging on failure
- wsd: test: invoke configure for each test
- wsd: test: capture the UnitBase instance in WebSocketHandler
- wsd: test: filter subsequent tests
- wsd: test: do not invoke WSD test when finished
> Test Improvements

- coolwsd.xml.in
- kit/ForKit.cpp
- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
Previously this defaulted to 'trace' - now it can be configured, but still defaults to 'trace'.
Change-Id: I0ecf2f0b991cd8cc29dbde866dd4589be4ca7957
* Resolves: # 
> allow more verbose log-level during startup to be configured.

- net/HttpRequest.hpp
- net/Socket.hpp
This avoids wakeup warning us that the thread is not started to wakeup.
Change-Id: Ifd5c483717024cb1c30521433d0d10acead01e2f
* Resolves: # 
> Tag polls correctly as running synchronously in the client thread.

- cypress_test/Makefile.am
Xvfb init was missing for check-* run-* rules in Makefile so   make check was working but mentioned before not on some remote desktop sessions.
I used QEMU VM and was not able to run cypress-run as chromium was trying to connect to wrong DISPLAY
> cypress: fix check-* run-* on remote desktop

- browser/src/map/Map.js
When doing save as we reconnect the app to different spreadsheet. We need to invalidate cursor position and geometry to avoid showing incorrect selection.
> calc: refresh cursor on reconnect

- browser/src/control/Permission.js
Before this commit both mobile and is_lock_readonly (upsell)
were being affected. Namely, the edit buttons was not being
shown for presentations and drawings
Change-Id: I903ea43ca5ea1c94eec6b8f63b8b5626b8ee2203
> Fix PDF detection when deciding if edit button should be visible

- wsd/Storage.cpp
Change-Id: I485c5254a534365cd9defb726ed0eb705977361e
* Resolves: # 
> _userCanWrite variable is set to false when the host is read-only.

- wsd/COOLWSD.cpp
introduced in e0752419575f09fef3d770f8cccf78c92a2d8612 commit. clearing new remote config  after addWriteable resulted into removing data top of top layer from Poco::LayeredConfiguration. This patch makes sure to remove old layer of remote config before applying the new layer
Change-Id: If11bd6e4b3a0a9f4ee32ae9bb43b076479e9bd84
* Resolves: # 
> wsd:fix: memory leak properly

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
Visible when using the following core change:
https://gerrit.libreoffice.org/c/core/+/142974
Note: no need to have generic CSS rules for spinfields
only for the sidebar
Change-Id: Id2c9df00d1067537adb9ec5e3db0eab8bd1b2290
> Fix jsdialog spinfield jumping on hover

- net/HttpRequest.hpp
- net/Socket.hpp
- test/HttpTestServer.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Non-functional improvements and cleanups. Some performance wins, eventually, when we remove unnecessary sessionId look-ups.
- wsd: breakup getWritableSessionId and getWritableSession
- wsd: log closed-socket state on read explicitly
- wsd: http: improved logs
- wsd: use client_from_this
- wsd: pass ClientSession to removeSession
- wsd: pass ClientSession to uploadToStorage
- wsd: pass ClientSession to uploadAfterLoadingTemplate
> Misc Non-Functional Improvements

- browser/src/control/Toolbar.js
- don't print to PDF forms, it's unnecessary, and buggy at the moment,
- don't print/export comments as notes, they aren't relevant.
Change-Id: I511940f1a97e1c4a6ed6afb87165c9854df56b78
* Resolves: ...
> browser: adjust print/PDF export settings

- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Reduce the number of lookups in `_sessions` when we already have the ClientSession instance.
- wsd: pass ClientSession to finalRemoveSession
- wsd: pass ClientSession to disconnectSessionInternal
- wsd: pass ClientSession to checkAndUploadToStorage
> Avoid Repeated ClientSession Lookup

- cypress_test/integration_tests/desktop/impress/table_operation_spec.js
- cypress_test/plugins/selectorList.js
impress/table_operation_spec.js was failing due to split dialog converting to jsdialog writer/top_toolbar_spec.js failing due to change in name of clear formatting button
Change-Id: Ia70b80540ebfee66b1499b931c1fc32ab6f9df95
> cypress: fix: notebookbar test failing

- wsd/COOLWSD.cpp
The idea is that the integration should look for hasZoteroSupport capability, and if it's missing or false, then it should not enable setting of the Zotero API key. Instead, it could write "This instance does not support Zotero, because the feature is missing." or " ... because the feature is disabled in configuration."
Change-Id: Ibff9cb61ada062f59e8b2b63ddcdb7a9cf899b82
* Resolves: # 
> add hasZoteroSupport to /hosting/capabilities

- browser/src/control/Control.Zotero.js
Change-Id: Ie96550faaf3dc23e0aff0c289a38f717c6624e6f
> zotero: fix library dialog empty when collection has notes

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarWriter.js
- configure.ac
LibreOffice has its own solution to handle bibliography. It is outdated, and reportedly everyone prefers Zotero or similar solutions. Moreover in Online this feature does not work, because the bibliography database is a file in the jail that is not retained, and because tunneled dialogs have serious UX problems.
Change-Id: Ibf6195c0265c767b3acf94012ee3f82339cf34d3
* Resolves: # 
> Remove the 'Insert Bibliography Entry' feature

- browser/src/control/Control.NotebookbarWriter.js
Avoid using `Current Index` (uno text) and instead set custom
string that is easier to understand
Change-Id: I5057b7c974a5bd33f8af5b93f5bf6a85af916f98
> Fix UpdateCurIndex string

- browser/src/control/Control.NotebookbarWriter.js
- Prefer to show zotero related actions within a dedicated tab (instead
of adding those within references tab as it was previously). This,
hopefully is more familiar to user using similar interface elsewhere
- Show this new tab conditionally (if zotero is enabled)
Change-Id: I1690295724d54693aca68ade567e9d1076f26876
> Introducing Zotero tab

- browser/src/layer/tile/CanvasTileLayer.js
When we have 2 users:
A is typing on the page 0
B is at the bottom of the document
We scrolled view B when page overflow happened what caused "flickering". This patch prevents us from scrolling when cursor is still on the screen and visible.
> Don't scroll when cursor still visible on the screen

- common/Session.cpp
- common/Session.hpp
- test/UnitWOPIFailUpload.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
This fixes a corner-case where if we had a document that was not editable, but commenting were allowed (e.g. a PDF), we uploaded even when the Storage had UserCanWrite=false. Includes tests.
- wsd: set _isViewFileExtension for LocalStorage
- wsd: correct setting read-only and allow-comments
- wsd: move isWritable to Session and rename
- wsd: support isWritable flag in Session
- wsd: disable editing when Storage UserCanWrite=false
- wsd: test: add read-only storage tests
> Do Not Upload to Read-Only Storage

- browser/src/control/Control.Menubar.js
To show a checkmark for "Freeze Rows and Columns" item on hamburger menu, we have to set "checked" propery of the item according to uno command's status.
Change-Id: Icfc2ac07a84ed8a843b3bb8b2fe4c75de8ad9233
* Resolves: # 
> Set the checked state of the FreezePanes item

- browser/src/map/Map.js
The code that is conditionally called based on that check verifies using ThisIsAMobileApp anyway.
Change-Id: Ic86cf102e061d90bedecb6efcb4ef171dc494004
* Resolves: # 
> Use window.ThisIsAMobileApp instead of checking for iOS or Android

- common/Util.cpp
- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- test/UnitCopyPaste.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPIHttpRedirect.cpp
- test/UnitWOPIHttpRedirectLoop.cpp
- test/UnitWOPITemplate.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
These patches reduce the number of superfluous WRN log entries significantly. Using the unit-tests as one reference, the number of warning log entries go down from around 2800 to around 170. The goal is to remove noisy logs without sacrificing the usefulness of the warnings, as they were designed. The commit logs may have more information.
- wsd: test: better post-close check in UnitCopyPaste
- wsd: preserve close reason when disconnected from Kit
- wsd: better log levels
- wsd: wait InitialPingDelayMicroS before first ping
- wsd: send WS close frame only when we have a socket
- wsd: do not warn of expected DocBroker disconnection
- wsd: support flushing control in WSProcess::sendFrame
- wsd: request Kit termination early when unloading
- wsd: do not send duplicate 'disconnect' to the Kit …
> Reduce Warning Logs

- kubernetes/helm/README.md
- kubernetes/helm/collabora-online/templates/configmap.yaml
- kubernetes/helm/collabora-online/templates/deployment.yaml
- kubernetes/helm/collabora-online/values.yaml
- now works with default configuration
- updated readme
- fixed unknown field "spec.terminationGracePeriodSeconds" in deployment.yaml
error. This field should be defined in pod spec not in deployment spec
- improved how aliasgroups are defined in helm chart
- change default to kubernetes "Deployment" instead of "StatefulSet"
- added support for kubernetes hostAliases
Change-Id: Ief1e2b3f0ea130425853babbd28462d48e50280f
* Resolves: # 
> updated helm chart

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.Zotero.js
user was allowed to select language without selecting the style, if style is not selected language data will also be not written in the doc.
force user to select style too if want to set the language.
Change-Id: Ie323b19189858e601f3fa979d747d7c688e4baf1
> zotero: fix locale drop down showing incorrect language

- browser/src/control/Control.ContextMenu.js
if command "None" and empty item text, there is
an unhandled exception, and no grammar suggestions are shown.
Change-Id: Ie2c832a2a3ff7fe9944024fa003370819b16a432
> browser: menu: ignore menu item with empty text

- browser/src/control/Control.JSDialogBuilder.js
There was a bug in the core with duplicated filds, also we can use original numeric argument to pass colori (tdf#150339). Let's don't use string color so we can remove that from the core in the future.
Related core commit: https://gerrit.libreoffice.org/c/core/+/144866 Resolves: tdf#150339 two arguments called "Color"
> jsdialog: don't use deprecated string color parameter

- net/Socket.cpp
I had added some extra debugging output to the !MOBILEAPP branch to log values of timeoutMaxMicroS and timeoutMaxMS and was wondering why I saw things like:
timeoutMaxMicroS=5000000 timeoutMaxMS=5009
and
timeoutMaxMicroS=0 timeoutMaxMS=9
Change-Id: Iac8599ce5b00ef90d62eabc29c5d92858e276bb6
* Resolves: # 
> Fix error in conversion from microseconds to whole milliseconds

- browser/src/control/jsdialog/Widget.TreeView.js
unified header and no header treeviews
icon shouldn't contain old extension
> jsdialog: use unified naming for treeview icons

- browser/package.json
- test/.gitignore
On every build, nodejs (v12.22.9 for me) re-sorts
the packages in package.json. I expect this is
the case for everyone, so best to commit it sorted.
- gitignore: differentiate files from dirs
- browser: package.json always get resorted anyway
> Misc Environment

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/core/LOUtil.js
Change-Id: I8497a6b34186ce4167e4f864579a49a7d9910fb6
* Resolves: # 
* Target version: co-22-05
hide fontworks ui for non-odf files. This should not be ported to master where the fix is underway in core master.
> hide fontworks ui for non-odf files

- gtk/mobile.cpp
Also, no reason to append a null byte to it.
Don't know why this worked even when not escaping "dangerous" characters. Does Webkit have a more relaxed lexical analyser?
Change-Id: Idfedcbf11a9ee565b954ba972e7e3bc9b804a122
* Resolves: # 
> Actually use the safer (escaped) string we construct

- browser/src/main.js
Note that the code changed is inside an anonymous function that is called with one argument: window, for the function parameter called global. Thus the assignment that this change removes sets window.socket.
The window.socket variable is not used by code later, so this change can be this minimal.
The window.socket variable has earlier been set to the WebSocket object used to communicate with the COOL server. Let's keep it for that purpose. app.socket is the app.definitions.Socket object. Even though JavaScript is not type-safe, it is very confusing to use the same variable for completely different object types at different stages in the code execution. I am working on some new code that will want to access the WebSocket object also later. …
> Don't pointlessly assign global.socket = app.socket

- browser/src/layer/tile/AutoFillMarkerSection.ts
- browser/src/layer/vector/CRectangle.ts
The cursor should minimally obscure the cell content - so the border should go outside and over the cell border, and the white contrast line inside it.
Similarly the autofill handle should not obscure the number in the cell you're trying to read - so move it out and down to a more familiar position, shrink the size somewhat, and correct the white boarders around it too.
Change-Id: Ib107adc2927172d69b8cd9a6523b50327d4f81cb
* Resolves: # 
> calc cell cursor: get the layout and sizing right.

- browser/src/control/Control.Zotero.js
- browser/src/control/Signing.js
- browser/src/core/Util.js
- browser/src/layer/tile/WriterTileLayer.js
now odf documents will by default use refmarks,
MS docs will use field marks by default
Change-Id: I57ef5de9bef8d1e5f6b5029e478d9a43e38dbc4d
With reference marks, citation renumbering will not work as of now due to the core not sending remarks in sequence of them appearing in doc. All else should work fine. core patch work is in queue. MS doc formats will work as expected
> Zotero refmark

- browser/css/btns.css
Before this commit, browsers such as chrome (without enabling
experimental features) were not supporting those float values
Change-Id: I2530e7bf46d161ac980559c181a4e03947edbeee
> Add float logical values fallback for buttonboxes

- browser/css/jssidebar.css
These have no effect on the ui-expander-content since they are set to display: block somewhere else (jsdialogs.css) plus, (and even testing with flex) this does not seem to improve or fix anything
Change-Id: I0260f44413ff46f79b9ea6a15e154ee62fb1e53f
> JSSidebar: remove non-effective rules for expanders

- browser/css/jsdialogs.css
Before this table columns were getting "glued" (content of one
col would end and immediately would start content of another col).
Plus, we were having table content normally aligned to th start
while headers were being centered aligned
Change-Id: Ie0908c26d1e7bedc37b3c5d768d941b091946524
> JSDialog: Add padding in between columns and fix th alignment

- browser/css/cool.css
On Windows firefox auto setting is not handled properly. Scrollbar flows on the sidebar elements. We use thin instead.
Change-Id: Ife27f461639e6b034ac9071624d628cd35709191
* Resolves: # 
> Use thin instead of auto for scrollbar width

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/core/LOUtil.js
Change-Id: I8497a6b34186ce4167e4f864579a49a7d9910fb6
* Resolves: # 
Hide fontworks ui for non-odf files. Revert this when actual fix lands in core master.
> browser: hide fontworks ui for non-odf files

- browser/src/control/Control.Zotero.js
Before this commit, when opening a document with citations,
citations would be updated and the document refreshed but without
any information of what is happening
Change-Id: I474e8cdf9c31e18027501ebfc9bd6dd2f55a58a5
> Show citation snackbar also when loading up document

- browser/js/global.js
This reverts commit 089b6d235a0e38d5b1d021fab024becc2def0ada.
Reason for revert: For packaging builds the global.js is in minified form hence marker comments are not present and it is difficult to extract the css url renamer function without js-language analysis tools or packages - this needs more thought.
* Resolves: # 
> Revert "share css-url renamer with branding"

- browser/src/layer/tile/CommentListSection.ts
In case of desktop browser window whose size is only a little bigger than the page, our native comments get collapsed and we use vex. In this case don't close the comment dialog on clicking outside the dialog or when switching browser tabs.
Change-Id: I92c9d800d58a6910d6df01371e6748c864641cff
* Resolves: # 
> writer: vex-desktop: clicking away drops comment

- browser/src/control/Control.Zotero.js
style settings were treated as html instead of xml, which caused attributes to lose its camelCase naming, due to which some attributes were unrecognised and caused regression
Change-Id: I34f211c54f9692ec67e08a872a68f516b1f82944
> zotero: fixed style attribute storage in xml

- browser/src/control/Control.Zotero.js
online stores keys as item id,
but other softewares use numbers for id and no other fields store keys. keys are required in order to fetch the data from API. So extract the item key from item URL
Change-Id: Ib2d25df81f975d0e926627408047b79c624394fb
> zotero: extract item key from item URL

- browser/css/jsdialogs.css
with the introduction of showModal:
https://github.com/CollaboraOnline/online/pull/5518 we now have
a type of a dialog that, without this commit, can grow without
limits and can be as small as its content which is not ideal.
Change-Id: I8768925377606924fd70fab8be40b0b755d802ac
> Add min and max width to jsdialog modalPopup

- kit/Kit.cpp
I can only assume that recent LOK's often don't have any lingering timeouts for cursor blinking or whatever, such that we get an infinite wait passed as a negative microseconds-count.
Best not to interpret that as a zero wait to avoid a busy loop.
Change-Id: If79228af969f4598f07681deb355c72f72602d19
* Resolves: # 
> kit: default timeout to ~5 seconds when we get a negative wait.

- browser/src/control/Control.Header.js
- browser/src/control/Control.RowHeader.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ScrollSection.ts
Another method is used for Calc while scrolling.
Remove unnecessary call to draw in control.header.js Add condition for draw calls while scrolling on desktop view. Scroll bar is visible by default on desktop.
Remove commented-out code.
Change-Id: Iaaa0267c63a9a92aa67786231baf53a625541440
* Resolves: # 
> Disable start/stop updates for Calc.

- browser/src/control/Control.Zotero.js
- browser/src/control/Toolbar.js
- allow reading bibliography properties on load without api key
- if fieldType is missing - use default
> Zotero: don't show errors on load

- browser/Makefile.am
Helps in the hopefully rare cases where you need to see what code some error message points to. Otherwise bundle.js will have extremely long lines, and many editors have a hard time with such. (For example: Line 1, column 2949562.)
Change-Id: I229814e985348e94c8cda2d88b77ad1ea4b74ae7
* Resolves: # 
> Limit line length in uglified bundle.js file

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/unocommands.js
Add button that opens the page number wizard in the Writer notebook bar
Signed-off-by: Paris Oplopoios <paris.oplopoios@collabora.com>
* Resolves: # 
Adds a button in the insert tab in the notebook bar that opens the one step page number wizard dialog.
co-22.05 patch: https://gerrit.libreoffice.org/c/core/+/144998 (not yet merged, should be merged before this PR is)
> browser: Add PageNumberWizard button in notebook bar

- browser/src/control/Control.Zotero.js
- when api key is incorrect - show snackbar
- when api key is empty but set - integrator has feature implemented so don't show our warnings about empty API key
> Zotero: error on wrong api key

- browser/src/control/Control.JSDialog.js
Similar to  LokDialog _onDialogClose, after the closing a JSDialog we should change the focus editor again.
Change-Id: I348ead91838703590d5b9753d6028ff7f70f6111
* Resolves: # 
> Switch focus to editor after JSDialog close event

- browser/src/layer/tile/CalcTileLayer.js
* Resolves: # 
Ability to switch between RTL/LTR layout in a sheet based on status provided by the core. A patch to add menu UI element for this switch is in the PR https://github.com/CollaboraOnline/online/pull/5570
- Fix offset in mouse events just after layout switch.
> calcRTL: switch between RTL/LTR layout in a sheet

- browser/src/layer/tile/CalcTileLayer.js
Change-Id: Ie5ff495d5ea6a75963f0379bbb670b3d04f6c656
* Resolves: # 
calcRTL: sync map area after RTL mode switch using uno command else there will be an offset in x direction due to the changed position of row headers.
> calcRTL: sync map area after RTL mode switch

- browser/src/control/Control.JSDialogBuilder.js
it confuses our selectors for focus widgets when
widget is hidden. unfortunately this property was
added to the inner node not top one so we don't see .hidden class. listbox doesn't need tabindex at all so just remove it
> jsdialog: listbox doesnt need tabindex

- browser/css/jsdialogs.css
Before this commit, the text in a dropdown could be overlapped by the
triangle (arrow). Example: Insert > Page number dialog
Change-Id: I770acb10b89239bce280cf44ad56b9ec2c3a8264
> Fix dropdown's arrow position

- browser/css/btns.css
Primary buttons, secondary buttons and others are getting styled
differently for the same 'disabled' status. Plus, they are react
on hover which can lead the user to wrongly think they are active.
- Fix inconsistencies and make it clear that they are all disabled
Example dialog: Find and replace
Change-Id: I45be52ecda264d0af9a53a70c222d1047a3cdf73
> Fix disabled buttons inconsistencies

- coolwsd.xml.in
Java & beanshell macros are unlikely to work, since they would require a JVM in the Kit process.
Change-Id: I390fb66d7aa835530dd7d2210fd8e1e89cdba325
* Resolves: # 
> Improve macro option documentation.

- browser/css/toolbar.css
Before this commit, on chrome/mium, menus such as
image or save as in the tabbed view (and with the browser zoom
set to bellow 80%) were being displayed with scrollbars.
Change-Id: Id32e86229fe5d7aad293d24a20c9bfa555fbe78b
> Fix w2ui menus appearing with unnecessary scrollbars

- net/HttpRequest.hpp
- net/WebSocketHandler.hpp
- test/HttpTestServer.hpp
- test/UnitWOPIAsyncUpload_Close.cpp
- test/UnitWOPIAsyncUpload_ModifyClose.cpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPIHttpRedirect.cpp
- test/UnitWOPITemplate.cpp
- test/UnitWOPIWatermark.cpp
- test/WopiTestServer.hpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
This replaces the hard-coded status-code
numbers with named compile-time constants.
Change-Id: Ibe678fb2c533b29efd696e4430f5377523eeb298
> wsd: http: define named HTTP status codes

- browser/src/control/Control.Zotero.js
sections are used to represent bibliography when citations are used as refmark
Change-Id: I4094cf053cb3fe1c86eb7f7f0a95816fb51fa8c7
* Resolves: # 
> zotero: added unlink citation support for section

- wsd/TileCache.cpp
If we are not caching tiles, it is misleading to log "Saved cache tile".
Change-Id: I0e0ec446d5edf266ea4acb42883c49d5f7063763
* Resolves: # 
> Avoid misleading wording in log

- common/RenderTiles.hpp
The default would be `std::thread::hardware_concurrency()` which can be ridiculously high for the WASM case.
Change-Id: I77902a58b96248d7afe638a039886712516fe905
* Resolves: # 
> Leave ThreadPool max concurrency at 2 for Emscripten

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Toolbar.js
- browser/src/core/Socket.js
- browser/src/map/handler/Map.WOPI.js
- common/FileUtil.cpp
- common/FileUtil.hpp
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
It allows to export PDF directly to the storage, without need to download it.
This is copy of the save as functionality flow (reuses interaction with integrator)
`Save as` scenario looks like:
1. we sent UI_SaveAs to integrator
2. Integrator opens dialog, user selects target file name, integrator sends response to us
3. client sends to server `saveas` with target file name and format
4. we export file locally on the server
5. server uploads local file to the integrator's storage
6. server sends message to the client
7. client reloads app, by opening new file
Differences in export:
* In point 4. we use uno command to open additional dialog with options. After that we receive callback: LOK_CALLBACK_EXPORT_FILE with: PENDING or ABORT status. Then again after file was exported we got …
> Export PDF to storage

- wasm/wasmapp.cpp
- wasm/wasmapp.hpp
- wsd/COOLWSD.cpp
Apparently handle_cool_message() gets called from a web worker thread and then using emscripten_run_script() in wasmapp.cpp to run a JS snippet that refers to the 'window' variable will not work. That variable exists only in the main thread. So use MAIN_THREAD_EM_ASM() instead.
Hardcode the document URL for now also in wasmapp.cpp.
Try to send the HULLO message from COOLWSD::innerMain().
Change-Id: Ic48042c6d0c6239a3b82e74f0565056a15f3d98d
* Resolves: # 
> More WASM hacking

- browser/css/jssidebar.css
There is an element displayed as a column before ratio
and we then hide it which is fine but, when ratio label
becomes to lengthly (Seitenverhältnis beibehalten) it then
gets cropped due to lack of space.
- Make it span across columns
- Do not align to the end
- Remove left margin from checkbox
Change-Id: I02ec7a608c0b330a52fa70db3b453fe04fefa805
> Sidebar: Fix to allow ratio to span across columns

- browser/src/control/Control.UIManager.js
When we click empty part of notebook bar, focus should be on sheet. Without this patch, focus is on browser itself and CTRL+S saves the HTML instead of current document.
Change-Id: Ia0a89ae761eeeb3bb21a655c5181425df19e1c94
* Resolves: # 
> Keep focus on sheet if empty part of the notebookbar clicked

- configure.ac
Pass the absolute pathname to directory that contains a tree of additional files you want to be available in the WASM in-memory file system. Relevant only if you build for WASM with Emscripten, i.e. with --host=wasm32-local-emscripten.
(This is not usable without my still uncommitted / unpushed WIP hacking.)
Change-Id: I97a4651bed89bf35c50b009e04ddaa3e03aa8006
* Resolves: # 
> Add --with-wasm-additional-files=<path>

- browser/html/cool.html.m4
- browser/src/core/Socket.js
- browser/src/main.js
- wasm/Makefile.am
- wasm/base64.hpp
- wasm/wasmapp.cpp
- wsd/COOLWSD.cpp
Now I hope things are initialised in the right order and the plumbing gets set up so that messages are passed as expected. It seems to work most of the time.
Main changes are:
- The online WASM executable is built using the -s MODULARIZE -s EXPORT_NAME=createOnlineModule options. This means that the WASM runtime is not automatically initialized and the main() function is not automatically started. Only when the createOnlineModule() function is called is that done. Calling exported C/C++ functions is a little bit more complicated.
- Code to actually Base64-encode strings to be executed as JavaScript when expected is now present in wasmapp.cpp. (After being passed through the Base64ToArrayBuffer function on the JS side.) Whether this is actually necessary is not fully clear, but to keep the …
> Make the temporary "WASM app" work

- browser/js/global.js
- browser/src/main.js
- configure.ac
- wasm/wasmapp.cpp
You now must pass --with-wasm-additional-files=<path> where path contains a file called sample.docx.
Change-Id: I21e62feb6282833a5d60b31db26328eda63cdaea
* Resolves: # 
> Change hardcoded sample document name and verify that we get it

- browser/src/control/Control.Menubar.js
Signed-off-by: Paris Oplopoios <paris.oplopoios@collabora.com>
Change-Id: Ibb92c17894166276c0e0ef33736522b282fea993
* Resolves: # 
Adds the page number wizard as a button in the compact view Insert menu
> browser: Add page number wizard to compact insert menu

- test/UnitWOPIFailUpload.cpp
- test/UnitWOPISaveOnExit.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd: set IsExitSave header only when unloading
- wsd: move setForced attribute closer to usage
- wsd: set IsExitSave attribute before uploading
- wsd: test: add IsExitSave check in UnitWOPIAsyncUpload_Close
- wsd: merge the storage attributes after uploading
- wsd: test: better UnitWOPISaveOnExit
- wsd: fix always_save_on_exit
- wsd: test: add UnitSaveOnExitUnmodified
- wsd: better storage attribute handling
> Storage Attribute Fixes and Improvements

- wasm/wasmapp.cpp
LOKit will be initialised in the lok_init_2() call in lokit_main() in Kit.cpp. This change also puts setting and getting the LOK_OPTIONS environment variable in the right order.
Change-Id: Iee6f5adcb60bb887083c67666c2d597a15686bf9
* Resolves: # 
> There is no need to call lok_cpp_init() here

- wasm/Makefile.am
Change-Id: I520aa232f6ac51a6a57f36d8ac775150aa095a4d
* Resolves: # 
> I don't see the reason to use the intermediate libonline.a for WASM

- browser/src/control/Control.Zotero.js
if document contains existing zotero citation,
restrict user from changing the field storage type.
currently online does not have any ways to change the field type maybe in future we can add some core APIs to support this
Change-Id: I58caf403744431d34344f5a1cb635781409d7e68
> zotero: restric user from changing field type

- browser/Makefile.am
to browser\dist, otherwise it has to be done by hand after every wasm build.
Signed-off-by: Balázs Varga (allotropia) <balazs.varga.extern@allotropia.de>
Change-Id: I46c432116d0d42016dfc1573009d284f82c52114
* Resolves: # 
> WASM: Copy all the necessary files from builddir\wasm

- browser/src/map/handler/Map.Keyboard.js
F5 for slideshow, too.
Regression from 47c52b90f3a295e29106a61596645e774949a0aa
Change-Id: I056703f575460076693b245f790c7284854162be
> browser: Make navigation shortcuts work in read-only mode

- browser/src/control/Control.Zotero.js
In cases where zotero item is added by a user and another user opens the doc, if the new user does not have that item in the database, he may fail to do activity related to that item, so we warn the user when we are setting up the zotero
Change-Id: I9056f38334cb8d9b127ddb594adb083d25bd4472
> zotero: added warning for unreachable citation items

- browser/src/control/Control.DocumentRepair.js
Without this change focus is on sheet and ESC does not close the dialog
Change-Id: Ib60e681726393c67b38101d6eb48e3693ba156e3
* Resolves: # 
> Set inital focus widget for repair dialog

- common/Protocol.hpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPISaveOnExit.cpp
- wsd/AdminModel.cpp
- wsd/ClientSession.cpp
Resolves #5450
- wsd: break cyclic setModified call
- wsd: const and minor cleanup
- wsd: more accurate possible-modification flagging
- wsd: test: simplify UnitWOPIExpiredToken
> Modified Flag Handling

- wasm/wasmapp.cpp
We are logging what we are evaluating as JavaScript later in the function anyway.
Change-Id: I79972ec585dee128bbcca910def1d46e8134cdc5
* Resolves: # 
> Bin superfluous logging of what we are about to send to the JS bits

- browser/src/control/Control.Command.js
If we have already a feature unlock dialog open, don't let open the second one.
Change-Id: I7c7235bc1a64c48ba69f11d0599bbb9839b7fe71
* Resolves: # 
> Prevent double feature unlock dialog

- wsd/ClientSession.cpp
When copying is disabled, we still allow
copy/pasting *within* the document. What
is disabled is exporting the copied data
to the browser.
Luckily, this code was broken, and it
wasn't really blocking .uno:Copy at all.
Change-Id: I50a01eefbe1de3758b4451385bbc51fbde5878a8
> wsd: .uno:Copy is allowed for internal use

- browser/src/layer/marker/Cursor.ts
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
Problem: pointer style was set up for a <div> element wrapping the map
pane, anyway a further <div> element in the middle had the pointer
style always set up to 'text', so any incoming mouse pointer msg had
no effect.
Now the pointer style is set up on the same <div> element.
Moreover I noticed that in writer mouse pointer hovering over an
edited text box had a wrong style. This commit fix this issue, too.
Change-Id: I3f62908b00ab748d19a3651270babb926252fe21
> handle incoming mouse pointer style msg

- browser/src/control/Control.NotebookbarBuilder.js
Swap the ID names of the font name combobox elements and don't add the "select2-selection--single" class.
Unfortunately, this change does not set the height of the font name combobox to the font size combobox. I made a few tries at overriding the CSS that sets the height of buttons to 36px but I was unsuccessful.
> Fixes for bugs in TestFlight2 release

- cypress_test/integration_tests/desktop/writer/help_dialog_update_spec.js
* Resolves: # 
Has several problems stopping tests from passing:
~~- [ ] Running entire spec causes all 11 tests to hang on 'pending' with no progress (may just be an issue on my end)~~
- Just needed the `UPDATE_SCREENSHOT=true` tag
> Fix writer/help_dialog_update_spec.js spec issues

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Toolbar.js
- this reduces code we need to show buttons (uses customtoolitem to invoke actions instead of new widget implementation per button)
- shares code between notebookbar and menubar better (without constructing menubar classes)
- makes us sure we keep focus on map after click on such buttons
- more conversions can be done later, to finally remove menubartoolitems
> Simplify notebookbar buttons code

- wasm/poco-1.12.4-emscripten.patch
Not sure why I now suddenly needed this, too, when I recompiled Poco for WASM (with different options than before).
Change-Id: I7221947e0cd2264535b6d34e0640b95d7cfc7cf4
* Resolves: # 
> Drop POCO_HAVE_FD_EPOLL for Emscripten

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Menubar.js
This fixes #353
For now add only the .uno:DefinePrintArea and DeletePrintArea
- Edit triggers a tunneled dialog and thus is not ready for mobile
- Add (allows to add multiple) is should not be added to mobile until
Edit is available
Change-Id: I27b5377d00080e745aab465da4dd65fffeaa3217
> Mobile: spreadsheet: Allow user to define and remove print area

- test/UnitWOPILock.cpp
- test/UnitWOPIUnlock.cpp
- test/WopiTestServer.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
Resolves #5870.
- wsd: minor log improvement
- wsd: test: support controlling the response to LOCK/UNLOCK
- wsd: avoid function-local static configs in LockContext
- wsd: detect unuathorized locking/unlocking response
- wsd: handle errors from locking/unlocking a document
- wsd: test: new test to verify refresh lock behavior
- wsd: test: minor cleanup of UnitWopiLock
> Improve Lock Refreshing

- browser/src/control/Control.NotebookbarWriter.js
Since the helptab is shared between different doctypes we need to
make sure that writer's accessibility check doesn't bleed out to
other doctypes
Change-Id: Ic4d35fe080cbefc2564db1a250dbf6d62274de69
> Accessiblity checker tabbed item should only exist for text doctype

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.UIManager.js
All modals shown with uiManager.showInfoModal should have overlay which helps to focus on modal dialog.
> jsdialog: show overlay for all modals

- fuzzer/HttpResponse.cpp
The max input size is 16384, so in case the input is saved after each
run, then this can allocate ~300MB of memory. This is considerable
amount, given that the upper limit of the fuzzer process is 2GB.
Change-Id: Ieedb6a537d5b539255ed8bacd79ff23db3c15e9f
> fuuzer, httpresponse: clear state before each run

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/control/Control.Notebookbar.js
It was possible to use only one tab control.
Now useSetTabs parameter for builder is introduced which defines if we want to use custom placement
of tabs handled by the parent container or put
tabs in the place where they are defined in JSON.
Custom placement is needed in mobile-wizard and notebookbar as for them tabs needs to be placed at the top bar.
> jsdialog: handle multiple tab controls inside dialog

- browser/src/control/Control.Zotero.js
sending requests without citation keys returns bibliography for all the items in library this causes problem is the document already has some kind of bibliography which is updated unintentionally
Change-Id: I34976f94bf3cbb6d07fe06e8b1ca974b2ee59ebb
> zotero: avoid updating bibliography if no citations

- browser/src/control/Control.Zotero.js
- browser/src/map/Map.js
when document is loaded zotero may not be initialized, this caused problem and citation style was never fetched
Change-Id: I827bf4edf03dc81bbf8e246280ed14370e438494
> zotero: fetch citation style when zotero is initialized

- browser/src/layer/tile/CommentListSection.ts
The recent changes in LO Core, when edit a comment
in Calc the author data is not preserved.
Change-Id: I4f26ef2044d28bf55ff6a00a2e585ece79c6eb9b
> browser: add author data to calc comment

- browser/src/control/Control.JSDialog.js
This is regression from:
a2d666d53adcb23e60ed61328e8e3fe44fdc1af5
JSDialog overlay: Use CSS rules for positioning.
When auto-save or save is performed we show busypopup. We shoudn't send any messages to the server as it is pure JS dialog.
Parsing error was caused by sending close message: 1677832085616 OUTGOING: control: 'dialog' id:'__DIALOG__' event: 'close' state: 'null' 1677832085617 OUTGOING: dialogevent busypopup {"id":"__DIALOG__", "cmd": "close", "data": "null", "type": "dialog"} 1677832085620 INCOMING: error: cmd=dialogevent kind=syntax 1677832085621 INCOMING: jsdialog: {"id":"busypopup","jsontype":"dialog","type":"modalpopup","action":"fadeout"} 1677832094401 OUTGOING: userinactive
Let's don't send that message for fade out effect we use to close it.
> jsdialog: don't show error on closing busypopup

- ios/Mobile/CODocument.mm
- ios/Mobile/DocumentViewController.mm
- ios/README
This is a near duplicate of pull request #5898.
> Partial fix #5885 Close the font picker when a font is tapped

- browser/src/map/handler/Map.WOPI.js
This fixes an issue where using save as to store a file with a name containing multiple dots like "example.1.odt" by adapting the logic to extract the file extension from the provided path.
> fix(SaveAs): Fix format extraction on SaveAs with filenames that contain multiple dots

- browser/css/mobilewizard.css
Change-Id: Ide0b810cab18d63748678e3007b8ee8c7234114e
* Resolves: #2813
in labels(classes):
- .no-color-control-label
- .auto-color-control-label
the value of padding-left property is
increased from 4px to 8px.
> Mobile: add extra space to color-control-label(s)

- common/RenderTiles.hpp
avoid an allocation and some pointer chasing
Signed-off-by: Noel Grandin <noel.grandin@collabora.co.uk>
Change-Id: I29711075d4bf840c2ef992341a6dadeeb87c6edd
* Resolves: # 
> no need for shared_ptr here

- browser/src/control/Control.DocumentRepair.js
- browser/src/control/Toolbar.js
We had this for tunneled dialogs but also for jsdialog it should be done. When trying to execute uno command when any dialog is opened - blink dialog to indicate that user has to close it to open next one. This blocks possibility to open multiple instances of the same dialog.
> jsdialog: don't allow opening multiple dialogs

- browser/src/core/Socket.js
- ios/Mobile/CODocument.mm
Limit escaping of non-ASCII text and splitting on the first newline to only certain message types on iOS.
> Another fix for issue #5843

- wsd/AdminModel.cpp
The setModified is on an internal, AdminModel
specific, Document object. It is not the
DocumentBroker.
This reverts commit e33d6aa2ca3231befd6634ddf2316712d681ded1.
Change-Id: Ib706927051678cfc19dc1246d679ef530eb8d586
> Revert "wsd: break cyclic setModified call"

- browser/css/cool.css
- Images (coming from link preview) could brake html parent element
- Metadata (p element) could brake html parent element
Change-Id: I362afe9eadd86b88dc6afc584f635d50fac0ad03
> Hyperlink: Fix thumbnail overflow

- browser/css/device-mobile.css
- browser/src/control/Control.FormulaBar.js
- browser/src/control/Control.FormulaBarJSDialog.js
commit db6581582a46fa0ffb1f671babbbec41d7c62e04 (HEAD -> private/pedro/fix-mobile-calc-expander-hide-startformula, origin/private/pedro/fix-mobile-calc-expander-hide-startformula)
Date:   Tue Mar 7 09:46:42 2023 +0100
Mobile: calc: formulabar element: align to top on expanded
Change-Id: I1579f526daa18c45af0e7106eff43d5491aaf89b
commit 164772259e1800afde50d26fbf5f1817b7433e3c
Date:   Mon Mar 6 12:26:37 2023 +0100
Mobile: calc: Fix addressinput  misalignment
In some browsers addressinput was misaligned (no initial margin)
- Remove FF specific margin-left
- Add non LTR specific margin to every browser
- Use the same dimension …
> Calc: fix formulabar expander being cropped on mobile

- wsd/COOLWSD.cpp
There are costs to many threads, and diminishing returns.
Change-Id: I4d4dc0491c48af303375d09d8eb19ffebedcad83
* Resolves: # 
> Warn and clamp unreasonable values of max_concurrency.

- browser/html/cool.html.m4
- common/LangUtil.hpp
- ios/Mobile/AppDelegate.h
- ios/Mobile/AppDelegate.mm
- ios/Mobile/CODocument.mm
- ios/README
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
The iOS app saves directly to local disk so, other than for "view file extension" document types or other cases that I am missing, we can assume the document is writable until a write failure occurs.
Change-Id: I72e80e74f1132d41c11015a80bcc0d79c77acb26
> Fix issues #5887 and #5841 on iOS

- wsd/DocumentBroker.cpp
Previously we only waited if a new auto-save has
been issued at the point of disconnecting the
last session. However, we could have a save in
progress, particularly when it's a slow one,
and we should equally wait for it before
disconnecting the last session.
Failing to do so will exit the kit right after
finishing the save and will rob us of the
ability to upload the just-saved version.
Change-Id: I678689a95211fa8b80bcd3e8d4537de7de5d6632
> wsd: do not disconnect the last session if saving

- wsd/DocumentBroker.cpp
It seems more complex to have #ifdef guarded logic
around a function call to pass or not pass an argument
when we that same argument is already defaulted in
that function.
If the difference between the two paths is primarily
the argument, then we can always pass it, making sure
that in the case that defaulting would have been used
that we pass the same default value. This is now done
with assertions.
Change-Id: I333eb3f42cb51dfab8584ae8c5aa52ee45c5a9a1
> wsd: simplify passing mobileAppDocId to getNewChild

- kit/ChildSession.cpp
Tweak the "zoom" variabe to be 1 so that with this thumbnail size, for a typical document we get more of it into the thumbnail.
Change-Id: I419afccbf57eae23062ab4c849dd41293f068f00
* Resolves: # 
> We aparently want thumbnails to be of size 1200x630 pixels

- cypress_test/integration_tests/desktop/writer/image_operation_spec.js
Tests consistently pass without these waits.
* Resolves: # 
* https://phabricator.collabora.com/T39833
> Remove unnecessary `.wait`s from image tests

- browser/src/core/Socket.js
Change-Id: Id41c98806bc4763797c9986a60ef39301581da06
* Resolves: # 
> Remove vex dialog from saved-as warning.

- net/Socket.cpp
If the server bind type is `IPV4` the client address will be `127.0.0.1`.  
If the bind type is `All` and a client connects to 127.0.0.1 the client address will be `::ffff:127.0.0.1`.  
Actually the `isLocal()` will return false if you set `net.proto=IPV4` and try to connect to 127.0.0.1, which will always cause a 400 BadRequest.
This happens because `rfind` returns the position of the match which means that if the client address is `127.0.0.1` it will return 0 (interpreted as false).  
When rfind fails it returns std::npos (-1, which is true), so this condition is wrong because it always returns true except for `127.0.0.1`.
It's currently working because the function (with `All` proto) always returns `-1`.  
I don't know if this is a security issue as I have no idea how this software …
> Fix isLocal failing check with IPv4

- net/HttpRequest.hpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd: http: set http::Request log context
- wsd: logging improvements
- wsd: better logging of WOPI::PutFile
- wsd: do not warn of unassociated Kit after unloading
- wsd: only warn of live sessions on unload
- wsd: correct log of time since last save response
- wsd: better logging in autoSaveAndStop
> Log Improvements

- browser/css/cool.css
- the popup was appearing with 2 border
- the content (list) was quite small and the parent element
bigger
Change-Id: I539c9cad0f94bfd65eb06b9d704fa9f89e1e949b
> MentionPopup: fix double border and parent padding

- browser/src/control/Control.AlertDialog.js
- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
Replace closeAll calls with uimanager.closeAll. It works for also mobile view.
Change-Id: Ieaf11fc8f68390f789c18a29813a171d51c13a88
* Resolves: # 
> remove lonely "close all" calls for vex.

- browser/src/control/Control.JSDialogBuilder.js
- ios/README
Behave the same as Contol.Menubar and never disable Paste toolbar
button. Native clients that run LibreOffice locally may send a
"statechanged: .uno:Paste=disabled" message when opening a document
if the system clipboard is empty, So, we ignore such messages or else
the current document's Paste toolbar button will never be enabled.
> Fix GitHub issue #5839 and never disable Paste toolbar button

- browser/src/control/Control.UIManager.js
- browser/src/control/Control.Zotero.js
Empty api key string indicates that integrator supports Zotero. When any functionality is accessed by the user we show notification to integration so it will show a popup for user with instructions.
> zotero: show buttons when integrator supports it

- wsd/ClientSession.cpp
When using Nextcloud with source file with spaces in the name eg. "file name.docx" and we tried to export as PDF then error appeared.
In the logs we had "SaveAs produced no output in '<...>file%20name.docx', producing blank url.
We need to decode file name similar to convert-to case.
> export as pdf: we need to decode path

- browser/src/control/Control.NotebookbarWriter.js
Before this commit remotelink HTML elements were being generated with
the following HTML ID (including spaces): "Pick Link"
Change-Id: I81b85c8bba9144e11b6579b777eb3df86e6e237d
> Fix remotelink id

- common/Util.cpp
- configure.ac
Change-Id: Id64b35a02718f59014b18f5c667a7465bcf8cb43
* Resolves: #5851
- instead of using /dev/[u]random devices, use
getrandom() and/or getentropy() to make direct
system calls if sys/random.h available.
- if getrandom() fails, we need to fall back to 
"/dev/[u]random" approach.
> use getrandom() instead of /dev/[u]random

- browser/src/layer/tile/CanvasTileLayer.js
When integrator shows dialog eg. for save as with the
input fields, keyboard appears resizing our frame.
We shouldn't then steal focus from input.
Change-Id: Ifda6e7049b1b329fb051966e38fa854c93c05065
> mobile: don't steal focus from save-as dialog

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
I replaced the hack with foreach.
Also added one more foreach for distinguishing the click events from keyboard events.
Change-Id: Ibc1d955636ea4dde214c24b911c17c7b0de5f9e0
* Resolves: # 
> We can use foreach when there is indexed assinments.

- browser/css/jssidebar.css
- browser/css/notebookbar.css
This makes any resizing or position easier
and it's what is expected from "buttons" (it's the default value)
and those icons are buttons even if the html elment is somehting else
Bottom line: better to account for any border and padding in the values
we specify for width, height, border and padding. This makes sure that
the content box shrinks to adapt to those values.
Change-Id: I39af02f983611bc751e764c26d13d955b7774928
> Set box-sizing for sidebar and notebookbar icons

- browser/css/notebookbar.css
Change-Id: Ie4eead1f20fb183b2f5c48aee4fe1f72fa7b12f1
* Resolves: #5395 
- Made bigtoolitem size from 24 to 32 px to make it's looks bigger than icon with inline labels.
@mmeeks, @vmiklos, @eszkadev, @Andreas-Kainz
> Made bigtoolitem appearance bigger than icon with inline labels.

- wsd/DocumentBroker.cpp
The following commit caused a regression with
PDFs which are read-only, but may allow comments.
commit cca0a561ed5d7750404d39191918320d71726d5b
Author: Ashod Nakashian <ashod.nakashian@collabora.co.uk>
Date:   Sun Jan 15 18:29:18 2023 -0500
wsd: never upload using a session that is read-only
Change-Id: I9bf1fde21b47a4f119b99cc58f76cd683c2152a9
* Target version: 22.05
> wsd: check for editable session not readonly

- browser/css/btns.css
the commit 51bb1d3 with the following change-id
I16a5df46bced608952c22bf979808bc735645366 introduced incomplete
CSS rule, rendering the whole css file invalid
So we should add back the rules and just remove the vex classes
but and upon further investigation button are already inheriting
font-family from jsdialogs.css: .jsdialog-container .ui-dialog-content
so we can just remove it altogether.
Change-Id: Iab42230efc7341e8967ce776f0d3decf41655ba6
> Fix regression from commit 51bb1d3

- test/WhiteBoxTests.cpp
'trimIfInactive' overrides a member function but was not marked 'override'.
Change-Id: I25b0033652a3362118a77b7ef5ef7a511ce492ea
> test: fix -Werror,-Winconsistent-missing-override

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileWizardBuilder.js
Responses have to be handled even in top level widget. After rework we sometimes didn't handle responses
because we didn't call container handler.
Put it in a build function also.
Bug was in find & replace dialog, help didn't work
> jsdialog: fix help buttons

- browser/html/framed.doc.html
- browser/src/map/handler/Map.WOPI.js
We needed to execute UNO commands using `postMessage` from outside of the iframe, in order to add some custom UI and custom functionality. So, because executing UNO commands (especially with arguments like InsertBookMark) was not supported, we decided to add it as a general feature.
I have updated the `framed.doc.html` file, I don't know if there is any file or documentation I should update for this PR. If any, please mention it and I will update it. `framed.doc.html` preview:
This is also our use case that uses `.uno:InsertBookMark` UNO command:
Our code is to add a sharing feature inside Collabora using custom-added buttons (using `Insert_Button` postMessage). We listen to the buttons' clicks and then we want to add a custom bookmark on the text (using UNO …
> Feature add Send_UNO_Command postMessage

- browser/src/control/Control.Menubar.js
Otherwise, the toolbar re-layout half the size.
Change-Id: I492a98f822a829d814b4c6e6b4765ec14a65cc98
> mobile: use attribute 'visibility' to hide toolbar back button

- browser/css/jsdialogs.css
- browser/css/notebookbar.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.DrawingArea.js
This changes tabs into button elements so they can be switched using keyboard Enter key. It's also better from a11y point of view
Styles has to be !important to override button styling
> jsdialog: make tabs accessible using keybaord

- browser/js/global.js
sheets[i].href can be null. Seen with proxy.php.
Change-Id: I3d774ace869d141973a92abab8ef9ac83e1e0018
* Resolves: # 
> handle Uncaught TypeError: Cannot read properties of null

- browser/css/jsdialogs.css
- added space between elements in grid
- spinfileds, listboxes have equal width, 100% of a grid cell
> jsdialog: fix alignment in dialogs

- browser/src/control/Control.JSDialog.js
The focusId element already has the focus, no need to
set initial element focus.
Change-Id: I25e3b5ba962aad9ce5bb1df26398297971b6a9e8
> jsdialogs: fix the initial focus if an editable element has it

- browser/css/btns.css
- browser/css/device-desktop.css
- browser/css/jsdialogs.css
- browser/css/mobilewizard.css
- browser/css/notebookbar.css
- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/mobile/calc/number_format_spec.js
- cypress_test/integration_tests/mobile/writer/focus_spec.js
Remove tabIndex from container so user can navigate between buttons with tab.
Change-Id: Iea6089370d36d2695426e5dc3116416562bbec15
* Resolves: # 
> Turn div elements which has button role into buttons.

- test/TileCacheTests.cpp
Attempted blind fix for intermittent failure:
[ kitbroker_004 ] TRC  Document::GlobalCallback LOK_CALLBACK_ERROR [{ "classification": "error", "cmd": "load", "kind": "io", "code": 770, "message": ""}]. filter/source/config/cache/typedetection.cxx:452: caught exception while querying type of ... "Could not open stream for <file:///tmp/.../disconnectMultiView_5f47c785_setclientpart.ods> at filter/source/config/cache/typedetection.cxx:1123"
[ coolwsd ] TST  disconnectMultiView-1  [loadDocAndGetSession] (+22012ms): ERROR: Assertion failure: Failed to load the document cool/file%3A%2F%2F%2Ftmp%2FdisconnectMultiView_5f47c785_setclientpart.ods/ws. Condition: isLoaded| helpers.hpp:531
Change-Id: I91062bf4c136dbd6a4cf6def842ff2ae7687c758
* Resolves: # 
> TileCacheTests: re-copy documents when repeating tests.

- browser/src/control/Control.Menubar.js
Before this commit was impossible to use the translate button
on mobile phone
Change-Id: Ia93e1bf009723f3f7791b63f0b15a74467595ab7
> Expose Translate option to mobile if feature is enabled

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
- re-use btn-size variable
- make it clear that this set of rules is intended to sidebar elements
- Improve selector (more clear and so it doesn't target other
elements outside of the sidebar)
- Move it to jssidebar.css file
Change-Id: Ib03c412a1e05fd6ed315f58a70486f14eaf5b9ea
> Set missing dimensions to sidebar button images

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
Before this commit we were setting buttons in places such as
the sidebar with weird ratio (not 1:1) this might lead to problems
when aligning, adjusting gaps. Better to adjust gap or margin if we
need bigger spaces in between
Change-Id: Id60cd6353de2ace2a066c0d1624000a09f0ca98e
> Fix button ration

- browser/src/control/Control.JSDialogBuilder.js
- ios/README
The fix for issues #6103 and #6104 changes the name of these
icons so map the new names to the old names.
> Fix issue #6145 by adding aliases for the PDF and EPUB icons

- cypress_test/Makefile.am
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/FileServer.cpp
add forcecaching parameter to coolwsd for debug mode.
Change-Id: I6f38e9a4fd6dbb76e92105c76e8abe3e75f19ef5
* Resolves: # 
> Cypress: accelerate tests by not re-downloading & JITting JS.

- browser/src/control/jsdialog/Widget.ScrolledWindow.js
Can be tested with Calc's Data -> Sort dialog:
When we have multiple entries we still should scroll only to the end of last entry. Previously we added lot of extra space when scrollbar was present. 
Can be tested with Conditional Formatting dialog:
Also this change prevents from adding unnecessary margin to drawing areas.
> jsdialog: don't setup additional margin for unmanaged scrollwindow

- browser/css/jquery-ui-lightness.css
- browser/css/notebookbar.css
Create a new CSS rule to make tabs' content lower enough from the tabs' buttons.
Change-Id: I3354b93711f1e93aa9c97c31b3717cad7b917351
* Resolves: # 
> Update jquery-ui.css to make the container's height reflect its content.

- ios/Mobile/AppDelegate.mm
- ios/Mobile/CODocument.mm
LANG values such as en_US.UTF-8 trigger an assert in the LibreOffice code so replace all "_" characters with "-" characters.
> Fix assert failure when running "My Mac (Designed for iPad)" in Xcode

- browser/css/notebookbar.css
similar to d1991e177c8bcb6e484ee62afd90a8c399edef40
but his time addressing:
- outdated css rules (remove them). They are outdated because we
already have `.unotoolbutton.notebookbar .unobutton`. Plus all of the
with exception of `vertical-align: middle;` were being ignored
- Do not allow browser to calculate width and instead set the same
value as in height
- Move `vertical-align: middle;` to a better place
Change-Id: Idb2de12365727d0ed2886729d9effbf36ede31ab
> Tabbed view: fix buttons occupying extra space

- browser/css/cool.css
If the page widget (elements that end their id with Page) have just
one column this will not take effect.
Why: the grip-grap (for both columns and rows) of 4 px set in the
jsdialogs.css is enough for many cases but when we have a Page with
more than 1 column the 4 pixels is too small to distinguish the
different sections.
Dialogs affected by this commit: All with child content id ending in
Page. Examples of improved dialogs:
- File properties
- Char format
- Settings of Footnotes and Endnotes
- Paragraph (format)
- Bullets and Numbering (position tab)
- Page Style (border, Header)
Change-Id: Iebe9f01b758f1af8b43317cdf01a44f74c70cc42
> Add additional column gap to all page widgets within dialogs

- cypress_test/integration_tests/common/helper.js
This changes make cypress tests more reliable, specially in slow or loaded machines.
Change-Id: I574b0db3e81e57a2dc682fbe2ed3f0301ad8e52d
> Various cypress fixes

- browser/src/control/Control.Notebookbar.js
With the a11y improvements from
9d3d0cdee73e84b8446324cf55fb1feefe720cd8
we now add !important to visibility: hidden that in turn makes the
browser ignore the inline display block. The result: we get a new tab
content without the tab itself (it's hidden)
- Fix this by removing the 'hidden' class when the tab button needs to
be shown
Change-Id: I276d3fa62d89b32935de0357d0b24f558fcf3fd6
> Tabbed view: Fix context tabs visibility

- cypress_test/plugins/index.js
The suspicion is that the update popup messes with focus, and can break tests after they start intermittently - at least in interactive mode.
cf. also https://github.com/cypress-io/cypress/pull/16694
Date syntax is altered to avoid another bug with cypress parameter parsing.
Change-Id: I92b9911eb7b3673a64a9d123b2c110111b7c3549
* Resolves: # 
> cypress: add flag to delay update popup in Chrome indefinitely.

- common/JailUtil.cpp
- common/JailUtil.hpp
- kit/ForKit.cpp
- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
This avoids removing the jails of other running coolwsd that share the same jails/ directory, such as unit-tests, cypress tests etc.
Assert on fatal system error to help catch this during test builds.
Remove old unit-test specific approach, and generalize it, since apparently we did a recursive cleanup of other people's jails anyway.
Remove over-complicated recursive approach, for a rather simpler one-level scheme. Avoid following symlinks too for safety.
Remove obsolete lo_jail_subpath setting.
Change-Id: I371f8c0e22f64fb2befb4b58f72cefa39567f3b5
* Resolves: # 
> Jail cleanup - include coolwsd pid + hash into a jails sub-directory.

- browser/css/jsdialogs.css
icons or being set with a non 1:1 ratio, missing width in the css.
Also better to reuse the btn-size
Change-Id: I55b005d83718da81d9a7a44193b6f9de7192d41e
> Fix listview icon sizes

- test/UnitWOPISlow.cpp
- test/httpwstest.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
The primary purpose of this PR is to make sure the IsModifiedByUser header passed to storage is accurate. We now get this flag from Core in the uno:Save response, so there are no race conditions.
- wsd: do not allow multiple saves in flight
- wsd: process the modified state from uno:Save
- wsd: track the storage attributes more accurately
- wsd: test: new test for superfluous save commands
- wsd: test: rulerupdate is an expected message
> Better Modified Tracking and Upload Headers

- docker/from-packages/scripts/start-collabora-online.sh
* Resolves: # 
Recently noticed that the inotify I originally added to cause an automatic restart of Collabora, if the coolwsd.xml was changed, no longer works.
Looking at the shell script the problem is obvious.
So, please merge ASAP.
Ralf
> Fix not working inotify / restart on coolwsd.xml changes

- browser/css/device-desktop.css
Fixes https://github.com/CollaboraOnline/online/issues/6254
Before this commit and with recent a11y changes generic btn hover
styles were bleeding out to multiple places where icon btns are present
Change-Id: I3855d081595a2d3aa56e58137e21aba5d7bf8532
> Fixes Menu items hover color are inconsistent #6254

- browser/css/jsdialogs.css
dark theme was switched with [data-theme='dark'] instead of prefer-color-scheme so the new setting respect [data-theme='dark'].
Change-Id: I9214fda63f6caea0a36ab8be7c26baf4e1c0f46e
> dark-mode use correct jquery-ui icons with data-theme value

- browser/src/control/jsdialog/Widget.MenuButton.js
Menubuttons are for example font color selectors in Writer's   Format -> Character -> Font Effects 
This PR allows to open dropdown using enter/space
> jsdialog: a11y: keyboard activation for menubutton

- browser/js/global.js
window.screen.width/height returns the width/height of the screen in CSS pixels. window.innerWidth/innerHeight returns the interior width/height of the window in pixels. This includes the width of the vertical scroll bar, if one is present.
That gives better result. eg: responsive mode
Change-Id: Ibecb9614224cb3bfd6d5d8dc9ad5febe6aa7673b
* Resolves: # 
> Fix wrong device detection logic.

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
can be tested with File -> Properties,
no error is shown with this patch and initially focused element is something we can use not an image
> jsdialog: improve initial focus in dialog #6271

- browser/admin/admin.html
- browser/admin/admin.strings.js
- browser/admin/src/AdminSocketOverview.js
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/DocumentBroker.cpp
- previously we set the Modified state in admin panel only when wsd successfully upload the document to storage
- modified state updation depends on core, it might happen that uploading is already done and successfull but we didnot get the modified state from the core which will show wrong modified status in admin panel
Change-Id: I014a8f92753fc6a93b37921d0f3cdce390bef35e
* Resolves: # 
> admin: added a seprate state for the uploaded document

- browser/src/layer/tile/CalcTileLayer.js
The UNO command  state has changed to Point (row, tab)
and Point (col, tab), Otherwise, if the row or column
has the same value for all sheets, the state cache will
not report any changes to the client side.
Change-Id: I0ad4a058d9328ff3b7b2455197a87880d8e43125
> browser: fix freeze row/column panes

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
In dialogs we put tab list directly where tab control is placed. We don't need special container anymore (setTabs is not used).
> jsdialog: don't create empty tabs container #6260

- browser/css/partsPreviewControl.css
- Make it bigger
- Also size is not enough, specially for slides that have backgrounds
- Add white inner margin so there is a clear distinction between
- what is the slide preview (image) and its contour
Change-Id: Ifee386b98d74c937efa35c19551334482ec18632
> [Backports] Impress: Fix imperceptible active (current) slide border

- browser/css/partsPreviewControl.css
- Make it bigger
- Also size is not enough, specially for slides that have backgrounds
- Add white inner margin so there is a clear distinction between
- what is the slide preview (image) and its contour
Change-Id: Ifee386b98d74c937efa35c19551334482ec18632
> Impress: Fix imperceptible active (current) slide border

- browser/src/control/Control.JSDialogBuilder.js
in dialogs only button accelerators were shown, add them also for labels
> jsdialog: show accelerator key for labels

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js
Add switch UI to notebookbar function to desktop helper. Remove tagnotebookbar.
Remove clickonidle function calls.
Tests should be more reliable and faster now - tested locally.
Change-Id: I8b05f0b7cf3755ce6e1fe35a26a4ec1154bb2510
* Resolves: # 
> Enable disabled cell appearance tests.

- browser/css/color-palette-dark.css
Reverts CollaboraOnline/online#6258
See #6302, this change (#6258) breaks dark mode on firefox.
This is how it would look on firefox (white screen):
> Revert "Dark Mode add color-scheme: dark setting"

- browser/css/cool.css
- browser/css/infobar.css
- browser/css/jquery-ui-lightness.css
ui-widget-header has no border-bottom-radius
ui-widget-content has no border-top-radius
cause both widgets are next to each other
ui-icon use the blue hightlight colors
and the blue icons for more consistancy
Change-Id: Id891548c56b540f8d0b27f65b805c1823fe28906
> jsdialog ui-widget-header border-radius and color fix

- browser/css/jssidebar.css
rules from sidebar were applied to dialog
writer -> review -> spell checking
> jsdialog: fix spelling dialog layout

- browser/css/btns.css
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/jsdialog/Widget.MobileTabControl.js
- cypress_test/integration_tests/desktop/impress/sidebar_spec.js
Fixes position and dragging in Writer -> Format -> Page Style dialog
It was caused by `<button>` with id = style inside dialog's `<form>`. In that case style property was a reference to the dialog, not CSS properties map. It cannot be changed... so Introduced new parent container which is div for setting position.
This PR also makes dialogs more compact, using minimal width thanks to using 'position: absolute' inside parent container. What helps to not cover whole screen with dialog.
> jsdialog: fix jumping Page Style dialog

- Makefile.am
- common/FileUtil.hpp
- common/JailUtil.cpp
- common/Util.cpp
- common/Util.hpp
- configure.ac
- kit/Kit.cpp
- test/Makefile.am
- test/UnitQuarantine.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/QuarantineUtil.cpp
- wsd/QuarantineUtil.hpp
- wsd/RequestDetails.cpp
This PR fixes known/reported issues, leaving the original logic/design mostly intact.
Key changes:
1. Support for copying when hard-linking fails.
2. Thread-safety.
3. Adding unit-test.
4. Correct timestamp comparison, sorting, and clean-up.
5. Correct loading of quarantined files at initialization.
6. Support for failed initialization and disabling of Quarantine.
7. Avoid reconstructing the path to the document manually.
8. Avoid reading the configuration repeatedly, which is slow.
9. Encapsulation of Quarantine members/data.
10. Minimize hard-coded values and code duplication.
Patches:
- wsd: more accurate comment
- wsd: test: add quarantine test
- wsd: clang tidy fixes
- make: silence clang complaining of -pthread
- wsd: FileUtil to link or copy files
- wsd: add fixme for safer jail …
> Quarantine Improvements

- browser/src/control/Control.NotebookbarCalc.js
In Calc compact view we have insert current date and time actions but in tabbed view we don't have them. For equality we need to add in tabbed view too.
Change-Id: I5498f47a8dc96a5403cdf17be52ef3a7ad66862c
* Resolves: # 
> Add date time fields under the insert menu

- cypress_test/Makefile.am
- cypress_test/README
- cypress_test/plugins/index.js
Change-Id: If07b5f54b60cd0d7a934f97973a487f103702581
* Resolves: # 
> Remove notebookbar seperation from Cypress tests.

- config.h.in
- configure.ac
- coolkitconfig-mobile.xcu
- coolkitconfig.xcu.in
- coolwsd.xml.in
- wsd/COOLWSD.cpp
Previously the help root URL was defined in coolkitconfig.xcu, but it was inconvenient to change. Now we have this setting in coolwsd.xml, therefore it can be changed more easily. For example a brand package can disable the Help buttons on dialogs by executing the following command in postinstall script:
coolconfig set help_url ""
Change-Id: I6d0bdd71ca908df3d2dd20bd321aff9e93896f52
> Add possibility to define help root URL from brand package

- wsd/COOLWSD.cpp
This is the product name served by hosting/capabilities endpoint. Also, it is used by update checker.
It can be defined --with-app-name build time, but if we would like to configure it run-time (e.g. with the brand package), then we need a config setting for it. E.g. brand package could execute
coolconfig set product_name "foo bar"
in postinstall script, if necessary.
Change-Id: I8e72d3a3735e3a77c7aaac9a88b2c0fc6a957c0e
> Add possibility to define product name from brand package

- kit/ChildSession.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
Fixes  https://github.com/CollaboraOnline/online/issues/6229
- renders preview with zoom so we don't produce thumbnail with only half width content in case of writer documents
- avoids infinite response time for rendering requests in case of not-existing targets, or first character in document
> linking api: improvements

- browser/src/control/Control.LokDialog.js
This fixes regression from popups rework.
Run collabora online, try to open not existing document. You should see error: "Well, this is embarrassing..."
> Show document loading error popup

- browser/src/control/Control.JSDialog.js
test with eg. &lang=he
after position of a dialog was changed to absolute position we had regression causing the dialogs to appear outside view in RTL mode. this patch uses margin-inline-start instead of margin-left what is more generic
> jsdialog: position dialogs correctly in RTL mode

- browser/html/cool-help.html
In tabbed view when we open help or keyboard shortcuts dialog "button" style of cool-help.html overrides the button.ui-tab.notebookbar. So all buttons (even in notebook bar) uses dialog buttons' text-decoration: underline and padding:0
Here we make the dialog's button style specific to related dialogs.
Change-Id: Iacaab42efa527fc5c6ada21fd007e4a352912b60
* Resolves: #6275 
> Make dialog button style to specific that dialog #6275

- browser/js/w2ui-1.5.rc1.js
Change-Id: Icec596bc4691b5bdd04ab2c687cc8c0c54608412
* Resolves: # 
Issue: 
- Occasionally a button appears on top right, which does not belong to the default control elements. It looks like a rewind button in a player.On tap nothing will happen and the button disappears.
Fixed this issue which now not showing any scroll button when document loads in android app. I have tested.
@pedropintosilva  can you  please review the changes.
> Remove scrollbar button in mobile view

- browser/css/jssidebar.css
Better to align everything to start so if the components differ in
width they will still be aligned (as opposed to be laid out in a staircase)
This is a follow up from 1bfbdf807208b98be56aa558f749e32c7a67acdf coming with
the following PR https://github.com/CollaboraOnline/online/pull/6389
Change-Id: Ic607567d30656cc122f9cbfd71bd3d910ebfe9bf
> Sidebar: Align everything to start and remove unnecessary css

- browser/js/w2ui-1.5.rc1.js
Change-Id: Icec596bc4691b5bdd04ab2c687cc8c0c54608412
* Resolves: # 
Issue: 
- Occasionally a button appears on top right, which does not belong to the default control elements. It looks like a rewind button in a player.On tap nothing will happen and the button disappears.
Fixed this issue which now not showing any scroll button when document loads in android app. I have tested.
@pedropintosilva
> removed An unknown button appears on top right of a document in android

- wsd/ClientSession.cpp
followup for:
commit 012b00d
linking-api: always response for thumbnail render requests #6229
in calc and impress we don't get cursor message when switching to target (slide, range), so don't check if target was reached, statechanged messages are good enough signal we are loaded already
> linking-api: always response for thumbnail render requests #6416

- browser/css/jssidebar.css
This hard coded width is not needed and was imposing that width value
to #indentfieldbox even if there is other elements present resulting
in the whole container being bigger than the sidebar itself
This issue became more evident with
https://github.com/CollaboraOnline/online/commit/27fddae9c6b3fe0dc0c948bb132034f9ffa38012 (even
though it's not related to the bug but rather exposed it even more)
Change-Id: I90e684b395b950e4cc25a96a9875d4702016411d
> Fixes: Sidebar icons are cut off

- browser/src/control/Control.UIManager.js
we didn't check if zotero was already initialized what caused reload of the notebookbar when any new user joined to collaborative editing
> zotero: initialize only one time

- browser/css/toolbar.css
Change-Id: I2a2ace9ffc2a31d500b6819f790a07e5762a5f6a
This is basically a regex replace for any usage where the background image was enforced with `!important` in toolbar.css for the classic toolbar. From my perspective those were not needed at all and also make life harder during icon adjustments in other css parts like branding. 
I went through the classic toolbar on all apps and couldn't find a problem, but probably needs some careful checking from @pedropintosilva
> fix: Avoid important property on all classic toolbar w2ui icons

- browser/src/layer/tile/CanvasTileLayer.js
Somehow escaping was disabled for this safe text we generate.
Change-Id: I47fbf72b9d47a80975ca1b926ff2d27c248fac12
* Resolves: # 
> restore tile debug popover content.

- browser/src/control/Control.UIManager.js
we didn't check if zotero was already initialized what caused reload of the notebookbar when any new user joined to collaborative editing
> zotero: initialize only one time (22.05)

- browser/src/control/Control.UIManager.js
Change-Id: Ia8b490de6144df771e5ee115c068b87e997e3ccb
* Resolves: # 
Fix error when toggling the darkmode wrongly tried to refresh the toolbar from compact mode.
```
Control.UIManager.js:425 Uncaught TypeError: Cannot read properties of undefined (reading 'refresh')
at NewClass.refreshToolbar (Control.UIManager.js:425:19)
at NewClass.toggleDarkMode (Control.UIManager.js:116:8)
at NewClass.dispatch (Toolbar.js:971:19)
at HTMLDivElement.<anonymous> (Control.JSDialogBuilder.js:2609:17)
at HTMLDivElement.dispatch (jquery.js:5429:27)
at elemData.handle (jquery.js:5233:28)
```
- Start cool with compact mode
- Switch to notebook bar
- Toggle dark mode back and forth
> fix(darkmode): Fix toggling darkmode in notebookbar

- browser/src/control/Control.NotebookbarDraw.js
Change-Id: If9a57484a8335034e3007f47513cd4827c8decbc
* Resolves: #6405 
- Fixed sidebar toogle functionality in odg (draw) file
> Fix Draw - Page Layout cannot be open from top tool sidebar icon

- browser/src/layer/tile/CanvasTileLayer.js
if the tile has a Canvas as tile element then it never gets cached.
All was apparently well at:
commit c812edc7d35782dfdccd10e4d7765df9f3b3da82
Date:   Mon Jun 7 12:31:26 2021 +0530
fix avoid putting empty tiles to cache
where the change to cache only if tile.el.src is non-null was added.
But by now tile.el can be (usually is) a canvas and generally doesn't get cached here.
It seems to work fine to just cache the Canvas directly.
note: This cache guard itself flip-flopped a bit in:
commit 6db97718967fd1434c0462dbe55a4d37eed04f88
Date:   Wed Jun 9 15:45:07 2021 +0300
CanvasTileLayer: Use el instead of el.src.
where changed as:
- if (!(this._tiles[key]._invalidCount > 0) && tile.el.src) {
+ if (!(this._tiles[key]._invalidCount > 0) && tile.el) {
but reverted in:
commit …
> Related: #6423 _removeTile nearly never populates the tileCache

- browser/src/errormessages.js
Better to make all error messages related to storage consistent and
avoid mentioning admin or administrator and respective %storageserver
link
- In some situations %storageserver domain is not the right place
to redirect users (integrator might have another support system in
place, etc)
This is a follow up from
- PR: Do not assume who the user needs to contact for storage space
- Commit: 2ace217813dc286376140ea0fdf7c8748a8ff8b0
Change-Id: Id49e4b7f775c1ded10fb02648c7525c6e9becf20
> Do not assume who the user needs to contact (storage error messages)

- browser/html/cool.html.m4
- browser/src/control/Control.UIManager.js
- browser/src/core/LOUtil.js
- test/WhiteBoxTests.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/FileServerUtil.cpp
Change-Id: Ief028dcec0daa2ae448f83df993e0e5ade594a7c
* Resolves: #6432
This adds the option to provide a default theme through the form parameters ui_defaults. As the frontend code currently only uses a boolean flag I mapped just UITheme=dark to enable the dark mode, all other values will use light by default.
> feat: Add UITheme option for light/dark to ui_defaults

- browser/src/control/Control.JSDialogBuilder.js
Change-Id: I58dab34e1dbe0811844a01aaa54bd889a2e6d033
* Resolves: # 
In Mobile view we are getting error related to image icon path not found. this is because section id is empty and we are tring to set value of based on that.
here i am posting  the fix for that :)
> fix worng image path name passing to setImage url

- browser/src/control/Control.JSDialogBuilder.js
fixes #6494
browsers are very strict with validating spinfields use as step values like: 1, 0.1, 0.01 so all the numbers with specified precision will be allowed
> jsdialog: silence spinfield validation errors #6494

- browser/css/btns.css
Impress -> Sidebar -> Animation tab -> Effects
Unset the hardcoded  min-width and use fit-content instead.
Change-Id: If524533997e33037d669055fd5479ddcbba80d71
* Resolves: #6378
> Set the width of the effects buttons #6378

- browser/css/notebookbar.css
Before this, save icon's dot was being cropped due to height rule
Change-Id: Id7b16b3fcd05d169c1206b9b7c3dbe615f0e8141
> Tabbed view: Fix save modified icon being cropped

- browser/css/toolbar.css
- browser/src/control/Control.MobileTopBar.js
Affected user flows:
- User opens read-only file
- Before this commit, there was no indication that the current mode
is read-only.
- User opens file
- Before this commit, the only indication about the current read
mode was the pencil Floating Action Button.
Change-Id: I7cc3982b0c0f827a96e144ee339d8f0e601bf03e
> Mobile: Add "Read-only" label to toptoolbar

- browser/src/control/Control.Menubar.js
Insert -> Smart Link option works if only the integrator supports the funcitonality. If not supported not need to show to user.
Change-Id: Iad6609ad6a90a57126b30288a9c089f9185d97f2
* Resolves: #6489
> Check the integrator has smart link funcitonality #6489

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/layer/tile/CanvasSectionContainer.ts
- Get directly the particular css var that we want instead of on relying on a container
- This makes things easier to maintain in the future
- Use a new --color-canvas instead of relying on --color-main-background
- color-main-background is used in many other places which means
that if we want to have some particular UI brighter or darker it
would affect the canvas. Better to use a different/new css var for that
Change-Id: I3d7d3ba188e96080d9f6f814a5c46f85ea378142
> Dark mode: Canvas, get directly the css var property value

- browser/css/jssidebar.css
Without patch image sizes are 336px and seems cropped in sidebar. We should use same width with sidebar width.
Change-Id: I617a4e79e15d1d49ca95aec8f5a20f95734160a2
* Resolves: # 
> Fit the images into the sidebar.

- net/Socket.hpp
Change-Id: I796d71e48ae7110fb8d88eda781e362faba75aa2
* Resolves: #4837
- Lock in callback function was already placed. 
- Poll already reads the whole value of wakeup[0] and it does not need to read wakeup[1].
- Check the condition to look for new sockets and call-backs before calling wakeup() is placed here. 
The third one was to check for callbacks and sockets before calling wakeup, which I implemented, and also studied more ways but checked that most of it was implemented.
> Fix: Speed-up callbacks

- browser/css/jsdialogs.css
Change-Id: I3d9611595819d505632fc58686f1ee9355228524
> jsdialogs radio button use same margin than checkboxes

- browser/src/control/Control.JSDialog.js
default button should be inside form so we execute correct action on ENTER
fixes: https://github.com/CollaboraOnline/online/issues/6404
> jsdialog: default button inside form #6404

- browser/css/jssidebar.css
I have noticed that sometimes the toggle doesn't get assigned with
selected css class. We could just rely on this line and avoid add and
removing css class to the DOM every time the mode changes
Change-Id: I7c19f626d60c761a1ebe2509e7ab7aa8031403ad
> Dark mode toggle: fix flimsy selected state

- common/MessageQueue.cpp
- common/StringVector.hpp
rearrange so we can use the tokens as they are generated and can end tokenization early as we find we don't need any more
from:
|--74.39%--SvpSalInstance::CheckTimeout
|          SalTimer::CallCallback (inlined)
|          Scheduler::CallbackTaskScheduling
|          |
|          |--63.01%--desktop::CallbackFlushHandler::Invoke
|          |          |
|          |           --62.92%--Document::ViewCallback
|          |                     |
|          |                     |--62.11%--MessageQueue::put
|          |                     |          |
|          |                     |          |--61.95%--MessageQueue::put
|          |                     |          |          TileQueue::put_impl
|          |                     |          |          |
|          |                     | …
> Related: #6514 removeCallbackDuplicate only needs up to 4 tokens

- browser/src/control/Control.UIManager.js
Change-Id: Ifdb5bbf06cb2ed5b8aa1e03ddb6796a0bc80b1c8
* Resolves: #6527 
Added css variable condition in setBackgroundColorMode which was not used in any part of online code. this will work for both the case the normal one and for css variables if we pass as url parms
> Fix Canvas tiles color do no change when clicking the dark mode toggle

- browser/src/control/Control.UIManager.js
It seems we were encoding even when setting the url via CSS.
Tested using richdocuments
Tested using browser/html/framed.doc.html
Context:
Open in local editor is insert via
https://github.com/nextcloud/richdocuments/blob/b77f855ded8ad94990d116e9a84229e9c999a8bf/src/document.js#L330
using https://sdk.collaboraonline.com/docs/postmessage_api.html?highlight=insert_button#id5
Change-Id: I526a5f476e90dbbc52640bd6d76f416a654a20a5
> Fix Missing icon "Open in local editor" #6507

- kit/ChildSession.cpp
This was forgotten in commit 21966e1a9c2379214d3bef2dfb93c7e7ee32ae82
(Fix copy command going out of bounds during delta creation,
2023-05-31).
Change-Id: I91ce26f46cc6cb7a2dc3ab0665dc9aeea8a5c00f
> kit: fix missing init of _isDumpingTiles in ChildSession

- browser/src/control/Control.UIManager.js
- happens when toggle darkmode in readonly document
Change-Id: I14c8e710ff33084e7380e1738f80c9101fdc9f70
* Resolves: # 
> fix: mix compact and tabbed view

- browser/Makefile.am
- browser/src/control/jsdialog/Widget.TreeView.js
Add a TR with the text:
"Headings and objects that you add to the document will appear here." if the navigator is empty.
Change-Id: Iff944df90b921e6f6415d2a3bee462b86e5a5eb4
* Resolves: # 
> navigator: explaining text in case of empty contenttree

- browser/src/map/Clipboard.js
Fixes #6597
error:
Clipboard.js:305 Uncaught TypeError: this.isPasteSpecialDialogOpen is not a function
at Clipboard.js:305:16
at request.onload (Clipboard.js:225:6)
Change-Id: I8c2717b627fead7a3ad3bdd870845c86c586eed4
* Resolves: #6597
> jsdialog: Pasting externally copied data in Calc can fail #6597

- browser/css/cool.css
Change-Id: I74d5e83641982acc1b0b328c707c09d06d68c56d
Add color property for annotation-textarea to get correct font color in comment box.
> 23.05: Dark Mode - Texts on Comments dialog on Dark mode is not visible during edit

- common/MessageQueue.cpp
Change-Id: Ibffa35d40ee9839635cbd37be8cdc9c69b834504
* Resolves: # 
> perf: avoid creating strings by using string_view

- browser/src/layer/tile/CanvasTileLayer.js
Encode the "JumpToMark" bookmark parameter to jump
sheet name with white spaces.
Change-Id: I3943751379bd00bbd4036e137256df1338d26f0d
> browser: fix encode hyperlink parameter

- browser/src/layer/marker/TextInput.js
The FireFox browser corrupts the first IME input character
while it is IME composing and changing cursor position.
Change-Id: I96a6ddd9f5c74b83566051b447b46e45745fa2be
> browser: fix first character IME input

- common/SigUtil.cpp
- common/Unit.cpp
- net/Socket.hpp
- wsd/COOLWSD.hpp
Some thread-safety fixes with the help of the thread sanitizer.
- wsd: signal handler cannot log
- wsd: test: better test timeout thread management
- wsd: thread-safe socket shutdown flag
- wsd: thread-safe kit pid
- wsd: signal handlers must preserve errno
> Thread Sanitization

- Makefile.am
- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/ContentSecurityPolicy.hpp
- wsd/FileServer.cpp
- wsd/QuarantineUtil.cpp
- wsd: allow for legacy quarantine directories
- wsd: simplify frame-ancestor handling
- killpoco: replace URI::encode with our wrapper
- wsd: add ContentSecurityPolicy manager
- wsd: more CSP refactoring
- wsd: support providing CSP header in the config
> Configurable CSP Header

- browser/src/control/Control.Notebookbar.js
This patch fix a regression started from
17b50868ea379b3271c4cb8e678b14f1a2725870
"impress: introduce slide hiding/showing in presentation"
Change-Id: I55263b07088d16fe07171e004b5d505eb3b70500
> When Calc starts with the notebook ui, sheet tabs are missing

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
- cypress_test/integration_tests/desktop/calc/delete_objects_spec.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
- cypress_test/integration_tests/desktop/calc/undo_redo_spec.js
- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/desktop/impress/delete_objects_spec.js
- cypress_test/integration_tests/desktop/impress/scrolling_spec.js
- cypress_test/integration_tests/desktop/impress/sidebar_spec.js
- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
- cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
- cypress_test/integration_tests/desktop/writer/file_properties_spec.js
- cypress_test/integration_tests/desktop/writer/focus_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
- cypress_test/integration_tests/desktop/writer/track_changes_spec.js
- cypress_test/integration_tests/desktop/writer/undo_redo_spec.js
- cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/FileServer.cpp
When accessibility is enabled in coolwsd.xml, overrides setting in
<user-interface> section by force to use the notebookbar UI.
Change-Id: I98f4b288439b21110214ca2a67df639b397184c9
> Force notebookbar ui when a11y is enabled

- common/Session.cpp
- ios/Mobile.xcodeproj/project.pbxproj
- net/HttpRequest.cpp
- net/WebSocketHandler.hpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.cpp
Still needed to add a bunch of #if !MOBILAPP to disable all of the Online server's unit testing classes so that the iOS app won't crash when opening a document.
TODO: the iOS app will get stuck in an infinite loop when opening a document on iOS in http::Request::readData().
> Fix iOS build breakages by adding http::Request to iOS build

- configure.ac
- coolwsd.spec.in
- debian/rules
- test/Makefile.am
rational: building for release takes a lot of time and we neither package, nor run (most of) these unit tests when we make packages.
CI runs all of these tests before merging PRs, so risk is low, if we do not run the few build-time unit tests when we package.
make -j12
--enable-tests (default): 3m 18s
--disable-test: 1m 9s
3x faster...
Change-Id: I4edd98af55748432e30c65c4c910e72c0221272a
> configure option to disable building unit tests

- browser/css/toolbar.css
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.PresentationBar.js
added slide hide/show option in presentation bar
rearranged icons to align them with core UI
Change-Id: Ic4b121ab5d9ab21d8f48e68bb07e51a31442586e
> impress: arrange slide/hide show menu entries better

- browser/src/layer/marker/TextInput.js
Change-Id: I8cb6211a3605503f4144a3c48e059960cf461617
Added condition for focus on textarea so ot will handle the keyboard in mobile view to stop flicker.
* Resolves: 
> 23.05 - Android : tapping on cells flickers the keyboard

- common/JailUtil.cpp
- test/httpwstest.cpp
- tools/mount.cpp
- killpoco: use own file stat helper
- mount: support mounting from character device
- wsd: fallback from mknode to bind-mount for random devs
- wsd: test: testInactiveClient may get jsdsialog message
> Bind-Mount Fallback to mknod

- test/httpwstest.cpp
test was failing because we received some initial sidebar content
> Fix unit-httpws by allowing jsdialog message

- browser/css/jsdialogs.css
This way they:
- Align to checkbox
- And have additional padding in places such as Format > Paragraph
Line spacing 's dropdown is glued to "of" label
This also fixes one task from https://github.com/CollaboraOnline/online/issues/6647
Change-Id: I53e66602dffbc96db39449cbda53d433a9dd12d8
> JSDialog: Add missing padding for ui-text labels

- wsd/FileServer.cpp
array_null: Comparing an array to null is not useful: "false", since the test will always evaluate as true.
Change-Id: Ib34694022484e9041827980c0b67fe614446f4b9
* Resolves: # 
> cid#318846 Array compared against 0

- browser/src/control/Control.JSDialogBuilder.js
Fixes #6650
When opened empty hello-world.odt document and
then in dialog Format->Paragraph switched tabs
and then returned to "Indents & spacing" - some
fields were marked as invalid.
This was caused by agressive validation done by the browser. Let's adjust step to min and max value also to avoid these errors.
> jsdialog: improve spinfields validation #6650

- kit/Delta.hpp
../kit/Delta.hpp:96:23: runtime error: index 4 out of bounds for type 'const uint64_t[4]' (aka 'const unsigned long[4]')
#0 0x558e8e0f800b in DeltaGenerator::DeltaBitmapRow::PixIterator::next() libreoffice/online-san/test/../kit/Delta.hpp:96:23
#1 0x558e8e0b8304 in DeltaTests::testRleComplex() libreoffice/online-san/test/DeltaTests.cpp:317:16
Change-Id: I01da1e99b5d224411344659dce8bd2f29e7d74b0
* Resolves: # 
> fix asan build test

- kit/Delta.hpp
but as seen with unit-tiletest that is not always the case
==24170==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x63400001e808 at pc 0x558a6f505973 bp 0x7ffc0670e7d0 sp 0x7ffc0670e7c8 READ of size 8 at 0x63400001e808 thread T0 (kitbroker_002)
#0 0x558a6f505972 in DeltaGenerator::DeltaBitmapRow::initRow(unsigned int const*, unsigned int) Delta.hpp:129:36
#1 0x558a6f4fc318 in DeltaGenerator::DeltaData::DeltaData(unsigned int, unsigned char*, unsigned long, unsigned long, int, int, TileLocation const&, int, int) Delta.hpp:233:21
#2 0x558a6f4f8a22 in DeltaGenerator::createDelta(unsigned char*, unsigned long, unsigned long, int, int, int, int, TileLocation const&, std::vector<char, std::allocator<char> >&, unsigned int, bool) Delta.hpp:574:17
#3 0x558a6f4f2a35 in …
> the tile is assumed to be 256 in width

- browser/src/core/Log.js
Otherwise it could grow without bound; now limited to 100 entries, each of <128 characters.
Change-Id: I6a1b96a8cb6a67f991c3870f5b724989f65e0e74
* Resolves: # 
> Limit memory usage of internal log storage.

- browser/src/control/Control.PartsPreview.js
Show New Slide and Paste (if clipboard is not empty) on context menu when the user cliked on the empty parts of the slides pane.
Change-Id: I3d009499cc4400612f1246c28ce5478b80469428
* Resolves: # 
> Show the context menu on click empty parts of slides pane
