CollaboraOnline/online

browser/src/control/Control.Sidebar.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/map/handler/Map.StateChanges.js, common/RenderTiles.hpp, kit/ChildSession.cpp, kit/DummyLibreOfficeKit.cpp
this one requires core change: https://gerrit.libreoffice.org/c/core/+/137869
=> masterpage: followup (part 2)

wsd/HostUtil.cpp
regression from commit 3aa3334a7b2b0abad7a07beefa881be62a83020b
Change-Id: I601ea3bde0419129e39c1a1454c22c676d4870bd
* Resolves: # 
=> wsd: fix: wopi.host not working when alias_groups are not defined

kit/Delta.hpp
Small deltas were not compressed at all, now they are.
Change-Id: I0543a488723816b4140b27c5690f657aea26226e
* Resolves: # 
=> zstd: tune for speed, and compress deltas.

browser/src/control/Control.Menubar.js
regression from https://github.com/CollaboraOnline/online/pull/5252
=> Fixes#5488 Sens UI_SaveAs also on mobile

wsd/COOLWSD.cpp
introduced in e0752419575f09fef3d770f8cccf78c92a2d8612 commit. clearing new remote config after addWriteable resulted into removing data from top layer of Poco::LayeredConfiguration. This patch makes sure to remove old layer of remote config before applying the new layer
make sure to update the feature_lock.lock_hosts[@allow] first before returnng
Change-Id: If11bd6e4b3a0a9f4ee32ae9bb43b076479e9bd84
* backport of : #5507 first commit 
* Target version: co-21-11
=> wsd:fix: memory leak properly

gtk/Makefile.am, gtk/README, gtk/gtk.hpp, gtk/mobile.cpp, wsd/Storage.cpp
Change-Id: I000fdcc059c39cf3c0c4a9ec066f4039c653cb70
* Resolves: # 
=> Make the gtk app build again

browser/src/core/Socket.js, gtk/README, gtk/mobile.cpp
=> Make the gtk app work again

wsd/ClientSession.cpp, wsd/DocumentBroker.cpp
Each commit describes what it does. These are unrelated, but small enough to get reviewed together.
- wsd: more flexible 'save' command parsing
- wsd: improve DocBroker state dumping logic
- wsd: faster forwardToChild
=> Improved Save, Load, and State-Dump Processing

.cirrus.yml, Makefile.am, configure.ac, test/Makefile.am
Change-Id: I109242bde268e63e9918af0f44fcb456e2b8f6c5
* Resolves: # 
The goal is to create binaries that can run on any Linux distro.
=> enable link to non-system libpng and openssl

browser/html/cool.html.m4
Also need to free them afterwards. Later.
Change-Id: Ie09f268132d01fb51a7126fc3c97272f1e11246c
* Resolves: # 
=> Need to pass strings to C++ with allocateUTF8()

browser/css/mobilewizard.css, browser/src/control/Control.AlertDialog.js, browser/src/control/Control.JSDialog.js, browser/src/control/Control.UIManager.js, cypress_test/integration_tests/mobile/writer/insert_object_spec.js
showModal is going to be replacement for vex
=> jsdialog: introduce showModal

net/WebSocketHandler.hpp
- wsd: simplify WebSocketHandler construction
- wsd: avoid locking weak_ptr when possible
=> Reduce Duplication in WebSocketHandler

browser/css/jsdialogs.css, browser/css/jssidebar.css, browser/css/mobilewizard.css, browser/src/control/Control.JSDialog.js, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardWindow.js, browser/src/control/Control.Notebookbar.js, browser/src/control/Control.Sidebar.js, cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
This is PR which introduces CSS grid to the jsdialogs instead of old table design.
It should be polished before merge.
=> jsdialog: simplify structure

gtk/Makefile.am
Change-Id: I075e69a385ec508d72a5d6e4b775dd932bca5184
* Resolves: # 
=> The gtk app needs PNG_LIBS

gtk/mobile.cpp
Change-Id: I544abda3744fc5415a4dfd935e0df864c5765ca3
* Resolves: # 
=> Enable developer console for webkit debugging.

browser/css/jssidebar.css
This also allow for one single shared place to have that
"margin"
Change-Id: Iac46810ac4ef219a4103bc315722dbd95e6fd169
=> JSSidebar: fix no vertical space by adding row gap

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
- wsd: autosave -> autoSave for readability and consistency
- wsd: move idleSaveInterval in SaveManager
=> Fix Saving on Idle Timeout

browser/src/control/Control.DocumentRepair.js
Allow Cancel button to be translated
Change-Id: I4e74bf23bea0edba5dad13f53967d380567dbdc7
=> Localization: Fix cancel button in document repair dialog

browser/src/control/Toolbar.js
Follow-up to 4ba2c209971913a2b53e0be5324ef4009218a564.
Change-Id: Id74c1ea9557e793386ba39844e7a03ddc766b7c0
=> browser: fix JSON syntax in print settings

gtk/Makefile.am
Change-Id: Ic0aaf8c944fa10ec370a0b733d1f5c881ea349ce
* Resolves: # 
=> Need Zotero.cpp here, too

browser/css/mobilewizard.css
Change-Id: I21b8095843393d924a6790e18eaa3f868516f90d
* Resolves: #5490 
=> remove fontheight rule from mobilewizard.css

browser/js/global.js
Change-Id: Ie6f713f062e9c89ed3679d709394089413184d0d
* Resolves: # 
=> sendCounter is unused

wasm/Makefile.am, wsd/COOLWSD.cpp
=> Minor build fixes

wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
- wsd: pass ClientSession to uploadAsToStorage
- wsd: pass ClientSession to sendUnoSave and simplify
- wsd: pass ClientSession to forwardToChild
=> More Avoid Repeated ClientSession Lookup

browser/src/control/Control.Menubar.js
Also make sure that new menu is only visible if zotero is
available
Change-Id: I0893515dbc5495aa8251fc9ca795fea357400e6c
=> Add zotero actions to menubar (compact mode)

test/UnitPasswordProtected.cpp, test/UnitWSDClient.hpp
Modernize the document password tests.
=> wsd: test: modernize password tests

browser/css/jsdialogs.css, browser/src/control/Control.UIManager.js, browser/src/control/Control.Zotero.js
- fixes border under notebookbar's tabs
- show dialog while waiting for server response
- added "collections" and "groups" tree
=> zotero: followup for jsdialog

browser/admin/admin.strings.js, browser/src/control/Control.Menubar.js, browser/src/control/Toolbar.js, browser/src/core/Socket.js, browser/src/layer/marker/ProgressOverlay.js, browser/src/map/Clipboard.js, docker/from-packages/RHEL8, docker/from-packages/Ubuntu, docker/from-packages/scripts/install-collabora-online-rhel8.sh, docker/from-packages/scripts/install-collabora-online-ubuntu.sh
Change-Id: I231f06f509c2d70ba092658b828e1d201cef2887
* Resolves: # 
=> Add '(unbranded)' string to product name, when branding is missing

common/StateEnum.hpp, wsd/COOLWSD.cpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp
- wsd: use ClientSession in refreshLock
- wsd: flush sockets only when we have any
- wsd: support short-form names in STATE_ENUM
- wsd: shorter wait between cleanup checks on exit
- wsd: DocBroker dumps isStorageOutdated
- wsd: clang-tidy fix of initializing a string member
=> Misc Improvements

browser/src/control/jsdialog/Widget.TreeView.js
=> jsdialog: filteing also non header list

browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ib8d5bedba3a6d9c05a26a73edd81b52cd94e3358
* Resolves: # 
=> Fix the insert hyperlink behaviour on Calc.

browser/src/control/Control.Zotero.js
Change-Id: I52710acb3a56e8930438d07cfe28be491e0161b7
=> zotero: add zotero citation data json with field mark

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
Change-Id: I86880ab3c54994554ab7f91921d028f962318e5a
* Resolves: # 
=> Make export EPUB/PDF always with options dialog (Calc, Impress, Draw)

browser/src/map/handler/Map.Keyboard.js
It tries to bring up formula bar, which is unsupported, and causes issues.
Change-Id: I9aaf445fde9ed5fa507e503e72319b6c7a146e44
=> browser: Disable F2 handling in Writer

browser/css/jsdialogs.css, browser/src/control/Control.Zotero.js, browser/src/control/jsdialog/Widget.TreeView.js
- use correct selection for insertion
- a11y: tab works in treeview
- subcollections in the tree
=> zotero improvements

browser/src/control/Control.Zotero.js
=> Zotero: use correct index for entries

browser/src/control/Control.Zotero.js, browser/src/layer/tile/WriterTileLayer.js, browser/src/map/Map.js
Change-Id: Ib29683c96bb4037a1084baee282fb4b066018d38
=> zotero: set citation style

net/Socket.hpp, net/WebSocketHandler.hpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/TileCache.cpp, wsd/protocol.txt
- wsd: correctly log the time since upload request
- wsd: log number of unremoved sessions when destroying DocBroker
- wsd: minor log improvements
- protocol: minor documentation fixup
- wsd: correctly clear the stream caches in TileCache
=> Misc Non-Functional Improvements

browser/src/layer/tile/CanvasTileLayer.js
avoid comparison with undefined for mode param
=> Calc: show cursors from others

browser/src/control/Control.Menubar.js, browser/src/control/Control.Zotero.js, browser/src/control/Toolbar.js, browser/src/layer/tile/WriterTileLayer.js, browser/src/map/Map.js
Change-Id: If6d1f2189eb27785cd2bb2d15a50ee01c4735afc
=> zotero: insert bibliography

browser/css/jsdialogs.css, browser/src/control/Control.Zotero.js
set and fetch citation language for zotero
=> Zotero localization

browser/src/control/Control.Zotero.js
Change-Id: Id375958bd17b528dee7e9000d056ca60da064133
=> zotero: fixed broken item query function

browser/src/control/Control.Zotero.js
Change-Id: I420c5f22f8b4aa880f202fe8b0d981f091c1dfa7
=> zotero: in style dialog show selected style

coolwsd.xml.in, wsd/COOLWSD.cpp
Change-Id: I0e05ed89d02a9b467e1707db1638fc9ee554586a
=> config: add REST API Protocol to LanguageTool

browser/src/control/Control.Zotero.js
Change-Id: I048d351e5590413fe57e1ac009bd96933e73b5df
=> zotero: add missing fields in style property

browser/src/control/Control.Zotero.js
Change-Id: I6aab932715cdfc9511f0b96b4f6aaf671f0b6efb
=> zotero: avoid asking unnecessary bibliography data

browser/src/control/Control.Menubar.js, browser/src/control/Control.Zotero.js, browser/src/control/Toolbar.js, browser/src/core/Util.js, browser/src/map/Map.js
=> Zotero citation update

browser/src/control/Toolbar.js
Change-Id: I59b5c7a66ae5811331a53288146c5965dcf610e3
* Resolves: # 
=> Remove extra sidebar command.

browser/src/control/Control.Menubar.js
Change-Id: Id82bb40ef7a86f6c2a068896cdfb3084e63aaf60
* Resolves: # 
=> Re-show formula bar if only the document is a spreadsheet.

browser/src/control/Control.Zotero.js
- after citation refresh
- after style change
=> Zotero: show snackbar on citations update

Makefile.am, configure.ac, wasm/Makefile.am, wasm/README, wasm/poco-1.12.4-emscripten.patch, wasm/poco-devel-emscripten.patch, wasm/wasmapp.cpp, wasm/wasmapp.hpp
=> Start cherry-picking commits from the feature/wasm branch

browser/src/control/Control.Zotero.js
- in the new document it will show selection on last used style (we still have to download style data so we will show the dialog)
=> Zotero: remember last used style

common/SigUtil.cpp, common/Util.cpp, wsd/COOLWSD.cpp, wsd/Storage.cpp
=> Continue cherry-picking commits from the feature/wasm branch

browser/src/control/Control.Zotero.js
Merge after:
- online: https://github.com/CollaboraOnline/online/pull/5651
- richdocuments: https://github.com/nextcloud/richdocuments/pull/2726
=> Zotero: use private info for key

browser/js/global.js
Change-Id: I849948c69e9cc656c410513f9f95db2e7fb07e03
* Resolves: # 
=> share css-url renamer with branding

browser/src/control/Control.Zotero.js, browser/src/layer/tile/WriterTileLayer.js
Change-Id: I2cddea94988c12459e35c83ca9327c2a0a32f0f9
will require some changes on the core side. work is in progress for it.
=> zotero: introduce bookmark support for zotero citation

browser/src/control/Control.Zotero.js
Introduced bibliography for all field types (refmark, fieldmark, bookmark)
=> Zotero bib

browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I1e537108e4ad43f5e7161e629c8fa72387eac3e2
* Resolves: # 
=> delta: add trace events to monitor delta performance better.

browser/src/control/Control.Zotero.js
it reads citation style and shows only available languages if last used locale is available - use it
if not - use default defined by style
=> Zotero: check available languages

cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/desktop/impress/annotation_spec.js, cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
Change-Id: Ic04ed73d91d3a019d89406322045221370349ac7
* Resolves: # 
=> cypress:refactor: undo_redo_spec.js

browser/css/jsdialogs.css, browser/src/control/Control.Zotero.js, browser/src/control/Toolbar.js
Change-Id: I0387d01e3e4eaec7a11e9ef58c790b1719f9abee
=> zotero: update bibliography together with citations

browser/src/control/Control.Zotero.js
renumber the identification number in bibliography to match the citation number
Change-Id: Ic1eec6044e45c2b24aff1f9127fdb13cdab97313
=> zotero: renumber numeric bibliography

browser/html/cool.html.m4, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Control.UIManager.js, browser/src/control/Control.Zotero.js, browser/src/layer/tile/WriterTileLayer.js, browser/src/map/Map.js, wsd/FileServer.cpp
- It sends post message to the integrator: UI_ZoteroKeyMissing if API key was not provided in CheckFileInfo and user tried to perform any action on bibliography
- It shows snackbar with message that key is missing
- It hides bibliography functionality if zotero.enable = false is set in coolwsd.xml
=> Zotero: ask integrator if key is missing

browser/src/control/Control.UIManager.js, browser/src/core/Socket.js, browser/src/map/handler/Map.Welcome.js
- Missing Fonts dialog: Use JSDialog instead of Vex, allow dismiss
- Fix Missing title on showInfoModal when on a mobile
=> private/pedro/font missing to jsdialog T39589 T39329 T39075

browser/css/device-desktop.css
Change-Id: Ic07482aebe79e1dbd796acafbbd132a1449fe121
=> Fix invisible text on primary button (hover)

browser/src/control/Control.Zotero.js, browser/src/layer/tile/WriterTileLayer.js
* Resolves: # 
This set of commits will allow us to insert multiple citations at a place which will be merged according to the rules of the citation style selected. 
required core patches to be merged first:
https://gerrit.libreoffice.org/c/core/+/145413
https://gerrit.libreoffice.org/c/core/+/145459
=> Zotero cluster

browser/src/control/Control.Zotero.js, browser/src/control/Toolbar.js
Add also notification once they are unlinked
Change-Id: Id26f7228f5a845b79f941256738a0d83bd12e43f
=> Inform user about all the implication related to unlinking citations

browser/src/control/Control.Menubar.js
- browser: menu: ignore menu item with empty text
- browser: move "Default Language" menu to the last
- browser: add "More..." menu item to Language menu
- browser: add "More..." menu entries specific to writer
* Resolves: # 
=> Add More... menu language entry

browser/html/cool-help.html
Signed-off-by: Hannah Meeks <hmeeks4135@gmail.com>
* Resolves: # 
=> Dialogs: Help Page - Spelling Fix

browser/css/spreadsheet.css
Change-Id: I956f199bd69c32639d1b75993769c18fd85be693
=> Increase color contrast on calc's dropdown marker

browser/src/control/Control.ContextMenu.js
Change-Id: Icb08839c28847e90605cae808b9d6441d5fc2f51
* Resolves: # 
calcRTL-ui: open submenu to left
=> calcRTL-ui: open submenu to left

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js
Change-Id: Iaee293f4d3b1d9ee4779abc89be9e3662d8026bb
* Resolves: # 
=> Improve JSON data handling for response buttons.

browser/src/control/Control.Zotero.js, browser/src/layer/tile/WriterTileLayer.js
fixed regression: user was note able to insert any citations as bookmark
This also reduces number of queries to find the citations under the cursor
Change-Id: I40148e61a0109e5a807b50ea0121ab623bc41e4d
=> zotero: fixed bookmark insertion

browser/css/jssidebar.css
- Sidebar fix cropped checkbutton label
- Fix checkbutton label vertical alignment and spacing
=> private/pedro/fix T36058 checkbutton sidebar

browser/src/control/Control.Toolbar.js, browser/src/control/Control.Zotero.js
this also helps in case of undo
Change-Id: I880fa4589f4b40e3f7733ff59f3c6866f82db899
required core patches:
https://gerrit.libreoffice.org/c/core/+/145753 
https://gerrit.libreoffice.org/c/core/+/145774
https://gerrit.libreoffice.org/c/core/+/145777
https://gerrit.libreoffice.org/c/core/+/146007
=> zotero: handle citation field deletion

wasm/Makefile.am
Change-Id: I9c6c7075fff9d67c921d0c525eb8c0fe474b847c
* Resolves: # 
=> Bump PTHREAD_POOL_SIZE to 15

browser/html/cool.html.m4
Change-Id: Icb7c280c20ed02ef5840272a0e979e1446af2b56
* Resolves: # 
=> Stop using Qt for COWASM

wasm/Makefile.am
Change-Id: Ie7814a0f0f02a577f641a7d223fbb0c81ab3b2ab
* Resolves: # 
=> Use -gseparate-dwarf like in core

browser/html/cool.html.m4
Change-Id: I832414864130b9baa1ce7577b3006c7c37dc14eb
* Resolves: # 
=> Use branding.css also in the EMSCRIPTENAPP case

wasm/wasmapp.cpp
Change-Id: I50285b974403e95f48106950a81a1ea9bbd95b86
* Resolves: # 
=> Use COOL log level 'error' instead of 'trace'

browser/src/control/Control.Menubar.js, browser/src/control/Control.PresentationBar.js, browser/src/control/Control.UIManager.js, browser/src/control/Toolbar.js, cypress_test/integration_tests/desktop/impress/slide_operations_spec.js, cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js, cypress_test/integration_tests/mobile/impress/slide_operation_spec.js
can be found in menubar -> slide -> delete
=> jsdialog: convert delete slide modal from vex

browser/src/control/Toolbar.js
Change-Id: I9b74978f7778a9772f69e0d3ad982945cd646120
* Resolves: # 
=> Keep focus on map after hyperlink dialog closed

browser/Makefile.am, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/jsdialog/Widget.MultilineEdit.js
- moved to separate file
- removed jQuery usage
- arrow up/down navigation in formulabar in Chrome fixed
=> jsdialog: multiline edit cleanup

browser/src/control/Control.ColumnHeader.ts, browser/src/control/Control.Header.ts, browser/src/control/Control.RowHeader.ts
click and drag mouse pointer on row/column headers to select them in calc
=> calc: allow to select mutliple columns using mouse

browser/src/control/Control.Menubar.js
Change-Id: I610b6e2d01b5e202c6c2689a76d7f22acd141a8c
* Resolves: # 
=> 22.05: Compact view: Citations update name values

browser/src/control/Control.UIManager.js, browser/src/control/Control.Zotero.js
Change-Id: I8429e81c58e72e846ce39de47e883ab6c96c8ebe
=> zotero: introduced support for endnote and footnote citation

browser/src/control/Control.JSDialogBuilder.js
we need to use containerHandler to get response bindings
=> jsdialog: handle standard responses in messagebox

docker/from-packages/RHEL8, docker/from-packages/Ubuntu, docker/from-packages/Ubuntu-ppc64le
* Resolves: # 
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
N/A
=> Use COPY rather than ADD in Dockerfiles

browser/src/control/Control.TopToolbar.js
Signed-off-by: Tushar <tusharbarman123@gmail.com>
Change-Id: I0cbbd1653ff49beb12fc51ebd8b9d66b532ca406
* Resolves: # 
=> solves toggleMenubar wrong icon. Fixes issue #2816

coolwsd.xml.in
Change-Id: I0350cc2005325cec378a8942e3294ed18a66538a
=> Better documentation of remote grammar checker settings

cypress_test/integration_tests/desktop/impress/searchbar_spec.js, cypress_test/integration_tests/desktop/impress/undo_redo_spec.js, cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js, cypress_test/integration_tests/mobile/impress/searchbar_spec.js, cypress_test/integration_tests/mobile/impress/undo_redo_spec.js
Change-Id: Id3a2555cc9e3adbcf1a616ec3c5d4404c7293c5b
=> cypress: disable impress searchbar tests

common/FileUtil.cpp
Change-Id: I17bb678d0bc977b4355745142f4ccc882652a677
* Resolves: # 
=> Avoid CodeQL warning

browser/Makefile.am, browser/src/control/Control.LanguageDialog.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.StatusBar.js, browser/src/control/Control.Toolbar.js, browser/src/control/Control.TopToolbar.js, browser/src/control/jsdialog/Widget.LanguageSelector.js, browser/src/docstate.js, browser/src/map/Map.js
- unified menus in notebookbar (no more, multi level menu)
- unified 10 favourite languages and More... button in statusbar, menubar and notebookbar
- dialog for "more..." languages
This helps with LanguageTool where we have available
lots of languages and list cannot appear fully on the screen.
Test together with: https://gerrit.libreoffice.org/c/core/+/146665
And LanguageTool for list with 20+ languages.
=> Unified language/spell checking menus

common/FileUtil.cpp, common/SigUtil.cpp, common/Unit.cpp, net/ServerSocket.hpp, net/Socket.cpp, net/WebSocketHandler.hpp, wsd/COOLWSD.cpp, wsd/Storage.hpp
Change-Id: I0fd4fe36cece9caaeb076a0e91894890186706d0
* Resolves: # 
=> Fix compiler warnings when building for WASM.

wasm/README, wasm/README.no-container.md
Change-Id: I8c1697732a9102197d4c273c23e60378420e598a
* Resolves: # 
=> Provide separate documentation for building COWASM without the container

browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js
Change-Id: I1be5a42b99571309782d6624e6487d6d5817dc57
=> browser: Add LTR/RTL text direction commands to Calc tab bar and menu

browser/src/layer/tile/CanvasTileLayer.js, wsd/COOLWSD.cpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp
- wsd: log improvements around media handling
- wsd: play media when selected by other views
=> Improved Media Playback

wsd/Admin.cpp, wsd/Admin.hpp
regression from 49bac0da174e31fcdbe5a4458f2f2100d606b6dc
Change-Id: Id006db718d49da2b1f9142c4d6d5c6985b18ecc9
=> admin: fix: monitor doesnot try connecting again after disconnecting

browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I6760ade82caf4b268955642181b04cfff83b3f4e
=> browser: handle no graphic-selection when showing media

.github/workflows/add-issue-to-project.yml, .github/workflows/add-pr-to-project.yml
Change-Id: Ib28cf0dd5381cd5617ff8f6f2cdc7c564a0ebe0a
=> GitHub Actions to automate project: Add PR to project

browser/css/toolbar.css, browser/src/control/Control.Toolbar.js
Fixes #5418
Change-Id: I12efe479c77ebd4c91ebe50687799da9e695e262
=> Improve connectors popup dropdown #5418

browser/admin/src/AdminSocketBase.js
Change-Id: I73192156e7a5a95bf757111db01f95bb38c6e80e
* Resolves: # 
=> Remove vex usage from AdminSocketBase.js

browser/src/layer/Popup.js, browser/src/layer/tile/CanvasTileLayer.js
- browser: extract internal link bookmark
- browser: enable URL popup internal hyperlink
- browser: send ".uno:JumpToMark" command
* Resolves: # 
=> Internal links in Calc

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/unocommands.js
Change-Id: I2781b7ff4a0ba4fa93a49ae2d62ba18d35789e52
=> browser: add switch between RTL/LTR to Calc main menu

README.FILENOTICES.md
Change-Id: I98d5bf92cd1c354b9f448272f397681101b81715
=> File Notices recommendation

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js
Change-Id: I7938f042e3d8a49887bd15e4e5e2331bcfff133c
=> Tablet: tabbed view: Allow user to go back to read only mode

browser/src/control/Control.Menubar.js
Change-Id: I9d8ae8c4585c86b53eff952a96b1494da7197746
=> Compact view: Do not show translate if the respective op is false

browser/css/menubar.css
Change-Id: I29a899a1113c6188558e8b85bf9adde5bc9049fe
* Resolves: # 
=> Hide sidebar button on readonly mode.

browser/Makefile.am, browser/package.json, browser/src/layer/tile/ContentControlSection.ts
replaced jquery-ui-dist node_module with jquery-ui for localization
Change-Id: I6dd95cb8859cd2e0626195a0b87b496fe44afc49
* Resolves: # 
=> js: added localization for jquery-ui datepicker

browser/css/cool.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/map/handler/Map.WOPI.js, wsd/DocumentBroker.cpp, wsd/Storage.cpp, wsd/Storage.hpp
1) Insert > "Pick Link" button is shown when `CheckFileInfo` contains `EnableRemoteLinkPicker`.
After press `UI_PickLink` is send via postMessage to integrator.
Action should be finished with sending back `Action_InsertLink` to editor with JSON `{ url: .... }`
Links then is inserted into document.
2) When user clicks on link, preview popup appears with "Loading..." text
At that time editor sends via postMessage `Action_GetLinkPreview` with JSON `{ url: ... }`
Integrator should send back   `Action_GetLinkPreview_Resp` with JSON ` { url: ..., title: 'some text', image: 'base64 encoded image'}`
=> Insert link

browser/src/control/Control.JSDialogBuilder.js
Change-Id: Ibd5a2d6de35c2f7142afe0254f4133746152226d
related core patch: https://gerrit.libreoffice.org/c/core/+/148145
=> jsdialog: support toggle event for push buttons

browser/admin/src/AdminSocketOverview.js, browser/po/templates/cool-ui.pot
Change-Id: I04bab594327d9e75fe612bf84ee047e58a71ff22
* Resolves: # 
=> Remove vex dialog from AdminSocketOverview.js file.

ios/Mobile/AppDelegate.mm, ios/Mobile/Resources/Settings.bundle/Root.plist.in
Copy pull request #5890 but completely remove the old code in the master branch
Change-Id: I69d03bb3f10e756823ba2e32aae0c099c54928c5
* Resolves: # 
=> Remove template list URL from application settings

browser/src/control/Control.JSDialog.js, browser/src/control/Control.UIManager.js
Add an empty callback for the busypopup window.
Change-Id: I84ed797feed93cfad6a66f1a4981ecacce23f104
* Resolves: # 
=> Send close message to core side when closing all jsdialog windows.

browser/src/layer/marker/TextInput.js
Change-Id: I0ac901dc0d5a53e82be70d3c89f17e03b8872989
* Resolves: #5342 
Empty area when pressing `Esc`
=> Fixed missing % upon pressing the escape key

browser/src/control/Control.Tabs.js, browser/src/control/Control.UIManager.js, cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js, cypress_test/integration_tests/mobile/calc/sheet_operation_spec.js, cypress_test/integration_tests/multiuser/calc/sheet_operations_spec.js
Change-Id: I605104e16ab02d106717319e4a9bff537db13e3c
* Resolves: # 
=> Remove vex from delete sheet modal.

cypress_test/integration_tests/desktop/calc/image_operation_spec.js, cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js, cypress_test/integration_tests/desktop/impress/annotation_spec.js, cypress_test/integration_tests/desktop/impress/undo_redo_spec.js, cypress_test/integration_tests/desktop/writer/scrolling_spec.js, cypress_test/integration_tests/mobile/writer/searchbar_spec.js
=> Cypress flaky tests

browser/src/control/Control.AlertDialog.js, browser/src/control/Control.IdleHandler.ts, browser/src/control/Control.UIManager.js
Change-Id: Ibc437f14d36594763ddf70639d0c5d3fa2531d72
* Resolves: # 
=> Remove vex dialogs from alertdialog.js file.

browser/src/control/Control.JSDialogBuilder.js
Change-Id: I288b1c1b013dd0a1395f6f18890b09582f309fbc
=> jsdialog: use display grid for vertical button box

browser/src/control/Parts.js, cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js, cypress_test/integration_tests/mobile/calc/sheet_operation_spec.js
Change-Id: I85a754f2bb6bd738bd30384c9b40f40104daacc5
* Resolves: # 
=> Remove vex from parts.js.

wsd/DocumentBroker.cpp
Change-Id: I0c59c4fb3c99dee0f6e18850ca795467a9421b33
=> wsd: make sessions readonly on disk errors

browser/src/control/Control.Command.js, browser/src/control/Control.MobileWizardWindow.js
Change-Id: Ib5df6c75c5f837cb7ccc0060f6b762d2a9fea1bc
* Resolves: # 
=> Remove vex dialog from command.js.

browser/css/cool.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/map/handler/Map.WOPI.js, wsd/DocumentBroker.cpp, wsd/Storage.cpp, wsd/Storage.hpp
- added button Insert -> Pick Link
- added shows link preview in popup when link is clicked
=> link picker 22.05

browser/src/control/Control.Toolbar.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/main.js, kit/ChildSession.cpp, wsd/COOLWSD.cpp, wsd/ClientSession.cpp, wsd/ClientSession.hpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
- endpoint extract-link-targets
- endpoint get-thumbnail
- jump to target after document is opened
=> Link target

browser/src/control/Permission.js
Change-Id: I240e6771ab1f57118cfa263fda1566349a38f8ac
* Resolves: # 
=> Remove vex from confirmation dialogues.

browser/js/global.js, wsd/AdminModel.cpp, wsd/protocol.txt
Change-Id: I5c11cc7aa6f705184a9607dece88ab106b85a856
* Resolves: # 
=> indirection_endpoint improvements

wsd/COOLWSD.cpp
Change-Id: I805e27df25d3134eb12926f28b6f9ff09b4ed230
=> Stop erasing the whole tmp directory after a download

browser/src/control/Control.UIManager.js, browser/src/control/Permission.js, cypress_test/integration_tests/desktop/calc/open_different_file_types_spec.js
Change-Id: I444ea61eb6cf6c92858833a30be92ee9a6a36509
* Resolves: # 
=> Remove vex from _switchToEditMode function in permission.js.

browser/src/control/Control.UIManager.js, browser/src/core/Socket.js
Change-Id: Ibd7364e44d14eaca025037c37d85cb621a2ebec5
* Resolves: # 
=> Remove vex from password dialog.

browser/src/control/Control.Mention.js, browser/src/control/jsdialog/Widget.TreeView.js, browser/src/layer/marker/TextInput.js
- forcefully send unocommand to insert popup is still opened
- fix navigation using ArrowKeys in treeview
Change-Id: I6dd75b8b576754513574749e1bd9675581caeabf
* Resolves: # 
=> fix: mention cannot be inserted

browser/src/main.js
Change-Id: Ia15f57817a892753b3579eee8f38366f36f44672
* Resolves: # 
=> Remove vex from main.js.

browser/src/control/Control.UIManager.js, browser/src/core/Socket.js
Change-Id: I7b57fd57ce4809e4d829e6e4224f4486c7c88259
* Resolves: # 
=> Remove vex from documentconflict message.

Makefile.am, configure.ac, debian/changelog
Change-Id: Ic81a642decb73ba24ac9eaa0951cc6e50ebbb53a
* Resolves: # 
=> Bump version to 22.05.11.1

browser/Makefile.am, browser/css/jsdialogs.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/jsdialog/Widget.ScrolledWindow.js
- it implements scrolled window (used eg. in Function Wizard in Calc)
=> jsdialog: scrolled window

browser/Makefile.am, browser/css/jsdialogs.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/jsdialog/Widget.DrawingArea.js, browser/src/control/jsdialog/Widget.MenuButton.js
this is used in:
- Calc -> Insert -> Symbol
- Calc -> Data -> Standard filter (https://gerrit.libreoffice.org/c/core/+/148787)
=> jsdialog improvements - drawingarea

cypress_test/integration_tests/desktop/calc/autofilter_spec.js, cypress_test/integration_tests/desktop/calc/delete_objects_spec.js, cypress_test/integration_tests/desktop/writer/scrolling_spec.js, cypress_test/integration_tests/desktop/writer/statusbar_spec.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js, cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js, cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
Change-Id: If4c2b252ca53ecfe4e3db6722d2bb7cb5069a242
* Resolves: # 
=> cypress: updated the test for core co-23-05

browser/css/jsdialogs.css, browser/src/control/jsdialog/Widget.ScrolledWindow.js
test with: https://gerrit.libreoffice.org/c/core/+/148789
=> jsdialogs: improvements for calc Data -> Sort dialog

browser/js/global.js, browser/src/layer/tile/ContentControlSection.ts
Change-Id: Id03cccad6964e7555de6300b0eac619bf521802b
* Resolves: # 
* Target version: co-22-05
=> fix: date picker always in norwegian

browser/css/color-palette.css, browser/css/cool.css, browser/src/control/Control.MobileWizardWindow.js, browser/src/layer/tile/CommentListSection.ts, cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/common/mobile_helper.js, cypress_test/integration_tests/desktop/writer/help_dialog_update_spec.js, cypress_test/integration_tests/mobile/calc/annotation_spec.js, cypress_test/integration_tests/mobile/impress/annotation_spec.js, cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js, cypress_test/integration_tests/mobile/writer/annotation_spec.js, cypress_test/integration_tests/mobile/writer/insert_object_spec.js
Change-Id: Ie548bc5576bc7a7afb426f9cf9ef4a7c1cafbb88
* Resolves: # 
=> Remove vex from comments.

browser/css/notebookbar.css, browser/src/control/Control.JSDialogBuilder.js
Change-Id: If418a3d50da2d66e17277e64adc462b9a111816c
* Resolves: # 
=> Turn tab buttons into button elements from span elements.

coolkitconfig-mobile.xcu, ios/Mobile/Base.lproj/Main.storyboard, ios/Mobile/DocumentBrowserViewController.mm, ios/Mobile/TemplateCollectionViewController.h, ios/Mobile/TemplateCollectionViewController.mm
This is a near duplicate of pull request #6046 for the master branch.
=> Fix issue #1962 Dismiss view by tapping outside of the view and add a cancel button

browser/src/control/Control.UIManager.js, browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ia53de291acf90f0d40ae7aea97fa6de0896938df
* Resolves: # 
=> Remove isAnyVexDialogActive from canvastilelayer.

browser/src/layer/tile/TilesSection.ts
Change-Id: I8c34f2ad7370b2dcc7e4c03522c30d8df394b4a3
* Resolves: # 
=> Remove focus from slides pane when map is clicked.

test/TileCacheTests.cpp
Change-Id: I1103d6c5f474b2f177189f3cc82030be7340235c
=> Uncomment most TileCacheTests

browser/src/control/Control.JSDialogBuilder.js
Change-Id: I80e12330e202890b0c98388b225a1f58e8f2e965
* Resolves: # 
=> Switch focus to map when menu is focused and ESC is pressed.

kit/ChildSession.cpp, kit/ChildSession.hpp, kit/Delta.hpp, kit/Kit.cpp, test/WhiteBoxTests.cpp, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp
Builds on a new LOK API to do the same in the core.
Change-Id: I4443cd2ffbb6c7af0726162aec2ba78fc354d901
* Resolves: # 
=> trim memory when user is inactive.

browser/css/btns.css, browser/css/notebookbar.css
Tabs were changed to buttons and thus we need to readjust the CSS
so text color and others are correctly applied to the text
Also add :not exception so the tabs are not styles as regular buttons
Change-Id: I1bc1681e86f17ee7afb435f7c3fc099b80abac2e
=> Fix main tabs text styles on tabbed view

browser/src/control/Control.NotebookbarWriter.js
Change-Id: Icc8f20885236e65fbbc0fa9c0d02af30c120968f
* Resolves: #1546 
=> Add chapter numbering option into format tab on tabbed view.

browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
Change-Id: If4bb4c16855ee4a8f2cb3e0c2f7b7516b4275c42 (cherry picked from commit 6e0b1debbb2146a9a69c4d3786758c6809413ada)
* Target version: co-22.05
=> Hide download in tabbed view when HideExportOption is true

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js
reuse dispatch commands between menubar and notebookbar
=> simplify notebookbar items

browser/css/jsdialogs.css, browser/css/mobilewizard.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/Control.UIManager.js, browser/src/control/Parts.js, browser/src/control/Toolbar.js, browser/src/control/jsdialog/Widget.ScrolledWindow.js
requires: https://gerrit.libreoffice.org/c/core/+/149717
=> jsdialog: use labelFor property for labels

browser/css/cool.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/docstate.js, browser/src/layer/marker/TextInput.js
Change-Id: I3ba2249d8e2441d013c09bf8b552498661fd069f
* Resolves: # 
=> access keys support is being prepared.

browser/src/control/Control.JSDialog.js
Change-Id: I99251c1f35b23a5b1a41bbe1820efcf090353db4
* Resolves: # 
=> Set focus to last element after a popup window is closed.

browser/src/map/handler/Map.Keyboard.js
Change-Id: I43bbb0d6a795ef11d43eb7ab2845f6f4674ca722
* Resolves: # 
=> Provide a way to focus on the menu from map.

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js
Change-Id: I64b8fd378abdedf0e97bcb3075da13799460f01b
* Resolves: # 
=> Use htmlFor attribute for labels.

browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.NotebookbarWriter.js
Change-Id: Ie2ff0d212e0dc55eadf32e9fbbfb5abd0ee8bf68
* Resolves: # 
=> Avoid duplicate ids.

browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
Change-Id: I26cfae75d65fc2588225b22b752a34571d5abc34
* Resolves: # 
=> Update shortcuts for accessibility.

browser/src/control/Control.JSDialogBuilder.js, browser/src/core/Socket.js, browser/src/map/handler/Map.WOPI.js, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp
Change-Id: I2e1fc1e5b6e50cd7ec5ad9d78db36e76ce6426c9
=> Disable Change Password button for user that don't own the document

browser/src/control/Control.Mention.js
Change-Id: I1cc628b682215414611a256986731a9046bb6b35
* Resolves: # 
=> js: fix mention popup positioning on large resolution

net/Socket.cpp, net/Socket.hpp, wsd/DocumentBroker.cpp
- wsd: drain the wakeup pipe on each read
- wsd: update the poll round-robin index right before usage
- wsd: better merge new sockets into poll sockets
- wsd: make removeSockets private
- wsd: always handle socket polls without skipping
=> Socket Improvements

net/Socket.cpp, net/Socket.hpp, net/SslSocket.hpp
Please see commit log for detailed explanation of these changes.
- wsd: correct log argument order
- wsd: more tracing of socket and poll activity
- wsd: reduce SocketPoll lock contention
- wsd: handle read failure on closed socket better
- wsd: return SSL_do_handshake error-codes unmodified
=> More Socket Improvements

browser/src/control/Control.JSDialogBuilder.js
Best to avoid span elements around button text
The innerHTML here is harmless since we are using a string created
by us within the same function.
Change-Id: I72af17cd2788e7ba4b3ec1c255058e18884e0be1
=> Tabbed view: Tabs: Improve html structure

browser/src/map/handler/Map.Feedback.js, browser/src/map/handler/Map.Welcome.js
Change-Id: I6e548370c9569117b401f5db3f750fb3633cb2cd
* Resolves: # 
=> Fix #6192: onMessage error: e.data.startsWith is not a function

browser/src/control/Toolbar.js
Change-Id: Ia82fdb90e19da8dd3ed3c38b36b7b3b45c5e7908
* Resolves: # 
=> Improve accessibility of about and help dialogues.

cypress_test/integration_tests/common/calc_helper.js, cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/common/mobile_helper.js
Change-Id: I89720c6cfd16d27375a87375154e7cb2f050a180
=> improvement on commit 6407fff

cypress_test/integration_tests/common/helper.js, kit/ChildSession.cpp, kit/Kit.cpp, kit/Kit.hpp
Check that everything is where it should be; catch and warn about jails that are corrupted beyond our control, or perhaps manually un-mounted etc.
Change-Id: Ib5f7769ded119d7c6126984b040d0e5565ca8055
* Resolves: # 
=> Consistency checking at various points: load, save.

browser/src/map/Clipboard.js, cypress_test/integration_tests/desktop/writer/copy_paste_spec.js, cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js, cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js, cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
Change-Id: Ic9e7b11ddcca432b7ec4d218c4085496c56059bc
* Resolves: # 
=> Add close button to paste warning dialogues.

browser/src/core/Socket.js
Change-Id: I55699802d0e5f82514884f0db49e9f5667b2a7e0
* Resolves: # 
=> fix:Cannot read properties of undefined (reading 'testing')

common/SigUtil.hpp, common/StringVector.hpp
Change-Id: I2e743c4572777dcca69c364c7799a3ae7ecf0941
* Resolves: # 
=> Add missing headers that cause compiler errors on newest compilers.

browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/unocommands.js
Signed-off-by: Tomaž Vajngerl <tomaz.vajngerl@collabora.co.uk>
Change-Id: Ia50656414c0db2173d2233c4864b67e2c5dbd2e3
* Resolves: # 
=> add ThemeDialog to the notebook bar and main menu

browser/src/errormessages.js
- I some situations %storageserver domain is not the right place
to redirect users (integrator might have another support system in
place)
- Do not assume the document will be read-only, integrator might have
something different in place
Change-Id: I0008819665a96677cca06d9654e6629cfcac98b1
=> Do not assume who the user needs to contact for storage space

browser/css/notebookbar.css
https://github.com/CollaboraOnline/online/issues/6249
affecting some themes
Change-Id: I3b0a796350243add9615615d569f3b480189cd29
=> Fixes  Impress: Some icons are missing #6249

browser/css/color-palette-dark.css
see https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme
| before | after |
| -------- | ------- |
| ![Screenshot_20230428_235549](https://user-images.githubusercontent.com/8517736/235260988-80ee3091-ded7-4626-bd92-c9cf04913df4.png) | ![Screenshot_20230428_235601](https://user-images.githubusercontent.com/8517736/235261025-10dbca9c-3e6e-40cd-8d83-376f4b8dcd91.png) |
Change-Id: Ie563059174471d50b5f9a8e24d1f08b2540799c5
=> Dark Mode add color-scheme: dark setting

browser/src/control/Control.JSDialogBuilder.js
this fixes visible help buttons when no url for it is provided
=> jsdialog: post process also elements in buttonbox

browser/js/l10n.js
Change-Id: I5d29ff68870d0cd84d86658ccfd4e3185cc62562
=> browser: catch failure to get localization files

browser/css/notebookbar.css
Change-Id: I49be20532bc921e1424b07cb8d96c3477461bf8e
* Resolves: # 
=> Fix the position of dropdown triangle of uno button #6236

browser/src/core/Socket.js
Change-Id: Idd0d7a5d74e5f4b0ef82d12877a46e55c172a992
=> browser: Missing fonts dialog only worked if welcome dlg was enabled

cypress_test/integration_tests/desktop/calc/open_different_file_types_spec.js, cypress_test/integration_tests/desktop/impress/open_different_file_types_spec.js, cypress_test/integration_tests/desktop/writer/open_different_file_types_spec.js
Change-Id: Ib527fbd70c0c50d31fb984b2f379d252aa7badc1
* Resolves: # 
=> Disable some unstable tests for now.

browser/css/mobilewizard.css
see #6263 
Change-Id: I68ac07c50759a2ea1bc7c3c5122b74eecb8d741d
=> mobilewizard button color fix #6263

browser/css/jsdialogs.css
Change-Id: I5ad67a1dfc0ac1fd8b3a3eb75f4caa5e6727d895
* Resolves: #6288 
=> fixed element styling in hyperlink dialog box

browser/css/btns.css, browser/css/jsdialogs.css
input elements use css var's
| before | after |
| --------- | -------- |
| ![Screenshot_20230428_231244](https://user-images.githubusercontent.com/8517736/235259957-8d3c0f63-02f7-4177-a66d-8c13037a6d16.png) | ![Screenshot_20230428_234537](https://user-images.githubusercontent.com/8517736/235259973-573d57a2-3c41-4418-ac49-783dc80e3d0f.png) |
| ![Screenshot_20230428_234608](https://user-images.githubusercontent.com/8517736/235260000-626d841a-4296-446e-bc0a-619250a27195.png) | ![Screenshot_20230428_231314](https://user-images.githubusercontent.com/8517736/235260029-862b386c-e36c-427d-ba4c-187e78524dee.png)
Change-Id: Ie2ebe22bcf7fc377894f4b43c1bb081a3d5f5c16
=> Dark Mode Dialog css fixes

cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js, cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js, cypress_test/integration_tests/desktop/impress/fullscreen_presentation_spec.js, cypress_test/integration_tests/desktop/writer/complex_image_operation_spec.js
Change-Id: Ia8a2f1d58a3a083c38d259450343b597c64c5919
* Resolves: # 
=> Skip some tests.

browser/src/control/Control.Notebookbar.js
This reverts commit d816daef163b47b14cf0b6bb6b445039a54df857.
it didn't help for switching the deck...
=> navigator: use standard command for deck switch

cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js, cypress_test/integration_tests/mobile/impress/table_operation_spec.js, cypress_test/integration_tests/multiuser/writer/track_changes_spec.js
Change-Id: Idb21db8f295c960b7bed64372060d1590ec1da35
* Resolves: # 
=> Skip some tests for now.

browser/src/control/Control.JSDialogBuilder.js
Change-Id: Ie305a48ab5509b52eb604eb73bdef042993b1083
* Resolves: # 
=> Add aria-haspopup attribute if button opens a popup.

common/StringVector.hpp
Change-Id: I4a79e3a63524abeb34e3edf828aa9ce0c8332ca1
* Resolves: # 
=> Order headers alphabetically when possible.

common/Log.hpp, kit/ForKit.cpp, kit/Kit.cpp, net/HttpRequest.hpp, net/Socket.cpp, tools/WebSocketDump.cpp, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.cpp
- wsd: move streaming operators to the global space
- wsd: simplify log streaming
- wsd: http: native support for logging http::Header
- wsd: move streaming operator overloads
- wsd: minor logging cleanup
- wsd: make unreusable classes final
- wsd: use helper where available
=> Misc and Logging

cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
Change-Id: I75540d483b71b4d61ad274097c61b3f974be1393
* Resolves: # 
=> Enable impress text paragraph props test.

net/HttpRequest.cpp, net/HttpRequest.hpp, net/WebSocketHandler.hpp, test/HttpRequestTests.cpp, test/HttpWhiteBoxTests.cpp, test/UnitCopyPaste.cpp, test/UnitHosting.cpp, test/integration-http-server.cpp, wsd/COOLWSD.cpp, wsd/ProxyRequestHandler.cpp, wsd/Storage.cpp, wsd/Storage.hpp
Change-Id: I82f030d1d91afa504a095b852dcdaec9d2df386d
=> killpoco: replace HTTP status codes

cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
Change-Id: I71f5d43bb1e52e1962db0dfd9e66c6a4a4726e51
* Resolves: # 
=> Enable desktop impress undo redo spec.

cypress_test/integration_tests/desktop/impress/delete_objects_spec.js
Change-Id: Ib26227b453a8e21e9c5393872aaa04fe6142fd77
* Resolves: # 
=> Enable impress delete objects spec.

cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Remove notebookbar tag and use switch UI functionality.
Change-Id: I49cfc7340b7ef07d06b0b7c37d24d88127c03735
* Resolves: # 
=> Enable skipped tests in desktop writer top toolbar spec.

cypress_test/integration_tests/desktop/writer/track_changes_spec.js
Change-Id: I3d465f331bda1f2619939e8d6d9ca89ef95a0026
* Resolves: # 
=> Enable one writer desktop test in track changes spec.

browser/css/jsdialogs.css
Change-Id: I00bd8d75a2e0ae509f78eda3ae1af687da088419
* Resolves: #6285
=> Fix the layout of page number diaog

browser/Makefile.am
builddir != srcdir
Change-Id: I0c129d2bc9ea11fc0d46b37a72faa6a32a69b002
=> browser: fix bundle exceptions

wsd/ClientSession.cpp
Change-Id: Ibcd149d51b20df552a0961c58b7c9159fbf0af9e
=> enable export to pdf for readonly documents

browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
added navigator button:
- in view tab in notebookbar
- in menu in compact mode
=> navigator: added to menu

cypress_test/integration_tests/multiuser/calc/sheet_operations_spec.js, cypress_test/integration_tests/multiuser/writer/paragraph_prop_spec.js, cypress_test/integration_tests/multiuser/writer/repair_document_spec.js, cypress_test/integration_tests/multiuser/writer/sidebar_visibility_spec.js, cypress_test/integration_tests/multiuser/writer/track_changes_spec.js
Change-Id: Ia8855091da9334fcb0491441aaa0aa06cf6c26d7
* Resolves: # 
=> Disable 2 multi user tests for now.

wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/DocumentBroker.hpp
Change-Id: I82f030d1d91afa504a095b852dcdaec9d2df386d
=> wsd: http: killpoco in prisoner http handler

wsd/DocumentBroker.cpp
This corrects the ending of renaming by
moving that logic only after we get the
async upload results (either success,
failure, or timeout).
It also cleans up a few cases, such as
not needing to special case renaming with
identical names. This ensures that
subsequent attempts are not ignored.
Change-Id: Ib7a432d8a3b6ef5448291763cd31cc844c997e7e
=> wsd: improve rename action handling

net/HttpRequest.hpp
The normal path is now streamlined and error handling
is at the end. We also now always set the disposition
to closed and fire onDisconnect() when disconnected
or hit an error.
Change-Id: I984ad71601b92b8042dc7984e7339f0804c8083b
=> wsd: http: improved http::Session::handleIncomingMessage

browser/css/btns.css, browser/js/global.js
=> Fix close master view button size

browser/css/jsdialogs.css, browser/css/jssidebar.css
and move all navigator css rules into one place
=> navigator: hide panel title in sidebar

browser/css/btns.css, browser/css/device-desktop.css
Change-Id: I752691d09195e0fc6e502736a5b809fe8d92aa50
* Resolves: # 
=> Fix huge dropdown arrow of form control

kit/ChildSession.cpp, kit/Kit.cpp
Change-Id: Ibc2be5bc7676b1b67b7494c200011e4622a5b294
=> Handle LOK_CALLBACK_DOCUMENT_PASSWORD_RESET

browser/css/jquery-ui-lightness.css
tooltip use var colors.
**Before**
**After**
**After light mode**
Change-Id: Ic8addda2167be038d7e435d424448824be73127a
=> Dark Mode: box-shadow tooltip fix

wsd/COOLWSD.cpp
Change-Id: Idc47510f5b6c28f27b3cfac476e7a648dad03fb5
* Resolves: # 
=> iOS: build fix

wsd/HostUtil.cpp, wsd/HostUtil.hpp
follow up for 25efeea0d847b5dbb9df801570bb1aa1768d415d missing const in modified function caused build error
Change-Id: Ic0f4ae39476e16a9a49904e06b44f26d2a5d4fe7
* Resolves: # 
=> wsd: const parameters

browser/src/control/jsdialog/Widget.TreeView.js
=> jsdialog: add class to treview icons #6417

browser/src/control/Control.JSDialog.js
Change-Id: I2a0c59001761489f34cdc9ab9be8c1d6255c4eff
* Resolves: # 
=> Fix: Can't focus to map after a popup is closed.

browser/css/jssidebar.css
identfieldbox and box3 use the same css class see #6392 
Change-Id: I7a95fdd8ae3a9bfffbe676917cb412a99cb40818
=> Sidebar.ParaPropertyPanel css class merged

browser/src/control/Control.UserList.js
Change-Id: Id9ff2ba9954c513b86e183c5f013048c3856f2fe
* Resolves: # 
=> Add pointer for map variable.

browser/src/map/Clipboard.js
Change-Id: Ibd88b588d2aa26c1b1e3380f3f336521b200fe2a
* Resolves: # 
=> Fix this/that binding problem.

browser/html/cool-help.html
Change-Id: I57e715f71bf3f485e8fd66495ab378688010a26b
* Resolves: # 
=> Add shortcuts to help popup.

browser/html/cool.html.m4, browser/js/global.js, browser/src/control/Toolbar.js, browser/src/core/Socket.js
Change-Id: I498dd2a9f1fb08d9af116ac27ac645b31b87ed57
* Resolves: # 
=> added serverId and routeToken in about dialog

browser/src/layer/tile/CanvasTileLayer.js
* Resolves: # 
- [X ] I have run tests with `make check`
=> Restore precache next slide

browser/src/control/Toolbar.js
Change-Id: Ib6aaa1491d3f808eade75e50a5709045eaa6e40a
* Resolves: # 
=> fix: routeToken not shown in about dialog

browser/css/btns.css, browser/css/device-desktop.css
Change-Id: I752691d09195e0fc6e502736a5b809fe8d92aa50
* Resolves: # 
=> Fix huge dropdown arrow of form control and missing button border

browser/css/color-palette-dark.css, browser/css/color-palette.css, browser/css/leaflet.css
Change-Id: Ie545ef51462b23a5abb3c389b5acf4cd6d118e45
* Resolves: #6502
Updated the cursor background to contradict the background, so that cursor can be clearly visible.
=> Fixed cursor background in dark mode

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/jsdialog/Widget.TreeView.js
changes bt : Darshan Upadhyay <1110darshan@gmail.com>
Change-Id: I6d6c5d497fc565a8040a5fd7ecbfb4c488020638
* Resolves: #
After switch to dark mode some icons are missing in navigator
**Issue fixed**  : 
@eszkadev  can you confirm the changes ?
=> fix missing icon for dark mode in navigator

browser/css/toolbar.css, browser/images/dark/lc_view100.svg, browser/images/dark/minus.svg, browser/images/dark/plus.svg
Change-Id: Ia675cf4c1607d4ef5f19268647a40ea701109d76
* Resolves: #6505
fixed part 1 mentioned in this issue : https://github.com/CollaboraOnline/online/issues/6505
=> add minus,plus and search icon for bottom toolbar

Makefile.am
Change-Id: Ie3027c63cc31eea2dea2cb0a997d296a24476581
* Resolves: #3216 
=> Condense common parameters in Makefile.am for run and run-one rules

cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js, cypress_test/integration_tests/desktop/impress/annotation_spec.js, cypress_test/integration_tests/desktop/writer/annotation_spec.js
Change-Id: Ib8eff92da8d0f092995d7b004e8d3bb4b7158080
* Resolves: # 
=> Fix some annotation tests.

browser/css/jssidebar.css
Background Color use justify-content: end
Change-Id: I23a5690b0b33dae426914ebef30fae6d97d598c7
=> Sidebar writer Paragraph Section BackgroundColor justify-content: end

browser/css/device-mobile.css
Change-Id: Id929475af828f6bddf4abaadea443dd3f707af4c
=> Mobile: About dialog: remove unnecessary elements

cypress_test/integration_tests/common/repair_document_helper.js, cypress_test/integration_tests/desktop/calc/annotation_spec.js
Change-Id: I2714d0c84a9ee4f539fd7f3e055bf61ce66130be
* Resolves: # 
=> Fix some more desktop tests for 22.05.

cypress_test/integration_tests/desktop/calc/navigator_spec.js, cypress_test/integration_tests/desktop/draw/navigator_spec.js, cypress_test/integration_tests/desktop/impress/navigator_spec.js, cypress_test/integration_tests/desktop/writer/navigator_spec.js
There will be a setting for them.
Change-Id: I75264e7de14f79642cfd33a7d798ec78188f9213
* Resolves: # 
=> Disable navigator tests for now.

browser/src/control/Control.PartsPreview.js, browser/src/control/Parts.js
=> impress: introduce slide sorter context menu

browser/css/cool.css, browser/src/control/Control.JSDialogBuilder.js
Change-Id: I5a4b4b5a3c2960d21cdb894faa9e2cb488f66abf
* Resolves: # 
=> Add a button to color dialog for setting the color to auto.

browser/src/layer/tile/CommentListSection.ts
Change-Id: If2d8ad40ba692473667a28bedfb8203d343940cc
* Resolves: # 
=> Make the collapsed mode treshold narrower.

browser/html/cool.html.m4, browser/src/control/Toolbar.js
Change-Id: I263e0622159db7e26c706b97e21e9da787e2deb5
* Resolves: # 
=> remove serverId duplication from about dialog

browser/css/jsdialogs.css
Change-Id: I5442d6a99bb202ad2a850ac42baf2140adc4d1a2
* Resolves: # 
=> Expand the Page style and Character dialogs #6493

wsd/DocumentBroker.cpp
Change-Id: I938e02db8ad6adc85d6464d3260dfc8c0bb7ca9a
=> fix a bug introduced in 418ffa3

browser/src/layer/marker/A11yTextInput.js
When a key was typed the focus was grabbed from the clipboard area
because of caret/text selection events received from core.
Change-Id: I60b945d7d4742faf4a946c836628bdf70b266eb7
=> A11TextInput: clipboard area stolen focus from text search field

browser/css/jquery-ui-lightness.css
Change-Id: I64bc99145943e98a6548d682917a120c0d8a33f4
* Resolves: # 
=> Dark mode: make readable the links in About dialog

browser/src/control/Control.NotebookbarCalc.js
Change-Id: Ib1887e54a5cabacec90cf2989adbe596a165ba11
=> browser: Fix Calc tabbed button for auto spell checking

common/Protocol.hpp
Change-Id: I56ce6e6b882fe6b5940478a16e4ecf6dcb1287a8
* Resolves: # 
=> use std::string_view in COOLProtocol::matchPrefix

browser/src/control/Control.ColumnHeader.ts, browser/src/control/Control.Header.ts, browser/src/control/Control.RowHeader.ts
Refresh Calc header after mode change
Change-Id: Ifcc8c29f6b8316580570a7a9c4728965297ddc8b
=> Calc: Inconsistent behaviour when switch/reloading dark mode in Calc

browser/admin/src/AdminSocketOverview.js, wsd/FileServer.cpp
- browser: admin: fix vex dialog on socket close
- wsd: fix secure cookie Set-Cookie
=> cookie fixes

browser/css/jssidebar.css, browser/src/control/jsdialog/Widget.TreeView.js
Change-Id: I110f4efd3ff24b3f38a5756432b5847f0a852832
* Resolves: # 
=> Disable HTML dragging on navigator until the feature is activated.

browser/src/layer/marker/TextInput.js
Change-Id: I6eae62ce7762f153df40bb5cd993e2337e8af95c
=> lok: a11y: fix regression: link autocorrect doesn't work anymore

browser/src/control/jsdialog/Widget.TreeView.js
Change-Id: If0eeb49ec35793ab8a7d312f317d046d665dea99
* Resolves: # 
=> Fix JS error.

common/Protocol.cpp, common/Protocol.hpp
Change-Id: Iad56a97f9bef1f6f905f08002b1958072a209551
* Resolves: # 
=> use more string_view

browser/js/global.js, browser/src/control/Control.JSDialogBuilder.js
- browser: add 'getLang' function to get the current ...
- browser: use Intl built-in object to get number format
- browser: improve _preventNonNumericalInput function
=> prevent non numerical input

browser/src/control/jsdialog/Widget.DrawingArea.js
Change-Id: Ieab3c17f1772a2f47fc519b8cc031c1cf50dfa52
* Resolves: # 
=> Use native handlers for click and doubleclick events.

browser/src/layer/tile/CanvasTileLayer.js
We throttle the "move" event, but in moveEnd we always call a _move anyway, so if there are throttled moves still pending by the time moveEnd is called then there is no point processing them after _moveEnd because we are up to date already when they arrive and to do would just duplicate tile requests
Change-Id: I15c6fe5f0f1b6171a299a4519138912000dd9b68
* Resolves: # 
=> "throttled" move events can be processed after moveEnd

browser/css/cool.css
Change-Id: I3a1e9473cabc9df2b33e3b99168f9698d1beb86c
* Resolves: #4792 
=> Fix: Annotations, comments on hover

browser/js/global.js, browser/src/control/Control.JSDialogBuilder.js
- browser: add 'lang' property to get the current ...
- browser: use Intl built-in object to get number format
- browser: improve _preventNonNumericalInput function
=> pr/distro/collabora/co 22 05/06

browser/src/layer/marker/TextInput.js
This reverts commit f59dd62f6f06a3b03bee0887842b18f7edda19e3.
* Resolves: # 
=> Revert "23.05 - Android : tapping on cells flickers the keyboard"

kit/Delta.hpp
Change-Id: I4f06f9c4bd6f6fc41b6eed23eb2331daa26f0b5b
* Resolves: # 
=> double delta cache

browser/src/layer/tile/CanvasTileLayer.js, kit/Delta.hpp, test/DeltaTests.cpp
optimized build server flamegraph before:
optimized build server flamegraph after:
=> Push unpremul and reorder to client

wsd/DocumentBroker.cpp, wsd/TileCache.cpp
Change-Id: I218c0fbdef6815a56bf8d4059bfcae186b32ebed
* Resolves: # 
=> wsd: double size of the delta cache.

browser/Makefile.am, browser/css/cool.css, browser/src/control/Control.UIManager.js, browser/src/docstate.js, browser/src/dom/NotebookbarAccessibility.js, browser/src/dom/NotebookbarAccessibilityDefinitions.js, browser/src/layer/marker/A11yTextInput.js, browser/src/layer/marker/TextInput.js
Change-Id: Iae4e8d5cc6044c5aa089c1b0d7c077ee350da3b0
* Resolves: # 
=> Notebookbar accessibility keys

net/HttpRequest.hpp
github_android_online_co-23.05/net/HttpRequest.hpp:1391:63: error: no matching function for call to 'min'
<< Util::dumpHex(std::string(data.data(), std::min(data.size(), 256UL))));
^~~~~~~~
Change-Id: I5b81096c696565b9e4eb4f3ca39c16bc1e5b9182
* Resolves: # 
=> fix android ci

browser/src/control/Toolbar.js
Change-Id: I2ce4d5fe03ac3c38ff179cbd2466ba25961db92d
* Resolves: #6381
- Added a copy button in "Help > About" to copy version related information to clipboard
=> Added copy button in "Help > About" to copy version information to clipboard

browser/src/layer/tile/CanvasTileLayer.js
in which case it fails, just use the Uint8ClampedArray view to look back at previous input pixel after all.
Change-Id: I1ee5d7480bf9a11145ca6514ef7efb7882c183cb
* Resolves: # 
=> rawDelta may not be sufficiently aligned for Uint32Array

browser/src/control/Control.StatusBar.js, browser/src/control/Parts.js
Change-Id: Icb4f9116deb9a79fec3b6fe708625619a80ddb9c
* Target version: distro/collabora/co-22-05
Update page number in status bar when read-only mode is enabled.
=> Update page state inn statusbar for readonly mode.

browser/src/control/Toolbar.js
* reuse string from LibreOffice (and make it translatable)
* use an icon instead of button text, like in LibreOffice
* small amendments to text copied to clipboard
Change-Id: Ic16d786fe467c1f8ff718b1f46364541bba8e6ab
**Questions:** 
* How to set the style of the button popup text (title attribute)? Other toolbar/sidebar buttons have different style.
* The popup does not appear on mobile UI with log tap, unlike other button popups. Why?
=> Amend 'Copy all version information in English' on About Box

browser/src/control/Control.JSDialog.js, browser/src/control/Control.JSDialogBuilder.js
- browser: add method 'setContainer' to JSDialog
- browser: use 'checkValidity' for spin field element
- browser: use 'reportValidity' to validate number
* Resolves: # 
=> validate inputs

browser/src/control/Control.JSDialog.js, browser/src/control/Control.JSDialogBuilder.js, browser/src/map/handler/Map.Welcome.js, cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/desktop/writer/table_operation_spec.js, cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
- browser: add method 'setContainer' to JSDialog
- browser: use 'checkValidity' for spin field element
- browser: use 'reportValidity' to validate number
* Resolves: # 
=> validate input data

browser/src/layer/tile/ContentControlSection.ts
Change-Id: Ib348e46af68ab00819a76f2e9cb1b26732034ad4
* Resolves: # 
=> show alias tags in contentcontrols

Makefile.am
Change-Id: Ic39a90bf263504bb45b0b933e06893629966e357
* Resolves: #3216 
=> Condense common parameters in Makefile

scripts/weblate-leader-board-parser.py
Used for translators leader-board in the forum
Change-Id: I04a557c3beaa109b0ab010ca32ec749b585d07cc
=> Scripts: Add parser used in forum for monthly leaderboard

browser/src/layer/marker/TextInput.js, cypress_test/Makefile.am, cypress_test/README, cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/desktop/writer/editable_area_spec.js, cypress_test/integration_tests/desktop/writer/track_changes_spec.js, cypress_test/integration_tests/desktop/writer/undo_redo_spec.js
- a cypress env var for enable/disable a11y on testing + a a11y tags
- cypress: expectTextForClipboard helper function never fails
- cypress tests when editing with a11y disabled
=> private/marco/a11y/cont edit/cypress tests a11y disabled

browser/Makefile.am, browser/src/map/handler/Map.Welcome.js, cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/desktop/writer/table_operation_spec.js, cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
- browser: fix bundle exceptions
- cypress: no welcome if cypress test running
- cypress: adjust values for '#copy-paste-container' elements
- cypress: fix possible random file duplicates
- cypress: fix failing unit test apply_paragraph_props_text_spec.js
=> pr/distro/collabora/co 22 05/08

browser/js/global.js, browser/src/core/Socket.js, coolwsd.xml.in, wsd/Admin.cpp, wsd/Admin.hpp, wsd/AdminModel.cpp, wsd/AdminModel.hpp, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/DocumentBroker.cpp, wsd/protocol.txt
Change-Id: Iefb9ed77f78b13e1558e995b3e3a2cf3022b53db
=> implement document migration

.github/workflows/helm-release.yml, kubernetes/helm/cr.yaml
=> fix(helm): ci with helm- prefix on tag and release

kubernetes/helm/collabora-online/Chart.yaml
- update appVersion according to https://hub.docker.com/r/collabora/code/tags newest image
- create first helm-chart release in helm repo on this repo / github-release
- expected tag-name is: `collabora-online-1.0.1` (like the chart-name and version)
=> fix(helm): update appVersion

kubernetes/helm/README.md
Change-Id: I505c0c177a649a5ebed63dcc5232a3cba3e5fbf7
* Resolves: # 
=> updated k8s readme to use collaboraonline.github.io repo

browser/src/control/Toolbar.js
Change-Id: Iff50721ef8befd3802967a575e61233540298ced
* Resolves: #6765
Updated:
=> Mobile: Enable tooltip for copy version button

browser/src/layer/tile/CanvasTileLayer.js
removed in:
commit d859da11b098f0e7495e19adc211264e78330710
Author: Caolán McNamara <caolan.mcnamara@collabora.com>
Date:   Wed Jun 28 11:12:28 2023 +0100
rawDelta may not be sufficiently aligned for Uint32Array
because it would failed with nonaligned data from the delta case.
Those tend to be very short, so for that case copy into a suitable aligned buffer and the lengthy keyframe case which is suitable aligned already can get the win.
before: ![before2](https://github.com/CollaboraOnline/online/assets/833656/f439e6ea-5b05-48b7-90d4-c37e6183f05a)
after: ![after](https://github.com/CollaboraOnline/online/assets/833656/0d19f0a5-a319-4e48-88fa-4a566820d240)
Change-Id: I8acfcb18c69380c55128c07f1749eb301c1145a1
=> restore using Uint32Array for previous pixel compare

browser/src/control/Control.NotebookbarWriter.js
Better to reorder these so we have higher probably to meet user's
expectations and fix the priority in which the elements are placed
Change-Id: I9ae3bcd087f82e2cfa02da780638424f37a3589c
=> Tabbed view: Writer: Insert tab: Reorder elements

browser/src/control/jsdialog/Widget.MultilineEdit.js
when selection is clicked it should disappear
=> formulabar: hide selection on click

android/app/build.gradle.in, android/lib/build.gradle.in
Change-Id: Id2199c0e43bae0cf3edbdf9b1c012bebb6d544fd
* Resolves: #6788 
=> Android: bump targetSdk to 33 #6788

browser/src/control/Control.UIManager.js, browser/src/docstate.js, browser/src/dom/NotebookbarAccessibility.js, browser/src/dom/NotebookbarAccessibilityDefinitions.js, browser/src/layer/marker/A11yTextInput.js, browser/src/layer/marker/TextInput.js
Change-Id: I185f60960cb819814dfdc72900bafaef023cafd6
* Resolves: # 
=> Add multi-language support for Notebookbar accelerators.

browser/src/layer/marker/TextInput.js
Change-Id: I47b104de283f001ec5d0486d94e88336ceba87e0
* Resolves: # 
=> refactor: consolidate mentions-related code in TextInput.js

browser/src/layer/tile/TilesSection.ts
Change-Id: I27cef6d9903e93fe4f87a8627c4fab84257129ef (cherry picked from commit 308f367ffa6daec90f24603cca07bf7f26d37825)
* Resolves: # 
=> draw a checkerboard for missing tiles when debugging

browser/css/jsdialogs.css
Change-Id: Ica7977c8d334bbb8bcb3bfd3c8aca8d4876c0571
* Resolves: #6795
Fixed hyper link textarea dialog box's width
=> Fix odd looking textarea width.

wsd/QuarantineUtil.cpp
Change-Id: I977f65bbd11060fecf4db31e7e25e068771c17b7
* Resolves: # 
=> cid#318897 Using invalid iterator

browser/src/dom/NotebookbarAccessibility.js, browser/src/dom/NotebookbarAccessibilityDefinitions.js
Change-Id: Ica9f8709d8c29bcbb8610f37d933fd34b7bca8e0
* Resolves: # 
=> Don't use space symbol as part of access key combination.

browser/admin/admintemplate.html
- websocket uri, admin-bundle.js uri, href links
Change-Id: I84a484938191e2f62b9d262ee922e8b04de74a44
* Resolves: # 
=> add RouteToken in admintemplate

browser/css/jsdialogs.css
So user understands the component is disabled
Change-Id: Ide4fb7589b5be611975de4a704b458bb626be0e0
=> Gray out empty treeview and signal it as disabled component

cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
Breaking the chain may be useful in this case, in order to benefit from timeout.
Change-Id: I4242df23698b2019028cb4e8a3c6206499b80083
* Resolves: # 
=> Sometimes Cypress doesn't try multiple times when commands are chained.

browser/src/control/Control.NotebookbarWriter.js, browser/src/dom/NotebookbarAccessibility.js, browser/src/dom/NotebookbarAccessibilityDefinitions.js
Change-Id: Iaedb0b365a6671b685f1c7600503b533976f82ad
* Resolves: # 
=> Add missing accelerator keys for the writer notebookbar.

browser/src/control/Control.JSDialog.js, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Notebookbar.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.Sidebar.js
duplication shown by copy-paste detector in https://github.com/CollaboraOnline/online/pull/6802
=> jsdialog: share code for widget update

browser/src/control/Control.JSDialogBuilder.js
Change-Id: I76f2db4340a3c832979215c18e06af3e61042a15
* Resolves: # 
=> Activate the focused tab immediately when navigating with arrow keys.

browser/package.json
Change-Id: I79bcfce90a858ad5a6f432ba8e36b0936c505bf3
* Resolves: # 
=> bump to latest fzstd release

browser/src/layer/tile/CanvasTileLayer.js
=> Fetch enough for next vertical scroll

browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/TilesSection.ts
=> Osc ctxs and offscreen canvases are write only

browser/Makefile.am, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/jsdialog/Widget.Calendar.js, browser/src/control/jsdialog/Widget.MenuButton.js
Can be tested in Writer -> Review -> Manage -> Filter (date dropdown)
Requires:
https://gerrit.libreoffice.org/c/core/+/154133
https://gerrit.libreoffice.org/c/core/+/154135
https://gerrit.libreoffice.org/c/core/+/154136
https://gerrit.libreoffice.org/c/core/+/154192
https://gerrit.libreoffice.org/c/core/+/154193
Fixes date picker and time field
=> jsdialog: calendar control

browser/src/control/Control.PartsPreview.js
Change-Id: Ia9f1a33d2b698e64660391866ed357b4346339b0
* Resolves: #6613 
=> Fix : Wrong context menu in Slides Pane in master view for Impress

browser/css/jsdialogs.css
Icon's are already available, the css rule has to be themed as for the other toolbar icons.
Change-Id: I0ffd594ba3e897a36c2caa8a5fe9aace9e04a63d
=> DarkMode checkboxes will be themed

browser/src/control/Control.IdleHandler.ts, browser/src/dom/NotebookbarAccessibilityDefinitions.js
- in notebookbar a11y
- in idle handler
=> Fix type errors

browser/src/control/Control.PartsPreview.js
Change-Id: I9f661df619581aa9d66d98f7e63c3562c6a939b9
=> impress: avoid all slide preview context menu in master view

browser/css/jsdialogs.css
Change-Id: I0fa5bb60ece88e4107408448a17378b526020784
Signed-off-by: Darshan-upadhyay1110 [darshan.upadhyay@collabora.com](mailto:darshan.upadhyay@collabora.com)
* Resolves: #6839 
Set Minimal width for suggestions list
Added some padding for spell check text box for more readability
=> Fixed Spellcheck dialog size

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java, android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, wsd/DocumentBroker.cpp
* Resolves: # 
regression from: https://github.com/CollaboraOnline/online/commit/17f739ca7710428765c40d5daac5fdaecfe708e2
https://developer.android.com/about/versions/11/privacy/storage
=> Fix android bugs

browser/js/global.js, browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I83d39fa4829938e8f217361fec3fbdab79adbac9
show error message:
=> fix: media cannot play with indirection server

browser/css/mobilewizard.css
Change-Id: I8c10857b0ca7e166b5f9364db9ea2a01e5acfffa
* Resolves: #6861 
Follow Androids navigation drawer divider
https://m3.material.io/components/navigation-drawer/specs#25f67916-87fa-4cbb-b390-175096ae559b
=> Mobile sidebar header layout #6861

browser/css/jsdialogs.css
Change-Id: Idc0800eaa4ab751601bd34bba6c2e9cfef38de4d
* Resolves: #
=> Fix Spell checker js Dialog

browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/vector/SVGGroup.js
regresssion from 3c55baf4e2e36c6df43707a7e469dae3fec2c3b0
Change-Id: I21831ba076140d49a54a56e9c52f7edfca923ef5
* Resolves: # 
=> fix: failed to play media when using indirection

kubernetes/helm/collabora-online/Chart.yaml, kubernetes/helm/collabora-online/templates/dynamicConfig/configmap.yaml, kubernetes/helm/collabora-online/templates/dynamicConfig/ingress_upload.yaml, kubernetes/helm/collabora-online/templates/dynamicConfig/service.yaml, kubernetes/helm/collabora-online/templates/dynamicConfig/statefulset.yaml, kubernetes/helm/collabora-online/templates/dynamicConfig/upload_secret.yaml, kubernetes/helm/collabora-online/values.yaml
config uploader on dynconfig (for allow lists over 1MB usefull)
=> feat(helm): dynconfig upload

configure.ac, debian/changelog, ios/Mobile/Info.plist.in
Change-Id: I5716d9d6556f45185b7b78fa05277403855d0353
* Resolves: # 
=> Bump version to 23.05.2.1

browser/css/jsdialogs.css, browser/css/override-vex.css
Change-Id: I09583d7c27cffc0f5b9722de1925977089bf832b
=> Fixes #6946 and all unstyled kbd elements

configure.ac, debian/changelog
Change-Id: Ib03fddb00af05eaec4711c0b623713a993a5d56b
=> Bump version to 23.05.2.2

browser/css/notebookbar.css, browser/src/dom/NotebookbarAccessibility.js
Change-Id: Id8c8e2a8bcb57c90e0762dd3916b851fff8e0a6f
* Resolves: #6934 
- accessibility key features 
- focus on tab when press `Alt`.
- move back and forth tab focus by ArrowLeft and ArrowRight
=> Add Left or right arrow on a tab label should switch tabs

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/bug_report_smoke-test.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Tex2002ans improve GitHub templates

browser/css/jsdialogs.css
Change-Id: I1cd97503e0d3ca4333b11552ca3571093cf10bfe
* Resolves: #6877 
=> Fix : Menubutton should have disabled state styling different

browser/images/dark/lc_collapsenotebookbar.svg, browser/images/lc_collapsenotebookbar.svg, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
Change-Id: Ic15fb1723bff6861b1fc115ef161cf6caa1b70af
* Resolves: #4115
Collapse notebook bar from tab view
I took some liberty with the label and i created an new icon.
This is my first time, i'm not very sure how things are done.
Linked to : https://github.com/CollaboraOnline/online/pull/6982
=> Collapse notebook bar from view tab

browser/admin/admintemplate.html, browser/admin/src/AdminSocketBase.js, browser/admin/src/Util.js, wsd/Admin.cpp, wsd/FileServer.cpp
- admin: add access token
- browser: admin: use access token
=> admin: use access token

kit/ChildSession.cpp, kit/ChildSession.hpp, kit/Kit.cpp, kit/Kit.hpp, test/WhiteBoxTests.cpp
=> save-as preserves document password

browser/src/map/Clipboard.js
Change-Id: I438ca03c8122c6c85acac7dda141f685a94fdc53
=> show copy/paste timeout warning

docker/from-source/ArchLinux
Change-Id: I6eac76976c6bd076f24c795b3eeec876bfef3e6b
* Resolves: # 
=> docker: fix permission denied in archlinux

.github/workflows/code-duplication.yml, browser/src/control/Control.ColumnGroup.ts, browser/src/control/Control.GroupBase.ts, browser/src/control/Control.RowGroup.ts
Detector for code duplication in the PR. For now set minimal length of 26 lines, as we have some dups of 25. In the future we can decrease after refactor.
=> Add action for detecting code duplicates

browser/src/control/Permission.js
Change-Id: Ifdb59ff3463a0354549316994f8e80b341e28133
* Resolves: # 
=> accessibilty: added accessibilty fields to the mobile edit button

browser/js/w2ui-1.5.rc1.js, browser/src/control/jsdialog/Widget.MenuButton.js
Change-Id: I9ff58eec19ccc7229c81b9d1f258bc8c4825634d
* Resolves: # 
=> Improve accessibility of w2ui drop down menus.

browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/CommentListSection.ts, browser/src/map/Map.js
Change-Id: I0a70f1801f519df066ff5bc9dd57a5d485967b61
* Resolves: # 
=> cool#6911 calc comment positions are now cell addresses

wsd/FileServer.cpp
Change-Id: Idcd85266a4cc5020aeaca7d7fb8428bc0a3d7d32
=> admin: fix auth issue when switching between

browser/Makefile.am, browser/admin/adminBody.html, browser/admin/adminClusterOverview.html, browser/admin/admintemplate.html, browser/admin/src/AdminClusterOverview.js, browser/admin/src/ModalDialogCreator.ts, browser/package.json, wsd/FileServer.cpp
Change-Id: Ib631f5bcb63b85789233a47ef9631230757bf7c8
* Resolves: # 
=> admin: added cluster overview page

browser/src/control/Control.Toolbar.js, browser/src/dom/NotebookbarAccessibilityDefinitions.js
Change-Id: I7421cbf8e745b0dd973c7f99b985e8bf98b4859f
* Resolves: # 
=> Make insert shapes menu accessible.

browser/admin/admintemplate.html, browser/admin/src/AdminSocketBase.js, wsd/FileServer.cpp
To avoid confusion with the WOPI access token.
Change-Id: Ie38e0f11d0655e89eb1c7f1e20b73a9b8756ba21
=> admin: rename ACCESS_TOKEN -> JWT_TOKEN

android/app/src/main/java/org/libreoffice/androidapp/SettingsActivity.java, android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, browser/html/cool.html.m4
Change-Id: I108601f78f4d7bbf704b5f5f89b20c8f8a597355
=> android: enable dark mode in documents

browser/welcome/welcome.css
Otherwise content is not reachable.
Change-Id: Ibef06bd7ee18702674e41e8f942449ef49ffdd62
=> Welcome: allow scroll bar

browser/src/layer/tile/CanvasTileLayer.js, browser/src/map/handler/Map.TouchGesture.js
Change-Id: I4c5f1f2923f894156f5f05382b0f54476dea8a56
* Resolves: # 
=> fix: cursor jump when hyperlink popup clicked in mobileview

common/SigUtil.cpp, kit/ForKit.cpp, wsd/Admin.cpp, wsd/COOLWSD.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
- wsd: move statics into anonymous namespace
- wsd: simplify shutdown and termination flagging
=> Termination Flag

browser/admin/adminClusterOverview.html, browser/admin/src/AdminClusterOverview.js
and round cards
Change-Id: I632ca5a3053247ce4d12c4e028e0322ee1545124
=> AdminCluster: Use proper card headers for title instead

browser/admin/src/AdminClusterOverview.js
Change-Id: I323735c989e3a4448f57d896ea635dcdeb6bbe8b
=> admin: use humanizeMem in adminClusterOverview.js

wsd/README
Document that authentication changes need double amount of care,
compared to other normal functional changes.
Change-Id: Ib1820581f7175957f08f5e080d542c7441a3ffa2
=> wsd, coding style: document double review for security

browser/src/control/Control.JSDialogBuilder.js
Change-Id: I6b6049751d95af7c42d931666beed424fd4a208e
Before:
After:
=> fix: cell border preview in mobile wizard

browser/src/control/Control.NotebookbarDraw.js
Also simplify definitions.
Change-Id: Ieccb431ba66a25a4e35ea4c2cb59c4490b84986d
* Resolves: # 
=> Add accessibility definitions to draw UI.

browser/admin/adminClusterOverview.html, browser/admin/src/AdminClusterOverview.js, wsd/FileServer.cpp
Change-Id: I6412d68ef0c86d7a618eaf0ad252c16dee565d77
=> clusteroverview: send routeToken with auth message

browser/src/control/Control.Menubar.js
We forgot to dispatch it
Change-Id: If1ae87ee8029d469d092680437023d389efcdec7
=> Fix Rename document button works only on tabbed view #7109

android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, browser/src/control/Control.UIManager.js
- priortize theme settings from SettingsActivity over savedState
- fix darkmode toggle button does not behave as expected
Change-Id: Idb884cba3af335edc0936736f35610e91cfd64e6
=> android: enable webview localstorage

browser/src/control/Control.JSDialogBuilder.js, browser/src/dom/NotebookbarAccessibility.js
Resolves #6933
Change-Id: I1cf696223ff5739e6a48095acbdf3fd778af1ffd
* Resolves: # 
=> Up and down arrow work for notebook bar

browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
The newly added button in 24ac74db4f3327bf9caf443f21af1f5b585f8237 was
only added to writer
Also add css class
Change-Id: I630640d94884cb5e50559fbbd8298554deb0a651
=> Add missing renamedocument button

browser/src/control/Control.Command.js
Change-Id: I5ec30ef6be17aa18ff0ec8b4ff7c6a8da831fa04
=> feature-locking: fixed broken feature unlock popup

coolkitconfig-mobile.xcu, coolkitconfig.xcu.in
The new option made by this gerrit:
https://gerrit.libreoffice.org/c/core/+/155079
This commit make that option true in Collabora online.
Change-Id: I3bcb3092ab041e053db806ac704fc05b529e3950
* Resolves: # 
=> sc: set hyperlink MS interoperability true in online

wsd/Admin.cpp, wsd/protocol.txt
Change-Id: I2e640a746c839ea6f4494ddbdfcb8f924150906f
=> admin: add new command to verify auth token

browser/css/jssidebar.css
Change-Id: I7f7e2d48eedf0f204acefadccb36764f553d65f5
=> Navigator: fix active element style on dark mode

browser/src/control/Control.Menubar.js
Change-Id: I83470c2b0f3ad6737ebd0648f4b89ffa24dd381a
* Resolves: # 
=> Mobile : Add dark mode option to Calc,Impress & Draw

browser/Makefile.am, browser/css/jsdialogs.css, browser/css/notebookbar.css, browser/css/toolbar.css, browser/src/control/Control.JSDialog.js, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/Control.Notebookbar.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Permission.js, browser/src/control/jsdialog/Widget.Combobox.js, cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js, cypress_test/plugins/selectorList.js
To work requires chain of core changes:
https://gerrit.libreoffice.org/c/core/+/155853
=> jsdialog: combobox with custom entries (font previews)

android/app/build.gradle.in, android/app/src/main/java/org/libreoffice/androidapp/ui/RecentFilesAdapter.java, android/app/src/main/res/layout/file_explorer_grid_item.xml, android/build.gradle.in, android/gradle/wrapper/gradle-wrapper.properties, android/lib/build.gradle.in, android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
=> Android dependencies update

browser/js/global.js, browser/src/core/Socket.js, browser/src/errormessages.js
Change-Id: I0efb38b714894dffb44cb5e2ca06be12ccf43b89
Attached a screencast:
[Screencast from 2023-08-28 19-35-34.webm](https://github.com/CollaboraOnline/online/assets/26241069/f506566d-bb37-4666-99f0-f2b438c10829)
After 3 retries it will open the document but with warning modal dialog
=> indirection: get new routeToken if serverId mismatch

browser/css/jsdialogs.css
Change-Id: Idb8b2dcb29b7cc00f37e7aa2b05a05127c96ddcd
* Ref PR: #6914 
=> Fix: hover states on disabled

browser/css/mobilewizard.css
- regression from 8379ae65dd713c30ac729ae10a2d78cfc98e9a6c
Change-Id: I28edf882ce9efd586730a48a95f3bde555a63690
* Resolves: # 
=> fix: comment annotation table not aligned

browser/css/mobilewizard.css
Change-Id: I7a3d430ddd96ccb3ea0605eb0a0f2523d66225ce
=> mobile: fix images not visible with branding

browser/src/layer/tile/CommentListSection.ts
- regression after removing unused slide sorter from this patch 639068e3fe9b4e727c03e8d8f28ceac657fe8da2
Change-Id: Idc94f316d3e2b7d8ed23c8202c20b14252390b97
=> android: fix cannot open pdf

browser/src/map/handler/Map.Keyboard.js
Change-Id: I097691edd81fdc95718d778fcac57c0b0d3e9fb5
* Resolves: #4346
Added support for keyboard shortcut to add
- Unordered  list Ctrl + Shift + L
Still => * (asterisk) then Spacebar to add list view not implemented will add new PR for that as seems a big change with addition to some core side code to be added...
=> Unordered  List Keyboard Shortcut

browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
Change-Id: I78a0adbf84fbea8e2a6c08b0b4eaded7309fa79a
=> Tabbed view: Add missing CSS class for simple search button

browser/src/layer/tile/CommentListSection.ts, browser/src/layer/tile/CommentSection.ts, browser/src/layer/tile/WriterTileLayer.js
to parent from parentId while importing the comments.
Change-Id: I2f8fa3eae995d894b33558a2fb67639c7af5f1a1
* Resolves: # 
=> Update the comment property for writer.

browser/src/layer/tile/ScrollSection.ts
Change-Id: If52d3b4b3afa8ad629adeeda6fd65c7a80776b06
* Resolves: #5473 
=> Add Scrollbar onmouseover effect

common/Protocol.cpp, common/Protocol.hpp, kit/Kit.cpp, test/WhiteBoxTests.cpp, wsd/COOLWSD.cpp, wsd/DocumentBroker.cpp
Change-Id: I5bcf615521d13758b2b70a0c9466a3bbc1a0a918
* Resolves: # 
=> Avoid logging messages when anonymization is on

browser/src/control/Control.Notebookbar.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js
Change-Id: I24d892e0618d7105062e794c032fb8f96f76ccf3
* Resolves: # 
=> Add accessKey properties for save buttons of shortcuts toolbox.

browser/css/jsdialogs.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/Control.MobileWizardWindow.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.Toolbar.js, browser/src/control/Toolbar.js, browser/src/control/jsdialog/Widget.MobileTabControl.js, cypress_test/integration_tests/mobile/calc/insertion_wizard_spec.js
introduce it in Calc only as it has better knowledge about cell content and what should be edited
=> Use dialog from core in Calc Insert Hyperlink

browser/src/control/Parts.js, test/TileCacheTests.cpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/TileDesc.hpp, wsd/protocol.txt
getTokenString(const StringVector& tokens...) loops over each token and calls
getTokenString(const std::string&...) with token.getParam() on each token. We already have a loop over each token, so we can merge those loops here.
Though looking further, broadcast seems unused by anything now.
To be followed up on that topic.
Change-Id: I244637043c58d90562001ec58fac494da54e55a8
* Resolves: # 
=> getTokenString is another loop over the tokens that we already loop over

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.Toolbar.js, browser/src/control/Control.TopToolbar.js, browser/src/control/Toolbar.js, browser/src/control/jsdialog/Widget.MenuButton.js, cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
Change-Id: Ic4514648bd998575990bce877eda5d45884a8514
* Resolves: # 
Added 2 options to print
- Active sheet
- All sheets
=> Add option for print sheet

browser/src/control/Control.NotebookbarWriter.js
Change-Id: I10d821080a06b8bd93993e2ab6bf0fe212449b2d
* Resolves: # 
=> writer: add missing accelerator keys for file tab.

browser/html/cool-help.html, browser/src/control/Control.Menubar.js, browser/src/control/Toolbar.js, browser/src/map/handler/Map.Keyboard.js
Change-Id: Id55c56e65cf27dd67bf6c88488b5f29b6e5dade8
* Resolves: # 
=> Resolve id conflicts between contents and the buttons.

browser/src/dom/NotebookbarAccessibility.js
Change-Id: Ia812d8a8dd89e12b8c6f0d3d7f3586700b1e6ce3
* Resolves: # 
=> Re-position the accessibility info boxes.

browser/src/control/Control.NotebookbarWriter.js
So it doesn't conflict with others.
Change-Id: I3f114aa007572cb40acff58f9d3b4a45f3d57988
* Resolves: # 
=> Change the insert > insert table command access key.

browser/src/dom/NotebookbarAccessibilityDefinitions.js
Change-Id: Ic101061ed8d39178c1dc0777350126c3fa545258
* Resolves: # 
=> Add shorcutstoolbar to the integrator containers list.

browser/src/layer/tile/CommentListSection.ts, cypress_test/integration_tests/mobile/writer/annotation_spec.js
Change-Id: Ia089ae8348c718f82fb39e80234a29a17e602a61
* Resolves: # 
=> Fix the mobile comment issues of writer.

browser/src/control/Control.NotebookbarBuilder.js, common/SigUtil.cpp, ios/Mobile/AppDelegate.mm, ios/Mobile/DocumentViewController.mm, kit/Kit.cpp, test/TileCacheTests.cpp
This patch contains changes to iOS and/or Android code only.
=> Fix minor iOS build and runtime problems

browser/css/notebookbar.css, browser/src/control/Control.NotebookbarBuilder.js
Change-Id: If4feb0806ce92fadeb90f6676809bcbefc51eb24
* Resolves: # 
=> Fix "modified state notifier" visibility.

browser/src/control/Control.Menubar.js
- Added view option to all other apps on mobile view.
- previously only text contains the view option in mobile view. ( click on hamburger menu on mobile view)
Change-Id: I04e06e346d398d947e637bd71e4134bc3e901c4d
* Resolves: # 
=> Add  "view" and move things like dark mode into that menu

browser/src/core/Socket.js
Change-Id: Ia75d085d17c49a64e56f0dc5c9494fd88d846bfa
=> don't reload the tab if reconnected by indirect socket

common/Simd.cpp, common/Simd.hpp, kit/DeltaSimd.c, kit/DeltaSimd.h, kit/ForKit.cpp
and avoid local static in simd_initPixRowSimd
Change-Id: Idb89d5069da5ff10b346b5e4d767374d4529a96f
* Resolves: # 
=> do init_gather_lut at start if simd::init succeeds

browser/src/core/Socket.js, browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/ImpressTileLayer.js
in calc on reconnect
Change-Id: I7dafcd5f8d57ae79952153faf90b682f17a33cfd
=> persist slide number in impress and sheet number

browser/src/control/Control.Tabs.js
Change-Id: I541d076a457daa0e01b660e5cd91e468a22aa09d
* Resolves: #7238 
=> calc: hide spreadsheet context menu in readonly mode

browser/src/map/handler/Map.Keyboard.js
Change-Id: I56ff4672699860208b37c0aad575dc4ba294763b
* Resolves: # 
=> German shortcut changes for Calc

common/MessageQueue.hpp
which is a little dubious anyway
Change-Id: If12bd7807ca5f2cff0ca05cad4948962b0cf6688
* Resolves: # 
=> remove unused used method

wsd/TileDesc.hpp
perf reported 1% of time in collaborative multi user test on 2023-09-14 was spent in TileCombined::parse.
generic-ize and reuse the TileDesc::parse approach for TileCombined::parse to avoid need for std::unordered_map
Change-Id: Iadfc2001e298d8f4d46200c8488f0eb4cd8734c2
* Resolves: # 
=> reduce cost of TileCombined::parse

Makefile.am, net/Socket.hpp
Failed with:
fuzzer/HttpEcho.cpp:111:17: error: 'removeSockets' is a private member of 'SocketPoll'
And:
kit/Delta.hpp:208:(.text._ZN14DeltaGenerator14DeltaBitmapRow7initRowEPKjj[_ZN14DeltaGenerator14DeltaBitmapRow7initRowEPKjj]+0x127): undefined reference to `simd_initPixRowSimd'
Change-Id: I6d980698b43ca3545d9eae5f40eabaf4e442ca17
=> Fix the --enable-fuzzers build

browser/src/control/Control.Tabs.js
Change-Id: Ibf25b0d76d8487e582ed6a6cf1f82467869453f6
* Resolves: #2567
=> calc: Show tabs context menu on a tablet's press

browser/src/control/Control.JSDialogBuilder.js
Change-Id: Ic51d3d020568e4c9488cc8be71ea446e66227a25
* Resolves: #7321 
=> Calc: fix Format->Sparkline menu items in notebookbar

scripts/locorestrings.py
Change-Id: I0328dc4cb97aa143fc2911255817b7cc636b5bec
* Resolves: #7349
=> Adapt locorestrings.py for Python 3

common/Message.hpp, coolwsd.xml.in, kit/ChildSession.cpp, kit/ChildSession.hpp, kit/Kit.cpp, kit/Kit.hpp, net/Socket.cpp, net/Socket.hpp, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
Change-Id: Idadfe288a78cfd72b01253dfdade150d506e3f05
* Depends on: https://gerrit.libreoffice.org/c/core/+/154680/
* Resolves: # 
=> Add support for URP messages in COOLWSD

browser/src/map/handler/Map.WOPI.js
Change-Id: I9cdb26c3d2787beac6e2344d5f768e0fa6993bd8
* Resolves: # 
=> return false early on 'null' origin

common/Log.cpp
Change-Id: I1805db7c9c6bc6c66afbb912a16e01f6bf0f2699
* Resolves: # 
=> logging: allocate temporary buffer on the stack.

browser/js/global.js
Change-Id: I779bfc658c54255a675e3a047ed371e7e0586327
=> indirection: use errorcode to map errormsg and translate it

.gitignore
Change-Id: I9c3c315f13cb419ae4e51d962ca36c245d9dcdbd
* Resolves: # 
=> Ignore temp file in the repo.

docker/from-source/.gitignore, docker/from-source/ArchLinux, docker/from-source/Debian, docker/from-source/Ubuntu, docker/from-source/build.sh, docker/from-source/openSUSE
- remove start-collabora-online.pl from-source
Change-Id: I4cc477733e8bd6a2c736e16bcb2d75aa295e9895
=> docker: cleanup

wsd/Admin.cpp, wsd/protocol.txt
Change-Id: Ic09b33c9eb2c0072f84b7147acc673031dbac0d8
=> admin: added id field in verifyauth msg

kit/Delta.hpp
On iOS, each app has its own sandbox which has a temporary directory. The FileUtil::getSysTempDirectoryPath() method successfully gets this directory and we create a tiledump directory under it. Sadly, we then try to write to /tmp regardless of where the temporary directory is.
This commit makes us also write our file in the directory returned by FileUtil::getSysTempDirectoryPath()
Change-Id: Ic8425cb94d1d85ac9c77212eb84d0ca7c46cd34e
=> Fix tile dumping when /tmp is not temporary directory

test/TileQueueTests.cpp, test/lokassert.hpp
and
cid#318839 Explicit null dereferenced
cid#318838 Explicit null dereferenced
Change-Id: I34685ea04722aeccc21910283fa4819dbf45c012
* Resolves: # 
=> cid#318830 help coverity see assert

browser/src/core/Socket.js
without a need for an additional timer to poll when that is possible.
Change-Id: Ia019d8d8516f8c9156f3e96be262138a16343983
* Resolves: # 
=> delayed messages can be applied when _map._docLayer becomes available

browser/src/layer/tile/CommentListSection.ts
Change-Id: I504df4738054076b35e36b878d8f8651af4543eb
=> annotation: fixed autosaved comment cannot be closed

browser/src/core/Socket.js, browser/src/layer/marker/TextInput.js, browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/ImpressTileLayer.js, browser/src/layer/tile/WriterTileLayer.js
- don't invalidate the tiles
- don't reload the document if serverId changes
- writer: fix cursor jumps to top the document
Change-Id: Ie42850e77f9011cd1c820115919f10283407f216
* Resolves: # 
=> browser: make reconnnect experience smoother

browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js
Some of the options seems to not working on mobile app
Change-Id: I934e446dfeeab46f26e95898522cb0b7c1cc64a2
* Resolves: # 
=> Fix export as options on android app

browser/src/core/Socket.js
https: //github.com/CollaboraOnline/online/pull/7390#discussion_r1351943503
Change-Id: I0a32933d54fa44486c6807c4d0b01e2029700271
* Resolves: # 
=> reduce onStatusMsg retry timeout to 10ms

browser/Makefile.am, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/jsdialog/Widget.Frame.js
Change-Id: Ie0b949c8dcd820de380f9ee6b497631e594114f3
* Resolves: # 
=> jsdialog: make sure all elements in frame are displayed

browser/src/control/Control.JSDialogBuilder.js
Change-Id: Ie110bc895d7a639266affb9ba3129a5a831d6e2c
* Resolves: # 
=> Remove ellipsis (…) char at the end of notebookbar button labels

common/RenderTiles.hpp
We only run one task in each thread when run() is called, then complete the remainder of tasks in the main thread while the other threads wait.
https: //github.com/CollaboraOnline/online/issues/7374
Change-Id: Id4fc0a620d98b0bb55310b495eeff7411a4544b5
* Resolves: # 
=> cool#7374 very little delta threading

browser/Makefile.am, browser/src/control/Control.FormulaBarJSDialog.js, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/Control.Sidebar.js, browser/src/control/jsdialog/Widget.MobileBorderSelector.js
- move mobile border selector widget to separate file
- reduce warnings in sidebar and formula bar we can ignore
=> Small jsdialog cleanup

browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CommentListSection.ts
=> Calc comment positions

kubernetes/helm/collabora-online/README.md
Change-Id: I5c145bc2c5b718266caa40f9177e0b0591ab3522
* Resolves: # 
=> k8s: update readme

kubernetes/helm/collabora-online/Chart.yaml
Change-Id: Iac2823f4055f4489555b28e989f31be1f23f14e7
=> helm: update appVersion

browser/src/control/Control.UIManager.js, browser/src/core/Socket.js, browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ic853ba5108a1f6f9db2a7f8ab5310fe77357b07c
* Resolves: # 
=> browser: fix white document background on reconnect with darkmode

browser/src/control/Control.JSDialogBuilder.js
Change-Id: I27cf86972e70d956b9005fc1ea0b65a622e898d7
* Resolves: #7196
=> Fix Format Cell broken with custom text

browser/src/control/Control.UIManager.js
resolves: #7468
Change-Id: Icb6563f76cc0f9c7d81eac96fedc6e476dfdad46
=> UI: Prefill rename dialog with the current document name

browser/html/cool.html.m4, browser/src/map/handler/Map.WOPI.js
Without that integrator doesn't know what happened. We were silently ignoring messages.
=> postmessage: add more logging for debugging issues

coolwsd.xml.in, kit/ChildSession.cpp, wsd/COOLWSD.cpp
Change-Id: I060b3d2d9d1e7e29a18f5ea1d619c9349eae67c3
* Resolves: # 
=> Control overwrite mode function via config

browser/css/btns.css, browser/css/jsdialogs.css
- Writer - Insert tab - Page Number page preview
- Writer - References tab - Table of Contents and Index - Columns preview 
- Calc - Autofilter - Two image buttons
=> dark mode improvement of UI images

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/jsdialog/Widget.Combobox.js
Fixes #7488
calc perf: switching sheets spams font bits
requires: https://gerrit.libreoffice.org/c/core/+/158345
instead of "update" of the widget we send "action" (setText, select)
=> jsdialog: small listbox updates

browser/src/control/Permission.js, browser/src/layer/tile/CanvasTileLayer.js, kit/ChildSession.cpp, wsd/ClientSession.cpp, wsd/protocol.txt
Change-Id: I8c410460a5f500f724996fbcbf8f9650028daaf9
* Resolves: #6048 
Removed unused requestloksession command.
=> Remove unused requestloksession command

browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.TopToolbar.js
Change-Id: I4697ea48e1a10fb3e442102c3ad97a35c8a6e3ea
* Resolves: #7470
=> Fix wrong label on Draw UI: ModifyPage

browser/src/control/Control.Notebookbar.js
- regression from 8607aa7
Change-Id: Id94b98c832d8801dd9c05cdd6223bad17d202d71
* Resolves: # 
=> browser: fix readonly document menubar not working

common/JailUtil.cpp, net/Socket.hpp
Change-Id: Id2517f310a1df71dc1357d103ea074bdd12e7e65
* Resolves: # 
=> These warnings are frequent but harmless

browser/src/layer/tile/CommentSection.ts
Change-Id: I45bbfc7095bf94d9d68faae054ab96287dfc62b8
=> annotation: avoid trying autosave empty comments

browser/src/core/Socket.js, browser/src/errormessages.js, browser/src/map/Map.js, browser/src/map/handler/Map.WOPI.js
Change-Id: Ib654d0e81d0796ba379e9482ad90e6cb8af5901d
* Resolves: # 
=> browser: show error msg when socket connection is closed unexpectedly

browser/src/control/Control.NotebookbarCalc.js
Change-Id: I9d8729830470c23dd3cb03c7ce0ca75f05b9c249
=> Calc: Notebookbar definitions: add missing class for collapse tabs

browser/src/layer/marker/A11yTextInput.js, browser/src/map/Map.js
Change-Id: Iec00a71ad86e5d6114be9dc6864953284f66a0b0
=> a11y: calc: make possible to enable/disable a11y for spreadsheets

browser/Makefile.am, coolwsd.xml.in, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/FileServer.cpp
Change-Id: Idb66227d98f8fcca35307c3598a1fcc6b69e38c6
=> wsd: config cleanup and warning fixes

wasm/README
Change-Id: I2a73e876290c10ee34385f807364ca4dd5b52063
* Resolves: # 
=> cowasm: parameterize masses of paths included in command-lines.

browser/src/layer/tile/CommentSection.ts
Change-Id: I080f817a3020249de4eefd12b3d23af1141a273d
=> annotation: fix parent comment being deleted if reply cancelled

browser/css/jsdialogs.css, browser/src/control/Control.JSDialog.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/jsdialog/Util.Dropdown.js, browser/src/control/jsdialog/Widget.Combobox.js
- showsubmenu event on hover
- hidedropdown event on leave
- submenu is inserted into the same overlay as parent dropdown
- don't destory overlay if submenu is closed, do that only for root
=> jsdialog: open submenu on hover in dropdowns

cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/desktop/calc/annotation_spec.js, cypress_test/integration_tests/desktop/impress/annotation_spec.js, cypress_test/integration_tests/desktop/writer/annotation_spec.js
=> Annotation autosave cypress

browser/src/layer/tile/CanvasTileLayer.js
- regression from 762ce28e22f4c11e0f4d7c2ba0ba66144586f11c
Change-Id: I86b913213135982031d33b4b29f54df2e8320ea4
=> browser: wireId out of sync on reconnect

README.md
Updated the icon for Twitter
Change-Id: Iff04c41135f8c5523f8dc12ae46c14209575bb13
* Resolves:
=> Updated the icon for Twitter handle

browser/src/layer/tile/CommentSection.ts, browser/src/layer/tile/ImpressTileLayer.js, cypress_test/integration_tests/desktop/impress/annotation_spec.js
=> fixed impress disappearing comments on autosave 

browser/src/layer/tile/CommentSection.ts
Change-Id: If27a60d73454ec69912b91b17128aa62b209cf6d
* Resolves: # 
=> Provide better tracking of focus in-out events for comment containers.

browser/Makefile.am
Change-Id: I3a09891900ff0c22e9f133d9032a2625ef47e6a8
=> src/docstate.js contains localizable UI strings

kit/ChildSession.cpp, test/httpwstest.cpp
Change-Id: Ief478ba97ac33f386d7b09aa551168e2c05259de
=> Make wsd aware of LOK_CALLBACK_CORE_LOG callback

browser/src/layer/tile/CommentListSection.ts, browser/src/layer/tile/CommentSection.ts
Change-Id: I48bf2826df07cb501603f5c545f1bfc73d3b1254
* Resolves: # 
=> replying comment creates duplicate

browser/src/map/handler/Map.Keyboard.js
Change-Id: I0a5e3b1061b6ccff8ce98d60cddd906fcb337003
=> browser:disable ctrl+s when HideSaveOption is true

.gitpod-files/coolwsd-gitpod.xml
Add missing defaults and update user_interface defaults
Change-Id: Icbb3a40e507bbb409d208a434920e36c62eb1f03
=> Gitpod: update defaults in coolwsd-gitpod.xml

browser/css/jsdialogs.css
Change-Id: I9214fda63f6caea0a36ab8be7c26baf4e1c0f46e
(cherry picked from commit a963987ff20dd8bdfd729f070dc0ca64740f5839)
=> dark-mode use correct jquery-ui icons with data-theme value

browser/src/layer/tile/CanvasTileLayer.js
in:
commit 24f0819337e26651a0aac2442e777f702e3db9ad
Date:   Wed Jul 12 10:09:10 2023 +0100
tile debug: render updates as well as deltas in the tile.
one is typo for the other
Change-Id: I9cb27d7912aa86373b8ef399fca442f85cfd69fb
* Resolves: # 
=> _debugLoadUpdate isn't set, _debugUpdates isn't read

browser/src/control/Control.JSDialog.js, cypress_test/integration_tests/desktop/calc/help_dialog_update_spec.js, cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
The PopUp dialog is not closed, and side effects
are unresponsive key input
Change-Id: Id72ef0c6d081aa73acb39a07eb3e8b33d0e8dc85
=> browser: fix undefined property 'isPopup'

browser/html/cool.html.m4
Change-Id: I23e03ba381aa320511aacf24196aba1ff934fc52
* Resolves: # 
=> disable spell check for document name input field

browser/src/control/Control.Notebookbar.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Control.UIManager.js, browser/src/map/handler/Map.WOPI.js
https://github.com/CollaboraOnline/online/issues/5957
https://github.com/CollaboraOnline/online/issues/7517
Change-Id: I719f27063f01e4d76742358189b080087881ab7c
* Resolves: #5957
=> notebookbar: handle show/hide button

browser/html/framed.doc.html
Change-Id: Idbd1b5d89ea53d4f9925b727e8db2854ac23b17f
* Resolves: # 
=> framed.doc: Relayout the post message test harness

browser/src/control/Control.PresentationBar.js, cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
- browser: fix slide pane height container
- cypress: add unit test to check slide pane height
=> slide pane container height

coolwsd.xml.in, wsd/COOLWSD.cpp, wsd/FileServer.cpp
Change-Id: I583a8104f590e26a76837bef00814684e2015c7a
* Resolves: # 
=> allow testing wasm in non-debug mode

browser/js/global.js
Change-Id: I43c3bc5e1725f9d364c44638364f836e94f38290
* Resolves: # 
=> indirection: change request interval from 10s -> 3s

browser/src/control/Control.Command.js, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js, browser/src/control/Control.PartsPreview.js, browser/src/control/Toolbar.js, browser/src/control/jsdialog/Widget.MobileBorderSelector.js, browser/src/control/jsdialog/Widget.TreeView.js, browser/src/core/LOUtil.js, browser/src/layer/FormFieldButtonLayer.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/CommentListSection.ts, browser/src/layer/tile/CommentSection.ts
- All Icon HTML structure shoulb be same as other icons
- Most of the places we have this way to add icon in DOM
- <Button> <img/> <Button>
- This patch is to change for some icon with drop down which is not consistent with above structure
Change-Id: I1a82bc4b3dfbca15f62bfe111e36804c754da539
* Resolves: # 
=> Make icon structure consistent

wsd/ClientSession.cpp
- send blockingcommandstatus after document is loaded
- also fix odd nodocloaded dialog
Change-Id: I8f0ae405ffa77b47e09c01caf51ddc4fd5e1d862
* Resolves: # 
=> wsd: fix: failed to load passwordprotected and csv files

browser/html/framed.doc.html
Change-Id: Idad883f566a02b1e777c8c7af6b9b52da3a62e69
* Resolves: # 
Adds buttons to switch app in the demo frame.
Note: this is not to provide a public demo. Nor was it before.
=> framed.doc: Allow switching app on the fly

browser/src/core/Socket.js, wsd/Admin.cpp, wsd/Admin.hpp, wsd/AdminModel.cpp, wsd/AdminModel.hpp, wsd/ClientSession.cpp
- routetoken_sanity_check
Change-Id: Ieaabcd044b65ad0620089ae6413e3f626ff68c4c
=> admin: indirection add new command for sanity check

browser/src/control/jsdialog/Widget.TreeView.js
=> Change checkbox state by click on checkbox label

browser/src/control/Control.ColumnGroup.ts, browser/src/control/Control.RowGroup.ts
Change-Id: I68572eb126acf4a00ed96af870c1f908083aec8b
* Resolves: #7369 
=> Calc: make grouping responsive for each group level

browser/src/control/Control.Mention.js
Change-Id: I2002721dbd92fc44e9b924e67107b627e7176b87
=> fix: can't insert mention on pressing 'Enter' key

browser/src/control/Control.Header.ts
- Update only row or column section based on isColumn value
- it will not update both section if there is only need to refresh only row or only column
Follow-up PR for : https://github.com/CollaboraOnline/online/pull/6579
Change-Id: I7d614528195f0d7b0dfd0a1afa865cc890a35c2c
=> Refactor changes for update clac Header on mode change

browser/src/control/Control.PartsPreview.js, browser/src/control/Control.Tabs.js, browser/src/control/Parts.js, browser/src/layer/tile/CommentListSection.ts
=> annotation: don't change slide/sheet while editing comment 

browser/css/notebookbar.css, browser/css/toolbar.css
Change-Id: I992936919e26c135a05c29d44c62dc07e1c49d04
=> Dark mode: Fix icon's opacity and color on shortcuts component

browser/html/cool-help.html
Change-Id: I3015e6a40030d40fe11d2db85703b8be1eefbed1
* Resolves: #  
=> Fix: Many Icons Not Inverting Color In Dark mode cool-help

browser/src/core/Socket.js, browser/src/docstate.js, browser/src/errormessages.js, browser/src/main.js
Change-Id: I84c93d81f0aea1f79e2ede9186b2864bf11f723a
* Resolves: # 
=> spdx: improve machine and human readability of headers.

kubernetes/helm/collabora-online/Chart.yaml
Change-Id: Ie44e132dd230dcb8028aafd9ab249f60c9502a91
* Resolves: # 
=> Update Helm Chart with new release 23.05.6.3

.github/workflows/helm-release.yml
supports OCI specification
Change-Id: I5bc031552fe2eb6940f068dcef82fe71f640585c
* Resolves: #7831 
=> helm: push chart to github container registry which

cypress_test/integration_tests/common/helper.js
And other changes to reduce logs by about
20 lines per test (15% of total)
Change-Id: Ia6a1c96752816c5cd9fb11368cf921bdce9936ff
Replace `cy.cGet('#x').should('exist')` with `cy.getFrame().find('#x')`
Only print used params
Inline/simplify frame selection for document checks
Silence logs for checks that are part of doIf* helpers
Before
```
cy:log ✱  Loading test document - start.
cy:log ✱  Param - fileName: annotation.ods
cy:log ✱  Param - subFolder: calc
cy:log ✱  Param - noFileCopy: undefined
cy:log ✱  Param - isMultiUser: undefined
cy:log ✱  Param - subsequentLoad: undefined
cy:log ✱  Param - hasInteractionBeforeLoad: undefined
cy:log ✱  Param - noRename: undefined
cy:command ✔  window	
cy:log ✱  Loading test document with a local build - start.
cy:log ✱  Param - fileName: …
```
=> Replace cy.cGet with cy.getFrame in document load

browser/css/mobilewizard.css
Change-Id: Ie6bdb2423f92b5959a2233ee0dccc6f8e2e5dc35
* Resolves: #7701
=> Android: Insert Cells Menu Misaligned Radio Buttons

browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/ImpressTileLayer.js, browser/src/layer/tile/TilesSection.ts, browser/src/layer/tile/WriterTileLayer.js, browser/src/map/handler/Map.Keyboard.js
- Split the tools into categories (Display, Logging, Input)
- Made a tool for the tile overlay grid and turned it off by default
- Commented out Sidebar Rerendering and Always Active which as far as I could tell from a code search don't have any affect anymore
=> More work on the debug menu

coolwsd.xml.in
Change-Id: I8a15ef06e5a6c8a9f246cb9520f277357d6fc43f
=> config: correct the description of always_save_on_exit

kubernetes/helm/collabora-online/Chart.yaml, kubernetes/helm/collabora-online/templates/prometheus-rules.yaml
Ping @Rash419 just a small change
=> fix(helm): improve alerts

browser/css/device-mobile.css, browser/src/layer/tile/CommentListSection.ts
Change-Id: Ibb6beff5659f5240ff2b49897e8a491f08933691
* Resolves:
Comment:
HyperLink:
=> Mobile: Insert comment layout is too narrow and doesn't occupy full height

kubernetes/helm/collabora-online/Chart.yaml, kubernetes/helm/collabora-online/templates/prometheus-rules.yaml
Ping @Rash419 (sorry for again).
after #7679 was merged, it is possible to add more labels (like the wopisrc / `key`, filename and wopiHOST)
=> fix(helm): improve alerts many viewer on document with metadata

browser/src/control/Control.IdleHandler.ts, browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CommentListSection.ts, browser/src/layer/tile/CommentSection.ts
Change-Id: Ifc76f83ef1cca6cf6113f63bcb50312523ffbf52
=> annotation: scroll to make selected comment visible

browser/Makefile.am
Change-Id: Ifb6795647332b6f2dfb208e9b426f788759e325a
* Resolves: # 
=> Add src/control/Control.UIManager.js to list of localizable files

test/UnitUNOCommand.cpp
The JS code does the same at
browser/src/layer/tile/CanvasTileLayer.js:3074.
In preparation of picking core.git
51d8a2ef54751403fa707816e27ddb4e7faa8231 (cool#7492 sfx2 lok: fix bad
view id / statusbar string on async binding update, 2024-01-08) to
core.git co-23.05: this online.git commit should go in first to avoid
breakage.
Change-Id: I652e5c738b7e137970a820de2d71f9c03ba6df7e
=> test, UnitUNOCommand: also accept json payloads for statechanged

browser/src/layer/tile/CanvasTileLayer.js
since:
commit dbc4227fa373b6bdaedb727aef0b10a09e408a36
Date:   Tue Jan 2 12:37:45 2024 +0000
debug menu: initialize state on enabling debug.
Change-Id: I600583b670a0cd5846c95d297703c9d79f98a71a
* Resolves: # 
=> _debugGetTimeArray not found

browser/css/spreadsheet.css
- add bg-color for active sheet tab in Calc
- this will differentiate selected tab with the not selected
- add hover effect on active tab
Change-Id: I1e1b4dfa868c30bbf7b3abdd6dafad88777ce19a
Before:
After:
=> Add bg color for active sheet tab in Calc

browser/src/control/Control.Header.ts
The header entry initialization does not correctly set the "backgroundColor" or "hoverColor" and fails silently. Fix that by grabbing a known CSS property.
The "onMouseMove" callback incorrectly sets the previous entry to the resulting (new) entry before using it within a comparison. This causes the branch to never be taken. Fix it by saving the previous entry and use the previous entry when appropriate.
In "onLeave" set the "isOver" property to false so the redraw removes the highlight.
Change-Id: I801fd3e6b6759b0ab66a99d68cd0ef80f1f3737e
Signed-off-by: Mazin Alhaddad <mazin@getstate.dev>
* Resolves: #7959 
- [] Documentation (manuals or wiki) has been updated or is not required
=> Fix control header entry highlighting

ios/Mobile/DocumentViewController.h, ios/Mobile/DocumentViewController.mm, kit/ChildSession.cpp
Have the document's DocumentViewController display a save dialog and export a copy of the file written by the LibreOffice code.
=> Implement LOK_CALLBACK_EXPORT_FILE for download requests in the iOS app

browser/images/lc_presentinwindow.svg
Change-Id: I4488d432b71fde92dad643bf2069ea4694708e96
=> Add missing present in window icon

browser/src/layer/tile/CanvasTileLayer.js, kit/ChildSession.cpp
Converting the coordinates were inconsistent.
Created JSON was not valid.
This PR fixes the issues.
Change-Id: Ibb9cf4e4517a8e3f2d5fc701fdcf287ce72b6b9c
* Resolves: # 
=> Fix readonly click event.

browser/src/control/Control.IdleHandler.ts
This is followup for commit add3b76eb5ad576332c8a7150c2ad07881ec224f
IdleHandler: bring back idle timeout for view
Which restored dimmed view, but I forogot to bring back sending userinactive message in some cases
=> IdleHandler: sedn userinactive to server

browser/src/core/Socket.js, browser/src/layer/tile/CanvasTileLayer.js
and just "tile invalidations" toggled on
Change-Id: I8b8070acd9a7fc39ae176b8cf7a7c89517cd9ec5
* Resolves: # 
=> exceptions with triple debugging on but screen overlay toggled off

browser/css/device-mobile.css, browser/src/control/Control.MobileWizardWindow.js
* Resolves: # 
Before: 
After: 
[Previous PR](https://github.com/CollaboraOnline/online/pull/7719#pullrequestreview-1788477979)
=> Mobile: Change the full height of the busy popup to narrow

common/Util.cpp, common/Util.hpp, test/WhiteBoxTests.cpp, wsd/COOLWSD.cpp
But re-write them anyway to be more sensible.
Change-Id: Ie146f4f84b539ab7e826a1c1b947497acde7e384
* Resolves: # 
=> convert-to: be more tolerant of unusual filenames.

browser/css/jsdialogs.css
=> Improve combox text input border appearance

browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ibcc38ba7af9108305a2efd940060267ec08dbbdf
* Resolves: # 
=> Enable readonly click for all document types.

browser/src/layer/tile/CanvasTileLayer.js
Using internal tricks to accomplish the task.
Change-Id: Ie969a934f17a1b57a5c7acae8aa84baadfc5b5e2
* Resolves: # 
=> Do copy the hyperlink location in readonly mode.

coolwsd.xml.in
=> Increase out-of-focus idle timeout to 5 min

browser/Makefile.am, browser/admin/admin.strings.js, browser/admin/adminClusterBody.html, browser/admin/adminClusterOverview.html, browser/admin/adminClusterOverviewAbout.html, browser/admin/admintemplate.html, browser/admin/src/AdminClusterOverviewAbout.js, wsd/FileServer.cpp
- show full license
Change-Id: Ia51012b5277e6666733fc83441754276a79759da
* Resolves: # 
=> admin: add about page for indirection server

browser/src/map/handler/Map.Feedback.js
Change-Id: I251aec921d6f174652e3068dfa06e5dfcaf61965
=> browser: close feedback dialog if ESC key is pressed

browser/src/layer/tile/CanvasTileLayer.js
Sets dark mode, zoom, spell check, sidebar, and moves around the sheet in calc
Change-Id: I56adcc425e3d7472f811f6e1e904186554dd432f
* Resolves: # 
Just the first part of https://github.com/CollaboraOnline/online/pull/7975, with a couple of improvements
=> Randomize user settings

browser/css/cool.css
Change-Id: I40f716a5989ffb370eb87d34bd9ab0fee5df9dbb
**Before:** 
Light mode:
Dark Mode:
**After:** 
Light mode:
Dark Mode:
=> Modify freeze cloumns and row style for better user experience

browser/html/cool.html.m4, browser/js/global.js, browser/src/core/Socket.js, browser/src/errormessages.js, browser/src/main.js, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/FileServer.cpp
Use "fetch()" function to save logging client data
to server side.
Change-Id: I8b6a94b7ad7ae02ca00666759e3695867df4d372
=> browser: simplify logServer

browser/js/global.js
Change-Id: Ie007dbdc2d4066c657d2a1cd05c6f4532404495b
* Resolves: # 
=> lang ended up as "(null)" and docs from debug.html didn't load

browser/html/cool.html.m4, browser/js/global.js, browser/src/core/Socket.js, browser/src/errormessages.js, browser/src/main.js, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp, wsd/FileServer.cpp
- browser: simplify logServer
- browser: simplify getParameterByName
- browser: if 'console.error' is invoked also invoke ...
- browser: catch exceptions should include the stack trace
- browser: simplifiy global === window
- browser: simplify no implicit access to L object
- browser: remove unused function "onSlideClick"
- browser: remove unused function "Base64ToArrayBuffer"
- browser: move iOS app init event listeners
- browser: move function "isLocalStorageAllowed"
- wsd: add logging token javascript errors
- browser: add logging token to send to server side
- lang ended up as "(null)" and docs from debug.html didn't load
=> back-ports

browser/src/layer/tile/CanvasTileLayer.js
Added two options:
Randomize user settings: Sets dark mode, zoom, spell check, position in sheet
Automated user input: loops over actions: type in cell/formula, delete cell/row, insert/type in shape
These replace the chaotic inputs from before
I encountered a crash somewhere around editing the text in the shape. I got the stack trace and am trying to get better reproduction steps.
It's not ready to submit yet but I want to get some feedback:
- What do you think of the approach, a toggle for starting the input and a toggle (button, really) for randomizing the settings
- Additional settings to toggle (I understand interface language is not possible)
- Additional tasks to do (I already plan to select a block of cells and change the row height)
- How do I programatically click in the sheet? …
=> Input tools

browser/src/control/Control.Tabs.js
- Trying to open context menu from a sheet tab also changes the active tab. This occurs when right click on a sheet tab (or long tap on mobile or tablet)
- moveLeft and moveRight of inactive tabs are implemented.
- added _moveSheetLR and _moveOrCopySheet functions.
Change-Id: I5b25a8cb363b8e04fd6dcec1f500e7ff2982b678
* Resolves: # 
=> Calc: Don't switch tabs when context menu is triggered

browser/src/map/Clipboard.js
- cool#8023 browser, clipboard: try using navigator.clipboard before showing the paste popup
- cool#8023 browser, clipboard: fix navigator.clipboard for the plain text case
- cool#8023 browser, clipboard: fix navigator.clipboard for the image case
- cool#8023 browser, clipboard: try to use navigator.clipboard for paste special, too
- cool#8023 browser, clipboard: try to use navigator.clipboard only in experimental mode
=> clipboard: try to use the new navigator.clipboard API

browser/admin/src/AdminClusterOverview.js
=> fix UI bugs in adminClusterOverview.html

browser/src/map/Clipboard.js
- cool#8023 browser, clipboard: try using navigator.clipboard before showing the paste popup
- cool#8023 browser, clipboard: fix navigator.clipboard for the plain text case
- cool#8023 browser, clipboard: fix navigator.clipboard for the image case
- cool#8023 browser, clipboard: try to use navigator.clipboard for paste special, too
- cool#8023 browser, clipboard: try to use navigator.clipboard only in experimental mode
=> private/vmiklos/distro/collabora/co 23.05

browser/js/global.js, browser/src/control/Control.DownloadProgress.js, browser/src/core/Util.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/map/handler/Map.Keyboard.js, browser/src/map/handler/Map.Mouse.js
Change-Id: I3ce0eaa5145c8d8bb40422c9b2d472579b0ec74f
* Resolves: # 
=> global: Add L.Browser.mac to not parse user agent everywhere

browser/src/layer/tile/CommentSection.ts
Change-Id: I660ca7cbc9e6ce6eaa3834ebd3c2829c606bc045
=> browser: fix "Uncaught TypeError: getSectionWithName"

browser/src/core/Debug.js, browser/src/core/Socket.js, browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I768562e7e4a17d65338d0f5a64c4346e2f09f53f
Continuing to disentangle debug management code from feature code
Features now do not need to know about the overlayData data structure or leaflet attributions
=> Encapsulate debug overlayData

browser/src/map/handler/Map.Keyboard.js
Change-Id: I8000946e5d4c28288d0ad778b243ce8442c3b8c0
* Resolves: # 
=> add pageup and page down to preview navigation

.github/workflows/helm-release.yml
=> release: upload helm chart to docker hub as well

net/FakeSocket.hpp, net/NetUtil.cpp, net/Socket.cpp, test/helpers.hpp
Change-Id: I5f59ed9446a1fda301bb4791f98ca7c1c137e606
* Resolves: # 
=> sockets should use CLOEXEC ticket cool#8016

coolwsd.xml.in, wsd/COOLWSD.cpp, wsd/ClientSession.cpp
Change-Id: I12abdd0755883acb7bae126ac3c9c999598b4428
=> wsd: Add config to customize OS version info

ios/Mobile/Resources/Settings.bundle/Root.plist.in, ios/Mobile/Resources/Settings.bundle/en.lproj/Root.strings
=> Update iOS settings panel

browser/css/toolbar.css, browser/src/control/Control.JSDialog.js, browser/src/control/Control.Tabs.js
- avatar popup list in the top right corner was getting cropped if we have multiple users ( like more than 10=12)
- this patch will make overflow auto and add scroll option to tackle this issue
Change-Id: Id57539cb91a7f4a2a3766e6d01f0e6a00d3af92a
Backport PR: https://github.com/CollaboraOnline/online/pull/8097
=> Fix cropped userlist popup

scripts/profile-cool
and how to sudo it, and tweak PATH to use the suggested info automatically when sudoed
Change-Id: I977f04bd38ad76393203c06d21f4a27abd0705ef
* Resolves: # 
=> add info to profiling script how to install dependencies

browser/src/core/Debug.js
Add debug tools to resize and delete columns
Also fixed position for "Click, type, delete", and added delete for "Insert and delete shape".
Video shows several times through the two tools.
Each step is the same 2000ms, column resize and delete are just really slow for some reason.
[Screencast from 2024-01-30 21-16-05.webm](https://github.com/CollaboraOnline/online/assets/153108452/0d13e4e0-e2a0-453c-845e-71485fa78763)
=> Add debug tools to resize and delete columns

browser/src/core/Debug.js, browser/src/core/Log.js, browser/src/core/Socket.js, browser/src/layer/marker/A11yTextInput.js, browser/src/layer/marker/TextInput.js, browser/src/map/handler/Map.Keyboard.js
Change-Id: I157cf9b651069e8f4c81b4595cddf7748323c062
Adds three new tools:
- Log incoming messages
- Log outgoing messages
- Log keyboard events
I left them on by default in debug mode but this change does disable the logging until debug mode is started.
=> Debug tool for incoming/outcoming/keyboard msgs

browser/css/jsdialogs.css
Change-Id: Iff389334e534eb386904705b00b917a848a7154e
* Resolves: #8031
=> fix padding of spinfield unit on Firefox #8031

browser/js/global.js, browser/src/layer/tile/CanvasTileLayer.js, cypress_test/integration_tests/idle/calc/idle_spec.js
=> Backport automated user work to 23.05

common/FileUtil.cpp, common/FileUtil.hpp, test/helpers.hpp, test/integration-http-server.cpp
Change-Id: I7c8a122425c689edb3eeb8c80e08470eac347bcc
* Resolves: # 
=> getTempFileCopyPath is only used by tests so move to test-only code

browser/css/toolbar.css
It seems when users are unknown we can get a different JSON bject:
Object { ViewId: "8", UserName: "Unknown", Color: 13013504, … }
This is then flagged and set as a different (from the identified
avatars) html element in createAvatar from Control.UserList.js
Better to fix the alignment via CSS
Change-Id: I94fee62ae14bb47c6f989b4e0bb147f8ffc9ff39
=> backporting: Avatar list: set Unknown user avatar with 0 margin, fix alignment

kubernetes/helm/collabora-online/Chart.yaml
Change-Id: I60134cca4ae3a62fdc2fcf23e43a629034188496
* Resolves: # 
=> Update Helm Chart with new release 23.05.8.4

browser/src/layer/tile/CanvasSectionContainer.ts
Also move its declaration to the top of the class section with other class members.
Change-Id: I506423078423074171ab00efb6f2d3fab0c68796
* Resolves: # 
Mostly a code smell fix and a formatting change, but it might help https://github.com/CollaboraOnline/online/issues/8157
https://github.com/CollaboraOnline/online/pull/8168 will prevent the actual issue.
=> browser: CanvasSectionContainer initialize boundsList

browser/src/core/Debug.js
Change-Id: Id6ba3e351214f9bd2676b4935baa8105646d12c0
* Resolves: # 
=> Adjust zoom limits for random user

browser/src/core/Debug.js
Change-Id: I4f0e39784e82ce332b344f71456ac90bbd92a7d6
* Resolves: # 
Mostly copied from delete rows/columns tool.
=> Add automated user tool to insert rows/columns

wsd/DocumentBroker.cpp
Change-Id: I622bc1569c775c57d7f268a063195706bb12be7b
* Resolves: # 
=> tidy doc path

kit/Kit.cpp, net/Socket.cpp
Given the surrounding debug we should be able infer the same state from its absence.
Change-Id: Id20de40f67ed52dc5535585aec9b5888131d6324
* Resolves: # 
=> Reduce noise of somewhat excessive trace debug.

net/HttpRequest.hpp, wsd/COOLWSD.cpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp
and
cid#336290 COPY_INSTEAD_OF_MOVE
cid#336288 COPY_INSTEAD_OF_MOVE
cid#336282 COPY_INSTEAD_OF_MOVE
cid#318980 COPY_INSTEAD_OF_MOVE
cid#318853 COPY_INSTEAD_OF_MOVE
Change-Id: Icf6447b8298432359ec37242427ce595f8de4160
* Resolves: # 
=> cid#336284 COPY_INSTEAD_OF_MOVE

browser/css/cool.css, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/vector/CPath.ts, browser/src/layer/vector/CSplitterLine.ts, browser/src/layer/vector/CanvasOverlay.ts
- added row/col divider with a transparent gradient over the area where cells are concealed
- shadow color will change according to UI theme (Dark/Light)
[Screencast from 2024-01-23 19-38-01.webm](https://github.com/CollaboraOnline/online/assets/61383886/c44ea050-2fa8-45d3-b213-ecaa0d28a30a)
Change-Id: I3fe6f3b35ec84cda5d93fe9a094765cfb75b906c
=> Add visual hint for freeze pane Lines

browser/src/layer/tile/CommentListSection.ts
Change-Id: I3c5a3267947e0dfc8f53663ccdc7032ebd1819c3
=> annotation: scroll sheet if comments are not fully in view on hovering

browser/.eslintrc, browser/package.json, browser/src/control/Control.Header.ts, browser/src/control/Control.JSDialogBuilder.js, browser/src/layer/tile/CanvasTileLayer.js
=> es2015: bump eslint version

wsd/DocumentBroker.cpp
Change-Id: I622bc1569c775c57d7f268a063195706bb12be7b (cherry picked from commit d8041e951695cff7f8f24ecf1e1644a317c6193f)
* Resolves: # 
=> use a path name unrelated to the parent dir name

browser/src/control/Control.Menubar.js, browser/src/control/Toolbar.js
Change-Id: Ifcb34977b72bb0eccd23667deb4750637810e569
* Resolves: # 
cc #8029
=> browser: move  impl of savecomments command to Toolbar dispatch

browser/js/global.js
We use this for the richdocumentscode case, but it is more generally useful, this should be a pure re-factor.
Change-Id: I3a7f09d3da902a85dc2b362f7a160f07c90b97c6
* Resolves: # 
=> refactor: split out CSS image visiting.

browser/src/control/Control.Tabs.js
Require LOKit change Ib8e8209225d027472c1f2eef57839df5784acf30 
https://gerrit.libreoffice.org/c/core/+/163205
Change-Id: Ie54b355ad794a0e34fabbd8e56b4a17a936686f7
* Resolves: Part of #551 
=> calc: Enable sheet protection

browser/src/core/Debug.js
Instructions for exiting debug mode, just in case a user accidentally ends up here
=> Add header to debug menu

net/Socket.cpp, wsd/COOLWSD.cpp, wsd/DocumentBroker.cpp, wsd/RequestVettingStation.cpp
and
cid#336280 COPY_INSTEAD_OF_MOVE
cid#318848 COPY_INSTEAD_OF_MOVE
cid#318964 COPY_INSTEAD_OF_MOVE
cid#344354 COPY_INSTEAD_OF_MOVE
Change-Id: I60a904be4b5edf61cfd5b2efab81e5c1a089b661
* Resolves: # 
=> cid#344351 COPY_INSTEAD_OF_MOVE

browser/src/layer/tile/CommentListSection.ts
Change-Id: I3c5a3267947e0dfc8f53663ccdc7032ebd1819c3
=> annotation: scroll sheet if comments are not fully in view on hovering (backport)

browser/css/cool.css, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js, browser/src/layer/tile/CommentListSection.ts, browser/src/layer/tile/CommentSection.ts
=> Handle deletion of tracked comments (backport PR)

browser/src/layer/tile/CanvasSectionContainer.ts
* Target version: 23.05 
backport of https://github.com/CollaboraOnline/online/pull/8182
=> Backport: browser: CanvasSectionContainer initialize boundsList #8182 

browser/src/layer/tile/CanvasTileLayer.js
5 small automated user and debug menu changes that can go into 23.05
=> Backport automated user/debug menu changes to 23.05

browser/src/layer/vector/SVGGroup.js, net/HttpRequest.hpp, wsd/COOLWSD.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
- "range" requests
- "position" in safari
=> Safari: embedded video playback (22.05)

test/FileServeWhiteBoxTests.cpp, test/Makefile.am
Change-Id: I7a5b96da9e892c1948cbbc52c57344a2b67daab6
=> fix fail unit test "builddir != srcdir"

browser/src/map/handler/Map.SlideShow.js
237d9c084a7ebf4681e1e850c4c5df410f8fa67a fixed videos rendering in the wrong place on Safari (and all iOS browsers) in edit mode. Unfortunately, it made the oversight of missing presentation mode, which gets its SVGs from a completely different place :facepalm:.
This commit fixes presentation mode.
After this commit, you will see the video in the right place. Please note that the white border present in edit mode is not there in presentation mode, so if you line the video edge up with something in the presentation you may think the video is offset: I suggest lining something in the video up rather than the edge of the video object.
Known caveats:
- This commit seems to be a few pixels off with larger border sizes. It's a lot better than before, but still not perfect
This commit does not …
=> Fix video position in safari presentation mode

browser/src/layer/vector/Circle.js
Change-Id: Iee185c006f158b49d43834e756b40f236cc94b16
* Resolves: # 
=> add a comment for a potential unused file.

browser/css/spreadsheet.css, browser/src/control/Control.Tabs.js, browser/src/core/Socket.js, browser/src/layer/tile/CalcTileLayer.js, kit/KitHelper.hpp
* Resolves: #  See #551
* Target version: 23.05 
The required LOKit patches have landed.
=> backport - Sheet protect status

cypress_test/integration_tests/desktop/writer/track_changes_spec.js
Change-Id: If1a2bbe7d9d3ec7fa821db91aea1f7b3ed6f2c1e
=> cypress: add tests for tracked comments operation

browser/src/control/Control.NotebookbarCalc.js
Change-Id: I845bd0dd4d8da4955c88e932c2701931b46e155f
* Resolves: # 
=> calc: Added protect sheet command in the notebook bar

browser/src/layer/tile/CommentSection.ts
but it gets computed anyway, move it so its only called if actually needed
Change-Id: I187540df6def6b4f92199e273665e04ed493035a
* Resolves: # 
=> getComputedStyle is very slow, but we don't need it for LTR comments

cypress_test/integration_tests/desktop/writer/track_changes_spec.js
Change-Id: If1a2bbe7d9d3ec7fa821db91aea1f7b3ed6f2c1e
=> cypress: add tests for tracked comments operation (forward porting)

browser/src/layer/tile/CommentListSection.ts
In calc all comments are hidden and only shown when mouse hovers the cell to which the comment is attached. Anchor was always a wrong value so when we were at some more distant position - it always jumped to random place on hover.
This is regression from:
commit 6550e713c4bf687931aa721f36d0a28ac70e94f0
annotation: calc scroll vertical to make selected comment visible which was followup for:
commit 2bf93e34c349cbce3bfb70c5b92aed61b749101a
annotation: writer scroll to make selected comment visible
We need to compare the same type of positions. Now all the values will be in core pixels and methods have comment which indicates that.
=> calc: calculate correct position when scrolling to comment

browser/js/global.js, wsd/AdminModel.cpp
Change-Id: I5fc4017e647403822fbb0ceefd00b8aa7cfde531
* Resolves: # 
=> Fix indirection issue

browser/js/global.js, wsd/AdminModel.cpp
=> Backport indirection server

browser/src/control/Control.NotebookbarCalc.js
Change-Id: I845bd0dd4d8da4955c88e932c2701931b46e155f
* Resolves: #  #551 
* Target version: 23,05
=> backport to 23.05 - calc: Added protect sheet command in the notebook bar

browser/src/control/Control.DocumentNameInput.js
Change-Id: I11b07d8352a0e29a4756db489f570cee55c9d03e
=> [Backport] disable file renaming in readonly mode

browser/Makefile.am
Change-Id: I3236d8ebb323b7d682e58c01da4ad8ec01ee943d
=> fix unconditional install-data-hook

wsd/ClientRequestDispatcher.cpp
Change-Id: I362e8f8c0645f51b0d49294edb097dfee22b353e
=> wsd: fix missing CommandControl.hpp include

browser/src/control/Control.ColumnHeader.ts, browser/src/control/Control.Header.ts, browser/src/control/Control.RowHeader.ts
Change-Id: I82bdbaea429d4b2fec8cda9c431a215feb47a129
* Resolves: # 
=> Don't reinit header entry styles without a mode change.

cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js, cypress_test/integration_tests/desktop/impress/table_operation_spec.js, cypress_test/integration_tests/desktop/writer/invalidations_spec.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js, cypress_test/integration_tests/desktop/writer/track_changes_spec.js, cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
- missing notebookbar cypress update
- disabled 2 tracking changes tests
=> fix cypress 23.05

browser/src/control/Toolbar.js
Change-Id: I5d1a9c72f0eac33b608c118b6024f2b9a562d26b
=> Make the 'Search' placeholder localizable in help window

browser/css/cool.css, browser/src/control/Control.UIManager.js, browser/src/core/Socket.js, browser/src/layer/tile/CanvasTileLayer.js
backport of https://github.com/CollaboraOnline/online/pull/8310
-------
commit 1c1b23ea87924669294f4050405ffe2a082f1286
Author: Gülşah Köse <gulsah.kose@collabora.com>
Date:   Mon Feb 19 16:10:06 2024 +0300
Show tooltips over the cell while typing a function in a cell.
Change-Id: I85354a6c17947824408ae0458f29b858f31ab0e3
=> [Backport] Show tooltips over the cell while typing a function in a cell.

browser/src/map/Clipboard.js
- **cool#8023 browser**
- **cool#8292 browser**
=> [co-23.05] cool#8292 browser, clipboard: fix navigator.clipboard error handling

browser/html/cool-help.html, browser/src/control/Control.DocumentRepair.js, browser/src/control/Toolbar.js
Backport PR of https://github.com/CollaboraOnline/online/pull/8211
* Resolves: # 
* Resolves: # 
=> Back port : Add search content in help dialog and fix document repair for non-Eng UI to 23.05

browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Idda52eeaaef73ada94481f2a5f49b67e47b05d4a
* Resolves: # 
=> Make tooltip text translatable.

browser/Makefile.am
Change-Id: I3236d8ebb323b7d682e58c01da4ad8ec01ee943d
* Resolves: # 
=> [co-23.05] fix unconditional install-data-hook

browser/admin/src/AdminClusterOverview.js, browser/admin/src/AdminClusterOverviewAbout.js
=> Fix admin console issues

browser/src/control/Control.UIManager.js
Change-Id: Ia72fd5a4ac51f912e0b9688f39f2618ab603de12
* Resolves: # 
=> Do not trigger hidetip if no tips are present

browser/src/map/Clipboard.js
The 4 commits complete points 1-4 from https://github.com/CollaboraOnline/online/issues/8342 . This contains new l10n strings, so not to be backported as-is.
=> Improve the paste special fallback dialog, step 2

net/Socket.cpp, net/Socket.hpp, tools/WebSocketDump.cpp, wsd/Admin.cpp, wsd/ClientSession.cpp
Signed-off-by: Noel Grandin <noel.grandin@collabora.co.uk>
Change-Id: I987cc515e27fbaf4e778a5ac6f005a43ff88be71
* Resolves: # 
=> replace Poco in StreamSocket::send

browser/src/control/Toolbar.js
Forward port commit from 23.05 : https://github.com/CollaboraOnline/online/pull/8353/commits/28e1b52d5bcc0b7ca5ef5b7b97b4576e8b6917d0
- Localization of "search" placeholder in - help dialog & - Keyboard shortcut dialog
Change-Id: Idcb622dccb9e62ae02fb7eae089c7a4bf7f219a5
=> Localization of placeholder string in "Keyboard" and "help" dialog

browser/src/map/handler/Map.KeyboardShortcuts.ts
fixes broken cypress on master
=> KeyboardShortcuts: update cypress

browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js
Change-Id: I0e4f40d1f2ad50c323e9780e05451d7fe9e6e4c9
=> UI:annotation: fixed selection indication for track change buttons

browser/src/map/Clipboard.js
This backport contains 2 of the 5 master commits, these don't break translations.
=> [co-23.05] Improve UX of the paste special fallback dialog

browser/css/cool.css, browser/src/layer/tile/CommentListSection.ts
=> Tracked deleted comment interection

browser/css/cool.css, browser/src/layer/tile/CommentListSection.ts
* Target version: distro/collabora/co-23.05 
backport for: #8457
=> Tracked deleted comment interection (backport)

kubernetes/helm/collabora-online/Chart.yaml
Change-Id: I3a9d5273ee0bfbe0188f685cd66b159423498bc3
=> Update Helm Chart with new release 23.05.9.3

browser/css/cool.css, browser/src/layer/tile/CommentSection.ts, cypress_test/integration_tests/desktop/writer/track_changes_spec.js
Change-Id: Iedea40c331892140db66766e6d622e2db4da499e
=> annotation: hide deleted tracked comment if "show" option is off (backport)

browser/src/layer/tile/CommentListSection.ts
Change-Id: I4447c5e0be4c86a6c579b91de868a6736704fbfd
=> annotation: comment added with tracking must deleted without trace(backport)

wsd/COOLWSD.cpp
Change-Id: I2e10a25850a64bb666d0473d8881878ff41ad6b1
* Resolves: # 
=> Add sample URLs for readonly mode to console output.

browser/src/layer/tile/CommentListSection.ts
Change-Id: I4447c5e0be4c86a6c579b91de868a6736704fbfd
=> annotation: comment added with tracking must deleted without trace

browser/src/layer/tile/CommentListSection.ts
Change-Id: I9dac9b62b1d4f80c7a79a7d1f7c8f2d40167b29d
=> annotation: added a null check

.gitignore
coolbench binary created in https://github.com/CollaboraOnline/online/pull/8501
Change-Id: Iee40c108b7c4bfa15e19ba0a3eb683c1d8b66c9d
=> .gitignore coolbench

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/jsdialog/Util.StateChange.ts, browser/src/control/jsdialog/Widget.Combobox.js, browser/src/control/jsdialog/Widget.MenuButton.js, browser/src/control/jsdialog/Widget.MultilineEdit.js, browser/src/control/jsdialog/Widget.Timefield.js, cypress_test/Makefile.am, cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js, cypress_test/integration_tests/desktop/impress/jsdialog_spec.js, cypress_test/integration_tests/desktop/impress/sidebar_spec.js, cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
For me it fixes `make check-desktop` tests. Some tests I disabled some are fixed.
=> cypress: master fixes of check-desktop

browser/src/control/Control.IdleHandler.ts, browser/src/control/Control.UIManager.js
This reverts commit e9cf81f29ecf7fbca69c3ae412dc8660b56142f7.
problem:
when comment is being edited, nothing could be copied from the doc
Change-Id: I34ceacc5d9c7d5eb7d57ec2489a47734b80a044f
=> Revert "Check for comments in isAnyDialogOpen" (23.05)

browser/src/control/Control.JSDialog.js
Backport #8470 to distro/collabora/co-23.05
=> backport: Make JSDialogs fully reachable when wider than the screen

browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/Toolbar.js
Change-Id: I0e4f40d1f2ad50c323e9780e05451d7fe9e6e4c9
* Target version: distro/collabora/co-23.05 
backport of: #8454
=> UI:annotation: fixed selection indication for track change buttons (backport)

Makefile.am, test/KitPidHelpers.cpp, test/KitPidHelpers.hpp, test/Makefile.am, test/TileCacheTests.cpp, test/UnitCursor.cpp, test/helpers.hpp, test/httpcrashtest.cpp, test/httpwstest.cpp, test/integration-http-server.cpp, test/test.cpp, test/test.hpp, wsd/COOLWSD.cpp, wsd/COOLWSD.hpp
Backport of https://github.com/CollaboraOnline/online/pull/8486
Plus https://github.com/CollaboraOnline/online/pull/8463 and https://github.com/CollaboraOnline/online/pull/8504
* Resolves: # 
=> Backport kit process counts

cypress_test/integration_tests/common/calc_helper.js, cypress_test/integration_tests/common/contenteditable_helper.js, cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/common/mobile_helper.js, cypress_test/integration_tests/common/nextcloud_helper.js, cypress_test/integration_tests/common/repair_document_helper.js, cypress_test/integration_tests/common/search_helper.js, cypress_test/integration_tests/common/writer_helper.js
Backport of https://github.com/CollaboraOnline/online/pull/8532
Description and log examples there.
Change-Id: I61812b730fa58ee1c2969f4ded84b08f5eca981a
* Resolves: # 
=> Cypress: log helper function start and end (backport)

browser/css/leaflet.css, browser/src/control/Control.Header.ts, browser/src/layer/tile/AutoFillMarkerSection.ts, browser/src/layer/tile/CanvasSectionContainer.ts
Change-Id: Icd4452a30479591035282a789ad6c9ae742c1b0b
* Resolves: # 
=> Merge onContextMenu and onLongPress events.

browser/Makefile.am, browser/css/cool.css, browser/css/jsdialogs.css, browser/css/jssidebar.css, browser/css/notebookbar.css, browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.NotebookbarBuilder.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/control/Control.NotebookbarDraw.js, browser/src/control/Control.NotebookbarImpress.js, browser/src/control/Control.NotebookbarWriter.js, browser/src/control/jsdialog/Definitions.Menu.ts, browser/src/control/jsdialog/Util.Dropdown.js, browser/src/control/jsdialog/Widget.ColorPicker.ts, browser/src/control/jsdialog/Widget.MenuButton.js, browser/src/docstate.js, cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/desktop/calc/autofilter_spec.js, cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js, cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js, cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js, cypress_test/integration_tests/desktop/writer/notebookbar_spec.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js, cypress_test/plugins/selectorList.js
- w2color conversion to JSDialog dropdown
=> Remove w2ui #3: Notebookbar

wsd/ClientRequestDispatcher.cpp, wsd/RequestVettingStation.cpp
We might not have the WS yet when
CheckFileInfo fails or returns unauthorized.
Change-Id: Id0fe34a6fadef7ba4094707a0ae82b83b9b2a5fb
=> wsd: check if we already have a WS in RVS

cypress_test/integration_tests/desktop/writer/focus_spec.js
Add a cypress test for the change in commit dfe1e1b5
Change-Id: Id829d271efe7ccebf58c9f83cc67e6b1cf8b72e9
=> add test for font input focus

common/SigUtil.cpp, common/TraceEvent.cpp, common/TraceEvent.hpp, kit/ChildSession.cpp, kit/Kit.cpp, tools/Replay.hpp, tools/map.cpp, wsd/Admin.cpp, wsd/AdminModel.cpp, wsd/COOLWSD.cpp, wsd/ClientSession.cpp, wsd/FileServerUtil.cpp, wsd/wopi/CheckFileInfo.cpp, wsd/wopi/CheckFileInfo.hpp, wsd/wopi/WopiStorage.cpp
- wsd: better construction of ProfileZone
- wsd: better encapsulation in ProfileZone
- wsd: emit ProfileZone recording on demand
- wsd: streamline TraceEvent strings
- wsd: better empty string operations
- wsd: support ProfileZone in CheckFileInfo
- wsd: avoid duplicate string copying for ProfileZone
- wsd: corrections to TraceEvent
- wsd: add ProfileZone to WopiStorage::uploadLocalFileToStorageAsync
=> Profile Zones

browser/Makefile.am, browser/src/control/jsdialog/Util.Events.ts, browser/src/control/jsdialog/Widget.MenuButton.js, browser/src/dom/NotebookbarAccessibility.js, browser/src/dom/NotebookbarAccessibilityDefinitions.js
This enables keyboard accelerators for MenuButtons in notebookbar.
---------------------
notebookbar: a11y: open dropdown for MenuButtons
--------------------
jsdialog: allow to press dropdown arrow using keyboard in MenuButton
------------------------------
notebookbar: a11y: show accelerators for MenuButtons
=> Remove w2ui #4: Notebookbar

Makefile.am, common/Watchdog.hpp, net/Socket.cpp, net/Socket.hpp, wsd/COOLWSD.cpp
Change-Id: Id58efab0c0fee88a3da094765eb6b7641aec6e02
* Resolves: # 
=> Watchdog to call probe-point when SocketPolls are slow.

kubernetes/helm/collabora-online/Chart.yaml
Change-Id: I9bcf32e0422a886b790d5836fb4bf1f5d68090ee
* Resolves: # 
=> Update Helm Chart with new release 23.05.9.4

browser/src/map/Clipboard.js, cypress_test/Makefile.am, cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/mobile/calc/cell_appearance_spec.js, cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js, cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js, cypress_test/integration_tests/mobile/writer/apply_font_spec.js, cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
=> Fix Cypress mobile tests

browser/src/control/Control.JSDialogBuilder.js
Back port PR: https://github.com/CollaboraOnline/online/pull/8539
=> Backport: Improve Update state of uno Tool button state on stateChanged

wsd/COOLWSD.cpp, wsd/ClientRequestDispatcher.cpp
Change-Id: Ib59494884333a200d768eec8b829e565f6470e2a
=> wsd: fix support-key build

browser/css/notebookbar.css, browser/css/toolbar.css, browser/src/control/Control.PresentationBar.js, browser/src/control/Control.UIManager.js, browser/src/docdispatcher.ts, cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/desktop/draw/navigator_spec.js, cypress_test/integration_tests/desktop/impress/navigator_spec.js, cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
- it is on the left below slides list
- handle disabled state in CSS for regular unotoolbuttons
=> remove-w2ui #7: PresentationBar

browser/src/dom/Draggable.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/ScrollSection.ts, browser/src/map/handler/Map.Scroll.js, browser/src/map/handler/Map.TouchGesture.js
=> Fix panning with RTL

browser/css/leaflet.css, browser/src/control/Control.Header.ts, browser/src/layer/tile/CanvasSectionContainer.ts
Change-Id: Ifaf76e198f0357e669c9966a185b6ab506e56f49
* Resolves: # 
=> Provide longpress timer for IOS devices.

browser/src/layer/tile/CommentSection.ts
Change-Id: I37dc47e7daf991c1b2bb771fc1a96e939edd270d
=> annotation: fix calc mobile comment not visible

browser/js/global.js, browser/src/layer/tile/CanvasTileLayer.js
Backport of https://github.com/CollaboraOnline/online/pull/8254
Change-Id: Ib72b5ef4c2c31f7707a384b2d819d5cde57a796d
* Resolves: # 
=> Fix &debug=true and &randomUser=true url parameters (backport)

kubernetes/helm/collabora-online/README.md
- added recommendation for resource values for production enviroment
Change-Id: Ia9a4b730bb7fd4c990d8c34531230b04c3a7f250
=> helm: update README

browser/css/toolbar.css, browser/html/cool.html.m4, browser/src/control/Control.Menubar.js, browser/src/control/Control.Notebookbar.js, browser/src/control/Control.UserList.ts, browser/src/docdispatcher.ts, browser/src/map/handler/Map.Keyboard.js, browser/src/map/handler/Map.KeyboardShortcuts.ts
Fixes scrolling of compact mode toolbar after opening the menu - removed old hack wrt overflow.
-------------
user-list: hide follow chip when clicked on it
------------------
user-list: center name vertically, avatar ratio
- avoid resized avatar due to text padding
----------
remove-w2ui: use JSDialog dropdown for user list
- reuse JSDialog Dropdown
- remove hack with overflow which was needed to show
any popup above notebookbar
- fixes scrollbar visible above compact toolbar when
switching from notebookbar mode
=> Fix user list / compact mode scrollbar issues

browser/src/control/Control.JSDialogBuilder.js
* Resolves: #6960
When focus is in the notebookbar, arrow keys allow focus to be moved.
Change-Id: Iccc9122f77c224e0190f25732ff9e4a24e4eab3e
=> Arrow keys traverse focus around notebookbar

browser/src/docdispatcher.ts
- in the formulabar in Calc
- type "=" then click "accept formula"
=> Fix TypeError on accept formula button

browser/src/control/Control.NotebookbarCalc.js
Change-Id: I6d23bc3c1c4b080ade32a97dd8408149f49d160d
* Resolves: #8651
=> fix : Format -> Conditional Menu Button Not Working

browser/src/control/Control.NotebookbarImpress.js
Change-Id: I8b2824f6a17091d1a5202051cc95b6a53013f0cf
* Resolves: # 
=> fix : Present in the window button hides only for mobile apps

browser/.beforeprettier, browser/Makefile.am, browser/src/core/geometry.ts
Change-Id: Ic1819ff187edc9c0d33f77b3b82054cb8b27c6dc
* Resolves: # 
=> Add simple geometry classes.

net/Socket.cpp
Remove toErase list; instead null socket pointers earlier to make things more deterministic.
Simplify toErase path, by just removing null sockets.
Check _socketPoll array bounds to cope with a re-entrant mutation - imperfect; but the fd comparison will help.
Change-Id: I27d81358a7d80b939b50ce4ccb1b2178a091a360
* Resolves: # 
=> SocketPoll: better re-entrancy protection.

coolkitconfig.xcu, kit/Kit.cpp
- **kit: fix missing theme option**
- **config: fix font color value (Dark Theme)**
=> Font Color (Dark view)

browser/Makefile.am, browser/css/jsdialogs.css, browser/css/toolbar.css, browser/src/control/Control.MobileBottomBar.js, browser/src/control/Control.MobileSearchBar.ts, browser/src/control/Control.MobileTopBar.js, browser/src/control/Control.StatusBar.js, browser/src/control/Control.Toolbar.js, browser/src/control/Control.TopToolbar.js, browser/src/control/Control.UIManager.js, browser/src/control/Control.UserList.ts, browser/src/control/jsdialog/Component.Toolbar.ts
- base class for toolbars
- use ES6 classes not leaflet's objects
=> remove-w2ui: cleanup, create shared base class for toolbars

browser/src/control/Control.Header.ts, browser/src/core/geometry.ts, browser/src/docstate.js, browser/src/docstatefunctions.js, browser/src/layer/tile/AutoFillMarkerSection.ts, browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CanvasSectionContainer.ts, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/CommentSection.ts
Use SimpleRectangle for cell cursor.
Add .clone function to SimplePoint.
Use app.file.calc.cellCursor.visible for checking the cursor visibility instead of null variables. Replace map._cellCursorPixels with app.file.calc.cellCursor.rectangle Remove map._cellCursorXY with app.file.calc.cellCursor.address Replace map._validatedCellXY with SimplePoint.
Change-Id: I9b1e2c92e5029b2f184055083d35200bb5e6b8c9
* Resolves: # 
=> Use SimplePoint for cell address.

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml, browser/.eslintignore, browser/.prettierignore
Change-Id: Ia3ee3f6b508c5146df172cb07f4f515627ec75f1
* Resolves: # 
=> remove obsolete/removed files from CI check configs

kubernetes/helm/collabora-online/Chart.yaml
Change-Id: I8b739297ded85f4e24c61a88b4b16c46a3f96626
* Resolves: # 
=> Update Helm Chart with new release 23.05.10.1

cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/desktop/calc/clipboard_spec.js, cypress_test/integration_tests/desktop/writer/copy_paste_spec.js, cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js, cypress_test/integration_tests/desktop/writer/track_changes_spec.js, cypress_test/integration_tests/desktop/writer/undo_redo_spec.js
- cool#8648 clipboard: fix desktop/calc/clipboard_spec.js
- cool#8648 clipboard: fix desktop/writer/undo_redo_spec.js
- cool#8648 clipboard: fix desktop/writer/track_changes_spec.js
- cool#8648 clipboard: fix most of desktop/writer/top_toolbar_spec.js
=> cool#8648 clipboard: mechanical conversations

browser/src/control/jsdialog/Widget.TreeView.js, browser/src/map/handler/Map.StateChanges.js
problem:
zotero was not loading because element.text didn't exist on adding bibliography there was error to parse JSON, because there's some more data in string after JSON
Change-Id: If34791ae7ca79ca7fd304b506cd483e929f4d2ac
=> added check for undefined properties

browser/welcome/welcome.html
Change-Id: I01d62428ec98b051a7b131901bab3c346e7697d0
The numbers can be translated as well.
=> welcome window: allow to translate tab numbers

cypress_test/integration_tests/desktop/impress/table_operation_spec.js
Change-Id: Iccd348ca815d60336423c559732cd6b4e22b1176
* Resolves: # 
=> Fix failing test destkop/impress/table_operation_spec.js 'Delete row'

Makefile.am, android/lib/src/main/cpp/CMakeLists.txt.in, common/ConfigUtil.cpp, common/ConfigUtil.hpp, common/Crypto-stub.cpp, common/Crypto.cpp, common/Crypto.hpp, ios/Mobile.xcodeproj/project.pbxproj, tools/Config.cpp, wasm/Makefile.am, wsd/COOLWSD.cpp, wsd/ClientRequestDispatcher.cpp, wsd/DocumentBroker.cpp, wsd/FileServer.cpp
Change-Id: Iec477c223f2dc75e0be8b472c8439ca9311d6aae
=> wsd: Unconditionally compile support-key-enabled code paths

browser/.eslintrc, browser/src/control/Control.MobileBottomBar.js, browser/src/control/Control.Toolbar.js, browser/src/control/Control.UIManager.js, browser/src/control/Control.UserList.ts, browser/src/map/Clipboard.js
Change-Id: I2cb0f61d3b159c78e67d99f163b828f60cb0f5e2
=> eslint: introduce strict rules

browser/.eslintrc, browser/src/control/Control.MobileBottomBar.js, browser/src/control/Control.Toolbar.js, browser/src/control/Control.UIManager.js, browser/src/control/Control.UserList.ts, browser/src/map/Clipboard.js
It didn't work: prettier still used double quotes as a standard so it was not possible to pass make check
This reverts commit 7c5c5bd47bce5bd725eb8b4685bdd68fe7e43396.
=> Revert "eslint: introduce strict rules"

coolkitconfig.xcu
Change-Id: Ib7a368c1257d69ba57e13fdcec044855826a2cdd
(cherry picked from commit 67affdb956dedf35aa20a3fc3b2cb4277944d4d7)
* Resolves: # 
=> config: fix font color value (Dark Theme)

wsd/wopi/WopiStorage.cpp
Let the error detail the error origins.
Change-Id: I67a98dfe1001fd663af464ec5ec417330d0fbfb1
=> WopiStorage: turn err to warning logging for PutFile

browser/src/control/Control.PartsPreview.js, browser/src/control/Parts.js
- **browser: fix queue preview part duplicate**
- **browser: logging warning if empty rects**
- **browser: logging to check request preview parts**
- **browser: logging fetched preview parts**
=> logging preview parts

cypress_test/integration_tests/desktop/calc/autofilter_spec.js, cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js, cypress_test/integration_tests/desktop/calc/delete_objects_spec.js, cypress_test/integration_tests/desktop/calc/focus_spec.js, cypress_test/integration_tests/mobile/calc/apply_font_spec.js
- **cool#8648 clipboard: fix desktop/calc/focus_spec.js**
- **cool#8648 clipboard: fix desktop/calc/delete_objects_spec.js**
- **cool#8648 clipboard: fix desktop/calc/autofilter_spec.js**
- **cool#8648 clipboard: fix desktop/calc/cell_appearance_spec.js**
- **cool#8648 clipboard: fix mobile/calc/apply_font_spec.js**
=> cool#8648 clipboard: finish desktop tests, start mobile tests

browser/src/layer/tile/CalcTileLayer.js
Change-Id: I840cc711076e4473dee8b6a1b823a362e0eecd84
* Resolves: # 
=> Rename forgotten variable.

cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/desktop/calc/annotation_spec.js, cypress_test/integration_tests/desktop/impress/annotation_spec.js, cypress_test/integration_tests/desktop/writer/annotation_spec.js
=> Cypress: closeDocument improvements

browser/src/control/Control.UIManager.js, browser/src/core/Socket.js, browser/src/layer/tile/CanvasTileLayer.js
=> Forward port reconnection bug

kit/Kit.cpp
but impress/draw should continue to use the existing document preference. Writer and Calc have spell as a pre-view feature, while impress/draw still has it per document.
Change-Id: Ieb8c307b13f2ee010e09058a1ba63c7808637487
* Resolves: # 
=> on joining an existing session calc/writer can use new users spell pref

browser/src/layer/tile/CommentListSection.ts
=> Private/pedro/copy from pranams pr #7800 writer annotation scroll

browser/css/jsdialogs.css, browser/css/toolbar.css, browser/src/control/Control.StatusBar.js, browser/src/control/jsdialog/Widget.HTMLContent.ts, cypress_test/integration_tests/desktop/calc/statusbar_spec.js, cypress_test/integration_tests/multiuser/calc/invalidations_spec.js
statusbar: use ui-badge for items
Statusbar items which are not active previously were grey.
Recover that styling and do cleanup to not specify CSS in the
JS code.
------------------------------------------
statusbar: better strings formatting
After:
=> statusbar: improve formatting

browser/.beforeprettier, browser/Makefile.am, browser/src/control/Control.MobileTopBar.ts, scripts/unocommands.py
Change-Id: Ibced15ed3ebec2c7a7b07539f25270b19d615a1f
=> browser: Convert MobileTopBar.js to TypeScript

browser/.beforeprettier, browser/Makefile.am, browser/mocha_tests/CanvasSectionContainer.test.ts, browser/mocha_tests/helper/canvasContainerSetup.ts, browser/mocha_tests/refs/globals.ts, browser/src/core/geometry.ts, browser/src/docstate.js, browser/src/docstatefunctions.js, browser/src/layer/SplitPanesContext.ts, browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CanvasSectionContainer.ts, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/CellCursorSection.ts, browser/src/layer/tile/CommentSection.ts, cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
Change-Id: I43f9e744882c8d9158e07cc8f66a029c42f0a9fc
* Resolves: # 
=> Lat / Lng Removal

browser/src/layer/tile/CalcTileLayer.js, cypress_test/integration_tests/common/calc_helper.js, cypress_test/integration_tests/desktop/calc/annotation_spec.js, cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js, cypress_test/integration_tests/mobile/calc/sheet_operation_spec.js
a problem since:
commit 72b2ce4bb649aeb36182303783f064b0b5d5e35a
Author: Caolán McNamara <caolan.mcnamara@collabora.com>
Date:   Wed Oct 25 19:19:08 2023 +0100
we don't need to round-trip through core to reposition notes
Change-Id: If00ae17a8e80ca3f8d2a530efa6cdba90207be56
* Resolves: # 
=> if a sheet is removed or moved, re-request comment positions

browser/mocha_tests/CBounds.test.ts, browser/mocha_tests/CPointSet.test.ts, browser/mocha_tests/SheetGeometry.test.ts, browser/src/control/Control.ContextMenu.js, browser/src/geometry/Bounds.ts, browser/src/geometry/Point.ts
=> Insert comment from context menu

cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/mobile/calc/searchbar_spec.js, cypress_test/integration_tests/mobile/calc/spellchecking_spec.js, cypress_test/integration_tests/mobile/impress/delete_objects_spec.js, cypress_test/integration_tests/mobile/impress/impress_focus_spec.js, cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
- **cool#8648 clipboard: fix mobile/calc/searchbar_spec.js**
- **cool#8648 clipboard: fix mobile/calc/spellchecking_spec.js**
- **cool#8648 clipboard: fix mobile/impress/delete_objects_spec.js**
- **cool#8648 clipboard: fix mobile/impress/impress_focus_spec.js**
- **cool#8648 clipboard: fix mobile/impress/insertion_wizard_spec.js**
=> cool#8648 clipboard more mobile test fixes

cypress_test/integration_tests/mobile/impress/spellchecking_spec.js, cypress_test/integration_tests/mobile/writer/apply_font_spec.js, cypress_test/integration_tests/mobile/writer/delete_objects_spec.js, cypress_test/integration_tests/mobile/writer/insert_formatting_mark_spec.js, cypress_test/integration_tests/mobile/writer/insert_object_spec.js
- **cool#8648 clipboard: fix mobile/impress/spellchecking_spec.js**
- **cool#8648 clipboard: fix mobile/writer/apply_font_spec.js**
- **cool#8648 clipboard: fix mobile/writer/delete_objects_spec.js**
- **cool#8648 clipboard: fix mobile/writer/insert_formatting_mark_spec.js**
- **cool#8648 clipboard: fix mobile/impress/insertion_wizard_spec.js**
=> cool#8648 clipboard: more mobile test conversions

browser/src/control/Control.PartsPreview.js
The code is old and it is not used anymore by
new changes did it.
Change-Id: Id163cba7f586e3a083bff4cbb169a5d16e4b0cce
=> browser: preview: remove unused code

cypress_test/integration_tests/mobile/writer/table_properties_spec.js, cypress_test/integration_tests/mobile/writer/track_changes_spec.js
- **cool#8648 clipboard: fix mobile/writer/track_changes_spec.js**
- **cool#8648 clipboard: fix mobile/writer/table_properties_spec.js**
=> cool#8648 clipboard: fix remaining mobile tests

tools/map.cpp
Change-Id: I24c1bf9f103f3bf1325246a0223919ff1dbf62b4
* Resolves: # 
=> cid#360697 Ignoring number of bytes read

browser/src/control/Control.NotebookbarImpress.js
...and remove duplicate code.
Regression from c9ef8c3015d505208ddba6be7f2b665c6c32ef9e
Change-Id: Ib992d2c169d3e40f9cab670935696ab2899c639c
=> Browser: Duplicate Repair option in Impress tabbed bar

browser/html/cool.html.m4
This is a backport of #8844, with the same motivations. It fixes the last 2 blockers before mobile release!
* Resolves: # 
=> mobile: Use SavedUIState=true

browser/.beforeprettier, browser/Makefile.am, browser/css/selectionMarkers.css, browser/src/layer/tile/CanvasSectionProps.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/layer/tile/HTMLObjectSection.ts
Change-Id: I90719321781afcd29b72aa6d8eaafb186b4238dc
* Resolves: # 
=> Introduce HTMLObjectSection

common/JsonUtil.hpp, common/MessageQueue.cpp, common/Unit.cpp, common/Util.cpp, kit/ChildSession.cpp, kit/Kit.cpp, test/WopiTestServer.hpp, test/helpers.hpp, test/httpcrashtest.cpp, wsd/Auth.cpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/FileServer.cpp, wsd/FileServerUtil.cpp, wsd/SenderQueue.hpp, wsd/Storage.cpp, wsd/Storage.hpp, wsd/wopi/StorageConnectionManager.cpp, wsd/wopi/WopiProxy.cpp, wsd/wopi/WopiStorage.cpp
Change-Id: I976c5b8d6763cbbf0ee5cadfa2f7335ec719fe85
* Resolves: # 
=> killpoco: remove lots of redundant JSON headers.

cypress_test/integration_tests/desktop/writer/invalidations_spec.js, cypress_test/integration_tests/multiuser/calc/invalidations_spec.js, cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
which may kick in at an arbitrary point. We shouldn't invalidate if there is no change, but that's a TODO.
Change-Id: I910c96f2c2a0efab393ccea52c9f25d5804cd967
* Resolves: # 
=> do invalidation tests without spellchecking

browser/src/control/Control.NotebookbarImpress.js
...as in other tabbed bar JS files.
Change-Id: I29c43d9dc0ce4fa929e049e70171e0b8ab029088
=> browser: Add correct class to Share / See History buttons in Impress

browser/src/layer/marker/TextInput.js
Change-Id: If2ffdf4d561d34f3febc6c976e7427621c5cdf79
* Resolves: # 
=> Fix typo. Causes JS error.

browser/src/control/Control.PartsPreview.js, browser/src/control/Parts.js
Change-Id: I0d7c3877924544064bafc3ca93c887329b04a245
=> browser: preview: simplify 'updateAllPreviews'

browser/src/layer/tile/CommentListSection.ts
=> annotation: resize comment list section on view size change(backport)

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.Menubar.js, browser/src/control/Control.NotebookbarCalc.js, browser/src/layer/tile/CalcTileLayer.js, browser/src/layer/tile/CanvasTileLayer.js, browser/src/unocommands.js
Fixes #8066
Requires https://gerrit.libreoffice.org/c/core/+/166647
Change-Id: I2196e1a8e654a8afd20519b18f00cefafa048f2c
* Resolves: #8066
We now show / hide the grid in the spreadsheet.
Requires LOKit patch.
=> calc: Implement hiding the grid lines
