- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
when user hide or show multiple selected slide,
slides were actually hidden or shown but previews did not reflect that, only first selected preview was marked as performed action
Change-Id: Ie0c2eea8442feb0a4340551a63d8d39932adad3c
> impress: mark multiple slides as hidden or show

- common/JailUtil.cpp
- tools/mount.cpp
We now warn when we fail to use mknod
to create the random devices and have
stricter requirements to mounting
character-devices. Specifically,
we explicitly only allow mounting
the random devices.
Change-Id: Ib0dc300dedc40942ea52426af2b267f6a81fbeb8
> wsd: random device mounting

- browser/css/jsdialogs.css
i.e: theme dialog(format->theme)
Change-Id: I9a09d52cd2c0d95cfae18ae12995761985d8111d
* Resolves: # 
> jsdialog: fixed dialog content being cut off

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Toolbar.js
PDF export was avalaible only with a modal "pdf options" window. It seems a little complicated for some users who'd like to simply press the button and receive pdf.
Added a new menu item to download pdf directly.
Change-Id: Id824179adeac3b516e58c85a9e2d01838f81c892
* Resolves: # 
> Add new "download as" PDF option

- browser/src/control/Control.MobileTopBar.js
The new label added in a13f33b777b0ecc85752f832cd475736206f241e might
be a bit confusing and not necessary if the edit button (pencil) is
already present.
Better to:
* Have only the edit button (that should already be enough to signify
that the user is currently in a read-only transient mode)
* Add Read-only label for the cases were the user is opening a
read-only file (without permission to edit and thus the edit button is
absent)
Change-Id: I1fc5ca821bfd9feb75f411d2c3260a43d54e16cd
> Mobile: Add "Read-only" label ONLY when it's not possible to edit

- browser/src/control/Control.UIManager.js
- use encodeUri instead of encodeURIComponent because
it preserves those characters that are part of the URI
syntax
Change-Id: Ibde1b9ad40424b9bd2ce065cddfe2e83b23271c5
> fix missing icon 'Open in local editor' in compact mode

- browser/src/control/Control.StatusBar.js
Before this the read-only label was being added to the status bar even
if the user has writing access but is currently in that transient
read-only mode state (pencil icon is visible)
Don't show read-only label for those cases. We already have the pencil
icon/btn that signifies that.
Change-Id: I5295564244977388034c7a7930840cb45dfdd629
> Tablet: Add "Read-only" label only for users with no writing access

- coolkitconfig.xcu.in
Change-Id: I717ef1080fe3b9af39ed081eb79355d0e5bd6e4e
* Resolves: # 
> Disable CalcHiddenColRow by default

- browser/src/control/Control.JSDialogBuilder.js
when we open Writer -> Format -> Footnote field: Thickness shows an alert about incorrect value. It's caused because step is set to 1 but value is 0.5 as core uses step only for increase/decrease but not for valudation. Fix this annoying error by allowing to use 0.1 step.
> jsdialog: get precision for validation also from value

- browser/src/layer/marker/A11yTextInput.js
When text is unselected by clicking somewhere, selected text innside
the editable area was unselected, selected again, unselected again.
That was causing the screen reader to report such a nonsense sequence.
Change-Id: Ib9d6628f7ac30fe2cd40ee7823ac67eb6471d1f2
> A11yTextInput: improve screen reader on unselecting text

- browser/src/layer/tile/CanvasSectionContainer.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- kit/ChildSession.cpp
It used to be that scrolling in dark mode would show a white color while the tiles were loading - now shows the document background color.
Change-Id: Id4c3881e728ae18496bf276e8c565a7abc1de7b5
> Make writer page background match document color

- .github/workflows/helm-release.yml
- kubernetes/helm/README.md
* Resolves: #5371
This PR adds an Github-Actions, on every change of the `version:` in `Chart.yaml` it will:
1. bundle the helmchart to a `.tgz`
2. add an git-tag / github-release with `<helmchartname>-<version>`:
3. upload the bundle `.tgz` to the github-release
4. update the `index.yaml` in branch `gh-pages`:
- add the new helmchart release with url to the `tgz` on github-release
- so this index.yaml should be accessible under: https://collaboraonline.github.io/online/index.yaml
---
so everybody could use it as an helm-repository like:
```bash
helm repo add collabora https://collaboraonline.github.io/online/
helm install --create-namespace --namespace collabora collabora-online collabora/collabora-online -f my_values.yaml
```
TODO:
> feat: add helm-repo release ci (with usage of github-pages as helm repo)

- browser/src/control/Control.MobileBottomBar.js
Change-Id: I264d02b57a5e2c969ac9245cee2fa4be028e1c04
* Resolves: #6755
Fix wrong backcolor tooltip for mobile UI
> Fix : Wrong label 'BackColor' on mobile UI

- configure.ac
Omitting this space leads to the error "test: too many arguments"
Change-Id: Id8a83d77adfb484dcc949a10b4b25f6ad81130f8
When building Collabora online I noticed this error:
```
./configure: line 18286: test: too many arguments
configure: WARNING: lxml for python3 is needed. It might be in a package called python3-lxml. But
if you are building the JS bits on another (Linux) machine, that doesn't matter
checking for polib for python3... no
./configure: line 18286: test: too many arguments
configure: WARNING: polib for python3 is needed. It might be in a package called python3-polib. But
if you are building the JS bits on another (Linux) machine, that doesn't matter
```
It appears that a typo was made in this test command as a space was missing between a uname …
> configure.ac: Fix missing space in test command

- browser/css/device-mobile.css
- browser/css/jsdialogs.css
- browser/src/control/Control.FormulaBar.js
- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/jsdialog/Widget.FormulabarEdit.js
- browser/src/layer/marker/A11yTextInput.js
- browser/src/layer/marker/TextInput.js
- cypress_test/integration_tests/common/calc_helper.js
It converts formulabar's textarea into contenteditable div.
Input is handled by TextInput.js used for document
and already in the past for formulabar. Replaces
usage of keyevents which are not triggered with
eg. Japanese.
Fixes also #6737
Fixes on mobile #6767 requires: https://gerrit.libreoffice.org/c/core/+/153717
New widget consists of text layer with visible content
and cursor layer with selections and cursor. When clicked
it focuses TextInput.js field for typing.
> formulabar: handle Japanese input and fix mobile

- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/jsdialog/Widget.MultilineEdit.js
- browser/src/layer/marker/TextInput.js
it was already used on mobile so
disable "raw key events" and enable "text input".
this also requires core change:
https://gerrit.libreoffice.org/c/core/+/153718
fixes #6737
> formulabar: use IME also on desktop #6737

- browser/src/control/jsdialog/Widget.TreeView.js
entries are a tree structure so we need to iterate through it using a special function
this fixes eg. date filtering in autofilter
where checkboxes didn't work
> jsdialog: fix checkboxes in treeview

- browser/src/control/jsdialog/Widget.TreeView.js
entries are a tree structure so we need to iterate through it using a special function
this fixes eg. date filtering in autofilter
where checkboxes didn't work
> jsdialog: fix checkboxes in treeview (22.05)

- net/WebSocketHandler.hpp
If COOL is running in debug mode ther is a
check that incoming messages are UTF-8.
We skip this tests if the message refers
to an image pasted.
Change-Id: I4f7e4a647deb22ec2a032d4d6347d910184c0701
* Resolves: # 
> Avoid crash when pasting image in debug mode

- browser/src/control/Control.LanguageDialog.js
- browser/src/control/Toolbar.js
* Resolves: #6808
When a user selects a different language for the document using the More... dialog, the system does not apply the selection. This patch allows the system to send the LanguageStatus command even when the jsdialog is opened.
Change-Id: I7a1a39b31db59f1bc5f980d63f3040ffa9b311e5
> fix: language selection in More... dialog is not applied

- wsd/DocumentBroker.cpp
And tile::needsFetch on that result will always return true given the default of invalidFrom of 0 and the comparison of
return this.invalidFrom >= this.wireId || ...
so the tile return from the cache is unusable.
It is typical for a request not to have a wireId, if we don't use the cache then doRender will send a timecombine result with wireIds set. But if we use the cache here we send a response using the wireId of the request.
Change-Id: I586406af86b0f503dfc204e20120cc8acebf5b8e
* Resolves: # 
> On a cache hit for a tile the result typically had a wireId of 0

- browser/src/layer/tile/CanvasTileLayer.js
- common/Png.hpp
- kit/Delta.hpp
- kit/DummyLibreOfficeKit.cpp
- test/DeltaTests.cpp
so if core is compiled with a cairo using rgba the pixels can be sent without need to reorder in server or client
Change-Id: Iaf0410f1eaa605b9ce2716625f6c968bca523ccb
* Resolves: # 
> transport in rgba order

- browser/src/control/Control.NotebookbarWriter.js
Better to reorder these so we have higher probably to meet user's
expectations and fix the priority in which the elements are placed
- Move "Columns" (.uno:FormatColumns) to a higher priority place
- Demote "Title page" (.uno:TitlePageDialog) to a toolitem: This
Button is already present in the insert tab and so we don't need to
have it as a bigtoolitem here
- Move Hyphenate and LineNumbering to be right after breaks
Change-Id: I6cba0ad920e9ee9ec836f9e06e201f0ff9264f84
> Tabbed view: Writer: layout tab: Reorder elements

- common/RenderTiles.hpp
but they don't go through the delta mechanism, so move the assert to the delta path, the other path is ok wrt gt 256x256
Change-Id: I2ba4d8affb7645349540f3a5de31d1802f04c53d
* Resolves: # 
> impress slide previews are not 256x256 to triggers assert

- kit/Delta.hpp
=============== START DeltaTests::testRleComplex
../kit/Delta.hpp:98:23: runtime error: index 4 out of bounds for type 'const uint64_t[4]' (aka 'const unsigned long[4]')
#0 0x55d29dacd21b in DeltaGenerator::DeltaBitmapRow::PixIterator::next() libreoffice/online-san/test/../kit/Delta.hpp:98:23
#1 0x55d29da8d514 in DeltaTests::testRleComplex() libreoffice/online-san/test/DeltaTests.cpp:316:16
#2 0x55d29daf7a87 in void std::__invoke_impl<void, void (DeltaTests::*&)(), DeltaTests*&>(std::__invoke_memfun_deref, void (DeltaTests::*&)(), DeltaTests*&) /usr/bin/../lib64/gcc/x86_64-suse-linux/9/../../../../include/c++/9/bits/invoke.h:73:14
Change-Id: Ib6e13eaf0fb89ad086a99251d5b8edcdcedd6800
* Resolves: # 
> asan error seen in testRleComplex

- browser/src/control/Control.IdleHandler.ts
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
problem:
resolves: #5995
it was just annoying for user when he goes to some other tab or clicks somewhere, and the comment is saved automatically while they may want to still edit
also this solved another problem where in multiple users case, if another user switches tab comments were saved even if user was editing it
Change-Id: Iee32f21803d6a0dbc164bbf9a9bee803228aad7a
> annotation: avoid saving comments on losing focus

- kit/Delta.hpp
it shouldn't happen, but return early if it does
Change-Id: I1733d346ff370827fd882caacebca111f790bbe1
* Resolves: # 
> return failure early in case of oversized tiles

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
Change-Id: I4b34ae795465ecc402c5228478b7797298acc5a7
* Resolves: 
* Focus back to document when escape key pressed on any element in Notebookbar
* Exception: When drop down is already open then focus back to element.
> Focus back to document when Escape key pressed

- docker/from-packages/Dockerfile
- docker/from-packages/scripts/start-collabora-online.sh
The domain resolution problem from jails was properly solved by https://github.com/CollaboraOnline/online/commit/bc8da0cb339cc685f9a24c78e8a92aadcd690479 This hack is not necessary in docker.
Change-Id: I59664b895d187b2a8930a34b096305e0b7c384e3
> docker: remove obsolete fix

- browser/src/layer/tile/CanvasTileLayer.js
unlike TilesSection::oscCtxs which is
Change-Id: Iaad8dd61cd0e4432abcc50ca3ca71cdcb96a66db
* Resolves: # 
> TileSectionManager::_oscCtxs is unused

- browser/css/cool.css
- browser/src/layer/tile/ScrollSection.ts
Change-Id: I222d246148d5d84a5c0b3cfdb1890350f428e696
problem:
In safari and gnome web when you scroll using scroll bar,
DOM elements on the slidebar and documents would get selected
> scroll: avoid selecting elements while dragging scroll bar

- browser/src/core/Socket.js
-  hard to find exception if browser logs error at info level
Change-Id: I9f354480e1ee1d2da8a85973acd7b6563df83291
* Resolves: # 
> fix: info level log for exceptions

- browser/src/layer/tile/CanvasTileLayer.js
problem:
unselecting shape would make document jump to position where cursor was before selecting the shape
Change-Id: I4aa75932631de51e84e3aca9b439f1a9a945e2d3
> scroll: override any pending scroll for cursor following

- browser/css/iframedialog.css
- browser/src/control/Control.JSDialog.js
Make snackbar non-modal
Snackbar shoudn't block user interactions with other
UI components. This fixes regression introduced with
vex rework to JSDialogs where snackbar become modal.
This fixes problem with "send feedback" and "Zotero"
snackbars which block users for ~10s from editing.
------------
Center IFrameDialog using CSS
instead of using hardcoded pixel distance...
> snackbar: do not block users

- test/UnitQuarantine.cpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPILock.cpp
- test/UnitWOPISaveOnExit.cpp
- test/httpcrashtest.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
This PR resolves a number of corner-cases related to disconnecting and unloading sessions.
Details in the commit logs.
- wsd: better session disconnection logic
- wsd: always-save-on-exit skips uploading as-loaded docs
- wsd: better modification detection after saving
- wsd: better data-loss detection
- wsd: test: new UnitWopiLockReadOnly test
- wsd: better detection of upload skipping for save-on-exit
- wsd: better always-save-on-exit handling
- wsd: test: enable testCrashForkit
- wsd: save and upload rapidly when unloading
> Disconnecting with Read-Only Session

- browser/src/layer/tile/CommentSection.ts
after commit 51d19dd60e268ddf0a087c38dc3ad8290f4ac4c2 annotation: avoid saving comments on losing focus
We had regression causing collapsed comment to be completly hidden if user first opened 'modify mode' and clicked outside comment area. Then comment was collapsed but when selected again - content wasn't shown.
This commits makes us sure that when we select comment it has visible content.
> comments: fix hidden comment after lost focus in modification

- net/WebSocketHandler.hpp
- wsd/ClientSession.cpp
Revert "Avoid crash when pasting image in debug mode" This reverts commit 78558fe9af361dd0238bd3021c67e9d431dcf981.
Instead of detecting paste command and not trigerring assertion: fix frame type so it will be binary in case of paste.
> Fix pasting image assertion

- browser/src/control/Control.Menubar.js
Before this commit this option was only available on tabbed view
Change-Id: I6e027f1b84d09e802f7ea6c6fd9e5144cae2eb91
> Compact view: Add missing InsertObjectStarMath (formula object)

- browser/src/dom/NotebookbarAccessibility.js
Change-Id: I9ab9e004e9dc883d18b8f750a9a400e1f318240e
* Resolves: 
Enter key will not be necessary to change tab by accessibility key
> Enter shouldn't be a requirement to trigger a tab or a button

- browser/src/control/Control.FormulaBar.js
problem:
regression from 919db16
when address input has focus and keyboard is open, tapping on sheet would not close keyboard and bring focus back to map only way to close keyboard and focus map was to accept the input
Change-Id: I2c6f23be9efcbbe8e4d47d11505074a75abc000f
> calc: blur address bar when tapped on sheet

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/layer/tile/CanvasSectionContainer.ts
With c04c065edcfe9e00e4f7e50834e6317caaceb9ea we start to dynamically
set the canvas background. The problem is that for Calc cells do not
have intrinsically a background and thus what we end up to see as the
document background color is actually the canvas color.
- Make sure that when we are in presence of calc we set the
canvas color (clearColor) with the value coming from
documentBackgroundColor
- To make it clear: create a new CSS variable to be used as
background-document
Change-Id: I4c456e4aeea233609ee58684d967984dd8afd63a
> Calc: fix document background. It should be white.

- browser/src/control/Control.JSDialog.js
when any dialog is shown we block executing uno commands don't count snackbar as a dialog and allow full interaction of the user when snackbar is shown
> jsdialog: don't block uno commands when snackbar is shown

- browser/css/cool.css
- browser/src/control/Control.IdleHandler.ts
- browser/src/control/Control.UIManager.js
- browser/src/map/Clipboard.js
Large Clipboard  and document idle modals were being set with tabindex
0 allowing for manual user focus plus were being focused dynamically
for each instance:
- Transfer all that (just once) to showinfomodal instead for the
cases where we have buttons
- This in turn sets the things to the parent (dialog itself)
and not the subcontianer
- Set tabIndex with negative value so, it only allows focus via
code
- This fixes the weird outline (focus) that sometimes would appear
on sub containers of that dialog instances
Change-Id: If40192e05c4b0e25e2ce71bc612ab64fc54a29ec
> Don't add outline to ShowInfoModal that have no buttons

- kit/Kit.cpp
When all users idle their activities
for at least 10 seconds, we take the
opportunity to trim the memory footprint.
We are careful not to issue a subsequent
trimming too soon. A minimum of 30 seconds
needs to pass to trim again. This should
give a decent balance between performance
and reduced memory footprint.
Change-Id: I1c8b2c4a265c9aa0ac5033762695706ad970f11e
> wsd: trim memory on idling

- browser/src/layer/tile/CanvasTileLayer.js
While scrolling using scrollbar we tried to prefetch lots of tiles adjacent to the view.
Introduce timer which will protect us from prefetching tiles we will not need when scrolling is fast.
We will avoid doing it synchronously on every little step.
_update is called a lot in onMouseMove handler:
_update (CanvasTileLayer.js:6220)
...
panBy (Map.PanAnimation.js:51)
scroll (Scroll.js:11)
ScrollSection.scrollVerticalWithOffset (ScrollSection.ts:657) ScrollSection.onMouseMove (ScrollSection.ts:776)
CanvasSectionContainer.propagateOnMouseMove (CanvasSectionContainer.ts:1097) CanvasSectionContainer.onMouseMove (CanvasSectionContainer.ts:1403)
> Adjacent tiles prefetching with delay

- browser/css/toolbar.css
If we set the initial backgrounds without `!important` then there is
no need to use `!important` for dark-mode (since we are already using
a more specific targe via data-them attribute)
Change-Id: I600629dfc0485edac6ff725f6278de1501e1c9a7
> refactor: Toolbar down icons: remove unnecessary !important rule

- kit/Kit.cpp
In calc and impress we send different data depending on the view in status: message which is triggered by LOK_CALLBACK_DOCUMENT_SIZE_CHANGED. Every view can be on a different part / sheet / slide where document size can be also independent.
This helps to reduce status: messages sent to other view when switching sheets in other view.
> LOK_CALLBACK_DOCUMENT_SIZE_CHANGED is different per view

- browser/src/control/Control.PartsPreview.js
This fixes the problem when we requested a preview but server didn't answer. This can happen when we have
nviewid mismatch and error is generated in logs:
ERR  Session is not found. Maybe exited after rendering request.
> Mark slide preview as fetched when it arrives

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.FormulabarEdit.js
in some browser scrollIntoView causes problem without parameters in this particular case problem was entire view being pushed upwords out of view reproducing steps:
Open a spreadsheet in two views,
With 1st view, navigate to bottom right corner via Ctrl+⬇ and Ctrl+➡, With 1st view, type something in that cell, and then the cell above (stay editing the cell, don't press Enter), With 2nd view, start typing in A1.
2nd view's editing view is pushed upwards
Change-Id: I4bc551de321483608eb210718c1d81a622de5a6d
* Resolves: # 
> formulabar: fixed scrollIntoView caused problems

- kit/Kit.cpp
This would have only a small impact on memory use, and a large impact on interactivity, performance and bandwidth use. So lets not do that.
Change-Id: I07b2538cd4f5cd2c91926cfabeaa159dd992b068
* Resolves: # 
> deltas: don't drop delta cache on 10 seconds idleness.

- tools/Config.cpp
tools/Config.cpp: In member function 'virtual int Config::main(const std::vector<std::basic_string<char> >&)': tools/Config.cpp:480:18: error: ignoring return value of 'int chown(const char*, __uid_t, __gid_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
480 |             chown(proofKeyPath.c_str(), pwd->pw_uid, -1);
|             ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
From fc946198d39da83e829eed4c852f904631f45e0f
Change-Id: Iaa4db6fb4dc6f742779754d4e05708aa8f41ebd6
> config: Fix 'warn_unused_result' during build

- browser/html/cool.html.m4
- wsd/FileServer.cpp
problem:
till now we used values from DOM elements which were unreliable, sometimes they are not discoverable due to nested iframs. That threw some 404 due to incorrect theming path.
Change-Id: Ibc291ce9f64db799095e1edcb14c598bdd085de7
> theme: use integration theme value from the interation message

- browser/src/layer/tile/CanvasTileLayer.js
Fixes type error on switching sheets in Calc:
1. Open Calc spreadsheet with 2 sheets and 2 user sessions
2. Switch user A to sheet 1
3. Switch with user B to sheet 2 and select few cells
4. close user B browser / tab
5. switch user A to sheet 2
> Remove view selection on user disconnection

- browser/js/global.js
On actual iPad (2048x1536 native, 1024x768 browser), in landscape view in Safari, mobile phone view is shown in online instead of tablet.
This reverts commit f1e9ee72fe48d21ac7a78b7702055b91ba8f3ba9.
Change-Id: I2cd4ba6cdcd616760c06c7db479e6d13be3d83b4
* Resolves: # 
> Revert "Fix wrong device detection logic."

- browser/src/control/Control.ColumnGroup.ts
- browser/src/control/Control.GroupBase.ts
- browser/src/control/Control.RowGroup.ts
Introduce getTailsGroupRect method which will be different in every implementation but share findTailsGroup logic using above function.
This fixes code duplication detected by: https://github.com/CollaboraOnline/online/pull/6802
> Share code for findTailsGroup

- browser/src/control/Control.UIManager.js
Do not wrongly switch part of the UI to edit mode when on read-only
mode. Best to be only remove readonly css class when it's not needed as
opposed to removed it whenever refreshNotebookbar() is called.
- We were showing tabs in wrong mode (readonly mode) -> every-time
refreshNotebookbar() was called. Thus, initial tablet mode was
appearing with icons and actions from edit mode.
Change-Id: I6ad9c8c14e60d4c3513f63b75717db0a124b73ea
> Tablet: Non-functional sidebar button shown in read-only mode

- net/WebSocketHandler.hpp
- wsd/DocumentBroker.cpp
We don't want to dump the whole paste buffer as hex, or indeed any large mis-encoded string - instead crop to the problematic section for easier debugging, and no performance hit.
Change-Id: I30518beea436895a42b3429c3cb6e16e2093cca9
* Resolves: # 
> paste: cleanup excessive debugging.

- browser/src/layer/tile/CalcTileLayer.js
and so this loop never finds anything, the intent is clearly to find an existing comment in this cell so use the right field for that.
possibly a problem since:
commit 922ae4924ad36b501eff187b57aa940bb1a02d9a
Date:   Wed Jan 26 15:08:31 2022 +0300
calc: Fix new comments do not check tabid on insert
Change-Id: I11208493ef7eae6a01576d90129b25ed9f792d62
* Resolves: # 
> calc insert comment checks undefined tab field

- kit/Delta.hpp
- test/DeltaTests.cpp
Simplified code:
+ re-use the bit mask as an inner loop counter.
+ turn alpha only rows into zero length with agreed lastPix.
+ keep lastPix around on the stack.
+ handle odd widths in a duplicate slow-path
Change-Id: Ibc7630f7187ea5f4904c6fed14dda28cdfbf7523
rle: further optimize the pixel reading & de-compression.
Change-Id: Ifcaaa45d1de6532b3fd43015c47a37daf56c2ea5
* Resolves: # 
> rle: optimize inner loop bit-bashing.

- browser/src/layer/tile/CanvasTileLayer.js
When Collabora Online is inside iframe and we load Calc spreadsheet, after few seconds we receive CellCursor message. In case when user was typing outside iframe in some textbox - we were stealing focus, what caused that user started to type inside spreadsheet.
> Don't steal focus from outside iframe on load Calc

- browser/src/control/Control.Menubar.js
Change-Id: Ic15fb1723bff6861b1fc115ef161cf6caa1b70af
* Resolves: #6995
Add `Hide menu bar` in `View` menu for the compact view
> feat: Add hide menu bar entry in compact view

- browser/css/jsdialogs.css
Fixes the ui-treeview's limited occupied vertical space in writer. 
Change-Id: I8551242fc2b987f00c67088caa0ed07ee8526a72
* Resolves: #6977 
As there are 3 hidden grids, changing their individual heights did not change anything so I forced change the height of ui-treeview.
> Fix to issue #6977

- browser/src/control/Control.UIManager.js
Change-Id: I103461b02405bc03d63671b885a31735668d4111
* Resolves: #
Added tablet check for Insert buttons to display on dom or not based on passed condition .
- By default custom buttons will show up in tablet.
> Add check for Insert_buttons to display in tablet view

- browser/src/layer/tile/CanvasTileLayer.js
Unfortunately, we cannot show the hyperlink pop-up,
in client side based on cell formula, because the formula
had not been evaluated.
=HYPERLINK(A1,A1);
The server should fire event "hyperlinkclicked".
Change-Id: Ie2b743812493e1790b9e54f0050974c585e61e00
> browser: remove hyperlink pop-up

- test/TileCacheTests.cpp
sometimes the deltas arrive in a different order, later in the same test we have "ordering is undefined tiles arrive in so swap if needed" for a pair of later deltas, so do the same reordering for this intermittently failing earlier test
Change-Id: If51edb9a4e22d469d9e029c38da7348c34b17832
* Resolves: # 
> occasionally testTileSubscription fails

- browser/src/layer/tile/CanvasTileLayer.js
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/protocol.txt
Change-Id: I383542b6c9c3a888937e2f7e330ec7e77efaaa82
* Resolves: # 
> allow tileprocessed to accept multiple comma-seperated tileids 

- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
- browser/src/layer/tile/CanvasTileLayer.js
- common/Session.hpp
- kit/Kit.cpp
- test/TileCacheTests.cpp
- test/UnitWOPIWatermark.cpp
- test/httpwstest.cpp
Resolves issue where presentations would not load all at once. Along with https://gerrit.libreoffice.org/c/core/+/154940, the dark mode related Draw bugs should be fixed.
> Draw dark mode fixes

- browser/admin/adminClusterOverview.html
- browser/admin/src/AdminClusterOverview.js
- Graph axis text is too small (10px) better to set it to 1em based on
parent div (16px). Good to also set any group within svg to 1em to
avoid any surprises
- Currently tablets from one card is spilling over to the next card
when there is not enough space. Better to allow scrolling.
- The left pane should be hidden even before reaching the mobile
size. This will fix the lack of space for cards and avoid everything
being so small
Change-Id: I58c88385875469b56542703663e570ab4d63fbdc
> admin: imprv ui sizes of adminClusterOverview.html

- browser/src/control/Control.JSDialogBuilder.js
Change-Id: I0ebe938080fa0e6865d4bf18e5dd33b0eb6a1567
> Screen reader doesn't properly report tab names in Tab View UI

- browser/src/control/Control.UIManager.js
Change-Id: I18908150ee537bfe7dd36b0b94f8baa11d2739ea
* Resolves: # 
Before it was showing custome buttons even if tablet flag is false. but now we will only insert button if conditon matches 
Patch for this PR : https://github.com/CollaboraOnline/online/pull/7005
> Remove open_local_editor button in tablet view

- wsd/ContentSecurityPolicy.hpp
- wsd/FileServer.cpp
We need to allow loading media sources from
the web-server URL. This seems to be necessary
at least on iOS.
Change-Id: Ic7b23c4f80b975460de9311a67f3c5cb51758d14
> wsd: add the web-server URL to the media-src list

- browser/src/layer/tile/AutoFillMarkerSection.ts
so the autofill handle in hidpi didn't work
Change-Id: I718d9a8d3954a441705849eba174fe6b5b2983c4
* Resolves: # 
> autofill onMouseDown doesn't generate working event position for hidpi

- browser/css/jsdialogs.css
These changes provide a decent padding to both the label and text area, with having no changes caused in the sidebar. 
Change-Id: I53494733c47b35d59133979c456665b4174e393c
* Resolves: #7037
> FIX: JSDialog: label vs textarea vs input field inconsistent paddings

- cypress_test/integration_tests/desktop/impress/sidebar_spec.js
- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
this was changed in the core:
commit 0a549b2c9595cd076e3b503b67df93bff380885a
svg: export text decoration for text run not paragraph
> cypress: fix svg text-decoration detection

- browser/src/control/Control.DocumentNameInput.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
Change-Id: Iec25de88aa3e7089af102dd9f4bda6507308c215
Related: [#6989](https://github.com/CollaboraOnline/online/pull/6989)
Add button to notebookbar and menubar to rename document.
* Resolves: # 
> Add rename document to notebookbar and menubar

- browser/src/control/Control.JSDialogBuilder.js
When button is inserted using postmessage API
it can have no command property. Prevent us from
TypeError here.
> jsdialog: fix error on insert_button

- browser/src/map/handler/Map.SlideShow.js
Full screen feature is not available on iPhone,
only on iPad with iOS 12+ (https://caniuse.com/fullscreen).
Instead open svg directly in the browser as a fallback.
> Don't show presentation on iOS in small frame

- browser/src/control/Control.JSDialog.js
Block only close requests from the user clicking on 'X' button. We need to always process close messages from the server.
Eg. Format -> Theme, click Add:
then close parent dialog using 'x' -> should not work then close parent using 'cancel' button -> should exit dialog
test together with: https://gerrit.libreoffice.org/c/core/+/155715
> jsdialog: always execute close message from server

- browser/css/device-mobile.css
- browser/css/mobilewizard.css
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.MobileWizard.js
- browser/src/control/Control.PartsPreview.js
- browser/src/layer/tile/ImpressTileLayer.js
- to show previews we use slide-sorter element and presentation-controls-wrapper as container
Change-Id: Iaed0892779d5016a565d556955305317129edea4
> impress: remove unused mobile-slide-sorter

- android/lib/src/main/cpp/androidapp.cpp
- It exits LOActivity when lokit thread finishes using lokit_main_mutex. But if we edit document and exit without saving lokit thread gets finished but COOLWSD is still running to clean up the docBrokers. It takes some time to clean up this docBrokers. We need to exit the LOActivity only after COOLWSD is finished
- for that I have added coolwsdRunningMutex again - it was removed in ad32888d7c2ec960255d826c245f7df2e93c3f1b
Change-Id: Ic9785f5aa55deafbac98efc4013bd3376d0ba62d
> android: fix app crashes after closing the document

- browser/css/jsdialogs.css
Without it in calc -> insert -> chart treeview
for chart type selection was invisible / 0px width
> jsdialog: add minimal size for treeview

- browser/src/map/handler/Map.SlideShow.js
On entering full screen the normal browser window goes "idle" on losing focus. When the full screen presentation exits no "focus" events gets sent to the normal window so clicking "presentation" again doesn't do anything as idle inhibits anything getting actually sent to the server.
in:
commit 5f655a7555cd836933dc14395495561f5f8cd04e
Date:   Tue Oct 13 19:26:16 2015 +0300
loleaflet: print handler tdf#94607
a similar _map.focus() is done after a similar L.DomUtil.remove()
and doing there same here gets this case to work.
Change-Id: Iae44ba949af2a64bf669b9d5f1113c647a354af1
* Resolves: # 
> cool#7102 fix 2nd presentation under chrome not appearing

- scripts/unocommands.py
Otherwise eg. non-ASCII shortcuts appearing in files can cause failures like this.
Traceback (most recent call last):
File ".../rpmbuild/BUILD/coolwsd-23.05.2.2snapshot/scripts/unocommands.py", line 454, in <module>
toolbarCommands = extractToolbarCommands(onlineDir)
File ".../rpmbuild/BUILD/coolwsd-23.05.2.2snapshot/scripts/unocommands.py", line 163, in extractToolbarCommands
for line in f:
File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
Encountered after 1a2500c8d31f12a8e23c648a0afb208e3d09bb05.
This is not ASCII in browser/src/control/Control.NotebookbarWriter.js:
`'accessibility': { focusBack: true,     combination: 'AI',      de: 'ÖI' }
Change-Id: I72aac2809530c14b9440f73e5072db17770f438a
> unocommands.py: Treat JS/TS files as UTF-8

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.UIManager.js
Change-Id: I89100d703444e8bfe2a8960d00c62a1e1ea88a84
* Resolves: #7094 
- Added missing dark mode icon  with checkmark.
> Add missing dark mode toggle in mobile view

- browser/src/control/Control.MobileWizardWindow.js
- it was only affecting wizard with tabs
Change-Id: I6172a3a1a498982927e63676c4743be8f2ff9d80
> fix: empty mobile wizard when opened for the first time

- browser/src/control/Control.TopToolbar.js
- browser/src/control/Control.UIManager.js
Change-Id: I05011bf9ffec99af8558c7af06dce5e350511f7c
* Resolves: #3751 
Add tooltip (Show Menu / Hide Menu) to the up/down chevron button (compact view)
> feat: Add tooltip to hide menu button (compact view)

- configure.ac
- Previously giving --with-lo-path as a relative path caused collabora online to crash with "component context fails to supply singleton" errors
- This patch uses readlink on the with-lo-path option, expanding it into its full canonical path
- I could probably have gotten away with realpath, but for consistency with --with-lokit-path I decided to use readlink -f
Change-Id: I16aacddbda9749451578fb7aded6c3c4e145ee26
Fixes #7041 
> Fix failed starts when core is at a relative path

- browser/src/control/Control.JSDialogBuilder.js
vertical tabcontrol has "vertical: true" property
for now just handle it as normal tab control,
it doesn't use tabpages but regular grids for
tab contents
> jsdialog: handle vertical tabcontrol

- browser/css/jsdialogs.css
A regression in #7011 caused the manage changes dialog to continue expanding when new elements were added, no matter how big it got. This would cause you to be unable to see all the changes when there were a lot of them because you could not scroll through the list. This patch fixes the scrolling, without making the list area very small again.
Change-Id: Ib29fb161522773ea9893b7bc21d06aab19b74c52
> Fix 'manage changes' dialog expanding infinitely

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
This way we increase status bar discoverability ( fixes #7098 ) and
group both search functionality in one place in the home tab
Change-Id: Ia1fa8fe58903088aad37a560edd033a184d35e0e
> Notebookbar: introduce simple search button

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/desktop/writer/file_properties_spec.js
this is regression from commit:
f8e53bd851a267fd50f369a1beb3c398d46f620a
Assign tab ids while defining tabs.
When opened Format -> Page Style dialog in Writer. There was "123" label next to the tabs.
Also when switching between widgets using tab key
it was moving focus outside window.
Core is sending id as plain number what is easy to duplicate. Let's add some unique name.
> Fix regression in tab cycle in dialogs

- common/Log.hpp
- common/Util.hpp
- wsd/TileDesc.hpp
perf reported 6.58% of time in collaborative multi user test on 2023-08-24 was spent in TileDesc::parse and much of that in std::unordered_map.
There are only 12 arguments in the map we care about here so we can just used a sorted array, look by name on write, and read by index.
Change-Id: Iadfc2001e298d8f4d46200c8488f0eb4cd8734c2
* Resolves: # 
> reduce cost of TileDesc::parse

- browser/src/map/handler/Map.Keyboard.js
* Resolves: #7062
JSdialog popups on Impress would have the keydown events not captured. The events would be handled by the main document.
Now they will be captured by the correct element.
Change-Id: I543e25ddbcb1766cc677f7fbc6629e8d04a5b394
> Make jsdialogs capture keydown events in Impress

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
* Resolves: # 
Adds support to trigger the Theme dialog in menu bar and notbeook bar in Calc, then also Impress and Draw.
> Support for Theme dialog in Calc, Draw, Impress

- browser/src/control/Control.Command.js
- configure.ac
- wsd/COOLWSD.cpp
- regression from ec17f72fb516e8b68fac669f9bd0a28c1264f9a3
- also removed the restriction to have "static" in unlock_image url
Change-Id: Ie4f1170fb6a12db5218fb28f21d78f88ebc61d56
> feature_lock: fix unlock_image option not working

- wsd/ClientSession.cpp
wsd/ClientSession.cpp:520:32: error: implicit conversion from 'uint64_t' (aka 'unsigned long') to 'double' changes value from 18446744073709551 to 18446744073709552 [-Werror,-Wimplicit-const-int-float-conversion]
(counter < (uint64_t)(std::numeric_limits<uint64_t>::max() / 1000)))
~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Which is a problem since commit e0b70657fa3575f1a85e020869d10f171dc079e0
(cid#318912 Result is not floating-point, 2023-08-23).
Let's make the conversion explicit, hoping that makes both Coverity and
clang happy at the same time. No change in actual behavior intended.
Change-Id: Ib9727f0df4df65a9504d421654d519bee0733b80
> wsd: fix -Werror,-Wimplicit-const-int-float-conversion

- browser/src/control/jsdialog/Widget.TreeView.js
dblclick seems not to work on ios, but click does. We can simulate dblclick with single clicks.
Change-Id: Ic9ae58a39122025c9947294ebfd2292ffe04ae5c
* Resolves: # 
> ios: fix doubleclick in navi, with single clicks

- browser/src/dom/NotebookbarAccessibility.js
This fixes regression introduced in commit 2ac7183e44e16a2a6956665d2d461c0873d62d95
Add Left or right arrow on a tab label should switch tabs
When we are in writer: Alt + H, K - opens spacing dropdown
Before this patch focus was stolen by the map even if the spacing item has focusBack property set to false
> a11y: don't focus map if focusBack is false

- browser/css/mobilewizard.css
- also fixes the misalignment in cool-annotation-table
Change-Id: I58db4c6918c3a36a230c6f9317ddf39c3361bb24
Before:
After:
> mobile-wizard: fix textarea remains white in darkmode

- browser/src/control/Control.JSDialogBuilder.js
Fixes case when:
1. in calc, right click column header, open column width
2. set 1.7, ok
3. open column width dialog again
4. try to set 1.62, ok
Result: there was validation error, cannot close dialog
> jsdialog spinfield validation (22.05)

- test/UnitWOPIFailUpload.cpp
- wsd/ClientSession.cpp
Read only sessions cannot modify the document, so
we shouldn't consider input from such a session
as potentially modifying the document. This
becomes important during an abrupt disconnection
where we look at isPossiblyModified() as an
indicator for data-loss.
New unit-test that reproduces the corner-case
with disconnection. With graceful unloading
a previous unit-test verified that it worked
as expected.
Change-Id: Id84cda4f4599c559018247c32ea1205e154e4984
> wsd: exclude readonly sessions from modification indication

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarWriter.js
It seems the CSS class was only added to impress in
c582d75f5744b7fb8d3ebbabbc7bd647793c0294
Change-Id: I4e8884004bbd1a4f6e4e62a841eb940e23065f50
> Tabbed view: Remotelink: Add missing CSS class

- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
- browser/src/layer/tile/CanvasTileLayer.js
- common/Session.hpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- test/TileCacheTests.cpp
- test/UnitWOPIWatermark.cpp
- test/httpwstest.cpp
- wsd/ClientSession.cpp
@caolanm @mmeeks 
Following up on #7170
I'll summarize the issue as I understand it.
The issue is that when the client gets created, it doesn't have a canonical id yet, because the view options haven't been made clear from the browser side yet. The browser side loads, then sends an uno command to set the theme, and that triggers a canonicalidchange and that's what gives the first canonicalid to the client. However during that whole exchange, the client sometimes sends some tile/tilecombined requests. Since there's no canonical id yet, that would result in buggy behavior.
I reverted my old two patches that would send a canonical id with the tile/tilecombine command, as Michael pointed out that was a bad idea. Instead I added a couple asserts that should trigger if we ever receive a …
> CanonicalViewId fixes

- browser/src/core/Socket.js
and not just some of them discarding the others, so we always apply all messages received in order the arrived without omissions.
TODO: apply them when the conditions application requires become true rather than depending on a timer poll.
Change-Id: I265b6ccb45e211c15c5f4daf9d6572fa051b68eb
* Resolves: # 
> if we can't call _onMessage yet, delay all messages until we can

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
Change-Id: I7476aa13ad5d77cbc888339fb0ccd2d485b8f274
* Resolves: # 
> Writer: Set parent / child relationship in UI.

- cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js
- cypress_test/integration_tests/mobile/impress/slide_properties_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
this is only desktop test that fails, let's skip
it until we fix the regression and not block others from testing their patches
regression was introduces in:
commit 04ac02b0339008382dcf640899ea18513de5a4a5
Do not request tiles until we are sure a canonical id is set
> cypress: skip failing switching sheet test

- common/Util.cpp
- common/Util.hpp
- kit/ChildSession.cpp
Old format:
kit-27634-02839 2023-08-30 11:08:43.590564 +0000 [ kitbroker_17a ] SIG   Fatal signal received: SIGSEGV code: 1 for address: 0x4f00000007
unoCommand(2552f) : ToolbarMode?Mode:string=notebookbar_online.ui - Wed, 30 Aug 2023 11:08:31
New format:
kit-30199-30197 2023-09-06 14:30:21.417817 +0200 [ kitbroker_001 ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x3e8000075f7
Recent activity:
unoCommand(064) : ToolbarMode?Mode:string=notebookbar_online.ui - 2023-09-06 12:29:56
Change-Id: Idf62ea18c75c453d188d8c25723a43824d5fc147
> kit: improve date format of UNO commands in crashreports

- browser/src/layer/marker/A11yTextInput.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/writer/editable_area_spec.js
In order to allow screen reader to track caret navigation properly
even if there is some connection delay default behaviour for
Left/Right arrow key press is no more prevented in
Map.Keyboard._handleKeyEvent. In TextInput._onKeyDown, it has been
needed to handle some special caret position, such as when cursor is
at begin or end of a list item prefix.
When left/right arrow is pressed and text is selected, selection is
cleared and caret needs to be moved by one char left/right.
However, for an editable div the behaviour is different:
- when left arrow is pressed caret moves at start of previously
selected text
- when right arrow is pressed caret moves at end of previously
selected text
So we needed to prevent default behaviour and simulate the same
behaviour that occurs in LibreOffice. …
> a11y: improved screen reader caret tracking on text navigation

- browser/src/control/Control.NotebookbarBuilder.js
this fixes missing font name and font size comboboxes when opened spreadsheet protected from editing
> jsdialog: create also combobox without entries

- browser/images/dark/fold.svg
Change-Id: I650a9adcdbbd768017d4ba0e17277de562e7d184
added fold svg icon which was missing for dark mode
* Resolves: # 
> Missing icon for show menubar

- browser/src/control/Control.Tabs.js
Change-Id: I5139e0072caabd7db7c4d1255b497cf24e1359e6
Fix extra padding for sheets tab on mobile view
* Resolves: # 
> Calc: Sheet tab context menu: Rename Sheet has extra padding

- browser/js/global.js
- browser/src/layer/marker/TextInput.js
The problem affects no-a11y case since the editable area is empty.
Since no copy/cut event is emitted, Clipboard.copy/cut is never
invoked. So we need to emit it manually.
To be honest it seems a Firefox bug. We need to check if they fix it
in later version.
Change-Id: I036414b5ffb5b35ff1ef1d7de1044e890832c673
> Firefox 117 no copy event is emitted by hitting CTRL+C with no selection

- wsd/ClientSession.cpp
This fixes a regression where PDF comments were lost when
the document closed immediately after adding a comment.
Change-Id: Iac78ec13fdbaa7d1ffe25067ea0f41704abb3312
> wsd: comments can be added to PDF files which otherwise are readonly

- scripts/run-wsdunit
And also allow automatic re-trying to decide if this is a reproducible
failure or an unstable test.
Change-Id: I254d83cc1acc6b80ec3978e26e5fd64e676ff2a9
> scripts: add a simple script to invoke a single unit test

- coolwsd.xml.in
- wsd/COOLWSD.cpp
- This allows you to, say, have a docker container and --restart=always
to restart when you update the config
- This patch only listens for "/etc/coolwsd/coolwsd.xml", so if you
specify a config file that isn't there then you're out of luck... An
improvement for a followup patch will be make it listen to wherever
your config files actually are
- This patch doesn't work when editing /etc/coolwsd/coolwsd.xml with vim
as vim moves the file before writing a new file in the right place.
Again, this may be a fix for a followup patch. The current docker
scripts only listen for modifications, so this matches that behavior
- This patch adds an option to enable this feature, it is off by default
> Stop coolwsd when /etc/coolwsd/coolwsd.xml changes

- man/coolwsd.1
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
Change-Id: I75762ad620132037523fa82167a3ff17075c7027
Currently [in docker it is possible to do configuration through
environment variables](https://col.la/dockercodeconfigviaenv), which
works using the start-collabora-online.sh start-collabora-online.pl
scripts. This PR lets COOLWSD listen to the same environment
variables directly
> Add cli option to use settings from env variables

- test/UnitBadDocLoad.cpp
commit	413e7a2e6f0c363938a0a5ee5bd6eb5d56d5a8d8
lok: add broken package interaction handler
https://cgit.freedesktop.org/libreoffice/core/commit/?h=distro/collabora/co-23.05&id=413e7a2e6f0c363938a0a5ee5bd6eb5d56d5a8d8
in core added dialog which asks user if file should be repaired. This requires tests adjustment.
> Fix UnitBadDocLoad test after repair dialog is enabled

- browser/src/control/Control.JSDialogBuilder.js
Will not create `<u>` element for mobile wizard
Change-Id: Iaca88ac4be2c95dc4781180019ba8fede9cdc81a
* Resolves: #7141 
> Mobile: buttons with text color discrepancies

- common/FileUtil.cpp
- common/FileUtil.hpp
- kit/Kit.cpp
- net/HttpRequest.hpp
- test/helpers.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd: FileServerRequestHandler instance
- wsd: utility to read small files in memory
- wsd: const correctness
- killpoco: serve the Welcome file using http::Response
- wsd: simpler string appending in readDirToHash
- wsd: test: wait for 'statusindicator: find' instead of 'ready'
- wsd: add LOG_ASSERT to replace assert with extra logging
- wsd: improved assertion
- wsd: test: remove duplicate uninit
- wsd: use a smaller value when trimming after inactivity
> Misc Improvements

- browser/src/control/Control.UserList.js
Change-Id: Idc467c33e690c6e13023ad022b7cf57380d32ff3
* Resolves: # 
This pull request addresses the issue where the userListSummary popover remains open when it should close upon clicking on user list icons. The implementation ensures that the popover is closed when a user clicks on user list icons of the popover, providing a more intuitive and user-friendly experience.
> fix: close userListSummary popover on click

- kit/ChildSession.cpp
We assumed in the code that LO will return in a
LOK_CALLBACK_EXPORT_FILE url starting with "file:///tmp/" But that is not true for all the cases. Let's use
more generic approach to extract file name.
> Correctly extract file name for exported file

- README.md
The forum link in the README is missing https://. This PR fixes that
> fix broken forum link in README

- common/MessageQueue.hpp
- kit/DeltaSimd.c
- kit/DeltaSimd.h
Note: no patches were needed to build LibreOffice branch distro/collabora/co-23.05 on macOS Sonoma.
> Fix compiler warnings when building on macOS Sonoma

- browser/src/control/Control.UIManager.js
- browser/src/layer/tile/CanvasTileLayer.js
- kit/Kit.cpp
- wsd/protocol.txt
- it applies for 2 cases:
1. when document is loaded for the first time document already has tiles of respective theme
2. when Kit loads the document it sends canonicalidchange  unconditionally (https://github.com/CollaboraOnline/online/blob/5520965b151cb854acbac3f1bbb68aec5ac2e1f2/kit/Kit.cpp#L1708) we don't need to request new tiles for that also
Change-Id: I42cdc5a03e70c3d3d653f3124d3d5ed9382e22c0
* Resolves: # 
- [] I have run tests with `make check`
> don't request new tiles unnecessarily on canonicalidchange

- browser/src/map/handler/Map.Keyboard.js
This fixes error:
Map.Keyboard.js:364 Uncaught TypeError: Cannot read properties of undefined (reading '_docType')
at NewClass._globalKeyEvent (Map.Keyboard.js:364:3
When we open document which requires some interaction from user before load and we press any key - that error appears. It can be seen with macro warning or broken file warning.
> Fix typeerror on key event in interaction handler dialog

- browser/css/device-mobile.css
- browser/css/mobilewizard.css
mobile: fix snackbar button position
This fixes regression from:
commit 07c353858971d83a651b667efe827973dc70c2ae
mobile-wizard: create separate window container
The snackbar with action button like "leave feedback | ok"
or "we can reconnect | reload" had buttons below text
what looked bad and it was not possible to click
------------------------------------------------
mobile: fix snackbar text
This fixes regression introduced in:
commit b6c26bee914a39b803a1a1ae78dfaf9a280b131e
Mobile sidebar header layout #6861
- remove additional top border
- make line height regular so text will fit into snackbar
without scrollbar
> snackbar regression fixes

- browser/src/map/handler/Map.Keyboard.js
* Add CTRL + HOME and CTRL + END for selecting the first or last slide when slide sorter is focused.
German shortcut updates:
* F12 for save-as.
* SHIFT + F9 for showing / hiding the grid.
* SHIFT + F3 for changing the character cases.
* SHIFT + F5 for starting the slide show with the current slide.
Change-Id: If9eb59377af29bebfe89fa42ea9d5afdd1bf2335
* Resolves: # 
> Impress shortcuts:

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/map/Map.js
mobile screen is very small and there was not
enought space to scroll to the place where we "extend" scrollable area, this caused that in spreadsheets we were not able to scroll outside last used cells
this patch make us able to scroll 4 lengths of screen outside data for non-desktop devices to fix that issue
regression commit 48ec2f5925edec5550a1320ae7815a9bd86c4e12 Limit scrollbar range to used area in the spreadsheet
> mobile: allow scroll outside data area

- common/Log.cpp
- common/Log.hpp
- common/RenderTiles.hpp
- common/SigUtil.cpp
- common/Util.cpp
- kit/Kit.cpp
- net/clientnb.cpp
- test/fakesockettest.cpp
- tools/Config.cpp
- tools/Connect.cpp
- tools/KitClient.cpp
- wsd/COOLWSD.cpp
These patches replace the Console Channel of Poco with our faster and simpler implementations. The new loggers are behind EnableExperimental, so this change is safe to go in.
- wsd: test: enable experimental features in tests
- wsd: set up signal handlers early
- killpoco: our implementation of ConsoleChannel
- wsd: log: retry on write failure and flush
- wsd: support EnableExperimental in Log
- killpoco: own implementation of BufferedConsoleChannel
- killpoco: own implementation of ColorConsoleChannel
- wsd: stop the rendering thread pool before exiting
- wsd: log: BufferedConsoleChannel with thread-local buffer
- wsd: log: verify that all threads are stopped
- killpoco: replace LocalDateTime
> Kill Poco Logger (Partially)

- wsd/COOLWSD.cpp
Change-Id: Id7480ab88564965cc7aba34c5020daaf18259815
> docker: fix all aliasgroup env variable added to blocked list

- .github/workflows/helm-release.yml
- kubernetes/helm/cr.yaml
Change-Id: I2658fdefde7e40ab46cae2b9a3c0bfcac4ce626f
* Resolves: # 
current the helm-release set his helm to latest github-release, lets disable.
On this way just collabora releases (and not helm-chart) is marked as latest.
> fix(ci): do not set helm to current github-release

- browser/css/toolbar.css
- browser/src/control/Control.Notebookbar.js
The scroll indicator set with an absolute position ends up being
positioned in the 0 y coordinate. Since the wrapper has a top padding
of 3 pixel it means the scroll indicator is not 3 pixel off.
Also, and since these measurements are set in the CSS (the height of
the wrapper and the padding of the other wrapper), better to just move
everything to the CSS and avoid unnecessary inline styles.
Change-Id: Icc1e51b2590ee27b318f9e4c3d550183b08cb49d
> Tabbed: Calc: Scroll indicator is 3 pixels misaligned

- browser/src/map/handler/Map.Keyboard.js
Added CTRL + ALT + N shortcut.
* This sends the NewDocument postmessage to integrator along with the document type.
* Integrator should handle the message.
Change-Id: I8458f382771211b245ad4cedf501b73b50afc1c7
* Resolves: # 
> Add CTRL + ALT + N shortcut for new documents

- browser/css/btns.css
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- cypress_test/integration_tests/desktop/impress/sidebar_spec.js
Use 'position: absolute' in jsdialog-window and jsdialog-container so we don't stretch the dialog. It will use minimal needed size.
this is backport of: https://github.com/CollaboraOnline/online/commit/afbf052bb5d1f9b74389c068552c40878301aa43
fixes super long warning dialogs:
> jsdialog: use minial size of a dialog needed

- wsd/COOLWSD.cpp
it's a good catch, but inotify man page says it can't happen
Change-Id: I350f8fad2aa8308563ccb4f9f3ec9b7850a72fa7
* Resolves: # 
> cid#323357 silence String not null terminated

- wsd/COOLWSD.cpp
wsd-00001-00001 2023-09-07 06:57:38.412560 +0000 [ coolwsd ] FTL  Failed to initialize COOLWSD: Syntax error: Cannot convert to boolean: | wsd/COOLWSD.hpp:513
Syntax error: Cannot convert to boolean:
<shutdown>-00001 2023-09-07 06:57:38.413335 +0000 [ coolwsd ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x6400000001
Change-Id: I446bc9b2c2172d820da2ea148eefd1d7f964be80
> fix: docker failed to initialize when aliasgroups is passed

- browser/src/map/handler/Map.Keyboard.js
* Replace CTRL + SPACE with CTRL + ALT + S for search.
* CTRL + SPACE is used for resetting the character properties.
Change-Id: I99ed1e99cf7e1ea23344961d36cce42d72cbba5f
* Resolves: # 
> German keyboard shortcuts:

- browser/src/layer/tile/CalcTileLayer.js
Reason:
Sometimes cell address is at the end of a merged cells block. That kind of cell address is invalid. Example:
Merged cells: A1-A5.
When example merged block is selected, cell address should be A1. If it is A5, cell cursor is not drawn.
If cell cursor is not drawn "EMPTY" message is sent from core side. And we cannot enable drawing in this case.
So we enable drawing even if the cell cursor message is "EMPTY".
Change-Id: I456bc757725c9bfaede20068cf165310712488e7
* Resolves: # 
> Enable drawing even if the first cell cursor message is empty.

- browser/Makefile.am
- browser/css/jsdialogs.css
- browser/src/control/Control.DownloadProgress.js
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Util.ModalHelper.js
- browser/src/control/jsdialog/Widget.Progressbar.js
- browser/src/map/Clipboard.js
- browser/src/map/handler/Map.Keyboard.js
Improvements in copy-paste:
- all dialogs/popups converted to jsdialogs
- when user does complex copy first time - dialogs explaining the process are present
- when user does complex copy after on fully successful process - snackbar is used for messages
- to quickly copy, download, confirm copy to clipboard - shortcut 3x CTRL + C can be used
- when snackbar with download button appears but user changes selection -> we hide snackbar
> New copy paste dialogs / snackbars

- browser/src/control/Control.UIManager.js
We want to re-force the choice, i.e. people who mistakenly set their UI to compact mode, now will get tabbed mode and can decide, if they like it better or not.
Change-Id: Ic5810321abf2cbc3996478816fe153d848c66c71
> Change the local storage setting name 'CompactMode' to 'compactMode'

- browser/Makefile.am
Change-Id: Ic9b49a401b63af65f4e53e3eb2584b8258575c2a
* Resolves: # 
> exclude debug/dev files from production packages

- net/HttpRequest.hpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
The range header allows a client to specify that they would like only part of a file, e.g. only the first 1000 bytes of a video. When playing video on Apple devices (Macs, iPads, iPhones etc.) this is required to avoid Safari rejecting the video as broken. This is the first part of a fix to embedded videos on Safari.
This pull request does not implement specifying multiple ranges at once (e.g. bytes=0-9,-100 to get the first 10 and last 100 bytes).
This feature is necessary to play video on Apple devices, but it is not sufficient. In particular, I believe some further client-side fixes will be needed to make the video play properly.
Change-Id: Id89a06d374b7d0efbf2b3184d8618df61684dcb6
> Allow http Range header for media files

- browser/src/layer/vector/SVGGroup.js
This commit fixes videos rendering in the wrong place on Safari (and all iOS browsers). Note that it will still need the server fixes contained in https://github.com/CollaboraOnline/online/pull/7367 for Safari to play video
To reproduce, load a document with an mp4 video in Safari (this may also work with other formats, but we know of unrelated bugs with non-mp4 videos) and click on the place where the video should be.
Before this commit, you will see a white rectangle where the video should appear. After this commit, you will see the video. If you have this commit but not #7367 you will see a play button with a "broken video" strikethrough. In non-Safari/iOS browsers you will see the video both before and after this commit.
This commit does not include detection for the upcoming …
> safari: workaround SVG position bug

- browser/css/jsdialogs.css
Don't allow dialogs to grow taller than the web browser's viewport
instead,
- Set (for dialog's content) a max of 90% of the View height and subtract the dialog's
header. This way the header with the close button stays always visible
- Set overflow accordingly so it can be  scrollable
Change-Id: I61a2a41d8b1198fe00b939427cde43d247dc08bb
> JSDialog: Dialogs shouldn't be taller than viewport

- kit/Kit.cpp
- net/Socket.cpp
in which case don't send it, which then implies we might have an empty shareFDs which we can treat the same as a nonexisting shareFDs
Change-Id: I80a78a01c69dbee5ee28a64442a5069a6c2b4dbe
* Resolves: # 
> ProcSMapsFile might not be a valid file descriptor

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
can result in still unfulfilled requests for the first tab in requestedTiles when the new requests are compared with those for duplicates
Change-Id: Id8d40f0a7e7f9d32fed67a415756284d7f6a53d4
* Resolves: # 
> different 'parts' in requestedTiles on switching calc tabs

- kit/ForKit.cpp
AdminModel::cleanupResourceConsumingDocs uses SIGABRT as first attept to kill misbehaving documents, we should give DocumentBroker a chance to quarantine documents killed off by SIGABRT as we do SIGSEGV/SIGBUS
Change-Id: Ic3a703572393050379b5a1444a5380bbeafcf2d3
* Resolves: # 
> keep quarantine files on SIGABRT too

- browser/css/jsdialogs.css
Change-Id: I6e8194ea456e4af3104754cf9219be22f135c042
* Resolves: # 
> Fix CSS selector: make checkboxes visible in light mode

- browser/src/layer/marker/TextInput.js
Set up accessible text through aria-description for describing how to
enable accessibility support for text content when it is disabled.
The description is reported by the screen reader on document load and
on explicit request to read current text content.
Change-Id: I439b7703c15d3b38c39181d27c11da438834c414
> a11y: accessible description to describe how to turn on accessible mode

- browser/src/map/handler/Map.Keyboard.js
* Resolves: #7084
In certain sections of the code, the shortcuts was tied to the e.key value. However, this approach doesn't function correctly on keyboard layouts that significantly differ from English. Therefore, it has been rewritten to utilize 'e.keyCode,' which is not influenced by the keyboard layout.
> Shortcuts for different keyboard layouts

- coolwsd.xml.in
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
- It logs activities like when admin logged in, authenticated metrics endpoint accessed, external monitor getting connected and admin actions like kill the document etc
Change-Id: I059f6b6ee0d8269aec7e3f521622773e348304a3
* Resolves: # 
> admin:log activities irrespective of logging.level

- browser/src/layer/tile/CommentSection.ts
problem:
this caused problem in autosaved comments,
when comment list is empty autosaved comments may be closed when focus is lost
Change-Id: I1fc2d087828ce44495001f97b5323dffb8adb2ef
> annotation: make sure comment list is fetched correctly

- browser/src/map/Map.js
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
problem:
earlier restriction/lock status was sent to kit via browser, now client session send this status directily to the kit. this design will require less communication between server and browser
Change-Id: I6b830f30fb326a5e6637e345250893cbba101de6
> feature-locking: send lock/restriction status from client session

- browser/src/control/Toolbar.js
queryselectorall('something').queryselectorall('something else') fails.
^ This JS error is fixed.
Also we don't have specific images for German help page. So we removed the "de" from that language list.
Change-Id: I69b56e8f4bd2b92835c4aca9c2284750f3df9455
* Resolves: # 
> Fix JS error on translations.

- browser/src/control/jsdialog/Widget.MobileBorderSelector.js
- jsdialog requires to create in the handler single root node with id of the widget
- remove old style update by _refreshSidebar
> jsdialog: make mobile border style control compatible

- browser/src/control/Control.JSDialogBuilder.js
Change-Id: I740f86e9477656d371ba3b8793bff99671444d7c
- Condition modified for getPrecision.
- it was not handling the cases for dot value less then 0.
* Resolves: #7236
> Fix spinfield doesn't adjust the value

- wsd/DocumentBroker.cpp
- wsd/QuarantineUtil.cpp
scraping the logs with:
if line.find('Backtrace ') != -1:
pid = re.findall(r'Backtrace ([0-9]+?) -', line)
if pid:
for file in os.listdir("/opt/cool/quarantine"):
if file.find(pid[0]) != -1:
...
shows an unexpected lack of hits
Change-Id: I63b5e62a5d46627146763cb0f847b976017f6c4b
* Resolves: # 
> raise quarantine logging to WRN and include more information

- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
when anonymization is enabled
Change-Id: I0aee79411b79745078f98581094d2ddb1638fad6
* Resolves: # 
> avoid logging user content from spreadsheet cells

- browser/src/layer/tile/CalcTileLayer.js
With this fix, user can open a new commen popup without closing a previous new comment popup.
Without this, a new comment section lingers at the background and new comment command fails until user refreshes page.
Change-Id: If7f151eb11d3f5d26dae2ca6331eb5dc0dfd9881
* Resolves: # 
> Fixed the name of the new comment.

- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
and
cid#318819 Uncaught exception
take a reference in the COOLWSD/DocumentBroker ctor, so indicating it exists before the calls in the COOLWSD/DocumentBroker dtor, and so the Admin ctor doesn't throw during the COOLWSD/DocumentBroker dtor.
Change-Id: I8190cc3594a5f81fedd355aeadcca45e532bda90
* Resolves: # 
> cid#318817 avoid Uncaught exception

- test/TileCacheTests.cpp
with the original 25 expected results from 25 requests
from cid#318925 Structurally dead code
Change-Id: I236876fadd5b5c82ecdbcc52a13fc58e8513aa12
* Resolves: # 
> restore TileCacheTests::testTileProcessed

- browser/src/control/Control.UIManager.js
If postmessage to insert custom button will arrive early before we initialized notebookbar it could
fail in insertion into compact mode toolbar due to not existing toolbar.
This prevents us from that error. It will be not added at the time of postmessage execution
but we remember all the custom buttons in special
array, so when UI will be initialized it will be added there.
> Avoid using undefine in custom button insertion

- common/RenderTiles.hpp
We only run one task in each thread when run() is called, then complete the remainder of tasks in the main thread while the other threads wait.
https: //github.com/CollaboraOnline/online/issues/7374
Change-Id: Id4fc0a620d98b0bb55310b495eeff7411a4544b5 (cherry picked from commit d6c1916cb201dcd0c851b31ed776c1cbf24540a0)
* Resolves: # 
> cool#7374 very little delta threading

- wsd/DocumentBroker.cpp
It fixes richdocumentscode case when trying to request media:
`[ websrv_poll ] ERR  #-1: Failed to open file [.../9a2gf9.ogg] for uploading| net/HttpRequest.hpp:1603`
> Fix media request error

- browser/css/jsdialogs.css
Change-Id: I245e0979cd069f13eb8237eb155aa1760289a180
* Resolves: # 
I did not modify the keyboard shortcut window, because I found that it is better when keyboard shortcuts and their descriptions are close to each other.
> Help window was too narrow

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.ScrolledWindow.js
This fixes side effect from commit a1b2091ae622437f531f1126a8de9c143b06be68
JSDialog: Dialogs shouldn't be taller than viewport
which introduced scrollbars to dialogs when not needed, examples:
Writer -> Format -> Character
Calc -> Data -> Validity
> jsdialog: fix scrollbars inside dialogs

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.TreeView.js
Use pure CSS to make margins for different levels.
Inspired by: https://www.w3.org/WAI/ARIA/apg/patterns/treegrid/examples/treegrid-1/#ex_label
- reuse arrow from tree view and expander widget
- center verticaly entries in the tree grid / list view
- add pointer cursor for expander arrow
- do not allow to sort tree grid - it makes no sense
Tree grid is a kind of table with headers but rows can be expanded
and have subentries with different "level" in the tree.
It can be tested in Writer -> Review -> Manage Changes
> jsdialog: treegrid

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.UIManager.js
Previously we reloaded sidebar or notebookbar on theme change because we wanted to load icons to match new colors. This change makes icons aware of theme change so they automatically switch the URL. Reload of notebookbar or sidebar is not needed then.
> jsdialog: change icon theme without reloading whole components

- net/Socket.hpp
It seems that when TCP_NODELAY fails to be set,
the failure is permanent. As such, there is no
point in filling the logs with the same error.
This patch logs the error only once, per process,
and supresses further logs from Socket::setNoDelay().
Change-Id: I52c6b8cca35a8c281b4c4639d61a7e2521775d49
> wsd: log TCP_NODELAY error only once

- browser/src/control/Control.IdleHandler.ts
- browser/src/map/handler/Map.WOPI.js
postmessage: handle Get_User_State
Get_User_State postmessage is used to query user status.
If user is active or idle and how many seconds ago there
was registered last activity.
{
state: 'idle',
elapsed: 2.3
}
-------------------------
postmessage: send User_Active when become active again
We send User_Idle when user become idle, but there was no
similar message when user become active again.
> Idle status postmessages

- browser/src/layer/marker/TextInput.js
The problem occurs when accessibility is disabled
Exactly when the editable area is not empty and the cursor inside the
editable area is at the end.
Change-Id: Ia69e0f56233497e91babf9e33080701e1f1adad2
> a11y: on Firefox delete key doesn't work in some specific case

- browser/html/wasm.html
- common/Util.hpp
- net/HttpHelper.cpp
- net/HttpHelper.hpp
- net/HttpRequest.hpp
- net/Socket.cpp
- test/UnitHTTP.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPITemplate.cpp
- test/WopiTestServer.hpp
- tools/WebSocketDump.cpp
- wasm/README.no-container.md
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/ProxyRequestHandler.cpp
- wasm: improved build instructions in readme
- wsd: log TCP_NODELAY error only once
- browser: add wasm.html to load documents via wasm
- wsd: http: use named HTTP status-code instead of naked int
- wsd: http: no need to pass the mime-type explicitly to sendFile
- wsd: helper to serialize pairs
- killpoco: replace HTTPResponse in sendFileAndShutdown
- wasm: support serving wasm files
> Misc Improvements and Kill Poco

- browser/html/framed.doc.html
Change-Id: I13976c21ebea018150469dd56f93b3b1ab2105cc
* Resolves: # 
This allow to send arbitrary post message. This is just UI in the postmessage interface page.
This is how I did test #7517
> postmessage: Add field to allow sending arbitrary postmessages

- browser/src/map/handler/Map.WOPI.js
Change-Id: Id357c54bce57464334a24115175087e4bbfa4aea
* Resolves: # 
The warning is confusing if the UI message has been handled.
@eszkadev This is a follow up on your change.
> postmessage: Don't output error for handled UI message before ready

- browser/src/control/Control.JSDialogBuilder.js
problem:
rename dialog sometimes flickered in Firefox
it flickered when the button label was clicked,
it made the event bubble and triggered the click event multiple times. trying to open dialog when already opened makes it flicker intentionally
fixes: #7479
Change-Id: I290c905ac321650bd7979495c78de7d66f188ffd
> UI: fix rename dialog flickering

- browser/src/layer/marker/A11yTextInput.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
- kit/ChildSession.cpp
Avoid screen reader to wrongly report text when a shape or image is
selected:
- Got editable area to be made empty when user is not editing text
- Got default for any input to be prevented (except for some special
cases) when user is not editing text so editable area is kept empty
The selection action and the selected object name (e.g. "Rectangle",
"Presentation Title", etc.) are sent to the client.
That allows screen reader to report: "Presentation Title selected" or
"Rectangle unselected", according to the action type.
Selection text content is reported too when available.
Something alike is reported on cell navigation in a spreadsheet.
Change-Id: I75a8b66ef8cb7b24b28d749f0b24afe2587de45e
> a11y: impress: help screen reader to report shape selection

- browser/css/device-mobile.css
- browser/css/jssidebar.css
This fixes regression from commit c77f1041a58cd4606c69a0808888dc16dd654785 jsdialog: implement horizontal separator
Where horizontal separator widget was implemented
and now it appears in the sidebar, but as we have grid layout there - it occupies only half of the sidebar because we have 2 columns.
> sidebar: fix paragraph panel layout

- browser/src/core/Socket.js
which is done by addLayer, otherwise its possible to handle a onViewInfoMsg before map is set
Change-Id: If6e6d15c90de129614bcc2b64705d0b51b5c4e83
* Resolves: # 
> apply delayed messages after docLayer.map is set

- browser/src/layer/tile/CommentSection.ts
problem:
After entering the comment modify mode and clicking somewhere else, to lose comment focus, comment cannot be closed by clicking cancel.
Change-Id: I05ce2b4f6dcba47d40095bb16fdb56ce5b9c20cf
> annotation: avoid marking comment autosave if its not saved

- browser/src/control/Control.DocumentNameInput.js
problem:
filename textbox will revert to original name after user confirms the name and then again changes to new name after its processed
fixes: #6131
Change-Id: Ibb1645e5e6517b391d475add7b7d421a260e0ba8
> UI: avoid changing back to original name after renaming

- browser/js/global.js
Change-Id: Ic661358cd47600ec9c3a329bef361b8087483017
> a11y: keep a11y disabled on executing cypress Calc tests

- browser/css/jsdialogs.css
- JSdialog: Fix ui-separator visual importance
- Multi-level menus (dropdowns): Fix chevron elements
- Menus (dropdowns) with separator: Fix hidden keyboard focus
> Menu: Fix separators, chevron and focus

- browser/src/layer/tile/CommentListSection.ts
select and unselect usually updates the layout but,
in case if it failed we manually do the layout update
problem:
when already selected comment try to modify,
it will not rearrange replies in the thread this caused overlapping of the comments and bad user experience
fixes: #7527
Change-Id: Id56a5c35795e1ff75e8c3a92032afce6b8585fcb
> annotation: forcefully reselect comment before modifying

- browser/src/layer/tile/CommentSection.ts
problem:
when a user modifies a comment and its autosaved,
if user then cancels the modification they were still added
Change-Id: I26c872f0957f0815882c4b1aedae83fe6736b7a2
> annotation: fix cancelled modification of autosaved comment

- browser/src/layer/tile/CommentSection.ts
part 2
fix from #7552 stopped working, this patch amends it
Change-Id: I8c1227199112599fc2ade4e425452709e9cd05e5
> annotation: fix parent comment being deleted if reply cancelled

- browser/src/core/Socket.js
which is done by docLayer._onStatusMsg(), otherwise its possible to handle a onViewInfoMsg before viewid is set
Change-Id: Id68dba5f5cdc8efd0b5f6ed429ac4f105cef4866
* Resolves: # 
> apply delayed messages after docLayer.viewid is set

- browser/html/framed.doc.html
- browser/src/map/handler/Map.WOPI.js
The new messages are: Collapse_Notebookbar and Extend_Notebookbar As a side effect they also hide the classic toolbar the same way
Change-Id: Ic9d04876acb06f2885a6be1e171df7f87e513ed8
* Resolves: # 
Add two postmessage to show hide the notebookbar. Due to the UI layout, they also hide
the classic toolbar in that mode.
> postmessage: added message to collapse / extend notebookbar

- kubernetes/helm/collabora-online/Chart.yaml
- from the logs Error: error creating GitHub release helm-collabora-online-1.1.3: POST https://api.github.com/repos/CollaboraOnline/online/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
Change-Id: I434963728bf935204a4dc6e533aaa1b5a8408350
> fix helm chart releaser

- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.RowHeader.ts
- browser/src/control/jsdialog/Widget.Combobox.js
Fix Uncaught TypeError in combobox selection
TypeError: Cannot set properties of undefined (setting 'selected') emitting event jsdialog: { "jsontype": "sidebar", "action": "action", "id": 0, "data": { "control_id": "applystyle", "position": "-1", "action_type": "select"}}
When selecting whole column in Calc
----------------------------------
Fix Uncaught TypeError in col/rows headers selection
Uncaught TypeError: Cannot read properties of null (reading 'index')
at RowHeader.onMouseUp (bundle.js:24879:87)
at CanvasSectionContainer.propagateOnMouseUp (bundle.js:14350:24)
at CanvasSectionContainer.onMouseUp (bundle.js:14442:6)
> Fix TypeErrors in Calc

- browser/src/control/Control.FormulaBar.js
- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/jsdialog/Widget.MenuButton.js
- fixes regression from Accessibility commit 1a2500c
- it fixes formulabar control of AutoSum button #7548
- removes useless commit a7ece5d: jsdialog: reduce warnings in console for formulabar
- id with ":" contains "id : menuId", so we can identify menu which should be used, let's not use whole string as HTML element id - we don't want ":" there
> jsdialog: fix id for buttons with menu #7548

- browser/css/jsdialogs.css
vertical separator was overlapping other widgets
can be found in: Calc -> Insert -> Pivot Table -> next
Before:
After:
> css: pivot table dialog separator fix

- browser/html/framed.doc.html
- browser/js/global.js
- browser/src/layer/marker/TextInput.js
- browser/src/map/handler/Map.WOPI.js
Before this change, panning a calc spreadsheet would cause the onscreen keyboard to pop up when in tablet mode. Dismissing the keyboard would not stop it from being popped up the next time you panned around. This made it very difficult to pan around spreadsheets in calc without either using an external keyboard, the mobile app or another device altogether.
This commit introduces a known regression: when you are on a tablet and have a physical external keyboard, you could previously select the cell and start typing. Now you must tap into the cell in the same way you would if you have an onscreen keyboard. This matches the behavior on mobile devices. I consider this regression a reasonable tradeoff, so notwithstanding I believe this should be merged.
~~A followup is planned to add a POST …
> Stop onscreen keyboard when panning calc on tablet

- browser/src/layer/tile/CanvasSectionContainer.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/TilesSection.ts
If we end up dirtying only due to a series of TileRange reasons then we only need to redraw the bounds of those tiles.
https://github.com/CollaboraOnline/online/issues/7166
checked: split calc sheets and rtl calc sheets
Change-Id: If468b735bdff85408155fb23ebf6db891a449d5e
* Resolves: # 
> We don't always need to redraw the entire canvas

- net/DelaySocket.cpp
- net/NetUtil.cpp
- net/ServerSocket.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/SslSocket.hpp
- test/HttpRequestTests.cpp
- tools/WebSocketDump.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.hpp
Change-Id: Ic0f720554080a01b7a46abbffda023834016c0ea
* Resolves: # 
> net: don't try to set TCP_NODELAY on local Unix sockets.

- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.ContextMenu.js
- browser/src/control/Control.RowHeader.ts
In some case[*] when we right click on row header and release mouse button, first element of the context menu is invoked. To prevent this, I planned just prevent the mouseup event on context menu items but it prevented to do click event too.
[*] 1920x1080 resolution with %75 browser zoom
Change-Id: I28299e7a7cf83eaed27ef4ed6c3555fb2cc80682
* Resolves: # 
> Prevent mouse button up event to click on menu item.

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
we know where they are by cell addresses, so defer getting the screen positions until we need them and we don't need to get core to trigger recalculating them. When we redraw the comments after the new geometry arrives then we can place them via the address.
When adding a new note we want to know the range of the potentially merged cells we are inserting into.
https://github.com/CollaboraOnline/online/issues/7334
https://gerrit.libreoffice.org/c/core/+/158560 needs to be applied to solve the problem described there that becomes apparent when this is in place.
Change-Id: I3228dc8fa8d47ba4e796e50427c125d7f78fe5fc
* Resolves: # 
> we don't need to round-trip through core to reposition notes

- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.Header.ts
- browser/src/control/Control.RowHeader.ts
- browser/src/control/jsdialog/Widget.FormulabarEdit.js
formulabar: modify DOM only when content is complete
createDocumentFragment creates out of the DOM nodes which we can use while building the new content of the formulabar. This reduces reflow and similar operations on node insertion.
------------------------------
perf: do not call addEventListener on every header update
This helps with performance of typing into spreadsheets.
Regression from commit https://github.com/CollaboraOnline/online/commit/46c1248c770c2409ebb3b38c796690220ea98880
Prevent right mouse button up event to click on menu item.
Do not add new event listener on every header update what
happens often but rather apply right click blocker when
context menu is opened. Original commit was trying to prevent
menu items activation on right click.
> formulabar: optimization

- browser/js/global.js
matchMedia allows you to check matches for CSS media queries from JavaScript. By checking if the primary pointer is 'coarse' we have a pretty good shot at guessing that it's a touch device (mice, etc. are 'fine' instead). This expands our current touch detection so it detects more screens, while making sure it doesn't detect devices which have a touchscreen but also a mouse/touchpad/whatever. This non-detection is important, because our touch support currently breaks things like the rightclick menu on calc.
Touchscreen detection is useful for devices that are being used as touch devices, because it enables some features like pinch-to-zoom and hold-for-rightclick-menu which improve usability when you are using a touchscreen. These are particularly important without a mouse.
Some devices …
> Add touch detection for pointer:course media query

- browser/src/layer/tile/CanvasSectionContainer.ts
- browser/src/layer/tile/TilesSection.ts
doesn't happen in ci, but is happening in tinderbox and for some users.
Seeing as ScrollSection doesn't have the problem, follow the export and namespace pattern used there.
Change-Id: I4c4916ba7a3ad19275bd8b0f5bc53111b3b30cd5
* Resolves: # 
> fix; error TS2304: Cannot find name 'TilesSection'

- browser/js/global.js
- wsd/FileServerUtil.cpp
The new ui_defaults option OnscreenKeyboardHint is a tristate denoting whether the device accessing Collabora Online has an onscreen keyboard
If unset, Collabora Online will do its best to guess. At time of writing, this is the same as checking if the device is a mobile phone or a tablet (note: only tablets which have the browser registered as a "mobile" browser will be detected, e.g. the Microsoft Surface tablets would not be detected)
If "true", Collabora will assume the device has an onscreen keyboard. This will change when we trigger the keyboard, for example in calc if we know of an onscreen keyboard we will not automatically focus a cell for editing when it is selected, as this would pop up the keyboard.
If "false", Collabora will assume the device does not have an onscreen …
> Add a ui_defaults option for onscreen keyboards

- browser/src/map/Clipboard.js
* Add a paragraph.
* Select the whole paragraph and add comment.
* Add hyperlink to a word in the paragraph.
* Try to copy the hyperlink via its menu.
* It sometimes doesn't copy the hyperlink.
We are checking if a comment has focus or not before doing the copy operation. This check is for another issue. I changed the check with "app.view.commentHasFocus" which seems reliable. Then tested the previous fix.
Also commented out code is removed.
White space change is automatic.
Change-Id: Ibc2c5e550eb8a3e24b734e0371c87dac44b2ff6d
* Resolves: # 
> Copying the hyperlink issue:

- browser/src/control/Control.UIManager.js
- wsd/FileServerUtil.cpp
Change-Id: I189224581451c9f5d534593696b060c8efb23414
* Resolves: # 
Pass `{Text,Spreadsheet,Presentation,Draw}Toolbar=false` in the POST to hide the toolbar in compact mode.
> browser: Add ui_default to hide the toolbar

- browser/css/writer.css
- browser/src/layer/tile/ContentControlSection.ts
- add missing image path for data-them dark
Change-Id: If6850770548d35eb95125ce0be1c52a557f5b344
> Fix Content control "down arrow" cannot be recognized in dark mode

- browser/src/control/Control.JSDialogBuilder.js
Change-Id: I3c6f770058ae1409f56d6bd12f5e7a8cd2441941
Previous behaviour was like user is able to check or uncheck a checkbox even if that checkbox is disabled.
For ex : Format => Character => select position option => try to chec/Uncheck the checkboxes which are disabled
- This will fix not to check or uncheck if a checkbox is disabled by clicking on a lable of a checkbox
* Resolves: #7630
> do not allow check uncheck for disabled checkbox

- browser/css/jsdialogs.css
- Added missing data-theme = dark for #valueset-img
Change-Id: Ibddeaa28089ba21250753f121af4746e3947cf38
* Resolves: #7590
> Fix "Format > Columns" Menu Has Dark Icons

- browser/src/layer/marker/Cursor.ts
- browser/src/map/Map.js
It was reported on some iOS devices that we fail with TypeError in getCorePxDocBounds - missing this.options.docBounds.
getCorePxDocBounds is used in Cursor class, check if we have docBounds before use so we don't try to update without valid data
> Avoid TypeError in getCorePxDocBounds

- common/Log.cpp
Change-Id: I93f7ac7a83c9724537b9b214cd8b54e5132c54e4
* Resolves: # 
> fix log date, tm.tm_mon is 0-11

- wsd/FileServerUtil.cpp
Caused log ERR on startup:
[ websrv_poll ] ERR  unknown UI default's component UITheme| wsd/FileServerUtil.cpp:99
Change-Id: I82f036e393cfb271e2dec2c52c5dc512aed265c8
> missing continue keyword

- browser/src/map/Clipboard.js
problem:
when user copy cell with formula and paste it outside of online, formulas are pasted instead of values.
Ideally we should always put real value in client clipboard
Change-Id: I93af2fffa501c3cdc3d8ecc78d3c44121784d3e8
> clipboard: do not put formulas into client clipboard

- browser/src/layer/tile/CanvasTileLayer.js
A slide preview tile falls into the special case with early return and no tileprocessed is sent back to the server, so eventually a 'Tileprocessed message did not arrive in time' will be reported
Change-Id: Iab85e5eca535ce377508e91cf67f1435e9242bc4
* Resolves: # 
> 'Tileprocessed message did not arrive in time' for slide preview

- browser/src/control/Control.ContextMenu.js
- browser/src/unocommands.js
This is now safe to show, as it'll trigger the frame insert/properties
dialog, which was converted to jsdialog in core.git commit
355681eead2411d70caf4f52f1b802cf8c61a981 (sw floattable: make Insert
Frame dialog async and mark it as a jsdialog, 2023-11-06).
Change-Id: I910012286416231d607cf79cc9b3811803c52768
> context menu: allow frame properties for Writer text frames

- browser/js/global.js
- wsd/FileServerUtil.cpp
At the moment, we try to detect whether the browser is running with a touchscreen, however this is very imperfect. It's possible an integrator may have more information about whether COOL is running on a device with a touchscreen, so this ui_defaults property allows us to specify. Touch mode binds inputs for touchscreen devices (long press for menu, pinch to zoom, etc.) and does not bind the normal inputs (right click for menu, etc.), so it's crucial to get it on all touch devices and no desktop devices, as input is severely hampered if they are the wrong way round.
The property is called TouchscreenHint. Setting it to 'true' will enable touchscreen mode, setting it to 'false' will disable touchscreen mode. Leaving it undefined will keep our detection active.
This property must be set at …
> Add a ui_defaults hint for touchscreens

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
when cursor is on page 2
Change-Id: Iae8d28ad54401fbbe78a2f2429f1a6912f1ea967
* Resolves: # 
> make this other test more robust if partial page 1 is still visible

- browser/js/global.js
- browser/src/control/jsdialog/Widget.Calendar.js
- browser/src/layer/tile/ContentControlSection.ts
It seems that datepicker control expects only a language input in regional property (e.g. fr) instead of language-country (e.g. fr-FR).
Change-Id: I7d5ac40cfa4a72cdc7862a8b4c4d14bdecad6c3b
* Resolves: # 
> fix language issue in datepicker control

- coolwsd-systemplate-setup
for curl >= 8.3.0 which removed the nss backend, requiring the certs with the OpenSSL backend.
DeepL access doesn't work otherwise.
Use the same list and order as used in core:
see: similar to https://gerrit.libreoffice.org/c/core/+/158915
and: https://www.happyassassin.net/posts/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/
Change-Id: Ic9de1e926977f63592146ac17df42704c8d86ccd
* Resolves: # 
> copy CA certificates to jail

- .github/ISSUE_TEMPLATE/bug_report.md
When creating NEW bug in GITHUB, there is template text, it includes OS, Browser, Version, but missing is COLLABORA Version. I am seeing reports with all fillied, but missing that which is most important. In addiiton, I set Browser with Versoin to be single line with e.g. Chrome 114.
* Resolves: # 
> Update bug_report.md with Collabora

- browser/src/control/Control.UIManager.js
Previously, when using the Collapse_Notebookbar postmessage or equivalent ui_defaults (SpreadsheetToolbar=false, etc.), particularly in compact mode, it was possible to additionally hide the menu bar. As the button to show the menu bar is on the notebookbar, this meant that you couldn't reactivate either notebookbar or menubar until you refreshed the page. This is particularly annoying in integrators that may not provide an easy way to reload the page
This commit makes it so that hiding the menu bar automatically uncollapses the notebookbar and won't let it be collapsed again. Whether the notebook bar should be collapsed (the last thing done to it was a collapse) is remembered and restored after the menu bar is shown again, so if you send a postmessage that will affect the state of the …
> Menubar & Tabs visibility logic fixes

- browser/Makefile.am
presumably a regression from 158fe2f93:
Trying to init LOKit cause mysterious runtime error...
Change-Id: I28603a98a7c9015afc76d46a302a23ccf4ece261
* Resolves: # 
> wasm: don't try to package obsolete and/or renamed online.data

- browser/src/core/Log.js
- browser/src/core/Socket.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
Remove unused co-ordinates parameter, and unhelpful L.Log call locations, ensure that all protocol messages are logged.
Increase the buffer to record startup and replay it for easier debugging after startup.
Now when enabling "Protocol Logging" in the first minute from document load, we get:
INCOMING[!fullyLoadedAndReady].statusindicator: find INCOMING[!fullyLoadedAndReady].statusindicator: connect INCOMING[!fullyLoadedAndReady].statusindicator: ready INCOMING[!fullyLoadedAndReady].perm: edit
INCOMING[!fullyLoadedAndReady].filemode:{"readOnly": false, "editComment": true} etc.
Change-Id: I5d2a8639e8038dbcc31d6e8fd1b8f8ebf2fff7bc
* Resolves: # 
> Logging - dump our log history to the console when asked.

- browser/css/mobilewizard.css
- browser/src/control/Control.Menubar.js
Change-Id: Ib982a59c141d937c7f92eb9684b91fc7f2548df5
- will fix Misaligned ui-tabs in mobile wizard
- also added scrollable property that will handle more fields in tabs if it does not fit into screen
* Resolves: #7638 
- Before
-After
> Fix mobile-ui-tabs Misaligned Headings

- kubernetes/helm/collabora-online/grafana_dashboards/ha-allocation.json
- kubernetes/helm/collabora-online/templates/prometheus-rules.yaml
- wsd/AdminModel.cpp
- wsd/metrics.txt
@mmeeks i like to have the pid value as an label so it would be use on the other metrics for lookup with [promql group_left](https://prometheus.io/docs/prometheus/latest/querying/operators/#group-modifiers)
i believe it is usefull to rename that metrics afterwards my suggestion `doc_info` as an representer for all the metrics
After this change i will enrich the PrometheusRules / Alerts to show more information (based on the instance and pid label) - current i believe the following should work:
`doc_active_views * group_left(doc_info)`
> fix: metrics change doc_pid to doc_info use pid as label

- .github/workflows/helm-release.yml
- kubernetes/helm/collabora-online/Chart.yaml
- kubernetes/helm/collabora-online/templates/prometheus-rules.yaml
- kubernetes/helm/collabora-online/values.yaml
Change-Id: I5076c74c3beeada0978d5b29dcc4e531cfce9241
ping @Rash419
we refactoring your default alerts there text and redefined the Alert DocumentsOpenSimultaneously: where on critical, it say how many of all documents are opened simultaneously on different pods procent (if the ingress does not work correct)
> fix: improve prometheus-rules

- common/RenderTiles.hpp
The ThreadPool::work function can get its condition signalled -very- late.
With bad timing, this can occur after all the work is done, and when the next batch of work is being fed into the pool.
This can mean that it takes work from the queue, and subverts the:
bool useThreads = _threads.size() > 1 && _work.size() > 1;
check in ThreadPool::run - which can believe we are in a single threaded, single tile mode - and not wait for this thread to complete.
That's not good [!] so ensure that threads are only runnable during ThreadPool::run.
Change-Id: Ifebb0f15cbb4c22ef33ffba06e7c6c87493818be
* Resolves: # 
> delta: fix threading gotcha when working.

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
problem:
User A writes Comment 1 and saves
User A replies to himself, write something, click away to autosave, Cancel
user A modifies Comment 1 and OK - comment disappears, although it is there, seen after reload, but without modification.
Change-Id: I5d83936f26939b5a05a0ce3099c01923a55c9606
> annotation: reset comment id if autosave is cancelled

- wsd/ClientSession.cpp
Change-Id: I190a03abcf80176cc2da77fd32190c683852b9a7
* Resolves: follow up of https://github.com/CollaboraOnline/online/commit/6b06f1d8fec1788c18c5755d7e5c2046c3407cbf
> wsd: disable ctrl+s when HideSaveOption is true

- browser/src/control/Control.ContextMenu.js
- browser/src/unocommands.js
This is safe to do as it's not interactive, so it happens synchronously.
The matching uno command was added on core.git co-23.05 in commit
1f5c20352725cd6133e68e80e8523d865006161f (sw floattable, delete UI: add
an uno command to unfloat frame from context menu, 2023-11-17).
Change-Id: I74736c7d589c2062a8e9255a42f81bf790b7d3e3
> context menu: allow unfloat table for Writer text frames

- browser/src/layer/tile/CommentListSection.ts
problem:
some times we order comments before parent-child relation is established, this caused reply count not being updated correctly for other users
steps to reproduce:
User A open ODT, let us say already with comment or add one, and keep Sidebar open so that comments are short. user B opens the same ODT with full comments. adds reply User A does not update ticket number, does not have +1
Change-Id: If3360c8dd938c6bd177764d3c1383d7f3f845990
> annotation: make sure parent-child relation is established

- browser/js/global.js
- browser/src/control/Control.FormulaBar.js
- browser/src/control/Control.Layers.js
- browser/src/control/Permission.js
- browser/src/control/Ruler.js
- browser/src/dom/DomEvent.js
- browser/src/dom/Draggable.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/vector/CPath.ts
- browser/src/layer/vector/Path.Drag.js
- browser/src/layer/vector/Path.Transform.js
- browser/src/layer/vector/Path.js
- browser/src/layer/vector/SVGGroup.js
- browser/src/map/Map.js
- browser/src/map/handler/Map.DoubleClickZoom.js
- browser/src/map/handler/Map.Scroll.js
- browser/src/map/handler/Map.TouchGesture.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/calc/delete_objects_spec.js
- cypress_test/integration_tests/mobile/calc/image_operation_spec.js
- cypress_test/integration_tests/mobile/calc/sheet_operation_spec.js
- cypress_test/integration_tests/mobile/impress/delete_objects_spec.js
- cypress_test/integration_tests/mobile/writer/delete_objects_spec.js
L.Browser.touch is sometimes nice, but it's ultimately a flawed concept to use it for input events. Using L.Browser.touch for input handicaps people with mice if it's too liberal in what it classes as touchscreens, and handicaps people with touchscreens if it's too conservative. There's also no sweet spot: it's impossible to choose correctly if someone is using both a touchscreen and a pointer device, as there's no right option!
Previously many of our event handlers and some of our UI was gated behind L.Browser.touch. This commit adds a new "window.touch" property which is used instead. It has functions to help with event detection, allowing you to easily make event handlers that work for only the input devices they are designed for, without gating them behind feature detection. This has …
> Unify touchscreen handling, remove L.Browser.touch

- browser/html/cool.html.m4
- browser/src/main.js
- wasm/wasmapp.cpp
- wsd/FileServer.cpp
> wip: demo with nextcloud support

- browser/src/control/Control.NotebookbarCalc.js
Change-Id: Ic5f69b64221ca9890794b1b3dcb5dbe069992459
* Resolves: # 
> add missing css class to dark mode icon in Calc

- browser/css/jssidebar.css
Change-Id: Icbd85bdd3ec400a016f2c9affdfca04b78711987
* Resolves: # [ Chrome: Navigator Hyperlinks Don't Linebreak #7425 ](https://github.com/CollaboraOnline/online/issues/7425)
> fix:navigator hyperlinks line-breaking on chrome and firefox

- browser/src/control/Toolbar.js
- wsd/ClientSession.cpp
- Allowed downlaod options for PDF/PDF as /EPUB
- PDf/PDF as/EPUB will be downlaod in read only mode
Change-Id: Ic6e0c4a16fa5dffc61e61fd4ece9aeeaec1450b9
* Resolves: #6653 
> Fix downlaod options (PDF/PDF as/EPUB) in read only mode

- browser/src/core/Socket.js
- specifically a case where coolwsd is cleaning up the document we don't want to give up on clientside and show the error message to user
Change-Id: Ie75fa3e19f97ca18acc8e881813d6c617fc9f7b7
* Resolves: # 
> browser: don't show socket error message if we are reconnecting

- .github/workflows/helm-release.yml
- kubernetes/helm/collabora-online/Chart.yaml
- from the logs Error: error creating GitHub release helm-collabora-online-1.1.5: POST https://api.github.com/repos/CollaboraOnline/online/releases: 422 Validation Failed [{Resource:Release Field:tag_name Code:already_exists Message:}]
Change-Id: I7b10e972564eae2cd6ad2146470d16fd05401361
> chart-releaser: fix 422 Validation Failed

- cypress_test/integration_tests/common/helper.js
added and rearranged new parameters in the reload function call, its safe because so far all the calls to reload are made using only three parameters...
Change-Id: I8fa8e4b1e20de0af16368cb23ca641b8d7186bfc
> cypress: refector mismatching parameter in function call

- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.Header.ts
- browser/src/control/Control.RowHeader.ts
problem:
In Calc click on a row header and drag the mouse. The selection does not follow the mouse, selection only appears when you release the mouse button
Change-Id: I510f35d9f61fca63a619e83c04ff340f9578f5d2
> calc: select whole row/column on mouse drag

- browser/src/control/jsdialog/Widget.FormulabarEdit.js
problem:
In a spreadsheet, click on a cell with content,
In the formula bar, select the content in a way that the mouse key is lifted outside the edit field Note how the formula bar doesn't get into edit mode, but you can still edit the content
Change-Id: Ib4f193b897d57e0ffa9c3bfdd598e0c3c4201195
> formulabar: select formulas on mouseleave event

- browser/src/control/Control.JSDialog.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
Make sure we don't expect response from server for online-only component: dropdown which doesn't have corresponding widget in the core
fixes regression on close from:
commit a23adac78c34d3ea1717954fcab1a3caaeef0bbb
browser: fix undefined property 'isPopup'
> jsdialog: close dropdown properly

- browser/src/layer/marker/TextInput.js
This reverts commit 9b3e115fb50ae8bdf998b08425e340e8b986a3c1. It was meant to have been dropped without being merged, but #7619 was merged with it in
Change-Id: I698c7a0aa680a1b8155c08c8d292f609522fe347
> Unrevert "Stop onscreen keyboard when panning calc on tablet"

- browser/html/framed.doc.html
- browser/src/map/handler/Map.WOPI.js
* Resolves: # 
postmessage: Added `Show_StatusBar` and `Hide_StatusBar` to show / hide the status bar, like with the ui_defaults.
> postmessage: Added Show_StatusBar and Hide_StatusBar

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
When a parent comment is removed, child comment is disabled.
* When a parent comment is removed, the children of that comment are not informed.
* We have adjustParentRemove function. ** Function wasn't handling the "parent is removed" case. ** Function was handling the "child is removed" case in a wrong way. Children list has pointers, not indexes.
* When a parent is removed, child wasn't shown. Now we re-set the display property in case it was set to 'none' before.
* getSubRootIndexOf function was trying to continue with index=-1.
On mobile, a reply was added twice, fixed.
Change-Id: Id8f95bbe1cb78bf93bf35fe73a6e86203455691c
* Resolves: # 
> Bug: When a parent comment is removed, child comment is disabled.

- browser/src/layer/tile/CommentListSection.ts
Lack of "parent" property was causing inconsistent behaviour for redlines.
Change-Id: Iaa2424aeee160a9b28d6b0a29b456ddbc3a1b620
* Resolves: # 
> Initialize parent for red lines.

- wsd/ClientSession.cpp
- fix: disabled 'Action_Save' postmessage when HideSaveOption is true
This reverts commit 34f3dd4a625796e5be41176184caee5381176b4c.
> Revert "wsd: disable ctrl+s when HideSaveOption is true"

- browser/src/control/jsdialog/Widget.DrawingArea.js
Thickness dialog has an image in. When the image render is delayed we are getting image size 0x0. That wrong size caused wrong resizing of the parent containers. To show better result, we need to get image's actual size from core.
Change-Id: I207fd2fcca63deee21f51ef34c1ad670e15afd87
* Resolves: # 
> Fix the thickness dialog is shown cut

- wsd/DocumentBroker.cpp
Similar to commit eb5c86a4d32d4e84a0e6dddaa6c4b5772435b85f
(DocumentBroker::saveToStorage: guard against nullptr _storage,
2020-10-26), with the same input.
Change-Id: I17ac2bc12ba086d16ccbf3d5c758e081a32cbf5a
> doc broker: handle no _storage in uploadToStorageInternal()

- browser/src/control/Control.JSDialogBuilder.js
Before it was impossible to correctly target one dimensional menu
entries such as Help, About, Feedback and Latest updates.
This affects places such as Mobile: hamburger menu where now menu entries
get automatically assign an additional css class based on its data.id.
Note: we could also employ the same thing within explorableEntry if
needed. But that's outside of the scope of this change.
Change-Id: Ib50cf1e29f4fae072b8739c76e7facaa540c0ad5
> menuItemHandler: add additional identifier as css class to ui-header

- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- uses new lok_allow setting to provide such list
- for backward compatibility uses also all post_allow and storage.wopi entries
- Used for example in: PostMessage Action_InsertGraphics, =WEBSERVICE() function, external reference in the cell
> Add list of allowed data sources

- browser/src/layer/tile/CanvasSectionContainer.ts
Invalidations were not cropped to the split pane, such that large invalidations that crossed from the mane pane over another top/left split pane, would cause partial re-render, flicker and other problems.
Regression from: 0453140f6180c4f82ec66c9515014b7341d732c4
Potential fix is to have a complex multi-rectangle clip region, or to only do this for simple cases, which are common: of invalidation within a single split pane, doing a complete re-render elsewhere.
Change-Id: I255806286f6c80a233d4c6ade2bcb4e12f2bf753
* Resolves: # 
> calc: split pane mis-rendering.

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/map/handler/Map.WOPI.js
Change-Id: Idaa86f7a936a282c636fa0532ab165c6977db873
* Resolves: # 
postmessage: Add a show/hide command
New postmessage `Show_Command` and `Hide_Command`.
Pass a command name (uno or otherwise) in `Values.id`.
Will hide the corresponding toolbar, menu and notebookbar items.
> postmessage: Add a show/hide command

- wsd/DocumentBroker.cpp
To reproduce:
./clientsession_fuzzer -max_len=16384 fuzzer/data/crash-32e5136d2291e6c5fa99aa5942acded42b66a528
Failed with:
#7 0x7f1aeb9c9cf1 in __assert_fail (/lib64/libc.so.6+0x42cf1) (BuildId: f732026552f6adff988b338e92d466bc81a01c37)
#8 0x55a9f13968a5 in DocumentBroker::forwardToChild(std::shared_ptr<ClientSession> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, bool) /home/vmiklos/git/collaboraonline/online-fuzz/wsd/DocumentBroker.cpp:3613:5
#9 0x55a9f1676a9a in ClientSession::forwardToChild(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, std::shared_ptr<DocumentBroker> const&) /home/vmiklos/git/collaboraonline/online-fuzz/wsd/ClientSession.cpp:1414:23
#10 0x55a9f166f96a in …
> wsd: fix missing session handling in DocumentBroker::forwardToChild()

- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
Also add state dumping of tile on the fly statistics per session.
Change-Id: I8413cdfd489be3c238738f95d9d5c4aa177ff262
* Resolves: # 
> Refactor: move tile limit accounting into ClientSession.

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.TopToolbar.js
- browser/src/map/handler/Map.WOPI.js
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
This disable being able to pick up a local image. Handle the UI as well. To be used with `EnableInsertRemoteImage`
Return `DisableInsertLocalImage`: true as part of the WOPI CheckFileInfo reply
Change-Id: I1925f804433a7bda6025cb65b0943d78927bea15
* Resolves: # 
> wopi: Added DisableInsertLocalImage

- kit/Kit.cpp
debugging some intermittent failures in UnitBadDocLoad I see that there are some duplicate jsdialog messages appearing which is easily reproducible by just opening test/data/corrupted.odt in online.
probably has been like this since:
commit 7f7019772316ade43f2241e7f99e35c20424768a
Date:   Mon Dec 28 11:37:27 2020 -0400
kit: enable input process when early dialog show
and possibly not the problem I was originally trying to chase
Change-Id: I7aa342e86ad9ae73082cb71f1b2c9b2bf0f212b9
* Resolves: # 
> duplicate jsdialog messages seen in UnitBadDocLoad

- browser/html/framed.doc.html
Change-Id: I6337029fe1eeffb7f20acaa100602ea44a0dbc63
* Resolves: # 
If JSON.parse() failed this cause an error that lead to the button click considered
like a form submission.
> framed.doc: if entering bad message data, recover

- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
so the launching site can query if wasm is enabled to see if it needs to insert the required headers, so we can then in turn make it optional on those being set to also require matching headers.
Change-Id: Icd73081809abb8098c21bc61a8357869db45ff6c
* Resolves: # 
> add hasWASMSupport to capabilities

- browser/Makefile.am
- wasm/Makefile.am
The warning is:
em++: warning: running limited binaryen optimizations because DWARF info requested (or indirectly required) [-Wlimited-postlink-optimizations]
With an non-debugging build dropping gseparate-dwarf for online.wasm gives an approx 13M saving.
And leave gseparate-dwarf  enabled for debugging builds
* Resolves: # 
> use of gseparate-dwarf can block some optimizations

- browser/src/layer/tile/CanvasTileLayer.js
otherwise the carefully retained startup log message don't appear in a non-debugging online version
Change-Id: Ie4caf3462539e07f14f6c84bccab47fcbe9d5203
* Resolves: # 
> enable window.logging before dumping delayed log

- browser/css/cool.css
- browser/src/control/Control.IdleHandler.ts
- browser/src/docstate.js
- browser/src/dom/PosAnimation.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
- browser/src/layer/tile/ImpressTileLayer.js
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
Reverts all the previous comment autosave commits and implements a new approach.
Original approach before comment autosave:
When we save a new comment, original DOM element which user was editing
is removed from the DOM and new comment DOM element is created from the data and message sent by core.
Previous comment autosave approach:
When we save a new comment, original DOM element which user was editing
is not removed but kept in editing mode. We register the comment message sent by the core
but react and create new comment DOM element only after user clicks on save or cancel.
This lazy initialization caused many regression due to juggling of the new and old comment DOM element.
All these problems were in JS side only, reloading doc would bring comment in correct …
> Annotation: revamp comment autosaving

- browser/src/layer/tile/CommentSection.ts
it was previously required to handle comment scrolling separately but not anymore it was introduced in a3e59d1
current problem:
when a comment is very long that it overflows and has a scroll bar, it is only possible to scroll using the scroll bar and mouse wheel didn't work
fixes #7735
Change-Id: I6d9f85c61b837f86e021a795e8af43b375a318d1
* Resolves: #7735
> annotation: avoid wheel event handling for comments

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.UIManager.js
Change-Id: I4ccc93dabb4dd260338d5a941b18ebaf8e42b1ad
- previously, when document was getting idle, it was
showing a snackbar "The server is disconnected" which
unnecessary plus the snackbar was persistent even
after reconnection.
- There are two scenarios to be tested,
1. It shouldn't show snackbar on idle
- Set per_document / idle_timeout_secs to something small, eg. 30,
- Open a document, and wait until it idles out.
- make sure it doesn't show "The server is disconnected" snackbar
2. It should show "The server is disconnected" snackbar when you shutdown
the server, when you start the server again snackbar should disappear
* Resolves: # 
> fix: persistent snackbar after the document get idle

- wasm/README
the default suggestion uses --enable-qt5 which isn't needed for LOKit and breaks finding custom notebookbar widgets so online notebookbar doesn't work with it.
Change-Id: I644924a0f8cdb01d4ec20d70ff7aedb27a2c899f
* Resolves: # 
> update wasm.README for distro-config

- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
- browser/src/core/Socket.js
- common/Log.cpp
- common/RenderTiles.hpp
- config.h.in
- configure.ac
- wasm/wasmapp.cpp
- wasm/wasmapp.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/RequestDetails.cpp
- wsd/RequestDetails.hpp
- wsd/Storage.cpp
- configure: enable rtti with sanitizers on C++ TUs only
- wsd: reduce includes where possible
- configure: WASMAPP is now defined for WASM targets
- wasm: header include cleanup
- wasm: truncate string only if will log
- wasm: disable file and color logging
- wasm: log to stdout instead of stderr
- wasm: browser: add UI button to switch modes
- wasm: wsd: switch modes handlers
- wasm: wsd: make switching wasm-only
- wasm: wsd: switch modes handlers - check and save
- wasm: wsd: client handler to switch to disconnected
- wasm: wsd: coolwsd remembers disconnected mode preference
> WASM Switching

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/WriterTileLayer.js
There was a bug in Writer not allowing to successfully reconnect after idle state if we were not a first view in the initial document. Let's update view id even if document size wasn't changed. Added also additional error logging to be sure we never use -1 viewId which is a default "bad value" when we enter some unwanted state in the core.
1. set per_document.idle_timeout_secs to something small, eg. 30, so sessions time out quickly,
2. Open a document with 2 sessions (remember which one was loaded first - A, important!)
3. wait for it to idle out in both sessions
4. activate SECOND session (B) by click on the document area
Result:
in the browser console you can see an exception:
Exception TypeError: this.map._viewInfo[this.map._docLayer._viewId] is undefined emitting …
> Update viewId in Writer after recover from idle

- wsd/FileServer.cpp
[ websrv_poll ] ERR  FileServerRequestHandler: File not found: Invalid URI request: [/browser/515f66e2bc/soffice.data.js.metadata].| wsd/FileServer.cpp:738
Change-Id: I6e4bb8a5a617f4ff8921430eae1f23147fd1a8cd
* Resolves: # 
> serve wasm metadata

- browser/src/layer/tile/CanvasTileLayer.js
Since core commit 690d4eb71509649ad147cfe60f5b97e2cfaaa519 (tdf#43100
tdf#104683 tdf#120715 sw: cursor on spaces over margin, 2022-07-04)
the cursor travels outside of text body area in Writer. Desktop view
doesn't follow the cursor in that case; the problem in Online was
that its view did follow the cursor. This resulted in the following
scenario:
1. Have a document with a thousand of trailing spaces in some line,
before a word that would appear on a next line;
2. Put cursor to the beginning of that following line;
3. Press backspace (or left arrow key)
This resulted in the view jumping far to the right, with the page
being completely out of the view; the user only saw an empty screen
without any text, which was highly confusing.
Fix this by limiting the coordinates in _onUpdateCursor; …
> Do not scroll the view outside of page bounds

- browser/src/layer/tile/CalcTileLayer.js
We were using old cursor data after recovering the view from idle state. For the user there was impression that view jumped at some point - caused by other user action. But it was just an update to real cursor position which scrolled view to it, because previously we were showing some other place in the spreadsheet.
Steps to reproduce bug:
1. Open spreadsheet with 2 views
2. B should have cursor in the bottom part of sheet, let's say row 600
3. Wait for idle in both sessions
4. Open the same spreadsheet with some other user C
5. C does some action on row 300 and goes away (closes tab)
6. User B activates view and selects row 600
7. User A activates view (he should be at the top still)
8. User B changes font size using dropdown in notebookbar, or double clicks on any row header
Result: …
> Refresh cell cursor after recover from idle in Calc

- browser/src/control/jsdialog/Widget.TreeView.js
- We should fire `active` state call back for selected color value in filter by color
- it will directly apply filter to columns
- this change is consistent with LO
Change-Id: I90977cff67cda1bca78c7d60c132bd0685cadbaa
> Fix filter by color in Calc (auto-filter)

- wasm/wasmapp.cpp
ClientSession::handleTileInvalidation returns early with _tileWidthPixel (etc) of 0 because _tileWidthPixel (etc) never get set
These are supposed to get set from 'clientzoom' which the javascript side sends. clientzoom arrives, but the attempt is made to dispatch via a thread and during startup there are enough messages dispatched via threads to overwhelm wasm
```
bundle.js:56376 ================ handle_cool_message(): 'clientvisiblearea x=-3915 y=0 width=20640 height=7980 splitx=0 splity=0'
bundle.js:56377 Tried to spawn a new thread, but the thread pool is exhausted. This might result in a deadlock unless some threads eventually exit or the code explicitly breaks out to the event loop. If you want to increase the pool size, use setting `-sPTHREAD_POOL_SIZE=...`. If you want to throw an …
```
> wasm often doesn't get tiles after invalidates

- wsd/COOLWSD.cpp
disable this with VCL_NO_THREAD_SCALE for wasm
"Yacht.odt" document with lots of large images fails to render:
Tried to spawn a new thread, but the thread pool is exhausted. This might result in a deadlock unless some threads eventually exit or the code explicitly breaks out to the event loop. If you want to increase the pool size, use setting `-sPTHREAD_POOL_SIZE=...`. If you want to throw an explicit error instead of the risk of deadlocking in those cases, use setting `-sPTHREAD_POOL_SIZE_STRICT=2`.
Change-Id: I8b2f994d2d3d23f8a0043f0c7fefa4d5e250b8bc
* Resolves: # 
> wasm: limit threads using for scaling

- browser/src/control/Control.Header.ts
problem:
while resizing row/column it would select all the rows and column user hovers over
regression from: 87a55af
Change-Id: If786c57222b9bb89ac3faa1e645acc223a8dcd7e
> calc header: avoid selecting row/col while resizing them

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
Bug:
When a parent and a child comments are removed then user reverts the action respectively:
* Child comment is revived first and it cannot find its parent.
* Add a possibleParentCommentId to use in case also the parent comment is revived.
* Consider the child comment as a parent until parent appears.
Other changes:
* Remove duplicate call to updateIdIndexMap.
* Remove duplicate call to unselect.
* Remove duplicate call to adjustParentAdd.
* Reorder the 'remove' operation's rows: To avoid unselecting the comment after it is removed.
Change-Id: I2247b23c710236c578b5b5c78d2b7bb45f7a51b4
* Resolves: # 
> Fix bug in undoing deletion of a parent comment.

- wsd/DocumentBroker.cpp
When user switches to dark theme, previously requested tiles' normalizedViewIds may need to be updated.
Issue:
Users sometimes were getting tiles from the wrong theme.
Change-Id: Ie3324eb3f4879da5bfd0738513409e190422a9c0
* Resolves: # 
> Make sure to set the correct normalized view id for the tiles.

- browser/src/core/Socket.js
from idle
The following scenario was affected:
- user A and B both goes idle
- user B starts typing
- user A reconnects, all tiles updated by user B were not getting reflected for user A
Mismatch of canonical ids was causing the issue. On reconnection, tilecombine messages were sent before uno:ChangeTheme can update the canonical id on server side, therefore the received tile cache from server were from old canonical id(https://github.com/CollaboraOnline/online/blob/4a8974d107896c7fb4b7c35e326b52a986144a8b/wsd/ClientSession.cpp#L1379).
By reseting the previousTheme on connection we make sure there after canonicalidchange we invalidate all the tiles
Change-Id: I874bfe0bd71d176bacf0c7aa768e49613535ebd5
* Resolves: # 
> fix: tiles not updated after reconnection

- browser/src/layer/tile/CommentSection.ts
now as we only allow one comment to edit at a time, we don't need to check if any comment is being edited, we can hide all comment except the one being edited
Change-Id: Ibee2b61fc6ba873231a05e5e1d2dab210491c68f
> annotation: only don't hide comments which are editing

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
Sometimes we only request and only get two rows of tiles in writer on an initial load. Most frequently I see this with a non-debug online server via nextcloud of the default "Welcome to Nextcloud" docx in firefox in the 2nd or 3rd tab of opening the same document. While the page doesn't visually resize there is a resize delivered after the initial request of tiles.
Change-Id: Id263adbbd98ad0a7c6143d241d0d91e1c28eaac5
* Resolves: # 
> Sometimes we only request two rows of tiles in writer on an initial load

- browser/src/layer/tile/WriterTileLayer.js
if (command.viewid) will not allow set to 0.
This is fillowup for commit f3baeb25b19d8a6200858ecaafe56314836ff73a Update viewId in Writer after recover from idle
> Update viewId also if equal 0

- browser/html/framed.doc.html
- browser/src/map/handler/Map.WOPI.js
They allow respectively to switch to fullscreen, or to start the presentation in impress in fullscreen
Action_FullscreenPresentation can get the following arguments:
- StartSlideNumber: the slide to start at
- CurrentSlide: start at the current slide The options are exclusive to each other. StartSlideNumber takes precedence
Change-Id: I4d97eadf8c119e70e5738df4063d209feb5db793
* Resolves: # 
Added Action_Fullscreen and Action_FullscreenPresentation post message
> postmessage: Added Action_Fullscreen and Action_FullscreenPresentation

- browser/js/global.js
- browser/src/control/Permission.js
- browser/src/control/Ruler.js
- browser/src/dom/DomEvent.MultiClick.js
- browser/src/dom/Draggable.js
- browser/src/layer/vector/Path.Drag.js
- browser/src/layer/vector/SVGGroup.js
- browser/src/map/Map.js
- browser/src/map/handler/Map.DoubleClickZoom.js
- browser/src/map/handler/Map.Mouse.js
- browser/src/map/handler/Map.Scroll.js
- browser/src/map/handler/Map.TouchGesture.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/calc/delete_objects_spec.js
- cypress_test/integration_tests/mobile/calc/image_operation_spec.js
- cypress_test/integration_tests/mobile/calc/sheet_operation_spec.js
- cypress_test/integration_tests/mobile/impress/delete_objects_spec.js
- cypress_test/integration_tests/mobile/writer/delete_objects_spec.js
Touch unification (https://github.com/CollaboraOnline/online/commit/b3bff28bede07a48cdecefcda14a6fc9da86e4bb, change ID
I9016fc15ad3ccb3664af348fdcdca006495b0778) was a rework of the input
system to better support touch devices, but unfortunately it caused some
fairly serious regressions. This commit fixes the following:
- Triple/Quadruple clicking was no longer recognized on non-touch
devices.
- There were some issues recognizing wrapped events
- Pens were considered to be touch devices, but this broke some
remote/virtual machine setups. It's possible that this change will
cause a regression for apple pencil users. I plan to get an Apple
pencil to test whether preventing pens from being touch devices breaks
the Apple pencil workflow instead
- manualDrag was taken to mean "is on a touch …
> Followup to unified touch handling

- browser/src/control/Control.DownloadProgress.js
The initial copy action already used Cmd+C but when a download is required the snackbar actions were still requiring Ctrl-C which is not common on macOS.
Change-Id: I24d9e01bc23a1dc32a1362f48775c6890f5a77c8
* Resolves: # 
> fix: Use proper command + c keyboard shortcut for copy actions on snackbar

- browser/css/spreadsheet.css
- browser/src/control/Control.Tabs.js
- drop zone indicator added to the left of all tabs
- additional drop zone indicator added to the right of the last tab
- added drop zone container at the end of tabs for the last drop zone indicator
- div#drop-zone-end-container element also adds a space to the end of the tabs so that the last tab can be seen easily after scrolling to the end.
Change-Id: I25a87bc1798b94c5f294532d308cd46292ef1795
* Resolves: #7813
> Calc: improve drag&drop functionality of sheet tabs

- browser/js/global.js
- browser/src/control/Toolbar.js
- browser/src/layer/tile/CalcTileLayer.js
This relies on core change I5e6c93c64af0d201a8ec045fea5546e189baca74 (https://gerrit.libreoffice.org/c/core/+/160313) as the logic to keep the cell focused is from there.
Here we set the new option when there is an onscreen keyboard hint given by ui_defaults or a postmessage. As ui_defaults are set at page load, we need to wait to send our message until we're initializing everything else to set our options. Additionally, we need to use the socket directly rather than sending this through the map so that this bypasses things like readonly mode
Change-Id: Ie6d80c0e1ebca607b9d705b673ab8008fae39260
* Resolves: # 
> Stop onscreen keyboards closing when used to move

- autogen.sh
This is backwards-compatible and core.git autogen.sh executes
configure, so it eliminates a pointless difference.
Change-Id: I897bd2f6464201a19e26e55006cd52727abdfc41
> autogen: conditionally invoke configure at the end

- browser/src/control/Control.Tabs.js
- we need to remove 'tab-drop-area-active' class after a sheet tab is dropped, otherwise drop
zone indicator will still be shown after dropping
- this fixes the bug from f8433d323d2f49852501961c7949300b4a59a512 Calc: improve drag&drop functionality of sheet tabs #7846
Change-Id: Iff7ea455452c431907cc7534cbd111e7b4f037d8
* Resolves: # 
> Calc tabs: remove drop zone indicator after drop

- Makefile.am
- browser/.eslintrc
As discussed [on Matrix](https://col.la/suppresseslintindevelopment) the set of things we want to pick up in CI and development are different. Specifically, there are some things that only get in the way during development but should not be allowed in merged code. Examples are 'debugger' statemens, dead code (e.g.  resulting from 'if (false)') and unused variables.
After #7822 there are no more eslint warnings, so we can use it as a separate state for these issues that should only block in CI.
This commit adds a new workflow which will run eslint and fail if it receives any warnings, and changes those 3 errors so that they only emit warnings.
It's expected that there are more annoying warnings which I've missed, if you have any please make a followup change!
This commit explicitly does …
> Add a lint workflow to fail on eslint warnings

- browser/src/layer/tile/ImpressTileLayer.js
- cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
problem:
1. Duplicating slide with comment will not have any comment
2. Rearranging slides, causes comments to stay with its previous slide location, i.e: if earlier comments were on the first slide and they are rearranged to be nth slide, comments will be displayed on the first slide
3. Deleting slide, displays comment on the next slide
all these problems are just display problems in online, if you reload the document, comments are displayed correctly.
Change-Id: Ie494761802f133f5f433053456edfd7d55d1312a
> annotation: refresh annotation on part updates

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- fix view jump by adding display `hidden` in js-dialog overlay 
Change-Id: I4e48fd2d7363db53d4bf3a1d85f9897de3b1e91a
> Fix view pushed up in Calc for autfilter popup

- browser/src/control/jsdialog/Widget.TreeView.js
- Added radio buttons in  `filter by color` options which had Checkboxes
- it should have radio buttons same as we have in LO core
- it also makes sense because we only need to apply one filter at a time in cases like `filterByColor`
Steps to check patch
- Open .ods file
- add some dummy data in different rows, but column should be the same
- click on the top cell of dummy data
- got to `DATA` tab and apply `AutoFilter`
- open auto filter popup and select filer by color
- compare previous version with the current patch
- check same thing in LO core
Change-Id: I00b4d84e5117b3c1f05fbc37c61331d2c3bc2a31
> Filter by color options should have radio buttons insted of Checkboxes

- browser/src/control/jsdialog/Widget.TreeView.js
- Fixed filter by color options which had Checkboxes
- it should have radio buttons same as we have in LO core
- it also makes sense because we only need to apply on filter by setting at a time
Steps to check patch
- Open .ods file
- add some dummy data in diffent rows but column should be the same
- click on the top cell of dummy data
- got to `DATA` tab and apply `AutoFilter`
- open auto filter popup and select filer by color
- compare previous version with the current patch
- check same thing in LO core
Change-Id: I00b4d84e5117b3c1f05fbc37c61331d2c3bc2a31
> [Backport to 23.05] Filter by color options should have radio buttons insted of Checkboxes

- browser/src/layer/tile/CanvasTileLayer.js
I noticed that it directly modifies `this._visibleCursor`
which should be our own cursor. So it was not clear if
`modifierViewId === this._viewId` check if something left
from the past or that message can be received with
different viewId...
It seems that received viewId only tells us who "triggered"
the cursor movement, but position in the message is still "our".
It is used with different viewId in Writer but not in Calc.
protocol.txt comment about the message:
The payload contains a rectangle describing the cursor position
and the id of the view which triggered the invalidation. JSON payload.
and seems to be introduced in:
commit https://github.com/CollaboraOnline/online/commit/ffd7151443ee360c7764aaa77f9e7fe5f5d64eee
Date:   Sun Apr 8 00:00:53 2018 +0200
Writer: View jumps to cursor …
> Add explanation for invalidatecursor with different viewId

- coolwsd.xml.in
This can be useful for debug purpose. This allows to use integrator with `localhost` domain and still beeing able to paste/insert some remote content.
> Allow localhost name in lok_allow

- wsd/COOLWSD.cpp
We automatically add allowed wopi hosts to lok_allow. But we expect to have plain host names, we need to remove protocol if it is present.
Example:
wopi - group - host: `https://.*\.mydomain.com`
we need to add: `.*\.mydomain.com` to lok_allow list.
> Remove protocol when adding to lok_allow

- browser/src/control/Control.AlertDialog.js
Insert -> Image (from integrator), when integrator is not configured as allowed. Should not happen with correct config.
requires: https://gerrit.libreoffice.org/c/core/+/161001
> Add warning for blocked external image insertion

- cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
Change-Id: Ia9f2a35f0e334c97565edc4334df943723a958d7
Found this after stumbling on another one introduced a couple days ago. That one was fixed in https://github.com/CollaboraOnline/online/pull/7883.
Ran the test with `make check-desktop spec=calc/row_column_operation_spec.js` and the other testpoint passed.
> Remove inadvertent it.only to re-enable tests

- browser/css/toolbar.css
- in Compact/Classic mode typing text are dark in dark mode
To reproduce:
- change to dark mode and select Compact mode
- type in input field of Font or in Font size
- without this patch, color will be dark in dark mode
Change-Id: I4510001cfdf26acf8419eb0aa4ee3611b0a51b09
Before:
After:
> Fix text in font and style dropdown types dark in Dark mode

- wsd/ClientSession.cpp
here std::ceil is operating on the result of an int divided by an int so the input is already an effectively floor-ed int result of the division so the ceil doesn't do anything
so we end up filtering out some of the invalidates for tiles in frozen panes.
Change-Id: Ibfb25fdfdfb84735ca9410f8250d2e5b9fa1070e
* Resolves: # 
> missing tiles in multi-pane spreadsheets

- cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
- cypress_test/support/index.js
Even after https://github.com/CollaboraOnline/online/pull/7877, I am still not happy with the cGet logging. In order to get reasonable logging on failure, the extra assertion `.should('exist')` is required, which is explicitly discouraged in the cypress docs, and is easy to forget. And as a side effect of including .should('exist'), several noisy lines are logged each time, and there is no way to disable it (https://github.com/cypress-io/cypress/issues/7693).
cy.getFrame() does the same thing as cy.cGet() but with simpler code and a slight reordering of commands. It also produces reasonable logs on both pass and fail.
The behavior should be identical so replacing one command with the other should be easy. However it is used thousands of times so it will take some time to do the changes …
> Add new Cypress command cy.getFrame()

- browser/src/layer/tile/CommentSection.ts
this caused problem when new doc is loading and we are settings up comments, but they are not initialised and marked as being in editing. i.e: this will cause problem with showing reply count(in collapsed view) initially
Change-Id: Ia688ca0bfc37dd925bd74dc5826d43fdb37c81db
> annotation: if comment is not initialised its not in editing mode

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
use strict datatypes for the properties where possible, also allow to add new properties dynamically
Change-Id: Ia2eb850f61031f91b0e37339475e1ca4e768dad1
> typescript: use defined types for CommentSection properties

- browser/src/layer/tile/CommentListSection.ts
it did not make sense to check for selection if we are unselecting before selecting
problem:
when already selected comment try to modify,
it will not rearrange replies in the thread this caused overlapping of the comments and bad user experience
Change-Id: I276c34301b45951a7051018770e21b4970603861
> annotation: remove redundant condition

- browser/src/layer/tile/CanvasTileLayer.js
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/DummyLibreOfficeKit.cpp
- wsd/ClientSession.cpp
* These changes are made primarily for reading the hyperlink data from the document in readonly mode.
* Added readonlyclick event.
* Added readonlyhyperlinkclicked event.
* And the handlers for these.
When user clicks on document in readonly mode, a readonlyclick event is sent to the server. Childsession checks if there is a hyperlink at the clicked location. If so, the information of the hyperlink is sent to the client.
Change-Id: I9c104a1ec770491725337b9bbb1e2d1c2851321b
* Resolves: # 
> Changes for handling readonly mode click events:

- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/support/index.js
Change-Id: I4f54b35f01b41bfb47a1d5d359de5cdab4cb9640
Use cy.getFrameWindow() custom command added in https://github.com/CollaboraOnline/online/commit/5979eb9a1f7d68ce3ff326a1567e96767c8a60eb
Replaces and removes helper.getCoolFrameWindow()
> Use new custom command cy.getFrameWindow()

- browser/src/control/Toolbar.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/WriterTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
Change-Id: I6e2520035d54b9de2b4cf8e015741aaae517fee1
I'm trying to add additional debug tools for automated input but the current structure was not conducive to adding new tools. The mess clearly just comes from years of adding one tool at a time. I think it's time for a refresh.
Here are some issues this change addresses:
- Each tool getting added and activated in a different way
- Tools relying on other tools
- Required knowledge of leaflet layer internals
- Code in many far apart places
- Unclear or incorrect names
- Unclear ownership or intent of variables
Now, each tool gets added with a call to `_addDebugTool`, and its name, setup and teardown code are declared all in the same place. This will make it much easier to add or modify new tools, and to add new functionality to the debug …
> Refactor debug menu

- browser/src/map/handler/Map.Mouse.js
This fixes view jumps in the Calc when some user tried to drag a selection but did it very quickly so it was interrupted by the _mouseOverTimeout callback.
Timer was introduced in commit 72c407e0ed5c3a9ffd2ae518f9f5d4407e1f5d61 loleaflet: support mouse cursor calback
But we noticed the issue recently. I remember that dragging the selection was not working some time ago, it is possible that it was fixed and because of that we experience this bug.
What it does is that it stops dragging mode in half-done state so then other views sometimes use the leftover data. To be 100% fixed it should be also protected on the core side.
1. Open calc in 2 sessions
2. A selects some range of cells (for example 3x3)
3. A clicks inside selected range and holding the mouse button does …
> Calc: don't stop dragging the selection on quick move

- browser/src/core/Socket.js
- browser/src/errormessages.js
- before this patch when socket connection failed, we used to show the same error for socket connection failure and send the 'Action_Load_Resp' with same errorMsg
- now we show/send different message for unauthorized and loading failure
Resolves: #7709
Change-Id: I71b1b7f8e2eca93790d068583370787825911a41
> improve error message on invalid WOPI host

- coolwsd.xml.in
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/COOLWSD.cpp
This applies the cgroup memory limit, if set,
such that if it is lower than the configured
memproportion percentage, we do not exceed it.
Otherwise, we risk running out of our cgroup
limit and by then it is too late to do anything
but die due to OOM.
This also moves the logging of the cgroup memory
stats from COOLWSD into Admin, to avoid duplicate
logging.
Also updated the description of memproportion
config entry to account for the cgroup logic.
- wsd: admin: minor clean-up of memory-tracking members
- wsd: admin: use the cgroup limit as available memory
> Memory Accounting

- browser/html/cool.html.m4
- ios/Mobile/Info.plist.in
When building the iOS app, the %SAVED_UI_STATE% does not get replaced with a quoted string during the build and the resulting unquoted string causes document loading to stop.
Also, eliminate warnings when running in Xcode by adding missing CFBundleTypeRole entries in the iOS app's Info.plist.
> Set window.savedUIState to false in iOS app

- browser/src/control/Control.UIManager.js
- wsd/ClientSession.cpp
- allow `ChangeTheme` event to update document theme in read-only mode
Change-Id: Ic64bc61011a9e053c105e5c7540dddd4eb530681
* Resolves: #7888 
> Do not supress ChnageTheme event in readonly mode for any document

- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
Below cases are covered in current patch
- `Filter by Color` in autofilter should have radio buttons.
- Changes should be applied when we select any option from `filter by color` submenu.
Change-Id: I1a757e09be81df934b46d48f71e8be28fc48c984
> Add more cypress test in Autofilter (Calc)

- browser/src/control/Control.DocumentRepair.js
Change-Id: Ib8b745fd10aca2eea2e829ad42cf1d91f7ff2129
* Resolves: #7795 
We are receiving actions dates in ISO8601 format from Core. We can convert them to both local date and a human-readable format.
Before:
After:
> Make 'File > Repair' date and time human-readable

- wsd/COOLWSD.cpp
Fixes #7885
Be more flexible and allow to run service with configured hosts which doesn't work with lok_allow (invalid regular expression for std::regex which is used in core).
This change instead adds error report in the logs, without it it was crashing when any host was not compatible. For example when using domain like:
`*.example.com` which should be `.*\.example\.com`
> Don't pass invalid hosts for lok_allow #7885

- browser/src/control/Toolbar.js
- browser/src/core/Socket.js
- wsd/ClientSession.cpp
Share a single emission function. Events are re-parsed and emitted and adjusted in ClientSession; JSON escape event names.
Change-Id: If489d516bf20d5ec34cfe61f7e4fb09cf2e14bf2
* Resolves: # 
> traceevent: re-factor and cleanup trace event emission.

- test/UnitWOPISaveOnExit.cpp
- wsd/DocumentBroker.cpp
This forces autoSave when always_save_on_exit
is true. This is needed so we can guarantee
that we don't have modification and that
we upload if there has every been one.
The latter case is checked in
DocumentBroker::needToUploadToStorage(),
which is called from
DocumentBroker::checkAndUploadToStorage().
A new test reproduces the issue and defends
the fix.
Change-Id: I0b2105a57cfd7049ba7b1f63e62a700fdc3744c2
> wsd: force autoSave on always_save_on_exit

- browser/html/framed.doc.html
This was introduced in https://github.com/CollaboraOnline/online/pull/7514
Change-Id: I98b9b5b04742541904afa2361ac961498a54c29d
* Resolves: # 
Added new test UI for Get_User_State
> framed.doc: Added postmessage for Get_User_State

- wsd/ClientSession.cpp
- wsd/TileCache.cpp
Improve logged message: setclientpart syntax error
Don't show error to the user as it is not critical
but put in the logs more meaningful message so we can debbug
later.
Improve logged message: cache miss
so it doesn't sound that serious like previous message
and is less generic and more easy to find in the code
> Log messages improvements

- browser/src/map/handler/Map.TouchGesture.js
It internally handles the mouseup. So we don't send it again.
Without this change, context menus can't behave normal. Because mouse pointer is set to somewhere else with the mouse up event.
Change-Id: I719565b1ce192045250f9217e971725d8cc1003b
* Resolves: # 
> Core side handles the right click with mouse down event.

- common/Util.cpp
- kit/Kit.cpp
Using the aggregated file saves a hundred+ system-calls per pid we're getting data for, and presumably also lots of time.
Change-Id: I41c40982ebbec44aba72a1d15dabf24a8986f59e
* Resolves: # 
> Use /proc/self/smaps_rollup for improved perf #7927

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
This is partial revert of "jsdialog: use open/close instead of toggle for dropdowns" commit 0833ec64894fc6815748bb9ab7f7cc02073842a9.
Which introduced "state" variable which was desynchronised with core in some cases. Now directly call desired close command in closePopover.
This fixes bug:
1. Click on the sidebar's Paragraph's "Ordered list" dropdown arrow;
2. Click on any kind of the list (so that the current paragraph gets the chosen list style);
3. Click on the drop-down arrow again, expecting the drop-down to open. Result: you need to click two times to open menu again
> jsdialog: simplify dropdown closing

- ios/Mobile/DocumentViewController.mm
The new WKWebView.inspectable property must be set to YES in order for Safari to connect to a debug version of the iOS app whether the app is running on an iOS device or on macOS.
> Reenable debugging from Safari

- test/UnitWOPISaveOnExit.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
When always_save_on_exit=true we should
still not upload the document when it
isn't modified.
In this case, because we now always
save the document (forced) when
always_save_on_exit=true, and because
saving always generates a new file on
disk, with a new timestamp, we couldn't
detect that there are no modifications.
We now still force save, but ask Core
to skip it if the document is unmodified.
This is safe since we now always issue
the save, but rely on Core to do the
right thing. When the document is saved,
we do the normal upload as in that case
we know we have a new version of the
document, which must be uploaded.
Worth noting that the closedocument
command doesn't trigger the same path.
To reproduce the issue, we need a new
test that disconnects, instead of the
graceful closedocument …
> Do not upload unmodified document

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ib6cb1080780f75dc0ea75930c757567e90c46bd8
Typer: Type text into document. One keystroke every 50ms.
Move around sheet: For Calc only. Move to random corner or center of sheet and click on a cell there. Repeat every 1s. This expands the sheet very quickly.
Toggle dark mode: Toggles dark mode every 3s.
Add/Remove shapes: Adds a shape then removes it 2s later, repeat every 4s. This is a bit unstable because I couldn't reliably select the shape again, so it relies on the shape remaining selected for 2s. So it can't really be mixed with Typer or Move around sheet.
Zoomer: Select a random zoom level every 1s.
None of these makes for a complete or realistic user. Also having more than one of these selected is quite chaotic. It's fine if there are multiple windows and each has one tool …
> Add automated user debug tools

- browser/src/dom/DomEvent.MultiClick.js
The 'addMultiClickListener' fires 2 times
'triple click', because it also registers
for 'quadruple click' too.
Change-Id: Iee7565163e64373c87016743c06fe1cc084b80f4
> browser: fix triple click event

- browser/css/cool.css
It is a bug from Firefox, according to records
https://bugzilla.mozilla.org/show_bug.cgi?id=292284
The vertical scroll bar requires minimum height to render.
Change-Id: I93b06c625bc98c307dde0c1d6331d457ff99baa5
> browser: adjust initial annotation height

- browser/src/control/Control.IdleHandler.ts
- browser/src/core/Socket.js
- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
Don't make view inactive when dialog is opened
If user opened any dialog and we got blur event on
map - it was doing the view inactive by sending
userinactive message to the server and ignoring any
meesages we tried to send. Because of that it was
impossible to test in cypress dropdown dismiss by
click outside popup (due to losing focus from map).
This is regression from rework:
commit 86e8491707c8f25b106909a340f45edd65e704e5
For .eslintrc change, see: https://github.com/typescript-eslint/typescript-eslint/issues/1824
where we changed:
- if (!this._active || isAnyVexDialogActive()) {
+ if (!this._active || isAnyVexDialogActive() || this.map.jsdialog.hasDialogOpened()) {
Make more precise condition so we check if the dialog is a dim one.
cypress: autofilter dismiss by click outside popup …
> cypress test: autofilter

- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- when migrating document from one server to another using indirection server tiles were not getting updated
- _resetClientVisArea should be called even if there are no changes to the client because the server needs new data even if the client is unmodified.
- changing wireId and invalidFrom values to 0, 0 to force a keyframe https://github.com/CollaboraOnline/online/blob/b1f0834ac45c459ca904406bf32254c074b91c64/browser/src/layer/tile/CanvasTileLayer.js#L7266
Change-Id: I9aa0b34c3b1f157f3e4494568802588e00376d7e
> fix: tiles not getting updated after migration

- browser/js/w2ui-1.5.rc1.js
- browser/src/docstate.js
- browser/src/layer/tile/CanvasTileLayer.js
It will be possible to use "theme colors" then.
It requires core part: https://gerrit.libreoffice.org/c/core/+/161771
sc: announce theme colors with lok callback
> Add color palette selector to Calc and Impress 2

- browser/src/control/Control.JSDialogBuilder.js
Not only quotes must be escaped; JSON.stringify does it correctly.
Change-Id: Idd7deca3cb9154eaece48ef3b197eb75d975f252
> Fixes: #6956 Escape payload strings sent in JSON

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
Change-Id: Id1be5607e15ac23596e527c3e27fca83c91ee380
* Resolves: # 
Many testpoints in this file were sporadically failing. Tests add a comment and then immediately modify it. I'm not sure how exactly, but starting to edit the annotation as it was animating from the top left to the right caused text to be inserted in the wrong spot.
I added a wait directly after saving the new annotations. I ran the tests several times with no failures. Tests failed about half the time before adding the wait.
> Fix failing test multiuser/writer/annotation_spec.js

- common/JsonUtil.hpp
- fuzzer/admin-data/crash-f0458999f81408ca2bc48148d30c0a000b07ea2d
terminate called after throwing an instance of 'Poco::JSON::JSONException'
...
#11 0x7f70540e006a in Poco::JSON::ParserImpl::parseImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) (/usr/lib64/libPocoJSON.so.92+0x4206a) (BuildId: 149b3c1772e35fcbe5692d435f1b06820707bad3)
#12 0x556a70a9511b in Poco::JSON::Parser::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /usr/include/Poco/JSON/Parser.h:202:9
#13 0x556a70a9511b in JsonUtil::parseJSON(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, Poco::SharedPtr<Poco::JSON::Object, Poco::ReferenceCounter, Poco::ReleasePolicy<Poco::JSON::Object>>&) /home/vmiklos/git/collaboraonline/online-fuzz/./common/JsonUtil.hpp:37:50
#14 …
> admin: improve error handling on bad json for updateroutetoken

- browser/Makefile.am
- browser/src/control/Control.IdleHandler.ts
- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
Check for comments in isAnyDialogOpen
As described in the comment there was problem with
userinactive command. This is now solved due to:
commit fa006fc3afacc7c7369ceaed20833c8c9ba05989
Don't make view inactive when dialog is opened
Comment was from commit 6550e713c4bf687931aa721f36d0a28ac70e94f0
annotation: calc scroll vertical to make selected comment visible
-------
IdleHandler: bring back idle timeout for view
This fixes regression introduced in
commit 86e8491707c8f25b106909a340f45edd65e704e5
For .eslintrc change, see: https://github.com/typescript-eslint/typescript-eslint/issues/1824
Where per_view.idle_timeout_secs and out_of_focus_timeout_secs
settings didn't have any effect.
<out_of_focus_timeout_secs desc="The maximum number of seconds before dimming and stopping updates when the …
> Idle Handler fix

- browser/src/control/Control.ColumnHeader.ts
This allows to select several columns (or individual cells) at once,
and then double-click on the respective "border" area to resize them
automatically to their content (.uno:SetOptimalColumnWidthDirect).
Change-Id: I8b19ecb00a6285fec90d73ca09731b4393be6981
> Don't select columns, when clicks are over resize area

- browser/css/cool.css
In old versions of Safari, typing text would not input anything. This appears to be a regression from replacing the input area with a contenteditable div (1d2607e8363dab839e7060ab38612123d284c98f).
This seems to be caused by "Safari has the user-select CSS setting as none by default" (see https://stackoverflow.com/a/31831776/12293760). From my research, this only affects old versions of Safari, but adding this CSS fixes it and does not prevent editing in other browsers.
Change-Id: I708708b87f3169f6f69cab28003379519ce114dd
* Resolves: # 
> safari: fix contenteditable on old versions

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.UIManager.js
See https://github.com/CollaboraOnline/online/issues/7403
Change-Id: I20aa320a6efbbf8ce19eda34c3d5278a601e15fc
* Resolves: #7403 
When you get the idle message, click on the message like you'd click in the document to dismiss. It feels more natural.
To trigger the message, in the JS Console, in the COOL frame, type:
```javascript
app.idleHandler._dim()
```
> Click on a resume message to dismiss it

- browser/src/control/Control.Header.ts
The header highlighting was tied to the position of the cell cursor
so when editing a cell the highlights disapeared with the cell cursor.
This also checks the previous cursor position if there isn't a current one.
Change-Id: I93bf38b42cbaf091511c05e38bfab331e9532f4a
> highlight row/col header when editing

- browser/src/control/Control.ColumnGroup.ts
- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.RowGroup.ts
- browser/src/control/Control.RowHeader.ts
- browser/src/layer/tile/CanvasSectionContainer.ts
Round width and center lines of row/column headers so that they don't overflow in the pixel grid and cause antialiasing artifacts at zoom levels > 100%.
Also use constant linewidth of 1 for group level headers and of size 2 for group controls for the same reason.
110% zoom:
150% zoom:
> Center header/group lines in the pixel grid

- cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
Change-Id: If34a07e6a70f2c4293e8a2eb9d5e3d5fd14258ac
* Resolves: # 
Test was failing because second user wasn't completely reloaded.
> Fix failing test multiuser/writer/invalidations_spec.js

- browser/src/control/Control.ColumnGroup.ts
- browser/src/control/Control.GroupBase.ts
- browser/src/control/Control.RowGroup.ts
- groups was using indexes to find their parent groups.
- this does not work properly and causes following issues: 
- some groups are created but not drawn (so they are invisible)
- some parent groups does not hide their child groups
- this patch:
- removes the index-based search of parent groups.
- implements startPos and endPos based search.
Change-Id: Ia3b85f3d9a032008f8abbc7b38ad2417aa0ec6c8
* Resolves: #7811
> Calc grouping: find parent groups correctly

- wsd/ClientSession.cpp
- regression from https://github.com/CollaboraOnline/online/commit/d118874bee9196206d3de24a89df8700f62cd89b which was a fix for regression from 93b5bdf
- previously we used to send blockingcommandstatus message to the core when we were getting statusindicatorfinish but when file is readonly we load the document first therefore we get the statusindicatorfinish first then wait for the input from the to whether to open the readonly document or not
- now we send the blockingcommandstatus only after we get the first status message which indicates document is loaded and opened
Change-Id: I0f4934e085befa6f9a918ac61a265391b217a2f2
* Things I  tested:
* Resolves: # 
> fix: can't open readonly files

- browser/src/layer/vector/Path.Drag.js
Previously, noManualDrag was not bound to any object. This worked fine in SVGGroup.js because the 'this' that was inferred was the correct 'this', however in Path.Drag.js the 'this' inferred was incorrect. This code path was occasionally called when dragging which caused an intermittent error while dragging objects in draw
This is a followup to Iab0d3bcca588eaed14469597868a9c4e2dcf8488, which I believe introduced this regression
Change-Id: If8657133a1b6c000b1096fb2c822d02d728de80c
* Resolves: # 
> bind noManualDrag in Path.Drag.js

- cypress_test/integration_tests/desktop/calc/focus_spec.js
Change-Id: Ibcd6a2b3d27cbd56d8a24de5f12316bacbd2061f
* Resolves: # 
The test is about typing into the formula bar. The issue was that clickOnFirstCell hasn't finished, so clicking on the formula bar didn't work. Specifically, the accept and cancel buttons weren't visible.
I added a short wait after calling clickOnFirstCell, and cleaned up the code a bit. Also uncommented the second half of the test.
> Fix failing test desktop/calc/focus_spec.js

- browser/css/cool.css
- browser/js/w2ui-1.5.rc1.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Toolbar.js
Make it more unified with "Office" color picker.
Use styling from jsdialog for color picker to match all other ui components.
Unified with existing "Automatic" button for font color.
Before:
After:
Core for comparison:
> Color selector: add no-fill as button

- browser/src/layer/tile/CommentSection.ts
followup for commit 4c70df5
Fixes case:
Uncaught TypeError: app.sectionContainer is undefined
isAnyEdit CommentSection.ts:991
isAnyDialogOpen Control.UIManager.js:1141
_activate Control.IdleHandler.ts:83
_onSocketOpen Socket.js:256
connect Socket.js:72
loadDocument Map.js:326
<anonymous> main.js:117
<anonymous> main.js:137
> Fix uncaught TypeError in isAnyEdit 2

- browser/src/map/handler/Map.Keyboard.js
If there are multiple sheets, you can switch between them with Ctrl+Alt+PageUp/PageDown.
this shortcut has been updated as:
- Ctrl+Alt+PageUp -> go to the previous tab
- Ctrl+Alt+PageDown -> go to the next tab
Change-Id: Ic88adbe6cdd629b002810770bc19dc7af35d4499
* Resolves: # 
> Calc: swap Ctrl+Alt+PageUp / PageDown behavior

- browser/src/layer/marker/ProgressOverlay.js
ensure that progressbar in mobile apps doesn't display 'Collabora Online'
Change-Id: I972b3acdbabc24df8d51643215c7bf5c9d226a65
> ensure that progressbar in mobile apps doesn't display 'Collabora Online'

- kit/Kit.cpp
...not when it wasn't even attempted.
Change-Id: Ide56c46b1a2d99c3639aace430cec099c6afcbf4
> kit: Only log smaps_rollup open failure when it actually failed

- browser/css/jsdialogs.css
- Insert chart in odt
- right click and select properties
- see dialog looks odd
Problem:
- label element after spinfieldunit getting overlapped
- user can not see label tag after spinfield conatiner
Improvment:
- added css for spinfieldconatiner to fix overlapping issue.
- improve margin for more readability of .jsdialog.ui-text
Change-Id: If64d30d10021a023c76852647ef8aebdede0513a
Before:
After:
> Improvment in spinfield conatiner class.

- browser/src/layer/tile/TilesSection.ts
Change-Id: Ic25805de741d6d71153211de68fb0ccc88e62d40
Follow up from https://github.com/CollaboraOnline/online/pull/8007/files
The error is TS2569: Type 'IterableIterator<any>' is not an array type or a string type. TS is complaining about the use of an iterator in the for loop where it expects an array or string.
The error message and everyone on stackoverflow recommend setting the compiler option --downlevelIteration. But wrapping in Array.from() is simpler.
Compiles on my machine with `./node_modules/typescript/bin/tsc mocha_tests/CanvasSectionContainer.test.ts --outfile mocha_tests/CanvasSectionContainer.test.js --module none --lib dom,es2016 --target ES5` when before it didn't. But I didn't run any other tests.
> Resolve TS build error

- kubernetes/helm/collabora-online/README.md
- kubernetes/helm/collabora-online/templates/_helpers.tpl
- kubernetes/helm/collabora-online/templates/dynamicConfig/flow_dynconfig.yaml
- kubernetes/helm/collabora-online/templates/dynamicConfig/flow_dynconfig_upload.yaml
- kubernetes/helm/collabora-online/templates/flow.yaml
- kubernetes/helm/collabora-online/values.yaml
@Rash419 it would be more beautiful, if collabora would start use machine-readable logs (like [logfmt](https://www.brandur.org/logfmt) or json)
- validate if it works with
- README update with new Logging section, here rendered: https://github.com/genofire/collabora-online/blob/feat/helm-logging/kubernetes/helm/collabora-online/README.md#kubernetes-cluster-logging
> feat(helm): add logging-operator flows

- browser/src/control/Control.ContextMenu.js
- browser/src/unocommands.js
Change-Id: I40a40a99551a756ad234e73956169018b761fa42
Allow edit section for Writer text sections, the dialog is made async in https://gerrit.libreoffice.org/c/core/+/161828.
> context menu: allow edit section for Writer text sections

- browser/Makefile.am
so on failure remove the output so a second attempt doesn't appear to succeed
Change-Id: Ibc1f7d46c2946cdc6a4dbcd6181872fb12e19fb6
* Resolves: # 
> tsc can report an error but create js output, so 2nd make's 'succeed'

- browser/src/core/Socket.js
- browser/src/map/Map.js
- kit/ChildSession.cpp
Send "tooltip: <payload>" to client for this callback type.
Client-side handling should be implemented separately.
Change-Id: I2d1a07dd36fa20a4b5ff785da788356e0f41d62f
> Handle LOK_CALLBACK_TOOLTIP in wsd

- coolwsd.service
- debian/coolwsd.service
According to the systemd.kill man page, when
KillMode=control-group "all remaining processes
in the control group of this unit will be killed
on unit stop." This ends up killing the kit
processes as well, which prevents saving any
unsaved modifications before shutting down.
The setting we want is 'mixed'. According to
the man page, with mixed "the SIGTERM signal is
sent to the main process while the subsequent
SIGKILL signal is sent to all remaining processes
of the unit's control group."
In other words, with KillMode=mixed, coolwsd
will receive the termination signal and it will
manage its children. But systemd will still
make sure that when coolwsd terminates, or when
it times out, all children and properly killed.
This changes KillMode to mixed.
Change-Id: …
> service: change KillMode to mixed

- browser/Makefile.am
- browser/package.json
Unused in the package since:
commit 2def6dc3d5c30fb4be8268536bfb988655693a1f
Date:   Sat Aug 27 17:49:50 2022 +0100
Switch to zstd image compression.
Change-Id: I785ad2c1522721ed34cf89a1922ee06d5e2507e4
* Resolves: # 
> drop pako dependency.

- browser/css/jsdialogs.css
- use margin-inline-start/end instead of margin left / right.
- This is important for RTL mode
Change-Id: Ie352a247aeedb1d1e9ff331a442a1c5214dbb470
Regression PR: https://github.com/CollaboraOnline/online/pull/7937
> fix spinfieldcontainer regression

- browser/src/control/Control.NotebookbarImpress.js
This commit hides the 'Present in Windows' button in Impress on mobile and tablet devices. This change is necessary because, on tablets, pressing this button currently results in the presentation being saved as an SVG file, which is not the intended behavior. The button should only be available on desktop environments.
Change-Id: I362183d899409f3c3075aeaaa3e50cde11e59925
* Resolves: # 
> Impress: Disable 'Present in Windows' Button on Mobile and Tablet

- browser/js/global.js
- cypress_test/integration_tests/idle/calc/idle_spec.js
Change-Id: I109e8c1b4e14be096741ceea5285456b77a38d04
* Resolves: # 
Enable new idle test added in https://github.com/CollaboraOnline/online/pull/7982
Test was failing due to known issue in accessibility code.
Change adds new idle directory to excluded directories.
> Enable Idle test

- Makefile.am
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
This non-functional PR only adds new code, without making any changes to existing code in any way (with one exception in DocBroker, where an new optional parameter is added to `addSession`). This new code is all required for async/parallel loading, which will come in a much smaller patches.
This code primarily adds two new class: `StorageConnectionManager`, responsible for creating connections to the Storage server (extracted from the Storage namespace) and will refactor code there later. And `RequestVettingStation`, responsible for doing the authentication of new connections, asynchronously, before creating DocBroker, committing resources, and spinning a new Kit instance.
- wsd: add StorageConnectionManager
- configure: enable rtti with sanitizers on C++ TUs only
- wsd: add …
> Parallel Loading Prerequisites

- test/FileServeWhiteBoxTests.cpp
- test/integration-http-server.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/FileServerUtil.cpp
This reworks the variable-substitution logic in files by first extracting all the user-variables into an object. Next step will be to kill Poco.
This is a prerequisite for async loading.
Most of the new lines are new test code. Functional code is actually small.
- wsd: new PreProcessedFile class
- wsd: better PreProcessedFile and new disabled test
- wsd: improved PreProcessedFile with SegmentType
- wsd: new Substitute helper for PreProcessedFile
- wsd: test: Sustitution of PreProcessedFile
- wsd: new helper class UserRequestVars
- wsd: access_token substitution
- wsd: access_token_ttl substitution
- wsd: access_header substitution
- wsd: ui_defaults substitution
- wsd: css_variables substitution
- wsd: postmessage substitution
- wsd: branding theme substitution
- wsd: …
> Variable Substitution in Files

- cypress_test/integration_tests/desktop/calc/focus_spec.js
Change-Id: Ib7a24823d5ea8c74a40936a8ae3b491b76d3da64
* Target version: co-22.05 
Test is failing in 22.05 tinderbox. I recently submitted a fix for this to master (https://github.com/CollaboraOnline/online/pull/7977).
I tried to port it to 22.05 but couldn't get 22.05 building on my machine. Instead of wasting time trying to get 22.05 to build, this just filters the test so that the tinderbox can pass again.
> Disable failing test in co-22.05

- browser/src/map/Clipboard.js
- test/UnitCopyPaste.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- this is a first step towards fixing https://github.com/CollaboraOnline/online/issues/8023
- this doesn't switch to the new API yet, but adds a new markup to recognize if the clipboard has our own HTML or something else
- the new markup is better, because <meta> tags are removed by the browser when using the new navigator.clipboard API, and this one is not
- this is meant to be a safe set of first commits, we already write the new markup, but we don't remove the old one yet, e.g. Android needs updating still
- on the other hand, this already provides enough markup so src/map/Clipboard.js can start experimenting with the new API, including the internal paste codepath
> Clipboard: add new-style metadata that survives browser sanitize

- kit/TestStubs.cpp
CXXLD    unittest
/usr/bin/ld: ../kit/unittest-Kit.o: in function
`Document::updateEditorSpeeds(int, int)':
/opt/shared/work/libreoffice/repo-online/online-cl/test/../kit/Kit.cpp:1488:(.text._ZN8Document18updateEditorSpeedsEii[_ZN8Document18updateEditorSpeedsEii]+0x2d9):
undefined reference to `ChildSession::getSpeed()'
Change-Id: If95662647d33f80dd98013b6bc81be897dd6ffc5
> fix linking error for clang 17

- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
- browser/src/map/Map.js
Use once to call event handler just one time
Use dedicated option, don't do it manually.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#once
-----------------------------------------------------
Move document tooltip helper to UIManager
so it is with all other showXXXX helpers
> Small tooltip refactor

- browser/src/map/Clipboard.js
- wsd/ClientSession.cpp
As pointed out at
<https://github.com/CollaboraOnline/online/pull/8041#discussion_r1457933092>,
it's not valid to have a markup like <div><html>...</html></div>.
The old markup was <html><head><meta ...></head>...</html> and that got
stripped away.
Fix the problem by going with <html><body><div ...>...</div></body></html>
which survives browser sanitize and also is a valid HTML.
Both the browser side and the wsd side is updated to go with this
inside-body markup. This also allows simplifying setTextSelectionHTML(),
because the valid HTML means the browser automatically strips the
<style> element whtn converting to plain text. Also remove a leftover
debug code in ClientSession::preProcessSetClipboardPayload() that I
forgot to remove. …
> cool#8023 clipboard: switch marker from outside-html to inside-body

- common/FileUtil.cpp
/usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/bits/stl_vector.h:1124:9: runtime error: reference binding to null pointer of type 'char'
#0 0x557ce8c06055 in std::vector<char, std::allocator<char>>::operator[](unsigned long) /usr/bin/../lib64/gcc/x86_64-suse-linux/12/../../../../include/c++/12/bits/stl_vector.h:1124:2
#1 0x557ce8f16e3f in FileUtil::readFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&, int) /home/vmiklos/git/collaboraonline/online-23.05-san/test/../common/FileUtil.cpp:449:37
While running toplevel 'make'. Both 'st.st_size' and 'off' were 0, so
this is an edge case.
Change-Id: I4899bffa48a761c84b6ee7d42776453b641ff5a7
> common: fix 0 read size in FileUtil::readFile()

- browser/src/control/Control.Tabs.js
- Trying to open context menu from a sheet tab, also changes the active tab. This occurs when right click on a sheet tab (or long tap on mobile or tablet)
- moveLeft and moveRight of inactive tabs are implemented.
- added _moveSheetLR and _moveOrCopySheet functions.
Change-Id: I5b25a8cb363b8e04fd6dcec1f500e7ff2982b678
* Resolves: #7354 
> Calc: Don't switch tabs when context menu is triggered

- common/Util.cpp
- common/Util.hpp
- test/WhiteBoxTests.cpp
- wsd/ClientSession.cpp
Add a way to search with an offset in findInVector() and then we can
avoid strstr() which assumes a null-terminated input, which may not be
the case.
READ of size 55 at 0x606000068a56 thread T8 (docbroker_001)
#0 0x55d0d6718a5a in StrstrCheck(void*, char*, char const*, char const*) /home/abuild/rpmbuild/BUILD/llvm-15.0.7.src/build/../projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:652:5
#1 0x55d0d6718882 in __interceptor_strstr /home/abuild/rpmbuild/BUILD/llvm-15.0.7.src/build/../projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_common_interceptors.inc:669:5
#2 0x55d0d71872c9 in ClientSession::postProcessCopyPayload(std::shared_ptr<Message> const&)::$_4::operator()(std::vector<char, std::allocator<char>>&) const …
> wsd: fix reading past the end of the clipboard in postProcessCopyPayload()

- browser/src/map/Clipboard.js
- common/FileUtil.cpp
- common/Util.cpp
- common/Util.hpp
- test/UnitCopyPaste.cpp
- test/WhiteBoxTests.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- cool#8023 wsd, ClientSession: add new style clipboard marker to our HTML output
- cool#8023 wsd, ClientSession: extend HTML clipboard marker removal
- cool#8023 Remove HTML marker in unit-copy-paste
- cool#8023 browser: generate and interpret new-style clipboard marker
- cool#8023 browser: make sure 'style' content doesn't affect plain text selection
- cool#8023 clipboard: switch marker from outside-html to inside-body
- common: fix 0 read size in FileUtil::readFile()
- wsd: fix reading past the end of the clipboard in postProcessCopyPayload()
> private/vmiklos/backport 23.05

- browser/src/map/Map.js
After document idle (document become unloaded on the server) when we click in the popup and document was reloaded - if sidebar was present previously it should be reinitialized.
Without that it was visible but not interactive and it was not possible to hide it.
1. To test that use small timeout in the coolwsd.xml: per_document.idle_timeout_secs
2. Open sidebar
3. Wait for idle
4. Click in the idle popup
Sidebar should be interactive and it should be possible to hide it.
> sidebar: initialize after recover from idle

- browser/src/control/Control.JSDialog.js
Steps to reproduce problem:
1.    open spreadsheet
2.    open function wizard (Fx icon next to the formulabar)
3.    move dialog so it is outside view partially
4.    select some function and click inside edit field for it's param
5.    click on the sheet content
Result: view jumps and moves everything up
> calc: avoid view jump when using formula wizard

- browser/src/core/Socket.js
- browser/src/map/Map.js
It seems that commit 2d7743cb734b31b763f389d686ca349661de9739 sidebar: initialize after recover from idle
Introduced a regression, in multi user case sometimes sidebar is shown/hidden by other users. Also app was slow sometimes what could be a sidebar reloading all the time.
Revert previous single-init on docloaded and use dedicated reconnection code to reinitialize sidebar.
This should still fix the problem that when doc become unloaded with sidebar opened - after reconnecting it was not possible to close.
> sidebar: reinitialize after reconnect only

- browser/package.json
It was a dependency of "pako" package, which it was removed.
Change-Id: Ia35b4c4ff9ee5e9ab1f09da398f6d93e51d24a1f
> browser: remove 'tmp' dependency

- browser/src/map/Clipboard.js
- wsd/ClientSession.cpp
The old marker is stripped away when Chrome sanitizes the incoming
clipboard HTML. We used to go with both markers to allow an incremental
conversion.
By now, there are no remaining consumers of the old marker, so remove it
before somebody would depend on both markers by accident.
Change-Id: Ib9dd0e7cf64e1a99d6038a179651ef5e114c6f8b
> cool#8023 clipboard: remove old marker

- browser/src/core/Socket.js
- browser/src/map/Map.js
It seems that commit 2d7743cb734b31b763f389d686ca349661de9739 sidebar: initialize after recover from idle
Introduced a regression, in multi user case sometimes sidebar is shown/hidden by other users. Also app was slow sometimes what could be a sidebar reloading all the time.
Revert previous single-init on docloaded and use dedicated reconnection code to reinitialize sidebar.
This should still fix the problem that when doc become unloaded with sidebar opened - after reconnecting it was not possible to close.
Perf problem visible in profile: https://github.com/CollaboraOnline/online/issues/8051#issuecomment-1909953739
> sidebar: reinitialize after reconnect only (23.05)

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.Tabs.js
- jsdialog not getting close when we change tab
- this will close all dialogs when we click on tab or change the tab
To test this patch
- add 2 or 3 tab sheet in calc
- add `autofilter` in any calc sheet tab
- open autofilter popup
- change sheet tab
Before this patch:
- popup not getting close when focus goes away.
After: - all dialogs should be closed now when change the sheet tab.
Change-Id: I4eb308e499853a6e1d86b8dc7f60aa938e9c03b9
> Close autofilter popovers when click or change the sheet tab

- browser/css/toolbar.css
- avatar popup list in the top right corner was getting cropped if we have multiple users ( like more than 10=12)
- this patch will make overflow auto and add scroll option to tackle this issue
[Screencast from 2024-01-25 22-06-50.webm](https://github.com/CollaboraOnline/online/assets/61383886/ae7872fd-6a2d-4d4e-ac92-9452c180fee3)
Change-Id: Id57539cb91a7f4a2a3766e6d01f0e6a00d3af92a
> Fix cropped userlist popup

- kit/Kit.cpp
so we can pass through the full state that the view reports which makes it easy to see if a browser side is given a view whose render settings are unexpected.
e.g. clicking "formatting marks" and not getting a viewrenderedstate with 'P' or view#1 clicks their "formatting marks" and view#2 receives a 'P'ilcrow state.
Change-Id: I31d3a8397f02dedf2505bed5dd83576f3138b504
* Resolves: # 
> the viewrenderedstate=string string is only used in debugging

- browser/Makefile.am
- browser/src/control/Control.LokDialog.js
- browser/src/control/Toolbar.js
- browser/src/core/Debug.js
- browser/src/core/Socket.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- browser/src/layer/tile/WriterTileLayer.js
- browser/src/map/Map.js
- browser/src/map/handler/Map.Keyboard.js
Change-Id: I20f42d24a6af91bdcf79dc7fe19e1cf25f90bd89
* Resolves: # 
Moves 600+ lines out of CanvasTileLayer.js into an new file core/Debug.js. Most of this code had nothing to do with the CanvasTileLayer, that's just where it was put because the first debug tool happened to have been put there.
The only changes are to move the code, move the ownership from the doc layer to the map, and rename variables and functions. There is no functional change.
I'm looking for feedback on the new file location (perhaps map/Debug.js would be better?), gotchas around adding a new js file (I added it to the two lists in the Makefile but I'm not sure it needs to be in the pot section), and anything else.
> Extract debug tools to new file core/Debug.js

- browser/js/global.js
- browser/src/core/Debug.js
Sets random language and launches debug mode,
turning on the Randomize User Settings tool
Change-Id: I5e06be624cd5383784ea640304980a82e76be229
Start random user with
`http://.../...html?...&randomUser=true`
> Add url parameter to launch with random settings

- common/Util.cpp
- common/Util.hpp
using fork(), the kernel needs to copy the VM data structures, which can be quite large for the main COOL processes.
I looked into things like vfork(), clone() and using a helper-process, but it looks like posix_spawn is sufficient for our needs. Internally it uses clone(CLONE_VM) which means we avoid the VMA copies.
Also, simplify the arguments of spawnProcess,
we don't use the optional params anymore.
Change-Id: I8f943541dc4d7f56c2d36ccbf7b78c40ec14b8e0
* Resolves: # 
> cool#8016 speed up spawning/execing child programs

- browser/src/map/Clipboard.js
- wsd/ClientSession.cpp
This reverts commit cc12a1b060adb31afe037bb5e18f1cbe4885c3e6, because
there is not much short-term benefit of this and it may cause problems,
as it affects builds produced without --enable-experimental, too.
Change-Id: I4c27614e9ee26c8aaa2c510ee6bd115cd19a45f3
> Revert "cool#8023 clipboard: remove old marker"

- browser/src/map/handler/Map.SlideShow.js
Resolved an issue in Impress's 'Present in Window' feature where the snackbar would persist even after closing the presentation window or pressing the escape key. Now, the snackbar properly disappears as intended, ensuring a cleaner and more intuitive user interface experience.
Change-Id: Id491e39d88b433993b5ff83e10c3ca2b1eb8ab40
* Resolves: # 
> fix: Impress: Dismiss snackbar on presentation window close

- browser/src/control/Control.JSDialog.js
- browser/src/geo/LatLngBounds.js
- browser/src/layer/tile/CalcTileLayer.js
calc: avoid view jump when focusing formula wizard
Change from commit 85ff10db7a861ac0a848d6276347b8709d151a23
calc: avoid view jump when using formula wizard
wasn't enough to fix the issue. When we receive grab_focus
action for widget which is hidden outside view - browser
will move the app view leaving blank space on bottom.
Steps to reproduce problem:
1.    open spreadsheet
2.    open function wizard (Fx icon next to the formulabar)
3.    move dialog so it is almost completely outside view (edit field
with focus has to be outside view)
4.    select some function and click inside edit field for it's param
5.    click on the sheet content
Result: view jumps and moves everything up
-----------------------------------------------------------------------------
calc: don't jump on merged …
> Backports 23.05: calc: view jumping fixes

- test/UnitBadDocLoad.cpp
Probably went wrong with bf8b9945ab304c3c4604ff296ff33b3f127accf7 (Warn
on non-async dialog usage when in debug mode., 2024-01-26).
Change-Id: Ifb92e0d9431f252cdf26ac92dd428b87e5d6e8e0
> unit-bad-doc-load: fix this to pass again

- browser/css/notebookbar.css
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js
- cypress_test/integration_tests/desktop/impress/table_operation_spec.js
- cypress_test/integration_tests/desktop/writer/invalidations_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
It is request from user that currency icon has no dropdown to select something else than USD.
To enable that we need widget from core be enabled + restructure notebookbar so we use correct id's in the communication with core.
To get this done I simplified notebookbar by using CSS grid and removing old cell/row containers structure.
So similar to sidebar we will have plain structure of widgets.
> notebookbar: enable currency dropdown

- browser/css/jsdialogs.css
Change-Id: Ib9c6d8e972ff061223af4fa96a63b8e96d21e772
* Resolves: # 
Before:
After:
No changes for ltr languages
Follow-up to https://github.com/CollaboraOnline/online/pull/8024
- [x ] Code is properly formatted
- [x ] All commits have Change-Id
- [x ] I have issued `make run` and manually verified that everything looks okay
> widgets: combobox border-radius handle rtl languages

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
In 24.04 we activated dialog which informs about idle dialog. It covers full screen so some tests fail on that.
Add {force: true} to ignore that in failing case.
> cypress: fix writer/top_toolbar_spec.js insert special character

- browser/src/layer/tile/CalcTileLayer.js
If a cell is edited and suddenly press ESC key,
followed by Shitf + Arrow down to select more cells,
so the "uno:InsertMode" state arrives late and
it cannot update the row header selection.
Change-Id: Ib0e4e0699336e07d96efd96559f7b47caa285921
> browser: fix cell selection if ESC is pressed

- browser/Makefile.am
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.Timefield.js
Change-Id: I9e3e280db4a0b1f3e3a9df5fe8b6e0bfd97ddaa5
* Resolves: # 
It uses input[type=time] which might not be looking as good as we'd like.
Requires CORE patch: https://gerrit.libreoffice.org/c/core/+/161892 to expose the custom properties tab.
And https://gerrit.libreoffice.org/c/core/+/162598 to expose the field.
> widgets: Add a time field

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
jsdialog: openmenu action support in notebookbar
In notebookbar we insert additional containers for rows and cells.
When sending openmenu action we need to pass id of the real parent
of a button which is a toolbox. Go up in the structure to get
correct node.
This is 23.05 only as in master we already have simplified structure.
--------------------------
notebookbar: enable dropdown for currency toolitem
use toolbar from notebookbar_online.ui in the core
> notebookbar: enable currency dropdown (backport to 23.05)

- browser/src/control/Control.JSDialogBuilder.js
Followup for commit e8357ceb287d506096f489f3ca3479ed228f7bf9
jsdialog: openmenu action support in notebookbar
This is 23.05 only as in master we already have simplified structure.
It fixes case: click on currency button (not arrow) in notebookbar to toggle.
> jsdialog: use correct parent for toolbox actions in notebookbar (23.05)

- cypress_test/integration_tests/common/helper.js
Change-Id: I15b3e0c02ad841872dc9d472672c112860f2bf47
I'm tired of scrolling around the logs just trying to figure out what test has failed. 
```
cy:log ✱  Starting test: integration_tests/desktop/calc/clipboard_spec.js / Calc clipboard tests. / HTML paste, internal case
...
cy.log ✱  Finished test: integration_tests/desktop/calc/clipboard_spec.js / Calc clipboard tests. / HTML paste, internal case
```
> Log test name when starting and finishing test

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
Helps us to catch un-necessary invalidations more precisely.
Change-Id: If5d681c025252e9e860e744945b33b68047524d9
* Resolves: # 
> calc & impress: show invalidations debug only for the current part.

- cypress_test/integration_tests/common/helper.js
Change-Id: I15b3e0c02ad841872dc9d472672c112860f2bf47
This is a very low risk quality-of-life improvement, just merged into master but it would be nice to have in 23.05 too.
>  Log test name when starting and finishing test (backport to 23.05)

- common/Util.cpp
- common/Util.hpp
And improve quality of low-grade random numbers significantly. _rd.entropy() ? is not your friend.
Change-Id: I477557245949334bec517cdeae653c7452ed2049
(cherry picked from commit b627777b13a32cb17ac17d575f300eb411cd2bc5)
* Resolves: # 
> Remove trendy C++ & Poco wrappers for random numbers.

- common/Util.cpp
Avoid using LOG_TRC etc. during static initializers before logging is setup:
#0  0x00007ffff7362183 in std::string::size() const () from /lib64/libstdc++.so.6
#1  0x00000000007d1acc in std::operator==<char> (__lhs="", __rhs=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>)
at /opt/rh/devtoolset-12/root/usr/include/c++/12/bits/basic_string.h:3586
#2  0x00000000008fdc04 in Poco::Logger::unsafeGet (name="") at src/Logger.cpp:289
#3  0x00000000008fdb81 in Poco::Logger::get (name="") at src/Logger.cpp:280
#4  0x000000000066a30f in Log::logger () at /opt/rh/devtoolset-12/root/usr/include/c++/12/bits/new_allocator.h:90
#5  0x0000000000692f8e in Util::rng::getBytes (length=16) at ../common/Util.cpp:122
#6  0x0000000000693312 in Util::rng::getSeed () at …
> randomness: abort if we can't get randomness, with a message.

- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/Storage.cpp
To avoid the following warning in C++20:
error: implicit capture of ‘this’ via ‘[=]’ is deprecated in C++20 [-Werror=deprecated]
Change-Id: I8b195d675ddc87fa6b16f7240a046fac9a7769e1
> Capture this explicitely by name

- browser/css/spreadsheet.css
This button does nothing (Sidebar: Style: dialog button [square with arrow])
- There is no paragraph style dialog in calc
- The style sidebar pane visible on core side is not implemented in
online
Better to hide it for now.
Fixes https://github.com/CollaboraOnline/online/issues/8135
Change-Id: I62db3ec6466782a9dc2cb89deffec8023851de2d
> Calc: sidebar: Hide Styles dialog button

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/contenteditable_helper.js
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/common/writer_helper.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/desktop/impress/table_operation_spec.js
- cypress_test/integration_tests/desktop/writer/editable_area_spec.js
- cypress_test/integration_tests/desktop/writer/invalidations_spec.js
- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/autofilter_spec.js
- cypress_test/integration_tests/mobile/calc/cell_appearance_spec.js
- cypress_test/integration_tests/mobile/impress/slide_properties_spec.js
- cypress_test/integration_tests/mobile/writer/focus_spec.js
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
- cypress_test/support/index.js
Change-Id: I6b7bbcfd580a7ddb454218eeba96019b408f53e5
- Removed calls to cy.wait()
- Stubbed waitUntilIdle, which was usually acting as wait(1250)
- Added comments to some waits that are necessary (like holding for long press on mobile)
- Fixed failing tests by taking advantage of cypress's retry functionality. For example:
-- Add assertions that items have appeared, disappeared, or are no longer disabled
-- Replace .then() with .should()
-- Click on the underlying button instead of the div (better actionability detection)
-- Force click (skip actionability detection)
-- Use waitUntil to retry unsafe commands like clicking
-- Remove chained unsafe commands
- I did not actually remove the waitUntilIdle or clickOnIdle functions because that would require touching many files.
- I focused on …
> Remove waits from cypress tests (make cypress tests 45% faster)

- coolwsd.spec.in
Change-Id: Ia022c46e7ada12e6e07b2da95e3cdccc026609cc
* Resolves: #7071
A change in the output of `busctl --system get-property org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager Version` causes some `if`-statements to fail when installing the RPM package on RHEL8 (or derivatives). This PR adjusts for that.
> fix error in RPM postinstall scriptlet on RHEL8 (#7071)

- coolwsd.spec.in
* Resolves: #3125, #7606
The current `%preun` and `%postun` cause the `coolwsd.service` to be disabled after each update of the RPM. This is due to the [order](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#ordering) in which the scripts run. In this case, the `%preun` and `%postun` of the *outdated* package being uninstalled runs after the installation of the updated package - thus always disabling the service.
> fix the coolwsd.service being disabled after updates (#3125, #7606)

- common/Clipboard.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
This moves the clipboard resque logic earlier to
make sure it is cached before the Kit process
exits.
By putting the clipboard-fetching command before
the save-before-exit, we should get the clipboard
in most-all cases. There are still edge-cases
that can slip through, but they should be much
less frequent, and they will require much more
involved logic (tbd).
> wsd: rescue the clipboard before autosaving on unload

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
Curently, the exportpdf command hangs in the android app. A fix is in progress, but as a stopgap solution disabling the command will avoid people getting stuck
Change-Id: Ied74c3f1fa57356542f3f71e1becbae81f5af7fc
> Hide exportpdf command in the android app

- common/Util.cpp
- common/Util.hpp
- test/HttpRequestTests.cpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
so remove one in favor of the other
Change-Id: I47778f7bce24f0687565aa179b7a3bbea9d95120
* Resolves: # 
> rng::getHardRandomHexString is now the same impl as rng::getHexString

- common/Log.cpp
- common/Util.cpp
- common/Util.hpp
- kit/Kit.cpp
- wsd: header clean up and SPDX license
- killpoco: move own logging out of experimental
- wsd: no need to create existing mount-point
> Kill Poco Logging

- browser/src/control/Control.Header.ts
problem:
drag selection starting from the first row or column would result in first col or row being unselected. It was caused by index being 0 resulting in condition being false
Change-Id: I3619f52ccc7fdb2883af547f1c907c07ef27ddf9
> Calc: Selecting columns by dragging mouse deselect the first column

- browser/js/global.js
- browser/src/map/Clipboard.js
Fix error on clipboard download fail
----------------------------------
Use encoded WOPISrc in ws requests
This is an issue if we use encoded and decoded WOPISrc for the
same document when using load balancers like HAProxy. It should
be always encoded.
What we did:
cool.html:
http://haproxy.local:9980/browser/2a43eb3236/cool.html?WOPISrc=http%3A%2F%2Fsomewopisrcfileaddress&title=title
ws:
ws://haproxy.local:9980/cool/http%3A%2F%2Fsomewopisrcfileaddress/ws?WOPISrc=http://somewopisrcfileaddress&compat=/ws
These 2 were redirected to different nodes when balancing
was done based on WOPISrc
This is regression from commit https://github.com/CollaboraOnline/online/commit/a722687c116f81be19423fc92630cb7d7209b65a
browser: simplify getParameterByName
> Load balancing fix

- browser/js/global.js
- browser/src/map/Clipboard.js
Fix error on clipboard download fail
----------------------------------
Use encoded WOPISrc in ws requests
This is an issue if we use encoded and decoded WOPISrc for the
same document when using load balancers like HAProxy. It should
be always encoded.
What we did:
cool.html:
http://haproxy.local:9980/browser/2a43eb3236/cool.html?WOPISrc=http%3A%2F%2Fsomewopisrcfileaddress&title=title
ws:
ws://haproxy.local:9980/cool/http%3A%2F%2Fsomewopisrcfileaddress/ws?WOPISrc=http://somewopisrcfileaddress&compat=/ws
These 2 were redirected to different nodes when balancing
was done based on WOPISrc
This is regression from commit https://github.com/CollaboraOnline/online/commit/a722687c116f81be19423fc92630cb7d7209b65a
browser: simplify getParameterByName
> Load balancing fix 2305

- cypress_test/package.json
- cypress_test/support/index.js
Change-Id: I8edbcbb72e1ad016df0ff6a2466d20865f517683
I am affected by https://github.com/cypress-io/cypress/issues/27869 which causes random crashes when using make run. Some days it's worse than others but today it was preventing me from using make run at all. The recommended solution is to upgrade to at least Cypress 13.3.
I also upgraded cypress-wait-until, which has a major update in 3.0.0 regarding measuring timeouts.
I also deleted cypress-iframe which was unused, no longer updated, and throwing npm errors.
There are still some errors thrown from cypress-tags via its dependency @cypress/browserify-preprocessor. Unfortunately there's no more recent version.
```
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard …
```
> Upgrade to Cypress 13

- common/SigUtil.cpp
- common/SigUtil.hpp
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/Kit.cpp
- test/WhiteBoxTests.cpp
Cue up some basic state for being signal safe dumped on crash/abort.
Change-Id: Ibc6713aef2a0e7b878b178b05f0e13c8d40b47fc
* Resolves: # 
> signal activity dumping: enrich with session details and state.

- browser/Makefile.am
- scripts/unocommands.py
This resolves the following Python warning.
unocommands.py:319: SyntaxWarning: invalid escape sequence '\('
f.write('''};
Also make sure the output depends on the script
Change-Id: I11f1e028c9c132f4afc66f9b5a6137b478f00774
* Resolves: # 
I was seeing this warning. Escaping rules applied. I compared the output and it is unchanged. I run Python 3.12.1 in case this started to only pop on recent Python.
> Fix warning for unocommands.py

- browser/css/menubar.css
- browser/css/toolbar.css
- browser/html/cool.html.m4
- browser/src/control/Control.DocumentNameInput.js
- browser/src/core/Socket.js
Add loading indicator for document title saving
To address the lack of visual feedback during the delayed saving of document titles, a loading bar has been introduced below the document name/title input field. This provides users with a clear indication of the ongoing save operation. Additionally, the delay that previously occurred after entering a new document name and pressing Enter has been eliminated, streamlining the save process.
[Screencast from 05-02-24 09:08:35 PM IST.webm](https://github.com/CollaboraOnline/online/assets/61119120/d7e0d58a-bff5-4d90-a414-b516f828b0e6)
In case the document saves too quickly to see the loading bar, here are the steps you can follow to reproduce the loading effect:
- Open the source in the debug console and select the file …
> Add loading indicator for document title saving

- cypress_test/integration_tests/common/helper.js
- cypress_test/support/index.js
Change-Id: Ic1eaae123ae70f5f09553d6c69bfa699a02a921f
* Resolves: # 
Seems to have been added to support Nextcloud tests but is now unused.
> Remove cSetLevel (unused)

- test/WhiteBoxTests.cpp
WhiteBoxTests.cpp:660:10: error: 'updateActivityHeader' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
void updateActivityHeader() const
^
../kit/ChildSession.hpp:89:18: note: overridden virtual function is here
virtual void updateActivityHeader() const = 0;
^
Change-Id: I12f21fd9fbe0ba77d2196bfcd1cbdb5ef07e5d06
> test: fix -Werror,-Winconsistent-missing-override in WhiteBoxTests

- browser/src/core/Debug.js
Move Typer and Randomize User Settings to "Functionality" menu
Rename main toggle to "Enable"
Change-Id: I75709124f835c46ae741c4d51e14ed0b868528ae
* Resolves: # 
> Clarify Automated User menu

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
My local run failed in this test, because scrolling to the right just
twice resulted in a partially clicked toolbar item, so:
cy.cGet('#Home-container .unospan-CharmapControl').click();
failed. Add a 3rd click if scrolling to the right is still possible.
Change-Id: I4caa3dc79df1bbbd5bd0c7e88ef1baea8ae4b17e
> cypress, desktop/writer/top_toolbar_spec.js, 'Insert Special Character.': add conditional 3rd click

- kit/Kit.cpp
and don't check for it in the other cases, so drop it in these ones
Change-Id: Ie343178869cadc127ee898968fef8f798b6068d5
* Resolves: # 
> we never have an empty std::unique_ptr for .second

- browser/src/map/handler/Map.SlideShow.js
https://github.com/CollaboraOnline/online/commit/237d9c084a7ebf4681e1e850c4c5df410f8fa67a fixed videos rendering in the
wrong place on Safari (and all iOS browsers) in edit mode.
Unfortunately, it made the oversight of missing presentation mode, which
gets its SVGs from a completely different place 🤦.
This commit fixes presentation mode.
After this commit, you will see the video in the right place. Please
note that the white border present in edit mode is not there in
presentation mode, so if you line the video edge up with something in
the presentation you may think the video is offset: I suggest lining
something in the video up rather than the edge of the video object.
Known caveats:
- This commit seems to be a few pixels off with larger border sizes.
It's a lot better than before, but …
> Fix video position in safari presentation mode

- cypress_test/integration_tests/common/helper.js
- cypress_test/support/index.js
- Print full test name in beforeEach and afterEach
- Originally added to beforeAll and afterAll in helper.js in https://github.com/CollaboraOnline/online/pull/8120
- Moving to beforeEach and afterEach in support/index.js
- No functional change
- Hide xhr requests
- Before: 
- After:
- No logs
- Hide repeated actual and expected values on passed assertions
- Before: 
- After:
- Failed assertions still display
- Add test name and error message to failure display
- Before:
- After:
Change-Id: Ic1a20481c05afb05b9c29d0bd428b59615d49dc7
* Resolves: # 
> Cypress test logging improvements

- browser/css/cool.css
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
When a comment is deleted while tracking is on, we need to show it if showChanges is also on. This PR improves the handling of tracked changes for comments.
Change-Id: I2f6956fa18504995f91e6e1c0fa3d633f4317f5c
* Resolves: # 
> Introduce redlinedDeletion type for comments.

- browser/src/core/Debug.js
- browser/src/layer/tile/CanvasTileLayer.js
Extract "splits section" tool
It doesn't seem to do anything though
Also minor edits to "tile pixel grid section" tool
Change-Id: I008acc087e99d83225c1ba3184743e6e5a60e283
* Resolves: # 
> Debug menu cleanup

- browser/src/core/Debug.js
Change-Id: I7692bb07adf7fc50ef72c4e933584573755295ad
Adding more sidebars (Navigator for all document types, slide editing sidebars for Impress). The way sidebars are managed is very weird and requires lots of different cases.
Formatting marks is a straightforward toggle
The &randomUser=true url parameter doesn't open sidebars (and doesn't work for some other settings too). This will be fixed in a future change.
> Add formatting marks and sidebars to random user settings

- net/WebSocketHandler.hpp
- wsd/COOLWSD.cpp
- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd/StorageConnectionManager.cpp
- wsd/StorageConnectionManager.hpp
- wsd/WopiProxy.cpp
- wsd/WopiProxy.hpp
Non-functional changes in preparation for parallel loading. This should help reduce the review of #8052.
- wsd: exclude WopiStorage in mobile builds
- wsd: simplify WebSocketHandler::sendErrorAndShutdown
- wsd: support sendMessage with string literals
- wsd: optional timeout to getHttpSession helper
- wsd: refactor findOrCreateDocBroker
> More Parallel Loading Prerequisites

- browser/src/core/Debug.js
- browser/src/core/Socket.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/WriterTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
The goal was to get that long list of variables associated with their individual tools.
You can view the changes by commit if you want.
1. Tile Invalidations tool
Rename and reduce scope of variables associated with tile invalidations debug tool
2. Ping tool/Tile invalidations tool
Rename variables and functions
Move server ping to separate tool
Fix keypress detection for timing
3. Tile data tool
Rename variables, make them all behave the same, rewrite display
4. Overlay tool
Tools can clear their messages when they get turned off
> Debug tool improvements

- wsd/DocumentBroker.cpp
Change-Id: I622bc1569c775c57d7f268a063195706bb12be7b (cherry picked from commit d8041e951695cff7f8f24ecf1e1644a317c6193f) (cherry picked from commit 9acb400221853753affa8dc6c7597a2118fd7a35) (cherry picked from commit 15ab8922040915d3d6a51b1fe709532718bdc060)
* Resolves: # 
> use a path name unrelated to the parent dir name

- browser/Makefile.am
- browser/js/global.js
- browser/src/control/Control.DownloadProgress.js
- browser/src/control/Control.Tabs.js
- browser/src/core/Util.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Keyboard.js
- browser/src/map/handler/Map.Mouse.js
- scripts/unocommands.py
* Resolves: #  See #551 
* Target version: co-23.05 
Backport the following:
* calc: Enable sheet protection
* Fix warning for unocommands.py
* global: Add L.Browser.mac to not parse user agent everywhere
> Backports: sheet protecion + other

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Toolbar.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
problem:
tracked comments deletion was not reflected with accept/reject all changes
Change-Id: I0964fbd220f450cb144a115e8203250467e7edae
> annotation: refresh comments on accept/reject all tracked changes

- wsd/COOLWSD.cpp
and default printer. In typical deployment these should be effectively no no-op, so mostly aligns debugging env with deployment env so whatever printer happens to be installed locally has no effect.
Change-Id: I09651d9af2de9817d4d278d25937c9ce0dc87352
* Resolves: # 
> disable getting the host printer queue

- browser/src/control/Control.Menubar.js
Change-Id: I1511419858e361ad7a7653b2939e8d516c2d7e59
* Resolves: #  See #551 
This is to be consistent with LibreOffice.
Not sure about the notebook bar.
> calc: Add protect sheet command to Tools menu

- browser/src/core/Debug.js
- browser/src/core/Socket.js
Change-Id: I2452d4c7e3e3152533b676fb2db81ef95d96fb54
* Resolves: # 
> Reenable logging socket messages before debug mode

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
This is a backport of #8140, I believe it's uncontroversial because the issue causes this feature not to work already and to instead hang the app
Curently, the exportpdf command hangs in the android app. A fix is in progress, but as a stopgap solution disabling the command will avoid people getting stuck
Change-Id: Ied74c3f1fa57356542f3f71e1becbae81f5af7fc
* Resolves: # 
> backport: Hide exportpdf command in the android app

- README.md
This is a backport of #8232, I believe it's uncontroversial because it only modifies the README
The libera.chat matrix bridge shut down a while ago, so links to our room on matrix load forever. Additionally, we use matrix rather than the IRC room so we should not be advertising it when they will only need to be redirected to the right place if they join.
I run a matrix homeserver (clicks.codes) and have set up a room address on there. By telling people this room address instead of the libera.chat one they can join the existing room even though libera.chat is not hosting matrix.
Change-Id: I8a4224f1a856e7295325196f1b1a80f860ed7962
* Resolves: # 
> backport: Replace dead chat links

- browser/src/control/Control.Tabs.js
1) Load a document with a large number of tabs
2) The last tab was selected
Change-Id: I0326bf2e374dddd7e075ea5806e5aefe5f598611
> browser: fix scroll the currently selected tab

- browser/src/control/Control.PartsPreview.js
- browser/src/layer/tile/ImpressTileLayer.js
Invalidate tile preview when canonical view id
changes.
Change-Id: I62d2e20946ec863ceb71014bb0216675316a658b
> browser: impress: override invalidate preview tiles

- browser/src/map/handler/Map.SlideShow.js
This is a backport of #7618
237d9c084a7ebf4681e1e850c4c5df410f8fa67a fixed videos rendering in the wrong place on Safari (and all iOS browsers) in edit mode. Unfortunately, it made the oversight of missing presentation mode, which gets its SVGs from a completely different place :facepalm:.
This commit fixes presentation mode.
After this commit, you will see the video in the right place. Please note that the white border present in edit mode is not there in presentation mode, so if you line the video edge up with something in the presentation you may think the video is offset: I suggest lining something in the video up rather than the edge of the video object.
Known caveats:
- This commit seems to be a few pixels off with larger border sizes. It's a lot better than before, but still not …
> backport: Fix video position in safari presentation mode

- browser/css/menubar.css
- browser/css/toolbar.css
- browser/html/cool.html.m4
- browser/src/control/Control.DocumentNameInput.js
- browser/src/core/Socket.js
To address the lack of visual feedback during the delayed saving of document titles, a loading bar has been introduced below the document name/title input field. This provides users with a clear indication of the ongoing save operation. Additionally, the delay that previously occurred after entering a new document name and pressing Enter has been eliminated, streamlining the save process.
Change-Id: I9c5a41f999d02dcfaa24e7925029499cf310b2e0
* Resolves: # 
> backport: Add loading indicator for document title saving

- browser/css/spreadsheet.css
- browser/src/control/Control.Tabs.js
- browser/src/core/Socket.js
- browser/src/layer/tile/CalcTileLayer.js
- kit/KitHelper.hpp
This set the CSS class 'spreadsheet-tab-protected' on the sheet tab.
Requires LOKit change https://gerrit.libreoffice.org/c/core/+/163325
Also set the state of the state of the context menu UI.
* Resolves: #  See #551 
This show the status.
Not sure how correct that UI code is.
> calc:  Receive the sheet protected status

- wsd/ClientSession.cpp
Revert "Avoid crash when pasting image in debug mode" This reverts commit 78558fe9af361dd0238bd3021c67e9d431dcf981.
Instead of detecting paste command and not trigerring assertion: fix frame type so it will be binary in case of paste.
This is backport.
How to reproduce:
- open website in browser and right click any image and do "copy image"
- open COOL and try to paste using ctrl + v (in debug build it crashes)
> Fix pasting image assertion (22.05)

- browser/src/control/Control.Tabs.js
- browser/src/core/Socket.js
- browser/src/layer/tile/CalcTileLayer.js
This was introduced by backport #8271 of the sheet protection
Change-Id: I07a9fd428b11042ce191a5c7a48d53400253c445
* Resolves: #  #8271 
> calc: Don't use es6 let and () =>

- browser/src/control/Control.Zotero.js
problem:
in some types of items fields may be named differently, leading to fields not being found and empty dialog entries.
currently only itemType 'case' was culprit but in future there maybe some other types too
Change-Id: I24b58dc474a555b3f26c34bb4ae0b144c06abc57
> zotero: fix missing field data in the dialog

- browser/js/global.js
This fixes a regression where `framed.doc.html` wouldn't load.
Change-Id: I57b4a617755be4615ec6ec734f6e084d57eaebce
* Resolves: # 
> globals: Make sure coolParams.get() return an empty string instead of null

- browser/src/map/Clipboard.js
- cypress_test/integration_tests/desktop/calc/clipboard_spec.js
> cool#8292 browser, clipboard: fix navigator.clipboard error handling

- browser/src/control/Control.Zotero.js
problem:
in some types of items fields may be named differently, leading to fields not being found and empty dialog entries.
currently only itemType 'case' was culprit but in future there maybe some other types too
Change-Id: I24b58dc474a555b3f26c34bb4ae0b144c06abc57
> zotero: fix missing field data in the dialog (backport)

- browser/css/jsdialogs.css
problem:
when titles are long they go beyond dialog area and are not scrollable, this hides the date and author details which can not be scrolled either
Change-Id: Iae8a5affb870faff0639ac9083e118cec40debd0
> zotero: fix long title taking all the space in dialog

- browser/css/jsdialogs.css
> zotero: fix long title taking all the space in dialog (backport)

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.TreeView.js
- separator should be treated as UI not any object value
Before:
After:
Change-Id: Ie6182dda40b7fd3c0d1ea87c5df78a46239677ed
> Handle sperator case for tree Widget

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.TreeView.js
Back port PR of https://github.com/CollaboraOnline/online/pull/8315
- separator should be treated as UI not any object value
Change-Id: Ie6182dda40b7fd3c0d1ea87c5df78a46239677ed
> Backport to 23.05: Handle sperator case for tree Widget

- browser/src/control/Control.UIManager.js
Fixes and gives more details for debugging in case of:
INCOMING: viewinfo: [{"id":3,"userid":"admin","username":"admin","userextrainfo":{"avatar":"http://.../avatar/admin/64","is_admin":true},"readonly":"0","color":0}] cool.html:323:37
Exception TypeError: this.map._viewInfo[this.map._docLayer._viewId] is undefined emitting event [object Object] onUpdateViews@http://.....:9980/browser/08e0fd2e1b/src/control/Control.UIManager.js:823:31
1. Open spreadsheet with 2 views in Nextcloud
2. close with view B
3. Open again with view B
Result: TypeError
> Avoid exception on view list update

- browser/src/core/Socket.js
On the client side, when setting up the socket, we encode  beforehand, so there's no need to encode it again.
Change-Id: I09e59c6fdda4c93de5dd36fca5023ac88926c4d4
* Resolves: #8303
> Fix: Multiple Encoding of wopiSrc  During Document Renaming

- test/UnitQuarantine.cpp
- test/UnitWOPIFailUpload.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
Quite possibly we did successfully up-load, or at least our timestamp may not match, but we cannot be sure enough to warn the user in this case. We cannot reliably get notified of remote alteration on the server of files, so wait until a more succesful save or new user join to get an improved timestamp.
Change-Id: I5c8124ed74ba5c26371768ac778b9670282c87a3
forward port to master ...
> wsd: Blank stored timestamp if an up-load times out.

- browser/js/global.js
- common/Session.cpp
- common/Session.hpp
- kit/Kit.cpp
- wsd/ClientSession.cpp
like we do for the spelling setting, so we have the document in the desired state early before any rendering, dropping the early full document invalidations during initial setup
requires https://gerrit.libreoffice.org/c/core/+/163650 in the code to be useful
Change-Id: I6b762c95fd4c00c7da04cf89f7bbeef4bc57375d
* Resolves: # 
> init document theme during load

- test/UnitBadDocLoad.cpp
Parse jsdialog responses, and send the right dialog id to click items on.
Adapt to unexpected multiple updates for the corrupted document warning dialog on load.
Change-Id: I0f934cdc60b2204afc493cf367f98a9cfa0aa6c0 (cherry picked from commit 2be1f8c3457b2966144268c212bcf025a6d6b65b)
* Resolves: # 
> UnitBadDocLoad - adapt to new jsdialog behavior.

- common/Unit.cpp
- common/Util.hpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- net/HttpRequest.cpp
- net/WebSocketSession.hpp
- test/HttpTestServer.hpp
- test/UnitQuarantine.cpp
- test/UnitSession.cpp
- test/UnitTiffLoad.cpp
- test/UnitUNOCommand.cpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPILanguages.cpp
- test/WOPIUploadConflictCommon.hpp
- test/WhiteBoxTests.cpp
- test/WopiTestServer.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/FileServerUtil.cpp
- wsd/RequestDetails.cpp
- wsd/Storage.cpp
- wsd/WopiProxy.cpp
Replace a few cases of Util::toString(...), too.
Change-Id: I53c5dbbdf2f60710e94add9dd137aa9becb7bd3e
> Replace Util::startsWith/endsWith w/ C++20 equivalent

- browser/html/cool-help.html
- browser/src/control/Toolbar.js
Change-Id: I7578c621c28b7a5d18c76f2fff834ad2edd68ca5
- this filter not works same as we do search by `Ctrl + F`. 
- it will help user to find sections by search term, it means it will show highlighted sections which have the search term. 
- Also, other section which does not have these matching values will be hidden.
I consider some priorities like Whether to highlight a full section or just a subsection.
- Priority 1: if search term matches main section header, then show that full main section
- Priority 2: if content matches with subsection and not with headers, then show that subsection with main section header.
- Reason to show header with subsection, so user knows better in which context this paragraph/content is about
Test cases
1. Try to search header tags only: it will height …
> Add  filter content with entry widget in help => online-help

- common/FileUtil.cpp
- config.h.in
- configure.ac
- test/helpers.hpp
Should be fully supported on compilers now.
Except leave this workaround in place for now:
b30757417b73180bb02c0e3f20b194ece1516ea1
Change-Id: I6e19ec034b3c64e66f5bf5ff1f436f94514fabd0
> C++17 Remove checks on std::filesystem

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
- cypress_test/integration_tests/desktop/calc/open_different_file_types_spec.js
- cypress_test/integration_tests/desktop/calc/row_column_operation_spec.js
- cypress_test/integration_tests/idle/calc/idle_spec.js
- cypress_test/integration_tests/mobile/calc/autofilter_spec.js
- cypress_test/integration_tests/mobile/calc/row_column_operation_spec.js
- cypress_test/integration_tests/multiuser/calc/repair_document_spec.js
* Resolves: # 
Commit 1:
The autofilter test was failing quite often in the tinderbox. It regularly failed and then passed on rerun locally.
I could not figure out exactly why, but I added a wait so that it will pass.
Commit 2:
I also cleaned up the verification of sheet contents, replacing the custom autofilter function with the one in calc_helper. And I wrapped the function with one whose name says what it does (assert the sheet contents) instead of how it does it (look at the clipboard).
> Fix sporadically failing autofilter test, simplify autofilter and other calc tests

- browser/src/control/Control.DocumentRepair.js
- Do not use translated string `UNDO` and `REDO` as UNO command
- added action prop to handle above change in document repair file
To test
- open document in non-English format
- make some changes in the document
- open document repair
- try to perform REDO or UNDO ops
Change-Id: Ia98270b7623634fe4315988287445f14467df3f9
> Fix: DocumentRepair does not work for non-english

- cypress_test/integration_tests/common/desktop_helper.js
Change-Id: I58f9571dd31d775cadd586f49a545bbc2198471c
* Resolves: # 
Use force click on buttons instead of scrolling the statusbar to make them visible
Fixes failure in master vs 23.05 tinderbox
> Fix zoom button click in cypress tests

- browser/html/cool-help.html
- browser/src/control/Toolbar.js
Enable search input in keyboard shortcut dialog
Refactor main section selection query
-  Select section based on dialog type (either "help-content" or "Keyboard-shortcut-content")
-  There are some section specific to DOCTYPE, so only consider the section based on current DOCTYPE
Refactor show/hide section code
-  we need to add display clock or table-row according to section tag
-  add generic function to show or hide any section or subsection
> Enable search input in keyboard shortcut dialog and refactor main section selection query

- browser/src/map/Clipboard.js
If the user doesn't read the text of the dialog, make it clear that
pressing the button will cancel the process, this is not a warning
dialog to be just ignored.
This is a minimal fix that introduces no new l10n strings.
> cool#8342 browser, clipboard: start improving the paste special dialog's button

- browser/css/jquery-ui-lightness.css
what: jquery ui-tooltip visible when user hovers buttons in the
notebookbar on when user starts a formula in calc (helpful floating
tooltip appears)
Before this commit, ui-tooltip was being set with a harsh
shadow making it more of a main element than a simple tooltip. Best to
don't inherit that strong shadow from .ui-widget-shadow (used in
overlays) and instead set a new one just for tooltip elements.
Change-Id: Ibf3ad525f97decc1d82ca7172ca1fb2bb7c1a6f2
> ui-tooltip: don't inherit the same shadow values as regular overlays

- browser/src/control/Control.UIManager.js
Fixes and gives more details for debugging in case of:
INCOMING: viewinfo: [{"id":3,"userid":"admin","username":"admin","userextrainfo":{"avatar":"http://.../avatar/admin/64","is_admin":true},"readonly":"0","color":0}] cool.html:323:37
Exception TypeError: this.map._viewInfo[this.map._docLayer._viewId] is undefined emitting event [object Object] onUpdateViews@http://.....:9980/browser/08e0fd2e1b/src/control/Control.UIManager.js:823:31
Change-Id: I915f4d6e235426d1ae1d12c64629a6e250c16766
> Avoid exception on view list update (backport 23.05)

- browser/css/jsdialogs.css
With the inclusion of the searching (actually filtering) input field
the dialog would change width mid typing. Example: 1. open dialog: the
width would be x; 2 type something in the search box: the width would
be < x. Better to set a fixed width so if the biggest element is
hidden the dialog doesn't change in size.
Change-Id: I6662433388efa66812317f60a4e0a6bf36e5e98a
> [Backport] Keyboard shortcuts dialog: don't allow width to change after opened

- browser/css/jsdialogs.css
With the inclusion of the searching (actually filtering) input field
the dialog would change width mid typing. Example: 1. open dialog: the
width would be x; 2 type something in the search box: the width would
be < x. Better to set a fixed width so if the biggest element is
hidden the dialog doesn't change in size.
Change-Id: I6662433388efa66812317f60a4e0a6bf36e5e98a
> Keyboard shortcuts dialog: don't allow width to change after opened

- browser/css/jquery-ui-lightness.css
what: jquery ui-tooltip visible when user hovers buttons in the
notebookbar on when user starts a formula in calc (helpful floating
tooltip appears)
Before this commit, ui-tooltip was being set with a harsh
shadow making it more of a main element than a simple tooltip. Best to
don't inherit that strong shadow from .ui-widget-shadow (used in
overlays) and instead set a new one just for tooltip elements.
Change-Id: Ibf3ad525f97decc1d82ca7172ca1fb2bb7c1a6f2
> [Backport] ui-tooltip: don't inherit the same shadow values as regular overlays

- browser/css/cool.css
- browser/src/layer/tile/CommentSection.ts
- cypress_test/integration_tests/desktop/writer/track_changes_spec.js
regression from 4a2e256
Change-Id: Icddb4e5ef631574773e716e02df1a20ac078d44f
> cypress: replace incorrect class name checking

- cypress_test/integration_tests/common/desktop_helper.js
Use force click on buttons instead of scrolling the statusbar to make them visible
Backport to 23.05
https://github.com/CollaboraOnline/online/pull/8362
Change-Id: I58f9571dd31d775cadd586f49a545bbc2198471c
* Resolves: # 
> Fix zoom button click in cypress tests (23.05 backport)

- cypress_test/integration_tests/common/desktop_helper.js
Use force click on buttons instead of scrolling the statusbar to make them visible
Change-Id: Ib6e7eadcfb02f47e7bd4b44c71f44387f0b19168
* Resolves: # 
Previous change (https://github.com/CollaboraOnline/online/pull/8362) did not fix all failures.
> Fix zoom button click in cypress tests (part 2)

- android/lib/src/main/cpp/CMakeLists.txt.in
- ios/Mobile.xcodeproj/project.pbxproj
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/RequestDetails.cpp
- wsd/RequestDetails.hpp
- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd: use RequestVettingStation for async loading
- wsd: restructure RequestVettingStation interface 
- wsd: use a single shared_ptr instead of container for RequestVettingS… 
- wsd: extract ResourceAccessDetails from cool.html file request 
- wsd: make wopiInfo a member of RequestVettingStation 
- wsd: RequestDetails from document-load URI components 
- wsd: parallel load with cool.html 
- wsd: better logging in RequestVettingStation::handleRequest 
- wsd: split createDocBroker into createClientSession
> Parallel Loading of Users' Requests

- common/Util.cpp
- common/Util.hpp
- net/HttpHelper.hpp
- test/RequestDetailsTests.cpp
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
- wsd/RequestDetails.cpp
- wsd/RequestDetails.hpp
We should always have an encoded WOPISrc.
We add detection logic to make sure
that all URIs that contain WOPISrc have
it encoded properly. We do this by
comparing the decoded WOPISrc with
the original URI.
> wsd: detect unencoded WOPISrc

- browser/.eslintrc
- browser/src/map/Clipboard.js
This spec was released 7 years ago, and allows e.g. async/await, which
can result in more readable code in some cases.
There is danger that we return to the main loop too easily using this
construct, so no suggestion to rewrite any of the existing code to use 
this, as that can have side effects on how e.g. we process incoming
websocket messages.
Do use await at a single place to make sure await can be indeed used.
Thanks Hubert to notice that the await-using function itself has to be
async, the error message from eslint isn't too clear in that case.
> es2017: bump eslint version

- kit/Kit.cpp
now that we will typically init the document theme, etc. from the users last used settings, the current rendering state is likely the one that the user wants to use.
The browser-side throws away all tiles, etc on getting a canonidalidchange, so get the current document renderering state to describe this initial state so later LOK_CALLBACK_VIEW_RENDER_STATE events can be compared to this initial state and only emit canonidalidchange if there is a need.
requires https://gerrit.libreoffice.org/c/core/+/163666 to be merged first
Change-Id: I2902ff4e143f432755c335e1225149207fafdfc3
* Resolves: # 
> set the initial rendering state before the first invalidateCanonicalId

- browser/Makefile.am
- browser/js/ResizeObserverPolyfill.js
This reverts commit c69e14a5ddf25dd8ba8494008b112e20f839eacd.
The above commits causes document loading in the iOS app to always fail. Even the animated loading graphic never appears.
I don't know why removing that .js file causes this behavior, but I did see the following in the trace messages in Xcode.
To Online: load url=null accessibilityState=false lang=en-US
It appears that the JS code is sending a null URL to load.
> Revert "Remove unused file."

- browser/src/control/Control.NotebookbarBuilder.js
problem:
if writer->insert tab-> insert comment button is clicked, if button is clicked from icon is works fine,
but if button is clicked on label event is triggered twice, which caused js errors
Change-Id: I3956083b02204733abc3543c73f6019d3a3b4c67
> notebookbar: event prevent default for insert annotation button

- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
Tests desktop/impress/top_toolbar_spec.js and mobile/impress/apply_font_text_spec.js have been failing after a change in core that slightly alters the position of some text elements.
These tests fail when run against core 24.04 but not against 23.05. So there must have been a core that caused them to fail. I have not tried to find the change.
I'm not sure whether to consider this a regression in core or a flaky test here in online. Nevertheless, I'd like to submit these changes to get the tests passing as quickly as possible.
These positions were stable for several years and I don't know why they have changed now.
The new x value of "top_toolbar_spec.js/Apply left/right element" is the same in Jenkins and on my machine, but the y values of "Apply superscript" and "Apply subscript" are …
> Fix cypress impress text position test failures

- browser/src/control/Control.IdleHandler.ts
If the document reloads while the user is on an input field, do not
take the focus away to the document.
Change-Id: If5e97a666ddef6e7c28a30c8bd8ef8bca5f5b336
> keep focus on input field on document load

- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
Close confirm overwrite dialog after pressing insert
The test was failing because there is a dialog to confirm entering overwrite mode. I couldn't find exactly when or where the dialog was introduced.
Annoyingly, the dialog is just a canvas so I couldn't easily click the yes or no button from cypress. Fortunately, the close button is clickable and continues entering overwrite mode.
Change-Id: I4dacb731c70b1bfd9bcbc2134f6e3cd7e242d468
* Resolves: # 
> Fix desktop/writer/statusbar_spec.js

- browser/src/control/Control.UIManager.js
- browser/src/layer/tile/CanvasTileLayer.js
Using same callback caused a regression about showing tooltip while reviewing a change in writer. So we have to use a special message for function usage tooltip.
Change-Id: I6f769a43af6a01ed8e13abfd9c35a57ccd47c1ac
* Resolves: # 
> Handle specific tooltip message for function usage tooltip

- browser/src/control/Control.IdleHandler.ts
- browser/src/control/Control.JSDialog.js
- cypress_test/integration_tests/idle/calc/idle_spec.js
- All dialogs should be closed if document become idle
- There are 2 cases for which all dialogs are being closed before socket closed or before screen dim 1. Document idle : we disconnect from server 2. View idle: only screen dim, server is still connected
To test:
- add auto filter in calc sheet
- open autofilter popup
- wait for document to become idle
Note: change value of `idle_timeout_secs` in coolwsd.xml to test
Change-Id: If76f03d830b8b3744fd2b54d131c5fa85a024c5c
> Close all dialogs on document idle

- browser/src/layer/tile/CommentListSection.ts
problem:
when tracked change show is off, and reply is deleted, it will not be visible so but count shows it, it may cause counfusion to user
Change-Id: I730ebb1b5909b3db75611b5b6d60498d0b796c58
> annotation: don't count deleted reply when tracked change show off (backport)

- browser/src/control/Control.NotebookbarBuilder.js
problem:
if writer->insert tab-> insert comment button is clicked, if button is clicked from icon is works fine,
but if button is clicked on label event is triggered twice, which caused js errors
Change-Id: I3956083b02204733abc3543c73f6019d3a3b4c67
> notebookbar: event prevent default for insert annotation button (backport)

- coolwsd.xml.in
- test/UnitWOPIAsyncUpload_ModifyClose.cpp
- test/UnitWOPIFailUpload.cpp
- test/UnitWOPILock.cpp
- test/WopiTestServer.hpp
- wsd/COOLWSD.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
We no longer send LOOL-WOPI headers, unless
the configuration specifically flags for
legacy servers. But we always send COOL-WOPI
even to legacy servers, to help them upgrade
seamlessly.
Change-Id: Ifc919ed8f6665cd8f846117ef4e8b7ef09fbd563
> wsd: move deprecated logic under legacy_server config

- browser/src/layer/tile/CommentListSection.ts
problem:
when try to insert comment(inside text with existing comment) and comment field is empty, click on some other comment(which is on same text), it will cause an empty comment insertion in DOM which can not be removed until doc reload.
This subsequently prevented new comment insertion.
Change-Id: I29294dcfbbaddddaa768e08b47b855b3e8c7f454
> annotation: avoid resetting comment show state if being edited (backport)

- browser/src/control/Control.Tabs.js
- browser/src/layer/tile/SheetSwitch.ts
This is a regression from 74a4484e "calc: on tab switching document
view can be restored to a wrong position"
Moreover the passed index was wrong when tab is dragged on the right
wrt to current tab position. Now the correct zero based index is
always computed.
Change-Id: I7395773da5a846ce61d8508bbd1d6e2e833d4511
> calc: tab drag&drop does not work properly

- browser/html/cool-help.html
- type="search" for a11y
- spellcheck=false" to avoid red underlines
- localizable placeholder is added programmatically from https://github.com/CollaboraOnline/online/blob/34bf81f14688544d32cbbb0425c594ad1571bc68/browser/src/control/Toolbar.js#L552
Change-Id: I695990a25ccb00821a16738a9388a51001199112
> help search input attributes

- browser/README
- browser/css/jquery-ui-lightness.css
Before this commit, already opened ui-tooltips were being placed on top
of everything, including modal dailogs. Fix that, set jquery css
line to the same z-index used by non-modal dialogs.
Additionally: update browser/README file so it documents this change
and clean up vex legacy bits.
Change-Id: Ie7123822d96c594433ac197aeb9c651aa9b14461
> Modals should always be placed on top of tooltips

- browser/src/control/Control.PartsPreview.js
Backport to 23.05 from #8388
We need to get the right node in the control
See https://github.com/CollaboraOnline/online/issues/6941
Change-Id: Ib37c6411667fcbf4714e6f6448292c84adc78f0e
* Resolves: #6941, #8388   
> 23.05 backport impress: Make sure that dropping a slide between slides reorder correctly.

- browser/css/cool.css
- browser/css/device-mobile.css
- browser/css/mobilewizard.css
Change-Id: Ie20202f48fedb0e062e00f2b4d92eaba425c854e
> css: annotation: removed unused mobile wizard css classes

- browser/src/map/Clipboard.js
Now that
<https://sdk.collaboraonline.com/docs/advanced_integration.html#clipboard-handling>
is figured out, this should be less risky.
Change-Id: I549adad6386d328d7dc5f7e4eeee16446665df82
> cool#8023 browser: try to use the new Chrome clipboard in non-experimental mode

- browser/js/global.js
The URLSearchParams() function was confused in the proxy.php case, because the global.location.search contained two '?' marks, like ?req=/browser/dist/cool.html?WOPISrc=...&lang=..&etc... In the normal case the string started with ?WOPISrc=
Change-Id: I566935656be6622d698ea2ba3c949455877526f6
> Fix processing of URL parameters (in proxy.php case)

- browser/css/cool.css
- browser/src/layer/tile/CommentSection.ts
problem:
when we turn off the option to show the resolved comments, author image was not hidden and stuck on screen which can't be interacted or scrolled
Change-Id: Id0fb30c787b6e8c288df1142b9f882b7633f3dc9
> annotation: fixed resolved comments are not hidden completly

- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.Header.ts
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.RowHeader.ts
- move freeze options from layout tab to view tab
- options should be consistent for both compact and tabbed view
- Add freeze-panes options to column/row headers
> Move freeze options to view tab and add freeze-panes options to column/row header context menu

- wsd/COOLWSD.cpp
Noticed in some k8s deployments where alias groups were defined with port. For lok_allow we need only host name. Avoid adding empty hosts.
> lok_allow: remove also port

- test/helpers.hpp
- test/httpwstest.cpp
- test/test.cpp
- test/test.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
Fix race condition in testSaveOnDisconnect by waiting for kit process to stop instead of just counting total kit processes
Change-Id: I6bda6b114070123a1366bc04eac1873f19928ac0
* Resolves: # 
> Fix for unit-httpws failure

- wsd/COOLWSD.cpp
Noticed in some k8s deployments where alias groups were defined with port. For lok_allow we need only host name. Avoid adding empty hosts.
> lok_allow: remove also port (backport)

- browser/css/cool.css
- browser/src/layer/tile/CommentSection.ts
problem:
when we turn off the option to show the resolved comments, author image was not hidden and stuck on screen which can't be interacted or scrolled
Change-Id: Id0fb30c787b6e8c288df1142b9f882b7633f3dc9
> annotation: fixed resolved comments are not hidden completly (backport)

- browser/css/cool.css
Before this commit annotations could have different widths. A comment
with a very short text - not filling a line - would result in a
abnormal narrow annotation card, screenshot of the observed bug:
https://archive.org/download/collabora-online-comment-width-bug/collabora-online-comment-width-bug.png
Change-Id: I7d51ebf53d5eb9e1361c59cee9ce9ba19e703299
> 23.05: Comment (Annotation): Fix inconsistent width

- browser/src/control/Control.JSDialog.js
[Improve screen-edge jsdialog drag ergonomics](https://github.com/CollaboraOnline/online/commit/b4dc25401442955925833803663047a3ad014f5b) 
When trying to drag a jsdialog offscreen, we previously froze the
dialog. This was frustrating if you dragged a jsdialog to the edge of
the screen, because you then couldn't continue to drag it at all without
moving it away from the edge of the screen, even if the direction you
tried to drag it would not move it offscreen.
An example is if I dragged a jsdialog to the right edge of the screen,
it would be harder to drag it up as it would "stick" to the edge. I
would expect the upwards component of the movement to be honored, even
if the rightwards component could not be.
[jsdialogs: allow limited dragging …
> Make JSDialogs fully reachable when wider than the screen

- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/multiuser/impress/annotation_spec.js
There are now two .avatar-img elements after recent user list changes
Change-Id: Ia229422b4dc3e90ede240e36927b4615091cb97d
* Resolves: # 
> Fix click in impress annotation tests

- browser/html/cool-help.html
- type="search" for a11y
- spellcheck=false" to avoid red underlines
- localizable placeholder is added programmatically from https://github.com/CollaboraOnline/online/blob/34bf81f14688544d32cbbb0425c594ad1571bc68/browser/src/control/Toolbar.js#L552
Change-Id: I695990a25ccb00821a16738a9388a51001199112
> [co-23.05] help search input attributes

- browser/html/framed.doc.html
- browser/src/core/Socket.js
- browser/src/map/handler/Map.WOPI.js
- kit/ChildSession.cpp
CI running on 23.05: https://github.com/CollaboraOnline/online/pull/8467
------------------
PostMessage test page: add export with notify set
This allows to test responses.
-----------------------
Notify WOPI host about status after export
It requires to add `Notify: true` in the Action_Export
postmessage. Result will be sent with `Action_Save_Resp`
----------------------
Make exportas error more informative for user
Replace "The server encountered a xxx error while parsing
the yyy command." with more informative "Document cannot
be exported. Please try again." on export issues.
----------------
Errors can be tested with core patch:
```
diff --cc sfx2/source/doc/objserv.cxx
index b5bde70a3ca6,b5bde70a3ca6..b0c5c8ad2568
--- a/sfx2/source/doc/objserv.cxx
+++ b/sfx2/source/doc/objserv.cxx …
```
> WOPI: Action_Export responses (master)

- browser/html/framed.doc.html
- browser/src/core/Socket.js
- browser/src/map/handler/Map.WOPI.js
- kit/ChildSession.cpp
PostMessage test page: add export with notify set
This allows to test responses.
Change-Id: Idfee8632ac0aeb8a105555e7c9d527288568091e
-----------------------
Notify WOPI host about status after export
It requires to add `Notify: true` in the Action_Export
postmessage. Result will be sent with `Action_Save_Resp`
Change-Id: Iaeee2e22bf1a2ae934eb657116c1878cb6ed50f6
----------------------
Make exportas error more informative for user
Replace "The server encountered a xxx error while parsing
the yyy command." with more informative "Document cannot
be exported. Please try again." on export issues.
> WOPI: Action_Export responses

- browser/src/layer/tile/CommentSection.ts
problem:
when pressed page up/down button inside the annotation textarea, entire view is forcefully pushed upwards to put the cursor at the top of view. This is a chrome bug reported at: https://issues.chromium.org/issues/41417806
Change-Id: I30048374e7b8330cd8c865010e3b4237d355391e
> annotation: prevent page up/down button from messing the view

- Makefile.am
- test/KitPidHelpers.cpp
- test/KitPidHelpers.hpp
- test/Makefile.am
- test/TileCacheTests.cpp
- test/UnitCursor.cpp
- test/helpers.hpp
- test/httpcrashtest.cpp
- test/httpwstest.cpp
- test/integration-http-server.cpp
- test/test.cpp
- test/test.hpp
Wait for doc kits or spare kit counts specifically. This removes the chance of
race conditions between waiting for doc kits to shutdown and the spare kit to
start back up.
Follow up to https://github.com/CollaboraOnline/online/pull/8463, addressing other tests that were using the same helpers.
An incomplete list of things changed:
* Consolidated pid-related functions from countcoolkits.hpp and test.cpp to a new file kit_pid_helpers.cpp/hpp
* Rewrote the retry loop
* Added or clarified lots of log messages
* Simplified pid killing in HTTPCrashTest
* Fixed HTTPCrashTest::testBarren
* HTTPCrashTest::testRecoverAfterKitCrash no longer wastes 20s trying then retrying to connect
* HTTPWSTest::testReloadWhileDisconnecting still failing, it passes if you wait for the process to go away but I …
>  Replace total-pid-count waits with targeted waits 

- browser/src/layer/tile/CommentSection.ts
problem:
when pressed page up/down button inside the annotation textarea, entire view is forcefully pushed upwards to put the cursor at the top of view. This is a chrome bug reported at: https://issues.chromium.org/issues/41417806
Change-Id: I30048374e7b8330cd8c865010e3b4237d355391e
> annotation: prevent page up/down button from messing the view(backport)

- test/KitPidHelpers.cpp
- test/KitPidHelpers.hpp
4 seconds proves too short in some cases
and times out occassionally. 10 seconds
seems more reasonable.
Change-Id: Icede882355a66bf383ebdd87858f1ded77825c5f
> wsd: test: extend process timeout

- browser/src/control/Control.DownloadProgress.js
Have 3 paragraphs in Writer, insert an image in the middle with
(to-char) anchoring. Select all text, copy to trigger the complex copy
codepath. Insert the result to Wrtier, some "text/html" and a number
extra paragraphs appear before the result content in the past result.
Seems the root of the problem is that the clipboard format generated by
ChildSession::getClipboard() is 1) a mime type on its own line 2) size
3) real content; but we just skipped 1) and 2) in the past, but now this
doesn't work, presumably due to a change on the core side.
Fix the problem by just making the header check case-insensitive for
now.
Once I add a html+plain text mode here, I'll probably switch to properly
skipping the first two lines instead, since the plain text won't have a
well-known header to identify …
> cool#8465 clipboard: fix skipping the header of the complex case in JS

- .gitpod.yml
Change-Id: Ibe21ffb1a9743088d20017d3b64144e69b29c3c1
> Gitpod: Update branch parity, use core 24.04 instead

- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.MobileWizardWindow.js
- Fix image path for base spin field icons
- Do not hide or show elements which are force to be hidden in mobile view
> Mobile-view: paragraph section fixes

- Makefile.am
- browser/Makefile.am
- browser/src/layer/tile/CanvasTileLayer.js
- configure.ac
- config: fix eslint 'prettier' package extension
- browser: admin: ignore eslint transpilation code
- config: add 'prettier' command before bundeling process
- browser: fix format style
- browser: simplify eslint call
- browser: create eslint rule
- browser: simplify 'prettier' call
- browser: create prettier rule
- browser: create 'prettier-write' rule
* Resolves: # 
> fix prettier builddir != srcdir

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/contenteditable_helper.js
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/common/nextcloud_helper.js
- cypress_test/integration_tests/common/repair_document_helper.js
- cypress_test/integration_tests/common/search_helper.js
- cypress_test/integration_tests/common/writer_helper.js
Cypress makes it really hard to compare logs to code or to get a backtrace of a failure. This change will make it easier to see when cypress is in a helper function.
There was some of this already, but it was not consistent and it was hard to see in the logs. By using ">>" and "<<" I hope it will be easier to see. And by applying it on nearly every helper function I hope it will be more likely to show the exact point of failure.
Example: It is immediately obvious that the failure is in selectTextOfShape:
```
4) Change bulleting level of selected text.
cy:log ✱  Starting test: integration_tests/mobile/impress/apply_paragraph_props_text_spec.js / Apply paragraph properties on selected text. / Change bulleting level of selected text.
cy:command ✔  cSetActiveFrame	#coolframe
cy:log ✱  >> …
```
> Cypress: log helper function start and end

- browser/src/layer/tile/CommentListSection.ts
problem:
when using display scaling/zooming clicking on comment may cause overlapping on comments if the previous comment from clicked comment is long
Change-Id: I6e9eec3ba5c3fb9f871ce42bb0a554d7e2cc3c5e
> annotation: fix scaled comment positioning(23.05)

- browser/src/control/Control.UserList.ts
- browser/src/layer/marker/TextInput.js
When you are following someone and start typing, it's a pretty good indication that you don't want to be following that person, particularly because if they edit you will then be jumped over to where they are
We also need to stop unfollowAll from always rerendering the user list, as when we rerendered on every keypress there was a noticable performance degredation. Instead, we can make it only rerender when we're following someone, which is a lot better.
Change-Id: I110ca74859b7cee03c6a58c87d3975275f29760d
> Stop following anyone when you start typing

- cypress_test/integration_tests/common/helper.js
- cypress_test/support/index.js
Backport of https://github.com/CollaboraOnline/online/pull/8214
Description and screenshots there.
Has had no issues in 24.04. Would be nice to have these improvements in 23.05 too.
Change-Id: Ic1a20481c05afb05b9c29d0bd428b59615d49dc7
> Cypress test logging improvements (backport to 23.05)

- net/clientnb.cpp
<timar> net/clientnb.cpp:117:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
<timar>   117 |     std::shared_ptr<WebSocket> getWebSocket()
<timar>       |          ^~~~~~~~~~
<timar> net/clientnb.cpp:38:1: note: ‘std::shared_ptr’ is defined in header ‘<memory>’; did you forget to ‘#include <memory>’?
IWYU agrees it's a missing include even if this builds for me by
accident.
Change-Id: I367ef3efcf2bdaf1b69c4bf21ef168e03807365c
> clientnb: missing include

- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.MobileWizardWindow.js
Back port PR : https://github.com/CollaboraOnline/online/pull/8492
> backport mobile wizard paragraph section fixes

- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/mobile/impress/spellchecking_spec.js
- kit/ChildSession.cpp
problem:
before this patch innert textarea svg was not updated after changing text, it was static based on first selection of textbox/shape, to update the textarea we needed to unselect and reselect shape/textbox
Change-Id: I11ceaf76867cecf5a356149d2072181e9f10b86e
> canvas:svg: update inner text area of shape/textbox based on input

- common/Util.cpp
- configure.ac
Change-Id: Id6a2629c06d641eb4e7cf3991de4036d2f7b346e
* Resolves: #5851 
- instead of using /dev/[u]random devices, 
use getentropy() to make direct system calls if the system is a BSD.
- if getentropy() fails, we need to fall back to "/dev/[u]random" approach.
> use getentropy() for BSD systems

- android/app/build.gradle.in
- android/lib/build.gradle.in
- android/lib/src/main/cpp/CMakeLists.txt.in
Android build fails due to use of std::filesystem and
c++20 features like string::starts_with.
cmake requires c++2a flag
std::filesystem requires ndk 22+
Change-Id: Ibba1e5e76a32ba5526d9d7111b810a650f372a02
> android: add support for c++20 and std::filesystem

- browser/src/layer/tile/CommentListSection.ts
problem:
when using display scaling/zooming clicking on comment may cause overlapping on comments if the previous comment from clicked comment is long
Change-Id: I6e9eec3ba5c3fb9f871ce42bb0a554d7e2cc3c5e
> annotation: fix scaled comment positioning

- browser/js/global.js
- browser/src/core/Debug.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
Randomized settings had been getting overwritten by later setup. This change moves the randomization to after the other setup.
Move debug toggle to after docloaded message
Move sidebar toggle even later than that
Change-Id: Ib72b5ef4c2c31f7707a384b2d819d5cde57a796d
* Resolves: # 
> Fix &debug=true and &randomUser=true url parameters

- browser/src/control/Control.JSDialogBuilder.js
- We made some adjustment in core side
- it will now send both property 
1." State" = either button is selected or not 
2."disabled" = either it is disabled or not
- based on above message made some adjustment and refactoring in update function
Core patch : https://gerrit.libreoffice.org/c/core/+/164767
Change-Id: I7aa9bae647252782fcc88bd11b34bf9954741502
> Improve Update state of uno Tool button state on stateChanged

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/vector/SVGGroup.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/mobile/impress/spellchecking_spec.js
- kit/ChildSession.cpp
problem:
if a textbox/shape is being edited and try to move it while still in editing, it was not animated, so user gets illusion that shape was not moved, but in fact it moved and directly appears at the last moved position without animation
Change-Id: I830e368e162b3b38edea0d9240cf82800fa8080a
* Resolves: # 
> canvas: svg: show textbox move animation while edit (backport)

- browser/css/jsdialogs.css
Better to use the same height so to fix the misalignment
Change-Id: If3e76a695a943eee4861479e2ce7b6b1dd287d4f
> Custom properties dialog: Fix height mismatch select and input field

- browser/src/control/Control.IdleHandler.ts
- browser/src/control/Control.UIManager.js
This reverts commit e9cf81f29ecf7fbca69c3ae412dc8660b56142f7.
problem:
when comment is being edited, nothing could be copied from the doc
Change-Id: I34ceacc5d9c7d5eb7d57ec2489a47734b80a044f
forward port for: #8530
> Revert "Check for comments in isAnyDialogOpen"

- browser/css/toolbar.css
- browser/html/cool.html.m4
- browser/src/control/Control.UserList.ts
~~Depending on the page font size, 0.8em may resolve to a different size.~~
~~If this is larger the text will overflow the --btn-size heighted container.~~
~~By sizing based on --btn-size instead, we can avoid this issue. A smaller button can have smaller text.~~
With some styles the following text was too large for the chip.
Unfortunately, sizing it to be consistent made it unreadably small. To
solve this, we can show only the first line of the text in the following
chip and show the second as a tooltip instead.
Change-Id: I4b5306370c31f4d0b13e1a91bf17a9d491807c45
> Stop following text overflowing chip

- browser/src/map/Clipboard.js
Copying from a document, closing it, reopening it and then pasting
did nothing.
The short-circuit for internal paste gave a false positive.
Change-Id: Ib21faf270d2ed03af2954f79bee8c1efbb0fd0ca
> clipboard: do no compare wth invalid metapath

- cypress_test/integration_tests/common/calc_helper.js
Wait for formula bar buttons before typing
Change-Id: I0603fee2acd7ba3090f7b8536a5e5d6f18a52179
* Resolves: # 
> Fix desktop/calc/focus_spec.js (23.05)

- browser/src/core/Socket.js
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- Docbroker only uploads the document when the document is already saved and there are no further modifications.
- But when using typer once dockerbroker saves the document and tries to upload there are already new changes to the document. Therefore, docbroker keeps on saving this new changes and keeps on skiping the upload as there are new changes to the document; until it times out
Change-Id: I427d37a6228299006530daddebdf4365af63588b
* Resolves: # 
> fix: data loss when shutting down while using typer

- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Remove some pre-unipoll legacy superstition =)
> unipoll cleanup - remove obsolete DocumentBroker mutex.

- common/Authorization.hpp
- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- tools/WebSocketDump.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/FileServerUtil.cpp
- wsd/ProxyRequestHandler.cpp
- wsd: new isAdminLoggedIn that only verifies a valid token
- wsd: move stringifyBoolFromConfig to anonymous namespace
- wsd: include cleanup
- wsd: add authenticateAdmin helper
- wsd: simplify isAdminLoggedIn
- wsd: simplify jwtToken extraction
- wsd: parse config only once in Admin
- wsd: minor cleanup of Admin::getLogLines
- wsd: remove duplicate Server and Date headers
- wsd: remove sendWithDateAndAgent
- killpoco: use http::Response for Admin metrics
- killpoco: use http::Response in admin file serving
- wsd: reuse the response in FileServer
> Reuse Response in all File Server Scenarios

- browser/css/cool.css
- browser/src/control/Control.JSDialog.js
- The title of the modal window is currently marked with a `span` tag instead of an appropriate heading tag (such as `h2`, `h3`, etc.).
- This affects the semantic structure of the page and makes it difficult for users with assistive technologies like screen readers to effectively navigate the page.
- The modal title is not recognized as such, which hinders orientation and understanding of the content.
- Solution:
- replace `span` tag with `h2`(header tag) for `ui-dialog-title`. 
- to make font-size consistent, added CSS rule for `ui-dialog-title`.
Note: this will change all JS dialog title with header tags (not only specific to writer but also effected for every document type)
Change-Id: I5a1e276c3a129400aa5834e186a263db95f01833
> accessebility: replace `span` tag with header tag in modal(js dialog) title

- browser/src/layer/vector/Path.Transform.js
problem:
in impress get into textbox editing and then try to drag and move text box, you get js error because map is null
regression from 9cf64b0726a5b8850db02363f125c9a8d285e4e4
Change-Id: I586c5f242241aa50f62c49371c994aeb7c370525
> fixed js console error

- cypress_test/integration_tests/mobile/calc/spellchecking_spec.js
Test failed because of a change in .leaflet-marker-icon
Rewrite openContextMenu and remove uses of .leaflet-marker-icon
23.05 core change that caused the failure: https://gerrit.libreoffice.org/c/core/+/164701
24.04 pull request: https://github.com/CollaboraOnline/online/pull/8589
Change-Id: Iecfacdd192ea723001ed56e6c9f0c32645a6af2c
* Resolves: # 
> Fix failing test mobile/calc/spellchecking_spec.js

- wsd/ClientSession.cpp
E.g. unit-copy-paste emitted a warning like this:
wsd-1576653-1576734 2024-03-20 21:28:53.448488 +0000 [ docbroker_002 ] DBG  ToClient-005: Missing <body> ...
This is a real problem in case the clipboard has HTML, but it's fine
when the clipboard is just plain text.
Fix the noise by returning early when the body of the clipboardcontent
message contains just plain text.
This works because the body never starts with plain text when HTML is
also available: the JSON case is not an issue and the entire clipboard
dump lists HTML before plain text.
Change-Id: I1ff51249fb710e3a9c127917aae4178c22738668
> Related: cool#8023 wsd, ClientSession: fix bogus <body> warning with plain text

- cypress_test/integration_tests/common/calc_helper.js
Finally, a robust solution for checking sheet contents
Uses .should() to make a retriable assertion, subject to normal timeouts and with no need to wait before.
Fixes sporadic failures in desktop/calc/autofilter_spec.js
Example logs:
Pass:
```
cy:log ✱  >> assertDataClipboardTable - start
cy:command ✔  cGet	#copy-paste-container table td
cy:command ✔  assert	expected **[ <td>, 5 more... ]** to have a length of **6**
cy:command ✔  assert	expected **[ Array(6) ]** to deeply equal **[ Array(6) ]**
cy:log ✱  << assertDataClipboardTable - end
```
Fail length:
```
cy:log ✱  >> assertDataClipboardTable - start
cy:command ✔  cGet	#copy-paste-container table td
cy:command ✘  assert	expected **[ <td>, 5 more... ]** to have a length of **5** but got **6**
cy:command ✔  fail:	
Test failed: …
```
> Cypress calc helper: make assertDataClipboardTable retriable

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/multiuser/calc/annotation_spec.js
- cypress_test/integration_tests/multiuser/impress/annotation_spec.js
- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
The annotation tests have always been very flaky and very hard to debug. This should make them simpler and more stable.
Replace four helper functions (insertMultipleComment setupUIforCommentInsert createComment saveComment) with one (insertComment)
Simplify code flow
Remove unneeded docType conditionals
Remove unneded arguments from every call
Use force click to remove extra toolbar clicks
Add more relevant assertions
Apologies for the hard to follow diff in desktop_helper.js because it matched on a random `else`.
The diff in the spec files is all like this:
```
- insertMultipleComment('calc', 1, false, '[id=insert-insert-annotation]');
+ desktopHelper.insertComment();
```
except for the autosave tests, which do not click the save button:
```
- setupUIforCommentInsert('calc');
- …
```
> Rewrite desktopHelper.insertComment()

- cypress_test/integration_tests/common/impress_helper.js
Creates more reliable svg dom
Follow up from https://github.com/CollaboraOnline/online/pull/8545
Change-Id: Ie8adb7b2e543c93a4a23c49dd84aac973543f208
* Resolves: # 
> Use escape in removeShapeSelection

- browser/src/control/Control.DownloadProgress.js
Have 3 paragraphs in Writer, insert an image in the middle with
(to-char) anchoring. Select all text, copy to trigger the complex copy
codepath. Insert the result to Wrtier, some "text/html" and a number
extra paragraphs appear before the result content in the past result.
Seems the root of the problem is that the clipboard format generated by
ChildSession::getClipboard() is 1) a mime type on its own line 2) size
3) real content; but we just skipped 1) and 2) in the past, but now this
doesn't work, presumably due to a change on the core side.
Fix the problem by just making the header check case-insensitive for
now.
Once I add a html+plain text mode here, I'll probably switch to properly
skipping the first two lines instead, since the plain text won't have a
well-known header to identify …
> [co-23.05] cool#8465 clipboard: fix skipping the header of the complex case in JS

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/vector/SVGGroup.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/mobile/impress/spellchecking_spec.js
- kit/ChildSession.cpp
Revert "cypress: fixed tests after textbox/shape svgs updates"
This reverts commit 0601166aa0e5cece07355acbb441dda2d691fb90.
Revert "canvas:svg: update inner text area of shape/textbox based on input"
This reverts commit e796ec7b445b36a2bee4a26e23aad942efff0a84.
Revert "canvas: svg: show textbox move animation while edit"
This reverts commit a6ca6b3cd9e297ad29481e570e4e910e91fe5cbb.
> Revert Textbox move while editing

- common/Authorization.hpp
- net/HttpHelper.cpp
- net/HttpHelper.hpp
- net/HttpRequest.hpp
- test/UnitHTTP.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPITemplate.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/FileServerUtil.cpp
- wsd: new isAdminLoggedIn that only verifies a valid token
- wsd: move stringifyBoolFromConfig to anonymous namespace
- wsd: include cleanup
- wsd: add authenticateAdmin helper
- wsd: simplify isAdminLoggedIn
- wsd: simplify jwtToken extraction
- killpoco: replace HTTPResponse in sendFileAndShutdown
- killpoco: use http::Response for Admin metrics
- killpoco: use http::Response in admin file serving
- wsd: use http::Response in FileServerRequestHandler::preprocessFile
- wsd: reuse the response in FileServer
> Backport: Reuse Response in all File Server Scenarios

- browser/src/control/Control.AlertDialog.js
* Enable security.enable_macros_execution in coolwsd.xml.
* Open a file with a macro.
* Click Help.
Expected result: the popup dialog should not close
Change-Id: I3981c1ddbb3782dd9ee43dc0c9dce282d2f21392
> browser: fix dialog warning alerts

- browser/src/dom/Draggable.js
In Iea4d16918b054d355e6d8695e0dc1d6ededd6793, a regression was introduced where we would check for a specific property of _map when dragging anything. This was needed only in calc to determine the RTLness of the sheet. Unfortunately, _map can sometimes be undefined (such as when dragging around a comment in impress).
By moving the RTL check so it only executes if there is a map, we can avoid this error, but the check will still run where it needs to.
Change-Id: I9994a3957e37975360126fab33ba08e807d723dd
* Resolves: # 
> impress: comment movement: Fix undefined _map error

- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/calc/focus_spec.js
The core commit 'show cell cursor on in place editing' introduced a
regression: cell cursor messages grabs focus from the formula bar when
used for editing. The regression was causing the failure of
desktop/calc/focus_spec.js cypress unit test.
Change-Id: If4274cc510af065feb7aa13806a86746302b22b2
> calc: fix regression due to core commit: 8f7dd2340b7

- browser/src/control/Control.UserList.js
- browser/src/core/LOUtil.js
This is a backport of only the fixing commit of #8633. It doesn't contain the reversion, because the reverted commit was never backported.
> Previously, we would sometimes get the same error event mulitple times,
leading to us erroneously believing that an image which loaded correctly
was invalid. This caused images to sometimes disappear, particularly
when switching to dark mode.
> 
> Additionally, some images are critical to layout so even if they fail to
load we should not 'display: none' them. We can set their src to an
invisible pixel to get a similar effect. We must assume that they have
their width/height correctly set elsewhere or things such as the broken
image would also break the layout.
> backport 23.05: Fix LOUtil.checkIfImageExists reprocessing errors

- browser/src/control/Control.UIManager.js
Position and Size dialog of the shape has a rotation angle widget in rotation tab. User can drag move instead only one click on the rotation angle widget. It causes a permanent tooltip on document. So It is better to handle mousedown instead click to close tooltip.
Change-Id: Idbea0bb8a56568a92f3f4d4c9ee6df1da01b7c24
* Resolves: #8045
> Fix permanent tooltips on dialogs

- browser/src/control/jsdialog/Widget.Combobox.js
- icon URL passed inside `setImage` function was wrong
- line spacing icons are not correctly
- this patch will correct the URL before setImage
Change-Id: Ie733c79c4edae404d934953eaea20632bc18f8da
* Resolves: #8595 
- Before:  ![image](https://github.com/CollaboraOnline/online/assets/61383886/406a5447-6b39-41f3-b165-fa14f7c8159a)
- After:   ![image](https://github.com/CollaboraOnline/online/assets/61383886/865674a4-d696-4197-a399-839b272c45cb)
> Fix image path for line spacing

- browser/src/control/Control.UIManager.js
we now load the document in the initial theme, so we don't need this additional activation of the dark theme.
Change-Id: I523dda19cacd6fd3f81cd86ee554aacd5f73edea
* Resolves: # 
> drop additional activation of dark theme

- browser/css/cool.css
Before this commit annotations could have different widths. A comment
with a very short text - not filling a line - would result in a
abnormal narrow annotation card, screenshot of the observed bug:
https://archive.org/download/collabora-online-comment-width-bug/collabora-online-comment-width-bug.png
Change-Id: I7d51ebf53d5eb9e1361c59cee9ce9ba19e703299
> Comment (Annotation): Fix inconsistent width

- browser/src/control/Control.JSDialogBuilder.js
"An invalid form control with name='' is not focusable."
Change-Id: Ic81d91748371147beed6cbc7b43cc569412760ba
> browser: ignore validation of hidden inputs

- common/Util.cpp
- configure.ac
- instead of using /dev/[u]random devices, use getentropy() to make direct system calls
if the system is a BSD.
- if getentropy() fails, we need to fall back to "/dev/[u]random" approach.
Signed-off-by: Bayram Çiçek <bayram.cicek@libreoffice.org>
Change-Id: Id6a2629c06d641eb4e7cf3991de4036d2f7b346e (cherry picked from commit 93f3bcff825b728ae4756c91172086adf08b7052)
* Resolves: #5851
> [backport] use getentropy() for BSD systems

- browser/src/control/Control.UIManager.js
Tooltip can be modified only when was already initialized. Sometimes we tried to hide it without initilization.
> Fix error on hide tooltip

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ScrollSection.ts
- browser/src/map/handler/Map.Keyboard.js
Add a guard for potentially undefined functions in scroll section. Remove unused variable DEFAULT.
Allow arrow and home, end keys in readonly mode.
Change-Id: Ie695ebf2cd14f49fbb4db2b9ba8f81df5b289591
* Resolves: # 
> Show cursor in readonly mode.

- cypress_test/integration_tests/common/calc_helper.js
Finally, a robust solution for checking sheet contents Uses .should() to make a retriable assertion, subject to normal timeouts and with no need to wait before.
Fixes sporadic failures in desktop/calc/autofilter_spec.js
Backport of https://github.com/CollaboraOnline/online/pull/8608/. Example logs there.
Change-Id: I9c4e36b3bcdf0968e9b95237f3f17f284d2628de
* Resolves: # 
> Cypress calc helper: make assertDataClipboardTable retriable (backport)

- net/Socket.cpp
perf probe -x /usr/bin/coolwsd watchdog_probe
is not (yet?) universally available, at least
Ubuntu 22.04.4 doesn't link per to libtraceevent
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2019247
so use a (obscure) syscall to use as an event instead
Change-Id: I1e4b7ab702b1a25b2ecd627dea4580eef10f8a7c
* Resolves: # 
> do a syscall from the watchdog

- common/Util.cpp
- common/Util.hpp
- common/Watchdog.hpp
- net/Socket.cpp
- net/Socket.hpp
By tracking the thread-id, we can deliver a SIGUSR2 to the right thread at the right time; this avoids perf polling our uninteresting watchdog thread.
In that thread use Caolan's suitably obscure futimestat system-call, so that we can record based on that to see only slow things:
perf record -e syscalls:sys_enter_futimesat -ag --call-graph dwarf,65528
Change-Id: Iad05d8589fdc9541a7d0599f63625d2cde5fdf89
* Resolves: # 
> Watchdog: re-direct USR2 when enabled to snapshot a late thread.

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- browser/src/layer/vector/CanvasOverlay.ts
- browser/src/map/handler/Map.Scroll.js
- browser/src/map/handler/Map.TouchGesture.js
Previously, the document would not always properly follow your finger
when you tried to pan while in a pinch-zoom. In particular, we would
sometimes get this disatrously wrong (e.g. at some zoom levels we would
move our fingers one way and have the document go the other!).
I have rewritten the _getZoomDocPos function to avoid this, in
particular by adding a parameter to keep track of where our zoom started
from which lets us know where we need to zoom around. In the
mouse/button zoom case this doesn't change, but in the touchscreen zoom
case it informs us how much the viewport should have been moved.
I've also changed the surrounding code to use the new logic, in particular
the code which positions the mouse cursor
> calc: Fix pinch zoom positioning

- .gitpod-files/coolwsd-gitpod.xml
- browser/html/cool.html.m4
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/test/load.js
- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
Change-Id: I47c07ed88d68de5fc65b2e5e1e0896bc2a082131
* Resolves: #8484
The changes included:
1. Removal of the `group_download_as` from relavant files.
2. Modification of the relevant logic to default the group_download_as option.
> Removed Group download as option from coolwsd.xml

- browser/css/btns.css
- browser/css/jssidebar.css
- browser/css/notebookbar.css
- browser/src/control/Control.Toolbar.js
Selected state for top toolbar in compact mode. Some code still in unused so added TODOs for later, when we remove w2ui.
jsdialog: css: put toolbuttons rules in btns.css
- put in single place with other button rules
- apply also to .jsdialog case (selected, hover)
so it will be used in new toolbars
-------------------------------------
remove-w2ui: update toolbar item status
- toolbar had it's own status updates
- adjust the old code to use new toolbar functions
> Fix styling of selected toolbar buttons

- browser/src/control/Control.TopToolbar.js
it happens on context change (eg. shape selection) in compact mode where context change handler used wrong instance of toolbar
> Fix TypeError on context change

- browser/css/device-mobile.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileTopBar.js
- browser/src/control/Control.MobileWizard.js
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/control/Control.PartsPreview.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Control.UserList.ts
- browser/src/control/Toolbar.js
- browser/src/docdispatcher.ts
- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/common/interference_user_spec.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/desktop/writer/table_operation_spec.js
- cypress_test/integration_tests/mobile/calc/alignment_options_spec.js
- cypress_test/integration_tests/mobile/calc/annotation_spec.js
- cypress_test/integration_tests/mobile/calc/bottom_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/focus_spec.js
- cypress_test/integration_tests/mobile/calc/formulabar_spec.js
- cypress_test/integration_tests/mobile/calc/undo_redo_spec.js
- cypress_test/integration_tests/mobile/impress/annotation_spec.js
- cypress_test/integration_tests/mobile/impress/undo_redo_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/mobile_wizard_state_spec.js
- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
- cypress_test/integration_tests/mobile/writer/toolbar_spec.js
- cypress_test/integration_tests/mobile/writer/undo_redo_spec.js
- converts mobile top bar to JSDialogs
> remove-w2ui #11: Mobile top bar

- browser/src/control/Control.JSDialogBuilder.js
A11y improvement
Problem
-  The labels for the `select` elements are being associated with a `div` element that surrounds the corresponding `select` element, instead of directly linking it to the `select` element.
-  This creates an unclear semantic relationship between the label and the actual form element, affecting usability for users with assistive technologies
-  this was not only issue with `select` element but for all input selection elements in JSDialogBuilder
Solution
-  `lable` and it's corresponding `input/select` element should have same `for` and `id` values
-   this patch will make `for` attr of `label` equals to `id` attr value of 'input/select' elements
Change-Id: If341174edcdb72af6fde3da14d5ed36ba0c3ae95
* Resolves: # 
> Direct Label Association

- browser/src/control/Control.Tabs.js
If the element 'spreadsheet-tab-scroll' does not exist
when loads document, then scroll to the selected tab.
Change-Id: Iec86225f7ea97a149d455210921daaf91a4e761a
> browser: fix scroll tab when loading document

- browser/src/control/Control.DownloadProgress.js
- browser/src/map/Clipboard.js
This way it can be reused in future code in Clipboard.js when
navigator.clipboard.write() is used, without duplication.
Change-Id: I843577e55802bcb7ad6cbdc5f83919172bc7d3e0
> Related: cool#8648 clipboard: extract parseClipboard() from Control.DownloadProgress.js

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/control/jsdialog/Widget.Combobox.js
A11y improvements
Problem:
- At various places, form elements are linked to the same label both through the 'for' attribute in the
associated label, and through the 'aria-labelled by' attribute in the element itself.
-  This double linkage
can lead to confusion and redundancy, especially when using assistive technologies.
What should we do:
- Remove Redundant Linkage: In most cases, the 'for' attribute in the label is sufficient to
establish a clear linkage. The 'aria-labelled by' attribute can be removed in this case to avoid
redundancy.
- Consistent Use of Attributes: Ensure consistent use of attributes throughout the website. Use
either 'for' or 'aria-labelled by' depending on the context and requirements, but avoid double
linkage
Solution :
- as we made label `for` attribute value …
> Remove Redundant Linkage: `aria-labelledby`

- kit/ChildSession.cpp
- test/UnitCopyPasteWriter.cpp
Visit the
/cool/clipboard?WOPISrc=...&MimeType=text/html,text/plain;charset=utf-8
endpoint, you get a JSON with HTML and plain text. Visit
/cool/clipboard?WOPISrc=...&MimeType=text/html, you get HTML with a
custom header that is only possibly to skip easily because HTML itself
has as well-known header.
This is decied in ChildSession::getClipboard(), which has 3 cases: 1)
single specific format 2) multiple specific formats and 3) all formats.
So far only 2) used JSON, but the new async clipboard copy will want to
(als) request just plain text, where skipping our own custom header is
hard, given that the text itself has no well-known header (unlike HTML).
Solve the problem by always using JSON when a specific format is
requested, so both the HTML and HTML+plaintext case gives JSON.
The …
> Related: cool#8648 clipboard: use JSON when requesting HTML only

- kit/ChildSession.cpp
problem:
when online created file using WOPI clients, creation dates were never set. in online files are created using templates, even empty files are created using an empty template
Change-Id: I312d7af17bf322ca55b6e20bba344e4fc6628e66
> kit: set creation date when online creates file from template

- common/MobileApp.cpp
- common/MobileApp.hpp
- test/UnitWopiOwnertermination.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
- wsd/wopi/WopiProxy.cpp
This allows for creating DocumentBroker and downloading documents in parallel to serving the client files to the browser.
- wsd: cosmetics
- wsd: simplify findOrCreateDocBroker call
- wsd: move overloaded findOrCreateDocBroker to RVS
- wsd: structured binding in findOrCreateDocBroker
- wsd: uninitialized member
- wsd: create DocBroker once CheckFileInfo clears
- wsd: Support ahead-of-time document loading
- wsd: merge single-use findOrCreateDocBroker overload
- wsd: move wopi stub/dummy interface to MobileApp.hpp
- wsd: simplify DocumentBroker construction
- wsd: capture the file size in StorageBase::FileInfo
- wsd: CheckFileInfo parses the JSON response
- wsd: DocBroker with wopiFileInfo
- wsd: remove MOBILEAPP for parsing CheckFileInfo json
> Advance Download

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Clipboard.js
- cypress_test/integration_tests/desktop/writer/copy_paste_spec.js
For one, getting the selection HTML all the time when we create a text
selection is a waste of resources, since only a subsequent copy needs
that HTML. For another, the complex selection case required a confusing
"two step copy" workflow, where first you press Ctrl-C, then you
download the large selection, finally you press Ctrl-C again.
The underlying problem is the same: the document.execCommand() API for
copy (and cut) is synchronous, but network operations are async, which
don't play well together.
Fix the problem by trying to use navigator.clipboard.write() instead:
the write() call still has to happen inside a magic security context
(keyboard used, click happened), but it can take a callback as a
parameter, and inside that callback it's fine to perform async network
operations, …
> cool#8648 clipboard: try to use navigator.clipboard.write()

- browser/src/control/Control.UserList.ts
- browser/src/core/LOUtil.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
- User avatar should first consider if there is already extract info available or not
- if we already have that image source data then please do not set default value
- also when mode change we do preform some refresh function on all icons
- `map.on('themechanged', setupIcon, this);`
- in that case as well, first check if we have user extract info or not
- and based on that set image source URL
Change-Id: Ifbd543322f5222fa7717b40a5ae565ed2f3c9891
* Resolves: # 
> User avatar should be consistent after mode change

- common/Watchdog.hpp
- kit/ForKit.cpp
So watchdog won't fire for a stalling kit.
After a fork the child has only one thread, but a copy of the watchdog object.
Stop the watchdog thread before fork, let the child discard its copy of the watchdog that is now in a discardable state.
And allow it to create a new one on the next SocketPoll ctor.
Change-Id: I7dc166dca3996401fbdc20cd7643f944662454c8
* Resolves: # 
> After fork we don't have a watchdog thread

- kit/Kit.cpp
- kit/Kit.hpp
It needs to be short as it directly affects the time needed to load a document.
> On mobile platforms, the default poll time needs to be short

- net/Socket.cpp
we picked something obscure, and clearly aarch64 took advantage of not adding something obscure unnecessary for backwards compatibility on that arch
Change-Id: I097ef24c98e23931a3997c743d17d52c0afd52b7
* Resolves: # 
> aarch64 doesn't have SYS_futimesat

- browser/src/map/Clipboard.js
- browser/src/map/Map.js
At least on iOS, the new copy handler works as intended and sends an uno message to the LibreOffice code.
> Enable new copy handler on mobile platforms

- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/writer/copy_paste_spec.js
Once the patch from
<https://github.com/CollaboraOnline/online/issues/8648#issuecomment-2037278091>
is applied to make CanvasTileLayer.js _onTextSelectionMsg() not fetch
the clipboard proactively, this test started to fail.
This happened because the test assumed that once a text selection is
created, we have the HTML for it, which is no longer the case.
Fix the problem by extending the dummy clipboard code to also handle
plain text and by adding a function which triggers the copy(), to
minimize the changes to the actual test code.
This is just a start, lots of other tests still need fixing, and once
the pattern is clear, common code should be extracted to
cypress_test/integration_tests/common/helper.js, probably.
Change-Id: …
> cool#8648 clipboard: fix desktop/writer/copy_paste_spec.js

- browser/src/control/Control.UserList.ts
A nice followup would be a change to automatically do this on all JQuery tooltips, maybe I will make a commit to do that later
Change-Id: I545f5e8d45849fb1b000c321b3554efd874eaaf8
* Resolves: # 
> Fix formatting on JQuery join tooltip

- Makefile.am
It will launch the gui at the end if found
It's much faster than valgrind+massif
Change-Id: Ied5a00ab634f78bbb0dd24a48a83ae4293183cd4
* Resolves: # 
> Makefile: added a target to run with heaptrack

- browser/src/layer/tile/CanvasTileLayer.js
every _postMouseEvent in a spreadsheet calls _setSpliterGradient which triggers a redraw
```
_applyDelta [bundle.js:18978:86]
ensureCanvas [bundle.js:18941:64]
TilesSection.prototype.ensureCanvas [bundle.js:15642:88]
TilesSection.prototype.drawTileToCanvasCrop [bundle.js:15654:54]
TilesSection.prototype.drawTileInPane [bundle.js:15503:66]
TilesSection.prototype.paintWithPanes [bundle.js:15481:48]
TilesSection.prototype.paint [bundle.js:15532:78]
TilesSection.prototype.onDraw/< [bundle.js:15602:52]
TilesSection.prototype.forEachTileInView [bundle.js:15536:71]
TilesSection.prototype.onDraw [bundle.js:15592:56]
CanvasSectionContainer.prototype.drawSections [bundle.js:14091:56]
CanvasSectionContainer.prototype.requestReDraw [bundle.js:13724:76]
CanvasOverlay.prototype.redraw …
```
> _setSpliterGradient triggers excess drawing

- tools/mount.cpp
We fall back to MNT_FORCE only when
MNT_DETACH fails. Also improves when
we log the error to stderr.
Change-Id: I8b8b2a863b0339ddd489f1d0150446e6bae82a8a
> mount: smarter umount handling

- browser/src/map/handler/Map.SlideShow.js
Open an empty popup with a blank url, then set the content of the popup to be our slideURL wrapped inside an iframe with a user friendly title.
Focus the iframe on load so that arrowkey navigation works and forward the eventlisterner of the iframe to the parent window to watch for escape key calls
Change-Id: Ie1063095db51119fd45453b8b4b180fcacb6d7c1
* Resolves: # 
> Change convoluted url and name in windowed presentation

- common/MessageQueue.hpp
- kit/Kit.cpp
- test/FileServeWhiteBoxTests.cpp
- wsd: redunce string concatenation churn
- wsd: test: move single-use local map
- wsd: remove unused eof from the TileQueue
> Coverity Fixes

- browser/html/cool.html.m4
- browser/js/global.js
One way for integrations to ask for dark mode is to set URL parameters.
This works for e.g. the language, but didn't work for dark mode.
There was already a parameter for this, but it was limited to Android.
Fix the problem by exposing the parameter for non-Android as well, and
also extend global.js to default to this, but keep the local storage as
an option to customize the setting if the user wants to.
Tested with 'make run', <input type=hidden> way may need more work on
top of this.
Change-Id: I78c4115a8e337ef2b1ea9e498db2572965762bef
> cool#8734 browser: allow enabling dark mode from a URL parameter

- browser/src/control/jsdialog/Widget.Combobox.js
Add accessibility support to combo-boxes inside font panel in sidebar so that screen reader can read with ease.
- Add aria-label to input if aria properties present in the widget data
- Add appropriate roles to input and div as per standards mentioned in MDN docs for accessbility combobox
- Modified combobox button click event to open popup using Space key as well, as mentioned in the MDN docs for accessbility
Change-Id: I66ebc6897e6a9a73a65f53d5cbd2f06a645dcb3f
Change-Id: Id39242ea2fa57f8f5a46efca7a73b529ceae088d
> Add accesibility support to comboboxes inside font panel in sidebar

- browser/src/control/Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Type a word into Writer, select it, Ctrl-K, the link text should default
to the selection, but it was empty.
This happens because Toolbar.js getTextForLink() doesn't have the
pre-fetched clipboard anymore, so we return an empty string there.
Fix the problem by triggering a text selection fetch (and leaving the
clipboard alone), and then handling the hyperlink dialog on the
CanvasTileLayer.js side.
Once this is done, the usual dummy clipboard registration & copy() calls
need adding and the test passes even with the patch from
<https://github.com/CollaboraOnline/online/issues/8648#issuecomment-2037278091>.
Change-Id: Ibd8313588e705c4b027643b452099bbf02cfe8ec
> cool#8648 clipboard: fix insert hyperlink dialog

- browser/src/control/Control.NotebookbarImpress.js
Change-Id: I8b2824f6a17091d1a5202051cc95b6a53013f0cf
* Resolves: # 
> [Backport] fix : Present in the window button hides only for mobile apps

- kit/ForKit.cpp
The SocketPoll ctor which may, depending on COOL_WATCHDOG env variable, want to override the SIG2 handler so set user signal handlers before that otherwise tthat choice is overwritten
Change-Id: I305570ab8becb41f0696e60908c1ca26fd9ba14a
* Resolves: # 
> use SigUtil::setUserSignals before creating SocketPoll

- browser/src/control/Control.MobileTopBar.js
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/mobile/writer/toolbar_spec.js
Hide disabled elements on mobile top-toolbar
- we disabled some specific button on mobile top toolbar
- but just disabling it won't hide that from UI
- maybe it is better to not show those buttons
- it also occupies much space in top view
Add read-only option in JSON for all application
- Read-only option was only present in writer before this patch
- this will add option for all other Apps: Calc,Draw,Impress
- There is slight issue while getting the read-only flag for MobileTopBar . 
- `app.map. isReadOnlyMode ()`: Still not work because at point of getToolItems() no permission had be setted in permission.js file for function `isReadOnly()`
- it means this._permission still undefined when we cal `app.map. isReadOnlyMode ()` from Control.MobileTopBar.js
> Hide unwanted toolbar btns for readonly in mobile & Add reaonly option for other application in mobile view

- browser/css/toolbar.css
Avatars on the user list where shown too big
When userlist-dropdown was separated from userListHeader as a
JSDialog, the proper avatar-img css stopped applying.
Change-Id: I58539c492758c4ecea09d598ba7e113034078cd9
> browser: correct avatar css on userlist

- browser/src/control/Control.UserList.ts
- browser/src/core/LOUtil.js
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
Problem :
- Open the document which have some comment from other User
- we can see that they are same as the logged in user avatar
Regression
- this is a regression from commit https://github.com/CollaboraOnline/online/pull/8640/commits/e855aa6114bda90fdd64fbcbb32a77adcf7938f4
- we were passing url of user which is logged in and that should not happening for other user avatar image
Solution: - while setUserImage function pass viewId
- this will help to identify the user Info from map
Change-Id: I5ee8b41c2e58a4ba15ecf551b264f944aa926da8
* Resolves: # 
> Fix header avatar have the same image of current UserList

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/map/Clipboard.js
At least on iOS, the new paste handler needs to send an uno message to the LibreOffice code.
Also, reenable fix for GitHub issue #5839.
> Enable new paste handler on mobile platforms

- browser/src/control/jsdialog/Widget.Combobox.js
eslint now forces single quotes.
Change-Id: Ia462bc21bc720b64caf5d535eb46e637e24b9f4a
> browser: fix merge conflict in Widget.Combobox.js

- browser/css/cool.css
- browser/src/layer/tile/CommentListSection.ts
Make comments window bigger, if needed, and possible. Selected commits grow up to MAX size, even if there is no space for it.
There is 2 constant limitation:
MAX - --annotation-max-size this is the maximum size commentText window can grow. If the comment have more text, than it will have scrollbar.
MIN - --annotation-min-size if there is not enought space, but comment have more text, this is the minimum size of commentText window.
note: commentText window can be smaller then MIN, if it has less text.
During doLayout:
first, in resetCommentsSize comments size resets to default. (max-height = MIN size.)
after comments positioned with loopUp / loopDown,
resizeComments check all comments (maybe it could be optimized)
If a comment have more text as its actual size, then it check the space …
> writer: resize comments based on space

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialogBuilder.js
- do not focus separators or spacers on tab keyboard button
- use variable for separator color
> remove-w2ui: statusbar focus fix

- wsd/DocumentBroker.cpp
Change-Id: I66d80d415ea8e19823ccb7e6b3e8b6af1df51fbc
* Resolves: # 
> unwanted extra quote at end of true in json

- cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
error is:
1) Joining a document should not trigger an invalidation
Join after document save and modify:
CypressError: Timed out retrying after 10050ms: `cy.click()` failed because this element:
`<div class="leaflet-layer" style="position: absolute; width: 642px; height: 484px;"></div>`
is being covered by another element:
`<div class="jsdialog ui-button-box end" id="">...</div>`
Fix this problem, or use {force: true} to disable error checking.
Change-Id: I8b0dde030b2aadf554db75872facb6c5c96a321c
* Resolves: # 
> try adding {force: true} to leaflet-layer clicks

- net/Socket.cpp
which is more efficient than repeatedly erasing in a vector.
Change-Id: Iebd41130b37a67ffd74fa2d692b83220b1cab3f4
* Resolves: # 
> use erase/remove idiom to clean pollSockets

- common/SigUtil.cpp
- common/SigUtil.hpp
- kit/Kit.cpp
Potentially zombie / badly behaving kits should be taken down by the kernel, and this lets us continue our cleanup by killing just the parent process.
Change-Id: I1e81f41cded0c67b72622f8ed88602daf427238c
* Resolves: # 
> bgsave: ensure kit processes die when their parents do.

- .github/workflows/codeql-analysis.yml
see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
Change-Id: I92253f747b8bbb9d365bb49b40402c832d63d0de
* Resolves: # 
> Use CodeQL Action v2

- browser/src/control/Permission.js
If wopi.UserCanWrite tells us we can't write the file no reason to show the edit button that would do nothing anyway.
Fix https://github.com/CollaboraOnline/online/issues/8686
Change-Id: I4f6d1f8d8be520e422e260f2e532cb86541e8d0f
* Resolves: #8686
> permission: Don't show the edit button if read-only

- wsd/DocumentBroker.cpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
In certain scenarios, such as with Proxy.php,
we don't have CheckFileInfo in advance and
need to request it before proceeding further.
This adds a wrapper to wait for the
CheckFileInfo request to complete.
Change-Id: I8afa955f841899eb667c02168a29a68c1dffb21b
> wsd: support synchronous CheckFileInfo

- browser/src/core/LOUtil.js
- browser/src/layer/tile/CommentSection.ts
In e855aa6114bda90fdd64fbcbb32a77adcf7938f4 a regression was introduced where a comment avatar was set to your avatar if the user was not in the document
This commit returns it to the previous behavior, which had a "default" avatar instead. It might instead be nice to embed avatars in the document to avoid the avatars being missing, however the previous behavior is far less confusing than the regressed behavior and is far easier to get to than embedding avatars in the document
Change-Id: I82834089062b1e7c2570d9fd78c7e1a3077f4c96
* Resolves: # 
> comments: fix avatar when author is not in document

- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- it might happen viewinfo message arrives before status message, viewinfo message update view list with old _viewId because new _viewId after reconnection is not avaialable yet
- this patch fixes this by reseting the _viewId on socket close and call updateviewlist event after client gets new _viewId from status message
Change-Id: I88a6ade574faa1368b1635db891fe87f89fa080e
* Resolves: # 
> fix: duplicate `You` on reconnect
