loleaflet/src/control/Control.PartsPreview.js, loleaflet/src/control/Parts.js, loleaflet/src/map/Map.js
We should limit the on-fly preview requests to stop trashing
the server with countless preview requests
depending on the slide size and ask for more when we have them
rendered.
This patch adds the preview tile requests to a queue to be sent to server
as 3 requests at a time until they are rendered and received by the client
Also adding them to the queue allows us to check whether we already have
the same tile in the queue waiting to be sent which we can avoid sending
twice.
Change-Id: I03684dc807a7aef6c996a91efba100a9dca9686d
* Resolves: # 
=> Throttle preview requests on Impress

loleaflet/Makefile.am, loleaflet/css/jsdialogs.css, loleaflet/src/control/Control.JSDialog.js, loleaflet/src/control/Control.JSDialogBuilder.js, loleaflet/src/control/Control.MobileWizard.js, loleaflet/src/control/Control.MobileWizardBuilder.js
We need JSDialogBuilder to be a common class for other builders.
MobileWizardBuilder will handle mobile specific cases only.
Change-Id: Icff024fe70d0e5386c92bdd106b6db2e74a584b5
* Resolves: # 
=> jsdialog: make MobileWizardBuilder a separate thing

loleaflet/src/control/Control.LokDialog.js
Unfortunately when show/hide sidebar the "offsetWidth" property
works only if the element is visible otherwise it returns parent
empty size.
To fix add temporary a visibility property, then obtain the sidebar
"offsetWidth" property and update document container size.
Change-Id: I8e1c821518a4c155340edcfc8f2313098edff8b0
=> loleaflet: fix "offsetWidth" property value of the sidebar panel

cypress_test/integration_tests/mobile/calc/formulabar_spec.js
It's state is inconsitent and so it fails randomly.
Change-Id: Icd84d618fc87e64228918ad2e6e1ac602eac0e05
=> cypress: don't use togglemergecells as an indicator here.

loleaflet/src/control/Parts.js, loleaflet/src/layer/tile/TileLayer.js
We dont send broadcasts anymore for thumbnails
therefore no need to use higher dpi in case
we have highdpi views. This causes glitching on the thumbnail
especially when a watermark is applied. It gets smaller and bigger
back and forth and also this mean x2 more rendering for single preview.
Change-Id: I80ba8c70bcd9d5d3c00c2ddffadae11a6b0b2e61
* Resolves: # 
=> Fix different size thumbnail rendering problem

loleaflet/src/control/Control.LokDialog.js
Always call resize update when sidebar modifies the document
the size values, this will cause internal events to update the
document bounds, zoom, etc.
Change-Id: If8efce4b08b96e6156a87f69fe6188cf9d75f5d5
=> loleaflet: update the document container when the size changes

loleaflet/css/loleaflet.css
- set a fixed bottom position only when on calc (due to tabs)
Change-Id: I9f98cdc65e83c06da814fe7b89b43ebbe6760f40
=> Sidebar: avoid using two sidebars by fixing bottom position

loleaflet/src/control/Control.ColumnHeader.js, loleaflet/src/control/Control.Header.js
Change-Id: I12a071877548dda02a5c6199ade570c74f8dc7ee
* Resolves: # 
* Target version: distro/collabora/co-4-2 
problem: in mobile we could resize the column from anywhere in entier header
This caused problem because of the small size we may resize adjacent column
now allow user only to resize from resizing area even if resizing handler are invisible
=> leaflet: avoid wrong column resizing in mobile

loleaflet/src/map/Clipboard.js
…browsers
This undoes the plumbing change in
0752631deac1e427294ebec932be6624df220452 for desktop and non-iOS mobile browsers.
Change-Id: I3452f18ec005a44c06ec7e4d17ede111c7c7e4c0
* Resolves: # 
=> Attempt to fix the "Copy Hyperlink Location" for desktop and Android … (cherry-pick from co-6-4)

loleaflet/src/layer/marker/TextInput.js
Our existing function getValueAsCodePoints() returns an array of
integers that are Unicode code points, as its name says. (Code points
can be larger than 65535, especially for emojis and interesting
scripts). It does not return an array of UTF-16 code units (which are
always less than 65536).
Still, the code used the JavaScript function String.fromCharCode() on
the elements of the returned array. That function expects UTF-16 code
units, and it simply truncates the argument to 16 bits. This obviously
leads to very wrong results.
There is a function String.fromCodePoint() that would work, but it
isn't present in MSIE so we can't use it. Instead, introduce a new
function codePointsToString() that works properly, producing surrogate
pairs as necessary.
Additionally, the code in …
=> Fix various problems in handling of non-BMP code points (cherry-pick from co-6-4)

loleaflet/src/layer/marker/TextInput.js
Our existing function getValueAsCodePoints() returns an array of
integers that are Unicode code points, as its name says. (Code points
can be larger than 65535, especially for emojis and interesting
scripts). It does not return an array of UTF-16 code units (which are
always less than 65536).
Still, the code used the JavaScript function String.fromCharCode() on
the elements of the returned array. That function expects UTF-16 code
units, and it simply truncates the argument to 16 bits. This obviously
leads to very wrong results.
There is a function String.fromCodePoint() that would work, but it
isn't present in MSIE so we can't use it. Instead, introduce a new
function codePointsToString() that works properly, producing surrogate
pairs as necessary.
Additionally, the code in …
=> Fix various problems in handling of non-BMP code points

loleaflet/src/layer/tile/TileLayer.js
Change-Id: I2c4bd4e46a42854bdcc5a09f6af170d33dc4e8c0
* Target version: distro/collabora/co-6-4  
problem:
once text inside the cell is selected,
taping on other cell does not remove the selection
=> leaflet: calc text selection is never removed

cypress_test/integration_tests/mobile/impress/annotation_spec.js, cypress_test/integration_tests/mobile/writer/annotation_spec.js, cypress_test/integration_tests/mobile/writer/focus_spec.js, cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js, cypress_test/integration_tests/mobile/writer/insert_object_spec.js, cypress_test/integration_tests/mobile/writer/toolbar_spec.js, loleaflet/css/device-mobile.css, loleaflet/css/mobilewizard.css, loleaflet/src/control/Control.JSDialogBuilder.js, loleaflet/src/control/Control.MobileTopBar.js, loleaflet/src/control/Control.MobileWizard.js, loleaflet/src/layer/AnnotationManager.js, loleaflet/src/layer/AnnotationManagerImpress.js, loleaflet/src/layer/marker/Annotation.js, loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/ImpressTileLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/tile/WriterTileLayer.js
Now in mobile, all the comments will be shown into the wizard.
* Tapping on the comment will highlight the text/cell/object on which comment is made
* In writer tapping on a comment will open the comment thread 
* In other application tapping on a comment will just highlight the text/cell/object
=> leaflet: Mobile Comment Wizard

common/Util.cpp, common/Util.hpp, fuzzer/ClientSession.cpp
The fuzzer ran out of memory, 955443527 bytes (79%) of the used memory
was this map.
Change-Id: I2dd84a094d3dd3d98618667e3c78591e2193bce2
=> fuzzer-clientsession

configure.ac
The "AC_LINK_FILES" is replaced by "AC_CONFIG_LINKS"
Change-Id: I4821f56e437faa0a9adc523b31ac4c5905c4276e
=> configure: replace obsolete configuration links

loleaflet/src/control/Control.TopToolbar.js
In Impress, the Clear Direct formatting button sends a uno:SetDefault command. The bug existed because the uno:SetDefault command was not captured in the Control.TopToolbar.js file. I added the uno command and set the hidden attribute to true to enable the button show up only when an impress document is loaded
Change-Id: I13c96856714c63df5929087f14af3fa2b4628462
* Resolves: # 
=> Impress: A fix on Clear Direct Formatting attribute

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.cpp, wsd/Storage.hpp
Some preparation work for asynchronous IO:
- wsd: extract wopi upload response handling
- wsd: session is optional to broadcasting doc modification time
- wsd: extract storage saving reponse handling
- wsd: make session in the upload details weak_ptr
- wsd: label storage operations as upload and download
=> Storage refactoring for Async IO

loleaflet/src/control/Control.NotebookbarBuilder.js, loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
grid -> container,
for grid handler there were 'top' and 'left' properties missing.
issue appeared when I implemented real grid handler based on positions.
Change-Id: I90d63188b77ec6590123648f8833a387d1463622
* Resolves: # 
=> notebookbar: fix custom tabs

loleaflet/css/loleaflet.css
- set a fixed bottom position only when on calc (due to tabs)
Change-Id: I9f98cdc65e83c06da814fe7b89b43ebbe6760f40
=> Sidebar: avoid using two scrollbars by fixing bottom position

cypress_test/plugins/blacklists.js
Change-Id: I6762c08b9a921eb942ee537195cbe530f3260dc1
=> cypress: NC: disable failing 'Automatic spell checking.' test.

loleaflet/css/spreadsheet.css
- Tabs get restyled due to inline button rules
- Improve positions and sizes
- Remove redundant declarations
Change-Id: I65dfdafd0db359ffaeea76e41fa82bb7fd8defe5
=> Spreadsheet tabs glitch when opening Help dialog

loleaflet/src/control/Control.TopToolbar.js
Impress: A fix on Clear Direct Formatting attribute
In Impress, the Clear Direct format button sends an uno:SetDefault command while in writer and Calc, the Clear Direct Format button sends an uno:ResetAttribute command.
The bug existed because the uno:SetDefault command was not captured in the Control.TopToolbar.js file.
I added the uno:SetDefault command and set the hidden attribute to true. I also set the hidden attribute of the uno:ResetAttribute to true.
This is to create these Clear Direct Formatting buttons as hidden and show them for their respective documents.
Change-Id: I37439a902684f015ffcc8d0a9acde40fec3603d5
=> Impress: A fix on Clear Direct Formatting command

loleaflet/css/notebookbar.css
- or ipad
- vex dialogs examples: shortcuts and help
Reset z-index to be the same as in `main-menu(desktop-only)`:loleaflet/README
Change-Id: Ib9bf635c03312e4302b14d99fc5c461bc0f7fb0d
=> notebookbar-shortcuts-bar: overlays vex dialogs on small screens

loleaflet/src/control/Control.PartsPreview.js, loleaflet/src/control/Parts.js, loleaflet/src/layer/tile/GridLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/map/Map.js
Fetch the tiles of the part that is in the direction
of travel. This way we will avoid the tear effect
while browsing the tiles sequentially.
Change-Id: Ie47d1174f986253e4b43aa0c3276f05e7ddd0c81
* Resolves: # 
=> Pre-fetching next or previous slide tiles

common/Util.cpp, common/Util.hpp, fuzzer/ClientSession.cpp
The fuzzer ran out of memory, 955443527 bytes (79%) of the used memory
was this map.
(cherry picked from commit 10c1885a83850139bb9b88ed9a6109428a7f42d5)
Change-Id: I2dd84a094d3dd3d98618667e3c78591e2193bce2
=> fuzzer-clientsession: fix out of memory

loleaflet/src/control/Control.ColumnHeader.js, loleaflet/src/control/Control.Header.js, loleaflet/src/control/Control.RowHeader.js, loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js
Change-Id: I7442f69d7653b2eb95ec60b281d4b61533dbf2ff
* Resolves: # 
This commit resolves:
* Sizing of column and row headers of Calc.
* Uses core pixel sizes for tiles.
=> Calc: use pixel coordinates for pane sizing

loleaflet/package.json
I am using the "npm" version 7.0.12, and after
bundling the "loleaflet", the "package.json" is modified.
Let's sort permanently so I cannot get contaminated with
something that I did not touch in my source directory files.
Change-Id: I6a1e6d6b3f1b2898288f06de85fc0307b62cbbeb
=> loleaflet: sort the packages in package.json

kit/Kit.cpp
The different attributes of a document/user
are decoded when the kit receives them.
Decoding them a second time is usually harmless,
unless, that is, they contain '%'.
After the first decoding the '%' character might
not be escaping anything valid (depending on what
follows it). So a second attempt at decoding
might very well fail and throw, since the escape
code is invalid.
Change-Id: I73d56ce995b0237140a54b6c06bd36bde8b387bd
=> wsd: do not decode already decoded fields

cypress_test/integration_tests/mobile/writer/table_properties_spec.js
This reverts commit e1ed5d3c299f2664d108375a5ea3cb90814556a4.
=> Revert "cypress: use moveCursor() helper method in table tests."

net/Socket.cpp, net/Socket.hpp, wsd/Admin.cpp, wsd/Admin.hpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp
A number of call-sites, eg. clipboard, or admin-ws were
writing to sockets assuming they could return all the data
in a single series of writes, without needing to poll. As
such they failed to addSocketToPoll on the new poll - eg.
the docBroker. Unfortunately this meant that on EAGAIN
writes, the socket would be closed and the last parts
of a message lost.
Browsers would give net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
The situation is/was intermittent, so painful to debug.
On under-loaded developer machines, socket buffers are larger,
so this was seldom seen.
The re-factor forces a transfer to another SocketPoll via
the disposition, except for a couple of corner cases.
Change-Id: I2f1b2f99f179c4fda84464c9241fe434fa527725
* …
=> Socket - re-work disposition to ensure we transfer sockets.

common/Log.hpp, common/Png.hpp, common/RenderTiles.hpp, kit/ChildSession.cpp, kit/Kit.cpp, net/DelaySocket.cpp, test/UnitPrefork.cpp, test/countloolkits.hpp, wsd/Admin.cpp, wsd/AdminModel.cpp, wsd/AdminModel.hpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp, wsd/Storage.cpp, wsd/Storage.hpp, wsd/TileCache.cpp, wsd/TileCache.hpp
This is an attempt at avoiding mixing int/double with implicit units of time in favor of std::chrono, which does all that and more in a type safe and efficient fashion.
=> Use chrono data types for type-safety and readability where possible

loleaflet/css/jsdialogs.css
- use original icon size and add margins
Change-Id: I8fb77a147e9bbe16be29b8c53e38052fe3abb41b
=> PivotTable: AutofilterDropdown: Fix toggle_all.checkbutton sizes

loleaflet/src/layer/tile/TileLayer.js
Occurs when using the latest LO master branch
the mobile wizard fails:
Util.js:107 Uncaught RangeError: Maximum call stack size exceeded
at String.split (<anonymous>)
at Object.splitWords (Util.js:107)
at NewClass.on (Events.js:20)
at Function.listenNumericChanges (Control.JSDialogBuilder.js:124)
at _formattedfieldControl (Control.JSDialogBuilder.js:1312)
at NewClass.build (Control.MobileWizardBuilder.js:145)
at NewClass.build (Control.MobileWizardBuilder.js:150)
at NewClass.build (Control.MobileWizardBuilder.js:150)
at NewClass.build (Control.MobileWizardBuilder.js:150)
at NewClass.build (Control.MobileWizardBuilder.js:150)
The builder recursive looks like an infinity loop,
and the cause is that the server is not sending the array children
data type.
Change-Id: …
=> mobilewizard: warn children data type check

loleaflet/css/spreadsheet.css
Change-Id: Ic04b8acc43b2863bd3f3483d7d3f14438bf8fd6f
before: 
after: 
Things to notice here after applying the patch is that headers are aligned and row header border is now visible which was covered earlier.
=> leaflet: aligned sheet grid with headers

loleaflet/src/control/Control.JSDialog.js, loleaflet/src/layer/tile/TileLayer.js
Unfortunately when firifing the event "jsdialog"
this._map.fire('jsdialog', msgData);
the data type is replaced with the event type
Change-Id: Ib7ceb96c5fad82dc2d9db61d8399d7fa858c7044
=> jsdialog: fix the type dialog

loleaflet/src/layer/tile/TileLayer.js
Occurs when using the latest LO master branch
the mobile wizard fails:
Util.js:107 Uncaught RangeError: Maximum call stack size exceeded
at String.split (<anonymous>)
at Object.splitWords (Util.js:107)
at NewClass.on (Events.js:20)
at Function.listenNumericChanges (Control.JSDialogBuilder.js:124)
at _formattedfieldControl (Control.JSDialogBuilder.js:1312)
at NewClass.build (Control.MobileWizardBuilder.js:145)
at NewClass.build (Control.MobileWizardBuilder.js:150)
at NewClass.build (Control.MobileWizardBuilder.js:150)
at NewClass.build (Control.MobileWizardBuilder.js:150)
at NewClass.build (Control.MobileWizardBuilder.js:150)
Change-Id: I743ce22f62a1436d7814d6a414f6b703cd3df997
=> jsdialog: warn children data type check

loleaflet/css/jsdialogs.css
When Macro Dialog Selector dialog is shown,
the empty list box is too small.
Change-Id: Ic07d2e027c250744f0e830d648a5d0865a3375ee
=> jsdialog: increase minimum width and height

loleaflet/src/layer/ImageOverlay.js, loleaflet/src/layer/Popup.js, loleaflet/src/layer/marker/Cursor.js, loleaflet/src/layer/marker/Marker.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/GridLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/vector/Renderer.js, loleaflet/src/layer/vector/SplitPanesRenderer.js, loleaflet/src/map/handler/Map.TouchGesture.js
These are remnants of the css-based zoom animation, they will not be
used with the new, canvas-based zoom animation.
Change-Id: I331968be144b0fbc3f5c8850cc08bac0b6e8f011
=> canvas layer: Kill the _animateZoom() methods.

loleaflet/css/mobilewizard.css, loleaflet/src/control/Control.JSDialogBuilder.js
- make top level look like cards with their padding etc
- add class for comment threads and make it look like we entered the thread (thus the list style)
Change-Id: I062841c645d416b7db4dc20302e2095d77416f8d
=> mobileWizard: Fix comment layout and avoid inline syles

loleaflet/css/btns.css, loleaflet/css/jsdialogs.css
- Update btns acording to last changes and add missing margins
- Make sure search input field occupies all available space
- Submenu: Remove extra border as it has already one (since it's a box
inside of a box without any other siblings)
- Make sure entries inside of Autofilter do not have additional padding
Change-Id: Ia7cc4690b99f46976ed1f7590fbbc6fd606cf9f1
=> JSDialog: Autofilter: Fix font, Fix Ok btn, Fix search width, Fix submenu, Fix entries

net/SslSocket.hpp
This merges OpenSSL's poll events with ours.
Effectively, we now do a single poll when
there are reads and writes to be done,
regardless of the reason (i.e. SSL-specific
or application-specific).
Simpler code, and more efficient performance
by sharing code with http and reducing the
number of poll syscalls.
Change-Id: Ib329c7e76fccfdadc4a0783c1ad79c3eedcdd8f3
=> wsd: ssl: simplify SSL poll events

loleaflet/css/notebookbar.css
In some browsers the 3 components (icon, label and arrow)
were not being displayed properly.
- Adjust arrow element for StatisticsMenu
(fiddle with useInLineLabelsForUnoButtons and noLabelsForUnoButtons [Control.JSDialogBuilder.js] wouldn't solve it)
- Remove unnecessarily padding-left: 25% from .unotoolbutton images
- Also avoid other problems with regular arrow by setting its dimensions to 0
Change-Id: I907bfe711bbf81ac2a1071b73c322813426fc4e9
=> Notebookbar: Fix StatisticsMenu arrow on Chrome

cypress_test/package.json
I see some random test failures:
"An uncaught error was detected outside of a test:
SyntaxError: The following error originated from your test code, not from Cypress.
> Invalid or unexpected token"
There is no backtrace or code pointer or anything to find out
what is the actual problem, but it might be related the missing
import of 3rd-party code.
Change-Id: Ia2243852e825eee18c226d89fd17e92960daa129
=> cypress: try to fix random syntay error.

common/FileUtil.hpp
We shouldn't assume two files are different just
because one was touched recently. This is an issue
when we think systemplate is out of date when it isn't.
Since we only do this file comparison on (very) small
/etc files, it's simply safer to compare the files
when their sizes are the same, instead of assuming
that timestamps are indicative of being outdated.
Ironically, by comparing the contents we spawn
jails faster when there is nothing to update
and we can safely use bind-mount.
Change-Id: Idb2088fcb52b493c91bef92890750f1dfcfbcc25
=> wsd: don't trust modified time when comparing files

common/Log.hpp
Signed-off-by: 22shubh22 <22shubh22@gmail.com>
Change-Id: Ie042253d2b99237537bac450a4b3b673606a84a9
* Resolves: # 
Remove unwanted Poco::Timestamp #115
=> Remove unwanted Poco::Timestamp functions

loleaflet/admin/admintemplate.html, loleaflet/admin/src/AdminSocketBase.js
vex.css reference is removed from admintemplate.html file. main-admin.js already injects it into html.
There was a bug causing "socket closed" message to appear on every page refresh.
Change-Id: I1ae625a184bc353feb6af056f5767b92b518be16
* Resolves: # 
=> Admin: vex.css usage improvements.

loleaflet/css/jsdialogs.css
- Fix checkbox
- Chrome: fix input dimensions
- Remove unnecessary margins
- Hide frame-label in SelectSourceDialog (we don't need it, there is only one frame and we already have  a title)
- Add .ui-treeview-cell.with-sub-dialog to be used when we get that class
- fix hideitems, remove border
Change-Id: I5b07c543038163a33c66ea81672a858fca2b4059
=> JSDialog: style frame-label, fix ui-alignment, fix expanders' container..

cypress_test/plugins/index.js
When we run cypress tests in parallel (e.g. make check -j4), the
tests randomly fail with an uncaught error. The issue might be
because the same support file is shared between the different threads,
and they might access it at the same time. We try to create different
instances of the support file via preprocessing. Let's see whether it
makes the issue go away.
Issue's error message was:
"An uncaught error was detected outside of a test:
SyntaxError: The following error originated from your test code, not from Cypress.
Unexpected end of input"
Change-Id: I7b256cd686fb2b0e79ab602e95d197388a5aadca
=> cypress: try to handle support file better during parallel run.

loleaflet/src/layer/tile/CalcTileLayer.js
When eg. Statistics -> Sampling dialog was opened
we received empty split position what caused to
setup NaN for split pos and no rendering at all
Change-Id: I4bd37778d23b15a01f1850459924c66f437f1570
* Resolves: # 
=> Don't apply invalid canvas split position

loleaflet/src/control/Control.JSDialogBuilder.js
Apparently the treeview control in server side,
create a "<dummy>" entry when no children exist.
Change-Id: If2afdd8aed7f8090ed33a8b77a96447394cad7bf
=> jsdialog: avoid to insert the "<dummy>" entry

loleaflet/src/control/Control.JSDialogBuilder.js
Occurs that when showing the Macro Selector Dialog
the nodes of the treelistbox are shown on demand,
so the item is collapsed waiting user click to expand.
Change-Id: I45ea3252c9ea7f3806b22aec3063a57bf59c6d21
=> jsdialog: add class "collapsed"

loleaflet/src/control/Control.JSDialogBuilder.js
Occurs when showing the Macro Selector dialog,
the node children populate on demand when the
user click the expand element.
So client side will send the request 'expanding'
and asynchronous it receives the data to update
the dialog, another result it is not acceptable.
Change-Id: Ib176b86ab7f1b3bb5b463c825565f5d25fedf1f9
=> jsdialog: request 'expanding' to server side

loleaflet/src/control/Control.Menubar.js
- Named Ranges and Expressions were duplicated (appearing both on Sheet and Data)
- Plus avoid uno commands that wither were not tested, simply do not work or are unstable
Change-Id: I257b9a2eb9e7db0d8881c96e7f3f31dba94f020a
=> Fix regression coming from 8887abe9de14d636a9951c454d9880c5d3bfd69f

cypress_test/Makefile.am
So we can catch crashes / debug messages of core code.
Change-Id: Ib11426e7fdd8f219be4715b3f1e2983ad33d7f2b
=> cypress: record the loolwsd's command line output.

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/map/handler/Map.TouchGesture.js
...(CanvasTileLayer) for the pinch-zoom event. This uses extra canvas
elements for each freeze-pane which are not attached to the DOM
(OffScreenCanvas is not available in IE11). These canvases will always
be kept updated as the main canvas except that they also include a few
(three for now) border tiles, so that zoom-out works. The zoom animation
frames are drawn on the main canvas by drawImage() call from the
offscreen canvas at the right intermediate scaling. After the pinch zoom
event has ended (_onPinchEnd()) the map's zoom/center are updated and
offscreen canvases are cleaned up.
Caveat: The zoom animation frames will have out of sync row/col headers
and it is slow to render them frame by frame for every intermediate
zoom. It is much easier/faster to have them in sync if they are …
=> zoom-animation in the canvas

loleaflet/src/control/Control.NotebookbarImpress.js
Change-Id: Iadae860ec5bb82d84e262eaf5bc602f2ce304758
Before
After pull request
LibreOffice (Desktop)
With the PR the Impress Insert tab follow how it look on desktop (exclusive the non existing commands) and the layout is similar to how NB's are designed. Each group start with one big button and than the commands are arranged in two columns.
=> Notebookbar Insert Tab: update impress insert tab

loleaflet/src/control/Control.NotebookbarCalc.js
Change-Id: I0d829aaa2e9869de87cddc997b8758fe8d20823c
Before
After pull request
LibreOffice (Desktop)
With the PR the Calc Insert tab follow how it look on desktop (exclusive the non existing commands) and the layout is similar to how NB's are designed. Each group start with one big button and than the commands are arranged in two columns.
=> Notebookbar Insert Tab: update calc insert tab

loleaflet/css/notebookbar.css, loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I255116b6bb16e84d2b465f8fb862145924552f68
Before
After pull request
LibreOffice (Desktop)
With the PR the Writer Insert tab follow how it look on desktop (exclusive the non existing commands) and the layout is similar to how NB's are designed. Each group start with one big button and than the commands are arranged in two columns.
=> Notebookbar Insert Tab: update writer insert tab

loleaflet/src/control/Control.NotebookbarCalc.js
Change-Id: I86e4eec764dcbe3771d0d381e078bbbb57665c3f
Calc file tab: bottom align labels
I use `'type': 'bigtoolitem',` like it is know from writer instead of `'type': 'menubartoolitem',` which arrangement is the one you prefer @eszkadev ? the layout from writer or from calc.
=> NB updates

loleaflet/css/notebookbar.css
Change-Id: I08c0ca3a33f50b046b51705b0933e5623b203b48
content is now vertical-align within the tab, no need for hardcoded px numbers.
=> NB: vertical-align content

loleaflet/src/control/Control.JSDialog.js
It will update the control that has changed the model,
in the current visible dialog instead to recreate the
dialog again.
Change-Id: Ibad681df32952f380d63ccd82b01d83c488d95b4
=> jsdialog: only update the incoming control changes

loleaflet/src/layer/marker/Annotation.js
Change-Id: I9bb092a053b61f9cdd13c020b1349ae753d2289a
problem: the user could not scroll sometimes when there are too many annotations and the mouse is over an annotation. This will make things more convenient for the user.
=> leaflet: allow document scrolling when mouse is over annotations

test/Makefile.am
fatal error: test/lokassert.hpp: No such file or dire
ctory
17 | #include <test/lokassert.hpp>
Change-Id: I935cc4e0afd6862469d27b3d2620dfa83e38ef69
=> test: makefile: fix build  builddir!=srcdir

loleaflet/src/control/Control.Toolbar.js
Change-Id: Idfdfd8acfa6d738bf695a473610d399b123e7019
problem:
undoing something on mobile does not trigger any input method
this causes problem in mobile working with suggestions
i.e: type "than" and then select "thank" from suggestion
now undo and then again select "thanks" from suggestions
final output is "thans"
this happens because undo doesn't change the textArea value
and no other way to maintain the history
So better to clean the textarea so no suggestions appear
=> leaflet: avoid keyboard suggestions after undo/redo

loleaflet/src/control/Control.MobileWizardBuilder.js
Change-Id: I78403b489f8057b3131e1ccc1cbeef74377bedc4
In safari, firefox and in ios app user could enter non-numeric characters in the spin field, this patch prevents it.
=> leaflet: prevent entering non numeric value in spin field

common/FileUtil.cpp, common/Log.hpp, common/SigUtil.cpp, common/Util.cpp, kit/ForKit.cpp, kit/Kit.cpp, net/Socket.cpp, net/Socket.hpp, net/SslSocket.hpp, wsd/LOOLWSD.cpp
Most C and Posix API clobber errno. By failing to save
it immediately after invoking an API we risk simply
reporting the result of an arbitrary subsequent API call.
This changes LOG_SYS and LOG_SFL to take errno explicitly.
This is necessary because sometimes logging is not done
immediately after calling the function for which we
want to report errno. Similarly, both of these log
macros need to save errno before calling any functions.
This is necessary in case the argument is in fact errno
and not a copy.
Finally, both of these log macros append errno to the
log message, so there is little point in ending the
messages with a period.
Change-Id: Iecc656f67115fec78b65cad4e7c17a17623ecf43
=> wsd: save errno before invoking any other functions

loleaflet/src/control/Control.MobileWizardBuilder.js
Change-Id: I5f6342febcf444c71eef964da5585e5f73ae367e
problem:
creating an additional container for frames causes problem in wizard
while trying to go level up because changing level depends upon
finding the sibling of the current not and making them visible or invisible
having extra container breaks this relation
in addition not creating an additional container does not affect anything visually
=> leaflet: don't create container for frame in mobile wizard

loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Ibd9b04c1f275adb8e2fd0429e1bef3adb1916e0b
no need to add child comment into the DOM if the thread has only one comment
=> leaflet: avoid creating child comment when possible in wizard

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/map/Map.js, loleaflet/src/map/handler/Map.TouchGesture.js
* Resolves: # 
The patchset fixes lack of zoom-animation in writer/impress, reduces the view jump after zoom animation due to rounding of zoom and finally fixes oversized canvases due to double application of DPI-scale.
=> Zoom-animation and oversized canvas fixes

fuzzer/ClientSession.cpp
This went wrong in commit 693a2e19e3732a08609d1a709010e12325de1e32 (wsd:
SocketPoll::poll accepts chrono duration, 2020-12-14).
Change-Id: I04780d7a5ef8ba54530df7727f2fe4df59995fb9
=> admin fuzzer: fix build

kit/Kit.cpp
Before loading the document and if it has an embedded
macros, it will show the "Macro Security Warning"
message dialog.
If the input process is not enabled, the result will be
a virtual deadlock, so it should filter some messages at least.
Change-Id: I565569a0227ac0e7ce2feae2cf3ccdf21ce4b1d4
=> kit: enable input process when early dialog show

test/helpers.hpp
'bytes' can be smaller than the size of the buffer, so go with that size
instead.
Change-Id: I233c4281eee696fcac936b2a9502a0c28fcdf578
=> test: avoid garbage at the end of the message in getErrorCode()

Makefile.am, common/FileUtil.cpp, common/FileUtil.hpp, common/JailUtil.cpp, debian/loolwsd.postinst.in, docker/from-source/Debian, docker/from-source/Ubuntu, kit/ForKit.cpp, kit/Kit.cpp, loolwsd.spec.in, wsd/LOOLWSD.cpp
In some cases we cannot do a fast bind-mount of the files we want
in our jail since we don't have cap_sys_admin for loolmount inside
eg. docker.
Thus we need to fallback to hard-linking, however various security
systems namespace parts of our tree, such that link() fails with
EXDEV even across the (apparently) same file-system.
As such we need to assemble a copy of what we want to hard-link
close to our jails. However, this needs to be owned by root / the
system to avoid having writable files shared between jails. Hence
we need cap_chown in addition to cap_fowner, to get ownership right
and then hard-link.
Change-Id: Iba0ef46ddbc1c03f3dc7177bc1ec1755624135db
=> Optimize copy of jails to hard-linking with new capability.

loleaflet/src/layer/marker/Annotation.js
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
at NewClass.onRemove (src/layer/marker/Annotation.js:48:24)
at NewClass.removeLayer (src/layer/Layer.js:83:10)
at NewClass.onAnnotationCancel (src/layer/AnnotationManagerImpress.js:107:14)
at NewClass.fire (src/core/Events.js:152:22)
at NewClass._onCancelClick (src/layer/marker/Annotation.js:314:14)
at HTMLInputElement.handler (src/dom/DomEvent.js:51:14)
Change-Id: Ib4a9f60d6b0685b80cdf1271f506692dffe19715
=> loleaflet: fix remove child

wsd/DocumentBroker.cpp, wsd/Storage.cpp, wsd/Storage.hpp
A minor cleanup of UploadResult to make tidy
it up a little bit and make it less specific.
Single-argument constructors should be explicit
to avoid unexpected conversion and other surprises.
Change-Id: I57599805743dffddac620f501dc6ca79c2217f89
=> wsd: UploadResult cleanup

cypress_test/plugins/blacklists.js
Change-Id: I3d48a5069eb0bfad8168826b6ab79ccd7f207b32
=> cypress: NC: disable failing spellchecking tests.

wsd/LOOLWSD.cpp
The development environment is necessary analyse
the logs, so disable setting SAL_LOG instead to
add a parameter to already a long list of options
Change-Id: Id8e4a66e1dcb32c636806e47e1d69270af4c53f5
=> wsd: disable setting "SAL_LOG" in "DEBUG" mode

wsd/Storage.cpp, wsd/reference.md
While UserFriendlyName is an optional field
in the WOPI protocol, Core needs it for
the Author of the document. When it's blank
the Author is not set and the document fails
to load.
By default we are at least able to load the
document with a sensible placeholder for the
Author. Meanwhile, we log a warning to let
the integrators know of the issue.
Change-Id: I4dd2c9d164b4d889f85701a4a27ee8d395bff220
=> wsd: default UserFriendlyName if missing

loleaflet/css/jsdialogs.css
- iconview fix layout without using hard-coded margins
- fontwork: make sure the elements start at the same left position as the title and that they occupy the dialog evenly
- hide unnecessary label
- space-around when on mobile
Change-Id: Ia92acf1cbf09a3e7c6e996f9a846163835b115af
=> Fontwork: layout improvements

loleaflet/css/notebookbar.css
Change-Id: I539d70ab1ba07d27cf34b61a8bf1a333e0bc4531
Before
After
not available commands shouldn't be "highlighted"  with a gray background. The icon and string are gray (like in the menu bar) so there is no reason for additional colors.
=> Notebookbar: disable commands without gray background

common/Unit.cpp, common/Unit.hpp, net/Socket.cpp, net/Ssl.hpp, test/UnitWOPI.cpp, test/UnitWOPIDocumentConflict.cpp, test/UnitWOPIRenameFile.cpp, test/UnitWOPISaveAs.cpp, test/UnitWOPIVersionRestore.cpp, test/UnitWopiOwnertermination.cpp, test/WopiTestServer.hpp, test/test.cpp, wsd/Admin.cpp, wsd/LOOLWSD.cpp
These commits fix 4 WOPI Tests so they wouldn't rely on the timing of the SocketPoll interval, instead they now properly wait for the different events from Core before they move to the next test phase.
Better logging, comments, and overall readability is also improved. 
More info in the individual commit messages (but the review is best done over all changes together).
- wsd: test: remove redundant wakeupWorld and log the exit status
- wsd: test: move inherited filterSendMessage to onFilterSendMessage
- wsd: test: make DocumentConflict test robus and simpler
- wsd: test: make UnitWOPI test robust and simpler
- wsd: test: make owner-termination test robust and simpler
- wsd: test: make Version Restore test robust and simpler
- wsd: test: simplify sending commands
- wsd: test: shorter poll …
=> WOPITest improvements

net/Socket.cpp, wsd/Admin.cpp, wsd/DocumentBroker.cpp, wsd/LOOLWSD.cpp
- wsd: avoid reading the config entry more than once
- wsd: log when simulating socket error to help troubleshoot
- wsd: misc and cosmetics
=> Misc minor improvements

cypress_test/run_parallel.sh
Before this commit failure logs were gathered inside an error log
file and they were displayed after all tests are finsihed.
After this commit we print this failures logs when the error occurs
and also at the end of the test run. Sometimes Jenkins does not finish
the whole build because of timeout abortion. In this case, it would
be helpful to see some failure logs.
Change-Id: Ibe7cb6aa2c9f99912d604c4b642cda363352ffcd
=> cypress: print out test failure output online during parallel build.

kit/ChildSession.cpp
I don't recall if simply ifdeffing is the proper way to bypass UnitKit
stuff (that I don't understand) for the mobile apps, but at least it
helps.
Signed-off-by: Tor Lillqvist <tml@iki.fi>
Change-Id: I85d477e4ee7d11c597d95a9b0b42af7e5f7ad122
* Resolves: # 
=> Fix crash in iOS app: Don't bother with UnitKit

loleaflet/src/layer/SplitPanesContext.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js
* Fixes offset between grid-lines and headers.
* Removes 1px empty spance near headers.
* Fixes debug mode tile-border red rectangle drawing.
=> Fixes offset between grid-lines and headers and other canvas related fixes

loolkitconfig.xcu
Change-Id: Ieeb8c5f37efb6e3f262d50f4fb54bbef59c2ff06
The problem is, that the svg2png rendering in core result in bad quality. That's the reason LibreOffice use .png icons by default and the .svg icons are available ONLY for HIDPI screens.
As the sidebar was rendered by core the sidebar has to use the .png icons instead of the .svg one.
before
after
=> Sidebar should use .png icons instead of .svg fix #786

loleaflet/Makefile.am, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasSectionProps.js, loleaflet/src/layer/tile/CanvasTileLayer.js
We are drawing things from different files onto the same canvas.
CanvasSectionContainer is organising them. When they are too many, it is difficult to know about sections' important properties.
CanvasSectionProps keeps sections maintainable.
Change-Id: I9e81104c30f30a47c02625ce9d6716a98958317c
* Resolves: # 
=> CanvasSectionProps: Add an overview of sections.

kit/ChildSession.cpp
This method needs to be called with having the correct view activated.
It caused a crash in writer/simultaneous_typing multi-user cypress test.
Change-Id: I57dd58a635ce7ea127200a6a3f0cadc8c0861aaf
(cherry picked from commit 218e47e65a5e59871b9670e4bad020cf389d17fc)
=> Switch to the correct view before calling getSelectionType() method.

cypress_test/integration_tests/mobile/calc/chart_spec.js
It crashes if the mobile wizard is closed before exiting
chart editing mode.
Change-Id: I47143543220aaebf474e1d1aa560c7df2c2a14f5
=> cypress: fix up and enable chart test.

cypress_test/package.json
It fixes a hang related to retries. It might be useful
in our case too. I've seen hangs on Jenkins, which might be
related.
Change-Id: I8320f9b38c59074d2b5dd3d7b0cad0c5828b0849
=> Update cypress: 6.1.0 -> 6.2.1.

Makefile.am, net/HttpRequest.cpp, net/HttpRequest.hpp, test/HttpRequestTests.cpp, test/Makefile.am
This implements HTTP/1.1 per RFC 7230, partially.
Unit-tests are provided with documentation on usage.
This is desgined to serve as the http implementation
throughout loolwsd, for both synchronous and
asynchronous requests.
Change-Id: Iaf1b8c5fcb8cec032445e27c9f70d2fb807aa4dc
=> wsd: asynchronous HTTP/1.1 implementation

kit/ChildSession.cpp
The other code in this function carefully checks before indexing
tokes, and has already stored the integer from tokens[1] (if it
exists) into winId. Do it in one more place for consistency.
Change-Id: I2bc09b3e44e0549a94469d7569f724df17a113b3
* Resolves: # 
=> Use winId here, too

loleaflet/css/loleaflet.css, loleaflet/src/layer/tile/CanvasTileLayer.js
Canvas element's drawings will include part of UI outside of map area. Its size should be larger than tilelayer's and map's sizes.
Change-Id: I89bf79ccfe0240abdb031b937626b0bb81f3ed6f
* Resolves: # 
=> CanvasTileLayer: Canvas is moved outside of "map" div.

kit/ChildSession.cpp, kit/ChildSession.hpp, kit/Kit.cpp, kit/KitHelper.hpp, loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/TileLayer.js
The same cache size is used in server and client. The caches use the
invalidation algorithm. Pass the hash of the pixmap in the
windowpaint: message. The client stores dialog images in its cache.
The server stores hashes of the images. When the server knows that the
client already has an image cached, it sends just its hash and the
client will use the cached image.
Pass the size of the cache to the client so that we don't have to keep
the the cache size synchronised in two places in the code.
Change-Id: Ie6cbfca79a9ede48fcc115e3acc669b925bb624e
* Resolves: # 
=> Add caching of tunnelled dialog images

loleaflet/src/layer/AnnotationManager.js, loleaflet/src/layer/marker/Annotation.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/GridLayer.js, loleaflet/src/layer/tile/ImpressTileLayer.js, loleaflet/src/layer/tile/WriterTileLayer.js
it is not necessary fire 'updatemaxbounds',
because the association map <-> document layer
1:1
Change-Id: Ic41ab328f7d3d331624107a13acf9f1fdd4c46df
=> loleafet: simplify update max bounds

docker/from-source/build.sh
After compiling and installing poco the script is left in the wrong path, resulting core to be deployed underneath poco directory which breaks configure --with-lo-path later on.
=> fix build.sh: wrong directory after poco install

loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/TileLayer.js
If the client cache seems to be inconsistent with what the server
thinks, send an ERROR message to the server that will be logged.
Change-Id: Ic7f9d7fb15b2c34f7a6cd2decbacaa7745ac9389
* Resolves: # 
=> Add  sanity checks to the PNG cache code in loleaflet

test/HttpRequestTests.cpp, test/Makefile.am
These tests require network setup and therefore
can be problematic for `make run`.
Change-Id: I8747a505e15edc91964b290a5476a24069b7d538
=> wsd: test: move HttpRequestTests to 'make check'

wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
This is to disambiguate between Saving the document in Core and Uploading to Storage.
- wsd: DocumentBroker documentation
- wsd: lastStorageSaveSuccessful -> lastStorageUploadSuccessful
- wsd: saveToStorage -> uploadToStorage
- wsd: saveAsToStroage -> uploadAsToStorage
- wsd: saveToStorageInternal -> uploadToStorageInternal
=> Disambiguate between Save and Upload

net/HttpRequest.cpp
Limit its length, we know the version length anyway.
Change-Id: I0db2b9227baf3e10055082ad394c0f555b9898e1
=> net: http version string may not be null-terminated

kit/ChildSession.cpp, loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/TileLayer.js, wsd/ClientSession.cpp, wsd/protocol.txt
=> Back-port of dialog image caching work

cypress_test/integration_tests/mobile/impress/slide_properties_spec.js
In master view, the 'Master Slide' list should be empty and so it's
not shown on mobile wizard. No, I disable this test, because
it needs the core core to be updated.
Change-Id: I12562c453673ac85e050303ebb5803fee6f1892a
=> cypress: update 'Check disabled elements in master view.' test.

loleaflet/loleaflet-api.html, loleaflet/postmessage-api.html
references.html has been replaced by 2 files with content LOLeaflet
and PostMessage setions respectively.
Change-Id: Id095da5f1ab11c96d090bceab921d74b4fe68482
=> cleanup dev doc: loleaflet and postmessage references in separate files

test/HttpRequestTests.cpp
The last enumerator in Poco::Net::HTTPResponse::HTTPStatus is 511.
Change-Id: Id183916729c8d13f63fe0d6e0d7ca7e84c8afaeb
=> test: avoid http status 512 and higher when interacting with poco

cypress_test/run_parallel.sh
It's a useful option to create a video during headless run.
It's much closer to the headless build wrt. timing, than
interactive test runner.
Change-Id: Ic9889209ac07b9fe0a9b6e326e60513412950780
=> cypress: mention video recording option in failure log.

test/HttpRequestTests.cpp
These are not needed to be executed on an ongoing
basis, only when modifying the http code.
As the external service is only used to verify
the initial implementation, it will also get
replaced with an internal (loopback) one.
Disabling for now to avoid noise when randomly
failing, due to network or other reasons.
Change-Id: I54f5203c39e48ba442313698d519b035200b41e5
=> wsd: test: disable external http regression tests

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
This PR introduces a new DocumentStatus class to encapsulate the document lifecycle states
and the related members to track it.
- wsd: introduce DocumentState class
- wsd: move the closeRequested flag into DocumentStatus
- wsd: move the markToDestroy flag into DocumentStatus
- wsd: move the loaded flag into DocumentStatus
=> Document State

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
Documentation for the DocumentBroker states and design, and some misc. changes:
- wsd: remove default arguments of uploadToStorageInternal
- wsd: save -> upload
- wsd: log at info level when we force uploading
- wsd: documentation of DocumentBroker states
- wsd: correct assertion on storage and not tilecache
=> Documentation and Misc Changes

loleaflet/src/layer/marker/Marker.Drag.js, loleaflet/src/layer/marker/Marker.js
This reverts commit 284e8ce308f2e8a3ea124f93fb7f8c27fbed0910.
We have to disable panning handler to avoid panning when resizing
the selection using handles.
Change-Id: I9994b3e9ba32bc3e43567d43e547eada311c050e
* Resolves: # 
=> Revert "Don't block handling of touch events"

cypress_test/integration_tests/mobile/writer/insert_field_spec.js
There is no more span inside the HTML representation
of a text field. After this commit:
b982d0e6f94ca70765231ff4242c829f5bec5def
Change-Id: Ic64a20dcb0534876af062a1fb40cb0e39fd27f10
=> cypress: update writer field tests.

loleaflet/src/core/Socket.js
Without this, when joining an editing session of a spreadsheet, you
don't see the cell cursors of another participant until they move the
cell cursor.
Change-Id: I87b8ad584d57bce52b39706fa9f0bbf56a59082a
* Resolves: # 
=> Also save cellviewcursor: messages for handling when we are ready

common/JsonUtil.hpp
To be able to locate them in the logs more easily; this is likely to
catch mistakes early in the development of new integrations.
Change-Id: I11c528d11e4a4e1d13f8d32085fa1bf1a163b779
=> CheckFileInfo: Report mis-spelled CheckFileInfo properties as errors.

loleaflet/src/layer/tile/TileLayer.TableOverlay.js
- Currently the markers are not touchable on ipad (both via web and app) so
- Revert back listener change introduce in ebaca16c4f28ae7a499c632b70b24eaaa1083439
Change-Id: Ia2ff20ed4ddf810c50b11c49600709489f07785f
=> Make table markers clickable on desktop

loleaflet/src/control/Control.LokDialog.js, loleaflet/src/layer/tile/CanvasTileLayer.js
When column groups is used, document was badly aligned.
This commit fixes it.
Change-Id: If572735a935fae1db2a94b66711b0a9080490a37
* Resolves: # 
=> Calc: Fix document-container position.

loleaflet/src/control/Control.ColumnGroup.js, loleaflet/src/control/Control.RowGroup.js
Row and column group controls' plus & minus signs were not hairline. It is fixed.
Change-Id: I964f0e3916df91b110ba17e819c24d589c6bd3cd
* Resolves: # 
=> Calc: Minus & plus sign hairline drawings.

loleaflet/Makefile.am, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasSectionProps.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/vector/CBounds.ts, loleaflet/src/layer/vector/CLineUtil.ts, loleaflet/src/layer/vector/CPath.ts, loleaflet/src/layer/vector/CPoint.ts, loleaflet/src/layer/vector/CPolyUtil.ts, loleaflet/src/layer/vector/CPolygon.ts, loleaflet/src/layer/vector/CPolyline.ts, loleaflet/src/layer/vector/CRectangle.ts, loleaflet/src/layer/vector/CanvasOverlay.ts, loleaflet/src/map/Map.js
* Resolves: # 
This is a set of patches to help migrate SVG based overlays objects like cell-cursor, selections etc to directly draw on main canvas via canvas-sections. It migrates cell cursor to main canvas to start with. The other overlay layer objects will be migrated one by one in further pull requests.
Following typescript classes are written based on corresponding old L. js classes but without the latlng stuff:
CanvasOverlay.ts  <- L.Canvas.
CPath <- L.Path
CPolyline <- L.Polyline
CLineUtil <- L.LineUtil
CPoint <- L.Point 
CBounds <- L.Bounds
CPolygon <- L.Polygon
CPolyUtil <- L.PolyUtil
CRectangle <- L.Rectangle
=> overlays on main canvas

cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js, kit/SetupKitEnvironment.hpp
e.g. in case of CODE AppImage, that is built from packages,
/etc/loolwsd/loolkitconfig.xcu will not be good, the good
location is within the AppImage's file system.
Change-Id: Ie2bf56cd95781c193a0e7185bd96d40c4849d920
* Resolves: # 
=> sometimes it's useful, when path to loolkitconfig.xcu is configurable

loleaflet/src/layer/marker/TextInput.js
Change-Id: I084635c5d3e61215a4e88d84271587186605133d
original problem was when in read only mode document container
is not in focus and that is why keyboard shortcut events were
never triggered
This solution focuses the document for composed keys to trigger
shortcuts
=> leaflet: fixed print shortcut not working in readonly mode

scripts/unocommands.py
use original names as it is required for pulling translations
Change-Id: I0b679d0802afcfacc7db8cb56a08254749811bc1
* Resolves: # 
=> update unocommands script: don't replace characters

net/WebSocketHandler.hpp
Change-Id: Icdb67f0576992cd54c8e15c85fbaf2745aba218c
=> Fix build with libc++: std::min() parameters should be of the same type.

loleaflet/css/loleaflet.css, loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/vector/CPolyline.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
* Resolves: # 
Follow-up fixes to PR#1439 "Migrate text/cells selections overlays to main canvas"
=> Follow-up fixes to PR#1439

loleaflet/src/control/Control.LokDialog.js, loleaflet/src/layer/tile/TileLayer.js
…dering debugging
Change-Id: I631e45c2c364522eb6b9875ff35c243db0673f35
* Resolves: #914
added new option that explicitly enables and disable invalidation re-rendering in sidebar when debug mode is enabled
I was confused what should I name this option .I have gone with sidebar rerendering.
=> added a separate option in debug mode for sidebar invalidation re-rendering debugging

kit/Kit.cpp, loleaflet/js/global.js, loleaflet/src/core/Socket.js
This resolves a dependency on userName
(a.k.a. UserFriendlyName) that was a source
of issues when missing.
It turns out that when it's missing but
spellOnline is set, an edge-case caused
an exception that failed loading.
The spellOnline value, in its turn, was
incorrectly set to "null" when in fact
it was missing. This resulted in online
spell-checking being active by default.
Perhaps this was intentional, but here
we don't change this behavior at all.
Instead, we avoid sending "null" when
it's missing, and by default we always
enable online spell-checking, unless
it is explicitly set to "false".
This way, the exception is not thrown
and spellOnline doesn't have invalid
values, while preserving the current
behavior.
Change-Id: I4a09ac44ff5d6147c715afa0fb34af9650da4afd
Signed-off-by: Ashod …
=> wsd: userName is optional

kit/ChildSession.cpp, kit/ChildSession.hpp, kit/Kit.cpp, test/UnitWOPITemplate.cpp, test/WhiteBoxTests.cpp, wsd/Storage.cpp
Templates were downloaded by Core
upon loading. This works fine, as
long as there is no special network
setup in loolwsd. However, when
loolwsd has a complex network setup,
such as when using reverse proxies,
Core wouldn't know about the details
and would likely fail to download
the template.
Luckily, there is no reason to rely
on Core for downloading templates.
Instead, we download it in loolwsd,
just like any other document, and
load it in Core as normal. The
remaining post-load saving of
templates remain unchanged.
Change-Id: Ib22ada4ae469863d5e5c8baeee27f667f7cd40ff
=> wsd: download templates by wsd

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
We use download/upload in the storage
and load/save elsewhere, to avoid confusion.
This renames 'save' to 'upload' in the storage
for consistency.
Change-Id: I9ac991c2b52e2586b97c58db02110ff04bfd17d3
=> wsd: Save -> Upload in StorageManager

loleaflet/src/control/Control.ColumnGroup.js, loleaflet/src/control/Control.ColumnHeader.js, loleaflet/src/control/Control.CornerGroup.js, loleaflet/src/control/Control.CornerHeader.js, loleaflet/src/control/Control.RowGroup.js, loleaflet/src/control/Control.RowHeader.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasSectionProps.js, loleaflet/src/layer/tile/TilesSection.ts
Now, sections can be anchored to other sections's edges.
One does not need to set approximated initial positions for expandable sections any more.
Change-Id: Ic012960dedbd937c19c7442cefefdfebdaffafd3
* Resolves: # 
=> CanvasSectionContainer: Improve anchor property.

loleaflet/css/menubar.css, loleaflet/css/notebookbar.css
- Fix #1395
- This was also affecting iPad
- Overflow property doesn't apply to some table elements like table grouping and containers by default.
Change-Id: I2e12c3cb1e5e2ced16748e79063774502c670946
=> Partly revert cb27d2c ..

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.cpp, wsd/Storage.hpp
This fixes the time-tracking of the download stage and simplifies the code a little.
- wsd: actually compute the CheckFileInfo duration
- wsd: correct GetFile duration tracking
- wsd: wopiLoadDuration -> wopiDownloadDuration
=> Download time tracking

loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/TileLayer.js
Now, bound sections propagate events to the sections those are beneath
them. StopPropagation feature is also implemented.
Change-Id: I54c886fea0e254d4b97c4d06585db8ed28d40ab9
* Resolves: # 
=> CanvasSectionContainer: Event propagation.

kit/ChildSession.cpp
Otherwise this will break badly in the collaborative editing (multiple
views) case.
Change-Id: I63d391cb5a7d118c34564c4e1a4df7710b13e90e
* Resolves: # 
=> Include the view id in the tunnelled dialog image hash

loleaflet/postmessage-api.html
Change-Id: I2798b137df43cc322879012a774248fa8185cdec
=> loleaflet: Postmessage-api: Fix missing tr tag in documentation

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.cpp, wsd/Storage.hpp
This PR replaces Poco with our new http::Request and family.
- wsd: Loaded -> Downloaded
- wsd: set the result of saving and mark the response time
- wsd: storage: download with http::Request and http::Session
- wsd: storage: GetFileInfo with http::Request
=> Replace Poco with http::Request for Synchronous Requests

loleaflet/src/layer/tile/TileLayer.js
Signed-off-by: Bayram Çiçek <mail@bayramcicek.com.tr>
Change-Id: I6c49ff442b1ed11f10802a54c675eca1cbd8a1f7
* Resolves: # 
Redundant if statement removed according to https://lgtm.com/projects/g/CollaboraOnline/online/snapshot/d45121a0459e03c06ea3afb45d5cb1e38cd9f487/files/loleaflet/src/layer/tile/TileLayer.js?sort=name&dir=ASC&mode=heatmap#L780
=> removed a duplicate of if statement in TileLayer.js

wsd/DocumentBroker.cpp
```
wsd/DocumentBroker.cpp:772:57: error: constexpr variable cannot have non-literal type 'const std::chrono::system_clock::time_point' (aka 'const time_point<std::__1::chrono::system_clock>')
constexpr std::chrono::system_clock::time_point Zero;
^
/usr/include/c++/v1/chrono:1355:28: note: 'time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1, 1000000>>>' is not literal because it is not an aggregate and has no constexpr constructors other than copy or move con
class _LIBCPP_TEMPLATE_VIS time_point
^
```
Change-Id: I88c5466b8ad104178cf7fa4101f5f5265ccf5e86
=> Fix compilation with libc++

wsd/ClientSession.cpp
Normally the client session waits for a message
"status:" when the document has loaded to forward
to client side. However, when the document has macros
embedded, and a Macro Warning Security dialog popup
it will never receive the "status:" message.
So it is added "statusindicatorfinish:" to formally set that
the document has loaded.
Change-Id: Id40b853c002403577d7664c4f8206cb5a01403b6
=> wsd: set state loaded when "statusindicatorfinish:" received

kit/Kit.cpp
Otherwise the LOK_CALLBACK_STATUS_INDICATOR_FINISH
message is lost, and client side does not receive
it when Macro Security dialog popup.
Change-Id: Ife52c77078160b8cc1075eff9137de2d26b87b55
=> kit: enable send LOK_CALLBACK_STATUS_INDICATOR_FINISH

net/HttpRequest.hpp, net/NetUtil.cpp, test/HttpRequestTests.cpp, wsd/Storage.cpp
- wsd: http::StatusLine initialized as invalid
- wsd: fail when trying to connect to an invalid host
- wsd: test: http::Request with invalid host
- wsd: storage: better handling of failed http requests
- wsd: properly log time duration natively
=> Better http::Request error handling

kit/Kit.cpp
The commit in question breaks two unit-tests: wopi-template
and copy-paste. Temporarily reverting until the regressions
it introduces are resolved.
This reverts commit be68f06f70ce0acdec688abf1d201b98a367d376.
Change-Id: I1fafd73fdea57077eea05a146b7df0b013e6e8ba
=> Revert "kit: enable send LOK_CALLBACK_STATUS_INDICATOR_FINISH"

loleaflet/src/control/Control.LokDialog.js
When window is resized, sometimes header drawings aren't updated. This
patch solves that bug.
Change-Id: I1920435a49662c283e9b691bc02d32865ca401e8
* Resolves: # 
=> Calc: Fix header rendering.

loleaflet/mocha_tests/CBounds.test.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CBounds.ts, loleaflet/src/layer/vector/CPath.ts, loleaflet/src/layer/vector/CPoint.ts, loleaflet/src/layer/vector/CPolygon.ts, loleaflet/src/layer/vector/CPolyline.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
* Resolves: # 
The patchset addresses three zoom animation related issues :
1. A leak of requestAnimationFrame loop after zoom has ended.
2. Absence of overlays like cell cursor and selections etc during animation.
3. Incorrect rendering of freeze panes on pinch zooming.
This also fixes an issue of inability to pan after making an area selection.
=> Pan and zoom animation fixes

net/HttpRequest.hpp, wsd/Storage.cpp
This converts Poco to http::Request in sync mode,
thereby not changing functionality. In a follow-up,
this will be converted to async.
Change-Id: Ifbecd44ff599394799c1131470d77f803ed8cc45
=> wsd: storage: upload to storage using http::Request

net/Socket.cpp
We avoid changing the SSL wantsTo state and instead set EAGAIN in SSL just like we do for the non-SSL, because the error-handling is the same for both cases. We also have correct (and more informative) logging now.
- wsd: set errno when simulating socket errors for SSL
- wsd: socket error simulation to maintain the ssl state
=> Simulate socket errors more reliably

net/WebSocketHandler.hpp
- wsd: log when simulating socket error to help troubleshoot
- wsd: flush the WS buffered data when shutting down
=> Flush the WS frames before shutting down the socket

loleaflet/src/control/Control.CornerGroup.js, loleaflet/src/control/Control.CornerHeader.js
wholeColumnSelected and wholeRowSelected variables need to be set before the command is sent to the server.
Change-Id: I302643d5dbaeb3a6919c51eef34a2523e5f9bfa0
* Resolves: # 
=> Calc: Set variables upon selection all.

wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
Add a new state before load the document,
when Macro Security dialog popup, and avoid
to send the event load timeout.
Change-Id: I5973c5205e90e5447e5478cbab895709a68606f6
=> wsd: add interactive state

loleaflet/css/notebookbar.css
with inline-block with many styles there were
empty spaces
Change-Id: I5752b26694b630e871b26a1fd7044db58808ccfe
* Resolves: # 
=> styles preview: use flex layout

loleaflet/src/control/Control.NotebookbarBuilder.js
(Some of our tooltip() calls are conditional on
window.mode.isDesktop(), others on !window.ThisIsAMobileApp. Which is
more correct?)
Fixes https://github.com/CollaboraOnline/online/issues/1461
Change-Id: I98cd4c5f0cd05b78236c6722104cd1fe03f3e70f
* Resolves: # 
=> Avoid tooltips for the colour control in the mobile apps

loleaflet/src/control/Control.UIManager.js
Changing ui mode on mobile causes problems eg. after save as
or reloading the document.
We don't support notebookbar on mobile also
Change-Id: Iaa8d80dbdd139833c0505354be870f33b4f95413
=> Don't allow to switch ui mode on mobile

loleaflet/src/layer/marker/TextInput.js
Change-Id: I9cc00e5d50d21384155b16b60318090e4de70ac2
problem:
In the android keyboard when you try to erase in an empty area
and then enter some character,
The first character will likely travel with the cursor,
And that is caused because after entering the first character
cursor position is never updated by keyboard (I know it is strange)
so here we manually correct the position
steps to reproduce:
1. type "=sum" in formula bar or an empty odt (or even just "=s" is okay)
2. now tap on backspace for total character +1 times (in this case 5 or 3 times)
3. now type "=s" it will become "s="
but this can be reproduced with any special characters (i.e: }, + etc...)
=> leaflet: cursor: avoid first character not updating cursor position

loleaflet/css/leaflet.css, loleaflet/src/layer/marker/Cursor.ts
Use listener to detect focus change. Hide cursor by css class to not break JS code around cursor.
Change-Id: I6dd2ba0a88eff71870dc608ba6d961c9d0f7a67f
=> Don't show blinking cursor when no focus on document

loleaflet/src/control/Control.PresentationBar.js, loleaflet/src/control/Control.UIManager.js
We have these on the Top toolbar but in notebookbar case
We have only insert and duplicate options and they are
located in Insert tab. So deletion is not possible
with notebookbar. This patch re-enables presentationbar
with the correct hints of these items according to the doctype
Change-Id: I885b6353bce82232cfdfb5577f8cfbee16b219c7
* Resolves: # 
=> Draw: Display Presentationbar for Insert/Duplicate/Delete Pages

cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js, cypress_test/integration_tests/mobile/impress/searchbar_spec.js, loleaflet/src/layer/marker/TextInput.js, loleaflet/src/layer/vector/Path.Transform.js
Dragging is impossible when cursor is active so
displaying them only leads to confusion
Change-Id: Ib0586ce6ac38354b84076972e01be136f7ec66f9
* Resolves: # 
=> Hide selection handlers when cursor is active

loleaflet/src/control/Control.JSDialogBuilder.js
scrollIntoView scrolled whole page inside iframe
when selection in the fontwork dialog was changed
Change-Id: I40f59c1821d1327aaf6ce910e07587f0dcb5af31
=> jsdialog: don't scroll whole page

loleaflet/src/control/Control.DownloadProgress.js
Previously a 'click' on 'start download' - also resulted in a pair
of mouse down/up events getting sent to the map, the TileLayer, and
thus the core - resetting the object selection during the download,
and causing nasty issues in the second 'Confirm copy to clipboard'
which had a different & random selection depending what was under
that popup.
Change-Id: I7f6510494500dd36beb232e4720a66f2d9e09f27
* Resolves: # 
=> copy/paste dialogs: stop propagation to avoid confusing the document.

wsd/DocumentBroker.cpp
When loading hasn't completed yet, DocBroker can't
simply send a message to Kit that the session is
disconnected, because there would be no UI or
handlers for events if that were the only session.
Of course letting the document load, only to close
it, is also less than helpful to resource consumption.
Here, we recognize this case and simply terminate the
loading by killing the Kit process altogether to
avoid any potential hangs or resource wastage.
Change-Id: Ia72de715cc6238831c244444bb47b417b9b1e1a4
=> wsd: terminate Kit when disconnected while loading

android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, android/lib/src/main/res/values/strings.xml
Backport, so translations can be in sync between co-6-4 and master.
(cherry picked from commit d35a5f963e9e6f487997f4e8223eab49556ac14f)
Change-Id: Ic85297eb112def4a9197116177c857db910459cf
=> android: de_document -> the_document

loleaflet/css/jsdialogs.css
- Align description group with the Macro name group
as it's related to that
- Ensure paragraph is set with the right capitalization
Change-Id: I25d4a1f811225f6efd46bfa0733635fa4544281f
=> MacroSelectorDialog: Style Description

loleaflet/css/vex.css
- to avoid having the link in bold on smartphones
Change-Id: If2363f36af43ed1e19daad35c13ba395f4b55e92
=> loleaflet: Mobile: AlertDialog: Ensure normal font-weight

loleaflet/src/layer/vector/CanvasOverlay.ts
canvasRenderingContext2D.translate() and friends only seem to function
with numbers < 2^24, at least on Chrome 89.
So when the pane is being drawn where this limit is hit, lets do the
translation ourselves.
But in the case of zoom-animation more complicated transformations are
needed. Till we implement the manual matrix transformations correctly,
lets not animate overlay objects when the view area has hit this limit.
Change-Id: Ib48d6029ba1c6f1d7ade35060baf4ebe3e0a5fd3
=> avoid incorrect overlay painting due to big document coordinates

loleaflet/css/mobilewizard.css, loleaflet/src/control/Control.MobileWizard.js, loleaflet/src/control/Control.MobileWizardBuilder.js
When going back to the root level show not only headers.
Change-Id: I86d91f03b6f9aaa1ce14fb9ccbb567a62fb4fb15
=> mobilewizard: show all elements from previous level

loleaflet/src/layer/tile/TilesSection.ts
The issue is: On creating a page break on a empty writer file and
hitting backspace, the deleted page or parts of it is still rendered.
We get a 'status' message containing the document size every time it
changes. So avoid the issue do not draw tiles that are not within the
document area.
Change-Id: I88d1715e861f068326d28d2930d01e3b5355be02
* Resolves: # 
=> fixes: ghost pages/tiles in writer

wsd/LOOLWSD.cpp
The clipboard content is handled by the DocBroker,
if it it's available, otherwise, we fallback to the
cached clipboard entries.
When DocBroker has already terminated polling and
is no longer valid, we may end up using it for
the clipboard. In this case, we don't send anything
back, since there is no SocketPoll thread to
process the request or the socket data plumbing.
We avoid this by simply using the fallback (cache)
when we don't have a valid DocBroker.
Change-Id: Idf7f27b453605d173dd8e40d4a5d101f50355468
=> wsd: avoid using invalid DocBroker for clipboard

loolkitconfig.xcu
This reverts commit 3ce3108a5fbddb4e3e5cdcbd519e8044882d52fc.
Reason: We added macro config settings to loolwsd.xcu
=> Revert "config: add "Macro Security" default value"

common/Session.cpp, common/Session.hpp, kit/Kit.cpp, loolwsd.xml.in, wsd/ClientSession.cpp, wsd/LOOLWSD.hpp
"Specifies whether the macro execution is disabled in
general. This will disable Basic, Beanshell, Javascript
and Python scripts. If it is set to true, the
macro_security_level is ignored. If it isset to false,
the mentioned entry specified the level of macro security".
Change-Id: I4bc5b690268a93994d17e2b02b7b60b6398646b7
=> config: add "enable_macros_execution" item

loleaflet/src/layer/vector/CanvasOverlay.ts
* Fix overlay drawing on headers when animating zoom when view is tied to cell A1.
* Patch to avoid 2 branches of code to do coordinate translation/scaling for easier testing of overlays.
=> zoom animation fixes

loleaflet/src/layer/vector/CanvasOverlay.ts
* Fix overlay drawing on headers when animating zoom when view is tied to cell A1.
* Patch to avoid 2 branches of code to do coordinate translation/scaling for easier testing of overlays.
=> Backport of zoom animation fixes

Makefile.am, net/DelaySocket.cpp, net/DelaySocket.hpp, net/Socket.hpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp
Large and complex objects such as SocketPoll and its derivatives and users need controlled lifetime management to avoid destroying them out-of-order and especially after other statics are destroyed. One such external static is the Logging (and other) Poco instances that we can't control. A static object that logs anything at all can potentially crash if it runs after Poco is destroyed (partially or completely).
We hit such an issue on one of the CI boxes. The issue had been there, but a small change in the logging and other structures in the code resulted in consistent segfaults on said box everytime loolwsd exited. This failed the build, of course, which was enough to catch our notice.
Even though the issue was now in the limelight, it was still not reproducible elsewhere. It wasn't …
=> Avoid static objects in LOOLWSD

kit/Kit.cpp
built-in hard-link support performs extremely badly otherwise.
Change-Id: I26d5080590538cb6342d64e2e0a4023bbc84c427
=> Optimize for overlayfs by forcing an initial copy to linkable/

loleaflet/src/layer/tile/TileLayer.js
Cell cursor shouldn't jump to end when whole row or column selected.
"undo delete row" and "undo delete column"  actions shouldn't cause cell cursor to jump to the end.
Change-Id: I51f077c5b3fdd5c7a610631f1e0259775278ab53
* Resolves: # 
=> Calc: Improve "cell cursor jump"-Online part.

net/HttpRequest.cpp, net/HttpRequest.hpp, net/ServerSocket.hpp, net/Socket.cpp, net/Socket.hpp, test/HttpRequestTests.cpp, test/HttpWhiteBoxTests.cpp, test/Makefile.am, test/WhiteBoxTests.cpp, test/helpers.hpp, test/lokassert.hpp, test/test.cpp
Partial support for HTTP Server, new tests and fixes to the Client HTTP code and logging improvements.
- wsd: http: better logging and tracing
- wsd: encapsulate ServerSocket::_socketFactory
- wsd: http: factor out whitespace check
- wsd: http: normalize helper function API
- wsd: http::Request parser
- wsd: test: WhiteBoxTests include cleanup
- wsd: test: HttpRequestTests improved
- wsd: better http poll thread name
- wsd: minor logging improvement
- wsd: http: define streaming operators
- wsd: http: support setting header fields from Request
- wsd: http: StatusLine tests
- wsd: http: better logging
- wsd: http: better test assertions
- wsd: test: LOK_ASSERT messages support ostream
- test: don't use colored logging when output is redirected
=> HTTP improvements, tests, and fixes

loleaflet/src/layer/marker/TextInput.js, loleaflet/src/map/Map.js, loleaflet/src/map/handler/Map.TouchGesture.js
Fix description:
On setting the view area/zoom in map after the pinch has finished the
textarea for the text input is getting focus and the keyboard pops up.
This is prevented by temporarily disabling the textarea while setting
the view area/zoom in the map.
Change-Id: I193d36c7366c9c0a200c00b2966c5d31c4f2df2c
* Resolves: # 
=> Backport: touch: do not show onscreen keyboard post zoom

loleaflet/src/control/Control.NotebookbarCalc.js
New section has been wrongly back-ported as was being set inside of
existing group instead of a new one. This was resulting in a column with
3 elements and thus the whole notebookbar content was vertically
misaligned.
Change-Id: I21683caf5d2d47b825b4c11eabdea98e516364e4
=> Calc: Notebookbar: Download as CSV fix alignment

loleaflet/src/layer/marker/TextInput.js, loleaflet/src/map/Map.js, loleaflet/src/map/handler/Map.TouchGesture.js
Fix description:
On setting the view area/zoom in map after the pinch has finished the
textarea for the text input is getting focus and the keyboard pops up.
This is prevented by temporarily disabling the textarea while setting
the view area/zoom in the map.
Change-Id: I193d36c7366c9c0a200c00b2966c5d31c4f2df2c
* Resolves: # 
=> touch: do not show onscreen keyboard post zoom

loleaflet/src/layer/tile/CanvasTileLayer.js
Headers weren't being refreshed when:
* Keyboard is hidden on mobile.
* Setting mode to read only.
Change-Id: Iaa65c6145289f160977269a54c1b8409c411615d
* Resolves: # 
=> Calc: Refresh headers after a resize.

loleaflet/src/control/Control.JSDialogBuilder.js, loleaflet/src/control/Permission.js, loleaflet/src/layer/tile/TileLayer.js
Change-Id: I72e6c7d5077433c2eec283e9bc05493fdb8abefe
comment wizard allowed comment insertion and modification,
in readonly mode too
=> comment wizard: fixed permissions for comment insertion

loleaflet/src/control/Control.NotebookbarBuilder.js
In sequence of issue #1285:
* https://github.com/CollaboraOnline/online/issues/1285#issuecomment-764556056
* @kendy we are actually using the right variant
which is the one used also in core tabbed layout but it also has those
ellipsis
* Removing the ellipsis in the most visible case (File tab) for Print...
and Save As... shouldn't be problematic as it does not had any extra
condition and instead just slices the string under their respective
object's property
Change-Id: I04b01d8fb8b3ecb242fa684019a293cb5aaf51b8
=> Notebookbar: File tab: Remove ellipsis from Print and _saveAs

loleaflet/src/layer/tile/CalcTileLayer.js
Fix description:
Doing an undo causes core to do switch sheets if last change was in some
other sheet. But core sends status message with changed sheet number, so
ask for sheetGeometryData for this selected sheet if the sheetGeometry
we have is not for that sheet.
Change-Id: I6870bed86e0ffa234d659b8853a9ef9a33e02bc5
=> fix: undo + sheet switch breaks cursors

loleaflet/css/notebookbar.css
- Icon and label occupy a lot of horizontal space
- Dramatic in smaller laptops
- Limit width of that long label without increasing height
Change-Id: I1e78257f0c6c166372b585b2a5a47e2811f54129
=> Notebookbar: References tab: InsertMultiIndex is too long

loleaflet/src/layer/AnnotationManager.js
Change-Id: I33ad7080c3a068ad99fdd485d9abe05ac7a3beb0
other users comment activity would open comment wizard in every mobile view
=> comment wizard: fixed unintentional comment wizard opening

loleaflet/html/loleaflet.html.m4, loleaflet/src/control/Toolbar.js
We cannot use jQuery.get (a.k.a. $.get) in the mobile apps as that
uses some XMLHttpRequest thing that obviously won't work when there is
no web server involved, but loleaflet.html has been loaded from a
file: URL. Simply store the help file into a global variable and use
that instead.
A small refactoring of the showHelp function was needed to factor out
the call of vex.open into a separate function. That is called directly
from showHelp in the mobile app case. Otherwise, it is called from a
short function passed to $.get, as before.
This fixes https://github.com/CollaboraOnline/online/issues/401
Change-Id: I16dc960f26af7e6e89663c3ac0523ce5c3d41c34
* Resolves: # 
=> Handle the help file in the mobile apps

loleaflet/src/control/Control.Menubar.js, loleaflet/src/core/Socket.js
Change-Id: Idcd70f49010b074ee9987755132b7010b72a86f9
pdf cloud not be loaded at all
regression caused by ddbc4e25ffb0c40b27aa8a0 (#1737)
also fixed the main menu in mobile for pdf/drawing
=> leaflet: fixed pdf loading

loleaflet/src/control/Control.UIManager.js, loleaflet/src/control/Permission.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js
Fixes issues with incorrect position and size of the canvas on tablets.
Fixes some errors (using null reference) and initializes properly the view
in readonly mode on tablets so it shows rows and columns headers
=> canvas: fix sizing on tablets (master)

loleaflet/src/control/Ruler.js
We don't need to have both a panend event (as generated by Hammer.js)
and a mouseup event cause the _endTabstopDrag function to be called
when ending a touch drag of a tabstop, especially as for the mouseup
event the result was that the tabstop jumped oddly from where you have
dragged it.
Also other simplifications of events used in the iOS app case. Likely
even further simplifications would be possible.
This does not perhaps fix what
https://github.com/CollaboraOnline/online/issues/732 specifically
mentions, but at least for me it makes moving tabstops in the iOS app
work much more reliably.
Change-Id: I14ff5baeb775f0017368c0c53300df39ab0ab6e6
* Resolves: # 
=> Avoid duplicate events when ending tab stop drag in the iOS app

loleaflet/src/map/Clipboard.js
it was not possible to paste or copy to/from
the insert hyperlink dialog or search field.
Fixes this problem also in other browsers
Change-Id: Id4cef6681a53e451eeb1f7d9e6d3b9c26b49d66f
=> ie11: fix pasting in vex and other ui inputs

loleaflet/src/map/handler/Map.WOPI.js
This was not necessary in the end; and a bad idea in general probably,
so given that has never appeared in a release yet, let's revert it.
This reverts commit 5999a5b7cc7815f88484ff4f55e06406d1add068.
Change-Id: I5ee98ea85324f584db7de702a8d98ff9a6780027
=> Revert "Action_Paste postMessage to work around the pasting mechanism."

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/map/handler/Map.TouchGesture.js
Fix description:
The view jump is because after the zoom animation has ended, the map
center is set to the pinch center and not the last frame's center. The
patch computes the last frame's center and uses that to set the map
view's center. This only fixes the view jump and not the flicker after
the animation which is an independent issue.
Caveats:
Since we show only one discontinuous frame at the "final allowable zoom"
at the end of the zoom animation, there will be perceived view jump at
the end of the animation itself. This is apparent if the user pays
attention to the contents of the document at the corners of the view
before and after the is pinch stopped. This jump is more pronounced if
the pinch zoom factor is much different from the "final-zoom".
Note: The final zoom is determined …
=> fix: avoid view jump after pinch zoom animation

common/Clipboard.hpp, common/Common.hpp, common/UnitHTTP.hpp, common/Util.cpp, common/Util.hpp, kit/Kit.cpp, net/Buffer.hpp, net/HttpHelper.cpp, net/HttpRequest.cpp, net/HttpRequest.hpp, net/Socket.cpp, net/Socket.hpp, net/WebSocketHandler.hpp, net/clientnb.cpp, test/HttpRequestTests.cpp, test/HttpWhiteBoxTests.cpp, test/UnitWOPILoadEncoded.cpp, test/httpcrashtest.cpp, tools/Stress.cpp, wsd/Auth.hpp, wsd/FileServer.cpp, wsd/LOOLWSD.cpp, wsd/ProofKey.cpp
- wsd: http: tolerate the absence of a reason phrase
- wsd: test: better http tests
- wsd: http: parse the http header only
- wsd: http: improved whitebox http tests
- wsd: Util::toLower helper
- wsd: prevent poco from inserting line breaks in hex bytes
- wsd: http: map Status Codes to Reason Phrases
- wsd: http: log the hostname in warning
- wsd: cleanup Poco headers
- wsd: http: improve StatusLine
- wsd: test: http: improve HttpRequestTests
- wsd: http: better serialization into the socket buffer directly
- wsd: add member to Socket to flush safely
- wsd: http: use writeData to serialize http::Request
- wsd: correct User-Agent usage in http headers
- wsd: const correctness
- wsd: tolerate missing FinishedCallback in http::Response
- wsd: http: set date and server/agent as early as …
=> HTTP improvements to allow for Server-Side handling

loleaflet/src/control/Control.NotebookbarWriter.js
- Remove duplicated of "Field" (Fields dialog)
- Retain bigtoolitem
- Remove menutoolitem with label
- Fix alignment of remaining field items
- Group it in two groups
- Vertically so to use notebookbar space more efeciently
Change-Id: I40f74dbf7818d19ddead0d7e36f1f42f3ce59032
=> Notebookbar: Writer: References tab: Fields: rm duplicated & fix layout

loleaflet/src/control/Control.UIManager.js, loleaflet/src/control/Permission.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js
Fixes issues with incorrect position and size of the canvas on tablets.
Fixes some errors (using null reference) and initializes properly the view
in readonly mode on tablets so it shows rows and columns headers
=> canvas: fix sizing on tablets

loleaflet/src/map/handler/Map.Keyboard.js
Change-Id: I97ff4d95250aad326b7d48635ab425045959ca5d
in german shortcut for bold is ctrl+shift+f
bold shortcut is handled in the core
so we prevent online overwriting the search shortcut with shift
=> leaflet: prevent search shortcut with shift or alt

loleaflet/src/map/handler/Map.Keyboard.js
On Apple devices, shortcuts like Copy, Paste, etc use the Cmd key
(also known as the ⌘ key), not the Ctrl key. We shouldn't check
KeyboardEvent.ctrlKey but e.metaKey. Introduce a function _isCtrlKey
that checks the proper property depending on platform.
That Cmd-V still doesn't work for plan text put on the pasteboard by
another app needs to be fixed in core.
Change-Id: I4e8a05afaed0bde193d00a7ded52fcebf3536b5f
* Resolves: # 
=> tdf#141217: Fix several keyboard shortcut problems on iOS

loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/ScrollSection.ts
Scroll bar animation was flickering after mouse leaves its area.
Change-Id: Ie4d96d98dee806e6b02c8c8a23dd4eaccabbf7b0
* Resolves: # 
=> Scrollbar: Fix flickering.

ios/Mobile/Info.plist.in
Part of implementing https://github.com/CollaboraOnline/online/issues/1824
Change-Id: Ib1fd2626880d0bafece2a79f6bfd26616d8a61ad
* Resolves: # 
=> Allow the iOS app to open PDF files

loleaflet/css/notebookbar.css
in the sequence of the idea started in
https://github.com/CollaboraOnline/online/pull/1212
- by adding padding to unobuttons (independent of its status)
- do not really solely on margin
Change-Id: Iad3389226297b7a8504def148b5d869db936fd19
=> Notebookbar: Increase select status of unobuttons

common/RenderTiles.hpp
It caused a crash when opening some PDF files, for instance.
Change-Id: I85515e2e14ffac8928714d218cd2353df228ff4b
* Resolves: # 
=> Remove incorrect assertion in iOS-only code

loleaflet/src/control/Control.UIManager.js
Canvas element wasn't sync with map element.
Change-Id: I7771f662fb9a244b2acb1d450413343f4c450b1f
* Resolves: # 
=> Notebookbar: Sync tile container size after collapsing / expanding tabs.

loleaflet/src/layer/marker/Cursor.ts
use window instead of document.
now it works also in chrome.
Change-Id: Id58b8810fb6a8d5ba00369308cce1dd201b7340a
=> Blinking cursor only when window is focused

fuzzer/Admin.cpp, fuzzer/ClientSession.cpp
fuzzers build was failing with:
In file included from fuzzer/Admin.cpp:3:
In file included from ./wsd/Admin.hpp:12:
In file included from ./wsd/AdminModel.hpp:20:
In file included from ./net/WebSocketHandler.hpp:18:
./net/HttpRequest.hpp:667:31: error: expected ')'
_header.add("Server", HTTP_SERVER_STRING);
^
./common/Common.hpp:62:51: note: expanded from macro 'HTTP_SERVER_STRING'
#define HTTP_SERVER_STRING "LOOLWSD HTTP Server " LOOLWSD_VERSION
^
./net/HttpRequest.hpp:667:20: note: to match this '('
_header.add("Server", HTTP_SERVER_STRING);
^
Change-Id: Ibc3905e3e62e0eb9788b750971916ff4a4937f12
=> HttpRequest: add missing config.h include

loolwsd.xml.in, wsd/LOOLWSD.cpp
The defined envar is used by Core to override its
default resolution (of 96 dpi), when specified.
Change-Id: Ie7164e78f98990ac88b02dbfe2becbae8c134e9c
=> wsd: support configurable PDF rendering resolution

loleaflet/src/layer/tile/CanvasSectionContainer.ts
Avoid pure white and instead use another color for canvas background
Change-Id: I4cc9dffd19932bc631f5b880e53f8d413357d662
=> Fix background color in which document page is placed

loleaflet/js/global.js
The UTF-8 decoder here was buggy, and additionally it tried to feed
the Unicode codepoints it had constructed directly to
String.fromCharCode() even if that function takes UTF-16 units, not
Unicode codepoints.
The function in question is used only on IE11, apparently, so
presumably the problems had not been noticed.
Change-Id: I78f8ecea6ce6349e4121066774ae5c3fcfa87363
* Resolves: # 
=> Fix UTF-8 decoding and fix handling of non-BMP codepoints for IE11

common/MessageQueue.hpp, common/Util.hpp, net/NetUtil.cpp, net/NetUtil.hpp, net/Socket.cpp, net/Ssl.hpp, net/WebSocketHandler.hpp, test/TileCacheTests.cpp, test/UnitEachView.cpp, test/UnitLoadTorture.cpp, test/UnitTyping.cpp, test/WhiteBoxTests.cpp, test/helpers.hpp, test/lokassert.hpp, test/run_unit.sh.in, test/test.cpp, tools/WebSocketDump.cpp, wsd/Admin.cpp, wsd/LOOLWSD.cpp, wsd/RequestDetails.cpp, wsd/SenderQueue.hpp
- wsd: test: make test assertion failures more obvious
- wsd: test: log connection security
- wsd: dump blank in hex dump for out of data
- wsd: case-insensitive string equality utility added
- killpoco: replace Poco::icompare
- wsd: more informative SSL state reporting
- test: make run_unit.sh more helpful on failure
- wsd: include cleanup
- wsd: add utility to parse URIs into primary components
- wsd: test: use chrono for readable and safe time durations
=> Test improvements, cleanups, killpoco, etc.

net/HttpRequest.hpp, net/NetUtil.cpp, net/NetUtil.hpp, net/Socket.cpp, net/Socket.hpp, test/HttpRequestTests.cpp, wsd/LOOLWSD.cpp
A number of improvements to support server-side HTTP handling.
- wsd: http: comments and documentation
- wsd: http: get header entry with optional default
- wsd: http: Response writes out the body
- wsd: http: support sending http::Response directly to the socket
- wsd: http: support creating http::Session from URIs
- wsd: http: Response supports header getter and no Finished callback
- wsd: better support for erasing from the socket in-buffer
- wsd: log socket data only in debug builds
- wsd: trace socket data
- wsd: add utility to connect to socket given a uri
- wsd: test: http: name increase test timeout
- wsd: http: don't process timeout if the request is done
- wsd: exclude all of the kit config logic from mobileapp
=> HTTP fixes, improvements, documentation, logging, and tests

loleaflet/src/layer/tile/CalcTileLayer.js
RowColSelCount is used for 2 different states.
Change-Id: Ia5f68ca15881102a42016e80ea0b947c0e4d9106
* Resolves: # 
=> Calc: Fix error when filter is active.

loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CanvasOverlay.ts, loleaflet/src/map/handler/Map.TouchGesture.js
Client side grids and zoom animation improvements.
1. Prepare calc online grid/tile rendering for transparent tiles (without background and grids). Merged cell border clearing will be done by core. The feature of client side grid rendering is not yet enabled, it needs a core patch before that.
2. Zoom animation improvements: Avoid flicker, avoid swipe-pinch zoom overlap, fixes thicker overlay line width on zoom out.
=> Client side grids and zoom animation improvements

loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CanvasOverlay.ts, loleaflet/src/map/handler/Map.TouchGesture.js
Client side grids and zoom animation improvements.
1. Prepare calc online grid/tile rendering for transparent tiles (without background and grids). Merged cell border clearing will be done by core. The feature of client side grid rendering is not yet enabled, it needs a core patch before that.
2. Zoom animation improvements: Avoid flicker, avoid swipe-pinch zoom overlap, fixes thicker overlay line width on zoom out.
=> Client side grids and zoom animation improvements PR for master

test/helpers.hpp
./test/helpers.hpp:211:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
Perhaps it could go further and even call LOK_ASSERT_FAIL().
Change-Id: I4f68f6d290bcb0a832ea71153d5f699d5366def9
=> test helpers: fix -Werror,-Wreturn-type

loleaflet/src/layer/tile/CalcTileLayer.js
Change-Id: I866edb95f55d8b16a6ce3ba4e0cb4bbaa79e182d
* Resolves: # 
* Apply filters to columns.
* Add some value under filters.
* From a filter, select "show empty".
* If there is no empty rows, all rows will be hidden.
* In this case, if user has created a split-pane between the hidden rows, when user selects "show non empty" option, panes are mis-positioned.
=> Calc: Filter with split panes improvement.

ios/Mobile/AppDelegate.mm, ios/Mobile/Resources/Settings.bundle/Root.plist.in, ios/ios.h, ios/ios.mm, wsd/Storage.cpp
Used for comments added to documents by the user.
There is no trivial way on iOS for an app to programmatically find out
the name of the user, and that is good from a privacy point of view.
Fixes https://github.com/CollaboraOnline/online/issues/1843
Change-Id: Ie68fcbacf886ec8f1c74021a71879b38d4180c15
* Resolves: # 
=> Add an iOS setting for the user's name or nickname

net/HttpRequest.cpp, net/HttpRequest.hpp, net/NetUtil.cpp, net/NetUtil.hpp, net/Socket.hpp, test/HttpRequestTests.cpp, test/Makefile.am, test/UnitCopyPaste.cpp, test/UnitHTTP.cpp, test/UnitHosting.cpp, test/WhiteBoxTests.cpp, test/integration-http-server.cpp, test/lokassert.hpp, wsd/LOOLWSD.cpp, wsd/Storage.cpp
- wsd: test new unit-httplib test for http tests
- wsd: test: log before asserting
- wsd: test: better loggin in UnitCopyPaste
- wsd: http: use std::move where sensible
- wsd: http: parse the host and validate
- wsd: http: use parseUri
- wsd: test: http: more parseUri tests
- killpoco: use http::Request in UnitHosting
- wsd: http: use std::move
- wsd: http: default Session timeout is now public
- wsd: http: simplify syncRequest to return Response
- wsd: http: improved parseUri and new parseUrl with tests
- wsd: http: new syncRequest with timeout and new helper
- killpoco: use http::Request in HTTPServerTest
- wsd: http: set the port in the Host header entry
- wsd: http: support http Connection: close header
- wsd: log the inBuffer size not the outBuffer
- wsd: set http 'Connection: close' …
=> Better HTTP + Better Tests - Poco

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
where we set "zoomChanged". So we should have another state variable
waitForTiles to wait for tiles instead of re-using zoomChanged.
Change-Id: I3bd71fb97694a56be5f49a9e7b7ac7b9c49caa88
* Resolves: # 
=> fix: tiles not rendered on calls from setZoom()

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
where we set "zoomChanged". So we should have another state variable
waitForTiles to wait for tiles instead of re-using zoomChanged.
Conflicts:
loleaflet/src/layer/tile/CanvasTileLayer.js
Change-Id: I3bd71fb97694a56be5f49a9e7b7ac7b9c49caa88
(cherry picked from commit c9d6d9f569fcee3516a55d3f3a8719b7338687a4)
=> fix: tiles not rendered on calls from setZoom() (master)

loleaflet/src/layer/tile/CalcTileLayer.js
This patch fix the following Calc issue:
- type '='
- swicth to another Calc tab
- click on a cell in order to enter a cell ref
- press enter
expected result:
1 - swicth back to the previos Calc tab
2 - the cell ref has been entered correctly
3 - cell cursor is placed just below the modified cell
4 - no selection overlay
actual result:
1, 2, 3 are fine
4 - an odd rectangle overlay is visible inside the modified cell
Change-Id: I932b604db8c337eb46d50259b6b8ec1c21d179eb
=> lok: sc: wrong selection rectangle shown on hit enter

kit/ChildSession.cpp
Change-Id: I489648bb5ccd7223746fea42050088e078046a1a
send status after performing any comment operation,
updating status send page dimensions,
which help in canvas layer to resize actual page size
without updating page size comments may go out of view
and will also not be scrollable into view
resolves: #1830
=> loolwsd: after comment operation update status

loleaflet/src/layer/marker/TextInput.js
Change-Id: I6adda739dc26fb93857bf8dcf70348b07f8eab33
This is absolutely necessary for impress,
if cursor visible state is not changed,
we do not add or remove the cursor,
which handles the mouse cursor
so we explicitly set mouse cursor
i.e: in impress try to edit in one text box,
now click on the text on another text box
the mouse cursor will be incorrectly set
=> leaflet: set mouse cursor on cursor show

Makefile.am, common/FileUtil.cpp, loleaflet/Makefile.am, net/HttpRequest.hpp, net/Socket.cpp, net/Socket.hpp, net/WebSocketHandler.hpp, net/WebSocketSession.hpp, test/HttpRequestTests.cpp, test/Makefile.am, test/UnitHTTP.cpp, test/UnitLoad.cpp, test/UnitLoadTorture.cpp, test/helpers.hpp, tools/WebSocketDump.cpp, wsd/Admin.cpp, wsd/FileServer.cpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp
- leaflet: make: cleanup timestamp files
- wsd: create the temp directory root recursively
- wsd: test: unit-http is part of group0
- wsd: use http::Response for LOOLWSD 401 and 404 errors
- wsd: use http::Response for LOOLWSD 400 errors
- wsd: use http::Response in LOOLWSD file serving
- wsd: use http::Response in WebSocketHandler 101 responses
- wsd: use http::Response in LOOLWSD
- wsd: use setbody in LOOLWSD and avoid manual plumbing
- wsd: WebSocketHandler accepts http::Request in addition to Poco
- wsd: WebSocketHandler fully supports http::Request
- wsd: test: new WebSocket load Test using http::Request
- wsd: restrict WebSocketHandler members
- wsd: http: handle client-side WebSocket upgrade
- wsd: new WebSocketSession to createa a WebSocket connection
- wsd: test: new …
=> WebSocket and Tests

net/Socket.hpp, net/WebSocketHandler.hpp, net/WebSocketSession.hpp, test/UnitLoad.cpp, test/helpers.hpp, test/httpwstest.cpp
- wsd: always include port in the Host header
- wsd: use Socket::eraseFirstInputBytes for a cleaner interface
- wsd: std::move better than copy-from-ref
- wsd: test: fixup helpers
- wsd: test: WebSocketSession helper
- wsd: improved WebSocketSession
- wsd: support asyncronous shutdown of WebSocketSession
- wsd: trap disconnection in WebSocketSession
- wsd: test: improved UnitLoad test
- wsd: test: killpoco in httpwstest
=> WebSocketSession in Tests and Replace Poco (partially)

loleaflet/src/layer/tile/TileLayer.js
For calc, gridoffset must be taken into account
when calculating the center point of the shape
otherwise the coordinates will not match with
core
Change-Id: Ie1003d52f233a79e5b1640c2cf7a095a7315a749
* Resolves: # 
=> Fix Rotation moves the center away on calc

loleaflet/css/loleaflet.css, loleaflet/css/partsPreviewControl.css, loleaflet/css/toolbar.css
- Make sure width doesn't get above the available space
- Do not force scrollbar when there is no content to scroll
- use visible (default): implicitly compute to auto
Change-Id: Ib7b6b15dcf093d6172a35346679a7985584f4ef9
=> Impress: Fix #presentation-toolbar on chrome

loleaflet/css/mobilewizard.css, loleaflet/src/control/Control.JSDialogBuilder.js, loleaflet/src/control/Control.MobileTopBar.js, loleaflet/src/control/Permission.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/ImpressTileLayer.js
Change-Id: Ie80f9a808d0234f6c58b768fa27673c9fe50b122
in addition, allow users to work with comments in read only mode
wizard z index increased to avoid mobile-edit-button overlapping it
=> leaflet: enable comments for PDF in mobile

net/WebSocketHandler.hpp, net/WebSocketSession.hpp, test/TileCacheTests.cpp, test/UnitCopyPaste.cpp, test/helpers.hpp, test/httpcrashtest.cpp, test/httpwstest.cpp
- wsd: override getPollEvents in WebSocketSession
- wsd: test: killpoco in httpwstest
- wsd: test: killpoco in crashtest
- wsd: test: killpoco in tile cache test
- wsd: log the buffer size in WebSocketHandler::sendFrame
- wsd: test: dump clipboard state in test to the log
=> Kill Poco in Tests

loleaflet/css/loleaflet.css, loleaflet/images/table-row-or-column-select-marker-selected.svg, loleaflet/src/layer/tile/TileLayer.TableOverlay.js
- Do not use big rectangles as markers
- it hides surrounding content
- too intrusive (since it appears every time we select a table)
- Use smaller discreeter elements WHILE maintaining the existing
active zone size (so it's still easy to click it, no need to be precise)
- Add missing hover status
- Create new SVG plus add rounded corners
- Treat column and row marker as different elements
- Use one generic class + add another for each type (element modifier)
- So we can target each one and have a nice center line
no matter the disposition (vertical, horizontal)
note: motivated by the reported issue:
https://github.com/CollaboraOnline/online/issues/1297
Change-Id: I4d997864e99582f74411a12c33381a926fd47a05
=> Writer: Improve table controls (markers)

loleaflet/src/control/Control.Menubar.js
Change-Id: I282aeaa171081b60633720b4619e0b0f250b501a
=> leaflet: Removed impress download options from drawing doc

loleaflet/src/control/Control.Toolbar.js
This fixes hyperlink button enabling issue when dynamically changing UI mode to classic.
Change-Id: Ib4494e71c8cedf0818c946abea75e52e1b5ca7ad
* Resolves: # 
=> loleaflet: translate hyperlink toolbar button uno command to id

kit/Kit.cpp
Unfortunately the sequence message sent
from LO core is important, and the status
indicator finish should arrive to client side
before any dialog interactivity (i.e. Macros Warning Dialog).
However the LO core sends like 3 times status
finish for now we cannot duplicate them.
Change-Id: Ieee2ee93555b50b0e67507aae36096e10728a038
=> kit: fix status indicator finish

wsd/LOOLWSD.cpp
Even if we use http:// locally via a tunnel the new outgoing socket
code needs SSL initialized to connect securely to remote servers.
Change-Id: If64a3838267182757591a8026097bf08d9ba732f
* Resolves: # 
=> Initialize SSL un-conditionally.

wsd/DocumentBroker.cpp
Change-Id: I174a86f48e6b4107d0f846fd9af28a7ab1f62afc
=> wsd: revisit log messages DocumentBroker.cpp

configure.ac, kit/Kit.cpp, loolwsd.xml.in, wsd/DocumentBroker.cpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp
It is (for now) produced (by the ProfileZone things in core) whenever
logging level is "trace". The Event Trace file pathname can be given
in the loolesd.xml file or on the loolwsd command line.
Change-Id: I6d5829121e71460a4600ee94d2ebf51043c8893f
* Resolves: # 
=> Produce a Chrome Event Trace file

common/Util.hpp, test/WhiteBoxTests.cpp
Behave more similarly to before 65c245eab0.
Change-Id: I0156310257caf7c578fb273393566a0970b3bb1f
* Resolves: # 
=> Avoid ERANGE poisoning numerical conversions.

test/helpers.hpp
ProductVersion used to be e.g. "6.4", but co-2021 sets it to just
"2021".
Change-Id: I08c1204c42bba21c8036975138e3d999b7357bdf
=> test: tolerate missing minor core version

loleaflet/src/layer/marker/Annotation.js
Change-Id: I814c57069781a7fa39651c2beb4826775c0df177
problem: when document was loaded comments were not highlighted
=> annotation: fixed annotation highlight on document load

loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I9029e1d9d6e951b77e195e8e0543e7e96d627efe
* Resolves: #1018
All color pickers has a dropdown element at NB implementations
=> FIX #1018 add dropdown arrow to color picker

loleaflet/css/mobilewizard.css
Change-Id: I0e903990cb83bfe5e4194f760ae294c6c9083fc7
* Resolves: # 1611
before
after
The change was done in mobilewizard.css file, I don't know what I break with remove the #Color stuff in mobile. So review is needed.
=> fix #1611 remove gray background of uno:color command in NB

loleaflet/src/control/Control.JSDialogBuilder.js, loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I9d9d70c292772b349687d14fc3b92cd3fd5d86b7
* Resolves: #1284 
No ... any more at the Notebookbar labels
As there is already an _cleanText function to remove the ~ I added the '...' for replacement and add _cleanText to the NB labels.
If NB use the wrong strings from core this PR isn't wrong anyway cause it's remove the elipsis elements in addition to ~ when the string from core don't has ... it's also well.
=> fix #1285 remove elipsis ... from NB strings

loleaflet/src/layer/AnnotationManager.js
Change-Id: Ie9422cb5c868eac52239a3a0998246e9b98972cb
problem:
when the text where comment was inserted is modified
it would invoke comment wizard
i.e: try to insert image between comment text
=> annotation: avoid comment wizard opening on text modify

test/httpcrashtest.cpp
Change-Id: Ibb9f7d7681d502d06de92c2f5d8305c3f27a76c0
=> unit-crash: avoid socket deletion before _socketPoll completes the async shutdown

Makefile.am, fuzzer/HttpHeader.cpp, fuzzer/httpheader-data/load
Run the actual fuzzer like this:
./httpheader_fuzzer -max_len=16384 fuzzer/httpheader-data/
Change-Id: I91afe44a632826cc15bd1c338bcc5234582e9674
=> Add an initial libfuzzer based fuzzer for http::Header::parse()

loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I0b38c1a92c008a6e6356ac81db29d6439ffb7fef
Make the SaveAs export labels similar between the different apps.
=> NB File Tabs SaveAs Label similar between apps

loleaflet/css/notebookbar.css, loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I2fe501fcf512f7712022177806b45eb48bc4e204
* Resolves: # 
Update writer notebookbar home tab
1. Paragraph section is now one single group (more simple)
2. Preview of 4 styles. Online it's not so importend how width an widget is cause the widget wasn't hidden. Next group is something like an "shortcut" for insert. In addition show more previews, will be easier to select, recognize, and there are Default Style, Text Style, Title, Subtitle (4 items) than Heading 1, Heading 2, Heading 3, Quoations
=> Writer Notebookbar Home Tab update

.clang-format
Improve readability by not suggesting changes like:
-                    if (JsonUtil::findJSONValue(object, "Url", url) &&
-                        JsonUtil::findJSONValue(object, "Name", filename))
+                    if (JsonUtil::findJSONValue(object, "Url", url)
+                        && JsonUtil::findJSONValue(object, "Name", filename))
Note that clang-format is never enforced (we never re-format existing
code), but your editor may respect it for new code.
Change-Id: Id6679220f83b77a4c63ca9a9429052535c75939a
=> clang-format: turn off BreakBeforeBinaryOperators

loleaflet/src/unocommands.js
- improve labeling: Basic Shapes command open all shapes not just basic shapes
- shorter strings are more space efficient
bug: #2111
=> Rename BasicShapes string #2111

loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
Update the structure of the Insert Notebookbar Tab for all apps.
1. section: app specific
2. section: Image/Table/Chartbigtoolitem will be the most used item depending on the app
3+4. section: Hyperlink and Field values
5. section: Textbox Shapes + *new* inkl. Fontwork and Line
6. section: Headers Symbol and Comment
- Fontwork move to Textbox/Shape section
- Line move to Textbox/Shape Section
- Formating Mark + Symbol + Comment are a new Section (Formating Mark is bigtoolitem hardcoded)
- Fontwork move to Textbox/Shape section same with Line
- Header and Footer + Symbol and Comment are is a new section
- Fontwork move to Textbox/Shape section same with Line
- Header and Footer + Symbol and Comment are is a new section
* Related to: #2007
=> Notebookbar Insert Tab update #2007

loleaflet/src/control/Control.NotebookbarWriter.js
Update the structure of the Writer Layout Notebookbar Tab
Use the JSON Layout from #2007
- Page Dialog is the most importend command, so it's the first one (before last one). In LibreOffice it's the last command, cause there are dropdown menues for aspect/ratio, size, ... which are not available for cool. So have the dialogue is ok but as bigtoolitem
- Title Page and Watermark switch to bigtoolitem, cause there are not that much commands in the Layout tab
- Wrap, Object Align and Forward/Back Object use the layout from the context Draw tab so it's everywhere the same layout.
=> Notebookbar Writer Layout Tab update #2007

loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
Update the structure of the Insert Notebookbar Tab for all apps.
1. as there are not that much commands and it's very difficult to arrange them into 3 item groups, all commans are bigtoolitems
- writer use the most format commands
- start with tiny and get bigger
- character, paragrapn, page, line / area / position
- as Lists and Bullets and Numbering are related to Paragraph they are next to Paragraph
- As Columns and Sections are related to pages or part of a page, the commands are related to Page Style
- Character, Format
- Paragraph
- Page
- Cell and Conditionals (calc related only)
- Line / Area / Position
- Character
- Paragraph with Bullets
- Page
- Line / Area / Position
=> Notebookbar Format Tab update #2007

loleaflet/css/notebookbar.css, loleaflet/images/lc_goalseekdialog.svg, loleaflet/src/control/Control.NotebookbarCalc.js
Update the structure of the Insert Notebookbar Tab for all apps.
1. as there are not that much commands and it's very difficult to arrange them into 3 item groups, all commans are bigtoolitems
Define and Manage commands moved from Data Sheet to Insert Sheet, section Hyperlink
- Now the group is similar to LibreOffice Insert Tab
*Before*
*After*
Group/UnGroup Hide/Show Details moved to Data Tab
- Now the group is similar to LibreOffice Data Tab
- Commands are at the Menubar also in Data Section
*Before*
*After*
- Pivot Table + Refresh/Delete Section was removed cause it's already in Insert Tab and Data Tab has a lot of content, so no need for duplicated content at the very left area
- Sort section has the same layout than all other sections
- Autofilter section layout is similar to all …
=> Notebookbar Calc Sheet and Data Tab update #2007

loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
- Property get the first item
- ParaRightToLeft was removed, already in Home Tab
- Rearranged of NumberFormatDecimal items
Change-Id: I78969e46ba94f300d26ab2f6413657a65b537832
*Before*
*After*
*Before*
*After*
=> Notebookbar Writer/Impress Table Contextual Tab update

loleaflet/src/control/Control.NotebookbarCalc.js
In writer and impress there is File / Home / ... Review / Format / Help
In calc there is  File / Home / ... Format / Review / Help
As there is no reason why there should be a difference in calc compare to writer and impress, this patch change the arrangement of the Review and Format Tab.
=> Notebookbar Calc sync tab arrangement wit writer/impress

loleaflet/src/control/Control.NotebookbarDraw.js, loleaflet/src/control/Control.NotebookbarImpress.js
Change-Id: Ifccb641a45d985d46c8938d5e0c495ce9a396d2b
Update the structure of the Home Notebookbar Tab for Impress and Draw.
- draw didn't has options for edit text in the notebookbar (LibreOffice has a text context tab)
- impress has the text editing stuff in the home tab
Solution use the same layout in impress and draw with text editing stuff at the home tab.
- past / cut / copy like writer and calc
- text editing stuff
- add shadow and fontwork stuff instead of SubScript /SuperScript (which mean same number of commands in all text editing sections, easier alignment when set character spacing was added)
- align section
- bullet and paragraph stuff
- TextBox, Shapes, ... drawing section
- Most imported insert tab stuff 
- Start Presentation …
=> Notebookbar impress - draw home tab update #2007

loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I0a4ac6ce73856d7f322e9cbf8fa52b7ad4aa81f4
* Resolves: # #2007 
Remove an subgroup at the grow/shrink text setting in writer and calc. The structure of the json file will so follow #2007
=> Notebookbar writer calc remove grow-shrink subgroup #2007

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
* Resolves: # 
Autofill/reference selection fix, flicker with freezepane fix and other canvas related fixes.
=> autofill/reference selection fix, flicker with freezepane fix and others (to co-6-4)

loleaflet/src/control/Control.UIManager.js
When notebookbar is activated but user is in readonly mode
show the simple menubar with download and view options
instead of empty bar on the top
Change-Id: I49ac7f8d7d8691761a15fd767f278e23ea228b50
=> Show menu with download options in readonly on tablets

common/Util.cpp, common/Util.hpp, net/HttpRequest.cpp, test/WhiteBoxTests.cpp
std::atoi() assumes a null-terminated string and our strings are not
always null-terminated. So add a version that takes a length parameter,
this way we don't have to copy strings around.
Also switch to this in http::StatusLine::parse().
Change-Id: I449b356c1b9948c562434618596e8e3b38656088
=> Add version of std::atoi() that needs no extra allocation

loleaflet/images/lc_basicshapes.svg, loleaflet/images/lc_line.svg
Change-Id: I327dc32c22ee156a967fea3c6012d6bd0b677482
line icon is now a horizontal line, cause when click on line icon an horizontal line was drawn.
shape icon is now pixel align and use highlight color (blue), cause by default the shapes are blue.
=> Fix insert line and shape icon #2152

loleaflet/src/layer/tile/ImpressTileLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/map/Map.js
The activate() function assumes that the document
is loaded when the socket is connected.
This is not true until a status message arrives,
then a document layer is created.
If the document has an interactive dialog (i.e. Macro Warning)
the document formally is not loaded and it should not send
messages that will receive "nodocloaded error".
Change-Id: I01ceb156376712234ab4c12226d080446aa9279d
=> loleaflet: fix activate messages

loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I5018bfcf5925ce5026a3d4069cb4bb096921742c
Update the structure of the Draw Notebookbar Tabs for Writer, Calc, Impress and Draw.
- Position and Size is the first item
- Flip Horizontal/Vertical as Subsection
- (Line and) Area property dialog isn't available, but should be than there
- Line and Area Color Control
- Wrap
- Align
- Arrange
- Group
- Textbox, Shapes, ... as known from Insert (for faster drawing only, no switch between Insert and Draw tab)
**Before**
**After**
- See writer Draw Tab (could be synched between writer and calc
- Before there was no Draw Tab, now it's available
**After**
- Layout like in writer and calc
- Line was replaced with Connectors
**Before**
**After**
=> Notebookbar Draw Tab update #2007

loleaflet/css/notebookbar.css
Had too many different border styles (parent with dashed border,
different colors used in different places, and not making use of
css vars)
- Less decorative css styles
- Decrease distinction between Styles preview and whole notebookbar
(more at home with the surroundings)
- Use shadows to differentiate states
- add vendor prefix
- add border-collapse: separate; for ie
Change-Id: I77188f414b7d539f8ea6631016b5def8dcf90034
=> Notebookbar: Styles preview: Fix inconsistency, less borders

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
* Resolves: # 
Autofill/reference selection fix, flicker with freezepane fix and other canvas related fixes.
=> autofill/reference selection fix, flicker with freezepane fix and others

loleaflet/css/toolbar.css
it seems close button is bigger than it's parent
- Avoid that
- Remove paddings
- Use background position instead
Change-Id: I9ff86be375be78fc27dddaf5a8d38d4c41590be9
=> Notebookbar: closebutton: Fix size

cypress_test/integration_tests/common/desktop_helper.js, cypress_test/integration_tests/common/mobile_helper.js, cypress_test/integration_tests/desktop/impress/image_operation_spec.js, cypress_test/integration_tests/desktop/writer/image_operation_spec.js, cypress_test/integration_tests/mobile/impress/image_operation_spec.js, cypress_test/integration_tests/mobile/writer/image_operation_spec.js, loleaflet/src/control/Control.ContextMenu.js
Change-Id: Ic552217d03d77f93f5c38107d622d8404c122cd7
added delete option in context menu when rightclicking on graphic
=> cypress: added image operation tests for impress and writer

common/Clipboard.hpp, common/Unit.cpp, common/Unit.hpp, net/Socket.hpp, net/WebSocketSession.hpp, test/HttpRequestTests.cpp, test/HttpTestServer.hpp, test/Makefile.am, test/TileCacheTests.cpp, test/UnitClient.cpp, test/UnitCopyPaste.cpp, test/UnitCursor.cpp, test/UnitLoad.cpp, test/UnitLoadTorture.cpp, test/helpers.hpp, test/httpcrashtest.cpp, test/httpwstest.cpp, test/test.cpp, wsd/Admin.cpp, wsd/DocumentBroker.cpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp
- wsd: test: killpoco web-sockets in httpwstest
- wsd: test: killpoco in UnitCopyPaste
- wsd: safer asyncShutdown in WebSocketSession
- wsd: read can return 0 from the socket
- wsd: log the reason for terminating DocumentBroker
- wsd: test: set the test name for old-style tests
- wsd: test: log the testname in the test setup and result
- wsd: test: remove superfluous object
- wsd: test: single UnitBase ctor with default name
- wsd: test: start the test poll thread only during the test
- wsd: test: move SocketPoll to UnitBase
- wsd: test: killpoco in TileCacheTests again
- wsd: test: killpoco in TileCacheTests
- wsd: test: fully enable loopback testing of http
- wsd: better and consistent logging of ShutdownRequestFlag setting
- wsd: test: log the actual test name instead of function names …
=> Async WebSockets in Tests and Kill Poco

common/Protocol.hpp, common/StringVector.cpp, common/StringVector.hpp, test/WhiteBoxTests.cpp, wsd/TileDesc.hpp
And use it in TileDesc::parse(), which is known to be a hot path.
Change-Id: I20375d7a1c31f61662446979e4d6799fd45b49d3
=> StringVector: add a way to get a number out of this without copying the token

common/Session.hpp, net/HttpRequest.hpp, net/Socket.cpp, net/Socket.hpp, net/WebSocketHandler.hpp, net/WebSocketSession.hpp, test/HttpTestServer.hpp, tools/WebSocketDump.cpp, wsd/Admin.cpp, wsd/ClientSession.cpp, wsd/ClientSession.hpp, wsd/LOOLWSD.cpp, wsd/ProxyProtocol.cpp, wsd/ProxyProtocol.hpp, wsd/TestStubs.cpp
Since it's most efficent to send full blocks at
once (especially so when SSL encryption is done),
we now perform write when the buffer has fewer
than the send-buffer-size bytes. Previously,
we were only getting more data to write to the
socket when the buffer was completely empty,
potentially wasting valuable opportunity to
write more data to the socket while we're at it.
Change-Id: I69a18a042dc2e551ebc5e1af40dae091da3f3d13
=> wsd: perform socket writes more efficiently

loleaflet/src/control/Control.JSDialog.js
When we display JS Dialog before the document is loaded
We should hide the progressbar. Spinning should be until the
1st user interaction.
Change-Id: Iad8bf56d9bcc57e106e76a961ba72490a74b26c0
* Resolves: # 
=> Hide the progressbar after the initial JS Dialog

loleaflet/Makefile.am
Used by android to build the JS it desires. We lost that in c6f2e2211d
Change-Id: I4b790a300aee66628baa2e5a2997685c42f709fa
* Resolves: # 
=> Restore missing rule to populate DIST_FOLDER with js.

loleaflet/src/layer/tile/CanvasSectionContainer.ts
scrolling a calc sheet down that contains some useful numerical data.
Seeming desynchronized can reduce copying and improve interactivity:
https://developers.google.com/web/updates/2019/05/desynchronized
alpha	desync	frame times	avg/ms
--------------------------------------
false	true	105, 94, 86	95
true	true	90, 108, 92	96
true	false	287, 284, 273	281
false	false	278, 298, 288	288
Change-Id: Id59ab3870ccd3d85d88fc0763bf9742cb21b5731
* Resolves: # 
=> Canvas: not alpha, and de-synchronized.

loleaflet/src/core/Socket.js
The browsers - unfortunately appear to round-robin consuming a single
WebSocket message and processing it, against updating the UI. This
ensures that for large / slow to render documents - responsiveness is
impaired by eg. 200ms frame render time. That in turn can rapidly
build up a 2500ms buffer full of messages in the browser too be
processed - before we find out about it.
Avoid this by slurping the websocket messages quickly onto a queue,
and deferring emitting those for a 1ms timeout or so and triggering
re-rendering.
Profiling shows this shortens the queue significantly and gives
better responsiveness. To test - hold down the 'down' arrow key in
calc until your view hits row 100 - ie. we have got to processing
those events from the browser's backlog. Then let go. With patch
- stops …
=> Websocket - message slurping.

android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
When a document is opened inside the app's document list
intent.getType becomes null. In this case we can retrive the
correct mimeType from contentResolver. This is needed especially
for csv files, because ".csv" is needed to be added to the temp file name
for lok to recognize it correctly. Otherwise it will be treated as
text file.
Change-Id: I61b853cf7ba9b648bf4ae8c54fd8b10d5754cf4c
* Resolves: # 
=> android: Fix intent.GetType() is null for the opened doc

android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, loleaflet/src/control/Control.MobileWizard.js
Text import dialog is displayed on initial document load
so we need to hide progressbar after that in order to
interact with the ui
Change-Id: I840bfea9d078260751622cbb09d256153821ff0e
* Resolves: # 
=> android: Hide progress dialog on initial mobilewizard pop up

loleaflet/src/layer/tile/TileLayer.js
Don't crash if marker object is not defined for a view.
Change-Id: If8f13da684ebf4028bff888c9edf4bac3ab359bf
* Resolves: # 
Problem summary:
Open eg. the sample hello world ODS in two views,
With view A, create and switch to a new sheet, and start editing a cell (don't finish it),
With view B, switch to the other sheet, and then add a new sheet.
-> View A's caret can be seen on the new sheet.
Fix: Add check for existence of marker for a view before accessing its methods.
=> fix: Other user's caret is shown when adding new sheet

common/ProfileZone.cpp, common/ProfileZone.hpp
Perhaps we should use the exact same code in both core and online? But
that would be a bit tedious as core needs to be cross-platform (and
thus we use things like osl_getSystemTime and osl_getProcessInfo in
its version) while online is Linux-only.
Also imporve the test for it.
Change-Id: I0bc9dca71dc4489bd1671e0dae1e582990a8f8b4
* Resolves: # 
=> Similar improvements to the ProfileZone here as to that in core

loleaflet/images/lc_helpindex.svg, loleaflet/images/lc_keyboard-shortcuts.svg, loleaflet/images/lc_report-an-issue.svg
* Resolves: #2026
lc_report_an_issue use the report icon with an edit symbol cause by click on it, user can edit cool
lc_keyboard-shortcuts icon get less keys so the icon isn't that busy and use the correct colors
lc_online_help the earch stuff was removed, sorry but cool is online so no need for an online symbol
Change-Id: I6c9f57f316997da3298f8ac4748bfe980733ad54
=> Update Help icons #2026

loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/TileLayer.js
The browsers - unfortunately appear to round-robin the asynchronous
unload of an individual tile - which causes a _tileReady callback
with updating the canvas.
This means that we re-render the canvas (at whatever speed) for each
tile we load - guarenteeing a nice animated effect of loading tiles
one by one, and refreshing the view: not so cool.
So - instead, as per WebSocket messages, slurp them - and then
refresh the view in one shot after 1ms; since it is fairly bogus
to convert a base64 encoded URL image to a real image asynchronously
anyway, this gives some nice results eg.
TileLayer.js:2464 Slurp tiles 34
TileLayer.js:2464 Slurp tiles 25
TileLayer.js:2464 Slurp tiles 53
TileLayer.js:2464 Slurp tiles 5
TileLayer.js:2464 Slurp tiles 3
It also significantly improves pageing down in …
=> Tile load slurping.

Makefile.am, kit/Kit.cpp, net/HttpRequest.cpp, net/HttpRequest.hpp, net/Socket.hpp, net/WebSocketSession.hpp, test/UnitLoad.cpp
net/HttpRequest.cpp:126:19: error: declaration of 'end' shadows a member of 'this' [-Werror=shadow]
kit/Kit.cpp:163:29: error: missing initializer for member 'statfs::f_bsize' [-Werror=missing-field-initializers]
kit/Kit.cpp:171:14: error: 'OVERLAYFS_SUPER_MAGIC' was not declared in this scope
Change-Id: Ibbd35ab5af3adad403ed22a0aeb70917b9e21970
=> Fix Debian 8 / gcc-4.9 warnings

loleaflet/css/notebookbar.css
* Resolves: #2121 and #2007
Instead of fixed margin-top values for each single notebookbar tab, I switched to `display: flex;` and `align-item: center;`
```
.notebookbar-scroll-wrapper {
overflow-x: scroll;
overflow-y: hidden;
scrollbar-width: none; /* Firefox */
-ms-overflow-style: none;  /* Internet Explorer 10+ */
display: flex;
height: 84px;
align-items: center;
```
As all tabs use similar json structure see #2007, all tab content is now center align. Only open work is the home tab, cause the height of the home tab, is heigher than for the other tabs. However the content is center align.
Most of the writer, calc, impress and draw specific settings were removed, cause for example the icon height is defined more global so they don't have to be defined within every bigtoolitem. 
- …
=> Notebookbar center align all tabs with display: flex #2121 and #2007

loleaflet/src/control/Control.NotebookbarCalc.js
In writer there is a layout tab and also in LibreOffice calc. There isn't really a lot of content only Page property Insert and Delete Row/Column Freeze and Alignment stuff like in writer.
Row/Column Break stuff was removed cause it didn't work, but can be added when available.
Tested also to add Freeze command into Data tab, but than it's way to much commands and as there are not that much tabs, I use Layout tab.
Change-Id: I2f7f4aeb1bd4f2a2b351e581d20589d37a20d87f
=> Notebookbar Clac Sheet tab was renamed to Layout #2130

loleaflet/src/control/Control.NotebookbarWriter.js
writer was missing now in all home tabs find and replace is visible.
Change-Id: Ic30b0a5c4d9cf72eacca92922597f80fc424fc33
=> Notebookbar Find and Replace everywhere in Home Tab #2136

loleaflet/src/core/Socket.js, loleaflet/src/map/handler/Map.WOPI.js
When user saves the document with a different name, new document will be
loaded.
While this happens, if there are more than one servers, client may be
directed to another server for the new file.
In this case, socket code will think that current server has restarted
and will reload the page. Socket code can't see if the server is
different than the previos one.
So, after a save-as operation, if we check the file adress with the
previous one, we can detect that the file we are viewving has changed.
In that case, we will not reload the page.
Change-Id: Idbf50678a453feccb34eb67a5b9286904a96bffa
* Resolves: # 
=> Page Reload: Add case for save-as.

common/StringVector.cpp, common/Unit.cpp, common/Unit.hpp, net/Buffer.hpp, net/HttpRequest.hpp, net/Socket.cpp, net/Socket.hpp, test/HttpRequestTests.cpp, test/HttpWhiteBoxTests.cpp, test/UnitHosting.cpp, test/UnitWOPI.cpp, test/UnitWOPIHttpHeaders.cpp, test/UnitWOPIVersionRestore.cpp, test/UnitWopiOwnertermination.cpp, test/WopiTestServer.hpp, test/run_unit.sh.in, wsd/DocumentBroker.cpp, wsd/LOOLWSD.cpp
- wsd: test: http::Header parsing tests
- wsd: simplify assertion
- wsd: test: UnitBase takes the test name from derived classes
- wsd: http: simplify appending to Buffer
- wsd: fix signed/unsigned mismatch
- wsd: shared_ptr can dereference directly
- wsd: explanation comment
- wsd: http: simplify sending response and shutting down the socket
- wsd: test: use http objects instead of manual strings
- wsd: test: assertPutFileRequest returns the http response
- wsd: test: log poco exceptions
- wsd: http: braces always on new line
- wsd: http: add isConnected getter to http::Session
- wsd: http: simplify http::get
- wsd: test: log UnitHosting activity
- wsd: test: safe header reader
- wsd: test: log the fake wopi response
- wsd: test: add the seconds suffix to the output
=> Backports from co-6-4 and test improvements

kit/SetupKitEnvironment.hpp
This reverts commit 9c217d6d9314bdb3a7a832c407e58ea5598932ab.
* Resolves: # 
restore client-side-grid: disable core grid and bg, now that fixes for related bugs are in co64.
=> restore client-side-grid: disable core grid and bg

loleaflet/src/layer/tile/TileLayer.js
* Resolves: # 
This fixes two different kinds of view jumps on autoinput/autocomplete.
=> Fix view jump on autoinput

loleaflet/src/layer/tile/CanvasTileLayer.js
* Resolves: # 
This fixes two different kinds of view jumps on autoinput/autocomplete.
=> Fix view jump on autoinput (master)

loleaflet/css/notebookbar.css, loleaflet/src/control/Control.UIManager.js
with #2235 and the fix of the home tab height it's now possible to reduce the notebookbar height to 72px in height instead of 84px.
Sure there would be 68 px theoretical possible, but the additional 4px in height are good for the home tab.
Change-Id: Id28bcc63db142d235986cb5449d750808b684c4f
=> Notebookbar height 72px instead of 84px #2088

loleaflet/css/device-mobile.css, loleaflet/src/control/Toolbar.js
- Fix problem introduced with d0253673a6e151661806b52f7c5e4bca7fe4fbcf
- Desktop was always without close button
- Add mobile specific class
- So we can style it apart from desktop
- So we can style it apart from mobile(other dialogs)
- Mobile: fix padding (remove for child element)
- So we can use more efficient the horizontal space
- Mobile: Dismiss button
- Make it full width
Change-Id: Icb6a5a0a4191b39ecf76eaafac06e182430490d0
=> Welcome dialog: do not mix desktop and mobile plus styling

loleaflet/css/notebookbar.css
93bc5f6083291f28460ccc7fd6c4e6b6ff55112f introduced a regression
in the Classic mode.
- Better target ui-combobox
- Use notebookbar class
- Simplify CSS declaration
Fixes: https://github.com/CollaboraOnline/online/issues/2088
Change-Id: I0ab1dee8a29408c58621297ba8eefc18db3c4fa9
=> Classic: select: do not change element's height

net/HttpRequest.hpp
- wsd: http: complete the http response only once
- wsd: http: add isConnected getter to http::Session
- wsd: http: disconnect if the server closed the socket
=> Fixes to properly close connections and not access released socket

loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarImpress.js
Thesaurus was removed from calc and impress/draw see issue #2129
Change-Id: If440bdf2c61aaac22811706cc440b9ccbe7a30d1
=> Thesaurus work only in writer #2129

loleaflet/src/control/Control.Notebookbar.js
As the notebookbar height was shrinked, the ScrollButton has to be shrinked also.
Change-Id: I6d195a10d98e57ec43d74f58d3bb13ed33b7b62f
=> Notebookbar ScrollButtons height shrink to 72px

test/HttpRequestTests.cpp
After 358b30a682227a5260e932fadbc585fddc9c0a8c.
Change-Id: I53ab88b240bde8fcd09dd916cf156dc251452b26
(cherry picked from commit 9bf17cd902402073c823446c90fc15ad6d33266a)
=> Fix build with --disable-ssl

cypress_test/package.json
Change-Id: Id7b955ad2154ec6393a4cb9d115f369db25b5008
problem:
every time running cypress test would change the properties,
in alphabetic order
this will make sure to avoid unintentional changes
=> cypress: rearrange dependencies in package.json

kit/Kit.cpp
We need a space after the prefix here to get past the
getForwardToken detection in the core; \n doesn't cut it.
Change-Id: I3f125d47586964ff844f0a89b04b8de866d01f8b
* Resolves: # 
=> Avoid parsers believing that the body is a forward message.

kit/SetupKitEnvironment.hpp
Kit initialization uses 'trace' for very early start, and then
switches to the configured trace level later on, so don't use
it this early.
Change-Id: I8e0333930b46e5ad25658d7eda12d7469bdfdd1e
* Resolves: # 
=> Don't enable profiling yet.

loleaflet/src/control/Toolbar.js, loleaflet/src/core/Socket.js, wsd/ClientSession.cpp, wsd/ClientSession.hpp, wsd/protocol.txt
Introduce a TRACEEVENT message from client to server
Add a function emitInstantTraceEvent() to leaflet that sends an
"Instant" Trace Event to the server for logging.
Add a function createAsyncTraceEvent() that creates an object that
records the timestamp of its creation and sends the 'b' event to the
server for logging, and when you call finish() on the object, sends
the corresponding 'e' event.
Finally, add a function createCompleteTraceEvent() that creates an
object for a "Complete" Trace Event that includes the end timestamp
*and* the duration. The event is sent to the server when you call
finish() on the object.
Loleaflet sends timestamps in the above messages from
performance.now(). To enable the server to turn those into absolute
timestamps, the loolclient message is amended to …
=> Introduce a TRACEEVENT message from client to server

Makefile.am, common/Unit.hpp, net/HttpRequest.hpp, wsd/ClientSession.cpp
- wsd: http: complete the http response only once
- wsd: http: disconnect if the server closed the socket
- wsd: log if we skip updating the modified flag
- wsd: make: add new files
- wsd: create the unittest SocketPoll thread only when testing
=> Backports from co-6-4 and a couple misc patches 

wsd/ClientSession.cpp
wsd/ClientSession.cpp:411:31: error: object backing the pointer will be destroyed at the end of the full-expression [-Werror,-Wdangling-gsl]
const char* str = tokens[2].data();
^~~~~~~~~
Change-Id: I67e4aa5f61e049ad13663dc1e11ae2bd67399bea
=> ClientSession: fix -Wdangling-gsl

cypress_test/integration_tests/common/calc_helper.js
because it is tunneled now as drawing on the canvas
Change-Id: I76c7d218abf155b2bd835d9f74b46d02e2808bbc
=> cypress: Don't check cursor in formulabar

Makefile.am, kit/ChildSession.cpp, kit/ForKit.cpp, kit/Kit.cpp, kit/Kit.hpp, loleaflet/js/global.js, loleaflet/src/control/Toolbar.js, loleaflet/src/core/Socket.js, wsd/ClientSession.cpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp
It enables turning Trace Event recording on (and off again). The
option is passed down to the client through loleaflet.html, and to the
KIT processes. If the option is not used, the new JS functions that
send trace events to the server turn into no-ops to avoid wasting
bandwidth.
It is always on in a "make run".
Change-Id: Iafe1919ccba7c376137d3e0568b857e20780bbc8
* Resolves: # 
=> Add an --enable-trace-event-logging option to loolwsd

common/Unit.hpp, wsd/LOOLWSD.cpp
This avoids having the test socket poll thread running when not testing (which was recently introduced with the async sockets in tests).
Also, initialize SSL when either termination is set or it's enabled outright.
=> wsd: create the unittest SocketPoll thread only when testing

wsd/LOOLWSD.cpp
Make it contain a proper empty JSON array if no trace objects have
been written to it.
Change-Id: Ided1992a822659561a909ac545536261b91adbac
* Resolves: # 
=> Clarify Trace Event file writing

loleaflet/src/layer/vector/Path.Transform.js
Dragging connector handles acts like regular shape handles
and scales uniformly
Change-Id: Ic3a729b3fa1c720990f9c1c687693bdb3cef02d7
* Resolves: # 
=> Fix connectors scale uniformly on mobile

loleaflet/src/map/Map.js
Some formats like PDF does not have progressbar implemented
in that case the progress dialog gets stuck at loading
We should dismiss that if the document is loaded
Change-Id: I6d6f5fae4da092c2605d85d014c634f3f12e0854
* Resolves: # 
=> android: Dismiss progress dialog on doc load

cypress_test/integration_tests/common/calc_helper.js, cypress_test/integration_tests/mobile/calc/overlays_spec.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/vector/CPath.ts, loleaflet/src/layer/vector/CPointSet.ts, loleaflet/src/layer/vector/CRectangle.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
* No AA bleeding: render pixel aligned (ie. 0.5 offset) for all hair-lines
* Two pixel wide line, around the cell - black; with the inner pixels /
line exactly on top of the cell border.
* inside this breaking the outline - an internal white border which is
exactly 1 pixel inside that black border - for a high contrast look.
The change introduces CPathGroup which is just an array of CPaths that
allows separate styling. CCellCursor and CCellSelection classes
specialize CPathGroup and implements the above three guidelines.
The view cell-cursors and view-selection also use the same
implementation with different styling.
The cypress tests are updated accordingly for the name change in the
test-div.
Change-Id: …
=> improve cell cursors and selections

loleaflet/css/notebookbar.css
`#table-optionstoolboxdown` was used for the sidebar icons by remove the 3 sections within notebookbar.css the arangement was similar to any other icons.
`.unospan-optionstoolboxdown` define `margin: 0 !important;` in `.unotoolbutton.notebookbar` `margin-right: 5px !important;` was defined.
As the margin between two icons / commands is everywhere else 5px I don't see an reason to have here a special case. At least it's easier to select.
`.cell.notebookbar` setting `padding: 0 !important;` is at any mother `.cell.notebookbar` 2px
`.unobutton` was defined already with `width: 24px !important;` and `height: 24px !important;` by remove `.cell.notebookbar` `padding: 0` the `padding: 4px` isn't needed any more
Change-Id: …
=> Notebookbar.css remove settings for #table-optionstoolboxdown

loleaflet/css/toolbar.css
Make sure we set white background only when the component
is enabled so to avoid displaying empty rectangle in the
notebookbar
Change-Id: Ic900bb42cb34b20d0cf1beb85caee1e0967bf01e
=> DocumentNameInput: Fix background when disabled

loleaflet/css/notebookbar.css
Calc has the most icons in the direct formatting group so the width of the fontnamecombobox was enlarged to optimize the group at calc
Writer, Impress/Draw use one icon less so I added an 44px space. By add Character Spacing command #2149 there are everywhere the same number of commands, so the 44px margin can be removed.
Change-Id: I8782cc738d79174a7f78f9e9e3fbd604f64e2233
=> Notebookbar: Home tab: positioning direct formatting icons #2085

loleaflet/js/global.js
URLs from host may already contain a query, like
http://server.tld/foo/wopi/files/bar?desktop=baz
Previously, we simply appended '?' and then our parameters, resulting in
http://server.tld/foo/wopi/files/bar?desktop=baz?access_token=...
which later was processed as if the question mark and following parameter
were part of previous parameter's value, so proper 'access_token' parameter
was missing.
This checks if the URL contains '?', and uses proper separator accordingly.
Change-Id: I1a237c0e47e1eea3704ef7d4a8a596283ea2a241
=> Properly process URLs with existing query

.cirrus.yml
This PR adds FreeBSD continuous integration using Cirrus CI. To make it work for https://github.com/CollaboraOnline/online repository, the Cirrus CI app should be enabled for it: https://cirrus-ci.org/guide/quick-start/
Running `make check` is currently disabled, as some tests fail for unknown reason. They pass on my local machine, though, so I hope to resolve it quickly.
=> Add Cirrus CI configuration for FreeBSD testing.

cypress_test/integration_tests/common/calc_helper.js, cypress_test/integration_tests/mobile/calc/overlays_spec.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/vector/CPath.ts, loleaflet/src/layer/vector/CPointSet.ts, loleaflet/src/layer/vector/CRectangle.ts, loleaflet/src/layer/vector/CanvasOverlay.ts
* No AA bleeding: render pixel aligned (ie. 0.5 offset) for all hair-lines
* Two pixel wide line, around the cell - black; with the inner pixels /
line exactly on top of the cell border.
* inside this breaking the outline - an internal white border which is
exactly 1 pixel inside that black border - for a high contrast look.
The change introduces CPathGroup which is just an array of CPaths that
allows separate styling. CCellCursor and CCellSelection classes
specialize CPathGroup and implements the above three guidelines.
The view cell-cursors and view-selection also use the same
implementation with different styling.
The cypress tests are updated accordingly for the name change in the
test-div.
Change-Id: …
=> improve cell cursors and selections (master)

common/MessageQueue.cpp, common/MessageQueue.hpp, common/RenderTiles.hpp, kit/Kit.cpp
* Resolves: #1234
Add `dumpState` methods to `TileQueue`, `PngCache`, `ThreadPool` classes
and call them from Document::dumpState method within kit.Kit.cpp.
Because `dumpState` method of `_websocketHandler` is protected,
currently we can't dump its internals.
Also dump the other members of the `Document` class. Note that as
`_lastMemStatsTime` is never used, we don't dump it. It seems we could
simply delete it.
=> Improve state dump

loleaflet/css/toolbar.css
When the formular toolbar was extended the tunneled toolbar missed the bottom horizontal line, the reason was the bottom margin was defined with -4px. That was fixed.
The toolbar .w2ui-reset was vertical-align center but at extended formular input field is has to be top aligned + some padding fixes
Change-Id: Ibd94b3beb815bce8a1e5e6de09d89b47be19df2a
=> Calc Formular bar alignment #809

Makefile.am, common/security.h, configure.ac
So if you're debugging the product build you can use:
--with-user-id=`whoami`
Change-Id: I3f753b83c0806729d36d45293bc2b6a38d50fdbb
* Resolves: # 
=> Allow easy configuation of the user-id that is accepted.

loleaflet/src/layer/tile/CanvasTileLayer.js
Interestingly for large CPU rendered skia surfaces - as used by
many browsers, rendering well spaced vertical lines is inordinately
expensive: 10x slower than horizontal ones, presumably due to cache
effects.
Grid rendering is around ~40% of our rendering performance measured
by knocking out various elements we render and re-timing.
By banding our vertical lines to re-use pixels close to where we
are drawing horizontal lines, and by creating more smaller paths
we get at ~25% overall performance improvement - 70ms -> 53ms
avg of ~10 frames.
Change-Id: I8ad1007b74866bd3d7b1b838f226a3efadcccbed
* Resolves: # 
=> Render grid-lines in horizontal strips for performance.

Makefile.am
We don't have permission for /var/log/loolwsd.log typically.
Change-Id: I37c04bfba25c4c8241b2d92d77d93e5a3b662d82
* Resolves: # 
=> make run should log to the console in product mode.

loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/ScrollSection.ts
Send the canvas container into a paused state just before a batch of
queued messages are going to be executed. During this state the
container dirties itself for every requestRedraw() call. After all
messages in the current slurp batch is executed, resume rendering
starting with a re-render if necessary based on dirty flag.
Change-Id: Ice5347aac78f4f19642b96edb929836b15c55599
* Resolves: # 
=> avoid rendering for execution of ~every message

.gitignore, configure.ac, loolkitconfig.xcu.in, loolwsd.xml.in
Now it is possible:
- to disable Help buttons and jumping to external website of Online Help (--without-help-url)
- set the icon theme of tunneled dialogs and sidebar (--with-core-icon-theme=<theme>)
- set the list of allowed dictionaries (--with-dictionaries=<language list>)
This patch obsoletes the packaging hacks that we had to use for certain customers.
Change-Id: I450f66ac133f6fcefae2bda9f29e04405ef3a6b7
=> 3 new build-time configurable settings

loleaflet/src/layer/vector/CSplitterLine.ts
Change-Id: I5b2c9f4937fbed9d03763cc25168142471d2f7a6
* Resolves: # 
=> fix: splitter line drawn over other overlays (co64)

loleaflet/css/override-vex.css, loleaflet/src/control/Toolbar.js
- Only close when user expressly pressed the close button
- Make it possible to select text
This type of dialogs with a lot of text should only be close when
pressing close button so to avoid accidentally closing it. The text
should also be selectable, allowing the user to save it in his own notes
, to share or to use it to simply report something
Fixes https://github.com/CollaboraOnline/online/issues/2357
Change-Id: I88e01904bad4d0fa2504296c892e28ba6df9d112
=> Help dialogs: avoid closing it by mistake and make it selectable

loleaflet/css/notebookbar.css
Context tabs were being shown via JS by setting display property to block
this in turn was maligning the tab's title ( as it's expecting flex)
Fixes #2385
Change-Id: I28e56f3f78390a626780bfbd1a302fef9c90ba38
=> Notebookbar: context tabs when selected: fix alignment

cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Default cypress view is too small, scroll first and then
attempt clicking in the bullet icon. This fixes failing tests
on this spec. No need to skip the test anymore.
Change-Id: Idffbfec94f94c784b03815c21ece0b8d38a8ba0e
=> Cypress: Toggle bulleted list test: scroll before testing

loleaflet/src/control/Control.JSDialogBuilder.js
Reuse existent font to set a different label for applystyle command.
- Avoid duplicates (icon value-string      value-string  > )
- Fixes layout breakage (no space)
- Set it as "translatable" string
- Translation needs to be updated
Change-Id: I2d10c772a15fcb36a7169d77ff72cb5e5f6f7ed1
=> Mobile: applystyle: Set different string for static label

loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I2e9d61f98d9cf4e96ae720cc660278f8bf0c6df8
* Resolves: #2171
* Target version: distro/collabora/co-6-4  
problem:
Jquery tooltip uses title property for tooltip content
this tooltip property is also applied to all the child element,
if they do not have their own title
resulting into false tooltips in many cases
=> leaflet: notebookbar: removed title property from notebook content div

loleaflet/css/notebookbar.css
With an 1px gray-color outline it's better visible where the mouse is hover an command.
When the user hover over an selected command it's also better visible.
Change-Id: I993888bd81a9f18f6d1746a42c9db4f165055e41
=> Notebookbar add outline for hover commands

loleaflet/src/layer/tile/CalcTileLayer.js
Change-Id: I6f260f87fadfd371b095784538473e8c728c95e3
* Resolves: #2197 
problem:
in some cases comments were not hidden
where specifying which part's comment to hide
i.e: when we add new sheet it is not possible to know which was previous sheet
so couldn't hide the comments from previous sheet after adding new sheet
in such cases hide all the comments
later showAnnotations handles which comments to show
=> leaflet: hide all comments in the document if part not specified

loleaflet/css/notebookbar.css
As the tab hover effect used an defined color and the plan is to use var colors, I implement another hover style for tabs.
Hover on notebookbar tabs show a 2px bottom line in primary-color depend on the app and the tab label color switch also to primary-color. The layout follow the cool color vars and look very consistent.
Change-Id: Ia8da2472f7feee97c198c14a9cb059a257168b3e
=> Notebookbar Tab hover use primary color

loleaflet/src/control/Control.Notebookbar.js, loleaflet/src/control/Control.NotebookbarBuilder.js, loleaflet/src/control/Control.NotebookbarDraw.js
As Fullscreen mode can be very usefull #2416 to save space, I suggest to add Fullscreen command to the Shortcut bar at writer, calc and draw. So also the number of items in the shortcut bar is always the same.
Change-Id: I5f37c8d1f9a42527372abcf99bac14b0f539c663
=> Notebookbar Shortcut bar add Fullscreen #2417

loleaflet/css/notebookbar.css, loleaflet/src/control/Control.NotebookbarCalc.js, loleaflet/src/control/Control.NotebookbarDraw.js, loleaflet/src/control/Control.NotebookbarImpress.js, loleaflet/src/control/Control.NotebookbarWriter.js
Sure Cut, Copy and Clone, Clear are two separate groups cause Clone and Clear are related to other stuff, but have them within one group, mean also icon only and that was the idea behind.
Cut, Copy symbols are very well know, so a label isn't needed from a usability point of view.
Have icons + label mean always that string translations will change the UI and Home tab has ordinary more content. However on the home tab there should be commands/icons which are well know only, so home tab without labels will improve a unified home tab on all languages.
Change-Id: I1c20091f616f5aac57bc802b30db629c9bacd66c
=> Notebookbar Cut, Copy commands without label

configure.ac, loleaflet/Makefile.am
The intent is that it should no longer be necessary to do the
JavaScript part on a Linux machine. For the configury and "make" part,
mostly just some minor portability issues had to be handled:
The readlink command on macOS has no -f option. But that use of
readlink is not necessary anyway in a tree for building a mobile app,
so bypass.
The find command on macOS always requires at least one directory name.
So when $(CUSTOM_ICONS_DIRECTORY) is empty the "find
$(CUSTOM_ICONS_DIRECTORY) -name '*.*'" command produced an annoying
error message. Handle that in a trivial way.
The echo command in /bin/sh on macOS does not have the -n option. Use
the more portable printf command instead.
To then configure and run the make (before you can do the actual build
in Xcode9, you need have Node.js …
=> Enable building the iOS app completely on macOS

loleaflet/css/notebookbar.css, loleaflet/images/lc_fullscreen.svg, loleaflet/images/lc_presentation.svg, loleaflet/images/lc_save.svg
By default all Statusbar icons use blue1-txt-primary-color
instead of use green0-txt-primary-color, yellow0-txt-primary-color and orange1-txt-primary-color hue-rotate svg filter was used.
-> Simplify codebase
Change-Id: I5f675c25b4711c2ecc2c04612b3a95682dc17ad9
=> Statusbar use hue-rotate styles svg icons

loleaflet/src/layer/tile/CanvasTileLayer.js
Don't confuse between tile object and the tile image element.
Assign the tile object to tile array correctly and update the tile image
using the tileCache.
Change-Id: I014cc47c7b6e4086384a66158fb8eb2534714b99
* Resolves: # 
=> fix: empty tiles on zoom back to previous level (co-6-4)

cypress_test/integration_tests/mobile/writer/annotation_spec.js, loleaflet/src/layer/tile/WriterTileLayer.js
Change-Id: If72e6f98acf5fcad1202332fa6521d7ad0e35e83
when we insert the comment in writer the value of parent,id coming from core is typeof string but after reload the value of parent,id coming from the core is typeof number
=> fix:comment doesnot appear in wizard after reload in writer

loleaflet/Makefile.am, loleaflet/css/color-palette.css, loleaflet/css/loleaflet.css
move loleaflet.css .root color varaibles into a separate color-palette.css file so all var colors are at a dedicated file and branding is easier.
Change-Id: I6fe879fbb09e2d5170c028820974bdda0466805d
=> CSS color-palette vars are within a separate css file

loleaflet/Makefile.am
error TS2503: Cannot find namespace 'NodeJS'
Change-Id: Id4f9fba48095d80725de97ef3bc464602707bf91
=> loleaflet: fix builddir != srcdir

loleaflet/src/control/Control.NotebookbarWriter.js
LatestUpdates was correctly calling the intended function but
the json was missing the updated values:
- Change item type
- Use already existent custom command
also related to #2232 issue
Change-Id: Ie1ed5ed48db22420347c9d9df432c6c9bc5fd342
=> Notebookbar: Help Tab: promote items to bigtoolitem: fix

loleaflet/src/control/Control.MobileWizard.js
Also changed the Down Arrow icon for GoBack button because
at this stage, it closes the document
Change-Id: I5f32939996ee1f21fcedab6468e47aa51251bd9d
* Resolves: # 
=> make mobilewizard fullscreen for dialogs visible before document load

Makefile.am
npm installation is taking too long,
it is preferable to process in parallel
while compiling some c++ source files.
Change-Id: Ie04726805723d94227806fb8b30c39909b84cb0f
=> parallel npm installation

loleaflet/css/toolbar.css, loleaflet/images/lc_mobile_comment_wizard.svg, loleaflet/images/lc_mobile_wizard.svg, loleaflet/images/lc_ok.svg, loleaflet/images/lc_ok_white.svg, loleaflet/images/lc_redo.svg, loleaflet/images/lc_undo.svg, loleaflet/src/control/Control.MobileTopBar.js
Fullscreen and presentation was removed (they are available at the hamburger menu)
Spacer after undo/redo so that there are 3 buttons on the left and 3 on the right
Update TopBar icons. All are now monochrome
Change-Id: Iff79bc24a4fcfacee63d87ecefea76c00b1dfdab
=> Mobile TopBar update layout

loleaflet/css/toolbar.css, loleaflet/src/control/Control.MobileBottomBar.js, loleaflet/src/unocommands.js
Presentation has a BottomBar, but drawing not as both can use the same BottomBar I add the presentation BottomBar to be used for drawing too.
If you check LibreOffice Draw and Impress they use OutlineRight and OutlineLeft instead of IncrementItem and DecrementItem so OutlineRight and OutlineLeft was added to BottomBar
Change-Id: I65a9e2b0b8aff21861daf24a5bbd6bb971f50629
=> Mobile add BottomBar for drawing

loleaflet/css/device-mobile.css
The height of the bottom bar items is 35px the height of BottomBar was defined with 34px so that it look always as the bottomBar was cutted.
Height is changed from 34px to 37px (check the blue select frame, it now wasn't cuted)
Change-Id: If30e56c582ca652cb35e73f669f440696c6b03b4
=> Mobile BottomBar fix height

loleaflet/src/control/Control.MobileTopBar.js
As Impress and Draw has the same TopBar commands, they share now the code to have a smaler codebase
Change-Id: I7867fef2704a57439288d044d881496d0f6c4c62
=> Mobile Impress/Draw share TopBar code

loleaflet/css/notebookbar.css
Context tabs were being shown via JS by setting display property to block
a previous fix has been pushed targeting only active tabs:
d64a16d74de74f4356a769677b64e36d07ccee9b
Related to #2385
- Do not single out active/selected context tabs
- Re-set proper flex property for all if block has been set (via jquery)
- with a plus that we can keep using .show()
Change-Id: I8b2bf89aaea9fffaf1d4079929156f3ded48cfc2
=> Notebookbar: context tabs: fix alignment

android/app/src/main/res/values/strings.xml, android/app/src/main/res/xml/libreoffice_preferences.xml, android/lib/src/main/cpp/androidapp.cpp, android/lib/src/main/cpp/androidapp.hpp, android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, wsd/Storage.cpp
This was already worked on iOS since commit
75a3ab02ca072bb09ec39623730eecc4db71d1cf (Add an iOS setting for the
user's name or nickname, 2021-04-07), start using the same API on
Android as well.
Change-Id: I37825d143b0ed92bd84f9a1512313e51ff5e761c
=> Add an Android setting for the user's name or nickname

wsd/Storage.cpp
As requested by mmeeks.
Change-Id: Iba04bc5255479b9b0998a385d558bf07279bf00c
* Resolves: # 
=> Add a ProfileZone around two more WopiStorage member functions

wsd/ClientSession.cpp
Change-Id: I4ab8d04099a432e7fd3fb6810d7a9aa038cbb57d
=> wsd: revisit log messages ClientSession.cpp

loleaflet/src/layer/tile/CanvasTileLayer.js
Before slurping events work, on switching parts the canvas was getting
painted as side effect of other events triggered from
Parts.js:setPart(). Let us enforce an explicit and possibly immediate
canvas update on part/slide switch in case we have all the necessary
tiles in the tile array or the cache in the doclayer method
_updateOnChangePart().
Change-Id: I776c1a2476adb1db2054eecdbba78feff290981a
* Resolves: # 
=> fix: no painting on switching to earlier slides (co-6-4)

loleaflet/src/layer/tile/CanvasTileLayer.js
Before slurping events work, on switching parts the canvas was getting
painted as side effect of other events triggered from
Parts.js:setPart(). Let us enforce an explicit and possibly immediate
canvas update on part/slide switch in case we have all the necessary
tiles in the tile array or the cache in the doclayer method
_updateOnChangePart().
Change-Id: I776c1a2476adb1db2054eecdbba78feff290981a
* Resolves: # 
=> fix: no painting on switching to earlier slides

loleaflet/Makefile.am
Change-Id: Ie2df89ba09597a34aca9221bf082b1f2df3c7d07
problem:
in compilation tsc removes blank lines from the file
this causes problem in debugging and mapping with IDEs
https://github.com/microsoft/TypeScript/issues/843
=> Do not include js files in TS compilation

net/Socket.cpp
We send lots of large tile data this way, this should help
accelerate tile data transfer marginally.
Change-Id: I1deab7845c09dc65b1f44e9f9fc762f70ce94cc3
* Resolves: # 
=> Use larger write buffer size for UDS from kit -> wsd.

loleaflet/src/control/Control.Header.js
When used 120% zoom and selected any row after 50
there were multiple rows highlighted.
Change-Id: I4bc5f4272bf65fb0f9d00d96527890281377c0a8
=> Avoid higlighting additional rows/cols

loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/GridLayer.js, loleaflet/src/layer/tile/ImpressTileLayer.js, loleaflet/src/layer/tile/WriterTileLayer.js
tile-size is always 256 core pixels, so twips size of a tile in
different zooms are different depending on zoom scale. But the document
coordinates of the tiles in twips are zoom invariant.
Problem it resolves: Open any writer/impress document, switch to 85%, 120% zooms and then back to 100%.
Make a very noticeable change like color change. Now switch to 85% or 120% zoom, the change is not there completely or there are blank tiles.
Change-Id: I648134aaf84d451d93dad54d62b66062fb1d9204
* Resolves: # 
=> fix tile invalidation for tiles of other zooms

android/app/src/main/res/values/strings.xml, android/app/src/main/res/xml/libreoffice_preferences.xml
i18n issue: android:defaultValue="Guest User" is not localizable.
Change-Id: Id80b01e7d7a1059476a688ebdf1ce848c6838cc4
=> android: mark "Guest User" for l10n

common/Log.cpp, common/SigUtil.cpp
It was a request an approved by @kendy despite the signal
handler limitations. After several tries, we were blind
when we introduce the commit using the heap.
This reverts commit 9720eb0f81e1dfb10fa4e0860041b909bc5ced88.
=> Revert "common: add tag string to extract backtrace logs"

kit/Watermark.hpp
Change-Id: I30ab21475b6654a9375574be825e01edbdabf82a
* Resolves: # 
* Target version: co64
=> fix: watermark not present in fully transparent tiles

loleaflet/css/mobilewizard.css
no command line break needed shadow is part of bold, italic, underline
Change-Id: I0538a0a5499829f472f4cef078bf4db1ef9877fc
=> Mobile css remove clear after shadow

loleaflet/css/mobilewizard.css
padding, margin, icon size same as everywhere else
label isn't realy needed and cause only additional space.
Change-Id: I2be56c64f7b9c0f15a62e8264fe9d8d3c474e65f
=> Mobile FontWorkShapes same alignment and padding than everywhere

loleaflet/css/mobilewizard.css
Change-Id: Ice1994ddcd5e87e64afe85a623e4a276f0e032f9
=> Mobile explorable-entry use the same padding-left than ui-header

loleaflet/css/device-mobile.css, loleaflet/css/mobilewizard.css
- Mobile explorable-entry use the same padding-left than ui-header
- Mobile show border-top ad bottomBar
=> private/andreas/Mobile BottomBar Border top

loleaflet/css/mobilewizard.css
the left padding come from toolbar.css on mobile it was replaced to have all arrows vertical aligned
Change-Id: I5f5d5bb9de9f1b4ef604778077db35ea5546357f
=> Mobile: fontnamecombobox use no left padding at mobile sidebar

loleaflet/src/core/Socket.js
If doclayer is initialized, call setpermission, if not, update
options.permission. So doclayer will get the value from
options.permission while it is initialized.
Change-Id: Ic8d0687a1e98f597b89cbc389407710d268dc6d4
* Resolves: # 
=> File perm: Handle message properly.

kit/Kit.cpp
No separate Kit process in the mobile apps, and the iOS app even can
have several documents open simultaneously, so the singletonDocument
variable does not make sense.
If we at some stage want to generate Trace Event log files also in the
iOS or Android app (perhaps not likely), will have to handle it in a
different fashion. All the code runs in one process anyway in the
mobile apps, so it wouldn't make sense to "send" collected Trace
Events to the code standing in for the WSD process.
Change-Id: I5777b48e98121c3ed55e590d5009e2658af2ef22
* Resolves: # 
=> Fix crash in iOS app

kit/Kit.cpp, net/Socket.hpp
While we are processing data in the poll handler, we can have
another helpful thread from the core sending things to us:
loolforkit(Socket::assertCorrectThread(char const*, int))
loolforkit(WebSocketHandler::sendFrame(std::shared_ptr<StreamSocket> const&, char const*, unsigned long, unsigned char, bool) const)
loolforkit(WebSocketHandler::sendMessage(char const*, unsigned long, WSOpCode, bool) const)
loolforkit(Document::postMessage(char const*, int, WSOpCode) const)
loolforkit(Document::sendFrame(char const*, int, WSOpCode))
loolforkit(ChildSession::sendTextFrame(char const*, int))
loolforkit(ChildSession::loKitCallback(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))
loolforkit(Document::GlobalCallback(int, char const*, void*)) …
=> Transfer LOK callback processing into our main thread if necessary.

configure.ac, net/HttpRequest.cpp, net/HttpRequest.hpp
- configure: allow for setting --with-lo-path with --enable-fuzzers
- wsd: http: performWrites can be called after destroying the socket
- wsd: better handling of invalid port in URL
- wsd: http: sync requests accept external poller
- wsd: http: an incomplete response is an error
- wsd: http: always destroy the socket last
- wsd: http: do not set the state explicitly on parsing error
=> HTTP fixes based on fuzzing

common/Util.hpp, net/HttpRequest.hpp, net/NetUtil.cpp, net/Socket.hpp, test/HttpRequestTests.cpp, test/HttpTestServer.hpp, test/UnitWOPITemplate.cpp, test/WhiteBoxTests.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.hpp
- wsd: disable socket traffic logging
- wsd: document ModifiedTime getter/setter
- wsd: typo
- wsd: remove unused DocumentBroker member
- wsd: correct sha1 logging of the downloaded doc
- wsd: test: log state transition in UnitWOPITemplate
- wsd: http: better logging of errors
- wsd: better handling of invalid port in URL
- wsd: add hexify-data utility
- wsd: http: better logs
=> Logging, documentation, tests, and minor fixes

kit/Kit.cpp
While we are processing data in the poll handler, we can have
another helpful thread from the core sending things to us:
loolforkit(Socket::assertCorrectThread(char const*, int))
loolforkit(WebSocketHandler::sendFrame(std::shared_ptr<StreamSocket> const&, char const*, unsigned long, unsigned char, bool) const)
loolforkit(WebSocketHandler::sendMessage(char const*, unsigned long, WSOpCode, bool) const)
loolforkit(Document::postMessage(char const*, int, WSOpCode) const)
loolforkit(Document::sendFrame(char const*, int, WSOpCode))
loolforkit(ChildSession::sendTextFrame(char const*, int))
loolforkit(ChildSession::loKitCallback(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))
loolforkit(Document::GlobalCallback(int, char const*, void*)) …
=> Transfer LOK callback processing to our main thread if necessary.

wsd/LOOLWSD.cpp
loleaflet does not look for a &enabletraceeventlogging=yes query
parameter. That was removed many weeks ago.
Change-Id: I33b36191f1d21c2c0177061ff704aa9bcd5f9ef3
* Resolves: # 
=> Remove leftover incorrect usage hint

net/HttpRequest.hpp
The Socket instance owns the protocol handler
by design. This implies that the Session,
which is also the protocol handler, cannot
itself own the Socket.
Here we change that ownership into a weak_ptr
and pass the exclusive ownership of the Socket
to SocketPoll. We track the connection state,
so we can create a new socket when we are
disconnected.
Change-Id: Id6bf6506b0c8e2e0564f91977e1e7189d934a68f
=> wsd: http: break cyclic dependency

loleaflet/src/control/Control.NotebookbarBuilder.js
structure for JSDialogBuilder has been changed and doesn't
fit notebookbar needs
Change-Id: Ib040edd32f2e039cb8d0395abdc2bfb39a3b43d8
=> notebookbar: keep old toolbox implementation

kit/Watermark.hpp
And only insert the new pixmap after the check.
Change-Id: I310d321443152967b3aed8992ece3b55287d01cc
=> Bail out of getPixmap gracefully, when rendering failed.

loleaflet/src/layer/tile/CanvasTileLayer.js
When map's position is changed via ResizeObserver, remember to center
the view by calculating the new center and calling setView() with that.
Change-Id: I12afbfd59e6acafab91027c6038c1eeeedaea661
* Resolves: # 
=> fix: comments sometimes overlap the document

android/lib/src/main/cpp/androidapp.cpp, android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java, android/lib/src/main/java/org/libreoffice/androidlib/PrintAdapter.java, loleaflet/src/control/Permission.js
In addition, refactored the restating the app bits for copy requests
Now, we dont need to reload the activity for the new document
instead LO will switch to the new.
Change-Id: I0319086ece0b7dcd0bbed865ac2a9681c7a1edb5
* Resolves: # 
=> android: Implemented conversion to odf  format for plain/text types

common/Common.hpp, gtk/mobile.cpp, kit/ChildSession.cpp, loleaflet/src/control/Control.DocumentNameInput.js, net/HttpRequest.cpp, test/Makefile.am, test/UnitWOPIAsyncUpload_Close.cpp, test/UnitWOPIAsyncUpload_Modify.cpp, test/WopiTestServer.hpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.cpp, wsd/Storage.hpp
These patches enable async uploading and add tests.
- wsd: add async API to Storage
- wsd: support asynchronous upload requests to storage
- wsd: handle async upload callback
- wsd: upload after saving only if necessary
- wsd: better logging of upload state
- wsd: better logging of autosave, upload, and modified states
- wsd: test: add async upload test on closing
- wsd: test: add async upload test to modify after fail
=> Asynchronous Uploading

common/Common.hpp, common/Util.cpp, common/Util.hpp, kit/ChildSession.cpp, loleaflet/src/control/Control.DocumentNameInput.js, net/HttpRequest.hpp, net/NetUtil.cpp, net/Socket.cpp, net/Socket.hpp, test/Makefile.am, test/UnitWOPI.cpp, test/UnitWOPIAsyncUpload_Close.cpp, test/UnitWOPIAsyncUpload_Modify.cpp, test/UnitWOPIHttpHeaders.cpp, test/UnitWOPIVersionRestore.cpp, test/UnitWopiOwnertermination.cpp, test/WopiTestServer.hpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/Storage.cpp, wsd/Storage.hpp
- wsd: document ModifiedTime getter/setter
- wsd: typo in argument name sessionId
- wsd: correct sha1 logging of the downloaded doc
- wsd: http: simplify sending response and shutting down the socket
- wsd: http: better logging of errors
- wsd: http: better logs
- wsd: correct conditional scope
- wsd: add async API to Storage
- wsd: remove unsused return values
- wsd: support asynchronous upload requests to storage
- wsd: correct GetFile duration tracking
- wsd: handle async upload callback
- wsd: upload after saving only if necessary
- wsd: better logging of upload state
- wsd: better logging of autosave, upload, and modified states
- wsd: test: use http objects instead of manual strings
- wsd: test: assertPutFileRequest returns the http response
- wsd: test: safe header reader
- wsd: …
=> Async Backports from Master

loleaflet/src/layer/tile/CommentListSection.ts, loleaflet/src/layer/tile/WriterTileLayer.js
- Introduce missing redline methods.
- Fix anchorPos, anchorPix computation.
Change-Id: Ifce70f4e9fc9f751035d86f1da9a05774e9d69dd
* Resolves: # 
=> restore redline as comments functionality

loleaflet/css/loleaflet.css, loleaflet/src/control/Control.UIManager.js
unless we are in presence of a presentation or drawing.
- Hide it by default
- Use UIManager to show element
Fixes the glitch responsible by presentation-controls-wrapper
being shown right at the initialization time no matter the doc type
Change-Id: I74c8ac615282774a7fdb35f5e79e5bec329ad774
=> On load: Do now show presentation-controls-wrapper

loleaflet/src/layer/marker/TextInput.js
Change-Id: I0a1e807a2872e83d654fb7564aa1e9f4a2b5b88e
When you try to hover over a caret resize element of the clipboard textarea was visible
=> leaflet: disable resizeable property from clipboard-container

loleaflet/src/core/Socket.js
Reduces memory pressure from 24Mb + expensive GC's to 11.5Mb by
avoiding allocating large numbers of strings during UInt8 conversion.
Change-Id: Ia3fc5079f76abfc94e78d61b74b20cb394bcdc9e
* Resolves: # 
=> Convert strings far more quickly with apply.

loleaflet/src/core/Socket.js
Uncaught RangeError: Maximum call stack size exceeded
at NewClass._extractImage (Socket.js:419)
Change-Id: I9e0f98d269a0ea1388e4c5385f7b369df6a24fde
* Resolves: # 
=> Convert from Uint8Array to String without blowing the stack.

net/Ssl.cpp, net/Ssl.hpp, net/SslSocket.hpp, test/helpers.hpp, test/test.cpp, tools/WebSocketDump.cpp, wsd/LOOLWSD.cpp, wsd/Storage.cpp
- wsd: separate the SSL locks from the context
- wsd: separate client SSL context from the server
=> Separate SSL Context for Client and Server Sockets

loleaflet/css/loleaflet.css, loleaflet/css/spreadsheet.css, loleaflet/css/toolbar.css, loleaflet/css/w2ui-1.5.rc1.css
- Calc: Fixes Tab list that was out of place and not visible
- Calc: Fixes inconsistency with background colours
- Calc: Fixes selected tab status by improving styling
- Also use CSS vars instead
- Fixes overall (for all applications) toolbar-down (status bar)
- Border was being overlapped and thus not being displayed
Change-Id: I766ca3ee3d82c89343a318d3adcf2d2e3a7dcf46
=> Fix Calc tab positions, sidebar width and Status bar

loleaflet/src/layer/tile/TileLayer.js
* Resolves: # 
* Target version: co-6-4-9
Backport of view jump fixes to co-6-4-9.
=> View jump fixes for co-6-4-9

loleaflet/src/map/Clipboard.js
Also make sure to not show the "Confirm copy to clipboard" in the end
of the download which is not intended for the local clipboard, but is
immediately uploaded to the target document
Change-Id: I09f27a234cc92fd0700bf29654f44cbaa158de47
=> Don't hide download progress when async download has started

loleaflet/src/control/Control.Menubar.js
Fixes the used id by removing `-` (to be the same as used by
`_onlineHelpControl` control in the desktop:Notebookbar).
In return the id is then used to call the correct svg file name.
Change-Id: I63951d20b204b61e64a6c0d7e394465e230b7377
=> Mobile: Hamburger menu: latestupdates: Fix missing icon

loleaflet/css/device-mobile.css, loleaflet/css/toolbar-mobile.css, loleaflet/src/control/Control.Menubar.js
- Add mobile class to #toolbar-wrapper to avoid targeting anything else
- Sets Menuwizard so it goes above toolbar (position absolute) so to be
properly aligned from the top
- Sets toolbarwrapper with normal z-index (according to its parent) so
menuwizard can be above it
Note, no need to touch #toolbar-hamburger.menuwizard-opened has it comes
already with z-index properly set
Behavior might be related with changes from
ff20ec7
Change-Id: I1a66057b7827309a6ad3871927099ac1c9339657
=> Mobile: menuwizard (hamburger): Fixes contents position

loleaflet/js/global.js
Change-Id: I0f253d68b4c78c5a7b29fa9d14c02e049af0b14e
(cherry picked from commit 4730ad5e08bc43d4ce85d3b69e8734ce46969ec5)
* Resolves: # 
* Target version: co-6-4-9
=> ie11: do not use Array.includes

wsd/LOOLWSD.cpp
The original behavior must be preserved, which is not to
initialize SSL when termination is enabled but SSL is disabled.
This reverts commit 1c9541a6a636647086397e1310084cc990b6ed70.
=> Revert "wsd: initialize SSL if enabled or termination is enabled"

loleaflet/css/device-mobile.css
Depends on: https://gerrit.libreoffice.org/c/core/+/116265
Fixes checkbutton (Use separators) position by placing it
before divider label ('separatoroptions') thus, improving readability. User
can now see it clearly that all those separator options are related
and hierarchically under a main option: #toseparatedby.checkbutton.
Change-Id: I97b133e3e873a76ca75290728adaf1a45c9bcece
=> Mobile: jsdialogs: Text import: Fix separator btn position

test/Makefile.am, test/UnitWOPIHttpRedirect.cpp, test/UnitWOPIHttpRedirectLoop.cpp, test/WopiTestServer.hpp, wsd/Storage.cpp, wsd/Storage.hpp
With some loadbalancers it may happen that HTTP 302 Found
response with redirect location will appear.
=> HTTP 302 Found - redirrect support for getWOPIFileInfo

loleaflet/src/control/Control.DownloadProgress.js, loleaflet/src/map/Clipboard.js
... after 1aea12bed0313e4e54f82646c8a77556a68c2407, where I blindly
assumed that the _doAsyncDownload is only called from one file. The
affected code path was in loleaflet/src/control/Control.DownloadProgress.js,
and one place in loleaflet/src/map/Clipboard.js was wrong marking
a "POST" operation as "for clipboard".
Change-Id: I5bc1e68603ab8281716bcec6f8586524b6e01c95
=> Fix async copy to clipboard

loleaflet/src/core/Socket.js
Avoids the use of the words `restarted` and `refresh` in the same message
that might cause confusion for the user that quick scans the message:
`Server has been restarted. We have to refresh the page now.` and could
induce in error (the page is already refreshed).
Maintains factual of this message but uses instead the word `reachable`.
Change-Id: I294e36bd121e0f84f1b5373b29de78084b4707f2
=> Fix confusing wording in message when server is restarted

loleaflet/html/loleaflet.html.m4, loleaflet/src/control/Toolbar.js
Sadly I had to use a global variable to access the actual
contents of the Help>About window as being displayed in its key event
handler. If somebody can figure out the correct clean way to do it, be
my guest. (Look for the ExpertlyTrickForLOAbout.)
Change-Id: I88582e490d566d127d60226e045535e12c172e9c
* Resolves: # 
=> Show verbose feedback when toggling log level and Trace Event generation

kit/Watermark.hpp
The vectors are accessing the elements without pushing to the back.
Change-Id: Ia01b54f80b70173b994e776e05710e92248f0e23
=> Initialize the vectors instead of reserving

cypress_test/integration_tests/desktop/impress/table_operation_spec.js, loleaflet/src/layer/tile/TileLayer.TableOverlay.js
when calling hasTableSelection(). Do not depend on stray/duplicate
tableselection messages that can ensure a valid _currentTableData
member of TileLayer.
Change-Id: I957fdfc43c1435ca98eb204dcb3ec1e76b85ce89
* Resolves: # 
=> fix: avoid crash in non writer apps

loleaflet/src/control/Control.ContextMenu.js, loleaflet/src/control/Control.Tabs.js
Change-Id: If96461a5670ceeda035a77715cf24d419a0c2151
If there is only one sheet following options are enabled which doesnot make sense:
Delete Sheet
Show Sheet
Hide Sheet
Move Sheet Right/left
Proposed solution:
The above options should be disabled when there is only one sheet
=> loleaflet: show some options in context menu only when there are more then one sheets

loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Ia2aa29bf064fb2bb518b80a6d5fa5617a1334f2c
As we discovered when we implemented this for the menu bar, it is really important in some browsers - particularly Safari, but others - to have the right security context for 'paste' to be able to work when you click it.
In order to do that we need to have a hyperlink to '#' for the buttons in the notebookbar - at least, any of those that want to be able to cut/copy but particularly paste.
=> leaflet:NB:added hyperlink in copy,paste and cut button

kit/ChildSession.cpp
Avoids logging an ERR message about it.
Change-Id: If9e9627b3a10362e415edf2bfa6abf1f37c0b650
* Resolves: # 
=> Ignore conversion error from std::stoull for "busypopup"

loleaflet/src/core/Socket.js, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp
We ask for save as for the plain/text type documents
such as csv or txt. Notify other views about it so
they can follow one to the new document
Change-Id: I4cdcec6148d1064ad4e90ad9be2ce483c19a8eda
* Resolves: # 
=> Broadcast save-as to other views

loleaflet/src/control/Control.DownloadProgress.js, loleaflet/src/map/Clipboard.js
So that when user decided to not start download or copy to clipboard,
and moved to other things, the notification gets disposed.
Change-Id: Ifebd61594a87a37e83b0ec81b62c501792913a98
=> Stop clipboard copy operation on selection change

loleaflet/src/control/Control.JSDialog.js
We need to reposition popups when the content is already fully
visible (after some delay). This prevents us from popups partialy
outside window when initialy had no content and some updates
were performed after positioning.
=> jsdialog: position popups when already filled

common/Freemium.hpp
Change-Id: I5b55c2de4a2467503108e4172de84a27e207ba3c
=> use pragma instead of header guards in freemium header files

loleaflet/Makefile.am
Hopefully will reduce the amount of "Document has changed in storage"
irritation if following the progress of the script in a normal
browser. Make a fresh copy manually before running `make run` and
opening the document in your browser.
Change-Id: Icba6dd80fb202fce3f2ff288af0d1759bc7789be
* Resolves: # 
=> Make a fresh perf-test-edit.odt copy only when needed

cypress_test/integration_tests/desktop/calc/sheet_operation_spec.js, loleaflet/src/control/Control.Tabs.js
leaflet: show option hidden when only one sheet
Change-Id: I885e64ce328b7d90777ec14e7cb24fa492490386
=> cypress: fix sheetoperation spec

loleaflet/src/layer/tile/CanvasSectionContainer.ts
Now, one can add all sections at once.
addSection(sectionObject, bulkInsert = true) => call for them all.
addSection(sectionObject, bulkInsert = false) => call for the last section (shouldn't be a document object), so it will trigger renewAllSections function.
Change-Id: Ie83265b5a57c11bd828a980c1797d6bfa3d6e287
* Resolves: # 
=> Enabled bulk insert for sections.

loolwsd.xml.in
Many of the settings in loolwsd.xml that you might want to tweak this
or that way during development are set on the loolwsd command-line for
a "make run". Don't waste time on trying to set them in loolwsd.xml
and wondering why it has no effect. I just did that. Hopefully these
comments will avoid such in the future.
Change-Id: I896e9cb2830bf36c165842bff53f0e4e471599ae
* Resolves: # 
=> Add some comments for developers

cypress_test/integration_tests/common/mobile_helper.js, cypress_test/integration_tests/mobile/impress/annotation_spec.js, cypress_test/integration_tests/mobile/writer/delete_objects_spec.js, cypress_test/integration_tests/mobile/writer/shape_properties_spec.js, loleaflet/css/device-mobile.css, loleaflet/css/loleaflet.css, loleaflet/css/partsPreviewControl.css, loleaflet/css/sidebar.css, loleaflet/css/toolbar.css, loleaflet/html/loleaflet.html.m4, loleaflet/src/control/Control.LokDialog.js, loleaflet/src/control/Control.MobileWizard.js, loleaflet/src/control/Control.PartsPreview.js, loleaflet/src/control/Control.UIManager.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/ImpressTileLayer.js, loleaflet/src/map/Map.js
So, we no longer need to set positions of HTML elements using margins or absolute positioning or attributes like "left: 30px".
Tested on mobile, desktop, tablet views with & without notebookbar.
Change-Id: Ib301dfa8c06a9cf12acd33caf1b6a852a2faab20
* Resolves: # 
=> Move side bars into flex container.

wsd/ClientSession.cpp
During the save during shutdown we can get big invalidation
emissions, there is no point in re-rendering the view at that
stage; so skip it.
Change-Id: Ie85ef57648815a1872ca35dcb1bdfc9fa54e64c0
* Resolves: # 
=> wsd: don't re-render tiles while closing a session.

.git-hooks/pre-commit
This was copied from core.git, but it's not relevant for online.git.
Change-Id: I8b9c0c3039e55dee46f30dc1afc8276f7bbd55c9
=> git-hooks: pre-commit: clean up not needed tweak of the perl library path

loleaflet/js/ResizeObserverPolyfill.js
ResizeObserver is not defined for JSDOM as well
Better to check that not only for IE11.
Change-Id: Idb080f1a320c291dca71a73e76b8d754a76e1108
* Resolves: # 
=> Additional control for ResizeObserver for NodeJS tests

loleaflet/css/partsPreviewControl.css, loleaflet/html/loleaflet.html.m4
Set min-height property to prevent exceeding the available size.
slide-sorter: Set max-height to prevent over-sizing relative its parent.
Change-Id: Ib8c50bc9f6f6ac4311cefa3b0e016da728efe95b
* Resolves: # 
=> Main-document-content: Prevent over-sizing.

common/SigUtil.cpp, common/SigUtil.hpp, common/Util.hpp, kit/ChildSession.cpp, kit/ChildSession.hpp
Records the uno commands from different instances of Child Session and
dumps the last 4 uno commands into the Crash log during a fatal crash
Signed-off-by: Gopi Krishna Menon <krishnagopi487.github@outlook.com>
Change-Id: I838f71769dc08df7076c040f3d72c15f7607e9d3
- [X ] Code is properly formatted
=> Log Last 4 Uno Commands During a Fatal Crash

loleaflet/src/layer/tile/CanvasSectionContainer.ts
User can pause drawing before adding multiple sections.
When resumeDrawing is called, reNewAllSections function will be called automatically.
Change-Id: Ie83265b5a57c11bd828a980c1797d6bfa3d6e287
* Resolves: # 
=> Adapt addSection function with pauseDrawing.

loleaflet/src/layer/tile/CanvasTileLayer.js
Thanks to cypress tests. It was being called in Impress document.
Change-Id: I4681486cdd0930429f824c5636a2becb26700ff6
* Resolves: # 
=> _refreshRowColumnHeaders: Function is calc-only.

kit/ChildSession.cpp
We cannot rely on wsd being slower than the kit - and the rename
happening before wsd / DocumentBroker gets to trying to access the
filename. fixes #2874.
Change-Id: Ie1e67cd059fb6a663048967c47759238c067172d
* Resolves: # 
=> Ensure that we get the file-name right before sending the save result.

loleaflet/src/control/Control.TopToolbar.js, loleaflet/src/control/Toolbar.js
This way both notebookbar and classic toolbar will have the select2
styling
Change-Id: I9b8294cb1c0308fcfeeed8f9e886e3075c2eb3a1
* Resolves: # 
=> moved initializing fontcombobox with select2 to Toolbar.js

g
In a scenario where onee has several parallel PRs, one needs to use
several local branches, and when updating PRs, *needs to provide PR
branch name explicitly* each time (my-PR-name-* in the example):
git checkout my-local-branch-1
<edit session>
git commit
./g review my-PR-name-1
git checkout my-local-branch-2
<edit session>
git commit
./g review my-PR-name-2
This changes the processing, so that when the user's local branch name
is different from the tracked branch name, it is treated as if user
used that name explicitly in a call:
git checkout -b my-local-branch-1 origin/master
git checkout -b my-local-branch-2 origin/co-6.4
<...>
git checkout my-local-branch-1
<edit session>
git commit
./g review # this uses "my-local-branch-1" as implicit second argument
git checkout my-local-branch-2 …
=> Use custom local branch name as explicit remote user branch name for PR

loleaflet/Makefile.am, loleaflet/test/bootstrap.js, loleaflet/test/load.js
now it's possible to pass parameters
typing_speed, typing_duration, single_view, node_inspect
also replaced the old perf-test with new-perf-test
Change-Id: I03f1f14db4ddd9afb9d4a9a60a87c135497db70c
* Resolves: # 
=> Parameters for perf-test

Makefile.am
Some of the folders we setup from the system are:
dr-xr-xr-x 1 michael users 2824 Jun  9 21:05 systemplate/usr/share/fonts/
before adjustment, and resist removal.
Change-Id: I8e5a96264b98d8091b205f7469bc46c401f47ab1
* Resolves: # 
=> systemplate: ensure we have write access to directories before cleaning.

kit/ChildSession.cpp, test/Makefile.am, test/UnitWOPIAsyncUpload_Close.cpp, test/UnitWOPIAsyncUpload_Modify.cpp, test/UnitWOPIAsyncUpload_ModifyClose.cpp, wsd/ClientSession.cpp, wsd/DocumentBroker.cpp
- wsd: test: correct logging of phase change
- wsd: test close-after-modify to confirm no data loss
- wsd: better logging of the document activity
- wsd: correctly update the modified flag
- wsd: track saving activity
- wsd: test: detect multiple uploads in test
- wsd: before closing save a copy to upload
=> Saving improvements

net/NetUtil.cpp, net/NetUtil.hpp, net/Socket.cpp, net/Socket.hpp, net/Ssl.cpp, net/Ssl.hpp, net/SslSocket.hpp, test/HttpRequestTests.cpp, test/UnitWOPIAsyncUpload_Modify.cpp, test/WopiTestServer.hpp, test/test.cpp, tools/WebSocketDump.cpp, wsd/LOOLWSD.cpp, wsd/Storage.cpp
- wsd: move isLocalhost to a common area 
- Revert "wsd: initialize SSL if enabled or termination is enabled" 
- wsd: support certificate verification 
- wsd: ssl certificate verification requirements 
- wsd: killpoco: cert verification 
- wsd: test: improve modify test 
- wsd: prevent recycling the listening port during tests
=> SSL Certificate Verification

loleaflet/src/map/handler/Map.Keyboard.js
We emit lots of 'keyup' events that don't match any keydown
event like this:
OUTGOING: textinput id=0 text=a
OUTGOING: textinput id=0 text=l
OUTGOING: key type=up char=0 key=517
OUTGOING: key type=up char=0 key=523
since we emit a textinput instead. So just emit events
when we have modifiers, or already sent an input event.
Change-Id: I0f86438d093497668bb5b749ff63ecd87d9b7636
* Resolves: # 
=> js: reduce keyup emission to allow event de-duplication.

loleaflet/src/control/Control.Notebookbar.js, loleaflet/src/control/Control.NotebookbarDraw.js
- when we receive any notification - mark notebookbar as initialized
- if we haven't received any information eg. in impress - warn
reduce importance of this from error to warn as it is not important
probably there is no widget which sends updates (correct for draw and
impress)
Change-Id: I88ae3a090014dd25e59e04993c0c244d8830435e
=> notebookbar: reduce importance of 'not initialized' message

net/HttpRequest.cpp
Given that "digit" is always less than 16, we can avoid the "- digit"
in the condition (because the division turns that into 0 anyway), making
it effectively constexpr.
Change-Id: Iaf9e53d3543f2237c00768f214114a02a4746020
=> http response: simplify the condition if the result would fit

net/HttpRequest.cpp
This is really a garbage in -> garbage out situation.
Change-Id: Ic1c33f44081f259e5cf5994ad901e1593fe8dfcf
=> http response: if the result doesn't fit, then consider that a fatal error

loleaflet/src/map/Clipboard.js, wsd/ClientSession.cpp
From our API description:
DisableCopy
Disables copying from the document in libreoffice online backend.
Pasting into the document would still be possible.
Change-Id: I1f7e272ad3b04208b534eff990fed895951b4751
=> Allow pasting into document even when DisableCopy is active

test/UnitTyping.cpp
Our JS code does not send 'textinput' messages with a 'type' parameter
either, so it is pointless to do it in a unit test.
(We still have code that checks for the 'type' parameter in received
'textinput' messages. That is pointless, too, and should be removed.)
Also, document what testWriterTyping() apparently is doing.
Change-Id: I4954379339f14e4a310a76788521001048d84e37
* Resolves: # 
=> Don't use the obsolete 'type' parameter in 'textinput' messages

test/UnitTyping.cpp
At least I didn't fully understand what the old code actually was
checking.
Also, use sizeof instead of magic numbers.
Change-Id: I01602a2e256b1fbe39793c9f1439e025461c5a72
* Resolves: # 
=> Check directly that the result is exactly what we expect

kit/Kit.cpp, net/Socket.cpp
Add profile zone around kitPoll function and SocketPoll constructor to
improve trace event generation
Signed-off-by: Gopi Krishna Menon <krishnagopi487.github@outlook.com>
Change-Id: Ia46e9add59a57935997649fe39861a8d851e1ff0
=> Add profilezone around kitPoll function and SocketPoll constructor

test/Makefile.am
if make is killed or interrupted during the execution
of their recipes, the target is not deleted.  So there is
an opportunity to check the logs, why are taking to long
time to finish the test.
Change-Id: I6e8176a48ff721ecb2b2efc01b1f149907dd359b
=> test: fix deleting log files

common/MessageQueue.hpp, test/UnitTyping.cpp
When adding a freshly arrived textinput message to the queue, check if
there is any outstanding one queued, and if so, remove it, and prefix
its text text to the text in the fresh message.
Change-Id: I712eebfb10d410bb424157c8df46b2848a236d88
* Resolves: # 
=> Merge textinput and removetextcontext messages when possible

net/SslSocket.hpp
For some servers we receive failure with HTTP 403 Forbidden in WOPI::CheckFileInfo
"Reason: The client software did not provide a hostname using Server
Name Indication (SNI), which is required to access this server"
fixes #2771 : https://github.com/CollaboraOnline/online/issues/2771
fixes #2752 : https://github.com/CollaboraOnline/online/issues/2752
=> ssl: setup hostname for SNI

test/run_unit.sh.in
If the Forkit process dies very early due
to Fatal error (i.e. No capabilities ),
the WSD process will wait a long time for children.
In this case the ForKit will never recover,
so exit fail the unit test (high probability).
Change-Id: I402c84c1e11c971d546536090b5962c741204588
=> test: run test with capabilities disabled

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp, wsd/Storage.hpp
WIP, should be merged on top of https://github.com/CollaboraOnline/online/pull/2930
When async save was started but we want to stop DocumentBroker we shouldn't kill the socket which listens to save result.
Because when we kill socket we will destroy DocumentBroker before saving is completed, this allows for a minimal time to connect again to the document and receive old content from the WOPI storage.
When we wait for async save result we will keep DocumentBroker alive and next session can be connected and receive correct content.
=> Wait for async save result on DocumentBroker stop

loleaflet/src/core/Socket.js, wsd/DocumentBroker.cpp
This way it will reload the document without getting
additional errors like "this is embaressing.."
and not timed out on large files due to retrying for a limited
time.
Change-Id: Ied341200ca21e1b7243daaf62813bc9ed69fecd3
* Resolves: # 
=> renamefile: Respond with reload instead

test/integration-http-server.cpp
So it can be easy to analyze the backtrace of the
failing assertion.
Change-Id: Icdcf55b1404f858eba1d499bd65719a0e2da21db
=> test: adjust "assertHTTPFilesExist" function.

kit/ChildSession.cpp
Change-Id: I1f7194edb833d8569ca7bd87cadd903deb84ef0e
* Resolves: # 
=> Print a header in front of the list of last UNO commands

kit/Kit.cpp, net/WebSocketHandler.hpp
Sometimes multiple messages are processed in a single iteration
at socket level. This happens in WebSocketHandler and when draining
Document queue.Just covered these cases.
Change-Id: Ifa46f5d484b67015cca64008b2c89426cc839e64
Reviewed-on: https://gerrit.libreoffice.org/c/online/+/99387
Tested-by: Jenkins
Tested-by: Gabriel Masei <gabriel.masei@1and1.ro>
Reviewed-by: Michael Meeks <michael.meeks@collabora.com>
Reviewed-by: Gabriel Masei <gabriel.masei@1and1.ro>
* Resolves: # 
=> kit: disable parallel processing at higher levels

loleaflet/src/map/handler/Map.Feedback.js
- Do not bother user with multiple dialog at the loading time
- Add additional timer after the welcome dialog is closed before
calling feedback again
Change-Id: Ib432e13205b1b3bef4dfa7ed8752a6561a4f0466
=> Feedback: Do now show dialog if welcome is present

loleaflet/src/core/Socket.js, loleaflet/src/errormessages.js, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp
- leaflet: explanatory message when loading fails while unloading
- wsd: allow new views while unloading
- wsd: log discovery.xml response at trace level
=> Support aborting unloading

loleaflet/src/core/Socket.js
We need to make sure that the message slurping processes the events
first, because there could have been a message like "close: idle" from
the server.
Without this, we'd immediately reconnect, because the "close: idle" was
not processed yet by the message slurping.
Co-author: Jan Holesovsky <kendy@collabora.com>
Change-Id: Id3e27164fb00de69f661ba7580075b36100a03c1
=> loleaflet: Process the reconnection in _onSocketClose in a timeout.

loleaflet/src/control/Control.Tabs.js, loleaflet/src/unocommands.js
Change-Id: Iea110a5c3e66e8ae1693b42bfedce81d19c6247f
=> loleaflet: use different name for 'Move or Copy Sheet' option when there is only one sheet

loleaflet/css/btns.css, loleaflet/css/jsdialogs.css
before fix buttons in jsdialogs were positioned vertically (ok and cancel buttons)
=> jsdialog: fix buttons alignment

net/SslSocket.hpp
=> Don't try to set empty hostname for SNI

net/HttpRequest.cpp, test/HttpWhiteBoxTests.cpp
* Resolves: #2846 
Not having reason phrase in the http status is not an error.
=> wsd: http: reason phrase is optional

net/ServerSocket.hpp, net/Socket.cpp
This required reverting 0dd30ba28ffd4482ea21e2495862e7979f0a4137, it was silly of me to push it so early. Sorry for that.
=> Remove non-abstract unix socket files on shutdown.

wsd/DocumentBroker.cpp
This log entry can be misleading on its own.
When shutting down, the modified flag is not reset,
and that in itself is not a cause for concern.
So this log entry is seen much more often than we
expect. If we truely fail to save/upload, there
will be other errors that will be the tell-tale
signs of a serious issue. So it's reasonable to
downgrade this error to a warning (and watch for
other errors).
Change-Id: Ic879c3fbac887ed5b64bdd1a31aa38bcfd863850
=> wsd: log stopping-although-modified as warning

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/test/load.js
a) removed event firing for catching tile messages
- injected socket onmessage function and made a middleware instead
- the middleware can catch any socket messages
b) Replaced "fake sleep" and while loop for keystroke messages
with setInterval function.
c) disabled processing incoming messages for multiple views
- Optimizing the front end for JSDOM seems to be hopeless.
the benchmark numbers for JSDOM and Real browser does not match
and most of the time are unrelevant. In most cases where JSDOM is
slower take almost no time for Real browser. These cases will not
make real experience smoother if somehow fixed. In addition,
rendering hundereds of socket messages makes nodejs use 100% of the cpu
and benchmarking the loolwsd or loolforkit properly becomes impossible
since nodejs cannnot …
=> perf-test: Performance updates

loleaflet/css/notebookbar.css
Some bigtoolitem icons (namely About) were being skewed and others
were being set at a smaller size to what they were supposed to have.
Fix it by adding height value
Change-Id: I5ec375358e9dcf46a6b8b17570bea78963e188c8
=> Notebookbar: Fix bigtoolitem size and keep ratio

kit/ChildSession.cpp
It returns a temporary.
Change-Id: I5a9df90a4e7dda05cc387e5dc11842ea8e237504
=> kit: improve StringVector usage in ChildSession::getClipboard()

loleaflet/src/control/Control.Freemium.js
IE11: does not support 'includes'
Change-Id: I4b90c3f540daaa03f4ace5a6f42b5776884c3abe
* Resolves: # 
=> freemium: fixed the TypeError for IE11

loleaflet/css/leaflet.css, loleaflet/css/loleaflet.css, loleaflet/css/notebookbar.css
- Fixes map z-index so annotation can be have higher z-index
- Now map and due to the latest changes introduced in:
8ca57fad3344f6da1b42158944bf9903f0ac528b we cannot use
container's border-top as our bezel divider
- Elements such as annotation need to go under
- So Fix toolbar-wrapper to use bottom border
- Notebookbar: Fix toolbar-wrapper background-Color which
was being set as transparent and thus elements passing under
were being visible
- Ruler: fix cropped ruler (was not going full width)
Change-Id: I8778619da43c51d1994dbb12d1112d4f1d42ff43
=> Synchronize map with TilesSection: Fix CSS

loleaflet/src/core/Socket.js
console.logException is used only for debugging
purposes
Change-Id: I7d761d0cd7b55c820b7b7dea4079dae0f6d09043
=> loleaflet: restore log2 function

loleaflet/css/loleaflet.css, loleaflet/src/layer/marker/TextInput.js, loleaflet/src/layer/tile/AutoFillMarkerSection.ts, loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/GridLayer.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/layer/vector/CPath.ts, loleaflet/src/layer/vector/CRectangle.ts, loleaflet/src/layer/vector/CanvasOverlay.ts, loleaflet/src/map/handler/Map.Keyboard.js
* Resolves: # 
Improved styling of cell cursor/selection autofill-marker.
1. Improve styling of cursor/selection/autofill-marker
* Autofillmaker should follow the grid (not go overboard as it is now)
* Add one white border to the selection (but very discreet, 1 pixel)
* The autofillmarker, selected outline and cell cursor should share the
same color. That color should come from css var (so it fits better
with surrounding elements, cell headers etc).
Caveats:
* Autofill-marker in mobile devices was positioned and sized
differently. With this change, they stay the same except for the color
and the contrast border. Styling this needs more thought.
2. Separate the styling of cell and text selections
We now have a very specific design for cell-area selections which …
=> Improve cell cursor/selection/autofill-marker style

loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/ScrollSection.ts, loleaflet/src/layer/tile/TileLayer.js
* Resolves: # 
Fixes view area jump (looks like a flicker) during document load in Calc.
Note that without the fix, the view jump is apparent only if last edited cell in the sheet is not in a view containing A1. 
So try something like A250.
The root cause of the jump is that the initial view area always the default (ie. starting cell A1) unless the client gets a cell cursor message and it adjusts the view such that it contains it. In this patch set we request for cell cursor early on during CalcTileLayer initialization. We avoid any canvas painting (except for clearing of the canvas during resizes) till we get the first cell cursor.
=> Fix view jump flicker on docload in Calc (co-6-4)

loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: Ic66ed15c90c1f012138a29b81ee0a8540667acf5
* Resolves: #2992 
=> loleaflet: fix: scroll buttons still appear when toolbar is narrower then window

common/Log.hpp, test/TileCacheTests.cpp
This can happen on an assertion failure, and causes noise while looking
for real memory errors.
Also disable an unstable test, it's not clear that it passes depending
on how loaded the machine is (just increasing timeouts doesn't seem to
help).
Change-Id: I049bd0a06f41e2d43702ec12a2c35944bc5200d8
=> log: avoid logging after shutdown on all log levels

net/HttpRequest.hpp
HA Proxy doesn't tolerate this very happily cf.
https: //serverfault.com/questions/502443/ignore-port-numbers-in-haproxy-host-header-matches/502630
Change-Id: Id285f8acd0e168a734cabd9eccc4a01fe323ab84
* Resolves: # 
=> Host: header don't append port for standard ports.

loleaflet/src/control/Parts.js
'updateparts' event must be fired only after requesting new part to
core, else both tiles and sheet-geometry will be wrong after the user
triggers sheet switch.
The move of 'updateparts' firing code was done in
commit 6da00622d08060b45452f0e6cbbf6077b117503b
Fix PDF view: Switching pages using buttons
but that move became unnecessary after the next PDF related commit
commit 9ca5d68ba21fbaf94049f85b1730390573b80184
Make page buttons scrollby view height instead instead of switching the page directly
Change-Id: Ib806e31965ecada5305f4ea647f1de6236b27486
* Resolves: # 
=> fix calc's incorrect sheet switch

kit/ChildSession.cpp, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TileLayer.js
* Resolves: # 
* Target version: co64
Introduce new callback for calc document background color.
=> New callback for calc document background color (co64)

loleaflet/src/core/Socket.js, loleaflet/src/layer/marker/TextInput.js, loleaflet/src/main.js, loleaflet/src/map/Clipboard.js
* Resolves:  [#2685](https://github.com/CollaboraOnline/online/issues/2685)
Removes any code referencing isInternetExplorer, excluding a popup in `/loleaflet/src/main.js
`
In `Clipboard.js` also inlines `compatRemoveNode` as it only exists for to handle IE.
=> Remove isInternetExplorer code paths

loleaflet/src/layer/tile/TileLayer.TableOverlay.js
Change-Id: Idcf62a2f787d098b1fcc78b57b4d07f9de685b31
Problem:
First row/column are treated specially as headings,
that's why heading are not sent through the entry.
Due to that if table has only single column or row,
entry will be empty and marker will never appear
=> leaflet: show table markers when table has no entry

net/Socket.cpp, net/Socket.hpp
We don't want to always start with the most recently added socket.
Change-Id: Ic4b4bf6c19c5d119e6e6f9b398789a4c77b47a10
* Resolves: # 
=> Handle poll results in SocketPoll in a round-robin order

loleaflet/src/control/Control.LokDialog.js
Change-Id: Ibea42d1fa9c3c7fe8abc6b5efdb5dc93cab1a491
=> loleaflet: fix: Calc: Dragging scrollbar and releasing button over formula bar keeps drag mode active

common/RenderTiles.hpp, ios/Mobile/AppDelegate.mm, ios/Mobile/DocumentBrowserViewController.mm, ios/Mobile/DocumentViewController.mm, kit/ChildSession.cpp
Remove the app's copy of the document after core has saved it and we
have stored the edited version at its real location.
Remove possible leftover tile bitmaps when the app starts.
Change-Id: Ibc41be38c2cfb689c532640d148116bc06a248ab
* Resolves: # 
=> Remove more leftover files taking space in the iOS app

tools/Replay.hpp
There is one EndSession record for each session that edited the same
document. That is not an error.
Change-Id: I9042411ad465fe07a8f88a29923f0dc051c755aa
* Resolves: # 
=> Bin misleading ERROR message

common/RenderTiles.hpp, ios/Mobile/AppDelegate.mm, ios/Mobile/DocumentBrowserViewController.mm, ios/Mobile/DocumentViewController.mm, kit/ChildSession.cpp
Remove the app's copy of the document after core has saved it and we
have stored the edited version at its real location.
Remove possible leftover tile bitmaps when the app starts.
Change-Id: Ibc41be38c2cfb689c532640d148116bc06a248ab
* Resolves: # 
=> Remove more leftover files taking space on the device in the iOS app

loleaflet/src/layer/tile/CanvasTileLayer.js
though cursor update is still required for the mobile on resize
because when the virtual keyboard appears cursor should be scrolled into viewing area
for more details: 3f04cd81835ac7e4af056363f68ba41c72d14a29
Change-Id: I08b54008d232d8a8d5277cf2acb5003f4c2a551a
=> canvas: avoid cursor update on window resize

common/MobileApp.cpp, common/MobileApp.hpp, common/RenderTiles.hpp, ios/Mobile/CODocument.mm, ios/Mobile/DocumentViewController.mm, kit/ChildSession.cpp, kit/Kit.cpp
Normally (ideally), tiles (.bmp files) are removed as soon as the JS
has displayed them. But occasionally something goes wrong and they are
left behind. (For instance, it seems to happen if the user closes the
document immediately when it shows up.)
Do not leave them on disk until the app starts the next time.
Change-Id: I0c764280a69a16ad3b7b67c329832fd5331c2e1e
* Resolves: # 
=> Remove leftover tiles in the iOS app already when the document is closed

loleaflet/src/control/Control.AlertDialog.js
closes #3152
Signed-off-by: Alexandru Vlăduţu alexandru.vladutu@1and1.ro
Change-Id: Ie1125f6f25f1264cbab18fd39b15a1e50ed03781
* Resolves: # 
Adds 'Edit' button to dialog that opens when clicking a link. The new edit button will open the edit link widget. Screenshots attached to feature request which this PR implements.
=> loleaflet: add edit option in link dialog

kit/ChildSession.cpp
When building against core.git master:
kit/ChildSession.cpp:2668:13: error: enumeration value 'LOK_CALLBACK_SC_FOLLOW_JUMP' not handled in switch [-Werror,-Wswitch]
It's not clear how we want to handle this in Online, so have a default
label in debug builds as well.
Change-Id: Ia0b1cef33e8a5a7fbc1518586ea1e3bb13aa5f22
=> kit: fix build

loleaflet/src/control/Control.MobileTopBar.js
Partly revert changes from c7b76b164f2b83f6355bb53bff13c55a84d0b2a6
By adding back fullscreen button to the top of the mobile bar.
Reason: I'm all in favour for consistency across document types but
we need to think twice about what the user uses in each specific app
(specially on mobile where forcing additional steps on frequent actions
can be really detrimental for the UX)
In this case it makes sense to display an additional top bar icon on
presentation documents where, probably, the user will not be using the
phone to create a whole presentation from scratch but rather to:
- review (and possibly do small adjustments)
- Practice
- And maybe adding comments
For this is quite important to have the fullscreen button up-front
Note: This commit also restores the ability the fullscreen button …
=> Mobile: Impress: Fullscreen: Promote to topbar btn

common/MobileApp.cpp, common/MobileApp.hpp, common/RenderTiles.hpp, ios/Mobile/AppDelegate.mm, ios/Mobile/DocumentViewController.mm, loleaflet/src/core/Socket.js
We don't want leaking tiles to take up valuable space on the device.
Not even just while a document is open.
Change-Id: I761c2bb2ab121ee76b5535e96bd5702d0fce6856
* Resolves: # 
=> Stop using .bmp files for tiles on iOS

loleaflet/html/loleaflet.html.m4, loleaflet/src/map/handler/Map.WOPI.js, wsd/FileServer.cpp
External apps load loolwsd inside the iframe
and loolwsd makes postmessages to parent window.
We receive the postMessageOrigin from checkfileInfo yet
we still send some messages before we even go to the WOPI Api
in that case, if parent window runs on a different domain, we
end up with CORS blocking by the browser. To prevent that we can
allow safely passing the origin inside the first post like access_token
and sanitize it with Poco::URI::encode.
Change-Id: I5724f2d103603a599d45b7f61da81fb30834ef0e
* Resolves: # 
=> Implemented an option to pass PostMessageOrigin

common/Util.cpp, common/Util.hpp, loleaflet/html/loleaflet.html.m4, loleaflet/js/global.js, loleaflet/src/control/Toolbar.js, loleaflet/src/core/LOUtil.js, loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/TileLayer.js, loleaflet/src/main.js, loleaflet/src/map/Clipboard.js, loleaflet/src/map/Map.js, loleaflet/src/map/handler/Map.FileInserter.js, loolwsd.xml.in, net/HttpRequest.cpp, test/HttpRequestTests.cpp, test/WhiteBoxTests.cpp, wsd/FileServer.cpp, wsd/LOOLWSD.cpp, wsd/RequestDetails.cpp, wsd/RequestDetails.hpp
This resolves #3086 and #3084.
- wsd: hexifying helpers and tests
- wsd: hexified URL support
- leaflet: move url manipulation to helper
- leaflet: support hexifying the body of the lool URI
- leaflet: replicate options.webserver in window.webserver
- leaflet: move map.options.server to window.host
- leaflet: move map.options.webserver to window.webserver
- leaflet: move map.options.serviceRoot to window.serviceRoot
- leaflet: makeURL -> makeHttpUrl
- leaflet: makeWsUrl
- wsd: configuration setting to control embedded-url hexifying
- wsd: throw when an invalid URL is used to create an http session
- leaflet: move wopiSrc into window and central URL maker
- wsd: improved dehexifying of URLs
- leaflet: centralize wopiSrc URL forming
=> Hexify URLs

ios/Mobile/AppDelegate.mm
Just clean out the whole tmp folder.
This gets rid of copies of edited documents left behind if the app is
killed (or crashes) while editing a document. It also gets rid of
files that NSS loves to leave around. Plus empty folders that are left
even when the app dies normally, i.e. while it isn't editing any
document.
Change-Id: If1caf8ace666eafc58df981d792f8fbfda8f9ff4
* Resolves: # 
=> Remove leftover temp files harder in the iOS app when it starts

ios/Mobile/Info.plist.in
Change-Id: I6467d8f9113fb1a25d9ea4301b37709d5a0e9762
* Resolves: # 
=> Bump Xcode internal version to 6.4.12 as 6.4.11 was released

loleaflet/src/control/Control.Menubar.js
This reverts commit 2739dfe44ca4063802044c8a0d6cd0e1dc1bfb11.
PDF view needs Insert menu to be able to insert comments.
Change-Id: I475aa95974d97fce6efb6b2bcffc997170adb255
=> Revert "Menubar: Do not allow Insert menu on readonly mode"

loleaflet/js/w2ui-1.5.rc1.js
loleaflet:  when user select existing color in colorPicker it comes on first position in recentRow
Change-Id: I200789fc5aa9cd5a6fc8a0bc311cbe71dde33e42
=> loleaflet: added local storage to recent and custom color in color pick

loleaflet/src/layer/tile/CommentSection.ts
* Resolves: # 
Fix slow doc loading that has lots of comments by avoiding eager importing of each comment at document load. Instead setup each comment only when it is necessary.
=> fix slow doc loading that has lots of comments [co-6-4]

common/Util.cpp, common/Util.hpp, loleaflet/html/loleaflet.html.m4, loleaflet/js/global.js, loleaflet/src/control/Toolbar.js, loleaflet/src/core/LOUtil.js, loleaflet/src/core/Socket.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/main.js, loleaflet/src/map/Clipboard.js, loleaflet/src/map/Map.js, loleaflet/src/map/handler/Map.FileInserter.js, loolwsd.xml.in, net/HttpRequest.cpp, test/HttpRequestTests.cpp, test/WhiteBoxTests.cpp, wsd/FileServer.cpp, wsd/LOOLWSD.cpp, wsd/RequestDetails.cpp, wsd/RequestDetails.hpp
- wsd: hexifying helpers and tests
- wsd: hexified URL support
- leaflet: move url manipulation to helper
- leaflet: support hexifying the body of the lool URI
- leaflet: replicate options.webserver in window.webserver
- leaflet: move map.options.server to window.host
- leaflet: move map.options.webserver to window.webserver
- leaflet: move map.options.serviceRoot to window.serviceRoot
- leaflet: makeURL -> makeHttpUrl
- leaflet: makeWsUrl
- wsd: configuration setting to control embedded-url hexifying
- wsd: throw when an invalid URL is used to create an http session
- leaflet: move wopiSrc into window and central URL maker
- wsd: improved dehexifying of URLs
- leaflet: centralize wopiSrc URL forming
=> URL Hex-Encoding

test/WhiteBoxTests.cpp, test/lokassert.hpp
test/lokassert.hpp:16:22: note: 'operator<<' should be declared prior to the call site
Change-Id: I7533490e64b1181b3349d0966b42eba4dcc88f05
* Resolves: # 
=> Compiler with recent cppunit.

test/UnitConvert.cpp, wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp, wsd/Storage.cpp, wsd/Storage.hpp
We now download the convert-to files into the
child-root/tmp directory and then move it into
the jail that will convert it. This way ownership
and cleanup become contained within our child-root
and jail subsystems. This reduces the chances of
leaking convert-to files and simplifies the design.
In addition, we avoid an extra file copy and improve
the security of the convert-to API.
(cherry picked from commit fad4222a2a91785e714df7ffad1ffd4ddb8f4142)
Change-Id: I450c24d0d0dc0da447c8072b0701c3b48d07c81b
=> wsd: move convert-to docs into the jail

android/lib/src/main/cpp/CMakeLists.txt.in
We had bug in android v7a release builds.
Due to high optimization app was not working correctly:
- formula bar was not initialized
- mobile-wizard didn't work
- typing into cells was not possible
- no blinking cursor
- in general editing didn't work
looks like webview -> native code - path was not working
but native code -> webview - path was working because I was able to see tiles after loading document
=> android: use lower clang optimization for release build

loleaflet/src/layer/tile/CanvasTileLayer.js
when we don't receive background color we need to assume we want gridlines.
In snapshot android builds gridline was missing.
=> android: show gridlines if background color not set

cypress_test/integration_tests/common/calc_helper.js, cypress_test/integration_tests/mobile/calc/formulabar_spec.js, cypress_test/integration_tests/mobile/impress/impress_focus_spec.js, cypress_test/integration_tests/mobile/writer/track_changes_spec.js, loleaflet/css/device-mobile.css, loleaflet/css/loleaflet.css, loleaflet/src/layer/tile/CanvasSectionContainer.ts
- Remove negative margins (no need for that anymore) and instead use
the ideal height values from the get go
- Also Remove parent's height rule (better to follow children's value)
- Remove rules that are never applied (since they are always superseded
by others)
- Align addressInput to left column header
- addressInput: Use the same text alignment as used in column header
- Set the addressInput border color to the same color as in formula
input field
Change-Id: If2ed681e408fb12dadc33ed47e3c68d8237324f9
=> Calc, mobile: fixed formula bar size (hide it on readonly)

loleaflet/admin/src/AdminSocketBase.js, loleaflet/js/ResizeObserverPolyfill.js, loleaflet/js/global.js, loleaflet/src/control/Control.LokDialog.js, loleaflet/src/control/Control.Menubar.js, loleaflet/src/core/Socket.js, loleaflet/src/layer/marker/Cursor.ts, loleaflet/src/map/Clipboard.js
* Resolves: [#2686](https://github.com/CollaboraOnline/online/issues/2686)
Removes legacy code supporting internet explorer, including polyfills and various other conditionals for IE.
Side note: I branched off the wrong branch so commits upto [Make IE warning translateable](https://github.com/CollaboraOnline/online/commit/81d47cfcfba9fbf31704de1279596466f73e1c41) were already merged in [#3101](https://github.com/CollaboraOnline/online/pull/3101)
=> Remove ie11 polyfills conditionals

loleaflet/src/map/handler/Map.WOPI.js
In some cases, the integration needs to paste the data directly to the
document, outside of our mechanism that detects whether we should use
the internal paste, or not.
Change-Id: I5e5de09a990ed68451af34dd208a81391a0e9cfa
* Resolves: # 
=> Action_Paste postMessage to work around the pasting mechanism.

loleaflet/src/layer/tile/CanvasTileLayer.js
example:
1. open spreadsheet, let's say you see 20 rows
2. doubleclick on 19th row to edit cell
before: cursor was under the keyboard
after: cursor is visible in the center of the visible area
=> mobile: keep cursor visible when keyboard pops up

android/lib/src/main/cpp/CMakeLists.txt.in, common/Unit.cpp, common/Unit.hpp
On android we had issue with not working release builds
(worked when optimization flag -O0 was used for Unit.cpp).
Global which stored instance of UnitBase subtype was returned
after cast to a choosen subtype. Unfortunately in case when
android didn't work UnitWSD was returned in UnitKit::get() !
Thich patch makes us sure we don't cast to not-correct type.
=> android fix: use correct instance for Unit classes getter

loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/map/handler/Map.TouchGesture.js
on mobile when keyboard is shown and user starts panning
keyboard shouldn't be hidden - it caused view to flicker
and keyboard was shown after short time again
=> mobile: don't trigger keyboard hiding when panning

loleaflet/src/core/Socket.js
When a document is reconnecting, it shows an empty dialog.
Change-Id: I00b8d47b2fee67175d2e2936d93e121b10c38389
=> loleaflet: avoid creating an empty dialog

kubernetes/helm/collabora-online/templates/ingress.yaml
Without this change I get 404 since host name is not set properly
=> Fix helm host binding to path in ingress.yaml

wsd/AdminModel.cpp
Change-Id: I9f9523336ddcbe24906787cfc3210f3471768ea8
* Resolves: # 
We saw this backtrace in logs:
```
wsd-10294-10397 2021-09-20 08:38:39.226851 [ admin ] SIG   Fatal signal received: SIGFPE
Backtrace pid: 10294 - wsd 6.4.12snapshot c1e85d9:
/usr/bin/loolwsd
SigUtil::dumpBacktrace()
./common/SigUtil.cpp:276
/usr/bin/loolwsd
handleFatalSignal
./common/SigUtil.cpp:255
/lib/x86_64-linux-gnu/libpthread.so.0
__restore_rt
??:?
/usr/bin/loolwsd
Document::setLastJiffies(unsigned long)
./wsd/AdminModel.cpp:154
/usr/bin/loolwsd
AdminModel::getKitsJiffies()
/usr/include/c++/7/bits/stl_tree.h:287
/usr/bin/loolwsd
Admin::getTotalCpuUsage()
./wsd/Admin.cpp:581
/usr/bin/loolwsd
Admin::pollingThread()
./wsd/Admin.cpp:437 …
```
=> prevent division by zero

loleaflet/css/mobilewizard.css
Change-Id: I7bfcb491f4c0d5d63d9f6def3aa3e18bb562d82f
From the desktop sidebar there are fixed positions defined
which has to be removed for mobile sidebar layout
=> Mobile Sidebar Layout fixes

loleaflet/src/core/Socket.js
Storing 'this' into a separate variable, typically called 'that,' is
needed only to enable it to be captured in a (callback) function that
you create in the scope of the 'that' variable. No callback or other
function is created inside the _slurpMessage function.
Change-Id: Iae2c6844a3dfb0ff486ee6762ee129893829f272
* Resolves: # 
=> No need to use a separate 'that' variable in the _slurpMessage function

loleaflet/css/device-mobile.css
- Not all elements were uniformly spaced out
- CSS was not targeting properly all elements
- Remove the need to add manually every element by id
every time we add a new one (or change it)
Change-Id: I6de930e351822c3477c26c8e6569c41975cee142
=> Mobile: actionbar items: Fix misalignment and css

loleaflet/css/notebookbar.css
Also avoid using flex (so smartmenu
to show and hide can still work)
Change-Id: I002b0fc9c5cc0a20f8fa4f0d72757c4b6ffd9697
=> Notebookbar: Set menu button without hardcoded px

Makefile.am, configure.ac
E: loolwsd: binary-or-shlib-defines-rpath usr/bin/loolconvert /snap/loolwsd/current/usr/lib
E: loolwsd: binary-or-shlib-defines-rpath usr/bin/loolconvert /opt/poco/lib
These RPATHs are not needed when we statically link poco, as we do with production
packages.
Change-Id: I5050fe1f1925937388793d443020fdc6a14ec97d
=> fix Lintian errors: binary-or-shlib-defines-rpath

configure.ac
Signed-off-by: NickWingate <nicholas.wingate03@gmail.com>
Change-Id: Ib7db15dfafa06c4ddcdef28a8831a91bb847a389
* Resolves: # 
Allows for a fourth version number to be specified for LOOLWSD in configure.ac.
=> Add fourth number to LOOLWSD versioning

loleaflet/src/map/handler/Map.TouchGesture.js
When we move marker we set IgnorePanning to true.
Unfortunately onUp handler is not called as Map.TouchGesture
overrides that event - so release variable there too.
=> mobile: reset IgnorePanning on touch end

wsd/LOOLWSD.cpp
wsd/LOOLWSD.cpp:1996:28: runtime error: member call on null pointer of type 'SocketPoll'
#0 0xcd8799 in LOOLWSD::doHousekeeping() wsd/LOOLWSD.cpp:1996:28
Change-Id: I3f5f8ad0d8a09a0f4244a32897c59d8a772a8d17
=> wsd: fix crash-on-shutdown in LOOLWSD::doHousekeeping()

tools/Stress.cpp
test/test.cpp and wsd/Storage.cpp has the same pattern.
Change-Id: Ic1dfbd3a5368eb9831bde9d77ea1bb813834d42b
=> stress: fix disable-ssl build

cypress_test/integration_tests/common/helper.js, cypress_test/integration_tests/common/impress_helper.js, cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
There is a problem with slides that does not fit into cypress tests
viewport.  Use the center of the visible area of the svg to
click/dblclick else clicking on the true center the event will not end
up in the svg. For example the click event could hit the slide
sorter(empty space in this case) or the invisible area outside the
viewport.
Change-Id: Iefa73f56b67be0b4c251921aa91404dbbfbed671
* Resolves: # 
=> cypress: restore shape text alignment test

common/SigUtil.cpp
Assuming that the intention is to output a pair of strings on start and
a pair of string on finish.
Change-Id: I1ab3b03c353a8d0875e2fee451ca34965fc3038e
=> common: fix leftover debug output

loleaflet/src/control/Control.JSDialogBuilder.js
=> jsdialog: don't use uno command for split button

loleaflet/src/layer/tile/CanvasTileLayer.js
When on mobile we hide keyboard it was visible that
content "under the keyboard" wasn't refreshed.
So be sure we draw everything after we detected resized view
and we did all the view position setup keeping cursor on the screen.
=> canvas: refresh when view size modified

loleaflet/src/core/Socket.js
Our permissions change callback modifies the UI so
first we have to create the UI when reconnecting.
This fixes the bug when on pdf renaming notebookbar appeared
above menubar.
=> First create UI then propagate permissions change

loleaflet/Makefile.am, loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/TilesSection.ts
* Zoom frames are drawn directly using tiles in tile-array or cache. 
* Draws grid before drawing tiles every zoom frame.
* A zoom level is chosen for every zoom-frame which has tiles that has maximum coverage for the zoom-frame area based on a score indicator. Tile of this zoom level is used to paint the frame.
* draw/pdf-zoomframe: needs special treatment of y coordinates
* adds SheetGeometry methods convert b/w core-pixels between zooms needed for Calc.
* Use sheetGeometry to transform the view coordinates for the chosen zoom-level for the frame. However this is not done for indivdual tiles. As a result there could be small alignment discrepancies between tiles and other stuff we draw using sheetGeometry such as grids and overlays.
* Desktop/Mobile Chrome …
=> Zoom-out animation improvements

loleaflet/css/notebookbar.css
Update bigtoolitem outdated CSS rule
Change-Id: Ie74c3a2d9226804eb9469cfa0d9cc25aa6bd2487
=> Notebookbar: Do not set items at 32 px

loleaflet/src/layer/tile/CanvasTileLayer.js
On mobile in hamburger menu > search when we focused input field
the focus was set to document so when user started typing we
received new characters in the document instead of input field.
Also it doesn't trigger showing the keyboard when 'next' button
is clicked in search dialog.
=> mobile: don't focus document when dialog opened

loleaflet/src/geometry/Bounds.ts, loleaflet/src/layer/tile/CalcTileLayer.js, loleaflet/src/layer/tile/CanvasTileLayer.js, loleaflet/src/layer/tile/CommentListSection.ts, loleaflet/src/layer/tile/CommentSection.ts
Fixes:
1. 'comment:' message will have cellPos in print-twips so convert that
to display twips before using it to draw.
2. use cursor-bounds in display twips for comments.
3. update display positions of comments whenever we receive commentPos
update from core.
4. Comment.updatePosition() must call both
convertRectanglesToCoreCoordinates() and setPositionAndSize().
Previously we called setPositionAndSize() only if the rectangle is
within view. This is not enough for the case of new comments added
via UI.
Conflicts:
loleaflet/src/geometry/Bounds.js
loleaflet/src/layer/tile/CommentListSection.ts
loleaflet/src/layer/tile/TileLayer.js
Change-Id: Ia21724c3fd60161387c9c0e819e019d63dfab43f
=> calc: fix comment addition - wrong coordinates [master]

cypress_test/Makefile.am
This is useful to run cypress with the preference
"capabilities" parameter of the developer.
Change-Id: I1f365ff7cc9790debef44d522c54d0f222680583
=> cypress: makefile: add capabilities parameter

common/Util.hpp, loleaflet/html/debug.html, wsd/FileServer.cpp, wsd/LOOLWSD.cpp
Change-Id: Ia5cfcc4c345ad062ac3e93b0e4f9bc6321781b63
*github issue: [https://github.com/CollaboraOnline/online/issues/110](url)
=> Local WOPI for debug builds

.gitignore, Makefile.am, common/FileUtil.hpp, loolwsd.xml.in, wsd/DocumentBroker.cpp, wsd/LOOLWSD.cpp, wsd/LOOLWSD.hpp, wsd/QuarantineUtil.cpp, wsd/QuarantineUtil.hpp
number of versions to maintain per file can be specified in loolwsd.xml
on exceeding specified quarantine size oldest file(s) is deleted
Change-Id: I3ca55b9ab29a82988f19fe0acd43e0fae2c2a423
=> quarantine: create hard links for quarantining when file is saved

wsd/ClientSession.cpp, wsd/ClientSession.hpp
Problem:
In ClientSession::postProcessCopyPayload() the serialized form of
clipboard's text/html is modified to inject meta origin and sent to the
client. When this data is sent back from client to the server(possibly a
different one) to set the core clipboard via "setclipboard", the parser
gets confused because the 'text/html' part/flavour's data length as
originally set by the core the first time does not agree with the actual
length due to the meta origin injection done previously. As a result the
parsed results of 'text/html' is only partial and possibly the parsing
of subsequent flavours are affected.
Fix:
Add a preprocess step for the payload for setclipboard to
remove the meta origin tag from the payload before parsing is done
(in ChildSession).
Signed-off-by: Dennis Francis …
=> clipboard: fix partial content read for text/html [master]

wsd/FileServer.cpp
Starting with 352d1d1f40c96cc76968ec657ad096ee36d7ca72 the CSP header contained two entries for img-src which caused the second to no longer take effect. This change brings back the rendering of avatars that may be loaded from external sources as provided by the WOPI integrator.
=> wsd: Only add one img-src rule to the CSP header

test/helpers.hpp
The sanitizers tinderbox regularly times out, and it's good to know if
the timeout value is an agressive one or the load is really that slow.
Change-Id: I2903481ea9efde68aca3f4ec00bd6e7e2d3b840a
=> test: log timeout limit when the document fails to load

wsd/DocumentBroker.cpp, wsd/DocumentBroker.hpp, wsd/LOOLWSD.cpp, wsd/RequestDetails.cpp, wsd/RequestDetails.hpp
Resolves #3085
- wsd: move sanitizeURI into RequestDetails
- wsd: move getDocKey into RequestDetails
=> Simplified DocKey processing in incoming requests

loleaflet/html/loleaflet.html.m4, loleaflet/js/global.js, loleaflet/src/core/Socket.js, loleaflet/src/main.js, loolwsd.xml.in, wsd/ClientSession.cpp, wsd/ClientSession.hpp, wsd/DocumentBroker.cpp, wsd/FileServer.cpp, wsd/RequestDetails.hpp, wsd/Storage.cpp, wsd/Storage.hpp
This remove reuse_cookies as a setting and feature
altogether. It was originally a workaround to aid
with authentication, prior to having access_token.
However, it proved to be less useful than originally
anticipated, primarily because cookies nowadays have
security restrictions in browsers. In addition to
the fact that access_token simply deprecated it.
While the documentation has also been updated,
tests still have reuse_cookies in input data.
This is intentional to ensure the code is
backwards compatible with any deployment that might
still pass URLs with reuse_cookies around.
Change-Id: If214b299b34a910face8cabc7c1335621990c85e
=> kill reuse_cookies

loolwsd.xml.in, wsd/LOOLWSD.cpp, wsd/QuarantineUtil.cpp
allow path specification for the quarantine directory
Change-Id: I407288db60fe5fbf0f6a9346175c3d4acfd35add
=> quarantine: keep quarantine off by default

loleaflet/src/core/Socket.js
Snackbar message for 'disconnected' or 'connected again'
shouldn't be shown if DisableInactiveMessages is set.
=> Don't show disconnected message when DisableInactiveMessages

loleaflet/src/layer/tile/CommentListSection.ts
Use trick to set 1px width for comment section so it doesn't
reserve space which can be used for document itself.
Thanks to that we don't see grey area on the right side when
zoom level is big enough so document is shown in a full width.
Position correctly HTML elements for comments so they are still visible.
=> Don't waste space for comment section

loleaflet/src/layer/tile/CommentListSection.ts
It prevents us from case when bubble is "higlighted"
but we cannot open comment preview.
=> Unselect comments when collapsing to bubbles

wsd/LOOLWSD.cpp
Do not check for incompatibility of trace level logging and user data anonymization
when cleaning up jails. The --cleanup switch of loolwsd is special and not used
normally in production.
Change-Id: If95c8c87c5fc2a278ee7d85e7e9089807a06602b
* Resolves: #2464 
=> fix build with --enable-anonymization #2464

wsd/FileServer.cpp
Should resolve the issue I've noticed back when testing https://github.com/CollaboraOnline/online/pull/3201 but when retesting it again now i think I've catched the issue there, but would appreciate some double checking if this really makes sense.
As far as I remember local static variables would be kept even when leaving the block so that seems to have caused that once the css/js links were initialized a change of the theme url parameter was not taking any effect.
=> Keep branding theme dynamic

kit/Kit.cpp
Remainder missing from 8083fb9cf73d2e8d125a328ff96108268eff1587
kit/Kit.cpp:171:14: error: 'OVERLAYFS_SUPER_MAGIC' was not declared in this scope
(cherry picked from commit 656eb310bb39ebd125f2ad6629c46625f1c00219)
Change-Id: I659f37e04eb3d494579e2b451d31d69ab6cb21f5
=> Fix Debian 8 / gcc-4.9 warnings (overlayfs part)

loleaflet/src/core/Socket.js
This caused an exception which prevented
the WSDServer member from updating after
a saveas operation that ended up on a
different server (in a load-balanced setup).
Change-Id: Ibf8f69d53dc3cb14fa004201660e3997ad5c298e
(cherry picked from commit 2b0180c4104ccf1a3e7da94cfc2d2f35c09d0684)
=> leaflet: correct map reference in socket

loolwsd.xml.in, wsd/FileServer.cpp
This allows people to perturb the etags for now, and in future the
URL sub-path to make it easier to develop with binaries where the
git hash doens't change.
Change-Id: I6082a71cde5d3a34cca29fa5858feaf6fdb7f4d6
* Resolves: # 
=> Add a version suffix configuration option.

configure.ac
To make it more clear that if you enable this in an existing build tree,
you'll get an outdated loolwsd binary, which is confusing.
Change-Id: Iaf6e747a9d7ac4262732c3df69bb5012bc7dc352
=> configure: extend --enable-fuzzers description

loleaflet/src/control/Control.TopToolbar.js, loleaflet/src/control/Toolbar.js
We dont need to use select2 for this since
we only use the simple values of each option
this way we spend 50% less time on creating the list
Change-Id: I470cfc7df1fa38246355acae9cb6cb0f4a1ab316
* Resolves: # 
=> Don't populate font size combobox with select2

loleaflet/css/jsdialogs.css, loleaflet/css/jssidebar.css
Many elements are too wide (as a group) which breakes the sidebar
layout:
- Spinfields and their labels (example cm) occupy too much width
- Many other elements are getting some with: max-content rules
from the geenric jsdialog.css file which is affecting and also
breaking the sidebar
Change-Id: Ie6c18e829cbe32319e77ce031521c6ccc7c6a5c9
=> JSsidebar: spinfields n edge elms: Fix alignments

loolwsd.xml.in, wsd/LOOLWSD.cpp
When enabled, the /lool/getMetrics endpoint will not require authentication.
By default authentication is required and this setting is set to "false".
Change-Id: I801130cf552eb14c231fcc0a0bdd39d9ebb6db7f
* Resolves: # 
=> Introduce security.enable_metrics_unauthenticated config item

cypress_test/integration_tests/desktop/writer/annotation_spec.js, loleaflet/src/layer/tile/CanvasSectionContainer.ts, loleaflet/src/layer/tile/CommentListSection.ts, loleaflet/src/layer/tile/CommentSection.ts, loleaflet/src/layer/tile/TilesSection.ts
- now we switch to minified mode also depending on document size
(not only window size) so when zoom is used we will also switch.
- no longer needed to use minSize property as comments section doesn't
change it's size
=> Simplify comments switching to bubbles

loleaflet/src/main.js, loleaflet/src/map/Map.js
Socket.js was failing in doc.connect with permission access in
a local debug build otherwise; possibly a JS init. ordering issue.
Change-Id: Iccb68a43ee300ae85498a3652d1a2f51ade3d115
* Resolves: # 
=> Ensure that options are always initialized.

loleaflet/src/layer/tile/CommentListSection.ts
Profiling points to updateReplyCount() as the bottleneck where it does
O(N^3) work where N is the number of comments. The innermost loop is
used to find the index of a comment-section in an array using its 'id'.
Turns out that flattening this loop to a < log(N) lookup via a js map
from id -> index pretty much cures the perceived 'slowness'. But we need
to ensure the correctness of the map by updating it whenever
'commentList' is mutated.
Time to load the document with 800 comments (arranged in 50 rows x 16
cols table):
Before the patch: 1min 31 sec
After the patch:  3.5 sec
After-load performance (comment popup/hide/scroll) with this patch is
similar to how it feels in co-6-4 which does not have this issue.
Change-Id: …
=> Fix slow loading/editing of sheet with ~800 comments [master]

test/helpers.hpp
The old code worked for "gcc -fsanitize=address", but the sanitizers
tinderbox builds with "clang -fsanitize=address".
Follow-up to commit f67b8901dd34e9c6d041a1d9797b861f95f90445 (test:
double the timeout in isDocumentLoaded() for sanitizers, 2021-11-03).
Change-Id: I4b802ec0d3d20516e3d58cc1c65d7e1422632b2b
=> test: fix sanitizers detection

wsd/AdminModel.cpp, wsd/AdminModel.hpp, wsd/metrics.txt
Change-Id: Ia65f0eeca8a9eccca17359bcb784b82ab6740317
* Resolves: # 
=> backport resource consuming docs metrics to 6.4

.gitpod-files/loolwsd-gitpod.xml, loolwsd.xml.in, wsd/FileServer.cpp, wsd/LOOLWSD.cpp
This means that we will no longer read loleaflet_html from old config files, which is
a good thing in 99.9% of the cases, because it contains a wrong default: loleaflet.html
For those integrators, who used this setting, we will offer an alternative slution later.
Change-Id: Ia82f812a5d3e522a9d33e7fcafcaa45130312d60
=> Remove config option loleaflet_html

browser/src/layer/tile/CommentListSection.ts
if comment is a bubble with opened preview and we zoom out
so bubbles will become full comments - we need to hide old popup
=> comments: when zoom is used close popup with preview

browser/css/notebookbar.css
The title of the selected tab is not crisp.
- Do not use colorful text shadows since it does not help with contrast
and in turn makes it blurry
- Instead use gray just as a way to
increase contrast and visually make it look like it's semi-bold (since
that font doesn't have anything in the middle between normal and 700)
- Also help user understand which tab is selected by increase the
contrast between the selected tab (rectangle) and the background via
box shadow
Resolves issue #3609
Change-Id: I4140a789df6418fed3484d96625bbbe3a99ab98f
=> NB: fix contrast n blurriness in the selected tab

wsd/LOOLWSD.cpp
Otherwise, the Integrator will not receive the document
disconnection on client side.
Change-Id: I2280d90df7b915838462f119e962b0420b5cf41f
=> wsd: rename 'docisdisconnected' -> 'docdisconnected'

browser/src/control/Control.MobileWizardBuilder.js
- setup standard responses for buttons in mobile-wizard
- by default hide close or cancel buttons in mobile-wizard
because it can be closed using 'v' button or by tap on document
=> jsdialog: mobile-wizard: handle standard buttons, hide close

browser/css/jsdialogs.css
On webkit based browsers spinfield controls (up an down) are hidden by
default and only appear on hover on top of that they look a bit wonky
(too small and not well positioned)
This improves that by sill using the same web native control while
styling those pseudo (vendor) classes. Extras:
- Mouse cursor change
- Different opacity values (so we retaining that visual difference
between hover and normal state)
- Increase size of those arrows
Change-Id: I07aacfc387cbf42efec1d302094bbfdfae4da4ed
=> Spinfield: improve input number (webkit)

test/TileCacheTests.cpp, wsd/DocumentBroker.cpp
When issuing tile render requests proactively (upon
getting invalidatetile event), if the registered
request has no subscriber, TileCache::saveTileAndNotify
simply drops the tiles!
New call sequence:
ClientSession::handleTileInvalidation
docBroker->handleTileCombinedRequest
tileCache().subscribeToTileRendering //< fix
The end result was that we rendered tiles only
to discard them, potentially leaving the clients with
stale tiles (unless they requested new tiles themselves).
If they do request them, we still benefit from the cached
copies of the internal requests we had issued (and dropped).
The issue is that we are wasting an opportunity for efficiency
and relying on the client to request tiles when we normally
push on invalidation, adding latency and being inconsistent.
Change-Id: …
=> wsd: always subscribe when proactively rendering tiles

browser/css/notebookbar.css, browser/src/control/Control.NotebookbarBuilder.js
The status for unsaved documents was lacking contrast and was solely
relying on color which can be a problem for some people (deuteranopia).
Improve this by:
- Increasing color contrast
- Adjusting hue rotation and make sure it only affects img elements
- Adding visual element (red dot) as an extra visual difference between
saved/unsaved status
- Use shadow to increase legibility between one and the other
- Instead of adding .savemodified class to img add it to its parent
(#save.unotoolbutton)
- So we can style more stuff (including the new ::after element)
without extra work
- So we can simplify all the rules for the 3 apps (unsaved status) to
one simple one
- Bonus: we are then sure everything is consistent on that front …
=> Nb: shortcuts: increase savemodified contrast n simplify CSS

test/Makefile.am, test/UnitWOPILock.cpp, test/WopiTestServer.hpp, wsd/DocumentBroker.cpp
If the last session is readonly on a document that
is already locked by a edit the file stays locked.
Change-Id: Ia48e73fffd7962da2e18acfa0f1259d237c72fa8
* Resolves: # 
=> Fix wopi-lock release problem

browser/css/jssidebar.css
This was affecting spreadsheet, presentation and drawing doc type
Make sure the alignment container does not contain too many
elements in one row.
- 1st normal alignment properties; 2nd left-to-right/left icons
- and then ensure the last parent goes into a new row
Change-Id: Iaa9f1fa12f577d5ae9dddb0597f060dd7f4019ae
=> JSsidebar: Fix alignment options, too many in one row

browser/css/cool.css
Remove bg image of a nonexistent asset introduced in
ba9feca725c357ab8a48de430263e10c78834821
Change-Id: I485afc3ff22a16d7bb212cb55ba8636fbfeea5a3
=> CSS: Remove typo (partly revert)

browser/html/cool.html.m4
Probably because we don't show the os-info? So use an empty paragraph
instead. Sad that the space for the logo doesn't expand automatically
to make space for it.
Change-Id: I429df1eee32fd454409731612b48f422529cece0
* Resolves: # 
=> For some reson we need more vertical space for the logo in the iOS app

wsd/TraceFile.hpp
This makes up most of the trace, and we have to simulate it anyway.
Change-Id: I3820e1d2281e696c119edb9ce989fda5ca4170e6
* Resolves: # 
=> trace: hard filter out tileprocessed.

browser/src/control/Control.JSDialog.js, browser/src/control/Control.Sidebar.js
When widget is updated and rrecreated - keep focus in the same space.
=> jsdialog: fixes#3615 keep focus in the updated input

tools/mount.cpp
On FreeBSD the mounting operations are allowed to be performed only by root
by default. When `loolwsd --cleanup` is called during normal compilation process,
it tries to unmount "jails" directory and spits EPERM-related errors.
Fix this by checking if the directory being unmounted is actually mounted and
return EINVAL in this case, just like Linux unmount2() does.
Change-Id: I0f72d265e33fb1e6129332bfa8e17e7d888d30b5
=> loolmount: Mimic the Linux behavior of umount2() on FreeBSD.

loleaflet/src/control/Control.UIManager.js, loleaflet/src/control/Toolbar.js, loleaflet/src/layer/tile/CommentListSection.ts
When we reopen document, 'show resolved comments' option state will be remembered.
=> comments: remember 'show resolved comments' state

browser/html/debug.html
Change-Id: I48d22e08f1f312033d49d315489f2404e48e4dd7
Make it a bit easier to test certain parameters by passing them to the actual frame and extracting just the file path search query parameter in debug.html
This will make appending `&ui_defaults=UIMode=notebookbar` to the existing debug.html url work again as it used before the rename:
`https://localhost:9980/browser/05638f9c2/debug.html?file_path=/home/jus/repos/collaboraonline/online/test/data/hello-world.ods&ui_defaults=UIMode=notebookbar`
=> Extract file_path from debug.html and pass other query parameters

docker/from-source/Debian
Set buster as source since is now oldstable
=> Fix debian dockerfile: explicitly set buster as source since is now oldstable

loleaflet/src/control/Toolbar.js
Insert hyperlink dialog was closed when we tried to copy link from
other window (after we losed focus and then focused Collabora Online
again).
=> Fixes #3647 : hyperlink dialog closed when window gets focus

browser/src/control/Control.AlertDialog.js
This changes commit eb387cc7b1e7d8389e138fa42372a38eea3a6148.
Edit dialog is not working, causes crashes and shows features
that doesn't work (linking to other documents in core).
Use dialog from online instead.
=> Use edit hyperlink dialog from online not core

tools/Tool.cpp
The vector is allocated on the stack in a for loop, so it's not valid to
refer to its address in the lambda that is executed on a thread. Rather
copy it.
Change-Id: Ie1f85d6efb27a4aa44b181f8d9f134e9fa41d508
=> coolconvert: fix stack-use-after-scope

browser/src/control/Control.JSDialogBuilder.js, browser/src/control/Control.MobileWizardBuilder.js
When opened mobile wizard with shape selected and then
selected some text and reopened mobile wizard - only
one panel was visible.
With new welded sidebar panels can be added to JSON but
not visible
=> mobile-wizard: count visible panels correctly

browser/src/main.js
Regression from f92e85dacce713ff019d5360c50e74703f9c9688
Ensure that options are always initialized.
Socket.js code expects that access_token and other params
are under map.options.docParams not map.options.options.docParams.
=> Fix reconnecting after rename

browser/css/cool.css, browser/css/menubar.css, browser/css/notebookbar.css, browser/css/toolbar.css, browser/html/cool.html.m4, browser/src/control/Control.Notebookbar.js, browser/src/control/Control.UserList.js
Taken over https://github.com/CollaboraOnline/online/pull/3529 for some further adjustments as discussed with @luka-nextcloud 
- As per discussion with @pedropintosilva the main navigation has been moved to a flex layout which makes positioning within it easier with the different elements that are part of it (main menu, last saved indicator, document title, avatarlist, closebutton)
- Avatar list implementation in the main navigation (from https://github.com/CollaboraOnline/online/pull/3529)
- Only show the new avatar list on desktop
- It might be worth to consider to also enable it on tablet mode
- The avatars shown in the header are limited to 3
=> Move avatar list to the header

browser/src/layer/tile/CommentListSection.ts
When comments were present in the document and collapsed into bubbles
- when user pressed "enter" above comment's target so paragraph position
was changed - bubble preview was shown.
After the patch we don't show preview in that case.
=> comments: don't show bubble preview on typing above

browser/css/cool.css
Make sure .cool-annotation-img does get inherit default padding
so both .cool-annotation-collapsed and .cool-annotation-img have the
same size
Change-Id: Ib0fd5cfd3b8eb124d39e3f7f36ad3e834b908b78
=> Comments: bubbles: avatars with different sizes

browser/css/cool.css, browser/src/layer/tile/CommentSection.ts
What was introduced in 263c8e8e8924a1f2abe3d59e3d2ebeae114a36f5
didn't work anymore and instead active comments (simply focuses,
not editing nor replying) were getting those css changes making them
auto width (result: super long width)
Fix that, by adding CSS classes to the container and making sure only
annotations with those textareas can be re-sizable
Change-Id: I109867505eba3aa4193d342a0a53d48dd772f807
=> Comments: make textarea re-sizable again

browser/src/control/Toolbar.js, cypress_test/integration_tests/mobile/calc/insertion_wizard_spec.js, cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js, cypress_test/integration_tests/mobile/writer/insert_object_spec.js
Related to:
https://github.com/CollaboraOnline/online/issues/3645
When we select text with multiple lines - line break
is ignered in the result. Paragraphs will be concatenated.
=> Hyperlink dialog: use textarea to handle line breaks

common/SigUtil.cpp, common/SigUtil.hpp, common/Util.hpp, configure.ac, kit/ChildSession.cpp, test/TileCacheTests.cpp, test/TileQueueTests.cpp, test/UnitSession.cpp, test/lokassert.hpp, wsd/COOLWSD.cpp
- wsd: test: safer assertions without side-effects
- wsd: test: more informative string assertion in TileQueueTests
- wsd: test: support logging passing test assertions
- wsd: Termination flag requires having ShutdownRequested
- wsd: fix 'potentially uninitialized' variables
- wsd: test: tollerate extra tiles on invalidation 
- wsd: test: killpoco web-sockets in testHandshake
=> Test improvements and minor fixups

browser/src/core/Socket.js
This fixes regression from:
https://github.com/CollaboraOnline/online/commit/293081a6317f551315c49055475c33bb0fc9792e
commit 293081a6317f551315c49055475c33bb0fc9792e
leaflet: centralize wopiSrc URL forming
global.wopiSrc is used to generate new URL but it is not updated
after we do save as action. It was always equal to initial value
which was set on the app load. Because of that we generated URL
with not matching file ids in the WOPISrc parameter.
WOPISrc parameter is used for load balancing so it was possible
that after save as the new session will be directed to the different
node.
=> Fix WOPISrc generation after save as

kit/ForKit.cpp
Core needs "notebookbar" ui mode string to activate
notebookbar widgets. If we pass "default" notebookbar
is not activated and style previews widget doesn't work.
followup for https://github.com/CollaboraOnline/online/commit/b4f588ea3cadad124f1c99718fb7f63e82c91953
=> notebookbar: activate in core when default ui mode

browser/css/jsdialogs.css, browser/css/notebookbar.css
Buttons with image and text stacked up plus arrow:
Some browsers (chrome/chromium) were not displaying the arrow correctly,
it was appearing as a gray block and also badly positioned.
This change fixes that.
Change-Id: I144aa39eb17361309683592928720986e8476f36
=> NB: Fix big unotoolbutton dropdown with image

browser/css/device-mobile.css
it was hidden in 6.4, now when it appears - other buttons are
positioned incorrectly
=> mobile-wizard: hide not usefull style options on mobile

wsd/FileServer.cpp, wsd/TileCache.cpp
- wsd: allocate temporary buffer dynamically
- wsd: cache misses are not errors
=> Misc fixes

browser/css/notebookbar.css
Signed-off-by: Andreas Kainz <kainz.a@gmail.com>
Change-Id: I50feec0c4bef0646fc3bea3a40bbd326ab12099f
As pedro added Character Spacing to writer #2149 the page margin-left: 44px isn't needed any more, cause with the additional command the alignment fit's perfect.
If character spacing will be available within impress/draw also #CharBackColor.notebookbar can be removed from notebookbar.css.
**before**
**after**
=> Remove Character spacing margin-left at writer BackColor

common/FileUtil.hpp, wsd/DocumentBroker.cpp, wsd/QuarantineUtil.cpp
added method to get inode number from Stat object
quarantine file on exit too
=> Quarantine followup: quarantine file on exit too

wsd/Storage.cpp
unit-wopi-saveas sometimes fails on me with sanitizers. The reason is
still not yet clear (the test is quite stable without them), but at
least try to find out if the suggested target is already wrong when we
put them to the HTTP header or it goes wrong later.
Change-Id: I25f65fd6e211022aa93c699cdaef49eb8978fdee
=> WopiStorage: log what is the final suggested target for save-as

browser/src/core/Socket.js
On documentconflict, we give 3 options;
discard, overwrite, save-as
the third option should be impossible if the user is not allowed
Change-Id: I30571d885259a02c4170ccf7e291d4456bf1880c
* Resolves: # 
=> fix: dont give an option to saveas if UserCannotWriteRelative is true

configure.ac
As discussed during today's COOL meeting. Even cp-6.4 now requires
C++17, so this should be always satisfied.
Signed-off-by: Luboš Luňák <l.lunak@collabora.com>
Change-Id: I7b4f96b6de54a747e42069f0fc839393cf3d1bec
=> require C++17

browser/Makefile.am
According to Linux man, `-r` and `-R` are synonims and `-a` implies `-R`.
However, FreeBSD `cp` errors out when both `-r` and `-a` are given.
This fixes `make install` on FreeBSD.
Change-Id: I5b325eb654ca52ad0f988e777c5bf5447d385ab5
=> Use `cp -a` instead of `cp -ar`.

wsd/QuarantineUtil.cpp
Instead of
1638118271_12013_%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F289_ocvq040ushf2
we would get
1638118271_12013_%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F289_ocvq040ushf2_bad.docx
I find it more useful.
Change-Id: I50918908173adeb68964b2aa542592b57ec82020
* Resolves: # 
=> quarantine: add the original file name to the quarantined file name

loleaflet/css/device-tablet.css
Those spaces and brackets are also needed when using tables
Change-Id: I9af86ecddc335e212ad76700ce66531453db2274
=> Aboud: Fix Desktop-only rules, affect also tablets

browser/src/core/Socket.js
In co2021 type of labels in core were changed for message boxes.
This should be non-editable fields.
=> jsdialogs: make message box fields non editable

kit/ChildSession.cpp
removed support for parameter "type" which is no longer sent with textinput
Change-Id: I97bb7e80fe9cc3bb0768fd37b0c15983310a538c
=> kit: removed back compatibility of textinput message

loleaflet/css/device-mobile.css
Reduce size of dialog title and its margins since we do not want
the heading to be so big and prominent that we end up to overshadow
the content and worst, be required to scroll (often when using
landscape view)
Change-Id: Id6414ecb6beac00bccf2345d2c244ddb9582a67b
=> About dialog: No need to use desktop heading sizes

browser/css/toolbar.css
Change-Id: Ie8b470dc597f4e9e7199550fe57cb98a9e5d42f1
* Resolves: #3773 
define a min-width solve the issue that the UI will jump if you switch between 10 and 10,5 font size width.
=> Fix Font size jumping width #3773

kit/ChildSession.cpp
Appearently core expects encoded path for filenames on saveas
and decodes it at the end.
So if the file name is something like a%20b
and it becomes a b in the storage.
Change-Id: Ib200c92859b4ab3f262cfe88747563c42e2c6a5c
* Resolves: # 
=> fix saveAs for files with encoding characters

browser/css/jssidebar.css
Change-Id: I825900d31c4e6ac20d5b8946859c477f4eb026ea
first elements are always left align
hide rotate setting cause it didn't work and the sizing isn't good
fix dropdown element
=> Sidebar alignment fixes

browser/css/toolbar.css
Change-Id: I82aeae9f7cb2d6352546b39f3ed008fc19da3020
=> Toolbar Separators use the same color than sidebar separators

browser/css/jssidebar.css, browser/css/notebookbar.css, browser/css/toolbar.css
Change-Id: I0cb4a98b322dcfd9de036a618866ec8fef1a4a98
* Resolves: #3716
synchronize the select, hover and select:hover layout between classic toolbar, notebookbar and sidebar. Each action has it's own layout. 
**select | hover | select**
**select and hover | unselect | select**
layout is the same at toolbar, notebookbar and sidebar.
=> Update highlight color layout

test/Makefile.am, test/UnitWOPISaveAsWithEncodedFileName.cpp
this test ensures that double encoded filenames are not a problem.
file names can already be encoded like a%20b and this was causing
problems and fixed with #3786
Change-Id: Ibaf0456f26c3a2e8d3c2863c2b925c7a5b9fc79c
* Resolves: # 
=> unit test for save-as files with encoding characters in the name

browser/css/jsdialogs.css
- Fix hover state: before, hovering into the arrow component would
affect its parent's width
- Make it more visible that the dropdown has two action in it (it is a
split button dropdown) by:
- adding background color
- adding divider, to emphasize that we are talking about two different
btns
- Use CSS var instead of random gray
Change-Id: I841749d143bcc240a1b4d820868b6a7af53db599
=> Sidebar: Fix Split Button dropdown hover state

common/Util.hpp, test/Makefile.am, test/UtilTests.cpp
Trying to construct a string using sprintf() and std::stringstream
is unnecessarily complicated for something as simple as this,
and it shows up in my profiling. This commit makes the hex values
change to uppercase because that's what hexFromByte() returns,
but I don't think it matters.
Signed-off-by: Luboš Luňák <l.lunak@collabora.com>
Change-Id: I31c7b8e7cf4c2a495eca0bf03ae4cab53b26a04b
=> make stringifyHexLine() simply work on std::string

wsd/TileCache.cpp
(cherry picked from commit e2515a7b15d47ad75d79048eff9fa4651e323ad0)
Change-Id: I373f85e68964610fe88cb6fa057c548b9a50fb51
=> TileCache: improve parsing in parseInvalidateMsg()

.github/workflows/codeql-analysis.yml
It was complaining:
npm WARN tarball tarball data for
vex-js@file:/home/runner/work/online/online/browser/archived-packages/vex-js-4.1.0-9ff760927.tar
(sha512-t8cpwh28HrmrkcqqvFTJl+xjLuPnusW3Eb3zczPm2RzX0Q8HbjHiywq1+ttQL+tLVob80CaQYOmmFY8rhtPEug==
sha512-n/dgknlD5CVl+Bn87kARnjwSknxZvSMflwzrBdgV0LLdLXpgmF6AKQ//bEEBBwK2JLXR0wG2R+il1zjcBtOi6Q==)
seems to be corrupted. Trying again.
npm WARN old lockfile Error:
sha512-t8cpwh28HrmrkcqqvFTJl+xjLuPnusW3Eb3zczPm2RzX0Q8HbjHiywq1+ttQL+tLVob80CaQYOmmFY8rhtPEug==
sha512-n/dgknlD5CVl+Bn87kARnjwSknxZvSMflwzrBdgV0LLdLXpgmF6AKQ//bEEBBwK2JLXR0wG2R+il1zjcBtOi6Q==
integrity checksum failed when using sha512: wanted
sha512-t8cpwh28HrmrkcqqvFTJl+xjLuPnusW3Eb3zczPm2RzX0Q8HbjHiywq1+ttQL+tLVob80CaQYOmmFY8rhtPEug==,sha512-n/dgknlD5CVl+Bn87kARnjwSknxZvSMflwzrBdgV0L …
=> Fix a CodeQL problem

kit/ChildSession.cpp
Problem is, all save-as requests received urlencoded
but when it is a wopi request we change the url bit of the message
with correct path jail filename parts. At that stage it becomes decoded
already. saveAs in the core also decodes the url and thats why we should
re-encode it. But unless it is a wopi request it should be already
encoded and we should not re-encode it again.
Change-Id: I08b3a1cff6c3aa9271222c255f4a35aa5b984819
* Resolves: # 
=> fix double encoding url on convert-to

browser/src/layer/tile/CanvasTileLayer.js
Issue sometimes on mobile only one tile was initially requested.
To make other tiles visible it was required to pan/zoom.
For me it was reproducible only using Android Nextcloud app,
probably it depends on device and browser.
Problem was caused by early call to _update() in CanvasTileLayer.js
Canvas was not initialized yet and map returned size of (0,0),
also _getTopLeftPoint() returned some point with negative coordinates
what caused that calculated tile positions were out of a valid range.
In result we requested only one tile with coorinates (0,0).
old log was like:
```
canceltiles
// one tile 0,0
tilecombine nviewid=0 part=0 width=256 height=256 tileposx=0 tileposy=0 tilewidth=1920 tileheight=1920
...
tileprocessed tile=0:0:0:1920:1920:0
...
// more tiles but position outsize screen - …
```
=> mobile: request correct number of tiles on init

browser/css/toolbar.css
lc_viewcomment was used ONLY at MobileTopBar and there
all other icons are monochrome. So this request suggest
to use the monochrome mobile specific comment icon.
As click on the viewcomments starts also the comment wizard,
the old icon wasn't the correct one.
Second option would be to add the mobile icon at toolbar-mobile.css
but as the command wasn't used anywhere else. The correct icon
can be used already in toolbar.css.
Change-Id: I750a9a7f0eb3dbfc466e6a36ce2e4ad998811023
=> Mobile: Replace lc_viewcomment with lc_mobile_comment_wizzard

common/SigUtil.cpp, common/SigUtil.hpp, common/Util.hpp, kit/ChildSession.cpp, test/WhiteBoxTests.cpp, wsd/LOOLWSD.cpp, wsd/TileCache.cpp
- wsd: Termination flag requires having ShutdownRequested
- wsd: fix 'potentially uninitialized' variables
- wsd: cache misses are not errors
- wsd: add endsWith helper with tests
- wsd: correct use the exit code from UnitWSD
=> Backports and minor fixes

loleaflet/src/control/Permission.js
Change-Id: I0ab4d4b8a79cf2d96fb47874dc7962718d279bb6
* Resolves: # 
=> Dont give option to saveas when UserCannotWriteRelative is true

browser/src/control/Control.TopToolbar.js
Change-Id: I5f1809858c5aecdef04d9c736711dbb25c80afaa
* Resolves: #3764
3 sections
1. section predefined styles
2. section favorite styles
3. section ALL available styles
As there is a search (compare to the sidebar) I listed all styles so the search result will find all styles that are available.
separator between predefined styles (default and clear) was removed to have less separations.
Fix is for writer (tested also for the other apps) maybe add favorites to the other apps to.
=> Fix styles dropdown: make all styles searchable, remove one separator

browser/src/control/Toolbar.js
html2po trims starting &lt;kbd&gt; and ending &lt;/kbd&gt;
Change-Id: Ia685cfe3bac301b991314c5108b688a20175dcea
=> Try harder to get translation of keyboard shortcuts

browser/html/cool.html.m4, wsd/FileServer.cpp, wsd/FileServer.hpp, wsd/FileServerUtil.cpp
- when reading from config use correct type so SyntaxException
is thrown when we type non-number into uint field
- handle SyntaxException and send 500 so user will get response
(previously we left request without response until timeout)
- log about incorrect value in the config
- simplify repeated bool -> string conversion after config read
Change-Id: I1c50de263ffdb1d97eb9381754bc7cf3bd05dbfa
* Resolves: # 
=> Use correct formatting for string variables

browser/css/mobilewizard.css
Drawing areas such as those found in impress lists: chart type or slide
layout were being downsized and thus blurriness was evident.
-> Remove old CSS rule that does not serve any purpose now and fix that.
Top level drawing areas (where the whole panel is occupied by it:
slide layout) were being set with wrong position (not center
aligned).
-> Always aligned to the center without extra margins that, otherwise
would offset them
Change-Id: If4f4057cffb566026374d4d2e725dc663ff6f3e5
=> MobileWizard: avoid re-scaling ui-drawing-area

test/TileCacheTests.cpp, wsd/protocol.txt
ChildSession::loKitCallback() may generate a message in the format
"invalidatetiles: EMPTY, 0". Handle it properly in tests.
Signed-off-by: Luboš Luňák <l.lunak@centrum.cz>
Change-Id: If8009be3c4ce031466ed304df7028848a8ab960f
=> handle properly "EMPTY" invalidatetiles message (T32137)

browser/src/layer/marker/Cursor.ts
Avoid showing colored user names during zoom animation,
because we didn't update their position according to the
animation and they were at the initial positiona during
whole animation.
=> Hide cursor during zoom animation #3758

wsd/LOOLWSD.cpp
Change-Id: I8a9a05498649dfea80ec425671326aa0c62d4917
* Resolves: # 
=> backport 'add pdf version option for conversion' to 6.4
