- test/Makefile.am
Change-Id: I351d21593b8c82f3a0866545762f75fa9eb9824b
> test: Makefile: fix builddir != srcdir

- wsd/ClientSession.cpp
Change-Id: I92b284883a633ebe3bf47ea8001f8c18692275a1
> ClientSession: simplify by using std::any_of()

- loleaflet/src/control/Control.Menubar.js
Change-Id: Ide725c9342b9df190f6c276bf951a6fd9403f43e
> Change bug tracker URL

- configure.ac
Change-Id: I749554fa899c24ed8d95b230f75f9a03ea5e1b85
> Update bug report URL and home page in AC_INIT

- loleaflet/js/w2ui-1.5.rc1.js
Change-Id: I05e9abfabedcdf19f6e42eb642cd7487ff3426af
> w2ui: avoid long drop downs going out of view

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/libreoffice/androidapp/SettingsActivity.java
- android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java
- android/app/src/main/res/drawable/ic_folder_black_24dp.xml
- android/app/src/main/res/layout/activity_document_browser.xml
- android/app/src/main/res/layout/file_explorer_grid_item.xml
- android/app/src/main/res/layout/file_list_item.xml
- android/app/src/main/res/layout/theme_selection.xml
- android/app/src/main/res/values/strings.xml
- android/app/src/main/res/values/themes.xml
- android/app/src/main/res/xml/libreoffice_preferences.xml
Change-Id: I631d31558ae9afac9585d12d66237bc04a761555
Reviewed-on: https://gerrit.libreoffice.org/c/online/+/93563
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Mert Tumer <mert.tumer@collabora.com>
> android: enable Dark Theme for Dark Mode changes

- loleaflet/src/layer/AnnotationManagerImpress.js
Deleted comment was only looked up on current page. Behaviour is improved.
Change-Id: Idb6d8ca3e034075434ba11fc3603da1cf2b31e88
> loleaflet: Refresh the page subject to annotation deletion.

- android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java
- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- android/lib/src/main/res/values/strings.xml
- loleaflet/src/control/Permission.js
if the file is opened in readonly mode, ask for
save as and re-open it with the copied file to be
able to edit it.
Change-Id: I4dc64c5664ce2c3b317d91808244410b4b5041d9
> android: Offer 'save as' when switching edit mode

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/map/handler/Map.TouchGesture.js
Hyperlink pop-up and context menu now share same functions when open-hyperlink event is fired.
Change-Id: I91380e838d83c73c48d86900b0e4638c1bb97cc5
> loleaflet: Hyperlink pop-up may ask for confirmation.

- loleaflet/src/control/Control.AlertDialog.js
- loleaflet/src/layer/CalcGridLines.js
- loleaflet/src/layer/marker/TextInput.js
Change-Id: I0a2b8deba4fdb48a8aed92b26d749a00f5f37ada
> Fix Issue #68 Ensure consistent function declaration

- loleaflet/src/layer/marker/TextInput.js
Change-Id: Iaaea154afb3a3c94db31a1f0f6e81127f337e832
> Ensure consistent function declaration in TextInput.js

- .github/workflows/notifyirc.yml
Change-Id: Icb49e5e3c0e08e9a4f1ca84fbe68a1856964d70c
> Add IRC notifications

- .github/workflows/notifyirc.yml
And be silent about tags, just to keep things simple.
Change-Id: I7cfe4efe8b82f84cf490ada8032b32b859f27c22
> notifyirc: write 1 line / pushed commit

- .github/workflows/notifyirc.yml
So that one can go there quickly.
Change-Id: If954f9843c2d94836e9575acb708bfeff2359e67
> notifyirc: add the URL of the commit, too

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/map/Map.js
Discovered by @timar through https://github.com/CollaboraOnline/online/pull/174
> Remove unused function showHelp()

- loleaflet/css/leaflet.css
- loleaflet/css/loleaflet.css
- loleaflet/css/menubar.css
- loleaflet/html/loleaflet.html.m4
- loleaflet/src/control/Control.StatusBar.js
- loleaflet/src/layer/marker/TextInput.js
- loleaflet/src/map/Map.js
from 3.9:1 (WCAG A) to 5.5:1 (> WCAG AA) and re-use css var
Change-Id: Ifda6eb45d7319a717e2c1503c51dbc6f6e883c64
> Improve accessibility

- Makefile.am
- autogen.sh
- scripts/refresh-git-hooks
So one can't forget enabling them.
Change-Id: Icb595e9d0711227eaa6f11c1a9ff87f2c361e0bb
> git hooks: enable them automatically during 'make'

- loolwsd.xml.in
- wsd/LOOLWSD.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
Originally authored by @yunusbulutt on #169 
@yunusbulutt, thank you again for the great work you did on this! :)
I just couldn't let your nice work wait any longer, and fixed the last bits so that it can be merged to master.
> Resolves #111 - Kill WebDAVStorage in the code

- .git-hooks/post-merge
- .git-hooks/pre-commit
The pre-commit is a bit stripped down compared to the LibreOffice
master.
Change-Id: I162ec1007fa1db5bd8fca522d712db50dafaf998
> Add also the pre-commit and post-merge hooks, they are useful too.

- test/TileQueueTests.cpp
Change-Id: Ie20da2f0060b86c05b1f45e930f31ca5cab6d9fa
> Unit test for skipping ModifiedStatus from deduplication

- Makefile.am
Change-Id: I1bb1b898f990b2353ff5956af4db9d25c46521f4
> Fix build with ./configure --disable-setcap.

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: Ieea2501eb4bc343173cd3a8fd2f0ee823d57a9fc
> Add alt text to generated buttons

- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I2aa8f868d2e70f0386fc680d29fd505279ec4687
> Notebookbar: avoid duplicated unused ids

- loleaflet/src/layer/marker/TextInput.js
In an upcoming change, CollaboraOnlineWebViewKeyboardManager will
start producing that.
> tdf#129371: Add a 'unoCommand' command to COKbdMgrCallback

- .gitpod.yml
Change-Id: I717c0e69cee9ecea61e82c1bb3755e4abf15655b
> Enable port 9980 on gitpod container

- ios/Mobile/Info.plist.in
Change-Id: Iac369102878879ddf4e9fbdd716d28339b9f0bb4
> Bump CFBundleShortVersionString to 4.2.12

- ios/CollaboraOnlineWebViewKeyboardManager/CollaboraOnlineWebViewKeyboardManager.m
Change-Id: I661a4a57a4e5422f7e5f45d81635d54ea0f330e1
> Introduce @available check for -[UIPress key] which is from iOS 13.4

- wsd/Storage.cpp
Change-Id: Ib964cb84be2cf31257b7ad59c0afb1f18b586afb
> Add a X-LOOL-WOPI-ServerId to help cluster debugging to requests.

- ios/CollaboraOnlineWebViewKeyboardManager/CollaboraOnlineWebViewKeyboardManager.m
Change-Id: I806a232e9ec0922b42c5405f707295a05dbf5cd8
> Fix the describeUIPresses debug output

- g
Similar to gerrit's 'git review' which creates/updates a change without
clicking anywhere in a browser.
Also add a './g pull' to help those who are used to that.
Change-Id: I240ff55c7480d0a2cd6de3f2ea3cd84ca0556af4
> Add a './g review' script to trigger CI for a commit in an easy way

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I0f9ce2adc9180c96df3bfb5e5b5bc528909a679e
> Fix Calc: keyboard shouldn't cover active cell on mobile

- loleaflet/css/toolbar.css
Change-Id: I9448d452a768eb8addee84579dbb9cccc6234952
> Toolbar: Use the right asset for incrementindent

- .gitpod-files/loolwsd-gitpod.xml
- .gitpod.yml
* Disable SSL and various security config
to be able to access the container from outside
* Meant to be used only for development/testing etc.
and temporarily
Change-Id: If799442b8a94b95554b6cefa7ad01675a66b93ce
> Gitpod: Add custom loolwsd.xml

- wsd/LOOLWSD.cpp
Change-Id: I4bcd0daed8b8ab5874e6dfca3d65b5f6870fdfa6
> Fix convert-to behavior

- .gitpod.dockerfile
- .gitpod.yml
Change-Id: I367b0c5d6daf805d257451c51e45dfebf84ed8d2
> Gitpod: Enable VNC and add browser

- wsd/LOOLWSD.cpp
Change-Id: I3e38f5f1a53ba2c06323d70d80118267152f43fe
> extra logging for debugging convert-to failure

- loleaflet/src/control/Control.MobileWizard.js
going up in wizards which has huge content (i.e: function in calc)
was very slow because animation performed on all the elements of the same class
but needed to perform it on the siblings only
Change-Id: I1db86492cc3ee7513efa44ccf08a0d15853364fd
> leaflet: optimized the changing levels in wizard

- scripts/locorestrings.py
Change-Id: If33d97ab9ddc33f5d674ddcc53db884338eb83c6
> #259 locorestrings style fixed

- .gitpod.yml
To make use of multiple cores/threads as suggested by kendy
> Gitpod: Use nproc with make

- loleaflet/src/control/Control.ColumnHeader.js
- loleaflet/src/control/Control.Header.js
- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/core/Util.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Canvas.js
- loleaflet/src/layer/vector/Path.Transform.Canvas.js
dpi scale variable is removed. Scaling is done at initializing.
Change-Id: Ib1d96bbe783b74161a7860227f2601645db2f1d6
> Leaflet: Canvas view improvement.

- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/common/nextcloud_helper.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/calc/nextcloud_spec.js
- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/nextcloud_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/nextcloud_spec.js
- cypress_test/integration_tests/mobile/writer/writer_mobile_helper.js
Change-Id: I876c087adff29ee86460120e8d09f9bbcb5ef01c
> cypress: extract selectHamburgerMenuItem() helper method.

- scripts/untranslated.py
Change-Id: I4a3d8db37ba013b581eeec8fff8fba6fe1bcc966
> pep8 coding style conformance for scripts/untranslated.py

- wsd/lint-discovery.py
Issue: https://github.com/CollaboraOnline/online/issues/258
> Fixing pycodestyle errors

- loleaflet/admin/src/AdminSocketAnalytics.js
- loleaflet/admin/src/AdminSocketOverview.js
- loleaflet/admin/src/AdminSocketSettings.js
- loleaflet/src/control/ColorPicker.js
- loleaflet/src/control/Control.ColumnHeader.js
i fix some eslint 4.0.0 format rule mismatches. After that there are still some another rule mismatches.
Change-Id: I15943579ca54840a092efeff12f95aab764b921f
> Fixes some eslint 4.0.0 format rule mismatches #229

- .github/ISSUE_TEMPLATE/easy-hack-template.md
Change-Id: I6133f7083ff090267cd88455253556df74ce1e24
> Update issue template for easy hacks

- .github/pull_request_template.md
Change-Id: I0c1de7a8b49e9f2ba9c72a3dc065caf36076dd9a
> Community: Add pull request template

- loleaflet/src/control/Control.ColumnHeader.js
- loleaflet/src/control/Control.Header.js
- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/core/Util.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Canvas.js
- loleaflet/src/layer/vector/Path.Transform.Canvas.js
Reverts CollaboraOnline/online#262
Turns out this was merged too early, causing blur in the case of non-100% zoom...
> Revert "Leaflet: Canvas view improvement."

- loleaflet/src/layer/ImageOverlay.js
- loleaflet/src/layer/marker/Cursor.js
- loleaflet/src/layer/marker/ProgressOverlay.js
- loleaflet/src/layer/tile/TileLayer.TableOverlay.js
- loleaflet/src/layer/tile/WriterTileLayer.js
Change-Id: I0ba5103011a3d1044575b8218f63678721dd6457
* Resolves: # 
> Fix indentations as per eslint 4.0.0

- README.md
* Add image & slogan above
* Add key features
* Format the development bits section
* Resolves: # 
> Touch-up README.md

- g
E.g. local branch is OK to be 'co-4-2' while it tracks
origin/distro/collabora/co-4-2.
Previously this was only working when the local branch was not renamed.
Change-Id: I11c24d71e903d27d34ec498604190d6b436b593d
> ./g review: don't assume that local and tracked branch is the same

- loleaflet/css/toolbar.css
Change-Id: Ibe1ef6827a466e5575995cb72e01637f3fe801f8
> Fix issue #210: StyleAply drop down menu width

- loleaflet/css/leaflet.css
- loleaflet/src/layer/marker/Cursor.js
cursor type was set incorrect when hovering on text box in impress
Change-Id: Iaa95398dc9d6f49342312dba0497b74f88d4bc14
> leaflet: specialise cursor for impress text

- wsd/DocumentBroker.cpp
- wsd/LOOLWSD.cpp
> Port to Util::make_unique for wsd

- scripts/unocommands.py
> pep8 coding style conformance for scripts/unocommands.py

- wsd/Storage.cpp
If IP address was set as allowed in storage.wopi, but its host
name was given in WOPI URI, the host was not resolved, and was
not accepted.
Change-Id: I20655cee8b435c9645d5cfdd102bdae9033fc1ab
> wsd: resolve host as fallback for allowed WOPI host check

- .gitpod.yml
Change-Id: Ib48510dfecb55bc5d021e2b26daf114fda267529
* Resolves: # 
> Gitpod: Silence the unneeded port popups

- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I5d9fd7655380d6926ca1f64b03128098fbb15270
* Resolves: # 
> Created the cypress test for the underline attribute in desktop writer

- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/control/Control.Scale.js
- loleaflet/src/control/Control.Scroll.js
- loleaflet/src/control/Control.StatusBar.js
- loleaflet/src/control/Control.Tabs.js
- loleaflet/src/control/Control.Toolbar.js
Change-Id: Ia8edd33586ab785dd4004e37034e8d9e4e622b89
* Resolves: # 
> loleaflet: eslint 4.0.0 conformance

- common/FileUtil.cpp
- common/FileUtil.hpp
- common/JailUtil.cpp
- loolwsd-systemplate-setup
- tools/mount.cpp
Resolves a number of issues in AppImage and supports symlink files and better /etc dynamic files update.
> Bind-mounting improvements

- README.md
> README.md: Add Gitpod badge

- loleaflet/src/layer/AnnotationManagerImpress.js
Change-Id: I5ae043fc593260794e6a2f4fda6d2338dc4075a6
added missing listener and method to reply annotation in impress
> leaflet: annotation: fixed reply in to the annotation

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
> Created the cypress test for strikethrough attribute

- cypress_test/integration_tests/common/mobile_helper.js
- loleaflet/src/layer/AnnotationManager.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/tile/WriterTileLayer.js
Added new thread options for annotation
- remove thread
- resolve thread
changed function of resolve to resolving a single comment
> leaflet: new option for comments thread added

- common/JailUtil.cpp
Should resolve the AppImage issue.
> mount: handle /dev directory creation failure

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/layer/FormFieldButtonLayer.js
Change-Id: Ibc159b6f5d2efceaf33ec37354ddd376f2aba649
* Resolves: # 
> Remove unnecessary escapes for eslint 4.0.0 conformance

- CODE_OF_CONDUCT.md
Change-Id: Iafed9167ae96d4d1b8e82e4dea0679d7102d5330
* Resolves: # 
> Complete the CoC statement

- loleaflet/.eslintrc
- loleaflet/package.json
- loleaflet/src/control/Control.Menubar.js
Change-Id: I4d04d5f2037c6af61050f94d28e7781a14cc1210
* Resolves: # 
> loleaflet: Bump eslint version to 4.0.0

- loleaflet/package.json
- loleaflet/src/layer/marker/Cursor.js
Change-Id: Icace27211809731d5dcbde6cd9cb11998efecac7
* Resolves: # 
> loleaflet: Bump eslint version to 4.18.2

- wsd/DocumentBroker.cpp
Upload to storage when/if the last attempt failed, even when the document hasn't been modified since.
> wsd: force saving to storage if the last attempt had failed

- loleaflet/css/mobilewizard.css
- loleaflet/css/notebookbar.css
remove unnecessary rules
Change-Id: Ifd8510da237f56be16c46dd208df0613a956d7db
> Notebookbar: selected btn: restrict declarations and

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I824275d99ea0342f1e704b4ca987d5470b6fb939
* Resolves: # 
> Make two identical warnings non-identical

- ios/Mobile/AppDelegate.mm
- ios/Mobile/CODocument.mm
- loleaflet/html/loleaflet.html.m4
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/layer/tile/TileLayer.js
(But not on iPhone.)
Change-Id: I0589fd914b2ccdd7a62981ab76c02363d7dcf114
* Resolves: # 
> Use the notebookbar in the iOS app on iPad

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: Id80b03625717e5061cb58449eab532536cc9fb50
* Resolves: # 
> Created the cypress test for font-size attribute

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
Change-Id: I3a33ec610769bc4e33c4b0ce3c1c465fca07b44f
> android: Paste images copied from Chrome using Copy image.

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- loleaflet/reference.html
- loleaflet/src/map/handler/Map.WOPI.js
> Implement pasting after Copy Image from Chrome

- g
This helps in case you deleted a remote branch using the GitHub web UI,
so the local view is outdated.
Change-Id: I98be33ea5712c66589f42b64e3462b76b84fbcc5
> g review: update list of remote branches before checking for branch existence

- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
* Avoid potential frequent saving on shutdown
* Remove default arguments and better document the 'force' flag when saving.
> Avoid potential frequent saving on shutdown

- loleaflet/html/loleaflet.html.m4
- test/WhiteBoxTests.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/FileServerUtil.cpp
Change-Id: If6e4096dc37573ff116f218ceb4ca14135820ff7
* Resolves: # 
> Make Themeing related CSS vars UI Configurable

- loleaflet/src/layer/marker/TextInput.js
Change-Id: I6a3f6ac133ccdccb0e208b283b09f818cfe321cd
> leaflet: Shift+Enter will create a new line, not  paragraph

- loleaflet/src/layer/marker/TextInput.js
Change-Id: I6a3f6ac133ccdccb0e208b283b09f818cfe321cd
> leaflet: Shift+Enter will create a new line, not paragraph

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I54ebe7fb81ca6598ba45f3cbed62474d103d055a
* Resolves: # 
> Created a cypress test for Clear direct formatting

- cypress_test/integration_tests/common/helper.js
- cypress_test/package.json
Fixes this issue:
https://github.com/cypress-io/cypress/issues/8621
Change-Id: Ied225391e7e72dfd9df852481ad29b6368c194cf
* Resolves: # 
> cypress update: 5.1.0 -> 5.3.0.

- wsd/DocumentBroker.cpp
Change-Id: Ic4fb2da63e761b78dedf9f67e0612e90e6d4be87
* Resolves: # 
> Autosave annotations in pdf

- loleaflet/src/layer/AnnotationManagerImpress.js
Change-Id: I59f5a9a9a44cd4d2bc5b1df9323b34890e1b673f
* Resolves: # 
> Switch comments also between pages #321

- .git-hooks/commit-msg
- .git-hooks/post-merge
- .git-hooks/pre-commit
- g
Change-Id: I3bf69169f90d465e03ed6884315477fc3a52e28c
> Copy the git hooks and the 'g' script from master.

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I80de963384fe6c2fe50607083fefe3ea1eb46af2
* Resolves: # 
> Created the cypress test for font-style attribute

- autogen.sh
Change-Id: Ib0e1cb3f34099a46e34e17a23e38d1c4bdb7dec9
> Add FreeBSD case to autogen.sh

- test/UnitWOPITemplate.cpp
- test/UnitWOPIWatermark.cpp
- test/WopiTestServer.hpp
> Remove Poco::LocalDateTime left-overs

- g
Change-Id: I689348489f89d74b10782302d7bea57a845e36d4
> g review: check if 'gh' is authenticated already

- loleaflet/src/control/Control.StatusBar.js
Change-Id: I9e6012bdaacbd5c82be92364e773faf0e925fa09
> enable l10n of two status bar strings

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: Id25ff65891ce7afa06f0877299d5220886fb5a1b
* Resolves: # 
> Created a cypress test for style combobox

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I5faa18791aaa3e7670ea67502f86662569fd28b5
* Resolves: # 
> Created the cypress test for Highlight color

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I0853c8c3d9cd88b0263c980a1e9ddcf81c6ca258
* Resolves: # 
> Created the cypress test for font color attribute

- loleaflet/css/device-mobile.css
- loleaflet/css/mobilewizard.css
Change-Id: I963f46cfa109808f53305cddc30ef85abd30b880
> Mobile: toolbardown: restrict rules for .checked elment (by moving it to device-mobile file)

- loleaflet/css/device-mobile.css
Change-Id: I826ac9b86d273a0df7c274b003a483b1c20ebaf9
problem:
i.e: show sheet in the mobile
> leaflet: vex: corrected misaligned checkbox in vex

- loleaflet/css/toolbar.css
Signed-off-by: Thais Vieira <thais.vieira@collabora.com>
Change-Id: I393f496cbfb930ea094292076db982c77143e444
>  Insertshapes dialog: fix padding

- loleaflet/images/lc_arrowshapes.up-right-down-arrow.svg
Change-Id: Ia548338e8354bd7e697997d5a1b21a36e89e5c33
> Cherry pick: icon fix without wip css setup

- cypress_test/README
- cypress_test/integration_tests/common/helper.js
We got some new exceptions and also we have a start
screen now.
Change-Id: I22288ede30540437e8b0a5d3ce4c607d42a465bc
> cypress: update nextcloud test to work with NC 20 version.

- cypress_test/integration_tests/common/helper.js
Change-Id: Idc9a948b0b689b484d609c8778c574c921918a5a
> cypress: try to fix nextcloud test failures.

- cypress_test/integration_tests/common/helper.js
Change-Id: I9d4666235308354f74105edfa0f5b1831ab0bf14
* Resolves: # 
> cypress: NC: visit the files URL directly.

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I8275fea411d42ec7f96c7d87c8102397f392befb
* Resolves: # 
> Created a cypress test for Insert Table

- loleaflet/html/loleaflet-help.html
Change-Id: I4c5efaf1b16a81a870befae30e0422c13acf0504
* Resolves: # 
> This is a help file, not marketing

- cypress_test/integration_tests/common/helper.js
Change-Id: I3b02cbe19578db2ecc8bcb597faa575a1552b55f
> cypress: NC: hide firstrunwizard.

- loleaflet/src/control/Control.Menubar.js
Change-Id: I6bd6bf447aca5831c0decba62e24e8aefe7edde8
> Menubar view - move sidebar to other show/hide items

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I6056962c7602859b5975d1e2b4da3d033c53dc4a
* Resolves: # 
> Created a cypress test for Insert Hyperlink on writer

- wsd/DocumentBroker.cpp
- wsd/LOOLWSD.hpp
Change-Id: Iab57b946cc29814155fccde9b1fbb0c6697b8c26
> wsd: privatize public members

- loleaflet/js/global.js
- loleaflet/src/control/Control.Header.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/core/Class.js
- loleaflet/src/core/Util.js
- loleaflet/src/geometry/PolyUtil.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Path.Transform.Util.js
- loleaflet/src/map/handler/Map.WOPI.js
Change-Id: Id7723f0f0ed81e074f56955f80eda3d70241294e
* Resolves: # 
> loleaflet: Towards eslint 6.0.0 #396 - no-prototype-builtins

- scripts/extract_translator.sh
added comma seperated author list support ( usable by `--csv file` format )
removed mail addresses from author list
Signed-off-by: kuesji koesnu <kuesji@koesnu.com>
Change-Id: I369794dfb0db978c890b7691e4101f8fdf316302
* Resolves: #482 
> pull request for issue #482

- scripts/extract_translator.sh
Change-Id: I412b035cf25f7ec40164d0d187881177c7de0f4e
* Resolves: # 
> Translator credits: Space after comma and tabs-to-spaces

- loleaflet/src/control/Control.Menubar.js
Change-Id: I005943ddfff7d4208dc432fec5836862c1f3638e
regression caused by 0da5c3a2
> leaflet: fixed jquery error on hovering over menubar

- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I808aa8a7b99d15129b130e4e42b9e6fd95ee0515
* Resolves: #70 
added postmessages in bottom left section of debug mode
> added postmessages in debug mode

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I689845328981d9dbfe34cc71eefebb802315a85e
* Resolves: # 
> Created a cypress test for Insert Shape on writer

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I1cd38fdcf1fa42257d75d02ecf4e2ccb1bd716fc
* Resolves: # 
> Created a cypress test for Insert chart on Desktop writer

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I294e46ce4ef147f85187c8da912a8056fb202553
* Resolves: # 
> Created a cypress test for Center alignment on Desktop writer

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I294e46ce4ef147f85187c8da912a8056fb202553
* Resolves: # 
> Created a cypress test for right alignment on Desktop writer

- cypress_test/integration_tests/common/helper.js
- cypress_test/plugins/blacklists.js
Change-Id: I4a8bc873dc1657a0e554ec6132f5fc41531bb3d3
> cypress & nextcloud

- loleaflet/css/loleaflet.css
- loleaflet/css/menubar.css
- loleaflet/css/notebookbar.css
Change-Id: I2c05bfc1a8906d6b67e3736174132e5cac9d0052
* Resolves: #237
> Fixes issue 237

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarCalc.js
The feature is not available there, so it is confusing the users.
Change-Id: I5ecd1ba3c1cf78e54433262d710ee64e38a8bd1e
> Disable Freeze panes menu & notebookbar entries on tablets.

- .git-hooks/commit-msg
Change-Id: Ic85bb838dfb236b7f1a244fd79f8ebeee0453a80
> git-hooks: check for signed-off-by in the commit-msg hook

- .git-hooks/README
- .git-hooks/commit-msg
Just the subset when author and the committer is the same.
Change-Id: Icff594a6a82bd0395e31f8e46cb56cb0e046e638
> git hooks: commit msg: allow to opt in for auto-sign-off

- loleaflet/css/notebookbar.css
Change-Id: Ifc5e19dfd23bc1c61f0095e68bc0fa52e82b84f4
> Notebookbar: shortcuts: Avoid setting hard height

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
> Cypress test paragraph attributes

- ios/Mobile.xcodeproj/project.pbxproj
Change-Id: I352a4a00c6ad0e80a6769a93fe6f5999aadf3128
* Resolves: # 
> Fix warning: MobileCoreServices has been renamed to CoreServices

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/plugins/blacklists.js
We need to do this differently in an NC environment.
Change-Id: I260fbe42851794e630be327bc25ec34201cad36c
> cypress: NC: disable new Saving test.

- .github/ISSUE_TEMPLATE/bug_report.md
Change-Id: I2c6469a050b40cd18a94c68611d51a7c813e65b0
* Resolves: # 
> No auto-assign of new issues

- ios/Mobile/Mobile.entitlements
Change-Id: I113e6d6a9702509a61fb2e5eb3ad7949fa836dda
* Resolves: # 
> Add the com.apple.developer.user-fonts entitlement

- loleaflet/css/toolbar.css
Change-Id: Ibd15d4d1d677e10e29019971707129ec26cc66d4
* Resolves: # 
> Add space between drop down widget see issue #350

- loleaflet/css/menubar.css
Change-Id: Ia657661252b2611d5c8d7f7d826b4510e07fa226
> Fixes issue #450

- loleaflet/css/device-tablet.css
Change-Id: Iaf8378153808582f7d8d785857eed69a6753dfa4
> Tablet: Notebookbar: hamburger menu issue #390

- loleaflet/src/control/Control.Menubar.js
Change-Id: I340474fba3cd61a3635ab9b657dc0ff358c08da8
* Resolves: # 
> Calc: add commands to calc menubar view and insert

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarWriter.js
+ Adds placeholder preview for styles.
+ Tries to reload notebookbar if not initialized correctly
> Notebookbar spinner

- loleaflet/css/mobilewizard.css
Change-Id: I9c84d756975ef87d60d98208aa34acd389ba38ac
> Mobile: mobilewizard: Reuse css var for ui-text and dividers

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/writer/form_field_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I6d931a59f4281c85347b0e824aefbcd8cf2e129f
> cypress: NC: fix up code.

- loleaflet/css/loleaflet.css
- loleaflet/src/control/Ruler.js
Change-Id: I2a6868e25ceddc9a6f5d383e6ecf41836ecdfc28
> Tooltips: improve upon PR #513, plus add rule-only css

- loleaflet/src/control/Control.Menubar.js
Change-Id: I28a9b46d139edfb6dffe2afde39bd767ac6a7af3
> Improve the check whether the PDF annotation is enabled.

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: Iefbffc90fc794b61815b92fd54702a4215858dc7
* Resolves: # 
> Created a Cypress test for Spacing attribute in desktop Writer

- loleaflet/css/leaflet.css
Change-Id: I0782d2117a9b08489b2f43e56f1831b45c4dd2b3
> Hyperlink popup (leaflet-popup-tip): fix cropped Shadow

- loleaflet/src/control/Ruler.js
Change-Id: I9603c79a544c2243ba47a8c27ad5f62fdb3fdbe3
> Simplify var name and follow same name convertions as in #513

- README.md
Its status is not reported on GitHub, so at least make this easy to
find.
Change-Id: I8a4f5bffbdb6692afa7f55e0f55ce41c04facd39
> README: mention the tinderbox

- loleaflet/.eslintrc
- loleaflet/package.json
Signed-off-by: Ayhan Yalçınsoy <ayhanyalcinsoy@pisilinux.org>
Change-Id: I08f7cc953aa6434fccbc92d74570c62a43c7dad9
* Resolves: # 
> loleaflet: eslint v.bump to 6.0.0 #396

- loleaflet/css/mobilewizard.css
Change-Id: I741bae0f2375d54ca0def7b9628003016cf20ca3
> leaflet: css: fixed wizard header miss alignment in impress

- cypress_test/integration_tests/mobile/calc/nextcloud_spec.js
- cypress_test/integration_tests/mobile/impress/nextcloud_spec.js
- cypress_test/integration_tests/mobile/writer/nextcloud_spec.js
In CI environment this does not work. I'll need to find out
how to make this tests work there too.
Change-Id: If9780796b52aa27fd18d72cc3bf786ab46865e4a
> cypress: NC: disable revision history tests for now.

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I2c4bd4e46a42854bdcc5a09f6af170d33dc4e8c0
problem:
once text inside the cell is selected,
taping on other cell does not remove the selection
> leaflet: calc text selection is never removed

- loleaflet/src/control/Control.Notebookbar.js
fix logo (document-header) overlap on some devices, namely iPads.
Change-Id: Ib2ca48d805f6decd941ae3f817f987791a074ed4
> Notebookbar: Fix the order in which elements are added,

- loleaflet/css/vex.css
to match its height (that is comming from vex theme)
Change-Id: Ibffc3040d07afd2ea98af65a3aeaa041b0dc73fe
> Vex dialogs: Fix close vertical alignment on hover

- loleaflet/src/control/Control.Tabs.js
> leaflet: resolved console error when right-clicking a sheet tab

- loleaflet/src/control/Control.Notebookbar.js
Change-Id: I2447d2662c4c092ae938794c3bbfff134df02710
(cherry picked from commit cc163ee0ce252459ed7244c6b27b28d4cea259f1)
* Resolves: # 
> Create OptionsSection for all tablets on Notebookbar

- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Change-Id: Ica5312ae9c7147c8dc969523e28d460348ba2e76
* Resolves: # 
> Set normalized view id for broadcast (ie. slide preview) thumbnails.

- kit/Watermark.hpp
Change-Id: Id1bda715723e717d6f0893dbc1aef937014076e3
* Resolves: # 
> Fix distortion on watermark text

- common/FileUtil.cpp
- common/FileUtil.hpp
- common/Util.cpp
- common/Util.hpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- test/WhiteBoxTests.cpp
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
> Stat and cleanup

- test/test.cpp
We now log the test assertion failure and exception (if any) details
with file and line number to assist in faster troubleshooting.
Change-Id: I3217458f30383cd24f3cbbe15431f2b9151744d4
> test: improve failure details

- loleaflet/src/control/Control.Notebookbar.js
Change-Id: I387d19a33c5682eef890cc9a9fb0283238ecbde9
(cherry picked from commit 1bda946b1c48608026ed07848a05ced664cc61e8)
* Resolves: # 
> Show/hide tabs on permission change for Tablets on Notebookbar

- loleaflet/src/control/Control.UIManager.js
Change-Id: I2eb4cbcd209c367a7f9a384a4745e244e8c64f30
* Resolves: # 
> Sidebar should be closed when entering readonly mode

- loleaflet/src/control/Control.Notebookbar.js
Change-Id: I97d05a9d831e4e8d30c0257ca6f1cf66ecf6c742
* Resolves: # 
> Adjust Sidebar Button offset next to X button for tablets

- android/lib/src/main/cpp/androidapp.cpp
- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- loleaflet/html/loleaflet.html.m4
This will enable notebookbar for tables
smaller devices will continue on classic mode
Change-Id: Ib74b8a0ad161d83300d807fff1fd8b3ffba11399
* Resolves: # 
> Android: Pass userInterfaceMode

- common/FileUtil.cpp
- common/Log.cpp
- common/Seccomp.cpp
- common/Util.cpp
- configure.ac
- kit/ForKit.cpp
- kit/Kit.cpp
- net/Socket.cpp
- net/Ssl.cpp
- tools/map.cpp
- tools/mount.cpp
- wsd/AdminModel.cpp
- wsd/DocumentBroker.cpp
- wsd/LOOLWSD.cpp
With these patches I was able to get everything compiled and linked. The build still fails, so no runtime testing yet.
```
sudo  cap_fowner,cap_mknod,cap_sys_chroot=ep loolforkit && sudo  cap_sys_admin=ep loolmount
sudo: loolforkit: command not found
```
> Assorted FreeBSD fixes

- loleaflet/src/map/handler/Map.Keyboard.js
Change-Id: I663fb4a1a108d78eec7bc4d3bc0c07eba294173c
* Resolves: # 
> Use only ThisIsAMobileApp control

- kit/Watermark.hpp
Change-Id: I8fac121f94c127518aadd10a6eac4c9f0e496242
* Resolves: # 
> Rotate watermark pixels by 45 degree

- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/insert_formatting_mark_spec.js
Change-Id: Ifad0e21de6ccd74f9d64951bd4e971d6ad92ca09
> cypress: update tests for co-6-4 branch.

- loleaflet/Makefile.am
- loleaflet/descriptions/google-play.html
Change-Id: I5e65b1baa30309b7558e5b596bc1b25d8e4c9e2d
> Translate the store descriptions and release notes via Weblate.

- loleaflet/src/map/handler/Map.Keyboard.js
Change-Id: Ieec5779cfbb6c864279ad4f725ed10a1860ce7a5
> ChromeOS: Fix loosing textarea focus when using arrow keys

- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
Add test for underline text shape.
Signed-off-by: Thais Vieira <thais.vieira@collabora.com>
Change-Id: Ia71b891d78bf621aec24d90e105fed1b32152528
> cypress_test/impress: Add test for underline text shape.

- loleaflet/src/map/handler/Map.Scroll.js
Change-Id: Iaccda3e98cca17dbd9a2099293ccbc15e434d8f1
> Trackpad scrolling on Chromebook

- android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java
Change-Id: Ie24817ac0770516b50256da04a362c87fca3b0d4
> Android: create new document labels are tappable now

- cypress_test/integration_tests/mobile/calc/formulabar_spec.js
To make it more stable.
Change-Id: Ib9c8878bdf266733ec03eb3ba018035b115c7f7d
> cypress: update this formulabar tests.

- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
Change-Id: If98fef3d53b190c79335306f4e81d59eda8e6f8c
* Resolves: # 
> Created a Cypress test for More option in border style in Desktop Calc

- loleaflet/css/mobilewizard.css
Change-Id: Ib12420fc5e2807e1e3f49abfe6d829f781fe381c
> Mobile: toolbar-down: Remove unnecessary down-sizing of active icons

- loleaflet/css/mobilewizard.css
Change-Id: Ic90464d225aa40f464159a22c4cd7c62884a5592
> Mobile-wizard: Fix disabled btn contrast and re-use vars

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/map/handler/Map.TouchGesture.js
Fixes https://github.com/CollaboraOnline/online/issues/398 .
Change-Id: I7ce26a45f2487ad18351ff382283b5c5167985c6
* Resolves: # 
> Ignore pan gestures while selection handle is being dragged

- loleaflet/src/control/Control.ContextMenu.js
- loleaflet/src/unocommands.js
Change-Id: Ic7700f32ab93e0150ad2242dd178a767c9e1d109
* Resolves: # 
> Accept changes tracking entries in context menu

- loleaflet/src/map/Clipboard.js
Change-Id: Ic6c84681d79af936c3f2e9d0ca983ecbb100e6fb
> clipboard: use input fields if active

- loleaflet/src/map/Map.js
Change-Id: If124eced58e012720f26030dd27b8f432a9b9081
* Resolves: # 
> Reload annotations after idle/reconnect

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarWriter.js
Remove leftovers after old tooltips
Change-Id: I935285150ed35c922fbcddbe7ff3af9a7c07fd34
Reviewed-on: https://gerrit.libreoffice.org/c/online/+/103682
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Andras Timar <andras.timar@collabora.com>
* Resolves: # 
> Use correct position for sidebar tooltips

- loleaflet/css/device-tablet.css
- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.Notebookbar.js
Change-Id: I319c4bc613adcf7d00a8c51e51cfa55ede25c7ec
* Resolves: # 
> Make notebookbar tabs pannable on tablets

- kit/ForKit.cpp
It is possible for the jail directory cleanup
to fail, if there are still references to at
least one file in the jail. In those cases we
keep the jail path around so we can retry the
next time we cleanup a jail. This reduces
the chance of leaking jails until restarting
the service.
Change-Id: If6116ef598afc91063de71c66870bd6426a971ba
> wsd: retry jail cleanup if it fails

- loleaflet/css/loleaflet.css
Change-Id: Id4a1c4c61b433108b30e348ee1c6573e2fa1f509
> Loleaflet: contextMenu: Fix submenu style and arrow on hover

- loleaflet/css/toolbar.css
- loleaflet/src/control/Control.StatusBar.js
Change-Id: I602b78823d45e8ce13f641515669a70016c8c88f
> StatusBar: InsertMode: differentiate between insert and overwrite mode

- ios/CollaboraOnlineWebViewKeyboardManager/CollaboraOnlineWebViewKeyboardManager.m
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/map/handler/Map.TouchGesture.js
> Two cherry-picks

- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
Add Cypress tests for font color.
Ticket: T24711
Signed-off-by: Thais Vieira <thais.vieira@collabora.com>
Change-Id: I583f93987ee9ec98b760cfd009628480faf71b31
> impress/cypress: add tests for font color.

- loleaflet/css/toolbar.css
- loleaflet/css/w2ui-1.5.rc1.css
Change-Id: Ie42c11a4a63d4e9f467b65ee71a9178f695d4479
> Toolbar-down: fix Selectors inconsistencies, make arrows react (flip)

- loleaflet/css/toolbar.css
Change-Id: Iac717395eb7012815b2bd9b5448ad40ced76d471
> Toolbar-down: zoom select flip arrow when opened

- common/MessageQueue.hpp
Should no longer be needed since the unipoll transition.
Change-Id: Ie534cad7da0cfa54099175a86bc28dd16c738890
> Remove obsolete locking and conditions around MessageQueue

- loleaflet/css/menubar.css
Change-Id: I38f8b6db97ca91901657b1738a87b4e40c2083a4
> leaflet: fixed menu entries being overlapped by menubar

- loleaflet/css/spreadsheet.css
Change-Id: Ib6980d284d5f1b22337320271106cad0bd0744d2
> leaflet: use crosshair cursor for autofill marker in calc

- loleaflet/src/layer/marker/TextInput.js
Our existing function getValueAsCodePoints() returns an array of
integers that are Unicode code points, as its name says. (Code points
can be larger than 65535, especially for emojis and interesting
scripts). It does not return an array of UTF-16 code units (which are
always less than 65536).
Still, the code used the JavaScript function String.fromCharCode() on
the elements of the returned array. That function expects UTF-16 code
units, and it simply truncates the argument to 16 bits. This obviously
leads to very wrong results.
There is a function String.fromCodePoint() that would work, but it
isn't present in MSIE so we can't use it. Instead, introduce a new
function codePointsToString() that works properly, producing surrogate
pairs as necessary.
Additionally, the code in …
> Fix various problems in handling of non-BMP code points

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I87c83a22497a385793c63eed283e037aa632c424
* Resolves: # 
> jsdialog: accept direct boolean values

- loleaflet/admin/admintemplate.html
- loleaflet/admin/src/AdminSocketAnalytics.js
- loleaflet/admin/src/AdminSocketBase.js
- loleaflet/admin/src/AdminSocketHistory.js
- loleaflet/admin/src/AdminSocketLog.js
- loleaflet/admin/src/AdminSocketOverview.js
- loleaflet/admin/src/AdminSocketSettings.js
Change-Id: Ifcf259aee446196cc6e8269a540a6514e628e4a8
* Resolves: #71
edit - Message has been updated to "Server has been shutdown please reload the page"
> added vex-overlay in admin console when Wsd shutdown

- loleaflet/src/control/Control.Tabs.js
- loleaflet/src/unocommands.js
Change-Id: Idd4857b9b36b09d549909330bd75dd385daeaaf3
new options added:
move sheet left
move sheet right
move/copy dialog (desktop online)
> leaflet: provide easy way to rearrange calc sheet

- loleaflet/admin/src/AdminSocketBase.js
Change-Id: Iad1cb19b68399e33cb852ceef4f5639ff2b52cab
correction in grammar in loleaflet/admin/src/AdminSocketBase.js
> leaflet: correct grammatical error

- loleaflet/css/toolbar.css
- do not use horizontal scroll
Change-Id: I1ed11035188c93f7539eb2c031c5d180d6587977
> Toolbar-down: menu: display scroll only when necessary

- g
Change-Id: Ie48782075d7ebed245577ae1c0db63bc557fa57a
> g backport: add a subcommand to easily backport all commits of a PR

- loleaflet/images/lc_selectbackground.svg
- loleaflet/src/control/Control.NotebookbarImpress.js
Change-Id: Icfc511b8da029fee4f4f773c5900e2452808fb59
* Resolves: # 
> notebookbar: add select background for impress

- kit/Watermark.hpp
Although we already save it for 256x256 regular
tiles, we use smaller tiles for preview requests
everytime there is a preview request the pixmap has to
recreated. Used unordered_map instead to keep different
resolutions saved for re-use
Change-Id: I3ced6b08b6e5f8096195b253abba8bb5afdffa3c
* Resolves: # 
> Save Watermark bitmaps per user for re-use

- g
And make the pull request query a bit more generic, so this can be
reused for other repos as well.
Change-Id: Ic231367bcf50f86b41430b48f752bb05d4e8d25f
> g backport: fix a temp file leak

- net/Buffer.hpp
- test/WhiteBoxTests.cpp
Change-Id: I4ad9ce7710f7f25884ca2ab31aabd82e2dc5be8e
* Resolves: # 
> Fix unit test to not rely on under-defined behavior.

- loleaflet/admin/admintemplate.html
- loleaflet/admin/src/AdminSocketAnalytics.js
- loleaflet/admin/src/AdminSocketBase.js
- loleaflet/admin/src/AdminSocketHistory.js
- loleaflet/admin/src/AdminSocketLog.js
- loleaflet/admin/src/AdminSocketOverview.js
- loleaflet/admin/src/AdminSocketSettings.js
> admin: added vex-dialog in admin panel when WSD shutdowns

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I185d5f731a00f2f7065e998c9e7ee87714384cc7
> leaflet: "table" in "Insert table" should start with capital T

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
> jsdialog: desktop version of frame and listbox

- loleaflet/Makefile.am
- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
> Split JSDialogBuilder into desktop and mobile builders

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.JSDialog.js
Change-Id: Ib83c62032c45b3d4e4cf9d92be8d4c4acaa55d80
* Resolves: # 
> Autofilter css fixes

- loleaflet/css/jsdialogs.css
Change-Id: Id507cebd9694de85b0b5ba6988cc32ad303e87d2
* Resolves: # 
> jsdialog: limit listbox height

- loleaflet/src/control/Toolbar.js
Change-Id: Iebf631b35ea1a0741e1356dfccb385dda915a9ce
> About-dialog: Add product name as a CSS class

- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I2d7a91fbb696fff77b29143593066db781eba2dc
* Resolves: # 
> Add new debugging layer for canvasTileLayer.

- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/map/Map.js
Change-Id: I9cec45f281b4f7195b333006bc0aa80dc8f28b32
* Resolves: # 
> CanvasTileLayer for Impress and Writer.

- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
Signed-off-by: Thais Vieira <thais.vieira@collabora.com>
Change-Id: I959a7bc455371504897e03dcc0be8b26178b0202
> impress/cypress: add tests for font size and font name.

- kit/ChildSession.cpp
Signed-off-by: bayramcicek <mail@bayramcicek.com.tr>
Change-Id: I735b9fb8f2e83da08eb50a6767cf127a80103cef
* Resolves: #214 
> Port to Util::make_unique for kit/ChildSession

- loleaflet/src/map/handler/Map.FileInserter.js
Change-Id: Iaa4134626a20b8852f26d00b4386380ffbb5d259
inserting image background in impress did not work in first try
> leaflet: fixed image background not being inserted

- loleaflet/css/device-tablet.css
following addendum form:
https://github.com/CollaboraOnline/online/commit/35c93f06d2b74c419fc3951fb36ec34117817dd0#diff-9d59bc00285529dcd71cc9eecc071f54e3a854ebf558848482dd9c5a3e381dccR69
Change-Id: I04d92ac9398504f3bd0a2f7d47dcf267ede18966
> Tablet: Notebookbar: Tabs: hide scrollbar

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/unocommands.js
Signed-off-by: Ayhan Yalçınsoy <ayhanyalcinsoy@pisilinux.org>
Change-Id: Ic2fc1720eceaebff87197c27b16c93a51bf65dbb
* Resolves: #781 
> Calc:recalculate command is added at Data menu

- loleaflet/css/device-mobile.css
Change-Id: Id9778057c5b0db070a987e0286aff977cb01b2cc
> Mobile: make sure no box-shadow is ever applied to w2ui-button

- wsd/LOOLWSD.cpp
Change-Id: I3050fd5f9e66174ece03620e956ee394684f369f
> clipboard: give a more explicit clustering error earlier.

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I2d7972a8bde1108648f867a3a5c4e65a98472556
* Resolves: # 
> jsdialog: Add headers support for treelistbox

- loleaflet/admin/adminHistory.html
- loleaflet/admin/adminLog.html
- loleaflet/admin/adminSettings.html
This is needed for localization.
Change-Id: I19b648f94ca83ef7ee9f1ff8679926e6bb4afbb3
* Resolves: # 
> Admin console: Make button sizes flexible.

- loleaflet/src/control/Control.JSDialog.js
- Swap them
- Add missing classes
Change-Id: I91f1f02c7423b613f8fc3c334b01b4a138e5c9c1
> JSDialog: Fix new close button alignment and style and its parent

- loleaflet/Makefile.am
- loleaflet/css/btns.css
- loleaflet/css/jquery-ui-lightness.css
- loleaflet/css/jsdialogs.css
Change-Id: Ib4518c60a6304ac175290e5231ed25738c0d44ef
> JSDialog: style btns, add generic btns file and reuse, fix font-family..

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Id2b5afcf2e3d831e6fd058a89495e89c59da8178
> jsdialog: add missing 'dialog' handler

- loleaflet/css/jsdialogs.css
and make sure contents do fill available space
Change-Id: I74fdfc50ac888c08f82077c78b16ddda8daaf845
> JSDialog: Fix pseudo table-rows dimension (actually they should be tables)

- loleaflet/css/jsdialogs.css
- Re-use existent SVG
- Make it interactive depending if it's expanded or collapsed
Change-Id: I9affb8d6809ce14e80883873c18f2fb9a149a5c5
> JSDialog: Improve expanders

- loleaflet/css/jsdialogs.css
Change-Id: I2072766bf654b3b97ac6a125db714162e3dc2260
> JSDialog: Fix root-container margins, Make labels react on hover, checkbtn

- loleaflet/css/mobilewizard.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
also move it from statics as we will use inheritance to
get correct implementation
Change-Id: Iefc2e37f31e10dfa890f11a8aa621353fbc188df
* Resolves: # 
> jsdialog: split spinfield implementation for mobile and desktop

- loleaflet/css/jsdialogs.css
Change-Id: I5ed7bafc3403232cb2b86ba97a7d3ba9a0ad65ef
> JSDialog: Fix input text line height and repective btn sizes and paddings

- loleaflet/reference.html
- loleaflet/src/core/Socket.js
Change-Id: I9a8abc4ece563954623d4de284d20417749dd77e
* Resolves: # 
> wopi: send file name with saveas response

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I5d69d13e63526e770f35f3f25577cc2774f96ddb
> JSDialog: PivotTable: Find parent container of #listbox-fields and apply divider

- loleaflet/css/btns.css
- loleaflet/src/control/Control.JSDialogBuilder.js
> jsdialog improvements

- test/WhiteBoxTests.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/FileServerUtil.cpp
Change-Id: I4995d871c309ea3a8c1126388f1ad345886c5c37
* Resolves: # 
> wsd: allow different UI mode for different views

- common/FileUtil.cpp
- common/JsonUtil.hpp
- common/LOOLWebSocket.hpp
- common/Log.hpp
- docker/from-packages/scripts/start-collabora-online.sh
- kit/ChildSession.cpp
- kit/Kit.cpp
- test/UnitWOPIHttpHeaders.cpp
- tools/Config.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/FileServerUtil.cpp
- wsd/RequestDetails.cpp
- wsd/RequestDetails.hpp
- wsd/Storage.cpp
- wsd/TraceFile.hpp
* Misc improvements and cleanups.
> Housekeeping

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I11e526fb6c2ad209c9231d75a655a6287a4f4bb5
> added sub-menu-arrow('>') and remove kebab menu in rootComment

- wsd/Storage.hpp
Change-Id: I603a5205f111b7c8f99baecd6ed482fc9502a6d5
> WopiStorage: fix uninitialized reads

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I6e5ac9e1656a60b9d31a5d988706eeba7586cbeb
* Resolves: # 
> jsdialog: add separator control

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarCalc.js
Change-Id: I63574abff5c9c425e6c68d8163e221a2315939ba
* Resolves: # 
> Move Named ranges management to data tab/menu

- loleaflet/css/btns.css
- loleaflet/css/jsdialogs.css
Change-Id: I17f315574af9bdd8a51b43990f31d96384592c8e
> JSDialog: buttons: Fix auto filter 2button layout and fix css plus remove unnecessary floats

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Ibb84385f2e85d9f519a52521ccceefe467c0e1e5
* Resolves: # 
> jsdialog: setup dialog id

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I1d2b76ae479e00e39e3596014a10ffd1c28252d9
> JSDialog: Select: Fix font and reuse jquery ui

- loleaflet/css/toolbar.css
- loleaflet/src/control/Control.MobileTopBar.js
so we can have insert viewcomments with different icons
Change-Id: If38b49ca3e02db20c45284d8b2980c2114b8f28b
> Mobile: Add new viewcomments element

- wsd/DocumentBroker.cpp
- wsd/TileCache.cpp
Avoiding some debug code ending up in the product.
Change-Id: If37b2986f134986a33b9dd5b4729b50c56cbc248
> Check ENABLE_DEBUG conditional correctly.

- loleaflet/css/btns.css
- loleaflet/css/jsdialogs.css
Change-Id: I19b5de53085a22a516941f9e45a98853a80bdac7
> JSDialog: make icon btns share existent styles, Fix dialog exceptions, use dialog ids

- loleaflet/css/btns.css
Change-Id: I8f718371584d8fce1078179a2312f585ee8adcce
> JSDialog: Fix disabled btn

- net/Socket.cpp
Change-Id: I6b38a68462c6c89a95ded5ac795702c18a7b762a
> Fix --disable-ssl build.

- loleaflet/css/btns.css
Change-Id: I1bb3c0e3318bc3e83982892861101ead7c91f4e5
> JSDialog: Statistics functions: fix reference btns

- loleaflet/css/mobilewizard.css
Change-Id: I1dc530bd4f5e5aca853c811fc06884cbf40e2ef7
> JSDialog: Statistics: Fix spinfields and respective labels

- loleaflet/css/jsdialogs.css
Change-Id: Iaed825d98c4eea7fc4256d39aedb6e76b982e682
> JSDialog: Set radiobutton and respective labels

- cypress_test/integration_tests/multiuser/calc/sheet_operations_user1_spec.js
- cypress_test/integration_tests/multiuser/calc/sheet_operations_user2_spec.js
- cypress_test/integration_tests/multiuser/impress/slide_operations_user1_spec.js
- cypress_test/integration_tests/multiuser/impress/slide_operations_user2_spec.js
- cypress_test/integration_tests/multiuser/writer/paragraph_prop_user1_spec.js
- cypress_test/integration_tests/multiuser/writer/paragraph_prop_user2_spec.js
- cypress_test/integration_tests/multiuser/writer/sidebar_visibility_user1_spec.js
- cypress_test/integration_tests/multiuser/writer/sidebar_visibility_user2_spec.js
- cypress_test/integration_tests/multiuser/writer/simultaneous_typing_user1_spec.js
- cypress_test/integration_tests/multiuser/writer/simultaneous_typing_user2_spec.js
Change-Id: Ia353c6933fae8098ae983d2196added263ba5784
> cypress: pass test state to afterAll() method in multi-user tests too.

- loleaflet/css/loleaflet.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Iccd3976fca0c8a5f4b55267b5abb783cdb8d7fe2
* Resolves: #949
> added number of replies in rootComment

- loleaflet/css/btns.css
- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- radio buttons
- label
- listbox and listbox-arrow
Change-Id: Icb3f4171a431fe794c2a97848952219a6bb2bee0
> JSDialog: Fix listbox disabled value and style surrounding elements

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/calc_mobile_helper.js
- cypress_test/integration_tests/multiuser/interference_user_spec.js
I see some random test failures:
"An uncaught error was detected outside of a test:
SyntaxError: The following error originated from your test code, not from Cypress.
> Invalid or unexpected token"
There is no backtrace or code pointer or anything to find out
what is the actual problem, but it might be related the missing
import of 3rd-party code.
Change-Id: Ia2243852e825eee18c226d89fd17e92960daa129
> cypress: import 3rd-party packages everywhere they are used.

- cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
- loleaflet/src/layer/AnnotationManagerImpress.js
- loleaflet/src/layer/tile/CalcTileLayer.js
Change-Id: I90bb301c35ba6d52c26a22dd0b686961b94181fd
> leaflet: open comment wizard on comment insertion

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I40d21f395239c7394c9e4ae0af3facd11100b0e1
* Resolves: # 
> jsdialog: disabled state for treeview

- loleaflet/css/jsdialogs.css
- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialogBuilder.js
tr should be inside the table...
Change-Id: I90c983f3d3446549b04e3b4379612dba7b762750
* Resolves: # 
> jsdialog: fix grid nodes

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Ia07a4ffd59be3b19dc38c0904f15086b9f3fe2c0
> JSDialog: Checkbox's parent shouldn't get dragged or selected plus label improvements

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Ifecaef9726a66f4dad840ced2d29ebe5d31026e9
> jsdialog: merge columns in grid

- loleaflet/css/btns.css
- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Ic0b2d36bb84b2521e2cb96fe1c754480f1fa3395
> jsdialog: button box

- loleaflet/css/btns.css
- loleaflet/css/jsdialogs.css
- loleaflet/css/mobilewizard.css
- loleaflet/src/control/Control.JSDialogBuilder.js
> mobilewizard buttonbox & textarea fixes

- autogen.sh
- common/security.h
- configure.ac
- scripts/refresh-git-hooks
> Some more FreeBSD adjustments

- loleaflet/src/control/Control.JSDialog.js
Change-Id: I2759d5ceba222cfc34528ca8cf1087b2d70be6bf
* Resolves: # 
> jsdialog: make draggable also on tablet

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
Change-Id: I010f616e4601789fde36f8143226fe99bac3bb1a
* Resolves: # 
> jsdialog: support step in spinfields

- loleaflet/src/control/Control.JSDialog.js
Change-Id: Id0a428280db2811efcd0f355f6109984179c50af
* Resolves: # 
> jsdialog: fix dialog jumping

- loolkitconfig.xcu
Add default option to execute macros with level 1
Change-Id: I6292edb935e2acbd366662ea4f1c49c471349cbc
> config: add "Macro Security" default value

- loleaflet/css/btns.css
- loleaflet/css/jsdialogs.css
Change-Id: I17f315574af9bdd8a51b43990f31d96384592c8e
> JSDialog: buttons: fix css plus remove unnecessary floats

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/unocommands.js
The ".uno:RunMacro" will pop up a dialog
to select a visual basic script to execute
server side.
Change-Id: Ide4143b0fab15b9882c5163d301a77016f81a7e8
> loleaflet: add new menu item "Run Macro"

- common/security.h
- kit/ForKit.cpp
Change-Id: If49be334cb1380daf1eaf24c7007f1b004754304
> Root actually has all the capabilities.

- .gitpod-files/loolwsd-gitpod.xml
- loleaflet/html/loleaflet.html.m4
- loleaflet/src/control/Toolbar.js
Change-Id: I9fa6e33a8012065262885a5a0ef1c855e2df5b53
> remove traces of "LibreOffice Online Personal" brand

- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/vector/Canvas.js
- loleaflet/src/layer/vector/SVG.VML.js
- loleaflet/src/layer/vector/SVG.js
- loleaflet/src/map/Map.js
Change-Id: If7e38c591e6b4b52fa16a47f4cc3f1c015ee0901
> canvas layer: _animatingZoom is no more needed too.

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/tile/WriterTileLayer.js
Change-Id: I5360922453f962a45e1d4cf7c418f2bbfa3a31ed
* Resolves: #990 
When there are no reply in comment then root comment shows kebab menu ,otherwise it shows submenu arrow
> add/remove kebab and sub-menu-arrow when necessary

- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I09e41341321b2cf03903d39533aba722abe5d2e4
update also writer and impress tab compare to calc #1072
> NB: Update writer and impress file tab according to calc #1080

- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: I36ede47c5bf917d5620a3dddeaa1e8133cc638a4
> NB update Format Tab

- loleaflet/css/notebookbar.css
Change-Id: I591f14db39261c7d319d179d98af122c06b028c9
> NB Writer home tab align bullet commands

- loleaflet/src/map/handler/Map.Keyboard.js
Change-Id: I95ed79cf557b53b6a6695e98eda7684f70a4dd24
> leaflet: prevent text editing in master view

- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/control/Parts.js
- loleaflet/src/map/Map.js
> Throttle previews patches forwardport

- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/control/Parts.js
Now the scrolling works as expected with the
parts that are invisible
Change-Id: I8fd41624befaea49978d43cf4e88249c47dc7534
* Resolves: # 
> Fix browsing parts visibility with PageDown/PageUp

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- android/lib/src/main/res/values/strings.xml
Change-Id: Ie08fcf77560ff285b7f9a94253439e551a08aefb
* Resolves: # 
> android: Fix crash when could not load the document

- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: Idb3dda5152c2baf7e967dccbbd442675c7d6a5e9
> notebookbar: hide non-async dialogs in graphic tab

- loleaflet/css/notebookbar.css
Change-Id: Ia93ff33742d16417a2a325ffcf649b2ca3499e23
Before
After
> NB shortcuts-bar vertical alignment update

- cypress_test/Makefile.am
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/desktop/writer/copy_paste_spec.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
- cypress_test/package.json
- loleaflet/src/control/Toolbar.js
Change-Id: I15c060e5eac1993116828dfaefe8916030fe2b63
> cypress: disable welcome dialog via loolwsd config.

- loleaflet/src/layer/marker/Annotation.js
Change-Id: I8923fdec4b09a6d7c8c8bc6f248d1ca671fd252c
earlier we could not add comment due to JS errors in mobile
> leaflet: add mousewheel handler only in desktop

- loleaflet/src/control/Control.Toolbar.js
- loleaflet/src/layer/marker/TextInput.js
Change-Id: Ifa368ac45e32183c1c0e242be44131afd995d0ce
> leaflet: moved undo handler for text in TextInput.js

- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/control/Parts.js
- loleaflet/src/map/Map.js
> Throttle preview requests on impress

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
Change-Id: Ic9b6765ec4d881091cc3b72b7e693b93fa598426
* Resolves: # 
> android: Fix typo on onBackpressed

- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/impress/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/insert_object_spec.js
- cypress_test/integration_tests/mobile/writer/toolbar_spec.js
Change-Id: I25ff9c590aa12d1787d8966cc4f68151ed8d505f
re-enabled the annotation tests desabled in 1c1274a5fd8660f349b944c4ddf92e848088f1e0
> cypress: modified annotation tests to work with comment wizard

- cypress_test/integration_tests/mobile/impress/annotation_spec.js
- cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
Change-Id: I8c1b4e6a679f31b9ebfa814b67f18b25eab3d2be
> cypress: fixed test and enabled missing test for annotation

- loleaflet/css/toolbar.css
> leaflet: use fixed width for the toolbar style menu drop down

- loleaflet/src/control/Control.MobileTopBar.js
Change-Id: I032f5430cd96cc66501aa813df2dd06f6aa4d7a6
this icon was added to writer but was missing in impress and calc
> leaflet: use new view comments icon in topbar

- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.UIManager.js
> notebookbar readonly

- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/TileLayer.js
When the "Macro Security Warning" message is received,
there are no instances of the document layer yet,
because the server does not have an instance for Model/View/Conroller.
Change-Id: I1ac36fb1553d8bd3ed48b86e75bf32d1b12d1d86
> jsdialog: move onJSDialog to Socket class

- wsd/LOOLWSD.cpp
Change-Id: Ie83ec794eb0962b6ecf3f1f7b201390d19fb0958
* Resolves: # 
> Remind admins of the costs of high log levels.

- loleaflet/src/layer/tile/CalcTileLayer.js
Change-Id: I0ff94444334ac2a9112475762bb9c64b44641167
* Resolves: # 
> CalcTileLayer: getSpanData function is optimised.

- loleaflet/src/layer/marker/TextInput.js
Change-Id: I3e080e6097a9819549ccaa8f4fa2c3191e228b97
> leaflet: clear text area using appropriate helpers

- kit/ChildSession.cpp
- kit/ChildSession.hpp
When the "Macro Security Warning" send clicks events,
the is no instance of Model/View/Controller yet.
So adjust to send to global events.
Change-Id: Idc395cfb86548481bbadc22874293d7d6238db89
> kit: send early dialog event to server

- kit/Kit.cpp
Change-Id: If5bb5727b8842f30b60f4c9cee392f94d1984dca
* Resolves: # 
> Drop cap_chown after use.

- loleaflet/src/control/Control.AutofilterDropdown.js
Change-Id: If4a0583e4160726bd0801a029161ba09442ab4f3
* Resolves: # 
> autofilter: don't allow to place outside screen

- loleaflet/.gitignore
- loleaflet/Makefile.am
- loleaflet/src/control/Control.ColumnHeader.js
- loleaflet/src/control/Control.Header.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/tsconfig.json
Change-Id: I69929595450c48ed45326c21743fbde3babc9803
* Resolves: # 
> Introduce CanvasSectionContainer class.

- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.Toolbar.js
- loleaflet/src/control/Control.TopToolbar.js
Change-Id: I283082d7d78359861a7920290e99f90393ef6588
* Resolves: # 
> Mark current linespacing setting in menu

- loleaflet/src/layer/tile/CanvasTileLayer.js
Change-Id: Ie0796d045e477c00c4edb1efa49e6de0bf2f95bc
* Resolves: # 
> CanvasTileLayer: Fix offset variable setting.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
Tested on mobile device and desktop. Event combinations are added.
Change-Id: I97087921c7cc4de292e8919bcc8a99fd86d27806
* Resolves: # 
> CanvasSectionContainer: Improve event handling.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
There was a regression because of the recent improvements.
Change-Id: If0b77349a65f2503b29de7ca5e967282c979b6bf
* Resolves: # 
> CanvasTileLayer: Fix image rendering.

- loleaflet/css/mobilewizard.css
Change-Id: I7866eed069857a9762c91d96407a710be3ae2187
> Mobile: Calc: Misaligned text in Validity > Error Alert

- loleaflet/css/toolbar.css
- loleaflet/images/lc_line.svg
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.NotebookbarWriter.js
- loleaflet/src/control/Control.TopToolbar.js
- loleaflet/src/unocommands.js
Change-Id: Id2a07308f5e9dc5730f69e4b4b5a9031102349ab
* related: #1139 
> Writer: Expose Insert Line on classic and NotebookBar mode

- loleaflet/src/control/Control.NotebookbarImpress.js
related: #1139
Change-Id: Iaa520f925eaf5808d7b1f9c3cf90bac0591c6640
> Impress: Expose Insert Line on classic and NotebookBar mode

- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
> Notebookbar JSON formatting

- loleaflet/src/control/Control.ContextMenu.js
Change-Id: Idd963d2f5789dbec4e1fb182d5e96925b64fabaa
Is it ok to add this commands or are there some troubles?
> add clone and clear to ContextMenu

- net/Socket.cpp
- net/WebSocketHandler.hpp
Change-Id: I1e6bc4724672d3e86ad997d7b13ff9db87aade1e
> wsd: chrono type-safe usage

- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/core/Socket.js
> Jsdialog updates

- loleaflet/css/jsdialogs.css
Change-Id: I2770137acb9c64bca79c21f0e99dfaabb2701217
> JSDialog: force checkbox style

- loleaflet/src/control/Control.JSDialog.js
Change-Id: I7ee2cf4f1bc0d39a13b8689e3ab1db395665d201
* Resolves: # 
> jsdialog: draggable only using titlebar

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
> Chart line settings

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
> Cypress test calc top toolbar

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
- loleaflet/src/control/Toolbar.js
Change-Id: Ic100b0857d9617c5fcdf3d2ea8a992206cd0cf5d
> Notebookbar: File: Promote First actions to bigtoolitem

- loleaflet/css/notebookbar.css
Change-Id: I96b21a616756d79ebb45a1d12e8bdeb4dfabc80d
Before
After
> Writer NB: Layout tab fix icon size of align commands

- common/security.h
- kit/ForKit.cpp
- tools/mount.cpp
Change-Id: Idc9db40c00d41c95160db130eb324c487f14de17
* Resolves: # 
> check if we run in a container

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/layer/tile/CanvasSectionContainer.js
Change-Id: I80821e25f78f8d90387faf54d31c1889773a3666
* Resolves: # 
> Add fontwork also in calc

- Makefile.am
- cypress_test/Makefile.am
- loolwsd.xml.in
Change-Id: I7fd725a83b0e9ca1012f2c0e0c3bf038e5fa0059
> wsd: disable ssl by default, enable ssl termination by default

- loleaflet/src/layer/tile/GridLayer.js
Change-Id: Iacd279f741c35703807f14a9798fbe2ef0f45d50
* Resolves: # 
> Fix calc text-input focus problem on Android

- wsd/LOOLWSD.cpp
Change-Id: I6c5042578a3b718e2305139c0e4ea390b4a43ed3
> wsd: test: don't report test timeout outside of tests

- Makefile.am
- net/NetUtil.cpp
- net/NetUtil.hpp
- net/Socket.cpp
- test/Makefile.am
Move the connect function into the NetUtil
translation unit to aid using it for the
upcoming async socket logic.
The NetUtil should also come in handy for
the miscellaneous network helpers we have.
Change-Id: I2ee0c6e3e1769fd87572d7407d3b4979b59ffe6a
> wsd: new NetUtil file for network utilities

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I3ce2be9cc6362c09725fe1692e6853f195274211
It work, is it sexy, I don't know.
> No Tooltip when command has icon + label #1029

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: Id3700692706bb67b8e626b24a2ae9c10dff1f772
* Resolves: # 
> popup: improve text layout

- common/Png.hpp
Change-Id: I37a72bc966424ca1b4c30b31d9fcf88d15c11789
* Resolves: # 
> Special case opacity to avoid arithmetic where possible.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
Bugs related to ordering of sections are fixed.
addSection and createSection functions are separated.
contextMenu event is added.
Sections' drawing orders are updated for future uses.
Change-Id: I89127c97ad7b7dac4b293c4108c44cb6c4427134
* Resolves: # 
> CanvasSectionContainer: Fixes.

- loleaflet/src/control/Control.StatusBar.js
Change-Id: I93dc5c54abb3a43cdffe1b12ca3e22247ed22f67
* Resolves: #675 
changed replace function argument to search ',' globally
> leaflet: display correct number of characters in statusbar

- .gitignore
Change-Id: I4662bfa7d22c76dde316c5162510f821f694507b
> Add coolstress to gitignore

- loleaflet/Makefile.am
Change-Id: I97083c0a093a4038cb91dd618096eeb4292463fe
> loleaflet: makefile: fix builddir != srcdir

- loleaflet/css/spreadsheet.css
- loleaflet/src/control/Control.Tabs.js
Change-Id: Ibe4106aca08456410c4c524eeb8a630993737815
now in desktop, we can rearrange the sheets via drag and drop
> leaflet: support reordering sheet tabs via drag and drop

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
Change-Id: I5d34e5ec9a1caa26ecee3dbc9dc23fb43423e29b
* Resolves: # 
> CanvasSectionContainer: Add background color and border color.

- loleaflet/css/jsdialogs.css
- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- ensure control has always single parent with correct ID
> jsdialog: keep correct structure (for partial updates)

- common/Png.hpp
Change-Id: I9217193534bbed8f55faaa105b603e1560b1519a
* Resolves: # 
> Bin unused function

- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/core/Socket.js
Prepares code handling updates of widgets
> jsdialog: prepare notebookbar for partial updates

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I85e41ffc9de69de9543b8e1ccae177054a9375ac
> leaflet: fixed missing selection overlay while selecting row/column

- cypress_test/integration_tests/mobile/calc/spellchecking_spec.js
- cypress_test/integration_tests/mobile/impress/spellchecking_spec.js
- cypress_test/integration_tests/mobile/writer/spellchecking_spec.js
- loleaflet/src/control/Control.ContextMenu.js
Change-Id: I149539983897d20828dc6e32ed053c9b7e279ad4
> leaflet: blacklist language selection on misspelled words in mobile

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I1123715cfadd8e752adb8f9a6bdf697006271390
> leaflet: fixed hyperlink popup being mispositioned around the edge

- loleaflet/css/mobilewizard.css
Change-Id: I8bd166209694155f09ed958c216fc9850b01bcc4
> Mobile: mobileWizard: style comment card's contents

- net/HttpRequest.hpp
- test/Makefile.am
- test/TileCacheTests.cpp
- test/countloolkits.hpp
- test/helpers.hpp
- test/httpcrashtest.cpp
- test/run_unit.sh.in
- test/test.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.hpp
- wsd: remove debug logs
- wsd: test: improvements
- wsd: load -> download
- wsd: cosmetic
- wsd: access _isLoaded member via getter
> Preparatory patches for Async

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I97839d01d88796e3a2c8c5ff3a27c05b6802578d
> leaflet: use marker to select the reference range in calc formula

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.TopToolbar.js
- loleaflet/src/control/Toolbar.js
- prepares listboxes for partial updates
- rework of font name selector which is needed for partial updates and also dynamic switching between classic and notebookbar mode
> jsdialog: partial updates for listbox

- wsd/ClientSession.cpp
Change-Id: I4fbb05b3b703ebcd1221faafd1ab3e33a1f8f144
* Resolves: # 
> Log the DEBUG messages from client with LOG_DBG and not to stderr

- loleaflet/src/control/Control.JSDialogBuilder.js
fixes regression introduced by: https://gerrit.libreoffice.org/c/core/+/109144
> jsdialog: TreeView doubleclick to activate row

- kit/ChildSession.cpp
- kit/Kit.cpp
- kit/KitHelper.hpp
Change-Id: I6aa3b7b25ae9eff462580eb17ceaa5bc40359c53
* Resolves: # 
> Use correct naming convention

- wsd/protocol.txt
Change-Id: I19fd4ed92315908af36362368ee2fdbc8558c2ae
* Resolves: # 
> Correct description of handling of the DEBUG message from the client

- wsd/ClientSession.cpp
- wsd/protocol.txt
Change-Id: If9f3316bb07f68b609c96135227a3e06a1112786
* Resolves: # 
> Add an ERROR message from client to server that is logged with LOG_ERR()

- test/HttpRequestTests.cpp
Change-Id: I0f6a4dac4aff05be65b5a0735b5ff0c67fc4f7a0
* Resolves: # 
> Fix ENABLE_SSL condition.

- kit/ChildSession.cpp
Change-Id: I4dabc1e70b2bca6751a60e5655a530c0025b09c5
* Resolves: # 
> Add comment describing a way to intentionally induce cache inconsistency

- Makefile.am
- debian/loolwsd.cron.d
- debian/loolwsd.postinst.in
- docker/from-source/Debian
- docker/from-source/Ubuntu
- docker/from-source/openSUSE
- loolwsd.spec.in
- wsd/README
Change-Id: I2eeaed12af6ac8789151b95a9c2a2aa1fd72573b
* Resolves: # 
> On-disk cache was removed long ago, clean-up in packaging

- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
Signed-off-by: Ezinne <nnamani.ezinne@collabora.com>
Change-Id: I873654c21649f849739cd25461f3d52335ecba8b
* Resolves: # 
> Created a cypress test for Text Wrap feature in Calc top_toolbar

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I06d49a56853fe391c4d137208865498a36c7a1e3
* Resolves: # 
> eslint is pickier in the co-6-4 branch, so cherry-pick fix here, too

- cypress_test/plugins/blacklists.js
Change-Id: Id494a522e0961894cdf9e5ce56b19b781a724974
> cypress: add new Save/Print test to php-proxy/NC blacklists.

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarCalc.js
This reverts commit 6c2d725c58922c69ae69e26bb5988a9b35925c89.
Change-Id: I50c248e3d2dfc7b06a9d0d2c1da3fe8a52d26560
* Resolves: # 
> Revert "Disable Freeze panes menu & notebookbar entries on tablets."

- cypress_test/integration_tests/common/mobile_helper.js
Change-Id: I3ce151f8ebe9405c5830630e941c94ab9ef2f7ae
> cypress: make sure the cell selection is visible before run test steps.

- loleaflet/css/loleaflet.css
- loleaflet/src/control/Control.LokDialog.js
Change-Id: I2c6421b34cd6c2345981008dd1bbee494bc13ca2
> Sidebar: panelContainer is being set without height #1322

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I5e0cd6cfa6c5a5db61dcfbfa557c9ec3bc4c8977
> loleaflet: do not update cursor from other views

- loleaflet/src/core/Socket.js
Change-Id: I4cecb72acc927707b68711478c5474326d456d82
> loleaflet: server recycling: Improve message

- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
Change-Id: Iec8be699d10640154d711b47a9d11400e2aefa1b
> cypress: use checkDialogAndClose() helper method here.

- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/calc/bottom_bar_spec.js
- cypress_test/integration_tests/desktop/calc/focus_spec.js
- cypress_test/integration_tests/desktop/calc/sidebar_dialog_image_caching_spec.js
Change-Id: I46b05c8533b4f323e181d3d4fd2acc1e4626e164
> cypress: move formulabar related check into beforeAll() helper method.

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/mobile/calc/calc_mobile_helper.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- loleaflet/Makefile.am
- loleaflet/css/device-mobile.css
- loleaflet/css/spreadsheet.css
- loleaflet/html/loleaflet.html.m4
- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.ColumnGroup.js
- loleaflet/src/control/Control.ColumnHeader.js
- loleaflet/src/control/Control.CornerGroup.js
- loleaflet/src/control/Control.CornerHeader.js
- loleaflet/src/control/Control.Header.js
- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.RowGroup.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/control/Control.TopToolbar.js
- loleaflet/src/control/Control.UIManager.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasSectionProps.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/map/Map.js
Change-Id: Ia612c25b0b9e8be96daf157fdcc1b9afc979c679
* Resolves: # 
> CanvasTileLayer: Use same canvas for row & column headers.

- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I47d09ea9e3da0c60f07821dee9197cbefc7080dc
* Resolves: # 
> eslint is pickier in the co-6-4 branch, so fix the same warning here, too

- scripts/unused-js-functions.sh
I haven't found any more advanced approach to finding unused JS
functions, but this seems to produce at least some results, so better
than nothing.
There is nothing new to remove though, the last round of cleanup has
removed what was there to remove.
Change-Id: If39fecb7781cc78b30cb95da354c71d3547b7ae7
> Trivial script to find unused functions in JavaScript

- loleaflet/css/jsdialogs.css
- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.TopToolbar.js
- loleaflet/src/control/Toolbar.js
- loleaflet/src/core/Socket.js
Online part of partial updates. Merge after: https://gerrit.libreoffice.org/c/core/+/109783
> jsdialog: partial updates (co-6-4)

- loleaflet/src/layer/tile/CalcTileLayer.js
Change-Id: If436fba45bbd6669a414c20579f13ac0dadd8241
* Resolves: # 
> Bin unused STD_EXTRA_WIDTH

- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.UIManager.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/map/Map.js
- send entry field value on every key press so we can validate it in the background eg. in define name dialog
> jsdialog: update field on keypress

- loleaflet/css/jsdialogs.css
- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.Notebookbar.js
When control gets update (eg. treeview with long list, scroll down and select some entry) we should remember the position of scrollbar.
> jsdialog: remember scroll position on update

- cypress_test/README
Change-Id: I49597e73d675ab9e916f7f73e740d5a89d2884b8
> cypress: document some extra run option in the README.

- wsd/LOOLWSD.cpp
Change-Id: I4e1e4f99cd2ac3d21b9426602de11e10bdd47a61
- Changes WRN log to INF,
- Adds logging for termination flag.
> wsd: tweak SSL logging

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/CBounds.ts
- loleaflet/src/layer/vector/CLineUtil.ts
- loleaflet/src/layer/vector/CPath.ts
- loleaflet/src/layer/vector/CPoint.ts
- loleaflet/src/layer/vector/CPolyUtil.ts
- loleaflet/src/layer/vector/CPolygon.ts
- loleaflet/src/layer/vector/CPolyline.ts
- loleaflet/src/layer/vector/CRectangle.ts
- loleaflet/src/layer/vector/CanvasOverlay.ts
* Resolves: # 
* Fix indentation issues
* Comments on usages and functionality of new TS classes/functions.
* Ensure integral core-pixel bounds for cursor rectangle to avoid pixel spill at non-100% zooms.
> Follow-up fixes to PR#1341

- loleaflet/src/control/Control.NotebookbarBuilder.js
> notebookbar: add run macro in hamburger menu

- loleaflet/src/control/Control.AutofilterDropdown.js
send click event for cancel button as there is no
better way to close this docking window...
Change-Id: Id5f30e3d823b154117e9da7dca6bbbdef2422591
* Resolves: # 
> autofilter: close properly welded window

- kit/Kit.cpp
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/TileLayer.js
This allows to use help button in macro security warning.
- handles standard button in dialog
- makes hyperlink handling globally available (even without loaded document)
> Macro security warning: help button

- common/Unit.hpp
- test/Makefile.am
- test/UnitLoad.cpp
- test/UnitWOPIFileUrl.cpp
- test/WopiTestServer.hpp
- test/helpers.hpp
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd: refactor downloadStorageFileToLocal
- wsd: support FileUrl
- wsd: test: helpers
- wsd: add FileUrl tests
> FileUrl Support

- loleaflet/src/control/Control.AutofilterDropdown.js
- loleaflet/src/control/Control.JSDialogBuilder.js
> jsdialog: don't share windowId value between instances

- loleaflet/src/geo/LatLngBounds.js
Please do not remove even if unused. It can be useful in temporary
console.log() etc.
Change-Id: I2734efa3cffb8dd5e4a9923672ec179fcae3e12f
* Resolves: # 
> Add toString()

- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- loleaflet/src/layer/marker/TextInput.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasSectionProps.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/GridLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/CPath.ts
- loleaflet/src/layer/vector/CPolyUtil.ts
- loleaflet/src/layer/vector/CPolygon.ts
- loleaflet/src/layer/vector/CPolyline.ts
- loleaflet/src/layer/vector/CanvasOverlay.ts
- loleaflet/src/map/handler/Map.Keyboard.js
* Resolves: # 
Migrate text/cells selections overlays to main canvas
> Migrate text/cells selections overlays to main canvas

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Temporary hide Run Macro dialog from menubar and notebookbar
> temporary hide VBA dialogs

- .gitignore
- loleaflet/Makefile.am
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TilesSection.ts
- loleaflet/src/layer/vector/CanvasOverlay.ts
It now detects and compiles ts files in specified directories.
Change-Id: Ia8a399650480001193be7177b05b5cbb195a98c7
* Resolves: # 
> loleaflet: Update makefile for typescript files.

- loleaflet/js/w2ui-1.5.rc1.js
- scripts/unocommands.py
- scripts/untranslated.py
Signed-off-by: umutbayramoglu <umut265@gmail.com>
Change-Id: I7c2565a01605846201cb4a35564eb52b52491fe8
* Resolves: # 
Removed unused variables according to LGTM alerts:
https://lgtm.com/projects/g/CollaboraOnline/online/snapshot/ecea5b0770264cc618e58949dc86dc03fa0e7ba2/files/scripts/unocommands.py?sort=name&dir=ASC&mode=heatmap#x690f726a2a4b2bf:1
https://lgtm.com/projects/g/CollaboraOnline/online/snapshot/ecea5b0770264cc618e58949dc86dc03fa0e7ba2/files/scripts/unocommands.py?sort=name&dir=ASC&mode=heatmap#x690f726a2a4b2bf:1
https://lgtm.com/projects/g/CollaboraOnline/online/snapshot/94cd7681511cd6bbfc389d6d8ba4744976031fdc/files/loleaflet/js/w2ui-1.5.rc1.js?sort=name&dir=ASC&mode=heatmap
> Remove unused variables

- .gitignore
Change-Id: I3a04b85558155e060bd0ed8ae67508d4a42afbfa
> Ignore CanvasOverlay.js

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.Toolbar.js
- loleaflet/src/control/Control.TopToolbar.js
- loleaflet/src/control/Control.UIManager.js
- loleaflet/src/core/Socket.js
- loleaflet/src/map/Map.js
- loleaflet/src/map/handler/Map.StateChanges.js
- loleaflet/src/map/handler/Map.WOPI.js
Change-Id: Id84a4feb8f37357d7de8f9cfebea3612751709b1
* Resolves: # 
> add support for changing ui mode dynamically

- loleaflet/css/spreadsheet.css
Change-Id: Ic04b8acc43b2863bd3f3483d7d3f14438bf8fd6f
> leaflet: aligned sheet grid with headers

- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
This introduces DocBroker's SaveManager and StorageManager, internal classes to manage the save and upload states.
> Save and Storage Managers

- loleaflet/Makefile.am
- loleaflet/mocha_tests/CBounds.test.ts
- loleaflet/src/control/Control.ColumnHeader.js
- loleaflet/src/control/Control.Header.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TilesSection.ts
* Resolves: # 
This includes fixes related to zoom animation, selections in headers and a 'make check' improvement in loleaflet.
> Misc. canvas related fixes

- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/map/handler/Map.Keyboard.js
> jsdialog: handle ESC key to close (co-6-4)

- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/Kit.cpp
- test/UnitWOPITemplate.cpp
- test/WhiteBoxTests.cpp
- wsd/Storage.cpp
- wsd: simplify UnitWOPITemplate
- wsd: download templates by wsd
> Download Templates by wsd

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
It wasn't detecting negative values.
Change-Id: I93a633e84828ef18d1b4fc4246065421e63748b9
* Resolves: # 
> CanvasSectionContainer: Drag distance check is updated.

- loleaflet/css/jsdialogs.css
- apply max-width
- fix text-transformation
- fix color
Change-Id: I6e40b8ab1b4fbeaee0bd6e97b3dae211c848505e
> Macro warn jsdialog: style

- common/Log.cpp
- common/SigUtil.cpp
Change-Id: I0eed9c6d3adc7c94f84f3f2115276df1d38f0a0f
> common: add tag string to extract backtrace logs

- loleaflet/src/control/Control.Header.js
Change-Id: If8013f0c8ea455adcb3032f1cf39b10b074e89c4
> leaflet: fixed context menu not working on first row/col

- loleaflet/css/btns.css
- loleaflet/css/override-vex.css
Change-Id: I7787588ccce5ce4042cdd553b781114cf0627fbe
> Fix Vex btns and input fields: consistent style

- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/insert_formatting_mark_spec.js
Change-Id: I440db4de4846879b279c2f34dae365de484eff33
> cypress: update tests after recent change of core UNO string changes.

- cypress_test/integration_tests/desktop/impress/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/impress/apply_paragraph_props_shape_spec.js
- cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
Change-Id: I67d09062313de939efb6bf2a83ad6fbf4fb7313c
> cypress: update shape related tests: TextShape -> SVGTextShape.

- common/Session.cpp
- common/Session.hpp
- kit/Kit.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
disable any dialog interactivity
Change-Id: I6d6fde721c7b3c18c519f87139525fcac1f6fb31
> wsd: add an option "batch mode" to load the document

- wsd/FileServerUtil.cpp
Change-Id: I1f6708c566fc69edc76e7c0d32625f6b1f4b3af4
> wsd: revisit log messages FileServerUtil.cpp

- wsd/FileServer.cpp
Change-Id: I44b84853e951f5a9d6a8bbb5bd0ceebcff75abe2
> wsd: revisit log messages FileServer.cpp

- kit/ForKit.cpp
LOG_ERR = load, save, session, connection
Change-Id: I105b0d2706db4ffeb2ab10923604f2e06c2d8d77
> kit: revisit log messages Fokit.cpp

- wsd/Storage.cpp
Change-Id: I960c1edd1e9e5be4d046617ebf8ae41996bf4395
> wsd: revisit log messages Storage.cpp

- wsd/Admin.cpp
- wsd/Auth.cpp
- wsd/ProofKey.cpp
- wsd/TileCache.cpp
Change-Id: Iaddfcf7f0853abfa96948fff28acda606cf88b55
> wsd: revisit log messages misc files

- loleaflet/src/layer/tile/CanvasTileLayer.js
It was broken because of one of the previous changes.
Change-Id: Ibcc1955d35227d2ac1b429245a97f20df669bfb0
* Resolves: # 
> Calc: Grid drawing is fixed.

- loleaflet/src/control/Control.Header.js
Change-Id: I6074009679f279815b5fc00e38f4e8316493ce65
* Resolves: #1500 
Fix issue when column is not selected/highlighted ,you could not resize it.
> loleaflet: fix column resizing when not selected

- test/run_unit.sh.in
Change-Id: I78dbdcb1ec3d960b283016d86e95614a8cb0255c
> test: run unit test with disabled capabilities

- kit/Kit.cpp
LOG_ERR = load, save, session, connection
Change-Id: Ieefc881876106b1afc4f34505903f1321b33411b
> kit: revisit log messages kit.cpp

- loleaflet/html/framed.doc.html
- loleaflet/postmessage-api.html
> Timar/action change UI mode

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.UIManager.js
- loleaflet/src/map/handler/Map.WOPI.js
Adds support for notebookbar shortcuts bar modification using existing post message API.
> notebookbar: shortcuts bar modification using post message API

- loleaflet/src/control/Control.Notebookbar.js
> Fix loop index

- loleaflet/src/control/Control.NotebookbarDraw.js
needed for show/hide functionality using postmessage
> Add ids for shortcutsbar in draw

- common/Session.hpp
- common/Util.cpp
- net/Socket.cpp
- net/Socket.hpp
- net/SslSocket.hpp
- net/WebSocketHandler.hpp
- test/UnitCopyPaste.cpp
- test/UnitWOPITemplate.cpp
- wsd: cosmetics
- wsd: better errno handling in sockets
- wsd: logging improvements
- wsd: test: improve Template test
- wsd: test: logging in copy-paste test instead of cerr
- wsd: test: assert when failing copy-paste test
> Misc improvements to tests and logging

- loolwsd-systemplate-setup
Change-Id: I9944e79d0fe220a5f2fe40d2ba98619c22d25a77
> Port loolwsd-systemplate-setup to FreeBSD.

- loleaflet/css/vex.css
to avoid padding affecting otter size anywhere
Change-Id: I45122bbb27d37de3bfb15f201c10a4888f2ff5c2
> Vex input field: ensure box-sizing

- loleaflet/src/control/Control.PartsPreview.js
Change-Id: Id8612ebbcb725b3c03ff6c2262c48c0f42544754
* Resolves: # 
> Fix Slide Sorter does not update on Draw

- loleaflet/src/control/Control.PresentationBar.js
- loleaflet/src/control/Control.UIManager.js
> Draw: Display Presentationbar for Insert/Duplicate/Delete Pages

- loleaflet/src/layer/tile/ScrollSection.ts
Change-Id: I5d00b444e43c65c65366efb2b54cc6d4c58c3499
* Resolves: # 
> ScrollBars: Make them pixel perfect.

- loleaflet/src/control/Control.NotebookbarDraw.js
Change-Id: I631f25f8cfe961957967b696c62481dc723427e8
* Resolves: # 
> Attempted fix of build failure on CentOS7 with old python

- loleaflet/src/control/Control.PresentationBar.js
Change-Id: Iaef6f2a405e0e55b082e303447fa9377a0ec96d0
* Resolves: # 
> Hide presentation button for Draw

- loleaflet/css/jsdialogs.css
- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarWriter.js
- loleaflet/src/core/Socket.js
push together with core
- converted style previews into icon view with scrollbar
> styles preview converted to icon view (cp64)

- loleaflet/css/jsdialogs.css
- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialog.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.Notebookbar.js
- loleaflet/src/control/Control.NotebookbarWriter.js
- loleaflet/src/core/Socket.js
push together with core
- converted style previews into icon view with scrollbar
> styles preview: converted to icon view (master)

- wsd/DocumentBroker.cpp
When loading hasn't completed yet, DocBroker can't
simply send a message to Kit that the session is
disconnected, because there would be no UI or
handlers for events if that were the only session.
Of course letting the document load, only to close
it, is also less than helpful to resource consumption.
Here, we recognize this case and simply terminate the
loading by killing the Kit process altogether to
avoid any potential hangs or resource wastage.
Change-Id: Ia72de715cc6238831c244444bb47b417b9b1e1a4
> wsd: terminate Kit when disconnected while loading

- cypress_test/Makefile.am
Change-Id: I6e5135cdc89c5790f11e1cf7fb4ee497e7a43078
> cypress: php-proxy: port was changed: 9982 -> 9983.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
Change-Id: Ie7c75172eb8e418c1047c0af5de0750962e5937d
* Resolves: # 
> CanvasSectionContainer: Improve bound sections list calculation.

- cypress_test/Makefile.am
Change-Id: I62c707c1b36e026f0f90a7109b040437acd34d26
> cypress: php-proxy: make sure that the preferred port is available.

- loolwsd.xml.in
- wsd/Auth.cpp
- wsd/LOOLWSD.cpp
Change-Id: Ifd2b078adfa3106765f5b54c0397e04ab66fc804
* Resolves: # 
> Allow jwt token expiry to be configurable.

- loleaflet/src/control/Control.Tabs.js
Change-Id: I13833ac5c6292dbf1b7589ae390125ae02be4e05
* Resolves: # 
> calc: double click on sheet tab to rename.

- kit/Kit.cpp
Change-Id: I9fd1c76aff9c97b800c6b7b6154beb9c596170fb
* Resolves: # 
> wsd: reduce jail size

- cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
> cypress: fixed failing impress insertion wizard tests

- loleaflet/css/jsdialogs.css
Change-Id: If54e91eadb54193e2d938ae1ffae9a43dd2b3d28
> Jsdialog: textarea: add max width

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- android/lib/src/main/res/values/strings.xml
Change-Id: Ic85297eb112def4a9197116177c857db910459cf
> android: de_document -> the_document

- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.Toolbar.js
- loleaflet/src/control/Control.TopToolbar.js
Change-Id: I3cc064410fad613984c8e2e531b0e77f2810adaf
> notebookbar: border style dropdown

- loleaflet/css/loleaflet.css
- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I440d113e54376ceed17a929e850763d9ae2e38be
> loleaflet: iPad: insert comment: Fix textarea static Width

- loleaflet/src/control/Control.NotebookbarDraw.js
show only .odg and .pdf formats in file tab
Change-Id: If95d871d0ec546569a3ccb0334b9acbd971a9f86
> notebookbar: draw file tab

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: Id3213519a9224ee0287b5dfdd0251230e4c5f00e
> jsdialog: fix line breaks for 'multiline' control

- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/searchbar_spec.js
- loleaflet/src/layer/marker/TextInput.js
- loleaflet/src/layer/vector/Path.Transform.js
> Hide selection handlers when cursor is active

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/unocommands.js
This reverts commit 05330d9f0756f263578d5f9301eea0929452eabe.
Change-Id: I7c142bc71aaf5b58b7b80df55a0eed5d4169f08e
> Revert "temporary hide VBA dialogs"

- wsd/LOOLWSD.cpp
Change-Id: Idbcd5d1b9063e2ef3b7478906a6a346e236db51d
* Resolves: # 
> Added Draw to "Launch one of these" prompt on startup

- common/Session.cpp
- common/Session.hpp
- kit/Kit.cpp
- loolwsd.xml.in
- wsd/ClientSession.cpp
- wsd/LOOLWSD.hpp
> henry's macro enable

- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
> Fix calc losing focus when CellCursor message arrives

- loleaflet/src/layer/tile/ScrollSection.ts
Change-Id: I831df582ec21aa040f6af2df7b5e6c4f8883c988
* Resolves: # 
> ScrollSection: Improve scrolling with touchpad.

- loleaflet/src/control/Control.MobileWizard.js
Change-Id: I875ebed7d2e8d0f8813c39a221e945988d511043
> mobilewizard: check if "_docLayer" object exists

- loleaflet/css/toolbar.css
- loleaflet/src/layer/Layer.js
- loleaflet/src/layer/Popup.js
- loleaflet/src/layer/marker/Marker.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/ScrollSection.ts
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/tile/TilesSection.ts
- loleaflet/src/layer/vector/CPolyline.ts
- loleaflet/src/layer/vector/CanvasOverlay.ts
- loleaflet/src/map/Map.js
* Resolves: # 
Backporting canvas related fixes to co-6-4 branch
> Backporting canvas related fixes to co-6-4 branch

- loleaflet/css/loleaflet.css
- loleaflet/css/mobilewizard.css
- Position the number of replies near to the chevron to indicate what
that is supposed to do.
Change-Id: Idd692f40f5f3420d7577147e8ca7bcf306e59899
> Mobile: Comment (annotation) layout improvements with grid

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I27cb2e6c5d2f1da8477750e59561e04edf50acae
> add "Run Macro" menu entries for Writer and Impress

- loleaflet/src/layer/AnnotationManagerImpress.js
Change-Id: Id12b3e422fcb7970241535345f3e90271ede42eb
> annotation: fixed error on annotation insertion in impress

- loleaflet/css/mobilewizard.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I312dd93cce463293c1a237c96d0d18c10f6d4a84
* reference #1403
> leaflet: annotation: wizard: indicate in wizard if there are no comments

- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/org/libreoffice/androidapp/ui/FileUtilities.java
- android/app/src/main/java/org/libreoffice/androidapp/ui/LibreOfficeUIActivity.java
- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- android/lib/src/main/res/values/strings.xml
Also now txt files can be opened and edited.
Change-Id: Id7b57c219a2e8eaa46153cd3ae4b91dcb9352eab
* Resolves: # 
> android: Request ODF conversion for text files on Android

- loleaflet/css/mobilewizard.css
- loleaflet/src/control/Control.MobileWizardBuilder.js
Change-Id: I6d9d42f5f31f19b6a0cd00803cc350fcac32d505
> mobilewizard: hide cancel and help buttons

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/ScrollSection.ts
Change-Id: Idd57b97f75e7f5732617b9d2e96927317498d699
* Resolves: # 
> CanvasSectionContainer: Improve mouse wheel handling.

- common/Util.hpp
- net/HttpRequest.hpp
- net/ServerSocket.hpp
- net/Socket.cpp
- net/Socket.hpp
- test/HttpRequestTests.cpp
- test/Makefile.am
- test/UnitSession.cpp
- test/helpers.hpp
- test/integration-http-server.cpp
- wsd/LOOLWSD.cpp
- wsd/Storage.cpp
- wsd: comment typos
- wsd: move ServerSocket creation into ServerSocket class
- wsd: test: more informative test failure
- wsd: test: improve unit-integration
- wsd: cosmetic
- wsd: better logging of socket activity
- wsd: improved SocketPoll start-thread guard
- wsd: better http::Session::create API
- wsd: test: use unique_ptr
- wsd: resuable http test helpers
- wsd: test: minor fix to Makefile
> Misc logging, comments, and test improvements

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
- loleaflet/src/control/Toolbar.js
Change-Id: Ic100b0857d9617c5fcdf3d2ea8a992206cd0cf5d
> Notebookbar: Promote Print to bigtoolitem

- loleaflet/css/mobilewizard.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/layer/tile/TileLayer.js
- Add proper html structure
- Add style to communicate that his is a empty state and thus different
from the regular mobilewizard view
- Add icon
- Fix alignments and sizes
Change-Id: I9815efe1a5b96862dba9d0e4c5863b5975132596
> leaflet: annotation: wizard: no comments: improve layout and style

- loleaflet/css/mobilewizard.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/layer/tile/TileLayer.js
* Resolves: #1403 for 6.4 branch
* indicate empty comment wizard
* insert comment suggestion when not comments are added
* insert comment button in title
> Comment wizard improvements on 6.4 (backporting)

- loleaflet/src/control/Control.UIManager.js
in sequence of PR #1660
Change-Id: I542c9092f88196c9e59d675ff71a7f44dfb8f67a
> Mobile: Edit btn: show only if no initial dialog is present

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
Allow dragging event even when the mouse is outside the document.
Change-Id: I2b871e9a7556b465d55aa0d1b50ac9f489246d17
* Resolves: # 
> CanvasSectionContainer: Improve dragging feature.

- common/Clipboard.hpp
- common/Log.hpp
- common/Util.hpp
- net/Buffer.hpp
- net/HttpRequest.cpp
- net/Socket.cpp
- net/Socket.hpp
- test/UnitCopyPaste.cpp
- test/UnitTyping.cpp
- tools/WebSocketDump.cpp
- tools/map.cpp
- wsd/ClientSession.cpp
- wsd/LOOLWSD.cpp
- wsd/ProxyProtocol.cpp
- wsd: remove a TODO and explain rationale
- wsd: simplify and document dumpHex
- wsd: better logging of hex data dumps
- wsd: better socket logging
- wsd: log on EPIPE while writing to socket
- wsd: do more outside mutex and std::move
- wsd: improved thread ownership management and logging
- wsd: better logging
- wsd: read -> wrote
- wsd: check before doing unnecessary work
- wsd: detect misuse of SocketPoll::startThread
- wsd: capture and log exceptions during initialization
> Logging improvements and documentation

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- NB Writer home tab align bullet commands
- NB Calc home tab align character commands
- NB Impress home tab align bullet commands
> private/pedro/porting NB alignments

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/statusbar_spec.js
- cypress_test/integration_tests/desktop/impress/statusbar_spec.js
- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
Change-Id: I3eed9e51460d39c4e12bf838077239488724e337
> cypress: extract resetZoomLevel() helper method.

- loleaflet/src/layer/tile/TileLayer.js
Cell cursor shouldn't jump to end when whole row or column selected.
"undo delete row" and "undo delete column"  actions shouldn't cause cell cursor to jump to the end.
Change-Id: I51f077c5b3fdd5c7a610631f1e0259775278ab53
* Resolves: # 
> Calc: Improve "cell cursor jump"-Online part.

- loleaflet/src/control/Control.NotebookbarDraw.js
> notebookbar: draw home

- loleaflet/src/layer/vector/Path.Transform.js
Wrong positioning etc.
Change-Id: Ie636b4d056faf0cb5204a1a8cda7a98d7ea2e681
* Resolves: # 
> Fix glitches of shape handlers on show/hide

- loleaflet/src/control/Control.Menubar.js
Change-Id: Id2b40f142c45e25b4af3adeaeb81490253424ead
> Mobile: Hamburger Menu: do not show Run Macro when in readonly

- fuzzer/admin-data/crash-b2410495ffc957f8ab01d9affe293db632f4ad14
- wsd/LOOLWSD.cpp
Change-Id: Ib0ee205ce5620d09bee877148b52dc2f3342145d
> LOOLWSD::sendMessageToForKit: add error handling

- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/ImpressTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
> Impress: Default view improvements.

- loleaflet/src/layer/tile/TileLayer.js
Even if the modifier view is different.
Change-Id: I32d0c12ae3c9c61da95f311dd8471cc4b7be5769
* Resolves: # 
> TileLayer: Update view cursor.

- loleaflet/src/control/Parts.js
Change-Id: I8e00c37db690ee8bd18d548e18b672268431ceaf
* Resolves: #1565 
add scroll functinality in vex dialog
> loleaflet:add scroll functionality in showPage dialog

- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
Resolved comments hamburger menu item behaves inconsistantly.
Change-Id: I9e32cd3c71d17cea551ce2a5aba5b20f8fae832d
> cypress: remove this unreliable test.

- cypress_test/plugins/blacklists.js
Change-Id: Iec4d50e4d883330707437e796d450d8325ba419b
> cypress: disable macro test for NC run.

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/core/Socket.js
Change-Id: Idcd70f49010b074ee9987755132b7010b72a86f9
pdf cloud not be loaded at all
regression caused by ddbc4e25ffb0c40b27aa8a0ee488efa54675e238 #1737 
also fixed the main menu in mobile for pdf/drawing
> leaflet: fixed pdf loading

- loleaflet/src/control/Control.ContextMenu.js
Change-Id: I8673dfa1cce2f5ddf57e28558617699263681185
* Resolves: # 
> Enable pivot context menu items now we have the dialogs.

- loleaflet/css/jsdialogs.css
- loleaflet/css/loleaflet.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/control/Toolbar.js
- loleaflet/src/core/Util.js
- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/map/Map.js
Added polyfills needed for IE11
> IE11 support

- loleaflet/src/control/Control.NotebookbarBuilder.js
- Safer approach
- iteration from https://github.com/CollaboraOnline/online/pull/1767
- in response to https://github.com/CollaboraOnline/online/pull/1767#discussion_r596834601
Change-Id: If5f3f1f2ed9b39e419911d39553df9e3fd9f19f4
> Notebookbar: File tab: replace instead of removing ellipsis

- loleaflet/src/control/Control.LokDialog.js
Change-Id: Ic4933a4afe7d991054811f16ce0df25f90b9d3c7
* Resolves: # 
> LokDialog: JS error fixed.

- ios/Mobile/TemplateCollectionViewController.mm
A quick workaround for https://github.com/CollaboraOnline/online/issues/1433 .
Change-Id: I8d77df9858170cfa0cc9a4921e84cdb365aed1cf
* Resolves: # 
> Don't let the TemplateCollectionViewController be dismissed

- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
fixes for view cursor/selection issues :
* cell selector of another user not always shown
* crash when user with selection leaves
* don't crash if view message don't exist
> view cursor/selection fixes

- loleaflet/src/map/handler/Map.TouchGesture.js
Change-Id: I810af6c8950f9974dd4799fd4517917e12d8642c
* Resolves: # 
> Touch: Increase swipe speed.

- loleaflet/src/layer/tile/TileLayer.js
The new message contains coordinates so apply them
before creating the grey overlay.
Change-Id: I3593ce6a9ae9a1bb95962ecf9127f5055f3e8beb
> Update chart overlay coordinates on activation

- loleaflet/css/jsdialogs.css
- loleaflet/css/loleaflet.css
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/control/Toolbar.js
- loleaflet/src/core/Util.js
- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/map/Map.js
> ie11 fixes master

- loleaflet/src/layer/marker/Cursor.ts
- loleaflet/src/layer/marker/TextInput.js
- loleaflet/src/layer/tile/GridLayer.js
- loleaflet/src/layer/tile/TileLayer.js
This includes a few [view-]text-cursor fixes. The issue fixed are described in each commit's message.
> text cursor fixes to co-6-4

- loleaflet/src/layer/marker/Cursor.ts
- loleaflet/src/layer/marker/TextInput.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/GridLayer.js
- loleaflet/src/layer/tile/TileLayer.js
Forward port of canvas fixes in co-6-4
> Forward port of canvas fixes in co-6-4

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/ScrollSection.ts
Change-Id: Ifb335d433af4656294223fa6c16378819abbb950
* Resolves: # 
> CanvasSectionContainer: Add animation feature.

- loleaflet/src/map/handler/Map.Keyboard.js
Change-Id: I97ff4d95250aad326b7d48635ab425045959ca5d
> leaflet: set German bold shortcut to ctrl+shift+f

- loleaflet/po/templates/loleaflet-ui.pot
- loleaflet/src/core/Socket.js
Change-Id: I81eec6d40368768ca1a53d57bfe0eb6136464b90
* Resolves: # 
> Socket.js: Refresh the page after a server restart.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/tile/TilesSection.ts
- loleaflet/src/map/Map.js
- loleaflet/src/map/handler/Map.TouchGesture.js
Zoom animation: avoid abrupt scale change, reduce flicker, and other related fixes.
> Zoom animation: avoid abrupt scale change, reduce flicker etc

- loleaflet/src/map/handler/Map.SlideShow.js
Change-Id: Idb7742730294e6891e2971be8e63914c4985603b
> leaflet: removed Obsolete property fullscreen

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/ScrollSection.ts
Scroll bar animation was flickering after mouse leaves its area.
Change-Id: Ie4d96d98dee806e6b02c8c8a23dd4eaccabbf7b0
* Resolves: # 
> Scrollbar: Fix flickering.

- loleaflet/src/control/Control.LokDialog.js
Change-Id: I1dbe63587d9714101416dcf91726fcc40f8eedf8
* Resolves: # 
> Calc: Sync tile container size after expanding / collapsing input bar.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/tile/TilesSection.ts
- loleaflet/src/map/Map.js
- loleaflet/src/map/handler/Map.TouchGesture.js
Zoom animation: avoid abrupt scale change, reduce flicker, and other related fixes.
> Zoom animation: avoid abrupt scale change, reduce flicker etc : For master

- common/SigUtil.cpp
- common/SigUtil.hpp
- kit/ForKit.cpp
- kit/Kit.cpp
- wsd/LOOLWSD.cpp
Change-Id: I6b1f5ac1cebdd05dd9ff9541a5418059f55841ed
* Resolves: # 
> Dump versions when we have a signal.

- loleaflet/src/control/Control.Menubar.js
Change-Id: I7d4b86b010527adb8dc110246db5d4356b1cd2d3
* Resolves: # 
> Calc: Enable freeze-panes on mobile.

- loleaflet/src/layer/marker/Cursor.ts
- loleaflet/src/layer/tile/ScrollSection.ts
Change-Id: Ie27783cab0edfa3e264df41d584d81379e0afe79
problem:
when hovered over the scroll bar and then moving away from scrollbar,
mouse cursor would not be set to text even if cursor visible
> leaflet: set cursor to text if blinking cursor visible

- .github/workflows/codeql-analysis.yml
Change-Id: I3f0bd3763694181c91966d7fa54143b201c67825
* Resolves: # 
> Enable CodeQL cpp check

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Path.Transform.js
Change-Id: I6676d076cf6cff83f277eb701e98437f4e9c36d1
* Resolves: # 
> Fix shape handles are not aligned correctly in calc

- loleaflet/src/control/Control.NotebookbarCalc.js
Change-Id: Ib510f00666f4bf5af9d7780327b9f97c0f8964bd
> notebookbar: disable change tracking in calc

- EULA
- Makefile.am
- configure.ac
- debian/control
- debian/rules
- loolwsd.spec.in
The next version of Collabora Online will be version 2021.
Development of version 2021 will be carried on master branch
for the time being.
The corresponding core branch is distro/collabora/co-2021
Change-Id: I9c97aaac711c9e1f1e48ed25066b169ea7e26e84
* Resolves: # 
> forward port packaging bits to master branch

- test/WhiteBoxTests.cpp
Change-Id: I657586231eb7d7be344944c85b40eae9048931dd
* Resolves: # 
> Add explanation for trick used in WhiteBoxTests::testTime()

- loleaflet/src/layer/AnnotationManager.js
- loleaflet/src/layer/AnnotationManagerImpress.js
- loleaflet/src/layer/marker/Annotation.js
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
Change-Id: I130674753d0b34fb9afed778e99907d1848daf76
update comment wizard without closing it
in addition now newly added comments will be highlighted by default
> leaflet: comment wizard: update comment wizard without closing it

- kit/KitHelper.hpp
- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/ImpressTileLayer.js
- loleaflet/src/map/handler/Map.StateChanges.js
Change-Id: I2b1ececba67fb8855187baafdc42cb5baa051635
> impress: hide regular slides in master view

- loleaflet/src/map/Clipboard.js
Change-Id: I3bdf05ab3cd4159cb6e42f8705ad6987fa58ff08
* Resolves: # 
> Loleaflet: Paste shortcut CTRL + V does not work on comment dialog

- loolwsd.xml.in
- test/countloolkits.hpp
- test/httpcrashtest.cpp
- test/test.cpp
- test/test.hpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/LOOLWSD.cpp
- wsd/LOOLWSD.hpp
Change-Id: I31969196aa138b6da964c867679ec23f34c89fd0
* Resolves: # 
> admin: add support for lost kits cleanup

- .gitignore
- cypress_test/integration_tests/mobile/calc/formulabar_spec.js
- loleaflet/Makefile.am
- loleaflet/src/core/LOUtil.js
- loleaflet/src/layer/tile/AutoFillMarkerSection.ts
- loleaflet/src/layer/tile/CalcTileLayer.js
- loleaflet/src/layer/tile/CanvasSectionProps.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
> Create AutoFillMarker Section

- loleaflet/src/layer/tile/AutoFillMarkerSection.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
> Auto Fill Marker Section Follow Up

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I92dd6ada3a1179fe63fea428e554a7e490ca3c67
> Send mouse click position on drawingAreaControl

- loleaflet/package.json
Signed-off-by: Ayhan Yalçınsoy <ayhanyalcinsoy@pisilinux.org>
Change-Id: Ib93992efd676e7f1d35ed55f3a317eb35003a901
reviewer: @mrkara 
Eslint version bump to 7.0.0
> eslint:v.bump to 7.0.0

- common/MessageQueue.hpp
Signed-off-by: Ayhan Yalçınsoy <ayhanyalcinsoy@pisilinux.org>
Change-Id: Idc3f58e6c8f04efcbe636ab9aac940eee2f0affd
reviewer: @mmeeks
> added stdexcept include to fix build error

- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- test/HttpRequestTests.cpp
- test/HttpTestServer.hpp
- test/helpers.hpp
- wsd: test: http: add HttpTestServer
- wsd: test: retry poco requests and check body
- wsd: test: http: improve GET test validation
- wsd: test: http: improve http test server
- wsd: test: http: support external regression-test server
- wsd: test: http: simplify http test server
- wsd: test: http: use Response instead of crafting strings
- wsd: test: http: more mature http test server
- wsd: test: http: echo server
- wsd: test: http: loopback to echo server and random data
- wsd: http: support sending Request and Response in Socket
- wsd: test: http: use Response in the test server
> HTTP Server for loopback testing

- loleaflet/src/control/Control.ColumnHeader.js
- loleaflet/src/control/Control.RowHeader.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
Change-Id: Icfe1a71ea67d1a7e3c0adf324a7637ecf7f334fb
* Resolves: # 
> Calc: Update row headers on scroll when entire column/row selected.

- docker/from-packages/scripts/install-collabora-online-ubuntu.sh
when creating docker image
Change-Id: I8562b5bbccc50d11c6b8110a4791fa9592eff6b8
* Resolves: 
> Use CODE arm64 repository while the base OS architecture is aarch64

- loleaflet/src/map/Clipboard.js
Change-Id: I3bdf05ab3cd4159cb6e42f8705ad6987fa58ff08
* Resolves: # 
> Loleaflet: Paste shortcut CTRL + V does not work on comment dialog.

- loleaflet/css/loleaflet.css
- loleaflet/css/partsPreviewControl.css
- loleaflet/css/toolbar.css
Fix positions and backgrounds
Change-Id: I479cf7d01023ffc611a3cfa6a5fb90fb0dbda1d7
> Draw and Impress: fix slide sorter

- kit/SetupKitEnvironment.hpp
- loleaflet/src/layer/tile/CanvasTileLayer.js
- test/TileCacheTests.cpp
Client side grid fixes and patch to enable the feature.
> Enable client side grid

- kit/SetupKitEnvironment.hpp
- loleaflet/src/layer/tile/CanvasTileLayer.js
- test/TileCacheTests.cpp
Client side grid fixes and patch to enable the feature.
> Enable client side grid (co-6-4)

- .gitignore
- loleaflet/.gitignore
- loleaflet/Makefile.am
- loleaflet/package.json
- loleaflet/src/layer/vector/CPath.ts
- loleaflet/src/layer/vector/CPolygon.ts
- loleaflet/src/layer/vector/CPolyline.ts
- loleaflet/src/layer/vector/CanvasOverlay.ts
- loleaflet/tsconfig.json
Project level compilation for ts files in src/
> Project level compilation for ts files in src/

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
Change-Id: I53e9b13fd737af66a6715d1385eeff6b0b0795c1
* Resolves: # 
> tdf#129833 android: Move reading file to separate thread

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Path.Transform.js
Change-Id: Ia3d477fff3f79de72ed556b6a58806c38d387cfd
* Resolves: # 
> Implemented Glue points overlay

- loleaflet/css/loleaflet.css
- loleaflet/css/partsPreviewControl.css
- loleaflet/css/toolbar.css
Make sure width doesn't get above the available space
Change-Id: Ib7b6b15dcf093d6172a35346679a7985584f4ef9
> Impress: Fix #presentation-toolbar on chrome

- .gitignore
Change-Id: Id6c7f31343bb405e634a7d96521fe02adcc40c4c
> Gitignore: Add test/unithttplib to test list

- loleaflet/src/layer/tile/ScrollSection.ts
Change-Id: Ic1257df185d94524f7d6fe4a53cfb949700ba57c
* Resolves: # 
> ScrollSection: Remove unnecessary assignments.

- loleaflet/src/layer/tile/CanvasSectionContainer.ts
Change-Id: I296343dbf24e2daf5131d537d8d87496c0b51842
* Resolves: # 
> SectionContainer: Remove extra "interactable" check.

- test/Makefile.am
Change-Id: Ieacbfe9bedd90a7b1f55dac84d3fdffa22918e1b
> wsd: test: more parallel test execution and simpler Makefile

- loleaflet/css/device-tablet.css
- loleaflet/css/loleaflet.css
- loleaflet/css/menubar.css
- loleaflet/css/notebookbar.css
- loleaflet/css/partsPreviewControl.css
- loleaflet/css/toolbar.css
- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- Notebookbar: Increase select status of unobuttons
- Notebookbar: unnobutton: no need to increase size on hover
- Notebookbar: Improve shortcuts and fix top bar layout on tablet
- Fix background color in which document page is placed
- Draw and Impress: fix slide sorter
> private/pedro/backports NB canvasBG slideSorter

- loleaflet/src/layer/AnnotationManagerImpress.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
Change-Id: I40a820b932d3891dee9a32d319a4426e77e301d8
* Resolves: #1830
> leaflet: scroll to comments on pressing annotation buttons

- loleaflet/src/layer/tile/ScrollSection.ts
Variables are added into initialization for easy management.
Duration is adjusted.
Change-Id: Ic53a159d708a5f8b0121ec264b229da0141333fa
* Resolves: # 
> Scroll Section: Adjust scroll bar durations.

- loleaflet/src/control/Control.NotebookbarBuilder.js
> notebookbar: handle Get_Export_Formats wopi post message

- loleaflet/src/control/Control.Menubar.js
Change-Id: I282aeaa171081b60633720b4619e0b0f250b501a
> leaflet: Removed impress download options from drawing doc

- loleaflet/src/layer/tile/TileLayer.js
- loleaflet/src/layer/vector/Path.Transform.js
- loleaflet/src/map/handler/Map.BoxZoom.js
- loleaflet/src/map/handler/Map.Keyboard.js
Change-Id: Idafe2aa33f45225e704a617da34b5ef28f707d1f
* Resolves: # 
> Implemented uniform scaling for shapes with Shift key

- loleaflet/src/control/Control.ContextMenu.js
And not just for browser in mobile phone or mobile app. This is
apparently what we want. See
https://github.com/CollaboraOnline/online/issues/1751 .
Change-Id: I7cc89889899f20286913a1d2136b40dd6930d996
* Resolves: # 
> Add the 'Delete' context menu entry in browser on tablet, too

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.NotebookbarCalc.js
there was no space in the data tab with some languages
> notebookbar: reorganize sheet and data tabs

- loleaflet/src/control/Control.Notebookbar.js
> notebookbar: reinitialize only once

- loolkitconfig.xcu
Change-Id: Ia28fdcf76a899a6844d367bc6fb81e289abc12f6
> loolkitconfig: introduce config to show Non-printing Characters

- loleaflet/src/layer/tile/CalcTileLayer.js
Change-Id: I866edb95f55d8b16a6ce3ba4e0cb4bbaa79e182d
* Resolves: # 
> Calc: Filter with split panes improvement.

- loleaflet/src/control/Control.NotebookbarBuilder.js
Revert c28c6b2c3cea5f39bd0610f1c52cc85588456c99
Change-Id: Ic63e50fe5c87dea2dc7998a99e739b41e65cad1d
> Fixes #2003 (show paste icon)

- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I303b1cc1d2197eedf6e66b04dfebf72e3c763f75
* Resolves: #1018
> added dropdown arrow in FontColor BackColor and BackgroundColor buttons

- loleaflet/src/control/Control.Toolbar.js
Let the user see the red warning before it removes the class
Change-Id: I95528fee7414c745c3b7c1b3221ab45b2a820121
> Fixes #2008

- loleaflet/css/toolbar.css
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.TopToolbar.js
Fixes one subitem of https://github.com/CollaboraOnline/online/issues/2015
Change-Id: I20c2ec56fe5cc0b4374f25769d5a7403ddf55d2e
> Toolbar: W2ui: linespacing: change component and add icons

- loleaflet/css/notebookbar.css
- loleaflet/css/toolbar.css
- loleaflet/images/closedoc.svg
Change-Id: I24a0319305088fd44a296721a8e2f41b8876bd38
> Fixes #2030: Sidebar icons: cropped and misaligned

- loleaflet/css/jquery-ui-lightness.css
Signed-off-by: codewithvk <vivekpatel7202@gmail.com>
Change-Id: I151db6e80a446eefdee21b5536e00694b9734074
* Resolves: #2002 
> Fix : Notebookbar Labels Decrease font size

- loleaflet/css/override-vex.css
- loleaflet/html/loleaflet-help.html
- loleaflet/src/map/Clipboard.js
fixes #2011
Change-Id: I227fed8bc8838f09e878290650d47d000ac53801
> Keyboard keys: Fix style inconsistencies

- loleaflet/css/device-mobile.css
Change-Id: Ib28ce57172f9c93e49eab4eeca3abeaa783a1fd4
* Resolves: #2006 
> Fix: mobile: toolbar-down: swipe indicator now visible at the start

- loleaflet/src/core/Socket.js
Change-Id: I4ae4bc666320a6791cebd0da687ca79f3d5d6c83
> notebookbar: delay for message if not initialized

- loolkitconfig.xcu
Change-Id: I38af64c049e92965507f50df84d3955ba188eba2
* Resolves: # 
> loolkitconfig: introduce config to show Non-printing Characters #2

- loleaflet/css/override-vex.css
- loleaflet/src/map/Clipboard.js
- loleaflet/src/map/handler/Map.Keyboard.js
- improve normal paste html structure
- style special pasting
- make sure we are using consistent font size across the board
Change-Id: I9a0942ce086c9c96082ef79aa0450c4aab7daf35
> Style Paste special dialog and fix html structure

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarDraw.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
Change-Id: Ie83f7339cba5919868351cddf6989369760438de
* Resolves: #2095
Screenshots see https://github.com/CollaboraOnline/online/issues/2095#issuecomment-824955025
> fix #2095 NB File Tab update at all apps

- loleaflet/css/notebookbar.css
- loleaflet/src/control/Control.NotebookbarCalc.js
Change-Id: Icfcae2e856f0724395eef35e861826062e4f5d24
* Resolves: # 
Review of the Calc Home Tab.
*before*
*after*
> NB Calc update Home Tab

- net/Socket.cpp
Change-Id: Iecaa90f4c3030b5b2e20bb0e33ef9b75717bb578
* Resolves: # 
> Use the accepted socket, not the listening one.

- loleaflet/src/control/Control.JSDialogBuilder.js
Change-Id: I56ec50e613250c0be34b13b7385f7599fe80df26
* Resolves: # 
> Correctly handle response buttons of js dialogs

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Reverts CollaboraOnline/online#2079
Unfortunately the comment causes a breakage of cypress tests, and it seems the tests have actually really uncovered a problem - so we shouldn't merge the https://github.com/CollaboraOnline/online/pull/2147
> Revert "fix #1285 remove elipsis ... from NB strings"

- Makefile.am
- common/ProfileZone.cpp
- common/ProfileZone.hpp
Compiled but not yet used.
Change-Id: I3b85696ca6076e42d16e710b49bfd37bac342ec8
* Resolves: # 
> Add a ProfileZone implementation here, too

- loleaflet/css/mobilewizard.css
- loleaflet/css/notebookbar.css
CSS Var with RGB value goes inside of of `rgb()` and not the other
way around
Change-Id: I1401309c00d91160e757f4fdca0b00ea74763911
> Fix RGB within CSS vars

- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.UIManager.js
Signed-off-by: codewithvk <vivekpatel7202@gmail.com>
Change-Id: I83d560360103ad68bf0fdd226817bd9b2d172a07
* Resolves: checked status for full screen in menu
https://user-images.githubusercontent.com/61119120/115405981-5c7dfd00-a20c-11eb-8b53-27ea5a5bf11b.mp4
> leaflet: show checked status for full screen in menu

- loleaflet/src/layer/marker/TextInput.js
Change-Id: Ifc13261ddd58c17acbe1af65bff6a49bd4a0bb4a
> annotation: fix vex dialog losing focus on comment insert

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
- loleaflet/src/layer/marker/Annotation.js
Change-Id: I22072037c858c97250d50a8c323893cfbdc31b60
> cypress: added annotation test for desktop:impress,calc,writer and mobile:calc

- loleaflet/css/notebookbar.css
Change-Id: Id3c4f4051894d89d2ba6d416825bcce9b73c424a
The Label also has a background color AND a defined font color. In addition an outline give the selection some space.
> Notebookbar Selected Command visibility fix #2126

- Makefile.am
Change-Id: Iefeb034022a9cff7537c5d254c211bd4a0622ad9
* Resolves: # 
> Add net/WebSocketSession.hpp into packaging tarball

- loleaflet/src/control/Control.FormulaBar.js
- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
- loleaflet/src/control/Control.PresentationBar.js
- loleaflet/src/control/Control.SearchBar.js
- loleaflet/src/control/Control.SheetsBar.js
- loleaflet/src/control/Control.SigningBar.js
- loleaflet/src/control/Control.StatusBar.js
- loleaflet/src/control/Control.TopToolbar.js
- loleaflet/src/control/Control.UIManager.js
Change-Id: Idc9bb0ac12b849871292293286f9019449cc9851
additionally, tooltips in tablet will be visible on long press now
#1461
> leaflet: unified the tooltip bindings

- loleaflet/src/map/Map.js
Change-Id: Ia62a1f298b83cee879dabb8df113c61b3da594d0
Signed-off-by: codewithvk <vivekpatel7202@gmail.com>
* issue : #2160 
> Copy loleaflet-api.html into code: tileHeightTwips

- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/GridLayer.js
- loleaflet/src/layer/tile/TileLayer.js
It happens when reconnecting, a Macro Warning dialog is opened,
but the document is not loaded yet.
Change-Id: If98cf4d68ac8ef71d7c0ad3d8aa5151a77adbe4b
> loleaflet: fix error messages when a document is not loaded

- loleaflet/src/control/Control.LokDialog.js
Improves calc editing performance and interactivity significantly.
Change-Id: I1442d253ac3f449f7b9e7b5e7ac6dc01365e8dd3
* Resolves: # 
> Avoid touching the main docLayer canvas size pieces unless necessary.

- cypress_test/integration_tests/desktop/writer/track_changes_spec.js
- cypress_test/integration_tests/mobile/writer/track_changes_spec.js
Change-Id: Ifad0ecc0527b4bb1f1c76e66c79285c045b7af9a
> cypress:added tests for track changes in writer

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: I71f6083e727eef223e55e89df94e37c394359443
> jsDialogBuilder: Add CSS class to elements of type 'drop'

- net/Socket.cpp
- tools/mount.cpp
With this changes LOOL successfully runs on FreeBSD! http://arrowd.name/lool.png
> Final fixes for FreeBSD

- loleaflet/css/notebookbar.css
has-dropdown--color value work perfect
Change-Id: Icb719da3013e0981704aedbef981b84a448e22fd
> Button dropdown is now 24px in height like all other commands #2088

- loleaflet/css/notebookbar.css
Change-Id: Icd08b17f65b2c264c54b41b7a8f24fccb9573057
> Notebookbar.css cleanup unrelated values was removed

- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/TileLayer.js
The browsers - unfortunately appear to round-robin the asynchronous
unload of an individual tile - which causes a _tileReady callback
with updating the canvas.
This means that we re-render the canvas (at whatever speed) for each
tile we load - guarenteeing a nice animated effect of loading tiles
one by one, and refreshing the view: not so cool.
So - instead, as per WebSocket messages, slurp them - and then
refresh the view in one shot after 1ms; since it is fairly bogus
to convert a base64 encoded URL image to a real image asynchronously
anyway, this gives some nice results eg.
TileLayer.js:2464 Slurp tiles 34
TileLayer.js:2464 Slurp tiles 25
TileLayer.js:2464 Slurp tiles 53
TileLayer.js:2464 Slurp tiles 5
TileLayer.js:2464 Slurp tiles 3
It also significantly improves pageing down in …
> Tile load slurping.

- common/Unit.cpp
- net/Socket.cpp
Change-Id: Id998e2bdf7051d54784543015c7d34c0bdd64543
* Resolves: # 
> android: Fix build fail and crash on doc load

- cypress_test/package.json
Change-Id: I5181d78d73a88d1faaf1419a8315b44e034f5c97
* Resolves: # 
> cypress: update cypress-select-tests: 1.5.9 -> 1.7.0.

- loleaflet/src/control/Toolbar.js
Change-Id: Ia1b5c7316d20e14d9537281274c9ebd0b8f58ae7
* Resolves: #2021
> fix:added dismiss button in welcome page dialog mobile

- Makefile.am
- common/ProfileZone.cpp
- common/ProfileZone.hpp
- configure.ac
- kit/ChildSession.cpp
- kit/Kit.cpp
- loleaflet/src/control/Toolbar.js
- loolwsd.xml.in
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/LOOLWSD.cpp
- wsd/LOOLWSD.hpp
- wsd/protocol.txt
> Forward port of trace event stuff

- configure.ac
- loolwsd.xml.in
- wsd/DocumentBroker.cpp
- wsd/LOOLWSD.cpp
- wsd/LOOLWSD.hpp
Change-Id: I2515182d9369c3a25727dce0d3790e79de891bff
* Resolves: # 
> The Chrome format is called Trace Events, not Event Trace

- common/ProfileZone.cpp
Change-Id: I5cab82f0d869cc9f2ea97ac9320d8f4bbf466c37
> Use Util::getThreadId() instead of Linux system call.

- wsd/LOOLWSD.cpp
LOG_ERR = load, save, session, connection
Change-Id: I80e8ee0de2b6858ec8e1c27276eb2058acdb2970
> wsd: revisit log messages LOOLWSD.cpp

- test/HttpRequestTests.cpp
After 358b30a682227a5260e932fadbc585fddc9c0a8c.
Change-Id: I53ab88b240bde8fcd09dd916cf156dc251452b26
- [] I have issued `make run` and manually verified that everything looks okay
> Fix build with --disable-ssl

- common/Message.hpp
- test/WhiteBoxTests.cpp
Change-Id: Id11a702590539ff4f20fa56272beeb6d91b9e7bd
* Resolves: # 
> Message: cleanup message parsing of payloads.

- net/WebSocketHandler.hpp
Change-Id: I1a662dbdb2e43335f8739852e7797012de7be34a
* Resolves: # 
> There is no isManualDefrag parameter

- common/Authorization.cpp
- common/FileUtil.cpp
- common/JailUtil.cpp
Change-Id: I15bc840f5a6eaf9a74a1ee1caa57d447baa2afce
> common: revisit log messages misc files

- cypress_test/package.json
Change-Id: I8174ad69bde13df3a93ddbe7b8ace93b0b0aa44c
> cypress: update cypress: 6.2.1 -> 6.8.0

- kit/Kit.cpp
- kit/SetupKitEnvironment.hpp
> Forward-port two of mmeeks's patches

- loleaflet/css/notebookbar.css
Change-Id: Iaf876e786e8bc24dc6c03c412d12dc5e4700119c
> Notebookbar Tab Content vertical-align

- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/ImpressTileLayer.js
- loleaflet/src/map/Map.js
cherrypick of:
https://github.com/CollaboraOnline/online/pull/2032
https://github.com/CollaboraOnline/online/pull/2033
> macro nodocload error

- scripts/refresh-git-hooks
> scripts/refresh-git-hooks: Create hooks dir before making links

- wsd/ClientSession.cpp
Colon, not equals. Comma missing.
Change-Id: Ife64fe7c57e0cff155926f9b17beb17ce530d848
* Resolves: # 
> Fix syntax errors in generated Trace Event JSON

- loleaflet/src/layer/marker/Cursor.ts
- loleaflet/src/layer/vector/SVGGroup.js
Change-Id: I5c0348cf0d3f7055303d06a74c393dd2fe9c4981
* Resolves: # 
> Fix Impress: Text selection in the Title box using cursor does not work

- loleaflet/src/control/Control.Menubar.js
Change-Id: Id52b5fcc0f2d892ac07c7c1327987397ccc3fd96
* Resolves: # 
> fix:added chart option in insertion-wizard of writer and impress mobile

- loleaflet/css/w2ui-1.5.rc1.css
- loleaflet/js/w2ui-1.5.rc1.js
- Fix #2343
- Do not crop contents
- Centered message (vertically and horizontally)
Change-Id: Icc40a09d1690f683135ac16b274d237c81aab827
> Status bar: Do not crop showbusy message

- loleaflet/src/core/Socket.js
Change-Id: I9507a9de6cb4dfd427f1bda4cc12aae23ae38474
* Resolves: # 
> Don't allow a single event emission to stop processing the whole queue.

- loolwsd.xml.in
Change-Id: I54db3bd41b54fcb869f048f3581a6545e24cfd4b
* Resolves: # 
> It's trace_event, not event_trace

- loleaflet/css/notebookbar.css
Change-Id: I4550db174ce1a58b7ab097ffd4aef9eca51a63e4
> Notebookbar fontnamecombobox was one px to low

- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarDraw.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
Writer: add DrawText, DrawLine, 3DObject, MultiObject, Graphic and DrawFontwork
Calc: add Text, DrawText, DrawLine, 3DObject, MultiObject, Graphic and DrawFontwork
Draw: add Table, DrawLine, 3DObject, MultiObject, Graphic, DrawFontwork
Impress: add DrawLine, 3DObject, MultiObject, Graphic, DrawFontwork
Impress/Draw: update Table and Draw Tab
Change-Id: I619466c234443bb5e2d8f4ecb3ec67aac19d4ea3
> Notebookbar: add missing context toolbars #2175

- loleaflet/html/loleaflet-help.html
- Add missing <kbd> tags to Draw
Change-Id: I30c71ba576a42aa64935c6fa493ef9b54b51f1dc
> Keyboard keys: Fix style inconsistencies: missing Draw

- wsd/LOOLWSD.cpp
Change-Id: I99aa27d70c7c1d90f3048009644ebf9a41e73724
> wsd: remove unused using declarations

- loleaflet/src/map/handler/Map.Keyboard.js
This is a follow up patch for PR #2199.
I added return statement for not changing previous behaviour.
Change-Id: Ic390eebd95c8a85149351d3b23c19fe36df9b2c6
* Resolves: # 
> Page up & down on read only mode.

- loleaflet/src/layer/tile/CanvasTileLayer.js
Interestingly for large CPU rendered skia surfaces - as used by
many browsers, rendering well spaced vertical lines is inordinately
expensive: 10x slower than horizontal ones, presumably due to cache
effects.
Grid rendering is around ~40% of our rendering performance measured
by knocking out various elements we render and re-timing.
By banding our vertical lines to re-use pixels close to where we
are drawing horizontal lines, and by creating more smaller paths
we get at ~25% overall performance improvement - 70ms -> 53ms
avg of ~10 frames.
Change-Id: I8ad1007b74866bd3d7b1b838f226a3efadcccbed
* Resolves: # 
> Render grid-lines in horizontal strips for performance.

- loleaflet/src/control/Control.PartsPreview.js
Regression from 651a4f546aa07a42e0a5416af317ef46851c69b3
Change-Id: I2b97f84fd50ba4259bbfbf266e28ce7299012804
* Resolves: # 
> loleaflet: Make PgUp/Down work in slide sorter

- loleaflet/css/menubar.css
- replace old random top value with half if its height
- fix height (to be the same as the neighboring parents)
Change-Id: I738ca92b78daa4db773fe4dce6f1dd3d29001403
> Document-name-input: Fix top position

- cypress_test/integration_tests/desktop/calc/focus_spec.js
- cypress_test/integration_tests/mobile/calc/chart_spec.js
- cypress_test/integration_tests/mobile/calc/focus_spec.js
- cypress_test/integration_tests/mobile/calc/formulabar_spec.js
- cypress_test/integration_tests/mobile/calc/number_format_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
- cypress_test/integration_tests/mobile/impress/slide_properties_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/apply_font_spec.js
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
Change-Id: Icfdb53967eef14ad93ebfc6b1978304e9298db70
* Resolves: # 
> cypress:skip failing tests temporarily

- Makefile.am
- common/Util.cpp
- common/Util.hpp
- ios/Mobile.xcodeproj/project.pbxproj
- kit/ChildSession.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/Kit.hpp
- loleaflet/js/global.js
- loleaflet/src/control/Toolbar.js
- loleaflet/src/core/Socket.js
- loolwsd.xml.in
- wsd/ClientSession.cpp
- wsd/LOOLWSD.cpp
- wsd/protocol.txt
* Resolves: # 
(Once the Jenkins and Cypress bits of the CI are active again. Missing currently for some reason.)
> Trace Event related stuff I am working on

- ios/Mobile/Info.plist.in
Change-Id: Ie5f6af1c88f8c8d134e365d619af1f983c5b0230
* Resolves: # 
> Bump internal "Xcode" version to 6.4.10

- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/TileLayer.js
So that the core message ordering is maintained (by enforcing a single
queue).
Change-Id: I6ba0d3ed13f4c9b08461dd7ae046106aeaaa4c50
* Resolves: # 
> Unify queue slurping - msg and tiles

- loleaflet/css/loleaflet.css
- loleaflet/css/notebookbar.css
add --white-bg-color so that there will be also a dark notebookbar background possible
use as much var as possible. some values are still fixed, but when I don't know where the color was used, I didn't change anything.
Change-Id: I1e7f95021e687329560b5df1d0fd17bf0d391d0a
> Notebookbar.css var color update

- loleaflet/css/toolbar.css
- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarWriter.js
- Calc Formular bar alignment #809
- Notebookbar Layout Tab add Sidebar show/hide #2295
> private/andreas/Notebookbar Layout Tab Sidebar

- loleaflet/css/toolbar.css
Change-Id: Ic3480234e04f4bcd8a4cccb99c84614bd9f40cb4
> Calc Formular bar alignment #809

- loleaflet/css/device-tablet.css
- loleaflet/src/control/Control.NotebookbarDraw.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- Notebookbar Tablet: remove tab height
- Notebookbar Draw/Impress add Layout and Review tab
> private/andreas/Notebookbar Impress Draw Review Layout Tab

- loleaflet/css/device-tablet.css
- loleaflet/src/control/Control.NotebookbarDraw.js
- loleaflet/src/control/Control.NotebookbarImpress.js
by remove the defined heigt, the dynamic (full) height will be used.
Change-Id: I31d868c7e3a5232f994794af3393fc91ef2f14cc
> Notebookbar Tablet: remove tab height

- loleaflet/src/control/Control.Notebookbar.js
Add mime type icon under document-header according to document type
Change-Id: I42e80886919372a842a1d0fecf40b4a9557b5376
> Notebookbar: Add document icon in the case app icon is missing

- loleaflet/images/lc_showruler.svg
- loleaflet/images/lc_showstatusbar.svg
- loleaflet/images/lc_zoomreset.svg
- loleaflet/src/control/Control.NotebookbarCalc.js
- loleaflet/src/control/Control.NotebookbarDraw.js
- loleaflet/src/control/Control.NotebookbarImpress.js
- loleaflet/src/control/Control.NotebookbarWriter.js
File tab:
- add repair command
Layout tab:
- add FullScreen, Reset zoom, ZoomMinus, ZoomPlus
- add Sidebar and other view related commands like Show Ruler and Show Status Bar
Change-Id: I8fa709848244c28fe8f7534a5431e07e213ae458
> Notebookbar add commands to File and Layout tab

- ios/Mobile/Info.plist.in
> The internal ("Xcode") version is at 6.4.10

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Change-Id: I910dc2e6f8e99add6f7f46811d9c1a569c8d1fc1
* Resolves: # 
> cypress:fix failing test temporarily

- kubernetes/helm/README.md
- kubernetes/helm/collabora-online/templates/deployment.yaml
- kubernetes/helm/collabora-online/templates/hpa.yaml
- kubernetes/helm/collabora-online/templates/ingress.yaml
- kubernetes/helm/collabora-online/templates/service.yaml
- kubernetes/helm/collabora-online/values.yaml
updated the instructions to setup online in kubernetes
Change-Id: Ic01d94d095eac9dba54a09351eabcbc6ba83c16b
* Resolves: # 
> kubernetes: introduced kubernetes configuration

- loleaflet/package.json
Change-Id: I16241f0fe63191d204b01f0bef0640480b751c04
problem:
every time online would change the properties,
in alphabetic order
this will make sure to avoid unintentional changes
> rearrange dependencies in package.json

- loleaflet/src/control/Control.LokDialog.js
- loleaflet/src/control/Control.PartsPreview.js
- loleaflet/src/core/Socket.js
- loleaflet/src/layer/tile/CanvasSectionContainer.ts
- loleaflet/src/layer/tile/CanvasTileLayer.js
- loleaflet/src/layer/tile/ScrollSection.ts
- loleaflet/src/layer/vector/CSplitterLine.ts
* Resolves: # 
This is a forward port of message slurping fixes in co-6-4.
> forward port slurping fixes to master

- test/UnitFuzz.cpp
- wsd/DocumentBroker.hpp
- wsd/LOOLWSD.hpp
I.e., not in upper case. I was misunderstanding.
Change-Id: I3275446cba0eb954b5ef398d3406d0543c2fb7e7
* Resolves: # 
> The convention is to call the processes 'WSD', 'ForKit', and 'Kit'

- cypress_test/integration_tests/desktop/calc/delete_objects_spec.js
- cypress_test/integration_tests/desktop/impress/fullscreen_presentation_spec.js
Change-Id: If270c9400881292a6ebe54ed697fb70af6c80bb4
> cypress:fix calc delete chart test failing

- kubernetes/helm/collabora-online/templates/service.yaml
Change-Id: Ia8d13762ebc0b0203fd5fa6870f3e576f1648c8a
> kubernetes: use consistent hash in haproxy

- loleaflet/src/control/Control.MobileBottomBar.js
As there is a break in writer and calc, there should be also a break at impress between font stuff anf color stuff
Change-Id: I303ffc24a5f5bd049800622ac27ffe45143ad3e0
> Mobile BottomBar consistency

- loleaflet/Makefile.am
ESLint couldn't find the plugin "@typescript-eslint/eslint-plugin"
Change-Id: Ic6fc9660628ab9ef7ebfa4cb50a2595be5195b49
> loleaflet: fix builddir != srcdir

- loleaflet/src/control/Control.Menubar.js
PickList align Mobile with Desktop
SearchDialog everywhere on Top of Menubar for better visibility
FullScreen, Presentation, are sorted in all apps
Change-Id: I78b588fc232b887285f00b229d57143f0b3b14c2
> Mobile Menubar update

- loleaflet/css/device-mobile.css
- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.MobileTopBar.js
- Mobile BottomBar consistency
- Mobile Topbar Alignment
- Mobile Draw add TopBar commands from Impress
> private/andreas/Mobile TopToolbar Draw

- loleaflet/css/device-mobile.css
- loleaflet/src/control/Control.Menubar.js
- loleaflet/src/control/Control.MobileBottomBar.js
- loleaflet/src/control/Control.MobileTopBar.js
- Mobile BottomBar consistency
- Mobile Topbar Alignment
> private/andreas/Mobile TopToolbar Alignment

- loleaflet/Makefile.am
applying several times make clean
install the node_modules
Change-Id: I9004787ebf2087f541bec0248bd873252c88a40d
> loleaflet: fix make clean issue

- loleaflet/src/control/Control.FormulaBar.js
- loleaflet/src/layer/marker/TextInput.js
Change-Id: I48b8380ab289aa68b2d2fa4695aa53416ed33e8e
* Resolves: # 
> mobile: Fix impossible to escape/cancel formula selection

- loleaflet/images/lc_closedocmobile.svg
Change-Id: I6ab019f5774f8d501892cedae9019f830e5ea23f
> Mobile Icon closedocument fix

- loleaflet/css/device-mobile.css
Formularbar was vertical-align: top which cause issues on mobile formularbar.
Change-Id: I88140808657dd44e6b94fdf99485ce14079a3920
> Mobile Calc Formularbar arrangement fix

- loleaflet/css/notebookbar.css
Change-Id: I49792f65d51cbd0d95b9cfd5edca737aa182ce4d
> Notebookbar shortcuts-menu vertical alignment center

- loleaflet/images/lc_closedocmobile.svg
Change-Id: I72faf40324b41c494627006c9c427c989ef189a3
> Mobile fix closedocmobile icon

- cypress_test/integration_tests/common/desktop_helper.js
Change-Id: Ie339287becf98d50a79d9c34e53b744bc5ae7c50
> cypress: added delay before click on zoom level

- android/lib/src/main/cpp/CMakeLists.txt.in
- common/Log.cpp
- common/Log.hpp
- common/ProfileZone.cpp
- common/ProfileZone.hpp
- ios/Mobile.xcodeproj/project.pbxproj
- kit/ChildSession.cpp
- kit/Kit.cpp
- loleaflet/src/control/Toolbar.js
- loleaflet/src/core/Socket.js
- loolwsd.xml.in
- test/Makefile.am
- tools/WebSocketDump.cpp
- wsd/ClientSession.cpp
- wsd/LOOLWSD.cpp
- wsd/LOOLWSD.hpp
- wsd/Storage.cpp
- wsd/protocol.txt
> Re-work the profile zone implementation here, and other stuff piling up waiting for CI to pass

- loleaflet/src/control/Toolbar.js
Change-Id: Iadef2a635055a8761bcd71a7e2c869fa05d12fa9
* Resolves: # 
> Use key instead of keyCode

- loleaflet/src/layer/tile/TileLayer.TableOverlay.js
- loleaflet/src/layer/tile/TileLayer.js
Change-Id: I9ac799a0c9a0f77a61a85954d270af6e7ca28dac
* Resolves: # 
> connect just once to the zoomend message in a more sensible place.

- loleaflet/css/notebookbar.css
Change-Id: I34e8ace9db13f843a128731f36a5d6a4b4d12bb7
> Notebookbar shortcuts-bar horizontal center align

- cypress_test/integration_tests/desktop/impress/delete_objects_spec.js
- cypress_test/integration_tests/desktop/impress/fullscreen_presentation_spec.js
- cypress_test/integration_tests/desktop/writer/delete_objects_spec.js
…n_spec
Change-Id: I7333b6bd8a9de1d1f2f82041859374d1f65fc074
* Resolves: # 
> cypress:added delay in delete_objects_spec and fullscreen_presentation_spec

- kit/ChildSession.cpp
Change-Id: I76b4b066db59acd2e7dc45bf8606021104f79cae
> kit: revisit log messages ChildSession.cpp

- loleaflet/src/control/Control.FormulaBar.js
- loleaflet/src/layer/marker/TextInput.js
Change-Id: I50b52e2ffd1ee830578899e8d63ad65aca207602
* Resolves: # 
> mobile: Fix formula accept cancel buttons visibilty

- loleaflet/src/layer/tile/CanvasTileLayer.js
Change-Id: Ifb564a9779071d1e559a004150efc8eb937e10dc
* Resolves: # 
> fix avoid putting empty tiles to cache

- net/WebSocketHandler.hpp
Change-Id: Id573e8ff93f3a5914fef91b01802047881990dbf
* Resolves: # 
> Add commented-out TraceEvent::emitInstantEvent

- loleaflet/css/mobilewizard.css
Change-Id: I325e1f1ebb6b73c8d814596cbc0ae84e2a87bb18
> Mobile wrap icons alignment float: left

- loleaflet/src/core/Socket.js
Change-Id: Ia6de77ea3604ea00cca785f84456f9f0f6216371
* Resolves: # 
> We want microseconds here, too

- loleaflet/src/core/Socket.js
- wsd/ClientSession.cpp
> Two cherry picks

- loleaflet/css/mobilewizard.css
Reverts CollaboraOnline/online#2569
> Revert "Mobile explorable-entry use the same padding-left than ui-header"

- loleaflet/src/control/Control.JSDialogBuilder.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/control/Control.NotebookbarBuilder.js
Change-Id: Iebbc3685d4a274d1e84b0e68973757904d8657d9
> jsdialog: show/hide action support

- loolwsd.xml.in
Added missing class A ip addresses regex to config file.
> Added missing class A ip addresses regex to config file.

- cypress_test/integration_tests/mobile/calc/apply_font_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
- cypress_test/integration_tests/mobile/writer/apply_font_spec.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
Mobile Sidebar Remove Grow Shrink commands
Change-Id: Ia6de337d7f06efdca40e18359adb88b6b21fd58d
> Mobile Sidebar Character remove Grow and Shrink #2488

- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/calc/number_format_spec.js
- loleaflet/src/control/Control.MobileWizard.js
- loleaflet/src/control/Control.MobileWizardBuilder.js
- loleaflet/src/control/Control.Sidebar.js
Change-Id: I619abce604f1da05c2c22fe979439bbaaaee5709
> sidebar: remove non-deck entry from sidebar

- loolwsd.xml.in
Change-Id: Idcd1ec3ef111aa255446b8504bb1a70c30ff7f7a
* Resolves: # 
> Add Emacs mode line and indent the trace_event.path element correctly

- loleaflet/src/control/Control.SearchBar.js
BottomBar search and unfold are on the same place
Change-Id: I22b101f26eb9eeebccffec0ff592893bb4887a1d
> Mobile search fold as first item
