CollaboraOnline/online

- browser/css/spreadsheet.css
- browser/src/control/Control.Tabs.js
with cbf452b03d71e4ed773e059b83b86af102c473eb drop indicator was not shown if the cursor is over the <div> elements that inside the tabs.
- fix by using `e.currentTarget` instead of `e.target` and do some checks while on `_handleDragLeave`
- fix the misalignment of drop zone
Change-Id: Iec8e246f18e553487b0eb0d9264cff8bb37b6305
* Resolves: # 
* See also:  #8266, #7846
> Calc: fix drop zone indicator regression

- kit/ChildSession.cpp
problem:
in LOK/online to support async save, files in jails may have different extensions (ie: .upload, .uploading)
this caused problem to detect files as original file name may not exist. As result property like file size were always set to 0
Change-Id: Ia4b39c04412e191742b98046c5c31e3964db7ce9
> uno: .uno:SetDocumentProperties: add file path parameter

- browser/src/dom/Draggable.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/ScrollSection.ts
- browser/src/map/handler/Map.TouchGesture.js
Previously when we were in RTL mode panning would be flipped. This
commit unflips it
This is a nontrivial backport of #8565, nontrivial only because that contained some es6-specific code that cannot be backported
I also didn't backport removing the dead code, because I don't want to make any backport that's unnecessary to fix something
Change-Id: Iea4d16918b054d355e6d8695e0dc1d6ededd6793* Resolves: # 
> Draggable, TouchGesture: Fix panning with RTL

- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitWebSocket.cpp
- net/WebSocketHandler.hpp
Somehow this state can get confused in a bgsave process:
Kit Document:
...
inputProcessingEnabled: false
...
SocketPoll:
Poll [kit] with 1 socket - wakeup rfd: 39 wfd: 45
fd        events        rbuffered        wbuffered        rtotal        wtotal
52        0x1        process             0             0         r:    825
'process' should read 'ignore' for disabled input.
Change-Id: I787eebe6fda3ae1b527d7605b8813fa764e81890
* Resolves: # 
> bgsave: have a single source for InputProcessing enable & disable.

- common/MessageQueue.hpp
- kit/ChildSession.cpp
- kit/Kit.cpp
Get the polarity of the check on whether we succeeded to spawn a background save process right, so we don't spawn two saves concurrently, and block input processing in the wrong place.
Also a few obvious sillies fixed, and some more assertions for good measure; was not good:
[ kitbgsv_001_001 ] TRC  ToMaster-002: Finished synchronous background saving ...| kit/ChildSession.cpp:882
[ kitbgsv_001_001 ] TRC  ToMaster-002: saveDocumentBackground returns succesful start.| kit/ChildSession.cpp:887
[ kitbgsv_001_001 ] TRC  Document - input processing now: disabled was enabled| kit/Kit.cpp:2095
[ kitbgsv_001_001 ] TRC  ToMaster-002: uno command .uno:Save {... notify: true| kit/ChildSession.cpp:1944
Change-Id: Ie06a74a538bdd5038ca9c94b422f27cff9e4a82e
* Resolves: # 
> bgsave: don't try to save twice in the same background process.

- common/FileUtil.cpp
- configure.ac
can be disabled with --disable-hardening-flags, defaults on except for wasm and sanitizer cases
Change-Id: Id3ccb7492b73dfa6c7bbd5dd0419927032fc9bdf
* Resolves: # 
> default to using available compiler hardening flags

- browser/js/global.js
if it exists as the default dark/light theme to use if there is no explicit user setting for it
Related to: https://github.com/CollaboraOnline/online/issues/8734
similar issue as in 24.04 arises from similar 23.05 change of:
commit 100def4c80d6e467c32e2a3300e695905c358838
Date:   Tue Feb 20 16:23:37 2024 -0400
add parameter "theme" to load a document
Change-Id: I49596768ece16ceee1a74740877550122722d51a
* Resolves: # 
> backport 23.05 equivalent of honoring window.uiDefaults.darkTheme

- browser/src/control/Control.NotebookbarBuilder.js
problem:
if calc->view tab-> dark theme button is clicked, if button is clicked from icon it works fine,
but if button is clicked on label event is triggered twice, which means theme would be restored to first
reproducible only in firefox
Change-Id: Ie645df86651a7507582de44147885a2b62384ddb
> notebookbar: event prevent default for theme toggle button

- configure.ac
need to include some typical headers to get it to issue a failure diagnostic
Change-Id: I37d6e0f342698507952a8006b88d56e55060270e
* Resolves: # 
> compile check of -D_FORTIFY_SOURCE=2 not failing with CFLAGS=-O0

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- browser/src/layer/vector/CPath.ts
- browser/src/layer/vector/CPolygon.ts
- browser/src/layer/vector/CPolyline.ts
- browser/src/layer/vector/CanvasOverlay.ts
Previously the following issues were present when columns were frozen
- The frozen column was allowed to move, this was exacurbated when I made it easier to move in my 'calc: pinch-zoom:' commits, (3ba8257c6432a5a8f42901c9955c11f83a9a720a...b378a0fd778760dfb0f457c796769d14aaad11f6). This is now fixed
- A regression was also introduced in that range where the selected cell marker would become offset if you placed it in a frozen section then pinched to zoom. This is also fixed
Change-Id: I07f70a32e5cb68aeb759fd6cad626b2d4c0eed72
* Resolves: # 
> Fix broken frozen columns mid-pinch-zoom

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
Fixes for several sporadic issues, each uncovering the next
Sidebar was not getting hidden because the button was pressed too soon
- Wait for sidebar to show before hiding it
Comment text area was disabled
- Wait for disabled attribute to go away
Second half of comment text was getting sent to document instead of comment
- Wait after typing in document before inserting comment
Also add wrapper describe block to share setup/teardown
- Fixes copy/paste errors in one block, which was missing calls to selectZoomLevel and setActiveFrame
Change-Id: I13ef1189cfacc4beac0b2c3363c70aa1e8583db3
* Resolves: # 
> Fix failing cypress test multiuser/writer/annotation_spec.js

- browser/js/global.js
- browser/src/control/Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Clipboard.js
Trying to paste from the notebookbar in a setup which is not localhost
but uses http resulted in a JS exception:
> Clipboard.js:863 Uncaught TypeError: Cannot read properties of undefined (reading 'read')
We assumed that navigator.clipboard is always defined, but then its
'read' and 'write' properties may be undefined.
Fix the problem by abstracting this, and check for navigator.clipboard
as well in global.js.
Can be tested by disabling https in coolwsd.xml and changing localhost
to the real local IP in the make run URL.
Change-Id: I1dab14e311066fa640dbba65dfcc35526a6886d7
> cool#8806 clipboard: don't assume that navigator.clipboard is always defined

- browser/src/layer/tile/CommentListSection.ts
In 79028c6f881dd19ecbffa2c0653634879dd35496 I replaced an instance of using this.map._docLayer._viewId as if the user is not in the document this becomes your own view ID and shows the wrong avatar. Unfortunately I missed CommentListSection which has the same code.
As we already have a viewId fetched a little later down, I opted to use it rather than get another myself
Change-Id: Ieda06e03902effe9be8fef3623b73d3caeef6f65
* Resolves: # 
> Use existing viewId in commentListSection avatar

- browser/src/layer/tile/CommentListSection.ts
problem:
if comment thread is very long and some action is
performed to the last comments which puts root comment out of view, entering modify or reply mode will make scroll to root comment. This makes editing comment/reply go out of view
Change-Id: I99f8df6886a69242b3db92674516678a61d2904f
> annotation: do not scroll to root comment while editing

- browser/src/control/jsdialog/Widget.TreeView.js
- browser/src/map/handler/Map.StateChanges.js
problem:
zotero was not loading because element.text didn't exist on adding bibliography there was error to parse JSON, because there's some more data in string after JSON
Change-Id: If34791ae7ca79ca7fd304b506cd483e929f4d2ac
> added check for undefined properties (backport)

- browser/src/control/Control.Menubar.js
- We allow the slide menu and the few presentation commands
Change-Id: If2533450a3b2af365a89f780dca32daf87c0758a
* Resolves: # 
> impress: Allow presentation in read-only mode

- kit/Kit.cpp
Otherwise we go on doing work that the parent kit process should do eg.
[ kitbgsv_006_002 ] TRC  ToMaster-8f9: saveDocumentBackground returns succesful start.| kit/ChildSession.cpp:887 [ kitbgsv_006_002 ] TRC  Calling paintPartTile(0x4c0716f0)| common/RenderTiles.hpp:130
Change-Id: I257f61d05d8a0da0c8eb9d8c60e502da66dc8cdd
* Resolves: # 
> bgsave: ensure that a bgsave process doesn't have a tile queue.

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.TreeView.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
Add color image preview in autofilter dialog for filter by color option
- it's not user-friendly to just see color code with a radio button.
- this patch will show color image preview for filter by color options according to the color code
- it will apply only for dialogs with filter using color codes in `Autofilter`
-Fix radio buttons are not vertically aligned in center
Some snap shot :
> improvment in filter by color submenu

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.TouchGesture.js
Remove _cellCursor and use app.calc.cellCursorRectangle -> SimpleRectangle.
Turn _prevCellCursor,_cellCursorOnPgUp, _cellCursorOnPgDn into SimpleRectangle.
Remove horizontalDirection and verticalDirection calculations. They are not used. Also remove them from _onUpdateCellCursor function.
Use app.calc.cellCursorVisible instead of empty rectangle checks. Set variables to null to re-init them instead of assigning them empty rectangles.
Push lat/lng usage through markers (leaflet things).
Change-Id: I4b258a72f1ac3c94ccf25a07d0e7dab232165b90
* Resolves: # 
> Lat / Lng Removal

- browser/css/cool.css
- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
problem:
when in small window, comment was autosaved,
it wasn't collapsed but would hang on the edge of the screen half visible.
We can't collapse the comment directly as user will not be able to find again
which comment was being edited.
> Fixed Autosaved comment are half visible

- kit/ChildSession.cpp
problem:
in LOK/online to support async save, files in jails may have different extensions (ie: .upload, .uploading)
this caused problem to detect files as original file name may not exist. As result property like file size were always set to 0
chronology of events:
1. File is saved normally with existing name
2. After saved we make it ready for upload and add extension .upload in "renameForUpload"(kit/ChildSession.cpp) 3  We change to .uploading extension when we are uploading (DocumentBroker::handleSaveResponse, DocumentBroker::uploadAfterLoadingTemplate)
Change-Id: Ibda40b0c134ef6baef9edb0427b3c56340924858
> uno: .uno:SetDocumentProperties: add file path parameter (backport)

- browser/css/jsdialogs.css
- we need to also consider `th` tag to make it display none
- it's an empty text span, so do not that extra space.
Before:
After:
You can see in Header "Background color" there is extra space in before image.
Change-Id: Ib83d42f64a0115fdc4d17a8f7e952419a84cc9d5
> Remove extra grid cell space from header in autofilter child popup

- wsd/ClientRequestDispatcher.cpp
Similar like in:
commit d9d13d7092d2d597eb34d657945f2678756fb800
wasm: support serving wasm files
add headers required when we use WASM so we are able to embed presentation in window.
Without that we get:
not-set Cross-Origin-Embedder-Policy
> Allow to embed the presentation in window

- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/common/helper.js
This was just a workaround to keep tests working till they are fixed to
not assume we do an implicit 'copy' as soon as we have a text selection.
Change-Id: I37d16ee2841c41593a5af2fb6ceba025fe1c79e0
> cool#8648 clipboard: stop fetching the clipboard on text selection create in tests

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- browser/src/layer/vector/CPath.ts
- browser/src/layer/vector/CPolygon.ts
- browser/src/layer/vector/CPolyline.ts
- browser/src/layer/vector/CanvasOverlay.ts
- browser/src/map/handler/Map.Scroll.js
- browser/src/map/handler/Map.TouchGesture.js
This is a backport of #8647 and #8801 which greatly improve the pinch-zoom experience on touchscreens.
Change-Id: Ib4c6e686caaf78b3637563da6fcc914c06f3055a* Resolves: # 
> calc: touchscreen: pinch-zoom-fixes

- browser/src/control/Control.UIManager.js
We see multiple tooltip problem on drawing area widgets. Example case:
Add basic shape into a writer document
Right click on shape and open Position and Size dialog
Select the Rotation tab
Hold the rotation angle widget and drag around itself
When you inspect the "Rotation Angle" tooltip, count may be 600 We expect only 1.
So we prevent to show another tooltip if we have already one.
Change-Id: I2f548f8c7afce8095e83a6faa3722e164f990210
* Resolves: # 
> Prevent opening multiple tooltips on drawing area widgets

- browser/js/global.js
Previously using the onscreen keyboard would shrink the visual viewport while leaving the elements at the same size, meaning some of the content had to be offscreen. As we scrolled the page to have the cursor in view, this would move the notebook bar offscreen.
This commit does 2 things:
- First, we stick the viewport to the top of the screen with CSS, this avoids the possibility of the notebook bar being moved offscreen
- Then, to avoid the possibility of the cursor leaving the screen or the bottom toolbar being offscren, we use the VisualViewport API to force the logical viewport to have the same size as the visual one
Together, these vastly improve the iOS keyboard popup experience
Change-Id: I07726bee8b61334f6a32e873ab2d5428fa60dca3
* Resolves: # 
> iOS: stop keyboard pushing content offscreen

- browser/src/map/Clipboard.js
- cypress_test/integration_tests/desktop/calc/clipboard_spec.js
Copy an image in Firefox, paste in Chrome with the Paste button or with
Ctrl-V. Nothing happens in Calc, Writer gives you a popup to copy the
image, which is already the case.
What happens is that Clipboard.js already had some code to guess when
the HTML only contains an image, but while Chrome puts '<img ...' to the
clipboard, Firefox puts '<meta ...><img ...', so we don't recognize the
content as image.
Fix the problem by adding a new isHtmlImage() function to Clipboard.js
that handles both markups and use it from both places that deal with
paste (Paste button, keyboard).
Note that this also helps in case the HTML starts with a small
difference that is normalized during parsing, e.g. '<IMG ...'.
Change-Id: …
> cool#8806 clipboard: improve detection of HTML that's just an image

- cypress_test/integration_tests/idle/calc/idle_spec.js
This is not part of CI at the moment, so I didn't notice it till Szymon
pointed it out.
make -C cypress_test check-idle spec=calc/idle_spec.js
passes with this, which is the only suite in 'make check-idle'.
Change-Id: Ieeb15653abcc016bc7de87115df136dfe3f27d0d
> cool#8648 clipboard: fix idle tests

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
fixes:
1. Couldn't expand comments if the thread could not fit in view
2. Performing an action on last comments of the thread caused to scroll back to the root comment
3. Now the mouse scroll wheel works on the comment section too
4. Some code cleaning to avoid unnecessary unselect calls 
it nullifies the effect from 81b00e7
now if a comment is added at the end of the document and it goes beyond doc boundary doc will not scroll automatically to make the entire comment visible
> Annotation thread scrolling improvement

- browser/src/control/Control.UIManager.js
We see multiple tooltip problem on drawing area widgets. Example case:
Add basic shape into a writer document
Right click on shape and open Position and Size dialog
Select the Rotation tab
Hold the rotation angle widget and drag around itself
When you inspect the "Rotation Angle" tooltip, count may be 600 We expect only 1.
So we prevent to show another tooltip if we have already one.
Change-Id: I2f548f8c7afce8095e83a6faa3722e164f990210
* Resolves: # 
> Prevent opening multiple tooltip on drawing area widgets

- browser/css/toolbar.css
insert shape popup now shows all the items in one column. fix it so we have rows
> css: fix insert shape popup

- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/desktop/impress/editable_area_spec.js
- cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
Most users of selectTextOfShape also need to select all text. Sometimes the cursor appears but does not allow CTRL+a to select all text. Work around this by including the selection in the retry using waitUntil.
Fixes mobile/impress/apply_paragraph_props_text_spec.js, which started failing sporadically after commit e0a0646ce15c8390f6a1f9b159cdafac63ceee93.
I also adjusted the dblclick selector because it was finding multiple elements but I think that is unrelated
Change-Id: Icdfa731ba9a5f8d08a858192a4f1f5bc79b09b76
* Resolves: # 
> Cypress: Retry selectTextOfShape

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/common/interference_user_spec.js
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/calc/macro_spec.js
- cypress_test/integration_tests/desktop/calc/open_different_file_types_spec.js
- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/fullscreen_presentation_spec.js
- cypress_test/integration_tests/desktop/impress/open_different_file_types_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/form_field_spec.js
- cypress_test/integration_tests/desktop/writer/open_different_file_types_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- cypress_test/integration_tests/mobile/calc/annotation_spec.js
- cypress_test/integration_tests/mobile/calc/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/calc/nextcloud_spec.js
- cypress_test/integration_tests/mobile/impress/annotation_spec.js
- cypress_test/integration_tests/mobile/impress/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/impress/nextcloud_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/cursor_spec.js
- cypress_test/integration_tests/mobile/writer/hamburger_menu_spec.js
- cypress_test/integration_tests/mobile/writer/nextcloud_spec.js
- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
Removes the need to add subFolder information separately or duplicate it. For example, calc/macro_spec.js changes from
```
var newFileName = helper.setupDocument('macro.ods','calc');
helper.loadDocument(newFileName,'calc',true);
```
to
```
var newFilePath = helper.setupDocument('calc/macro.ods');
helper.loadDocument(newFilePath,true);
```
Follow up of https://github.com/CollaboraOnline/online/pull/8832 
Change-Id: I361d523f564e7b9a46dd2398080eef110eeae79c
> Cypress: Join subFolder and fileName into filePath

- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
Failed because mobile wizard opened too soon.
Fix: Wait for selection before opening mobile wizard.
Change-Id: Ie29e3f5be17bafa2dd09b3f8f5b6415104456cb7
* Resolves: # 
> Cypress: Fix mobile/impress/apply_font_text_spec.js

- wsd/FileServer.cpp
It's only relevant for regular URLs that contain version hash.
Change-Id: I73afaa0559c3dddc09a8ed5f786fb5126e1c8f0c
> Don't warn about version mismatch for admin console

- test/helpers.hpp
Some tests are designed to exercise the reconnection
logic. Once the test validates that the correct
reconnection logic is used, the test is considered
finished. In those cases, we need to break the
test framework's retry logic.
Change-Id: Ie0bb5dcc430a954910c2af4817a500f5b576bd4c
> wsd: test: give up attempting to connect if the test finished

- browser/src/map/Clipboard.js
Copy an image to the clipboard, click Paste -> Paste special on the
notebookbar in Firefox: the image is pasted, but the paste special
dialog doesn't close.
What happens here is that Firefox lacks navigator.clipboard.read(), so
the relevant code is Clipboard.js dataTransferToDocumentFallback(), not
the new _navigatorClipboardGetTypeCallback(). Here e.g. copy from
desktop Writer (html+text) would lead to a _doInternalPaste(), which
would call _checkAndDisablePasteSpecial() for us, but the image case
returns early, so the closing doesn't happen.
Fix the problem by explicitly calling _checkAndDisablePasteSpecial()
before returning early.  In contrast with the other uses of
_checkAndDisablePasteSpecial(), we don't need to call the paste or paste
special uno command (since …
> cool#8806 clipboard: fix paste special of images in Firefox

- browser/src/layer/tile/CommentListSection.ts
It sets a reply's status to "resolved" only if its parent is resolved.
I can't remember why we implemented this like this before.
But now, we don't need to.
Change-Id: Ia31dab0237d3b89e5d391cf87394514d18b595f7
* Resolves: # 
> Remove "updateResolvedState" function.

- browser/src/control/Control.UIManager.js
- regression from 9202365fc6dac4ab964c12a1b0858644435e1191
Change-Id: I4554a5fcc9b0c5dce48c8b35ea32142ff1c323f3
> fix: zotero options not visible when viewId is zero

- wsd/FileServer.cpp
It's only relevant for regular URLs that contain version hash.
Change-Id: I73afaa0559c3dddc09a8ed5f786fb5126e1c8f0c (cherry picked from commit b38e1f41ead138af1bdbe8fe5c333f4bfc832b1a)
> Don't log warnings about version mismatch for admin console

- browser/src/control/Control.NotebookbarImpress.js
...as in other tabbed bar JS files.
Change-Id: I29c43d9dc0ce4fa929e049e70171e0b8ab029088 (cherry picked from commit d471d93c1ef72e74345cd8e123c43514ba824b86)
> browser: Add correct class to Share / See History buttons in Impress

- browser/css/jsdialogs.css
- Fix alignment between rows by:
- Setting some of the columns' width
- Removing margin from all buttons & set width. Add column gap
- Fix vertical alignment
- Fix header alignment (Name, Type, Value) so it aligns to the content
- Make "Add property" occupy full width (ideally this button would be
part of the inner grid "last row" but for now this is already an
improvement)
- Remove lengthly css targets and the use of nth-child
Change-Id: I85d9bdbcc365c735757ee086f6e4912d694a011c
> Custom properties dialog: fix grid and misalignments

- browser/css/notebookbar.css
Before this commit buttons such as bold (in the notebookbar) or
sidebar button (in the top toolbar) would not change the cursor on hover
Change-Id: Ief075b4f4d187f6a5d87458d02077c0deaf69fe6
> [Backport] Fix unobutton's lack of pointer cursor

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/TilesSection.ts
- browser/src/layer/vector/CPath.ts
- browser/src/layer/vector/CSplitterLine.ts
- browser/src/layer/vector/CanvasOverlay.ts
Previously the freeze shadow would stay where it was, creating a hard
edge and confusion about where was frozen. With this change, the freeze
shadow moves with the zoom.
Previously when panning with zoom, the freeze shadow would stay in its
initial state (either hidden or shown) whether or not it should actually
be shown at the current position.
Previously when there was a frozen pane we calculated an incorrect
size on the unfrozen pane, leading to slight blank edges when you were
mid-zoom-out.
This pull request fixes all 3 of these issues
> Make freeze shadow move with a pinch-zoom

- browser/src/control/Control.JSDialogBuilder.js
problem:
when user selected disable macro in the opening dialog
document used to close and return to integrator
but now cancel button in csv import dialog is hidden,
so no need to distinguish there and we can continue to load without macros
In addition we still close the file if user clicks "X" button on title bar
> macro: open document without macros enabled

- browser/src/docdispatcher.ts
Change-Id: I635780723b98887e6c35a397940cc2517a6a9025
Fixes a regression in 24.04 where the link picker button emitted a post message `UI UI_PickLink` instead of the documented and previously used `UI_PickLink`
> fix(browser): Emit proper UI_PickLink post message

- browser/css/btns.css
in 24.04 more elements are grid now, it seems to be a regression in button box:
1. enable macro execution in coolwsd.xml
2. open spreadsheet with macro Result: you see the dialog with buttons in 2 rows
Expected: all buttons are in the same row
it seems to be missing grid placement for left and right sections
before:
> css: fix button-box alignment (backport)

- browser/css/btns.css
in 24.04 more elements are grid now, it seems to be a regression in button box:
1. enable macro execution in coolwsd.xml
2. open spreadsheet with macro Result: you see the dialog with buttons in 2 rows
Expected: all buttons are in the same row
it seems to be missing grid placement for left and right sections
Bug:
> css: fix button-box alignment

- browser/src/control/Control.JSDialogBuilder.js
problem:
when user selected disable macro in the opening dialog document used to close and return to integrator
but now cancel button in csv import dialog is hidden, so no need to distinguish there and we can continue to load without macros In addition we still close the file if user clicks "X" button on title bar
Change-Id: Ie0c7d77954e099cb3c8a72c400c688b3ae1343c7
> macro: open document without macros enabled (backport)

- browser/src/control/Control.MobileWizardBuilder.js
- Hide `Set outline format` uno button
- we will add this option again after fixing the dialog issue on mobile view for Outline option in `Bullets and numbering`
Change-Id: I270b78b7b9f00fd7b0f12c348794e3d3da3e653e (cherry picked from commit 4690d8ec28d62704f36d3d69217e37361fd4b5f7)
> Hide outline format button for mobile

- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
Wait for table select to fix copy/paste issue
Fixes copy/paste failure:
```
cy:command ✔  cGet	.unoSelectTable
cy:command ✔  click	
cy:command ✔  window	
cy:command ✔  cGet	#copy-paste-container table
cy:command ✘  assert	expected **#copy-paste-container table** to exist in the DOM
Actual: 	"#copy-paste-container table"
Expected: 	"#copy-paste-container table"
cy:command ✔  fail:	
Test failed: integration_tests/mobile/writer/table_properties_spec.js / Change table properties / layout via mobile wizard. / Distribute columns.
Timed out retrying after 10000ms: Expected to find element: `#copy-paste-container table`, but never found it.
```
Test was failing because the copy/paste warning screen was being shown (_warnCopyPaste in Clipboard.js)
Not sure if this is the root cause of the failure …
> Fix mobile/writer/table_properties_spec.js

- configure.ac
- coolwsd.xml.in
They should be cheap memory wise, and save quite a bit of latency.
Keep 1 for debug mode - to make attaching to the right process easier.
Change-Id: I230be6ae61874f36b47ffc93d888d455bea3a7d8
* Resolves: # 
> Default to four pre-spawned children.

- test/Makefile.am
- test/UnitJoinDisconnect.cpp
a normal case, where user#2 joins the document successfully and then their connection closes; where the remaining client gets the notification that there is only one client in the session.
an abnormal case, failing test currently disabled, where user#2 joins the document, "load url" is launched, but the connection is immediately dropped; the other client gets a notification that a user has joined to make it a 2 user session, but no notification that the user has dropped.
Change-Id: I8271fb3d4def917acdff0fae6a3a52b5d02ef7af
* Resolves: # 
> add a test for joining doc and disconnecting

- browser/src/control/Toolbar.js
Make code more deterministic by removing old hacks with timeout and cursor detection from:
- 6037d52
- b62320c
Bug was that on desktop when we were in formula edit mode and we clicked cancel button - it was not showing again the regular buttons but instead it was showing the accept/cancel buttons.
> Fix buttons visibility in formulabar on cancelformula

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Remove scrolling to get to toolbar buttons
Add test specifically for scrolling
Change-Id: I885d3ec33c8d570dfad45893c5d267b7fe8cc0b9
* Resolves: # 
> Fix failing test desktop/writer/top_toolbar_spec.js

- browser/src/layer/tile/CanvasTileLayer.js
order is since:
commit 06e4722cc93a4acdbf47700de97ea1a8e98ad6fa
Date:   Fri Aug 7 18:37:11 2020 +0530
loleaflet: rewrite tile-prefetcher for L.CanvasTileLayer...
Change-Id: I69b7dd8974d2333cecbc38f94d4851bb0c5f44fc
* Resolves: # 
> check for _docLayer existence before deref of _docLayer

- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
Was failing in moveCursor after slowdown introduced by https://git.libreoffice.org/core/+/ca31493a
Rewrote test to use the same select helper as all the other tests in the file
Change-Id: I5197a095d47e727526636b232df1f3be45e5bb52
* Resolves: # 
> Fix failing test mobile/writer/table_properties_spec.js

- cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
probably since merge of
commit 5140abd2c94b96f2a32f0f7416ae79239a2af187
Date:   Fri May 3 14:14:26 2024 +0500
tdf#152906: use correct Y offset
or similar of that topic
change 3285 to 3286
Change-Id: I4bd3509313c7a5801d5284eebc3882bf3550eed9
* Resolves: # 
> update impress/apply_font_shape_spec.js to pass

- browser/src/layer/tile/CanvasTileLayer.js
_applyDelta returns early if the initial "ensureContext" of the tile fails.
i.e.
var ctx = this._ensureContext(tile);
if (!ctx) // out of canvas / texture memory.
return;
and ensureContext already calls ensureCanvas, so tile.canvas is always true in the remainder of this function.
The "defer constructing the image & applying these deltas until the tile is rendered via ensureCanvas." implied a sort of deliberate optimization to wait until render time to apply the delta which doesn't actually exist.
Also move the stray "// 'Uint8Array' delta" comment back to where it originally came from as documentation of the type of the param, as in
commit 4140bf87417f4aa99780fc3d6c0438d4d469a53a
Date:   Sat Nov 6 11:11:13 2021 +0000
Bring back the delta application JS from the 6.4 branch.
... …
> tile.canvas is always true after a successful _ensureContext(tile)

- cypress_test/integration_tests/common/helper.js
instead of starting with sidebar and then removing it
Change-Id: If2ea433cd3d5fc18ad549bd3df095de15c126ad0
* Resolves: # 
> allow a test to start without sidebar

- browser/js/global.js
Sometimes an input we are focusing on is considered out of the viewport by the browser. This is not always the case, and, even when it is, it's not trivial to move it back in.
Instead, this change detects scrolling and re-scrolls the view to 0, 0.
Doing so is not without consequence, as there is a slight jitter before we can scroll back, however this is substantially better than having the controls off-the-page.
Change-Id: Ie5003f9244ce1c0e8a183de5fdbcf3a880b13a13
* Resolves: # 
> Stop page scrolling

- Makefile.am
- android/lib/src/main/cpp/CMakeLists.txt.in
- common/MessageQueue.cpp
- common/MessageQueue.hpp
- common/Session.hpp
- gtk/Makefile.am
- ios/Mobile.xcodeproj/project.pbxproj
- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitQueue.cpp
- kit/KitQueue.hpp
- kit/KitWebSocket.cpp
- kit/KitWebSocket.hpp
- test/KitQueueTests.cpp
- test/Makefile.am
- test/TileCacheTests.cpp
- test/UnitTyping.cpp
- test/WebSocketSession.hpp
- test/WhiteBoxTests.cpp
- wasm/Makefile.am
The MessageQueue is not a generic message queue, it has much more un-anticipated functionality; so don't use it where we don't need to.
In particular unexpected re-writing and merging of messages during tests is probably not a great idea.
Change-Id: I657738307e611be18f5f83e11c055bf8a88826da
* Resolves: # 
> MessageQueue cleanup, and avoid accidental use in tests.

- browser/src/layer/tile/CalcTileLayer.js
Doesn't hide the grid when the Function wizard is open anymore when disabling the ToggleSheetGrid button.
This is a follow up for issue #8066.
Requires https://gerrit.libreoffice.org/c/core/+/167370
**But this should land first.**
Change-Id: I79ba99716eb1103e7239fe5cc302c64827c9ef53
* Resolves: # 
> calc: Properly handle the disable state

- browser/css/jsdialogs.css
- browser/css/notebookbar.css
Since f7491e1f62de5401529db40b8b899e5c0563badc all combobox started having a with and min-width of 100px, this wasn't meant to be. Restrict this width setting to .jsDialog.
Add 5 px left padding to combobox, this looks better.
Set the font combobox width to 5em instead of 50px.
After:
Change-Id: I0f0247471376e4633f3bbffab89285e16f78cde9
* Resolves: # 
> UI: improve combobox appearence

- cypress_test/integration_tests/desktop/writer/invalidations_spec.js
Test is failing because of an extra empty invalidation when clicking between the body and the header
Change-Id: I887c9bc028f2b831d205bba2944c734cafb1743d
* Resolves: # 
> Skip failing test desktop/writer/invalidations_spec.js

- common/JailUtil.cpp
- tools/mount.cpp
- mount: reduce failure noise
- mount: avoid hard-coding
- wsd: mount: safeRemoveDir will not error when unmount fails
- mount: remove test-mount directory
> Various mountpoint handling improvements

- kit/KitQueue.cpp
/usr/bin/coolforkit
memcmp
asan/../sanitizer_common/sanitizer_common_interceptors.inc:875 (discriminator 9)
/usr/bin/coolforkit
(anonymous namespace)::textItem(std::vector<char, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool&)
online/kit/KitQueue.cpp:52
/usr/bin/coolforkit
KitQueue::put(std::vector<char, std::allocator<char> > const&)
online/kit/KitQueue.cpp:94
since:
commit f8a0d6c0863f4b7f7b99e9b57f8679168bc7d67f
Date:   Thu May 9 15:29:49 2024 +0100
Callbacks: minor efficiency wins, avoid tokenizing where we can.
Change-Id: Ie5d0f86bb33c810b6a5f177421485c977b7fc79a
* Resolves: # 
> AddressSanitizer: memcmp issue

- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/mobile/impress/apply_font_text_spec.js
I tried to diagnose why the click needed to be redone and ended up removing the use of selectTextOfShape altogether.
Old:
select shape
double click on shape to select text
sometimes this double click failed
New:
double click on shape (in center of document)
much more reliable and less jumping around through helper functions
I also removed a few other extra shape selections and unselections.
I also tried to fix the text highlight assertion (which has been failing recently) and added an assertion for shadowed text.
Change-Id: I60e5e571be181bd6f43db1727854973aca446b99
> Fix mobile/impress/apply_font_text_spec.js

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.Drag.js
Zooming always leads to same backwards and forwards, even when you have
hit the screen edge. At the edge of the screen, you can move no further,
which causes the illusion of it being "sticky" on the return journey.
By adding an offset when we reach the edge, we can avoid the stickiness.
I have made
panning past the document edge create an offset too. This provides
similar benefits to the fluidity of scrolling at document edges.
> fix(zoom,pan): Make screen edge offset document

- net/NetUtil.cpp
net/NetUtil.cpp:65:23: error: no matching constructor for initialization of 'net::DNSCacheEntry'
queries.push_back(DNSCacheEntry(addressToCheck, hostEntry, now));
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Went wrong in commit 5be3ccc8718c93c5e60ab6b6ace9b8747d0e1aa0 (cache DNS
results for 20 seconds, 2024-05-14), the rest of the code builds with
this toolchain.
Change-Id: Idc8ed4d88a7f955cf2cdc1e10ac9931823950126
> net: fix clang-15 build in resolveDNS()

- browser/src/control/Control.Header.ts
- browser/src/layer/tile/CanvasTileLayer.js
While zooming, things like the cursor move along with the zoom. The headers instead stayed fixed until the zoom is complete. This is inconsistent with panning, and worsens your experience when zooming
Additionally, I refactored the code in the HeaderInfo update() function a little since as so much of it needed to change anyway
Change-Id: I100de8f1fd62b831c285c9acab456260dbb77ead
* Resolves: # 
> Make headers move on pinch-zoom

- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
Another test failing because of shape selection.
Select text directly and remove calls to shape selection helpers. Unskip a testpoint.
Merge horizontal alignment testpoints (also vertical alignment testpoints).
Similar to https://github.com/CollaboraOnline/online/pull/9020
Change-Id: I729870d6cd43457d2297005f4c815fe29de39f42
> Fix failing test mobile/impress/apply_paragraph_props_text_spec.js

- browser/src/control/jsdialog/Definitions.Menu.ts
Changed the menu entries to conform to the new format used by
JSDialog menu since 07da50a.
Change-Id: I69109675ec69d66eb25ae128a6bb102e4628c705
> browser: fix print menu for Calc

- cypress_test/package.json
cypress-tags published an update today with some missing files. This keeps us on the old version until they can fix their release.
cypress-tags:
https://www.npmjs.com/package/cypress-tags
https://github.com/infosum/cypress-tags
Change-Id: Ie7b2ec506cae4bc244a70b4502a85d3a7530954b
> Lock cypress-tags to 1.1.2

- browser/src/control/Control.Notebookbar.js
This is a regression from commit 9923e695959
This is because jQuery .child() is only for the direct descendants. Use .find() instead which will search down the DOM tree.
This restore postmessage Hide_Command / Hide_Button and Show.
Change-Id: Ibe84c520c9786c6c0026d3507a27a8d3580b38a0
* Resolves: # 
* Target version: master (24.04)
This is in 24.04 only
> postmessage: Fix show hide / button / command in Notebookbar

- browser/src/control/Control.UserList.js
Previously we escaped usernames as soon as we got them in onAddView. Unfortunately, this led to some inconsistent behavior at the output, where we used a mixture of functions setting HTML directly and innerText/textContent attributes.
Sometimes this led to "double-escaping", where a username like '<script>' would initially be escaped to '&lt;script&gt;', and then further escaped to '&amp;lt&semi;script&amp;gt&semi;'. When this was displayed, it would incorrectly be shown to the user as'&lt;script&gt;'.
This commit moves escaping so it's always when we are about to display the username, either with innerText/textContent, or with our escapeHtml method
This was also fixed in 24.04 by a major refactor of the userlist, so there's no need to forward-port this fix
As this commit is touching …
> fix(userlist): XSS escaping: fix double escape

- kit/Kit.cpp
Causing excessive logging in error; we would find the right session next time around the loop; from:
commit 6f49f9398e237c46c71910915bf11925b85fd7a7
Author: Michael Meeks <michael.meeks@collabora.com>
Date:   Thu May 9 09:19:44 2024 +0100
Change-Id: I33f696e4fae899a896d94cbeb70d5d9306f3b414
* Resolves: # 
> callback logging fix mis-placed brace.

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.StatusBar.js
Before this commit menu buttons were always generated with img even if
it's not applicable. Example, the StateTableCellMenu (located in Calc
status bar that allows setting a state according to the function
chosen in the submenu): This text-only menu was generated with img
and thus throwing a 404 error in the console.
- Allow any unoToolButton to be set without image via option
- Add image: false option when setting StateTableCellMenu in the
statusbar
Change-Id: I3fc3b5954f80229835526819b9b80d2a650bd922
> Status bar: Fix MenuButtons being generated always with image

- browser/css/toolbar.css
- browser/html/cool.html.m4
- browser/src/control/Control.DocumentNameInput.js
- browser/src/map/Map.js
Change-Id: I3608bf597ab8d2c7660a1f884cf2c763c7652415
[Screencast from 2024-05-16 21-09-10.webm](https://github.com/CollaboraOnline/online/assets/26241069/b91591a4-c0ce-43af-aba7-a6699e167385)
* TODO:
* To Test:
1. Make autosave interval to something like 30 seconds
2. Open a huge document
3. Edit the document and wait for background autosave to happen
* Resolves: # 
> js: show progress bar during background save

- browser/src/dom/Draggable.js
In Iea4d16918b054d355e6d8695e0dc1d6ededd6793, a regression was introduced where we would check for a specific property of _map when dragging anything. This was needed only in calc to determine the RTLness of the sheet. Unfortunately, _map can sometimes be undefined (such as when dragging around a comment in impress or when resizing a table in writer).
By moving the RTL check so it only executes if there is a map, we can avoid this error, but the check will still run where it needs to.
This is a backport of https://github.com/CollaboraOnline/online/pull/8632
Change-Id: I9994a3957e37975360126fab33ba08e807d723dd
* Resolves: # 
> backport: dragging: Fix undefined _map error

- browser/src/core/Socket.js
It seems there are two handler for this message.
Since we moved the authentication logic ahead
of the web-socket upgrade, the handler for
the unauthorized error doesn't display the
message. This fixes the it so now we correctly
display the unauthorized message.
Change-Id: Ic62476c74ce1583a2d7f33e1233e6fafd43d3bc4
> browser: display unauthorized error message

- kit/Kit.cpp
- test/UnitJoinDisconnect.cpp
- wsd/ClientSession.cpp
Enable Caolan's unit test, pass the proper 'disconnect' message to the Kit so it can close the underlying window / resource for the view.
Potentially this also removes 'phantom' users in the user-list which might be another symptom of this issue.
Change-Id: Ib0d0c5cefa7033fff5827d0a825a932cc12f8323
* Resolves: # 
> Fix excessive logging when a session hard quits very early on.

- kit/ChildSession.cpp
To silence errors until feature arrives. Occurs after following core commit:
11b936629dd4ef9308d63b312900b8b7c8ff19b4
Change-Id: I6d9b01b265e3f07db2bc4ac7da46cbfcd0e17da5
> Add empty handler for LOK_CALLBACK_VERTICAL_RULER_UPDATE

- browser/css/notebookbar.css
So even '88 pt' fit in without getting cut.
Change-Id: I950b99b2bed7b1e038e1847586b517807f3aa9b0
After:
Before:
Follow-up of https://github.com/CollaboraOnline/online/pull/8979
> UI: slightly make the font size combo larger

- cypress_test/package.json
cypress-tags has fixed their npm publishing
Upgrade to take advantage of dependency updates
Reverts commit 873485f479ffa4fcdc607b6427475fd201ff0f1b
Change-Id: Ib4128dd4224a70777eaace0bf1e4bc14974a5189
> Upgrade to cypress-tags 1.2.2

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/docdispatcher.ts
We have that button for Writer, Calc, Draw, Impress menubar and notebookbar
Change-Id: I745c010749b8c5b88c0d181418f2a47921a94620
* Resolves: #9061
> Add Invert Background Color buttons

- browser/css/menubar.css
Change-Id: I8f60eadf53f173f26d47d3959589a233673703ee
Before:
* Resolves: # 
> css: fix progress bar overflowing in compact mode

- browser/css/device-tablet.css
Tab buttons and their background (gray) looks odd, extending the full
width even if there is no more tabs to show.
This sub container cannot be allow to extend (flex-grow). Otherwise,
we end up with tabs background extending all the available area.
We can safely turn this off because the parent element
".notebookbar-tabs-container" already sits in place and extends the
whole area.
Change-Id: I6ec3fa6f40d4138420569e9acf60c906a7c43035
> Tablet: Tabbed view: tabs container too wide

- browser/src/control/Control.NotebookbarWriter.js
Now that accessibility checker has change its command it's best to add
back in the CSS class that was being added automatically (based on the
uno command) for various reasons:
- Main one: the ".unoSidebarDeck.A11yCheckDeck" is less than ideal
class name (it includes a dot in the middle)
- Integrators might have customizations targeting the previous known
css class
Change-Id: I7685d000a2110872cdbe83323136b7a6be604ca3
> Writer: Accessibility Check: Add missing CSS class

- browser/js/global.js
- browser/src/map/Clipboard.js
In case an integration doesn't allow clipboard interaction via
<https://sdk.collaboraonline.com/docs/advanced_integration.html#allow-the-clipboard-permission-query>,
we end up in a situation where navigator.clipboard.write is not
undefined, but is broken.
By the time navigator.clipboard.write() fails, it's too late to fall
back to the old copy code, as the security context is already gone.
Fix the problem by improving the failure handling: show the popup to try
again copying, remember that navigator.clipboard.write() failed and
prefetch the text selection, so next time a copy is tried (via the
keyboard), the selection doesn't need re-creating. (Normally the
selection change would trigger the prefetch, so select->copy->copy-again
would still fail.)
Note that paste doesn't have a similar …
> cool#9072 browser: better error handling when navigator.clipboard.write is advertised but fails

- common/FileUtil.cpp
- common/FileUtil.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
Reuses file-reading utility, handles errors during compression better (always inserts an uncompressed version of each file and serves it if the compressed version is missing), reduces memory allocation/copying churn, deletes dead code, and adds comments. (Commit log messages have the details.) 
- wsd: FileServer cleanup
- wsd: refactored readFile to take buffer
- wsd: generic readFile
- wsd: simplify file-server caching
- wsd: fileserver: better compression failure handling
- wsd: remove unused (Is)ViewWithCommentsFileExtension(s)
> Fileserver Cache Improvements

- wsd/COOLWSD.cpp
and start it after WebServerPoll start.
AsyncDNS depends on COOLWSD::getWebServerPoll()
existing.
```
/lib/x86_64-linux-gnu/libc.so.6
__GI_abort
/build/glibc-bkR840/glibc-2.27/stdlib/abort.c:81
/lib/x86_64-linux-gnu/libpthread.so.0
__restore_rt
??:?
/lib/x86_64-linux-gnu/libpthread.so.0
__GI___pthread_mutex_lock
/build/glibc-bkR840/glibc-2.27/nptl/../nptl/pthread_mutex_lock.c:67
/usr/bin/coolwsd
ConvertToAddressResolver::dispatchNextLookup()::{lambda(std::string const&, std::string const&)#1}::operator()(std::string const&, std::string const&) const
??:?
/usr/bin/coolwsd
net::AsyncDNS::resolveDNS()
??:?
/lib/x86_64-linux-gnu/libpthread.so.0
start_thread
/build/glibc-bkR840/glibc-2.27/nptl/pthread_create.c:463
```
Change-Id: I372802b872bc899874404e7317ecd9ecb1d0757a
* Resolves: # 
* Target …
> shutdown AsyncDNS before WebServerPoll shutdown

- browser/src/control/Control.Zotero.js
- browser/src/control/jsdialog/Widget.Combobox.js
- problem: in combobox widget we were always passing the `_defaultCallback` which will send `dialogevent` to server but in zotero's case the callback is different
- also fixes some `undefined type` errors
Change-Id: I7bd7aff6a1a3a9715123c1335ea83ab13fd7b22a
* Resolves: #9108 #9109 
> zotero: fix: can't select language or store as option in citation style

- kit/KitQueue.cpp
since:
commit 6f49f9398e237c46c71910915bf11925b85fd7a7
Date:   Thu May 9 09:19:44 2024 +0100
Split outbound callback processing from incoming message queueing.
an out by one adjustment
Change-Id: Ie5c2133dd7239aa62c017306c962c26ea6e526bb
* Resolves: # 
> multiple "EMPTY" invalidations for different parts dropped as dups

- common/Message.hpp
- wsd/SenderQueue.hpp
- wsd/TileDesc.hpp
Parsing a string to a TileDesc and then comparing is inefficient enough, without doing that in an N^2 loop for the SenderQueue.
Still N^2 - and of dubious value in the world of deltas; but in almost all cases a simple string + integer compare.
Change-Id: Ibe8230679e27b98cfa95567fea700e2f7d5ac09c
* Resolves: # 
> cool#9120 - use a simple hash to avoid most tile: comparisons.

- configure.ac
This change warns the user to install node and to update proper path in make file while building cool for iOS in Mac machines.
> Updating error message for node check while building cool for iOS.

- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Definitions.Menu.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Util.MessageRouter.ts
- browser/src/control/jsdialog/Util.SnackbarController.ts
- no functional changes, just a cleanup
- move types into single file and remove duplicates
- move snackbar internals into separate TS file (to be continued)
> jsdialog: cleanup and deduplicate

- browser/css/cool.css
- browser/css/leaflet.css
- browser/src/control/VRuler.ts
- Replacing the height value with the CSS variable will help maintain better consistency.
Change-Id: I0627778919885c8ee0a989f0b47b976304892585
* Resolves: # 
> Replace ruler height hard coded value with css-variable

- common/RenderTiles.hpp
- test/KitQueueTests.cpp
- test/WhiteBoxTests.cpp
- wsd/DocumentBroker.cpp
- wsd/TileDesc.hpp
If we have all default values of imgSize, wid, old-wid then we should simply not serialize these out to save space and improve readability.
Unfortunately, this means that we need to catch the mutation of the TileCombined's content in two places; now just one. Building the queue of rendered tiles to send back is now moved and wrapped into a TileCombinedBuilder class - this also lets us stop serialize taking a random vectors of TileDescs. However the DocumentBroker::handleTileCombinedRequest method needs to set the force-keyframe oldWid=0 flag on individual tiles and then update the TileCombined.
Ideally we would have a nice visitor API and drop the non-const getTiles() method that returns a reference to our internal vector.
Update tests, to not have redundant attributes, and add more tests …
> Cleanup and shorten tilecombine descriptor lists.

- cypress_test/integration_tests/mobile/impress/apply_font_shape_spec.js
unblock CI from:
cy:command ✘  assert	expected **<tspan.TextPosition>** to have attribute **y** with the value **'3286'**, but the value was **'3285'**
> cypress: quick fix for rounding error

- browser/src/control/jsdialog/Component.Toolbar.ts
- if we switch to compact mode & server get reconnected, some icons are visible in desktop which should be only visible in mobile view.
- in control.toolbar.js we call updateItem method for icon in mobile - `toolbar.updateItem({id: 'closemobile', type: 'customtoolitem', w2icon: 'editmode'});`
- after this updateItem call we should also check all condition about that item like - item should be visible in mobile or not - item should be available in tablet or not etc
- this patch will do that checks
Change-Id: I11adc3d94cacd4afe85e177d050ccc73f3112872
* Resolves: # 
> Close mobile icon should be hidden in desktop

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
- Input elements in jsDialog does not change state after CORE update message
- this is because in previous commits we changed input element structure.
- we should synchronize the child elements with parent.
- this patch will Synchronize disable state of parent with it's child elements
Change-Id: Ice94de732dc7392f3c79100e6a2d60480294eb0e
* Resolves: # 
> Fix state update of input element

- browser/css/jsdialogs.css
increased jsdialog width to fit content when necessary. max width is set to 1000px because some other dialog(i.e: Zotero) already uses tree widget width 800px which makes the entire dialog approx 990px.
removed margin from icon to make it look even spaced in listview (i.e: manage changes, zotero add citation)
Change-Id: I225b5b5d42d573cb4afcdb428e2eb3b81aa99073
> jsdailog:css: increase width to fit content in manage changes dialog

- browser/src/control/Toolbar.js
Change-Id: Ife153056b3dccb64b66a614c37532c59690bd792
* Resolves: 
#8876
#8280
- Fix Text box to not gobble up spaces before/after text
- Fix broken url when link has a leading space
- Added autofocus on input box of link when hyperlink modal opens
- Preserve Valid URL Protocols
- Automatically Add 'mailto:' for Email Addresses
> Writer: Fix broken urls, preserve valid URL protocol and enable auto-focus when hyperlink modal open

- fuzzer/Common.cpp
Recent a failed jenkins job had a lot of output, the tail of the log
starts with: "Skipping 3,970,746 KB".
I guessed that the problem is that the fuzzer figured out what is the
protocol to change log levels, but it isn't there yet.
What seems to happen is that fuzzer/Common.cpp defines the log level to
be "none", but this is not handled at GenericLogger::mapToLevel(), so we
managed to enable trace level for known-broken input where we're not
interested in the errors/warnings.
The fix can be tested by adding assert(false); to Log::log(), previously
the fuzzer failed with an assertion failure for a simple input like "12"
(unknown command) and now it just exits silently.
Change-Id: Ib5f4bedca706d7a0310a2eb9f661053a3095822d
> fuzzer: fix default log level

- README.md
The matrix saga seems to be solved now
- There were 3 rooms. I needed to remove both local and published address from there (the old matrix.org room)
- Skyler helped by setting the local address of the active room to the matrix.org
- Then we could set the published and the main address as #cool-dev:matrix.org
Change-Id: I7e73e0750dd94744eb0706230da40ab51bbad7f7
* Resolves: # 
> Update Matrix room name and url

- browser/css/jsdialogs.css
- the label between Structure tab and TreeView was misaligned. This is corrected with this commit.
- label "Structure:" changed to "Functions in use and their validity:" with https://gerrit.libreoffice.org/c/core/+/168161 (6c15d246afa1774298e1438f2117b593a065bfe4)
Change-Id: I197fb84154226709395f4f2789fc288367c00f05
* Resolves: # 
> Formula Wizard: better alignment of label that under the Structure tab

- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.TopToolbar.js
- Impress on tabbed and compact view didn't have the common (and in
used in the other apps) 'unoResetAttributes' css class
Set all with the same CSS class so integrators with customizations
are not force to single out special cases.
Change-Id: I82deb98a628b527470fcd2e54f1374df21380bfa
> Toolitem: Set Clear direct formatting btns with the same css class

- browser/src/layer/tile/CanvasTileLayer.js
That condition shouldn't be checked before scrolling to selection position.
This fixes "doesn't scroll to searched text" issue.
Change-Id: I9f901ba2fa15ade5416ad68f62e356e34163c641
* Resolves: # 
> Text selections handles should be active when there is a text selection.

- common/FileUtil.hpp
doesn't exist since:
commit fdf5687d7c76d8bea3268bcc65a42fcfc45b1877
Date:   Mon Apr 20 16:30:05 2020 +0300
Bin some dead code, this gets rid of a use of Util::alertAllUsers(), yay
Change-Id: I90976ab75649ab58197d593520d90d6579a07cfe
* Resolves: # 
> remove mention of saveDataToFileSafely that doesn't exist

- .gitignore
- ios/Mobile/Info.plist.in
There are various settings in Info.plist (generated from Info.plist.in at configure time) which are incorrect. Particularly important are the API and encryption declarations (which will be required to upload builds from tomorrow), and making the Collabora Office folder visible in iCloud (which stops files created from the recents tab being hidden)
This is a forward-port of #8933 
Signed-off-by: Skyler <skyler.grey@collabora.com>
> iOS: update Info.plist -> master

- .gitignore
- ios/Mobile/Info.plist.in
There are various settings in Info.plist (generated from Info.plist.in at configure time) which are incorrect. Particularly important are the API and encryption declarations (which will be required to upload builds from tomorrow), and making the Collabora Office folder visible in iCloud (which stops files created from the recents tab being hidden)
Signed-off-by: Skyler <skyler.grey@collabora.com>
> iOS: update Info.plist

- kit/Kit.cpp
wsd: always exit Kit when unloading
We never re-use a Kit process. Therefore,
when we unload a document, we must also
exit the Kit process.
Alternatively, when there is at least
1 session, we keep the document loaded
and the Kit process so that a new
view can be created.
> Unload Kit Session/View

- browser/src/control/Toolbar.js
1) press F2 to edit a formula cell with defined range
2) The reference it is marked and painted
3) The formula bar lost focus and force to clear the mark
The references will be cleared due to response from server message.
Change-Id: I32fbacc8d846cf8ba8b3371f3386d07e9cebe470
> browser: toolbar: avoid forcing to clear references

- browser/src/control/Control.UIManager.js
This is a fix for a regression from
I4cc9cc885aa8cd0b40646629cd73bef236963a94
Compact/tabbed mode was saved on a per-app basis, but read on a global basis. This meant that the read preference was never changed, causing it to be impossible to switch out of compact mode once you had entered it.
The fix is to change back to the previous behavior of saving and reading on a global basis
Refs: CollaboraOnline/Online#9181
Change-Id: Ie9d72d6b7e10e209f10acf662535c866e06a98de
> fix: allow changing compact to tabbed mode

- kit/ChildSession.cpp
- test/UnitCopyPaste.cpp
Have two COOL servers, copy on one instance, paste an on other instance,
nothing happens on Ctrl-V.
It appears the JS code in Clipboard.js
_dataTransferDownloadAndPasteAsync() gets the correct HTML, but when it
tries to contact the "copy" server for the underlying full clipboard,
some security policy prevents the JS code from doing that. Which means
1) perhaps we should do that HTTP fetch on the server, not in JS and 2)
the fallback code should at least work via normal HTML.
Fix 2) by extending ChildSession::setClipboard() to recognize if the
data has the typical HTML header, and only start the usual parsing in
case the data we got is not bare HTML.
The 1) still needs fixing.
Change-Id: I55a102c2a39d21ac898f82041760a220e46784cb
> cool#9219 kit: fix setclipboard command with HTML payload

- browser/src/control/jsdialog/Util.MessageRouter.ts
Fix for using uninitialized app.map, when calling cool.html without parameters:
Uncaught TypeError: Cannot read properties of null (reading 'fire')
at JSDialogMessageRouter.processMessage (Util.MessageRouter.ts:95:12)
at NewClass._onJSDialog (Socket.js:1540:26)
at NewClass._onMessage (Socket.js:1292:9)
at NewClass.showModal (Control.UIManager.js:1139:14)
at NewClass.showInfoModal (Control.UIManager.js:1250:8)
at main.js:79:16
at main.js:137:2
> jsdialog: use early initialized map

- browser/src/canvas/sections/ScrollSection.ts
Mobile (not tablet) mode has a different sort of scrollbar to desktop
mode. Like the desktop scrollbar, it should render on the other side if
we are in RTL mode.
---
This is a fix for a regression which I introduced in
If4261a3e32375f6127241b846b97a3b4ac29eb0b.
Before this fix we were flipping the direction of scrolling on RTL mode
twice, once in onMouseMove and once in scrollHorizontalWithOffset. This
had the effect of cancelling to not flip the scroll at all. Oops.
The scrollHorizontalWithOffset isRTL distinction is still important to
keep for panning, so I'll remove the other one.
---
In If4261a3e32375f6127241b846b97a3b4ac29eb0b, I introduced isRTL, which
can be set at construction of a ScrollSection. Unfortunately, some
places in ScrollSection still used isCalcRTL which could …
> RTL scroll fixes

- browser/js/global.js
- test/FileServeWhiteBoxTests.cpp
- test/integration-http-server.cpp
- wsd/FileServerUtil.cpp
savedUIState isn't a normal UI_default, so it doesn't show up in the
ui_defaults list, and we can't fetch it with our prefs helper. Instead,
we should use the property on window
---
Previously we converted some ui_defaults values to booleans.
Unfortunately, when we save similar preferences to LocalStorage, we can
only save them as strings. To make sure code doesn't get booleans when
it's expecting everything to be a string, let's only send strings back
in our ui_defaults json
---
Finally, I figured out a way to stop compatibility breakages being so annoying
with the prefs refactor without needing to keep a prefs dictionary
around forever.  If, on starting the application, we set new preference
names to old preference values we can choose when to break
compatibility.
This will allow us to …
> fix: various fixes to prefs

- browser/src/control/Control.ServerAuditDialog.ts
I see this on a local nextcloud where the audit dialog only has one entry which is "ok".
Change-Id: I55f12125cbc0ca4c88c9220ed114d455e84639e0
* Resolves: # 
> Don't show audit snackbar if all entries are all 'ok' state

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
problem:
when we imported comments we cleared all the comments and inserted every comments from start.
This caused problem if some action from another user caused to import the comments for all users(i.e: show/hide changes) This means if comments are in autosave state, import will fail
Change-Id: I888dfeb53fb215f7c7a0507593a06b09da7caf64
> annotation: show dialog for conflicting comment modification

- browser/src/map/Clipboard.js
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Copying the full clipboard (including ODF) from a remote server into the
JS client failed with:
Refused to connect to '...' because it violates the following Content Security Policy directive: "connect-src ..."
If this happens, still send the original URL to the server, so it can
download the full clipboard, which gives better result for pasting,
compared to going via HTML only.
Not done in this commit: 1) the JS still tries to get the clipboard
itself, we download on the server only on failure and 2) the server does
a blocking HTTP download, which may not be wanted.
Change-Id: I9ed8c8050f9dbe71dc8fcd36c9d8fa6e8bba44f6
> cool#9219 clipboard: support URLs in the payload of the setclipboard command

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/control/Control.ContextMenu.js
On small window sizes, a context menu may be forced to open in such a way that it goes over the same region as the notebookbar or spreadsheet tabs.
In that case, the context menu should be above the other element, or some of the context menu options could be unreachable.
Change-Id: Id269e3fb9bc2251677a0792d83fc51bd56b9cb21
> fix(contextMenus): move above UI elements

- browser/src/layer/tile/CanvasTileLayer.js
Previously we were mixing up lat/lng, which made calc jump to unexpected places when the person we're following's cursor is offscreen.
Change-Id: I4db4c93118fbc3ffd04c7152652ccd2b26209b5d
* Resolves: # 
> fix(calc): Prevent following view jumps

- browser/src/control/Control.MobileWizardWindow.js
Previously, when entering or exiting mobile wizard sublevels you would start scrolled down to the place you were before. For example, if you scrolled down a few items on the main context menu of an image in order to reach "arrange", you would always end up right at the bottom of the "arrange" menu.
By always scrolling up to the top, we can prevent you from ever having content hidden above you.
Change-Id: I02365ecef859fb6f199d14a12a49937d5a30b8e7
> fix(mobileWizard): Always start at the top

- browser/src/canvas/sections/CommentListSection.ts
problem:
Core behaviour:
if comment A has 3 replies (i.e: in order B, C, D) when user again replies to comment A
a new reply will be inserted after A but before B.
But in online same reply will be displayed after D. On reload of the document or after save-as when comments are reloaded, this order will change as comments in the doc is saved according to the core behaviour.
Change-Id: I3bf4e06c4b6f48eb086c7eaebe102eac0f90681d
> annotation: match the reply order to core

- browser/src/control/Control.ServerAuditDialog.ts
- browser/src/control/Control.UIManager.js
- browser/src/docstate.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.VersionBar.js
- common/Session.cpp
- common/Session.hpp
- test/httpwstest.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
and set old is_admin inside UserExtraInfo as deprecated
TODO: SDK update so links will point to the content
> ServerAudit: use IsAdminUser property

- common/Log.cpp
- fuzzer/data/crash-87714cc10c192b4d917cdc3a6fac1841a11d91f4
This was similar to commit 2c82f0a712962f1e5c7285912014a738626fd48b
(fuzzer: fix default log level, 2024-05-29), but here the fuzzer figured
out how to increase the log level. Explicitly avoid setting the log
level in setThreadLocalLogLevel() for the fuzzing case to avoid the
huge, uninteresting logs: we just want the output from the fuzzer
itself, not from the fuzzed code.
Change-Id: I92623f1c384ce7d4b746d3cbdc6a7c911a2f29a6
> fuzzer: reject increasing the log level

- browser/src/layer/tile/CommentListSection.ts
problem:
Core behaviour:
if comment A has 3 replies (i.e: in order B, C, D) when user again replies to comment A
a new reply will be inserted after A but before B.
But in online same reply will be displayed after D. On reload of the document or after save-as when comments are reloaded, this order will change as comments in the doc is saved according to the core behaviour.
Change-Id: I3bf4e06c4b6f48eb086c7eaebe102eac0f90681d
> annotation: match the reply order to core (backport)

- browser/src/layer/tile/CanvasTileLayer.js
Scroll the new position if the cursor is not
visible.
Change-Id: Ib5a77fefa5ec16defa0695806c770f21beec4243
> browser: fix PageDown cursor position

- browser/css/jsdialogs.css
In case 800px is bigger than 80% of the screen - use 80%. This helps with "server audit" and "zotero" on tablet like iPad mini
After:
> Tablet: use dialog width which fits the screen

- test/UnitCopyPaste.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
This is something no sensible webserver would ever server for a normal
file, so we likely only download COOL clipboards and nothing else.
Noticed the missing DocumentBroker::lookupSendClipboardTag() case while
working on the test.
Change-Id: Ib69115feaed6bff36b270b072a0e38fabe35d8c9
> cool#9219 clipboard: add custom X-COOL-Clipboard header

- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.VersionBar.js
- before setting the viewId we check for _documentInfo in onStatusMsg, it might happen that on reconnect documentInfo remains same.
- steps to reproduce:
1. Open writer document 4 times in different tabs
2. Kill the server (Ctrl + C)
3. Run the server again and wait of clients to reconnect
4. Check all the tabs, there must one tab where you should see the userlist empty. If not, kill and run server again...
- this patch fixes it by reseting the _documentInfo on socket disconnection
Change-Id: I7be045f2b2433b9e12b6749fefbdd53ab5f0a0cd
* Resolves: # 
> fix: sometimes userlist is empty on reconnect

- browser/html/cool.html.m4
This reverts commit 1ed033efe816ab3c2fb02cbe8455bc2525fb4ffc, and I've also added a comment to avoid the same mistake happening again.
Removing this function prevents the Android webview communicating with the C++ code, it's vitally important for it to remain so long as this is still the case. It's not directly used in our JavaScript, though, so this is a fairly easy mistake to make.
Change-Id: I160363d5739a4ea3601348c0059488e39468c4b6
This will need to be ported to master, however I wanted to merge to 23.05 first as that is the current Android base
> Revert "browser: remove unused function "Base64ToArrayBuffer""

- wsd/Admin.cpp
- if monitor connection to doesn't exist because maybe controller died or something we shouldn't wait for migration messages
Change-Id: I568f365f534e100010fe31ef6ae80f1b4c839cc2
> admin: handle case where monitor connection to controller is disconnected

- browser/src/control/Control.UIManager.js
I noticed this in our richdocuments cypress tests which try to open a file with both classic and notebookbar mode depending what is configured by the admin.
This fixes the compact mode when integrators set it through the ui_defaults with UIMode=classic or UIMode=compact
Currently the backend uses either notebookbar or classic as UI mode values not compact, so the check seems to have never worked as intended
https://github.com/CollaboraOnline/online/blob/master/wsd/FileServer.cpp#L1300-L1307
https://github.com/CollaboraOnline/online/blob/master/wsd/COOLWSD.cpp#L2171-L2178
https://github.com/CollaboraOnline/online/blob/master/wsd/FileServerUtil.cpp#L217-L228
Patch that can be used for testing:
```
--- a/browser/html/debug.html
+++ b/browser/html/debug.html
@@ -17,6 +17,8 @@
<body>
<form …
```
> fix: Properly check for ui mode set by coolwsd

- browser/src/canvas/sections/CommentListSection.ts
This is particularly relevant on touch devices, where some events can be triggered a bit differently to desktop. Previously it was sometimes hard to reply to or edit a comment as upon hitting the modify/reply buttons we would consider the comment deselected and collapse it.
The easiest way I have found to deal with this is to prevent the collapse during an edit
Change-Id: I740b1c260e9ee63bac6e667f99ed6da141d71a9c
* Resolves: # 
> fix(comments): avoid comment collapse during edit

- browser/src/layer/marker/TextInput.js
Change-Id: I6bc6575cc28126388c7c88424128d0ec7f341610
* Resolves: # 
> Can't show the cursor before the _tileWidthTwips is set.

- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
its skipped because its filtered on slurp
add explicit logging for it in its handler
_logSocket is currently only called in two places that both check the same debugging flags so move that check inside _logSocket.
Change-Id: Icacd8b99b4aaf5feaa468f89b3273101d6722ca6
* Resolves: # 
> invalidatetiles not logged like the other incoming messages

- browser/src/control/Control.ContextMenu.js
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/layer/tile/CommentListSection.ts
This is a trivial backport of my context menu fixes, #9228 and #9230.
I didn't include #9277, as it is not yet merged.
---
On small window sizes, a context menu may be forced to open in such a
way that it goes over the same region as the notebookbar or spreadsheet
tabs.
In that case, the context menu should be above the other element, or
some of the context menu options could be unreachable.
Change-Id: Id269e3fb9bc2251677a0792d83fc51bd56b9cb21
---
Previously, when entering or exiting mobile wizard sublevels you would
start scrolled down to the place you were before. For example, if you
scrolled down a few items on the main context menu of an image in order
to reach "arrange", you would always end up right at the bottom of the
"arrange" menu.
By always scrolling up to the top, we can …
> Context menu fixes

- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Ruler.js
- browser/src/control/Toolbar.js
-  Initialized ruler UI for DOCTYPE Presentation
- Now functionality is available independent of the selected view.
- Ruler is present in both Compact/Tabbed view
Change-Id: Ie443a69d0afead8fde2ac08b63442b491710fcb8
* Resolves: # 
>  Presentations: Ruler

- test/run_unit.sh.in
If it's this large, it will be some endless loop and the start will go
outside the console history anyway, but it can fill the disk with logs on
CI.
Change-Id: I89f9cc1afb6436210d825f1f60cbccb8ed5e48b3
> test: avoid showing too large files

- common/Log.cpp
The failure was:
==79463== ERROR: libFuzzer: out-of-memory (used: 2053Mb; limit: 2048Mb)
392260464 byte(s) (45%) in 5448062 allocation(s)
#0 0x5648cd721266 in operator new(unsigned long) /home/abuild/rpmbuild/BUILD/llvm-15.0.7.src/build/../projects/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
#1 0x7f8c4bd0e7ed in Poco::Logger::add(Poco::AutoPtr<Poco::Logger>) (/usr/lib64/libPocoFoundation.so.92+0xf57ed)
Given that Log::setThreadLocalLogLevel() calls GenericLogger::create(),
which calls Poco::Logger::add(); and given that
StaticHelper::setThreadLocalLogger() explicitly leaks loggers, fix the
problem by returning earlier in Log::setThreadLocalLogLevel() for the
fuzzing case, the new logger would not be activated anyway.
Change-Id: …
> fuzzer: don't leak poco loggers

- browser/src/control/Control.Menubar.js
- browser/src/control/jsdialog/Definitions.Menu.ts
Previously, the menu and submenu of conditional formatting options were technically correct but not very readable. We replaced 'Condition...' with 'Highlight cells with...'.
Change-Id: I92a326e1394d1b40211748062c5bcddea049ffb4
* Resolves: # 
> Improvement to conditional formatting

- browser/src/layer/vector/SVGGroup.js
It's important to have correct WOPISrc for load balancers. We need to decode "&" before other params like ServerId and Tag so load balancer will not use it as a part of WOPISrc.
In other case when I had 2 instances of COOL behind HAProxy sometimes request to get the video was forwarded to the wrong instance.
> Fix video playback with load balancer (23.05)

- browser/src/canvas/sections/ShapeHandlesSection.ts
It's important to have correct WOPISrc for load balancers. We need to decode "&" before other params like ServerId and Tag so load balancer will not use it as a part of WOPISrc.
In other case when I had 2 instances of COOL behind HAProxy sometimes request to get the video was forwarded to the wrong instance.
> Fix video playback with load balancer (master)

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.VersionBar.js
It will look like this in the browser logs:
- IN viewinfo: ...
- IN adminuser: ...
and if we are the admin:
- OUT versionbar
- IN versionbar: ... < latest version ... if needed show the message
Thanks to that snackbar will be shown on the load, not when next user joins.
> Use dedicated signal for version bar initialization

- browser/src/docstate.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.VersionBar.js
- common/Session.cpp
- common/Session.hpp
- test/httpwstest.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
- wsd/Storage.hpp
This is partial backport from master (without audit dialog). Unifies admin detection.
Should fix problem with notifying regular users about updates.
-----------------------------------
Fallback and warning for using is_admin in the browser
We migrated to using IsAdminUser:
https://sdk.collaboraonline.com/docs/advanced_integration.html#isadminuser
Warn in the browser logs about that for debugging the integration.
Also use fallback if someone is still using old is_admin property.
These properties are used to show additional notifications in the UI
like: new version is available.
-----------------------------------
Use optional isAdminUser to detect when it is missing
-------------------------------
Pass IsAdminUser property to the client
- use app.isAdminUser for storing it
- use adminuser: …
> Use IsAdminUser (23.05)

- browser/src/layer/tile/CanvasTileLayer.js
This is followup to the commit d3ed75d0a2f7adecf682b9fd4803f7b734bdb437 User following: don't mark myself as followed
- detection of "visible cursor" both for cell cursor and text cursor
- only scroll to the cursor if we really follow ourself (when not Off)
> Scroll to cursor only if we want to follow ourself

- common/Log.cpp
- fuzzer/admin-data/crash-c3a9755c1f4fbbb7414b80f8eee6e1f518cad28f
Similar to commit 9e3de293af4a0df9d6d2834356ba964657a9d41a (fuzzer:
reject increasing the log level, 2024-06-12), but that was for
setThreadLocalLogLevel() used by the loggingleveloverride protocol
command, and this is for setLogLevelByName() used by the
update-log-levels protocol command.
Change-Id: I56eb8c311e01a995604d408d1933559890499a0b
> fuzzer: reject increasing the log level via update-log-levels

- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/RequestVettingStation.cpp
The iOS and Android platforms run the LibreOffice backend in the client process so there is no SSL sockets. Instead, all client and server communication is done through a buffer shared between threads.
> Fix mobile build breakage

- browser/css/jsdialogs.css
Before this commit things like status language dropdown etc were being
rendered with a light color
Change-Id: Ie2af6f4f88ff1b99fa6ee658a8dc8e700deac977
> Dark mode: Fix dropdown shadow: use correct css var

- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/RequestVettingStation.cpp
This is a trivial backport of #9340
The iOS and Android platforms run the LibreOffice backend in the client
process so there is no SSL sockets. Instead, all client and server
communication is done through a buffer shared between threads.
> backport 24.04: Fix mobile build breakage

- browser/src/control/Control.Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- kit/ChildSession.cpp
Right now .uno:CopyHyperlinkLocation only works on edit mode or
inside a draw object, but LOK_CALLBACK_HYPERLINK_CLICKED is
dispatched outside of edit mode and the copy command from
the pop-up is ignored.
Since there is no text cursor, the position of the hyperlink is
needed to discriminate the correct field, since there could be
multiple hyperlink fields inside the same cell.
Change-Id: Ie814867e0a4a319e78381b68343847491034d85f
> calc: fix copy hyperlink outside of edit mode

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/css/notebookbar.css
Before this commit there were
- Odd border artifact
- The styles previews were being rendered and looked like detached
rectangles (with different background than the background of the main
container)
This commit fixes those while making use of css vars. Additionally,
decrease the brightness of the whole stylesview to 90% (100% on hover
state) so the user doesn't have a very bright component always up
there.
Change-Id: I1bb21871d8a866f8f4308efda937904ac97504bb
> Stylesview: Fix dark mode background and border

- coolwsd.service
- debian/coolwsd.service
- kit/Kit.cpp
Since commit 144b701453de72c7c5a741cc148a42b25c309ad4 
cool#8703 - Drop random node creation and rely on inherited fd.
Change-Id: Iea3610989fa9eb46c41a9d3d2d6627ffa479cbd1
> CAP_MKNOD is no longer used

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/control/Control.UIManager.js
Inverts calc document color even app is dark mode. Follow-up 8cd1245efa3f98b64853053ebd8e479ae62db133
Other components has special DOCCOLOR and canvas color behind the document. Calc is special case because we see directly canvas color behind the cells. DOCCOLOR doesn't affect here directly. So we handle calc case in this commit.
Change-Id: I56b279495cb050d79ee5452b363c8bf7e5b1026e
* Resolves: # 
> Invert Calc document color

- browser/src/control/Control.NotebookbarWriter.js
Use the previously translated string "Accessibility Check" instead of
the one that comes from the uno command "Open Accessibility Check Deck"
Change-Id: Id4ace21a933e31405a76eda7a530c05aea4d1c21
> Accessibility Check btn: Fix label

- browser/src/control/Control.NotebookbarWriter.js
Sometimes when a user shares a file that doesn't allows to be re-shared
but allows to see revision history the button is rendered oddly
Change-Id: I8119b063d6c243141e06bdfeeb00acc326e2370f
> File tab: Revision history sometimes is rendered as inline button

- browser/css/leaflet.css
Before this commit the vertical ruler when the page is zoomed in would
expand beyond its parent. The result: ruler was present under
tabs. Example:
- Integrator has tab container margin (ruler would be visible full
height)
- User customized the color of the tab container making it transparent
Change-Id: I71d17c18c899cdb19b2c7e3bfd9903ba87221a78
> Ruler: Clip it, don't spill over other UI elements

- browser/html/framed.doc.html
Add button in the post message tester to verify if inserting an image works properly. I used resource from our SDK so it is external domain, if not allowed it shows an error. We need to add domain to coolwsd.xml in the lok_allow section to allow importing the image.
> postmessage demo: insert graphic test (master)

- test/.gitignore
- tools/Replay.hpp
Change-Id: I415d414c832a00d2b55815df89f28a2d836a1290
* Resolves: # 
The performance of the CPU is measured by the run time in ms, Network by the incoming and outgoing bandwidth in kB/s and latency is split into buckets of ping and tiles in ms. The data is stored in separate CSV files which will be updated each unit test allowing the performance data to be in a form which can be re-used, graphed or at-least monitored in the future.
> feat: record the performance of CPU,Network,Latency

- test/UnitWOPILock.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
This resolves #9185.
The issue relates to loading asynchronously. This ahead-of-time loading is done before the client opens the WebSocket. This meant that the locking function didn't have the necessary details to decide whether locking was needed or not, and so it was skipped. The issue wouldn't happen if by the time we downloaded the document the WebSocket was created. As such, this is a time-sensitive bug. However, reports indicate that it's not uncommon that we weren't taking the lock.
The issue is resolved with this PR and now we take the lock when the _first_ editor joins (and as before, we unlock when the _last_ editor leaves). An improved unit-test asserts this behavior.
- wsd: all view-only extensions accept comments
- wsd: minor refactor around on-demand CFI
- wsd: always set …
> Locking Documents

- browser/src/layer/vector/Polygon.js
- browser/src/layer/vector/Polyline.js
instanceof L.SplitPanesSVG is not found since removed at:
commit 2c92b1e8c95126d5032db0e3d1fc24bac8cdb0f7
Date:   Fri Jun 28 21:14:29 2024 +0300
Remove unused files.
Change-Id: Idb83dd388a7d93cce35f0fb97c8049d35c95851c
* Resolves: # 
> fix debugging overlay

- browser/src/control/Control.MobileWizardWindow.js
This is a backport of #9277
* Resolves: # 
> backport 24.04: feat(mobileWizard): keep past scroll position

- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
There is some instability with annotation ids. Sometimes it has the id annotation-content-2 instead of annotation-content-1. (or -3 instead of -2). The fix is to make the test look for either id.
Change-Id: Ie3759b5001f7194efea2d613752363bb0462f61f
* Resolves: # 
> Fix failing impress annotation tests

- docker/from-source/Fedora
similar to the openSUSE one. Tracks latest fedora, assumes 999 as the cool userid
Change-Id: Ibaf564d84a08314e39d8cca2446b8bfac8a01371
* Resolves: # 
> add a Fedora DockerFile

- common/CoolMount.cpp
- tools/mount.cpp
because we have changed uid within that namespace to 0 when using mount namespaces
--enable-debug disables this check, so missed that.
Change-Id: I162ad8c384064dc49056155b2858fd95cd05b2cb
* Resolves: # 
> don't use hasCorrectUID for mount namespace case

- common/FileUtil.cpp
- common/FileUtil.hpp
- common/JailUtil.cpp
- net/HttpRequest.hpp
- wsd/DocumentBroker.cpp
- wsd: do not re-use incoming response for outgoing
- wsd: jails: remove empty directories
- wsd: jails: failure to unmount is not an error
- wsd: simplify renaming after save
> Jail Clean-up

- browser/src/control/Control.NotebookbarWriter.js
Use the previously translated string "Accessibility Check" instead of
the one that comes from the uno command "Open Accessibility Check Deck"
Change-Id: Id4ace21a933e31405a76eda7a530c05aea4d1c21
> [Backport] Accessibility Check btn: Fix label

- browser/src/control/Control.NotebookbarWriter.js
The initial fix was merged with
33163c1f8789d461ca77f425e1c43d5b8b5f1e84 but was introducing a new
translatable string with it
Change-Id: I3723e1e3d4bb204894b9c0ec74b9e35937f914b3
> Accessibility Check btn: Fix label: avoid new translatable string

- browser/src/layer/tile/CanvasTileLayer.js
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- wsd/ClientSession.cpp
This adds support for getting the presentation info from core. This change uses the new GetPresentationInfo() funciton that was added to the LOKit API.
Change-Id: I19f5809fd841e4b2603a2446e1d9d54392dd1bd7
* Resolves: # 
> Add support for "getpresentationinfo" command

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/css/notebookbar.css
Before this commit there were
- Odd border artifact
- The styles previews were being rendered and looked like detached
rectangles (with different background than the background of the main
container)
This commit fixes those while making use of css vars. Additionally,
decrease the brightness of the whole stylesview to 90% (100% on hover
state) so the user doesn't have a very bright component always up
there.
Change-Id: I1bb21871d8a866f8f4308efda937904ac97504bb
> [Backport] Stylesview: Fix dark mode background and border

- wsd/COOLWSD.cpp
We need to initialize these, because we saw in the wild that a customer removed the empty defaults from coolwsd.xml and coolwsd stopped with fatal error.
Change-Id: Ifc75e3eb2fe50c2028f84d8f61ba5a034b14b4cf
> Initialize storage.ssl.* config items

- browser/src/control/Control.Header.ts
in a spreadsheet with a rows tall enough to show the vertical resize indicator in the column ui to the spreadsheet left
select the row by clicking on its entry in the column ui, then hover the mouse over the resize indicator and click and drag to the right, and release over the spreadsheet content, it might take 3 or 4 attempts.
Change-Id: I95d3a76b33a50d4f1cc600832c6759785f0f16cf
* Resolves: # 
> _prevMouseOverEntry seen as null on dragging row resize indicator right

- common/CoolMount.cpp
- common/JailUtil.cpp
- tools/mount.cpp
in deployment on remounting the mount pointing to /opt/cool/systemplate with an additional MS_NOATIME results in EPERM.  Where that dir is on a (toplevel) [rel]atime mount.
man 2 mount states 'An attempt was made to modify (MS_REMOUNT) the MS_RDONLY, MS_NOSUID, or MS_NOEXEC flag, or one of the "atime" flags (MS_NOATIME, MS_NODIRATIME, MS_RELATIME) of an existing mount, but the mount is locked'. Presumably we can add flags that drop privs, but not those that could circumvent original mount policy.
Change-Id: I4c0c6a6e4a0e7fae04255e247b18cd5a86c3f327
* Resolves: # 
> namespace mount can fail due to adding MS_NOATIME

- kit/Delta.hpp
==3858==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow /usr/bin/coolforkit
__asan_memcpy
asan/asan_interceptors_memintrinsics.cpp:22
/usr/bin/coolforkit
DeltaGenerator::copy_row(unsigned char*, unsigned char const*, unsigned int, LibreOfficeKitTileMode)
online/./kit/Delta.hpp:522
/usr/bin/coolforkit
DeltaGenerator::DeltaBitmapRow::packForNetwork(unsigned char*, LibreOfficeKitTileMode) const
online/./kit/Delta.hpp:175
presumably an issue since:
commit a9d4dcb71d61e3c8825c439b84cf0739f48b6341
Date:   Mon Jun 10 17:07:00 2024 +0100
deltas: zstd compress already RLE compressed pixels.
Change-Id: Iba3288a3efc3f6df3411ff2ecc66ce5d89693ea2
* Resolves: # 
> rle data size is two bytes not one

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.SidebarContainers.ts
Add aria labels to 'More option' button in sidebar
- Add aria>label data to toolbutton struct when creating more option button for Panel
- Removed alt attribute from Tool Button since buttons don't support alt attribute
- Added condition to set alt for button image from aria>label, if present
Change-Id: Ic608ee29891154e0f46523a1f5b1e5c249c54c6a
> Add aria lables to more option button in sidebar

- .gitignore
dist_git_hash is used in distribution, and might also be needed if git is unavailable or broken (for example certain bind-mounts into docker containers or use of tools such as jj).
One thing you absolutely mustn't do, however, is commit it. It overrides future git commit detection, which would subtly cause caching and/or version issues for everyone.
Let's gitignore it to avoid that.
Change-Id: I9cf5412bf6693afab7cb7b0ca2a8a377575ed929
* Resolves: # 
> fix(gitignore): Add dist_git_hash

- tools/Replay.hpp
Rewrite .uno:Save as it crash (in debug)
Change-Id: Ifae0ffb007ab13150f4e021e2c557fdf062910b5
* Resolves: # 
To allow older replays, two of the commands have been removed and case the test to bail out. `.uno:Save` is no longer allowed directly, and triggers an assert (fatal in debug) so it is rewritten.
> coolstress: Rewrite removed commands

- wsd/DocumentBroker.cpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
We don't need a mutex & a condition - we can just spin our own TerminatingPoll to get what we need; saves launching an un-necessary thread, and reducing threading complexity.
Change-Id: Ia65398aa8a59ca297cd0a0caf0fa607681960764
* Resolves: # 
> wsd: CheckFileInfo - avoid over-complicating things.

- wsd/ServerAuditUtil.cpp
- wsd/ServerAuditUtil.hpp
[ websrv_poll ] SIG   Fatal signal received: SIGABRT code: 18446744073709551610 for address: 0x730000696e
Backtrace 26990 - wsd 24.04.4.4snapshot 07bc101:
__GI_abort                                     glibc-2.27/stdlib/abort.c:81
__GI___pthread_mutex_lock                      glibc-2.27/nptl/../nptl/pthread_mutex_lock.c:67
ServerAuditUtil::set(std::string, std::string) /usr/include/c++/12/bits/std_mutex.h:103
SocketDisposition::execute()                   /usr/include/c++/12/bits/std_function.h:591
SocketPoll::poll(long)                         /usr/include/c++/12/bits/shared_ptr_base.h:1070
Also cleanup member naming to match the COOL standard.
Change-Id: I4fd6f4d57c3cbfe1edf7121895e5dab7e13fa4fc
* Resolves: # 
> Attempt to fix curious assertion around ServerAuditUtil.

- browser/html/debug.html
- browser/html/wasm.html
- browser/src/map/handler/Map.Print.js
- browser/src/map/handler/Map.Welcome.js
- Add a 'title' attribute to each iframe element, providing a brief but clear description of the content and purpose of the iframe
Change-Id: Ie2179e9d39d9f4f00be5eebf7d30509d0b31cc0b
> Add 'title' attribute to iframe for accessibility

- browser/html/framed.doc.html
Add button in the post message tester to verify if inserting an image works properly. I used resource from our SDK so it is external domain, if not allowed it shows an error. We need to add domain to coolwsd.xml in the lok_allow section to allow importing the image.
> postmessage demo: insert graphic test

- browser/src/canvas/sections/URLPopUpSection.ts
Right now .uno:EditHyperlink and .uno:RemoveHyperlink only work on
edit mode or inside a draw object, but LOK_CALLBACK_HYPERLINK_CLICKED
is dispatched outside of edit mode.
Since there is no text cursor, the position of the hyperlink is
needed to discriminate the correct field.
Change-Id: I8499b430d5e62b904caba5bb5c7c34e784a8b850
> calc: fix edit and remove hypelink outside of edit mode

- wsd/FileServer.cpp
regression from 246e87fea21d6121fd4bd2daeff8a4f92082477e 
we've got [ERRFMT].js and [ERRFMT].css
Change-Id: Ic59257fedb6d9ae6712f7f9ff16022c01f70112a
> Fix branding of COOL Lite when key is not present or expired

- common/FileUtil.cpp
- common/FileUtil.hpp
- common/JailUtil.cpp
- common/JailUtil.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/Storage.cpp
use buildLocalPathToJail instead of direct JAILED_DOCUMENT_ROOT concat
e.g. download as pdf/save as pdf
move buildLocalPathToJail to FileUtil instead of JailUtil given
that the JailUtil code isn't built on mobile
Change-Id: I6f8ddaf1053d084ec8c1f22adf830a677e80cadc
* Resolves: # 
> use buildLocalPathToJail instead of direct JAILED_DOCUMENT_ROOT concat

- wsd/COOLWSD.cpp
It pays from a latency perspective to have fewer machines or containers each with more threads, rather than more of them with fewer threads.
Change-Id: Id791438d080989ffcf6b079e551f622cf92353e2
* Resolves: # 
> Warn on low thread count systems.

- browser/html/cool.html.m4
- browser/src/control/Control.JSDialogBuilder.js
Changes are based on below points to improve accessibility
- The element that serves as the toolbar container has role toolbar.
- If the toolbar has a visible label, it is referenced by aria-labelledby on the toolbar element. Otherwise, the toolbar element has a label provided by aria-label.
- If the controls are arranged vertically, the toolbar element has aria-orientation set to vertical. The default orientation is horizontal.
Change-Id: I38f234461d4bf7982eec01ffe866c390256f50a0
> Accessibility: Add ARIA roles for buttons

- browser/src/canvas/sections/CommentListSection.ts
when entire comment list was imported initially
or after showing hiding changes, animation
was played multiple times which was annoying
and distracting to users
Change-Id: I8a3da3cd551288bef94f5627ca11effd85bf99d0
> annotation: remove initial comment animation

- browser/css/jsdialogs.css
Change-Id: Ic3d751e2f781441f0b860183773fac752147972e
* Fixes : https://github.com/CollaboraOnline/online/issues/9320
> fix: unusual spacing between the icons in the mobile view 

- browser/src/control/Control.UserList.ts
When user used "following user XYZ" chip to unfollow someone, then not all properties of the state were set and the next try of following someone was not jumping th the cursor.
This fixes that without much change in the code. As a followup I will try to reduce the complexity by keeping single state for the following. Currently we duplicate it in the UserList component and docstate
> following: correctly turn off

- browser/src/control/jsdialog/Widget.MenuButton.js
Fox example font color item on the notebookbar didn't have tooltip with the name of a button.
> jsdialog: add tooltip to menubutton

- browser/src/control/Control.StatusBar.js
- browser/src/docdispatcher.ts
- Fix: animate "Reset Zoom" to remove traces of previous document zoom level
- sync zoom options
Change-Id: I1dc7847e21ab3cb56b9ec01a1a8f577bb26366d1
* Resolves: #7214
> fix: animate zoomreset to remove traces of previous document zoom level

- kit/ChildSession.cpp
Send encoded JSON string instead of decoded.
This way it will not have special characters, and it will reach the core side even with a \n or \r inside ot it.
This way we can set multi-line text to a contentControl.
Change-Id: I8b32aeef522faf7f4597405bec9bbb37b99d53cf
* Resolves: # 
> fix EOL issue in transform Document Structure

- fuzzer/data/crash-b496d62466ab907e19b8418d1dde11855a4ebc50
- wsd/DocumentBroker.cpp
Avoids this assertion failure:
#7 0x7f9fbef8fcf1 in __assert_fail (/lib64/libc.so.6+0x42cf1) (BuildId: cfb059a57e69ac95d5dadab831626b3bd48a4309)
#8 0x55d44ed78891 in DocumentBroker::startActivity(DocumentBroker::DocumentState::Activity) /home/vmiklos/git/collaboraonline/online-fuzz/./wsd/DocumentBroker.hpp:1550:13
#9 0x55d44ee0884f in DocumentBroker::startSwitchingToOnline() /home/vmiklos/git/collaboraonline/online-fuzz/wsd/DocumentBroker.cpp:4654:10
#10 0x55d44f05760a in ClientSession::_handleInput(char const*, int) /home/vmiklos/git/collaboraonline/online-fuzz/wsd/ClientSession.cpp:1168:20
Change-Id: Iedc515b90c0e4f43dc14f0d998ba5c756fddd10d
> wsd: avoid nested startActivity()

- browser/src/map/handler/Map.Scroll.js
wsd-308160-312471 2024-07-17 08:14:44.302140 +0000 [ docbroker_031 ] ERR  ToClient-7e2: jserror {
"userAgent": "mozilla/5.0 (x11; linux x86_64; rv:127.0) gecko/20100101 firefox/127.0",
"vendor": "",
"message": "TypeError: docLayer is undefined",
"source": ".../browser/.../bundle.js",
"line": 20766,
"column": 37
}
docLayer is undefined
L.Map.Scroll<._onWheelScroll<@.../browser/.../bundle.js:20766:37
Change-Id: Ibaa7aef4051977e708b7dad5396ac0564b06a5af
* Resolves: # 
> undefined docLayer seen on _onWheelScroll

- browser/src/layer/marker/Marker.Drag.js
this can be reproduced by inserting a table in writer, and then clicking and dragging one of the "marker" indicators above the columns
wsd-308187-308314 2024-07-17 06:59:38.909586 +0000 [ websrv_poll ] ERR  jserror {
"userAgent": "mozilla/5.0 (x11; linux x86_64; rv:109.0) gecko/20100101 firefox/115.0",
"vendor": "",
"message": "TypeError: this._marker.closePopup is not a function",
"source": "https://.../browser/.../bundle.js",
"line": 21863,
"column": 88
}
this._marker.closePopup is not a function
_onDragStart@https://.../browser/.../bundle.js:21863:88
possibly since:
commit 9932ad7516f55c46a0713231fe1f481bebdba378
AuthorDate: Tue Jul 9 18:41:52 2024 +0300
Remove unused files, variables and functions.
Change-Id: I34b21713b980beba0e1123a9738c870334c10354
* Resolves: # 
* Target version: …
> this._marker.closePopup not a function

- wsd/COOLWSD.cpp
Signed-off-by: Josh Richards <josh.t.richards@gmail.com>
Change-Id: Ib2c5bc13ded052aa3e76b0dcb280b32d7febedb5
> fix(COOLWSD): Fix a typo `remove_font_config`->`remote`

- Makefile.am
- configure.ac
- cypress_test/Makefile.am
- test/run_unit.sh.in
- wsd/README.md
which don't use coolmount and coolforkit, but instead use linux mount spaces with coolforkitns instead.
That doesn't need sudo, so drop automatically calling that in make to setcaps on coolmount + coolforkit for an easier developer experience.
Change-Id: I6f8ddaf1053d084ec8c1f22adf830a677e80cadc
* Resolves: # 
> default make run to use mount namespaces

- README.md
In the top-level README.md, fix links to
other READMEs:
* adjust the reference to the wsd one to include the `.md` suffix as the file was renamed in commit 79b667a3317335f04f4829688b7bd31c6b555d98
* Use the path to the actual file for the URL/target, not just to the parent directory, as just browsing to the containing directory when clicking on the link text showing a specific file name is rather unexpected
I actually tried the build steps above, but they failed. I tried to use both, COOL master and LibreOffice master, which fails with
```
make[2]: Entering directory '/home/michi/development/git/collabora-online'
CXX      kit/Kit.o
kit/Kit.cpp: In member function ‘void Document::startThreads()’:
kit/Kit.cpp:1342:17: error: ‘using …
```
> README: Fix links to other READMEs

- browser/src/layer/tile/CanvasTileLayer.js
As event listeners are called in the order they are registered, and both the resize listener I have moved and the one registered directly above its new location call this._update, this._update is called *before* the second event listener (whichever it is) gets a chance to execute. In the old case, this causes us to request tiles for a different view level, which at the start of the program requests tiles for a default position and zoom level. In Android this triggers a core bug that sends us blank tiles. These tiles are then later treated as valid for the section and lead to a blank render.
Got all that? Good, because that confusion you feel is exactly why this fix isn't a particularly good one! This "fix" is hacky, hard to understand, and does it all through something I can reasonably …
> fix: Reorder resize event listeners

- ios/Mobile.xcodeproj/xcshareddata/xcschemes/Mobile.xcscheme
- ios/Mobile/CODocument.mm
- ios/Mobile/DocumentViewController.mm
- wsd/DocumentBroker.cpp
The iOS app (and presumably the Android app) do not have jails. Instead, they read and write files directly from the user's local file system.
Also, running the iOS in trace mode is nearly unusable so move the key "To JS" and "To Online" iOS messages to LOG_DBG and run the app with "debug" instead of "trace" by default.
> Fix failure to load documents in iOS app

- browser/css/jsdialogs.css
With *45bd9c6 merged an improved was introduced but it still didn't
fix the alignment for all cases. Example if an integrator uses a
different font stack or the user doesn't have the 1st and the 2nd
default font it would fall back to something else. These differences
in font would change how the dropdown is aligned due to line-height.
On top of that, we were not accounting for the transparent border when
aligning. Set margin-top to 4px so to offset the existent transparent
border: 4px.
*45bd9c6:
- Vertical align dropdown arrows
- 45bd9c6009baf33eb7a4225c969c474edddaaa6c
Change-Id: Ie695fa3a4a3a7edf3ec2f15ba2565bb2079d16fa
> Fix dropdow arrows changing depending on users font stack

- .git-hooks/pre-commit
git-diff-index isn't always provided separately to the main git binary, so we can't necessarily use that as the command. We should always be able to use `git diff-index`, as the git binary will find files named `git-foo` when you run command `git foo`, so this will work whether the binary is separate or not
Change-Id: Id705855eedfd7e12c0706a9c7638e0bfb911b3fd
* Resolves: # 
> fix(hooks): Replace git diff-index call

- wsd/DocumentBroker.cpp
recently we introduced multiple changes to the paths used by COOL server, it has to be adjusted so we will find the video file
request before:
`/jails/16613-ae50568c/HCUlXOt8uWVwjWey/tmp/5aempc.mp4`
request after:
`/jails/16613-ae50568c/tmp/cool-HCUlXOt8uWVwjWey/5aempc.mp4`
> embedded videos: fix path to the tmp directory

- browser/css/jsdialogs.css
With *45bd9c6 merged an improved was introduced but it still didn't
fix the alignment for all cases. Example if an integrator uses a
different font stack or the user doesn't have the 1st and the 2nd
default font it would fall back to something else. These differences
in font would change how the dropdown is aligned due to line-height.
On top of that, we were not accounting for the transparent border when
aligning. Set margin-top to 4px so to offset the existent transparent
border: 4px.
*45bd9c6:
- Vertical align dropdown arrows
- 45bd9c6009baf33eb7a4225c969c474edddaaa6c
Change-Id: Ie695fa3a4a3a7edf3ec2f15ba2565bb2079d16fa
> [Backport] Fix dropdow arrows changing depending on users font stack

- browser/css/cool.css
- browser/css/leaflet.css
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
- Canvas margin would be ignored when showruler is triggered
- Because of this the bg ruler couldn't be transparent (otherwise
the canvas scrollbar would be visible overlapping it)
With this commit: Whenever ruler is visible -> re set the canvas
container y position
Change-Id: Id320a025675b92eb3b32734308a91dd6dd34dc43
> Fix canvas margin when ruler is toggled on

- browser/src/control/Toolbar.js
we send "vnd.sun.star.script" message without uno prefix via uno command
Change-Id: If0e103bd74ac7f34a57559b2eebc1001352b0057
> uno: fix CallPythonScript calling js error

- browser/src/control/jsdialog/Widget.IconView.ts
- Allow style selection using arrow keys and tab
- Communicate selection state using aria-pressed attribute
- Ensures better accessibility for users relying on keyboard navigation.
Change-Id: Ib33d2a3a04e0dacbd0194012e7697b1a3bc87de3
* Resolves: # 
> accessibility: Improve keyboard accessibility for style selection

- browser/src/control/Control.FormulaBarJSDialog.js
To test:
type into "address" input next to the the formula bar
view should jump to the target cell
> calc: jump to cell on address input

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
The zoomreset button was occupying 100% of the vertical space but was
being render in one line instead of a big icon. Better to render it as
a big icon to aid in grouping.
Note on future implementations: Ideally we would actually have in one
line and we would replace the zoom out and zoom in btn with one
menu (something like `ZoomMenu`) that would allow the user to change
the zoom level (similar as already happens in the status bar). The
menu definition would be moved to menuDefinitions.
Change-Id: Ia136aa95e410f192984629feeb8eb05922372226
> [Backport] Notebookbar: Promote Reset zoom to bigmenubartoolitem

- browser/css/cool.css
- browser/css/leaflet.css
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
This reverts commit 2e00fea4b6aba889834b3ee037565930d42f32bd.
So to fix the text cursor being in wrong place:
1. User A switches ruler on
2. User B Switches ruler off
3. Users click in line 1 but the blinking cursor is rendered in the
line 2
It seems we cannot change the top position of
.leaflet-canvas-container without introducing a regression affecting
cursors. Probably browser/src/layer/marker/Cursor.ts need to be
updated also and maybe other markers also such as form controls.
Change-Id: Ice70463934b0065b5eda4429c4a51995aeb9a4df
> [24.04] Revert "Fix canvas margin when ruler is toggled on"

- browser/css/cool.css
- browser/css/leaflet.css
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
This reverts commit 5f6e845dbed8a00987815f6146926745bbcff840.
So to fix the text cursor being in wrong place:
1. User A switches ruler on
2. User B Switches ruler off
3. Users click in line 1 but the blinking cursor is rendered in the
line 2
It seems we cannot change the top position of
.leaflet-canvas-container without introducing a regression affecting
cursors. Probably browser/src/layer/marker/Cursor.ts need to be
updated also and maybe other markers also such as form controls
> Revert "Fix canvas margin when ruler is toggled on"

- test/.gitignore
- test/UnitPerf.cpp
- tools/Replay.hpp
Change-ID:Iee66f82e1026eae517f4452decf074fc0959bce0
* Resolves: 
The CPU usage is calculated by the difference between the start up stats
compared to when the unit test has completed. Peak memory usage is measured
by comparing the memory of the process initially compared to, post loading a
document. Both metrics are recorded into seperate CSV files.
> feat: recording CPU usage and peak memory usage

- browser/src/control/Control.StatusBar.js
So, don't show those items by default. For the other apps we already
specifically show them within the switch case in onDocLayerInit()
Change-Id: If25b09a8a37bcd5270f421f1d07d6e381be1d3d2
> Status bar: Presentation there is no insertmode nor selection status

- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/impress/scrolling_spec.js
This is revert of commit 468cf22b4bf95a7a24282d828d46d05ce5c1ae3d calc: jump to cell on address input
When uno command is sent user interacted with the app so we should reset following state to - follow my own cursor.
This helps solving the issue with "address bar", "search" usage in calc. Also removed old hack which caused to jump back to cursor after address bar was used in calc.
> following: reset on user interaction by uno command

- browser/src/control/Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/impress/scrolling_spec.js
This is revert of commit https://github.com/CollaboraOnline/online/commit/468cf22b4bf95a7a24282d828d46d05ce5c1ae3d
calc: jump to cell on address input
and partial revert of commit https://github.com/CollaboraOnline/online/commit/bab8c94f0a87c7e637c2d187d932f3a9ac4898f4
calc: fix view jump after search
When uno command is sent user interacted with the app so we should
reset following state to - follow my own cursor.
This helps solving the issue with "address bar", "search" usage in
calc. Also removed old hack which caused to jump back to cursor
after address bar was used in calc.
> fix view jumping in calc (backport 24.04)

- browser/css/spreadsheet.css
- Don't rely on margin to align it
- We are using flex box, add missing align property
- Fix height of containers: Use even numbers otherwise we end up with
- non equal margins: (39-32)/2 = 3.5. Use 38 instead.
Change-Id: I467acc1ec81fdccd48d76a52bb7bbc39d28e1ba6
> [Backport] Calc: sheet tabs: center tabs

- browser/css/cool.css
We already have high brightness on light mode and low brightness on
dark mode for comment background -> no need to try to increase it
further on hover since there is no high/low values to claim.
It fixes weird hover effect on the whole card.
Also related with
https://github.com/CollaboraOnline/online/issues/9631
Change-Id: I102bf161f90e6059bd6d981abb00d2abc854193d
> Annotations (comment): do not change background on hover

- browser/src/control/Control.UserList.ts
- browser/src/map/Map.js
- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
The UI component should only trigger map._setFollowing with correct parameters. Don't do own view jump management. This will help to finally centralize the following feature.
This patch fixes the issue with jumping to own cursor on any key press, example:
1. open writer with many pages
2. scroll to other page so you don't see the cursor
3. pres CTRL on the keyboard Result: jump back to the cursor
Expected: nothing happens
Keypress should activate following own cursor, but wait with the jump for a signal from the core
> following: simplify followUser

- test/testlog.hpp
Add (dummy) uses of the `NAME` and `X` params to the non-debug-build version of the `TST_LOG_NAME` macro.
This fixes build failures like the following ones seen in a GCC 13 build without the `--enable-debug` configure option:
WopiProofTests.cpp: In member function ‘void WopiProofTests::testCapiBlob()’:
WopiProofTests.cpp:63:20: error: unused variable ‘testname’ [-Werror=unused-variable]
63 |     constexpr auto testname = __func__;
|                    ^~~~~~~~
KitQueueTests.cpp: In member function ‘void KitQueueTests::testKitQueuePriority()’:
KitQueueTests.cpp:77:20: error: unused variable ‘testname’ [-Werror=unused-variable]
77 |     constexpr auto testname = __func__;
|                    ^~~~~~~~
KitQueueTests.cpp: In member function ‘void …
> test: Fix '-Werror=unused-variable' for non-debug build

- browser/src/control/Control.StatusBar.js
So, don't show those items by default. For the other apps we already
specifically show them within the switch case in onDocLayerInit()
Change-Id: If25b09a8a37bcd5270f421f1d07d6e381be1d3d2
----
Backport of https://github.com/CollaboraOnline/online/pull/9615
> [Backport] Status bar: Presentation there is no insertmode nor selection status

- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialogBuilder.js
PushButtonControl: Fix alignment (regression from locking overlay)
With the "new" wrapper introduced in
e02e1df76d8379e4da7e7c87f10c594bc558d6d2 all the buttons are misaligned.
- Ensure that the wrapper is set with its child centered
Change-Id: I73b0c7952daf70851a59e4b0e290ba3d32feed23
-----
Offset outline in input fields placed inside of a dialog
Before this commit, when the field was getting the focus in some
dialogs (example rename file) the outline was being cropped
Change-Id: I9edb516143c7f6aff47681e01fd8822a5b9e6743
----
Backport of #https://github.com/CollaboraOnline/online/pull/9599
> [Backport] Offset outline in input fields placed inside of a dialog

- .github/workflows/codeql-analysis.yml
Those are invoked in other checks (on Jenkins) and recently one unit
test started to fail only here, so disable that till the problem is
understood there.
Change-Id: I57704c72ed239aadc460de1d2fd67b5cf0bc3597
> github, codeql: no need to run tests

- browser/src/layer/tile/CanvasTileLayer.js
We want to follow our own cursor if we see it on the screen. We used calc's cell cursor always, but in Writer we need text cursor.
> following: fix status update in writer (backport 24.04)

- common/JailUtil.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/Kit.hpp
otherwise post-install they can't be updated by coolforkit if they fall out of sync.
f.e.
service coolwsd stop
rm /opt/cool/systemplate/etc/hosts
service coolwsd start
```
[ coolforkit ] DBG  File contents mismatch: [/opt/cool/systemplate//etc/hosts] missing, 0 bytes, modified at 0 =/= [/etc/hosts]: exists, 423 bytes, modified at 1721313302| common/FileUtil.hpp:301
[ coolforkit ] INF  No write access to path [/opt/cool/systemplate]: Permission denied| common/FileUtil.cpp:305
[ coolforkit ] WRN  The systemplate directory [/opt/cool/systemplate] is read-only, and at least [/opt/cool/systemplate//etc/hosts] is out-of-date. Will have to copy sysTemplate to jails. To restore optimal performance, make sure the files in [/opt/cool/systemplate/etc] are up-to-date.| common/JailUtil.cpp:557
[ …
```
> systemplate and its immediate subdirs should be owned by 'cool'

- Makefile.am
- common/Authorization.cpp
- common/CharacterConverter.hpp
- common/Session.cpp
- kit/Kit.cpp
- test/UnitWOPIRenameFile.cpp
- test/UtilTests.cpp
- test/WhiteBoxTests.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/QuarantineUtil.cpp
- wsd/TraceFile.hpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
- wsd: skipped quarantines is not a warning
- killpoco: Poco::URI::decode
- wsd: test: move hex tests to UtilTests
- wsd: test: move isValidUtf8 test to UtilTests
- wsd: remove redundant initialization
- wsd: test: better rename test
- wsd: new CharacterConverter utility
- wsd: use CharacterConverter
> Renaming and Other Improvements

- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
Draw a white rectangle behind a slide or shape with a not
solid color will not look correct if the slide has no background.
Set canvas to null when presentation is over also for the present in a
window case or we can't play presentation a second time.
Change-Id: Ice9b66b1f262eca8758366ba4badbd44f0244248
> SlideShowPresenter: some fixes

- browser/src/control/Control.Header.ts
Previously, when a row or column header context menu is openend, you could access the spreadsheet toolbar (switch sheets, scroll right etc..) and the context menu would stay open.
This was also an issue with the cell context menu aswell but skyler fixed it by changing the z-index of the its overlay. Howevever, the row and column header context menu's were left unchanged, so now the overlay for the context menu is above the spreadsheet toolbar.
Change-Id: I8dfe2304d86c15d1b343890797b9b2600ed61e31
* Resolves: # 
> fix: Cell header context menu

- browser/html/cool.html.m4
- browser/js/global.js
In I3155e799530d4c307569e88612a13570d0913e03, the mobile app was broken in 2 ways. This change fixes both of them. Here they are:
- First, certain elements were excluded on mobile. We presumably meant to check whether they were present before reading their value, but instead looked at whether they had a value ... this caused an error where we attempted to get a property on "undefined", crashing out of our initialization
- Second, we hardcoded the help information by catting `html/cool-help.html` into an input's value attribute in m4. Unfortunately, we neglected to add any form of escaping to speech marks, which caused it to flow out of its attribute... polluting the rest of the page with broken help information. I've used sed to replace speech marks with escaped HTML entities
Change-Id: …
> fix(android): Allow document loading

- browser/html/cool.html.m4
- browser/src/slideshow/transition/CombTransition.ts
- browser/src/slideshow/transition/DiagonalTransition.ts
- browser/src/slideshow/transition/PushWipeTransition.ts
By looking at the top of the document "`<!DOCTYPE html>`" it seems we
don't need trailing slash for self-closing tags but maybe the parser
needs (?). This seems to be super safe and it would be nice to see if
it fixes the "fails to build a proper html tag, unclosed link tag" problem.
- For consistency (in other lines we use it)
- For XHTML-compatibility
Change-Id: I00bf34104a5b56d094196cb2b912e1dc308b6253
> Add missing trailing slash

- browser/css/cool.css
We already have high brightness on light mode and low brightness on
dark mode for comment background -> no need to try to increase it
further on hover since there is no high/low values to claim.
It fixes weird hover effect on the whole card.
Also related with
https://github.com/CollaboraOnline/online/issues/9631
Change-Id: I102bf161f90e6059bd6d981abb00d2abc854193d
----
This is a backport of https://github.com/CollaboraOnline/online/pull/9635
> [Backport] Annotations (comment): do not change background on hover

- docker/from-packages/Dockerfile
Ports #9623/#9624 to `distro/collabora/24.04` branch. 
* Resolves: (no open Github issues)
* Target version: 24.04
* ChangeId: I39cc4329fcb640f853d691663fe3ef92619eafbe
This fix was necessary to ensure curl would follow redirects following the change of domain from collaboraoffice.com to collaboraonline.com. This PR cherry-picks the same commit and applies it to the `distro/collabora/24.04` branch.
> docker: update URLs used (24.04)

- browser/src/control/Control.UserList.ts
- browser/src/map/Map.js
- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
cypress: check new page view jump in writer
---------------------------------------------------------------
following: simplify followUser
The UI component should only trigger map._setFollowing
with correct parameters. Don't do own view jump management.
This will help to finally centralize the following feature.
This patch fixes the issue with jumping to own cursor on any
key press, example:
1. open writer with many pages
2. scroll to other page so you don't see the cursor
3. pres CTRL on the keyboard
Result: jump back to the cursor
Expected: nothing happens
Keypress should activate following own cursor, but wait with
the jump for a signal from the core
> Fix view jumping on keypress in writer (backport 24.04)

- browser/src/control/Control.DownloadProgress.js
in mobile when user copied anything using context menu, user used to get unwanted message due to incorrectly triggered keydown event. message said "use on screen keyboard for copy/paste" which is not even possible in case of copying
Change-Id: I586021db1d1551d53993ba0791071ede8e742681
> clipboard: mobile: fixed js error

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/js/global.js
- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
- browser/src/docdispatcher.ts
- common/Session.cpp
- common/Session.hpp
- kit/Kit.cpp
- kit/Kit.hpp
- wsd/ClientSession.cpp
This change makes our calls to .uno:InvertBackground specify the desired
theme (requires core change I05486860c5f562c3cfa59b4a7fc492d48913a181),
saves the background theme for different color themes, applying it when
they are loaded, and sends the previous theme on document load (requires
core change I8c22c03d3b4589736d48509004f7789dd5166389)
We need to send the desired background theme manually, as otherwise Core
looks at a global document background theme, meaning that switching your
background theme actually switches to whatever wasn't the last background
theme set by anyone
It's also nice to preserve this inverted document background, both when
switching in/out of dark mode and when reloading the document entirely.
Storing the desired preference on a per-theme basis avoids us having a …
> fix(invert): Specify desired theme

- .github/workflows/docker.yml
- docker/from-source-gh-action/Dockerfile
- docker/from-source-gh-action/README.md
- docker/from-source-gh-action/build.sh
- docker/from-source-gh-action/start-collabora-online.sh
Change-Id: I56d28f4b2428b248c52d550825d1ac337a536bdf
Provides a separate docker build method to build a container isolated from the host system. The goal is to have a nightly docker image on the github container registry that can be used for easier testing and running automated tests in integrators.
For now only the built from the precompiled core assets is covered.
Note I've tested building in the github action in my local fork https://github.com/juliushaertl/online/actions/runs/10083478724 but not in here yet.
> ci: github action for nightly docker

- browser/src/control/Control.ServerAuditDialog.ts
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/ServerAuditUtil.cpp
- Implemented a new error code type `hardwarewarning` to indicate insufficient hardware resources.
- Updated server audit widget to display the new hardware warning message.
- Included link to hardware requirements documentation for user reference.
Change-Id: I3151b57acc1275564d8de1cdc18922685e8edebe
* Resolves: #9491
> Add hardware resource warning to server audit widget

- browser/src/control/Control.Menubar.js
- For 'marked read only' file somehow menubar item does not get initialized.
This patch:
- Introduced `isEventBound` function to check if an event with a specific type and namespace is already bound to an element.
- Simplified the `isEventBound` function to use the `Array.prototype.some` method for namespace checking.
- Created `bindEventIfNotBound` function to bind events only if they are not already bound.
- Updated event binding for `#main-menu` to use `bindEventIfNotBound`, preventing duplicate bindings for 'select.smapi', 'beforeshow.smapi', 'click.smapi', and 'keydown' events.
Change-Id: I26c95a7e366270b0020ce0fb27055f5acf9c1539
* Resolves: #9632 
> Fix event binding issue by initializing event handlers once

- browser/admin/src/AdminSocketSettings.js
- common/Util.cpp
It can happen that performance depends on what poco version is used, in
this case exposing this information helps debugging.
Of course it won't help with old versions, but at least start showing
this info, to help in the future.
Change-Id: I32439d70022b918094a7110bfce3aff29ce8b35d
> cool#9710 admin console: expose poco version

- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- wsd/ProxyProtocol.hpp
Fixes compiler warnings with `-Woverloaded-virtual`.
> wsd: correctly override dumpState

- wsd/RequestVettingStation.cpp
ambiguous overload for ‘operator==’ (operand types are ‘Poco::JSON::Object::Ptr’ {aka ‘Poco::SharedPtr<Poco::JSON::Object>’} and ‘std::nullptr_t’)
assert(_checkFileInfo && _checkFileInfo->wopiInfo() == nullptr &&
~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
Change-Id: I9b11cdc3304506832aae9326fed4d7d3618c77dc
> fix build: ambiguous overload for ‘operator==’

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.TreeView.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
On autofilter disable entries that have already been filtered out by
another autofilter. The same as it works on desktop.
Change-Id: I72a9999d9a6ba2f257bb88f8abeee99b01e55e4a
> calc autofilter disable already filtered entries

- .gitignore
- common/Unit.hpp
- test/UnitPerf.cpp
- wsd/DocumentBroker.cpp
Fix build in UnitPerf
./common/Unit.hpp:488:18: error: 'UnitWSD::onDocumentLoaded' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
caused by commit 6e790c63d0997094979b2a237f428ef7706e62ef
feat: Changes to UnitPerf measuring
> Fix build & ignore test csv

- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
symptoms appear as:
```
/usr/bin/coolwsd
SigUtil::dumpBacktrace()
common/SigUtil.cpp:450
/lib/x86_64-linux-gnu/libpthread.so.0
__restore_rt
??:?
/lib/x86_64-linux-gnu/libc.so.6
__GI_raise
/build/glibc-aGgxh2/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51 (discriminator 3)
/lib/x86_64-linux-gnu/libc.so.6
__GI_abort
/build/glibc-aGgxh2/glibc-2.27/stdlib/abort.c:81
/lib/x86_64-linux-gnu/libpthread.so.0
__restore_rt
??:?
/lib/x86_64-linux-gnu/libpthread.so.0
__GI___pthread_mutex_lock
/build/glibc-aGgxh2/glibc-2.27/nptl/../nptl/pthread_mutex_lock.c:67
/usr/bin/coolwsd
ServerAuditUtil::set(std::string, std::string)
/opt/rh/devtoolset-12/root/usr/include/c++/12/bits/std_mutex.h:103
/usr/bin/coolwsd
SocketDisposition::execute()
/opt/rh/devtoolset-12/root/usr/include/c++/12/bits/std_functi …
```
> RequestVettingStation can be deleted before callback is executed

- browser/css/jsdialogs.css
- browser/css/notebookbar.css
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.IconView.ts
Change-Id: I44e3e40b3be1dcfd0d099939e6f6a9a4e574fdbd
* Resolves: # 
- Previously, we only showed icons in cases where we wanted to display the IconView from the core. Now, if the IconView contains text, the text will be displayed below the icon from the IconView.
> Widget: enable iconview with text

- browser/src/control/Control.UserList.ts
This fixes issue #9682 :
- open session with multiple users
- user A is following the other user
- user A stops following by click on a following chip Result: chip is not rendered correctly
> Update full chip when stoped following #9682

- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
Make sure the video is paused when we change the slide, so that we don't keep playing the video in the background.
Change-Id: I39b9118f7606a997f4cdf2eb4e3f1b736812074f
* Resolves: # 
> slideshow: pause all videos when changing the slide

- browser/src/layer/tile/CanvasTileLayer.js
reproducible with hello-world.ods and insert a comment, some text and ok, close document
when document is closing...
_map is null at
this._map._docLayer.isCalcRTL()
```
(anonymous) @ bundle.js:16912
ScrollSection.drawVerticalScrollBar @ bundle.js:16463
ScrollSection.onDraw @ bundle.js:16511
CanvasSectionContainer.drawSections @ bundle.js:12702
CanvasSectionContainer.requestReDraw @ bundle.js:12339
CommentSection.onResize @ bundle.js:13746
CanvasSectionContainer.reNewAllSections @ bundle.js:12616
CanvasSectionContainer.paintOnResumeOrEnable @ bundle.js:12254
CanvasSectionContainer.resumeDrawing @ bundle.js:12253
CommentSection.clearList @ bundle.js:14159
(anonymous) @ bundle.js:11008
fire @ bundle.js:9893
close @ bundle.js:9940
```
stepping into this._map._docLayer.isCalcRTL() suggests …
> Uncaught TypeError: Cannot read properties of null (reading '_docLayer')

- browser/src/control/Control.Header.ts
Previously, we bound a context menu on mouse-over even when we were in the mobile view and therefore should be using the mobile wizard instead... this can cause trouble when using mice on mobile, in the mobile view on browsers, or possibly if selecting the header before activating the menu...
...by inactivating the unnecessary _bindContextMenu function in mobile view, we can prevent this happening entirely
Fixes: #9744
Change-Id: I74f5802d8c058fa1b30cf06cc44c06d5df321e54
* Resolves: # 
> fix(header): Prevent context menu on mobile

- browser/src/layer/tile/CanvasTileLayer.js
Sometimes a TypeError JS Exception was raised due to accessing
this._graphicSelection.extraInfo while _graphicSelection is null.
Change-Id: I7520e125dd0f1a5815f4324ada8a74950fdbac7d
> check for null _graphicSelection on _onShapeSelectionContent

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
Previously, we didn't have a way to restore the document background color on load for Calc, leading to a document that was inverted according to our LocalStorage and Core, but which didn't have the background to show it. This led to text rendering issues, as well as needing multiple presses to switch into invert background mode properly...
...in this change, I've simplified the calc background code to rely on our existing css data-bg-theme property, and made it consistently set the background color to --color-background-document ... it's possible this causes problems with changing themes alongside LOK_CALLBACK_DOCUMENT_BACKGROUND_COLOR, but I'm confident this is an improvement over the previous behavior as that should also have been true of it...
...this brings Calc invert backgrounds to …
> fix(calc): Restore inverted document on load

- browser/src/control/jsdialog/Widget.MultilineEdit.js
In 3bb07cdd528f37ec45af488ec6e58608cd041915, we changed the 'change' event for multiline text inputs to use 'keyup' instead. Unfortunately, that change forgets about ways in which the input field can change text without there being a 'keyup' event.
Of particular relevance to me is on iOS, where pasting into one a field won't trigger a 'keyup' event, leading to, e.g., QR codes to fail generation with pasted URLs
This patch is a bit unfortunate in that it makes things which *do* trigger 'keyup' events (which is most text edits) send double events for these text fields... I think there's some duplicate-event filtering that could be done, but I think it's better to get this in before worrying about it.
Change-Id: I188c13cfe7f5dbe2600551f4023d1c9d98bbbba2
* Resolves: # 
* Target version: …
> fix(jsdialog): Trigger change without keyup

- browser/src/control/Control.ContextMenu.js
It's possible sometimes for us to filter out everything in a context menu with _createContextMenuStructure. If we do that on mobile, we will end up with an empty mobile wizard, so it's much better to skip the context menu altogether...
Fixes: #9740
Change-Id: Iae65aa95a38c4e46f4bea544bd0b41195000cba1
* Resolves: # 
> fix(contextMenu): Avoid displaying empty menus

- Makefile.am
like how clean-local already ignores failure to entirely remove the old systemplate.
This can happen if a non-namespace mount was left behind by a non-namespace ver of online. Then a namespace version lacks the privileges to remove the classic mounts.
Change-Id: I3aade8540b1cace405f13fa3b41a8e91b50ab06c
* Resolves: # 
> continue with coolwsd-systemplate-setup if already mounted

- browser/src/layer/tile/CanvasTileLayer.js
Previously, continuously panning for too long would cause a range error
like so...
TilesSection.ts:153 Uncaught RangeError: Maximum call stack size exceeded
TilesSection.drawTileInPane @ TilesSection.ts:153
-------------- 8< snip --------------
fire @ Events.js:152
_updateScrollOffset @ CanvasTileLayer.js:970
-------------- 8< snip --------------
fire @ Events.js:152
_updateScrollOffset @ CanvasTileLayer.js:970
-------------- 8< snip --------------
fire @ Events.js:152
_updateScrollOffset @ CanvasTileLayer.js:970
...this appears to be due to us continually checking if we're panning,
and if so continuing to recurse. Eventually, we run out of call stack
and error.
Erroring causes:
- A failure to draw tiles and UI properly, including but not limited to
completely blanking out headers
- On …
> fix(pan): avoid range error in long pan

- browser/css/jsdialogs.css
- browser/css/notebookbar.css
By default use well aligned 3 column grid.
In styles preview use old flex layout so
we don't change the behavior we had.
> jsdialog: css: use CSS grid in icon view

- browser/src/control/Control.Header.ts
- Disabled non-read-only operations in context menu for row/column headers when in read-only mode.
- Ensured that the context menu does not display options for actions that are not permitted.
Change-Id: I0a7cd1f0722529acb52d44f93ca6fc885b571efd
* Resolves: #9748 
> Fix: Remove non-read-only context menu options in read-only mode

- browser/src/layer/tile/CanvasTileLayer.js
This is a backport of #9721
reproducible with hello-world.ods and insert a comment, some text and ok, close document
when document is closing...
_map is null at
this._map._docLayer.isCalcRTL()
(anonymous) @ bundle.js:16912
ScrollSection.drawVerticalScrollBar @ bundle.js:16463 ScrollSection.onDraw @ bundle.js:16511
CanvasSectionContainer.drawSections @ bundle.js:12702 CanvasSectionContainer.requestReDraw @ bundle.js:12339 CommentSection.onResize @ bundle.js:13746
CanvasSectionContainer.reNewAllSections @ bundle.js:12616 CanvasSectionContainer.paintOnResumeOrEnable @ bundle.js:12254 CanvasSectionContainer.resumeDrawing @ bundle.js:12253 CommentSection.clearList @ bundle.js:14159
(anonymous) @ bundle.js:11008
fire @ bundle.js:9893
close @ bundle.js:9940
stepping into …
> backport: Uncaught TypeError: Cannot read properties of null (reading '_docLayer')

- browser/src/control/Control.Header.ts
This is a backport of #9745
Previously, we bound a context menu on mouse-over even when we were in the mobile view and therefore should be using the mobile wizard instead... this can cause trouble when using mice on mobile, in the mobile view on browsers, or possibly if selecting the header before activating the menu...
...by inactivating the unnecessary _bindContextMenu function in mobile view, we can prevent this happening entirely
Fixes: #9744
Change-Id: I74f5802d8c058fa1b30cf06cc44c06d5df321e54
* Resolves: # 
> backport: fix(header): Prevent context menu on mobile

- browser/src/control/jsdialog/Widget.MultilineEdit.js
This is a backport of #9693
In 3bb07cdd528f37ec45af488ec6e58608cd041915, we changed the 'change' event for multiline text inputs to use 'keyup' instead. Unfortunately, that change forgets about ways in which the input field can change text without there being a 'keyup' event.
Of particular relevance to me is on iOS, where pasting into one a field won't trigger a 'keyup' event, leading to, e.g., QR codes to fail generation with pasted URLs
This patch is a bit unfortunate in that it makes things which *do* trigger 'keyup' events (which is most text edits) send double events for these text fields... I think there's some duplicate-event filtering that could be done, but I think it's better to get this in before worrying about it.
Change-Id: I188c13cfe7f5dbe2600551f4023d1c9d98bbbba2
* …
> backport: fix(jsdialog): Trigger change without keyup

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/js/global.js
- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
- browser/src/docdispatcher.ts
- common/Session.cpp
- common/Session.hpp
- kit/Kit.cpp
- kit/Kit.hpp
- wsd/ClientSession.cpp
This contains various invert background fixes, backporting #9652, #9667 and #9697
These changes both allow invert background to be used on phones, as well as fixing it for devices (e.g. tablets) that already had it
Change-Id: I221058206b0fbbaa7b2a73e06f12d5e95e3b700a* Resolves: # 
> backport: invert background fixes

- browser/src/control/Control.ContextMenu.js
This is a backport of #9741
It's possible sometimes for us to filter out everything in a context menu with _createContextMenuStructure. If we do that on mobile, we will end up with an empty mobile wizard, so it's much better to skip the context menu altogether...
Fixes: #9740
Change-Id: Iae65aa95a38c4e46f4bea544bd0b41195000cba1
* Resolves: # 
> backport: fix(contextMenu): Avoid displaying empty menus

- browser/css/jsdialogs.css
So no matter the height, they are well aligned:
- fixes compact mode separators
Change-Id: Iea6501d827093dfa24af0595b7a61f93e1621c08
> All vertical separators should be automatically centered

- browser/Makefile.am
- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/SlideCache.ts
Introduce container for cached content. Reset data when we receive new presentation info. This should be improved in the future to detect and reset only modified slides. Also we want to put into cach all other layers.
> SlideShow: reset cached slides to show updated content

- browser/src/control/Control.UserList.ts
There are a few cases where you can be shown a popup for yourself
leaving a document. These are generally where either the server has
disconnected (e.g. it crashed) or the document has moved (e.g. you
rename it in the NextCloud title bar)
In this case, it's rather weird to show the popup, and the current
message ("You has left") is gramatically incorrect because we do not
expect this to happen. It's better to not permit yourself to show in a
join/leave message at all...
Change-Id: I0da9fee162ab3d6cbfffccb461c5fc292c94f480
> fix(userlist): Don't show popup if you "leave"

- common/JailUtil.cpp
if, like with apparmor, user namespaces are possible, but mounts are not (not even the initial "none" mount to not propogate mounts to the host env) then we are in a namespace, but not seen in our env as any particular user.
that leads to worrying warnings about "incorrect user-name" like:
```
[ coolwsd ] DBG  Move into user namespace as uid 0| wsd/COOLWSD.cpp:1965
[ coolwsd ] ERR  enterMountingNS, root mount failed: Inappropriate ioctl for device| common/JailUtil.cpp:78
[ coolwsd ] ERR  creating usernamespace for mount user failed.| wsd/COOLWSD.cpp:1969
[ coolwsd ] INF  Cleaning up childroot directory [/opt/cool/child-roots/].| common/JailUtil.cpp:307
[ coolwsd ] TRC  Checking pid for jail 3192148 /opt/cool/child-roots/| common/JailUtil.cpp:335
[ coolwsd ] DBG  Removing …
```
> if creating a user ns worked, but mount doesn't then map orig uid

- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
During slideshow the video could still continue playing if the slide with a video was the last one.
Also stop rendering when all the videos are paused.
Additionally unmute the video, so we have the sound from the video during the slideshow.
Change-Id: I32f3f405b0c92e446f84ba4f4f3f60f9dd294eb1
* Resolves: # 
> play, pause the video during slideshow, transition, unmute sound

- CODEOWNERS
- browser/.beforeprettier
When we added prettier, we didn't want to format all the files in the repository then and there, so the compromise we came to was the .beforeprettier file
.beforeprettier is there to ignore files that were there "before prettier", i.e. legacy files that do not need to be formatted
Unfortunately, we didn't make this intent as clear as we could have, and the file has been changed several times since (see https://github.com/CollaboraOnline/online/commits/master/browser/.beforeprettier), including during migrations of files from JavaScript to Typescript and additions of new files, both of which should result in the file being formatted.
This change adds a comment to the top of the file, explaining that people shouldn't add new content to it. It also makes a CODEOWNERS file to ping myself and …
> chore: discourage .beforeprettier changes

- browser/src/canvas/sections/OtherViewCursorSection.ts
showcursor variable is set by the core side. Extra assignment is removed.
Change-Id: I010be4f9f540ba53c982d9b21315c020c7c4147d
* Resolves: # 
> Fix other views' cursor visibility.

- browser/src/control/Control.JSDialog.js
Resolved accessibility issue by changing the close button's tabindex from -1 to 0, enabling keyboard focus and interaction. Note: to access the close button using keyboard we need to add in cycle ( the tab cycle which will help to reach close button using keyboard )
Change-Id: I9ec0cef8a36de92daefa4bc0051a19e6ef3df1c2
* Resolves: # 
> Accessibility : Make JSDialog close button accessible via keyboard

- browser/html/debug.html
- browser/js/global.js
- browser/src/core/Socket.js
- cypress_test/data/multiuser/cypress-multiuser.html
In I636e07a93d2ed17d56b2a9fc11d66b7e4c3c19f3, Michael Meeks added a new
popup to show when we have an exception in an event. This is excellent,
and is catching errors. Unfortunately, the messages we get in our
Cypress tests when this fails are... not amazing.
They don't include the error, and instead the new popup just makes some
actions that we wanted to perform silently fail to happen. This causes
later assertion errors, but they are disconnected from the root cause -
the error. It's much neater to throw here if we're in cypress, failing
the test.
Change-Id: Ia729489ba2adc3be0e9286f942d128acafd29858* Resolves: # 
> test: Make cypress fail on exception

- browser/src/layer/tile/CalcTileLayer.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
Fixes #9783 :
Calc: cannot see the cell cursor after "insert sheet before"
Steps to Reproduce:
1. Go to Calc
2. Scroll to around 100 row
3. Right-click on a sheet tab, Insert sheet before
Expected Behavior:
We should see new sheet with visible cursor at A1
Actual Behavior:
We don't see A1 but in my case row 25. Might depend on window size.
In case when new sheet has bigger size than a visible area - we were forcing view reset by bounds update which caused view jump. We were jumping outside of cursor visibility so user following was disabled and in the end user was not able to see own cursor.
Related to the following functionality change in:
commit df158a9
calc: don't jump to own cursor if not looking
> Calc: don't force view reset if not needed

- browser/src/layer/tile/CalcTileLayer.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
This reverts commit ec33245158dd168ff57e7eb8563bd61f02722b5e. We need to test it more as detected in the reivew of other change. When you scroll down in calc and resize celected row - it jumps.
> Revert "Calc: don't force view reset if not needed"

- wsd/DocumentBroker.cpp
this is similar to:
commit 01165fbe1f074e530c0a6cb057fbc9b3b177971f
AuthorDate: Tue Jul 4 15:33:15 2023 +0100
On a cache hit for a tile the result typically had a wireId of 0
this one can typically be reproduced by opening a presentation and can be seen when the slide preview tiles are requested
Change-Id: If5f7d0717a4068332aa96052a8a285171a13c03d
* Resolves: # 
> Invalid syntax for tileprocessed wireid 'NaN'

- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/transition/CombTransition.ts
- browser/src/slideshow/transition/FadeTransition.ts
- browser/src/slideshow/transition/PushWipeTransition.ts
pushWipe transition subtypes are routed to the wrong gl transition
horizontal and vertical comb are inverted
fade transition subtyped are routed to the wrong gl transition (index
start from 1 instead of 0)
Change-Id: I516fafc1dcb39120ecec96df8d6834a13840cb3e
> slideshow rework: bug: some transitions are wrong

- browser/src/slideshow/LayersCompositor.ts
Previously, we adjusted the resolution of the slides, so the size of the slide would be max 1920x1080. This restriction is removed now so the slide size can use the actual size of the screen. With this change the slides look much better on a high DPI screen (4k), but will also take longer to be transfered to the client as the size of the slides is bigger also.
Change-Id: I9b132ad5ac897f956768c5d5a1e77fa18cb34246
* Resolves: # 
> slideshow: remove resolution adjustment - use the screen size

- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd/wopi/StorageConnectionManager.cpp
- wsd/wopi/StorageConnectionManager.hpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
**Possibly for RED.**
Some Kill-Poco and refactored locking to prepare for async locking.
- wsd: updateStorageLockState -> lockDocumentInStorage
- wsd: use an enum for lock states
- wsd: use LockState enum in LockContext
- wsd: encapsulate supportsLocks in LockContext
- wsd: refactor AsyncUpload for reuse
- wsd: use STATE_ENUM
- killpoco: document locking without poco
- killpoco: remove unused http helpers
- wsd: move and update StorageConnectionManager::initialize()
- wsd: use StorageConnectionManager::getHttpSession()
> Async Locking Prerequisites

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/transition/FadeTransition.ts
Fade over color transition is based on the transition fade color
property not on the direction.
Change-Id: Idf5b0cef385f7e9f31159dd0f5669d08f4258cef
> slideshow rework: bugfix: fadeovercolor transition

- configure.ac
Previously it was quite cumbersome to specify a different architecture than armeabi-v7a, as you had to specify *both* a core in the armeabi section and one for whatever architecture you wanted to build (these could be the same core, the armeabi one didn't need to actually be armeabi...)
This was made more confusing by the requirement to specify cores in the right position - requiring you to put colons between cores even when you were only planning to build a single ABI, but only if that ABI wasn't armeabi-v7a...
For example, to build arm64-v8a you would have to do something like
--with-lo-builddir=$(realpath ../android-core):$(realpath ../android-core)::
This is now changed, so specifying a single core is equivalent to specifying it 4 times, i.e. these are both the same thing …
> build(android): Simplify configure abi selection

- browser/src/canvas/sections/CommentListSection.ts
problem:
some elements can not have comments, when these elements get selection, comment button in menus were disabled but shortcuts still worked, this ensures no element for comment insert is created in first place
Change-Id: Ib76366c23e9ad7f6fc29f98add65b0840d00ead9
> annotation: avoid creating comment insert box if annotations disabled

- browser/src/control/Control.TopToolbar.js
Fixes #9816
When we open classic/compact mode, then switch to notebookbar mode - the old component of top toolbar is not correctly removed. What leads to an error.
Steps to Reproduce:
1. Open any document, use compact mode
2. Switch to notebookbar mode
3. Change context, eg. select shape then select text
Don't use bind(this) so we successfully remove the same instance of handler we inserted, we already pass "this" as 3rd param. Notice we should also remove callback from app.events but it doesn't have that function yet
> Fix error on context change after mode switch

- browser/src/unocommands.js
Now the ChangeBezier uno command has a proper context menu item in draw
Fixes https://github.com/CollaboraOnline/online/issues/9813
Change-Id: I834c19a80e6d8c6a279ae298e78ba650bbea1fb1
* Resolves: #9813 
Turns out presentation and drawing have the same set of commands, but we distinguish on the doc type.
> draw: just get the UNO commands for presentation

- browser/html/cool-help.html
- browser/src/map/handler/Map.Keyboard.js
Change-Id: I369d73c85beff934968fbafadf2da8bd4dccf8be
Wire conventional alternative shortcut for Copy with Crtl + Insert.
Not sure where to find the user manual.
> Keyboard: Add Ctrl + Insert as Copy Shortcut

- net/HttpHelper.cpp
- net/HttpHelper.hpp
- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- test/UnitSession.cpp
- test/helpers.hpp
- wsd/Admin.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/wopi/WopiStorage.cpp
WSD's ClientRequestDispatcher shall keep the socket open on successful document and favicon download requests.
HttpHelper::sendFile(..) is refactored from HttpHelper::sendFileAndShutdown(..) w/o the socket closing (shutdown) and used in WSD's ClientRequestDispatcher accordingly.
WebSocketHandler: Added public isConnected() StreamSocket queries, allowing our unit tests to validate the connected state.
FileServer.cpp's FileServerRequestHandler::handleRequest(..) also keeps the socket alive (ENABLE_DEBUG and env 'COOL_SERVE_FROM_FS') with this patch.
Check whether this is desired, as not covered by a unit test!
+++
Analyze whether the following maintained HttpHelper::sendFileAndShutdown(..) use-cases shall be converted to keep-alive as well:
- WSD's ClientSession::handleKitToClientMessage() …
> cool#9621: Have WSD Keep Download-Socket open for file and favicon.ico requests (ClientRequestDispatcher); ..

- wsd/DocumentBroker.cpp
- wsd/Storage.hpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
- wsd: generalize ScopedInvokeAsyncUploadCallback for reuse
- wsd: encapsulate updating the lock state
- wsd: asynchronous locking stubs
- wsd: unify LockResult and LockUpdateResult
- wsd: return lock update failure through the result
- wsd: remove the LockContext lockFailureReason
- wsd: encapsulate the LockContext lockToken
- wsd: simplified updateLockState error handling
- wsd: check for asyncRequest success for uploading
> More Async Locking Prerequisites

- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/layer/tile/CanvasTileLayer.js
Previously in impress we would always start a drag no matter how little
a tap had moved. This commonly inhibited us from tapping into a text
field to edit it, particularly when we didn't have something else
selected first.
I wondered for a little while about detecting whether the tap brought up
the keyboard, but it seems that by the time we know that it's already
too late. This tap distance detection seems reliable while also being
very simple to implement, and a drag of less than 0.1 would be an
unrealistically small drag anyway.
---
Additionally, 
Previously when we got a `cursorvisible: false` message from COOLWSD, we
would set `app.file.textCursor.visible` to `false` and then attempt to
update the cursor.
Unfortunately, updating the cursor was disabled when …
> fix(android): don't start drag on unmoving tap

- test/HttpRequestTests.cpp
- wsd/DocumentBroker.hpp
- wsd/wopi/WopiStorage.cpp
Some older PR was not compatible.
There was old check of success introduced in
commit 76fded3ef0065a04753422ba8b2910802943efcb
wsd: check for asyncRequest success for uploading
but in the meantime we have new callback for connection
fail what requires change from us:
commit f6ce37b579c1753e61a71788a78bb25d5d60eb1d
hook Session::asyncRequest up to use net::asyncConnect
calls _onConnectFail on async connect fail instead of returning false on
sync connect fail
So let's not use scoped callback trigger but rather do it manually
on returns and in the fail callback. Successfull one is already
done this way. Notice: on success we were firing it two times:
on Running state and Complete. Running doesn't happen if we fail
on connection...
> Fix build in clang

- .gitignore
- Makefile.am
- coolwsd.spec.in
- coolwsd.xml.in
- debian/control
- debian/coolwsd-deprecated.install
- debian/coolwsd-deprecated.postinst
- debian/coolwsd.install
- debian/coolwsd.postinst.in
- docker/from-source-gh-action/Dockerfile
- docker/from-source/ArchLinux
- docker/from-source/Debian
- docker/from-source/Fedora
- docker/from-source/Ubuntu
- docker/from-source/openSUSE
- man/coolconfig.1
- man/coolconvert.1
- man/coolforkit-ns.1
- man/coolmount.1
- man/coolstress.1
- man/coolwsd-systemplate-setup.1
- man/coolwsd.1
- wsd/COOLWSD.cpp
Default namespaces to on, and move non-namespaces helpers to a deprecated subpackage
- centos
- 8.0 works with namespaces out of the box
- 7.9 (EOL*) not enabled by default, possible with echo 10000 > /proc/sys/user/max_user_namespaces
* RHEL7 is EOM
- debian
- 11 (bullseye) works with namespaces out of the box
- 10 (buster) EOL, not enabled by default, possible with sudo sysctl -w kernel.unprivileged_userns_clone=1
- 9 (stretch) EOL, not enabled by default, possible with sudo sysctl -w kernel.unprivileged_userns_clone=1
- ubuntu
- 16.04 works with namespaces out of the box
Change-Id: Iffabea0a871d23797c1482cb8d2ca7de3e98f34a
* Resolves: # 
> split out a deprecated subpackage of the helpers not needed with namespaces

- Makefile.am
With Ubuntu 24.04 apparmor rules default to denying user namespaces. https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2046844
podman though is allowed by default, so podman unshare can (currently) be used to create an initial namespace env to work within.
Change-Id: Ic2a9f5b9ff8bb403c88e48e05a52ec44d3501a82
* Resolves: # 
> test and workaround Ubuntu 24.04 apparmor defaults for make run

- browser/js/global.js
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
- browser/src/core/Socket.js
- browser/src/docstate.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
regression from commit e36d6ffb9b13ffd440744425da128a9446530f01 fix: fix UI preference inconsistencies
where we introduced second place where enableAccessibility is controlled. This caused that we were out of sync in few places so we used regular TextInput while having a11y enabled...
We got bunch of this._map._textInput.onAccessibilityFocusChanged is not a function
This was visible only after we added additional dialogs/errors on unhandled exceptions inside cypress recently.
> cypress: fix errors due to missing a11y handling

- scripts/unocommands.py
This is a followup to commit daf8ad7
The unocommands.js is a generated file, and the code is part of it.
Fixes https://github.com/CollaboraOnline/online/issues/9813
Change-Id: I00856c21b3f49437739240830c142efec41c9602
* Resolves: #9813
This was overlooked in the previous patch.
> draw: Fix the unocommands.py

- browser/src/map/handler/Map.Feedback.js
if feedback dialog was enabled we failed on mobile tests:
> Cannot read properties of undefined (reading 'remove')
> cypress: fix error when using feedback

- net/Socket.cpp
- net/Socket.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
* Resolves: #9621 POST fileserver request
Change-Id: I7db359aeb7773733f817a31e8777e076b8cd4408
cool#9621: Resolve POST fileserver request, commit 6e4d2b2350100367f780664a4c5af1f5d7702488
Commit 6e4d2b2350100367f780664a4c5af1f5d7702488 mitigated the issue of
wrongly handled POST requests in ClientRequestDispatcher::handleIncomingMessage()
by simply shutting down the socket (non keep-alive socket).
This patch resolves the issue by removing the complete HTTP request
including the optional HTTP POST body from the socket's buffer,
i.e. removing map._messageSize bytes.
It also includes a fix in StreamSocket::parseHeader()
of only adjusting map._messageSize w/ contentLength if the latter is valid.
Hence we also allow reusing the given socket connection
for POST HTTP …
> cool#9621: Resolve POST fileserver request

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
Fixes #9783
Calc: don't force view reset if not needed
Fixes #9783 :
Calc: cannot see the cell cursor after "insert sheet before"
Steps to Reproduce:
1. Go to Calc
2. Scroll to around 100 row
3. Right-click on a sheet tab, Insert sheet before
Expected Behavior:
We should see new sheet with visible cursor at A1
Actual Behavior:
We don't see A1 but in my case row 25. Might depend on window size.
In case when new sheet has bigger size than a visible area - we
were forcing view reset by bounds update which caused view jump.
We were jumping outside of cursor visibility so user following
was disabled and in the end user was not able to see own cursor.
Related to the following functionality change in:
commit df158a9
calc: don't jump to own cursor if not looking
> Fix Calc: cannot see the cell cursor after "insert sheet before"

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- browser/src/control/Parts.js
- browser/src/docstate.js
- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- cypress_test/integration_tests/multiuser/calc/cell_cursor_spec.js
calc: use hashes for parts
part number is not enough when adding/deleting/moving the sheets
fixes regression from commit 703dae0ea2322cee3f7af3d293f6ab7307f4d91a
Don't save position data when not switching sheets
1. Open Calc
2. in the current sheet scroll down a but and make some rows bigger
3. right-click on the sheet tab, insert sheet before
Result: resized rows are still visible
Expected: new sheet has equal small rows
---------------------------------------
impress: move part hashes to the docstate
// unify code with calc
> Calc: update geometry and position on new sheet insertion

- browser/css/notebookbar.css
Fix ce3b222049b2d1db3ffc5289a39e502ff7f1edb0
change-Id: I3abec2756997a589123ccc872114cb3c85edd826
Buttons and label wouldn't get the cursor, and disabled items would get the cursor too, while it is supposed to have the cursor "not-allowed".
disabled items are not properly handled currently, but that's a different issue.
ce3b222049b2d1db3ffc5289a39e502ff7f1edb0 needed to be adapted.
> unobuttons: have cursor pointer also on buttons

- kit/ForKit.cpp
```
Direct leak of 104 byte(s) in 1 object(s) allocated from:
#0 0x8a2200 in __interceptor_calloc
#1 0x7f6fc253d114 in cap_init (/usr/lib64/libcap.so.2+0x3114)
#2 0xaa6b57 in haveCorrectCapabilities() kit/ForKit.cpp:261:10
#3 0xa9e77e in forkit_main(int, char**) kit/ForKit.cpp:778:50
#4 0x110a0ad in main kit/forkit-main.cpp:19:12
#5 0x7f6fc1bb424c in __libc_start_main (/lib64/libc.so.6+0x3524c)
```
Change-Id: I74f8c01f3e5db12a690fa9fbfcd858fe0740f16e
* Resolves: # 
> result of cap_get_proc should be released with cap_free

- browser/src/layer/tile/CalcTileLayer.js
- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/layer/tile/WriterTileLayer.js
_onStatusMsg(textMsg) is only called from one place and there it is always followed by a call to _update();
since:
commit dffaeb228bb787af2be6b7a88048fc97c1df07d5
AuthorDate: Mon Nov 14 13:44:41 2022 +0100
masterpage: correclty refresh after switching mode
Mode is sent via status message so handle it there to avoid
race
but each _onStatusMsg impl might also call _update() so there are duplicate tilecombine requests
Change-Id: I6403852321cb727750aba4874d053a2d3c37abc4
* Resolves: # 
> duplicate _update() calls

- browser/src/control/Control.JSDialogBuilder.js
Core side PR: https://gerrit.libreoffice.org/c/core/+/172239
The problem:
When there is no unit for the number field, it is treated as time field.
Users with "," as decimal separator have issues when the field type is not set properly.
> Attempt to use a more precise filter for time field.

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
- browser/src/canvas/sections/CommentListSection.ts
- browser/src/control/Control.Menubar.js
- wsd/DocumentBroker.cpp
- wsd/protocol.txt
When we switch apps, we previously always saved the document. This causes trouble with some documents, such as PDFs, that can't be saved. When we try, the save fails and we cause an error popup.
Instead, let's not save the document when we switch apps and aren't in edit mode. To avoid missing any saves, we should also save the document when we leave edit mode.
* Resolves: # 
> fix(android): Stop saving readonly docs

- browser/html/cool-help.html
Before this commit the 2 shortcuts that trigger copy were placed
side by side with a comma in between, this was breaking the visual
table.
-> Add a break line so, it's easier to scan.
Note: the alternative would be using a rowspan="2" in the <tr> and
then add a new <tr> after that so, to achieve the same result but that
would break the search results (searching for copy would only show the
first shortcut). Conclusion: better to just add a </br>
Change-Id: Id1bd13dce0cacba7cdc38934f5b067fb26baf060
> Keyboard shortcuts dialog: Improve formatting on copy shortcut

- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.hpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
- wsd: async updateLockState
- wsd: disable editing when document locking fails
- wsd: LockUpdateResult captures the requested lock state
- wsd: read the readonly flag after writing
- wsd: async lock/unlock documents
- wsd: better logging of http status in WopiStorage
> Async Lock Refreshing

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/docdispatcher.ts
Fixes #8029 
All menubartoolitems which left are now converted to customtoolitems which use dispatcher to invoke internal commands. Code is shared with menubar this way. Remove it so noone will add more of them again.
> notebookbar: remove menubartoolitems #8029

- browser/css/notebookbar.css
- added icon path for `as-png-submenu-icon`
Change-Id: I82599f0a3ce757d62f2215ccb8118060cd9b7eb6
* Resolves: # 
> Add missing icon for download as PNG in draw

- browser/css/btns.css
Change-Id: Icdac9332fcd9584dc004f98a52772da041ff8496
* Resolves: #7591
When "None" is selected for the Columns style, the text is misaligned with the arrow.
> fix format > columns menu misaligned style text

- browser/html/cool.html.m4
- browser/js/global.js
This is a backport of #9884
Previously we exposed WOPI_HOST_ID and PROXY_PREFIX_ENABLED,
despite those variables being undefined for mobile. Additionally, we
incorrectly displayed the app name as MOBILEAPPNAME.
These appear to be regressions from https://github.com/CollaboraOnline/online/pull/9442
> backport: fix(mobile): Surface real information in "about"

- browser/css/jsdialogs.css
- browser/css/mobilewizard.css
This is a backport of #9890
Some of the coloring issues on mobile at the moment are truly egregious.
They leave dark mode text on a light mode background (or vice-versa),
leading to the text being entirely unreadable.
This happens because we have some colors hardcoded. Replacing them with
variables fixes this.
There are still some hardcoded colors after this change. I'm not sure
that this fixes everything, but it fixes the most obvious issues.
Change-Id: Ie1579751fb4154d1816dfd84becc726d06bc7876
> backport: fix(mobile): correct egregious dark UI colors

- browser/html/cool.html.m4
- browser/js/global.js
Previously we exposed "%WOPI_HOST_ID%" and "%PROXY_PREFIX_ENABLED%", despoenite those variables being undefined for mobile. Additionally, we incorrectly displayed the app name as MOBILEAPPNAME.
These appear to be regressions from https://github.com/CollaboraOnline/online/pull/9442
* Resolves: # 
> fix(mobile): Surface real information in "about"

- browser/js/global.js
As we insert other stylesheets after the head (and therefore later than
stylesheets in the head), they take precedence over stylesheets in the
head.
Therefore, we can't insert our device and branding stylesheets in the
end of the <head>. We need to insert them after the latest other
stylesheet.
This appears to a regression from https://github.com/CollaboraOnline/online/pull/9442
> backport: fix(mobile): reorder stylesheets

- browser/js/global.js
As we insert other stylesheets after the head (and therefore later than stylesheets in the head), they take precedence over stylesheets in the head.
Therefore, we can't insert our device and branding stylesheets in the end of the <head>. We need to insert them after the latest other stylesheet.
This appears to a regression from https://github.com/CollaboraOnline/online/pull/9442
Change-Id: I829c0dc1ad95a28650845d39aad9f975692319b8
* Resolves: # 
> fix(mobile): reorder stylesheets

- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- this is useful for controller, collabora online vm setup
- usually when running the collabora online in k8s environment we pass POD_NAME env variable. POD_NAME is needed as a env variable because on every restart POD_NAME changes that's not the case for COOL running in the vms
- why don't use POD_NAME for VMs as well ? In container you only create one user and COOL process run under same user. If we set env variable in container it sets env varialble for that user only and COOL process can access it. For VMs, that's not the case we might have multiple users. so you need to set global env variable to make it. Instead of doing that I prefer providing the name inside coolwsd.xml
Change-Id: I92c204a0315c74ab121b5aa48795646b9dede39a
> indirection: expose server_name when provided

- kit/Kit.cpp
- kit/Kit.hpp
core.git has an Application::AnyInput() mechanism to inform idle jobs
when they should stop their work (and continue that at a later stage),
but this was not aware of pending online.git work. This lead to e.g.
performing all the idle layout after pasting into a numbered list in a
Writer document, instead of first rendering tiles for the visible area,
and only then doing the rest of the layout.
This is a problem for interactivity, e.g. the above scenario with 300
Writer pages results in a 274 ms hang till the first tile is rendered.
Fix the problem by using the new registerAnyInputCallback() LOK API, so
interested core.git code can ask our side if there are pending input
events.
The first naive implementation resulted in interrupting core.git idles
far too often, so apart from calling …
> Related: cool#9735 kit: use the new registerAnyInputCallback() LOK API

- browser/src/canvas/sections/CommentListSection.ts
problem:
once comments are imported(i.e after reload) regardless of the show resolved comments, they were always shown
Change-Id: Ieb425faf2566bf7694723bea37dc9660f4c0ef5b
> annotation: after importing comment set showResolved stat

- browser/src/canvas/sections/CommentListSection.ts
- Adjusted the collapsedMarginToTheEdge so comment box does not get cut after document zoom
- better to have value same for all devices
Change-Id: I626388cdbf1db5bedf5f3fc5fe180e3d15a9ecfc
* Resolves: # 
> Fix comment box cut-off issue when zooming in

- browser/src/canvas/sections/CommentListSection.ts
- Adjusted the collapsedMarginToTheEdge so comment box does not get cut after document zoom
- better to have value same for all devices
Change-Id: I626388cdbf1db5bedf5f3fc5fe180e3d15a9ecfc
* Resolves: # 
> Backport: Fix comment box cut-off issue when zooming in

- browser/css/cool.css
- browser/css/tooltip.css
- tooltip font was "serif" -> changed to "sans-serif"
- added: --tooltip-font-size: 14px; for tooltip font-size
Change-Id: Ia06868b50a0c45b7dfe5df5462b932231e6e44a3
* Resolves: # 
> Change tooltip font to sans-serif

- kit/Kit.cpp
**Backported**
The mount-point must exist already, since
we always mount read-only. There is no
directory to create, but the subsequent
chmod always fails, since the mounted
directory is read-only. Since we started
warning when chmod fails recently,
6208b37a327266c583f47cdd13948d57ecfcce05,
these previously-silent failures became
noisy.
Change-Id: I9efaa89182c016e9a7a5d36cc3da5bfa7ee599c2
(cherry picked from commit c1ced10f17d1190f259030d93b8002aee177ce6b)
> wsd: no need to create existing mount-point

- browser/src/control/jsdialog/Widget.ScrolledWindow.js
This reverts subset of: https://github.com/CollaboraOnline/online/pull/8011
Impact:
- calc function wizard
- insert symbol
- file properties - custom properties
Related bugs on master:
https://github.com/CollaboraOnline/online/issues/9614
https://github.com/CollaboraOnline/online/issues/9559
https://github.com/CollaboraOnline/online/issues/9770
It seems it fixes all of them, but breaks "polished look" of custom properties. Which is less damage.
cc: @meven @thebearon @timar
> revert scrollwindow patches breaking function wizard (co-24.04)

- browser/css/partsPreviewControl.css
- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
When we insert a new slide via context menu of the slidesorter, new slide should be inserted on pointer position instead of end of the last selected slide.
Change-Id: Ie5efb78d6b6ee468cda150cc416cbd2ab536d6dd
* Resolves: # 
> Insert new slide to specific position

- browser/Makefile.am
It is:
find: 'node_modules/jquery-ui/ui/i18n': No such file or directory
This directory is created during normal build.
Change-Id: Ie7c2cee129f1f880a22c4a4d8a48788b73570d5b
> silence error from find during 'make dist'

- browser/src/core/Socket.js
this will fail on CI jobs - protecting us from breaking local testing
> cypress: fail on exceptions even without debug

- wasm/base64.hpp
./wasm/base64.hpp:109:7: error: ‘uint32_t’ was not declared in this scope
Change-Id: I9de3054504fc6108b473f99c8b43cc3c7cc567fe
* Resolves: # 
> uint32_t needs <cstdint>

- wsd/FileServerUtil.cpp
Compiler complains about unknown uint32_t type.
Change-Id: I690d89470bfdd977e7fa71957cdc118d9257b7b9
> fix regression from "Use a hidden variable to get the css vars from url"

- browser/src/control/jsdialog/Util.KeyboardGridNavigation.ts
- Resolved an issue where keyboard arrow keys were not moving the cursor in custom input fields within grid elements.
- Ensured consistent keyboard interaction across all input fields in grid-based components.
Change-Id: Ice8023bec31d2dfb318d2a4ec92ebb8329c5bac9
> Fix: Enable keyboard arrow navigation in custom input fields within grids

- browser/src/layer/tile/CanvasTileLayer.js
we can pass undefined rectangle data to otherViewCursorSection as it is already expecting that case.
To reproduce error:
- session A runs automatic typer in Calc
- session B opens the same sheet and then reloads the page Result: error in session B
> Fix JS error: missing sheetgeometry

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
problem:
even if resolved comments were not shown,
on resizing window enough to change stat of comments from collapsed to full or vice versa, text containing comment was highlighted
Change-Id: Ia69fd39392411478d84a409fb92af0050db71a1e
> annotation: resolved comment highlights get visible on resize

- common/Util.cpp
- net/DelaySocket.cpp
- net/HttpRequest.hpp
- net/ServerSocket.hpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
* Resolves: C++ ambiguity, no issue report
Resolving some C++ ambiguities, no issue report.
See commit messages for details.
> C++ Cleanup: Default ctor/deleter, drop virtual of virtual-overrides and fix Util::getSystemClockAsString()

- ios/Mobile/Info.plist.in
* Resolves: # 
This is a parallel to #9958, however it is nonidentical as master is on 24.04.7 not 24.04.6
> chore(iOS): bump version to 24.04.6

- debian/coolwsd.postinst.in
- debian/coolwsd.postrm
Change-Id: I40e3b4069486141df7e01ba8df480fd9a4820e91
* Resolves: # 
> remove apparmor profile that depends in abi 4.0 if that is not available

- Makefile.am
so the step to set caps is missing
https://github.com/CollaboraOnline/online/issues/9948
Change-Id: I9dd2cd2309f2169d05c4b7d3ecdaca5a978b965b
* Resolves: # 
> coolwsd-deprecated package missing its postinst

- net/DelaySocket.cpp
net/DelaySocket.cpp:32:18: error: private field 'WindowSize' is not used [-Werror,-Wunused-private-field]
const size_t WindowSize = 64 * 1024;
> Fix clang build: unused WindowSize

- kit/ChildSession.cpp
Works with https://gerrit.libreoffice.org/c/core/+/172796
Change-Id: Ifb9dc903c9518d4097f2f0ea2679add840b47233
* Resolves: # 
> Use current statuses for caching normal-notes view changes.

- browser/src/canvas/sections/CommentListSection.ts
problem:
incorrect function call was sending additional ShowResolvedAnnotations requests it caused to disregard the ShowResolvedAnnotations stat on reload unless document was saved
Change-Id: I3ab0f8b804428ea813582c04c85540363e51e210
> annotation: fixed incorrect function call

- browser/css/cool.css
Change-Id: I94999b6d8de45ddf9c7c1012d9314694ec5be33b
Fixes the problem of visible "false" string in About box.
> Hide these elements in About box effectively

- kit/Kit.cpp
Commit 930cd616fb6defd8c0de0163bd92e637c7b6b76f (Related: cool#9735 kit:
use the new registerAnyInputCallback() LOK API, 2024-08-26) started to
interrupt Writer layout and other idle tasks when we have pending
events.
The intent was to check if we have pending events in anyInputCallback(),
but it turns out that poll() not only checks if there are events to be
processed but also potentially processes them, which I didn't realize
when I did the above commit.
Fix the problem by only checking the callbacks list and the tile queue
in anyInputCallback(): that is enough to keep the interactivity win and
makes sure to avoid a re-entrancy hazard there.
The 300 pages bugdoc with its numbered list is still laid out in 2 steps
(visible page layout, repaint, rest of the layout) after this. …
> Related: cool#9735 kit: make sure we don't process events in the any input callback

- browser/src/canvas/sections/ShapeHandlesSection.ts
Remove inline style from svg html string before using it.
Change-Id: I36d215e63e5e7947695b7da00c53ccf283ab82a9
There is a JS error if we use inline style for SVG elements. We remove it before assigning the SVG content.
To reproduce:
* Add a shape and write some text into it. Then select it.
> Impress: Fix shape selection JS error.

- browser/src/control/Control.Attribution.js
- browser/src/layer/tile/CanvasTileLayer.js
Remove unused function.
Change-Id: I1dfd82476e827fce0b83eafe85536c5a0424c99d
* Resolves: # 
Enable debugging tools and and enable tile invalidations. There is a JS error that prevents text on screen. This PR fixes the issue.
> Fix JS error in debug mode.

- docker/from-source/Debian
- docker/from-source/Ubuntu
Update Dockerfiles to be able to build local via docker (not via GitHub actions).
- Update to ubuntu 24.04 image to reflect change in gh action
- adapt user-id necessary since Debian 12 / Ubuntu 24.04
- add missing ca-certificates package that prevented WSD starting
> Fix Dockerfiles for local docker built

- net/HttpRequest.hpp
malformed Content-Typer header prevented admin pages from properly loading with certain browsers (Apple Safari).
> fix malformed Content-Type header

- browser/Makefile.am
- browser/css/helpdialog.css
- browser/html/cool-help.html
- browser/src/control/Toolbar.js
- Remove remove css from cool-help.html and replaced with class attrs
- moved all style tag css to file helpdialog.css
- fix typo for icon `fold`
Change-Id: I91076904a58e9d8e2a0952836f5073d744b715fe
* Resolves: # 
> Remove inline css from helpdialog

- common/CoolMount.cpp
- common/JailUtil.cpp
They used namespace mounts for / so that was both unmounted automatically when the child exited, and not visible to the parent anyway, so there is no "lo" dir to check for.
Change-Id: Ia98032abaae8a33abd57cef38bdc97f6ff4fb0c2
* Resolves: # 
> enable cleanup of namespacing using jails

- net/Socket.cpp
- net/Socket.hpp
#82030 0x000000000064f99f in DocumentBroker::pollThread() () at wsd/DocumentBroker.cpp:683
#82029 0x000000000062b7a1 in DocumentBroker::dumpState(std::ostream&) () at /usr/include/c++/12/bits/unique_ptr.h:461
#82028 0x0000000000802955 in SocketPoll::dumpState(std::ostream&) const () at /usr/include/c++/12/bits/shared_ptr_base.h:1665
#82027 StreamSocket::dumpState(std::ostream&) () at net/Socket.cpp:936
^^^ first call
#82026 0x0000000000803339 in ProtocolHandlerInterface::dumpState (os=..., this=0x7f8d54162cb0) at /usr/include/c++/12/bits/
#82025 0x00000000006b19ad in http::Session::dumpState (this=0x7f8d54162cb0, os=..., indent="\n ") at ./net/HttpRequest.hpp:1345
#82024 StreamSocket::dumpState(std::ostream&) () at net/Socket.cpp:936
^^^ reenter
probably an issue since:
commit …
> don't recursively call StreamSocket::dumpState

- browser/src/canvas/sections/CommentListSection.ts
On Writer, when in readonly mode with comments activated restrict
the hability to delete and modify comments to only those made by
the same user.
Change-Id: I7787946c7c25d7ad97074ebf6f1c8478fb9a84de
> lok: sw: restrict delete and modify on comment only mode

- browser/src/core/Debug.js
Previously we were using \<br/> tags to do newlines in debug mode. In https://github.com/CollaboraOnline/online/pull/9980, we changed from innerHTML to innerText - which is generally a good idea. Unfortunately, it also broke the HTML tags. We can use '\n' for newlines instead.
We also used \<b>, but that wouldn't be possible without introducing extra complexity into the debug overlay.
* Resolves: # 
> fix(debug): Correct newlines

- browser/css/cool.css
- Context sub-menu arrow key color was same as menu item bg color. Replaced with appropriate color variable
Before:
After:
Change-Id: I57bff4640156fa52f92ce1678caa364218349b9c
* Resolves: # 
> Fix context submeny arrow key color

- browser/src/canvas/sections/CellSelectionHandleSection.ts
When selecting multiple cells in a spreadsheet with lots of narrow cells, the selection drifted to the left. This made it very difficult to make accurate selections.
It appears this is due to erroneously missing the correct X position in the selection autoscroll.
Fixes: CollaboraOnline/online#9906
* Resolves: # 
> fix(calc): Stop incorrect movement in selection

- ios/Mobile/CODocument.mm
Also, use a local autorelease pool to force destruction of remaining temporary buffers immediately after use instead of waiting for the thread's current autorelease pool to drain.
Lastly, just to be safe, include the pretext and posttext lengths when allocating the vector's capacity.
> Reduce temporary copies of large buffers

- Makefile.am
- common/SigHandlerTrap.hpp
- common/SigUtil.cpp
- common/SigUtil.hpp
- common/Util.cpp
- kit/Kit.cpp
Centralize waiting in a single, normal exit location. This avoids us loosing and not being able to attach to and debug a crashed child thread when another thread decides to _Exit for some reason while the signal handler is running in the other thread.
Change-Id: I9a788960712506593c61b68305ed6cb90f948ead
* Resolves: # 
> signal waiting - always wait for signals before _Exit.

- net/ServerSocket.hpp
- net/Socket.cpp
- net/Socket.hpp
- Use override for virtual function overrides (incl. dtor)
- Use C++ std headers, e.g. cctype instead of ctype.h
- Use global anonym namespace for system functions or std:: system functions, whichever is applicable
- Use std::make_shared<StreamSocket>(..)
- Use std::make_unique<Watchdog>()
- Use 'const' where applicable
- Use pre-incr where applicable
- Use typename where applicable
- Drop redundant type conversions
Change-Id: Id844187c82fce3c6e9bceb512c07180705608ebc
* Prepares for: #9833
> C++ Misc Cleanup: More override, std-header, std::make_* usage, ..

- browser/src/control/Control.MobileWizardWindow.js
There is an error related to inline styles. This commit fixes the error.
Change-Id: I2eb1ca65e829d36c9fb80981dbf82980a8f2d173
* Resolves: # 
> Fix JS error when opening mobile wizard.

- android/lib/src/main/cpp/androidapp.cpp
- browser/js/global.js
- ios/Mobile/CODocument.mm
- wasm/wasmapp.cpp
In I66f8edb5f35e2300e3a0407a139e72039bec0d8d I introduced a regression where unicode messages were decoded as ascii, leading to, e.g., accented characters in jsdialogs being mangled.
I've written a function ("b64d") to decode these messages. I picked the name because it's the same length as the original "atob" (which is useful for buffer size compatibility) and stands for "base 64 decode".
* Resolves: # 
> fix(mobile): Unmangle unicode text messages

- android/lib/src/main/cpp/androidapp.cpp
- browser/js/global.js
- ios/Mobile/CODocument.mm
- ios/Mobile/Info.plist.in
- wasm/wasmapp.cpp
This additionally backports #9986 from @plubius, as the unmangle change doesn't apply cleanly without it
> backport: fix(mobile): Unmangle unicode text messages

- browser/src/control/Control.JSDialogBuilder.js
Previously the radio button text ignored whether the radio button was disabled, allowing you to click it and switch to a disabled radio button.
* Resolves: # 
> fix(jsdialog): Sync radio text disabled status

- browser/src/slideshow/LayerDrawing.ts
Fields are "template" elements like page number which are different on different pages. If we will cache one of them then we tried to reuse it on all other pages as we thought we already have correct data.
This patch disables caching for master pages with fields. This is temporary solution until we implement correct text fields handling on the core side. This change requires minimal "isField" JSON property add in the core to work.
requires: https://gerrit.libreoffice.org/c/core/+/173160
> slideshow: don't cache fields for now

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/MetaPresentation.ts
- browser/src/slideshow/engine/MetaSlide.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
it makes us aware of hidden slides (previously we didn't get them in the list - so requires core change)
handle both direction of skiping the slide when displaySlide fails
REQUIRES: https://gerrit.libreoffice.org/c/core/+/173218
> slideshow: handle hidden slides

- common/Util.cpp
- common/Util.hpp
noexcept is banned in coolwsd. It is a premature optimization that brings risk of unexpected termination of a server process. For simple in-line methods, the compiler will deduce this anyway, and for complex methods - it is unlikely that we can maintain this reliably.
Performance should be optimized after profiling.
Change-Id: Ib11e56580131d57d106976db5591f392803f4328
* Resolves: # 
> Remove noexcept usage.

- browser/src/control/Control.UIManager.js
- browser/src/dom/NotebookbarAccessibility.js
- browser/src/map/handler/Map.Keyboard.js
- browser/src/map/handler/Map.KeyboardShortcuts.ts
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
- Save and find events were not considered as global event, which is the reason of Keyboard shortcuts like CTRL + S or CTRL + F are not working outside `map`
- this patch will fix that issue. Now user can get focus on search input from anywhere on the document also document save will also work as expected.
- problems like after CTRL + S sometimes we got web browser save popup will be fixed by this patch
+++ Problem +++
- CTRL + S and Ctrl + F are not working before this patch for cases like
- Press alt (to activate the accesskey tooltip) in the notebookbar
- Place the cursor inside of the document name Press ctrl + S
- open About dialog
- Press ctrl + F it triggers in the browser search and not the status bar.
- Press ctrl + S it triggers in the browser save and not the COOL save action. …
> Fix keyboard shortcuts not working outside map region

- browser/src/map/Map.js
- kit/ChildSession.cpp
- kit/ChildSession.hpp
allow busy popups with specific ids to run until specific
busy popup is finished
problem:
busy popup used to disappear quickly, exported files may not have completed upload. User may think that exporting is finished and close the doc. Which caused failure in export.
Change-Id: I14bce386a200a4f2deae22b1fbefd597b9347268
> kit: show busy popup for exported file until ui is unblocked

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/MetaPresentation.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
- kit/ChildSession.cpp
handle presentation info has changed message
request for updated presentation info
clean current status
restart presentation from last displayed slide if it still exists from
first slide otherwise
make SlideSHowNavigator.quit to be invoked on closing the presentation
window through the window close button.
Change-Id: I72cf065056245b2c98ff5474be7131235e9683da
this needs core patch: https://gerrit.libreoffice.org/c/core/+/173061
> slideshow rework: presentation info changed on playing slideshow

- test/UnitSession.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
- wsd/FileServer.cpp
- wsd/RequestDetails.cpp
- wsd/RequestDetails.hpp
* Resolves: #10042
cool#10042: Close incoming HTTP Connection if requested (Regression of cool#9621)
Before commit 8c05bdcd74009eed11be2c247dfd8a5fd6c1c9fa
for cool#9621 `Keep Connection Open for files served via FileServerRequestHandler and ClientRequestDispatcher ...`,
all client connections got closed.
Since this change, we try keeping all connections open.
However, an explicit client request w/ `Connection: close` got ignored
in `ClientRequestDispatcher::handleIncomingMessage`.
This patch reverts behavior as follows:
- If the request has been handled synchronously (served==true),
then socket->eraseFirstInputBytes(body-bytes)
- If close-connection is requested via HTTP/1.1 header `Connection: close`
or if HTTP/1.0 header does not contain `Connection: …
> Close incoming HTTP Connection if requested

- browser/css/mobilewizard.css
- browser/src/control/Control.MobileWizardBuilder.js
The following were issues with the old radio button design:
- It flowed to the edge of the container, whereas everything else has a margin
- It didn't properly center the button vertically
- It had a strangely-sized right margin
To fix this, I've used flex to align everything (as float: right takes elements out of layout so can't be used without making the centering of the label brittle). I've also swapped the order of the creation of the button and label (as previously we were relying on float: right to visually swap them, and while you can do the same with flex's order property it's generally a poor idea for accessibility support)
Change-Id: I7863e1d41bcd5b9dc859fbb10b031f3e7a2859e3
* Resolves: # 
> fix(jsdialog): Clean up radio button styling

- kit/ChildSession.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
_clientSelectedMode is set after the first tiles invalidation.
So this commit sets it beforehand.
See Core side ViewShellBase.cxx -> getEditMode for more info.
> Fixes invisible typing issue.

- wsd/ClientRequestDispatcher.cpp
When built with additional configure flag: --enable-feature-lock
regression from commit cdbc3af0d764b46458de5ea696b695ade79c662d
cool#10042: Close incoming HTTP Connection if requested (Regression of cool#9621)
> Fix build with feature lock

- coolkitconfig-mobile.xcu
- coolkitconfig.xcu
problem:
font color did not account for the alpha channel
due to not having alpha channel, some conditions would evaluate false in core even if they are same color
i.e: fontColor == COL_AUTO because (COL_AUTO contains alpha channel)
Change-Id: I4c1d62a5203ae4efd03244a4c7fa9d0999a365dd
> config: remove font color value and use fallback 

- browser/src/slideshow/SlideRenderer.ts
When a slide contains a video, the pause timer text appears mirrored. This was due to the gl.UNPACK_FLIP_Y_WEBGL flag is true while rendering videos, which flips textures vertically. The flag was not reset afterward, causing subsequent textures (like the pause text) to be flipped.
This fix resets gl.UNPACK_FLIP_Y_WEBGL to false after rendering videos, ensuring that the pause text displays correctly
Change-Id: I529bfec5a1ebbac62d938dbeb7ce2782bfdf4a61
> Slideshow: Fix mirrored pause text issue with video slides

- browser/src/control/Control.PartsPreview.js
- browser/src/control/Parts.js
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
When we close fullscreen we don't call escape handler as earlier we turn off it's handler so we didn't properly clear status of navigator.
This caused bug when presenting second time. We didn't start from current slide but the last slide of previous fullscreen slideshow.
> slideshow: fix present from current slide

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- Ensure that background inversion applies exclusively to the document page/slide and not the surrounding areas.
- This fixes unintended behavior where inversion affected the non-document regions, which is inconsistent with expected behavior and user experience in most editing environments.
Change-Id: Id3113185b1cd954ad48c9b63df573a919c871049
* Resolves: # 
> Fix: Restrict invert background feature to document content only

- browser/src/control/Control.NotebookbarWriter.js
+ Corrected the hover text labels in the Table menu to ensure they accurately describe the actions they represent:
+ Adjustments are done based on which string should be displayed from unocommand.js file( "Context" or "menu")
This resolves inconsistencies and improves user experience by providing clearer descriptions for each menu action.- 
Updated string :
-  "Cell" to "Select Cell"
-  "Table" to "Delete Table" and "Select Table" accordingly
-  "Row" to "Select Row"
-  "Column" to "Select Column"
-  "Columns" and "Rows" to "Delete Selected Columns" and "Delete Selected Rows"
Change-Id: Iec2f04434eb175cbf5a38a5b91dd3e4e896ce7e9
* Resolves: # 
> Fix hover text labels in Table menu for consistency and clarity

- browser/src/slideshow/transition/FlipTilesTransition.ts
- browser/src/slideshow/transition/MicsShapeWipeTransition.ts
- browser/src/slideshow/transition/SimpleTransition.ts
Slideshow: Enhance flip tiles transition
* Added WebGL flags to enable multi-texture rendering for simultaneous display of both slides.
* Fixed a potential GL state issue in the displaySlides function, ensuring proper handling of texture binding and GL state preservation during the transition.
Change-Id: I15d0a7c418225e1f707f16fcb65ade68f4c90ad6
* Resolves: # 
> Slideshow: Enhance flip tiles transition

- browser/src/slideshow/SlideShowPresenter.ts
the last slide with text "click to exit the presentation" requires enabled webgl in the browser. Avoid error if it is missing and just close the slideshow.
> slideshow: allow to exit with 2d only mode

- browser/src/slideshow/transition/SimpleTransition.ts
This fixes a regression introduced in commit 3a1f0357c0e918cd2681211a9061a934c1dd2349.
In the FlipTilesTransition, we enabled several WebGL flags such as DEPTH_TEST and CULL_FACE, and disabled BLEND. Since WebGL uses a global state machine for each canvas, these state changes inadvertently affected other transitions that rely on different WebGL states, causing them to break.
To fix this issue we have to disable those flags in initWebglFlags.
Change-Id: I92d73ba079d29fa05c5077d06c5d64b9480ddd7c
> Fix broken transitions due to global WebGL state changes

- common/Util.cpp
- common/Util.hpp
- coolwsd.xml.in
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- before this patch we were trying to get timezone from the os timezone file. But that is not consistent because most of the VMs would have timezone set to UTC
Change-Id: Id241ad6f57eeb3c084733f174ba5d1c4a547ced6
* Resolves: # 
> indirection: get timezone from coolwsd.xml

- browser/src/slideshow/RenderContext.ts
Solves problem with closing slideshow with the video: SlideRenderer.ts:381 Uncaught TypeError: Failed to execute 'deleteTexture' on 'WebGL2RenderingContext': parameter 1 is not of type 'WebGLTexture'.
at RenderContextGl.deleteVertexArray (RenderContext.ts:93:6)
at VideoRenderInfo.replaceVao (SlideRenderer.ts:36:11)
> slideshow: fix error on vertex array delete

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
- browser/src/map/handler/Map.StateChanges.js
Fix dark mode icon not highlighted on reload
- StateChange Handler needs to get initialized for 'toggleInvert' on load.
Invert background button should get highlighted on toggle.
- add classs 'selected' on invertbackground after we change state or apply invert
- StateChange Handler needs to get initialized for 'invertbackground' on load.
* Resolves: # 
> fix dark mode & invert BG icon should be highlighted on mode change

- browser/css/jsdialogs.css
Change-Id: I338d995f23f898faffaadd5a32c17f982011c33b
* Resolves: #10041 
Fixes checkbox and label being misaligned in the Show Sheet modal
> Calc: fixes misaligned checkbox

- browser/src/canvas/sections/CommentSection.ts
- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
The helper function isAutoSave checked the author of the new
comment against the author of autoSavedComment. But in case of
an autosaved reply, autoSavedComment is the parent of the reply.
So we must check the new comment's author against the username,
who would be the author of an autosaved reply.
Change-Id: Ica5d12c81c58f81e00d70a5333053a2fa514f360
> annotations: isAutoSaved helper check correct author

- browser/src/control/Toolbar.js
Add .uno:PromoteComment to the list of allowed commands in readonly
mode with comment editing allowed.
Change-Id: Ic705175cc674f57626d845be1344afd3c1065bb9
> Add promote comment to allowed comment commands

- browser/css/jssidebar.css
commit e8f304033886564e2ab54bdad4d0db0b3b4a7891 (HEAD -> private/pedro/sidebar-n-transition-btntext, origin/private/pedro/sidebar-n-transition-btntext, master)
Date:   Tue Sep 3 10:02:40 2024 +0200
Impress: Transition sidebar buttons are unreadable in dark mode
Before this commit the sidebar elements were not being set with any
particular text color.
Change-Id: I8e8eab765619fcc6fec151c89854b4b478906324
commit 025d56b067ab650f82af8c7a1f34f20e351b1813
Date:   Tue Sep 3 10:01:13 2024 +0200
sidebar.css: Remove 0 byte legacy file
It seems there is not need to update browser/Makefile.am, the file is
not listed there …
> Remove sidebar.css and fix Impress' transition text on dark mode

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/Storage.cpp
- wsd/Storage.hpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
This is in preparation to re-synchronize the LastModifiedTime after we fail to upload.
_Best to review one commit at a time._
- wsd: wopi: remember the document size we uploaded
- wsd: wopi: track the document size on the server
- wsd: wopi: return the file-size from uploadLocalFileToStorageAsync
- wsd: centralize document conflict handling
> Prerequisites for Smarter Upload Failure Handling

- browser/src/control/Control.ContextMenu.js
In "_createContextMenuStructure" function, we are checkin the text against certain texts.
We first need to check if there is a "text" property.
To reproduce the issue, one can use the right click menu for spell-checked and redlined text portions.
Change-Id: Ic9a919e453886f752182a0aedc84e46597c13f2e
* Resolves: # 
> In context menu, separators don't have a "text" property.

- browser/src/slideshow/engine/SlideShowNavigator.ts
If we have presentation which has enabled repeated slideshow\with timer, we see at the end counter and presentation starts from the first slide. This was not working correctly as we didn't see first transition when we repeated first slide after seeing counter. Let's use better function which does initial setup too.
> slideshow: repeated presentation with initial transition

- scripts/contributors-credit.js
- Fetch contributors from GitHub and sort by contributions.
- Generate a Markdown file with pre-defined metadata.
- Create a styled HTML layout to display contributors.
Change-Id: Ibc2d8533e8b6636a61fca743a145c1c44cbb418e
* Resolves: # 
> Generate contributor list with metadata and HTML layout

- browser/src/control/Control.ContextMenu.js
Open Writer, copy some text, unselect, right click: a 'more options'
menu item is there for paste special, but the desktop has a clear 'paste
special' menu item instead.
Commit ab896c1c78ed220044ca7fc10b6746d78cdb529a (clipboard: add Paste
Special also in context menu, 2022-04-05) collapsed the desktop context
menu to only have 'paste special' as a menu item instead of a submenu,
which is fine -- but the 'item.text' set is overwritten later based on
the label of the uno command. That 'more options' label is fine, but
only in the context of the 'paste special' context menu, not standalone.
Fix the problem by adding PasteSpecial to the list of UNO commands where
we don't overwrite the label based on the command name.
Change-Id: …
> cool#10106 browser, context menu: fix label of the paste special menu item

- browser/html/cool.html.m4
- browser/src/control/Control.AboutDialog.ts
- browser/src/core/Debug.js
We want to hide some elements outside of debugging mode, which is activated by triple click on about dialog. That requires some elements to be created hidden by default. This commit removes the "style="display:none"" code from HTML. Because that way of defaulting to hidden raises CSP issues. Instead, we hide them right before we show the about dialog.
Also, there were duplicate IDs of elements in about dialog. Since we clone a dialog which already exists, all the IDs in that dialog are duplicated. This commit adds "-cloned" suffix to 2 elements which have duplicate IDs. We probably need to check also other duplicates.
Change-Id: Idef8e842b2b2fd90a1639db63dd490d7718ff1c9
* Resolves: # 
> Refactor some elements in about dialog box.

- browser/src/slideshow/engine/SlideShowNavigator.ts
after interaction feature was done we expect to always have it's data. but we also have dummy slides without any data for showing the text on blakc brackground (click to exit, etc)
> slideshow: fix error on dummy slides click

- browser/src/control/Control.IdleHandler.ts
don't enter idle mode if presenting, that diconnects us from the websocket and causes to stop the presentation in current point
> slideshow: keep connection when presenting

- browser/src/map/Clipboard.js
Previously on mobile, we were only using the uno commands for some
clipboard operations - the pasting ones. That's incorrect, as on Android
and iOS we don't have access to the browser clipboard APIs and should be
using the native bits, which for Android intercept these UNO calls and
use them to manage the clipboard.
For iOS, this still falls over - albeit in a slighly different way - but
the iOS clipboard code is in core and is nontrivial to fix. I have a
patch in the works which would make an API similar to
navigator.clipboard for iOS/Android (hopefully reducing our pains here)
but I don't see a point in not making a tiny, temporary Android fix.
When I change the clipboard system's mobile app bits, this will go away
anyway :)
> fix(android): Use uno command for all clipboard

- browser/src/control/Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Idd24de6d8765a983c7f36a3b5459f41d52a69b43
* Resolves: #6521
If text is selected when opening the hyperlink modal, focus will be set on the link input. If no text is select, then focus will be set on the text input.
> hyperlink modal text and link focus

- browser/src/control/Control.Menubar.js
Change-Id: Iafeeac96893816b813ff3d6fe0c5a845adcb759d
* Resolves: #9750
> menubar: disable "serveraudit" option in help menu items in read only mode

- browser/css/cool.css
Or browsers may ignore the rule. Also removed an unnecessary "calc" function.
Change-Id: Iab2715d93d84a6c3f314d1619b31f88c96b4d3cf
* Resolves: # 
> In CSS, "Calc" should start with lowercase "c".

- browser/src/slideshow/PauseTimer.ts
- browser/src/slideshow/SlideShowPresenter.ts
If we close "pause screen" with counter before it ends. Timer was still active causing an error in the browser console.
> slideshow: stop timer if closing

- browser/src/slideshow/engine/SlideShowNavigator.ts
global.js:552 Uncaught RangeError: Maximum call stack size exceeded
at Arguments.slice (<anonymous>)
at Object.logWithCool [as log] (global.js:552:40)
at DebugPrinter.print (tools.ts:181:23)
at SlideShowNavigator.displaySlide (SlideShowNavigator.ts:189:10)
at SlideShowNavigator.displaySlide (SlideShowNavigator.ts:224:9)
at SlideShowNavigator.displaySlide (SlideShowNavigator.ts:224:9)
> slideshow: avoid reccurent calls with wrong number

- browser/src/slideshow/SlideShowPresenter.ts
If we use presentation with autostart (.pps) then
fullscreen request fails as it is not invoked by the user interaction. For now do the fallback -> open in window. If user has disabled popup, he will be asked in the message box to allow the popup.
> slideshow: autostart in window

- browser/src/control/Control.JSDialogBuilder.js
Open the signatures dialog, add a signature, the certificate chooser
sub-dialog appears. Select a certificate, that enables e.g. the sign
button, but not the description input field for some reason.
Checking the websocket incoming traffic, the message for the working
button and the broken entry is the same:
jsdialog: { "jsontype": "dialog", "action": "action", "id": 10, "data": { "control_id": "viewcert", "action_type": "enable"}}
jsdialog: { "jsontype": "dialog", "action": "action", "id": 10, "data": { "control_id": "description", "action_type": "enable"}}
But the DOM is different:
```html
<button class="ui-pushbutton jsdialog" id="viewcert" accesskey="V" disabled tabindex="0"><u class="access-key">V</u>iew Certificate</button>
<div class="ui-edit-container jsdialog" id="description" …
```
> cool#9992 doc sign: fix missing enable on the cert chooser description entry

- browser/src/slideshow/StaticTextRenderer.ts
if we went to the last slide saying "click to close" the rendering was retriggered all the time.
that caused issue with going to the previous slides which were covered by the black slide with text
> slideshow: avoid infinite render

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
If the document has one signature, then the status bar has an icon and
you can add more signatures. But you can't add a signature if the doc
has no signature at all, which is the primary use-case.
There is no icon is the "no sign" case because signing is a relatively
obscure feature, and it's good to not clutter the status bar with an
icon by default.
Fix the problem by adding a button for it on the File tab of the
notebookbar. This has the benefit that it's not visible by default (Home
is the default), and it's also next to the Properties button, matching
the desktop order in the File menu.
Possibly later we'll hide these when we learn that user has no sign
certificates configured, that's not yet done here.
Change-Id: …
> cool#9992 doc sign: add sign button to the home tab of the notebookbar

- browser/src/map/Clipboard.js
Visit a URL like
http://192.168.0.3:9980/browser/.../debug.html?file_path=..., select
some text, copy, wonder why you get the old popup for complex selections
even on Chrome.
Compared to about half a year ago, Firefox now also supports the async
clipboard, see
<https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/127#apis>,
which means that the lack of async clipboard is not considered OK in
production. (Firefox ESR is now at 128.2.0esr, Chrome/Safari supported
async clipboard already). Also, non-localhost HTTP URLs have the entire
navigator.clipboard JS object as undefined, so a local dev setup can hit
this even with Chrome.
Fix the problem by showing a snackbar when we detect a broken setup, to
help understanding the root cause.
Show this all the time when async clipboard …
> cool#10159 browser, clipboard: visible warning on copy without async clipboard

- wsd/FileServer.cpp
Debugging the entire file storage -> COOL -> LO core chain in one step
can be complex, issues are easier to investigate if a COOL 'make run'
setup can also reproduce the problem. Not to mention that testing with
cypress is easier if the test case doesn't require an integration.
Signing certificates are meant to be handled similar to previous secrets
like the Zotero API key, but that only works with a file storage
integration.
Solve the problem by looking for files next to the loaded document for
the 'local file' WOPI provider (in debug mode). So for example test.odt
looks for files named test.odt.cert.pem, test.odt.key.pem and
test.odt.ca.pem: if those exist, then you can sign the document without
an integration.
The kit process in Document::load() doesn't make use of this sign data
yet, …
> cool#9992 doc sign: local file wopi provider: allow setting the sign cert/key/ca

- kit/Kit.cpp
- kit/Kit.hpp
This reaps zombie child processes that we
couldn't reap after getting disconnected
from them. Very likely because the kernel
hadn't unloaded the process yet.
We reap any child process after spawning
a background save. This way, we would
have at most 1 zombie at any time.
This gives the minimum overhead while
ensuring that we don't leak.
Change-Id: Idd8531ec721744fa31d7ec767b87dc3deb18c193
> wsd: reap the background save process

- ios/Mobile/Info.plist.in
- ios/modify_bundle_version.sh
This is a port of the unmerged https://github.com/CollaboraOnline/online/pull/10164. Hopefully this 24.04-mobile branch can become a branch that better represents how mobile is without having to merge risky patches into cool
Previously we were using versions like "24.04.7" for release "24.04.7.3". Unfortunately, this works poorly if we want to have a patch release, as we can't reuse codes so we have to immediately go to "24.04.8", even when releasing from a "24.04.7" tag.
Merging our year and major release into Apple's major release number makes more sense with how we expect releases to change over time...
We also need to change how we generate the CFBundleVersion, as  otherwise it will be invalidly-long (the maximum length being 18 characters and "2404.7.202410021739" being a frustrating …
> fix(ios): better approximate our version format

- kit/Kit.cpp
- kit/Kit.hpp
To be able to sign documents, at least the 'local file' WOPI provider
sets 3 keys under UserPrivateInfo to give the wsd, and then the kit
process the signing certificate.
The other end is the core side, which takes 3 keys as a view options in
initializeForRendering().
What was missing is to connect these two: this way a 'make run' session
can sign documents without hardcoding cert/key/ca PEM files anywhere.
The integration side and cypress tests are not yet done here.
Change-Id: I1f847349e10336c69019c7f1747208e6be954362
> cool#9992 doc sign: set the view's sign cert from the WOPI UserPrivateInfo

- kit/ChildSession.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
This is a backport of https://github.com/CollaboraOnline/online/pull/10026, it's only against 24.04-mobile as while it does improve things it also causes a regression - so we can't put it in our fully stable release, but hopefully it should still make things better enough to justify it being in this mobile release. 
_clientSelectedMode is set after the first tiles invalidation.
So this commit sets it beforehand.
See Core side ViewShellBase.cxx -> getEditMode for more info.
Change-Id: Iddd2e0b235cc754f850223f2aff36ba6fc2aeb85* Resolves: # 
> Impress: Fixes invisible typing issue on notes view.

- kit/ChildSession.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
This commit, as part of #10186, causes a regression to slide previews on
new slides, which I believe to be more common than editing presenter
text. Therefore, I've decided to back out.
This backs out commit cd2ad5a.
Change-Id: If8f53db3b87360681231063d727a373c2267eb61* Resolves: # 
> Back out "Assign invalidation part on server side for Impress."

- browser/html/cool.html.m4
- browser/js/global.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
Once an integration would provide the signing certificate/key, it's
necessary to configure this on the user settings page of the
integration. Given that document signing is not relevant for many
deployments, the integration may want to hide this.
The way this is done for the Zotero case is that coolwsd has a flag
(enabled by default, the sysadmin can disable it), and then the
/hosting/capabilities JSON informs the integration if this COOL instance
supports document signing or not.
Fix the problem by adding a similar flag for document signing.
At the moment this influences our capabilities JSON & disables the
JS UI buttons; the JS UI button doesn't check if the view actually
provides a signing certificate yet.
Change-Id: …
> cool#9992 doc sign: add a setting to be able to disable this

- browser/src/slideshow/LayerRenderer.ts
Refactored LayerRendererGl to utilize RenderContextGl, replacing repeated functions to reduce code duplication and improve maintainability.
Change-Id: I929ca8bb65897e98a10b4efa92c068a257cd9e16
* Resolves: # 
> Slideshow: Use RenderContextGl for LayerRendererGl

- browser/src/map/Map.js
Or it may cause JS errors if user doesn't have a name.
Guest users may cause this issue. I couldn't reproduce the issue, adding the check reading the logs.
Change-Id: I1b9ab5b90e95b99712d6d5acd8e05b2f15190f99
* Resolves: # 
> Add a check when getting view name.

- browser/css/menubar.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.UIManager.js
- browser/src/map/Map.js
- Fix typos in comment messages & correct the wrong comment message with right meaningful messages
- Dynamically set CSS content for saving and saved states
- Add padding-inline-start to retain margin when logo is removed
- fix: Set line-height to 0 to prevent cropping of "Saving" text
> Follow up pr for 10144 (Save notification )

- browser/src/control/Control.JSDialog.js
Accessibility: Set focus on the first or selected tab in dialogs with tab
- Implemented a recursive search for the 'tabcontrol' type within the dialog object.
- Updated the function to return the target element to focus on, or null if no tabcontrol is found.
- Removed direct focus call from the function, allowing for more flexible handling of the returned element.
To reproduce this issue
-  Open "Table of Content" dialog in ODT file
- then try to move focus using "Right Arrow key"
- you will see focus is inside the Tab content and not on the Tab itself
- Expected should be to have focus on Tab in case of dialog with tab control
> Fix : Automatic focus jump during tab navigation

- browser/src/control/Control.FormulaBarJSDialog.js
- browser/src/control/Control.IdleHandler.ts
- browser/src/layer/marker/TextInput.js
This fixes the main problem which is data loss when we
exit without confirmation of a cell content but also
problem with losing focus from formulabar on some actions.
Especially when we click outside iframe - we lost
focus on formulabar but we were still catching input to
it on the server side.
> calc: save edited cell on exit

- test/integration-http-server.cpp
Added filter = contentcontrol to the test, so new updates will not change the extracted result.
Change-Id: Ie090147940e3c2b1994ffa2106d12546f4b45c67
* Resolves: # 
> DocStructure: fix extract test

- .gitpod-files/coolwsd-gitpod.xml
- Makefile.am
- browser/test/bootstrap.js
- coolwsd.xml.in
- cypress_test/Makefile.am
- test/run_unit.sh.in
- wsd/COOLWSD.cpp
During development using of Linux Namespaces was an experimental feature. Therefore it was disabled in production builds, and enabled only in development edition (CODE). Later, as it matured, it was on by default. This change caused problems with upgrade, because when a user had mount_namespaces=false in /etc/coolwsd/coolwsd.xml, it remained false. Probably it is better to get rid of this configuration option, and try to use Linux Namespaces unconditionally. If it's not possible, the code will fall back to use coolforkit-caps and coolmount that require capabilities. And of course if these are not installed (coolwsd-deprecated package), a log entry will be made. It is assumed that this is a rare case. It is also assumed that nobody would want to disable using of Linux Namespaces, when the …
> remove mount_namespaces config option

- common/FileUtil.cpp
- common/JailUtil.cpp
- common/Log.cpp
- common/Png.hpp
- common/SigUtil.cpp
- common/SigUtil.hpp
- common/Unit.cpp
- common/Util-desktop.cpp
- common/Util-mobile.cpp
- common/Util.hpp
- kit/ChildSession.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/KitWebSocket.cpp
- kit/SetupKitEnvironment.hpp
- net/FakeSocket.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- test/UnitWOPICrashModified.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/RequestDetails.cpp
- wsd/Storage.cpp
- wsd: restore performance regression due to isMobileApp
- wsd: remove ifdef MOBILEAPP
- wsd: remove ifdef MOBILEAPP
- wsd: header cleanup
- wsd: remove ifdef MOBILEAPP
> Fewer MOBILEAPP Directive

- common/FileUtil.cpp
- common/FileUtil.hpp
- kit/Kit.cpp
- test/WopiProofTests.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/COOLWSD.cpp
- wsd: avoid unnecessary temporary strings
- wsd: support reading unknown-sized files
- wsd: dump the smaps summary on USR1
> Dump Memory Usage with SIGUSR1

- browser/src/canvas/sections/CommentListSection.ts
it _leaflet_pos is not defined, then, probably the comment position is not calculated yet, so it cannot be used.
In this case we dont know yet how much space is between 2 comments. So in this case we dont make the comment bigger yet, probably it will be calculated a bit later.
Change-Id: I103125194bdf20b5b7d43a53b3381cc86fd03cac
* Resolves: # 
> comments: fix undefined _leaflet_pos

- common/SigUtil.hpp
fix build with clang 15 after commit e4b51310e268aa05ad83ea6ed79e92885b783eb6 wsd: header cleanup
In file included from common/SigUtil.cpp:14:
./common/SigUtil.hpp:117:50: error: unknown type name 'uint32_t'
extern "C" { typedef void (*SigChildHandler)(uint32_t); }
^
> clang: fix unknown uint32_t error

- browser/css/notebookbar.css
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
Resolves Styles preview box width depand on window size #2210
No need to set hard coded width. Better to set it to a portion of the
viewport's width. Also make sure the grid is tidier by actually using
a grid and not inline-flex and setting the proper width and height
of each cell.
Note if more buttons are added to the Home tab then that 35vw should
be updated accordingly
Change-Id: Ifd8696caf0d9b49fcb2c6929ea5f23505d7cff42
> Make Styles preview box width flexible

- browser/src/layer/tile/CalcTileLayer.js
Previously we sent our UI_Defaults onscreen keyboard information to core rather than our guess, which could result in inconsistent scenarios where we didn't activate coreside onscreen keyboard features (like not preventing keyboard close on enter in calc) but did activate our onscreen keyboard features.
Unfortunately, one of these situations was also the mobile app - oops!
By using our guess, we make sure that we always send the right thing, whether a UI_Default is provided or not.
Change-Id: I58d131f46fa02eeee63d24b615d08b902d0e22c9
* Resolves: # 
> fix(mobile): Send onscreen keyboard guess to core

- browser/src/control/Control.Header.ts
- After selecting a row or column, the focus shifts from the 'map' to the 'document'
- Keyboard shortcuts are intended to work specifically within the 'map' area
- This patch ensures that focus returns to the 'map' after selection, allowing keyboard shortcuts to function correctly
This fix resolves the issue where shortcuts would stop working after a row/column selection.
To check this fix :
- Go to ods file
- click on row/column header
- Press CTRL + B 
Without this patch, nothing will happen. Expected behavior should be to make all text bold
Change-Id: Ic5265a7d3eced20e4f005aa1ce50acbc87946b4f
* Resolves: # 
> Fix keyboard shortcuts not working after row/column selection in Calc

- common/Session.cpp
- common/Session.hpp
Change-Id: I04eba16400825869522012eb16ba033200effeaa
* Resolves: #7935
1. disableSpellCheckIfReadOnly Method:
- Created a private method called disableSpellCheckIfReadOnly that updates the spellOnline property based on the isReadOnly status.
- This method sets spellOnline to "false" if _isReadOnly is true, and keeps the current value otherwise.
- Called disableSpellCheckIfReadOnly at the end of the parseDocOptions method to ensure spellOnline is set correctly based on the initial document options.
> Added method to disable spell check if document is read-only

- fuzzer/HttpEcho.cpp
Probably after commit 24c4af9f8bac7e318543f1f51ab57f32945d130b (we have
the DNS info at StreamSocket ctor time that its localhost, 2024-10-10).
Change-Id: I81fb60f5471a81a4cc276f5879d4b84d48b873e0
> httpecho_fuzzer: fix build

- common/Rectangle.hpp
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/Kit.cpp
- kit/KitQueue.cpp
- kit/KitQueue.hpp
- kit/TestStubs.cpp
- wsd/ClientSession.cpp
- wsd/TileDesc.hpp
* Resolves: #9989
Tile Intersection: Use a Rectangle/AABBox for Tile/TileCombined to reduce complexity
Use consolidated Rectangle Intersection on ChildSession/ClientSession's isTileInsideVisibleArea
Previous implementation left out the tile boundaries intersecting with the _clientVisibleArea, which is now fixed.
Use an AABBox in TileCombined for ChildSession::isTileInsideVisibleArea(), reducing complexity in Document::drainQueue
> Tile Intersection: Use a Rectangle/AABBox for Tile/TileCombined to reduce complexity

- kit/Kit.cpp
- test/UnitLoad.cpp
Generate a /s/token style share link in Nextcloud, open that link in
incognito window, the document fails to load.
The guest user has no private infos, but instead of {}, we get a [],
which is well-formed JSON and we used to tolerate that.
Fix the problem by assuming an empty object when the JSON is not a
dictionary but something else.
Ideally nextcloud would not send us such JSON, but we used to tolerate
that previously, so first fix this here.
Change-Id: Ie1b1a5db796c351f383dcfa8d44b003c84810d0e
> cool#10220 doc sign: don't assume that user private data is a dict json

- .github/workflows/contributor_fetch.yml
Change-Id: Ia3aad6d977e36e6a786d5adf4f23a60f2c294373
* Resolves: # 
> Secret name can not start with "GITHUB"

- net/NetUtil.cpp
- net/Socket.hpp
The missing functions are in #if !MOBILEAPP blocks so used the same for iOS. This PR mabye should be tested on Android.
> Minor fixes for iOS build breakages

- browser/src/layer/tile/CalcTileLayer.js
On commit "browser: fix freeze row/column panes"
fe45327ba0e8b330dfa5ea99e6247ed7c9abefad the type of FreezePanesColumn
and FreezePanesRow was changed from Int32 to Point. Since then, calls
trying to set the frozen panes with this commands sending an index fail,
setting the index to 1.
This change allows again a way to set them passing only an index of type
Int32.
Change-Id: I9837586f6c531bf885f24b5913af9a372dc0f5a1
> sc: change how .uno:FreezePanesColumn/Row get the index

- common/JailUtil.cpp
same as:
commit 852e8545af3f1807ff6619fe52a922f35bbd9da4
Author:     Caolán McNamara <caolan.mcnamara@collabora.com>
AuthorDate: Mon Jul 22 13:07:17 2024 +0100
mount an up to date copy of etc if systemplate's etc is out of date
but also do this is the out of date systemplate dynamic files are in a ro systemplate.
reproducible in make run with
rm -f systemplate/etc/hosts && chmod a-w systemplate
where the earlier change only works for
rm -f systemplate/etc/hosts && chmod a-w systemplate/etc
Change-Id: I054d844f15456f189d19cb204fd80541f827dcbf
* Resolves: # 
> mount an up to date copy of etc if ro systemplate's etc is out of date

- wsd/TileDesc.hpp
Change-Id: I84d16f3911d27e97cf613e0e434fe53dc6aa963d
* Resolves: #9989
> TileCombined::toAABBox(): Return const reference, avoiding copy

- common/Unit.cpp
- common/Unit.hpp
- net/Socket.cpp
- net/Socket.hpp
* Resolves: #10228 
- Resolve UnitBase's _socketPoll data race via its socketPoll()
- Resolve UnitBase's UnitWSD::get() data-race
> UT Stability: Resolve UnitBase data races

- .github/workflows/codeql-analysis.yml
Change-Id: I73fea30cc75a2a9ff2a3890c4c8e0ae2103c5a81
* Resolves: # 
It makes the CI a bit faster. libreoffice build deps are huge, and unnecessary. We use pre-built core assets.
> CI: I do not think we need libreoffice build deps

- browser/src/control/Control.Sidebar.ts
Execute 'make run' with a debug core, open e.g. writer-edit.fodt, and
notice this warning:
warn:lok:17376:17363:desktop/source/lib/init.cxx:283: lok exception 'Failed to dispatch undefined'
Seems it's harmless, but the JS side should never send such a command on
the websocket.
It turns out sometimes Sidebar.onSidebar() calls Sidebar.changeDeck()
with an undefined parameter, so guard for this.
Change-Id: Iacdad1392bc53ce9427fbb90863c8b58fc1fa3df
> sidebar: avoid dispatching an undefined UNO command

- common/Unit.hpp
- common/Util.hpp
- kit/Kit.cpp
- net/DelaySocket.cpp
- net/HttpRequest.hpp
- net/NetUtil.hpp
- net/ServerSocket.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/SslSocket.hpp
- net/WebSocketHandler.hpp
- test/HttpRequestTests.cpp
- test/Makefile.am
- test/UnitPerf.cpp
- test/UnitTimeoutBase.hpp
- test/UnitTimeoutConnections.cpp
- test/UnitTimeoutNone.cpp
- test/UnitTimeoutSocket.cpp
- test/UnitTimeoutWSPing.cpp
- test/WebSocketSession.hpp
- tools/Stress.cpp
- tools/WebSocketDump.cpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/ProxyProtocol.hpp
* Resolves: #9833
- ProtocolHandlerInterface::checkTimeout(..)
is now called via StreamSocket::checkRemoval()
to ensure tests even w/o input data (was: handlePoll())
- ProtocolHandlerInterface::checkTimeout(..)
- Add bool return value: true -> shutdown connection, caller shall stop processing
- Implemented for http::Session
- Timeout (30s) net::Defaults::HTTPTimeout with missing response
- Implemented for WebSocketHandler
- Timeout (2s = net::Defaults::WSPingTimeout)
after missing WS native frame ping/pong (server only)
- StreamSocket -> Socket (properties moved)
- bytes sent/received
- closed state
- Socket (added properties)
- creation- and last-seen -time
- socket type and port
- checkRemoval(..)
- called directly from SocketPoll::poll()
- only for IPv4/v6 …
> Handle limited open Connections due to keepalive connections

- browser/src/layer/tile/ImpressTileLayer.js
Reproducer:
* Open an impress file.
* Switch to notes view.
* Edit the note of page.
* Don't remove focus from note object (rectangle).
* Try to switch back to normal view.
We still send the notes view UI command because when user clicked on the note rectangle, context changed again. Now our UI thinks that we are in different mode. We will set our internal selectedMode variable selectively.
Change-Id: Iee73a1bb16aed7c19190ef15592910e39a056beb
* Resolves: # 
> Fix switching from notes view to normal view issue.

- browser/Makefile.am
- browser/css/jquery-ui-lightness.css
- browser/css/jsdialogs.css
- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.AutoFillPreviewTooltip.ts
- browser/src/control/Control.ContextMenu.js
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ice62a3eb891a1653b5ec6ad5b10efe2fac0e914f
* Resolves: # 
- show cell value previews in a popup while using autofill feature.
- this will allow users to see what value will be filled in the current cell in advance.
- add AutoFillPreviewTooltip class
- requires: https://gerrit.libreoffice.org/c/core/+/172589 (merged - 24.04 - master)
- requires: https://gerrit.libreoffice.org/c/core/+/174502 (merged - 24.04)
> introduce autofill preview tooltip

- browser/css/btns.css
- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/css/jssidebar.css
- browser/css/menubar.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
- browser/src/control/jsdialog/Widget.ColorPickerButton.js
- cypress_test/integration_tests/desktop/impress/delete_objects_spec.js
Change-Id: I4f0474e02411ada5547c8c2f23dda22cb4433557
* Resolves: #8566
This is my proposal for UI splitting the buttons in 2 parts.
I hope I didn't take too much liberty with the design ^^
> feat(UI): Improve split button styling

- common/Unit.hpp
- test/UnitTimeoutConnections.cpp
- test/UnitTimeoutNone.cpp
- test/UnitTimeoutSocket.cpp
- test/UnitTimeoutWSPing.cpp
- wsd/COOLWSD.cpp
Change-Id: I1a3b433cfadbf8d4da1be4bb72bddb40231e27c5
Avoid overloading virtual function `UnitWSD::configure`,
allowing to use compiler flag -Woverloaded-virtual
> Rename UnitWSD::config{ure -> Net}, to allow -Woverloaded-virtual

- browser/src/control/Control.UIManager.js
- Previously, when attempting to open a presentation file using the `&startPresentation=true` parameter, the presentation would not load, leading to either a browser console error or a direct error from Collabora.
-  This issue was resolved by dispatching the 'presentation' event only after the document has fully loaded, preventing premature attempts to start the presentation.
Change-Id: Ib066a28c0aff0ed4f979b5d6d463bfd900519730
* Resolves: #10198 
> fix: ensure presentation starts only after document is fully loaded

- browser/src/control/Control.UIManager.js
- kit/Kit.cpp
Have no sign keys configured, open a document, go to the File tab on the
notebookbar, the signature button clutters the UI but it provides no
actual functionality.
The JS UI already got the private user info in Control.UIManager.js
onUpdateViews(), where we initialize the Zotero UI.
Do something similar for the sign UI: keep it enabled by default, but
once we learn about the private user info and it has no signing
key/cert, then hide the button.
The notebookbar gets re-initialized from time to time, so best to do
this via showButton(), which can remember which buttons are shown/hidden
and gets maintained even after a rebuild of the notebookbar. (The
postmessage API uses the same code to hide a button from an
integration.)
Change-Id: …
> cool#9992 doc sign: hide sign button when user pref doesn't provide cert or key

- browser/src/map/Clipboard.js
Right now if a user selects text from a comment and tries to copy it,
the copy command goes to the document instead. This change allows the
user to copy from the content of a comment.
Change-Id: I9dc9198fd28f5a723c454444644f361bc31a4c49
> let the user copy text from a comment

- configure.ac
-Wall only enables -Woverloaded-virtual=1 but adding an explicit -Woverloaded-virtual enables level 2
Change-Id: I76ff5d752131a04e8f2c5b4001edf81680510efe
* Resolves: # 
> add an explicit -Woverloaded-virtual flag

- browser/css/jsdialogs.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
it was broken after PR:
commit db10c453e95f732d85c489fe8da8708cec0ad09c
fix(UI): set button size with a CSS variable
related to: https://github.com/CollaboraOnline/online/pull/10027
> css: fix icons size after split button rework

- THIRDPARTYLICENSES
- browser/Makefile.am
- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/css/cool.css
- browser/css/mobilewizard.css
- browser/html/debug.html
- browser/npm-shrinkwrap.json.in
- browser/package.json
- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- browser/src/canvas/sections/ContentControlSection.ts
- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.FormulaAutoCompletePopup.ts
- browser/src/control/Control.FormulaUsagePopup.ts
- browser/src/control/Control.Mention.ts
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.MultilineEdit.js
- browser/src/control/jsdialog/Widget.TreeView.js
- browser/src/layer/marker/TextInput.js
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/mobile/calc/annotation_spec.js
- cypress_test/integration_tests/mobile/impress/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
> implement comment at-mentions

- README.md
For contributors to mobile, it's nice to mention the process around the co-24.04-mobile branch in relation to master and co-24.04. I've opted not to use the platform-specific READMEs as (1) it applies to both platforms and (2) those aren't very good and probably need to be rewritten more generally
* Resolves: # 
> docs(mobile): Mention co-24.04-mobile in README

- browser/css/jsdialogs.css
This is a follow up of 3e8edc705578a624aaec22c008801784522e8e47
It fixes the cropped combo boxes in the status bar
Change-Id: I05ed4778c5663dfa92551a23f2383ea5aafd023b
> Dropdowns: Don't force any specific width

- fuzzer/HttpEcho.cpp
Probably missed in commit 4499e42b762ef3f96fc20a377cf7d663b48305d2
(cool#9833: Adding net::Defaults singleton for limit configurations
(timeout), 2024-10-16).
Change-Id: I01b1b7eb612b0b3332446e5399af94a829b1bd7b
> fuzzer, httpecho: fix build

- browser/css/toolbar.css
- browser/html/cool.html.m4
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.StatusBar.js
- browser/src/control/Toolbar.js
- browser/src/control/jsdialog/Widget.HTMLContent.ts
- browser/src/map/Map.js
- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
Change-Id: I04891ce23e0f250243d9453bfecb0570683cae7a
- adds a last modification setting as well in coolwsd.xml so that it
displays the last modified after a certain delay
- moves the last modification text to the bottom as well as adds a new
text related to the document status (if saved)
Change-Id: I3b21274ed7557b37789f63751e0b9db583469355
* Resolves: # 
> browser: add last modification and document status at the bottom

- browser/src/canvas/sections/CommentListSection.ts
if its writer then just send the comments as html, not text and html
Change-Id: Ia3e5a20cb4c82474cff951753a6a5fcc78992f3e
* Resolves: # 
> minimize data sent for writer rich text comments

- browser/Makefile.am
- browser/images/lc_presenterconsole.svg
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.UIManager.js
- browser/src/docdispatcher.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideCache.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/Transition2d.ts
- browser/src/slideshow/Transition3d.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
- browser/src/slideshow/transition3d/SimpleTransition.ts
- **browser: slideshow: simplify notify blocked popup**
- **browser: slideshow: simplify 'onSlideShowInfo'**
- **browser: slideshow: add options parameter to SlideShowPresenter**
- **browser: slideshow: add options parameters to not start presentation**
- **browser: slideshow: change to public '_startSlide' access**
- **browser: slideshow: add 'PresenterConsole' class**
- **browser: slideshow: avoid unhandled excpetions requestedSlideHash**
> Presenter Console

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/desktop/writer/navigator_spec.js
If any JSDialog action is sent - it means user did interaction with dialog / widget / button what should exit follow other user mode. We are now interested in our area of work.
Fixes #10282 10282
> writer: when navigator is used, follow the cursor - fixes #10282

- test/DeltaTests.cpp
the master commit:
commit 9d49ea31131972bc8e1581a353441230850a78c2
CommitDate: Tue Oct 15 06:51:14 2024 +0300
Add viewMode property to TileLocation to ensure that correct delta is replaced with the new one.
isn't in co-24, so the test of:
commit 0e7d356c960afdf51f0db4b85eda7352472a54ae
CommitDate: Sat Oct 19 18:50:26 2024 +0100
deltas: test random image - to check we have space allocation right
needs to be adjusted to account for that
Change-Id: If7a54fac69f34ab3fa75fee6fe67aea42d44c669
* Resolves: # 
> fix co-24.04 build

- browser/html/cool.html.m4
- browser/js/global.js
- browser/src/control/Control.StatusBar.js
- browser/test/load.js
- coolwsd.xml.in
- wsd/COOLWSD.cpp
- wsd/FileServer.cpp
user_interface.statusbar_save_indicator can be used to hide statusbar indicator of the last save. By default it is visible if entry is missing.
followup for: https://github.com/CollaboraOnline/online/pull/4531/files
> statusbar save indicator: add coolwsd setting

- browser/src/layer/tile/CanvasTileLayer.js
Blind fix for:
`bundle.js:19150 Uncaught TypeError: Cannot read properties of null (reading 'parentElement')`
> Fix TypeError in _syncTilePanePos

- net/Socket.hpp
Change-Id: I57d46e0428905137e05d34dad450fea1d6a0f127
* Resolves: #9833
Regression injected with commit 0579ee81c709865ea420c2d70dcc443bdf69de1a of PR https://github.com/CollaboraOnline/online/pull/9916
Original behavior was to do nothing in Socket::shutdown(), while the commit in question did setClosed() leading to an eventual socket close within SocketPoll::poll().
The latter causes an error within system ::ppoll().
> Fix regression in `Socket::shutdown()` when having `_noShutdown` set

- browser/src/docstatefunctions.js
- browser/src/layer/tile/CanvasTileLayer.js
so we don't skip cases when there is no scrolling using eg. mouse. this fixes problem in writer:
1. open long, multi page document
2. search for word which exists on every page
3. search using "next" button until you scroll to other page - works
4. scroll using mouse to the top
5. click before first word to put cursors there
6. click multiple times "next" button
result: cursor no longer shown when going to next page
expected: following the cursor all the time
> user following: update on cursor invalidation

- net/Socket.cpp
- net/Socket.hpp
* Resolves: #9833
Originally contained PR #10270 fixing a regression caused by PR #9916, leading to 100% CPU utilization on idle,
due to WebSocketHandler's checkTimeout not being called and hence no ping sent.
This PR contains remaining cleanups related to PR #9916
> Cleanup Socket/SocketPoll 'Limited open Connections' Changes

- browser/css/mobilewizard.css
- Adjusted the margin value for checkbox in mobile view
- styling should be same as we have for 'radio button'
Before: 
After:
Change-Id: I2d8697269b73a018cbf5976b794cd9a0f7418de9
* Resolves: # 
> Fix: checkbox position not good in mobile view

- browser/src/map/Clipboard.js
- now text is pasted in combobox input for example fonts, addressinput filed instead of in the document
Change-Id: Idb2ffa1e6a77d8b14fe43a71e2ed728d4d31a959
> fix: paste happens in document instead of combobox input

- wsd/AdminModel.cpp
- wsd/protocol.txt
Change-Id: I1f6432a3872e5d0dc91cb47e25e0d306402e88f0
> admin: add dockey to adddoc message

- common/JsonUtil.hpp
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/Kit.cpp
core.git commit d48264d51891d81f77fcfd77766e1d34ec17412b (cool#9992 lok
doc sign: allow late-init of the sign cert, 2024-10-22) allows sending
the sign key/cert only when actually signing.
Also commit 7998ba53a533be83ce8fed60cabc44b6457543c4 (fix uno:Signature
cypress test, etc., 2024-10-23) already started to annotate
.uno:Signature with sign parameters.
Complete this move by:
1) Extracting the .uno:Signature handling code to a separate function,
since ChildSession::_handleInput() is large enough already.
2) Poco::Dynamic::Var::extract() can throw an exception if the user
private info is not an object (but is e.g. a list), guard against
that.
3) Stop sending the sign cert/key in Document::makeRenderParams().
Change-Id: …
> cool#9992 doc sign: move sign key/cert init from doc init to sign dispatch

- net/Socket.hpp
./net/Socket.hpp: In member function ‘int StreamSocket::getSendBufferCapacity() const’: ./net/Socket.hpp:1429:20: error: ‘INT_MAX’ was not declared in this scope
1429 |             return INT_MAX; // We want to always send a single record in one go
|                    ^~~~~~~
./net/Socket.hpp:1429:20: note: ‘INT_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
Change-Id: I94a8b9cc578a9a59eaa74351965f49fea43c36e6
* Resolves: # 
> include climits for INT_MAX

- common/SigUtil.hpp
fix build with clang 15 after commit e4b51310e268aa05ad83ea6ed79e92885b783eb6 wsd: header cleanup
In file included from common/SigUtil.cpp:14:
./common/SigUtil.hpp:117:50: error: unknown type name 'uint32_t'
extern "C" { typedef void (*SigChildHandler)(uint32_t); }
^
Change-Id: I42020a2049e69693160eb92f49e7c89f5ba94a96
* Resolves: # 
> Backport: clang: fix unknown uint32_t error

- common/Util.cpp
- common/Util.hpp
- kit/Kit.cpp
- net/Socket.hpp
- test/TileCacheTests.cpp
- test/UnitLargePaste.cpp
- test/UtilTests.cpp
- wsd/ClientSession.cpp
- wsd: constexpr function's return type 'void' is not a literal type
- wsd: better Util::isMobileApp()
- wsd: Util::encodeId() now supports streaming
- wsd: remove unused Util::UniqueId()
- wsd: inline and optimize Util::encodeId()
- wsd: hexFromByte can be constexpr
- wsd: optimize encodeId
> Misc Refactoring

- browser/src/layer/tile/CalcTileLayer.js
map size and position are given in browser pixels and not core pixels.
Change-Id: I7dacb8324df822dc9673b64b7f34596c4fe82871
> calc: scroll fix convert pixels to twips

- browser/html/cool.html.m4
- browser/src/control/Control.UIManager.js
The #spreadsheet-toolbar element shows up in every doc type at
the loading time. This means that the user sees a flash at the bottom
and if the integrator has customized COOL via CSS var etc the color of
the bar or its border color then that flash stands out even more.
Change-Id: Ie325bfb841f5aff2a1cdc9711610fa747b6e1d7b
> Don't show spreadsheet-toolbar in other docType

- kubernetes/helm/collabora-online/templates/deployment.yaml
- kubernetes/helm/collabora-online/values.yaml
* Resolves: https://github.com/CollaboraOnline/online/issues/10020
Allows to configure wopi proof keys when installing Collabroa via the Helm Chart.
I tested it using the oCIS deployment example that has Collabora: https://github.com/owncloud/ocis-charts/blob/91b8eb2b6fa3a1e7d7ee7687c732b255b92c3f0c/deployments/ocis-office/helmfile.yaml
I modified this helmfile a little bit for testing:
```diff
- name: collabora
namespace: collabora
-    chart: collabora/collabora-online
-    version: 1.1.23
+    # chart: collabora/collabora-online
+    chart: /home/wkloucek/Projects/github.com/CollaboraOnline/online/kubernetes/helm/collabora-online
+    # version: 1.1.23
values:
- collabora:
aliasgroups:
- host: "wopi-collabora.kube.owncloud.test" # needed because we connect via …
```
> add option to the helm chart to configure wopi proof keys

- common/Util.cpp
- cypress_test/integration_tests/multiuser/calc/sheet_operations_spec.js
We resized the hash to 8 characters, which incidentally worked when our repo was smaller. Now short hash is 10 chars long.
Change-Id: Ib737e9c011488fbf085cfc2be3dd2a9b6e6daa0b
* Resolves: #10316 
**Note:** this bug does not effect official CODE/COOL packages. So the impact is small, fortunately. I checked, and on the machine where we build packages, `git log -1 --format=%h` produces 8 character long hashes. Only on my dev machine I saw 10 character long hashes.
> cool#10316 fix server version mismatch warning

- net/Socket.cpp
We lock this elsewhere when writing. Seems odd that we don't lock when reading.
Address Sanitizer reports:
```
READ of size 4 at 0x60300016be38 thread T7 (docbroker_001)
#0 0x1ab5b94 in SocketPoll::wakeupWorld() builddir/online/net/Socket.cpp:764:16
#1 0x14cc7e9 in DocumentBroker::DocumentBrokerPoll::pollingThread() builddir/online/wsd/DocumentBroker.cpp:153:9
#2 0x1a9beae in SocketPoll::pollingThreadEntry() builddir/online/net/Socket.cpp:477:9
#3 0x1b6fb24 in void std::__invoke_impl<void, void (SocketPoll::*)(), SocketPoll*>(std::__invoke_memfun_deref, void (SocketPoll::*&&)(), SocketPoll*&&) /opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/../../../../include/c++/12/bits/invoke.h:74:14
#4 0x1b6f694 in std::__invoke_result<void (SocketPoll::*)(), SocketPoll*>::type …
```
> lock getWakeupsArray for reading

- kit/Kit.cpp
The combination of a year+ old core, and a modern coolforkit can initialize and startup, but then fails subsequently in hard to diagnose ways, so look for badness and log it early.
Change-Id: I9b9c94997afcc8faa8174b7339483f832ec87dd6
* Resolves: # 
> Kit versions: log version on start, and also check for known badness.

- browser/src/canvas/sections/CommentSection.ts
Comment indicator is changed in core d395b42cdf3ef517d215dee905e5ccf2ae73b2b8 We draw that indicator on online side separately. Now we see the same indicator on online too.
Change-Id: I2c640f4850473724e8a14e75fa7d3c00f76d4e9e
* Resolves: #7130
> Shows calc comment indicator as a triangle.

- browser/src/map/handler/Map.Keyboard.js
- To reproduce the issue:
1. Open the attached .odp file
2. Go the second or third slide
3. Open the slide Properties dialog. Layout > Slide Properties
4. Open the Color Tab and try to delete the Hex color text.
- Problem: 
- If we change HEX color of any slide property, then by default if deletes the current selected slide.
- which should not be happening if focus is inside dialog
- Solution: 
- Added a check which will prevent the deletion if dialog is in open state
Change-Id: I9e090fd44e6ffedeb8097d7564d8aeadc57b2eb9
* Resolves: # 
> Fix: Prevent slide deletion when using Delete/Backspace in Hex color input with dialog open

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/slideshow/PresenterConsole.js
Both for light and dark mode. In here I opted to use a dark tint on both and later on - depending on the user feedback - we can switch so something lighter for the light mode
Change-Id: I31eed3b0bac327ac3db365f6fdf79405537058bb
* Resolves: # 
> Presenter Console: Add background and text color

- cypress_test/integration_tests/common/mobile_helper.js
It would not work anyway, because vex dialogs are not used any more.
Change-Id: I6bdd1d5b72823106d064b18dafc7802cd8518e9f
> cypress: remove unused executeCopyFromContextMenu

- common/Unit.hpp
- kit/Kit.cpp
- net/HttpRequest.hpp
- net/NetUtil.hpp
- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- test/UnitPerf.cpp
- test/UnitTimeoutConnections.cpp
- test/UnitTimeoutNone.cpp
- test/UnitTimeoutWSPing.cpp
- tools/Stress.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
* Resolves: #9833  refining PR #9916, partially replacing PR #10355
net::Defaults was a singleton, becoming a global, keeping untouched constexpr in SocketPoll.
- Reverts commit 4499e42b762ef3f96fc20a377cf7d663b48305d2
- SocketPoll::DefaultPollTimeoutMicroS is maintained original
- net::Defaults is a global instance w/ default values
- inactivityTimeout 3600s
- instead of using DefaultPollTimeoutMicroS for {idle->inactivity) checkRemoval
- wsPingAvgTimeout 12s
- wsPingInterval 18s
- maxTCPConnections 200000 (arbitrary value)
- for limiting connections in SocketPoll::poll,
instead of using the session count
> net::Defaults: Revert and re-apply revised code

- browser/src/docstatefunctions.js
- it happens when download failed with cluster configuration error
Change-Id: Ifc2fbc875f378d943cbb932b98c198aba773a48f
> fix: redundant 'Download failed' string in snackbar

- net/NetUtil.hpp
- net/ServerSocket.hpp
- net/Socket.cpp
- net/Socket.hpp
- test/UnitTimeoutBase.hpp
- test/UnitTimeoutConnections.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
* Resolves: #9833  refining PR #9916, partially replacing PR #10355
This PR is on top of #10366 !
Reimplementation of commit 80246f7ac1140257d14162504d3550909d6ba681 (post revert).
Adding external TCP connection limit to server-side TCP IPv4/IPv6 Sockets
- Counted at StreamSocket ctor
- Only limits TCP connections for server-side IPv4 or IPv6 TCP connections.
- Rejected at ServerSocker::handlePoll
- If exceeding net::Defaults.maxExtConnections, socket object and hence connection is dropped
- revise net::Defaults.maxTCPConnections to match actual system settings
- earmarked for subsequent PR
> Implement MaxConnection Limit (2)

- wsd/COOLWSD.cpp
- regression from 1b3218df0466a59fd1e9a8df72d97ede6448425e
- Steps to reproduce/test:
1. create env variable `export aliasgroup1=http://test.integrator,http://test.integrator1,http://test.integrator2`
2. Run COOL binary with `--use-env-vars`
3. You can either search for 'Adding trusted WOPIHost' in coolwsd logs and make sure all the aliases and hosts are allowed or you can add multiple entries to your `/etc/hosts` that points to same WOPIHost instance
Change-Id: I16785458724c81b681b8ebb979c119af5db9b808
* Resolves: #7730
> wsd: fix: failed to pass aliases using `--use-env-vars` option

- browser/src/layer/tile/CanvasTileLayer.js
- Fixes the following case:
1. Create 3 Named Ranges: testrange1, testrange111, testrange11111
2. Try to autocomplete `=SUM(test`
3. Autocomplete `test` with `testrange1`
4. Now popup will show up because there are `testrange111`, `testrange1111` which can be autocompleted if you select one of those it will autocomplete with `testrange1range111` which is not correct
Change-Id: I81cf0f8f3ebf23e275561f16301ac775e7d00a9f
> calc: fix: autocomplete formula edge case 

- net/Socket.hpp
Now that we re-use connections, we have revealed
a corner-case that causes some noise.
Remote connections might not retain HTTP
connections past their immediate purpose and
rudely reset the connection after a certain
timeout.
Apache has such a short timeout of between 5
and 15 seconds, by default. And, it seems,
HA Proxy is similar. When the connection is
not reused by the client within the timeout,
it is simply closed.
This wakes us up and we get revents with
POLLIN, POLLHUP, and POLLERR (that is, 0x19).
This patch handles this case by recognizing
that we got POLLHUP already and the socket
is closed before doing read(2). That is,
read(2) *is* expected to fail with ECONNRESET.
We handle this case specifically by avoiding
reporting it as an error. We will still log
an error if we get …
> wsd: reduce noise while draining with ECONNRESET

- kit/ChildSession.cpp
Trying to create signed PDFs during ODT->PDF conversion, a signature is
created, but it's not valid. The first trouble noticed while
investigating is that the load option we get is like this:
debug:666:660: doc_saveAs: pFilterOptions is '{"SignPDF":{"type":"boolean","value":"true"},"SignCertificateCaPem":{"type":"string","value":"-----BEGINCERTIFICATE-----
While this should be '-----BEGIN CERTIFICATE-----', since the syntax is
"load ... [options=<options>]".
Fix the problem in ChildSession::saveAs(), where a space was lost while
"load ... options=foo bar" was tokenized as "load", "...", "options=foo"
and "bar", and later we constructed <options> as "foobar", not "foo
bar".
Change-Id: Ibadcb3218d8776191193ca13788cfca4a8d1e11d
> cool#9992 doc sign: fix handling of saveas options containing spaces

- common/Log.cpp
In some cases it's benefitial to disable buffered-
logging and flush after each entry is generated.
We already have an unbuffered logger and a
property, called 'flush', already exists and
is used by Poco to also disable buffering its
file-logger.
We leverage this property to disable buffering
in both the console logger (this patch), as well
as in Poco's file-logger (existing functionality).
Change-Id: I5e3b75e66f82a8a5df57901ef4f6c8264aee3565
> wsd: use the 'flush' logging property to disable buffering

- common/Unit.cpp
- common/Unit.hpp
- configure.ac
- coolwsd.xml.in
- net/Socket.cpp
- test/HttpRequestTests.cpp
- wsd/COOLWSD.cpp
Hiding the server signature reduces the likelihood of targeted attacks by making it harder for attackers to identify the server's configuration.
In built-in default configuration security.server_signature is set to false. It is also set to false in coolwsd.xml packaged with production builds. HTTP response header is like:
Server: COOLWSD HTTP Server
In debug mode security.server_signature is set to true in coolwsd.xml. HTTP response header is like:
Server: COOLWSD HTTP Server 24.04.9.1
Change-Id: Ie23c2dbc1514e46e2942f558ada2e27d0f108bea
> Option to hide server signature in HTTP response

- net/Socket.hpp
- wsd/ClientRequestDispatcher.cpp
from Socket::createSocket during construction and init calls setNoDelay
Socket::Socket
...
, _fd(createSocket(type))
...
{
init()
}
cid#427983 Improper use of negative value
Change-Id: Ie1d197394f77071ac023485f291cd4626a08a2df
* Resolves: # 
> _fd might be -1 if ::socket failed

- common/SigUtil.cpp
- common/SigUtil.hpp
- common/Util.cpp
- common/Util.hpp
- kit/ForKit.cpp
- kit/Kit.cpp
- net/Buffer.hpp
- net/HttpRequest.hpp
- net/Socket.cpp
- net/Socket.hpp
- wsd/COOLWSD.cpp
- wsd/TileCache.cpp
Better formatting of `dumpState()` and more memory stats included. Also, we now forward SIGUSR1 to the child processes, to get their memory stats and other info.
- wsd: better dumpState formatting
- wsd: dump malloc-info with USR1
- wsd: refactor forwarding a signal to our children
- wsd: forward SIGUSR1 to children
- wsd: unify dump_malloc_state with getMallocInfo
- wsd: dump malloc_info in the children
> dumpState Improvements

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarDraw.js
Open Writer, switch to the compact (menu-based) UI, notice the file menu
has no entry to add a signature.
This is primarily interesting as notebookbar is our default, but PDF
files are still opened in compact & read-only mode by default.
Fix the problem by adding a menu entry to all 4 components in the menu
bar, at a position similar to the desktop.
Also the notebookbar button was missing for the Draw case, fix that.
Change-Id: I9af4e42d11f4717a3ab6c5e25b237dd35c407410
> cool#9992 doc sign: add menu item for the compact UI

- browser/src/map/handler/Map.Keyboard.js
Change-Id: Ic57c7f0825522b78f33f23fcebba4b4f8d9ba15b
Allow to trigger the browser web developper tools with the short Ctrl+Shift+I
> Keyboard: allow Ctrl+shift+I shortcut

- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
this is reproducible with F1 and a breakpoint on
app.map.showHelp('online-help-content');
in browser/src/docdispatcher.ts
Change-Id: Id140878d3a5d19450fe8141977c3324f97541cea
* Resolves: # 
> prevent double-dispatch of uno events bound to function keys

- browser/src/canvas/sections/CommentSection.ts
Change-Id: I8da6e1208b0cbba6b51da97c6926d29da19a47a4
Use Shift+Enter to save and close the comment popup for convenience.
This is a common shortcut for such functionnality.
> Comment popup: Use Ctrl+Enter shortcut to save and close

- common/ConfigUtil.cpp
- common/ConfigUtil.hpp
- common/Util.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd/ServerURL.hpp
- wsd/wopi/StorageConnectionManager.cpp
- wsd/wopi/WopiStorage.cpp
Non-functional refactoring of config helpers and migration from COOLWSD.?pp into ConfigUtil.?pp.
This is part 2, and includes part 1 patches (from #10324).
- wsd: config: consistent namespace name with convention
- wsd: config: move config helpers to ConfigUtil
- wsd: config: move RuntimeConstant to ConfigUtil
- wsd: config: check RuntimeConst in debug mode only
- wsd: config: move SSLEnabled and SSLTermination to ConfigUtil
- wsd: config: COOLWSD::isSSLEnabled() -> ConfigUtil::isSslEnabled()
- wsd: config: COOLWSD::isSSLTermination() -> ConfigUtil::isSSLTermination()
- wsd: config: inline ConfigUtil::isSupportKeyEnabled()
> ConfigUtil Refactoring (Part II)

- browser/src/control/Control.Menubar.js
- cypress_test/integration_tests/desktop/writer/file_properties_spec.js
Open a PDF file, it is loaded into a read-only Draw view, so the File
menu has no signing menu item to sign the document.
There are some menu items, but all of those are actions, and one of
those are inserting a comment: so probably the intent is to avoid not
necessary modifications to the PDF file (like delete the only bitmap on
the draw page), than to actually avoid modifying the document.
Similar to how we have an allowlist for actions, add an allowlist for
UNO commands which are OK to dispatch in read-only mode: just have the
signature command there for now.
In the future, we may want to revisit this to also have a more strict
read-only mode without commenting/signing, but treating signing similar
to commenting is probably good enough for now.
Signed-off-by: Miklos Vajna …
> cool#9992 doc sign: add UI to sign PDF files

- .gitignore
- browser/src/layer/tile/CanvasTileLayer.js
Since Ia685a7396372967888a59cf579df49035c18eb32, we've been trying to
start a web worker if there was a window.Worker object available in the
browser...
The mobile apps can't support the worker (due to csp of file://
addresses), but also *do* have a window.Worker object. This caused a
load failure on entering any document
Change-Id: Icee556ba6da9c6be79c1bb63e2c0cd74bdb9d100
> fix(worker): Exclude from mobile app

- Makefile.am
- browser/Makefile.am
- configure.ac
In release build only 8 character long hash was generated, and it turned out that it was too short. For example the link in About box did not work:
- https://github.com/CollaboraOnline/online/commits/778b9f6 
But a longer hash would have worked:
- https://github.com/CollaboraOnline/online/commits/778b9f619
Change-Id: I5b24d7dcc4ef30acac49b7c8d72f2eca55880aed
> Use 10 characters for short git hash

- kit/ChildSession.cpp
Running 'make -C cypress_test check-desktop' in a san environment and
checking cypress_test/cypress/wsd_logs/coolwsd_output.log after the run
contains:
kit/ChildSession.cpp:2482:5: runtime error: division by zero
If the rendering is fast enough that we round the cost of it to 0, then
avoid the division by zero.
This typically doesn't affect production setups, since the log is only
for trace level.
Change-Id: I19285a8b21f5b5594d7e9a2df6ae19e2c1e43f8a
> kit: fix div by zero in ChildSession::renderWindow()

- browser/src/map/Clipboard.js
In I881818277edb69ee1e98ba1bd3454e8d29593889, we allowed inserting multimedia into the document. We didn't, however, add any provision for dragging/dropping it into the document, so only images remained drag/droppable.
This commit is a preliminary change to enable drag/drop for audio/video files. It doesn't use the same copy/paste mechanism as inserting images (as this fails, which appears to be for the same reasons we need to specify a size manually on insert...). Instead, we use the normal insert pathway, as if the user had clicked the insert button and uploaded their file. This comes with a disadvantage by way of insert position: the video is always uploaded at the top left of the document. The way to fix this is probably to change the way we determine insert position, however, as the …
> feat: Allow drag and drop of A/V files

- browser/src/control/Ruler.js
- browser/src/control/VRuler.ts
- Avoid calculating offset if the vertical ruler is hidden.
- Skip updating paragraph indentation when the ruler is not visible.
- Optimize performance by directly extracting Y translation value from mapPane style
Change-Id: I1953d680b6e132c1d48f9b435fde8e06735ed48d
* Resolves: #10442
> Optimize VRuler performance by avoiding layout calculations when hidden

- docker/from-source-gh-action/Dockerfile
- docker/from-source-gh-action/build.sh
- docker/from-source/ArchLinux
- docker/from-source/Debian
- docker/from-source/Fedora
- docker/from-source/README.md
- docker/from-source/Ubuntu
- docker/from-source/build.sh
- docker/from-source/openSUSE
- docker: updated docker/from-source/README.md
- docker: inotifytools and procps are not dependencies
- docker: use theme names instead of magic numbers
- docker: install sass, if it's not installed
- docker: when building from source, --disable-tests saves build time
- docker: git clone --depth=1 saves some time, disk space and bandwidth
- docker: use poco version 1.12.5p2 (the same version is used in production)
- docker: wrong default, distro/collabora/co-24.05 never existed
- docker: we don't have to check for sudo without asking a password
> Misc small fixes to docker build from source

- browser/js/global.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/vector/CPath.ts
- browser/src/layer/vector/Path.js
Previously, when we wanted to determine if some touch UI should be shown
we would check if there were any touchscreens on the system. This is
still used in some places, but it turns out that this is poor in many
cases (a key example would be the cursor droplet, which showed on
touchscreen laptops even when the touchscreen was not being used, for
example).
You might think that this problem is easily solved: "Just check if the
thing that clicked into the document was a touchscreen, and only show
the droplet then". We can't, however, trivially detect if the input that
caused the cursor to show was from a touchscreen as we roundtrip through
core before showing the cursor. This sort of property (hard to get a
triggering event) holds true for the other events we were using
hasAnyTouchscreen for …
> backport: feat(touch): Determine last-used input method

- wsd/ClientRequestDispatcher.cpp
The build failed with:
wsd/ClientRequestDispatcher.cpp:78:13: error: function 'shutdownLimitReached' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
I.e. the trouble is that the compiler is aware that
shutdownLimitReached() will be never called at build time.
Silence that with ifdefs for now, we may want to provide 2 definitions
for one declaration in the future to avoid the ifdefs.
Change-Id: I7adb6328a8833c909638e8fc72bd633ee4004229
> Fix clang build of --without-support-public-key

- net/Socket.cpp
We were advised to hide not only version number but the 'COOLWSD HTTP Server' string, too.
Change-Id: I5f737405c4f44c18cc033ef634ce363e5c9a74ea
> Hiding server signature

- browser/src/canvas/sections/CommentSection.ts
Previously CanvasSectionContainer.onMouseWheel - spent 30% of its time setting comment properties to the same value.
Change-Id: I0e50de9bae65db762fd6637618002485514c13b6
* Resolves: # 
> cool#10440 - perf: don't touch comment's innerText unless it changes.

- browser/css/jsdialogs.css
- browser/src/control/Control.ContextMenu.js
- browser/src/map/handler/Map.Keyboard.js
* Resolves: https://github.com/CollaboraOnline/online/issues/8205
Cherry-pick two commits from: https://github.com/CollaboraOnline/online/pull/9825
Core side patch : https://gerrit.libreoffice.org/c/core/+/171914
> Enable context menu key

- kit/ChildSession.cpp
- test/Makefile.am
- test/UnitSave.cpp
- wsd/DocumentBroker.hpp
```
The bugreport was about an ODS file which was edited to have a model
where ODS export fails, but XLS(X) export works. No steps to reliably
reproduce the problem are known at the moment.
Investigating that problem, it turns out that we had logic in place, so
that once we get the UNO command result for an .uno:Save command, we
rename the result to "<original path>.upload". This has the benefit that
in case we would start uploading to storage but an other save starts in
the meantime, then we never upload a half-finished export result. The
downside is that some code in core.git expects the original file to be
around while editing, e.g. (at least) PDF signing won't work without it.
It's also hard to audit all save codepath to be sure that the lack of
original path doesn't break other …
```
> kit: don't remove original file after save

- net/Socket.cpp
- net/Socket.hpp
Change-Id: Iad74f253bdac5636757b130b299b5deacda658db
* Resolves: # 
> Remove redundant Socket::isOpen()

- wsd/Admin.cpp
- wsd/AdminModel.cpp
- wsd/metrics.txt
* Resolves: # 
Add max/used concurrent TCP connections to Prometheus text-based 'getMetrics' REST endpoint
> Add concurrent TCP connections to 'getMetrics' REST endpoint

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/CanvasTileWorkerSrc.js
I'd made the bad assumption that keyframe and delta tile updates always arrived separately, but this is very much not the case, especially outside of Writer apparently. This change fixes that assumption and un-breaks the very obvious breakage in Impress when editing.
> Fix combined keyframe+delta tile updates

- browser/src/slideshow/PresenterConsole.js
- Change BG-color on show notes
- Removed close button for show notes, as no need for this. We already have toggle button
[Screencast from 2024-11-12 16-55-35.webm](https://github.com/user-attachments/assets/1f011f06-42a9-4a79-97a0-5b92060ac600)
Change-Id: I6353f9ea68a5665fba8f890a779fcdebd71f6d5a
* Resolves: # 
> PresenterConsole: Add toggle effect on "show notes" button

- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
instead of 'Page 2 of 6'
similar ambiguity exists in statusbar test
Change-Id: I436a749c663d35684140373189c8ff2a88799c3f
* Resolves: # 
> sometimes this test has 'Pages 1 and 2 of 6'

- net/NetUtil.cpp
so there isn't a mystery thread with the same name as the parent process.
i.e. a diff on:
pstree -plt `pgrep coolwsd`
of;
```
coolwsd(1753433)─┬─forkit(1753438)───kit_spare_001(1753456)
├─{#1}(1753434)
├─{accept_poll}(1753458)
├─{admin}(1753460)
-                 ├─{coolwsd}(1753436)
+                 ├─{asyncdns}(1753436)
├─{prisoner_poll}(1753437)
├─{remotefontconfi}(1753457)
└─{websrv_poll}(1753459)
```
Change-Id: Ic63c2be172212b3fba6f80b7da4118c89dbba6a1
* Resolves: # 
> name the async dns thread

- browser/Makefile.am
- browser/src/layer/tile/CanvasTileLayer.js
so any browser/src/layer/tile/CanvasTileLayer.js files left behind by a make *before*:
commit 906519623fc8cf88eb4cf09500f711b318c64360
Generate CanvasTileWorker.js in DIST_FOLDER, not srcdir
are not relevant if auto-copied into browser/dist before this generation rule is applied
Change-Id: I1120ceada4e2d8a93576d43cecc09e5a38333a8c
* Resolves: # 
> rename generated CanvasTileWorker.js target to TileWorker.js

- net/HttpHelper.cpp
- net/WebSocketHandler.hpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/ProxyProtocol.cpp
Resolves #10454.
- wsd: remove redundant headers from WS request
- wsd: remove User-Agent from responses
- wsd: http: use http::Response
> User Agent

- browser/admin/src/AdminSocketAnalytics.js
- browser/admin/src/Util.js
- wsd/Admin.cpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
* Resolves: # 
Have AdminModel accumulate StreamSocket::getExternalConnectionCount() statistics
in same size and interval as net recv/sent.
The added statistic is rendered into the #NetVisualisation graph using a second y-axis on the right.
Here we use a human-readable quantity tick with added multiple, percentage (1/100) or permyriad (1/10'000) to net::Defaults.maxExtConnections.
Graph is accessible via `/browser/dist/admin/adminAnalytics.html#networkview`.
> Add (external) connections stats to #NetVisualisation graph

- browser/src/map/handler/Map.Keyboard.js
I found this on an Apple device, as Cmd+Z and Cmd+Shift+Z were both undoing. On every other app I could find, Cmd+Shift+Z was bound to redo, however here we hadn't set it. Without setting this shortcut, it instead also activates undo, causing trouble for people who are used to using it as redo.
* Resolves: # 
> fix(keyboard): Allow using Ctrl+Shift+Z for redo

- browser/src/map/Clipboard.js
_doCopyCut has the ability to call functions that depend on _unoCommandForCopyCutPaste, but despite having access to the required uno command here it never sets the variable.
That causes copy/paste commands that go through this route to use the last command executed, or if no commands were executed before this to throw an error and fail entirely.
I noticed this while working on #10498, but decided to avoid including it there as that is a pure refactor
Change-Id: I00549aa872fee8f51b5c0426e5d1eb1569210378
* Resolves: # 
> fix(clipboard): set command in _doCopyCut

- browser/src/control/Control.DownloadProgress.js
- browser/src/map/Clipboard.js
Previously the read and write functions were using callbacks and promise
chains, which worked but would have been more annoying for me to extend
with android-specific clipboard things.
As a bonus, async/await reduces nesting and jumping around in the code,
which should also make this easier to read, and arrow functions remove
this->that aliasing
Finally, using async/await in new places allows us to better use
existing places which do provide promises, for example we can go back to
only fetching the clipboard a single time without re-introducing the
race condition which fetching twice solved
> refactor(clipboard): convert to async/await

- browser/src/control/Control.Sidebar.ts
This fixes the error on switching the decks in Writer. Regression from commit b5eab2c988515c904f8c4b6c975a25e1f777e028 browser: treeview: remove global var hack
> sidebar: fix TypeError on switch

- common/Session.hpp
- kit/Kit.cpp
- kit/Kit.hpp
- wsd/ClientSession.hpp
Change-Id: Ic71b03747e57976ce4ac69a5f97a015d5d210648
* Resolves: # 
Add const qualifier to certain immutable methods, allowing interoperability with const references.
> Document/ClientSession/SessionMap: Make imutable methods `const`

- browser/src/control/Control.StatusBar.js
now EditDoc may have true, false or disabled values, handle it accordingly
Change-Id: I52668290007cc07d3f1bae015d533d50fc538c76
> stateChangeHandler: EditDoc now uses boolean or disabled payload

- browser/src/slideshow/PresenterConsole.js
- Because we same variable is the reason that notes text gets into #slides container text
- this patch will get notes content container and set inner text by default "no notes"
- we will assign text only if notes are defined in current slide
Before:
After:
Change-Id: I32dd646ca4cbabce94842cbc3d34cda636ec45b1
* Resolves: # 
> Fix: Notes placeholder string gets mixed up with "Slide of" string

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Toolbar.js
- browser/src/control/jsdialog/Definitions.Menu.ts
- browser/src/docdispatcher.ts
- browser/src/map/handler/Map.FileInserter.js
- browser/src/map/handler/Map.WOPI.js
- kit/ChildSession.cpp
- wsd/DocumentBroker.cpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
Similar to the existing "Insert Image", this turns multimedia insertion
button into a menu, which is optionally expanded to include the remote
item. It depends on explicit integration support (controlled by present
"EnableInsertRemoteMultimedia" file info response field), and requests
the integration to show a "pick an asset" UI with given MIME types (by
sending 'UI_InsertFile' request), and to reply Action_InsertMultimedia,
that expects an URL.
Change-Id: Ide6eefa6a55213f4ec0d1e47e35b5e4bf4a109be
> Implement remote multimedia insertion support

- kit/Kit.cpp
When switching between views, new pages may be created and old ones may get deleted. In this case, some pointers are null. Check "DrawViewShell not available!" warning on the core side. This null pointer causes render state payload to be empty. Empty payload is not correct value for client side renderState parameter.
Change-Id: I08af6208807e0dc38538b85539dd992bb166695c
* Resolves: # 
> Don't update the render state if the payload is empty.

- browser/src/map/Clipboard.js
- common/MobileApp.hpp
- ios/Mobile/AppDelegate.mm
- ios/Mobile/DocumentViewController.mm
- ios/Mobile/TemplateCollectionViewController.mm
- ios/ios.h
- There is a dependency in the iOS parts with https://gerrit.libreoffice.org/q/topic:%22private/skyler/ios-clipboard%22
- On Android specifically, this introduces several regressions, of which I have found the following
- This pastes formulas by value, rather than by reference
- This cannot copy images or graphics
On iOS these are not regressions, not because they don't exist but because copy/paste is already so broken that it doesn't matter. This is strictly an improvement.
---
I'm going to spend some time investigating these regressions, but if I'm not able to fix them within a timely fashion then I think the solution will be to split I9352a4473be7ab38acc6187a93a5b63e22208815 into iOS/Android copies, and then merge the following in a separate PR
- …
> feat: unify mobile clipboard with online

- kit/Kit.cpp
By the time the thread runs, the ctor's stack is gone, so capture the
doc ID by value.
A problem since commit f27f2e297eadcf06171bfeb86ce99d717f6c73fc (wsd:
bgsave watchdog thread, 2024-11-14).
Change-Id: Iec98aeff059104b1ba321442bff98198dce5cc61
> kit, BackgroundSaveWatchdog: fix memory management in the ctor

- browser/src/slideshow/LayerDrawing.ts
Current slideshow implementation is not notified about presentation
modification. A complete solotion would require a good amount of work.
In the meanwhile we need a workround, which it's waht this patch provides.
Change-Id: I1ae3c09a60a1273dfe829f0932bd0fd83404de93
> slideshow: invalidate cached layers on slideshow restart

- browser/src/map/handler/Map.Keyboard.js
- cypress_test/integration_tests/desktop/draw/pdf_page_up_down_spec.js
and its follow up fix for ctrl+s. Which is a bit of a bodge. So revert the two together and have another round at this later.
The goal was to enable "F3" to do something which isn't needed yet.
This reverts commit b2b637e153ac2d73c272c8284ed85e5fcffa3e16.
Change-Id: I79869dc3e07c86edf9f99bb6100b9e6dcb5b5698
* Resolves: # 
> Revert "prevent double-dispatch of uno events bound to function keys"

- browser/css/jsdialogs.css
In core change Ib94c8db5beb88d0b71035081680ce25a74774d08, we are adding support for the comments property in the word count dialog. Not styling this shows the property name and its value on separate lines
Change-Id: I12e7e07f59a5f30e51b65066adee5c90394a3991
* Resolves: # 
> fix(mobile): Style comment property on word count

- common/SigUtil.cpp
- common/SigUtil.hpp
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/KitWebSocket.cpp
This adds logic to reap zombie children on SIGCHLD, which doesn't leave zombies around until the next background save (which would leak if bg-save got disabled).
To avoid adding yet another reaping logic, we consolidate the implementations into a neat helper that also logs.
- wsd: sigaction's sa_handler takes int
- wsd: extract reapZombieChild and reuse
- wsd: reap bg-save on SIGCHLD
> Consolidate Reaping Helper and Reap on SIGCHLD

- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/layer/tile/CalcTileLayer.js
* Resolves: #10436
With workers enabled, drawing is sometimes not synchronous. This causes a problem when resizing, which clears the canvas entirely and expects tile rehydration to happen synchronously afterwards. Work around this by redrawing the old canvas contents when resizing.
I considered more comprehensive fixes, but they all added a lot of complexity and used more memory than this. I think there's probably a better possible fix here of doing less work when resizing, but how to do that wasn't immediately obvious.
I've also bundled a much smaller fix which is the more common case, where we were dumping the old canvas contents and redrawing everything even when the canvas size wasn't changed (for example, copy/paste from another open sheet causes two null …
> Fix black flashing when resizing the canvas

- browser/css/jsdialogs.css
This is a trivial backport of #10564
In core change Ib94c8db5beb88d0b71035081680ce25a74774d08, we are adding support for the comments property in the word count dialog. Not styling this shows the property name and its value on separate lines
Change-Id: I12e7e07f59a5f30e51b65066adee5c90394a3991
* Resolves: # 
> backport: fix(mobile): Style comment property on word count

- browser/src/map/Clipboard.js
_doCopyCut function is already sending the relevant command.
Also saw that _sendCommandAndWaitForCompletion returns a promise that is not needed anymore (after Skyler's refactorings).
So we can remove that and use a boolean value for pursuing the state of cut/copy commands.
This fixes (Calc):
* Cut text.
* Paste it.
* It pastes empty text - because of double issuing of cut command, second time it cuts empty text.
Change-Id: I0d4a2b0637892234a7dab68638f26cacadd8bb11
* Resolves: # 
> Remove duplicate sending of copy and cut commands.

- browser/src/control/Search.js
We need to wait for search results before sending new ones, or we end up skipping over valid results.
Change-Id: I957873ee8c80ac8c1ed04a33510b3c6b46886360
* Resolves: # 
> Fix intermittent searchbar_spec.js test failure

- browser/src/control/jsdialog/Widget.TreeView.ts
jsdialog: treeview: put dummy columns at correct position
It was a regression from commit aee68f732003d02bdf7c9b0768df8ca0a3880123
browser: treeview: align listbox with headers using subgrid
If we used autofilter in calc which has icons at the end of an entry,
we got dummy column at the beginning of the row...
This adds preprocessing of columns so we always have all of them
unified (the same number of cols in every row) with dummy ones at
the correct position. Exception is separator which has to be only
one in the row to be full width.
> treeview: missing columns

- browser/src/control/jsdialog/Widget.TreeView.ts
it was possible to skip some column before due to index calculation, code is also simpler now
> jsdialog: treeview: simplify missing columns injection

- browser/src/control/Control.ESignature.ts
- browser/src/control/Control.UIManager.js
- wsd/FileServer.cpp
Once the hash is extracted from the document, we need to send it to the
3rd-party for signing.
Given that we don't want to send the entire document, our signature
container should not be an entire PDF file, we just want this for the
signature binary itself (PKCS#7 blob), set the file type to "cades",
which does exactly this.
This requires passing the API URL, and credentials to
L.Control.ESignature.
Finally allow communicating with these hosts in the CSP headers.
Initially I attempted to take the URL from CheckFileInfo, but we seem to
decide this when serving cool.html, so that order doesn't allow making
the CSP headers depend on the CheckFileInfo response. In practice only 2
public servers implement this protocol (production and test), so just
allow them for now, similar to Zotero. If …
> cool#9992 doc electronic sign: send the hash to be signed

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/canvas/sections/CalcGridSection.ts
- browser/src/control/Control.UIManager.js
Change-Id: Ie379efb16f5e82de8d53203b88fdccad15e8da37
* Resolves: # 
This allow to adjust the calc grid line color through css variables. It also sets a different value for dark mode to make the contrast ratio with the background similar to light mode.
Change might be subtle but makes calc in dark mode look much nicer as discussed at some point already with @pedropintosilva and @jancborchardt
One issue seems still that a reload is required, on switching to dark mode the grid color is not picked up again. I'm not sure what the best way would be to update the sectionProperties values in that case. Maybe someone has a pointer there?
| Before | After |
|---|---|
| ![image](https://github.com/user-attachments/assets/2a66696a-edbe-45f1-bb3c-34c5b1ceb050) | …
> fix(calc): Improve grid colors in dark mode

- browser/src/slideshow/SlideShowPresenter.ts
it shows overlay with semi-transparent text indicating the paused presentation due to inactivity of a main window
it can happen when user switched tabs in the browser
[pause-2024-11-25_14.16.49.webm](https://github.com/user-attachments/assets/bd73d30e-8dc1-42af-b796-64625f50a6c2)
> slideshow: show pause indicator in the in-window presentation

- fuzzer/ClientSession.cpp
Seems to be a fallout from commit
fc2c44198812060095d016000906e9d926af1735 (wsd: move anonymization
implementation to own home, 2024-11-20).
Change-Id: I7392c7ebc40acae910fb308ccaa5bd7d702f0e46
> fuzzer: fix the build of 'clientsession_fuzzer'

- .github/workflows/docker.yml
Otherwise the cache would also contain the sources we build online from so only updates once the cache is invalidated.
Build time is still reasonable with 12 minutes as only ran once a day
Signed-off-by: Julius Knorr <jus@bitgrid.net>
Change-Id: I96d57cb75e48f2560ceae6ebdd5213478b03efee
> ci(docker): Remove cache from nightly container build

- browser/src/map/handler/Map.FileInserter.js
The 'pictureurl' message is handled in ChildSession::contentControlEvent,
which relies on the order of the arguments.
In commit 60d9a9c20bf69b3f1d8591b2d8400c4a453970ab (Implement remote
multimedia insertion support, 2024-11-19), I incorrectly modified the
order, trying to unify it between nearby calls. Fix it here.
Change-Id: I612973e1b8aa245a601d3053e516b67007482a69
> Fix incorrect order of message arguments

- browser/src/control/Control.ESignature.ts
- browser/src/control/Control.UIManager.js
- browser/src/map/handler/Map.WOPI.js
Open an PDF in Draw, Insert -> Electronic signature, the doc hash is
sent to ESignatureBaseUrl, but we don't attempt to sign it.
The actual signing happens using a HTML page provided by eIDEasy, so
open that in a popup.
We can avoid polling for the signature result by listening for
postmessages: the signing popups sends us a postmessage on completion.
This is the same mechanism that's used by the SignatureJS npm library,
developed by eIDEasy (but don't use that here, since it would pull in a
number of dependencies since it doesn't use the fetch() API).
Change-Id: I10902ec6868a64f250fe5afdd0cf9ba36a2f63e6
> cool#9992 doc electronic sign: actually sign the hash in a popup

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/Transition2d.ts
slideshow: refresh paused screen in Firefox
followup for commit b4decaee2bcd5f65a92ea887b9298968a9440db1
slideshow: show pause indicator in the in-window presentation
we detected that Firefox renders from time to time (around 1 / s)
the popup if main window is hidden - what doesn't happen in Chrome
---------------------------------------
slideshow: prevent Transition2d exception on program
this.program might be missing if using with hidden
main window browser tab
Transition2d.render (Transition2d.ts:153)
SlideChangeTemplate.SlideChangeBase.animate (SlideChangeBase.ts:82)
requestAnimationFrame
TransitionBase.startTransition (Transition2d.ts:36)
TransitionBase.start (Transition2d.ts:42)
SimpleActivity.startAnimation (SimpleActivity.ts:53)
ActivityBase.calcTimeLag (ActivityBase.ts:76) …
> slideshow: pause mode refresh

- browser/src/canvas/CanvasSectionContainer.ts
Don't try to call getImageData if the canvas width or height are zero, as this will result in an IndexSizeError.
> Check canvas size before copy in CanvasSectionContainer.onResize

- browser/src/control/Control.ESignature.ts
Sign a hash with electronic signing, we get a postmessage that the
signing is done on the external site, but we still don't have the
signed hash.
There is a /api/signatures/download-signed-file endpoint to fetch the
PKCS#7 blob, but that is only meant to succeed once we know the signing
happened.
Handle this by fetching the signature once we got a postmessage that
the signing was fine.
The blob we get still needs integrating, though.
Change-Id: Id0dcdf5a6518c6b71ab02f1f77a3736038546821
> cool#9992 doc electronic sign: fetch the created signature

- browser/css/spreadsheet.css
Before this commit the unotoolbutton was bigger than the inner button
resulting in a faulty hover style
Change-Id: Id63c4b9e05629d2d0584af1b6fefc6e4e2f1cbe7
> Calc: Fix spreadsheet toolbox button size

- browser/src/slideshow/SlideShowPresenter.ts
Apart from changing the current slide in the editor,
this causes the onUpdateParts to be triggered which in turn request presentation
info again even if that's not needed.
Change-Id: I15efd3d205c7b03a76d04ff0e8f4f22b07bac00e
> slideshow: prevent slide sorter to receive key events on fullscreen mode

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/css/spreadsheet.css
- browser/src/control/Control.Header.ts
Note: this commit doesn't touch or fix the problem with the corner
header being always white even if on dark mode. That is outside of the
scope of this patch.
Better to create dedicated css vars instead of rely on other generic
CSS vars such as background-color-darker etc. this way we avoid
calc regressions when someone changes those more generic values.
Also avoid setting the fill of header-row and header-column-selected
to the primary color. If the integrator wants to set that they are
free to overwrite that but better to default to neutral color that
looks ok on both light and dark mode.
Change-Id: I3c6d0b7a8e58ae8c239bda97d35454cdc70826fe
> Calc: Set spreasheet header colors from CSS vars

- man/coolconfig.1
- tools/Config.cpp
use --user and --password to pass the user and / or password to set-admin-password
Change-Id: I192262fde6fbef812487e4d4e49049d5ebd5c776
* Resolves: # 
--user and --password for `coolconfig set-admin-password`
> coolconfig: Allow passing admin user name password

- kit/Kit.cpp
- SfxDocTplService::init_Impl doesn't get initialized because unolibrary `ucphier1` is disabled
```
warn:sal.osl:1269089:1269017:sal/osl/unx/module.cxx:100:
dlopen(/lo/program/../program/libucphier1.so, 257):
/lo/program/../program/libucphier1.so: cannot open shared object file:
No such file or directory
warn:legacy.osl:1269089:1269017:ucb/source/core/provprox.cxx:347:
UcbContentProviderProxy::getContentProvider - No provider for
'com.sun.star.ucb.HierarchyContentProvider.
warn:sal.osl:1269089:1269017:sal/osl/unx/module.cxx:100:
dlopen(/lo/program/../program/libucphier1.so, 257):
/lo/program/../program/libucphier1.so: cannot open shared object file:
No such file or directory
warn:legacy.osl:1269089:1269017:ucb/source/core/provprox.cxx:347:
UcbContentProviderProxy::getContentProvider - No …
```
> kit: fix: templates don't get imported when mounting is disabled

- browser/Makefile.am
- browser/src/control/Control.ESignatureDialog.ts
- browser/src/control/Control.ServerAuditDialog.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- **jsdialog: avoid 'as any' cast by adding more types**
- **cool#9992 doc electronic sign: add a provider selector dialog**
> cool#9992 doc electronic sign: add a provider selector dialog

- browser/css/toolbar.css
With the improvements from db10c453e95f732d85c489fe8da8708cec0ad09c
https://github.com/CollaboraOnline/online/pull/10027 and its follow
ups, it is now needed to update close button divider margin so, it
goes back on being centered aligned
Also update code comments around that.
Change-Id: Ie3fac7e7131c46eb165b2c2d07eef97bfdbce4ce
> Main-nav: Fix close button divider (separator) position

- Makefile.am
- common/Anonymizer.hpp
- common/FileUtil.hpp
- common/Log.hpp
- common/Protocol.cpp
- common/Protocol.hpp
- common/Util.cpp
- common/Util.hpp
- kit/ForKit.cpp
- test/UnitTimeoutBase.hpp
- test/WopiTestServer.hpp
- test/lokassert.hpp
- tools/Replay.hpp
- wsd: remove unused helpers
- wsd: include cleanup
- wsd: remove superfluous const on primitives in declarations
- wsd: test: Use litteral character for readability
- wsd: inline getTokenInteger
- wsd: better ServerWSHandler ctor
- make: use $(MAKE)
> Misc Cleanup

- browser/src/layer/tile/CanvasTileLayer.js
This reverts commit a074a6f199c0594afd173fe3638b72d1d649b3ff. browser: fix PageDown cursor position
This causes randomm jumps on tile rendering when we need to move view to render. It sends additional curosr updates which are not correct (like 0,0,0,0 and scroll: true).
We already have logic here to scroll if needed, we shouldn't need any information from core.
see: https://gerrit.libreoffice.org/c/core/+/177520
> Revert "browser: fix PageDown cursor position"

- browser/src/map/Clipboard.js
It causes the process to think that clipboard API has failed. Then we don't try again with the clipboard API. This commit logs a warning and skips the fallback part.
Change-Id: I4f04feb3bf77ea986453733a6c8976ef3d0ac2a4
* Resolves: # 
> Clipboard write: Don't consider "Document is not focused." as an error.

- browser/src/control/Control.ContextMenu.js
I think the original author copy&pasted code from the previous condition, which was a menu. But in this case the item.type is command, and item.menu is undefined. Therefore with my fix the localization works, also the functionality works. I don't know what I'm doing, though.
Change-Id: I2e929d9f104beac83c195cdf03eba620a1a4ebb3
> Fix localization of Calc AutoFill context menu

- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
make this more clear with a more typical explicit std::move pattern
Change-Id: I8dc7da1af59c6aa09c608d3cbfcd2c9167eab418
* Resolves: # 
> setWopiFileInfo takes ownership of its arg

- browser/css/jsdialogs.css
- cypress_test/integration_tests/common/desktop_helper.js
commit 667103b356bf648a4f1323ceb8787f26bb6a961e (HEAD -> private/pedro/backport-mobile-5bfbb9b, origin/private/pedro/backport-mobile-5bfbb9b)
Date:   Mon Dec 2 12:41:50 2024 +0100
Mobile: Status bar dropdown is always an icon: no need for dedicated width
Previously the commit bellow fixed a regression related to dropdown
width:
591e003a300ecf9ffe5a5ce770e5d62f3cc1b28f
"Status bar: fix dropdown width"
However there seems to be no reason to apply this fix to the mobile
toolbar since we can safely conclude that the dropdowns always have
the same fixed size (icons)
Change-Id: I3733b4d736d1481a382fffb71b451b82ad77d04d
commit 591e003a300ecf9ffe5a5ce770e5d62f3cc1b28f **Cherry-picked …
> Status bar: fix dropdown width

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/control/Control.Mention.ts
Change-Id: `Id2484d5dee155a7755e0cca55a97d7191ec83985`
In Nextcloud, we are working on improving our mention support, and it would be really nice to also be able to pass a display name (label) along with a username (unique identifier) and the profile link. Having this would allow us to determine the user quicker and easier on our side, and I don't see the harm in having it there for other integrations as well, should they want it.
This is a work-in-progress PR, and it's my first contribution to this repository, so please bear with me and provide any constructive feedback you may have :)
> feat: Add user label to mention

- configure.ac
Change-Id: I9b4d12bf9baa6e64097447a228d863fdec19fdff
* Resolves: # 
> Avoid "warning: underquoted definition of AC_PROG_LCOV" from autogen.sh

- browser/src/control/Control.ContextMenu.js
- browser/src/layer/tile/CanvasTileLayer.js
When we click outside of the autofill context menu, menu is closed but marked area doesn't reset.
We fix the problem with the patch
Change-Id: I819d1b0393d1f062570c5b1d4776c32ae90aa887
* Resolves: # 
> Reset autofill mark on close autofill context menu

- browser/src/map/Clipboard.js
Or it opens 2 instances of the popup.
Change-Id: Id091775cef6b7f162c9ffd99d119a3d7c64085da
* Resolves: # 
> Return true if filterExecCopyPaste succeeds for pasteSpecial.

- browser/src/control/Control.Menubar.js
- browser/src/control/jsdialog/Definitions.Menu.ts
This reverts commit 1e096ee31200c4f9e815f59034e6e721466f7f4f.
Change-Id: I173b6b88b7621bc46df4579a5de0816d6942e821
Core patches are reverted corresponding to this commit
> Revert "UI: replace conditional format dialog with conditiona manager"

- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.UIManager.js
- browser/src/map/handler/Map.WOPI.js
Show_NotebookTab will show a previously hidden Notebookbar Tab Hide_NotebookTab will hide a Notebookbar Tab
Change-Id: If138b5f9327e8737dece211c70db19f63bb70465
* Resolves: # 
> PostMessage: added Show/Hide_NotebookTab

- browser/src/canvas/sections/ShapeHandlesSection.ts
When selecting a portion of text, ShapeHandlesSection's dragging is activated. This causes the shape to move while selecting a portion of text. Check the visibility of the cursor and don't start dragging event if cursor is visible.
Change-Id: I9a7c8917125cc3c32ffd14c81ab07bf491b7158d
* Resolves: # 
> Impress: Don't activate draggin if text cursor is visible.

- browser/src/control/Control.Notebookbar.js
- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
- Fire "state change command" to disable toolbar option for "Present Console" when we already in "Present in Window".
This ensures the "Presenter Console" option is disabled while the presentation is in window mode.
Change-Id: I65d37187be901a073a83cfcdd987fbb2e14bc896
* Resolves: # 
> Disable "Presenter Console" option when "Present in Window" is clicked

- ios/Mobile/Info.plist.in
- ios/modify_bundle_version.sh
This is a forward-port of https://github.com/CollaboraOnline/online/pull/10164
Previously we were using versions like "24.04.7" for release "24.04.7.3". Unfortunately, this works poorly if we want to have a patch release, as we can't reuse codes so we have to immediately go to "24.04.8", even when releasing from a "24.04.7" tag.
Merging our year and major release into Apple's major release number makes more sense with how we expect releases to change over time...
We also need to change how we generate the CFBundleVersion, as  otherwise it will be invalidly-long (the maximum length being 18 characters and "2404.7.202410021739" being a frustrating 19 characters, for example
Change-Id: I4aa9ab53b3a4d5786e04a90ab4c7c759d9606706
* Resolves: # 
> forward-port: fix(ios): better approximate our version format

- browser/src/control/Control.UserList.ts
- cypress_test/integration_tests/multiuser/calc/cell_cursor_spec.js
- cypress_test/integration_tests/multiuser/writer/cursor_spec.js
Change-Id: I4e7a06bab413dad0b5f2360c4bef729db7d5e0d0
* Resolves: #10167 
Fixes a UX bug that disrupts user workflow by leaving the selection popup open after a user is chosen, blocking underlying content.
Users Clicks in the avatars
Pop up closes when one of the users is clicked 
- ✅ I have run `make prettier-write` and formatted the code.
- ✅  All commits have Change-Id
- ✅  I have run tests with `make check`
- ✅ I have issued `make run` and manually verified that everything looks okay
> Ensure popup closes automatically on user selection

- Makefile.am
- cypress_test/Makefile.am
- test/Makefile.am
test/Makefile.am:362: warning: 'TEST_EXTENSIONS' cannot have conditional contents
- I removed the conditional from the test/Makefile.am and added conditional whether to descend into test/ subdirectory to the main Makefile.am. I did the same for cypress_test/Makefile.am, although that one did not cause warning.
test/Makefile.am:217: warning: variable 'unit_admin_la_SOURCES' is defined but no program or test/Makefile.am:217: library has 'unit_admin_la' as canonical name (possible typo) test/Makefile.am:218: warning: variable 'unit_admin_la_LIBADD' is defined but no program or test/Makefile.am:218: library has 'unit_admin_la' as canonical name (possible typo)
- unit_admin_la is commented out, so I commented out these lines, too
test/Makefile.am:305: warning: variable …
> fix automake warnings

- Makefile.am
- android/lib/src/main/cpp/CMakeLists.txt.in
- android/lib/src/main/cpp/androidapp.cpp
- common/Log.cpp
- common/Log.hpp
- configure.ac
- coolwsd.xml.in
- fuzzer/Common.cpp
- fuzzer/HttpEcho.cpp
- gtk/Makefile.am
- gtk/mobile.cpp
- ios/Mobile.xcodeproj/project.pbxproj
- ios/Mobile/AppDelegate.mm
- kit/ChildSession.cpp
- kit/ChildSession.hpp
- kit/ForKit.cpp
- kit/Kit.cpp
- kit/Kit.hpp
- kit/LogUI.cpp
- kit/LogUI.hpp
- scripts/undoStatistics.py
- test/Makefile.am
- test/test.cpp
- tools/WebSocketDump.cpp
- wasm/Makefile.am
- wasm/wasmapp.cpp
- wsd/COOLWSD.cpp
Log several kind of commands, and Undo count change. This may helps to find what user try to undo at most cases.
We can set what kind of commands we want to log at:
std::set<std::string> aCmdToLog = {
"uno", "key", "mouse", "textinput", "removetextcontext",
"paste", "insertfile", "commandvalues" };
We can set what commands should be merged at:
std::set<std::string> aCmdToMergeLog = {
"mouse", "textinput", "removetextcontext" };
Merged means, if the same command is called again, it wont be logged again, but the next time before a different command is called, the merged command's count will be logged.
Some commands merge may need some more deep logic. at "mouse" command only the move is merged.
"key" could be more complex as it can be an insert space, arrow keys, or pageup/down. now all of …
> Log UI commands related to undo

- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/canvas/sections/ScrollSection.ts
Change-Id: I5c6cce08f68ec6ac99ac668bb78c12274ce72f3e
* Resolves: # 
> Add animation to vertical wheel scrolling for smoother experience.

- common/Protocol.cpp
- common/Protocol.hpp
- common/Util.hpp
- test/UnitOAuth.cpp
- test/WhiteBoxTests.cpp
- wsd/FileServerUtil.cpp
- wsd: remove unused function
- wsd: string_view in Util
- wsd: string_view in Protocol
- wsd: pass string_view by value
- wsd: Util::split doesn't have to create strings
> More string_view

- net/WebSocketHandler.hpp
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007f5eba5167f1 in __GI_abort () at abort.c:79
#2  0x0000000000bee08e in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) ()
#3  0x00000000005cf12f in std::vector<char, std::allocator<char> >::operator[] (__n=0, this=0x7f5e397e7260)
at /opt/rh/devtoolset-12/root/usr/include/c++/12/bits/stl_vector.h:1121
#4  0x00000000005f2b46 in std::vector<char, std::allocator<char> >::operator[] (__n=<optimized out>, this=<optimized out>)
at /opt/rh/devtoolset-12/root/usr/include/c++/12/bits/stl_iterator.h:1072
#5  WebSocketHandler::handleTCPStream (this=this@entry=0x7f5ea09a62d0, socket=std::shared_ptr<StreamSocket> (use count 3, weak count 2) = {...})
at ./net/WebSocketHandler.hpp:431
#6 …
```
> WebSocketHandler::handleTCPStream abort

- Makefile.am
- browsersync-config.js
- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/calc/sheet_switch_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/navigator_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
config wasn't updated after we did rework of URL
to run:
- configure cool with --enable-browsersync
- run server with COOL_SERVE_FROM_FS=1 make run
- run browsersync with: make sync-[writer|calc|impress]
> browsersync: fix paths

- browser/src/control/Control.ContextMenu.js
Change-Id: I71ce81efcbbb0c6a57d808d5f5d0e691567dfad5
* Resolves: # 
Context menu entries will now get a class corresponding to the uno
command name associated, in a snake-case format.
I.e InsertAnnotation => insert-annotation
This allows to change style individual context menu entry or even remove them.
> ContextMenu: add a css class to entries

- browser/src/control/Control.ESignature.ts
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/draw/esign_spec.js
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/FileServer.cpp
- **cool#10630 doc electronic sign: expose the name of the document**
- **wsd: fix clang 18 -Werror,-Wvla-cxx-extension**
- **cool#10630 doc electronic sign: send the hash on the server**
> cool#10630 doc electronic sign: send the hash on the server

- cypress_test/Makefile.am
i.e. with:
./configure --enable-debug --enable-werror
and
cd cypress_test && make check-desktop spec=writer/form_field_spec.js
this always fails for me. And launching coolwsd with the same args of make check-desktop/run-desktop gives an online session that is entirely unresponsive.
changing:
../coolwsd ... --o:logging.level=trace --o:logging.file.property[0]=/path/to/cypress_test/cypress/wsd_logs/coolwsd.log
to
../coolwsd ... --o:logging.level=trace --o:logging.file.property[0]=/tmp/coolwsd.log
or
../coolwsd ... --o:logging.level=warning --o:logging.file.property[0]=/path/to/cypress_test/cypress/wsd_logs/coolwsd.log
works fine
Change-Id: I039cef96934ba6c164c37a03fa2c8816ac15f4f0
* Resolves: # 
> cypress tests with --enable-debug and trace logging fail

- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitQueue.hpp
Prepares us for having tiles that need rendering left over from a drainQueue and not necessarily having another queue item to trigger fast iteration of the poll.
Should do nothing at all as of now =) ... 
Change-Id: Id51441070dfb883a5964308d54880d46a3210087
> KitQueue - re-spin poll loop when we have tiles to render.

- common/Unit.hpp
- test/UnitClient.cpp
- test/UnitQuarantine.cpp
```
[ docbroker_001 ] DBG  Cannot save to disk: CanSave::NotLoaded| wsd/DocumentBroker.cpp:2816
[ docbroker_001 ] TRC  Disconnect session internal 001, LastEditableSession: true destroy? true locked? false, have 0 sessions (inclusive)| wsd/DocumentBroker.cpp:3365
[ docbroker_001 ] DBG  Disconnecting session [001] from Kit| wsd/DocumentBroker.cpp:3388
[ docbroker_001 ] INF  Session [ToClient-001] disconnected but DocKey [http%3A%2F%2F127.0.0.1%3A9981%2Fwopi%2Ffiles%2F0] isn't loaded yet. Terminating the child roughly| wsd/DocumentBroker.cpp:3399
[ docbroker_001 ] INF  Killing child [1283222].| wsd/Process.hpp:106
[ docbroker_001 ] DBG  Killing PID: 1283222 with SIGKILL| common/SigUtil.cpp:630
[ docbroker_001 ] TRC  Removed non-readonly session [001] from docKey …
```
> make unit tests reliable wrt SIGKILL

- browser/src/slideshow/PresenterConsole.js
- Next slide preview not getting updated
- because we removed the element of nextslide preview when we show slide sorter
- we need to just make it's display none make sure to change back to flex on show normal view
Change-Id: Id6e756b1d17b4445f1f85e8299af25808806b2f6
> Update next slide preview after slide selection in slide sorter

- browser/src/slideshow/LayerRenderer.ts
When user stopped presentation early, online still tries to draw slides because of delayed "slidelayer" messages from core. That is the cause of following error
TypeError: Cannot read properties of null (reading 'useProgram')
So we shold check if the user exited from presentation before drawing slides.
Change-Id: If3b3cb340cfc15632de16d0fed1c730ab4d9d763
* Resolves: # 
> Check LayerRenderer is disposed before drawBitmap

- kit/ChildSession.hpp
- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitWebSocket.hpp
Not on outgoing messages that have come from core.
We should not treat rendering / tile requests as input.
Change-Id: I0ced5ee0f07796e8aae015f31c91cb7845443ea8
* Resolves: # 
> anyInput - should only depend on incoming messages from coolwsd.

- browser/src/control/Control.Notebookbar.js
- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
Back port PR: https://github.com/CollaboraOnline/online/pull/10653
- Fire "state change command" to disable toolbar option for "Present Console" when we already in "Present in Window".
- This ensures the "Presenter Console" option is disabled while the presentation is in window mode.
Change-Id: I65d37187be901a073a83cfcdd987fbb2e14bc896
* Resolves: # 
> Back-port: #10653

- browser/css/toolbar.css
Change-Id: Ib7d5ae234efd9fc2d0438090f4a90e6b229b53e1
* Resolves: # 
Adjusts the size of the user avatar to ensure consistency with the sidebar icon dimensions. Previously, the avatar appeared disproportionately larger, which affected the visual alignment on the Toolbar
> Adjust user avatar size to align with sidebar icon dimensions

- browser/src/slideshow/SlideShowPresenter.ts
SlideShowPresenter.ts:499 Uncaught TypeError: Cannot read properties of null (reading 'clearInterval')
at SlideShowPresenter.disablePauseHandler (SlideShowPresenter.ts:499:30)
at SlideShowPresenter.<anonymous> (SlideShowPresenter.ts:574:11)
SlideShowPresenter.disablePauseHandler @ SlideShowPresenter.ts:499
(anonymous) @ SlideShowPresenter.ts:574
Change-Id: Icb55f06b89a5a930a47203caf5b6b2fbc6802530
> slideshow: fix Uncaught TypeError undefined

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/multiuser/calc/cell_cursor_spec.js
we need to select a cell before double click to type, it was like that before
> cypress: reenable multi/calc/cell_cursor_spec.js

- browser/src/slideshow/CanvasLoader.ts
- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayerRenderer.ts
- browser/src/slideshow/PauseTimer.ts
- browser/src/slideshow/RenderContext.ts
- browser/src/slideshow/SimpleTextureRenderer.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/StaticTextRenderer.ts
- browser/src/slideshow/Transition2d.ts
- browser/src/slideshow/Transition3d.ts
- browser/src/slideshow/engine/AnimatedElement.ts
- browser/src/slideshow/transition3d/SimpleTransition.ts
Moreover still after slideshow is ended, this patch tries to:
- skip to complete current layer rendering
- skip to complete current slide transition rendring
- skip to complete current animation rendering
- skip to go on with canvas loader rendering
- skip to go on with pause timer rendering
Change-Id: I0fb387a5b7c4fea10bf95f3db5cd03a9d7bd75df
> slideshow: not process left slide layers after quitting from slideshow

- browser/css/device-mobile.css
- browser/css/device-tablet.css
- browser/js/global.js
- browser/src/control/Control.JSDialogBuilder.js
When we used w2-ui, we hid tooltips on mobile devices and tablets. When
we moved to using JQuery's tooltips we didn't carry this over, causing
persistent tooltips when people were touching mobile devices. This was
not ideal.
Rather than hiding these on mobile devices we can show them only on
mouse events, since as you can use mobile devices without a touchscreen
or have touchscreen desktop devices (commonly touchscreen laptops).
We've just added support for touch event detection of the mouseenter
events that we need for this. We don't want to lock touchleave events to
mouse, as we want to close the tooltip if we start tapping on other
things.
> fix(tooltips): Don't display on touch events

- cypress_test/integration_tests/desktop/writer/annotation_spec.js
This reverts commit 8bd7603bd437fe6e30fd16e1c2950c2187ba044b. Somehow we failed always in collapsed annotations...
> cypress: restore Collapsed Annotation Tests

- browser/src/control/Parts.js
- Change the label from "Close" to "OK".
- Disable the OK button until at least one checkbox is selected.
- Add a heading "Show sheets" above the checkboxes.
Change-Id: I8fdabce9508296052f6c2e7741be651ef45df9f8
* Resolves: #10174
> Update sheet selection dialog UI

- browser/src/canvas/sections/CommentSection.ts
- browser/src/control/jsdialog/Util.FocusCycle.js
- browser/src/docstate.js
- browser/src/map/Clipboard.js
Some browsers don't support events like focusin focusout, also browsers may have different behaviour about parent of a focused element.
The issue: commentHasFocus variable is not updated correctly. This prevents cut/paste operations. Because when a comment is focused, cut/paste from document is prevented.
Fix: It's better to check if a modify / reply field is focused via document.activeElement.
This changes the code introduced in below commit:
* https://github.com/CollaboraOnline/online/pull/7634/files
So the fix will be re-checked.
> Use better checks for determining if a comment is focused or not.

- browser/src/control/Control.Toolbar.js
- browser/src/docdispatcher.ts
fixes regression from commit 662a707ec87d0a1855ca81102fa4dd512bece91a Share code for close action
if we open broken file and cancel repair - we end with closed document map is not initialized and dispatcher too, we need to use dummy one to allow close button to close view
> Fix close when map is not present

- browser/html/framed.doc.html
Change-Id: I1f43d4839341e9d1acac617cc6a6a96e2118a51f
* Resolves: # 
In the debug frame, if you let it run it would push the COOL frame down the page as the post message grew.
This does two things:
- add an overscroll limiting the height of the logs
- add a clear button to clear it up.
> debug frame: Limit the messages element in size

- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.JSDialog.js
- Change autofilter from canvas to whole document
- now on browser zoom because we change the parent autofilter dialog will go beyond the canvas and user can see content
- content will be visible for high browser zoom level
- as we now consider autofilter dialog for whole document and not canvas, i have adjusted the some corner case values to be sure at edge of document dialog stays visible
Change-Id: Ib467c3605ff55bf3d5df33979a923bcc31fe4583
* Resolves: # 
> Fix Autofilter dialog position on browser zoom

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Util.StateChange.ts
- browser/src/control/jsdialog/Widget.HTMLContent.ts
problem:
if listbox was initially disabled main container had missing disabled attribute, and because of that MutationObserver was never triggered to enable it
Change-Id: Ibc1686eb03f4099066ff5b1537c90747432aee66
> jsdialog: added missing 'disabled' attribute to listbox

- browser/src/slideshow/SlideShowPresenter.ts
Now that the presenter window is an iframe, its no more able to trigger the
resize event so we need to attach it to the main window.
Change-Id: I208aa90fd52bfa956bd30eebd6e8cd03538776a1
> slideshow: when presenter window is resized, slide is not

- common/Log.cpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- kit/Kit.hpp
- kit/LogUI.cpp
- kit/LogUI.hpp
- scripts/undoStatistics.py
Save documentID to the log, and rewrote reporting script to reorder the file. (because looks like some cases more kit processes wrote into the permanent file at the same time, and their log mixed)
fixed a configuration path problem
fixed a click merge problem
Change-Id: Ibf1281b560d94c7ea9a97614dd1648aaa10f00f7
* Resolves: # 
> fix for log UI Commands

- browser/Makefile.am
We need
- src/layer/tile/CanvasTileUtils.js (included from TileWorker.js) and
- src/layer/tile/TileWorker.js (because we have `this._worker = new Worker('src/layer/tile/TileWorker.js');` in bundle.js
These files have to be present separately in install dir. Whether it's a permanent solution, or a temporary hack, I don't know.
Change-Id: I9d0d21463be0cef10ff95a0cd80226a5fc29fa75
> add missing files to the install dir

- browser/css/jsdialogs.css
- browser/css/jssidebar.css
allows to automatically adjust height of list/tree of styles and show scrollbar if needed, before we showed full list and main scrollbar of sidebar, so checkbox at the end was invisible
[styles-2024-12-18_11.31.05.webm](https://github.com/user-attachments/assets/119a8551-7c0b-4447-8862-3eabade6f9bb)
REQUIRES: https://gerrit.libreoffice.org/c/core/+/178705
> css: sidebar: adjust height of style sidebar

- browser/src/canvas/sections/ShapeHandlesSection.ts
Since the fix for tdf#123874, we've stopped sending "shapeselectioncontent" to iOS. That message provided an SVG which, elsewhere, is used to preview the movement of the shape.
When modifying the preview, we correctly gated it in a check that the SVG was set. Unfortunately, we also introduced a dependency on this SVG ƒor other things: critical pieces for moving shapes such as preventing panning when a shape is being dragged. Instead, it's better to restrict the dependency on the SVG to only where it's needed, as that allows iOS to move shapes even without the SVG existing.
Change-Id: I69c9ea25011dedd31c492e56bf0ef4aca5cfb21f
* Resolves: # 
> fix(iOS): Allow moving shapes

- browser/src/map/Clipboard.js
- ios/Mobile.xcodeproj/project.pbxproj
- ios/Mobile/DocumentViewController.mm
The iOS clipboard handling code has up-until-now not supported much stuff that needed rich context. This patch allows us to store the whole internal clipboard on the system clipboard, letting us copy/paste things like images, or formulas where all referenced cells are included in the copy. This still isn't quite an internal paste, so it doesn't allow things like copying formulas within the same spreadsheet that don't include all their references.
> feat(iOS): Improve clipboard handling

- browser/src/layer/tile/ImpressTileLayer.js
- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
If the slideshow is started when impress is in notes view mode slides have a
wrong size and content is messed up.
Change-Id: I6621f8d756f2c6b6b1bcf478fb50be0fd83d25db
> slideshow: exit notes view before starting the slideshow
