- browser/src/map/handler/Map.SlideShow.js
> Backport #8645: Change convoluted url and name in windowed presentation

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
> Annotation scrolling improvements (backport)

- configure.ac
- debian/changelog
Change-Id: I39c8de7125edc3de3696487b7519dbd2b0717c26
* Resolves: # 
> Bump version to 24.04.1.4

- browser/src/layer/tile/CanvasTileLayer.js
problem:
when try to edit any cell for the first time,
there was console error due to undefined variable
Change-Id: I8a29ad6e0e6243cc55175be0173eceb80bfea877
> calc: fixed js console error

- browser/src/core/Socket.js
- regresssion from 464358ca70f23c999ac864d4c3bc3c56128439d7
Change-Id: If2b20c7960e3c242064fc04425b4f893612f6362
> fix: can't reconnect and get to edit mode after full server shutdown

- configure.ac
- debian/changelog
- ios/Mobile/Info.plist.in
Change-Id: I727f22a5d057b592b3f0d74bef2b33bd273e7699
> Bump version to 23.05.11.1

- browser/src/core/Socket.js
Backport of : https://github.com/CollaboraOnline/online/pull/8950
Change-Id: I90cb6ad849708f4d5250f10df1fedb7e640da4a5
> Backport: initializ UI after server reconnection

- browser/src/core/Socket.js
- Non-edit mode does not initialize after server reconnection
- this patch will fix initialized UI after reconnection
Change-Id: I43405067287dd3f7f134fc9dcabfdcae183724ce
> initializ UI after server reconnection

- scripts/watchdog-cool
Change-Id: I9d3b9b2a405d87bee6c8f242f8c71179abb44005
* Resolves: # 
> add sample watchdog script

- browser/src/control/Control.PartsPreview.js
- **browser: preview: remove unused console logging**
- **browser: preview: update 'createPreview' function**
- **browser: preview: simplifiy _resize function**
> browser: preview: clean up

- net/HttpHelper.cpp
- net/HttpHelper.hpp
- net/HttpRequest.hpp
- test/UnitHTTP.cpp
- test/UnitWOPIFileUrl.cpp
- test/UnitWOPITemplate.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
This reverts commit 9346a5c7f1c69b3989e181b9f42936f0e413afc9.
> Revert "killpoco: replace HTTPResponse in sendFileAndShutdown"

- browser/src/control/Control.PresentationBar.js
This fixes regression from commit ae5e33b30ce834a4028397365c5b447d8f90f0b0 remove-w2ui: convert presentation toolbar to JSDialogs
> Show run presentation icon in Impress slide sorter toolbar

- browser/src/control/Control.Selection.js
- browser/src/control/Permission.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/CommentSection.ts
- browser/src/map/handler/Map.Mouse.js
problem:
comments could not be inserted in calc mobile view if not entered into edit mode
> fixed calc comments in readonly mode

- browser/css/device-mobile.css
- browser/css/jsdialogs.css
- browser/css/spreadsheet.css
copy of https://github.com/CollaboraOnline/online/pull/8964
> formulabar css improvements after darshans work (duplicated to check CI)

- browser/admin/src/AdminClusterOverview.js
Change-Id: If72d27b0b32a00e0105dce08292afa4c792d6cb5
* Target version: co-23.05
> admin: fix gaps between cards when server/card gets removed

- browser/src/core/Socket.js
- coolwsd.xml.in
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Change-Id: Ia6e29a988d85fbb6f622f4d456ad64c6f747cb4e
> indireciton: migration on shutdown

- browser/src/control/Control.PartsPreview.js
- **browser: preview: fix time out resize event**
- **browser: preview: simplify 'isPreviewVisible'**
> clean up previews

- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
https://github.com/CollaboraOnline/online/pull/8978 made it fail even more often, oops. Let's try again.
Change-Id: Idab5a5bac4ac15aa0e13a2d660271a305fad945a
> Fix failing test desktop/writer/top_toolbar_spec.js

- browser/src/control/Control.PartsPreview.js
Change-Id: I4c03ccba4c421ad39e461b9161e964a715b26e0a
* Resolves: # 
> Removes an unused line.

- configure.ac
- debian/changelog
Change-Id: I56c4be6de327c7b678cc9a534b90f7fe2a916190
> Bump version to 24.04.2.1

- browser/html/framed.doc.html
Add CloseSession button.
Add messages from editor view
Also improve spacing of elements.
So that we can more easily tests events output.
Change-Id: I9999654f9d53d44016eeb0ea587cf3f61b000471
cc @hfiguiere
> postMessage test page: Add messages from editor view

- browser/.beforeprettier
- browser/Makefile.am
- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.Mention.ts
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Util.MessageRouter.ts
Change-Id: I575d9e14562b1a77f30d355024a2106d7955fe6a
* Resolves: # 
> Convert Control.Mention.js to Control.Mention.ts

- browser/src/map/Map.js
Change-Id: Idcd7040271e26bad4d04921bcb19dfb0ed45169b
* Resolves: # 
> Fix variable type error in "setDesktopCalcViewOnZoom" function.

- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/SheetGeometry.ts
- browser/src/layer/tile/WriterTileLayer.js
- browser/src/layer/vector/SVGGroup.js
- browser/src/map/handler/Map.Mouse.js
- browser/src/map/handler/Map.TouchGesture.js
Change-Id: Ibc84782abf8e7668d31360e106fc73522fcd4494
* Resolves: # 
> Use simpleRectangle for docLayer._graphicSelection.

- browser/css/spreadsheet.css
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ie5ba30b4080770e51c37e1266e1613c169e58cfa
* Resolves: # 
> Remove unused code and CSS rules.

- wsd/COOLWSD.cpp
Change-Id: I4d1a041f94ead329d9973aaacd85f40001417cf2
* Resolves: # 
> cool#8747 - disable un-necessary fsync'ing.

- browser/src/map/handler/Map.Keyboard.js
Change-Id: Ibea3a7dc30f8e948044cb513ff4f54166a50d162
> browser: fix doclayer de-reference

- browser/src/core/Socket.js
typically can be seen on a fast connection to a NextCloud instance
Change-Id: Ie3431d58cb2499464e1bfac95dcf3b981536a7a2
* Resolves: # 
> initial dark mode not always set

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ib3289dca84d02b7171db2e41f33dd18ba87c0cbf
* Resolves: # 
> Convert cellSelectionArea into simpleRectangle.

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I24686166eadfff8622e10bddaa4893ed821191eb
* Resolves: # 
> Remove some unused lines.

- browser/js/global.js
- browser/src/core/Socket.js
Change-Id: I5cba504273d4fd035a918839001ccb91976ccb16
* Resolves: # 
> explain the relationship of global and bundle 'onopen' handlers

- browser/src/canvas/sections/CellSelectionHandleSection.ts
Change-Id: I3d368e683747f249a5f44171023bd7f5293aca63
* Resolves: # 
> Fix to my silly mistake :)

- browser/css/jsdialogs.css
Signed-off-by: Méven Car <meven.car@collabora.com>
Change-Id: I4b57a1c04dc67620f4ee010e17fff4f9e677d0de (cherry picked from commit 8b2f8916b3490d273c3690125ad18aeb46d69924)
* Resolves: # 
> Add Css rules for custom properties fields

- kit/Kit.cpp
Change-Id: I0caa3300961cd3d9d919691eab77663b5c663bfc
* Resolves: # 
> logging: truncate long payloads before logging them.

- browser/test/load.js
Change-Id: I220d30074c412fe849f746bc7722d5f896544b1c
* Resolves: # 
> perf-test: update for latest substitutions in cool.html.

- browser/src/control/Control.NotebookbarBuilder.js
* Target version: distro/collabora/co-23.05 
backport for #8707
> notebookbar: event prevent default for theme toggle button (backport)

- browser/css/toolbar.css
Change-Id: Ib1e1b1247dc42e721921c6bf1b68726cf0c916e5
> Toolbar-down: Fix Search input field and other elements alignment

- kit/Kit.cpp
Change-Id: I4cf56d0b2aae394a3e2c4f40cf64f0de4de9f418
* Resolves: # 
> use new startThread

- net/HttpRequest.hpp
- test/UnitSaveTorture.cpp
- wsd/FileServer.cpp
Possibly the combination of "gzip" and us being unhelpful about lengths could lead to browser hangs; who can say.
Change-Id: I632dfc46afde3883544292d687bdff023bccc8ac
* Resolves: # 
> Send Content-Length and Connection: close to help browsers.

- browser/css/menubar.css
Change-Id: Ibbd2aed0739af6627d982db954487ad98159500e
* Resolves: # 
> css: decrease max-width at which filename is hidden

- browser/Makefile.am
- browser/css/cool.css
- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.FormulaAutoCompletePopup.ts
- browser/src/control/Control.FormulaUsagePopup.ts
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Widget.TreeView.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
When we start to type a formula in a cell eg: =S
We will see the possible function names in a popup. If we move with "ArrowDown and ArrowUp" and enter, or direcly select a function with mouse, function name will be automatically inserted into cell. Then we will see the usage details of the selected function in another dialog.
Change-Id: Ic06ca0d904770e95bb85ccdf9a73f60b7d5c5eb0
* Resolves: # 
> Introduce new formula auto complete feature

- browser/src/canvas/sections/AutoFillMarkerSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I5f130924455cd29018baf6fbc14c1ceffd29cf46
* Resolves: # 
> Fix coordinate calculation error of cell selection area.

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
Change-Id: I061901d748641ffbb40f60e2fa03fcc31df2cd7e
* Resolves: # 
> Hide Invert Background button until implementation

- README.md
Change-Id: I7814643089e83da2e45ff7bc83df73244cf2d1d4
* Resolves: # 
> readme: Added blurb about the SDK

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- improved color contrast between text area and edge.
- changed --color-canvas for contrast between text and edge area.
Change-Id: I8dd8296901da6ee5ce59704f7e27d8c37d29e8b1
* Resolves: # 
> Improve color contrast in application canvas

- coolwsd.xml.in
Change-Id: Ie804baec41b59fe7418bb7057f8110cd04b64b9a
* Resolves: # 
> fix resquest -> request in coolwsd.xml comment

- browser/css/cool.css
- browser/css/device-mobile.css
- browser/css/toolbar.css
- browser/html/cool.html.m4
- browser/src/control/Control.DocumentNameInput.js
Change-Id: I14c8a715e922d00b2cfd8f67afd7fc2df2dd9d38
* Resolves: # 
> mobile: add save progress bar on top toolbar

- browser/Makefile.am
- browser/src/control/Control.JSDialog.js
- browser/src/control/jsdialog/Util.SnackbarController.ts
Snackbars will appear one after other now.
Add forgotten SnackbarController to Makefile.
followup for: https://github.com/CollaboraOnline/online/pull/9150
> jsdialog: add queue for snackbars

- wsd/COOLWSD.cpp
- wsd/ClientSession.cpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/FileServer.hpp
- wsd: refactor hsts header
- wsd: serve all files through sts
> 23.05: FileServering with STS

- browser/css/device-desktop.css
Change-Id: I6544845526c2e70bee7d6e3b193e9fb4931422c6
> Text droplet (Teardrop): hide it when on desktop

- Makefile.am
- wsd/README.md
* Resolves: # 
Formatted the readme.md for better understanding
> Formatted and add missing .md

- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.UserList.ts
- browser/src/docstate.js
- browser/src/docstatefunctions.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- browser/src/map/handler/Map.Keyboard.js
> Put following state into docstate, fix following on other sheet

- ios/Mobile/Info.plist.in
Change-Id: I82f1a5c253f960c638977d633ff451a18386e513
* Resolves: # 
> iOS: Bump version to 23.05.12

- browser/src/layer/tile/CommentListSection.ts
- browser/src/layer/tile/CommentSection.ts
> annotation: show dialog for conflicting comment modification (backport)

- common/Clipboard.hpp
- test/HttpWhiteBoxTests.cpp
- wsd/ClientSession.cpp
Change-Id: If11229b713174a6c3d1a9794281858d6a8f64294
> cool#9219 clipboard: only accept downloaded data in own format

- kubernetes/helm/collabora-online/templates/hpa.yaml
- kubernetes/helm/collabora-online/values.yaml
Change-Id: I43931c6d19e3bb1695a6d0cf099c79fc0e534114
* Resolves: # 
> k8s: added config option to disable HPA scaledown

- browser/src/control/Control.Menubar.js
Change-Id: Ia4698049476bac11fda84f5f13c1241dd6d2769f
* Resolves: #9232 
> Fix the invert background button in compact view

- browser/src/control/Control.Notebookbar.js
>  Hide Invert background button on Light mode 

- browser/css/mobilewizard.css
- added width for comment section to match it's parent element.
- this will make comment section more visible and wide for mobile users
- This patch will fix the jammed content issue in comment for mobile
Change-Id: I961ca8e500cf1e9afe90fcf3571c5b79d8555d04
* Resolves: # 
> Fix congested comment section in mobilewizard

- common/Session.cpp
- common/Session.hpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/wopi/WopiStorage.cpp
- wsd/wopi/WopiStorage.hpp
use optional isAdminUser to detect when it is missing
> Show server audit if deprecated is_admin is used

- THIRDPARTYLICENSES
Change-Id: I1cb73c839e0234105c222710ca3051195d4b413d
> remove-w2ui: remove notice from THIRDPARTYLICENSES

- common/ThreadPool.hpp
- kit/Kit.cpp
- test/WhiteBoxTests.cpp
Change-Id: I673161ff7ae7c5e1958b5230364dc58b3ef1d923
* Resolves: # 
> cool#9271 - re-start delta thread pool after bgsave.

- browser/src/control/Control.NotebookbarCalc.js
Change-Id: I765a1af634db8901c1c2658b30f9dc2e7a156f4b
- [X ] Code is properly formatted
> browser: Fix View Grid Lines text in tabbed view

- wsd/ClientRequestDispatcher.cpp
Change-Id: Ida61c91eeb959f04ff5002b249d013ba8759c166
> expose pod name in /hosting/capabilities

- test/WhiteBoxTests.cpp
Change-Id: I446214be88e20fbca3093c8bb92481f56f680811
* Resolves: # 
> drop the waitForThreads part

- test/WhiteBoxTests.cpp
Change-Id: I1face168de0ba57a9da491e0f1946cabc7ec0d6a
* Resolves: # 
> fix build failure

- kit/ChildSession.cpp
Change-Id: Ie667b9e65f4130aab1210d6776bbfc6daf084bec
> wsd: appimage: fix template saving path

- browser/src/layer/tile/CanvasTileLayer.js
That's where the action is triggered.
Change-Id: I5d81e068c1b83ae9a66ed3d082784b101e4d4d53
* Resolves: # 
> Put the validity dropdown at the bottom of the cell.

- browser/html/cool.html.m4
- browser/src/control/Control.AboutDialog.ts
- browser/src/map/handler/Map.Feedback.js
- wsd/FileServer.cpp
Change-Id: I04004f416e7bc6cb2c265fe3ebc08f2c250e8009
> wsd: add 'wopi_host_id' to about dialog

- test/UnitSaveTorture.cpp
- test/WebSocketSession.hpp
Change-Id: I7d925e4703cdf9f252b1b3ffcd6716e4b3c87235
* Resolves: # 
> tests: try to catch endless loop waiting for modified status.

- kit/KitHelper.hpp
Change-Id: I2f499920559a0f123303077ed9b475370943253a
A simple optimization PR
> Optimize a bit - no need to use an intermediate stringstream

- browser/Makefile.am
- browser/src/control/jsdialog/Util.OnDemandRenderer.ts
- browser/src/control/jsdialog/Widget.Combobox.js
- browser/src/control/jsdialog/Widget.IconView.ts
- extract "on demand renderer" helper
- convert icon view to TS
> Icon view: convert to TypeScript

- browser/src/canvas/sections/ShapeHandlesSection.ts
Change-Id: Ie89099c73648a8aaaef19d1e41a822bba29a528e
* Resolves: # 
> update z-index of videos.

- cypress_test/integration_tests/mobile/writer/table_properties_spec.js
typeIntoInput was failing. Solution: Wait for the field to fully load before typing
Change-Id: I9c9fc50a1bfa3a579278bfaaf1a5a5e43b5f9f02
> Fix failing test mobile/writer/table_properties_spec.js

- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
Increased wait before inserting comment
Wait was added in a5e6a81cddb9084dc6189901787ebf96324bc1d2
Change-Id: Ia2aa4c901fc57d6700b43c7e0db0380055877081
> Fix failing test multiuser/writer/annotation_spec.js

- net/HttpRequest.hpp
- wsd/ClientSession.cpp
- **wsd: fix unused parameter ‘subjectHash’**
- **wsd: fix ‘ssl’ has not been declared**
> compile fixes

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.IconView.ts
This provides possibility to request icon view entry on demand so it doesn't produce big payload initially. Will improve loading time as style previews can slow down start of the app.
This has to go in first. Later server will provide functionality and will activate the feature by core commit.
> jsdialog: IconView previews on demand

- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
Regressing commit: https://github.com/CollaboraOnline/online/commit/d80689e551866763ca62f9867214e777c781cd50
Change-Id: Iff9026c9223c930be4d31b3891c21a6e95bbffad
* Resolves: # 
> Add mistakenly removed variable to tsManager.

- browser/.beforeprettier
- browser/Makefile.am
- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/src/canvas/sections/URLPopUpSection.ts
- browser/src/control/Control.Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.TouchGesture.js
Change-Id: I2cd85679c6de65fa7f999907a818d7406402b581
* Resolves: # 
> Introduce URLPopUp section.

- browser/Makefile.am
- browser/src/control/transition/FadeTransition.ts
- browser/src/control/transition/Transition2d.ts
- browser/src/dom/transition/shader/2dVertexShader.glsl
- browser/src/dom/transition/shader/fadeFragmentShader.glsl
Change-Id: I4745b6e8d747e68cc8e0264a534ba9bf87d90df8
* Resolves: # 
> Add 2d Fade transition

- browser/src/control/AutoCompletePopup.ts
- browser/src/control/Control.FormulaAutoCompletePopup.ts
- browser/src/control/Control.FormulaUsagePopup.ts
- browser/src/control/Control.Mention.ts
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
Follow-up commit 2acc5a94c9d883d1dc92ca52cb9a92116d177009
Move the "if exist" conditions into event handler
Change-Id: Iefdb36d95f53af79dcc3e7694a68e5cac3b1dfa1
* Resolves: # 
> Reduce code duplication

- cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
Change-Id: Ic1446d2b89ba6f60899181c3748c61cfaa3ee3be
* Resolves: # 
> Fix failing impress hyperlink mobile test.

- kubernetes/helm/collabora-online/templates/poddisruptionbudget.yaml
- kubernetes/helm/collabora-online/values.yaml
Adds an optional [PodDisruptionBudget](https://kubernetes.io/docs/tasks/run-application/configure-pdb/) manifest to the chart
> feat(helm): Add PodDisruptionBudget

- kubernetes/helm/collabora-online/Chart.yaml
- this version includes PodDisruptionBudget from commit 1068646b0931
Change-Id: Icec6f38371153c393f21b813812fcea14cbe93eb
> release: update helm chart version

- .gitignore
Change-Id: Ic32bb0c93c27be4a04cde51ff904ad81871d6d29
> .gitignore coolforkitns

- wsd/ClientRequestDispatcher.cpp
Change-Id: Ic107be34b63ec64e977ddac7957d775c9d711803
* Resolves: # 
> log the X-Forwarded-For header we operate on here

- browser/src/errormessages.js
user would not know what is token and what to do if it expires
Change-Id: I227690c91faec0465165ce4b59ff2d73b79271b7
> browser: give clear message to user about expired token

- wsd/COOLWSD.cpp
It will block main thread if fails.
Change-Id: I420c19f315b70b04e5e73c3dc7c6a93f3d165e34
> wsd: fix async request

- browser/Makefile.am
- browser/src/slideshow/PerformTransition.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/transition/CoverTransition.ts
- browser/src/slideshow/transition/PushTransition.ts
- browser/src/slideshow/transition/SimpleDissolveTransition.ts
- browser/src/slideshow/transition/SplitTransition.ts
> Add Remaining Transition

- browser/src/control/Control.UIManager.js
> Url sanitizer

- browser/src/core/Socket.js
- coolwsd.xml.in
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
* Resolves: # 
* Target version: co-23.05
> Backport shutdown patches

- browser/css/cool.css
Change-Id: I8ebff9ea79b0198cba80fe275c91cadb94c07ce7
* Resolves: # 
> Update the min-width property for username popups.

- common/FileUtil.cpp
- common/FileUtil.hpp
- wsd/COOLWSD.cpp
Change-Id: I4849dae47972be7215c50e06493f4e70d73c2eb7
* Resolves: # 
> ls -lR alike filesystem listing utility

- browser/src/slideshow/PerformTransition.ts
- browser/src/slideshow/SlideCompositor.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/Transition2d.ts
- browser/src/slideshow/transition/FadeTransition.ts
- browser/src/slideshow/transition/NoTransition.ts
> slideshow: Code refactoring for Fade transition type 

- common/SigUtil.cpp
Change-Id: I287c938bfcdbbdb76dd8f1253e52bb167b440a22
* Resolves: #9383 
> cool#9383: build error on FreeBSD

- browser/src/canvas/sections/ShapeHandleScalingSubSection.ts
Change-Id: I961b16e45ebe8e22b07a8a197bb6c96658715ded
* Resolves: # 
> Make the shape preview semi-transparent also when scaling.

- browser/src/canvas/sections/OtherViewCursorSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I3d6e198f7aec53826f1234854367c915b8e5df8c
* Resolves: # 
> Use reference info for Calc other view cursors.

- common/Unit.hpp
- regression from a866719
Change-Id: I21b20aabb4dffad3011b75de8d1f373d495a697d
> fix: coolwsd getting killed on kit segfault

- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- browser/src/map/handler/Map.Keyboard.js
this fixes the case:
- open writer
- press multiple times ctrl + Enter
sometimes you got new page but view was on the old page, so you were not seeing the cursor
> following users fixes

- common/Util.cpp
- common/Util.hpp
- test/integration-http-server.cpp
- wsd/ContentSecurityPolicy.hpp
- wsd/FileServer.cpp
Change-Id: I4f8cef1fb05a6f8fa8f85010adbf8b0ccd8af9e9
* Resolves: # 
> Trim URIs if necessary, and test that.

- browser/.beforeprettier
- browser/Makefile.am
- browser/src/canvas/sections/InvalidationRectangleSection.ts
- browser/src/core/Debug.js
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I837b71bab42070d744f6a61f463c315c9d4c413c
* Resolves: # 
> Use a small section for rendering invalidation rectangles.

- browser/src/canvas/sections/OtherViewCursorSection.ts
- browser/src/layer/marker/Cursor.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/layer/tile/SheetGeometry.ts
Change-Id: Iaadc19dc93cd29d2991768ed061b7cdd4b9ab4d8
* Resolves: # 
> Adjust the cursor heights a bit more.

- test/integration-http-server.cpp
Change-Id: I5dbf95be788fd38f4bd117e4bc36cdc14a2fd153
* Resolves: # 
> Extra trim test for documentation.

- browser/css/toolbar.css
- browser/images/closedoc.svg
So it's more inline with the rest of the icons. Also fix dark mode.
Change-Id: I0b27ecc179a139d34aa574617e0af5c3ef91ae81
> Redesign close document button

- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
> Backport controller patches

- browser/src/canvas/sections/CellCursorSection.ts
- browser/src/docstatefunctions.js
Change-Id: I83231572f4d9c1afa8737c7c05cc96b8a5d1b691
* Resolves: # 
> CellCursorSection: Fix RTL case.

- common/JailUtil.cpp
- common/JailUtil.hpp
- common/Log.cpp
- coolwsd.xml.in
- cypress_test/Makefile.am
- test/run_unit.sh.in
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
Change-Id: I5ce91a2aaefd8c84eecb6aa5d66f492cb8a3becd
* Resolves: # 
> default to using mount namespaces if experimental enabled

- browser/Makefile.am
- browser/css/tooltip.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Tooltip.js
- browser/src/core/LOUtil.js
- browser/src/main.js
- **browser: tooltip: add util function**
- **browser: tooltip: add Control.Tooltip.js file**
- **browser: tooltip: attach listener to buttons**
> accessibility tooltip

- browser/src/canvas/sections/CellCursorSection.ts
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ic26d6b26f967e3de9a9bb6217dbe9e0fb0accc28
* Resolves: # 
> Fix cellcursor visibility issue.

- browser/src/slideshow/Transition2d.ts
- browser/src/slideshow/transition/BarsTransition.ts
- browser/src/slideshow/transition/BoxTransition.ts
- browser/src/slideshow/transition/CheckersTransition.ts
- browser/src/slideshow/transition/CircleTransition.ts
- browser/src/slideshow/transition/CoverTransition.ts
- browser/src/slideshow/transition/CutTransition.ts
- browser/src/slideshow/transition/DiamondTransition.ts
- browser/src/slideshow/transition/FadeTransition.ts
- browser/src/slideshow/transition/NoTransition.ts
- browser/src/slideshow/transition/OvalTransition.ts
- browser/src/slideshow/transition/PlusTransition.ts
- browser/src/slideshow/transition/PushTransition.ts
- browser/src/slideshow/transition/SimpleDissolveTransition.ts
- browser/src/slideshow/transition/SplitTransition.ts
- browser/src/slideshow/transition/UncoverTransition.ts
- browser/src/slideshow/transition/VenetianTransition.ts
- browser/src/slideshow/transition/WedgeTransition.ts
- browser/src/slideshow/transition/WheelTransition.ts
- browser/src/slideshow/transition/WipeTransition.ts
- Remove redundant vertex shader.
- Call prepareTransition from Transition2d.
- Fix canvas width for VenetianTransition.
Change-Id: Iaa06b0f63726a6e8a982f7e3df68d0e4b4c47e82
> Slideshow: Reduce Duplicated Code

- browser/src/slideshow/transition/BarsTransition.ts
- browser/src/slideshow/transition/BoxTransition.ts
- browser/src/slideshow/transition/CheckersTransition.ts
- browser/src/slideshow/transition/CoverTransition.ts
- browser/src/slideshow/transition/OvalTransition.ts
- browser/src/slideshow/transition/PushTransition.ts
- browser/src/slideshow/transition/SplitTransition.ts
- browser/src/slideshow/transition/UncoverTransition.ts
- browser/src/slideshow/transition/WipeTransition.ts
Change-Id: I458fd8b631e4ece1da49f2d9d9ef44a2a16862e3
> enable jscpd ignore for prevent duplication error

- wsd/ClientSession.cpp
Change-Id: I028eacced01ea67baec45a233630a5d0b1c78c75
> wsd: fix ‘ssl’ has not been declared

- browser/src/control/Control.UIManager.js
UI: improved infoBar apperence by adding button for action
Change-Id: I51ce1fba1aa238b913d1fd44bdf54b7355edfdc5
> broswer: sanitize productFAQ url

- browser/src/canvas/sections/OtherViewCellCursorSection.ts
Change-Id: I64e1a2a2c31c06579e312da4d97e185a5e4c84b6
* Resolves: # 
> Adjust other view cell cursor pop up position when needed.

- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
fix in the fallback version of slideshow...
requires also: https://github.com/CollaboraOnline/online/pull/9550
so the request for a video will be successful
> slideshow: fix videos

- .github/pull_request_template.md
Github: Add prettier instruction for code formatting in pull request template
Change-Id: I4ecded23a80d3bd772ce8251d5e4e96f02f9d885
* Resolves: # 
> Github: Add prettier instruction for code formatting in pull request template

- kit/Kit.cpp
- net/HttpRequest.hpp
- net/ServerSocket.hpp
- net/Socket.hpp
- test/WebSocketSession.hpp
- test/WopiTestServer.hpp
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/ContentSecurityPolicy.hpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/QuarantineUtil.cpp
- wsd/RequestVettingStation.cpp
- wsd/ServerAuditUtil.cpp
- wsd/TileCache.cpp
- wsd/TileDesc.hpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/WopiProxy.cpp
- wsd/wopi/WopiStorage.cpp
and
cid#398403 COPY_INSTEAD_OF_MOVE
cid#398404 COPY_INSTEAD_OF_MOVE
cid#398405 COPY_INSTEAD_OF_MOVE
cid#398407 COPY_INSTEAD_OF_MOVE
cid#398412 COPY_INSTEAD_OF_MOVE
cid#398413 COPY_INSTEAD_OF_MOVE
cid#398415 COPY_INSTEAD_OF_MOVE
cid#398421 COPY_INSTEAD_OF_MOVE
cid#398422 COPY_INSTEAD_OF_MOVE
cid#398423 COPY_INSTEAD_OF_MOVE
cid#398430 COPY_INSTEAD_OF_MOVE
cid#398434 COPY_INSTEAD_OF_MOVE
cid#398436 COPY_INSTEAD_OF_MOVE
cid#398437 COPY_INSTEAD_OF_MOVE
cid#398442 COPY_INSTEAD_OF_MOVE
cid#398388 COPY_INSTEAD_OF_MOVE
cid#398395 COPY_INSTEAD_OF_MOVE
cid#398445 COPY_INSTEAD_OF_MOVE
cid#398447 COPY_INSTEAD_OF_MOVE
cid#398454 COPY_INSTEAD_OF_MOVE
cid#398455 COPY_INSTEAD_OF_MOVE
cid#398456 COPY_INSTEAD_OF_MOVE
cid#398458 COPY_INSTEAD_OF_MOVE
cid#398462 COPY_INSTEAD_OF_MOVE
cid#398469 …
> cid#398446 COPY_INSTEAD_OF_MOVE

- wsd/COOLWSD.cpp
NoCapsForKit doesn't chroot so the assumptions don't match, just disable namespaces if nocaps is used.
Change-Id: I399f08bfa1ca1bedde46146a04ca8bb8c0ac617e
* Resolves: # 
> disable Namespaces in NoCapsForKit mode

- browser/src/canvas/CanvasSectionProps.js
- browser/src/canvas/sections/CellCursorSection.ts
- browser/src/canvas/sections/OtherViewCellCursorSection.ts
> gokay's fixes backport

- configure.ac
- debian/changelog
> Bump version to 24.04.5.3

- browser/Makefile.am
- browser/src/slideshow/PerformTransition.ts
- browser/src/slideshow/transition/DiagonalTransition.ts
* Resolves: 
For testing , Transition Icon:
> SlideShow: Implement Diagonal Step Transition

- browser/src/control/Control.StatusBar.js
- browser/src/control/Search.js
- browser/src/layer/tile/CanvasTileLayer.js
calc: fix view jump after search
_searchRequested variable was set on wrong object
also when we requested search - allow to jump
---------------
Fix jsdialog error on search
> cals: fix jump after search (master)

- browser/css/jsdialogs.css
- browser/css/notebookbar.css
Change-Id: I24c93ce1a31a1bbb92071f77cf1ab9479e9dc3f3
> Combobox: decrease height so it aligns with 24px buttons

- browser/src/slideshow/transition/BoxTransition.ts
Change-Id: I7d41a4d6506f451343db8ba679af00bc2f695e63
> fix: reverse box transition slides

- browser/src/control/Control.StatusBar.js
- browser/src/control/Search.js
- browser/src/layer/tile/CanvasTileLayer.js
calc: fix view jump after search
_searchRequested variable was set on wrong object
also when we requested search - allow to jump
---------------
Fix jsdialog error on search
> cals: fix jump after search

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/css/leaflet.css
- browser/css/toolbar.css
- **Status bar: Fix language separator (divider) not being rendered**
- **Toolbars and ruler: Dim toolbar-down, toolbar-up, ruler's border**
> Status bar: Fix language separator (divider) not being rendered and dim toolbar-down, toolbar-up, ruler's border

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/css/leaflet.css
- browser/css/toolbar.css
- **Status bar: Fix language separator (divider) not being rendered**
- **Toolbars and ruler: Dim toolbar-down, toolbar-up, ruler's border**
> [Backport]  Status bar: Fix language separator (divider) not being rendered and dim toolbar-down, toolbar-up, ruler's border

- browser/Makefile.am
- browser/src/slideshow/PerformTransition.ts
- browser/src/slideshow/transition/CombTransition.ts
- browser/src/slideshow/transition/PushWipeTransition.ts
Change-Id: Ie15be32276fbd5398f478d6f8b721f5113a9052d
- Target version: master
> slideshow : Implement Comb Transition

- browser/src/control/Control.Menubar.js
- browser/src/control/jsdialog/Definitions.Menu.ts
Change-Id: I3e8ccdb50702bb940db290186d646d5a23f7169c
> UI: replace conditional format dialog with conditiona manager

- browser/css/jsdialogs.css
- browser/src/control/jsdialog/Widget.ScrolledWindow.js
* Resolves: #7193
- Correct the alignment issues for the "Recent Characters" and "Favorite Characters" sections to match it with libreoffice
- Resolve a potential bug where special characters are not displaying correctly due to an incorrectly named property.
> Fix special characters widget

- browser/css/mobilewizard.css
- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/control/jsdialog/Widget.MobileTabControl.js
> feat(mobilewizard): Use submenu when there's lots of tabs

- docker/from-packages/Dockerfile
Change-Id: I39cc4329fcb640f853d691663fe3ef92619eafbe
> docker: update URLs used

- browser/src/control/Toolbar.js
we only want to show it if there is no prefix
introduced in 18d100b
> Show error only when needed

- browser/html/cool-help.html
Change-Id: I02258c26a2d2e97da94ad30fc1e7c79d8a24bfe8
> Help: missing closing parenthesis

- browser/src/control/jsdialog/Widget.MenuButton.js
Set alt attribute to empty string.
Change-Id: I6732f70135a3ce60fb015e9fbeb72a3d93c2d687
> browser: accessibility: set menubutton alt attribute

- net/NetUtil.cpp
Change-Id: Iefdf0bf6a9e5b6d8c74a8a569ef149a16e1ba255
* Resolves: # 
> canonicalName is stored to, but never read

- wsd/DocumentBroker.cpp
...for the lifetime of coolwsd. The docbroker sticks around, in "isAlive" state with _stop of false.
WopiStorage::downloadDocument (wsd/wopi/WopiStorage.cpp) throws a StorageConnectionException exception so we leave pollThread on the failed downloadAdvance attempt without any cleanup and presumably then appear to later attempts as an active docbroker whose session should be joined to.
Change-Id: I16bc2648657ba0d1f3903f049483f8ff9c88a19e
* Resolves: # 
> if an "advance load" fails. e.g. due to a timeout, it cannot be reloaded

- browser/css/spreadsheet.css
Change-Id: I467acc1ec81fdccd48d76a52bb7bbc39d28e1ba6
> Calc: sheet tabs: center tabs

- docker/from-packages/Dockerfile
Change-Id: I39cc4329fcb640f853d691663fe3ef92619eafbe (cherry picked from commit 43563142cea05309058216a2204a1b75e724096c)
> docker: update URLs used (23.05)

- wsd/FileServer.cpp
Change-Id: If0e561bc276a24c86462d05b5c1bf75f2acb790b
> wsd: logging "host_session_id" parameter

- browser/.beforeprettier
- browser/Makefile.am
- browser/src/slideshow/SlideAnimations.ts
- browser/src/slideshow/SlideShowPresenter.ts
Change-Id: Ica809ccb9298c70c889d436fc30581bc432a9623
* Resolves: # 
> slideshow: create animation tree from animations info

- browser/src/map/Clipboard.js
no mobile/tablet keyboard(on screen) has copy button
Change-Id: Ibc1d6221008187fbbc33ebce7398d815a677dc8f
> clipboard: corrected clipboard message

- browser/src/control/Toolbar.js
> uno: fix CallPythonScript calling js error

- test/UnitInitialLoadFail.cpp
Change-Id: I9337c18c550a70cc8e1673ba762cbf11384f2d71
* Resolves: # 
> WaE: -Werror,-Winconsistent-missing-override

- browser/js/sanitize-url.js
- browser/src/control/Control.Infobar.js
* Target version: distro/collabora/co-22-05
> sanitize URL

- browser/css/cool.css
> Font of user tooltips has become serif (24.04)

- browser/src/control/Control.JSDialogBuilder.js
regression from b238f7e
Change-Id: Ide37eb5dddde34f7ccaf15858ca7b0e4069c0636
> UI: PushButtonControl: Fix alignment in mobile

- configure.ac
- debian/changelog
Change-Id: I12329865b3e6d10e4dae6dda2bf0f53f00587462
> Bump version to 24.04.5.4

- configure.ac
- debian/changelog
Change-Id: I12329865b3e6d10e4dae6dda2bf0f53f00587462
* Target version: 24.04
> Bump version to 24.04.5.4 (24.04)

- configure.ac
- debian/changelog
Change-Id: I1b9d36175aaba3feb14845e14b82e029eb3726ff
> Bump version to 24.04.6.1

- browser/src/control/Control.Menubar.js
Change-Id: I284ac6eb65af8c13fa5fd64b9538b9a76574098a
* Resolves: #9630 
> Add invert background button to mobile view

- wsd/README.md
Mostly copied from
<https://github.com/CollaboraOnline/online/pull/9493#issuecomment-2237455110>.
Change-Id: Ia94a3b0f2d431c8b1d44a0953704c5de62bc1176
> wsd: update outdated doc wrt gdb and capabilities

- browser/css/spreadsheet.css
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileSearchBar.ts
- browser/src/control/Control.SheetsBar.js
- browser/src/control/Control.StatusBar.js
- browser/src/control/Control.Tabs.js
- **JsDialogBuilder: add press and hold event for next and previous related commands**
- **UI: PushButtonControl: Fix alignment in mobile**
> private/pedro/Backport PR 9561 n 9662

- browser/src/slideshow/RenderContext.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
Change-Id: Ib92f50176d30ae46b6ef9a4cfc7a62c736170a23
* Resolves: # 
> slideshow: enable first slide transition

- debian/apparmor-profile
- debian/control
- debian/rules
See: https://wiki.debian.org/AppArmor/Contribute/FirstTimeProfileImport
Change-Id: I2451cfc222b6745307554fde37870717204e8a99
* Resolves: # 
> apparmor profile for coolwsd

- browser/Makefile.am
- browser/src/slideshow/CanvasLoader.ts
- browser/src/slideshow/RenderContext.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/Transition2d.ts
Change-Id: I82a4e2f596ddc71606ebe68b46f0e779d1944aa4
* Resolves: # 
> slideshow: add animation loader

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
On Android the document loading progress bar had regressed so it no
longer moved along as the document loaded. Instead, it stayed at 0%
until the document loaded, when it disappeared without having moved at
all...
...this was a known regression from
https://github.com/CollaboraOnline/online/pull/8957 -- known as in
"known before we merged it". We decided background save was important
enough that breaking the -- poor as discussed in the next paragraphs --
progress bar was worth merging it, and we would fix the regression
later. This is that fix.
The fix here still freezes for a surprisingly long time on "empty" -
enough that I wonder if there's something freezing the UI thread during
load - however it is at a similar level to before the regression and is
a definite improvement over the …
> fix(android): Restore progress bar

- common/Log.hpp
- common/Unit.hpp
- test/.gitignore
- test/UnitPerf.cpp
- test/traces/perf-calc.txt
- test/traces/perf-draw.txt
- test/traces/perf-impress.txt
- tools/Replay.hpp
- wsd/DocumentBroker.cpp
* Resolves: # 
Working on issue #9276
Signed-off-by: elliotfreebairn <elliot.freebairn@collabora.com>
Change-Id: I868a0a1c91b30392ab002ce149cefae0dd3036cc
>  feat: Changes to UnitPerf measuring

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.UserList.ts
- **browser: accessibility: fix 'arial-label' property to user list button**
- **browser: accessibility: fix 'aria-label' to all buttons**
> arial-label

- .git-hooks/pre-commit
Change-Id: Ibb7d7523bf64f7a18ee6f741caa3d94c5a3bf426
* Resolves: #9601
Before committing checks that files are prettier formatted and if not it will fail to commit.
> add prettier check to pre-commit

- browser/css/notebookbar.css
> Styles preview: don't use margin

- .git-hooks/pre-commit
Change-Id: I92d1fb05c804d6a734d1def8b49c75456b99cd3f
* Resolves: # 
> Git: Improve error message for prettier check on pre-commit :)

- kit/ChildSession.cpp
- net/WebSocketHandler.hpp
> insertfile: show more logs when we fail

- browser/src/slideshow/CanvasLoader.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/SlideShowPresenter.ts
fixes regression from commit d23168f7604b655c159d3e45f9307ac1133909c7
slideshow: add animation loader
> slideshow fix disabled canvas and cleanup

- browser/src/slideshow/SlideShowPresenter.ts
Change-Id: I4ba7343db60725a3fbb5ba1cac4449cc928421a7
> slideshow rework: bugfix: go backward triggers transition

- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/Transition2d.ts
Change-Id: I570e46b3ad7ef370938c6c46066bd95be8f20fe4
* Resolves: # 
> slideshow: Improve readablity of cord matrix

- browser/src/control/Control.Menubar.js
Change-Id: I5658869c7f901dfdec26c7329f48da54bb179c0e
* Resolves: #9746 
> menubar: disabled hideMenuBar button in readonly mode

- browser/src/layer/tile/CalcTileLayer.js
Change-Id: Ibf717a425aa9ee98aec6dd5044e96344a0351796
* Resolves: # 
> Calc: Hide text cursor when insert mode is set to false.

- README.md
- docker/from-source/build.sh
and the README.md wrt tinderbox too while I'm at it
Change-Id: I7af8eae3e7db5abae047f395aae6b368fdcacacd
* Resolves: # 
> update docker script to default to current core co-24.04 branch

- browser/js/global.js
- test/integration-http-server.cpp
- wsd/FileServer.cpp
It is assigned JSON object which uses quotes.
Also parse the variable at initialization.
Change-Id: Ie87869bdf2d6e278144c0cb1a0b5519a645fca9c
* Resolves: # 
> Use base64 string for UI_DEFAULTS variable. 

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I84cc7aebb7d41edef73ead0ab790a5de65abedd9
* Resolves: # 
> Check null pointer while closing the file.

- browser/src/control/Control.NotebookbarImpress.js
Fixes https://github.com/CollaboraOnline/online/issues/9801
Change-Id: Ic1bc7f9ac55a6da7d19e0bd8e85ed67386bb8bae
* Resolves: #9801 
> impress/draw: Fix ChangeBezier button label

- common/Log.cpp
- common/Session.cpp
- common/Util.cpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- net/HttpRequest.hpp
- net/NetUtil.cpp
- test/UnitPerf.cpp
- tools/Replay.hpp
- tools/Tool.cpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/FileServer.cpp
- wsd/RequestDetails.cpp
- wsd/Storage.cpp
- wsd/TileCache.cpp
and
cid#410829 COPY_INSTEAD_OF_MOVE
cid#410827 COPY_INSTEAD_OF_MOVE
cid#410825 COPY_INSTEAD_OF_MOVE
cid#410822 COPY_INSTEAD_OF_MOVE
cid#410820 COPY_INSTEAD_OF_MOVE
cid#410817 COPY_INSTEAD_OF_MOVE
cid#398543 COPY_INSTEAD_OF_MOVE
cid#398539 COPY_INSTEAD_OF_MOVE
cid#398538 COPY_INSTEAD_OF_MOVE
cid#398531 COPY_INSTEAD_OF_MOVE
cid#398525 COPY_INSTEAD_OF_MOVE
cid#398522 COPY_INSTEAD_OF_MOVE
cid#398516 COPY_INSTEAD_OF_MOVE
cid#398515 COPY_INSTEAD_OF_MOVE
cid#398514 COPY_INSTEAD_OF_MOVE
cid#398509 COPY_INSTEAD_OF_MOVE
cid#398507 COPY_INSTEAD_OF_MOVE
cid#398500 COPY_INSTEAD_OF_MOVE
cid#398495 COPY_INSTEAD_OF_MOVE
cid#398494 COPY_INSTEAD_OF_MOVE
cid#398487 COPY_INSTEAD_OF_MOVE
cid#398484 COPY_INSTEAD_OF_MOVE
cid#398482 COPY_INSTEAD_OF_MOVE
cid#398478 COPY_INSTEAD_OF_MOVE
cid#398477 …
> cid#410830 COPY_INSTEAD_OF_MOVE

- Makefile.am
Change-Id: I3315840a8f265c6990071065c4254b8e90e778dc
* Resolves: # 
> add debian/apparmor-profile to EXTRA_DIST

- browser/Makefile.am
Resolves #9818
Change-Id: Ia2005dd4b844bd0b2ba65c2a6d71a1a535889f10
> Fix Hyperlink button tooltips  not being translated

- browser/Makefile.am
- browser/src/slideshow/PauseTimer.ts
- browser/src/slideshow/SlideShowPresenter.ts
Change-Id: I1a8da69ba7c2f8f4f573c256891b8cd6fa03f5fd
* Resolves: # 
> slideshow: repeat slideshow

- browser/src/control/Control.Menubar.js
- browser/src/docdispatcher.ts
- browser/src/slideshow/SlideShowPresenter.ts
> Slideshow: Enable presentation from the current slide in compact view 

- net/AsyncDNS.hpp
- net/HttpRequest.hpp
- net/NetUtil.cpp
- net/NetUtil.hpp
- test/HttpRequestTests.cpp
- test/UnitProxy.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/ProxyRequestHandler.cpp
- wsd/wopi/CheckFileInfo.cpp
- wsd/wopi/CheckFileInfo.hpp
> use more async dns

- wsd/wopi/WopiStorage.cpp
Change-Id: I65ee775c584317d6dff720d009de8fe9874bfc8c
Commit f6ce37b579c1753e61a71788a78bb25d5d60eb1d created the change and regression,
master branch failed to compile
> Adopt WopiStorage::uploadLocalFileToStorageAsync() to ConnectFailCallback

- browser/js/global.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/core/Socket.js
- browser/src/docdispatcher.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Map.js
- don't use additional variable to store state, use prefs
- convert menubaritem in Nb to customtoolitem
- use dispatcher for sharing the code
followup for: https://github.com/CollaboraOnline/online/pull/9842
> a11y: simplify state handling

- browser/src/slideshow/PauseTimer.ts
- browser/src/slideshow/SlideShowPresenter.ts
fix: Slideshow repeat show last slide after pause countdown for few seconds
Change-Id: I99b8458f72c67ce9bb5c088c4e1ed6d2ff9273a5
* Resolves: # 
> fix: Slideshow repeat show last slide after pause countdown for few seconds

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ica2d5ca2b6a7ba65a9b370c5b8197dbc7298ea8b
* Resolves: # 
> this 'undefined' check doesn't look right

- browser/src/control/Control.IdleHandler.ts
this activate is called when we reconnect, but with the right timing we can have no docLayer here, so we can't tell that this is calc, and so end up requesting annotations without requesting calc geometry. The annotations then arrive before geometry does and on positioning the comments we fail with exception on use of the undefined geometry.
reproducible with:
make run-mobile spec=calc/annotation_spec.js
cy: command ✘  uncaught exception    TypeError: Cannot read properties of undefined (reading 'getCellRect')
cy:command ✔ error:    Cannot read properties of undefined (reading 'getCellRect')
TypeError: Cannot read properties of undefined (reading 'getCellRect')
at NewClass._cellRangeToTwipRect (.../src/layer/tile/CanvasTileLayer.js:1032:53)
at CommentSection.adjustCommentNormal …
> on reconnect of calc, annotations requested before geometry is available

- .gitpod-files/coolwsd-gitpod.xml
Change-Id: If626943a71e808df9ef59168a42bc65849da061d
* Resolves: # 
> sync gitpod config with main coolwsd.xml

- net/NetUtil.cpp
there are two back to back "if (fd < 0)" checks here
Change-Id: I4eb39673ec6dca1d3678228ba21f06579aee4961
* Resolves: # 
> duplicate check for failed fd

- wsd/FileServer.cpp
This grows the largest file we cache to accommodate for WASM files.
> wsd: cache WASM files and serve statically

- Makefile.am
Change-Id: I379c8509619fcc16f92807f22ec7232142fc0331
* Resolves: # 
> fix unary operator expected message

- browser/package.json
- browser/src/control/Control.ColumnGroup.ts
- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.Header.ts
- browser/src/control/Control.RowGroup.ts
- browser/src/control/Control.RowHeader.ts
- browser/src/geo/LatLngBounds.js
reduce number of lines so we will check duplication faster...
only by 1 this time :)
> duplicate check: reduce number of lines

- browser/src/control/Control.Menubar.js
- wsd/DocumentBroker.cpp
Change-Id: Ie9bea24ceae793f466ae7821022bc5ee61ad9430
* Resolves: # 
> Prepare Online side for readonly comment editing.

- browser/src/slideshow/PauseTimer.ts
slideshow: Improve slideshow repeat performance by reusing the off-screen canvas
We usually create an off-screen canvas to render text, which is then loaded into WebGL to display on the WebGL canvas. Previously, a new canvas was created each time, which negatively impacted performance. Now, we reuse the same canvas and simply update the text on it.
Change-Id: I8630c2c77dac2e2f77fa6940b86912c666d2a51a
* Resolves: # 
> slideshow: Improve slideshow repeat performance by reusing the off-screen canvas

- browser/src/layer/tile/CanvasTileLayer.js
since the start of the scroll, reset on end of scroll
Change-Id: I2f3e79d9f34ddcdd5b7ad64f35f4d81ee1fadd6d
* Resolves: # 
> during a scroll don't reissue tilecombines requests already issued

- browser/src/control/Control.NotebookbarBuilder.js
Change-Id: Icd816a326bc0264400f375444cf2e165d8f2e9ac
* Resolves: # 
> calc: added html entry in downloadas menu

- browser/src/map/handler/Map.Keyboard.js
For clash in Safari browser.
Change-Id: Ib7482638763477363968bf4b05b5e63599de4c1d
* Resolves: # 
> Add CTRL + Alt + R combination for insert comment command.

- browser/css/jsdialogs.css
- browser/images/lc_serverauditerror.svg
- browser/images/lc_serverauditheader.svg
- browser/images/lc_serverauditok.svg
- browser/src/control/Control.ServerAuditDialog.ts
- **Server audit dialog: remove extra internal border**
- **Server audit dialog: Add additional icon and improve existing ones**
- **Server Audit Dialog: Allow user to access Help urls at all times**
> private/pedro/server audit dialog Ui n help visibility

- android/lib/src/main/cpp/androidapp.cpp
- common/CommandControl.cpp
- common/Simd.cpp
- common/Util.cpp
- common/Util.hpp
- fuzzer/Admin.cpp
- fuzzer/HttpResponse.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- net/HttpHelper.cpp
- net/HttpRequest.hpp
- net/Socket.cpp
- net/WebSocketHandler.hpp
- test/HttpRequestTests.cpp
- test/HttpTestServer.hpp
- test/HttpWhiteBoxTests.cpp
- test/RequestDetailsTests.cpp
- test/httpcrashtest.cpp
- test/httpwstest.cpp
- test/integration-http-server.cpp
- test/test.cpp
- tools/Replay.hpp
- wsd/COOLWSD.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/FileServer.cpp
- wsd: split getVersionInfo into two getters
- wsd: restrict config_version.h
- wsd: header cleanup
> Header Cleanup

- browser/html/cool.html.m4
- browser/src/control/Control.AboutDialog.ts
- common/Util.cpp
- common/Util.hpp
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
Change-Id: Ibad81f5f90cdfdd909ed9f6370147c93119e9578
> geolocation_setup: send "TimeZone" with coolserver message

- browser/src/map/handler/Map.Keyboard.js
For clash in Safari browser.
Change-Id: Ib7482638763477363968bf4b05b5e63599de4c1d (cherry picked from commit c2c27e5517a937301c27d177fcf45ad2bd0f5096)
> Add CTRL + Alt + R combination for insert commenet command.

- browser/src/slideshow/RenderContext.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/transition/MicsShapeWipeTransition.ts
Change-Id: Ib03b2795ee2721aa151c83b96831680bc330540c
* Resolves: # 
> slideshow: delete textures of slides, videos when not used

- browser/src/app/GraphicSelectionMiddleware.ts
regression from: commit 1af37de
> Fix TypeError for calcInputBarHasFocus

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.UIManager.js
Change-Id: Ic738caebf6690f8fea090a689a5abef54e906a5d
* Resolves: # 
>   Mobile: Show status checkmark next to the invert background button 

- browser/src/control/Control.Menubar.js
Change-Id: I62791c49b0ca390558e8467390e1cb6fe72890f6
> calc,impress: added html option in compact mode downloadas submenu

- browser/src/canvas/sections/CommentListSection.ts
Change-Id: Ifb97d0d41ed33ce2b0edb4cd84dc0301d42a8302
> show thread options only on root comment

- ios/Mobile/Info.plist.in
> chore(iOS): bump version to 24.04.7

- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/jsdialog/Definitions.Menu.ts
Change-Id: I48e25d8e50964a5a71ab0af55fc10f803cf9a0c0
* Resolves: # 
> Slideshow: Enable presentation from the current slide for Tabbed view

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarWriter.js
+ Correct the zotero iconURL aliases
+ Added unoAccessibilityCheck class
- added class for Accessibility option inside review tab
- needed for integration with different theme.
> Corrected zotero icon aliase and added class for accessibility check

- browser/css/toolbar.css
- browser/src/control/Control.TopToolbar.js
- browser/src/control/Control.UIManager.js
Change-Id: I703acfb96491e264f498cc0945ef5d052d4f46ae
* Resolves: #9749 
> toolbar: make fold btn visible in compact mode

- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/SlideCompositor.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/MetaPresentation.ts
Removed duplicated code btw LayersCompositor and MetaPresentation
Removed also unused code.
This patch fixes also wrong hidden slide handling.
Change-Id: I433c97c49354c45c1ebc76f6cacb2f368063cf84
> animation engine integration: clean up MetaPresentation LayersCompositor

- browser/src/map/handler/Map.SlideShow.js
Change-Id: I690893218eb5a49538a75e60f9f481549ecf3f6a
* Resolves: # 
> Fix JS error in separate presentation window.

- wsd/ClientRequestDispatcher.cpp
Some handlers, like handleClientProxyRequest, used in the richdocumentscode  Nextcloud 'Built-in CODE Server' case, launch a task that will consume the message contents later, so we shouldn't consume the body in ClientRequestDispatcher::handleIncomingMessage.
While some like the file server, have already handled the message and we do need to discard the message contents (cool.html POST) because we expect multiple requests per socket and leaving the residue behind trashes that.
> repair richdocumentscode case

- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/engine/AnimatedElement.ts
- browser/src/slideshow/engine/MetaSlide.ts
- browser/src/slideshow/engine/SlideAnimations.ts
- browser/src/slideshow/engine/animationnodes/AnimationBaseNode.ts
- browser/src/slideshow/engine/animationnodes/AnimationTransformNode.ts
- browser/src/slideshow/engine/animationnodes/NodeContext.ts
- fix bug: some animations were not added to the queue
- provide layer to the AnimetedElement
Core side patches:
- https://gerrit.libreoffice.org/c/core/+/173050    (initVisibility property for hiding objects which will appear later)
> slideshow: fetch correct layer for AnimatedElement

- browser/html/cool.html.m4
- browser/src/control/Control.AboutDialog.ts
- browser/src/core/Socket.js
Change-Id: If0934089c2dbaa95ddfd345b2c360360c51640e4
* Resolves: # 
There are JS errors in about dialog. This PR fixes the issues.
> Fix JS errors in about dialog.

- browser/src/control/Control.FormulaAutoCompletePopup.ts
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ia07c579b3bc81ce73f40e86e6e07a02098e7bf4c
- I tested the following with following partial test cases:
1. =SUM(te;te)
2. =SUM(te
3. =SUM(te; MAX(testrangename1;testrangename2)
4. = SUM(te; test1)
> calc: fix: named-range can't be used in function like SUM

- browser/html/cool.html.m4
Change-Id: Ia0c40a1d094d62af1a1c4471f14ead01cfe470aa
* Resolves: # 
> Wrap about dialog elements inside a "dialog" element.

- browser/admin/src/AdminSocketLog.js
- browser/src/control/ColorPicker.ts
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/control/jsdialog/Widget.Combobox.js
- browser/src/control/jsdialog/Widget.IconView.ts
- browser/src/layer/FormFieldButtonLayer.js
- browser/src/map/Map.js
Change-Id: I752567574eb5d1ef69953db44cadeaf83bc21a1e
* Resolves: # 
> Some cosmetic changes for removing element content.

- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/SlideCompositor.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/AnimatedElement.ts
- browser/src/slideshow/engine/MetaPresentation.ts
- browser/src/slideshow/engine/animationnodes/AnimationBaseNode.ts
Change-Id: Ib0e86df7f4a60f99f09177fb0dac883c69dfd982
> slideshow rework: initial support for rendering and playing animations

- browser/src/control/Control.StatusBar.js
update edit permission indicator based on WOPI parameters received
Change-Id: I83a743f8aff646e357ce1a0e73abf9d3db99280e
> UI: indicate edit permission in status bar

- browser/src/canvas/sections/CommentListSection.ts
Change-Id: Ia6b290af30dfda8a4b9e1502456cf5cd695eb6f6
> WIP: sw: annotation: add option to promote reply to rott comment

- browser/src/slideshow/transition/FallTransition.ts
- browser/src/slideshow/transition/HelixTransition.ts
- browser/src/slideshow/transition/PermTextureTransition.ts
- browser/src/slideshow/transition/ReflectionTransition.ts
Change-Id: I8e131a691a5616a8636af48919d290e3c3ea7491
* Resolves: # 
> Slideshow: use the correct displaySlides_ method for transition

- browser/src/slideshow/LayerDrawing.ts
followup for commit b8a951fa25db717724a6ff469b6d5ce3d1a873af slideshow: don't cache fields for now
somehow the previous patch was not working after the merge
> slideshow: do not cache page numbers

- browser/js/l10n.js
Change-Id: I736c5749642a0830d3c38d9c100a1f25d2c6d9aa
* Resolves: # 
> Set html language to the user's language.

- browser/src/slideshow/SlideShowPresenter.ts
it was not fixed previously after rebase ...
> slideshow: fix start from current slide

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
please click to exit presentation - was not working regression from commit bb8b7dadee8ee360ce43a8433730484e8ccaca22 slideshow: fix present from current slide
> slideshow: fix exit on click

- browser/css/cool.css
- browser/html/cool.html.m4
- browser/js/global.js
Change-Id: Iad038bf4bca1ff3b8ae7cf52ef50e45ecce59207
* Resolves: # 
> Add a page load indicator until all files are loaded.

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
* Resolves: # 
This implement the interactions in impress slideshow.
Requires 
~~Includes that enable the UI (not necessary for this patch, useful for testing it) 
https://github.com/CollaboraOnline/online/pull/9836~~
> implement the interactions in impress slideshow.

- test/UnitWOPILock.cpp
- wsd/ClientSession.cpp
- wsd: handle on-document-load events only once
> Document Load Event

- browser/src/slideshow/engine/SlideShowNavigator.ts
Change-Id: I764fc569d6a56d13c33d4817a0870d221966d997
* Resolves: # 
> slideshow: use clientWidth/clientHeight for the mouse clicks

- kit/Kit.cpp
fix this low hanging issue anyway
Change-Id: Ib105339bc94e767b1bcfe87a06e5edd7fc932ec4
* Resolves: # 
> fix anyInputCallback

- browser/src/control/Control.StatusBar.js
Change-Id: Ic7616a1d5a839a7dadbac765a4f8a469ffd0e946
> UI: indicate write protect status by snackbar

- kubernetes/helm/collabora-online/templates/network_policy.yaml
- kubernetes/helm/collabora-online/values.yaml
- I have tested some of the scenarios from https://github.com/ahmetb/kubernetes-network-policy-recipes
Change-Id: I852cd8a533f2591c5eed2a83235634b521db4eb8
* Resolves: # 
> helm: added support for network policy

- browser/css/menubar.css
- browser/css/notebookbar.css
- browser/css/toolbar.css
- use available space for document name.
- make the title bold for more visibility.
Change-Id: Ia3513708ac831ab4eca6cc8f11a0694c2651a07a
* Resolves: # 
> Display the name of the document more completely

- net/NetUtil.cpp
Change-Id: Ie0d9e547dc9b4803ea95848c76302601a996c53a
* Resolves: # 
> make this thread local

- browser/css/cool.css
- browser/src/canvas/sections/URLPopUpSection.ts
- browser/src/map/handler/Map.WOPI.js
When the preview of the link is shown, the position of the popup needs to be re-adjusted. Or if the link increases the height of the popup, popup's position overlaps with the current cursor position.
Also added borders to arrow div.
> Fix hyperlink popup position.

- browser/Makefile.am
- browser/src/slideshow/operation/RotateAndScaleDepth.ts
- browser/src/slideshow/transition/Venetian3dTransition.ts
**Slideshow: Fix Venetian horizontal transition**
Change-Id: I51f6d06ca90a52b8814e6043bf0a0ab39160f2a7
* Resolves: # 
> Slideshow: Fix Venetian horizontal transition

- browser/js/global.js
- browser/src/control/Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/Clipboard.js
Modify ClipboardApi checks.
Merge read and write permission checks.
Rename the cookie name to "clipboardApiAvailable".
Tested on FF 131 flatpack version.
> Modify ClipboardApi checks.

- browser/html/debug.html
- browser/html/framed.doc.html
- browser/html/framed.html
Change-Id: Ieaa9824c7f569965f0ac8ebb9e8f92e8843195c0
Seems bests to have it here, even though it is only necessary for XSS but it spread the knowledge and could prevent issues
cc @hfiguiere
> browser/html: allow fullscreen for dev pages

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.LokDialog.js
- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.UIManager.js
- browser/src/docdispatcher.ts
- browser/src/layer/tile/CanvasTileLayer.js
calc: edited cell on exit of the only user
steps to reproduce:
1. open calc
2. type something in the formulabar but don't accept it (no enter)
3. close the app using "X"
result was: we didn't save cell's content
> calc: edited cell on exit of the only user

- browser/src/canvas/sections/ShapeHandleScalingSubSection.ts
Change-Id: Id340ab65134b09621d2a965c2dc27e4204586f92
* Resolves: #5147 
Keep the ratio of the image/shape when Ctrl+Shift are pressed.
> feat(UI): Holding Ctrl+Shift to preserve the image ratio when resizing

- Makefile.am
- coolwsd.spec.in
- debian/coolwsd-deprecated.install
- debian/coolwsd.install
- man/coolconfig.1
- man/coolconvert.1
- man/coolforkit-caps.1
- man/coolforkit-ns.1
- man/coolmount.1
- man/coolwsd-systemplate-setup.1
- man/coolwsd.1
Change-Id: I18176bdff0c839ae4d0965810e26bb193d0e9a17
* Resolves: # 
* Target version: master & distro/collabora/co-24.04
> do not install man pages of deprecated binaries with the main package

- browser/src/control/Control.JSDialogBuilder.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
1. open writer
2. select some default formatted text
3. click on left side of background/highlight button (not arrow)
result: become black
expected: be still transparent
> jsdialog: transparent color apply

- browser/src/control/Control.ContextMenu.js
- browser/src/unocommands.js
Change-Id: I92f6a1e27cbbd81eab8214cb69e449d7d561330f
> added "ContentControlProperties" to context menu

- browser/src/canvas/sections/URLPopUpSection.ts
- cypress_test/integration_tests/desktop/calc/clipboard_spec.js
Change-Id: I9f0900609fa3001230898f2056d03b3a2f6831a9
* Resolves: # 
> Reposition the URL PopUp element when it's off the borders.

- browser/Makefile.am
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.NotebookbarBuilder.js
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/control/jsdialog/Widget.ColorPickerButton.js
- browser/src/control/jsdialog/Widget.MobileBorderSelector.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
solves issue with not remembered transparent (no fill) color selected from the picker
> jsdialog: transparent color in picker

- browser/src/slideshow/SlideShowPresenter.ts
avoid infinite reccurency... mistake when solving conflict
> slideshow: fix getting the document node

- browser/src/slideshow/SlideShowPresenter.ts
it fixes regression introduced in commit a9985a414f9f60299e7ea42e8cee2e0646ff6a25 cypress: run new slideshow in iframe
> impress: fix selection of objects

- wsd/COOLWSD.cpp
Change-Id: I9baac88e1f5a73097221283ce8afcc2fdb00a676
* Resolves: # 
> Use new configmgr static-ization to reduce shared page dirtying.

- browser/src/control/Control.Toolbar.js
Change-Id: I04c34ab13ca1d45de1ada3ddeb656d00bbc0447c
* Resolves: # 
> condition format: fixed incorrect parameters in function call

- browser/html/debug.html
- this is blind fix I can't reproduce it
Change-Id: Idcbca55ace10b2afd3f60ba391b474e00c52f847
* Resolves: # 
@mcecchetti  I think in your environment some extension is trying to send postmessages which is not in json format hence the error
> fix: [object Object] not valid json error

- browser/src/slideshow/engine/AnimatedElement.ts
It seems that we create too many webgl context because of running transition
filter animations for shapes.
Now we clear the gl context for animated elements at least when we switch to a
new slide.
Change-Id: I708e13c455d69ea8a63fc1b02b3121c8dfd6d568
> slideshow: fix lost GL context

- browser/html/debug.html
- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.Mention.ts
- browser/src/layer/marker/A11yTextInput.js
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.WOPI.js
* Resolves: #10047 & #7923 
I tested the following things thoroughly for the PR manually
1. Document
2. Comment
1. Document
2. Comment
> Debounce mention user query

- browser/src/control/Control.Mention.ts
Change-Id: Id7f3ef6aff3124ce26f6843a1a00c11556190a38
> mention: popup position should be fixed unless '@mention' goes to newline

- browser/src/control/Control.Mention.ts
Change-Id: I75d4f92789798687f9b3352475db7a8ee863b293
> fix: @mention in comment doesn't send 'UI_Mention selected' postMessage

- browser/css/jsdialogs.css
- browser/css/mobilewizard.css
Change-Id: Idb2c0f27b6f2d9bfcc73ea6623ae6eee296501ff
* Resolves: https://github.com/CollaboraOnline/online/issues/10235
> fix: overflowing Button in Function Wizard

- browser/css/cool.css
- browser/css/jsdialogs.css
- browser/css/notebookbar.css
Issue that came up with its follow ups
db10c453e95f732d85c489fe8da8708cec0ad09c
https://github.com/CollaboraOnline/online/pull/10027
Change-Id: I6c9401e9f3a37fd604a2598388be64f026efce21
> Fix sizes on color picker, dropdown and notebookbar btn

- browser/css/jsdialogs.css
Change-Id: Ie034a0c766803a3cd3f1e5ad02f1228393289348
* Resolves: https://github.com/CollaboraOnline/online/issues/10238
> fix: formula field overflow on function wizard window

- kit/ChildSession.cpp
append the required into to the uno:Signature commmand, needed since core commit:
commit 2990c7ea4da17e555903ff8854c03b71aa7ecddd (HEAD -> distro/collabora/co-24.04, origin/distro/collabora/co-24.04) CommitDate: Tue Oct 22 15:16:36 2024 +0200
cool#9992 lok doc sign: never remember previous .uno:Signature params
later we probably can remove the equivalent from the initial initializeForRendering params
Change-Id: If6468f686d6a01e3a76558f670fe4de30db9c007
* Resolves: # 
> fix uno:Signature cypress test, etc.

- browser/src/layer/marker/TextInput.js
It was old code before following rework which used unfollowAll - now it it too aggressive. When user
does any interaction we should enter "follow me"
mode not "turn off" the following.
this is followup for commit 153974a35cfbfb79cefd859bf1f3623523dfa229 writer: when navigator is used, follow the cursor
> user following: do not turn off when typing

- browser/src/control/Control.UIManager.js
- browser/src/slideshow/PresenterConsole.js
- configure.ac
- cypress_test/Makefile.am
- cypress_test/integration_tests/desktop/impress/presenter_console_spec.js
- cypress_test/package.json
- cypress_test/support/index.js
Change-Id: I32ac343cf22265e4d2eaf17f3ce42026e036ab9d
> Unit Test Presenter Console

- browser/src/slideshow/RenderContext.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
Change-Id: I47e5be505f7304e80e06f1492e13638905811085
* Resolves: # 
Note: It's hard to see the difference between the old version and the new change, but we can ensure that nothing is broken.
> Slideshow: add mipmaps texture rendering for few transition

- .github/workflows/contributor_fetch.yml
- scripts/contributors-credit.js
- Added correct token to push file in IO website
- remove sidebar from contributor's page
> Update Contributors page

- coolwsd.xml.in
- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
- kit/ChildSession.cpp
- wsd/COOLWSD.cpp
Disable overwrite mode by default
> Disable overwrite mode in experimantal mode automatically.

- browser/src/control/Control.Toolbar.js
Change-Id: I9377b7bdbf7673100fababcca52d8048579a931f
> fix More... buttons of Calc conditional format dropdowns

- browser/css/jsdialogs.css
Change-Id: I2153cd6fc1035ed8250cb83223f7ac27cd15f3e5
> vex-fadein animation has been unavailable since vex was removed

- browser/src/control/Control.DownloadProgress.js
- wsd/ClientRequestDispatcher.cpp
Change-Id: I8d55639da342573bb37e2985d7c561dd78da2f19
* Resolves: # 
> js: show cluster config error copy request ends up on wrong server

- wsd/ProofKey.cpp
Change-Id: I2fe76ddd3aa0ca01ccbf357b285fbe3085440cb6
> remove unused header <Poco/BinaryWriter.h>

- browser/src/slideshow/PresenterConsole.js
vw: width of the viewport
vh: height of the viewport
Change-Id: I78db8b569e6b049ca3c6edbfc391b053409a05c1
> Presenter Console: Fix CSS units for width and height

- browser/src/control/jsdialog/Widget.Combobox.js
- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/calc/searchbar_spec.js
- cypress_test/integration_tests/mobile/calc/searchbar_spec.js
- it also fixes the random cypress failure when cypress tries to write in addressinputfield
Change-Id: Id2ca8efb0066506c3bac38d71c04f9e4f5690fcc
> calc: fix: don't update the combobox input if user is editing

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/mobile/calc/formulabar_spec.js
Change-Id: Id753ba6c9983844a6ab23b01fd84fb3f46f869b7
> cypress: attempt to fix clickOnFirstCell failing randomly

- browser/src/control/Control.DownloadProgress.js
- browser/src/docstatefunctions.js
- browser/src/map/Clipboard.js
follow up of e9a0eeb78dcc
Change-Id: I7c3cf0cbb0b0b945b6144d9b2b6a2d8cf02a0a2c
> fix: show error to user when online fails to download clipboard on pasting

- net/NetUtil.cpp
Seen in https://github.com/CollaboraOnline/online/issues/10332
where list has:
if (getifaddrs(&ifaces) < 0)
throw NetException("cannot get network adapter list");
which seems the likely source of the exception.
Change-Id: I889ae3107253acd69d2abc362523dba2eebfceb9
* Resolves: # 
> NetworkInterface::list can throw

- browser/src/canvas/sections/CommentSection.ts
- browser/src/control/Control.Mention.ts
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/mobile/writer/annotation_spec.js
- this makes the behaviour consistent with other applications
Change-Id: I680d8de9b48ebb502ec747e1ef3711fb1d69aa5d
> mention: insert extra space after inserting mention

- browser/src/control/Parts.js
- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/engine/SlideShowHandler.ts
Some browsers, such as Firefox, ignore height and width popup windows,
so it is better to specify more options.
Change-Id: I8076fdb4bf6e3ac95a3f18496bfea148d8948d11
> browser: slideshow: add more window feature options

- wsd/COOLWSD.cpp
at least the first spare kit created by forkit_main will exist without the fonts which arrive later
Change-Id: Idd778a40791266b0e2ff7ec6ba02dca6a19d0f23
* Resolves: # 
> When forkit installs fonts, sparekits that already exist don't get them

- common/Unit.hpp
- kit/ForKit.cpp
- test/UnitClient.cpp
- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/AdminModel.cpp
- wsd/AdminModel.hpp
- wsd/COOLWSD.cpp
- wsd/metrics.txt
Change-Id: I093c0640216a2346808c7cf84e2ea7b005ef01dc
* Resolves: # 
cc @timar
> ForKit: log and count killed child processes

- browser/src/canvas/sections/CommentSection.ts
- browser/src/control/Control.Mention.ts
- browser/src/layer/marker/TextInput.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
Change-Id: I1833bfdebf09342b25eb88c4e63a7b02288b4c19
> writer: fix: don't show mentionpopup when typing email address

- common/ConfigUtil.cpp
- common/ConfigUtil.hpp
- net/HttpRequest.hpp
- wsd/COOLWSD.cpp
- wsd: better hex data formatting in dumpState
- wsd: simplify config loading and capture the path
- wsd: dump the config
> Dump the Config

- wsd/Storage.hpp
Change-Id: Ie25532e1409a7eb1188b43122449711fce543bd2
* Resolves: # 
> drop redundant trailing semicolons

- browser/src/slideshow/PresenterConsole.js
Change-Id: Ic1ca45b85100cd8389c38ece968905533e0402cb
> browser: slideshow: fix pause/resume label button

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/Control.UIManager.js
- browser/src/docdispatcher.ts
- browser/src/unocommands.js
Change-Id: Iefa6acc480957aea174f722cc867ff10cf7f995b
* Resolves: # 
> Add Show/Hide all comments toggle button

- wsd/RemoteConfig.cpp
Change-Id: Id8fe9e2b28f8a6e38bd2f33f0db2953cb8d25f7f
> fix: fail to build wsd with `--enable-feature-lock`

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
In days gone by, every message was sent to the Android/iOS fake websocket as unencoded text. Unfortunately, some of the text was untrusted and this allowed XSS attacks to abuse sent messages like so...
message: 'command: {untrustedContent}' where {untrustedContent} is ' + maliciousJS() + ' would lead to the message executing maliciousJS()
...to prevent this, we encoded all messages in base64, and decoded them on the JavaScript side, leading to messages looking like this:
message: b64d('Y29tbWFuZDogJyArIG1hbGljaW91c0pTKCkgKyAn')
This appeared to work great - and in-fact did work great most of the time! Unfortunately, we failed to realize that sometimes we intercepted these messages in native Android code before sending them on to online...
...A specific case where we intercepted them was …
> fix(android): Fix progress bar with b64d messages

- wsd/COOLWSD.cpp
> wsd: config: correct the initialization order

- browser/html/framed.doc.html
We now have different samples and the heuristic are a bit different.
Change-Id: If79c810580aa686f71a7d81a48744a1f4557a258
* Resolves: regression caused by #9977
> debug frame: Fix the app selector

- browser/src/slideshow/PresenterConsole.js
Change-Id: I84864cb6466597b98de14229ef28a8160f07ed15
> browser: slideshow: fix "notes" toggle button

- browser/src/slideshow/PresenterConsole.js
Change-Id: Ia8410b9c1d63383cbeef9103f5d339a9b46f4d0a
> browser: slideshow: optimize drawing clock

- common/Clipboard.hpp
- common/CoolMount.cpp
- common/Crypto.hpp
- common/FileUtil.hpp
- common/Log.cpp
- common/SigUtil.cpp
- common/TraceEvent.hpp
- kit/ChildSession.cpp
- kit/Kit.cpp
- kit/KitQueue.cpp
- net/FakeSocket.cpp
- net/Socket.cpp
- wsd/COOLWSD.cpp
- wsd/Storage.cpp
> Various mostly stylistic cleanups

- browser/css/color-palette-dark.css
- browser/css/color-palette.css
- browser/src/canvas/sections/ShapeHandlesSection.ts
So they are configurable.
Change-Id: I29f9944bc2d51e184b585ada7b5ac452fc379f38
* Resolves: # 
> Read helper line styles from CSS vars.

- browser/src/slideshow/PresenterConsole.js
> Presenter Console UI Improvements: Font and gaps

- wsd/AdminModel.cpp
Change-Id: I4710aae86ae347326308719a08edbb647a07727b
* Resolves: # 
> Admin: add more paranoid thread affinity checks.

- browser/src/slideshow/PresenterConsole.js
Change-Id: I53aa412df3d2afeff1e986c8544ab4b8a20e244a
> browser: slideshow: fix undefined 'document' property

- browser/src/slideshow/PresenterConsole.js
Change-Id: I7e47ea1cdc344eeb8814e34614b4d095d7747713
> browser: slideshow: override pause if restart button is pressed

- browser/src/layer/tile/CanvasTileLayer.js
As tile updates that contain keyframes can still contain deltas and we handle that case correctly, there is no need to distinguish between the two in the tile object. This saves time, memory and makes the code a bit simpler, as it was before.
Change-Id: Id3957a74af8ca1cebb1995261cd9e09709db1a9b
A small fix-up after #10483.
> Remove tile.rawKeyframe

- .github/ISSUE_TEMPLATE/config.yml
- browser/descriptions/google-play.html
- browser/welcome/welcome.html
- configure.ac
- kubernetes/helm/collabora-online/Chart.yaml
Change-Id: Ia08fcd0678bd9d460ee81a9fac913777b17c2b6b
> The new website is at https://www.collaboraonline.com/

- browser/src/slideshow/PresenterConsole.js
Due to the close button was removed.
Change-Id: I1f99bf35ff8d331227dbdcc5807067d7f44f4bdd
> browser: slideshow: fix click slides

- browser/src/control/Control.Menubar.js
Change-Id: Ia56f70e8f53346a11db18a5b728fdeb3c378f75a
* Resolves: # 
> Presenter console: UI improvements: Add presenter console button for compact view

- browser/css/jsdialogs.css
- cypress_test/integration_tests/common/desktop_helper.js
They have now a flex box so we should allow them to grow but not to
shrink.
Change-Id: Ide87f81d403e1f77977c6098d6f1a6e85828468e
> Status bar: fix dropdown width

- wsd/COOLWSD.cpp
Change-Id: I882294d5c18b4c2abffa28d64d5cb76930bb31d3
> do not log admin console credentials at coolwsd startup

- browser/src/slideshow/PresenterConsole.js
- **browser: slideshow: fix request animation frame call**
- **browser: slideshow: optimize draw next frame**
> optimize draw next frame

- browser/src/slideshow/PresenterConsole.js
> Presenter console UI regression fixes

- wsd/COOLWSD.cpp
Change-Id: I9ce1b4d0e53d29b95bc2023604b1682cc197f604
> redact a few more sensitive config items in the log

- net/ServerSocket.hpp
- wsd/Storage.cpp
- wsd/wopi/StorageConnectionManager.cpp
- wsd/wopi/WopiStorage.cpp
* Resolves: # 
- [😃] All commits have Change-Id
- [😃] I have run tests with `make check`
- [😃] Documentation (manuals or wiki) has been updated or is not required
> We don't seem to need <Poco/Net/SocketAddress.h> here

- browser/src/control/Control.DownloadProgress.js
- browser/src/map/Clipboard.js
- common/MobileApp.hpp
- ios/Mobile/AppDelegate.mm
- ios/Mobile/DocumentViewController.mm
- ios/Mobile/TemplateCollectionViewController.mm
- ios/ios.h
This is a backport of #10506, #10498 and #10484
I've decided to combine them as later commits depend on earlier ones, even if they do make quite a large PR together...
> backport: feat: unify mobile clipboard with online

- browser/src/control/Parts.js
- wsd/TileCache.cpp
This is a trivial backport of #10290
> backport: Private/gokay/impress preview refresh

- browser/src/slideshow/PresenterConsole.js
Update to latest UI change adding the arrow back button
Change-Id: Ic6684f86c80c88ba834804ed3421ce5335632b2d
> browser: slideshow: fix click selection image

- browser/Makefile.am
- browser/admin/src/Util.js
- browser/src/slideshow/PresenterConsole.js
* Do not assemble localizable string from multiple parts
* SI prefixes are not for localization
* Enable localization of Presenter Console
> Localization fixes

- browser/src/slideshow/PresenterConsole.js
- Add consistent transparent border, padding, and rounded corners for non-selected images.
- Improve selected image border with dynamic color for better visual distinction.
Change-Id: I6dbaea13e06e8b2b8403cbeb08984852182d28ec
* Resolves: # 
> Enhance image preview border styling

- test/UnitQuarantine.cpp
A new crash test and improvements to an old one.
> wsd: test: quarantine tests

- android/lib/src/main/java/org/libreoffice/androidlib/LOActivity.java
This is a trivial backport of #10451 
---
In days gone by, every message was sent to the Android/iOS fake websocket as unencoded text. Unfortunately, some of the text was untrusted and this allowed XSS attacks to abuse sent messages like so...
message: 'command: {untrustedContent}' where {untrustedContent} is ' + maliciousJS() + ' would lead to the message executing maliciousJS()
...to prevent this, we encoded all messages in base64, and decoded them on the JavaScript side, leading to messages looking like this:
message: b64d('Y29tbWFuZDogJyArIG1hbGljaW91c0pTKCkgKyAn')
This appeared to work great - and in-fact did work great most of the time! Unfortunately, we failed to realize that sometimes we intercepted these messages in native Android code before sending them on to online...
...A …
> backport: fix(android): Fix progress bar with b64d messages

- test/UnitQuarantine.cpp
Change-Id: I2e73aa2989427910fdb433f4b068c313891b8667
> wsd: add missing header

- browser/src/map/handler/Map.Keyboard.js
Or it also prevents doocument save action.
Change-Id: I2561f274f656b5b31093227b145adf1517bc866c
* Resolves: # 
> Add an exception for default prevented boolean.

- browser/src/slideshow/PresenterConsole.js
The toolbar nagivation buttons handle them.
Change-Id: I330fb0e916195af0853b38bb09e8247970e88fcf
> click preview

- browser/src/slideshow/PresenterConsole.js
> Presenter console: add hover effect on presenter console btns

- test/UnitQuarantine.cpp
Change-Id: I5f6c18afef36a2fadd6d618a7864bf01d72cf8ad
> wsd: test: more stable UnitQuarantine

- browser/src/slideshow/PresenterConsole.js
- **browser: slideshow: avoid unhandled exception**
- **browser: slideshow: update preview aspect ratio on resize**
> update preview aspect ratio on resize

- browser/src/slideshow/PresenterConsole.js
> Disbale zoom after limit cross

- browser/src/slideshow/SlideShowPresenter.ts
the problemed occurred in fullscreen for the nextcloud integration
Change-Id: Iebaa76757c047dc3bd1f7badb4118e67c59e0ae7
> slideshow: on key down handler was not removed on exit

- browser/src/control/Control.Menubar.js
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarWriter.js
> Fix show all comment button problems

- browser/css/toolbar.css
- browser/src/control/Control.Toolbar.js
- browser/src/control/jsdialog/Util.Dropdown.js
- browser/src/control/jsdialog/Util.KeyboardGridNavigation.ts
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/control/jsdialog/Widget.DropDown.ts
> Add keyboard navigation for shapes and connectors

- wsd/wopi/CheckFileInfo.cpp
Change-Id: I0bbc5954f0abd8f70baa81cbace60de117127441
* Resolves: # 
> _wopiInfo checked twice

- browser/src/map/handler/Map.StateChanges.js
> Avoid undefined in CurrentTrackedChangeId

- scripts/build-samples.py
- test/samples/calc.fods
Hopefully this makes it easy to maintain in git, without bloating the repository with a large volume of data, while providing flexibility to change things in the future.
Change-Id: I474ead8aa90cea85cf38999c986631b557dcd06d
* Resolves: # 
> Generate calc sample file calc-edit.fods from a light template.

- browser/src/control/Control.ESignature.ts
- common/JsonUtil.hpp
- **cool#10630 doc electronic sign: improve error handling on bad client ID**
- **common: fix clang 18 -Werror,-Wvla-cxx-extension**
> cool#10630 doc electronic sign: improve error handling on bad client ID

- browser/src/control/Control.ContextMenu.js
- cypress_test/integration_tests/desktop/calc/clipboard_spec.js
Also add one more class name to context menu in order to be able to distinguish it amongst other pre-defined context menus.
Change-Id: I592e60c828cd516bcd56d558be97d4e1090ac0f6
* Resolves: # 
> Add a cypress test for paste-special command.

- browser/src/control/Control.ESignature.ts
- browser/src/slideshow/LayerDrawing.ts
- cypress_test/integration_tests/desktop/draw/esign_spec.js
- net/Socket.hpp
- **net: fix clang 18 -Werror,-Wvla-cxx-extension**
- **cool#10630 doc electronic sign: implement support for redirect-based providers**
> cool#10630 doc electronic sign: implement support for redirect-based providers

- wsd/COOLWSD.cpp
> "rebalance" return values cleanups

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/desktop/calc/cell_cursor_spec.js
- cypress_test/integration_tests/desktop/calc/searchbar_spec.js
- cypress_test/integration_tests/multiuser/calc/cell_cursor_spec.js
- remove timeout which showed us problem with click on first cell
- be sure we are in first cell before double click
> cypress: make clickOnFirstCell stable

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
- cypress_test/integration_tests/desktop/impress/presenter_console_spec.js
> presenter console: skip hidden slide in next slide preview

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
- cypress_test/integration_tests/desktop/impress/presenter_console_spec.js
> presenter console: close windows on document reload

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
> On presenter console window reload close the slideshow

- browser/src/control/Control.ESignature.ts
- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/draw/esign_spec.js
- kit/Kit.cpp
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/FileServer.cpp
- **cool#10630 doc electronic sign: get the signature on the server**
- **cool#10630 doc electronic sign: stop sending the secret to the client**
- **cool#10630 doc electronic sign: remove CSP rules**
> cool#10630 doc electronic sign: get the signature on the server

- browser/Makefile.am
- browser/src/control/Control.ESignature.ts
- browser/src/slideshow/LayerDrawing.ts
- **automake silent rules: handle tsc**
- **cool#10630 doc electronic sign: configure the language of the popup**
> cool#10630 doc electronic sign: configure the language of the popup

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
Change-Id: Ic92295225286874f4362d2b4e187bba61fa1d725
- To test:
1. Open new comment dialog in mobileview
2. Start typing mention at the start of paragraph
3. Entries doesn't show before the patch
> writer: mobile: fix mention doesn't work on start of paragraph

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
Back-port of following PR
- https://github.com/CollaboraOnline/online/pull/10675
- https://github.com/CollaboraOnline/online/pull/10669
* Resolves: # 
> Presenter console backport: 10675 & 10669

- THIRDPARTYLICENSES
Change-Id: Idfc8ea298a9c1ef052c798d2073ad2f5834ca779
> Add missing gl-matrix and l10n.js to license notes

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
- cypress_test/integration_tests/desktop/impress/presenter_console_spec.js
Change-Id: Ie36785314c17d145008b2fd4952efc649af08a80
> browser: slideshow: preview repeat duration to presenter console

- common/StringVector.hpp
- common/Util-mobile.cpp
- common/Util-server.cpp
- common/Util.hpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd: utility to get total PSS
- wsd: log the document and total PSS
> Log PSS of Process Tree

- browser/src/slideshow/PresenterConsole.js
- browser/src/slideshow/SlideShowPresenter.ts
> Handle close window cases for presenter console

- browser/src/control/Control.ESignature.ts
- browser/src/control/Control.ESignatureDialog.ts
- **cool#10630 doc electronic sign: default to a redirect-based provider**
- **cool#10630 doc electronic sign: set defaults without an index**
- **cool#10630 doc electronic sign: return dialog result without an index**
- **cool#10630 doc electronic sign: limit the offered providers based on the selected country**
> cool#10630 doc electronic sign: limit the offered providers based on the selected country

- browser/html/cool.html.m4
- browser/js/global.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/docdispatcher.ts
- coolwsd.xml.in
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
> slideshow: add option to enable legacy presentation

- browser/src/slideshow/LayerDrawing.ts
- kit/ChildSession.cpp
- kit/ChildSession.hpp
Requires https://gerrit.libreoffice.org/c/core/+/178580
Change-Id: Ib78b58e3e7be5615e2f109ed7cdf94571049c636
> slideshow: add "devicePixelRatio" parameter to "getslide " protocol

- kit/Kit.cpp
They are used only in one place, so expand them there.
* Resolves: # 
> Bin two pointless #defines

- browser/src/control/Control.NotebookbarWriter.js
> style list: make experimental

- browser/Makefile.am
- browser/src/control/Control.ESignature.ts
- browser/src/control/Control.ESignatureDialog.ts
- **automake silent rules: handle prettier**
- **cool#10630 doc electronic sign: sort the country & provider lists**
> cool#10630 doc electronic sign: sort the country & provider lists

- wsd/COOLWSD.cpp
Change-Id: I22386110225bb9a0c0052196fb0fc4059245f872
* Resolves: # 
> don't forward signals to pid -1

- browser/src/slideshow/PresenterConsole.js
Change-Id: I5136aa7ff4f35633f95b95794bc17b61753a854c
* Resolves: # 
> Enable notes by default on presenter console start

- browser/src/control/Control.StatusBar.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Widget.HTMLContent.ts
- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
Change-Id: I2d3a2b4eb17a839a2ed51e60a0e6c2c66d89b7e6
* Resolves: # 
> Writer: add show comments info into status bar.

- net/NetUtil.cpp
- net/NetUtil.hpp
Change-Id: Ibe3a8417b7ea54cfaa00857a5ed37bbf6f25e1dd
* Resolves: # 
> Add missing enum `MissingSSLError` and fix typo

- browser/src/canvas/sections/CommentSection.ts
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
- cypress_test/integration_tests/multiuser/calc/annotation_spec.js
- cypress_test/integration_tests/multiuser/writer/annotation_spec.js
Change-Id: Ic0583bab51eed52f7ba8045cca96b1be4a40c316
> annotation: put cursor at the end to modify comment

- wsd/ClientRequestDispatcher.cpp
Change-Id: I884c493a8da9bba5b0d6840de925fd2b83aa0738
* Resolves: # 
Amends #9202
> wsd: wopiAccessCheck fix typo in CheckStatus

- browser/src/control/Control.Tooltip.js
- browser/src/slideshow/PresenterConsole.js
- **browser: tooltip: handle 'ESC' key to hide tooltip**
- **browser: tooltip: add option to handle different windows**
- **browser: tooltip: add 'container' option**
- **browser: create initial tooltip for presenter console**
> tooltip improvements

- wsd/ClientRequestDispatcher.cpp
Change-Id: I0f4d4dad9c601ad40a67a16c85d6e5e8cfb4cebd
* Resolves: # 
Advertise #9202 
cc @timar @juliusknorr
> wsd: capabilities, advertise wopiAccessCheck endpoint

- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.Mention.ts
> improvment on autopopup calculation

- wsd/FileServer.cpp
Change-Id: Ib58f14b42e89ad06c28b9a9c0f7e91c149c43d7a
* Resolves: # 
> wsd: Upload a file to Nextcloud using an iframe

- browser/Makefile.am
- browser/src/app/GraphicSelectionMiddleware.ts
- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/draw/sign_spec.js
- **automake silent rules: handle m4**
- **cool#10630 doc sign: allow setting the position / size of a visual signature**
> cool#10630 doc sign: allow setting the position / size of a visual signature

- kit/Kit.cpp
Change-Id: Ia7a83a7b3de2744dece95234024d1ff2253982df
* Resolves: # 
> comment out very noisy tile log trace

- browser/src/control/Control.NotebookbarWriter.js
Change-Id: I79968099c117ef1f430cd32d00f3489128f203d4
> zotero: notebookbar: fixed borken bibliography button

- browser/src/canvas/sections/CommentSection.ts
instead of textContent so newlines entered into calc comments round trip
> use innerText to retain newlines in comments

- browser/src/canvas/sections/CommentSection.ts
- happens on firefox when you make the comment autosave and then finally save the comment
Change-Id: Ida59e546577a2c55197568225a1277340ef94367
> js: fix: comment doesn't presists newlines

- browser/src/docstatefunctions.js
Change-Id: I4d399d5d00ad40f38015d10f1f8faefd56dbcf30
* Resolves: # 
> Use twips and core pixels instead of latlng.

- browser/Makefile.am
- browser/src/control/Control.Menubar.js
- cypress_test/integration_tests/desktop/draw/esign_spec.js
- cypress_test/integration_tests/multiuser/calc/invalidations_spec.js
- **auto make silent rules: handle echo**
- **cool#10630 doc electronic sign: handle visual signatures**
> cool#10630 doc electronic sign: handle visual signatures

- browser/src/control/Control.ESignature.ts
- browser/src/control/Control.Menubar.js
- browser/src/control/Signing.js
- cypress_test/integration_tests/desktop/draw/esign_spec.js
- test/UnitSession.cpp
- **test: capture in lambda by value**
- **cool#10630 doc electronic sign: add a snackbar**
- **cool#10630 doc electronic sign: show the sign view dialog after esign**
> cool#10630 doc electronic sign: add a snackbar

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: I6a753412b5714c8d36c4742562b3176764bfb893
* Resolves: # 
> fix: after upload file refresh the ui

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Widget.DrawingArea.js
- **browser: jsbuilder: check if child has focusable element**
- **browser: jsdialog: fix keys event handlers**
> focusable element

- browser/src/control/Control.ESignature.ts
- browser/src/map/handler/Map.WOPI.js
- **cool#10630 doc electronic sign: remember the provider in localstorage**
- **cool#10630 doc electronic sign: show busy overlay while the popup is open**
- **cool#10630 doc electronic sign: close the popup on tab close**
- **cool#10630 doc electronic sign: avoid unwanted postmessage during sign**
> cool#10630 doc electronic sign: 4 fixes

- browser/Makefile.am
- browser/css/writer.css
- browser/src/canvas/sections/ContentControlDropdownSubSection.ts
- browser/src/canvas/sections/ContentControlSection.ts
- browser/src/core/geometry.ts
- browser/src/layer/marker/TextInput.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/map/handler/Map.TouchGesture.js
Change-Id: I1f4d5648241cd1df326295647ebc8947dc43134b
* Resolves: # 
> Simplify polygon drawing a little.

- .gitpod-files/coolwsd-gitpod.xml
- common/ConfigUtil.cpp
- coolwsd.xml.in
Change-Id: I81371935fcc559dc16b2f54f2de1196b220d930f
@eszkadev @hcvcastro maybe I missed something, but I did not understand why these two config items were commented out in coolwsd.xml. Please review.
> uncomment allow_update_popup and fetch_update_check in config file

- .gitignore
- Makefile.am
- common/Util.cpp
- cool-sbom-template.spdx.json
- kit/ForKit.cpp
- scripts/create-sbom.py
This PR creates and installs SBOM for the online part of COOL based on a template, that we can extend in the future. For now, it has all dependencies coolwsd/coolforkit/etc, C++ binaries, and the Javascript UI of COOL.
> SBOM (part #1)

- browser/src/app/GraphicSelectionMiddleware.ts
Open a 2 page PDF, scroll to page 2, Insert -> Signature, the graphic
selection doesn't appear for the signature line.
Seems the graphic selection always assumed a single part, but the text
selection doesn't have that problem since commit
a9c4aca4f8be5b3943cef777ac306aca99d78bbb (PDF View: Update search
feature to make it work with PDF view., 2021-07-27).
GraphicSelection.onMessage() seems to be the place where we parse the
graphic selection, so shift down the graphic selection there, as early
as possible, so nobody can have the info without the page offset.
The SVG inside the signature line & the drag of it is still broken.
Change-Id: Ia699c80ac94b9541fde2ea1ad1642e6150307cf7
> cool#10630 doc electronic sign: fix no graphic selection on 2nd page

- browser/src/control/jsdialog/Widget.DrawingArea.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
check map object if it is not assigned
Change-Id: I467d4a6ed901151bda4e867088affe09a83bebb1
> cypress focus unit test

- Makefile.am
- scripts/create-sbom.py
Change-Id: Ia28d07596b0fed84de4d99616a9d536c4c306a6e
> make: fix rule collabora-online-sbom.spdx.json, builddir != srcdir

- browser/js/global.js
- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
Change-Id: I0da568c8429db6c8315452c6b035c6badb28ebc0
> preset cosmetic followup

- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
Change-Id: I42d38f087f09f83a518d271110eea9ba1867eaea
* Resolves: # 
> follow up suggestions for kit_presets

- browser/admin/adminIntegratorSettings.html
- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- wsd/FileServer.cpp
Done
- Refactor entier iframe ui 
- accept css vars from integrator
- fix button upload problem with uploadWordbookButton
Todo: 
- append branding css
- try to replace svg to css svg if we have icons?
debug mode on ss: 
Change-Id: Ifbd34567ea716d334e2b277eba1abc255c523f69
> iframe: improve admin settings iframe ui

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/bug_report_smoke-test.md
- .github/ISSUE_TEMPLATE/easy-hack-template.md
- .github/ISSUE_TEMPLATE/easy-project-template.md
- .github/ISSUE_TEMPLATE/feature_request.md
Change-Id: I1d81bde6a59a2ee20f0646a17c0d1eaacdd876e0
* Resolves: # 
> Add label "24.04" for any new issue report on github

- wsd/DocumentBroker.cpp
Change-Id: If08d4caeab1917bdf604c39bef224b6471317d9b
> wsd: preset: failed to cache browsersetting json

- .gitignore
- cypress_test/integration_tests/desktop/calc/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
Change-Id: If756aa4b8fa369b13b32aad67b56faee86424ffe
> cypress: added test for tab navigation for comment button

- browser/src/control/Control.AddressInputField.ts
- browser/src/control/jsdialog/Widget.Combobox.js
Change-Id: I514412a860e54583237f8f6d542e1620c5d647ab
> calc: focus document on pressing 'Enter' in addressinputfield

- wsd/FileServer.cpp
- wsd/FileServer.hpp
> Make preset upload, fetch and delete async

- wsd/FileServer.cpp
Change-Id: Ib0ec66b257dd173fd3b6279b2fa8ae5d47afde56
* Resolves: # 
> wsd: cosmetic: remove unnecessary todos

- browser/src/map/handler/Map.Keyboard.js
Change-Id: I40cf7f0d0fcff4270a9172b6b50ffc4aa3da899e
> js: disable autotext dialog shortcut

- dev-notes/cursor-following.md
- dev-notes/keyboard-shortcuts.md
- dev-notes/locale.md
- keyboard shortcuts
- user following
> dev-notes update

- browser/css/notebookbar.css
- browser/src/control/Control.NotebookbarCalc.js
- **Calc: Notebookbar: remove numbertype's dropdown pixel width**
- **Calc: Notebookbar: Home tab: Add ui separators in between groups**
> private/pedro/notebookbar calc home tab UI fix

- browser/js/global.js
- wsd/FileServer.cpp
* Resolves: # 
replace needed template variables
And prevent bad values to be set to brandProductName and brandProductURL.
> FileServer: replace needed template variables

- browser/admin/src/AdminSocketSettings.js
- browser/src/core/Socket.js
Change-Id: I8923a2f3b81357f0ca4002fd208a210bf43b7a8f
> 7 chars long lokit git hash was too short sometimes

- browser/src/layer/tile/CalcTileLayer.js
Change-Id: I87ccbbc9f9f5e0fc0a31387ab6a68033551bbf2b
* Resolves: # 
> Prevent type error in case position info is empty.

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: I3c4677b6694b7b9a2e248170d3c4aaa30e6f5125
* Resolves: # 
> fix(admin): update enableDebug type in AdminIntegratorSettings

- browser/Makefile.am
- browser/src/slideshow/LayerDrawing.ts
- browser/src/slideshow/LayersCompositor.ts
- browser/src/slideshow/SlideCompositor.ts
- browser/src/slideshow/SlideRenderer.ts
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/VideoRenderer.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
Change-Id: Ifbac6a2a642ba2b5cf57224c09543f1f0f53666e
> slideshow: support video playing in presenter console

- common/ConfigUtil.cpp
- wsd/ClientRequestDispatcher.cpp
Change-Id: I8f4d3bb5c8629a469fbf377c2f1a9a55a3801198
* Resolves: # 
> config: support hasSettingIframeSupport capability

- browser/src/control/Control.JSDialogBuilder.js
Change-Id: Ie844465fdb0d08c4bb3d61873af91dcb6bcdb3f1
> browser: accessibility: add button attribute 'aria-pressed'

- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
Change-Id: I951501bad8952c1bd3c6856887adacc872033eaa
* Resolves: # 
> Check the previous page button actually move the cursor

- browser/src/map/Map.js
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/multiuser/calc/invalidations_spec.js
- cypress_test/integration_tests/multiuser/writer/invalidations_spec.js
I hope this helps to be sure we are ready to start testing.
Excluded from new check:
- multi
- draw
as are not working yet
> cypress: check if we are fully initialized before start

- kit/ChildSession.hpp
Change-Id: I33034965a8efbb584f41d9aaa057e987b71a8cd1
* Resolves: # 
> _isDocLoaded should be _isDumpingTiles here

- kubernetes/helm/collabora-online/templates/deployment.yaml
- kubernetes/helm/collabora-online/values.yaml
> feat(helm): Add extraVolumes and extraVolumeMounts options

- browser/admin/src/integrator/AdminIntegratorSettings.ts
- wsd/FileServer.cpp
Change-Id: I7dfccc85677545744646cd51f178ec48d2884b38
* Resolves: # 
> Rename shared config endpoints to settings config

- scripts/perf-record-stackcollapse
Change-Id: I67f8f02fb6f7c65f99ba2d560f12541a0da1e8d7
* Resolves: # 
> script to adapt incremental perf output for flamegraph input

- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: I341de2f1b14aec29eb0ba4c73415ea7b35929fbf
* Resolves: # 
> fix: reset file input after upload to allow re-upload of the same file

- common/Log.hpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/QuarantineUtil.cpp
- wsd/QuarantineUtil.hpp
- wsd/SenderQueue.hpp
Misc improvements with a key commit to contain exceptions while quarantining.
- **wsd: correct macro concatination used in logging**
- **wsd: better logs**
- **wsd: cosmetic dumpState**
- **wsd: remove more MOBILEAPP directives**
- **wsd: protect quarantineFile from exceptions**
- **wsd: simplify the 'unloading' flag helpers**
- **wsd: shorter poll when unloading**
> Safer Quarantine

- browser/src/control/Control.AboutDialog.ts
- browser/src/control/Control.DocumentNameInput.js
- browser/src/control/Control.Toolbar.js
- browser/src/control/Control.Tooltip.js
- browser/src/control/Control.UIManager.js
- browser/src/control/jsdialog/Widget.DrawingArea.js
Change-Id: Id0d681538644592305b262b7ef16606c93a62c8c
> browser: replace jquery-tooltip close button

- common/JailUtil.cpp
- kit/ForKit.cpp
- kit/Kit.cpp
- wsd/DocumentBroker.cpp
- wsd/RequestVettingStation.cpp
Change-Id: I501ebbfd75379f35ee33d4b3044d79f98b614058
* Resolves: # 
> each subforkit presets dir should be separate

- test/samples/writer.fodt
Remove empty headings.
Change-Id: I7cf30e22dbde0937a576b577650d625dffb6b1ec
> Update document sample

- wsd/Storage.cpp
We now validate the CheckFileInfo response
immediately after receiving it, and we mark
it as Fail if it doesn't pass.
This results in the prompt closing of the
client connection, with an equally immediate
"Document loading failed" message to the user
with "Unauthorized" in the message (though the
message refers to the host).
Change-Id: I1e706c7d12e66452476a90631b1521fc93d44e63
* Resolves: # 
> wsd: better CheckFileInfo validation

- browser/src/control/Control.ContextMenu.js
- browser/src/control/Control.MobileBottomBar.js
- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- cypress_test/integration_tests/desktop/calc/image_operation_spec.js
- cypress_test/integration_tests/desktop/impress/image_operation_spec.js
- cypress_test/integration_tests/mobile/calc/image_operation_spec.js
- cypress_test/integration_tests/mobile/impress/image_operation_spec.js
* requires: https://gerrit.libreoffice.org/c/core/+/181705
> feat: crop images in impress, calc and draw

- kit/ChildSession.cpp
- kit/LogUI.cpp
- scripts/undoStatistics.py
> Private/aszucs3/log UI savefixport

- browser/Makefile.am
- scripts/build-samples.py
- test/samples/writer-large.fodt
- tools/Replay.hpp
- **tools: fix clang-15 build**
- **tools: prefix members of PerfMetricInfo**
- **automake silent rules: handle cmp**
- **cool#11064 test: support creating a large Writer document with many pages**
> cool#11064 test: support creating a large Writer document with many pages

- wsd/protocol.txt
> Add missing protocol info

- Makefile.am
- wsd/DocumentBroker.cpp
- wsd/FileServer.cpp
- wsd/PresetsInstall.hpp
- wsd/RequestVettingStation.cpp
- wsd/RequestVettingStation.hpp
so the associated fds accumulate
Change-Id: Ic47a676447dc102bcae9698c0aaea68541b6963c
* Resolves: # 
> asyncRequest doesn't close the connection

- browser/src/control/Control.Zotero.js
Change-Id: I6c7d76d08e305cd67e714abe5cf36000b8fc05c0
> zotero: request items in async chunks using paging for speed

- browser/src/app/TilesMiddleware.ts
Issue: Checking against "undefined", raises assertion errors.
For testing: Scroll in a PDF document.
Change-Id: Id168ac7b2bb8e0d85f275fc627de395fcd0e2dfb
* Resolves: # 
> Default value for forZoom is "null" now.

- docker/from-packages/Dockerfile
Change-Id: If690af3ad746f6ecc6f4afcfed4cd6d627d589a7
* Resolves: # 
> use higher uid/gid for cool in docker images

- browser/src/app/TilesMiddleware.ts
- browser/src/layer/tile/CanvasTileLayer.js
- cypress_test/integration_tests/desktop/calc/top_toolbar_spec.js
Fixes 2 regressions from: https://github.com/CollaboraOnline/online/pull/11211
Change-Id: I5103da8223cdf9875ca6eeca2d34b8d7c1acff4a
* Resolves: # 
> Fix regressions from tilesMiddleware class.

- browser/src/control/Control.StatusBar.js
- browser/src/control/jsdialog/Widget.HTMLContent.ts
Change-Id: I4e7259ba81665c603bd6e00f9e959d869653fb59
> browser: replace the 'title' attribute with 'cool-tips'.

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- browser/src/layer/tile/CalcTileLayer.js
also display time in comments
Change-Id: I3c98a02bec018560daceb3b0350f1cc95d532396
> comment: use iso date strings everywhere

- cypress_test/integration_tests/common/helper.js
Change-Id: Id6abad9df18c206554f53163e4bb4d63a20849d3
* Resolves: # 
> Cypress: Attempt to make typeIntoInputField more stable.

- common/RenderTiles.hpp
Change-Id: Icd9b4ad5d7ac489e6324ba7bdf6d38e4209c86ca
* Resolves: # 
> tiles: improve diagnostics for large render areas.

- browser/js/global.js
Change-Id: I89b64a7c014ec52898906b88829d08edda18894f
> browsersetting: don't send update if old value and new value is same

- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Change-Id: I1297d71308bcd3650e3bc6c0faf770bd5ed0bb1e
> Misc Improvement

- scripts/undoStatistics.py
Removed save/load parameters from commands statistics, so they merged together.
Rounded filesize to something logarithmic like, to reduce filesizes groups in statistics
Fixed an index problem of load/save - time statistics, and made sure the last line will be displayed too.
Fixed an index problem od load/save - count statistics, so odg counts will be visible.
Change-Id: I975ed46c9cd0e4ddf9906084e841f847d37f5fa5
* Resolves: # 
> UILog fix/finetune statistics of load/save

- net/Socket.hpp
Change-Id: Ib06d0e400328a8ca3aa8b52044a2d7e86b0b6ac4
* Resolves: # 
> add some more info to log

- browser/src/control/Control.AboutDialog.ts
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/calc/bottom_bar_spec.js
- cypress_test/integration_tests/desktop/calc/clipboard_spec.js
- cypress_test/integration_tests/desktop/calc/statusbar_spec.js
- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/desktop/impress/jsdialog_spec.js
- cypress_test/integration_tests/desktop/impress/statusbar_spec.js
- cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
- cypress_test/integration_tests/desktop/writer/image_operation_spec.js
- cypress_test/integration_tests/desktop/writer/jsdialog_widgets_spec.js
- cypress_test/integration_tests/desktop/writer/statusbar_spec.js
- reduces races
- better checks to be sure we are ready for the next actions
> ci: stability fixes

- wsd/DocumentBroker.cpp
Change-Id: I2e9e1b36c34f349fe84f7e9240606e93b87fe7b1
> browsersetting: don't fail to load if browsersetting json is broken

- browser/src/control/Control.UIManager.js
- browser/src/control/Toolbar.js
in sidebar there is shortcut icon in Calc to activate style list - use correct command for it to remember selection adn allow to activate it not only first time when clicked
> styles list: allow second activation in Calc

- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
- cypress_test/integration_tests/mobile/impress/annotation_spec.js
- cypress_test/integration_tests/mobile/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/mobile/impress/insertion_wizard_spec.js
- cypress_test/integration_tests/mobile/writer/shape_properties_spec.js
- cypress_test/integration_tests/multiuser/impress/annotation_spec.js
- wsd/FileServer.cpp
- fetch-wordbook is not async
Change-Id: Iac7ca9062b0e8ca6d0ff9b5da050bfea3015fcc4
* Resolves: # 
> wsd: preset: close socket for fetch-wordbook

- browser/src/app/TilesMiddleware.ts
- cypress_test/integration_tests/common/calc_helper.js
this is most failing piece, it seems we don't wait for correct update on formulabar or address input
> cypress: make click on first cell more stable

- browser/src/app/TilesMiddleware.ts
additional check which was needed for 24.04 (https://github.com/CollaboraOnline/online/pull/11351)
> cypress: fix exception in TilesMiddleware.ts

- net/Socket.hpp
Change-Id: I40decda9f89c8c3be35627e2f04a1f301ee2aebf
* Resolves: # 
> warn when StreamSocket inBuffer reaches over 100M

- browser/src/app/TilesMiddleware.ts
Also, when a tile is comes, compare its scale with the document's scale before setting the view dirty.
Issue: On Calc:
* Change background color of a cell.
* Zoom out.
* See that the background color of the cell is not updated.
* Because tile was not invalidated due to different zoom level and wrong calculation of bounds.
Change-Id: I5d9317b8a94b08fdc468016a0c2e4c20c34d2303
* Resolves: # 
> Use tile's own scale when getting bounds of a tile.

- browser/src/map/Map.js
Change-Id: I3e9a5270b00d53825899972035461d7f851a0e5f
> browser: accessibility: fix zooming the browser at 400%

- browser/src/control/Control.MobileSearchBar.ts
- browser/src/control/jsdialog/Component.Toolbar.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Util.OnDemandRenderer.ts
- browser/src/control/jsdialog/Util.SnackbarController.ts
- browser/src/control/jsdialog/Widget.ButtonBox.ts
- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/control/jsdialog/Widget.Containers.ts
- browser/src/control/jsdialog/Widget.DropDown.ts
- browser/src/control/jsdialog/Widget.Edit.ts
- browser/src/control/jsdialog/Widget.HTMLContent.ts
- browser/src/control/jsdialog/Widget.IconView.ts
- browser/src/control/jsdialog/Widget.SearchEdit.ts
- browser/src/control/jsdialog/Widget.SidebarContainers.ts
- browser/src/control/jsdialog/Widget.TreeView.ts
to protect us more from regressions
> jsdialog: add type for builder

- browser/src/app/TilesMiddleware.ts
> Make sure to bounds-check the limit in CanvasCache.trim

- wsd/wopi/CheckFileInfo.cpp
Change-Id: Id4687f3914b26bdaba62e385276e854811a4d432 (cherry picked from commit 698a0c9232916605760132d0ead91e9e2884043d)
* Resolves: # 
> call onFinishCallback on early error cases too

- browser/src/control/Control.ESignatureDialog.ts
After commit e56548fbc4374987df905e25d51766fd7a51cd7f (jsdialog: add
type for builder, 2025-03-25).
Change-Id: Ia059ab3849b1dcf6fb88cb7a7a711d955939992d
> esign: add type for builder

- browser/src/app/TilesMiddleware.ts
- browser/src/docstatefunctions.js
Change-Id: I49bd6754c9b2b6041d61aec37ec045a7274a41a1
* Resolves: # 
> Remove unused variable and fix getScale function.

- wsd/DocumentBroker.cpp
Change-Id: I04d84be74403324f163cda678508e152897f8616
* Resolves: # 
> add Doc PSS beside Total PSS

- test/TileCacheTests.cpp
Revert "cool#11254 unit-tiletest: restore testTileRequestByInvalidation()"
This reverts commit c0a9e0febef6957d021a58014c45b7e512281365.
Revert "cool#11254 unit-tiletest: restore testTileInvalidateCalc()"
This reverts commit cd2ee4e71fa54d29f6eb485fa8989ff2edbb64e9.
Revert "cool#11254 unit-tiletest: restore testTileInvalidateWriterPage()"
This reverts commit 3192ae95c68c1250fdaefbe1c1237495ba8ae3cc.
Revert "cool#11254 unit-tiletest: restore testTileInvalidateWriter()"
This reverts commit 1e85beef867dd2f3295dd907b21afd6f8962feb2.
Revert "unit-tiletest: disable remaining broken tests in this suite"
This reverts commit 47ac440152152f138af36f8f6d72d486f6f1aaa6.
Revert "unit-tiletest, testUnresponsiveClient: don't assume invalidate is sent without having tiles first"
This reverts commit …
> cool#11289 revert invalidation optimization on co-24.04

- browser/src/control/Parts.js
- cypress_test/data/desktop/calc/calc-zoomed.fods
- cypress_test/integration_tests/desktop/calc/sheet_switch_spec.js
- Consider calc file with many sheets, BROWSER ZOOM 150% or higher
- We are NOT FOLLOWING anyone currently
- We INSERT new sheet
Result: we switch to other sheet but scrollbars are at random position, not seeing our own cursor
Expected:
A) we see our own cursor
B) if we are FOLLOWING anyone - stop following others and start following OUR OWN CURSOR C) if we are NOT FOLOWING anyone - start following our own cursor
> following: follow cursor on sheet insertion

- wsd/RequestVettingStation.cpp
- wsd/wopi/WopiStorage.cpp
Change-Id: Icae2f8cb2e51b0b2d3eb62bd525c60dbf61fad33
* Resolves: # 
> drop unneeded mutable on lambdas

- browser/src/app/TilesMiddleware.ts
Make some effort to de-duplicate some of the tile manipulation code we have. This also fixes unnecessarily rehydrating off-screen tiles.
> Consolidate some tile management code

- browser/src/control/Parts.js
- cypress_test/data/desktop/calc/calc-zoomed.fods
- cypress_test/integration_tests/desktop/calc/sheet_switch_spec.js
- Consider calc file with many sheets, BROWSER ZOOM 150% or higher
- We are NOT FOLLOWING anyone currently
- We insert new sheet
Result: we switch to other sheet but scrollbars are at random position, not seeing our own cursor
Expected:
A) we see our own cursor
B) if we are FOLLOWING anyone - stop following others and start following OUR OWN CURSOR C) if we are NOT FOLOWING anyone - start following our own cursor
> following: follow cursor on sheet insertion (backport 24.04)

- clang/plugin.cpp
- net/HttpRequest.hpp
- test/HttpRequestTests.cpp
- tools/Stress.cpp
- tools/WebSocketDump.cpp
- wsd/Admin.hpp
- wsd/COOLWSD.cpp
Change-Id: I6e4173bcdc18ac09aae65202144fd1e2c4b04a60
* Resolves: # 
> enforce SocketPoll is created via shared_ptr

- tools/Config.cpp
* Resolves: #11348 
* Change-Id: Ie7e5f35416bdc4ec789a696fc8c835acdc5df2b1
> added help message for migrateconfig

- wsd/ClientSession.cpp
Change-Id: I7fb0d9a8d84fa2bec29ed09955e0d642afa7138d
* Resolves: # 
> we only care if these match at the start

- test/UnitPerf.cpp
- test/UnitSession.cpp
- wsd/ClientSession.cpp
- **wsd: fix coplugin:capture**
- **test: fix coplugin:refcounting**
> clang coplugin fixes

- net/WebSocketHandler.hpp
- wsd/ClientRequestDispatcher.cpp
Change-Id: Iacb3a26d47a13570cc89d32510eea3ef76307afa
* Resolves: # 
> check ws header consistency

- wsd/Admin.cpp
- wsd/Admin.hpp
- wsd/ClientRequestDispatcher.cpp
Change-Id: I60fa91a1d4df2ae2b21a35ce377aa28233c9239c
* Resolves: # 
> check admin ws header consistency

- browser/admin/adminIntegratorSettings.html
- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/admin/src/integrator/WordBook.ts
- wsd/FileServer.cpp
Change-Id: Id0ef2d1f99f9112c235fd9e5d081d7d5876cdf59
* Resolves: # 
> enhancement(wordbook): Add language and type dropdown for wordbook

- wsd/ContentSecurityPolicy.hpp
Change-Id: Ifeb22cc14288ab780149d07d5aaa9f183f94c581
* Resolves: # 
> cid#518318 Use of auto that causes a copy

- .github/workflows/codeql-analysis.yml
- .gitpod.yml
Change-Id: I0099cf815dd11fbe62043918bea108e7d0d5632a
> use core-co-25.04-assets in master branch (and make wget/tar less verbose)

- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: If43cb45e09771a51829b73deac6035e3a01b714d
* Resolves: # 
> fix: add error handling popup to notify user when an error occurs

- browser/src/map/handler/Map.KeyboardShortcuts.ts
These are the combinations also used on the core side.
Change-Id: If6f9b41d09b2923ddd1a0d9eeb70df7ae9639f97
* Resolves: # 
> Add CTRL+SHIFT+F/K/U shortcuts for German layout.

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/desktop/calc/clipboard_spec.js
- cypress_test/integration_tests/desktop/impress/editable_area_spec.js
- reduce use of force
- reuse more code
- click on correct layer to activate editing the text inside shape
- hide sidebar to not cover handles...
> cypress: make editable_area_spec.js more stable

- net/Socket.cpp
- net/Socket.hpp
- wsd/DocumentBroker.cpp
Change-Id: Ied1bcb52a273c0da42f4bcca5ead97b6d314d40c
* Resolves: # 
> limit what can call Socket's setThreadOwner/resetThreadOwner

- dev-notes/socket-ownership.md
Change-Id: I6594acc4f64473122c837d64d9026fcd85f1407a
* Resolves: # 
> socket ownership notes

- common/ConfigUtil.cpp
- net/Socket.cpp
- net/Socket.hpp
- wsd: dump the total socket buffer size
- wsd: skip empty config entries
> Backports to 24.04

- browser/src/map/handler/Map.Welcome.js
Change-Id: I590793f39107f0a89bed45525486147d0153699b
> fix: cannot read properties of undefined (reading 'replaceAll')

- browser/src/map/handler/Map.Welcome.js
Change-Id: I590793f39107f0a89bed45525486147d0153699b
> fix: cannot read properties of undefined (reading 'replaceAll')(backport)

- net/HttpRequest.hpp
to be more verbose as to the issue the ordering addresses.
and move _result earlier
Change-Id: Ie02fa1416b674ca57422cfa3986e7d5cfc8e6576
* Resolves: # 
> expand "Must be the last member" comment

- browser/mocha_tests/CanvasSectionContainer.test.ts
- browser/src/app/TilesMiddleware.ts
- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/canvas/CanvasSectionObject.ts
- browser/src/canvas/sections/CalcGridSection.ts
- browser/src/canvas/sections/HTMLObjectSection.ts
- browser/src/canvas/sections/OtherViewCellCursorSection.ts
- browser/src/canvas/sections/OtherViewGraphicSelectionSection.ts
- browser/src/canvas/sections/PixelGridSection.ts
- browser/src/canvas/sections/ScrollSection.ts
- browser/src/canvas/sections/ShapeHandleCustomSubSection.ts
- browser/src/canvas/sections/ShapeHandleGluePointSubSection.ts
- browser/src/canvas/sections/ShapeHandleRotationSubSection.ts
- browser/src/canvas/sections/ShapeHandleScalingSubSection.ts
- browser/src/canvas/sections/SplitSection.ts
- browser/src/canvas/sections/TilesSection.ts
- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
Relies on work in #11555.
This adjusts the current area a bit less aggressively than master - importantly, it doesn't shrink the buffer area in the opposite direction of travel so that changing directions doesn't immediately cause flicker. To ensure that doesn't happen though, we go further and pause drawing when visible tiles are being dehydrated. This allows us to jump to areas of a spreadsheet we've previously visited with no visible flicker.
This *doesn't* solve flicker in the case of waiting for the server - we shouldn't block UI on something that may never return - on the other hand, I think we may want to consider expanding the buffer area to reduce the chance of this and in the case of large jumps initiated by the keyboard, we may want to wait in those situations. That can be the …
> Adjust current area and disallow drawing while visible tiles are dehydrated

- browser/admin/adminIntegratorSettings.html
- browser/admin/css/adminIntegratorSettings.css
- wsd/FileServer.cpp
- wsd/FileServer.hpp
Change-Id: I5d60b87a1f51be8da399ce567b59536337bf6c44
* Resolves: # 
> refactor(settings): use CSS variables for iframe

- net/HttpRequest.hpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
Change-Id: I98e3d0f8385e0db0127ad13e79035ab1837162f6
* Resolves: # 
> return std::weak_ptr in DocumentBroker::getPoll()

- wsd/COOLWSD.cpp
Change-Id: I4de0ba220c640059523d5fa14f42ff80f6afc25b
* Resolves: # 
> call malloc_trim occasionally

- cypress_test/integration_tests/common/calc_helper.js
- cypress_test/integration_tests/common/impress_helper.js
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/apply_paragraph_props_text_spec.js
- cypress_test/integration_tests/desktop/impress/image_operation_spec.js
Similar to commit f691cc628398713e81416b709e039a26432d644f cypress: stabilize calc click on first cell
fine-tune pixel coordinates which seems to be bit off and causing CI sometimes to fail
> cypress: improve stability of calc/autofilter_spec.js

- .github/ISSUE_TEMPLATE/feature_request.md
Change-Id: Iad6d86bfade0bae711832ad04d5accc18185e3a4
* Resolves: # 
> Add label "25.04" for any new issue report on github

- browser/src/layer/tile/CalcTileLayer.js
onStatus function gets the new size of the document. And we resize the canvas and map elements when required according to document size.
So we need to check the HTML sizes after getting the new size of the document.
I also added guards for new size. So the HTML modifications won't be fired when user is only scrolling the document.
Issue:
*Calc:  With large monitors, HTML sizes are not updated correctly.
Size is checked elsewhere and if status message comes after the size is checked, HTML sizes stay behind the document size.
> Calc: Call _syncTileContainerSize from "onStatus" function.

- common/Anonymizer.hpp
- common/ConfigUtil.cpp
- common/ConfigUtil.hpp
- common/Crypto-stub.cpp
- common/MobileApp.hpp
- common/ThreadPool.hpp
- common/Util-mobile.cpp
- fuzzer/ClientSession.cpp
- fuzzer/Common.cpp
- fuzzer/Common.hpp
- gtk/mobile.cpp
- ios/Mobile/CoolURLSchemeHandler.h
- kit/KitWebSocket.hpp
- kit/LogUI.cpp
- kit/LogUI.hpp
- kit/forkit-main.cpp
- net/NetUtil.hpp
- test/KitPidHelpers.cpp
- test/KitPidHelpers.hpp
- test/lokassert.hpp
- tools/ConfigMigrationAssistant.cpp
- wsd/ClientRequestDispatcher.hpp
- wsd/QuarantineUtil.hpp
- wsd/RequestVettingStation.hpp
- wsd/coolwsd-fork.cpp
- wsd/coolwsd-inproc.cpp
- wsd/wopi/CheckFileInfo.hpp
- wsd/wopi/StorageConnectionManager.cpp
- wsd/wopi/StorageConnectionManager.hpp
- wsd/wopi/WopiProxy.hpp
typically the vim ones which are at the end
Change-Id: Ic10bf16a2f6ac20789cf827729af0fc7446200fa
* Resolves: # 
> add missing mode lines

- wsd/RequestVettingStation.cpp
- **wsd: extend RequestVettingStation lifetime**
> Extend RequestVettingStation's Lifetime

- wsd/ClientRequestDispatcher.cpp
Change-Id: I52ead1ab8afc9f681835b34ee78e897259293e0c
* Resolves: # 
> use SocketDisposition::setTransfer instead of SocketDisposition::setMove

- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- **Integrator Settings: Use more semantic titles**
- **Integrator Settings: Add descriptive texts**
- **Integrator Settings: Fix font size**
- **Integrator Settings: Add font-family face**
> private/pedro/Integrator Settings UI fixes

- net/HttpRequest.hpp
Change-Id: I9649c0fdf7fbb67abdfde522eeb89b0797d4926d (cherry picked from commit 2ba36ce90f619887e492317e2be397a6309dc175)
* Resolves: # 
> Don't try and restart a finished SocketPoll

- browser/src/canvas/CanvasSectionContainer.ts
We should prolly get this into the next 24.04.14 release if people ar happy.
> Simple workaround to avoid multiple un-necessary re-draws.

- test/HttpRequestTests.cpp
Change-Id: If695197af3aadb61504b29a57ce744e6b6e6c8a7
* Resolves: # 
> Don't store Socket outside SocketPoll

- wsd/COOLWSD.cpp
Change-Id: Id6d9e7bbfce7c750e4c7fc19f51bd795d7571103
* Resolves: # 
> Don't store Socket in a non-SocketPoll Object

- browser/css/cool.css
- browser/src/canvas/CanvasSectionContainer.ts
- browser/src/canvas/CanvasSectionObject.ts
- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
Change-Id: Ic2834f506cb422458563385e7f5eb92f969994dc
* Resolves: # 
> CSC: Remove unused enum.

- browser/src/control/Control.IdleHandler.ts
Fixes regression from commit ffceec6a6ab9a7a9a7a137bce628fd421ef985ca jsdialogs: slurp also widget updates
fixes #11631 - error on idle
> Fix async idle popup #11631

- wsd/ClientRequestDispatcher.cpp
- wsd/ClientRequestDispatcher.hpp
Change-Id: I2150c067b3f26bcf938933fa4b0213bdc03d12e1 (cherry picked from commit c8a12f313b9d453521e44e9f2d3e022d4f645a08)
* Resolves: # 
> explictly capture what we need

- wsd/ClientRequestDispatcher.cpp
Change-Id: Ic6c5f06d029fdb3d8548e9985bb710d0f9708c16
* Resolves: # 
> hold Socket in lambda by weak_ptr

- browser/src/map/handler/Map.KeyboardShortcuts.ts
Change-Id: I334383b68c489c734e55948d9cee57741e3051a0
* Resolves: # 
> These are the combinations also used on the core side.

- wsd/wopi/WopiProxy.cpp
Change-Id: I63ca65edf4a54c57b81d9c8c82c30a005be1ce26
* Resolves: # 
> Drop this use of Disposition::setMove

- wsd/DocumentBroker.cpp
- wsd/Process.hpp
to put them directly to its SocketPoll. Keep weak_ptr references outside that SocketPoll owner.
Change-Id: I7270163d4efe97338559f87efad1b8218c45945e
* Resolves: # 
> defer creating urp sockets to when docbroker is available

- browser/src/control/Control.NavigatorPanel.ts
- browser/src/control/jsdialog/Widget.TreeView.ts
- browser/src/dom/NotebookbarAccessibilityDefinitions.js
> add accessibility info box for floating nav icon

- browser/src/control/Toolbar.js
- cypress_test/integration_tests/desktop/calc/jsdialog_spec.js
regression from JSDialog async rework: dialog for help was not working correctly (press F1)
> Fix help dialog

- browser/Makefile.am
- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/admin/src/integrator/Xcu.ts
Change-Id: Ia3d3398248e7733cee240140ab1197ce9611fa20
* Resolves: # 
> feat(integrator-setting): Xcu Parsing

- browser/src/control/Control.AutoFillPreviewTooltip.ts
- browser/src/control/Control.FormulaUsagePopup.ts
- browser/src/control/Control.JSDialog.js
- browser/src/control/jsdialog/Definitions.Types.ts
- do not focus close button of formula usage popup
- do not use titlebar for formula usage popup
- support case where focus is not allowed - do not focus then
> calc: fix regression in formula usage popup focus

- browser/src/canvas/sections/CommentListSection.ts
do modification in task after showModal
> Comment insertion dialog fix after async JSDialog

- browser/admin/src/integrator/WordBook.ts
Change-Id: I6667f2400629c2b05310c9904517b5004d6494c9
* Resolves: # 
> fix(integrator-setting): debounce new-word input validation

- browser/src/control/Control.PartsPreview.js
- browser/src/map/Clipboard.js
- kit/ChildSession.cpp
Change-Id: Ib692639c7cd7ff8307146dde28da748162352aac
> impress: implemented slide copy across documents

- browser/src/app/LayoutingService.ts
- cypress_test/integration_tests/desktop/impress/image_operation_spec.js
- make code more readable
- allow more tasks in a single run (35 ms + overflow limit)
- publish API for later use in canvas rendering handler
> layouting service: cleanup

- wsd/ClientRequestDispatcher.cpp
follow up for: https://github.com/CollaboraOnline/online/pull/11648
Change-Id: I53d1c301f9d7fdddda3f86bffbdafdf28af6a42a
* Resolves: # 
> log the URI on these failures

- wsd/wopi/WopiProxy.cpp
- wsd/wopi/WopiProxy.hpp
Change-Id: Iba86f5018f4f19445917bcab740564541da61f11
* Resolves: # 
> hold weak_ptr of StreamSocket in WopiProxy

- browser/src/canvas/sections/CommentListSection.ts
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
This reverts commit 2ae5df73b3276154b4ae9a9d1860028ecf85593f.
> Revert "cypress: skip failing annotation test for now"

- wsd/ClientSession.cpp
- wsd/ClientSession.hpp
Change-Id: I6d03b3464e5bc8302e231690c45b0ba0fd9d719f
* Resolves: # 
> hold weak_ptr of StreamSocket in ClientSession

- browser/src/control/jsdialog/Widget.Combobox.js
Change-Id: Ia9a193be25b6dedf1938b1ffea3ee9c2f4c9b5ae
> browser: accessibility: add role='listbox' to the custom combobox

- browser/src/control/jsdialog/Widget.IconView.ts
Change-Id: I4b67b5fb52464277c7c37a072c42c0b63a294e56
> browser: accessibility: fix the undefined alt attribute in the icon view

- browser/src/app/TilesMiddleware.ts
> Don't try to create an ImageBitmap when delta application fails

- net/HttpRequest.hpp
Change-Id: I7da14009540b5036921e2a019f21711fdd8e8b2b
* Resolves: # 
> use weak_ptr in ServerSession

- clang/plugin.cpp
- fuzzer/HttpEcho.cpp
It was working before, keep it working till it's not too much effort.
Change-Id: I20f8f1b8cebecb2fd918392b09ee9cf49d56a39f
> clang plugin: fix build with clang-15

- wsd/DocumentBroker.cpp
Change-Id: I86aceeb0eda689ba732b39f59a185b911c570dc1
* Resolves: # 
> Don't save clipboards of convert-to conversions

- browser/css/btns.css
- browser/css/device-desktop.css
- browser/css/jsdialogs.css
- browser/css/jssidebar.css
- browser/src/control/Control.JSDialogBuilder.js
Change-Id: I233a0e0759585bef5299b2831e0f540f367a7439
> browser: accessibility: add 'aria-expanded' attribute to expander label

- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: I0eafacb325aad9a41947139577801662e771ca60
* Resolves: # 
> Avoid calling "onScrollTo" function when the X and Y diffs are both 0.

- browser/admin/css/adminIntegratorSettings.css
Change-Id: I91d745d89c7d5ab4e0e2d6ebb279e8e30ef9c010
* Resolves: # 
> fix(integrator-setting): fix font color

- browser/src/control/jsdialog/Widget.ColorPicker.ts
- browser/src/docstate.js
- browser/src/global.d.ts
- browser/src/layer/tile/CanvasTileLayer.js
Change-Id: Ia1a34d479145a98a4f77a79f0a5dab541aba6f26
* Resolves: # 
> Show color names as tooltip on ColorPicker dialog

- net/Socket.cpp
so there clarity as to the lifecycle of captures
Change-Id: I74d9d5e269cc31ebdf57403911ed382894d9ba2e
* Resolves: # 
> explicitly clear these here to drop any captures

- net/Socket.cpp
- net/Socket.hpp
- wsd/COOLWSD.cpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.cpp
- wsd/Process.hpp
Change-Id: I5043c79960d995cf1e9ad727b2038a3f1f51bf98
* Resolves: # 
> rework SocketPoll::takeSocket to use transferSocketTo

- browser/css/jsdialogs.css
- Fixed alignment issue in the manage dialog for date/time picker.
- Increased ui-listbox-container height for better visibility.
Change-Id: I8c36526343593329da45b557e07e9d12636975a5
* Resolves: # 
> Manage Changes Filter date/time picker needs alignment

- browser/css/leaflet.css
- browser/src/dom/Draggable.js
Change-Id: I65b3a0c288d9217c8d04180baf170de171e7c442
* Resolves: # 
> Remove unused CSS classes.

- common/FileUtil.cpp
- common/Session.cpp
- common/Util.cpp
- common/Util.hpp
- kit/Kit.cpp
- kit/KitWebSocket.cpp
- wsd/ClientRequestDispatcher.cpp
- wsd/DocumentBroker.cpp
- wsd/QuarantineUtil.cpp
- wsd/RequestVettingStation.cpp
- wsd/wopi/WopiProxy.cpp
- wsd/wopi/WopiStorage.cpp
Change-Id: If4c6bdaec48ee574998521ebe9e0869272665954
> anonymize user information

- net/Socket.cpp
- net/Socket.hpp
Change-Id: Idfa9711feea2778d17b8c54d5846bc59e50edf7a
* Resolves: # 
> add some comments and explanatory variable names

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.MobileWizardBuilder.js
- browser/src/control/Control.MobileWizardWindow.js
- browser/src/control/Control.Sidebar.ts
- browser/src/control/Control.SidebarBase.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Widget.SidebarContainers.ts
- cypress_test/integration_tests/common/mobile_helper.js
- cypress_test/integration_tests/desktop/impress/image_operation_spec.js
- cypress_test/integration_tests/desktop/impress/jsdialog_spec.js
- cypress_test/integration_tests/mobile/calc/apply_font_spec.js
- cypress_test/integration_tests/mobile/calc/cell_appearance_spec.js
wo no longer use UI testing module in the core so we don't need to refresh whole sidebar, welding sends messages when needed
> mobile: do not send invalid jsdialog message

- wsd/DocumentBroker.cpp
- wsd/RequestVettingStation.cpp
> call DocumentBroker::createNewClientSession from docBroker SocketPoll thread

- kubernetes/helm/collabora-online/Chart.yaml
Change-Id: I3848f0820363f936373ba52a69d93b81457b97fb
> helm: update chart version to 1.1.38

- browser/css/jssidebar.css
Change-Id: Ie3d22cb9b7e4a12c7dfe1f1d1304a13ac5c58845
> chart color palette: current color palette button is too small

- common/Unit.cpp
Change-Id: I44533041047b891bc7966ca8eae70acd06b313a2
* Resolves: # 
> cid#398488 Indefinite wait

- common/ConfigUtil.hpp
- wsd/Admin.cpp
- wsd/COOLWSD.cpp
- wsd/CacheUtil.cpp
- wsd/DocumentBroker.cpp
- wsd/DocumentBroker.hpp
- wsd/SpecialBrokers.cpp
- wsd/wopi/StorageConnectionManager.cpp
- **wsd: support chrono types in ConfigUtil**
- **wsd: use chrono configuration getters in DocBroker**
- **wsd: use chrono config getters**
> More Chrono Usage

- common/Util.hpp
- kit/ChildSession.cpp
Also remove hungarian variable name leakage.
Change-Id: Ia041221d1d015750794a5328c5c57effff77e3a6
* Resolves: # 
> cool#11779 - slideshow - get slidelayer: message ordered correctly.

- browser/src/control/Parts.js
- browser/src/layer/tile/CanvasTileLayer.js
SearchService.ts alread draws the search results.
Unused function also causes JS errors.
Change-Id: I7d68a40378c37b2bab69a0a3e4f8ec9490514d97
* Resolves: # 
> Removed unused "_drawSearchResults" function.

- common/JailUtil.cpp
Change-Id: I14d43d10d33ea50158c3e73d0a2928e98f4564db
* Resolves: # 
> srcFilePath is unused

- browser/css/cool.css
- browser/html/cool.html.m4
Change-Id: I4fef639bc88c5a74fbbc9ddaa19954ae96b069b9
* Resolves: #11513 
> Consolidated Sidebar and Navigator Panel Styles

- browser/src/control/Control.Menubar.ts
Change-Id: Ic720a5185a2d739fa7647c1d6e1cabd1ee87fd80
* Resolves: # 
> Add formula edit related menu items to compact view of Writer

- test/Makefile.am
- test/UnitInvalidation.cpp
- test/data/invalidate.fods
- test/helpers.hpp
Unit test for invalidation issue - most of the structure there, needs better checking of the invalidation stream though ...
> cool#11826 - Unit test for calc multi-view invalidation issue.

- cypress_test/integration_tests/common/desktop_helper.js
> cypress: remove force from zoom items click

- browser/src/layer/tile/CalcTileLayer.js
- cypress_test/integration_tests/desktop/calc/autofilter_spec.js
Adding extra spacing leads to negative coordinates of view. Issue:
* Adding some extra space while jumping to cursor may cause negative document coordinates.
* If the cell cursor's left X pos is 0 (zero), then adding -SpacingValue causes negative X coordinate.
Change-Id: Ieb178dc831b364c3c94ffbcff0000265b3d81c3d
* Resolves: # 
> Calc onUpdateCellCursor: Fix spacing issue.

- browser/src/layer/tile/CalcTileLayer.js
Change-Id: Ibd039855db495ba04320a12889955d5c0ad8006f
* Resolves: # 
> Calc: Use getBoolean for getting focus-cell setting.

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/dom/NotebookbarAccessibility.js
- cypress_test/integration_tests/desktop/writer/notebookbar_spec.js
> Add missing activation label

- browser/css/jssidebar.css
related to
https://github.com/CollaboraOnline/online/issues/11868
and
https://github.com/CollaboraOnline/online/issues/11482
Change-Id: I653eec8cc07a9ec4669198bdaa7ef6510ad0daf9
> Sidebar: Hide non-functional hyphenate toggle

- net/Socket.cpp
- net/Socket.hpp
Based on Ash' suggestions:
https://github.com/CollaboraOnline/online/pull/11846
Change-Id: Ifee9597175db487135946afa3daeb80b086882ce
* Resolves: # 
> Further simplify onDisconnect and shutdown logic.

- kit/ForKit.cpp
- tools/KitClient.cpp
- tools/Replay.hpp
- wsd/ClientRequestDispatcher.cpp
- wsd/ClientSession.cpp
- wsd/FileServer.cpp
- wsd/RequestDetails.cpp
and
cid#522503 Variable copied when it could be moved
cid#522501 Variable copied when it could be moved
cid#522500 Variable copied when it could be moved
cid#522499 Variable copied when it could be moved
cid#522498 Variable copied when it could be moved
cid#522497 Variable copied when it could be moved
Change-Id: Ic3cedfcba9b671c63ca4d086733825e2f9f0b4c3
* Resolves: # 
> cid#522503 Variable copied when it could be moved

- CONTRIBUTING.md
Avoid completely rejecting a useful tool, but document what's forbidden.
Change-Id: I67f97672c6ff5818ca0d0bb3fc4824f0c7fb7d75
> CONTRIBUTING: add AI policy

- browser/src/control/Control.Toolbar.js
Change-Id: Ic353ef11915260ea7726710b482977d0bc434395
> Closebutton: Fix alignment

- cypress_test/integration_tests/common/desktop_helper.js
- cypress_test/integration_tests/common/repair_document_helper.js
- cypress_test/integration_tests/desktop/writer/scrolling_spec.js
do not ignore errors if we don't need, better to wait for correct state
> cypress: don't use force

- browser/src/control/Control.PartsPreview.js
- browser/src/map/handler/Map.Keyboard.js
Change-Id: Ia1d1841d43346a210235440698009155cc89151d
> slides: focus on preview when using keyboard navigation

- browser/src/docstatefunctions.js
when there was unsaved sheet and now it's missing
> Avoid exception on reload in calc

- .gitignore
Change-Id: I56ac5a50aefe70cdba9c3c06abd0352d8da27de6
> gitignore: added writer-large-edit.fodt

- browser/src/app/TilesMiddleware.ts
So if they are changed by the user, they are taken into account properly.
Change-Id: I97a735f3020f70cb0038f2a842229d63fbf0c43e
* Resolves: # 
> TileMiddleWare: use service root to import js

- browser/src/core/Socket.js
- browser/src/slideshow/LayerDrawing.ts
- kit/ChildSession.cpp
fixes: #11740
Change-Id: I7dcca4a564582270cb38f55f3c6f903a3002a825
> presentation: use zstd to compress bitmaps for presentations

- net/HttpRequest.hpp
Change-Id: I3d1ea593ee7517305c132daf94d8f379459757cd
* Resolves: # 
> ServerSession::asyncUpload is always of a file

- kit/ChildSession.cpp
- wsd/ClientSession.cpp
- wsd/protocol.txt
Change-Id: I6e985983b1caf955864ff0dfe8af1fd2f35b79b7
* Resolves: # 
> use an explicit 'mimetype' argument for getclipboard

- browser/src/layer/tile/CanvasTileWorkerSrc.js
This reverts commit be09007443095e5ad6535eb69b2fe5ad029a820d. It was causing artifacts to be shown on a screen when applying deltas. Very visible when using formatting marks which require lots of small changes.
> Revert "Handle Worker transactions progressively"

- kit/Kit.cpp
Change-Id: Icdc9eb2db4c06c7f874e9526f09c22d835ac804a
* Resolves: # 
> disable changing bg prio

- net/HttpRequest.hpp
- wsd/DocumentBroker.cpp
Change-Id: Iceabb009e1e4d60b2e28fbd3addfac01cbdee2cf
* Resolves: # 
> allow setting multiple headers in asyncUpload

- browser/src/control/Control.UIManager.ts
- Improves usability and accessibility by enabling horizontal scrolling via mouse wheel.
- Preserves default scroll behavior (e.g., Shift + scroll).
Change-Id: I2c81d06f2018d71307e34e67e30584387197bb5a
* Resolves: # 
> Enable horizontal scroll on main nav with mouse wheel

- browser/css/jsdialogs.css
Before this the OK button was not centered - vertically - aligned
Change-Id: I8741f163b6a889f289b0b47214e8ae252aa14794
> Snackbar: Center buttons

- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/calc/scrolling_spec.js
- cypress_test/integration_tests/desktop/impress/undo_redo_spec.js
- cypress_test/integration_tests/desktop/writer/file_properties_spec.js
- cypress_test/integration_tests/desktop/writer/top_toolbar_spec.js
- fix not executed conditionals based on document type
- wait for style previews in writer
> cypress: fix conditionals and wait for UI initialization

- browser/src/control/Control.JSDialogBuilder.js
from: https://github.com/CollaboraOnline/online/pull/11920
> backport checkbox state fixes: 24.04

- wsd/ClientRequestDispatcher.cpp
Change-Id: I29c3abadea1b8b5c347d0ac97764facbf65f45ff
* Resolves: # 
> improve convert-to capabilities logging

- cypress_test/Makefile.am
Change-Id: Ib64fb81db5646138f4e261be1b4cf0e2071d03e4
* Resolves: # 
> dump coolwsd console log on failure

- test/samples/calc.fods
in the past we faced some issues with handling hidden columns in Calc let's add that simplified case to the Password sheet in sample file
> update sample file: add hidden columns to protected sheet

- net/Socket.cpp
- net/Socket.hpp
- net/WebSocketHandler.hpp
- test/HttpTestServer.hpp
- wsd/ClientRequestDispatcher.cpp
related SocketHandler method is performWrites
Change-Id: Ib70af3e8a8bab33e0db1eb4766784bc1687a4470
* Resolves: # 
> rename flush to attemptWrites

- browser/src/control/Control.Toolbar.js
> [backport] Closebutton: Fix alignment

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Util.FocusCycle.js
- browser/src/dom/NotebookbarAccessibility.js
> Fix arrow navigation for notebookbar

- net/NetUtil.cpp
Change-Id: I5dbbf2bbc15e0baba6475d0f2f9be0b6f8f4b5a8
* Resolves: # 
> Don't use deprecated Poco::Net::NetworkInterface::NetworkInterfaceList

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Util.StateChange.ts
We try to do all JSDialog DOM operations in LayoutingService at once, do the same for state updates we create using the dedicated helper
> LayoutingService: put disabled state updates in queue

- browser/Makefile.am
Similar to commit ea0da20704222371e4bbda185246b8f22b4e5d15 (automake
silent rules: handle CSS stylelint, 2025-05-16).
Change-Id: I808e62d9b08b099ee7bc9d71c67cd9801da9f2f1
> automake silent rules: handle scripts/unocommands.py

- browser/css/jsdialogs.css
This reverts commit bdda2610f9853b8c331d7131ee5ab83bf440e469. It was causing issues in the Manage Changes dialog in Writer when we had lots of actions with tree structure and icons
> Revert "Manage changes dialog alignments"

- browser/src/core/Socket.js
- browser/src/slideshow/LayerDrawing.ts
- kit/ChildSession.cpp
this is temporary revert for release purpose
This reverts commits
d82d7ca8e96e6fb125d527cf8ac066a734216115
9009f0d1fc7e91172a5cfc91f4ed21ec510fc01f
Change-Id: I653ac50438264c74fb4a1c2e8f8976f5526f51b6
> presentation: revert zstd rework

- scripts/perf-record-stackcollapse
- scripts/profile-cool
- scripts/watchdog-cool
this seems good enough in practice
Change-Id: I77a9f43e972f0a954ad099ef4121706a11bff5b1
* Resolves: # 
> use dwarf,16384 in examples

- wsd/ClientRequestDispatcher.cpp
regression from a0b123add6730c0811d9ec1a93f7f89204937592
Change-Id: I8f2b74423fd5c33068b8bb36f6701663f6970564
> fix off-by-one error that prevented dowloading LibreOffice Technology logo

- wsd/COOLWSD.cpp
Which can happen if the remote font config changes and the primordial forkit exits to restart, and a request for a new subforkit is issued while the forkit hasn't restarted yet.
That request was silently dropped. Now instead queue the addforkit to be issued when the main forkit reappears.
Change-Id: I0ae2f2d39076114599976966d6af995bf11b47a9
* Resolves: # 
> queue addforkit messages if root forkit doesn't exist

- common/SigUtil-server.cpp
Change-Id: Ia8e5046b8fb3c63faaf5e1214c6a55d0acf49579
* Resolves: # 
> dump backtrace via gdb

- browser/src/map/handler/Map.Keyboard.js
Change-Id: Ic08233b4b4dbecdb3737db8fa0192214a639edbe
> slides: handle control key when slides are in focus

- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/Control.Sidebar.ts
- browser/src/control/Control.SidebarBase.ts
- cypress_test/integration_tests/common/helper.js
- cypress_test/integration_tests/desktop/writer/sidebar_spec.js
- **browser: accessibility: avoid making the sidebar container focusable**
- **browser: accessibility: focus the first focusable child element of the sidebar container**
> browser: accessibility: focus the first focusable child element of the sidebar container

- kubernetes/helm/collabora-online/templates/custom_fonts.yaml
- kubernetes/helm/collabora-online/templates/deployment.yaml
- kubernetes/helm/collabora-online/values.yaml
- Ability to add fonts to collabora online pods
- Change-Id: I57f6e2a5e2bd6f225ac79e8ca2ecff958f163dc4
* Resolves: # 
> helm: feat: add custom/user fonts

- common/Util.cpp
- common/Util.hpp
- net/HttpRequest.hpp
- test/UnitSession.cpp
- wsd/AdminModel.cpp
- wsd/RequestVettingStation.cpp
Change-Id: I8baa02db5c3c9722e83211a8eddd3a4420b0c816
* Resolves: #12087
In getMetrics:
Before:
kit_memory_used_total_bytes214540288
kit_memory_used_average_bytes214540288
kit_memory_used_min_bytes214540288
kit_memory_used_max_bytes214540288
After:
kit_memory_used_total_bytes 214540288
kit_memory_used_average_bytes 214540288
kit_memory_used_min_bytes 214540288
kit_memory_used_max_bytes 214540288
Seems like a regression from commit 1ab117cc9de36faff3e1bd4fe61a44d47361998b
Second commit
print function returns oss, but only prints once.
Consequently Print does not have any prefix outputed.
Before:
document_all_views_all_counttotal0
average0
min0
max0
document_active_views_all_counttotal0
average0
min0
max0
document_expired_views_all_counttotal0
average0
min0
max0 …
> AdminModel/getMetrics: add missing space between metric name and value

- .github/config.yml
Change-Id: Ie1296e330995d14afbaadd313dd29d9f796f018d
> Welcome Bot: Add Darshan

- kubernetes/helm/collabora-online/Chart.yaml
Change-Id: Ib5c54f501412d8c1b1f7ad7fd9e548a2a491e2b7
> helm: release chart 1.1.40 with alternate way to add custom fonts

- browser/src/control/jsdialog/Widget.IconView.ts
Change-Id: I217ab3183ee2757ca9505d686b041aa148b5d9b5
> iconview: added support for keyboard navigation after click

- Makefile.am
- common/Anonymizer.hpp
- common/Globals.hpp
- common/Log.cpp
- common/StaticLogHelper.hpp
- common/Util.hpp
- config.h.in
- kit/forkit-main.cpp
- net/Socket.hpp
- net/clientnb.cpp
- test/HttpRequestTests.cpp
- test/KitQueueTests.cpp
- test/fakesockettest.cpp
- tools/Benchmark.cpp
- tools/Config.cpp
- tools/Connect.cpp
- tools/KitClient.cpp
- tools/Stress.cpp
- tools/WebSocketDump.cpp
- wsd/COOLWSD.cpp
and
cid#525184 Initialization or destruction ordering is unspecified cid#525186 Initialization or destruction ordering is unspecified
Change-Id: I258a38ba10a9bbbad33d129620f114c59c81c775
* Resolves: # 
> cid#398521 Initialization or destruction ordering is unspecified

- common/Authorization.hpp
- common/Log.hpp
- common/Message.hpp
- common/MobileApp.hpp
- common/Seccomp.hpp
- common/Unit.hpp
- kit/ChildSession.hpp
- kit/Kit.cpp
- kit/Kit.hpp
- kit/KitQueue.hpp
- net/NetUtil.hpp
- test/helpers.hpp
- wsd/COOLWSD.hpp
- wsd/DocumentBroker.hpp
- wsd/FileServer.cpp
- wsd/ProofKey.hpp
- wsd/RequestDetails.hpp
- wsd/Storage.hpp
- wsd/TileCache.hpp
Change-Id: Ifb6679b9dca93dc77f42176ab55ffb4d2223b4f0
Should allow marginal memory usage improvement, allowing their values to fit in smaller registers...
> Minimize memory size of many enums

- browser/js/global.js
- browser/src/core/Socket.js
- browser/src/map/Map.js
And flush to wopi server after 5 seconds, or on loss of focus or on close of tab/window.
https://github.com/CollaboraOnline/online/issues/11656
Change-Id: I6b989f5f7fa2a5100b67a92342a00efd878768f2
* Resolves: # 
> batch browser setting updates together

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
> Add ui separators to File and Help tabs

- browser/css/btns.css
- browser/css/device-desktop.css
- browser/css/jsdialogs.css
- browser/src/control/Control.JSDialog.js
- browser/src/control/Control.JSDialogBuilder.js
- browser/src/control/jsdialog/Definitions.Types.ts
- browser/src/control/jsdialog/Util.Dropdown.js
- browser/src/control/jsdialog/Widget.Combobox.js
- browser/src/control/jsdialog/Widget.Containers.ts
- **browser: accessibility: fix the ARIA role attribute for the custom combobox component.**
- **browser: accessibility: fix the ARIA listbox role for the dropdown container.**
> fix the ARIA role attribute for the custom combobox component

- browser/.eslintrc
https://eslint.org/docs/latest/rules/no-await-in-loop#rule-details
> eslint: check await

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarDraw.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
Change-Id: Ia744f947811a45bd47d125af17211754e84df91d
* See: https://github.com/CollaboraOnline/online/pull/12222#pullrequestreview-2962184339
> Notebookbar: File tab: add ui separators in between grouped items

- kubernetes/helm/collabora-online/Chart.yaml
Change-Id: I4b9a1783af4329cbdcc3af60583e26cbe443210d
> helm: release 1.1.43 with ability pass configuration files

- browser/src/app/GraphicSelectionMiddleware.ts
- browser/src/canvas/sections/URLPopUpSection.ts
- browser/src/control/Control.StatusBar.js
- browser/src/control/Control.Toolbar.js
- browser/src/layer/tile/CanvasTileLayer.js
Use URLPopUpSection instead of app.definitions.uRLPopUpSection. Use sectionProperties instead of function variable.
Change-Id: I7c66a23e37e893595e754cd14caf61570cff59a8
* Resolves: # 
> URLPopUpSection remove unused variable.

- .gitpod-files/coolwsd-gitpod.xml
- coolwsd.xml.in
Change-Id: I43515f169a5a90fde11adba70be5b2b0c950bb77
* Resolves: # 
> coolwsd.in: correct Action_InsertGraphic mention

- browser/src/control/jsdialog/Widget.HTMLContent.ts
~~Requires #12348~~ - same as, but for Calc.
* Resolves: # 
> ui: Clicking on the sheet status show the goto sheet dialog

- browser/admin/src/integrator/AdminIntegratorSettings.ts
- wsd/FileServer.cpp
Change-Id: I3b868d4d03c25ef2a2bb649cd86e83f13a6e4f7b
* Resolves: # 
> SettingIframe: log config fetch response for better debugging

- browser/src/control/Control.JSDialogBuilder.js
as suggested here: https://github.com/CollaboraOnline/online/pull/12319#pullrequestreview-3008833461
> Clarify code

- browser/src/control/jsdialog/Widget.Progressbar.js
Change-Id: Id56e0a66943ea3966bd53d4b651a07ee40d1d264
* Addresses: #12108, but does not resolve 
Replaced var with const in this file https://github.com/CollaboraOnline/online/blob/master/browser/src/control/jsdialog/Widget.Progressbar.js
> fix:replace var with const/let

- browser/src/control/Control.Menubar.ts
Change-Id: I08af635184daa889a87abe4a95e4fb2b67a0336f
* Resolves: # 
> Insert "Manual Break" command to compact view of Writer

- browser/src/canvas/CanvasSectionContainer.ts
On some devices we are experiencing blurring in portrait mode. We've tracked this down to a commit that changed how the canvas was resized. We don't have time to fix this commit, and we'd prefer a slight performance degredation on resize (which happens rarely on mobile) to a blurry canvas in portrait mode in the mobile app. To do this, we can revert the commit that caused this: "Delay canvas resize until redraw"
This reverts commit c53dbb7d7325bd9b772747248141aca2dc19961a.
Change-Id: I6a6a6964f5153c02fc6100f9564f68aea838ea75
* Resolves: # 
> fix(iOS): stop blurring canvas in portrait mode

- browser/src/control/Control.PartsPreview.js
Change-Id: I4f82b10795636861350d434e8338bcbe0e9719d4
> slide preview: keep focus on preview after deleting slide

- browser/src/canvas/sections/CommentSection.ts
Change-Id: I3dd792b8bb580182e9d53b04075051baa90cc9ff
* Resolves: # 
> Add label "Press Ctrl + Enter to Post" to comment modify/insert

- configure.ac
- dev-notes/dependency-issues.md
Change-Id: If452ab5f885d92cab35fff66fffa194f84fec3e8
* Resolves: # 
> detect buggy poco version 1.13.0 and add workaround dev note

- browser/src/control/Control.JSDialog.js
- browser/src/control/jsdialog/Component.Toolbar.ts
- browser/src/control/jsdialog/Widget.OverflowGroup.ts
- browser/src/control/jsdialog/Widget.OverflowManager.ts
- cypress_test/integration_tests/common/search_helper.js
- cypress_test/integration_tests/desktop/writer/searchbar_spec.js
- cypress_test/integration_tests/desktop/writer/track_changes_spec.js
fixes issue when after using uno button inside popup, small empty popup left on the screen
> jsdialog: close overflow popup on fold

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/control/Control.NotebookbarWriter.js
- cypress_test/integration_tests/desktop/calc/cell_appearance_spec.js
> fix(ui): make few button in UI as split button

- browser/src/app/ViewLayoutMultiPage.ts
Change-Id: I5d8fc97041f8422b674aa6bb0ccd0f4d119fe951
* Resolves: # 
> cid#548378 Expression with no effect

- wsd/RemoteConfig.cpp
- patch adds ability to add indirection_endpoint setting to remoteconfig
Change-Id: I07e99d45227e35dd8220c792df2c494d28e943ed
> remoteconfig: fetch indirection_endpoint

- browser/admin/adminIntegratorSettings.html
- browser/admin/src/integrator/AdminIntegratorSettings.ts
Change-Id: Ic7a1399bf49326850b474a0b64c348490a091678
> settingIframe: pass service_root to fetch requests(backport)

- browser/src/control/jsdialog/Util.Dropdown.js
default in middle of switch statement was hurting my eyes LOL
Change-Id: I7233bcfcc569530c0bf0c6f7f4aebf863d017b30
> code refector

- browser/css/notebookbar.css
- browser/src/control/Control.Notebookbar.js
- browser/src/control/Control.NotebookbarImpress.js
Signed-off-by: Mohit Marathe <mohit.marathe@collabora.com>
Change-Id: I2b2db04f78c882036127b54020dc53e4b5fa33f7
> Notebookbar: add inline label to Share button on the top bar

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarWriter.js
Backpoort of : https://github.com/CollaboraOnline/online/pull/12665
Change-Id: I96670607a9f557f3524a963894b74ac688926c77
* Resolves: # 
> Add missing localization strings

- browser/css/jssidebar.css
- browser/src/control/Control.NavigatorPanel.ts
- browser/src/control/Control.QuickFindPanel.ts
* Resolves: # 
* Target version: distro/collabora/co-25.04
Backport #12714
> Navigation Sidebar: null checks (backport)

- coolwsd.xml.in
Change-Id: I1492b07d2c2476bf8def007606aa48f3d9d60e71
* Resolves: # 
> Improve security.seccomp description

- browser/src/control/Control.NotebookbarWriter.js
Change-Id: I41c4528b90e6c2baaf77245b36af8c83897907ce
* Resolves: # 
> Added missing translation prefix

- browser/src/control/Control.ColumnHeader.ts
- browser/src/control/Control.RowHeader.ts
Backport for https://github.com/CollaboraOnline/online/pull/12736
> Revert cell selection bug (backport 25.04)

- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/src/control/Control.UIManager.ts
- browser/src/core/Socket.js
- browser/src/layer/tile/CanvasTileLayer.js
- common/Session.hpp
- wsd/DocumentBroker.cpp
removed old zotero api key handling code
Change-Id: I9cf4d1ae1da2e99337d8ab055d43d9c8f5df0773
> introduce zotero setting in AdminIntegratorSettings

- browser/src/slideshow/SlideShowPresenter.ts
Signed-off-by: Samuel Mehrbrodt <samuel.mehrbrodt@collabora.com>
Change-Id: I0500b6d36a9ca417b7f09ffdc927afcd058d2a8d
> Next/Prev btns should trigger next effect, not next slide

- common/ThreadPool.hpp
- common/Util.cpp
- wasm/wasmapp.cpp
> Some (Emscripten) thread name improvements

- wsd/DocumentBroker.cpp
PresetsInstallTask::install() does a lot that can
go wrong, such is opening and copying files,
HTTP requests, etc. Exceptions thrown during
such operations are likely and that can
disrupt the loading of documents.
This likely fixes #12703.
> wsd: don't leak exceptions from PresetsInstallTask::install()

- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/PresetsInstall.hpp
Change-Id: If8a5cf516f55299e74c31cdbf0dc2aadef4c9b0f
> wsd: clang-tidy fixes

- browser/src/map/handler/Map.KeyboardShortcuts.ts
Change-Id: Ia45a72cdd5338705b112dafbb49588267d138786
* Resolves: # 
> Add semicolon shortcut for insert date shortcut.

- browser/html/cool-help.html
Add: Insert Date shortcut definition.
Change-Id: Ib5a68f2f5410a03b9ef10fd4865cda401ed809fa
* Resolves: # 
> Calc: Improve shortcuts help popup.

- browser/css/jsdialogs.css
1. Calc - Insert - Chart - Chart Wizard(Data series)
- **Preview:**
2. Listbox UI grid: This will affect all grid having listbox role
- **Preview:**   
3. Writer - Form - Properties(Dropdown)
- **Preview:**
> Jsdialog UI fix

- browser/src/canvas/sections/CommentSection.ts
Change-Id: Ia1c1d8238a65c1440ba0c6c1635c597324ee5472
* Resolves: # 
> Cancel the uninitialized comments on lost focus

- browser/Makefile.am
- browser/admin/css/adminIntegratorSettings.css
- browser/admin/src/integrator/AdminIntegratorSettings.ts
- browser/src/app/ServerConnectionService.ts
- browser/src/control/Control.UIManager.ts
- browser/src/core/Socket.js
- browser/src/docstate.js
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/main.js
- common/Session.hpp
- wsd/DocumentBroker.cpp
https://github.com/CollaboraOnline/online/pull/12694
and
https://github.com/CollaboraOnline/online/pull/12800
> backport: viewsetting (25.04)

- wsd/ClientSession.cpp
clipboards are expected to be passed around as files, this case missed that change.
Change-Id: I3b86fdcab9ffaac33c174e19c03b42fbbe3def9b
* Resolves: # 
> Copying between servers can miss clipboard

- browser/css/jsdialogs.css
> Backport 25.04 jsdialog UI fix

- browser/src/canvas/CanvasSectionContainer.ts
Previously if we were not able to redraw we also would not resize the canvas. Unfortunately this can cause issues where the canvas is in an uninitialized size when we do get to drawing on it, leaving our drawing blurry until the next resize.
Resizing the canvas if we can't actually draw fixes this.
Change-Id: I6a6a696419ae3fcf3605d3d93c7ba30e16087a3c
* Resolves: # 
> fix(canvas): always resize when it is needed

- browser/src/layer/tile/CalcTileLayer.js
- kit/KitHelper.hpp
Issue: Print ranges are not rendered on document load.
Change-Id: I9ff60d39ede93d6f5ab800ee3091a4114403e380
* Resolves: # 
> cool#12762: Calc: Add print ranges into status message.

- browser/images/dark/lc_followmepresentation.svg
- browser/images/lc_followmepresentation.svg
- browser/src/control/Control.NotebookbarImpress.js
- browser/src/docdispatcher.ts
- browser/src/layer/tile/CanvasTileLayer.js
- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowNavigator.ts
- wsd/ClientSession.cpp
how it works:
1. We first mark the starter of the presentation as the leader 
2. We then copy all the leader's moves and broadcast it to all views
Change-Id: Icbaf9773828cd13be1d5e4021e16b759faa88ffa
> introduce follow me slideshow

- browser/src/control/Control.JSDialog.js
pressing enter key will click the "Find Next" button
Change-Id: I3d5cd87127176f3282962c018b119f771b17f773
> Backport: Find and Replace dialog: handle Enter key

- configure.ac
Change-Id: If665c4f45fb53b52edf58b6fbd30ef5deb2a0fa7
* Resolves: # 
> don't break the build if brave is installed instead of chromium

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
Change-Id: If49c7ead83d5901a92f044c20a8c82c8ba399aab
> slideshow: rename 'ally' to 'a11y' for consistency

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
- cypress_test/integration_tests/desktop/impress/annotation_spec.js
- cypress_test/integration_tests/desktop/impress/slide_operations_spec.js
- cypress_test/integration_tests/desktop/writer/annotation_spec.js
> Backport 25

- browser/src/slideshow/SlideShowPresenter.ts
- browser/src/slideshow/engine/AnimatedElement.ts
- browser/src/slideshow/engine/SlideShowHandler.ts
- browser/src/slideshow/engine/animationnodes/AnimationBaseNode.ts
- browser/src/slideshow/engine/animationnodes/AnimationNodeInfo.ts
- **slideshow: move a11y string setting to presentSlide function**
- **slideshow: announce a11y string updates for slide transition start/end**
- **slideshow: announce a11y string updates for animation objects**
> a11y string updates

- browser/css/jssidebar.css
Change-Id: I729d1bd2189a36fd0e9a9a69eb52c182865e7c4e
* Resolves: # 
> fix formulas sidebar iconview css issue

- wsd/ClientRequestDispatcher.cpp
Change-Id: Ie39caafb9ff64691a6c9afa24519ac78cfa9d828
> add PDF/A-4, PDF-1.7 and PDF-2.0 to convert-to API

- kit/KitHelper.hpp
Commit c63c461c06cbb00353deef2cfcce76300b7f635e (cool:12762: Calc:
Add print ranges into status message., 2025-09-10) added a manual
std::free(), introduce a ScopedString type and use it in one place (as a
start) to avoid manual resource management.
Change-Id: I0801b01e5e2e2a2e9e141db9c616c0193eb88ecc
> KitHelper: avoid manual memory management in fetchCalcSpecificData()

- browser/src/control/Control.ServerAuditDialog.ts
- kit/Kit.cpp
- wsd/COOLWSD.cpp
- wsd/DocumentBroker.cpp
- wsd/Process.hpp
- wsd/ServerAuditUtil.cpp
- wsd/ServerAuditUtil.hpp
Useful to show an admin how well the system is configured, and how efficient it is.
Change-Id: Ic7de7854b878f5da5308794b903cb0fda801e099
* Resolves: # 
> Admin: get kit properties into the admin console.

- browser/src/control/Control.PartsPreview.js
- browser/src/map/Clipboard.js
backport of https://github.com/CollaboraOnline/online/pull/13008
* Target version: distro/collabora/co-25.04
> Slide copy improve backport

- browser/src/canvas/sections/ShapeHandleScalingSubSection.ts
- browser/src/canvas/sections/ShapeHandlesSection.ts
> make shape's bounding rectangle visible and improve shape handle colors

- browser/Makefile.am
Signed-off-by: Samuel Mehrbrodt <samuel.mehrbrodt@collabora.com>
Change-Id: Id5566a9bce62ec599f4e5c61d957d57c928b51c1
> Make truncate work on uutils truncate

- browser/src/canvas/sections/CommentListSection.ts
- browser/src/canvas/sections/CommentSection.ts
Signed-off-by: Samuel Mehrbrodt <samuel.mehrbrodt@collabora.com>
Change-Id: Ia624e4dc0d86c060842a528683080fcf26b62a7a
> Highlight search term within comments

- browser/admin/src/integrator/Xcu.ts
Change-Id: Iea9257584a355754ec647003d3c741f8ddc676bc
> AdminIntegratorSettings: make Save button translatable

- browser/html/wasm.html
- wasm/wasmapp.cpp
- wasm/wasmapp.hpp
- wsd/Storage.cpp
> some clean up

- browser/src/control/Control.NotebookbarCalc.js
- browser/src/control/Control.NotebookbarWriter.js
- browser/src/control/jsdialog/Util.ModelState.ts
- browser/src/docdispatcher.ts
- browser/src/global.d.ts
- better fallback
- do not use functions in notebookbar JSON, use dispatch action name instead
> notebookbar: fix error on copy object

- browser/src/map/handler/Map.Feedback.js
- **browser: add 'version_number' field**
- **browser: remove iframe close on feedback submission**
> add 'version_number' field

- browser/src/control/jsdialog/Widget.MenuButton.js
- browser/src/control/jsdialog/Widget.OverflowGroup.ts
- reduces spam of misleading errors
> notebookbar: logging fixes

- browser/src/app/iface/Clipboard.Interface.ts
- browser/src/app/iface/DocLayer.Interface.ts
- browser/src/app/iface/Map.Interface.ts
- browser/src/app/iface/SocketTypes.Interface.ts
- browser/src/app/iface/Welcome.Interface.ts
- browser/src/control/Control.UIManager.ts
- browser/src/global.d.ts
let's merge in a safe way part by part ts-conversion from @dennisfrancis
> browser: more typings needed for Socket TS migration

- browser/src/app/iface/DocLayer.Interface.ts
- browser/src/app/iface/Map.Interface.ts
- browser/src/control/Control.Sidebar.ts
- browser/src/control/Control.SidebarBase.ts
- browser/src/control/jsdialog/Component.Base.ts
- browser/src/control/jsdialog/Component.Toolbar.ts
- browser/src/control/jsdialog/Definitions.Types.ts
- more typescript cross-checking
> jsdialog: use map type replacing any

- browser/Makefile.am
- browser/src/app/SocketBase.ts
- browser/src/core/Socket.js
Change-Id: I259efd2d0133891fd86df5b84535cc44172a7dc3
* Resolves: # 
Typescript conversion of browser/src/core/Socket.js.
> browser: Incremental move from src/core/Socket.js to typescript

- scripts/build-samples.py
- test/samples/writer-large.fodt
Change-Id: I30215983d8ed74d125b0d0cfbbfe69a7d8915045
* Resolves: # 
> writer-large test - add some trickier pieces: shape, comment, header.
